### ISSUE TITLE
Remove deprecated healthz port 10248

### ISSUE THREAD

**Issue by ArtfulCoder** [GoogleCloudPlatform/kubernetes#10003]
monit monitors kubelet's health using port 10248.
that port only has the default health handler that always shows kubelet as healthy.

monit should use https port 10250 or port 10255

@dchen1107 @lavalamp

**Comment by roberthbailey** [comment]
Port 10250 would be better than 10255, because 10255 is the read-only port which only has the default healthz handler installed. The custom healthz handler is only running on the https port (10250).

**Comment by ArtfulCoder** [comment]
@roberthbailey we need monit to able to use the https endpoint. I couldn't find documentation yet to able to do that.  ( I looked at https://mmonit.com/monit/documentation/#HTTP)

**Comment by roberthbailey** [comment]
In that case, maybe making the healthz on 10248 (which is called the HealthzPort on the command line) seems like it might make the most sense.

**Comment by ArtfulCoder** [comment]
Will do

**Comment by ArtfulCoder** [comment]
@roberthbailey and I discussed offline. 
We will use 10255 for the health check. 
Reason: health checks are very kubelet-internals-specific. It is easier to add healthchecks on 10255, which has easy access to kubelet internals.

**Comment by roberthbailey** [comment]
Also, we should audit uses of 10248 and remove it if it was only used by monit (which I believe is the case).

**Comment by dchen1107** [comment]
10248 currently is only used for monit. Validation cluster doesn't validate nodes healthy anymore. It is safe to remove it now.

**Comment by dchen1107** [comment]
We settle down to use 10255 the read-only port, plan to remove 10248 port. I lower down the priority to p2.

**Comment by lavalamp** [comment]
We should use the same healthz handler for ALL the ports that we serve healthz on.
