### ISSUE TITLE
AWS persistent storage

### ISSUE THREAD

**Issue by ghost974** [GoogleCloudPlatform/kubernetes#10017]
Hello,

EBS is said to be supported here https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/persistent-volumes but in the example code, there is only gce, local-01/02 and nfs. Is there any sample for using AWS EBS ?

Thanks

**Comment by markturansky** [comment]
An EBS example just got merged https://github.com/GoogleCloudPlatform/kubernetes/pull/9665

PV should work fine swapping out the examples with an EBS volume.

**Comment by satnam6502** [comment]
@ghost974 can we close this issue?

**Comment by ghost974** [comment]
Yes thanks. Just adding a bit of information for whoever read this later, if you use CoreOS, you will need to add Instance Role permissions for the Kubernetes minions : 
"ec2:AttachVolume",
"ec2:DetachVolume",
"ec2:DescribeInstances",
"ec2:DescribeVolumes"

Also the script "safe_format_and_mount.sh" will be missing from coreOS, still working on that.

**Comment by markturansky** [comment]
thanks @ghost974.  would you mind updating the EBS example created in #9665 to include the CoreOS requirements for each node?

**Comment by swagiaal** [comment]
> Yes thanks. Just adding a bit of information for whoever read this later, if you use CoreOS, you will need to add Instance Role permissions for the Kubernetes minions :

@ghost974 Yeah if you can update the example that would be great!

> Also the script "safe_format_and_mount.sh" will be missing from coreOS, still working on that.

Yeah #8530 should fix that but it is scheduled for post 1.0. On CoreOS is think safe_format_and_mount is in a different path according to #7042. So you might have to create a symlink to get it working for the time being

**Comment by swagiaal** [comment]
@satnam6502 Yes, I think this can be closed.
