### ISSUE TITLE
Kube2Sky doesn't create SRV records for services

### ISSUE THREAD

**Issue by nebelpfade** [GoogleCloudPlatform/kubernetes#10018]
Hello,

I try to use DNS (SkyDNS) as discovery service and found that Kube2Sky creates only A records for services, no any SRV. What can be a problem here? I'm using gcr.io/google_containers/kube2sky:1.9

**Comment by ArtfulCoder** [comment]
1. The service port should have a name.
2. The SRV record is of the format _my-port-name._my-port-protocol.my-svc.my-namespace.svc.cluster.local

Check out https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/README.md

If you are already doing this, then can you give more details about your service spec ?

**Comment by thockin** [comment]
SRV records are only created on new-style names:  *.svc.cluster.local - this tripped me up, too.  Please confirm.

**Comment by thockin** [comment]
closing for now, please reopen if needed
