### ISSUE TITLE
Include examples in e2e tests

### ISSUE THREAD

**Issue by mwielgus** [GoogleCloudPlatform/kubernetes#10013]
It would be good if e2e tried to bring up cassandra, redis, etc using the configs from `examples/` and check if they start properly (for instance by greping kubectl logs).

@marekbiskup

**Comment by satnam6502** [comment]
The e2e cluster does bring up Elasticsearch and Kibana and one of the e2e tests does a pretty decent check of Elasticsearch to make sure it works. Do you think the e2e tests should also check that the configs under examples are healthy? Perhaps -- but I think this should be a separate e2e tests under the examples directory and it should not be conflated with the test/e2e tests which are aimed at core functionality.

**Comment by mwielgus** [comment]
@satnam6502, do you want to just put the code in a different directory or to completely separate these e2e tests from the core tests (different scripts in `hack/`, etc)?

**Comment by satnam6502** [comment]
Well, first, let's not write any more scripts please.
I think it is a bit of a project to do a good systematic job of developing e2e tests (or framework) for the examples -- I think there is also already an issue for this? I think we should start to think about this after the 1.0 release? Otherwise it is not going to get the attention it needs for code review etc? Do you think this can wait a bit?

**Comment by fgrzadkowski** [comment]
I agree that implementing a generic framework for running examples as e2e tests is a lot of work and we should probably not focus on this right now. However, I believe that making sure that our examples actually work is really important. We had examples where this was not the case.
Manual testing and then implementing e2e tests that verify this, was something that @brendanburns suggested we should also focus on in the upcoming weeks.

**Comment by satnam6502** [comment]
Being able to run `--validate` in some kind of dry-run mode could be low overhead and useful?

**Comment by mwielgus** [comment]
There is already a [test]( https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/examples_test.go) that checks if the configs are parseable an have reasonable content.

**Comment by roberthbailey** [comment]
A while back, @jayunit100 was also interested in doing this.

**Comment by jayunit100** [comment]
yeah i have a pr pending for k8petstore soak #8145

**Comment by ixdy** [comment]
@mwielgus should we start a Jenkins project to start running these tests?

**Comment by jayunit100** [comment]
still a big fan of this.  I Have #8145  which is a soak test that id like to run in E2Es, however 
- its mor involved, more code to it
- it takes longer
but i can refactor that PR to have a similar "Describe" string so its easy to catch it in the same filter .

**Comment by mwielgus** [comment]
@ixdy That would be great. But until the remaining PRs are merged the suite will check only 2 examples.

**Comment by ixdy** [comment]
Created #11600 to start up a Jenkins project for the Examples e2e tests.

**Comment by ixdy** [comment]
The examples tests are now running in https://goto.google.com/k8s-test/job/kubernetes-e2e-gce-examples/.

**Comment by mwielgus** [comment]
Great, thanks @ixdy :+1:

**Comment by ihmccreery** [comment]
Closing based on @ixdy's comment above.
