### ISSUE TITLE
Short-name DNS resolution broken

### ISSUE THREAD

**Issue by erimatnor** [GoogleCloudPlatform/kubernetes#10014]
Short-name DNS resolution is broken for me on AWS with v0.18.2 and v0.19.1. Full-name resolution works fine. I haven't tested other configurations, but I suspect the same holds true there.  

This problem means cluster services like Kibana are broken out-of-the-box. Here's the Kibana log output right after doing a `kube-up.sh`:

```
ELASTICSEARCH_URL=http://elasticsearch-logging:9200
{"@timestamp":"2015-06-18T10:28:56.936Z","level":"error","node_env":"production","error":"Request error, retrying -- read ECONNRESET"}
{"@timestamp":"2015-06-18T10:28:56.943Z","level":"warn","message":"Unable to revive connection: http://elasticsearch-logging:9200/","node_env":"production"}
{"@timestamp":"2015-06-18T10:28:56.943Z","level":"warn","message":"No living connections","node_env":"production"}
{"@timestamp":"2015-06-18T10:28:56.946Z","level":"info","message":"Unable to connect to elasticsearch at http://elasticsearch-logging:9200. Retrying in 2.5 seconds.","node_env":"production"}
```

I then logged into the Kibana container and did DNS queries for both short-name and long-name elasticsearch:

```
root@kibana-logging-v1-vhzi8:/# dig elasticsearch-logging

; <<>> DiG 9.9.5-9-Debian <<>> elasticsearch-logging
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 32503
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;elasticsearch-logging.		IN	A

;; Query time: 2 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Jun 18 10:03:00 UTC 2015
;; MSG SIZE  rcvd: 39

root@kibana-logging-v1-vhzi8:/# dig elasticsearch-logging.default.cluster.local

; <<>> DiG 9.9.5-9-Debian <<>> elasticsearch-logging.default.cluster.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25001
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;elasticsearch-logging.default.cluster.local. IN	A

;; ANSWER SECTION:
elasticsearch-logging.default.cluster.local. 30	IN A 10.0.108.241

;; Query time: 3 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Jun 18 10:03:08 UTC 2015
;; MSG SIZE  rcvd: 77
```
Here's the log output of Skydns for the above queries:
```
2015/06/18 09:56:49 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [1]
2015/06/18 09:56:49 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/06/18 09:56:49 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
2015/06/18 09:56:58 skydns: can not forward, name too short (less than 2 labels): `elasticsearch-logging.'
2015/06/18 09:56:58 skydns: can not forward, name too short (less than 2 labels): `elasticsearch-logging.'
2015/06/18 09:57:00 skydns: can not forward, name too short (less than 2 labels): `kubernetes.'
2015/06/18 09:57:00 skydns: can not forward, name too short (less than 2 labels): `kubernetes.'
2015/06/18 09:57:01 skydns: can not forward, name too short (less than 2 labels): `kubernetes.'
2015/06/18 09:57:01 skydns: can not forward, name too short (less than 2 labels): `kubernetes.'
2015/06/18 10:03:00 skydns: can not forward, name too short (less than 2 labels): `elasticsearch-logging.
```

**Comment by ArtfulCoder** [comment]
Can you paste the /etc/resolv.conf file from kibana-logging-v1-vhzi8 container ?

**Comment by erimatnor** [comment]
@ArtfulCoder here's the /etc/resolv.conf:

```
root@kibana-logging-v1-sufky:/# cat /etc/resolv.conf 
nameserver 10.0.0.10
nameserver 172.20.0.2
search default.cluster.local cluster.local eu-west-1.compute.internal
```

**Comment by thockin** [comment]
Two things:

1) Newer (0.19 I think) kubelets should give you a search more like this:
`search default.svc.cluster.local svc.cluster.local cluster.local`
Note the "svc"

2) Your resolv.conf looks fine.  Sadly, DNS resolution is implemented by
libraries outside of kubernetes' control and some of them are broken.
There's a wonderful tiny-linux container base called 'alpine' that I would
use for EVERYTHING except the libc that it uses does not support 'search'
for DNS.  Could your app be falling into the same trap?

**Comment by erimatnor** [comment]
@thockin note that I wasn't running my own app. This was the kibana-logging pod on a clean cluster running on AWS immediately after doing a kube-up.sh. I see no reason why this shouldn't be reproducible by anyone bringing up the a similar cluster. Also, I did test 0.19 with the same result.

**Comment by erimatnor** [comment]
Ok, I figured it out. Apparently 'dig' does not perform domain search resolution by default. You need to query with "dig +search" for it to append the search domains in `/etc/resolv.conf`. The Kibana errors must be due to the cluster coming up and elasticsearch-logging not yet running. So, conclusion is that this is probably a false alarm.

**Comment by thockin** [comment]
doh, of course.  I knew that.  I apologize for not seeing it.  We all need
a good red herring every now and then.  Can we close this issue out, then?

**Comment by erimatnor** [comment]
Yes, should be able to close this one.
