### ISSUE TITLE
Networking test should also run on a one-node local cluster

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10012]
Follow-up from a discussion in #9676:

From @jayunit100:
Looks like this makes it impossible to run e2e networking tests on a single node. but i think networking.go should work on single nodes - in fact - its an important test for local development imo. is there a way we can dial back the nodes >= 2 requirement?

(...) (see #9676 for all the discussion)
From @lavalamp:
 I'm fine with, e.g., gating the two node requirement with a comparison to the cloud provider.

Conclusion:
The test should fail if there is only one node, but only on GCE (and maybe other cloud providers):

**Comment by jayunit100** [comment]
LGTM, rather than adding more filters for other providers, later on we can parameterize it as an option if need be.  Thanks!

**Comment by mbforbes** [comment]
Fixed by #10015 (please reopen if not) (btw if you write "fixes #X" in the PR description GitHub automatically closes it...  I guess their synonym matching doesn't expand do "Resolves" :-) )

**Comment by marekbiskup** [comment]
Max, thanks for the hint!
