### ISSUE TITLE
Pods that are using host network should still be accessible to other pods via the API semantics

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#10022]
We realized just recently that HostNetwork pods aren't given a pod IP.  I wanted to get agreement on how we can make that pod visible. 

1. The effective ip of the pod is the host ip (which we also set).  
  1. We could set podIP to hostIP when in host networking and all higher level components would work
  2. We could change higher level components like the endpoints controller to look at hostIP instead of podIP in this case
2. The pod should get an ip assigned by the network plugin, but the network plugin makes the decision

We could do both of the above.  i don't know that we've formally stated hostIP is the internal cluster IP - because podIP is guaranteed to work in the cluster I think we would have to formalize that.

I'm looking for a quick decision (if possible) on whether 1.1 or 1.2 are acceptable - if they are, we are considering carrying a patch.

**Comment by smarterclayton** [comment]
@bgrant0607 @thockin

**Comment by thockin** [comment]
I think 1.1 is correct - the network plugin should not be engaged for host
networking.

**Comment by bgrant0607** [comment]
Yes, pod IP should be set to the host IP.

**Comment by bgrant0607** [comment]
If it's easy, I think we should take the PR.

**Comment by bgrant0607** [comment]
cc @dchen1107 @vmarmol

**Comment by smarterclayton** [comment]
@rajatchopra can you upstream your patch?

**Comment by dchen1107** [comment]
Yes, we should set Pod IP to the hostIP for pod using host network. @rajatchopra thanks for upload your patch.
