### ISSUE TITLE
Events API returns raw etcd errors in some cases

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#10031]
The events REST storage object is not using generic.Etcd, and it's not wrapping the returned errors from etcd with the appropriate `pkg/api/errors/etcd` handles.  As a result, we return raw etcd errors to clients which leaks server information (security) and is also ugly.

Spawned from https://github.com/openshift/origin/issues/3196

**Comment by davidopp** [comment]
@bgrant0607 should we close this as a dupe of #10064 which you referenced above and is already marked as 1.0?

**Comment by bgrant0607** [comment]
Sure. I copied the info over to the other issue, which itself is a dupe of #1990
