### ISSUE TITLE
Record pod StartTime when we receive a watch notification on the kubelet

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#10042]
Forked from: https://github.com/GoogleCloudPlatform/kubernetes/issues/9792#issuecomment-113213791, https://github.com/GoogleCloudPlatform/kubernetes/pull/7868#issuecomment-99706316

Proposal for StartTime modification:

1. Initialize StartTime, once, when the kubelet gets an add notification for the pod
2. If something else modifies it via the apiserver the kubelet will ignore the modification (we can probably evolve this to have the kublet correct any meddling)
3. If the pod is deleted and re-added, the timestamp will change, but not otherwise
4. If the kubelet is slow in dealing with a watch notification (eg: because of pod deletes) the StartTime will include that.

Such a timestamp would be helpful in measuring apiserver -> node watch latencies as well. Node team, thoughts? 

Fyi we can approximate the time it's currently recording as StartTime by sorting the startedAt timestamp of the containers of the pod.

@derekwaynecarr

**Comment by dchen1107** [comment]
I just updated the initial issue #9792 on this.

**Comment by bprashanth** [comment]
we decided not to do this
