### ISSUE TITLE
Consider not handling YAML in APIserver

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#1004]
The APIserver processes JSON and YAML.
A vulnerability in the apiserver would be critical.

Compared to JSON:
- YAML has a crazy complicated SPEC.
- YAML has a go implementation that is more complex 
  - 14KLOC JSON vs 30KLOC YAML
- YAML has fewer tests in the go implementation
  - 8KLOC JSON vs 2.5KLOC YAML
- Has a track record of vulnerabilities 
   - YAML has fewer vulnerabilities, but this may be due to its less widespread use in critical software
   - 24 CVEs match YAML vs 66 JSON, using http://web.nvd.nist.gov/view/vuln/search

Therefore we should consider one of the following changes:
 1. Do not process YAML in the apiserver itself:
  1. Convert YAML to JSON in clients 
  1. Recommend that users needing to use YAML via `curl`, etc, can pipe YAML through simple yaml to json converter tool.
 1. Convert YAML to JSON in a less privileged proxy process (which does not have access to etcd).

**Comment by smarterclayton** [comment]
We should remove YAML checking as part of the core runtime.Decode since the client now handles it via resource.Builder

**Comment by bgrant0607** [comment]
+1. We shouldn't be decoding YAML in Decode.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/decode.go#L23
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/decode.go#L49
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/decode.go#L112

**Comment by smarterclayton** [comment]
Fix incoming

**Comment by smarterclayton** [comment]
Fixed in #5533

**Comment by bgrant0607** [comment]
Is the content-type issue (setting in the client and documenting via go-restful) addressed by #5763?

**Comment by smarterclayton** [comment]
I'll add setting it from client commands to that pull, but the returning and documenting it is part of it already.

----- Original Message -----
