### ISSUE TITLE
Token discovery which falls back on service account tokens should log that fact

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10054]
I tried to break DNS to experience what everyone else is experiencing and ... it just worked.  @lavalamp explains that somewhere in the bowels of token code it says "hmm, that didn't work, let's try finding a service account".  And it does.  But how do I know that?

**Comment by lavalamp** [comment]
@mikedanese Since you're messing around in this code right now, can you add this log message?

**Comment by mikedanese** [comment]
Can I have an explanation or link of " what everyone else is experiencing" to make sure I understand this correctly? pkg/client doesn't seem to do any fancy token negotiation and only looks in the secrets dir.

**Comment by thockin** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/9857
