### ISSUE TITLE
kubectl exec eventually times out and can't be ^C'ed

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10056]
I see this reliably.  `kubectl exec -ti test-dns-4n4u4 -c kube2sky sh`, do some work, get a drink, come back and it's hung.  ^C doesn't work.  ^Z doesn't work.  The only answer I found was to kill it from another terminal.

@ncdc

**Comment by ncdc** [comment]
@thockin does your build have https://github.com/GoogleCloudPlatform/kubernetes/pull/9890? That should fix it.

**Comment by thockin** [comment]
will try

**Comment by thockin** [comment]
negative, still happens with a fresh-from-head build

**Comment by thockin** [comment]
umm, I forgot to push, lemme try that agin :)

**Comment by thockin** [comment]
ACK.  Now it drops the connection on timeout

**Comment by thockin** [comment]
Woops, it came back.

**Comment by thockin** [comment]
and eventually resolved itself - about 10 seconds, nothing happened and then it finally quit.

**Comment by ncdc** [comment]
@thockin I don't know if there's anything we can do about that. Here's what's going on:

1. You run up against the Kubelet's 5-minute hard-coded Read/WriteTimeout (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L68-L69), which terminates the request
1. The Kubelet's handleExec finishes (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L362)
1. It takes some amount of time (in my observations, 10-30 seconds) for the generic rest proxy to "see" the read/write timeout (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/generic/rest/proxy.go#L152-L170)
1. Once the proxy notices it, everything connection-wise is terminated, and you get your shell back

1 thing to note: if you run with a TTY and you hit the Kubelet's timeout, the process that is created via exec remains alive, and there's no way to automatically kill it, as Docker's exec doesn't provide either the process's PID or a means to stop/kill the exec'd process.

**Comment by bgrant0607** [comment]
See also #9180, #9013

**Comment by bgrant0607** [comment]
cc @krousey

**Comment by mikedanese** [comment]
Closing as dup of #9180
