### ISSUE TITLE
client code, kubecfg file being ignored by kube2sky in favor of service account token

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10068]
We end up making a non-verified connection to the wrong IP (service IP instead of VM IP).

@lavalamp @roberthbailey @mikedanese

**Comment by roberthbailey** [comment]
This could be solved by https://github.com/GoogleCloudPlatform/kubernetes/issues/7648, depending on which implementation path we take.

**Comment by thockin** [comment]
I am not close enough to this logic to say, but the current behavior is
pretty clearly a bug.

**Comment by mikedanese** [comment]
Is it correct to use only the inClusterConfig when it's available and ignore all other available configs, maybe even configs passed imperatively from command line args? This seems unintuitive and prone to confusion.
