### ISSUE TITLE
Improve schema validating error message from kubectl create when '--validate' is set

### ISSUE THREAD

**Issue by feihujiang** [GoogleCloudPlatform/kubernetes#10079]
kubectl create when '--validate' is set, it uses a schema to validate the input  before sending it.
But now in schema validate, if an error occurs, it returns at once, only just show an error message. We should aggregate errors like server validate.
in schema validate, it doesn’t handle required fields now. We should handle them.

**Comment by satnam6502** [comment]
Actually assigned to @feihujiang

**Comment by satnam6502** [comment]
Please can the appropriate TL determine a milestone for this change.

**Comment by bgrant0607** [comment]
I'd like this for 1.0. We need to give clear, actionable feedback to users when their configs are incorrect.

**Comment by satnam6502** [comment]
Fixed via #10007
