### ISSUE TITLE
Clarify the "who", "when", "why", and "how" for the Kubernetes UI

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10097]
Kubernetes UI (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/ui.md):
 - Need to make this content clearer
 - Clarify the ""who"", ""when"", ""why"", and ""how"" to use it. For example, define the expected workflow for how to setup, configure (to show what?), and use(ie. good for monitoring?). Plus clarify who this benefits. Is the intended user an admin?

**Comment by bgrant0607** [comment]
cc @jackgr @bcbroussard @preillyme

**Comment by bgrant0607** [comment]
Indeed, we have no docs about using the UI. We should create some overview and workflow-oriented docs, with screenshots.

**Comment by bgrant0607** [comment]
Looks like we also need to update deployment documentation, at least for non-GCE/GKE cloud providers: https://github.com/GoogleCloudPlatform/kubernetes/issues/10697#issuecomment-119005309

**Comment by davidopp** [comment]
Is there anyone who has more experience with the UI who would be interested to take this issue from me?

**Comment by bgrant0607** [comment]
cc @JanetKuo

**Comment by JanetKuo** [comment]
I'll update docs/ui.md by adding a section "Using the UI" which describes why user need to use the UI, and what they can do with it (along with some screenshots). 

cc @timstclair @lavalamp

**Comment by bcbroussard** [comment]
Thanks @janetkuo, let me know if there is any support you need from me.
