### ISSUE TITLE
Validate and revise the "namespaces" help topic

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10109]
Today, the namespaces content exists in a 'design' doc (not a stand alone help topic). We should create a V1 specific topic to clarify and define namespaces for v1.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/namespaces.md

**Comment by derekwaynecarr** [comment]
Will write this up on Monday

**Comment by bgrant0607** [comment]
Needs to be done this week if it's going to get into our 1.0 doc branch. Is there a PR for this?
