### ISSUE TITLE
Add another contributed client library link

### ISSUE THREAD

**Issue by perljedi** [GoogleCloudPlatform/kubernetes#10114]
I have been working on a perl client library for interacting with kubernetes.  Would it be possible to include it in the "User Contributed" section of docs/client-libraries.md?

[Net::Kubernetes](https://metacpan.org/pod/Net::Kubernetes)

**Comment by satnam6502** [comment]
Sure. Why not submit a PR?

**Comment by perljedi** [comment]
Will do, thanks
