### ISSUE TITLE
Provide task oriented documentation around Clusters

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10125]
We have disconnected documentation around these tasks (and their workflows) but need to explicitly define them in a single location.

We should have a document that addresses our Cluster related tasks:

Managing Clusters:
 - Overview *(simple intro about how to manage a Cluster and mention if there are any routine tasks that should be regularly performed)*
 - Prerequisites 
 - Creating
 - Configuring
 - Scaling?
 - Viewing
 - Deleting (Tearing Down)
 - Other tasks?
 - Next Steps *(direct user to the next steps/tasks they can perform)*

Here is a good example of what we need: The "[Container Clusters](https://cloud.google.com/container-engine/docs/clusters/operations)" topic in GKE.
Key benefits to note: A single consolidated reference that is task oriented, explains the possible methods for accomplishing the task, provides a general workflow that applies to all, and provides syntax and examples.

**Comment by thockin** [comment]
Another for @alex-mohr @wojtek-t

**Comment by wojtek-t** [comment]
@gmarek @jszczepkowski - can one of you please take a look?

**Comment by brendandburns** [comment]
Asssigning to @gmarek since I think he has it in #10827

**Comment by bgrant0607** [comment]
Can this be closed?
