### ISSUE TITLE
Flaky e2e: Shell should pass tests for services.sh (Failed 3 times in the last 30 runs. Stability: 90 %)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#10127]
Master issue is #9312 

Recent failures include:

====

waiting for service3 at 10.0.193.5:80
wget: download timed out
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
testing service3 VIP from container failed
namespaces/services-test-701

===

waiting for service3 at 10.0.110.153:80
Test 7: Bring up another service, make sure it does not re-use IPs.
Starting service 'services-test-15187/service4' on port 80 with 3 replicas
error: could not read an encoded object from STDIN: unable to connect to a server to handle "replicationcontrollers": couldn't read version from server: Get https://173.255.114.153/version: dial tcp 173.255.114.153:443: connection refused

error: no objects passed to create
error: couldn't read version from server: Get https://173.255.114.153/version: dial tcp 173.255.114.153:443: connection refused

====

**Comment by quinton-hoole** [comment]
See also #8849.

**Comment by quinton-hoole** [comment]
See also #8953

**Comment by brendandburns** [comment]
I'm going to take another shot at cleaning this up.

**Comment by quinton-hoole** [comment]
I suspect that the part of the test that is failing is working correctly in test/e2e/services.go, and can simply be deleted from this shell-based test?

**Comment by wojtek-t** [comment]
@brendanburns - are you planning to look into it today? If not, I can look into it tomorrow waw time and check whether the shell script is testing anything that is not tested by go test.

**Comment by wojtek-t** [comment]
I will look into it tomorrow waw time.

**Comment by wojtek-t** [comment]
@quinton-hoole 

FYI: after merging #10819 the test already passed 10 times as part of gce-flaky. I will leave it there for one more day and move it to stable tomorrow if there won't be any failures until then.

**Comment by wojtek-t** [comment]
There are still 2 kind of failures that are happening:

    Test 5: Remove the iptables rules, make sure they come back.
    Manually removing iptables rules
    Verifying the VIPs from the host
    waiting for service3 at 10.0.175.78:80
    Verifying the VIPs from a container
    waiting for service3 at 10.0.175.78:80
    wget: download timed out
    ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].

and

    Test 1: Prove that the service VIP is alive.
    Verifying the VIP from the host
    waiting for service1 at 10.0.76.189:80
    waiting for service2 at 10.0.17.239:80
    expected 'service2-1z6tg service2-2x41m service2-l8voq', got 'service2-2x41m service2-l8voq': will try again
    expected 'service2-1z6tg service2-2x41m service2-l8voq', got 'service2-2x41m service2-l8voq': will try again
    expected 'service2-1z6tg service2-2x41m service2-l8voq', got 'service2-2x41m service2-l8voq': will try again
    expected 'service2-1z6tg service2-2x41m service2-l8voq', got 'service2-2x41m service2-l8voq': will try again
    expected 'service2-1z6tg service2-2x41m service2-l8voq', got 'service2-2x41m service2-l8voq': will try again
    service2: failed to verify portal from host

**Comment by wojtek-t** [comment]
Hopefully - this should be fixed now. I will be monitoring the test and will move it to non-flaky suite tomorrow.

**Comment by wojtek-t** [comment]
Fixed by #10989

**Comment by quinton-hoole** [comment]
#10989 broke e2e-gce-parallel, our parallel test run (and presumably all per-PR e2e runs). See comment there on how to fix it.

**Comment by davidopp** [comment]
This failed again:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/7545/

**Comment by wojtek-t** [comment]
I think I understand the failure - in test 6 we don't wait until apiserver is really restarted, so it sometimes happen that at the begining of test 7 apiserver is still down (or at least not yet responding to request). I will prepare a fix for it.

**Comment by saad-ali** [comment]
Sorry to keep beating a dead horse, but "Shell should pass tests for services.sh" still looks flaky. After #11139 was merged it has failed two GCE E2E runs, and the 1 and only GCE soak test run after today's 2 PM deployment.

See:
* job/kubernetes-e2e-gce/7575/
* job/kubernetes-e2e-gce/7576/
* job/kubernetes-soak-continuous-e2e/1981/

**Comment by saad-ali** [comment]
Fixed with #10127

**Comment by wojtek-t** [comment]
@saad-ali - thanks for fixing it!
