### ISSUE TITLE
Provide task oriented documentation around Services

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10123]
We have disconnected documentation around these tasks (and their workflows) but need to explicitly define them in a single location.

We should have a document that addresses our Services related tasks:

Managing Services:

 - Overview *(simple intro about how to manage a Service and mention if there are any routine tasks that should be regularly performed)*
 - Prerequisites
 - Creating
 - Configuring?
 - Viewing
 - Updating?
 - Deleting
 - Other tasks?
 - Next Steps (direct user to the next steps/tasks they can perform)

Here is a good example of what we need: The "[Services](https://cloud.google.com/container-engine/docs/services/operations)" topic in GKE.
Key benefits to note: A single consolidated reference that is task oriented, explains the possible methods for accomplishing the task, provides a general workflow that applies to all, and provides syntax and examples.

**Comment by bgrant0607** [comment]
I'm going to treat this issue, #10121, #10119, #3153, #8524, and others as a single issue: 

Need a task-oriented user guide for managing applications.

Concept-oriented docs and examples can provide supporting material.

Side note: we should separate the concept-oriented examples (e.g., examples/liveness) from application-oriented examples (e.g., examples/cassandra). I'd put toy example apps (e.g., guestbook, k8spetstore) in the concept category.

**Comment by bgrant0607** [comment]
Services documented by #11072
