### ISSUE TITLE
Provide task oriented documentation around Replication Controllers

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10121]
We have disconnected documentation around these tasks (and their workflows) but need to explicitly define them in a single location.

We should have a document that addresses our Replication Controller related tasks:

Managing Replication Controllers:
 - Overview *(simple intro about how to manage a Replication Controller and mention if there are any routine tasks that should be regularly performed)*
 - Prerequisites 
 - Creating
 - Configuring
 - Scaling
 - Viewing
 - Updating
 - Deleting
 - Other tasks?
 - Next Steps *(direct user to the next steps/tasks they can perform)*

Here is a good example of what we need: The "[Replication Controllers](https://cloud.google.com/container-engine/docs/replicationcontrollers/operations)" topic in GKE.
Key benefits to note: A single consolidated reference that is task oriented, explains the possible methods for accomplishing the task, provides a general workflow that applies to all, and provides syntax and examples.

**Comment by bgrant0607** [comment]
See #10123

**Comment by bgrant0607** [comment]
Fixed by #11071
