### ISSUE TITLE
Kube-Proxy Nodes Still Referencing Old Portal Net

### ISSUE THREAD

**Issue by akamalov** [GoogleCloudPlatform/kubernetes#10120]
<b> Environment </b>
```OS: CoreOS 695```
```Kubernetes Release: 0.19.0```

<b> Problem </b>

I had to change my portal net from <b>10.100.0.x</b> to <b>11.0.0.0/8</b>. Updated kube-apiserver & restarted it and restarted worker nodes. However, I've noticed that worker node kube-proxies were still referencing old value:

```
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.107605    3181 iptables.go:193] running iptables -N [KUBE-PORTALS-HOST -t nat]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.109779    3181 iptables.go:193] running iptables -C [OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.110756    3181 iptables.go:193] running iptables -N [KUBE-NODEPORT-CONTAINER -t nat]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.112607    3181 iptables.go:193] running iptables -C [PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.113852    3181 iptables.go:193] running iptables -N [KUBE-NODEPORT-HOST -t nat]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.115809    3181 iptables.go:193] running iptables -C [OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.117953    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment default/kubernetes-ro: -p tcp -m tcp --dport 80 -d 10.100.0.1/32 -j REDIRECT --to-ports 57308]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.120173    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment default/kubernetes-ro: -p tcp -m tcp --dport 80 -d 10.100.0.1/32 -j DNAT --to-destination 10.9.159.76:57308]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.122421    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment default/kubernetes: -p tcp -m tcp --dport 443 -d 10.100.0.2/32 -j REDIRECT --to-ports 51459]
Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.124865    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment default/kubernetes: -p tcp -m tcp --dport 443 -d 10.100.0.2/32 -j DNAT --to-destination 10.9.159.76:51459]
```

As you can see, instead of referencing ```11.0.0.x```, it is still referencing ```10.100.0.x``` environment.

As I've mentioned, kube-apiserver has been updated with new portal net:

```
wwserver60 coreos-install # systemctl -l status kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2015-06-19 19:44:55 UTC; 56min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 17663 ExecStartPre=/usr/bin/chmod +x /opt/bin/kubectl (code=exited, status=0/SUCCESS)
  Process: 17659 ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v0.19.0/bin/linux/amd64/kubectl (code=exited, status=0/SUCCESS)
  Process: 17656 ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-apiserver (code=exited, status=0/SUCCESS)
  Process: 17654 ExecStartPre=/usr/bin/curl -L -o /opt/bin/kube-apiserver -z /opt/bin/kube-apiserver https://storage.googleapis.com/kubernetes-release/release/v0.19.0/bin/linux/amd64/kube-apiserver (code=exited, status=0/SUCCESS)
  Process: 17651 ExecStartPre=/usr/bin/mkdir -p /opt/bin (code=exited, status=0/SUCCESS)
 Main PID: 17666 (kube-apiserver)
   Memory: 37.0M
   CGroup: /system.slice/kube-apiserver.service
           └─17666 /opt/bin/kube-apiserver --allow_privileged=false --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --insecure_bind_address=0.0.0.0 --insecure_port=8888 --kubelet_https=true --secure_port=6443 --service-cluster-ip-range=11.0.0.0/8 --etcd_servers=http://127.0.0.1:2379 --public_address_override=10.9.158.219 --basic_auth_file=/var/lib/kubernetes/basic_auth.csv --token_auth_file=/var/lib/kubernetes/known_tokens.csv --cluster_name=test_cluster1 --logtostderr=true --v=2

Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.313998   17666 handlers.go:135] GET /api/v1/nodes/10.9.159.75: (1.670274ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.75:47065]
Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.410017   17666 handlers.go:135] PUT /api/v1/nodes/10.9.159.75/status: (94.543051ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.75:47065]
Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.615202   17666 handlers.go:135] GET /api/v1/nodes/10.9.158.72: (1.802073ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.72:45436]
Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.735802   17666 handlers.go:135] PUT /api/v1/nodes/10.9.158.72/status: (119.253898ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.72:45436]
Jun 19 20:41:07 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:07.115758   17666 handlers.go:135] GET /api/v1/nodes/10.9.159.76: (1.564129ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.76:37718]
Jun 19 20:41:07 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:07.209871   17666 handlers.go:135] PUT /api/v1/nodes/10.9.159.76/status: (91.897732ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.76:37718]
Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.514406   17666 handlers.go:135] GET /api/v1/nodes/10.9.158.71: (1.758213ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.71:46963]
Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.612823   17666 handlers.go:135] PUT /api/v1/nodes/10.9.158.71/status: (97.023808ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.71:46963]
Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.614884   17666 handlers.go:135] GET /api/v1/nodes/10.9.159.77: (1.468648ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.77:37778]
Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.710113   17666 handlers.go:135] PUT /api/v1/nodes/10.9.159.77/status: (93.527004ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.77:37778]
wwserver60 coreos-install # 
```

Is it caching somewhere? What can I do so kube-proxy service would pickup a new value?

Thanks so much!!

Alex

**Comment by thockin** [comment]
On Fri, Jun 19, 2015 at 1:46 PM, akamalov <notifications@github.com> wrote:
>
> Environment
> OS: CoreOS 695
> Kubernetes Release: 0.19.0
>
> Problem
>
> I had to change my portal net from 10.100.0.x to 11.0.0.0/8.

First thought: you can't just use 11.* IPs - those actually belong to someone.

Second thought: you can't really change the portal net like that.  All
the Services that already exist already have IP addresses assigned.
We do not go through and re-assign them.  You have to delete all the
services and then re-create them, and that will allocate new IPs.

> Updated kube-apiserver & restarted it and restarted worker nodes. However, I've noticed that worker node kube-proxies were still referencing old value:
>
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.107605    3181 iptables.go:193] running iptables -N [KUBE-PORTALS-HOST -t nat]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.109779    3181 iptables.go:193] running iptables -C [OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.110756    3181 iptables.go:193] running iptables -N [KUBE-NODEPORT-CONTAINER -t nat]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.112607    3181 iptables.go:193] running iptables -C [PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.113852    3181 iptables.go:193] running iptables -N [KUBE-NODEPORT-HOST -t nat]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.115809    3181 iptables.go:193] running iptables -C [OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.117953    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment default/kubernetes-ro: -p tcp -m tcp --dport 80 -d 10.100.0.1/32 -j REDIRECT --to-ports 57308]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.120173    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment default/kubernetes-ro: -p tcp -m tcp --dport 80 -d 10.100.0.1/32 -j DNAT --to-destination 10.9.159.76:57308]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.122421    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment default/kubernetes: -p tcp -m tcp --dport 443 -d 10.100.0.2/32 -j REDIRECT --to-ports 51459]
> Jun 19 20:35:30 wwserver205.alphalocal.net kube-proxy[3181]: I0619 20:35:30.124865    3181 iptables.go:193] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment default/kubernetes: -p tcp -m tcp --dport 443 -d 10.100.0.2/32 -j DNAT --to-destination 10.9.159.76:51459]
>
> As you can see, instead of referencing 11.0.0.x, it is still referencing 10.100.0.x environment.
>
> As I've mentioned, kube-apiserver has been updated with new portal net:
>
> wwserver60 coreos-install # systemctl -l status kube-apiserver
> ● kube-apiserver.service - Kubernetes API Server
>    Loaded: loaded (/etc/systemd/system/kube-apiserver.service; static; vendor preset: disabled)
>    Active: active (running) since Fri 2015-06-19 19:44:55 UTC; 56min ago
>      Docs: https://github.com/GoogleCloudPlatform/kubernetes
>   Process: 17663 ExecStartPre=/usr/bin/chmod +x /opt/bin/kubectl (code=exited, status=0/SUCCESS)
>   Process: 17659 ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v0.19.0/bin/linux/amd64/kubectl (code=exited, status=0/SUCCESS)
>   Process: 17656 ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-apiserver (code=exited, status=0/SUCCESS)
>   Process: 17654 ExecStartPre=/usr/bin/curl -L -o /opt/bin/kube-apiserver -z /opt/bin/kube-apiserver https://storage.googleapis.com/kubernetes-release/release/v0.19.0/bin/linux/amd64/kube-apiserver (code=exited, status=0/SUCCESS)
>   Process: 17651 ExecStartPre=/usr/bin/mkdir -p /opt/bin (code=exited, status=0/SUCCESS)
>  Main PID: 17666 (kube-apiserver)
>    Memory: 37.0M
>    CGroup: /system.slice/kube-apiserver.service
>            └─17666 /opt/bin/kube-apiserver --allow_privileged=false --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --insecure_bind_address=0.0.0.0 --insecure_port=8888 --kubelet_https=true --secure_port=6443 --service-cluster-ip-range=11.0.0.0/8 --etcd_servers=http://127.0.0.1:2379 --public_address_override=10.9.158.219 --basic_auth_file=/var/lib/kubernetes/basic_auth.csv --token_auth_file=/var/lib/kubernetes/known_tokens.csv --cluster_name=test_cluster1 --logtostderr=true --v=2
>
> Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.313998   17666 handlers.go:135] GET /api/v1/nodes/10.9.159.75: (1.670274ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.75:47065]
> Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.410017   17666 handlers.go:135] PUT /api/v1/nodes/10.9.159.75/status: (94.543051ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.75:47065]
> Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.615202   17666 handlers.go:135] GET /api/v1/nodes/10.9.158.72: (1.802073ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.72:45436]
> Jun 19 20:41:06 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:06.735802   17666 handlers.go:135] PUT /api/v1/nodes/10.9.158.72/status: (119.253898ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.72:45436]
> Jun 19 20:41:07 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:07.115758   17666 handlers.go:135] GET /api/v1/nodes/10.9.159.76: (1.564129ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.76:37718]
> Jun 19 20:41:07 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:07.209871   17666 handlers.go:135] PUT /api/v1/nodes/10.9.159.76/status: (91.897732ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.76:37718]
> Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.514406   17666 handlers.go:135] GET /api/v1/nodes/10.9.158.71: (1.758213ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.71:46963]
> Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.612823   17666 handlers.go:135] PUT /api/v1/nodes/10.9.158.71/status: (97.023808ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.158.71:46963]
> Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.614884   17666 handlers.go:135] GET /api/v1/nodes/10.9.159.77: (1.468648ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.77:37778]
> Jun 19 20:41:12 wwserver60.alphalocal.net kube-apiserver[17666]: I0619 20:41:12.710113   17666 handlers.go:135] PUT /api/v1/nodes/10.9.159.77/status: (93.527004ms) 200 [[kubelet/v0.19.0 (linux/amd64) kubernetes/6b0d4ff] 10.9.159.77:37778]
> wwserver60 coreos-install #
>
> Is it caching somewhere? What can I do so kube-proxy service would pickup a new value?

Yeah - it "caches" it in our API's storage layer.

**Comment by akamalov** [comment]
Thanks Tim! I will rollback and re-configure flannel network to match 10.100.0.0/16
