### ISSUE TITLE
Update etcd to v2.0.12

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#10137]
We should update etcd to v2.0.12 to pick up its fixes over 2.0.9.  Inspired partially by #10122.

@davidopp @brendandburns I haven't seen instructions for updating our dependency versions -- any pointers, or is it tribal knowledge?

Also, should we start adding a step to our releases to pick up the most-recent version of our dependencies and rebuild those images?

**Comment by thockin** [comment]
This is a big topic.  We don't currently vendor etcd so we really have no
reproducible build.  I do not think we should blindly pick up new releases

**Comment by lavalamp** [comment]
Yes, I agree with Tim. We should *not* grab this for v1.0. etcd releases need to spend a lot of time in our e2e tests, soaking.

#10122 can be fixed by just not restarting etcd.

**Comment by alex-mohr** [comment]
@thockin I didn't mean blindly pick them up, but rather include them as part of our versioned kubernetes releases -- only release once they pass our validation steps?

And we apparently build our own etcd image: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/images/etcd

**Comment by thockin** [comment]
Yes, we build our own etcd image with no vendored code or deps.  It's
terrifiying.  I spent much of my free time last week reading and playing
with vendoring tools to help us and they are all weak at best.

**Comment by davidopp** [comment]
@thockin can you say more about why picking up a particular binary release of etcd, qualifying it, and then using it with our release is terrifying?

/cc @dchen1107 who I was actually discussing this general topic with last night.

**Comment by thockin** [comment]
We have no way to rebuild it or debug it, should something go wrong.  It's
not that I don't trust the CoreOS folks in specific, it's that sometimes
people screw up.  We've already had it happen a few times, where the git
SHA we vendored in got obliterated upstream and we could no longer recreate
a build, except that we had vendored the code.

Consider that every 3rd-party thing we deploy is one of two grades:

1) Stuff we NEED (etcd, skydns) and need to be able to debug, patch, hack,
etc
2) Stuff we USE (kibana, elasticsearch) but probably would not build our
own custom version of

@satnam did I miscategorize your work on these things?  How deep are our
changes?

I think that anything we NEED we should vendor (be that vendoring into
kubernetes of forking into a new repo) and build ourselves

The rest we might just build/push our own containers just so we can control
versioning

On Fri, Jun 19, 2015 at 4:04 PM, David Oppenheimer <notifications@github.com

**Comment by dchen1107** [comment]
Agreed with @thockin above.

For particular p0 issue #10122, CJ Cullen and I discussed, the current proposed solution is not starting any pods / containers until network configuration is done. In this case, shouldn't no need to rush to upgrade to a new etcd version?

**Comment by cjcullen** [comment]
I think the "not starting containers until network configured" would have to be handled in salt, by not copying manifest files until we've configured cbr0. Kubelet and docker run on startup with default args because of container-vm. So if we copy etcd.manifest to /etc/kubernetes/manifests before we get around to flipping docker, bad things can happen.

The right answer is probably to skip configuring cbr0 & flipping docker in the master's salt. I think @brendandburns is going to take a look on what that would take.

**Comment by dchen1107** [comment]
When I suggesting not starting containers until network configured, I were thinking kubelet check if network is configured properly. I remembered when cbr0 first introduced, one of my review comments is set NodeNotReady until cbr0 is configured, but I forget at the end if we did it or not. I will take a look on it.

Also @brendandburns's suggest could work around the issue too. The simplest way to achieve that is just disable this through kubelet flag --configure-cbr0

**Comment by brendandburns** [comment]
@dchen1107 I agree that we shouldn't start until the network is ready.

Check out https://github.com/GoogleCloudPlatform/kubernetes/pull/10153

which achieves this.

**Comment by davidopp** [comment]
It sounds like we're not going to upgrade to etcd v2.0.12? If so, we should close this issue (and #10140) and continue the discussion on #10153.

**Comment by alex-mohr** [comment]
We decided to update etcd to 2.0.12 in #10140.  @dchen1107 will also pick up #10153 to address #10122.
