### ISSUE TITLE
Use docker's --bip instead of our own bridge

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10143]
I think that will work and simplify a few things.

**Comment by kelseyhightower** [comment]
@thockin I've been doing this for a few months now without issue, and it means one less thing to setup (cbr0).

**Comment by derekwaynecarr** [comment]
For systemd distro, can't kubelet unit file just add an After=docker.socket and there would be no race?

**Comment by dchen1107** [comment]
@derekwaynecarr and @kelseyhightower please see my comments at 
https://github.com/GoogleCloudPlatform/kubernetes/pull/10153#issuecomment-113729964

Also I believe both your cloudproviders don't pass --configure-cbr0 to your kubelets yet. Instead the network is configured with pre-allocated CIDR at machine up time. In this case, there is no race.

**Comment by kelseyhightower** [comment]
I think long term we should migrate towards the new `docker network` command, which will allow us to ensure the right bridge network is in place and attach containers too it. As of docker 1.7 this functionaliity is marked experimental, but the underlying libnetwork is being used by default. https://github.com/docker/docker/blob/master/experimental/networking.md

**Comment by thockin** [comment]
Now that kubelet manages cbr0, I am going to close this.
