### ISSUE TITLE
Host-based load balancing

### ISSUE THREAD

**Issue by jhaagmans** [GoogleCloudPlatform/kubernetes#10155]
We've been playing with CoreOS for a while, in which we'd use fleet to provision containers including a global [vulcand](http://vulcanproxy.com) service for which entries were written to etcd using logic like this:

```
[Unit]
Description=Nginx
After=docker.service

[Service]
ExecStartPre=-/usr/bin/docker kill nginx-%i
ExecStartPre=-/usr/bin/docker pull nginx
ExecStart=/usr/bin/docker run --rm --name nginx-%i -p 80 nginx
ExecStartPost=/usr/bin/etcdctl set /vulcand/backends/nginx/backend '{"Type": "http"}'
ExecStartPost=/bin/sh -c "/usr/bin/etcdctl set /vulcand/backends/nginx/servers/%i '{\"URL\": \"http://'$(echo $(hostname))':'$(echo $(/usr/bin/docker port nginx-%i) | cut -d':' -f2)'\"}'"
ExecStartPost=/usr/bin/etcdctl set /vulcand/frontends/nginx/frontend '{"Type": "http", "BackendId": "nginx", "Route": "HostRegexp(\\"nginx.ourdomain.nl\\")"}'
ExecStop=/usr/bin/etcdctl rm /vulcand/backends/nginx/servers/%i
ExecStop=/usr/bin/docker stop nginx-%i
```

This works, but for many reasons we weren't very happy with our CoreOS setup and haven't pushed it to our development/staging environments. Kubernetes seems to be the definitive answer to most of our problems though. It feels solid and well thought-through. However, the above logic is something we haven't been able to find an analogy for. This is how far I came so far:

As I understand it, a Kubernetes service provides a service IP that _sort of_ load balances traffic, which would mean we could have one service subscribe to a node port (e.g. 30000) which would read the host headers and proxy forward to a service using the service IP. This would be the load balancer. I've tried to use vulcand for this, but I can't find a way to run a command when a service starts and/or stops. Is this possible at all? Or does the current Kubernetes landscape have an alternative solution for this?

I'd like to add that we would have somewhere around 150 applications running in individual services, so using an external load balancer for each application and forwarding to a nodePort is not something I would prefer. Besides, I'd like our service files to be descriptive for what's happening within a service instead of having to map nodePorts to applications in a loadbalancing service.

Thank you!

**Comment by fcantournet** [comment]
> I've tried to use vulcand for this, but I can't find a way to run a command when a service starts and/or 
> stops. Is this possible at all? Or does the current Kubernetes landscape have an alternative solution 
> for this?

I'm not sure I understand what you want to do, but if you want to hook on the creation and deletion of kubernetes services, you can use the watch services url

http://%your_kubernetes_master%/api/v1/watch/services

checkout the kiwi project from Lars Kellogg-Stedman. https://github.com/larsks/kiwi
It's not compatible with kubernetes API v1, so i've forked it and (sort of) fixed it.

Shoud give you some pointers.

**Comment by brosner** [comment]
I have had this exact need and looked at many options before deciding to write my own HTTP router. It is very rough around the edges, but it may give you more pointers or I would love additional contributions. https://github.com/eldarion-gondor/k8s-http-router

As I understand it, Kubernetes is looking to support L7 HTTP routing natively.

**Comment by jhaagmans** [comment]
@fcantournet That's indeed what I was looking for, thank you. If I'd be able to have a container running a script watching this stream and responding accordingly to this stream, I should be able to push messages to a loadbalancing container. I'd have to work it out some more, but the project you mentioned should give me enough pointers to get me started, indeed.

@brosner Well, that's looking wonderful! I'll check it out and see if it fits all our needs. Thank you very much!

I'll close this issue as it's been answered, but if anyone would like to weigh in or whenever native L7 routing support is ready, I'd love to know.

**Comment by thockin** [comment]
L7 is a high priority for me after 1.0
