### ISSUE TITLE
kubectl describe node succeeds for a nonexisting node

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10156]
```
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ cluster/kubectl.sh describe node/asdf
Error from server: minion "asdf" not found
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ cluster/kubectl.sh describe node asdf
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ echo $?
0
```

 1. error is found in the first case, but not in the second one
 1. the word minion should be replaced by node

**Comment by feihujiang** [comment]
Is there anyone to fix "error is found in the first case, but not in the second one"? If not, I'd like to volunteer myself to fix it.

**Comment by nikhiljindal** [comment]
@feihujiang I dont think anyone is working on it. Please feel free to take it up.
Thanks!

**Comment by feihujiang** [comment]
@nikhiljindal OK, I start to work on this now.

**Comment by marekbiskup** [comment]
minion->node change has already been done too.
