### ISSUE TITLE
Update all kubectl get output in the documentation

### ISSUE THREAD

**Issue by andronat** [GoogleCloudPlatform/kubernetes#10168]
As it is happening at #10167, we need to update all the documentation on the `kubectl get` output. Also inform the user for the `--label-column=` option for further information.

This is due to the update we had in #9032 and #9876

**Comment by bgrant0607** [comment]
I'd like to get this done now that we're focusing on docs for 1.0.

Different examples could be done by different people, in order to parallelize the work. Please pitch in once more critical 1.0 issues are resolved. 

cc @JanetKuo @caesarxuchao @krousey @nikhiljindal

**Comment by caesarxuchao** [comment]
I'll work on the first 5 examples for now, i.e. aws_ebs to cluster-dns.

**Comment by caesarxuchao** [comment]
I'll work on the next 5 examples, i.e. downward-api to glusterfs

**Comment by caesarxuchao** [comment]
I'll work on the next 10 examples, i.e. guestbook-go to logging-demo

**Comment by caesarxuchao** [comment]
I'll work on the next 5 examples, meteo to openshift-origin

**Comment by caesarxuchao** [comment]
I'll work through all the examples.

**Comment by JanetKuo** [comment]
I'll work on docs/devel/

**Comment by JanetKuo** [comment]
I'll work on docs/getting-started-guides/

**Comment by JanetKuo** [comment]
I'll work on all other documents.

**Comment by JanetKuo** [comment]
After all related PRs are merged, we can close this.
