### ISSUE TITLE
Kubernetes Dashboard - Graphs do not display legends in full

### ISSUE THREAD

**Issue by imesh** [GoogleCloudPlatform/kubernetes#10164]
I noticed this problem since Kubernetes introduced the Dashboard, please see the below image. If possible I would like to contribute to fix this issue:

Kubernetes version: 0.18.0
Environment: Vagrant, CoreOS 717.0.0

![screen shot 2015-06-21 at 2 36 51 pm](https://cloud.githubusercontent.com/assets/56142/8271127/51de8ea0-1824-11e5-9b2a-a51cc39e2b32.png)

**Comment by mikedanese** [comment]
dup of #9347

**Comment by mikedanese** [comment]
Closing as duplicate in favor of #9347
