### ISSUE TITLE
godep restore/update failing on mac

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/kubernetes#10195]
godep commands are failing on mac (head of master).

I'm pretty sure godep is doing a `go get` which tries to build the code, instead of just checking it out. So it's failing trying to build `github.com/google/cadvisor/api` and `golang.org/x/exp/inotify`.

Go installed with homebrew. 
`GOPATH=/Users/karl/workspace/k8s-master`

```
$ godep restore
package github.com/google/cadvisor/api
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: restore: exit status 1
package golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: restore: exit status 1
package golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: restore: exit status 1
package golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: restore: exit status 1
package golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: restore: exit status 1
package golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify
	imports golang.org/x/exp/inotify: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: restore: exit status 1
```

```
$ godep update github.com/onsi/ginkgo
godep: C source files not allowed when not using cgo: statvfs.c
godep: cannot find package "golang.org/x/exp/inotify" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/exp/inotify (from $GOROOT)
	/Users/karl/workspace/k8s-master/src/golang.org/x/exp/inotify (from $GOPATH)
godep: error loading dependencies
```

**Comment by karlkfi** [comment]
I managed to get godep commands to work:
1. Remove `github.com/google/cadvisor/http` and `golang.org/x/exp/inotify` from Godeps.json
2. Performing the godep commands
3. Re-add `github.com/google/cadvisor/http` and `golang.org/x/exp/inotify` to Godeps.json

```
		{
			"ImportPath": "github.com/google/cadvisor/http",
			"Comment": "0.15.1",
			"Rev": "ec588def40e1bb59f28f5a293b279f6762d13d44"
		},
```

```
		{
			"ImportPath": "golang.org/x/exp/inotify",
			"Rev": "d00e13ec443927751b2bd49e97dea7bf3b6a6487"
		},

```

**Comment by vishh** [comment]
cc @rjnagal

**Comment by mbforbes** [comment]
Is this worth an issue or mention in https://github.com/tools/godep ?

@karlkfi is there any work left in this issue? It looks like you've got it figured out so I'm closing... *please* re-open if I'm mistaken! Thank you!

**Comment by karlkfi** [comment]
I provided a manual workaround, but it seems unreasonable to expect developers to have to know and/or do this. 

It seems like an unrealistic expectation to expect all developers to develop on linux. I was under the impression many of the google developers use macs. Is no one else having this problem? I was hoping for some input or ideas.

I consider this a k8s bug, not a godep bug, but it might be possible to avoid it by adding a platform godep feature.

We have a few options:
- add a feature to godep to specify platform-specific dependencies
- change the project dependencies so that this workaround not required
- automate this workaround so that developers don't have to know about it
- document the workaround somewhere persistent and discoverable

**Comment by karlkfi** [comment]
I am unable to re-open this issue. It seems restricted to committers...

**Comment by mbforbes** [comment]
I also develop on a Mac.

I have only experienced pain and sorrow with godep.

@a-robinson has helped me once. Any wisdom?

**Comment by a-robinson** [comment]
I haven't updated our godeps in months, and never on OS X. There must be someone else more paged in to help with this?

**Comment by eghobo** [comment]
I see the same error at OSX 10.9.5 with go 1.4.2 (trough macports), workaround from @karlkfi help

**Comment by karlkfi** [comment]
real options:
- put SOMETHING buildable on all platforms in every directory, even if it's just `package x` with docs (we're doing this with doc.go files in k8s repo, but need to do it to deps)
- change godeps to not use `go get` so it stops trying to build when you don't need it to
- modify `go get` to have a flag to no build, and modify godeps to use it
