### ISSUE TITLE
Add source filename in “error from server” message when using kubectl

### ISSUE THREAD

**Issue by feihujiang** [GoogleCloudPlatform/kubernetes#10212]
When I use kubectl create –f, I found that some error messages show the source filename. But “Error from server: …” messages don’t show the source filename. I think this is inconvenient, especially when I create resources from a directory, I don’t know which template file caused the error. Is it necessary to add source filename in “error from server” message when using kubectl? What’s your point?

**Comment by bgrant0607** [comment]
Thanks, @feihujiang. I believe this can be closed since #10221 was merged.
