### ISSUE TITLE
Label selector query parameter is labelSelector instead of label-selector?

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/kubernetes#10229]
Both api.md and labels.md says the query parameter is `label-selector`
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md

But it seems like it should be `labelSelector`
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1beta3.json
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json

**Comment by jlowdermilk** [comment]
That looks like a bug in the documentation. PR sent to fix.
