### ISSUE TITLE
How to implement such network plugin?

### ISSUE THREAD

**Issue by hjianhao** [GoogleCloudPlatform/kubernetes#10222]
Senario : 
We have a global ip address pool and IP address resource service.
We will create a bridge for every node.
When Pod is being created, we don't need to assign a IP automatically for the container, instead the plugin will allocate IP from IP address resource and create  a pair of veth and link the bridge and container, assign the IP address to the Pos(container).
After that we need to assign this IP to the Pod in kubernetes' registry for further access.
When Pod is down, we will return the IP to the IP Pool.

Something need to do 
1. start the container without link the container to docker0 and assign IP.
2. plugin may need to access etcd and api server. Is there any good method to get the address?
3. after create the network link for container, how to tell the kubernetes to bind the Pod to this IP?

**Comment by jlowdermilk** [comment]
It sounds like you actually want to use a [service](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md) to allocate an IP from the pool for pods. The type of plugin you are proposing sounds very similar to work that @thockin is doing with allocating service IPs from a pool where the implementation is cloud-provider specific. @lavalamp may also be able to point you in the right direction.

**Comment by lavalamp** [comment]
Our current stack allocates a CIDR to each node, and then the node allocates pod IPs from that. So I think this will require changes to kubelet and/or docker. @dchen1107

**Comment by hjianhao** [comment]
Our scenaio is :
1. We want to treat the containers as a lightweight VM.
2. We run the enterprise application on the containers, this application based on VAS and must use the WS-AT protocol to support transactions acroos hosts. 
3. So we must let the container had it's own IP and hostname(because of the damn WS-AT), and container can talk to other containers and VMs(legacy applications still runs on VMs).
4. And we need to assign the IP from IP pool(both for VM and Container) to the pod. 
5. container can access other containers and VMs by hostname.

I found it's hard to customize the kubernetes to meet our requirements for our PaaS platform. The only thing I see now is use the network plugin for kubelet, but still feel hard to start. Is there any good idea? It's very common scenario in enterprise IT application development and depolyment. :) @lavalamp  @thockin @dchen1107 @jlowdermilk

**Comment by uruddarraju** [comment]
@hjianhao This is a sane implementation definitely. We do similar stuff at ebay where our POD ips are directly routable. This is not true in most of the public clouds and hence kubernetes has a design of the LBs around the minion IPs and not the pod IPs themselves.

But as @lavalamp pointed out, this is entirely, clouprovider specific. What we did was change the CreateTCPLoadbalancer function in out cloudprovider to query the apiserver for all the pods behind the service (get all endpoints) and create a tcp loadbalancer with these IPs and it worked great for us. Moreover, to keep the pool updated when there is a change in the endpoint list for the Service, you will have to make changes to the endpointcontroller or define a new controller to watch on these changes.

And in regards to assigning an IP tot he pod, you can assign each minion a cidr space and split the cidr space to give a part of it to the docker daemon. And the other part can be used for the VM itself. This shouldn't be a problem as long as you are private IP spaces on overlays.

**Comment by thockin** [comment]
The biggest problem I see in this is that Docker's bridge assumes a prefix, and all container IPs must be "behind" that prefix.  That said, some BGP-based solutions (e.g. Calico) have emerged, which might help you.  Sadly, Docker's network plugins are not ready for prime time, and that sort of limits what we can really do in our own Plugins, for now.  for example, I can not report a different IP through `docker inspect`.

This has been a few weeks, so I am going to close it, but please let me know if there's more guidance I can offer.
