### ISSUE TITLE
Flaky e2e test: Service_endpoints_latency_should_not_be_very_high fails 70% of the time

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#10248]
@lavalamp This is still failing ~70% of the time. I'll open a separate issue to track fixing this.

Example Jenkins link: 
job/kubernetes-e2e-gce-flaky/1162/testReport/(root)/Kubernetes%20e2e%20suite/Service_endpoints_latency_should_not_be_very_high/history/

**Comment by quinton-hoole** [comment]
See also #9592

**Comment by lavalamp** [comment]
Yes, I know how to fix it and have a ton of code locally, but I'm busy fixing the proxy.

**Comment by timothysc** [comment]
re: #10348, it pretty much always fails for us.

**Comment by zmerlynn** [comment]
We just had 4 GCE runs in a row fail on this test.

**Comment by zmerlynn** [comment]
(I would be more concerned, but gke-ci racked up a green blob in the middle, so hey.)
