### ISSUE TITLE
unresponsive server with guestbook example/vagrant

### ISSUE THREAD

**Issue by PeterLamar** [GoogleCloudPlatform/kubernetes#10250]
Following the current vagrant path with 19.3. I understand the pods should be reachable inside the vagrant boxes?

PETLAMAR-M-D113:kubernetes petlamar$ ./cluster/kubectl.sh get pods
NAME                 READY     REASON    RESTARTS   AGE
frontend-0pqjg       1/1       Running   0          24m
frontend-an48j       1/1       Running   0          24m
frontend-r4x1f       1/1       Running   0          24m
kube-dns-v3-g1be5    2/3       Running   4          33m
redis-master-hfyql   1/1       Running   0          26m
redis-slave-3rhvb    1/1       Running   0          24m
redis-slave-a34tq    1/1       Running   0          24m
PETLAMAR-M-D113:kubernetes petlamar$ vagrant ssh master
Last login: Tue Jun 23 19:01:51 2015 from 10.0.2.2
[vagrant@kubernetes-master ~]$ kubectl get services
NAME           LABELS                                                                           SELECTOR            IP(S)           PORT(S)
frontend       name=frontend                                                                    name=frontend       10.247.129.25   80/TCP
kube-dns       k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns    10.247.0.10     53/UDP
                                                                                                                                    53/TCP
kubernetes     component=apiserver,provider=kubernetes                                          <none>              10.247.0.1      443/TCP
redis-master   name=redis-master                                                                name=redis-master   10.247.23.200   6379/TCP
redis-slave    name=redis-slave                                                                 name=redis-slave    10.247.43.123   6379/TCP
[vagrant@kubernetes-master ~]$ curl 10.247.129.25:80
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Notification: Gateway Timeout</title>
<style type="text/css">

</style>
</head>

<body>

<h1>This Page Cannot Be Displayed</h1>
<hr>

<p>
The system cannot communicate with the external server (&nbsp;10.247.129.25&nbsp;).
The Internet server may be busy, may be permanently down, or may be
unreachable because of network problems.
</p>

<p>
Please check the spelling of the Internet address entered.
If it is correct, try this request later.
</p>

<p>
If you have questions, or feel this is an error, please contact
your organization's network administrator 
and provide the codes shown below.
</p>

<hr>
<table>
  <tr valign="top">
    <td valign="top" width="10%">Notification&nbsp;codes:&nbsp;</td>
    <td valign="top" class="code" width="90%">(1, GATEWAY_TIMEOUT, 10.247.129.25)</td>
  </tr>
</table>

</body>
</html>

**Comment by alexanderguzhva** [comment]
well, according to my experience, they were never available inside vagrant boxes

**Comment by PeterLamar** [comment]
In earlier versions, I could go 'inside' the cluster and curl the service to verify it was working. How does one do this on vagrant currently? The goal here is to verify the guestbook works with the latest vagrant up.

**Comment by derekwaynecarr** [comment]
You can create the service for your frontend.

And you can then SSH into any minion and curl the internal service ip.

I am fixing some SkyDNS issues today on Vagrant setup, but will round back on this issue later today with full set of steps (and probably look to update the documentation).

**Comment by PeterLamar** [comment]
Indeed, I was SSH into the minion and curling the internal service ip. It would be worth adding that to the docs as a trouble shooting option and I am happy to create the pull request. 

In this particular case, that wasn't working and I suspect it was due to a separate issue. You just verified that these steps still should work which is good to know.

**Comment by derekwaynecarr** [comment]
You would have needed https://github.com/GoogleCloudPlatform/kubernetes/pull/10562

I am now investigating this issue relative to that PR to see if there are any other issues.

**Comment by derekwaynecarr** [comment]
Ok, I ran through the guestbook example, and verified that with #10562, I am able to curl the service ip address for the frontend from any minion in the cluster and get a response.

**Comment by swti6690** [comment]
Hacking the Internet link of the collective computers in Colleges & increase the absolute reach of internet with occupied velocity. 

http://www.hackingaccount.com/how-to-hack-internet-server-provider/
