### ISSUE TITLE
Update heapster to use v1.0 API version

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#10255]
cc @dchen1107. This is required for v1.0 I guess.

**Comment by thockin** [comment]
Estimate the work?  Who is available and has context to work on this?

**Comment by vishh** [comment]
Heapster uses v1beta3 as of now. So the switch should be straight forward. I will assign this to myself for now.

**Comment by vishh** [comment]
This is fixed in heapster v0.15.0 release.
