### ISSUE TITLE
Set resource limits on Heapster

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#10256]
#5880 provides a resource profile for heapster.
Heapster containers have to be restricted to 0.5 CPU cores and 2GiB of memory, based on the resource usage patterns in a loaded 100 node cluster.

cc @dchen1107 @saad-ali

**Comment by dchen1107** [comment]
I already started to do it. assigned it to me. :-)

**Comment by dchen1107** [comment]
@vishh according to @saad-ali 's report, the peak memory usage of heapster is 2.4~2.5 GiB, why set to 2GiB?

**Comment by vishh** [comment]
2.5GB was with a lot of containers (~10000). Setting limits to 2.5GB sgtm
though!
