### ISSUE TITLE
implement "kubectl get ... -o wide"

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#10262]
@bprashanth ran into a scenario where the scheduler was putting all the pods onto the same node. A user would be very unlikely to notice this kind of thing now that we took hostname out of the output of "kubectl get pods." I think we should put it back in. To keep the length under control, we can either truncate it to a fixed length or (clever idea from @lavalamp) have kubectl compute the part that is the same across all entries that would be returned, and only print the part of the other part of the hostname (the part that varies).

@dchen1107 @bgrant0607 @jlowdermilk

**Comment by bprashanth** [comment]
or maybe get nodes can show the count of pods

**Comment by brendandburns** [comment]
I've definitely had requests to have a kubectl way to list the pods (and resources consumed) for each node.

This is low risk, and easy to do, so I think it's legit for v1.0.

**Comment by bgrant0607** [comment]
describe nodes should list the pods, or at least a count and resources reserved, as discussed in #9356

**Comment by bgrant0607** [comment]
get nodes could show the pod count if we put that in PodStatus in the API.

**Comment by davidopp** [comment]
I don't think "describe nodes" or even "describe pods" is adequate. Many users are probably going to use "get pods" and not think to try anything else. I don't think this will make "get pods" laughably wide as long as we truncate the node name in a sensible way.

**Comment by thockin** [comment]
Is node name the most important field that got cut?  I'm not sure of that.

**Comment by bgrant0607** [comment]
By default, node name should not be in get pods output. That violates separation of concerns. We don't want users to think about the nodes, in general. That's a cluster admin concern. It can be in describe pods and we could list/count pods in describe nodes. Or, you could use `-o template` or `-o json | jq` to print whatever fields you like.

We could maybe add a verbose flag of some kind to print wide columnar output, but that would be a bigger change.

**Comment by bprashanth** [comment]
>I've definitely had requests to have a kubectl way to list the pods (and resources consumed) for each node.

a describe nodes without any argument would be cool, one of my most used bash_rc functions shows pods/services per node and health.

**Comment by thockin** [comment]
Yeah, I really want get -o wide to give me the old view (or something like
it)

**Comment by bgrant0607** [comment]
cc @ghodss @andronat

**Comment by davidopp** [comment]
We discussed and came up with a compromise (which apparently was the plan to do eventually anyway) of adding "-o wide" that would print hostname and perhaps other stuff as well. @bgrant0607 pointed out we should make "-o wide" work for all the commands/objects (even if it gives you an identical output to the default for most commands/objects). I'll re-title the issue appropriately. Also, @JanetKuo was interested in working on this.

**Comment by davidopp** [comment]
> make "-o wide" work for all the commands/objects 

I just meant all objects. I think the idea was that we would only have -o wide for "get" not for things like "describe" (but if I misunderstood, I'm sure someone will correct me).

**Comment by bgrant0607** [comment]
Past discussion was in #7843

**Comment by JanetKuo** [comment]
Discussed with @bgrant0607 and decided to start with adding one more column for `get pods -o wide`, which is `NODE` (NodeName in API); `get services -o wide` will just show default columns. 

We may add some more columns later, such as ClusterIP, SessionAffinity, etc.
