### ISSUE TITLE
Time: Replacing a dead container with a new one

### ISSUE THREAD

**Issue by adyanthaya17** [GoogleCloudPlatform/kubernetes#10280]
Hi, 
When I stop a pod from working a new pod gets created instantly. Can anyone be kind enough to point out to me where I can decrease the timing if its possible? Changing the time in seconds while a new pod gets created.

Thank you.

**Comment by thockin** [comment]
You want the system to work slower?  What are you actually trying to
achieve?

**Comment by bgrant0607** [comment]
You can prevent restarts by setting pod.spec.restartPolicy to "Never".

How are you stopping the container/pod?

**Comment by adyanthaya17** [comment]
@bgrant0607 To stop the container I'm using the following command:
$ kubectl stop POD update-demo-nautilus.

@thockin Yes, I want the system to run slower as in ten seconds slower so that I can show the failed pod and demonstrate the new pod taking it's place.

**Comment by thockin** [comment]
I see.  We don't have a "run slower mode".  But each pod has a different
name and UID - is that enough?

**Comment by adyanthaya17** [comment]
I did observer that when I ran 'kubectl get pods' which gave different name and IP's that were assigned. That should be sufficient for now. Thank you.
