### ISSUE TITLE
Load balancer behavior changed in v1 api

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#10291]
This is from a user report:

> The v1 k8s API seems to break the existing load balancer behavior, which makes it difficult to go forward with upgrading the cluster.  It ties to closely to GCE load balancers, and then once they're created you can't change the IP of the LB, which sucks because I want to use one static IP for our LBs then switch the forwarding destinations when the new cluster is up and ready.  I have to use the deprecated API to support this workflow still.

@thockin @bgrant0607 @brendandburns

**Comment by juntagabor** [comment]
I share the sentiment: #10290

**Comment by thockin** [comment]
I don't have contact info for the original poster, but #10290 explains this, #10323 is specifically about LBs using specific IPs.  I don't see this getting fixed for 1.0.
