### ISSUE TITLE
`kubectl describe` docs: explain what happens if the object doesn't exist

### ISSUE THREAD

**Issue by DreadPirateShawn** [GoogleCloudPlatform/kubernetes#10299]
In kube-apiserver.INFO, I see a failed API call being attempted roughly every second:

```
kube-apiserver.INFO:I0624 15:26:22.970228    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (1.662407ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45055]
kube-apiserver.INFO:I0624 15:26:24.262562    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (1.80702ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45057]
kube-apiserver.INFO:I0624 15:26:25.558359    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (1.764591ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45064]
kube-apiserver.INFO:I0624 15:26:25.566240    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything-1jq7j: (2.054047ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45064]
kube-apiserver.INFO:I0624 15:26:26.855882    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (2.237989ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45066]
kube-apiserver.INFO:I0624 15:26:28.151144    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (1.868889ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45068]
kube-apiserver.INFO:I0624 15:26:29.445528    3508 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (1.792321ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:45070]
```

Note that legit endpoints, eg "/api/v1/namespaces/ns-mything/pods/mything-1jq7j", are also in the mix, and those are successful. Also note that many other endpoints are being checked, all successfully -- the specific endpoint is the only one returning a 404.

That invalid endpoint indeed returns 404:

```
$ curl -v http://10.0.0.2:8080/api/v1/namespaces/ns-mything/pods/mything
> GET /api/v1/namespaces/ns-mything/pods/mything HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: 10.0.0.2:8080
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Wed, 24 Jun 2015 15:47:21 GMT
< Content-Length: 233
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods \"mything\" not found",
  "reason": "NotFound",
  "details": {
    "name": "mything",
    "kind": "pods"
  },
  "code": 404
}
```

The problem is that "mything" is not a pod -- rather, "mything-1jq7j" and "mything-rdd7e" are pods, "mything" is just the common base name.

```
$ kubectl --server=10.0.0.2:8080 --namespace=ns-mything get pods
NAME            READY     REASON    RESTARTS   AGE
mything-1jq7j   1/1       Running   0          17h
mything-rdd7e   1/1       Running   0          17h

kubectl --server=10.0.0.2:8080 --namespace=ns-mything get rc
CONTROLLER  CONTAINER(S)   IMAGE(S)                                                                SELECTOR       REPLICAS
mything     mything        dev.foo.com:5000/foo/mything:314159a10cee8edd3059d0fce4036c72c2527392   name=mything   2
```

My rc/pod config:

```
{
  "apiVersion": "v1",
  "kind": "ReplicationController",
  "metadata": {
    "name": "mything",
    "namespace": "ns-mything",
    "labels": {
      "name": "mything"
    }
  },
  "spec": {
    "replicas": 2,
    "selector": {
      "name": "mything"
    },
    "template": {
      "metadata": {
        "labels": {
          "name": "mything"
        }
      },
      "spec": {
        "containers": [{
          "name": "mything",
          "image": "dev.foo.com:5000/foo/mything:314159a10cee8edd3059d0fce4036c72c2527392",
          "ports": [],
          "env": [
            {"name": "FOO", "value": "bar"}
          ]
        }]
      }
    }
  }
}
```

Is this a wayward API call / bug in kubernetes, or an indication that I've missed something in my setup?

**Comment by mbforbes** [comment]
@davidopp can anyone on master team triage this?

**Comment by davidopp** [comment]
@lavalamp

**Comment by lavalamp** [comment]
The user agent suggests that the calls are coming from a "kubectl/v0.19.3". Any chance it's something you left running in another tab?

**Comment by DreadPirateShawn** [comment]
OH! Good grief, you are absolutely correct. Specifically `watch -n1 'kubectl --server=10.0.0.2:8080 --namespace=ns-mything get pods mything'`

Knowing that... should a seemingly-valid "describe pods" call be generating 404 errors in the logs? Granted, they're info-level logs, not warning- or error-level, but they still appear concerning to someone trying to vet their setup for anything that may be out of whack.

It looks like this command:
```
kubectl --server=10.0.0.2:8080 --namespace=ns-mything get pods mything
```
...generates these URL hits:
```
I0625 16:54:53.069365   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything: (1.496561ms) 404 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.074368   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods: (2.607558ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.078425   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything-1jq7j: (2.017762ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.082366   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/events?fieldSelector=involvedObject.namespace%3Dns-mything%2CinvolvedObject.uid%3D09cd418d-19f6-11e5-b231-00505629c58f%2CinvolvedObject.name%3Dmything-1jq7j: (1.494445ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.084788   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/replicationcontrollers: (1.768382ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.089914   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/pods/mything-rdd7e: (2.053713ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.093735   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/events?fieldSelector=involvedObject.name%3Dmything-rdd7e%2CinvolvedObject.namespace%3Dns-mything%2CinvolvedObject.uid%3D09cd139d-19f6-11e5-b231-00505629c58f: (1.606795ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
I0625 16:54:53.096332   14428 handlers.go:135] GET /api/v1/namespaces/ns-mything/replicationcontrollers: (1.949623ms) 200 [[kubectl/v0.19.3 (linux/amd64) kubernetes/3103c8c] 10.0.0.2:52160]
```

However, there's doesn't seem to be a way to avoid triggering the 404 call... I tried the `--selector` flag that "get pods" supports, but "describe pods" doesn't support the same:

```
$ kubectl --server=10.0.0.2:8080 --namespace=ns-mything get pods --selector=name=mything
NAME            READY     REASON    RESTARTS   AGE
mything-1jq7j   1/1       Running   0          1d
mything-rdd7e   1/1       Running   0          1d
$ kubectl --server=10.0.0.2:8080 --namespace=ns-mything describe pods --selector=name=mything
Error: unknown flag: --selector
```

The `describe pods --help` options didn't seem to show any alternative flags, either.

Should we split this into a separate ticket which focuses on the "get" vs "describe" flag disparity and resulting 404 noise in the logs? Or is that by design? Hardly vital, but it seems like it would be a good idea to avoid generating what appears to be an error in the logs, so that others don't dig into debugging something that isn't actually a bug.

**Comment by lavalamp** [comment]
If you ask for a non-existent thing, you'll see 404 in the logs; that's how the server communicates "this thing doesn't exist", so that's by design.

You might try ```kubectl describe rc mything``` to get the info you're looking for.

I think `describe` doesn't work on multiple objects, which is why it wouldn't accept a label selector.

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9705 added support for --selector to kubectl describe

**Comment by DreadPirateShawn** [comment]
The problem there is that `kubectl describe rc mything` doesn't give the same amount of information as `describe pods`:

```
kubectl --server=10.0.0.2:8080 --namespace=ns-mything describe rc mything
[removed noise]
Name:		mything
Image(s):	dev.foo.com:5000/foo/mything:314159a10cee8edd3059d0fce4036c72c2527392
Selector:	name=mything
Labels:		name=mything
Replicas:	2 current / 2 desired
Pods Status:	1 Running / 1 Waiting / 0 Succeeded / 0 Failed
No events.
```

vs

```
kubectl --server=10.0.0.2:8080 --namespace=ns-mything describe pods mything
[removed noise]
Name:				mything-1jq7j
Image(s):			dev.foo.com:5000/foo/mything:314159a10cee8edd3059d0fce4036c72c2527392
Node:				/10.0.0.4
Labels:				name=mything
Status:				Running
Replication Controllers:	mything (2/2 replicas created)
Containers:
  awsdriver:
    Image:		dev.foo.com:5000/foo/mything:314159a10cee8edd3059d0fce4036c72c2527392
    State:		Running
      Started:		Wed, 24 Jun 2015 17:36:05 +0000
    Ready:		True
    Restart Count:	1
Conditions:
  Type		Status
  Ready 	True 
No events.
[removed noise]
Name:				mything-rdd7e
Image(s):			dev.foo.com:5000/foo/mything:314159a10cee8edd3059d0fce4036c72c2527392
Node:				/
Labels:				name=mything
Status:				Pending
Replication Controllers:	mything (2/2 replicas created)
Containers:
No events.
```

Interestingly, `describe pods myth` also describes my pods -- it looks like `describe pods` fetches info for any pods which **start with** the given string (great), in addition to attempting to fetch info for the exact string match (which generates the 404 error). This creates the illusion that the 2 "mything*" pods are deliberately being fetched with no troubles, while a 3rd nonexistent "mything" pod is attempted without an obvious reason.

If this is a deliberate feature, it might be worth tuning the API calls to avoid the 404 call... that is, the list of nodes is already being checked, in order to find other nodes which start with the given string... and if those are present, then maybe it could only fetch info for those pods which exist, rather than always fetching for an exact name match too. (Or if it's not a deliberate feature, then it might be worth removing this behavior entirely, since the `--selector` flag seems to be the newly-added official way to describe multiple pods at once.)

(Speaking of which -- the addition of `--selector` support is great news! Thanks for the heads up!)

**Comment by lavalamp** [comment]
It may only do the list at all if getting the specified name returns an error-- I'd have to check. In that case we'd be choosing between always doing a list and then a get, or always doing a get, and maybe doing a list. Optimizing the common case to be low-latency is worth it; optimizing to reduce 404 return codes is not really a consideration, though, since 404 is the intended way for the server to communicate that something doesn't exist.

**Comment by DreadPirateShawn** [comment]
Fair enough, I don't disagree. :-) Really I think I'm just looking for a way to convey this to others down the road -- either by dodging the 404, or perhaps by updating the "describe pods [NAME]" documentation to explain that if "NAME" doesn't exist exactly, then it'll fail via 404 in the logs, and will return any "NAME*" pods instead... also the perfect place to advise using `--selector` instead... otherwise it's a red herring for people who are debugging a kubernetes configuration in general, who might wonder (as I did) why the pod "NAME" is being attempted despite (what seemed to be) simply monitoring "NAME*" pods.

That being said, if you think it'll just add unnecessary noise to the docs, I completely understand and defer to you -- besides, I think we've said "404" enough in this ticket to make it easy for someone to find if they're searching for known things to cause a 404 error. :-P Feel free to close the ticket if there's no doc changes that you wish to track.

Thanks again!

**Comment by lavalamp** [comment]
I agree that the docs can & should be improved :) I'll update the title here.

__Action item: ```kubectl describe``` docs should explain what will happen if the object doesn't exist (namely, that it will then look for objects with names that begin with the requested name).__
