### ISSUE TITLE
[cluster/] migrate eparis/kubernetes-ansible to upstream.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#10293]
We can do this many ways.

1) add to vagrant setup so that we have a salt-free impl.   (i.e. create ./cluster/ansible/)
2) update contrib/ansible/ 

I think (1) is the route @eparis might be leaning to (the OS could be an option you send). 

seems ok that the cluster/ from ansible is not the exact same as the salt clusters that are created.

**Comment by eparis** [comment]
I'm going to go ahead and close this.  We have ansible in contrib/ansible.  In fact it works better than the salt stuff in some ways!

**Comment by jayunit100** [comment]
Yup! Sorry this was obsolete...
