### ISSUE TITLE
More helpful error when using unsupported api version

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#10318]
```
$ cat pod.yaml 
apiVersion: v2
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: gcr.io/google_containers/pause
$ kubectl create -f pod.yaml
error: no objects passed to create
$ kubectl create --validate -f pod.yaml
error validating data: the server could not find the requested resource
```
These are not helpful error messages.  We can do better, especially since we have people who are going to be reading v1 examples and trying them on older clusters.

**Comment by erictune** [comment]
Same unhelpful errors if I try to create a v1beta1 resource on a server which only supports v1beta3 and v1.

**Comment by feihujiang** [comment]
Is there anyone to work on this? If not, I'd like to volunteer myself to do this work.

**Comment by Kielan** [comment]
I'm coming across a very similar situation with replication controller. Even if copy/pasting the exact example from the documentation. Seems the error reporting could be more helpful at least. 

https://cloud.google.com/container-engine/docs/replicationcontrollers/operations

**Comment by bgrant0607** [comment]
@feihujiang We'd certainly appreciate your help. I'm not aware of anyone working on this.

**Comment by feihujiang** [comment]
@bgrant0607 OK, I start to work on this.

**Comment by buley** [comment]
Sorry to be the  "use case" (aka dumb user) but I'm running into this error message and this is the only reference to it on Google. For other inbound searchers, any tips on how to move beyond it? I've tried different version slugs mentioned above to no avail.

    version: v1
    kind: Pod
    metadata:
      - name: cache
    spec:
      containers:
        - name: shared
          image: gcr.io/media-production/shared
          imagePullPolicy: Always
        - name: varnish
          image: gcr.io/media-production/varnish
          imagePullPolicy: Always
          ports:
            - containerPort: 6081
              hostPort: 6083
              protocol: TCP
            - containerPort: 6082
              hostPort: 6084
              protocol: TCP
        - name: memcached
          image: gcr.io/media-production/memcached
          imagePullPolicy: Always
          ports:
            - containerPort: 11212
              hostPort: 11211
              protocol: TCP
      volumes:
        - name: "www"
          hostPath:
            path: /srv/www
        - name: "logs"
          hostPath:
            path: /srv/logs
      dnsPolicy: Default
      restartPolicy: Always

**Comment by wojtek-t** [comment]
@erictune - since #10447 is now merged, can we close this issue?

**Comment by bgrant0607** [comment]
yes, thanks
