### ISSUE TITLE
`kubectl describe pod` should list the reason/message of the status

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#10324]
The reason/message is important when debugging why the pod is in the current non-running state. 

E.g., here is the output from `describe pod`, which only shows the status is failed without giving any explanation.
```
Name:				foo
Image(s):			ubuntu,ubuntu
Node:				e2e-test-yjhong-minion-y38q/
Labels:				<none>
Status:				Failed
IP:				
Replication Controllers:	<none>
Containers:
```

If you do `get pod foo -o json`, you can see the message/reason that explains the status.
```
    "status": {
        "phase": "Failed",
        "message": "Pod was active on the node longer than specified deadline",
        "reason": "DeadlineExceeded",
        "startTime": "2015-06-25T00:02:37Z"
    }
```

Sometimes a relevant event is recorded and shows up in the output of `describe pod`, but sometimes there is no such an event. We also cannot rely on events too much since they will be flushed after sometime. I think we should include the information in `describe pod`

**Comment by mbforbes** [comment]
@yujuhong feel free to pick a relevant priority when you open these--I'm just guessing.

**Comment by bgrant0607** [comment]
cc @andronat @ghodss

**Comment by dchen1107** [comment]
Will send pr shortly.
