### ISSUE TITLE
vendored docker deps are out of sync

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10333]
```
                {
                        "ImportPath": "github.com/docker/docker/pkg/jsonmessage",
                        "Comment": "v1.7.rc",
                        "Rev": "0cd6c05d8112e9246b734107d54e2855e3d5fec5"
                },
                {
                        "ImportPath": "github.com/docker/docker/pkg/mount",
                        "Comment": "v1.4.1-1714-ged66853",
                        "Rev": "ed6685369740035b0af9675bf9add52d0af7657b"
                },
```

We can not vendor two revs of the same repo.  Godep ops fail because the 1.4.* rev does not have jsonmessage.

**Comment by thockin** [comment]
@rjnagal This is what I was trying to fix before.

**Comment by dchen1107** [comment]
@thockin Here is what I am having at my branch which is sync-ed one hour ago. 

                {
                        "ImportPath": "github.com/docker/docker/pkg/jsonmessage",
                        "Comment": "v1.4.1-4045-g2b27fe1",
                        "Rev": "2b27fe17a1b3fb8472fde96d768fa70996adf201"
                },
                {
                        "ImportPath": "github.com/docker/docker/pkg/mount",
                        "Comment": "v1.4.1-4045-g2b27fe1",
                        "Rev": "2b27fe17a1b3fb8472fde96d768fa70996adf201"
                },

The problem you pointed out is fixed by @rjnagal  or we just break it again?

**Comment by dchen1107** [comment]
I just checked HEAD:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/Godeps/Godeps.json#L157

they are on the same revisions too.

**Comment by rjnagal** [comment]
this is what I fixed. All docker pkgs should be from "v1.4.1-4045-g2b27fe1"

**Comment by thockin** [comment]
oh, damn, I know what I did.  trap
