### ISSUE TITLE
Measure kubernetes addons resource usage

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#10335]
In #5880, We measure resource usage of heapster and other monitoring containers in a 100 node cluster with and without load. Based on that those container's container manifests (#10260,  #10334) are updated with proper resource limit. But we don't have measurements for dns, and kibana yet. 

cc/ @davidopp @brendandburns

**Comment by dchen1107** [comment]
cc/ @satnam6502 on bringing up 100-node scalability tests.

**Comment by wojtek-t** [comment]
@dchen1107 - we are already running 100-node scalability tests on Jenkins:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-scalability/
 Does it make sense to run tests you mentioned as part of it?

**Comment by saad-ali** [comment]
Here are the results from a 4 node cluster 200 pod run.

## Test Setup
* Cluster characteristics:
  * 4 nodes
  * `n1-standard-1 (1 vCPU, 3.75 GB memory)`
* Test duration: 24 hours total
  * 200 pods (in addition to default), with 2 containers each (total 400)
  * Container used was a small a statically-linked C program that just sleeps for 28 days with a container size of 877.6 kB.

## Results
### Memory

**SkyDNS Memory Usage**
* Memory usage rising over 24 hours, but remained below 3.1 MB.
![skydns_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441648/7978d64e-1f2e-11e5-8a81-4d6568bcac93.png)

**kube2sky Memory Usage** 
* Memory usage rising over 24 hours, but remained below 3.0 MB.
![kube2sky_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441674/9bd725d8-1f2e-11e5-8dbb-9b03052fc3c7.png)

**dns etcd Memory Usage** 
* Memory usage remained stable between 8-14 MB.
![dnsetcd_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441697/c3240ab6-1f2e-11e5-82c9-b1933c12881f.png)

**Kibana-Logging Memory Usage** 
* Memory usage steadily rising over 24 hours, but remained below 100 MB.
![kibanalogging_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441605/3fa4f4f2-1f2e-11e5-8e6e-13bb310a9472.png)

**Heapster Memory Usage** 
* Memory usage remained more or less stable below 150 MB.
![heapster_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441392/b469418c-1f2c-11e5-9453-a1692eaf4a9b.png)

**InfluxDB Memory Usage** 
* This was rather surprising, influxDB usage continued to grow over the course of 24 hours hitting 1.1 GB. This needs to be investigated further (is InfluxDB trying to hold everything in memory and not flushing to disk periodically?).
![influxdb_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441516/9adcc422-1f2d-11e5-9873-bd3dbd5fcf72.png)

**Fluentd/ElasticSearch Memory Usage**
* Also steadily rising over 24 hours, but remained below 100 MB.
![fluentd-elasticsearch_memusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441550/eddd9660-1f2d-11e5-9ac1-44ff624eafb1.png)

### CPU

**SkyDNS CPU Usage** 
![skydns_cpuusage_4node_200pods](https://cloud.githubusercontent.com/assets/10052848/8441795/82225814-1f2f-11e5-84c5-db609f13148c.png)

**kube2sky CPU Usage** 
![kube2sky_cpuusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441799/89814ca0-1f2f-11e5-809f-3381f6fe092d.png)

**dns etcd CPU Usage** 
![dnsetcd_cpuusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441803/8f349486-1f2f-11e5-970d-8c9ec954eb1d.png)

**Kibana-Logging CPU Usage** 
![kibanalogging_cpuusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441811/9828c634-1f2f-11e5-9f75-dfdd65c92152.png)

**Heapster CPU Usage** 
![heapster_cpuusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441817/9f613e54-1f2f-11e5-9fe5-394c693cf020.png)

**InfluxDB CPU Usage** 
![influxdb_cpuusage_4node_200pod](https://cloud.githubusercontent.com/assets/10052848/8441828/b6ca66d8-1f2f-11e5-8f5e-da57b5ac6b3f.png)

**Comment by saad-ali** [comment]
Here are the results from a 4 node with 0 additional pods ("no load").

## Test Setup
* Cluster characteristics:
  * 4 nodes
  * `n1-standard-1 (1 vCPU, 3.75 GB memory)`
* Test duration: 24 hours total
  * Only default kubernetes pods (no additional pods)
  * Container used was a small a statically-linked C program that just sleeps for 28 days with a container size of 877.6 kB.

## Results
### Memory

**SkyDNS Memory Usage**
* Memory usage rising over 24 hours to around 3.1 MB with spikes up to 4.3 MB.
![skydns_memusage_4nodes_noload](https://cloud.githubusercontent.com/assets/10052848/8441992/c9959a66-1f30-11e5-8fa7-d2180742e651.png)

**kube2sky Memory Usage** 
* Memory usage rising over 24 hours, but remained below 3.2 MB.
![kube2sky_memusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8442022/0a0fb2ca-1f31-11e5-8acd-baddaf77aa2c.png)

**dns etcd Memory Usage** 
* Memory usage remained stable between 8-14 MB.
![dnsetcd_memusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8442046/2520466a-1f31-11e5-963d-829ecd1035fe.png)

**Kibana-Logging Memory Usage** 
* Memory usage steadily rising over 24 hours to nearly 110 MB.
![kibana_memusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8442056/30f4a24c-1f31-11e5-9c7b-66a1de49c5ab.png)

### CPU

**SkyDNS CPU Usage** 
![skydns_cpuusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8442093/5f679a12-1f31-11e5-9a79-33f632005050.png)

**kube2sky CPU Usage** 
![kube2sky_cpuusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8442088/5c44f5dc-1f31-11e5-871e-4c42f562893c.png)

**dns etcd CPU Usage** 
![dnsetcd_cpuusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8442085/577b10fe-1f31-11e5-8b2e-a22936655841.png)

**Kibana-Logging CPU Usage** 
![kibana_cpuusage_4nodes_noload](https://cloud.githubusercontent.com/assets/10052848/8442082/541ebd48-1f31-11e5-973c-7b2b1aea9d85.png)

**Comment by dchen1107** [comment]
@saad-ali and @vishh I did measurement last night over heapster, and found there are big increase of memory usage from 0.14.3 to 0.15.0

**Comment by saad-ali** [comment]
This is a follow up to the 4 node cluster 200 pod run, after 2 days.

## Test Setup
* Cluster characteristics:
  * 4 nodes
  * `n1-standard-1 (1 vCPU, 3.75 GB memory)`
* Test duration: 48 hours total
  * 200 pods (in addition to default), with 2 containers each (total 400)
  * Container used was a small a statically-linked C program that just sleeps for 28 days with a container size of 877.6 kB.

## Results
![4node_200pods_2days_1of2](https://cloud.githubusercontent.com/assets/10052848/8467728/7127880c-2017-11e5-8a8c-f573a80b6b7c.png)

**Comment by dchen1107** [comment]
@saad-ali Could please measure ui addons too?

**Comment by saad-ali** [comment]
@dchen1107 Yep, will do

**Comment by saad-ali** [comment]
Here are the initial results for the `kube-ui` container with no load.

## Test Setup
* Cluster characteristics:
  * 4 nodes
  * `n1-standard-1 (1 vCPU, 3.75 GB memory)`
* Test duration: 48 hours total
  * Default with no additional pods

## Results
![kubeui_memusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8505388/cb43bd06-2198-11e5-8a28-0c6d8c7bff2f.png)

![kubeui_cupusage_4node_noload](https://cloud.githubusercontent.com/assets/10052848/8505390/cdcafcd8-2198-11e5-94b8-9dfe0d350444.png)

Seems pretty light weight when not in use. Next I will add load to the cluster and leave the `kube-ui` web interface open.

**Comment by wojtek-t** [comment]
Since #10653 is merged - can we close this issue?

**Comment by dchen1107** [comment]
One last thing: kube-ui which requires resource limit was added lately. After that, we can close this one.

**Comment by thockin** [comment]
Who is doing this last one?  Saad?

**Comment by saad-ali** [comment]
Yep, I had a cluster running over the long weekend. I'll publish the remaining results for `kube-ui` with load shortly.

**Comment by saad-ali** [comment]
Here are the results for the `kube-ui` container with load.

## Test Setup
* Cluster characteristics:
  * 4 nodes
  * `n1-standard-1 (1 vCPU, 3.75 GB memory)`
* Test duration: 72 hours total
  * 200 pods with 2 containers each in addition to the default pods

## Results
![kubeui_memusage_4nodes_200pods](https://cloud.githubusercontent.com/assets/10052848/8529789/e9df85d4-23d1-11e5-9448-ce364d31baaf.png)

![kubeui_cpuusage_4node_200pods](https://cloud.githubusercontent.com/assets/10052848/8529791/ede2c146-23d1-11e5-87d2-318eeb37c44a.png)

**Comment by dchen1107** [comment]
All addons have default resource limit associated with. The document is addressed through #10779, and updating resource limit for addons is addressed through #7046. I am closing this issue now.
