### ISSUE TITLE
Provide access to kubectl without users needing to install it themselves, at least on GCP

### ISSUE THREAD

**Issue by jkingyens** [GoogleCloudPlatform/kubernetes#10337]
After spinning up a fresh GCE cluster, I found that when SSHing into individual instances that kubectl does not exist. I tried following the documentation for setting up kubectl using gcloud, but the gcloud that is already installed on the instances is out of date and conflicts with the documentation. 

Is there any way to update the GKE images to include the latest gcloud with kubectl already installed and authorized (via service accounts) to access the kubernetes API? Otherwise, I am having to manually authorize kubectl via service accounts / web tokens and am doing this manually for each instance.

**Comment by brendandburns** [comment]
kubectl is installed on the master afaik, if its not, that's a bug.

It's not installed on the workers by choice.  We could do it, I suppose, what is your use case for kubectl on the workers?

**Comment by jkingyens** [comment]
I don't have a specific use-case for the workers. Its just important that I remotely accessing kubectl on machines that don't have the tooling setup locally. How do I access the master via ssh on GKE? I just see worker nodes in my instance list.

**Comment by dchen1107** [comment]
cc/ @zmerlynn @roberthbailey 

This is a usability issue for our GKE customers.

**Comment by zmerlynn** [comment]
On the GKE Beta, we manage the masters. If you created the cluster on the command line, `kubectl` would just work. If not, you can use `gcloud beta container get-credentials <cluster>` to configure kubectl.

**Comment by roberthbailey** [comment]
Also note that kubectl isn't installed by default on GCE VMs. And even if you run `sudo gcloud components update kubectl` the binary will be dropped into `/usr/local/share/google/google-cloud-sdk/bin` which isn't on your default path. You can run the gcloud update command and then modify your path and at that point you will have kubectl on any gcloud VM. Once you've done that, running the get-credentials command that @zmerlynn suggested will create a local kubeconfig file that will allow you to send commands to the kubernetes apiserver. 

@zmerlynn -- do you know how kubectl gets installed on the master instances on GCE? Which version is it?

**Comment by jkingyens** [comment]
I was running into the issues that @roberthbailey mentioned when using the pre-installed gcloud to bootstrap the installation of kubectl. I couldn't find the kubectl command. I was also getting 401s back when trying to authorize credentials. The version of gcloud also seemed older than what the docs were assuming (the commands were out of date). I ended up installing a fresh copy of gcloud in my $HOME and got kubectl working. Credentials worked by getting a token via a web browser flow, but this all seemed very wrong if I wanted to automate this process.

**Comment by zmerlynn** [comment]
The `kubectl` installed in the normal OSS flow is the one built during the release, so it should always match the server version.

**Comment by roberthbailey** [comment]
@jkingyens - I tried to update the gcloud that was installed on my GKE node to add kubectl and hit a bunch of weird errors. I'm going to try on another node to see if I can reproduce, but I think in the mean time installing a fresh version seems like the best way to go. 

Re: Tokens, gcloud should grab a token from the service account attached to the GCE VM. Right now, all node VMs are created with compute read/write scope (which is unfortunate in general, but helpful in this case) which should allow you to query the GKE API and obtain authentication information for the master using the get-credentials call.

**Comment by alex-mohr** [comment]
I suspect we should do the following:
 * Make sure containerVM has a recent gcloud by default
 * Make sure kubectl is in the default path for that containerVM
 * Make sure that version of kubectl works with the v1 API regardless of master binary version without triggering the sanity check.

@thockin also mentioned driving cloud shell to get a more-recent gcloud and default to kubectl being installed?

**Comment by roberthbailey** [comment]
It's a trivial salt change to put the kubectl from the release onto the user's path on the nodes just like we do on the master (see #10590). I'm not sure if this is the best fix, but it works.

**Comment by thockin** [comment]
Cloud shell will include it in an upcoming release.

**Comment by bgrant0607** [comment]
@jkingyens You just want SOME VM/machine with the tools installed, but don't want to install them on your own host and don't want to create another VM?

**Comment by jkingyens** [comment]
Yes thats right. 


—

**Comment by bgrant0607** [comment]
@aalexand How often is gcloud updated in [developer shell](https://cloud.google.com/developer-shell/)?

**Comment by thockin** [comment]
kubectl is already deployed in cloud shell! They fixed it yesterday :)

finding the master auth info, well that's different.

**Comment by zmerlynn** [comment]
It actually works great on GKE. :)
```
zml@artful-fortress-786:~$ gcloud beta container clusters list
NAME             ZONE           MASTER_VERSION  MASTER_IP       MACHINE_TYPE   STATUS
generic-cluster  us-central1-f  0.19.3          104.197.20.105  n1-standard-1  RUNNING
zml@artful-fortress-786:~$ gcloud beta container get-credentials --cluster generic-cluster
Fetching cluster endpoint and auth data.
kubeconfig entry generated for generic-cluster. To switch context to the cluster, run
$ kubectl config use-context gke_artful-fortress-786_us-central1-f_generic-cluster
zml@artful-fortress-786:~$ kubectl get pods
POD                                                            IP           CONTAINER(S)            IMAGE(S)                                         HOST                             
                      LABELS                                                           STATUS    CREATED   MESSAGE
fluentd-cloud-logging-gke-generic-cluster-6183a884-node-90e2   10.212.0.2                                                                            gke-generic-cluster-6183a884-node
-90e2/10.240.179.38   <none>                                                           Running   5 days    
                                                                            fluentd-cloud-logging   gcr.io/google_containers/fluentd-gcp:1.6                                          
                                                                                       Running   5 days    last termination: exit code 0
[...]
```

**Comment by bgrant0607** [comment]
Sounds good enough for now.
