### ISSUE TITLE
pkg/api/resource isn't versioned

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#10338]
Does this matter? We import resource.Quantity into the various types.go but unless I'm misunderstanding, resource itself isn't versioned (except to the extent that in a future version of the API, you could use something called resource.Quantity_v2 or something, but I assume that's not what we had in mind).

@bgrant0607

**Comment by bgrant0607** [comment]
Quantity is a type, not a field name. We just need to ensure we don't change the behavior in a non-backward-compatible way for existing uses in the API. Incompatible behavior can be introduced into new API versions by whatever means we choose: new type name, new package name, constructor parameter, ...

The same applies to other custom types in the API, such as util.Time.

**Comment by bgrant0607** [comment]
Please close if that addresses your concern.
