### ISSUE TITLE
kubectl proxy command not completing

### ISSUE THREAD

**Issue by adyanthaya17** [GoogleCloudPlatform/kubernetes#10343]
When I run the below command:
$ kubectl proxy --www=examples/update-demo/local/
Starting to serve on localhost:8001

I have to make use of ctrl+c to come out as it looks like it's stuck. If I run the command again it tells bind address already in use. Does that mean it worked?

I'm trying use the update-demo from the examples here.

**Comment by brendandburns** [comment]
proxy runs a webserver.  it blocks permanently, you should open a web browser on http://localhost:8001/static/  while it is running.

and yes ctrl-c is the right way to exit.

your os is holding the listen port for a little time.  if you wait, you can re-run.
