### ISSUE TITLE
Heapster should use a service account for auth

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#10356]
Heapster currently uses a [system secret](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml#L46) to authenticate to the apiserver. This secret is generated in the [GCE-specific start up script](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L327) which means that folks who want to run heapster on other cloud providers must manually generate the secret for heapster to work. 

Heapster should instead use the service account (like we do for DNS) so that it works without any special configuration on all cloud providers. 

/cc @thockin

**Comment by roberthbailey** [comment]
@mikedanese

**Comment by thockin** [comment]
I'm testing new DNS to confirm it all works as expected.  If so, heapster
can follow suite.

**Comment by roberthbailey** [comment]
That's exactly what I was hoping. I'd be thrilled if we could reduce / remove the GCE-specific service accounts we create in our startup script.

**Comment by mikedanese** [comment]
Heapster needs to version bump their kubernetes dependency and use the InClusterConfig (which currently it doesn't). I can send a PR for this. After that, we need to rebuild the heapster image and version bump the hepaster addon. cc @vishh

**Comment by vishh** [comment]
Removing or making GCE specific accounts optional will be very helpful.

**Comment by vishh** [comment]
@mikedanese: Do post a PR. I can make a release soon after.

**Comment by mikedanese** [comment]
GoogleCloudPlatform/heapster#371

**Comment by mikedanese** [comment]
#10369

**Comment by erictune** [comment]
+1 to removing system secrets.  Sorry for creating them and not just
waiting for service accounts.
