### ISSUE TITLE
Spell out references to GKE and GCE

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#10354]
Replacing all instances of GKE or GCE in the documentation with full product names: Google Container Engine or Google Compute Engine. *Note: this is also a GKE/GCE guideline.*

This is also based on customer feedback: "got confused with the difference between gce and gke"

**Comment by mbforbes** [comment]
Out of curiosity, what's the data behind this? A single customer?

Once you know what GCE and GKE are, visually diffing "Compute" and "Container" is harder than "C" and "K," in my opinion.

**Comment by RichieEscarez** [comment]
Yeah, one customer that im aware of. Then adding on top of that the branding guidelines "official rules (signed off by marketing)".

I agree and think the real challenge is when gke and gce show up in a single document.

Ultimately, this is a consistency item and i think if and where we do use gke or gce in any particular document, it should be capitalized and the first reference should be defined "Google Container Engine (GKE)" and then can use GKE thereafter.
