### ISSUE TITLE
kubelet does not recover from machine reboot

### ISSUE THREAD

**Issue by timstclair** [GoogleCloudPlatform/kubernetes#10368]
I started a cluster running on GCE last week, using `go run hack/e2e.go -build -up`. Today I noticed today that both of my minion nodes were stuck in the NotReady state:
```
$ kubectl get nodes
NAME                           LABELS                                                STATUS
e2e-test-stclair-minion-cu9a   kubernetes.io/hostname=e2e-test-stclair-minion-cu9a   NotReady
e2e-test-stclair-minion-i5b9   kubernetes.io/hostname=e2e-test-stclair-minion-i5b9   NotReady
```
Inspecting the logs yields the same error message over and over again:
```
stclair@e2e-test-stclair-minion-cu9a:~$ tail /var/log/kubelet.log      
W0625 21:18:55.371135    2928 request.go:292] field selector: v1 - pods - spec.host - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
E0625 21:18:55.371813    2928 reflector.go:136] Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
E0625 21:18:55.371940    2928 reflector.go:136] Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
E0625 21:18:55.737900    2928 kubelet.go:1591] error getting node: node e2e-test-stclair-minion-cu9a not found
E0625 21:18:55.748663    2928 kubelet.go:1212] Failed creating a mirror pod "fluentd-elasticsearch-e2e-test-stclair-minion-cu9a_default": the server has asked for the client to provide credentials (post pods)
E0625 21:18:56.202222    2928 reflector.go:136] Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
W0625 21:18:56.371997    2928 request.go:292] field selector: v1 - nodes - metadata.name - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
W0625 21:18:56.372199    2928 request.go:292] field selector: v1 - pods - spec.host - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
E0625 21:18:56.372828    2928 reflector.go:136] Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
E0625 21:18:56.373378    2928 reflector.go:136] Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
```
Same with the proxy:
```
stclair@e2e-test-stclair-minion-cu9a:~$ tail -n 5 /var/log/kube-proxy.log 
E0625 21:18:44.957584    2968 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
E0625 21:19:31.023914    2968 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
E0625 21:20:08.662204    2968 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
E0625 21:20:43.884667    2968 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
E0625 21:21:15.108205    2968 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
```

Version:
```
$ kubectl describe nodes e2e-test-stclair-minion-cu9a
W0625 14:05:10.463312   16838 request.go:291] field selector: v1beta3 - events - involvedObject.uid - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
W0625 14:05:10.463428   16838 request.go:291] field selector: v1beta3 - events - involvedObject.name - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
W0625 14:05:10.463441   16838 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - : need to check if this is versioned correctly.
W0625 14:05:10.463451   16838 request.go:291] field selector: v1beta3 - events - involvedObject.kind - Node: need to check if this is versioned correctly.
Name:			e2e-test-stclair-minion-cu9a
Labels:			kubernetes.io/hostname=e2e-test-stclair-minion-cu9a
CreationTimestamp:	Thu, 18 Jun 2015 18:10:36 -0700
Conditions:
  Type		Status		LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	Unknown 	Fri, 19 Jun 2015 13:52:08 -0700 	Fri, 19 Jun 2015 13:52:53 -0700 	Kubelet stopped posting node status. 	
Addresses:	10.240.179.67,146.148.78.88
Capacity:
 cpu:		1
 memory:	3800808Ki
 pods:		100
Version:
 Kernel Version:		3.16.0-0.bpo.4-amd64
 OS Image:			Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:	docker://1.6.2
 Kubelet Version:		v0.19.0-634-g2fab19a748fabb-dirty
 Kube-Proxy Version:		v0.19.0-634-g2fab19a748fabb-dirty
PodCIDR:			10.245.1.0/24
ExternalID:			1522119118968509696
Pods:				(0 in total)
No events.
```

**Comment by mbforbes** [comment]
+cc @roberthbailey @lavalamp

**Comment by lavalamp** [comment]
Hm, that's weird. I don't think it's happening in our soak clusters. Can you tell from the logs exactly when it broke?

**Comment by timstclair** [comment]
Unfortunately the kubelet logs only appear to go back to 6/20, but the last heartbeat was on 6/19. I'll see if I can reproduce it in another cluster and catch it earlier, but let me know if there are any other logs I should be looking for (other than /var/log/kubelet.log.{1..5})

**Comment by roberthbailey** [comment]
Have the kubelet or kube-proxy been restarted? Can you look at the credentials that they are providing (kubeconfig for the kubelet and bearer token for the kube-proxy) and use them to try and access the apiserver manually? You can also check the apiserver configuration to see what bearer tokens it accepts. 

I'd be happy to poke at the cluster a bit if you want to give me access to your project?

**Comment by timstclair** [comment]
Would you mind elaborating on how I can find the kubeconfig (do you mean ~/.kube/config?) and the bearer token, and how to use them to manually access the API server?

I also gave you (@roberthbailey) access to my GCE project (stclair-k8s-ext)

**Comment by timstclair** [comment]
Hmm, if I look in `/var/lib/kube{let,-proxy}/kubeconfig`, I don't see any credentials:
```
root@e2e-test-stclair-minion-cu9a:~# cat /var/lib/kubelet/kubeconfig 
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    token: 
clusters:
- name: local
  cluster:
     insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
root@e2e-test-stclair-minion-cu9a:~# cat /var/lib/kube-proxy/kubeconfig  
apiVersion: v1
kind: Config
users:
- name: kube-proxy
  user:
    token: 
clusters:
- name: local
  cluster:
     insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: kube-proxy
  name: service-account-context
current-context: service-account-context
```

**Comment by timstclair** [comment]
Looking into this more, I believe this may have been the result of actually running the e2e tests on this cluster (via `go run hack/e2e.go -test`). I ran the tests on another cluster, and it was left with one node in a similar state (kubeconfig similar to above), and the other node running. Is this WAI?

**Comment by timstclair** [comment]
I'm going to write this off as caused by the e2e tests, and not normal functioning.

Sorry for the false alarm.

**Comment by lavalamp** [comment]
Is it caused by the resize nodes or restart test? If so, it's probably an
actual system problem that the test is just exposing.

**Comment by timstclair** [comment]
I actually had quite a few test failures, which I assumed was due to some local configuration error:
https://drive.google.com/a/google.com/file/d/0B4C6q5N3BbNLNjBaVk5xejZoUW8/view?usp=sharing

Is there a way to run individual e2e tests to determine which was causing this issue?

**Comment by roberthbailey** [comment]
Check out https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#flag-options. You can use the focus argument to select individual tests after launching your e2e cluster.

**Comment by timstclair** [comment]
Thanks Robert, that was exactly what I needed. I was able to reproduce this running (only) the Restart test: `go run hack/e2e.go -v -test --test_args="--ginkgo.focus=Restart"`

I've uploaded the test output and the kubelet & kube-proxy logs here: https://drive.google.com/file/d/0B_-O9fAr2fafNll5R2pmM3p0bG8/view?usp=sharing

At the beginning of the kubelet log, it complains that there is "no api server defined":
```
...
I0630 19:36:14.449441    2385 manager.go:154] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 7 (wheezy) DockerVersion:1.6.2 CadvisorVersion:0.14.0}
I0630 19:36:14.452938    2385 plugins.go:69] No cloud provider specified.
I0630 19:36:15.233405    2385 docker.go:289] Connecting to docker on unix:///var/run/docker.sock
W0630 19:36:15.242818    2385 server.go:566] No api server defined - no events will be sent to API server.
I0630 19:36:15.242869    2385 server.go:618] Adding manifest file: /etc/kubernetes/manifests
I0630 19:36:15.242892    2385 server.go:624] Adding manifest url: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest
E0630 19:36:15.252401    2385 http.go:54] Failed to read URL: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest: 404 Not Found
I0630 19:36:15.351203    2385 manager.go:150] Setting dockerRoot to /var/lib/docker
I0630 19:36:15.353074    2385 plugins.go:56] Registering credential provider: google-container-registry
I0630 19:36:15.353091    2385 plugins.go:56] Registering credential provider: .dockercfg
I0630 19:36:15.353530    2385 plugins.go:56] Registering credential provider: google-dockercfg
I0630 19:36:15.354029    2385 plugins.go:56] Registering credential provider: google-dockercfg-url
I0630 19:36:15.373313    2385 server.go:590] Started kubelet
E0630 19:36:15.373536    2385 kubelet.go:648] Image garbage collection failed: unable to find data for container /
W0630 19:36:15.373561    2385 kubelet.go:659] No api server defined - no node status update will be sent.
...
```
Did I set something up wrong, or is this a legitimate issue?

**Comment by lavalamp** [comment]
I'm running Restart test on my cluster I started last night to see if I can repro.

**Comment by lavalamp** [comment]
Just to confirm, the log files are from a node, not your master, correct?

**Comment by lavalamp** [comment]
I repro :'(

**Comment by lavalamp** [comment]
Although my kubelet doesn't seem to have auth errors. I get:

"0630 21:32:09.218542    3078 kubelet.go:777] Unable to register kubernetes-minion-fmp0 with the apiserver: minion "kubernetes-minion-fmp0" already exists"

**Comment by lavalamp** [comment]
Vagueified title, since I'm not sure of cause anymore.

**Comment by mbforbes** [comment]
Good thing we turned off the reboot and restart tests I wrote!

**Comment by roberthbailey** [comment]
Weird. That should only be logged if apierrors.IsAlreadyExists(err) returns false (see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L782) which used to work (back when the aforementioned reboot tests were passing).

**Comment by timstclair** [comment]
Yes, those logs are from the kubelet (minion).

**Comment by lavalamp** [comment]
@roberthbailey not necessarily. If all three checks don't fire, it'll also be printed.

Another clue is that this is logging every 100ms, so somehow the backoff code doesn't work or isn't firing.

**Comment by lavalamp** [comment]
I see a bunch of bad things here. Let me send a PR.

**Comment by lavalamp** [comment]
OK I think the problem is that the GCE external ID apparently can change when the node reboots. I'll send a PR. @dchen1107 does that make sense to you?

**Comment by roberthbailey** [comment]
>  the GCE external ID apparently can change when the node reboots

Really? The external ID is supposed to be the node name. How does that change across reboots?

Instance ID: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/gce/gce.go#L563

External ID: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/gce/gce.go#L554

**Comment by doublerr** [comment]
just FYI, I've seen this as well on other providers. Rebooting a node will put it in a NotReady state. removing the node and restarting the services force them to re-register.

**Comment by lavalamp** [comment]
@roberthbailey Well, empirically, it happens. Should we file a bug with GCE? I think we need this change anyway, in case it changes on some other provider.

**Comment by lavalamp** [comment]
@roberthbailey We don't use the external id as the node name.

**Comment by bliss** [comment]
Good day!
In spite of the problem has been marked as fixed on kubernetes at least 1.0.3 it's still persist. Just simple KVM setup, master and two nodes. After a node reboot it's never gets back and has NotReady status. Node kubelet status is OK. To bring a node back to cluster I have to restart node kubelet.

**Comment by roberthbailey** [comment]
I just rebooted a node in a GCE cluster and it properly transitioned back to the Ready state. Can you file a new issue so that we can tag it with the appropriate environment (bare metal / local cluster up / etc)?

**Comment by bliss** [comment]
@roberthbailey: surely. Thank you.
