### ISSUE TITLE
Circular dependency between kubelet <- docker <- cbr0 <- kubelet on systemd

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#10379]
On systemd, Docker depends on cbr0:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/docker/docker-defaults#L5

cbr0 is now created by kubelet (after https://github.com/GoogleCloudPlatform/kubernetes/pull/10312)

But kubelet depends on Docker: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kubelet/kubelet.service#L5

I'm a bit confused about how to break this loop (if it is even a loop).  What I'm seeing is that Docker can't start, but then kubelet fails to start because of the docker dependency.

**Comment by mbforbes** [comment]
+cc @dchen1107 @cjcullen @zmerlynn

**Comment by mbforbes** [comment]
I have an idea how this works (I think some number of things are brought up in a "bad" state, then something is reconfigured, then something gets killed/restarted, then we're good to go), but others I mentioned will be able to clarify the exact timeline and objects involved in these events.

**Comment by justinsb** [comment]
I was able to break the dependency by changing the kubelet service to not depend on Docker, and changing it to restart indefinitely.  Not sure if this is right, but I'll put up a PR when/if I get past the other problems I'm hitting.
