### ISSUE TITLE
Document the empty selector for fields and labels

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#10373]
In labels.md we cover the api but don't mention the empty select that covers everything.

**Comment by ae6rt** [comment]
I took a shot at this:

https://github.com/GoogleCloudPlatform/kubernetes/pull/10392

**Comment by ae6rt** [comment]
I recreated the original PR with a new one.  I hosed up squashing commits on the first one.  Sorry for the noise.  The content of the commit follows the suggestion made here:

https://github.com/GoogleCloudPlatform/kubernetes/pull/10392/files#r33394857
