### ISSUE TITLE
Containers don't get destroyed when stopping an RC on Kubernetes Mesos

### ISSUE THREAD

**Issue by parikhyash** [GoogleCloudPlatform/kubernetes#10371]
I'm using Kubernetes on Mesos by doing "export KUBERNETES_CONTRIB=mesos". I'm building Kubernetes from the master branch using "make". I can launch RCs and services normally (using the REST API as well as kubectl). However, when I destroy an RC, the containers on the slave keep running and I'm having to manually destroy them using "docker stop <container-id>" followed by "docker rm <container-id>".

My Mesos cluster has one master, two slaves and a Zookeeper (all different hosts). There is a different host for Kubernetes as well.

Earlier, when I was using the upstream branch on the k8sm repo (kubernetes-mesos), this issue wasn't there.

Is there any fix for this? @jdef

**Comment by jdef** [comment]
This sounds like a new bug. Needs investigation.

**Comment by sttts** [comment]
Can you check in your checkout that you this patch already (merged 2 days ago): https://github.com/GoogleCloudPlatform/kubernetes/commit/9e0c9b4f5a982b370924e5ecd56892db6f906ebf

In our docker-compose branch I cannot see the described behaviour, but it's also a few days old.

**Comment by parikhyash** [comment]
@sttts I do not have the patch since I had built the binaries a few days back. Will try it out and let you know if the problem still persists.

**Comment by sttts** [comment]
I guess the patch will fix it. Without it containers are leaking.

**Comment by parikhyash** [comment]
@sttts The patch does the job. The containers aren't leaking now. Thanks!
