### ISSUE TITLE
How to assign non-default namespace to Nodes?

### ISSUE THREAD

**Issue by codefx9** [GoogleCloudPlatform/kubernetes#10384]
We would like to assign non-default namespace to nodes when provisioning them. We would like to run pods from different namespaces on different nodes to maintain proper security isolation. Is that supported in Kubernetes?

**Comment by thockin** [comment]
Nodes are outside of any Namespace.  There is a basic assumption of a single trust domain, for now.

**Comment by erictune** [comment]
@codefx9

You can put different labels on your nodes.
And you can put different nodeSelector on your pods to force those pods to
those nodes.

If you want to make make a mandatory policy that certain pods have a
certain nodeSelector, you can write an admission controller which adds such
a node selector.  Something like:

```go
// Admit forces pods to have a node selector corresponding to their
namespace.
func (l *limitRanger) Admit(a admission.Attributes) (err error) {
        if a.GetResource() != string(api.ResourcePods) {
                return nil
        }
        obj := a.GetObject()
        if obj == nil {
                return nil
        }
        pod, ok := obj.(*api.Pod)
        if !ok {
                return nil
        }

        // Don't modify the spec of mirror pods.
        // That makes the kubelet very angry and confused, and it
immediately deletes the pod (because the spec doesn't match)
        if _, isMirrorPod :=
pod.Annotations[kubelet.ConfigMirrorAnnotationKey]; isMirrorPod {
                return nil
        }
        if !hasRequiredNodeSelector(pod.Spec.NodeSelector) {

              return admission.NewForbidden(a, err)
              // OR, set the missing selector here, and merge with any
other allowed selectors.

        }
        return nil
}
```
If you want to send a PR, we will take it after we finish v1.
