### ISSUE TITLE
How to create Kubernetes pods using private images on Docker Hub?

### ISSUE THREAD

**Issue by codefx9** [GoogleCloudPlatform/kubernetes#10383]
I have configured nodes by copying /root/.dockercfg files according to instructions [here]. But I am still getting error message "Failed to inspect image". Is there any complete working example of using private images from Docker Hub to start pods in Kubernetes?

[here]: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md#configuring-nodes-to-authenticate-to-a-private-registry

**Comment by erictune** [comment]
Can you do two things:

1) verify that the registry name in your .dockercfg is an URL, like this:
```
{
	"https://index.docker.io/v1/": {    <--------- This needs https: at the beginning
		"auth": "XXXXXXXXXXXXXX",
		"email": "user@example.com"
	}
}
```
If not add, and try again.

2) go to the node and check if you can `sudo docker pull $yousecretimagename`.

**Comment by erictune** [comment]
I tried this just now.  It worked for me.
I did:
  1. start a pod which pulls a private image from my account at the docker hub.  Verify that it failed to start.  delete the pod.
  1. verify I can run that image with docker on my desktop
  1. `for m in $(get list of nodes); do scp ~/.dockercfg root@$m:/root/.dockercfg`
  1. recreate pod from step 1.  verify that it starts.  It did.

I have this software version:
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.1", GitCommit:"befd1385e5af5f7516f75a27a2628272bb9e9f36", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}
```

**Comment by codefx9** [comment]
Hi Eric,
I tried your steps but it is not working for me. We are using docker 0.17.0. Which version of docker are you using? Just to be clear, we are not pulling images ahead of time to mater or any nodes.

 spec.containers{elasticsearch}		failed			Failed to pull image "xyz/elasticsearch:1.6.0": Error: image xyz/elasticsearch:1.6.0 not found

**Comment by erictune** [comment]
Which platform are you on?   Are you on Google Container Engine (GKE), or did you use one of the Getting Started Guides, and if so which one?.

**Comment by codefx9** [comment]
I am running on DigitalOcean using Ubuntu 15.04 and systemd.

**Comment by erictune** [comment]
If you ssh to one of your kubernetes nodes and do `sudo docker pull xyz/elasticsearch:1.6.0` do you get an error?  If you get an error doing that then the problem is on the docker side (your docker setup, your registry, or your .dockercfg).  If you don't get an error doing that, then the problem is with Kubelet.

**Comment by codefx9** [comment]
`sudo docker pull xyz/elasticsearch:1.6.0` can pull images from Docker Hub in any nodes. Is there any way to debug what is the issue with Kubelet?

**Comment by codefx9** [comment]
Thanks for your hint. We are able to pull private images from Docker hub. We have to set the .dockercfg file at the root `/.dockercfg`  instead of `/root/.dockercfg`.

In the kubelet logs we found the following lines:
```sh
looking for .dockercfg at /var/lib/kubelet/.dockercfg
looking for .dockercfg at /.dockercfg
```
But I am not sure why it was not working before:. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/credentialprovider/config.go#L67 tells me it should have worked with `/root/.dockercfg` .

**Comment by chiefy** [comment]
Not sure if this needs to get re-opened, but I am having issues pulling from a private docker hub registry.

I created both a `/root/.dockercfg` and `/root/.docker/config.json` with creds (the json form is used by docker >= 1.8), then created a RC which called to pull the private image. I can ssh into the minion and `sudo docker pull myuser/private:version` just fine.

**Comment by vishh** [comment]
@chiefy: From the [code](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/credentialprovider/config.go#L67), it looks like kubelet expects either `.dockercfg` or `config.json` to be present under one of the following paths:
* [`/var/lib/kubelet/`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L448)
* Kubelet's working directory - `/`on GCE. I'm not sure on systemd systems.
* `${HOME}/.docker`
* `/.docker`

[This doc](https://github.com/kubernetes/kubernetes/blob/2b6fd572202514e1b934279068e2a1cd4da18a97/docs/user-guide/images.md#configuring-nodes-to-authenticate-to-a-private-repository) needs to be updated.

**Comment by chiefy** [comment]
@vishh thanks, I tried both `.dockercfg` and `/root/.docker/config.json` to no avail.

**Comment by mrunix1998** [comment]
you can login in docker first then put imagePullPolicy in yaml file
