### ISSUE TITLE
0.20 build + cherrypick requests

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#10409]
I'm going to do today's build of a 0.20 and will use this issue to track its progress.  And if you have cherrypick PR requests, please tag this issue on them.

@brendandburns has pending #10274 to cut it.

**Comment by alex-mohr** [comment]
Thanks for the cherrypick requests.  Those will likely get kicked off on Monday along with any others that come up.
I've published 0.20.0 to the releases page, along with binaries.  Release notes still in progress, also to land on Monday.
https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.20.0

**Comment by thockin** [comment]
#10296 - EOL caching mirror

#10264 - CA certs for svcacct

##10361 - fix bug in #10264

#10150 - No more DNS token

**Comment by a-robinson** [comment]
@zmerlynn requested #10437

**Comment by alex-mohr** [comment]
Thanks.  v0.20.0 is now final with release notes and such.

I'll cut v0.20.1 after lunch now that all the above requests have been merged.

**Comment by alex-mohr** [comment]
Looks like #10296 - EOL caching mirror, #10264 - CA certs for svcacct, and #10361 - fix bug in #10264 were already in v0.20.0.

Cherrypicks in https://github.com/GoogleCloudPlatform/kubernetes/pull/10499:
 * Don't block etcd client #10427
 * Revert "Remove raw binaries from distro that are already included in … #10437
 * Revert "Set resource limit for both heapster and influxdb container b… #10430
 * #10150 - No more DNS token

**Comment by dchen1107** [comment]
If we want to cut v0.20.2, please do include PR #10400; otherwise, I plan to update our release notes for v0.20.1 for such breakage.

**Comment by dchen1107** [comment]
Ahh, I just saw @alex-mohr already includes pr #10400

**Comment by alex-mohr** [comment]
Yeah, just sent #10559 to cherrypick 3 PRs into v0.20.2:
  * Don't make kubelet systemd service depend on Docker #10400
  * Kubelet doesn't fight apiserver for cputime on the master. #10471
  * Wait until a token shows up to start addons (redux) #10542

*Unmerged* candidate for v0.20.3:
 * Make UpgradeAwareProxyHandler use transport.Dial if provided #10529

**Comment by vishh** [comment]
Can you include #10369 in the next patch release?

**Comment by alex-mohr** [comment]
@vishh Can you please summarize why #10369 should be cherrypicked?  What's the state of the world if we don't patch vs. we do?  Is it fixing a regression?  That is, we need to finalize 0.20.x and it's not clear to me if this is just a nice to have that's fine waiting for 0.21 or more urgent.

**Comment by alex-mohr** [comment]
Marked 0.20.2 as stable and removed pre-release tag.
