### ISSUE TITLE
Unable to revoke docker credentials

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#10425]
Steps to repro:
  1. put a .dockercfg in /root/.dockercfg with credentials for a private repository
  1. run a pod that uses an image from that repository.  it will succeed.
  1. stop the pod
  1. delete the .dockercfg
  1. restart the kubelet
  1. remove the image with `docker rmi -f [privateimagename]`
  1. `docker logout`
  1. verify that you cannot manually pull the private image with a node-local `docker pull`.
  1. run the pod again.   magically, the image is still pulled. :confused:

**Comment by erictune** [comment]
@deads2k

**Comment by erictune** [comment]
Repro'ed a second time to make sure I am not crazy.

**Comment by erictune** [comment]
The image clearly got pulled, but a straight docker pull still can't get the image:
```
root@gke-cluster-xxx:~# docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
erictune/private-test                  v1                  501410a09546        2 weeks ago         226 MB
gcr.io/google_containers/fluentd-gcp   1.6                 b05d63f3454a        5 weeks ago         420.9 MB
gcr.io/google_containers/pause         0.8.0               2c40b0526b63        12 weeks ago        241.7 kB
gcr.io/google_containers/pause         latest              6c4579af347b        11 months ago       239.8 kB
root@gke-cluster-xxx:~# docker pull erictune/private-test:v1
Pulling repository erictune/private-test
FATA[0000] Error: image erictune/private-test:v1 not found

**Comment by erictune** [comment]
What is baffling is that, since docker can't pull the image, it seems like the kubelet must be passing the credentials.
But the kubelet was restarted, so it shouldn't be remembering any credentials.

**Comment by erictune** [comment]
This isn't terribly severe.  But it would be nice to know what is going on.

**Comment by erictune** [comment]
TODO: in `pkg/kubelet/dockertools/docker.go` around line 152, see what credentials are being used.

**Comment by deads2k** [comment]
@erictune I can't reproduce this.  Are you sure you deleted `/root/.dockercfg` and not the one for your user?

```
[deads@deads-dev-01 origin]$ oc create -f ../secured-pod.json 
pods/my-pod
[deads@deads-dev-01 origin]$ oc get pods
NAME      READY     REASON    RESTARTS   AGE
my-pod    0/1       Running   0          2s
[deads@deads-dev-01 origin]$ oc delete pod/my-pod
pods/my-pod
[deads@deads-dev-01 origin]$ sudo rm /root/.dockercfg
[deads@deads-dev-01 origin]$ docker rmi docker.io/deads2k/private-repo
Untagged: docker.io/deads2k/private-repo:latest
[deads@deads-dev-01 origin]$ oc create -f ../secured-pod.json 
pods/my-pod
[deads@deads-dev-01 origin]$ oc get pods
NAME      READY     REASON                                               RESTARTS   AGE
my-pod    0/1       Error: image deads2k/private-repo:latest not found   0          3s
```

**Comment by erictune** [comment]
I'm sure I deleted /root/.dockercfg.
Thanks for trying.
Weird.
