### ISSUE TITLE
Add support for custom GKE scopes in cluster/gke/util.sh

### ISSUE THREAD

**Issue by chrishiestand** [GoogleCloudPlatform/kubernetes#10458]
I find it curious that this doesn't already exist. I assume there is a reason for that but I couldn't find any references for it. What is the reason?

If there is hope of adding custom gke scopes, I'd be happy to submit a PR, but I'd like some feedback first. I noticed notes for @mbforbes like "Refactor setting scope flags." What refactor was in mind? Currently scopes are set in the MINION_SCOPES variable which is a bash array. Because it's an array it needs a join_csv function. But as far as I can tell, the variable is never "pushed" or "popped" so I see no benefit from using the array. Although if we eventually want to push e.g. monitoring, logging scopes onto the array, we should keep it. Alternatively it might be easy to just concat comma-separated strings.

I don't mean to bike shed here, I'd just like to do the simplest PR that will be accepted and enable custom scopes in gke.

**Comment by erictune** [comment]
When you create a cluster through the GKE UI, at https://pantheon.corp.google.com/project/$YOURPROJECT/kubernetes/add you can click "More" near the bottom, and then you get a list of scope to select for your VMs.
Does that do what you need?

**Comment by roberthbailey** [comment]
Did you try changing the value of MINION_SCOPES in [config-default.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/config-default.sh#L44)?

**Comment by chrishiestand** [comment]
@erictune our cluster rollout is scripted for automated setup, by the same token I could just modify cluster/gke/util.sh myself (but that would require maintaining a fork - not so terrible, but I imagine other people would want to set custom scopes as well).

@roberthbailey Ideally I'd like to avoid maintaining a separate branch with my configuration. Much better to set configuration variables and then run the standard script. Also, the current kube-up() function in util.sh does not use the MINION_SCOPES variable when creating the cluster.

**Comment by roberthbailey** [comment]
@chrishiestand -- you are correct. It doesn't look like the gke config-default.sh even defines MINION_SCOPES and kube-up doesn't use it when [creating the cluster](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gke/util.sh#L153). 

This would be a fine feature improvement for the gke cluster creation scripts and we would certainly accept a patch that plumbs through the minion scopes (and allows you to override the default ones via an environment variable). 

We are currently in feature freeze for the 1.0 launch, but I believe this meets the criteria for inclusion since it brings GKE up to par with the GCE cluster creation scripts.

**Comment by chrishiestand** [comment]
Thanks @roberthbailey! If anyone, or @mbforbes in particular, has a strong preference as to the style of plumbing please let me know, I'm happy to help with the refactor. Otherwise I'll maintain the current style.

**Comment by mbforbes** [comment]
@chrishiestand no preference here, though feel free to include me in the PR. I wrote that TODO because I had been blindly copying those variables around when adding new paths (e.g. cluster/gce/upgrade.sh from cluster/gce/util.sh) and didn't like the code duplication.

**Comment by roberthbailey** [comment]
As discussed on the PR, this will land post 1.0.

**Comment by chrishiestand** [comment]
Thanks for your responsiveness and help, everyone.
