### ISSUE TITLE
Sample cloud-config master.yaml has wrong kube-apiserver options

### ISSUE THREAD

**Issue by chiefy** [GoogleCloudPlatform/kubernetes#10467]
[the --service-cluster-ip-range option](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloud-configs/master.yaml#L121) results in this:

```bash
$ ./kube-apiserver --insecure-bind-address=0.0.0.0 --service-cluster-ip-range=10.100.0.0/16 --etcd-servers=http://localhost:2379
unknown flag: --service-cluster-ip-range
Usage of ./kube-apiserver:
...
```

```bash
$ ./kube-apiserver --version 
Kubernetes v0.17.0
```

**Comment by roberthbailey** [comment]
This flag used to be called `--portal_net`. See https://github.com/GoogleCloudPlatform/kubernetes/pull/8740.

**Comment by roberthbailey** [comment]
It was changed with release 0.18.0 (see the [release notes](https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.18.0)).

**Comment by chiefy** [comment]
Ok, still seems like an issue since the master.yaml is [pulling down version 0.17.0 and using 0.18.0 options](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloud-configs/master.yaml#L117)?

**Comment by roberthbailey** [comment]
Yes, that seems like a bug. Are you interested in updating the configs to use a more recent release?

**Comment by chiefy** [comment]
@roberthbailey yeah, I actually got them working with my [terraform based project](https://github.com/chiefy/tf-aws-kubernetes). I will fork + PR.

**Comment by roberthbailey** [comment]
Thanks! I'd much rather see the configs catch up to a newer kubernetes version that keep old flags around.
