### ISSUE TITLE
running two times KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

### ISSUE THREAD

**Issue by svennela** [GoogleCloudPlatform/kubernetes#10466]
Hi ,

I ran below command 2 times. First time i canceled it because it failed with below error. 

can't be established.
ECDSA key fingerprint is 44:a4:6f:2e:d6:95:78:09:50:b7:5b:23:28:30:51:54.
 
when i run below second time i am getting below error? any help??
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

[sudo] password to copy files and start node:
cp: cannot create regular file ‘/opt/bin/etcd’: Text file busy
cp: cannot create regular file ‘/opt/bin/kube-apiserver’: Text file busy
cp: cannot create regular file ‘/opt/bin/kube-controller-manager’: Text file busy
cp: cannot create regular file ‘/opt/bin/kube-scheduler’: Text file busy
start: Job is already running: etcd

**Comment by erictune** [comment]
sounds like etcd, kube-apiserver, etc are still running.  Find them with `ps` and kill them, and then try again?

**Comment by svennela** [comment]
I did...
I created shell script ..:)
sudo service etcd stop

rm -rf /opt/bin/etcd
rm -rf /opt/bin/kube-scheduler
rm -rf /opt/bin/kube-controller-manager
rm -rf /opt/bin/kube-apiserver

rm -rf /opt/bin/flanneld

rm -rf /opt/bin/kubelet
rm -rf /opt/bin/kube-proxy

**Comment by yueyemaitian** [comment]
I modified utuntu/util.sh, and get 'Cluster validation succeeded'
First add -f for all cp commands, like this: cp ~/kube/default/* /etc/default/  ===> cp -f ~/kube/default/* /etc/default/
Then rerun ./kube-up.sh, you will encounter "start: Job is already running: etcd"
Then Modified utuntu/util.sh, change 'service XXX start' to 'service XXX restart' , and run kube-up.sh
You'll get the success message
