### ISSUE TITLE
pod field selectors are broken

### ISSUE THREAD

**Issue by sym3tri** [GoogleCloudPlatform/kubernetes#10515]
api version: v1
git version: "v0.19.3"

They are no longer working after upgrading. A request like this used to work:

`GET /v1/pods?fieldSelector=spec.nodeName=xxx`

but now returns:

```
{
  kind: "Status",
  apiVersion: "v1",
  metadata: { },
  status: "Failure",
  message: "field label not supported: spec.nodeName",
  reason: "BadRequest",
  code: 400
}
```

Any other field is also failing with the same response.

**Comment by a-robinson** [comment]
cc @nikhiljindal to triage/attempt to repro

**Comment by nikhiljindal** [comment]
I just tried it on HEAD and this works fine for me.
```
GET api/v1/pods?fieldSelector=spec.nodeName=xxx
```
gave me the expected output.
Changing nodeName to anything else gave me the field label not supported error.
Here is my version
```
Client Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-213-g09df440b79b5cf-dirty", GitCommit:"09df440b79b5cf74d6547a5cb3157a3b464d25b0", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-213-g09df440b79b5cf-dirty", GitCommit:"09df440b79b5cf74d6547a5cb3157a3b464d25b0", GitTreeState:"dirty"}
```

@sym3tri Can you please try syncing to HEAD and see if you still face this issue?

**Comment by sym3tri** [comment]
@nikhiljindal Thanks for the update. May just be an issue in v0.19.3. Sounds like it's fixed in master. 

Unfortunately I'm not able to run off of master right away.  I'll try the latest version once I'm able to and report back.

**Comment by nikhiljindal** [comment]
Closing. Feel free to reopen.

**Comment by brendandburns** [comment]
This was introduced by https://github.com/GoogleCloudPlatform/kubernetes/pull/10076

we're fixing it here:
https://github.com/GoogleCloudPlatform/kubernetes/pull/11084

and we're going to cherry-pick 0.21.2 with the fix.
