### ISSUE TITLE
Generate API docs from Go structs or vice versa

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#1052]
Now that we have API versioning in place, we should generate our api/doc schemas from Go structs (and probably even from a Godoc 'Example' which has sample values).  We should also look at how we can take the Godoc comments and stitch them into the formal doc.

**Comment by bgrant0607** [comment]
This looks like it may generate the static documentation we need:
https://www.npmjs.com/package/swagger-to-markdown
https://github.com/Skookum/SwaggerToMarkdown/blob/master/swagger-to-markdown.rb

If it works, we'll want to Dockerize this so people don't have to install ruby, similar to what I did previously for [raml2html](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/Dockerfile).

**Comment by nikhiljindal** [comment]
I looked at https://github.com/Skookum/SwaggerToMarkdown.
The last update to that project is more than 2 years old and it does not look like it is actively maintained.
Also there is no documentation regarding the files it requires (resources and parameter files). I looked at the sample parameters file there and it does not look like something that is generated by swagger for us. Seems like we will have to generate that file manually, which defeats the purpose.

https://github.com/roland-hochmuth/swagger-to-md is another such project which does not seem to be maintained.

I found https://github.com/swagger-api/swagger-codegen#generating-static-api-documentation tough, which seems promising.
I was able to generate static HTML documentation from our swagger spec using it.
It has some issues like: 
- the generated HTML has some issues on chrome. It works fine on firefox tough.
- the generated HTML combines documentation for api/v1beta1, api/v1beta2 and api/v1beta3 into a single api/ documentation, which makes it confusing.
But it looks promising. Will look into it in more detail.

**Comment by nikhiljindal** [comment]
Another options is to try a static version of Swagger UI. We can host that on kubernetes.io
Sent PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/3771 for that

**Comment by smarterclayton** [comment]
Can we run it in a pod easily and infer the master?  I do like the static generation for docs of other forms, but the first goal is easy access for sure.

**Comment by brendandburns** [comment]
Can't we just use the kubernetes-ro service to discover the master?

Brendan

**Comment by smarterclayton** [comment]
Yes, that's what I meant by infer.  Bad choice of words.

**Comment by brendandburns** [comment]
Closing this as we now have http://kubernetes.io/third_party/swagger-ui
