### ISSUE TITLE
kube-dns failed to connect to the api server

### ISSUE THREAD

**Issue by WIZARD-CXY** [GoogleCloudPlatform/kubernetes#10530]
@thockin I am updating the k8s 0.19.3 on ubuntu to use the latest kube-dns and I'm using the newest template which means v1 api to deploy. Only to find there is some authentication error. kube2sky complains as 

` 
E0630 05:00:10.016434       1 helper.go:247] expected to load root ca config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I0630 05:00:10.017427       1 kube2sky.go:455] Using https://192.168.3.1:443 for kubernetes master
I0630 05:00:10.017460       1 kube2sky.go:456] Using kubernetes API v1beta3
E0630 05:00:10.043602       1 reflector.go:136] Failed to list *api.Service: Get https://192.168.3.1:443/api/v1beta3/services: x509: failed to load system roots and no roots provided
E0630 05:00:10.044705       1 reflector.go:136] Failed to list *api.Endpoints: Get https://192.168.3.1:443/api/v1beta3/endpoints: x509: failed to load system roots and no roots provided
`

Indeed I have no  `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`. But I don't find how to generate it  in your doc https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/README.md
Now I only used service account https://github.com/GoogleCloudPlatform/kubernetes/pull/10393. Will you tell me how to get it work.Thanks a lot!

**Comment by thockin** [comment]
That's available in 0.20.0 and higher

**Comment by WIZARD-CXY** [comment]
Thanks for your quick reply. I will try it with 0.20.0 to see if it is ok.

**Comment by thockin** [comment]
Thanks, please reopen if that doesn't work.

**Comment by WIZARD-CXY** [comment]
It seems not working .apiserver logs:
`I0630 14:50:48.281520    4307 logs.go:41] http: TLS handshake error from 10.10.103.223:51723: remote error: bad certificate
`

kube-dns log 
`
I0630 06:48:35.953875       1 kube2sky.go:389] Etcd server found: http://127.0.0.1:4001
E0630 06:48:36.958448       1 helper.go:247] expected to load root ca config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I0630 06:48:36.958532       1 kube2sky.go:455] Using https://192.168.3.1:443 for kubernetes master
I0630 06:48:36.958549       1 kube2sky.go:456] Using kubernetes API v1beta3
E0630 06:48:36.967224       1 reflector.go:136] Failed to list *api.Endpoints: Get https://192.168.3.1:443/api/v1beta3/endpoints: x509: failed to load system roots and no roots provided
`
I think using the 0.20.1 version of k8s. I think I still need to manually configure the https cert and keys maybe?

**Comment by thockin** [comment]
You are missing a --kubeconfig= argument - I have not personally looked at
the ubuntu code, so I can not be more helpful right now.
