### ISSUE TITLE
garbage collection is not working

### ISSUE THREAD

**Issue by odis912** [GoogleCloudPlatform/kubernetes#10531]
i'm using gcr.io/google_containers/hyperkube:v0.18.2  with garbage collection option (minimum-container-ttl-duration)

docker run --net=host -d -v /var/run/docker.sock:/var/run/docker.sock  gcr.io/google_containers/hyperkube:v0.18.2 /hyperkube kubelet --api_servers=http://xx.xx.xx.x:8080 --v=2 --address=0.0.0.0 --enable_server --hostname_override=$1 --minimum-container-ttl-duration=1s --image-gc-low-threshold=80

but garbage collection is not working. Exited containers are remaining,

**Comment by zmerlynn** [comment]
@dchen1107, any thoughts?

**Comment by yujuhong** [comment]
`minimum-container-ttl-duration` sets "Minimum age for a finished container before it is garbage collected", but it only guarantees that a container would *NOT* be GC'd before that.

What you want to set is `--maximum-dead-containers`, which is the "Maximum number of old instances of a containers to retain globally`. The default is 100, once the number of dead containers is greater than 100, GC would kick in.

**Comment by odis912** [comment]
thanks!, '--maximum-dead-containers' is working.

**Comment by zmerlynn** [comment]
Closing. Reopen if you'd like further assistance. Thanks for the help, @yujuhong!
