### ISSUE TITLE
Set minimal shares for containers with no cpu specified

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#10543]
In #687, we explicitly set cpu shares to 0 for containers with 0 cpu specified. However, @yujuhong and @gmarek say that Docker gives such containers 1024 shares. If true, we should give such containers minimal shares (10? 50?) instead. Otherwise, containers that specify no cpu would get a lot more shares than those that explicitly specify a small amount of cpu, including due to the default in LimitRange.

cc @rjnagal @vmarmol @vishh @dchen1107

**Comment by vmarmol** [comment]
If we don't set shares Docker uses the kernel default which is 1024 (1 core for us). We treat 0 as "not specified" here: https://github.com/GoogleCloudPlatform/kubernetes/blob/0f1c4c25c344f70c3592040b2ef092ccdce0244f/pkg/kubelet/dockertools/docker.go#L308

We should probably either change that or use a different value as "zero".

**Comment by bgrant0607** [comment]
I don't care whether it's on purpose, accidental, or by negligence, but "0" shouldn't translate to 1024. It should translate to the smallest share we can set. In particular, "0" should be less than "100m".

When we implement nested cgroups, they'd go into a "best effort" cgroup.

**Comment by dchen1107** [comment]
Ahh, I misunderstood you @bgrant0607 earlier. Again I still think we should have better spreading algorithms in scheduler, or apply LimitRanger with default resource limit for all namespaces. But that is different issue. What you proposed here do make sense. I move this to 1.0, and assign it to myself. I am going to change this to "match" our internal system (2ms).

**Comment by bgrant0607** [comment]
Thanks. #10242 covers the scheduling of containers with no resources specified.

**Comment by dchen1107** [comment]
This issue is blocked by configuring default addon services with proper resource limit; otherwise, those services won't get any cpu.shares to run.
