### ISSUE TITLE
Inadequate monitoring documentation

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#10551]
Issues:
  - the documentation we have in cluster/addons/cluster-monitoring/README.md is terse. 
    - it should describe what metrics are monitored, and link to and from docs about limits, such as docs/resources.md
  - it is not under the docs directory where we keep user docs.  Some kind of overview should be in `docs`.
  - it is described as an addon but some form of cluster monitoring it seems to be enabled by default on GCE, AWS, GKE, Azure, vagrant, rackspace, ubuntu, etc.

**Comment by bgrant0607** [comment]
Janet is working on this. #11066
