### ISSUE TITLE
Improve scheduler event messages

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#10553]
Scheduler event:
```
Events:
  FirstSeen  ... Reason                    Message
  ...              ...  failedScheduling	Error scheduling: For each of these fitness predicates, pod frontend failed on at least one node: PodFitsResources.
```

Problems with this event message:
1. It says `Error`, but having pods fail to schedule is a common event in a system, and "Error" is too alarming a term.
1. It says `scheduling`, but the event makes it clear that this is about scheduling in both the `From` and `Reason` fields.
1. it says `For each of these fitness predicates .. failed on at least one node:` but there is only one predicate in this case.  Lets be concise and to the point where possible.  Maybe when only one predicate failed, say: `No node satisfied rule PodFitsResources`.
1. the message contains the string `pod frontend`, but that information is already present in the event object.  Save space by removing this.  Also, it reduces the cardinality of the set of distinct message strings, which facilitates grouping of events.

An improved output looks something like this:
```
Events:
  FirstSeen  ... Reason                    Message
  ...              ...  failedScheduling	No node found where PodFitsResources.
```

**Comment by davidopp** [comment]
I'm going to close this issue and copy the comments over to #9207.
