### ISSUE TITLE
Deleting a replication controller using the REST API doesn't delete the pods

### ISSUE THREAD

**Issue by parikhyash** [GoogleCloudPlatform/kubernetes#10564]
I'm trying to use the REST API to bring down a Redis cluster that I've launched. 

However, a DELETE call on the replication controller doesn't bring down the pods associated with it. Is this the expected behavior?

"kubectl stop" on a replication controller brings down the associated pods as well. So it seems that there's some disparity.

@bgrant0607

**Comment by jiangyaoguo** [comment]
Yes. If you want to delete rc and pods associated, you need to update replicas of rc to 0 and then delete rc.

**Comment by parikhyash** [comment]
@jiangyaoguo I see. So "kubectl stop" does both the operations that you described?

**Comment by bgrant0607** [comment]
@parikhyash Yes, kubectl delete and kubectl stop resize to 0.

We'd like to implement this in the server eventually -- see #1535. But currently we don't.

**Comment by jiangyaoguo** [comment]
@parikhyash Yes. You can check help information of "kubectl stop". You'll see "If the resource is scalable it will be scaled to 0 before deletion".

**Comment by parikhyash** [comment]
Got it. Thanks for the replies

**Comment by sputnick** [comment]
Is there any way to cascade the delete today with the Rest API? It seems like the api delete still doesn't delete pods in v1.4 for a Deployment which must mean that the business logic is all in kubectl which makes it difficult to keep up with kubectl features in other clients...

**Comment by mars00772** [comment]
still not implemented after one year @bgrant0607 ,also delete deployment by restful api won't delete the rs and pod ..

**Comment by bgrant0607** [comment]
@sputnick @mars00772 Underway.
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/garbage-collection.md
#26120
