### ISSUE TITLE
kube-apiserver generates a self signed cert that doesn't work for the kubernetes service

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#10577]
If no certificate is passed on the command line, kube-apiserver will [generate a self signed certificate](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L451-L452). 

We need to update the cert generate to add a few subject alternate names as per https://github.com/GoogleCloudPlatform/kubernetes/pull/10107.

**Comment by roberthbailey** [comment]
@eparis do you have time to take a look at this?

**Comment by thockin** [comment]
Can this be closed now?

**Comment by roberthbailey** [comment]
Will be fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10711.

**Comment by roberthbailey** [comment]
Actually, I think that PR is for a different bug and this can be closed.

**Comment by eparis** [comment]
correct #10643 is what fixed this (and led to #10711)
