### ISSUE TITLE
kubectl replace command breaks tests

### ISSUE THREAD

**Issue by krousey** [GoogleCloudPlatform/kubernetes#10572]
in pkg/kubectl/cmd/replace.go under RunReplace, there's

```go
if os.Args[1] == "update" {
    ...
}
```

Running `godep go test` in this directory panics with index out of range errors. Shippable/CI didn't pick this up because when run through hack/test-go.sh, the first arg is `-test.timeout=120s`

So this also doesn't account for any flags that could be between kubectl and the command.

**Comment by caesarxuchao** [comment]
FWIW, same problem here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg%2Fkubectl%2Fcmd%2Frollingupdate.go#L108

**Comment by krousey** [comment]
Yea that would have caused test panics to... if it were tested. Both should probably be fixed since they don't properly handle the `kubectl -flag command` case.

**Comment by caesarxuchao** [comment]
cc @bgrant0607
