### ISSUE TITLE
 Unknown options: --exact-timestamps

### ISSUE THREAD

**Issue by harish-myaccount** [GoogleCloudPlatform/kubernetes#10605]
When running  ./cluster/kube-up.sh

Output is
Starting cluster using provider: aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: ubuntu
Uploading to Amazon S3
Creating mycompany-kubernetes
make_bucket: s3://mycompany-kubernetes/
+++ Staging server tars to S3 Storage: mycompany-kubernetes/devel
Unknown options: --exact-timestamps

**Comment by harish-myaccount** [comment]
deleted --exact-timestamps option in kubernetes/cluster/aws/util.sh from line 
aws s3 sync

**Comment by CpuID** [comment]
FYI this option was added in awscli Version 1.3.23, there is a bugfix in 1.5.3 though.

https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst

If you update awscli this should work unmodified. Maybe the kube-up.sh script should have an awscli version check?

**Comment by zmerlynn** [comment]
The GCE version auto-updates `gcloud`. Could we do the same thing for `aws-cli`?

Anyways, drive-by comment. cc @justinsb for support.

**Comment by harish-myaccount** [comment]
updating aws-cli helped.thanks

**Comment by CpuID** [comment]
Worth reopening to add checks to enforce a min version?


Nathan Sullivan
