### ISSUE TITLE
Heapster is crashlooping with cluster monitoring set to google

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/kubernetes#10617]
The cause is probably #10369

More context https://github.com/GoogleCloudPlatform/heapster/issues/381

**Comment by mikedanese** [comment]
Does your branch include #10523? There was a race condition where serviceaccount ssl certs were sometimes not mounted for the cluster addons. Deleting the pod and allowing it to be recreated would temporarily fix it. #10523 should be a permanent fix.

**Comment by mikedanese** [comment]
Related issue #10507

**Comment by mikedanese** [comment]
Actually I am incorrect. I will investigate.
