### ISSUE TITLE
No unique way to identify Kubernetes objects

### ISSUE THREAD

**Issue by stefwalter** [GoogleCloudPlatform/kubernetes#10610]
Previously we could use ```object.metadata.uid``` together with ```object.kind``` to uniquely identify kubernetes objects loaded on the client side. Both unique during a single snapshot, and temporally unique across creation/delete cycles (as near as makes no difference).

However that is currently no longer the case: The ```kubernetes``` service does not have a ```metadata.uid``` field.

Is this an oversight? Can I add one for consistency? Even if it's hard coded?

CC @derekwaynecarr @smarterclayton

**Comment by smarterclayton** [comment]
It was a bug - but should have been fixed.  @liggiitt was there an existing
issue?

On Jul 1, 2015, at 4:54 AM, Stef Walter <notifications@github.com> wrote:

Previously we could use metadata.uid and metadata.kind to uniquely identify
kubernetes objects on the client side. Both unique during a single
snapshot, and temporally unique across creation/delete cycles (as near as
makes no difference).

However that is currently no longer the case: The kubernetes service does
not have a metadata.uid field.

Is this an oversight? Can I add one for consistency? Even if it's hard
coded?

CC @derekwaynecarr <https://github.com/derekwaynecarr> @smarterclayton
<https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10610>.

**Comment by erictune** [comment]
Do we tell API users that they need to use `(metadata.uid, kind)` or can they just use `metadata.uid`?

**Comment by smarterclayton** [comment]
Just uid, although I don't see harm in over specifying it now to include
both.

On Jul 1, 2015, at 5:27 PM, Eric Tune <notifications@github.com> wrote:

Do we tell API users that they need to use (metadata.uid, kind) or can they
just use metadata.uid?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10610#issuecomment-117830117>
.

**Comment by stefwalter** [comment]
> Do we tell API users that they need to use (metadata.uid, kind) or can they just use metadata.uid?

Well ```metadata.uid``` is not unique. For example endpoints match their service. I guess we should update the docs. Will open a pull request.

Anyway, it looks like this issue was fixed by @liggit in e869d5c6fc14b7c85205496e5633db6c091617f1 ... closing.

**Comment by thockin** [comment]
UUIDs should NEVER match.  If that is the case it is a bug.  can not repro:

```
$ k get svc kube-dns -o template -t "{{.metadata.uid}}  "; k get endpoints
kube-dns -o template -t "{{.metadata.uid}}  "
;
617e5d58-2046-11e5-936d-42010af0a9bc  6196f0d8-2046-11e5-936d-42010af0a9bc
```

**Comment by stefwalter** [comment]
Ah ok, so I confused this with Openshift. You're right that there is a slight difference between the service and endpoint uids in Kube.

In Openshift the various objects do have identical uids with different kinds when they theoretically represent the same object (eg: ```Project``` and ```Namespace```). Clients that want to deal with Openshift unfortunately cannot rely on ```metadata.uid``` for uniqueness.

But as you pointed out, that's not the case here.
