### ISSUE TITLE
kube-up.sh is stuck for many minutes

### ISSUE THREAD

**Issue by harish-myaccount** [GoogleCloudPlatform/kubernetes#10666]
![image](https://cloud.githubusercontent.com/assets/592646/8473611/9bd00712-20c8-11e5-9fb0-1777ecfe9164.png)

**Comment by harish-myaccount** [comment]
Changed 'aws s3 sync --exact-timestamps' to 's3cmd sync'

Seems working now...

**Comment by nikhiljindal** [comment]
Great to know that its working now.
