### ISSUE TITLE
Update docs and examples after cluster addons are moved to a separate namespace

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10668]
A follow-up from #9356.
I created a separate issue so that it's clear that @satnam6502's / @brendanburns's patch doesn't address this
I suppose it is not urgent and we can wait until the code for #9356 is ready (correct me if I'm wrong).

**Comment by marekbiskup** [comment]
Docs that need an update:
 * docs/getting-started-guides/logging.md
 * docs/getting-started-guides/logging-elasticsearch.md

Luckily, I haven't too many places that need an update.

**Comment by satnam6502** [comment]
What update is required beyond what was in my PR #10898 ?

**Comment by marekbiskup** [comment]
Everything looks fine now. Let's close this issue.
