### ISSUE TITLE
Release validation (running Jenkins on release branches)

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#10676]
I spent a little while thinking about this this morning, while working on finally writing up #1883. I would really like us to get in a state where we have a job hitting the N-1 release branch (where "N" is head). So today, it would be helpful if something were actually running against `release-0.20`. 

In particular, I think this requirement isn't just "run against the release". I'd like the cherry-pick procedure to become "cherry pick into release branch, wait for Jenkins to chew on it a while", rather than the existing "run e2es manually", because then the procedure for cherry picks and normal releases is pretty similar (you cut from the branch, always - it's just a matter of which branch you're cutting from).

One of the complications here is that the hack I introduced for "latest" continuous integration was `latest.txt`. If we were just to run `./build/push-ci-build.sh` on a release branch, you'd end up disturbing a bunch of Jenkins jobs.

I propose that `latest.txt` stays as head, but that for branch builds we could do `latest-<branch>.txt` in the CI bucket with a pretty fast modification to the script. (The actual bucket would then be unordered madness, but I'm not actually worried about that part.)

Then we could setup `kubernetes-build-release` Jenkins job, and a `kubernetes-e2e-gce-release` Jenkins job fairly quickly.

This issue is going to get larger as our releases are longer. It would be really nice if cherry picks were just gradual, i.e. people could just propose pull requests to the branch, we could dribble them in and gradually validate, then pull a new patch release.

cc @ixdy @quinton-hoole and cc @mikedanese because of recent involvement in latest.txt fun.

Note: This job is basically the analog of the `gke-test` job, but instead of happening *after* the release is cut, it happens *before*. *shocking*

**Comment by quinton-hoole** [comment]
SGTM

**Comment by zmerlynn** [comment]
I realized pretty quickly that the problem with just having a floating N-1 job is that the existing flaky/skiplist setup wouldn't transport very easily. It would work if we actually setup jobs for each release branch, though, and since the cadence of our release branches is expecting to slow to O(3mo) per https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/versioning.md, this should be fine.

**Comment by zmerlynn** [comment]
(#10932 is a test balloon for release-0.21 to vet this process. Trying to get the cherry-pick process in place as well.)

**Comment by zmerlynn** [comment]
There's a `kubernetes-e2e-gce-release` job now. It happens to be running on `release-0.21` right now and I haven't set it up for easy branch flipping (it's hardcoded on Jenkins), but given the cadence, I don't think we need that yet.

**Comment by zmerlynn** [comment]
We should also setup a soak test for this at some point..
