### ISSUE TITLE
allow mounting a different secret based on namespace

### ISSUE THREAD

**Issue by nlf** [GoogleCloudPlatform/kubernetes#10682]
For our node.js applications we base the configuration file that's loaded on the NODE_ENV environment variable, so for example if we run our app with `NODE_ENV=production` for configuration we load `production.json`, when `NODE_ENV=beta` we load `beta.json`, etc.

I've already found how to use the downward API to set the NODE_ENV environment variable based on the namespace, which is great.

What we're lacking is the ability to mount a different secret based on the namespace. For example, I would ideally like to have two secrets named `app-production` and `app-beta`. Then have my pod configured in some way such that when running in the production namespace, `app-production` is mounted, whereas if we're in the beta namespace `app-beta` is mounted instead.

Currently I'm storing all the configuration files for the different environments in one secret, but obviously that's not ideal. The only other alternative is to have a separate pod config for each environment which is also not ideal (especially seeing as only one line is changed).

**Comment by pmorie** [comment]
@nlf perhaps I'm missing something about the use-case, but since you already have different namespaces for different environments, why not use the same secret name in both namespaces, and have it contain env-appropriate configs in each.  For example, if you have two namespaces, `production` and `beta`, each of those namespaces can have an `app-config` secret which contains the environment-appropriate config.

**Comment by pmorie** [comment]
@nfl You may also be interested in: https://github.com/GoogleCloudPlatform/kubernetes/pull/6477

**Comment by thockin** [comment]
Paul is right - everything is namespace-relative, so you can just use the
same name in both, unless you run both prod and beta in the same
namespace.  You can't do cross-namespace secret references.

**Comment by nlf** [comment]
You're absolutely right, I don't know why I had it in my head that secrets aren't namespaced since they are. This is a non-issue.
