### ISSUE TITLE
kubernetes on ubuntu 12.04?

### ISSUE THREAD

**Issue by adyanthaya17** [GoogleCloudPlatform/kubernetes#10696]
Hi,

I wanted to know if deployment of kubernetes from the directory kubernetes/docs/getting-started-guides/ubuntu.md works for ubuntu 12.04 version? Like I have tested on ubuntu 14.04 but I'm unable to work it out on 12.04.

Thank you.

**Comment by thockin** [comment]
I don't think anyone has tried...
