### ISSUE TITLE
kube-ui endpoint not found

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/kubernetes#10697]
I have kubernetes running in a vm, but the apiserver proxy doesn't seem to be routing to the kube-ui.

Do I need to manually create a service for the kube-ui?

http://10.141.141.10:8888/api/v1/proxy/namespaces/default/services/kube-ui/#/dashboard/

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kube-ui\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kube-ui",
    "kind": "endpoints"
  },
  "code": 404
}
```

When I use `kubectl proxy --www=www/app --www-prefix=/` in the VM the statically hosted files are curl-able, but they aren't exposed outside of the VM, because they're on localhost and not the exposed 10.141.141.10 IP. A --bind-address on kubectl proxy might be nice to have, but that doesn't solve the problem of the UI not being available when the apiserver's up. 

The www readme talks about setting up a whole different server for the kube-ui. Is that necessary?

**Comment by nikhiljindal** [comment]
Does ``http://<masterIP>/ui``` work?

cc @bcbroussard @jackgr @preillyme

**Comment by karlkfi** [comment]
`http://<master>/ui` redirects to `http://<master>/api/v1/proxy/namespaces/default/services/kube-ui/#/dashboard/`

**Comment by F21** [comment]
Seeing the same problem here.

**Comment by akamalov** [comment]
If the question is to get to kube-ui, I've tried the following and it got me to <b>kube-ui</b>:

```
http://<kube-master-node>:8888/static/app/#/dashboard/
```

**Comment by bcbroussard** [comment]
If you are running off of master, the ui has been recently moved out into its own container - https://github.com/GoogleCloudPlatform/kubernetes/pull/10077. When using the salt scripts, a new kub-ui manifest file should be generated, and the container started by default. How are you starting your cluster?

The new container web ui can be launched manually with:
```
kubectl create -f cluster/addons/kube-ui/kube-ui-rc.yaml
kubectl create -f cluster/addons/kube-ui/kube-ui-svc.yaml
```

@timstclair it sounds like we may need to add some steps to the documentation. Mind taking a look?

@lavalamp @bgrant0607 Any ideas on how to ensure it is started by default now that it is not included in the kube-apiserver binary?

**Comment by timstclair** [comment]
I'll take another pass at the docs, but it should be enabled by default along with the other cluster addons. Are any of the other cluster addons running? You can check with:
```
kubectl get services,endpoints -l kubernetes.io/cluster-service="true"
```
The cluster addons are started according to the manifests in `/etc/kubernetes/addons/kube-ui`, so if those are absent that is the problem.
@bcbroussard if the addon manifests are not present, starting the UI manually will not work as the master will automatically take it back down.

**Comment by lavalamp** [comment]
If the addon script isn't running, you should be able to manually create addons as @bcbroussard says. (@timstclair correct me if I'm wrong, but I think the addon script is the only thing that would delete this? So it should be OK if it's not running at all?)

What cloud provider are you using? It may not start by default everywhere.

**Comment by karlkfi** [comment]
Thanks for the help! Wish I'd had all those comments a week ago. :)

I'm working on a new cluster setup for mesos, and we hadn't deployed the addon pod/service. After deploying it with the yaml in `cluster/addons/kube-ui` it came up as expected and was accessible via `http://<master>/ui`.

It was pretty confusing that the `/ui` redirect is built into the apiserver, but the ui itself isn't. Perhaps it would make sense to abstract that somehow so that it's possible to add other top level proxies. It'd also be nice if it were an actual proxy, instead of a redirect, to make the url cleaner.

It's pretty confusing that [docs/ui](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/ui.md) doesn't say anything about how to deploy the cluster addon. If you use a supported up to date kube-up it should be deployed for you, but when you're making a custom cluster it's unclear how to deploy it based on the docs.

It's also pretty confusing that the [www/README](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/www/README.md) is all about development and deploying, with nothing about usage or what to expect. And it seems kinda silly to have instructions for npm deployment when you can just deploy as a pod... The docs could use some love from someone who knows more about it.

Anyway, I'll leave this open for docs discussion, but my issue is resolved.

**Comment by lavalamp** [comment]
/ui is a redirect to /api/v1/proxy/namespaces/default/services/kube-ui/#/dashboard/, which is a proxy.

We moved the ui to an add-on pod to:
* Reduce security concerns from hosting UI directly from apiserver.
* Decouple UI & cluster version, making UI development easier.
* Make running the UI optional.

**Comment by timstclair** [comment]
@karlkfi thank you for outlining the specific issues you had with the docs. I created #10784 which I hope addresses most of your issues, except covering general dashboard usage information.

**Comment by karlkfi** [comment]
@lavalamp yeah I totally understand that it's an improvement to externalize the UI. It's just odd now that it gets a special hardcoded short url endpoint that you can't configure any other services to have.

**Comment by karlkfi** [comment]
I see the following follow-up issues have been created.
- #10097
- #10784

**Comment by karlkfi** [comment]
Closing. Just a documentation problem. Being addressed by other issues.
