### ISSUE TITLE
log aggregation

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#1071]
I spent most of the day actually trying to write a thing that ran on k8s. It seems clear that the most time consuming step is ssh into minion, find container, ```sudo docker log <long hex string>```. Providing an easy way to see your pod's log/exit notice would be a big usability win.

I think we can build a simple log aggregation application on top of k8s, and the only special thing we need to do is get kubelet to pipe logs over to it. I think we should do this soonish.

**Comment by bgrant0607** [comment]
We have EFK.
