### ISSUE TITLE
Fix Jube link in the wiki

### ISSUE THREAD

**Issue by bibryam** [GoogleCloudPlatform/kubernetes#10727]
Couldn't find what is the recommended way for PR to the wiki, so here is a diff 

diff --git a/Kubernetes-Community.md b/Kubernetes-Community.md
index 0ec7d3a..b2d52ec 100644
--- a/Kubernetes-Community.md
+++ b/Kubernetes-Community.md
@@ -14,7 +14,7 @@
 * [OpenStack on Kubernetes](https://github.com/stackforge/kolla)
 * [Apache Stratos](http://stratos.apache.org/)
 * [Java client](https://github.com/nirmal070125/KubernetesAPIJavaClient)
-* [Jube: Kubernetes in Java](http://jubeio.github.io/jube/)
+* [Jube: Kubernetes in Java](https://github.com/fabric8io/jube)
 * [Fabric8](http://fabric8.io/gitbook/)
 * [Circle CI](https://circleci.com/docs/docker#google-compute-engine-and-kubernetes)
 * [Digital Ocean](https://github.com/bketelsen/coreos-kubernetes-digitalocean)

**Comment by bprashanth** [comment]
@RichieEscarez who maintains the wiki?

**Comment by RichieEscarez** [comment]
Hi @bibryam, Im not sure (my first time trying to edit one of our wiki pages) but I found that I do have editing authority so Ive delivered the change. Please take a look:
https://github.com/GoogleCloudPlatform/kubernetes/wiki/Kubernetes-Community

**Comment by bibryam** [comment]
Yep, the link is fixed now. 
Thanks.
