### ISSUE TITLE
Cherry pick process

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#10730]
After 1.0, we've talked about the timeline for minor releases being longer (circa ~1mo), which means we'll be putting out more patch releases (1.0.1, 1.0.2, etc.) in the interim. Outside of developers, people are probably going to be running something closer to the `release-X.Y` branch, so release validation (#10676) is going to be very important as well.

Our current cherry pick "process" is very loose. We cobble together a list using an issue, or a label, and then we blast all of those commits together all at once as the patch version commit (e.g. #10559).

With a small amount of scripting, we can change this so that cherry picks are just proposed pull requests to the release branch. They can be completely automated, as a single commit with a small justification for the cherry pick. We could then decide on a group of people that were responsible for triage over the release branch (and maybe a small set with fastpath triage for hot stuff.)

This also has the added advantage that cherry-picks can just be trickled into the release branch gradually, and we would then either cut patch releases on cadence (i.e. "patch Tuesday") or immediately for a breakfix - and in the latter case we'd already know from validation that the other patches in the release branch are safe to ship as well.

The importance of this is also higher if the cadence of the minor releases is slower because the cherry picks will undoubtedly hit more and more conflicts towards the end of the cycle - validation after conflict resolution is doubly important.

c.f. #10709 (I'd update releasing.md after this)

cc @alex-mohr @goltermann @thockin @brendandburns @quinton-hoole

**Comment by thockin** [comment]
+1 - this needs to be really transparent and obvious.  Glomming commits
together into a cherry-pick is a terrible idea.

**Comment by zmerlynn** [comment]
@thockin: I hacked up something in #10757 that I think meets your "not smashing commits". I wish it were slightly more automated given the way PRs get automatically generated in GitHub (because I want the subject of these things to also tell us the original PR #), but I think it gets the job done and is thoroughly straightforward.
