### ISSUE TITLE
Readiness probe test flakes when image pulling is slow

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#10734]
If the container_probe test runs on a node without the nginx image, it sometimes takes > 90s to get the pod in running. Most of this time goes in pulling the image, so I'm assuming it's registry related hiccup. Using gcr.io might make it more reliable. 

Example failure: https://github.com/GoogleCloudPlatform/kubernetes/pull/10728#issuecomment-118623354. Note the following event in the logs:
```
INFO: event for nginx-c667459f-231b-11e5-8350-42010af07603: {kubelet pull-e2e-0-minion-5wmx} pulled: Successfully pulled image "nginx"
```

@mikedanese

**Comment by thockin** [comment]
a) we should not be pulling from docker in our tests - too hit-or-miss
b) we should replace nginx (132 MB) with
gcr.io/google_containers/test-webserver (4.5 MB) whenever possible.
