### ISSUE TITLE
Hazelcast (from examples/hazelcast) doesn't support namespaces and uses the old API

### ISSUE THREAD

**Issue by mwielgus** [GoogleCloudPlatform/kubernetes#10731]
It has the same problem as examples/cassandra (see #10231 and #10034) since the code for pod discovery is very similar ([Hazelcast](https://github.com/pires/hazelcast-kubernetes-bootstrapper/blob/master/src/main/java/com/github/pires/hazelcast/HazelcastDiscoveryController.java), [Cassandra](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java)).
Maybe we should create a tiny java library with this functionalty?

**Comment by bprashanth** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
@mwielgus , I think the change you made in #10231 is very good. I think it would be helpful if we make it a java library and reuse it in all related examples.

**Comment by mwielgus** [comment]
Fixed with #11146
