### ISSUE TITLE
Update heapster to use v1 API

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#10755]
I see that heapster is still issuing v1beta3 requests in e2e tests.
We need to update it to use v1 API.

We cant stop exposing v1beta3 in master, unless this is fixed (#10525)

Example request from e2e logs:
```
GET /api/v1beta3/namespaces: (719.741µs) 404 [[heapster/v0.19.3 (linux/amd64) kubernetes/unknown] 10.240.5.110:56593]
```

**Comment by nikhiljindal** [comment]
cc @dchen1107 @vmarmol @vishh @bgrant0607

**Comment by nikhiljindal** [comment]
Assigning this to @krousey since he had updated heapster for migrating it from beta1->3 and knows the steps.

**Comment by krousey** [comment]
@dchen1107 @nikhiljindal The PR is out. Once it's merged, a release will have to be pushed. Then we can update `cluster/addons/monitoring/...` to point to the new release.

**Comment by nikhiljindal** [comment]
Latest heapster image pushed.
