### ISSUE TITLE
Rebuild kube2sky with fixed client (to emit v1 API)

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10761]
Apparently the client libs were fixed after our 1.10.  We need to rebuild a v1.11 with no code changes but client lib.

**Comment by zmerlynn** [comment]
c.f. #10754

**Comment by ArtfulCoder** [comment]
#10771 
Verifying..

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10771
