### ISSUE TITLE
Resource management guidance for addons containers

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#10779]
#10653 and #10778 are merged to allocate resource limit (cpu and memory) for all addon containers based on current default configuration for GCE / GKE and AWS: 4 nodes, 30~50 pods per node based on #10335. We should provide scaling guidance and steps for cluster users to update their addon services based on cluster size and workloads. 

cc/ @bgrant0607

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by bprashanth** [comment]
Maybe we should add a best practices for production clusters section? We did a lot of tweaking and tuning to hit our perf goals for the 100 node cluster, and it would be great if we can rope in people who have experience running large clusters (redhat/coreos?) for their thoughts. 

I mean things like:
- qps, max-pods-per-node, ulimit settings
- kubelet/pausepod/container gc overhead
- gomaxprocs for etcd, apiserver etc
- master size, using a pd/ssd for etcd

Would be good if we could protect users from having to figure this out the hard way. @fgrzadkowski @wojtek-t wdyt?

**Comment by davidopp** [comment]
My only concern is that as we modify Kubernetes to hit 1000, pods a lot of that will probably change.

**Comment by bprashanth** [comment]
It would be a 1.0 doc

**Comment by davidopp** [comment]
I see. If it was versioned with 1.0 that makes sense.

(Also, not sure how "pods" got into my last response...)

**Comment by mconigliaro** [comment]
:+1:
