### ISSUE TITLE
flakey e2e test: Docker Containers should be able to override the image's default command  (Failed 3 times in the last 30 runs. Stability: 90 %)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#10798]

**Comment by wojtek-t** [comment]
This should hopefully be fixed by #10880

At least - I didn't see any failure of that test since that PR was merged.

cc @saad-ali

**Comment by saad-ali** [comment]
Yep, this should be fixed by #10880. There have been no failures of the `...should be able to override the image's default ...` tests since that PR was merged.

Please reopen #7840 if we notice failures again.
