### ISSUE TITLE
Create a single kubernetes binary for all cmds

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#108]
As we start building a bunch of binaries the size of our output goes up.  Because of go static linking, we end up with 8-10MB for each binary.  Currently we 7 of these for a total of 58M (`find output/go -type f -perm +111 | xargs du -ch`).

If we created a single binary with a switch for which functionality users want we would have a single binary that would adapt as necessary and probably be ~10M.

I'd image we'd call this thing `kube` and by default it'd be the client binary.  If you want to run a server component you would do something like `kube --daemon=api-server`.

Thoughts?

**Comment by kelseyhightower** [comment]
@bgrant0607 This one seems to be done now that we have hyperkube.

**Comment by bgrant0607** [comment]
Agree.

**Comment by maicohjf** [comment]
> As we start building a bunch of binaries the size of our output goes up. Because of go static linking, we end up with 8-10MB for each binary. Currently we 7 of these for a total of 58M (`find output/go -type f -perm +111 | xargs du -ch`).
> 
> If we created a single binary with a switch for which functionality users want we would have a single binary that would adapt as necessary and probably be ~10M.
> 
> I'd image we'd call this thing `kube` and by default it'd be the client binary. If you want to run a server component you would do something like `kube --daemon=api-server`.
> 
> Thoughts?

Create a file /opt/KUCC00302/kucc00302.txt that lists all pods that implement Service foo in
Namespace production.
The format of the file should be one pod name per line.

kubectl get svc -o wide -n production
得到label
kubectl get pod -l label=value |awk '{print $1}' |grep -v "NAME" >> /opt/KUCC00302/kucc00302.txt
kubectl get po -l label
