### ISSUE TITLE
Kubectl-proxy to support polling and socket.io

### ISSUE THREAD

**Issue by KSanthanam** [GoogleCloudPlatform/kubernetes#10809]
I have a node.js pod that uses socket.io for polling. I configured my nginx pod for polling with
ip_hash &              
proxy_set_header Connection upgrade;

so that subsequent requests are forwarded to the same service. However kubctl-porxy  configuration is not accessible to me to do the same from Service to POD.

How to do I alter the parameters for kubectl-proxy?

Currently I am experimenting hardcoding the list of node ip addresses in my nginx.conf. Which defeats the purpose of self contained docker image.

Thank you so much in advance.

**Comment by KSanthanam** [comment]
Is SessionAffinity the answer to my question? Can you please guide.

**Comment by yujuhong** [comment]
@KSanthanam, `SessionAffinity` allows the backend of a service to be chosen based on the client IP, so that the same client goes to the same backend. See [Services.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#virtual-ips-and-service-proxies) for more details. It looks like this should suit your case of service-> pod mapping.

**Comment by KSanthanam** [comment]
Thank you @yujuhong . I tried this but, I can see the traffic is being distributed. 
Below is my service.yaml (properly indended, but not showing up here). My Nginx receives the request and forwards. I have also given my NGINX.conf which forwards the IP Address. What am I doing wrong here? Thank you so much in advance.



apiVersion: v1
kind: Service
metadata:
labels:
    name: control
  name: control
  namespace: dn
spec:
  ports:
    - port: 3000
      containerPort: nodejs-control-server
      name: express-server
  selector:
    name: control
  sessionAffinity: ClientIP

#NGINX
worker_processes 4;
events { worker_connections 400; }
http {
   upstream control { server Express-Cluster-Service:3000; }
   server {
        listen 80;
        # server context
        proxy_http_version 1.1;
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        location / {
          proxy_pass http://control;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_cache_bypass $http_upgrade;
        }
    }
}

**Comment by thockin** [comment]
Can you clarify how you are testing this?   Session affinity works for me and is covered by tests.

Can you read back your Service with kubectl get -o yaml?

**Comment by KSanthanam** [comment]
Sorry @thockin , It was a problem with my yaml for nginx. Once I set the sessionAffinity to Client-IP for nginx service ALSO, kubernetes was directing the traffic to the sane node.js service everytime. 

nginx servide (with ClientIP) -> was directing to the same node.js pod in node.js service (client IP). 

Previously my nginx service's sessionAffinity was set to None.. 

I have a related question. Is it a best practice to have just one NGINX replication controller per cluster? SHould this be more than one?

**Comment by thockin** [comment]
What you do with nginx depends entirely on your application(s) and how you
use your cluster.  I can not prescribe an answer for that.
