### ISSUE TITLE
DNS broken after GKE upgrade

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#10850]
The Jenkins job for GKE upgrade, step 3 (e2e) has been failing since the 4:40pm (PST) run yesterday because of the following DNS problems:

```
DNS should provide DNS for the cluster

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:226
Unexpected number of pods (0) matches the label selector k8s-app=kube-dns,kubernetes.io/cluster-service=true


DNS should provide DNS for services

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:311
Unexpected number of pods (0) matches the label selector k8s-app=kube-dns,kubernetes.io/cluster-service=true
```

This is **after** the cluster is upgraded.

**Comment by mbforbes** [comment]
+cc @yujuhong @quinton-hoole @ixdy for triage / suggestions; @yujuhong mentioned #10711 as a possibility.

**Comment by roberthbailey** [comment]
This was almost certainly broken by https://github.com/GoogleCloudPlatform/kubernetes/pull/10487 which was merged at 3:35pm yesterday.

**Comment by satnam6502** [comment]
cc @marekbiskup

**Comment by quinton-hoole** [comment]
Yup, my money would be on #10487.  Should not be too difficult to track down the bug, given that GCE is working just fine.  I'd advise against rolling back #10487 if feasible, and rather debug the GKE end of the problem.

**Comment by satnam6502** [comment]
Staring at the test it is not clear if anything is wrong with it -- perhaps we need to look at the upgrade code.

**Comment by roberthbailey** [comment]
I believe that many of the e2e tests begin to fail if DNS isn't working, which to me implies that this is a problem with the test since the failures are isolated to just these two tests. 

As a side note, I think that this failure is actually correct in the sense that it is catching a legitimate behavioral change between the latest release (0.20.2) and head -- if someone was running code that depended upon the DNS pods to be running in the default namespace and we moved them away then their code would break. In this case, the break was intentional, but it's a behavioral change none the less.

**Comment by dchen1107** [comment]
@yujuhong also reported the test failure after upgrade test due to no node is ready in test cluster. We checked it, and found cbr0 is not configured because master never allocate ip range to node, and docker refuse to start.

**Comment by roberthbailey** [comment]
The code at head selects DNS pods from the system namespace. The code from the 0.20.2 release selects DNS pods from the default namespace. Right now this test is running the e2e test code from the latest release against a cluster that has been upgraded to HEAD.

**Comment by mbforbes** [comment]
Thanks for the debugging, all—as Robby said, this catches a behavioral change, which is good. To have the tests pass, we'll want to run the updated tests after an upgrade (this is my next task). I'll mark this as release-note and close it.
