### ISSUE TITLE
kubectl reports no pods after fresh deploy

### ISSUE THREAD

**Issue by mvdan** [GoogleCloudPlatform/kubernetes#10874]
On master, running `./hack/dev-build-and-up.sh` works and deploys fine. The grafana UI works just fine. Accessing `/api/v1/pods` does show the current pods, but `kubectl get pods` returns an empty list:

```
 % kubectl get services,rc,pods
NAME         LABELS                                    SELECTOR   IP(S)      PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>     10.0.0.1   443/TCP
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
NAME      READY     STATUS    RESTARTS   AGE
```

As you can see, the rc list is also empty. Weird because everything seems to work just fine, and the API reports these just fine. But kubectl won't.

Tried the same process on v0.20.2 and it worked just fine, including kubectl. FWIW this worked yesterday and broke this morning after I ran `git pull`. Can't say which commit caused this but I can git bisect this issue if necessary.

**Comment by dchen1107** [comment]
Try kubectl get services, rc, pods --all-namespaces. A recent merged PR moved all addons to a different namespace: kube-system

**Comment by yujuhong** [comment]
We recently moved all cluster add-ons from `default` to a different namespace `kube-system`. If you run `kubectl get pods --all-namespaces`, it should show you all pods in all namespaces.

**Comment by mvdan** [comment]
Makes sense, thanks for the quick reply and apologies for the noise.
