### ISSUE TITLE
AWS is broken in 0.20.2

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#10908]
Several problems:
  * /var/lib/kubelet/kubeconfig fails to install
  * Lots of races in Docker startup cause docker to fail and salt to get borked up.

**Comment by thockin** [comment]
@justinsb known?

**Comment by justinsb** [comment]
I've definitely been focused on the systemd patches & 15.04.  But I wasn't aware that things were as bad as that on "mainline".  I can have a look tomorrow morning.

**Comment by brendandburns** [comment]
Fixed in https://github.com/GoogleCloudPlatform/kubernetes/pull/10877

**Comment by brendandburns** [comment]
@justinsb no need to look (except to review the PR ;)

**Comment by brendandburns** [comment]
Closed by #10877
