### ISSUE TITLE
Creating a privileged container

### ISSUE THREAD

**Issue by satyajitpadhyewit** [GoogleCloudPlatform/kubernetes#10919]
I want to start a privileged container by Kubernetes. I did follow earlier posts https://github.com/GoogleCloudPlatform/kubernetes/issues/391 and I did the following:-
* written privileged:true in the pod json file
* updated allow_privileged:true in /kubernetes/cluster/saltbase/pillar/privilege.sls
* added --allow_privileged=true in /etc/default/kubelet & kube-apiserver

Still unable to start a privileged container.Any solution?

**Comment by thockin** [comment]
Did you confirm that kubelet and apiserver are actually running with the
right flags?  What error are you getting?

**Comment by satyajitpadhyewit** [comment]
Being a newbie, can you tell me how to confirm that kubelet and apiserver are running with right flags?
Since I have only done the above updations as mentioned in the question.

**Comment by roberthbailey** [comment]
Log into the master and run `ps -elf | grep kube-apiserver` and look at the command line flags. Log into a node and run `ps -elf | grep kubelet` and look at the command line flags. Do you see `--allow_privileged` being passed in?

**Comment by satyajitpadhyewit** [comment]
Thank you robert and thockin. I restarted the kebelet and apiserver daemons and tried to grep for the changes as mentioned above. Its working and I can create privileged containers by kuebernetes.
