### ISSUE TITLE
Cluster dns should survive etcd restart

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#10926]
We can either give dns etcd its own volume or restart kube2sky as well so it repopulates records if the  etcd restarts @thockin @ArtfulCoder

**Comment by ArtfulCoder** [comment]
I believe if we give etcd container an emptydir in the podspec, then a restart should give etcd the same dir again. If this is true , it should be a 5 line fix in the pod spec.

**Comment by thockin** [comment]
Yeah, I think an emptyDir is exactly the right fit.  Abhishek, do you have
time?

**Comment by ArtfulCoder** [comment]
sure, I will do it.

**Comment by ArtfulCoder** [comment]
Dawn is helping out. Thanks Dawn!

**Comment by thockin** [comment]
Dawn, do you actually have time for this?

**Comment by ArtfulCoder** [comment]
I will do it by tomorrow.

**Comment by bprashanth** [comment]
Feel free to assign it to me, I already have it tested locally for my other change

**Comment by thockin** [comment]
This needs to be in ASAP  Like before 10am

**Comment by quinton-hoole** [comment]
No priority on this one.  p1?

**Comment by thockin** [comment]
P1 assigned, fix is in flight.

**Comment by wojtek-t** [comment]
IIUC - #11055 was a fix for this. Can we close this issue now?

**Comment by ArtfulCoder** [comment]
This is fixed.
