### ISSUE TITLE
Mesos Getting Started - quay.io/coreos/etcd:v2.0.12 docker image error

### ISSUE THREAD

**Issue by jrcrawfo** [GoogleCloudPlatform/kubernetes#10943]
When trying to get Kubernetes running on top of Mesos, the docker image pulled from quay.io/coreos/etcd:v2.0.12 (as referenced in the getting started guide) doesn't expose its ports correctly or is misconfigured. 

When the container is running and you run the following command to test, the connection is refused from the server: 

`curl -L http://${KUBERNETES_MASTER_IP}:4001/v2/keys/`

The current work-around I found is to install the standard coreos/etcd image, which was in the guide previously:

`sudo docker run -d --hostname $(uname -n) --name etcd -p 4001:4001 -p 7001:7001 coreos/etcd`

 I noticed the image to run was changed 23 days ago in dc7a9c87926723dd7dfde6c1f2f8f608c4e2646c.

**Comment by karlkfi** [comment]
The coreos/etcd in dockerhub is ancient. The quay.io registry is the canonical repo updated by CoreOS. Did you specify `-p 4001:4001`?

**Comment by karlkfi** [comment]
I think the latest version listens on 127.0.0.1 by default, which is limited to local access. You'll probably need to append `-listen-client-urls http://0.0.0.0:4001` to your docker command.

**Comment by jdef** [comment]
it looks like the mesos getting started guide has this parameter in the `docker run` command to start etcd. closing this out.
