### ISSUE TITLE
Fixed masquerading rule on minions

### ISSUE THREAD

**Issue by caetanovendrami** [GoogleCloudPlatform/kubernetes#10955]
Kubelet on minions is creating an iptables rule for masking any connections except for 10.0.0.0/8 which is a fixed rule in pkg/kubelet/container_bridge.go.
I think it should be the ${CLUSTER_SUBNET} (which varies from provider to provider). Due to that rule I can't connect to an outside service on a different network (eg 10.100.0.0/16) which is out of my cluster address space. As a current workaround I can ssh to minions and add iptables rules to my private networks. Something like  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE -d 10.0.0.0/16 and everything goes well.

**Comment by thockin** [comment]
Folding into #11204
