### ISSUE TITLE
Generate static, object-focused documentation of types

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#10966]
Users should not have to read our go code to get documentation of the API types.  They could use swagger-ui.  But the swagger-ui is also not a good presentation because:
- It presents too much info about REST that is not relevant to most users:
  - it talks about POST, etc.  However, people are mostly going to use either Kubectl or pkg/client.  Those don't use the word POST.  Kubectl uses "create" and pkg/client uses "Create()".
  - it talks about the URLs.  However several parts of the url (api version, namespace) are not things that users normally need to think about when they are using Kubectl.  Mostly they just want to know what fields can be used and what they mean.
  - you have to click several times to find the schema on the swagger-ui page.
- It is not as accessible as markdown documentation
   - I don't think that the swagger-ui schema blurbs will be indexed in same way that github.com markdown docs are.
  - is is a different style than the markdown docs.
  - swagger inlines all subtypes in each object's schema.  This makes the schema overwhelming and defeats the grouping of related things that can be ignored as a group like SecurityContext or various volume plugins.  I'd rather there were links to subobjects. 

Therefore, we should generate markdown docs for the API types (but not the REST endpoints).
We could maybe generate this using a go program that reflects the struct tags from all the types in pkg/api/v1/types.go.

**Comment by erictune** [comment]
I think this is related to #3060

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
FWIW, if all we care about an API type is its description tag, then we can parse the files in api/swagger-spec.

**Comment by erictune** [comment]
yes let's do that for now.

**Comment by erictune** [comment]
Proposal:
```
for each version in [v1, ...] do:
open api_obects_$VERSION.md
  for each key in "models":
    print subheading for key minus the $VERSION prefix.  this allows easy
linking from other .md
    for each key in properties:
      print "**$NAME**  *$TYPE* $DESCRIPTION\n"
      in case of $ref link to bookmark in this file.
```

**Comment by caesarxuchao** [comment]
SGTM. Do you want to code it up or shall I? I'd be happy to do it.

**Comment by caesarxuchao** [comment]
Oh, we can parse the model.description for easy API type as well. go-restful will generate model.description, but we have filled in content yet. #5331

**Comment by erictune** [comment]
Go for it.

**Comment by caesarxuchao** [comment]
I used json.Unmarshal to unmarshel the spec file to swagger.apiDeclaration. The only problem with this approach is that it doesn't preserve the order of the fields, which is a known problem :(

**Comment by caesarxuchao** [comment]
FWIW, go-restful/swagger.ModelList.UnmarshalJSON also mess the order. It looks like we need a customized UnmashalJSON.

ref #10311

**Comment by erictune** [comment]
Let's get the basic information in a doc first and then fix up the order in
a later PR.

**Comment by caesarxuchao** [comment]
#10933 is related. Once #10933 is in, we can adapt its WriteSwaggerDocFunc() to write the .md docs.

**Comment by bgrant0607** [comment]
See also #9097

**Comment by caesarxuchao** [comment]
We have http://kubernetes.io/v1.0/docs/api-reference/definitions.html and http://kubernetes.io/v1.0/docs/api-reference/operations.html now. Close this issue.

Future improvements to those pages include: #11567
