### ISSUE TITLE
Vagrant: certificate is valid for 192.168.56.101, 10.247.0.1, not 10.245.1.2

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#10972]
While trying to test my systemd changed with vagrant, I am now getting this error during `go run hack/e2e.go -v --up`:

```
error: couldn't read version from server: Get https://10.245.1.2/api: x509: certificate is valid for 192.168.56.101, 10.247.0.1, not 10.245.1.2
```

I wonder if it is related to the removal of cert_ip in e2ddd2dd7bb617600768d89e2ab229fd16091c55 ?

Is there a workaround I'm missing (running vagrant on Linux with VirtualBox)?

**Comment by justinsb** [comment]
cc @derekwaynecarr

**Comment by AlexeyKupershtokh** [comment]
Reproduced on v0.21.1.
```
export KUBERNETES_PROVIDER=vagrant
cluster/kube-up.sh
```
finishes with the same error message:
```
Validating master
Validating minion-1
........
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: x509: certificate is valid for 192.168.56.101, 10.247.0.1, not 10.245.1.2
```

**Comment by derekwaynecarr** [comment]
I wasn't seeing that but I will investigate in the morning.  There is no
harm in re-adding cert_ip.  Will check certs for me in morning.  Thanks for
taking the time to assist.

**Comment by dchen1107** [comment]
I ran into the same problem this morning on GCE  during go run hack/e2e.go -v --test, not --up. I teared down the cluster, and couldn't reproduce the issue. Since I did some local hacks, I thought it must be my fault. Now looks like it might be a real issue.
