### ISSUE TITLE
Rewrite services shell e2e test in go

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#10980]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/e2e-suite/services.sh

This should be rewritten in Go, so that we will be reusing the whole testing infrastructure in all places (instead of maintaining another set of infrastructure in bash).

**Comment by zmerlynn** [comment]
This is a dupe of #4184. And go for it. :)

**Comment by wojtek-t** [comment]
Thanks @zmerlynn - I was trying to find that issue and didn't manage. I will try to do it after 1.0.
