### ISSUE TITLE
We need a documentation describing how to configure kubectl.

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#10984]
Currently it's done automatically on the machine from which you create the cluster, but if you want to use another one to interact with the cluster (or create a cluster using GKE) one need to run a few things. I managed to do it by following few different documents/getting started, but I believe it should be gathered and put into kubectl doc.

Assigning @bgrant0607 to reassign or say that it's 'working as intended'

**Comment by bgrant0607** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/sharing-clusters.md

**Comment by bgrant0607** [comment]
Added a sentence with a link to the above doc to the in-progress user guide.
