### ISSUE TITLE
Feedback from a hackathon with Bol.com and Xebia engineers

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#10992]
I joined Bol.com and Xebia engineers for a one-day hackathon. We were trying to deploy a service on a kubernetes cluster. We used the kuberentes release provided by GKE, probably 19.x.

Here are summary of issues that can be fixed (I'll create a separate issue to discuss new features):
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md -  the command to create the firewall is wrong - rule name must be just after create
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ gcloud compute firewall-rules create --network=default --description "test" --allow tcp:22 testrule
WARNING: Lists should be separated by commas, try "--allow tcp:22,testrule". If you intend to use testrule for positional arguments, put them before the flag.
usage: gcloud compute firewall-rules create  NAME --allow PROTOCOL[:PORT[-PORT]],[PROTOCOL[:PORT[-PORT]],...] [optional flags]
ERROR: (gcloud.compute.firewall-rules.create) too few arguments
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ gcloud compute firewall-rules create testrule --network=default --description "test" --allow tcp:22 
Created [https://www.googleapis.com/compute/v1/projects/google.com:biskup-kubernetes/global/firewalls/testrule].
NAME     NETWORK SRC_RANGES RULES  SRC_TAGS TARGET_TAGS
testrule default 0.0.0.0/0  tcp:22

 2. In our examples we always create an RC before creating a Service. Then spreading doesn't work.

 3. posting a pod to the API server without a namespace in the url doesn't work (even though it is described in the swagger API). the namespace in the url seems to be required.

 4. we don't have any doc describing which fields in the API are required

 5. kube-ctl rolling-update seems to be broken: 
kubectl rolling-update rc --image=image
kubectl rolling-update rc newrc --image=image
We managed to run only with -f option.

 6. There is no example for rolling-update

 7. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/simple-rolling-update.md - says `kubectl rolling update rc` - but rc parameter is not accepted

 8. In general, scale command has no reasonable error messages (create does print good messages). (We had problems with an rc having a rw pd. Scale failed, but there was no messages).

 9. kubectl does not have auto-completion. (or is it broken?)

**Comment by marekbiskup** [comment]
I will check all the problems listed and fix them (if easy), or report another bug (if complicated).

**Comment by thockin** [comment]
Thanks!  I can confirm the firewall rule one, at least :)

**Comment by marekbiskup** [comment]
Status:
1. corrected in #11143
2. reported #11144
3. to be investigated
4. to be investigated
5. we will ignore the error (see below)
6. we found one here: examples/update-demo
7. fixed in #11145
8. reported #11148
9. to be confirmed


Ad. 5
from @brendandburns:
I sorted out the kubectl rolling-update issue.  There is an issue with kubectl 0.20.1 and 0.19.3 clusters, you need to explicitly make kubectl 0.20.1 use the v1beta3 api by adding:

kubectl rolling-update --api-version=v1beta3 nginx --image=<next-image>

There must be a bug in our conversion code somewhere, but given that we have deprecated and removed v1beta3, it's likely not worth going back to fix the bug.



Remaining points:
3. to be investigated
4. to be investigated
9. to be confirmed

**Comment by marekbiskup** [comment]
4. we don't have any doc describing which fields in the API are required
#11214

Remaining: 3, 9.

**Comment by marekbiskup** [comment]
3. posting a pod to the API server without a namespace in the url doesn't work (even though it is described in the swagger API). the namespace in the url seems to be required.

reported #11218

**Comment by marekbiskup** [comment]
for 9:
Automcompletion works well, but has to be installed. I reported #11310 to include this information in the doc.

**Comment by marekbiskup** [comment]
All issues mentioned here were resolved or delegated to other issues.
