### ISSUE TITLE
e2e/networking.go broken on GCE and GKE

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#11014]
Starting between 8:30 and 9:20 PST this morning:

```
Networking should function for intra-pod communication

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:250
Timed out. Cleaning up. Details:
{
"Hostname": "nettest-l1bmr",
"Sent": null,
"Received": null,
"Errors": null,
"Log": [
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again.",
"Unable to read the endpoints for e2e-tests-nettest-tjw3p/nettest: the server could not find the requested resource; will try again."
],
"StillContactingPeers": true
}
```

**Comment by mbforbes** [comment]
+cc @alex-mohr @vmarmol

**Comment by mbforbes** [comment]
I don't see an easy culprit. Wild guess #10525 as appears to be only meaty thing in that time frame? Alternatively, consistent underlying GCE problems?

**Comment by vmarmol** [comment]
We've been tracking some GCE issues, possibly related.

+cc @ixdy @quinton-hoole

**Comment by ixdy** [comment]
GCE issues seem to be resolved now, but the test is still failing. My best guess is that #10525 broke things. Also note that this networking test is not run on the per-PR Jenkins.

cc @nikhiljindal

**Comment by nikhiljindal** [comment]
Looking at the logs to see if its due to v1beta3 deletion.

**Comment by ixdy** [comment]
This test appears to be using gcr.io/google_containers/nettest:1.4.

This image was built on May 29, 2015. Was that before the default API version was switched to v1?

**Comment by ixdy** [comment]
#9269 was merged June 4.

Probably building a new version of gcr.io/google_containers/nettest and updating the config is sufficient?

**Comment by nikhiljindal** [comment]
I see v1beta3 requests like the following in test logs:

```
GET /api/v1beta3/namespaces/e2e-tests-nettest-28efz/endpoints/nettest: (604.592µs) 404 [[webserver/v0.17.1 (linux/amd64) kubernetes/unknown] 10.240.7.113:50345]
```

I wonder which webserver this is, which is emitting v1beta3 requests

**Comment by nikhiljindal** [comment]
oh yes. @ixdy  you are right, the container running  gcr.io/google_containers/nettest:1.4 is named "webserver": https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/for-tests/network-tester/rc.json.
Updating the image should fix this.

**Comment by ixdy** [comment]
Yes, the webserver here is [contrib/for-tests/network-tester/webserver.go](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/for-tests/network-tester/webserver.go).

**Comment by ixdy** [comment]
@nikhiljindal are you going to take care of updating the image and config?

**Comment by nikhiljindal** [comment]
sure I can do that

**Comment by ixdy** [comment]
OK, assigning this to you, then! :)

I'll review your config changes.

**Comment by nikhiljindal** [comment]
Pushed the updated image.
Sent https://github.com/GoogleCloudPlatform/kubernetes/issues/11014 for updating the config file

**Comment by quinton-hoole** [comment]
@ixdy Is there any reason that this test should not be part of the per-PR e2e test suite?

**Comment by ixdy** [comment]
It's listed in GCE_PARALLEL_FLAKY_TEST_REGEX and has been for a while.

I don't know whether it's still too flaky to run in the regular parallel builds.
