### ISSUE TITLE
Controlling UID/GID of EmptyDir volume

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#11020]
Currently the emptyDir volume is owned by root:root.  Long-term, the uid/gid of this type of volume (and others based on it) should be set by the effective uid/gid of the container.

I'll write more on this later, wanted to create the issue before I forgot about this.  Spoiler alert: I think we can do this only for limited cases without the user namespace.

@thockin @erictune @ncdc @eparis @timothysc 

It's arguable that other volume types should handle this too.

@jmccormick2001 is hitting this currently with emptyDir and nfs IIRC

**Comment by timstclair** [comment]
@timothysc

**Comment by eparis** [comment]
much as docker added the :z and :Z to volume mounts, I feel like we'd be better suited adding a :u or something to the volume mount and telling docker to use it's knowledge of the uid/gid and chown -R down at that level.  But obviously we'd need to be able to make use of that feature up in kube.

**Comment by pmorie** [comment]
@eparis yep, that is one possibility I was going to mention.  If we rely on the container runtime to do this, we should make sure that it's well-known that container runtimes need to do this kind of thing.

**Comment by thockin** [comment]
Is this a dup of the other issue about volumes and non-root ?

**Comment by markturansky** [comment]
NFS requires the same (do i presume all volumes?).

**Comment by eparis** [comment]
While the solution might be useful on NFS, emptyDir is a bit special.  With NFS it is "possible" to set the uid/gid/selinux context/etc before kubernetes gets involved.  With emptyDir is kubernetes which 'creates' the empty tmpfs filesystem, and thus only kubernetes (or docker later) can fix the uid/gid/label/etc.

So the feature is likely applicable, the bug is not quite the exact same. (meaningless distinction, I know)

**Comment by markturansky** [comment]
@eparis thanks for the distinction.  I like learning the nuances.

We'll need to discuss security around NFS in another thread, because the current implementation requires a wide open share that PV only provides obfuscation for.

**Comment by pmorie** [comment]
@thockin 

> Is this a dup of the other issue about volumes and non-root ?

I don't think the other one encompasses ownership, but I will check

**Comment by pmorie** [comment]
My bad, @thockin 

Closing as a dupe of #9384
