### ISSUE TITLE
master HEAD is busted

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#11031]
edaa1a69e587db4588e10f1e198ad7525362d1a6 causes the updated deep-copies and conversions go nuts

@nikhiljindal 

I have no idea why shippable is not catching this.

**Comment by thockin** [comment]
shippable doesn't run those!

**Comment by nikhiljindal** [comment]
Looking at this now

**Comment by derekwaynecarr** [comment]
I thought it was just me :-)   Now I don't feel so bad for debugging this
for an hour this afternoon.

**Comment by thockin** [comment]
#11032 will hopefully "fix" shippable to break on this

**Comment by nikhiljindal** [comment]
Fixing this in https://github.com/GoogleCloudPlatform/kubernetes/pull/11039
