### ISSUE TITLE
kubectl simple rolling update fails

### ISSUE THREAD

**Issue by mrmiroslav** [GoogleCloudPlatform/kubernetes#11049]
```kubectl rolling-update frontend --dry-run=true --image=eu.gcr.io/<project>/<image>``` fails with error: ```may not update fields other than container.image```

Full Error:
```
Error updating pod (Pod "frontend-q23wc" is invalid: spec: invalid value '{Volumes:[{Name ... ... ... HostNetwork:false ImagePullSecrets:<nil>}': may not update fields other than container.image), retrying after 3 seconds
```

**Comment by al3xdm** [comment]
Item 5 on this list looks like other people have encountered this too: https://github.com/GoogleCloudPlatform/kubernetes/issues/10992

**Comment by brendandburns** [comment]
I will look into this today.

**Comment by brendandburns** [comment]
Ok, this appears to be a problem in version skew.

kubectl 0.20.1 doesn't work with rolling-update and version = v1.

The work around is adding ```--api-version=v1beta3```

e.g.

```kubectl rolling-update --api-version=v1beta3 nginx --image=redis```
