### ISSUE TITLE
Update-demo-nautilus: no route to host

### ISSUE THREAD

**Issue by suyogbarve** [GoogleCloudPlatform/kubernetes#11058]
My Configuration: 
Baremetal Centos machines as follows:
Kube_master: 10.101.109.73
Kube_node1: 10.101.109.84 
Kube_node2: 10.101.109.69

I am trying to use Update-Demo example.
The proxy server is running on Kube_master.

My kubernetes master is unable to talk to any of the pods.

curl http://kube_master:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-z7x57/data.json 
results in following error
Error: 'dial tcp 172.17.0.4:80: no route to host'

**Comment by brendandburns** [comment]
It looks to me like your networking isn't set up correctly.  You need to make sure that you can ping/connect to the Pod IP address range from all machines?

What are you using for the networking setup?  You probably need to set up CoreOS Flannel, or something like that.

--brendan

**Comment by suyogbarve** [comment]
I am trying to use Flannel on nodes, let me recheck my n/w setup.
