### ISSUE TITLE
test/networking - should function for intra-pod communication FAILING this morning.

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#11061]
http://fpaste.org/242697/14365404/

As of this morning only.  

Question: Is DNS now forced?  b/c the test used to pass w/o b4. 

cc @jayunit100 @rrati @eparis @roberthbailey @thockin

**Comment by brendandburns** [comment]
See:

https://github.com/GoogleCloudPlatform/kubernetes/pull/11035

For the fix, it was merged last night.

tl; dr; We switched the test container to the v1 API from v1beta3

**Comment by jayunit100** [comment]
fails on hack/local-up-cluster.sh as well, trivial to reproduce

**Comment by timothysc** [comment]
@brendandburns ^ different error from last night, but same spot.
