### ISSUE TITLE
Reboot (and probably many other) tests no longer have pods to look at

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#11079]
They used to look at all pods in the default namespace, which used to contain all of the vital infrastructure pods. The purpose of looking at these was to ensure the system was fully healthy after a reboot, restart, upgrade, etc.

However, now I see in the test:

```
INFO: Wanted all 0 pods to be running and ready. Result: true. Pods: []
```

I'm guessing this was related to the big namespace change? When moving all of the pods out of the default namespace we must have forgotten to update all of the tests that check the infrastructure pods.

I think this is fairly important because all of these tests are far weaker as a result. (We've caught many bugs in DNS, elasticsearch, kubelet, salt, ... by ensuring pods are running & ready in tests.)

Relatedly, if we switch the minimum here from 0 to 1 in GCE (it was 1 before), we could catch a test regression like this from happening again.

**Comment by mbforbes** [comment]
+cc @satnam6502 might this have been you? :-)

**Comment by satnam6502** [comment]
Probably. Drat. I thought I had cleared everything before going on vacation!

**Comment by ixdy** [comment]
Argh. I will work on fixing the minimum startup pods value for GCE Jenkins right away.

**Comment by mbforbes** [comment]
Thank you @ixdy! The regression in the 1&rarr;0 change is largely my fault because I didn't fight back hard enough or make sure it's used in GCE.
