### ISSUE TITLE
kubectl port-forward should accept a pod without -p

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#11089]
Similar to #8448 -- we fixed exec to match logs, but didn't notice that port-forward has the same problem.

cc @brendandburns @ncdc

**Comment by feihujiang** [comment]
@bgrant0607  Is there anybody to work on this? Just three days ago, I newed a PR  #10913 to fix small nits for this command. So if there is nobody, I'd like to work on this.

**Comment by JanetKuo** [comment]
Solved with #11138.
