### ISSUE TITLE
skydns always restart in a loop

### ISSUE THREAD

**Issue by Icedroid** [GoogleCloudPlatform/kubernetes#11101]
I has sucked in this problem for two whole days. I can't setup kubernetes cluster DNS successfully.Who could help me? Thank you.
```
# kubectl logs kube-dns-v1-q83yp skydns
2015/07/11 02:01:22 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [2]
2015/07/11 02:01:22 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/07/11 02:01:22 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0

#kubectl logs kube-dns-v1-q83yp kube2sky
I0711 02:01:49.049421       1 kube2sky.go:318] Etcd server found: http://127.0.0.1:4001
F0711 02:01:50.050863       1 kube2sky.go:431] Failed to create a kubernetes client: stat /etc/dns_token/kubeconfig: no such file or directory
```

About my used version info is:
```
# docker images
REPOSITORY                                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/google_containers/kube2sky                  1.7                 916d1b51d1d5        5 weeks ago         14.61 MB
docker.io/busybox                                  latest              8c2e06607696        12 weeks ago        2.43 MB
gcr.io/google_containers/etcd                      2.0.9               b6b9a86dc06a        3 months ago        12.82 MB
gcr.io/google_containers/skydns                    2015-03-11-001      791ddf327076        4 months ago        8.811 MB

# kubectl version
Client Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.0-157-g5520386b180d3d", GitCommit:"5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.0-157-g5520386b180d3d", GitCommit:"5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3", GitTreeState:"clean"}
```

**Comment by thockin** [comment]
the dns_token is no longer needed.  If you have your certs configured (see
recent messages here or google-containers about this topic) kube2sky will
"just work".  #10265

**Comment by roberthbailey** [comment]
Note that this is fixed only in newer version of kubernetes. If you really want to use version 0.18.x you will need to manually create a dns token and stick it into a secret.

**Comment by Icedroid** [comment]
@thockin You mean the kubernetes version 0.18.x also need to configured the cert use cluster/saltbase/salt/generate-cert/make-ca-cert.sh? But I can't successfully run this script.

@roberthbailey I install kubernetes 0.18.x in centos 7, If I upgrade to 0.20.x will fix these bugs? But I new to the k8s, I don't know how to upgrade? Thank you for your help.

**Comment by Icedroid** [comment]
I install k8s in centos with k8s docs, is it has a bug?
https://github.com/GoogleCloudPlatform/kubernetes/blob/release-0.20/docs/getting-started-guides/centos/centos_manual_config.md

**Comment by antoineco** [comment]
No, but it's outdated, skydns didn't work super reliably at that point. The way pods authenticate against the API has changed a lot since 0.18.0, might be worth updating the getting started guides.

**Comment by Icedroid** [comment]
@antoineco How can I got the latest docs. Now how could I do to make my k8s cluster is available? Oh, My god, make me don't know how to do.

**Comment by antoineco** [comment]
You probably want to read this:
[docs/getting-started-guides/scratch.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/scratch.md), seriously it's the best getting started guide around.

The *virt7-testing* repo doesn't seem to maintain recent versions of Kubernetes.

**Comment by Icedroid** [comment]
@antoineco Thank you very much. I will learn that, and then I hope I can upgrade my k8s version in centos 7 make it available.

**Comment by antoineco** [comment]
Yeah it's better to forget about the CentOS guide. Just download the latest version [here](https://github.com/GoogleCloudPlatform/kubernetes/releases) (kubernetes.tar.gz v0.21.2) and follow the instruction from the guide above on a **clean** system if possible.

It's quite some work but if you ever consider any serious deployment you will most likely automate things using SaltStack, Ansible, Puppet or whatever you like.

**Comment by Icedroid** [comment]
I want to use the automate things, But I don't have any IaaS Provider in this article.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md

**Comment by Icedroid** [comment]
@antoineco Could you help me. I have learn the scratch.md. Now I don't know how to start the etcd apiserver kube-controller-manager on my master machine.
``
Starting Apiserved

Place the completed pod template into the kubelet config dir (whatever --config= argument of kubelet is set to, typically /etc/kubernetes/manifests).
```
 I only install kubelet on the node machine, no kubelet start on my master machine. Does it mean kubelet also need start on the k8s master? 
What is the right args for kubelet start corretly with fanneld network?

**Comment by antoineco** [comment]
(maybe it would make things more clear if you changed the ticket title to something like "Kubernetes 0.21 on CentOS" or something similar, since the subject of the conversation has drifted a little bit)

The kubelet on the master is only used to start the Kubernetes master services inside containers, it doesn't have to be registered with the API since it won't be used to schedule pods others than the one configured on the local filesystem. It should be sufficient to start with the following flag: `--config=/etc/kubernetes/manifests`

It's also perfectly legitimate to run your Kubernetes services as host processes, and not inside containers. In this case just drop the binaries in your $PATH and forget about the master kubelet.
