### ISSUE TITLE
understanding expose with NodePort

### ISSUE THREAD

**Issue by Smana** [GoogleCloudPlatform/kubernetes#11110]
Hello,

I'm trying to expose a service externally. I'm not using a public cloud so i'm trying to expose the service using the NodePort option.
However there's something i still don't understand, i followed the example https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/README.md
And i've changed the frontend service as follows : 
```
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    name: frontend
```
From what i understand, each node should listen on port 80, right ?

But when i look to my configuration i'm confused:
my nodes have an ip on the subnet 10.115.0.0/16
but my services are listenning on a completely different, and unknown subnet : 
```
sudo kubectl get services
NAME           LABELS                                    SELECTOR            IP(S)            PORT(S)
frontend       name=frontend                             name=frontend       10.100.107.32    80/TCP
kubernetes     component=apiserver,provider=kubernetes   <none>              10.100.0.1       443/TCP
redis-master   name=redis-master                         name=redis-master   10.100.178.204   6379/TCP
redis-slave    name=redis-slave                          name=redis-slave    10.100.29.107    6379/TCP
```
i've checked my flannel network too and it is different:
```
ip a sho dev flannel.1
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether b6:8d:e3:c0:30:39 brd ff:ff:ff:ff:ff:ff
    inet 10.244.15.0/16 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::b48d:e3ff:fec0:3039/64 scope link 
       valid_lft forever preferred_lft forever
```
when i look iptables rules on nodes i can see rules forwarding to this unknown subnet.
```
Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            10.100.0.1           /* default/kubernetes: */ tcp dpt:443 redir ports 42877
REDIRECT   tcp  --  0.0.0.0/0            10.100.178.204       /* default/redis-master: */ tcp dpt:6379 redir ports 41546
REDIRECT   tcp  --  0.0.0.0/0            10.100.29.107        /* default/redis-slave: */ tcp dpt:6379 redir ports 60515
REDIRECT   tcp  --  0.0.0.0/0            10.100.107.32        /* default/frontend: */ tcp dpt:80 redir ports 37084

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            10.100.0.1           /* default/kubernetes: */ tcp dpt:443 to:10.115.77.87:42877
DNAT       tcp  --  0.0.0.0/0            10.100.178.204       /* default/redis-master: */ tcp dpt:6379 to:10.115.77.87:41546
DNAT       tcp  --  0.0.0.0/0            10.100.29.107        /* default/redis-slave: */ tcp dpt:6379 to:10.115.77.87:60515
DNAT       tcp  --  0.0.0.0/0            10.100.107.32        /* default/frontend: */ tcp dpt:80 to:10.115.77.87:37084
```
and on my nodes the tcp port 80 is not listenning:
```
sudo ss -lnp -o \( sport = :80 \)
Netid  State      Recv-Q Send-Q                                                                       Local Address:Port                                                                                      Peer Address:Port         
```
Note : my cluster is based on coreos v717.3.0 nodes.

Another question, i think it's a common one, i would like to use a load balancer (preferably haproxy) in front of my services. Is there a proper way to do so ?

Tell me if you need further information.
Thank you,
Smana

**Comment by Smana** [comment]
my mistake it is a configuration parameter on the kube-apiserver : 
```
/opt/bin/kube-apiserver \
          --service_account_key_file=/opt/bin/kube-serviceaccount.key \
          --service_account_lookup=false \
          --admission_control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
          --runtime_config=api/v1 \
          --allow_privileged=true \
          --insecure_bind_address=0.0.0.0 \
          --insecure_port=8080 \
          --kubelet_https=true \
          --secure_port=6443 \
          --service-cluster-ip-range=10.100.0.0/16 \
          --etcd_servers=http://127.0.0.1:2379 \
          --public_address_override=10.115.77.86 \
          --logtostderr=true
```

**Comment by thockin** [comment]
NodePort listens on a different port - an allocated port that it knows it
can get on EVERY node.

It's an imperfect API, and its primary utility is to build load balancers
on top of it (eg AWS ELB).

**Comment by Smana** [comment]
Unfortunately i still don't understand how i can expose a service externally without a public cloud load balancer.
Could you please guide me ?

**Comment by thockin** [comment]
If you set your service to type NodePort, it will allocate you a port.
Read your Service object back to see what port got allocated.  As long as
your Service object exists that port, on all nodes, is yours.

Have you read over docs/services.md ?

Alternately, https://github.com/GoogleCloudPlatform/kubernetes/pull/10405
will let you bind any port on any node to your service, which is a bridge
from where we are into the future APIs we want.

**Comment by Smana** [comment]
Thank you thockin,
I've redo all the steps and i've downloaded an updated version of kubectl and this works just as expected.

For the alternative, i'm looking forward what will be impleemented soon.
