### ISSUE TITLE
Kubernetes Replicator Resize and Pod grouping

### ISSUE THREAD

**Issue by kgrvamsi** [GoogleCloudPlatform/kubernetes#11133]
Hello,

i would like to know if given below things can be achieved through kubernetes when it is running the cluster.

1)When there is a Replicator running with resize 4 to 2 and can we explicitly say that this node should should go down or this container should go down.

2)Can i stop a POD on a specific host to stop instead stopping the pods on the whole cluster group.

thanks,
Vamsi

**Comment by thockin** [comment]
On Sun, Jul 12, 2015 at 11:39 PM, kgrvamsi <notifications@github.com> wrote:
>
> Hello,
>
> i would like to know if given below things can be achieved through kubernetes when it is running the cluster.
>
> 1)When there is a Replicator running with resize 4 to 2 and can we explicitly say that this node should should go down or this container should go down.

If you want to bring a node down, first mark the node as unschedulable.

http://releases.k8s.io/v1.0.0/docs/node.md#manual-node-administration

> 2)Can i stop a POD on a specific host to stop instead stopping the pods on the whole cluster group.

Sorry, when running under a replication controller all pods are
considered identical.

**Comment by thockin** [comment]
Closing for now.  Please reopen if this does not answer your questions.
