### ISSUE TITLE
Failed to create docker container with error: API error (500): No command specified

### ISSUE THREAD

**Issue by dieuroi** [GoogleCloudPlatform/kubernetes#11134]
With the help of kubernetes guestbook, I changed the image value and modified the imagepullpolicy as follows
```
"image":"suse13.1"
"imagepullpolicy":"never"
```
Since I am in China, I can't pull "gcr.io/google_container/pause:0.8.0". My friend in the USA pulled an image "Kubernetes/pause" for me and I specified *--pod_infra_container_image="Kubernetes/pause"*
But it failed and kubelet log says:
>E0713 14:20:34.182718   48272 manager.go:1556] Failed to create pod infra container: API error >?(500): No command specified; Skipping pod "suseapache_default" 

I can't understand this.

**Comment by thockin** [comment]
I don't know if your capiltalization is just a language thing or literal, but it does matter:

```
"image":"suse13.1"
"imagepullpolicy":"never"
```

is wrong

```
"image":"suse13.1"
"imagePullPolicy":"Never"
```
is correct

**Comment by dieuroi** [comment]
I'm sorry that I made a mistake when asking this question but I do used the **correct** one in my json file.
I found that when I pull the "kubernetes/pause" image from dockerhub then the image was useful. But when I saved the image for another computer which have no access to the Internet, kubernetes failed to create container again.
>E0713 14:20:34.182718 48272 manager.go:1556] Failed to create pod infra container: API error >?(500): No command specified; Skipping pod "suseapache_default"

My commands for saving the image are as follows.
```
# docker save -o pause.tar kubernetes/pause:latest
# cat pause.tar | docker import - pause
```

**Comment by thockin** [comment]
@dchen1107

**Comment by dchen1107** [comment]
"No command specified" is an error code returned by docker. Looks like you docker import removes all configurations from an image including both Entrypoint and Cmd. 

I think running docker load -i pause.tar should fix your issue here.

**Comment by dieuroi** [comment]
I found that the configurations are missing and modified them manually, now the issue is fixed. I also tried running docker load -i and this command did help me. Thank you for your instructions!

**Comment by xuedihualu** [comment]
@dieuroi 
Hi:
 I have the same problem with you, can you tell me how to solve?
E1015 10:36:21.521270    5744 manager.go:1579] Error running pod "test_default" container "test": API error (500): No command specified

**Comment by xuedihualu** [comment]
@dieuroi
 你的问题解决了没，我也遇到了api500的问题，
