### ISSUE TITLE
All Shippable builds are failing with "Please run hack/run-gendocs.sh"

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#11136]
I guess we merged a doc PR that hadn't run hack/run-gendocs.

Go to
https://app.shippable.com/builds/55a35fe2bd047d0c00e25ed8
or any other recent build to see the problem.

We should run hack/run-gendocs and submit the result ASAP.

**Comment by zmerlynn** [comment]
The offending PR was #11129
