### ISSUE TITLE
Document what can be updated with kubectl patch (and how)

### ISSUE THREAD

**Issue by mwielgus** [GoogleCloudPlatform/kubernetes#11141]
The current documentation is very vague https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_patch.md and doesn't explain what can be updated in this way. Can I rename or stop the pod, change number of replicas in RC etc.

For example it seems to be impossible to change pod name:
```
kubectl patch pod redis-master-l6lzx -p '{"metadata":{"name":"foobar"}}'
Error from server: the name of the object (foobar) does not match the name on the URL (redis-master-l6lzx)
```

**Comment by nikhiljindal** [comment]
cc @caesarxuchao @mikedanese

**Comment by caesarxuchao** [comment]
After an in person discussion with @bgrant0607, we think the docs should point people to the swagger-ui to find if a field is mutable. I'll add this point into the docs.
