### ISSUE TITLE
Update examples to create service before RC (so that spreading works)

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#11144]
In examples we always create an RC before creating a service. Then spreading doesn't work.

Examples should be corrected (or clarified that we make this simplification).

cc @lavalamp

**Comment by nikhiljindal** [comment]
Am sorry, can you please elaborate on "Then spreading doesnt work"?

cc @caesarxuchao @JanetKuo @bgrant0607

**Comment by bgrant0607** [comment]
Good point. We should add that to our documentation, also, such as best practices for examples #7257. I'll fix my new docs. 

cc @mikedanese

**Comment by marekbiskup** [comment]
By spreading I mean assigning pods to different nodes.
By default, the scheduler score is counted from the number of allocated pods, CPU allocation and memory allocation (and maybe more factors).
If there is a service over our pods, there is additional score for nodes that don't host pods of this service (this may be an oversimplification - I haven't looked in the code). So our pods are spread across different nodes.
To have this function, we have to create the service first.

**Comment by brendandburns** [comment]
We should really spread by label sets, and not just services.  That will ensure that we do spreading for both cases and things won't be order dependent.

However, I think that for the purposes of this issue, it is closed by #11179

**Comment by davidopp** [comment]
To clarify, if you create service and RC in the wrong order, it's only service-based spreading that doesn't work. We always do spreading based on resources (worst fit), including the case where no resources are specified (we pretend you requested 0.1 CPU and 200 MB of memory).

But I agree we should go through all the examples and do the same as we did in #11179. @marekbiskup  or @gmarek if you have time to do that, I think this would be great.

@brendanburns I wasn't clear on what you meant "spread by label sets, and not just services." Do you mean any time two Pods have the same value of the same label, we should try to put them in different machines? (And I guess by extension, the more <label,value> pairs they have in common, the harder we should try to put them in different machines?) This is an interesting idea. I think we need to revamp the whole spreading approach post-1.0 so we can take into account multiple levels of the hierarchy (spread across nodes, across various kinds of failure domains, etc.). So we'd have to think about how this could generalize.

As an aside, @gmarek has a PR #10667 that does spreading by RC when there is no service specified (didn't make it in for 1.0), but that's slightly orthogonal to this issue.

**Comment by gmarek** [comment]
#10667 was wrote exactly for this very reason. I just felt that going from spreading on services, to spreading on label sets as too big leap. In principle label-set driven spreading was exactly my goal.

**Comment by mikedanese** [comment]
I tried spreading by labels in #2312 but it was unpopular at the time, possibly because of implementation. Picking a good heuristic for spreading on label intersection was not straightforward.

**Comment by davidopp** [comment]
I think #10667 is a little different from @brendandburns described; IIUC #10667 explicitly spreads by RC (when there's no Service) while @brendandburns is talking about looking at the labels directly, regardless of which RC is controlling the Pods. It looks like #2312 (which I wasn't previously aware of) is closer to what @brendandburns is talking about.

**Comment by gmarek** [comment]
I agree - I just felt it would be too big change for people before v1 (I hoped it would make it to the release when I wrote it).

**Comment by bgrant0607** [comment]
Spreading by RCs is issue #4971.

**Comment by bgrant0607** [comment]
Regarding spreading by label sets, definitely read comments on #2312. I don't think spreading pods with anything other than exactly matching sets of labels makes sense.

**Comment by gmarek** [comment]
@bgrant0607 - IIUC a lot of people noticed this problem, but for some reason no one did anything with it. I believe that doing something (whether it's spreading by RC instead of Services, RC in addition to Services, or general label sets) it's way better than preserving status quo.

All of those changes would be pretty simple, and it'd be really easy to change ones mind after some time, and implement final thing, whatever we decide it to be. Plus we'd end up with the scheduler which is strictly better than the current one. Please correct me if I'm wrong.

**Comment by marekbiskup** [comment]
@davidopp, It's quite a lot of work to go through all examples. And creating an RC first seems to be natural, so I suppose we may want to go back to the current order (RC, then service). 

How about leaving the examples as they are and adding a note to only one or two of them for instance in the guestbook (I can do it). After 1.0 we will add either @gmarek's or @mikedanese's patch (or something else).

**Comment by bgrant0607** [comment]
@gmarek I wasn't suggesting that we do nothing.

If we spread by RC, then it should be by both RC and service.

If we spread by labels, then it should be by exact match, and we should also still spread by service.

**Comment by gmarek** [comment]
Can you elaborate a bit what you mean by "both RC and service"? I'll try to update my PR tomorrow.

**Comment by brendandburns** [comment]
@davidopp yes, I'm suggesting simply looking at the labels on the pods and scoring based on "overlap" or something like that.

You could make the priority a sigmoid function based on number of shared labels, or something like that.  That would emphasize exact and near-matches, while quickly down-voting partial overlap.

Alternately, we could only use exact match, so
```
priority(pod, node) == 1 / numPodsWithLabels(pod.metadata.labels, node)
```

**Comment by brendandburns** [comment]
and vis a vis @bgrant0607 's comment, I think we should also continue to explicitly spread by service too.

**Comment by bgrant0607** [comment]
One way to spread using both RC and service is to put pods matching either all into one set. See PR #9560 for a more general approach to anti-affinity. There was some discussion of spreading on #367 also.

**Comment by bgrant0607** [comment]
Semantic information is required in order to interpret overlapping labels sets. Just using a function of fraction of matching labels doesn't work well for many real examples. A differing label key might indicate a different app, prod vs. dev, or a new release being deployed during rolling update. Also, 7 out of 8 labels matching probably isn't typically more significant than 1 out of 2 labels matching. That's why I think we should either use the RC (though that will need changes when we add more controllers, convert RC to a plugin, etc.) or exact match of the label sets (though that has edge cases, also, such as when rolling update is in the middle of adding deployment labels).

**Comment by lavalamp** [comment]
> One way to spread using both RC and service is to put pods matching either all into one set. See PR #9560 for a more general approach to anti-affinity.

I think it's simpler to just spread things that have identical labels. Then that will continue to work even when/if we act on previous discussions to stop using labels to indicate ownership.

**Comment by gmarek** [comment]
@brendanburns @thockin @bgrant0607 @lavalamp @davidopp  - please decide if it should make it into v1.0. If so I'll be happy to implement it tomorrow, so also please decide how it should work. There were already too many discussions on this subject and I believe we just need someone who'll make a final (at least for now) decision. 

As I wrote - I believe that the current state is bad and we should do something with, but if you'll decide it's not important for v1, then we probably should aggregate all existing ideas and opinion on the subject, so it'll be easier to make the call post v1.

**Comment by bgrant0607** [comment]
I personally don't think the situation is that bad. There's a straightforward solution, which is documented as the recommended practice, and in the common, simple scenario of a small number of RCs deployed one after another the pods should be assigned to nodes approximately round-robin due to the least-requested priority function.

That said, urgency changes if we're actually going to produce a release in 3 months vs. 2 weeks.

**Comment by gmarek** [comment]
OK. If so then someone should fix all examples, as they're just wrong, as @marekbiskup pointed out.

I'll try to gather everything that was written about this topic in a single issue to make the discussion easier.

**Comment by bgrant0607** [comment]
Many aspects of most examples violate a number of proposed best practices: #7257. PRs welcome to help improve them.

**Comment by gmarek** [comment]
Yup. And I believe it's bad, as probably a lot of people will start by copying examples and modifying them afterwards. My experience in updating docs/examples from Europe is pretty bad (really long review cycle, which is bad especially for documents, as they need quite a few of them), so I guess it would be better if someone from US would fix this. Opened #11361

**Comment by bgrant0607** [comment]
@mikedanese is writing up the best practices, and will also make a pass over the examples.

Note also that there are other reasons services should be started first. kubecfg (the predecessor to kubectl) used to start services first among multiple resources to ensure that service environment variables would be created for the services.

It would also make sense to create the RC without specifying replicas (defaulting to 1), then create the service, then scale up the RC, which may work better in an example using progressive disclosure, and may have benefits in real scenarios also, such as ensuring one replica works before creating lots of them. That's a workflow that matches Docker and many PaaSes, and would also likely happen in the case of auto-scaling.

**Comment by mikedanese** [comment]
I've done this in most offending examples but I'm doing an audit in #11144 so I'm going to close this and fold it into #11144
