### ISSUE TITLE
Describe livenessProbe in the user guide

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#11152]
I may be wrong, but it looks like the livenessProbe is only described via examples:

examples/liveness/README.md
examples/walkthrough/k8s201.md

It would be nice to have it in the user guide too. It's a nice feature and the example may be overlooked.

**Comment by marekbiskup** [comment]
cc @brendandburns @yujuhong

**Comment by mikedanese** [comment]
Maybe user guide would have a better spot but doc is here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pod-states.md#container-probes

**Comment by marekbiskup** [comment]
Ok. I missed it.
I'll let the issue stay for a day, and if nobody objects, close it as not needed.

**Comment by mikedanese** [comment]
Looks like there will be some doc on liveness probes added here as well:

https://github.com/GoogleCloudPlatform/kubernetes/pull/11205/files

**Comment by marekbiskup** [comment]
Ok, there is more than I expected. Closing as a false report.
Sorry for bothering you.

**Comment by mikedanese** [comment]
Not bothered at all :) it's good to have people pointing out holes in the doc
