### ISSUE TITLE
docker --bip=true?

### ISSUE THREAD

**Issue by mconigliaro** [GoogleCloudPlatform/kubernetes#11167]
The "from scratch" getting started guide says this about configuring the bridge for Docker: `Or let docker do it with --bip=true.`

Setting the `bip` option to `true` results in the following error from the docker daemon:

```
FATA[0000] Error starting daemon: Error initializing network controller: invalid CIDR address: true
```

I believe the `bip` option needs to be a CIDR address (e.g. `--bip=192.168.1.1/24`).

**Comment by erictune** [comment]
Fixed by #11176
