### ISSUE TITLE
It should be possible to specify static public IP for LoadBalancer services

### ISSUE THREAD

**Issue by rojer** [GoogleCloudPlatform/kubernetes#11177]
What subj says - use existing allocated static IP instead of auto-assigning one.
Sometimes renumbering and reconfiguring is a pain, it would be nice to be able to preserve IP when moving to container clusters.
Could be a viable workaround for #11175 too. The two of them make service reconfiguration (adding/removing ports) impractical.

**Comment by thockin** [comment]
Closing as dup of #10323
