### ISSUE TITLE
controller-manager won't start without --cloud-provider

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#11172]
#kube-controller-manager --help
...
            --cloud-provider="": The provider for cloud services.  Empty string for no provider.
...

But when I try to start the cm, it fails with:
controllermanager.go:198] Failed to start service controller: ServiceController should not be run without a cloudprovider

The help implies cloud-provider is not required, and it didn't used to be required.

**Comment by timothysc** [comment]
umm we run local bare metal, someone care to explain this recent 11th hour change? 

/cc @eparis

**Comment by timothysc** [comment]
retract.

**Comment by thockin** [comment]
For posterity - can someone please summarize?

On Mon, Jul 13, 2015 at 1:17 PM, Timothy St. Clair <notifications@github.com

**Comment by Icedroid** [comment]
I meet the same problem. How to solve it?

**Comment by timothysc** [comment]
It's the latest cert update on introspective services.

**Comment by Icedroid** [comment]
How to sloved this?

**Comment by timothysc** [comment]
The easiest options are to use the salt-scripts or ansible setup to ensure proper deployment configuration.

**Comment by yuvipanda** [comment]
What exactly are the 'correct options'?

**Comment by yuvipanda** [comment]
Can someone either modify the docs to match reality or point out how to do a hand rolled setup without needing to use salt / ansible? (mostly because I'm trying to setup a puppet version)

**Comment by thuey** [comment]
Any updates on this? I'm running into the same issue.

**Comment by genti-t** [comment]
From documentation :
      --cloud-provider="": The provider for cloud services.  Empty string for no provider.
So, just put an empty string :-)

**Comment by ScOut3R** [comment]
Yeah, well, that gives us this:

```
Unknown cloud provider: ""
```

:)

**Comment by bprashanth** [comment]
It's only complaining about the service controller not starting. everything else should work, right? you only need the service controller for cloud tcp loadbalancers. We should clarify the error message.

**Comment by ScOut3R** [comment]
Correct, everything is working fine. :)

**Comment by schristann** [comment]
--cloud-provider=""

This empty string really helped a lot ^^ .. thank you

**Comment by andrewmichaelsmith** [comment]
hit this upgrading from 1.0.6 to 1.1
