### ISSUE TITLE
Unnamespaced POST (api/v1/kind) is broken for namespaced objects (pods, endpoints, etc)

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#11181]
POSTing to /api/v1/endpoints results in 403, while POSTing to api/v1/namespaces/default/endpoints woks fine.

Steps:

```$ curl -X POST http://localhost:8080/api/v1/endpoints -d @/tmp/endpoint.json ``` gives me:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Endpoints \"testendpoint\" is forbidden: Namespace \"\" is invalid: metadata.name: required value",
  "reason": "Forbidden",
  "details": {
    "name": "testendpoint",
    "kind": "Endpoints"
  },
  "code": 403
}
```
My endpoint.json:
```
 {
   "kind": "Endpoints",
   "apiVersion": "v1",
   "metadata": {
     "name": "testendpoint",
     "namespace": "default",
     "labels": {
       "name": "testendpoint"
     }
   }
 }
```

``` $ curl -X POST http://localhost:8080/api/v1/namespaces/default/endpoints -d @/tmp/endpoint.json ``` works fine and gives me 200 status:
```
{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "testendpoint",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/endpoints/testendpoint",
    "uid": "3e4ac6a8-29a3-11e5-8140-6c3be516adae",
    "resourceVersion": "437",
    "creationTimestamp": "2015-07-13T21:08:00Z",
    "labels": {
      "name": "testendpoint"
    }
  },
  "subsets": []
}
```

**Comment by nikhiljindal** [comment]
cc @bgrant0607 
As per discussion, POSTing to /api/v1/endpoints should not be allowed. It should return a 404.

**Comment by nikhiljindal** [comment]
Actually, this is not restricted to just endpoints. I tried it on a few more resources (POST to /api/v1/<resourceKind>) and all of them return the same 403 error.

cc @smarterclayton

**Comment by nikhiljindal** [comment]
If we want to stop supporting POST to /api/v1/\<resourceKind\>, then just removing one line https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/api_installer.go#L330 will fix it.
But I am not sure what is the right expectation here.

**Comment by smarterclayton** [comment]
It was there to support a few resources in Openshift that were hybrid cluster/namespace scoped and allowed create without a namesapce.  @deads2k and I are in the process of discussing how to remove that complexity - if necessary we can carry a patch.
