### ISSUE TITLE
Confusing instructions for starting cluster using Vagrant

### ISSUE THREAD

**Issue by arun-gupta** [GoogleCloudPlatform/kubernetes#11192]
Getting Started with Vagrant at https://github.com/GoogleCloudPlatform/kubernetes/blob/v0.21.2/docs/getting-started-guides/vagrant.md says to setup cluster using

```
export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash
```

and then 

```
cd kubernetes

export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh
```

The instructions are confusing and seems to indicate that both are required where as the first one downloads Kubernetes and starts the cluster. The later option requires to download Kubernetes and start cluster after that.

**Comment by karlkfi** [comment]
@derekwaynecarr has been owning the vagrant cluster, but I'm sure he'd prefer a PR for a docs change.

**Comment by arun-gupta** [comment]
sure, I can do it. Send the PR on trunk?

**Comment by karlkfi** [comment]
head of master, yes.

**Comment by arun-gupta** [comment]
Pull request created: https://github.com/GoogleCloudPlatform/kubernetes/pull/11200
