### ISSUE TITLE
./hack/verify-gendocs.sh verify failures

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/kubernetes#11199]
Shippable is failing on master and PRs. 

Locally on master:

```
$ ./hack/verify-gendocs.sh
docs/api-conventions.md
----
table-of-contents:
contents were modified

docs/application-troubleshooting.md
----
table-of-contents:
contents were modified

docs/getting-started-guides/scratch.md
----
table-of-contents:
contents were modified

docs/high-availability.md
----
table-of-contents:
contents were modified

FAIL: changes needed but not made due to --verify
!!! Error in ./hack/verify-gendocs.sh:52
  '"${mungedocs}" "--verify=true" "--root-dir=${DOCROOT}"' exited with status 1
Call stack:
  1: ./hack/verify-gendocs.sh:52 main(...)
Exiting with status 1
```

Examples: 
- https://app.shippable.com/builds/55a425f0bd047d0c00e52b92
- https://app.shippable.com/builds/55a44aaebd047d0c00e5c79b

**Comment by karlkfi** [comment]
Looks like failures to `mungedocs --verify` now explodes on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/verify-gendocs.sh#L52 without telling the user to run `hack/run-gendocs.sh`. Likely due to `set -o errexit`.

**Comment by karlkfi** [comment]
`hack/run-gendocs.sh` on master doesn't actually make any changes, but yet mungedocs --verify fails:

```
$ ./hack/verify-gendocs.sh
diffing /Users/karl/workspace/k8s/src/github.com/GoogleCloudPlatform/kubernetes/docs/ against freshly generated docs
/Users/karl/workspace/k8s/src/github.com/GoogleCloudPlatform/kubernetes/docs/ up to date.
/Users/karl/workspace/k8s/src/github.com/GoogleCloudPlatform/kubernetes/contrib/completions up to date.
```

**Comment by karlkfi** [comment]
`_output/local/bin/darwin/amd64/mungedocs --verify=true --root-dir=$PWD/docs/` passes on master.

**Comment by karlkfi** [comment]
False alarm. Recent master changes are causing PRs that aren't rebased to fail `./hack/verify-gendocs.sh`. They pass once rebased.

**Comment by thockin** [comment]
I synced to head and have no such problem.  Please resync

**Comment by thockin** [comment]
Sorry, I responded by email before reading it all :)
