### ISSUE TITLE
kubernetes1.0 build failed...

### ISSUE THREAD

**Issue by fzu-huang** [GoogleCloudPlatform/kubernetes#11206]
i download kubernetes1.0 and build in centos7.  but it fialed.

[root@localhost kubelet]# go build
# github.com/docker/libcontainer/cgroups/systemd
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:87: not enough arguments in call to theConn.StartTransientUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:102: not enough arguments in call to theConn.StopUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:121: not enough arguments in call to theConn.StartTransientUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:130: not enough arguments in call to theConn.StopUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:201: not enough arguments in call to theConn.StartTransientUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:272: not enough arguments in call to theConn.StopUnit
# github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt
rkt/rkt.go:288: cannot use acName (type "github.com/appc/spec/schema/types".ACName) as type "github.com/appc/spec/schema/types".ACIdentifier in field value
rkt/rkt.go:417: cannot use imgManifest.Name (type "github.com/appc/spec/schema/types".ACIdentifier) as type "github.com/appc/spec/schema/types".ACName in field value
rkt/rkt.go:585: not enough arguments in call to r.systemd.StartUnit

**Comment by lvlv** [comment]
I built through hack/build-go.sh, which use checked-in go deps, and it
passed, can you try that?

**Comment by fzu-huang** [comment]
@lvlv      thank you for your help~   i  run ./build-go.sh  but it still failed.this is the log:

[root@root hack]# ./build-go.sh
+++ [0706 16:42:20] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test

+++ [0706 16:45:04] Placing binaries
find: ‘rsync’: 没有那个文件或目录                     -->which means "find no file or directory"
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录
find: ‘rsync’: 没有那个文件或目录



i try to use go build  in /kubernetes/cmd/kubelet/ 
but it still failed ,with error log: 

[root@root kubelet]# go build
# github.com/docker/libcontainer/cgroups/systemd
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:87: not enough arguments in call to theConn.StartTransientUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:102: not enough arguments in call to theConn.StopUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:121: not enough arguments in call to theConn.StartTransientUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:130: not enough arguments in call to theConn.StopUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:201: not enough arguments in call to theConn.StartTransientUnit
../../../../docker/libcontainer/cgroups/systemd/apply_systemd.go:272: not enough arguments in call to theConn.StopUnit
# github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/rkt
../../pkg/kubelet/rkt/rkt.go:288: cannot use acName (type "github.com/appc/spec/schema/types".ACName) as type "github.com/appc/spec/schema/types".ACIdentifier in field value
../../pkg/kubelet/rkt/rkt.go:417: cannot use imgManifest.Name (type "github.com/appc/spec/schema/types".ACIdentifier) as type "github.com/appc/spec/schema/types".ACName in field value
../../pkg/kubelet/rkt/rkt.go:585: not enough arguments in call to r.systemd.StartUnit
[root@root kubelet]#

**Comment by fzu-huang** [comment]
but when  i  "go  build"   others , such as  kubectl.go      it succeeded.  by the log   i saw something wrong in the  code .  but this is the version 1.0!   i can't believe that...

**Comment by lvlv** [comment]
hack/build-go.sh now depends on rsync, try yum install rsync, and build
again

**Comment by brendandburns** [comment]
Your GOPATH is likely set to something incorrect.  Clear the GOPATH variable and try 'make' in the Kubernetes directory.
