### ISSUE TITLE
tag v1.0.0 (cd82144) fails unit test

### ISSUE THREAD

**Issue by lvlv** [GoogleCloudPlatform/kubernetes#11203]
This bug should already got fixed in commit ca21fca7 by Zach Loafman, shall we cherrypick?

$ hack/test-go.sh pkg/kubectl/cmd
Running tests for APIVersion: v1 with etcdPrefix: registry
+++ [0714 11:56:13] Running unit tests without code coverage
W0714 11:56:19.642163   31364 cmd.go:149] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0714 11:56:19.642215   31364 cmd.go:149] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0714 11:56:19.642222   31364 cmd.go:149] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0714 11:56:19.642263   31364 cmd.go:149] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
W0714 11:56:19.642523   31364 cmd.go:149] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
--- FAIL: TestRunExposeService (0.00s)
        expose_test.go:173: expose-external-service: unexpected output: &api.Service{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string{"svc":"test"}, Annotations:map[string]string(nil)}, Spec:api.ServiceSpec{Ports:[]api.ServicePort{api.ServicePort{Name:"default", Protocol:"UDP", Port:14, TargetPort:util.IntOrString{Kind:0, IntVal:14, StrVal:""}, NodePort:0}}, Selector:map[string]string{"func":"stream"}, ClusterIP:"", Type:"LoadBalancer", DeprecatedPublicIPs:[]string(nil), SessionAffinity:""}, Status:api.ServiceStatus{LoadBalancer:api.LoadBalancerStatus{Ingress:[]api.LoadBalancerIngress(nil)}}}
FAIL
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd       0.053s

**Comment by mikedanese** [comment]
It's been cherry picked. #11147

**Comment by mikedanese** [comment]
Wrong one. Here it is: #11160
