### ISSUE TITLE
Error exec "cluster/kube-up.sh". aws without public ip 

### ISSUE THREAD

**Issue by ardemiranda** [GoogleCloudPlatform/kubernetes#11201]
When you run the "Cluster / kube.up.sh" error below

./../cluster/aws/util.sh: line 182: get_instance_private_ip: command not found

i add the function in cluster/aws/util.s
```bash
function get_instance_private_ip {
  local instance_id=$1
  $AWS_CMD --output text describe-instances \
    --instance-ids ${instance_id} \
    --query Reservations[].Instances[].NetworkInterfaces[0].PrivateIpAddress
}
```

**Comment by thockin** [comment]
@justinsb

**Comment by brendandburns** [comment]
@ardemiranda any chance you can send a PR?

Thanks!
--brendan

**Comment by justinsb** [comment]
Actually, let me send a PR.  This should just be reversing a delete I made (in error).

**Comment by justinsb** [comment]
@ardemiranda if you do want to put together a PR we can of course use that instead, but I deleted this by mistake so I have created a PR to fix my mistake.

**Comment by ardemiranda** [comment]
@justinsb 
Believe also need to change the function check-minion.
To make a "ssh forward" by the master.

More has the following comment which makes check-minion in the file "aws/util.sh: 54"
\# Basic sanity checking
\# TODO(justinsb): This is really not needed any more

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/util.sh#L1054

I would make this change the "ssh foward" did not do more because of that comment above
Thanks

**Comment by michaelvilensky** [comment]
When I am running:
export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
with ENABLE_NODE_PUBLIC_IP all works fine and the cluster is up,
though when running with KUBE_ENABLE_NODE_PUBLIC_IP = 0, the cluster won't go up.

why the public ip's are needed for the nodes? isn't the VPC good enough?
Thanks.
