### ISSUE TITLE
local-up-cluster.sh not running correctly

### ISSUE THREAD

**Issue by roackb2** [GoogleCloudPlatform/kubernetes#11216]
when issuing following:
   `` [root@mymachine hack]# ./local-up-cluster.sh``
returns this:
   ``./local-up-cluster.sh: line 36: ./../hack/lib/init.sh: No such file or directory``
I suggest adding ``KUBE_ROOT=$PWD`` after ``cd "{$KUBE_ROOT}"`` to get absolute path:

I'm  a totally newbie to kubernetes & open source community who happens to found a small bug, 
hope this helps.
And if it does not or I did something wrong, please let me know gently :)

**Comment by smarterclayton** [comment]
Generally these are run from the root of the Git dir (above hack) - we'd need to change a lot of files to be consistent.  This does work when you run it from the root of the Git dir, correct?

**Comment by roackb2** [comment]
Then sorry about that, I was running the script directly in the hack folder.
Thanks for your reply
