### ISSUE TITLE
posting a pod to the API server without a namespace in the url doesn't work

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#11218]
but is documented in the swagger API.

We should remove this API call from the spec if it doesn't work.

This works for POST:
`https://146.148.17.25/api/v1/namespaces/default/pods`

This doesn't work for POST:
`https://146.148.17.25/api/v1/pods`

Details:

Pod:
```
{
  "kind": "Pod", 
  "spec": {
    "dnsPolicy": "ClusterFirst", 
    "restartPolicy": "Always", 
    "containers": [
      {
        "image": "jess/stress", 
        "args": [
          "-c", 
          "1", 
          "-m", 
          "2"
        ], 
        "name": "my-stress", 
        "resources": {
          "limits": {
            "cpu": "1m"
          }
        }, 
        "imagePullPolicy": "IfNotPresent"
      }
    ]
  }, 
  "apiVersion": "v1", 
  "metadata": {
    "generateName": "my-stress-", 
    "labels": {
      "run": "my-stress"
    }
  }
```

target url
`https://146.148.17.25/api/v1/pods`
result:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Pod \"my-stress-\" is forbidden: Namespace  does not exist",
  "reason": "Forbidden",
  "details": {
    "name": "my-stress-",
    "kind": "Pod"
  },
  "code": 403
}
```

target url
`https://146.148.17.25/api/v1/namespaces/default/pods`
(success)

If I add "namespace: default" to the pod spec:
`https://146.148.17.25/api/v1/pods`
(exactly the same error as without namespace)

`https://146.148.17.25/api/v1/namespaces/default/pods`
(success)

**Comment by bgrant0607** [comment]
Cc @nikhiljindal

**Comment by nikhiljindal** [comment]
Dup of https://github.com/GoogleCloudPlatform/kubernetes/issues/11181
