### ISSUE TITLE
kubectl replace --force doesn't work with stdin input

### ISSUE THREAD

**Issue by mwielgus** [GoogleCloudPlatform/kubernetes#11227]
Resource description is read 2 times (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/replace.go#L135).
The second attempt fails (stdin is not "rewinded")
```
$ kubectl create -f examples/update-demo/nautilus-rc.yaml
$ sed 's/update-demo-kitten/update-demo-nautilus/g' examples/update-demo/kitten-rc.yaml | kubectl replace --force -f -
replicationcontrollers/update-demo-nautilus
read /dev/stdin: bad file descriptor
```
As a result the resource is deleted but not created again.

**Comment by mwielgus** [comment]
The problem is caused by 2 visitors running on stdin (one in delete.go:Reap/DeleteResult and one in replace.go 

Possible fixes:
1. Write stdin to a temp file and update parameters passed by the user.
2. Introduce a wrapper around os.Stdin that stores all of the input in memory for future use. The wrapper would be used here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L413
3. Refactor replace.go to use only 1 visitor.

**Comment by bgrant0607** [comment]
cc @caesarxuchao
