### ISSUE TITLE
hack/local-cluster-up isn't setting/creating certificates, tests fail

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#11225]
The hack/local-cluster-up isn't generating and setting the --root-ca-file on the controller-manager, which is now needed for some tests to pass.  Running one of the networking tests:

_output/local/bin/linux/amd64/e2e.test --host=http://127.0.0.1:8080 --provider="local" --ginkgo.v=true --ginkgo.focus="should function for intra-pod communication" --kubeconfig="$HOME/.kubernetes_auth"

against the cluster from local-cluster-up results in failure with:

 Expected error:
      <*errors.errorString | 0xc2081aca90>: {
          s: "Giving up; pod went into failed status: \n(*api.Pod){TypeMeta:(api.TypeMeta){Kind:(string) APIVersion:(string)} ObjectMeta:(api.ObjectMeta){Name:(string)nettest-o9h9d GenerateName:(string)nettest- Namespace:(string)e2e-tests-nettest-7znow SelfLink:(string)/api/v1/namespaces/e2e-tests-nettest-7znow/pods/nettest-o9h9d UID:(types.UID)d594551c-2a29-11e5-b9a5-54ee7510755a ResourceVersion:(string)61 Generation:(int64)0 CreationTimestamp:(util.Time)2015-07-14 09:11:26 -0400 EDT DeletionTimestamp:(*util.Time)<nil> Labels:(map[string]string)map[name:nettest] Annotations:(map[string]string)<nil>} Spec:(api.PodSpec){Volumes:([]api.Volume)[{Name:(string)default-token-ogyoq VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource){SecretName:(string)default-token-ogyoq} NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaim:(*api.PersistentVolumeClaimVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil>}}] Containers:([]api.Container)[{Name:(string)webserver Image:(string)gcr.io/google_containers/nettest:1.6 Command:([]string)<nil> Args:([]string)[-service=nettest -peers=1 -namespace=e2e-tests-nettest-7znow] WorkingDir:(string) Ports:([]api.ContainerPort)[{Name:(string) HostPort:(int)0 ContainerPort:(int)8080 Protocol:(api.Protocol)TCP HostIP:(string)}] Env:([]api.EnvVar)<nil> Resources:(api.ResourceRequirements){Limits:(api.ResourceList)<nil> Requests:(api.ResourceList)<nil>} VolumeMounts:([]api.VolumeMount)[{Name:(string)default-token-ogyoq ReadOnly:(bool)true MountPath:(string)/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:(*api.Probe)<nil> ReadinessProbe:(*api.Probe)<nil> Lifecycle:(*api.Lifecycle)<nil> TerminationMessagePath:(string)/dev/termination-log ImagePullPolicy:(api.PullPolicy)IfNotPresent SecurityContext:(*api.SecurityContext)<nil>}] RestartPolicy:(api.RestartPolicy)Never TerminationGracePeriodSeconds:(*int64)<nil> ActiveDeadlineSeconds:(*int64)<nil> DNSPolicy:(api.DNSPolicy)ClusterFirst NodeSelector:(map[string]string)<nil> ServiceAccountName:(string)default NodeName:(string)127.0.0.1 HostNetwork:(bool)false ImagePullSecrets:([]api.LocalObjectReference)<nil>} Status:(api.PodStatus){Phase:(api.PodPhase)Failed Conditions:([]api.PodCondition)[{Type:(api.PodConditionType)Ready Status:(api.ConditionStatus)False}] Message:(string) Reason:(string) HostIP:(string)127.0.0.1 PodIP:(string)172.17.0.1 StartTime:(*util.Time)2015-07-14 09:11:27 -0400 EDT ContainerStatuses:([]api.ContainerStatus)[{Name:(string)webserver State:(api.ContainerState){Waiting:(*api.ContainerStateWaiting)<nil> Running:(*api.ContainerStateRunning)<nil> Terminated:(*api.ContainerStateTerminated){ExitCode:(int)1 Signal:(int)0 Reason:(string) Message:(string) StartedAt:(util.Time)2015-07-14 09:11:39 -0400 EDT FinishedAt:(util.Time)2015-07-14 09:11:39 -0400 EDT ContainerID:(string)docker://0fbcd924eeeacda06455943e28e056f45107644ff986d7461ba18e6e96074df2}} LastTerminationState:(api.ContainerState){Waiting:(*api.ContainerStateWaiting)<nil> Running:(*api.ContainerStateRunning)<nil> Terminated:(*api.ContainerStateTerminated)<nil>} Ready:(bool)false RestartCount:(int)0 Image:(string)gcr.io/google_containers/nettest:1.6 ImageID:(string)docker://3b63ff510f8b7415500e06d579f520cea5bec14971ef8c7d1af00aef633aa941 ContainerID:(string)docker://0fbcd924eeeacda06455943e28e056f45107644ff986d7461ba18e6e96074df2}]}}",
      }
      Giving up; pod went into failed status: 
      (*api.Pod){TypeMeta:(api.TypeMeta){Kind:(string) APIVersion:(string)} ObjectMeta:(api.ObjectMeta){Name:(string)nettest-o9h9d GenerateName:(string)nettest- Namespace:(string)e2e-tests-nettest-7znow SelfLink:(string)/api/v1/namespaces/e2e-tests-nettest-7znow/pods/nettest-o9h9d UID:(types.UID)d594551c-2a29-11e5-b9a5-54ee7510755a ResourceVersion:(string)61 Generation:(int64)0 CreationTimestamp:(util.Time)2015-07-14 09:11:26 -0400 EDT DeletionTimestamp:(*util.Time)<nil> Labels:(map[string]string)map[name:nettest] Annotations:(map[string]string)<nil>} Spec:(api.PodSpec){Volumes:([]api.Volume)[{Name:(string)default-token-ogyoq VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource){SecretName:(string)default-token-ogyoq} NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaim:(*api.PersistentVolumeClaimVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil>}}] Containers:([]api.Container)[{Name:(string)webserver Image:(string)gcr.io/google_containers/nettest:1.6 Command:([]string)<nil> Args:([]string)[-service=nettest -peers=1 -namespace=e2e-tests-nettest-7znow] WorkingDir:(string) Ports:([]api.ContainerPort)[{Name:(string) HostPort:(int)0 ContainerPort:(int)8080 Protocol:(api.Protocol)TCP HostIP:(string)}] Env:([]api.EnvVar)<nil> Resources:(api.ResourceRequirements){Limits:(api.ResourceList)<nil> Requests:(api.ResourceList)<nil>} VolumeMounts:([]api.VolumeMount)[{Name:(string)default-token-ogyoq ReadOnly:(bool)true MountPath:(string)/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:(*api.Probe)<nil> ReadinessProbe:(*api.Probe)<nil> Lifecycle:(*api.Lifecycle)<nil> TerminationMessagePath:(string)/dev/termination-log ImagePullPolicy:(api.PullPolicy)IfNotPresent SecurityContext:(*api.SecurityContext)<nil>}] RestartPolicy:(api.RestartPolicy)Never TerminationGracePeriodSeconds:(*int64)<nil> ActiveDeadlineSeconds:(*int64)<nil> DNSPolicy:(api.DNSPolicy)ClusterFirst NodeSelector:(map[string]string)<nil> ServiceAccountName:(string)default NodeName:(string)127.0.0.1 HostNetwork:(bool)false ImagePullSecrets:([]api.LocalObjectReference)<nil>} Status:(api.PodStatus){Phase:(api.PodPhase)Failed Conditions:([]api.PodCondition)[{Type:(api.PodConditionType)Ready Status:(api.ConditionStatus)False}] Message:(string) Reason:(string) HostIP:(string)127.0.0.1 PodIP:(string)172.17.0.1 StartTime:(*util.Time)2015-07-14 09:11:27 -0400 EDT ContainerStatuses:([]api.ContainerStatus)[{Name:(string)webserver State:(api.ContainerState){Waiting:(*api.ContainerStateWaiting)<nil> Running:(*api.ContainerStateRunning)<nil> Terminated:(*api.ContainerStateTerminated){ExitCode:(int)1 Signal:(int)0 Reason:(string) Message:(string) StartedAt:(util.Time)2015-07-14 09:11:39 -0400 EDT FinishedAt:(util.Time)2015-07-14 09:11:39 -0400 EDT ContainerID:(string)docker://0fbcd924eeeacda06455943e28e056f45107644ff986d7461ba18e6e96074df2}} LastTerminationState:(api.ContainerState){Waiting:(*api.ContainerStateWaiting)<nil> Running:(*api.ContainerStateRunning)<nil> Terminated:(*api.ContainerStateTerminated)<nil>} Ready:(bool)false RestartCount:(int)0 Image:(string)gcr.io/google_containers/nettest:1.6 ImageID:(string)docker://3b63ff510f8b7415500e06d579f520cea5bec14971ef8c7d1af00aef633aa941 ContainerID:(string)docker://0fbcd924eeeacda06455943e28e056f45107644ff986d7461ba18e6e96074df2}]}}
  not to have occurred

The docker logs for the pod show:

E0714 13:11:39.281447       1 helper.go:251] expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
2015/07/14 13:11:39 Unable to get server version: Get https://10.0.0.1:443/version: x509: failed to load system roots and no roots provided
E0714 13:11:39.281447       1 helper.go:251] expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
2015/07/14 13:11:39 Unable to get server version: Get https://10.0.0.1:443/version: x509: failed to load system roots and no roots provided

**Comment by timothysc** [comment]
cross-ref - https://github.com/GoogleCloudPlatform/kubernetes/issues/11061#issuecomment-120499034 

/cc @thockin

**Comment by erictune** [comment]
Summoning people who touched local cluster code recently or know about ca-files, in hopes of finding a volunteer to help with this issue:
 - @jayunit100 
 - @pmorie 
 - @nak3
 - @eparis 
 - @mikedanese

**Comment by jayunit100** [comment]
the key thing is knowing how to fix the cathing -once we have a direction on how to setup CAs ; fixing the script is probably easy ; happy to help there but CA advice definetly needed

**Comment by eparis** [comment]
I'll take a look I guess.  /cry

**Comment by liggitt** [comment]
local-up-cluster.sh doesn't specify a cert, which means the API server generates a self-signed one. you *should* be able to use that self-signed cert (generated at /var/run/kubernetes/apiserver.crt, I believe) as the CA...

**Comment by liggitt** [comment]
Hmm, tried this and ran into a couple errors:

1: the self-signed cert needs adjusting to be considered a valid CA cert (which it should be)
```
error: couldn't read version from server: Get https://192.168.1.129:6443/api: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "192.168.1.129@1436932236")
```

2: the self-signed cert doesn't include 127.0.0.1, which is probably ok, but means the API_HOST used by local-up-cluster won't validate against it

**Comment by liggitt** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/11285 should fix CA validation in local-up-cluster.sh
