### ISSUE TITLE
Map a container port to a random host port?

### ISSUE THREAD

**Issue by feihujiang** [GoogleCloudPlatform/kubernetes#11220]
We know, docker -P could map a container port to a random host port. I want to know if Kubernetes has this function (map a container port to a random host port)? if it has, what should I do to use this function, Is there any flag to be set in PodSpec or ContainerPort  to use this function?

**Comment by pmorie** [comment]
Currently there's no way to do this -- I would argue that it's probably not great to consume random host ports as it could complicate scheduling of other pods that wanted to use the consumed port.  Can I ask, what is the enclosing use-case?  Perhaps there's a better way to get you what you want.

**Comment by delianides** [comment]
@pmorie Am I correct in saying that random host ports within Kubernetes are even irrelevant because each pod will have its own generated IP? With docker, unless you have a networking plugin, everything is bound to the host machine's IP address.

**Comment by pmorie** [comment]
@delianides You can still consume a host port if you need it.  I'm having trouble thinking of a use-case for a random host-port, though.

**Comment by delianides** [comment]
@pmorie Sorry, that was my point. I was trying to highlight the difference between the docker client and kubernetes.

**Comment by erictune** [comment]
Kubernetes doesn't support this.
