### ISSUE TITLE
Swagger API documentation nicknames should include unique for each operation

### ISSUE THREAD

**Issue by cianclarke** [GoogleCloudPlatform/kubernetes#11229]
cc @smarterclayton 
As I understand it, the nickname for each operation should be unique[1]. I searched the open issues, and could not find an open issue relating to this, however my apologies if this is a duplicate. 
Since the introduction of 'namespaced' apis (`/api/v1/services` v.s.`/api/v1/namespaces/{namespaces}/services`), there are operations with duplicate nicknames [2][3].
This means when we try to consume APIs via their swagger definition, the client overwrites the namespaced version of the API with the non-namespaced version. 
Maybe `listService` and `listServiceByNamespace` might be the convention to go by? 

Thanks @webron for the help in IRC confirming this

[1] https://github.com/swagger-api/swagger-spec/issues/64
[2] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json#L9961
[3] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json#L10863

**Comment by erictune** [comment]
@bgrant0607 @nikhiljindal 

Can describe more about how this affects you?  For example, you cannot make a client in language X using library Y that depends on a valid swagger spec.   This will help us prioritize.

**Comment by erictune** [comment]
Question above directed at @cianclarke

**Comment by smarterclayton** [comment]
Yes I believe that was Cian's problem (I sent him towards using the swagger
JS client, which uses nicknames for the methods it uses internally).

On Tue, Jul 14, 2015 at 1:07 PM, Eric Tune <notifications@github.com> wrote:

> Question above directed at @cianclarke <https://github.com/cianclarke>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11229#issuecomment-121310485>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by nikhiljindal** [comment]
Thanks @cianclarke. 
Yes I just checked and we have duplicate nicknames, which we should not.
I am surprised because, last I checked, our swagger spec passed swagger validation, which it should not if we have duplicate nicknames.

**Comment by webron** [comment]
Umm, how did you run the validation? :)

**Comment by cianclarke** [comment]
@erictune Sure - when attempting to integrate with k8 APIs using https://github.com/swagger-api/swagger-js, I discovered that due to the duplicated nicknames, I was unable to utilise a swagger client to call the APIs I needed access to. In particular, we need to operate on namespaced APIs. 

Somewhat unrelated to this issue, for the immediate future we probably won't be using the Swagger API client to build this integration, so it's not blocking us - just would be a nice to fix :-)

**Comment by nikhiljindal** [comment]
```$ swagger-tools validate api/swagger-spec/resourceListing.json api/swagger-spec/api.json api/swagger-spec/v1beta3.json api/swagger-spec/v1.json api/swagger-spec/version.json ```

We do it as a one-off right now, so it is possible that it might have broken since I last checked.
I am working on adding it as part of our continuous tests: https://github.com/GoogleCloudPlatform/kubernetes/issues/5356

**Comment by webron** [comment]
@whitlockjc - does swagger-tools check for duplicate `nickname`s in 1.2 definitions?

**Comment by nikhiljindal** [comment]
I just ran swagger-tools validate again and didnt get any error, so I can confirm that it is not failing on duplicate nicknames.

**Comment by whitlockjc** [comment]
Not yet, it's on the list: https://github.com/apigee-127/swagger-tools/issues/219
