### ISSUE TITLE
Swagger API docs for getting container logs missing an input parameter

### ISSUE THREAD

**Issue by perljedi** [GoogleCloudPlatform/kubernetes#11226]
Using the REST api to get logs for a container running in a multi-container pod requires using "container" URI parameter.  That parameter doesn't not show up at all in the Swagger api docs.

**Comment by erictune** [comment]
@nikhiljindal

**Comment by erictune** [comment]
Thanks for the report, @perljedi

**Comment by nikhiljindal** [comment]
Being fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10426

**Comment by perljedi** [comment]
Cool, thanks!

**Comment by nikhiljindal** [comment]
Fixed by #10426
