### ISSUE TITLE
Replacing a service fails trying to modify clusterip

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#11237]
It is confusing that this doesn't work, especially since clusterIP was not part of the initial manifest or the replacement. 
```
$ cat svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    app: nginx

$ kubectl create -f svc.yaml
services/nginxsvc

$ cat svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: nginx

$ kubectl replace -f svc.yaml
Replace failedspec.clusterIP: invalid value '': field is immutable

$ kubectl delete -f svc.yaml; kubeclt create -f svc.yaml
services/nginxsvc
```

**Comment by thockin** [comment]
This one keeps popping up.  Principally the answer is that 'replace' is a
full replacement and really must be an RMW operation.  That's somewhat
unsatisfying in this case, though.

**Comment by bgrant0607** [comment]
`kubectl apply` is the solution. This is redundant with several other issues.

**Comment by nelsonenzo** [comment]
kubectl apply isn't a valid command. Any other suggestions to fix this?

**Comment by thockin** [comment]
I think it's been renamed to 'patch'

**Comment by atomantic** [comment]
I'm having this issue with a service that is currently running with a loadBalancerIP configured:

kind: Service
apiVersion: v1
metadata:
  name: "unid"
spec:
  selector:
    app: "unid"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4117
  type: LoadBalancer
  loadBalancerIP: 130.211.27.91


If I try to replace this service with the same file, it returns
```
The Service "unid" is invalid.
spec.clusterIP: Invalid value: "": field is immutable
```
I'm trying to remove the loadBalancerIP configuration because it's hemorrhaging logs with "CreatingLoadBalancerFailed" errors. Can't figure out how to change the service definition to remove this field.

**Comment by thockin** [comment]
"replace" is a full replacement operation, which fails the rules that say
service.spec.clusterIP can not change, once initialized.  Try using "apply"
or do a read-modify-write cycle on your resource.

**Comment by pawelprazak** [comment]
How about the REST API, how to update a service using it?

**Comment by yoshi522** [comment]
According to this document, you should add option "--force" to replace your service yaml.
https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#disruptive-updates

**Comment by thockin** [comment]
--force should not work for this - you can not change clusterIP this way -
you have to read the value back, or else use `kubectl apply` which
generates a PATCH

**Comment by asbjornu** [comment]
I just ran `kubectl replace -f <file.yaml> --force` now and it worked. Without `--force`, I too got the error message `Replace failedspec.clusterIP: invalid value '': field is immutable`.

**Comment by bgrant0607** [comment]
Working as intended. Use get+replace, patch, or apply if you want to keep the same clusterIP.

**Comment by gavvvr** [comment]
Facing the same issue with `client-go`. It also says that:

> [metadata.resourceVersion: Invalid value: "": must be specified for an update

**Comment by schollii** [comment]
Using `--force` worked for me in 1.8.11. Notice how the k8s objects are first deleted then replaced:
```bash
devops$ kubectl replace -f k8s-web.yaml --force
deployment "web" deleted
service "web" deleted
deployment "web" replaced
service "web" replaced
devops$ 
```

Whereas without the `--force`, there is no deletion: 
```bash
devops$ kubectl replace -f k8s-web.yaml
deployment "web" replaced
The Service "web" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

Upon digging into this difference further, this seems to be expected: the [docs about "disruptive updates"](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#disruptive-updates) say

> In some cases, you may need to update resource fields that cannot be updated once initialized, or you may just want to make a recursive change immediately, such as to fix broken pods created by a Deployment. To change such fields, use replace --force, which deletes and re-creates the resource.

**Comment by bgrant0607** [comment]
Deletion and re-creation will cause allocated IPs and node ports to change.

**Comment by thockin** [comment]
Because this came up again - `kubectl replace` (HTTP "PUT") is probably the wrong verb to be using.  `kubectl apply` should be better in most ways (acknowledging the issues around changing ambiguous ports, which may require a read-modify-replace cycle)
