### ISSUE TITLE
Pull request builder may not (or may) be working on release-1.0

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#11243]
See https://github.com/GoogleCloudPlatform/kubernetes/pull/11186#issuecomment-121325672

It's doing something really weird for alternate base-branch pull requests. Shippable seems to be handling these fine.

**Comment by ixdy** [comment]
I've set up the pull request builder to only touch PRs on the master branch. I can either remove this setting, or we can grow the whitelist.

**Comment by ixdy** [comment]
The [GitHub commit status API](https://developer.github.com/v3/repos/statuses/) only allows specifying the sha of a commit - there's nothing about pull requests or branches. So if a commit has the same sha in multiple PRs, they'll probably all share the same status, even if they get merged into different trees in the PR builder.

**Comment by ixdy** [comment]
The pull request builder now runs on the `release-.*` branches as well as master. It _should_ work correctly - reopen if this ends up not being the case as we cherry-pick things in?
