### ISSUE TITLE
cluster-info needs kube-system namespace

### ISSUE THREAD

**Issue by timstclair** [GoogleCloudPlatform/kubernetes#11248]
I believe the primary use case for `kubectl cluster-info` is to summarize the list of cluster addons running (label `kubernetes.io/cluster-service=true`). However, all cluster addons have been moved to the `kube-system` namespace:
```
$ kubectl cluster-info
Kubernetes master is running at https://108.59.86.171
$ kubectl cluster-info --namespace=kube-system
Kubernetes master is running at https://108.59.86.171
Elasticsearch is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Kibana is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/kube-ui
Grafana is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
Heapster is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/monitoring-heapster
InfluxDB is running at https://108.59.86.171/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

I think `cluster-info` should use the `kube-system` namespace flag by default, but if not some documentation needs to be updated:
https://github.com/GoogleCloudPlatform/kubernetes/blob/bdbcbe2e2fbde0528d387614bd7521f6e7be33c5/docs/getting-started-guides/logging-elasticsearch.md#L111
https://github.com/GoogleCloudPlatform/kubernetes/blob/bdbcbe2e2fbde0528d387614bd7521f6e7be33c5/docs/user-guide/connecting-to-applications-proxy.md#L22
https://github.com/GoogleCloudPlatform/kubernetes/blob/ab0d97e48aae3dd8cc4d9c272815f84442b9bfd0/docs/accessing-the-cluster.md#L193

**Comment by erictune** [comment]
Agree.  Want to send a PR?

**Comment by erictune** [comment]
@bgrant0607

**Comment by erictune** [comment]
Breaks a bunch of documentation if this doesn't work.  Changing kubectl seems low risk since this is single purpose command.

**Comment by erictune** [comment]
Hmm.  However, there is the problem of backwards compatibility of kubectl command.
Could it do the following:
 - if kube-system namespace exists, list that, otherwise, use default?

**Comment by timstclair** [comment]
Actually, it looks like this was already done by https://github.com/GoogleCloudPlatform/kubernetes/commit/988aa6fdf67110cdfc012bf79a15d39c337f58bc, I must have been using an old version.
