### ISSUE TITLE
Mungedocs should assert <some config> exists for examples using kubectl -f <some-config>

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#11305]
The following one-liner shows some errors:

```
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ git grep -- "-f " docs | sed -n -e 's/^.*-f //p' | cut -d ' ' -f 1 | grep ^examples | sort | uniq | xargs ls -l
ls: cannot access examples/downward-api/dapi-pod.yaml: No such file or directory
ls: cannot access examples/limitrange/limit-range.json: No such file or directory
ls: cannot access examples/persistent-volumes/claims/claim-01.yaml: No such file or directory
ls: cannot access examples/persistent-volumes/simpletest/pod.yaml: No such file or directory
ls: cannot access examples/persistent-volumes/simpletest/service.json: No such file or directory
ls: cannot access examples/persistent-volumes/volumes/local-01.yaml: No such file or directory
ls: cannot access examples/pod.yaml: No such file or directory
ls: cannot access examples/resourcequota/resource-quota.json: No such file or directory
ls: cannot access examples/secrets/secret-pod.yaml: No such file or directory
ls: cannot access examples/secrets/secret.yaml: No such file or directory
ls: cannot access examples/update-demo/kitten-rc.yaml: No such file or directory
ls: cannot access examples/update-demo/nautilus-rc.yaml: No such file or directory
ls: cannot access examples/walkthrough/pod2.yaml: No such file or directory
-rw-r----- 1 biskup eng 344 Jul  2 11:21 examples/guestbook/redis-master-controller.yaml
-rw-r----- 1 biskup eng 228 Jul  2 11:21 examples/guestbook/redis-master-service.yaml
```

As @lavalamp did recently with broken links, maybe we can do something with broken file paths. 
I don't have any idea how to do it easily.

cc @mikedanese

**Comment by bgrant0607** [comment]
Yes, we need to fix these

**Comment by lavalamp** [comment]
@krousey wants to add a thingy to mungedocs that inlines example files into the docs, so they don't need to be updated in two places. That would presumably fix this at the same time.

**Comment by lavalamp** [comment]
@mikedanese maybe we can leave this open for the general problem after your patch is merged?

**Comment by mikedanese** [comment]
@lavalamp my patch is in. I'm unassigning myself and renaming. Also moving to v1-candidate.

**Comment by bgrant0607** [comment]
Moved to v1.0 milestone. Clearly we need this.

**Comment by thockin** [comment]
This would be great.  @krousey says not working on it, I'll see if I can do something minimal

**Comment by thockin** [comment]
I have a validator written, but it get tricky.  many examples do things like:

```
$ cat <<EOF > quota.json
{
  "apiVersion": "v1",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "quota",
  },
  "spec": {
    "hard": {
      "memory": "1Gi",
      "cpu": "20",
      "pods": "10",
      "services": "5",
      "replicationcontrollers":"20",
      "resourcequotas":"1",
    },
  }
}
EOF
$ kubectl create -f quota.json
```

I'm going to assert that references with no directory elements are mostly of this form and are OK

**Comment by bgrant0607** [comment]
Or convert these to use stdin?

**Comment by bgrant0607** [comment]
Or /tmp/foo.yaml

**Comment by thockin** [comment]
I could switch them all to /tmp/whatever.yml if you like that better

**Comment by bgrant0607** [comment]
Seems like it would make validation easier.

**Comment by thockin** [comment]
I allowed ./ as a special case and made all examples and docs use that or
use real paths.  The one big ugly is the docs for kubectl, which include
help strings.  Instead of "-f FILENAME" for help, it now says "-f
/path/to/FILENAME".

I did it as a new commit so I can throw it away if you balk :)

Tim
