### ISSUE TITLE
Explicit errors while detaching GCE PD prevent PD from ever being detached 

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#11321]
If `GetCloudProvider` or `DetachDisk` calls fail while detaching a GCE PD, because the previous `Unmount` call succeeded, there are no further attempts by kubelet to detach the PD, and the PD remains attached to the node indefinitely.

Code in question [pkg/volume/gce_pd/gce_util.go#L114](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go#L114):
```
	// Detach the disk
	gce, err := cloudprovider.GetCloudProvider("gce", nil)
	if err != nil {
		return err
	}
	if err := gce.(*gce_cloud.GCECloud).DetachDisk(pd.pdName); err != nil {
		return err
	}
```

`verifyDetached(pd, gce)` is called to ensure retries on silent failures of the detach call (which are much more common); explicit failures should also be handled similarly.

Discovered while trying to repro #11231. 

Relevant logs:
```
W0715 07:17:51.574898    3062 kubelet.go:1343] Orphaned volume "7c60d5e7-2ac1-11e5-b69c-42010af04fdb/testpd" found, tearing down volume
I0715 07:17:51.575607    3062 mount_linux.go:129] Unmounting /var/lib/kubelet/pods/7c60d5e7-2ac1-11e5-b69c-42010af04fdb/volumes/kubernetes.io~gce-pd/testpd
I0715 07:17:51.579307    3062 gce_util.go:109] DetachDisk(pd) where pd is &gce_pd.gcePersistentDisk{volName:"testpd", podUID:"7c60d5e7-2ac1-11e5-b69c-42010af04fdb", pdName:"e2e-7096e666-2ac1-11e5-907d-f0921cde18c1", fsType:"", partition:"", readOnly:false, manager:(*gce_pd.GCEDiskUtil)(0x1c15f78), mounter:(*mount.Mounter)(0x1c15f78), diskMounter:(*gce_pd.gceSafeFormatAndMount)(0xc2096a71a0), plugin:(*gce_pd.gcePersistentDiskPlugin)(0xc20833aa60), legacyMode:false} and the globalPDPath is "/var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/e2e-7096e666-2ac1-11e5-907d-f0921cde18c1"
E0715 07:17:51.583962    3062 kubelet.go:1349] Could not tear down volume "7c60d5e7-2ac1-11e5-b69c-42010af04fdb/testpd": Get http://169.254.169.254/computeMetadata/v1/instance/zone: EOF
```

**Comment by davidopp** [comment]
@saad-ali any news on this? Should we block the release on this?

@brendandburns 

@wojtek-t if you or one of the other Warsaw folks have time, it would be great to look into this.

**Comment by saad-ali** [comment]
I will fix this as part of https://github.com/GoogleCloudPlatform/kubernetes/issues/11231
Hoping to have a PR out by EOD today.
