### ISSUE TITLE
kube-version-change Throws Error: "no kind "ReplicationController""

### ISSUE THREAD

**Issue by pnovotnak** [GoogleCloudPlatform/kubernetes#11334]
When I run the [kube-version-change](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/cluster-management.md#switching-your-config-files-to-a-new-api-version) command, I get the following error: 

    2015/07/15 11:34:02 Couldn't decode input: "no kind \"ReplicationController\" is registered for version \"v1beta3\""

Here's the configuration I'm trying to convert:

    ---
    kind: ReplicationController
    apiVersion: v1beta3
    metadata:
      name: acont
      labels:
        name: acont
    spec:
      replicas: 1
      selector:
        name: acont
      template:
        metadata:
          labels:
            name: acont
        spec:
          containers:
          - name: acont
            image: gcr.io/myproj/acont:latest
            imagePullPolicy: Always

Is this expected behavior?

**Comment by drampelt** [comment]
I'm getting the same thing, trying to upgrade from v1beta3 to v1

**Comment by bgrant0607** [comment]
What release of Kubernetes? Try release 0.20. v1beta3 is gone in Head

**Comment by drampelt** [comment]
Checking out v0.20.0 worked for me. Thanks!

**Comment by nikhiljindal** [comment]
0.21.2 was the last version that supported v1beta3 by default.
So that or the releases before that should work fine for converting configs from v1beta3 to v1.
