### ISSUE TITLE
Access external load balancing ID

### ISSUE THREAD

**Issue by csaintc** [GoogleCloudPlatform/kubernetes#11330]
I have an isomorphic javascript app that talks to the same API on both the front-end and the back-end.

On the back end, getting the service’s IP is no problem at all. 

But, the service’s external IP is not contained in containers’ environment variables, so I have no way to pass that address down to the frontend.

Is there a way to get a service’s external IP inside of a container?

**Comment by bprashanth** [comment]
Can you explain how your frontend differs from the backend? (what is it using the external ip for, is it running outside your cluster?)

**Comment by thockin** [comment]
service.status.loadBalancer.ingress

On GCE the ip field is set.  On AWS the hostname field is set
