### ISSUE TITLE
Implement the steps necessary for publishing docs to gh-pages (out of master)

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#11344]
As part of the release process, we need to process our .md files, specifically our user-facing documentation under the "docs" and "examples" folders in the master branch, and then copy them over to a release specific folder in the gh-pages (for example, the v1.0 folder is "v1_0" and the corresponding HEAD folder is "vHEAD".

The gh-pages directory structure will be match master with the exception that there will be a version specific container folder at gh-pages root. For v1.0, we need to copy all files into the 'v1_0' and 'vHEAD' folders.

View my fork(WIP) for the current test build: [http://richieescarez.github.io/kubernetes/v1_0/index.html](http://richieescarez.github.io/kubernetes/v1_0/index.html) *(note that ive manually fixed the .md files to get this staging site to work so it contains many broken links and missing files (ie. files in subdirectories of "docs" and all of vHEAD is missing))*

For V1.0, we will utilize the GitHub Pages build (which is a Jekyll build) and to do so, we need the following in order to deliver for v1.0 GA:

(1)
Every file file requires front matter (in every .md file - *for GitHub Pages/Jekyll build to recognize and process the file*). The layout we will use will be located here: gh-pages root > _layouts > [docwithnav.html](https://github.com/RichieEscarez/kubernetes/blob/gh-pages/_layouts/docwithnav.html).

To use that layout for each of our .md files, we need to run a script to insert the "docwithnav" attribute to the top (line1) of each file:

     ---
     layout: docwithnav
     ---
(*[view example here](https://github.com/RichieEscarez/kubernetes/tree/gh-pages/v1_0)*)

(2)
All the links in each of the .md files, must be process to replace pointers to *.md with *.html. (issue: https://github.com/github/pages-gem/issues/69)

This should cover all types of relative, anchor, and markdown style links (and not affect any external URLs). In order to keep links between files working, we should continue to use relative links so that files only link to those that correspond to that release version (within the same folder in gh-pages root).

Alternatively, we can hard code in the absolute urls and version's folder using `{{ site.url }}`/*vFolderVersion*/*relative_link_here.html.

Examples:  
Links like (but not limited to):

    `[link text](../filename.md)`
 - [example](https://raw.githubusercontent.com/RichieEscarez/kubernetes/gh-pages/vHEAD/index.md)

   `[Getting Started Guides](docs/getting-started-guides)`
 - [example](https://raw.githubusercontent.com/RichieEscarez/kubernetes/gh-pages/v1_0/README.md)

Must be changed to:

   `[link text](../filename.html)`

   `[Getting Started Guides](docs/getting-started-guides/README.html)`

(3)
Once the .md files are processed (front matter added and links fixed), then in order for us to be able to publish on kubernetes.io, we must copy those processed .md files into the corresponding folders in gh-pages (for v1.0, thats the 'v1_0' folder).

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by bgrant0607** [comment]
@nikhiljindal, @krousey, or @JanetKuo: Does one of you have time to work on this? @caesarxuchao has more to do on #11357

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by krousey** [comment]
I'll get an initial cut going.

Do we really want to have a vHEAD? That seems like a lot of churn for whatever process takes this over. Potentially every commit.

**Comment by krousey** [comment]
Is is possible to have javascript that just rewrites the links?

**Comment by nikhiljindal** [comment]
kubernetes.io/third_party/swagger-ui/ runs JS, so I dont think there is any restriction on running JS on kubernetes.io

**Comment by thockin** [comment]
that would be a cool trick - do you know JS well enough? :)

**Comment by krousey** [comment]
@thockin eh... not under a time limit.

**Comment by bgrant0607** [comment]
A couple issues I noticed:
* Single-`#` section titles aren't converted to html
* Code blocks don't have line breaks.

**Comment by caesarxuchao** [comment]
For the code blocks issue, we should replace ``` with ~~~

See [here](https://github.com/jekyll/jekyll/issues/3724#issuecomment-105170121)

**Comment by bgrant0607** [comment]
Issues reported by @thockin:

* markdown #### turns into centered HTML
* markdown ```yaml leaves the word yaml

**Comment by thockin** [comment]
markdown #### turns into centered HTML - I have a CSS fix

markdown ``` fenced code blocks render as one line - I have a config fix, but it has issues.  No coloring (I tried but I just can't make it work).  All three-tick code blocks need blank lines before and after

``` in general seems to work if you config for github markdown (sigh).

**Comment by thockin** [comment]
line-breaks in the middle of a link become real line-breaks:

e.g.:

[foo
bar](url)

**Comment by thockin** [comment]
scrolling should be independednt for nav and main window, or at LEAST clicking a nav link should warp you to top-of-page

**Comment by thockin** [comment]
aha, I got syntax highlights but it requires more transforms from plain old markdown

**Comment by thockin** [comment]
I think I fixed the #Header thing too

**Comment by thockin** [comment]
Fixed line wraps

**Comment by thockin** [comment]
We need a munger to enforce blank lines around ``` code blocks.

We need a munger to enforce a space after # (`# header` vs `#header`)

**Comment by bgrant0607** [comment]
http://stackoverflow.com/questions/13291272/how-to-change-all-links-with-javascript

**Comment by RichieEscarez** [comment]
Ive opened a PR ( #11423 ) to push the site files (minus the visible link to "Documentation") onto gh-pages. It includes the fix to the centered #### and also separate scrolling nav vs content area fixes.

**Comment by caesarxuchao** [comment]
Horizontal rule  ("---------") is rendered literally.

see title of
http://kubernetes.io/v1_0/docs/getting-started-guides/fedora/flannel_multi_node_cluster.html

**Comment by thockin** [comment]
I'm going nuts and nobody is here to stop me!  Muahahahaha

I merged Richie's PR.

I fixed the CSS (tsk tsk).

I offered a PR to turn on Github markdown, and then merged it myself.

Fixed:

# header is now H1.

``` code blocks render, without highlighting

### is not centered

Linebreaks are fixed

**Comment by thockin** [comment]
New problem - it never linebreaks.  Need some CSS help.

**Comment by thockin** [comment]
Issue: text overlap in the nav section with long names overflowing on top of the item below them.

**Comment by thockin** [comment]
I'm wrapping up for the night.

TODO:

- Limit width of text
- Limit width of code
- Try JS link rewrites
- update docs/examples
- script for updating docs
- munger for pound_headers_need_space
- munger for fenced_code_needs_blank_lines
- syntax coloring (needs a transform when importing)
- style issues
--- scrollbars on code blocks
--- overlapping nav text
--- some text descenders cut off (code)
- test the hell out of every link and nav

**Comment by bgrant0607** [comment]
Nice! It has come a long way.

I merged the outstanding mungers, a couple doc/example moves, some cross-linking PRs, and other doc changes. There are still a few changes in flight. After they land, we should do another doc copy.

**Comment by bgrant0607** [comment]
TOC is all one line separated by dashes. Should be nested bullet lists.

**Comment by thockin** [comment]
Kris should have a self-service doc-copier ready tomorrow, though we should
cherry-pick all docs and stuff into release-1.0 first

**Comment by bgrant0607** [comment]
Looks like we need a munger to insert blank lines before bullet lists, both the TOC style with dashes and bullets using asterisks.

**Comment by thockin** [comment]
I opened an internal spreadsheet to track all these issues today

**Comment by thockin** [comment]
Status update: great progress today.  More to do ASAP.  A bunch of style issues.  Nav content and links are paramount.  I am working on syntax styling.  @erictune reports an issue with mungers fighting with each other.

**Comment by caesarxuchao** [comment]
There are still dead links in the left side nav bar( e.g., user's guide->overview and concepts->nodes). Is someone working on it?

**Comment by bgrant0607** [comment]
Can we consider this done? Is there anything else we plan to do?

**Comment by thockin** [comment]
There's more to do.  Not emergency.  Close it :)
