### ISSUE TITLE
'expose' gives unnamed ports a name of "default"

### ISSUE THREAD

**Issue by rawlingsj** [GoogleCloudPlatform/kubernetes#11377]
Following on from a discussion yesterday #11296, when creating services using 'expose' it gives unnamed ports a name of "default".  There was a concern that this is a misfeature so issue raised here to track it.

The command used in this scenario was 
```
kubectl expose rc myservice --create-external-load-balancer=true --port=80 --target-port=9090
```

**Comment by lavalamp** [comment]
Yeah, I'd vote for it to be "". We can also improve our service proxy code to be more forgiving.

**Comment by thockin** [comment]
I agree we should not give it a name and that we can make the master proxy
try harder.

**Comment by bgrant0607** [comment]
I agree, though changing this would be a breaking change. We added versioning to generators for this reason. The right fix would be to create a "service/v2" generator with the new behavior and make it the default version, while retaining the v1 behavior.

**Comment by bgrant0607** [comment]
@nikhiljindal or @jlowdermilk: does either of you have time to do this today? If you're working on more critical 1.0 issues, we can let this slide.

We should at least document current behavior, if nothing else, however.

**Comment by nikhiljindal** [comment]
I can take this.

**Comment by thockin** [comment]
I don't really see it as a breaking change, at least not a very bad one -
any pods that exist will be fine.

But if we make the master proxy try to find the first port definition, we
can paper over this and call it done, for now.  Deprecate that, add a flag
that defaults to true, deprecate the flag and in a year change it to false?

**Comment by nikhiljindal** [comment]
Am updating kubectl expose to leave service ports unnamed in https://github.com/GoogleCloudPlatform/kubernetes/pull/11397

@thockin Didnt get you. Are you suggesting that we change master proxy to use the first port definition for now, but deprecate that later?

**Comment by bgrant0607** [comment]
OTOH, the kubectl change was pretty easy.

**Comment by thockin** [comment]
I was saying we should do both.

**Comment by bgrant0607** [comment]
I'm not sure it's worth it to rush this into 1.0.

**Comment by roberthbailey** [comment]
We should add this to the known issues bug.

**Comment by bgrant0607** [comment]
The kubectl change is ready to go
