### ISSUE TITLE
DNS_DOMAIN variable ignore during AWS Cluster setup

### ISSUE THREAD

**Issue by frosenberg** [GoogleCloudPlatform/kubernetes#11372]
I'm setting up a cluster on AWS. I want to use a custom domain name, however, the following environment variable seems to be ignored on the 1.0.0 release candidate (have not tried other versions):

```
export DNS_DOMAIN="mycompany.internal"
```

Anyone seeing this as well or am I doing something wrong.

**Comment by justinsb** [comment]
I don't think we let you change that on AWS.  (AFAICT, we don't let you change that on GCE etc either!)

Can I ask what you're trying to achieve by changing it?   This domain name is an internal implementation detail, that isn't exposed outside the cluster, and most pods inside the cluster will never notice either.

**Comment by frosenberg** [comment]
Fair enough. I was just wondering b/c it is exposed as environment variable in `aws/config-default.sh`.

We just wanted to adapt it, b/c we cross-configure some of our microservices with DNS name and we somehow wanted to have our "own" suffix. No big deal though.

Feel free to close.
