### ISSUE TITLE
Add serviceAccount to retain backward compatibility with 0.19

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#11380]
Forked from #11355.

GKE went to beta with 0.19 rather than 0.20, so now we need to support backward compatibility with 0.19. 

pod.spec.serviceAccount was renamed to pod.spec.serviceAccountName in #10081, which broke compatibility. We need to add serviceAccount back as a deprecated field and cross-populate each field from the other in conversion.

cc @liggitt @erictune @pmorie @mbforbes

**Comment by roberthbailey** [comment]
@mbforbes is working on a fix.

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by bgrant0607** [comment]
@mbforbes if you need help or have other fish to fry, @nikhiljindal could work on this.

**Comment by mbforbes** [comment]
It will be a fun exercise. I wouldn't mind a good review, though :-)

**Comment by liggitt** [comment]
I can jump in to help or review as well later tonight
