### ISSUE TITLE
Pods being double scheduled in Travis integration test

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#1139]
Binding is POST'd twice, the first time succeeds, the second times fails.  Maybe two schedulers running somehow?

https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/34210439#L2040

I can repro locally with hack/test-integration.sh (you see the errors in the logs).

EDIT: as per lavalamp, the scheduler doesn't see the results of scheduling the first pod before it tries to schedule a second pod.  Not high priority because it's able to recover and then correctly schedule.

**Comment by bgrant0607** [comment]
Is this still an issue?

**Comment by smarterclayton** [comment]
I don't believe so
