### ISSUE TITLE
kubelet agent fails to start containers defined inside the manifest

### ISSUE THREAD

**Issue by vially** [GoogleCloudPlatform/kubernetes#11407]
Creating a `container-vm` instance using a `containers.yaml` metadata manifest file results in an error:
`E0716 22:08:43.474283    2364 http.go:54] Failed to read URL: invalid pod: [metadata.name: invalid value '-containervm-test-1': must be a DNS subdomain (at most 253 characters, matching regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*): e.g. "example.com"]`

The easiest way to reproduce is by following the [quickstart example](https://cloud.google.com/compute/docs/containers/container_vms). The vm instance starts but the kubelet agent fails to start the containers defined inside the manifest.

**Comment by yujuhong** [comment]
@vially, the `containers.yaml` file in the examples is missing the "name" field in the pod.

You can try modify it to include a name (e.g., foo):
```
kind: Pod
metadata:
  name: foo
```

/cc @dchen1107 as I don't know who has the edit right of the page.

**Comment by dchen1107** [comment]
cc/ @bgrant0607 @erickhan Now we have an issue related to containervm here. :-)

**Comment by dchen1107** [comment]
@vially The issue should be fixed now.

**Comment by dchen1107** [comment]
cc/ @zmerlynn @roberthbailey

**Comment by zmerlynn** [comment]
This is an issue between `container-vm-v20150611` (which shipped with Kubelet 0.19.0) and `container-vm-v20150715` (which shipped with Kubelet 1.0.0). There was a breaking v1 API change that now requires the the metadata.name specification in the pod spec. We're updating the documentation now, but you can manually specify `--image container-vm-v20150611` as a workaround.

**Comment by zmerlynn** [comment]
@yujuhong: There's already an internal bug/code review out to fix the documentation.

**Comment by zmerlynn** [comment]
Closing. The documentation will be updated shortly. Thanks!

**Comment by thockin** [comment]
Late to this, but what was the breaking change?  I thought we accept name or generateName ?

**Comment by vially** [comment]
The problem was that the documentation was not mentioning that the `metadata/name` field of the Pod manifest is required as of image `container-vm-v20150715` (prior to that it didn't seem to be required).
