### ISSUE TITLE
Link to firewall docs gives 404 after creating a service of type LoadBalancer

### ISSUE THREAD

**Issue by rawlingsj** [GoogleCloudPlatform/kubernetes#11436]
After creating a service of type LoadBalancer information is displayed about configuring a firewall on GKE, the link displayed is an old location.  This is on v0.21.2.

```
An external load-balanced service was created.  On many platforms (e.g. Google Compute Engine),
you will also need to explicitly open a Firewall rule for the service port(s) (tcp:80) to serve traffic.

See https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/services-firewalls.md for more details.
```

**Comment by mikedanese** [comment]
Another doclink not checked. Do we version this url? cc @bgrant0607 @lavalamp @thockin

**Comment by thockin** [comment]
We do not subst any code files for versions.  Can you open a separate bug
for this?  It makes me a little anxious, but maybe we should process code
files as well.

**Comment by mikedanese** [comment]
This specific link is fixed on master:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/create.go#L130
