### ISSUE TITLE
Nodes Resize should be able to add nodes (Failed 2 times in the last 19 runs. Stability: 89 %)

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#11442]
Master tracking bug: #9312 

see e.g. runs:
- e2e-gce 7638
- e2e-gce 7631

failures:
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:456
Couldn't restore the original node instance group size: exit status 1

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:504
Expected error:
    <*errors.errorString | 0xc2085b3600>: {
        s: "timeout waiting for cluster size to be 4",
    }
    timeout waiting for cluster size to be 4
not to have occurred

**Comment by wojtek-t** [comment]
cc @jszczepkowski @piosz

**Comment by zmerlynn** [comment]
It's also been (unsurprisingly) noisy on `release-1.0`, so if you figure it out, please cherry-pick. (It's failed 2/30 on `kubernetes-e2e-gce-release`.)

**Comment by roberthbailey** [comment]
Do we have any logs from the kubelet or master during the flakes?

**Comment by roberthbailey** [comment]
This failed once on Saturday, but otherwise has been clean 29 of the last 30 runs. It also hasn't failed in the last 30 runs on `kubernetes-e2e-gce-release` tests targeting the `release-1.0` branch.

**Comment by wojtek-t** [comment]
It failed again 2 times today (e2e-gce runs: 7875 and 7879).

@piosz @jszczepkowski @fgrzadkowski - I think we should prioritize the fix for it now (as the important part of node autoscaling).

**Comment by piosz** [comment]
I believe increasing timeout should help.

**Comment by wojtek-t** [comment]
@piosz - I'm fine with increasing timeout. Can you please fix that?
