### ISSUE TITLE
RPM for Kubernetes-Mesos Integration

### ISSUE THREAD

**Issue by hrishimantri** [GoogleCloudPlatform/kubernetes#11455]
Hi @jdef/all,
Can we please have a rpm package for the master branch of kubernetes ?

**Comment by hrishimantri** [comment]
Any updates guys ?

**Comment by karlkfi** [comment]
We're concentrating on [DCOS](https://mesosphere.com/learn/) as our cluster package-manager of choice at this time.

**Comment by jdef** [comment]
as @karlkfi indicated, this isn't on our roadmap. if someone in the community wants to take this up we'll be happy to review PR's.

**Comment by jdef** [comment]
closing this out since it's not on our roadmap. rpm packaging should likely be captured in a separate repo anyway.
