### ISSUE TITLE
vagrant ssh very slow

### ISSUE THREAD

**Issue by wittyhandle** [GoogleCloudPlatform/kubernetes#11458]
I've run the setup to get a master and minion-1 vm running in vagrant, installation ran fine, but I find the commands to `vagrant ssh master` and `vagrant ssh minion-1` are very slow. It'll eventually work, but typically takes upwards of a minute to actually log onto the vm. I'm running vagrant version 1.7.2 and VirtualBox 4.3.30. I should mention that other VMs unrelated to kubernetes don't have this issue.

Has anyone else encountered this?

edit: output of kubernetes version:

```
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"21", GitVersion:"v0.21.3", GitCommit:"9411c5c55438658791ed204fb979e230be8a0dcd", GitTreeState:"clean"}
```

**Comment by derekwaynecarr** [comment]
I have not encountered this issue.

Is it reliably reproducible?

There is nothing special to my knowledge for how ssh in vagrant should be working.

**Comment by wittyhandle** [comment]
For me, it's not intermittent. Not sure what its hung up on exactly. I tried it again with VAGRANT_LOG=debug, didn't reveal much unfortunately:

```
DEBUG ssh: Checking key permissions: /Users/mike.ottinger/Projects/docker/kubernetes/.vagrant/machines/master/virtualbox/private_key
 INFO ssh: Invoking SSH: ["vagrant@127.0.0.1", "-p", "2222", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "/Users/mike.ottinger/Projects/docker/kubernetes/.vagrant/machines/master/virtualbox/private_key"]
Last login: Fri Jul 17 18:38:01 2015 from 10.0.2.2
```

More of an annoyance than anything since everything works otherwise.

**Comment by wittyhandle** [comment]
Not a problem anymore. I restarted my machine and performed a few updates to my mac. I also noticed an eset virus scan was in-progress during this slowness, may have nothing to do with the issue, but I've seen strange things with virus software before :)
