### ISSUE TITLE
Restarted pod/container does not recognize attached persistent disk as read/write

### ISSUE THREAD

**Issue by marcospedreiro** [GoogleCloudPlatform/kubernetes#11457]
I am unsure if this is an issue with Kubernetes/GCE or the database image I am using, so I am posting this here for now. I apologize if this is turns out to be an issue with the database image. 

Environment:

- Running a GKE cluster on GCE that has a replication controller managing a pod that runs a database container. 
- Manually attached disk to GKE cluster as read/write through console (I have not been able to automate this process).

Behavior:
If the replication controller for the database is deleted and recreated, there are no issues. However if the container/pod dies and gets automatically recreated, sometimes the database will crash and the logs will state that the filesystem is read only. When this happens, deleting the replication controller and recreating it fixes the issue. 

Replication controller:

```
{
   "kind":"ReplicationController",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"dev-influx",
      "labels":{
         "name":"influx"
         "function":"db"
      }
   },
   "spec":{
      "replicas":1,
      "selector":{
         "name":"influx"
      },
      "template":{
         "metadata":{
            "labels":{
               "name":"influx",
               "function":"db"
            }
         },
         "spec":{
            "containers":[
               {
                  "name":"influx",
                  "image":"influx:0.9.0",
                  "volumeMounts":[
                     {
                        "mountPath":"/var/opt/influxdb/",
                        "name":"dev-disk"
                     }
                  ],
                  "ports":[
                     {
                        "containerPort":8083,
                        "protocol":"TCP"
                     },
                     {
                        "containerPort":8086,
                        "protocol":"TCP"
                     }
                  ]
               }
            ],
            "volumes":[
               {
                  "name":"dev-disk",
                  "gcePersistentDisk": {
                     "pdName":"dev-disk",
                     "fsType":"ext4",
                     "readOnly":false
                  }
               }
            ]
         }
      }
   }
}
```

The influx image was built with a custom image to support data persistence upon container recreation. This is the docker file used to build the image: 

```
FROM ubuntu:14.04

RUN apt-get install -y curl

# Install InfluxDB
RUN curl -s -o /tmp/influxdb_latest_amd64.deb https://s3.amazonaws.com/influxdb/influxdb_0.9.0_amd64.deb && \
  dpkg -i /tmp/influxdb_latest_amd64.deb && \
  rm /tmp/influxdb_latest_amd64.deb && \
  rm -rf /var/lib/apt/lists/*

# Admin server
EXPOSE 8083

# HTTP API
EXPOSE 8086

WORKDIR /opt/influxdb/

CMD ./influxd -config /etc/opt/influxdb/influxdb.conf
```

**Comment by thockin** [comment]
@saad-ali

**Comment by saad-ali** [comment]
This sounds like the same problem as https://github.com/GoogleCloudPlatform/kubernetes/issues/11231#issuecomment-122049113 i.e. if a pod with a GCE PD volume is rapidly deleted and recreated the volume may appear empty (or in the worst case be corrupted).

@marcospedreiro could you please see if you can repro this issue with that patch (it was merged today).

**Comment by marcospedreiro** [comment]
I was able to recreate the same issue. I created a new cluster and disk, wrote some data, then deleted the pod with `kubectl delete pod <podname>`. The initial pod that came back had the container crash about 12 times with the `read only filesystem` message. 

After the 12 crashes the pod created a stable container and I was able to use my software, but there was no data visible. I deleted the pod and a new one was created without any crashes, but I was still unable to see any data. I deleted and recreated the replication controller and I was able to see my data again.

**Comment by saad-ali** [comment]
Thanks @marcospedreiro. I'll work on reproing this today.

**Comment by saad-ali** [comment]
@marcospedreiro I haven't been able to repro this.

I created a influxdb container using the Dockerfile you provided and pushed the image to my nodes.

I created a RC using the JSON you provided. I had to change `v1beta3` to `v1` because `v1beta3` is no longer supported.

A pod was successfully created by the RC. I deleted the pod using `kubectl delete pod <podname>` and the RC automatically created a new pod. The new pod started without issues on the same node.

Could you verify what Kubernetes version you are running (`kubectl version`)? Also are you able to consistently repro this? Are there any steps that I missed?

**Comment by marcospedreiro** [comment]
@saad-ali I only saw that issue the one time and have not been able to reproduce. Thank your for your help. If I am able to reproduce I will post here.

**Comment by saad-ali** [comment]
@marcospedreiro I'm going to close this for now as no-repro. If you run in to this issue again please reopen this bug and don't hesitate to reach out to me. Thanks again for the report!
