### ISSUE TITLE
kubectl describe node should include allocated resource

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#11498]
kubectl describe node reports node capacity, but not allocated resource. And there is no easy to retrieve such data today. Basically the user has to go through all pods allocated on a node, and sum the resource limits together to figure out. This is easy to handle by introduce a ResourceAllocated field to NodeStatus API, and let kubelet reports such information.

**Comment by yujuhong** [comment]
Closing this as dup of #11238
