### ISSUE TITLE
Cannot create pods properly on Ubuntu with k8s v1.0.0

### ISSUE THREAD

**Issue by dalanlan** [GoogleCloudPlatform/kubernetes#11544]
The cluster is created via [Docker](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md), and i have only one machine acting as master node currently.
The components talk to each other via HTTPS, certs stuff i mean.

Everything seems fine to me unless i try to deploy dns (v8).
It complains as 
$ kubectl --namespace=kube-system create -f skydns-rc.yaml 
Error from server: error when creating "skydns-rc.yaml": ReplicationController "kube-dns-v8" is forbidden: Namespace kube-system does not exist

 /cc @antoineco

**Comment by dalanlan** [comment]
Made some progress by changing the parm "--admission-control" of api-server to be less sensitive. 

And then came across a new one as #8734. I added the "--containerized" for kubelet and enforcing the SElinux, which leads me to

# docker logs for kubelet 
E0719 05:56:34.501091       1 kubelet.go:1190] Unable to mount volumes for pod "kube-dns-v8-cjlqc_kube-system": fork/exec /nsenter: no such file or directory; skipping pod
E0719 05:56:34.507480       1 pod_workers.go:111] Error syncing pod c57b6408-2dda-11e5-b392-f8bc1298bf7c, skipping: fork/exec /nsenter: no such file or directory


docker version:1.7.1
k8s version:1.0.0
/cc @pmorie

**Comment by dalanlan** [comment]
Also I bet "--containerized" may not be ready currently?

**Comment by antoineco** [comment]
Regarding the first post, with the recommended admission controls you're expected to create namespaces manually, bit apparently you figured that out.

Are you running your kubelet in privileged mode?

**Comment by dalanlan** [comment]
U R a great help@antoineco 
I did fix it myself yesterday though ;-) Thx anyway.
Closing it.

**Comment by asdfsx** [comment]
@antoineco I'm new to kubernets, and I got the same problem.
```shell
$ cluster/kubectl.sh create -f cluster/addons/kube-ui/kube-ui-rc.yaml --namespace=kube-system 
Error from server: error when creating "cluster/addons/kube-ui/kube-ui-rc.yaml": ReplicationController "kube-ui-v1" is forbidden: Namespace kube-system does not exist
```
and I can not find  'kube-system' in namespace.
```shell
$ cluster/kubectl.sh get namespace
NAME      LABELS    STATUS
default   <none>    Active
```
So you mean I should create the kube-system manualy?
If so , how to create a namespace ?

**Comment by antoineco** [comment]
You need to create this namespace beforehand indeed (at least with the default admission control).

Take a look at this: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/namespace.yaml
