### ISSUE TITLE
doc needs fix

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#11564]
In https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/scratch.md, the "Alternate, manual approach:" list is messed up, because the markdown interpreter requires extra spaces before sub-list, e.g.
the following markdown source code:
```
1. aaa
- bbb
```
won't be rendered as 

1. aaa
  - bbb

but

1. aaa
- bbb

I opened an issue for this because it's an interesting fact, and to remind myself to fix it.

**Comment by davidopp** [comment]
Instead of doing this as a separate PR, I'd suggest that you add it to the review thread on #11454. Somehow I missed that when I was reviewing the PR (but it hasn't been submitted yet).
