### ISSUE TITLE
Missing download for Release 1.0.1

### ISSUE THREAD

**Issue by DreadPirateShawn** [GoogleCloudPlatform/kubernetes#11581]
It looks like the "kubernetes.tar.gz" download is missing from the 1.0.1 release.

https://github.com/GoogleCloudPlatform/kubernetes/releases

All other releases have three downloads --
[kubernetes.tar.gz](https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v0.21.4/kubernetes.tar.gz)
[Source code (zip)](https://github.com/GoogleCloudPlatform/kubernetes/archive/v0.21.4.zip)
[Source code (tar.gz)](https://github.com/GoogleCloudPlatform/kubernetes/archive/v0.21.4.tar.gz)

However, the latest release, v1.0.1, only provides the latter two:
[Source code (zip)](https://github.com/GoogleCloudPlatform/kubernetes/archive/v1.0.1.zip)
[Source code (tar.gz)](https://github.com/GoogleCloudPlatform/kubernetes/archive/v1.0.1.tar.gz)

In particular, the usual "kubernetes.tar.gz" download includes a "server" directory, which contains "kubernetes-server-linux-amd64.tar.gz", which contains binaries for kube-apiserver, kubectl, kube-controller-manager, kube-proxy, etc... These are what I'm looking for.

**Comment by brendandburns** [comment]
Fixed.  Sorry about that!

--brendan
