### ISSUE TITLE
Left Nav bar "Escalating" is misspelled 

### ISSUE THREAD

**Issue by erickhan** [GoogleCloudPlatform/kubernetes#11591]
Under header below, should be spelled as "Escalating". Taking heed of your point about left nav bar link state.

--------------
Support
> Esculating Security Issues

**Comment by erickhan** [comment]
@thockin @caesarxuchao

**Comment by caesarxuchao** [comment]
cc @RichieEscarez

**Comment by RichieEscarez** [comment]
This entry was removed for GA as the content was not ready (ive noted this for in the near future when this content gets added). Closing.
