### ISSUE TITLE
Where is kubelet.md?

### ISSUE THREAD

**Issue by feihujiang** [GoogleCloudPlatform/kubernetes#11642]
I knew there was kubelet.md in docs directory before. But now I couldn't find it now, where is it?

**Comment by davidopp** [comment]
docs/admin/ directory
We've done a fairly large reorganization of our docs in the past couple of weeks. Hopefully it is easier to navigate now, but a lot of files moved.

**Comment by feihujiang** [comment]
Thanks for your quickly reply!
