### ISSUE TITLE
Run scale tests somewhere

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#11658]
```
Scale [Skipped] should be able to launch 500 pods, 10 per minion, in 25 rcs/thread.

Scale [Skipped] should be able to launch 500 pods, 10 per minion, in 5 rcs/thread.
```

The scale tests aren't being run anywhere.

_(x/ref: #10548 / https://github.com/GoogleCloudPlatform/kubernetes/issues/10548#issuecomment-122398038 / https://github.com/GoogleCloudPlatform/kubernetes/issues/10548#issuecomment-123013303/ )_

+cc @ixdy @wojtek-t @rrati

**Comment by davidopp** [comment]
I believe they are supposed to be running here
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-scalability/
but it appears it got misconfigured and isn't running anything.

**Comment by wojtek-t** [comment]
@davidopp - I don't understand your comment.
e2e-gce-scalability suite is running "Density 30 pods" and "Load capacity" (with sleeping and "working" pods)
This is working as intended.

**Comment by davidopp** [comment]
Ah sorry, you're right, it is running 3/100 tests and I thought the yellow bar extended all the way to 100 (running 0/100 tests).

**Comment by gmarek** [comment]
I tried running those tests and they reliably fail, which is a good reason for not running them. We get errors similar to:
```
 Expected error:
      <*errors.errorString | 0x4c208361a10>: {
          s: "Only 9 pods started out of 20",
      }
      Only 9 pods started out of 20
  not to have occurred
```

The main reason is that this test ignores `max-pods`, which would be OK, if RunRC had longer timeout. Currently for 500 pods, 10 pods per Node and 5 RCs per thread we try start: `500 / 10 * 5 = 10` threads , each of which creates 10 pods per Node, hence we try to start 100 pods/Node which is currently impossible.

I'm not quite sure what this test was supposed to test, so I don't know how to fix this. We can either limit number of pods, merge test-kubelet-config PR and increase max-pods to bigger number, increase timeout in RunRC, or do something different (e.g. delete this test if we don't think it does anything useful).

**Comment by gmarek** [comment]
IMO this test is useless now. In my understanding the reason for this test was to verify that concurrent RC creation works as expected. This is covered by load.go test right now. Create #11691 to remove this test.

**Comment by ixdy** [comment]
Scale tests were removed.
