### ISSUE TITLE
Links in types.go is outdated

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#11677]
For example, this [line](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L146) in v1/types.go directs people to http://releases.k8s.io/HEAD/docs/labels.md, which is moved to http://releases.k8s.io/HEAD/docs/user-guide/labels.md now. 

Because the api-reference [page](http://kubernetes.io/v1.0/docs/api-reference/definitions.html) is built based on types.go, so the links there are also outdated.

@mikedanese, I thought you were helping moving those docs around. Do we have any handy scripts that update the links? I'm trying not to reinvent the wheel. Thank you.

cc @RichieEscarez @bgrant0607

**Comment by nikhiljindal** [comment]
We also have a valid link checker in mungedocs. We should run it on types.go as well.
cc @lavalamp

**Comment by mikedanese** [comment]
@thockin

**Comment by bgrant0607** [comment]
This is 3 issues:
1. Fix the links in HEAD
2. Fix the links on kubernetes.io and maybe 1.0.1
3. Extend the link checker

**Comment by caesarxuchao** [comment]
IIUC, the links in HEAD v1/types.go should be
 http://releases.k8s.io/HEAD/docs/user-guide/labels.md,

the link in kubernetes.io should be http://kubernetes.io/v1.0/docs/user-guide/labels.html,

and the links in release-1.0 branch v1/types.go should be
http://releases.k8s.io/release-1.0/docs/user-guide/labels.md?

**Comment by bgrant0607** [comment]
Ideally, all of the release links would direct to the appropriate release on kubernetes.io, and on HEAD to http://releases.k8s.io/HEAD/docs/user-guide/labels.md.

**Comment by caesarxuchao** [comment]
fixed by #11726
