### ISSUE TITLE
validate-cluster fails. Waits for ready nodes

### ISSUE THREAD

**Issue by vmrekhate** [GoogleCloudPlatform/kubernetes#11689]
I am following the same steps as mentioned for configuration on the github page. I am trying to create a master and minion on the same machine (using localhost).
This is the error I get:
![ubuntu-plain-five-2015-07-22-18-28-24](https://cloud.githubusercontent.com/assets/5052424/8826412/ff6a3154-30a3-11e5-87c6-a0861fd034db.png)

P.S. I followed the same method last week and it was working fine for me. I was trying again on the new system with the same configuration as the older system, and I'm running into this error.
Please help.

**Comment by gmarek** [comment]
I'm not familiar with Ubuntu setup, but can you log into Node and check `/var/log/startupscript.log` and/or `/var/log/kubelet.log` for errors?

**Comment by vmrekhate** [comment]
I'm using this document for reference: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

And I cannot find any log files in the locations you mentioned.

**Comment by gmarek** [comment]
What's your setup? Are you running on multiple physical machines? It seems to me that you don't have any Nodes/Minions set up.

**Comment by vmrekhate** [comment]
I'm running the cluster on a single machine configuring it as master-minion. However, while setting up the earlier cluster, I didn't have to install docker manually, it got installed with the build.sh script.
However installing docker as mentioned here: https://docs.docker.com/installation/ubuntulinux/
resolved the issue.
Thanks for the help.
