### ISSUE TITLE
How to make two nodes offer same service with same IP

### ISSUE THREAD

**Issue by dieuroi** [GoogleCloudPlatform/kubernetes#11681]
I cannot understand the mechanism about routing forwarding. 
If I used *docker run* to launch a container with port mapping, I could find information about port forwarding.

```
 docker ps -a
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                                 NAMES
bf7fa5c5d7e9        sles12/apache:latest   "/bin/sh -c 'service   34 minutes ago      Up 34 minutes       80/tcp, 145.0.36.182:40000->455/tcp   backstabbing_pike 
```

Then I created a replicationController with two pods containing an apache on the same node. I also created a service which map port 80 in container to 30000 for outer access. I can have access to both apache in pods, but I cannot see the information in the result of *docker ps -a*.

```
 docker ps -a
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                                 NAMES                                                              
02764d31f726        sles12/apache:latest   "/bin/sh -c 'service   46 minutes ago      Up 46 minutes                                             k8s_suseapache.167cc_test-1jyr5_default_b0ca3fd3-2f95-11e5-8a5a-90e2ba30bcd4_9f9b16e7   
cea23882be42        sles12/apache:latest   "/bin/sh -c 'service   49 minutes ago      Up 49 minutes                                             k8s_suseapache.167cc_test-ayh4h_default_b0ca256d-2f95-11e5-8a5a-90e2ba30bcd4_ca02ea18   
c976491f7ac2        pause:latest           "/pause"               20 hours ago        Up 20 hours                                               k8s_POD.bbb5e038_test-1jyr5_default_b0ca3fd3-2f95-11e5-8a5a-90e2ba30bcd4_a2b744de       
3543fac2b4bd        pause:latest           "/pause"               20 hours ago        Up 20 hours                                               k8s_POD.bbb5e038_test-ayh4h_default_b0ca256d-2f95-11e5-8a5a-90e2ba30bcd4_4d5f3dfd   
```

I checked iptables  with *iptables -nvL -t nat* and found Kubernetes map inner port 80 to a random port then to outer port 30000. Now I have two questions. First, when I visit the site how Kubernetes decides which port would offer service for me. Second, if I have two nodes, what can I do to make this two nodes offer same service with same IP address and port.

**Comment by gmarek** [comment]
If you create a RC with two Pods, you don't have a guarantee that they'll land on the same Node (in ordinary case).

Kubernetes completely overwrites Docker networking - design is explained [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/networking.md) and user guide is [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/services.md).

**Comment by dieuroi** [comment]
@gmarek  I know if I create a RC with two Pods, they may land on different Nodes. But now in each Pod, there is an apache container for another program. The IP of Node A is 188.0.45.182, The IP of Node B is 188.0.45.183, how can I use one IP to offer service for another program.

**Comment by gmarek** [comment]
Pods have their own IPs, so Node IPs are not important. To have a single entry point for multiple Pods you should create a Service on top of them.

**Comment by dieuroi** [comment]
Though I read the user guide of service, I still found no parameter to make the IP address of the entry point for multiple Pods. The outer program need the service has no access to the inner IP address of Pods.

**Comment by gmarek** [comment]
You use a Service IP. Take a look at e.g. [guestbook example](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook). IP address of a Service is random, so you need to either use DNS to find it, or environment variables that are create on all Nodes when Service is created.

**Comment by dieuroi** [comment]
Thank you, I' ll try.

**Comment by gmarek** [comment]
@dieuroi - closing this Issue, please reopen if issue persists.

**Comment by test-shyam** [comment]
?
