### ISSUE TITLE
https://get.k8s.io/ not pulling 1.0 release

### ISSUE THREAD

**Issue by mbabker** [GoogleCloudPlatform/kubernetes#11699]
Running through setup right now using the https://get.k8s.io/ bash script and version 0.21.3 was downloaded to my system.

**Comment by davidopp** [comment]
Same for me.

Seems to be because 'curl https://storage.googleapis.com/kubernetes-release/release/stable.txt' returns 'v0.21.3'

@zmerlynn @roberthbailey

**Comment by roberthbailey** [comment]
@brendandburns mentioned to me right before lunch that I forgot to run mark-stable.sh. I just ran it so curling that file should now print v1.0.1.
