### ISSUE TITLE
[1.0.1] Web Interface /ui does not load

### ISSUE THREAD

**Issue by laguiz** [GoogleCloudPlatform/kubernetes#11697]
I have an issue with https://x.x.x.x/ui endpoint.

All endpoints from page https://x.x.x.x/ are working : 
```
{
  "paths": [
    "/api",
    "/api/v1",
    "/api/v1beta3",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
```
except this url : https://x.x.x.x/ui/ .

For the url `https://x.x.x.x/ui/` i got asked user/password and get redirected to `https://x.x.x.x/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/` but nothing usable is visible. Sometimes I start to see left panels and the logo on top left but most of the time it does not show anything.

Tried on latest Chrome and FF on MacOS.

I think the service is properly setup (some resources like html, js and css are loaded) but I cannot figure out why UI does not load properly.

![image](https://cloud.githubusercontent.com/assets/550822/8830256/8db22ab0-309b-11e5-9dce-94ed9218f7f5.png)

I guess I got it loaded properly once : 

![image](https://cloud.githubusercontent.com/assets/550822/8830591/4dce8cc0-309d-11e5-8c4b-103905e5426f.png)

Even after loading it one time properly it does not load anymore.

On master I did not find any clue from log files `kube-apiserver.log`, `kube-controller-manager.log` and `kube-scheduler.log`. (I may post the contant if required).

I'm not sure if related to https://github.com/GoogleCloudPlatform/kubernetes/issues/11684 . In my case it's start to load but not completely.

Available to help debugging the situation (angular app or making so tests to reproduce the issue).

**Comment by jweissig** [comment]
Suspect this might be related to #11119

**Comment by laguiz** [comment]
Definitely similar. Can be closed.

**Comment by vishh** [comment]
Closing in favor of #11119
