### ISSUE TITLE
Clarify merge policy

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#11757]
It's sometimes confusing to contributors what our current merge policy is (1 LGTM, 2 LGTM, ok-to-merge, blahty-blah). There's a lot of us that live this stuff, but even then, we should probably just have a markdown doc that specifies the current policy, and link to it off of https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md and maybe https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/faster_reviews.md (since the latter seems to be a guide on pushing your review along).

(It's also possible I'm missing it?)

cc @brendandburns @goltermann @thockin @bgrant0607

**Comment by bgrant0607** [comment]
We changed the policy at least 3 times and different kinds of PRs have different policies, so it's not surprising that you're confused.

We need to decide what policy we want going forward. 2 LGTMs for every change was pretty onerous, but certain kinds of changes should require approval by a TL / area owner.

**Comment by zmerlynn** [comment]
This was actually more for everyone else. I can poke @brendandburns most of the time (he's sitting right here), but he's not as convenient as a markdown doc. I opened this because it might be handy if everyone just had a place to go that was canonical, instead of guessing.

**Comment by goltermann** [comment]
Yes, once the post v1.0 policies are hammered out, we'll be putting everything in docs somewhere.  There will be more stable policies going forward, so things shouldn't be changing much at all once decided.
