### ISSUE TITLE
broken doc link

### ISSUE THREAD

**Issue by jmccormick2001** [GoogleCloudPlatform/kubernetes#11771]
this link appears to be broken today, July 23

http://kubernetes.io/v1.0/docs/api-reference/operations.html

I tried to click on 'Kubernetes API Reference' in the left nav bar on the main documentation
site and it shows the above as the URL.  Nothing shows in the right side panel.

http://kubernetes.io/v1.0/docs/api-reference/operations.html

**Comment by vishh** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
@RichieEscarez

**Comment by RichieEscarez** [comment]
fix by #11717
