### ISSUE TITLE
"What is Kubernetes?" on kubernetes.io shows 404

### ISSUE THREAD

**Issue by cleung2010** [GoogleCloudPlatform/kubernetes#11799]
The documentation site http://kubernetes.io/v1.0/docs/whatisk8s.html leads to a 404.

**Comment by RichieEscarez** [comment]
the source file in master was just merged but #11723 wiped out the temporary copy (script was run before the merge). the next time the script runs, this wont happen.

**Comment by thockin** [comment]
Richie, I do not see that file in master

**Comment by RichieEscarez** [comment]
Sorry Tim, got my Issues/windows mixed up. This is the PR with the file that should be in master. Im just working through the check errors then it can be merged.

**Comment by thockin** [comment]
I thnik I fixed it.

**Comment by thockin** [comment]
Richie,

I have to run now.  I added back .md files but something is weird.

This loads:

http://kubernetes.io/v1.0/docs/api-reference/operations.html

But when I go through the nav bar it doesn't... Help?

**Comment by RichieEscarez** [comment]
Oh, hmm. We need to delete those .html files out of that directory and replace them with the .md files here #11717. Ill open another PR to push those .md files into master too.

**Comment by RichieEscarez** [comment]
The .html files are overloading the Jekyll build (output from the .md files). See #11717 for the PRs i opened to fix this.
