### ISSUE TITLE
Links in docs to releases.k8s.io/... pages are just redirecting to kubernetes.io landing page

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#11853]
I'm seeing this on Chrome on OS X. All requests to releases.k8s.io are just getting a 302 and redirecting to the kubernetes.io landing page, rather than into the docs, regardless of whether I use HTTP or HTTPS. For example, try any of the 3 links in the [DNS doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/dns.md).

@RichieEscarez @lavalamp @brendandburns

**Comment by thockin** [comment]
Will take a look ASAP - later tonight.

**Comment by nikhiljindal** [comment]
It was broken yesterday, but the links are working fine for me right now.

But, shouldnt those links be relative? Why are they pointing to releases.k8s.io?
http://releases.k8s.io/HEAD/cluster/addons/dns/README.md should instead be ../../cluster/addons/dns/README.md?

**Comment by thockin** [comment]
We fixed the site config, but yeah those should be relative.

**Comment by thockin** [comment]
I'm wrong.  Only docs/... and examples/... are relative because of gh-pages
not having a full checkout of code.

**Comment by nikhiljindal** [comment]
aah ok.
