### ISSUE TITLE
service found need some help, thanks

### ISSUE THREAD

**Issue by sunvooker** [GoogleCloudPlatform/kubernetes#11876]
I have a cluster made up of ubuntu nodes 192.168.1.108 ("ai"), 192.168.1.111("i"), 192.168.1.112("i"), following the example guestbook-go project, I create the guestbook-controller(rc : 3 replicas) and created guestbook service (192.168.3.18 : 3000), in every node, i use "curl http://192.168.3.18:3000" I can load the guestbook service web page, but I found a strange problem, when guestbook-controller decrease to 2, then in one node machine i use "curl http://192.168.3.18:3000" command, will response "curl (56) recv failure: Connection reset by peer".

In the failed node, I checked iptables with "iptables -nvL -t nat", which exist the port redirect, and "nc -zv 192.168.3.18 3000" reponse "connection succeeded!"

so why curl command in one node failed ? any suggestion is welcome, thanks.

**Comment by antoineco** [comment]
Sounds like a network issue between your nodes. Are you using an overlay network to let your containers talk to each other across nodes?

What does `kubectl describe se/guestbook` return?

**Comment by sunvooker** [comment]
![image](https://cloud.githubusercontent.com/assets/13518194/8902042/4ea1da26-3480-11e5-8348-2867a45e1ff1.png)

this is my service return.

**Comment by sunvooker** [comment]
cluster step: 1. git clone the kubernetes master.
2. vi config-default.sh , change the "export nodes=xxxx", which replace myself machine
3. call ./build.sh download the ubuntu os cluster binary
4. call ./kube-up.sh  which run the cluster
5. goto guestbook-go example. kubectl create -f guestbook-controller.json   & kubectl create -f guestbook-service.json
6. only i change is the guestbook-controller.json,  the pods number, when change to 2, there must one machine no pod in it, so curl command is fail. that's my problem. It's looks that proxy can't cross the machine.

**Comment by antoineco** [comment]
That's why I'm asking if you set up an overlay network between your nodes to let the container networks reach each other.

Look at these two documentation pages:
* [docs/design/networking.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/networking.md)
* [docs/getting-started-guides/scratch.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/scratch.md)

They both suggest easy solutions like [flannel](https://github.com/coreos/flannel).

**Comment by sunvooker** [comment]
thanks, I will test it.

**Comment by sunvooker** [comment]
sorry! I follow this guide:https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md
and it looks like that containering the flannel.
for verified flannel is working, what can I do. 
thanks!!

**Comment by sunvooker** [comment]
the guestbook has two pods: one vip:172.16.1.2  and in the node: 10.1.140.209;  
the other vip:172.16.26.2 and correspond node: 10.1.142.157.  
in the any node, I ping 172.16.1.2 and 172.16.26.2, that's all successfull.

**Comment by sunvooker** [comment]
I just kube-down / kube-up,  but this time everything is ok, I don't understand, but thanks!
