### ISSUE TITLE
unable to execute kubectl exec  on pod (v1.0.1)

### ISSUE THREAD

**Issue by loky9000** [GoogleCloudPlatform/kubernetes#11898]
Ubuntu 14.04
Mesos 0.22.0
kubectl describe pod mysql
Name:				mysql
Namespace:			default
Image(s):			mysql:5.7
Node:				ec2-54-161-243-202.compute-1.amazonaws.com/10.183.211.227
Labels:				name=mysql
Status:				Running
Reason:
Message:
IP:				172.17.0.4
Replication Controllers:	<none>
Containers:
  mysql:
    Image:	mysql:5.7
    Limits:
      cpu:		500m
    State:		Running
      Started:		Mon, 27 Jul 2015 19:33:53 +0000
    Ready:		True
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	True
....
Events:
Mon, 27 Jul 2015 19:33:53 +0000	Mon, 27 Jul 2015 19:33:53 +0000	1	{kubelet ec2-54-161-243-202.compute-1.amazonaws.com}	spec.containers{mysql}			created			Created with docker id 159cd9a39692
  Mon, 27 Jul 2015 19:33:53 +0000	Mon, 27 Jul 2015 19:33:53 +0000	1	{kubelet ec2-54-161-243-202.compute-1.amazonaws.com}	spec.containers{mysql}			started			Started with docker id 159cd9a39692

$ kubectl  exec mysql -c mysql date
error: Error executing remote command: Error executing command in container: failed to exec in container - Exec setup failed - No such container: 159cd9a396922bbdad87a784d6b5034671dca7ba8e5b439715e9fe013f3b7ba6

**Comment by loky9000** [comment]
the same on other pods

**Comment by loky9000** [comment]
cluster configured by https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md

any ideas why?

**Comment by mbabker** [comment]
I've personally found that the `kubectl` binaries don't seem to be running well with AWS but using the `cluster/kubect.sh` script does work OK.  So give that a shot in the meantime?

**Comment by thockin** [comment]
You're going to have to provide more details if you hope to get real help.
We'd love to help you but this is not enough to do anything with.

**Comment by loky9000** [comment]
Resolved:
old version of docker on mesos slave (v1.0.1)
