### ISSUE TITLE
why kube-dns not working 

### ISSUE THREAD

**Issue by sunvooker** [GoogleCloudPlatform/kubernetes#11924]
I make up a cluster with 3 machine, one is master (ai), two nodes (i). 
following this guide:https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/README.md

step1 create a test pod, OK.
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always

step2 wait for this pod to go into the running state.
I also get expected result.

but step3 Validate DNS works,  there response error info.
   nslookup: can't resolve 'kubernetes'

ps: use commond kubectl get pods --all-namespace & kubectl get services --all-namespace, i saw that exist kube-k8s pods and service,  but why nslookup is failed??
I will attach the screen picture below.

thanks very much for your help!!!!

**Comment by sunvooker** [comment]
<img width="648" alt="busy" src="https://cloud.githubusercontent.com/assets/13518194/8931292/b7ec0640-3567-11e5-9548-d39952c6a5ca.png">

**Comment by sunvooker** [comment]
in my 3 nodes, only one node can do nslookup success,
![image](https://cloud.githubusercontent.com/assets/13518194/8931949/8e54d76c-356c-11e5-9831-dfda5ed08b2e.png)

the other two response error
<img width="663" alt="docker2" src="https://cloud.githubusercontent.com/assets/13518194/8932001/dbe52c2a-356c-11e5-8e5f-cbd815e13c61.png">

**Comment by ArtfulCoder** [comment]
I believe you have a "reachability" issue where containers on different nodes cant ping to each other.
You were able to use dns when you tried the lookup from a container on the same node as the dns pod.

I would start with checking if containers in different nodes can ping each other..

**Comment by loky9000** [comment]
the same  on kubernetes v1.0.1 and mesos 0.22.0

**Comment by sunvooker** [comment]
I use kubernetes v1.0.1 also.

**Comment by sunvooker** [comment]
when I use command kube-up.sh, why the KubeDNS is auto run, 

![image](https://cloud.githubusercontent.com/assets/13518194/8948070/838d2fd2-35d5-11e5-9b1d-f282cf95d66d.png)


In this guide : https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md
which say you must deployAddons so active the DNS, so which error???

**Comment by dalanlan** [comment]
I believe that's because you didnt tear down the rc before u rebuild the cluster.
Use`$ KUBERNETES_PROVIDER=ubuntu ./kube-down.sh` before rebuilding, if you please.

**Comment by nasry** [comment]
Hello guys,
I am installing kubernetes (master + 3 nodes) and I have kube-dns problem, the `nslookup kubernetes` works only in containers  that are installed on the same node in which kube-dns is installed, in the other nodes I get `** server can't find kubernetes: NXDOMAIN`
ps : I can ping nodes from each others
