### ISSUE TITLE
Any way to close insecure port api-server serves on for now

### ISSUE THREAD

**Issue by dalanlan** [GoogleCloudPlatform/kubernetes#11920]
According to [this guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/accessing-the-api.md), it seems not possible for now. 8080 would be listened by default.
Just to confirm. Am i missing sth?

**Comment by mikedanese** [comment]
By default it listen's on 127.0.0.1 so it is not visible on the network. Does that satisfy your concern?

**Comment by dalanlan** [comment]
Not really. If only i could even make that non-reachable ( even it may not seem reasonable)

**Comment by mikedanese** [comment]
Currently it will always be visible insecurely local to the master. We advise that you lock down access to the master regardless. What is your use case?

**Comment by dalanlan** [comment]
It fits these scenarios - - I take over someone's machines and make them a cluster, yet i would prefer he cannot access the api-server by himself in some way ;-)
