### ISSUE TITLE
No events for Pods deleted due to lost node 

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#11993]
When a node is lost and the corresponding pod is deleted, there is no trace of that pod getting deleted in the event stream.

To repro:

* Create a new pod w/o a replication controller
* Disable the node in question -- i did it by killing the kubelet and keeping it dead on that node.  (for GCE, this means disabling/modifying monit)
* Wait ~5 minutes
* Notice the pod is gone
* Run `kubectl get ev` and see that there is no event to mark that pod going away.

**Comment by bprashanth** [comment]
The node controller should send this event, it's caused us clarity problems in the past  (https://github.com/GoogleCloudPlatform/kubernetes/issues/10306) @gmarek

**Comment by gmarek** [comment]
I'll fix this in not-too-distant future.
