### ISSUE TITLE
Kubelet shouldn't need compute scope to register w/ apiserver (on GCE)

### ISSUE THREAD

**Issue by cjcullen** [GoogleCloudPlatform/kubernetes#12000]
Kubelet calls cloud.Instances().ExternalID(), which makes a call to gce.service.Instances.Get(). The externalID is on the metadata server. We should get it from there.

**Comment by cjcullen** [comment]
This is one piece of #8074.  Arguably more important, because right now you can't get a functional cluster without compute.read. We should be able to give you a functional cluster with 0 scopes on the nodes (it just won't be able to mount PDs or use gcr.io private repos).

**Comment by zmerlynn** [comment]
@brendandburns / @goltermann: The PR for this one slipped through the cracks for 1.0.2. I removed the label from the ones where we actually had cherry picks already.

Not sure where this was supposed to fit in the process.
