### ISSUE TITLE
Update-demo-nautilus

### ISSUE THREAD

**Issue by adyanthaya17** [GoogleCloudPlatform/kubernetes#12018]
Hi, 

Update-demo-nautilus folder was taken out from the kubernetes example. I needed to know where I could find it .It would be of great help.

**Comment by roberthbailey** [comment]
I think you are looking for https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/update-demo/README.md.

**Comment by adyanthaya17** [comment]
Thank you, that's what I was looking for.
