### ISSUE TITLE
Mess in controllers code.

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#12072]
Currently code for various controllers is spread out around whole codebase (replication controller in `controller` directory, node controller, route controller and service controller in `cloud_provider`, other controllers in other places). In addition naming is inconsistent, some of them are called XYZController, other XYZManager.

This is confusing (and can be annoying).

cc @wojtek-t @bgrant0607

**Comment by gmarek** [comment]
I'm going to make naming uniform, and move all controllers that are 'real' controllers (i.e. are started in controller-manager) to `controller` directory.

**Comment by bgrant0607** [comment]
Ref #4851

**Comment by bprashanth** [comment]
@mikedanese we already have controller/replication

**Comment by gmarek** [comment]
All controllers are now in controller directory.
