### ISSUE TITLE
NFS Server Example Fails

### ISSUE THREAD

**Issue by mbabker** [GoogleCloudPlatform/kubernetes#12093]
Attempting to follow the [NFS example](http://kubernetes.io/v1.0/examples/nfs/README.html) and deploy to GCE, the server pod fails to deploy correctly.

Issue 1:

```sh
The Pod "nfs-server" is invalid:spec.containers[0].securityContext.privileged: forbidden '<*>(0xc20a04618c)true'
```

Removing the `securityContext` from the [pod's container spec](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/nfs/nfs-server-pod.yaml) gets past this issue at least and allows the pod to deploy.

Issue 2:

Once the pod reaches the running state, the logs show the mount failed to set itself up:

```sh
Michaels-MacBook-Pro-2:kubernetes mbabker$ ./cluster/kubectl.sh logs nfs-server
Serving /mnt/data
mount: permission denied
rpc.nfsd: Unable to access /proc/fs/nfsd errno 2 (No such file or directory).
Please try, as root, 'mount -t nfsd nfsd /proc/fs/nfsd' and then restart rpc.nfsd to correct the problem
NFS started
```

**Comment by thockin** [comment]
Privilege is required for NFS

**Comment by mbabker** [comment]
Even after changing the `privilege.sls` on the master and each node in my cluster, the same issues came up.  And since that file isn't shipped as part of the tagged release package (which I'm using), there's no way to edit it on my local system.

Is this something that I need to run from the git base on?

**Comment by mbabker** [comment]
OK, so after getting my local system running on a recent git build (commit 136d53466a4e82b8cebc046c62785578f268f044 because of the memory issues in that open issue), I was able to deploy a pod with NFS.

But, now I have to ask.  For what reason is the `cluster/saltbase` folder [removed from the tagged releases](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/build/common.sh#L760)?  If editing contents in this folder is a requirement to deploy NFS, its contents should definitely be included in the release package or instructions on how to put it in place included.

**Comment by mbabker** [comment]
I'm going to close this and open a new issue for documentation.  Copying the cluster/saltbase directory from git to the downloaded 1.0.1 release I'm working from got things working OK from the release tag.  Something in the docs advising about this would definitely be helpful.

**Comment by NOX73** [comment]
@mbabker

> I was able to deploy a pod with NFS

could you explain how did you do that?

**Comment by mbabker** [comment]
Essentially had to build from Git to do it.  Privilege has to be compiled into the binaries it seems.

**Comment by NOX73** [comment]
I did the same, but still both issue actual. How do you rebuild your cluster?
I use ubuntu provider.

**Comment by mbabker** [comment]
I've been deploying on GCE with mostly default configs (the only 2 changes in the git tree are setting privilege to true in `cluster/saltbase/pillar/privilege.sls` and changing the disk type for the master since I'm on a trial account at the moment).  The cluster has to be deployed with the binaries and packages from the git build, so if you have any existing SHA signatures in your local system or packages uploaded to your hosting infrastructure you'll need to delete those before issuing the `kube-up` command.

**Comment by four43** [comment]
Note: 1.1.0 has this enabled by default.

But `make release` at the root has been what's working for me after making the changes @mbabker suggested. Make sure you're using the correct `kubectl`, mine was in `{{project root}}/_output/release-stage/full/kubernetes/platforms/linux/amd64/kubectl` after being built. Just FYI as I play with this NFS stuff.
