### ISSUE TITLE
Fix path to kube-up.sh in Ubuntu Getting Started Guide

### ISSUE THREAD

**Issue by ae6rt** [GoogleCloudPlatform/kubernetes#12126]
The ubuntu.md markdown file contains an invocation of kube-up.sh whose path is wrong.

The cited path is ./kube-up.sh.

It should be ../kube-up.sh

**Comment by WIZARD-CXY** [comment]
I'm sorry about this guide is not very straightforward, so many people have changed it  
but the doc said
`
After all the above variables being set correctly, we can use following command in cluster/ directory to bring up the whole cluster.
`

**Comment by ae6rt** [comment]
I'm sorry I missed that sentence.

I'm fine with declining this PR.  Given that sentence, the markdown does not need to be changed.
