### ISSUE TITLE
OpenStack implementation does not pass SubnetID when creating a VIP

### ISSUE THREAD

**Issue by jgriffiths1993** [GoogleCloudPlatform/kubernetes#12131]
When creating a load balancer in OpenStack, the call to vips.create() does not pass the subnet ID - this is required, thus all calls fail.

**Comment by spothanis** [comment]
Have you made sure that the config file that is used to initialize kube-controller-manager has a subnet-id field is properly set to id of the network in which vips are to be created?

**Comment by jgriffiths1993** [comment]
Yeah that's all set
The problem is in the `getAddressByName` function in `openstack.go`:
```
if s == "" {
    if tmp := findAddrs(srv.Addresses["private"]); len(tmp) >= 1 {
        s = tmp[0]
    }
}
if s == "" {
    if tmp := findAddrs(srv.Addresses["public"]); len(tmp) >= 1 {
        s = tmp[0]
    }
}
```
In our implementation of OpenStack Kilo, for example, the network name is neither *private* nor *public* and so will be `srv.Addresses["myNetworkName"]`

I think it would be best to range over srv.Addresses or get the network name from the *SubnetID* and use that as the key

**Comment by jgriffiths1993** [comment]
I have indeed but it isn't passed with `vips.CreateOpts`

The issue is at `vips.CreateOpts` in `openstack.go` - it should have `SubnetID: lb.opts.SubnetId,`

**Comment by spothanis** [comment]
True, I remember fixing it in my local repo sometime ago, but somehow forgot to send a PR. Sorry my bad
