### ISSUE TITLE
Docs UI: closes and opens menu items on each back-and-forth

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#12150]
Load a page in a sub-menu.  Then click another page in that same submenu.  Then go back and forward between them.  It closes and opens the menu on each back-and-forth, even if that sub-menu was already open.

**Comment by thockin** [comment]
@RichieEscarez

**Comment by RichieEscarez** [comment]
Sorry i missed this in my inbox and opened #12154 , ill close this one since ive added details in the other.
