### ISSUE TITLE
Human readable times in `kubectl`

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#12280]
Instead of:
```console
$ kubectl get events
FIRSTSEEN                         LASTSEEN                          COUNT     NAME          KIND      SUBOBJECT   REASON             SOURCE         MESSAGE
Tue, 21 Jul 2015 16:25:06 -0700   Wed, 05 Aug 2015 08:56:09 -0700   416805    frontend4     Pod                   failedScheduling   {scheduler }   Failed for reason MatchNodeSelector and possibly others
```
let's print
```console
$ kubectl get events
FIRSTSEEN        LASTSEEN         COUNT     NAME          KIND      SUBOBJECT   REASON             SOURCE         MESSAGE
15 days ago      30 seconds ago   416805    frontend4     Pod                   failedScheduling   {scheduler }   Failed for reason MatchNodeSelector and possibly others
```

That save about 30 characters of width.  We could have a flag like `--machine-readable-time` or something to enable the old behavior.  Default to the new.

We could use https://gowalker.org/github.com/dustin/go-humanize or just write a 20 line function that specifically handles humanized time printing.

**Comment by erictune** [comment]
Same thing for when we print events at the end of a `describe`.

**Comment by erictune** [comment]
@hurf this might interest you since you made a similar change last month.

**Comment by hurf** [comment]
@erictune - sure, I'll working on it.

**Comment by bgrant0607** [comment]
We have a more concise printer we use for the AGE column.

**Comment by hurf** [comment]
@bgrant0607 I also noticed the function we used to format time. And I mentioned this in the PR for ideas.  In latest patch I have made the output same with the old style.
