### ISSUE TITLE
[contrib] ansible playbook fails on Copy master binaries

### ISSUE THREAD

**Issue by brianlund** [GoogleCloudPlatform/kubernetes#12392]
using both fedora 22 on AWS and RHEL7 I get the following:

TASK: [master | Copy master binaries] ***************************************** 
<172.31.234.22> ESTABLISH CONNECTION FOR USER: fedora
fatal: [172.31.234.22] => input file not found at /home/fedora/kubernetes/contrib/ansible/roles/_output/local/go/bin/kube-apiserver or /home/fedora/kubernetes/_output/local/go/bin/kube-apiserver

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/cluster.retry

172.31.234.21              : ok=21   changed=1    unreachable=0    failed=0   
172.31.234.22              : ok=67   changed=1    unreachable=1    failed=0   
172.31.234.23              : ok=21   changed=1    unreachable=0    failed=0

**Comment by shanemikel** [comment]
What did you to to fix this?

**Comment by brianlund** [comment]
It was user error. I hadn't actually build kubernetes so there was nothing to copy.

Running "make all" in the kubernetes top dir, ensured there was something in _output for ansible to work on.

**Comment by ls42** [comment]
> Running "make all" in the kubernetes top dir

I think this should be added to the documentation [here](http://kubernetes.io/v1.0/docs/getting-started-guides/fedora/fedora_ansible_config.html), since it's not mentioned in the `Prerequisites`.

**Comment by brianlund** [comment]
Agreed. If I had been more familiar with Ansible I would probably have found the solution faster than I did, but since I am not, it had me puzzled for a bit.

**Comment by ls42** [comment]
On a sidenote: Just building is not enough, the platform has to match, too. Of course *cough*. Means building the binaries on Mac OS X and then deploying them via ansible does not work, they have to be built on linux, too.

I built them on the kube-master and the rsync'ed them to my mac host. That worked.
