### ISSUE TITLE
1.1 roadmap update - Docker 1.7/1.8 target

### ISSUE THREAD

**Issue by countspongebob** [GoogleCloudPlatform/kubernetes#12409]
https://github.com/GoogleCloudPlatform/kubernetes/milestones

Per contributor meeting today, could we update doc to specify Docker 1.7.1 as minimum, and 1.8.x as aspirational?

**Comment by dchen1107** [comment]
This is a reasonable request, and I marked https://github.com/GoogleCloudPlatform/kubernetes/issues/8918 for 1.1 and will send pr shortly.

**Comment by bgrant0607** [comment]
Done
