### ISSUE TITLE
Bringup of Kubernetes Cluster on Ubuntu fails

### ISSUE THREAD

**Issue by bharbhi** [GoogleCloudPlatform/kubernetes#12412]
Image used: Ubuntu Cloud image: trusty64.
Created using Vagrant
URL followed: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

Issue:

1) Cluster does not comeup when following the instructions in the URL.

2) The issue is when validating minion. The script gets stuck in a loop. Pls note that i have ssh-keygen on all the servers and have copied the all the keys to all the nodes such that the ssh from one to another node does not require any password to be manually entered.

3) Additionally, /etc/hosts and cluster/ubuntu/config-default.sh has been updated accordingly

4) The loop is due to failure of ''pgrep -f $daemon' for kubelet & docker on minion as part of verify-minion(). Due to this failure, validated is always set to 1 leading to unending loop.

5) When i checked the minion, only kube-proxy is running while kubelet and docker does not run. Hence the failure

6) To my surprise, same check pass'es on master (act as minion too) even-though it does not run kubelet and docker.

Additional Logs details.

Found following in Master kubelet.log
W0807 18:32:58.517411   10907 server.go:462] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such fi                le or directory. Trying auth path instead.
W0807 18:32:58.518003   10907 server.go:424] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_a                uth: no such file or directory. Continuing with defaults.
mountpoint for cpu not found
W0807 18:32:58.586369   10914 server.go:462] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such fi                le or directory. Trying auth path instead.
W0807 18:32:58.591661   10914 server.go:424] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_a                uth: no such file or directory. Continuing with defaults.
mountpoint for cpu not found
W0807 18:32:58.667236   10922 server.go:462] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such fi                le or directory. Trying auth path instead.
W0807 18:32:58.667625   10922 server.go:424] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_a                uth: no such file or directory. Continuing with defaults.
mountpoint for cpu not found

Found following in kube-proxy.log on the master.

W0807 18:16:27.430306    6029 server.go:86] Failed to start in resource-only container "/kube-proxy": mountpoint for cpuset not found
E0807 18:16:27.805696    6029 api.go:180] Unable to load endpoints: Get http://10.33.75.103:8080/api/v1/endpoints: dial tcp 10.33.75.103:8080: connection refused
E0807 18:16:27.811698    6029 api.go:108] Unable to load services: Get http://10.33.75.103:8080/api/v1/services: dial tcp 10.33.75.103:8080: connection refused
W0807 18:32:57.356008    6029 api.go:153] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:EOF Reason: Details:<nil> Code:0}
W0807 18:32:57.357278    6029 api.go:224] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:EOF Reason: Details:<nil> Code:0}
W0807 18:32:57.583511   10808 server.go:86] Failed to start in resource-only container "/kube-proxy": mountpoint for cpu not found
E0807 18:32:57.821289   10808 api.go:180] Unable to load endpoints: Get http://10.33.75.103:8080/api/v1/endpoints: dial tcp 10.33.75.103:8080: connection refused
E0807 18:32:57.826259   10808 api.go:108] Unable to load services: Get http://10.33.75.103:8080/api/v1/services: dial tcp 10.33.75.103:8080: connection refused

**Comment by satnam6502** [comment]
@zmerlynn @derekwaynecarr can either of you help or is there someone else we can ask?

**Comment by hw-qiaolei** [comment]
Hi bharbhi,
From your description I suspect the failure is due to docker does not installed or started properly, so the validation of nodes failed. Please verify your docker installation using 'dpkg-query -l lxc-docker'.  if it is not installed please use 'apt-get install lxc-docker' to install it (Note it is 'lxc-docker' here not 'docker'). The tutorial requires a docker version 1.2+. On my testbed it is 1.7.1

**Comment by bharbhi** [comment]
Thanks HangZhou. Yes. It is issue with docker. After correcting the docker issue, things work.

Sorry for the confusion. Closing this case.

**Comment by bharbhi** [comment]
It was issue with docker. Probably the install script can check the version and installation of docker on all nodes.
