### ISSUE TITLE
PersistentVolumeClaim get output is not useful

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#12439]
Related to #12424, the output for `get pvc` could be improved

```
$ oc get pvc/pvc-90ahi
NAME        LABELS    STATUS    VOLUME
pvc-90ahi   map[]     Pending   
```

Labels is incorrect, should be using formatLabels.  The claim size for storage should be printed as a column since that is almost always used, and if bound should probably be the actual capacity.

**Comment by smarterclayton** [comment]
@markturansky

**Comment by timothysc** [comment]
cc @childsb

**Comment by hurf** [comment]
I can work on it.

**Comment by markturansky** [comment]
@hurf thanks but i got it.

**Comment by hurf** [comment]
OK, I though it has been opened for 3 days, but I forgot the weekend:-)
