### ISSUE TITLE
Kubernetes keeps attempting to create an ELB even after service is removed

### ISSUE THREAD

**Issue by thesamet** [GoogleCloudPlatform/kubernetes#12445]
When kubernetes fails to create an ELB for a service, it will keep attempting to create one every few seconds, even if the services that triggered the ELB creation has been deleted.

**Comment by satnam6502** [comment]
@justinsb

**Comment by a-robinson** [comment]
Which version are you hitting this on? The repeated attempting should at least stop after a few minutes if you're on 1.0.2 or later, which pulled in #11891.

Sorry for the issue!

**Comment by a-robinson** [comment]
Also, closing this in favor of #9382. Let's try to keep the discussion there unless this seems to be something different.
