### ISSUE TITLE
Fix minor typo in docs/admin/authentication.md

### ISSUE THREAD

**Issue by ae6rt** [GoogleCloudPlatform/kubernetes#12473]
Change 

Basic BASE64ENCODEDUSER:PASSWORD

to

Basic BASE64ENCODED(USER:PASSWORD)

to make it clearer that base64 is performed over the user:pass string, rather than just the user string.

**Comment by a-robinson** [comment]
Looks like this was fixed by #12475. Thanks @ae6rt!
