### ISSUE TITLE
Previously failed pods are visible in kubectl get pods

### ISSUE THREAD

**Issue by mwielgus** [GoogleCloudPlatform/kubernetes#12479]
See the log below. A pod (created by a RC) failed to schedule several times. All of the failed attempts are visible along with the one that succeeded. RC's replicas is set to 1. 

```
$ kubectl get pods --all-namespaces

NAMESPACE     NAME                                           READY     STATUS                RESTARTS   AGE
[...]
kube-system   monitoring-heapster-v7-1xljv                   1/1       Running               1          1m
kube-system   monitoring-heapster-v7-czp8j                   0/1       InsufficientFreeCPU   0          1m
kube-system   monitoring-heapster-v7-iio5r                   0/1       InsufficientFreeCPU   0          1m
kube-system   monitoring-heapster-v7-r1ddh                   0/1       InsufficientFreeCPU   0          1m
```
ref: #12476

**Comment by yujuhong** [comment]
Thanks for reporting the issue. It is a known issue that terminated pods need to be manually deleted. Related open issues are:
 - #7660: Reap terminated pods
 - #9979: kubectl delete rc does not delete terminated pods

There is also an open PR to hide failed pods in the output of `kubectl get pods` for clarity: #12102 
Closing this bug as a duplicate.
