### ISSUE TITLE
RBD defencing issue

### ISSUE THREAD

**Issue by gambol99** [GoogleCloudPlatform/kubernetes#12481]
Appear to have an issue when tearing down a RBD volume, a stack trace below; The rbd unmap works fine, the volume is removed successfully, but the unlocking throws an exception

    Aug 10 14:07:20 core101 hyperkube[3665]: W0810 14:07:20.383951    3665 kubelet.go:1355] Orphaned volume "cad31130-3f67-11e5-a5bb-06baeabbce11/data" found, tearing down volume
    Aug 10 14:07:20 core101 hyperkube[3665]: W0810 14:07:20.384023    3665 kubelet.go:1355] Orphaned volume "cad31130-3f67-11e5-a5bb-06baeabbce11/logs" found, tearing down volume
    Aug 10 14:07:20 core101 sudo[11723]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/lsmod
    Aug 10 14:07:20 core101 hyperkube[3665]: E0810 14:07:20.665110    3665 util.go:68] Recovered from panic: "integer divide by zero" (runtime error: integer divide by zero)
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:62
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:53
    Aug 10 14:07:20 core101 hyperkube[3665]: /usr/src/go/src/runtime/asm_amd64.s:401
    Aug 10 14:07:20 core101 hyperkube[3665]: /usr/src/go/src/runtime/panic.go:387
    Aug 10 14:07:20 core101 hyperkube[3665]: /usr/src/go/src/runtime/panic.go:24
    Aug 10 14:07:20 core101 hyperkube[3665]: /usr/src/go/src/runtime/sigpanic_unix.go:33
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go:82
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go:176
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go:267
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/rbd/disk_manager.go:100
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/rbd/rbd.go:230
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/rbd/rbd.go:226
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1359
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1491
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1784
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1739
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:741
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:670
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:111
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:112
    Aug 10 14:07:20 core101 hyperkube[3665]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:93
    Aug 10 14:07:20 core101 hyperkube[3665]: /usr/src/go/src/runtime/asm_amd64.s:2232

The code throws a "divide by zero" exception in the following line; 

    // construct lock id using host name and a magic prefix
    lock_id := "kubelet_lock_magic_" + node.GetHostname("")
    
    l := len(b.Mon)
    // avoid mount storm, pick a host randomly
    start := rand.Int() % l  <--- HERE .. the size of the monitor array
    // iterate all hosts until mount succeeds.
    for i := start; i < start+l; i++ {
    
   This structure is read in from the persisted rbd.json file 

    ip-10-50-2-93 rbd-image-gitlab-data # pwd
    /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-gitlab-data
    ip-10-50-2-93 rbd-image-gitlab-data # cat rbd.json 
    {"Pool":"rbd","Image":"gitlab-data","ReadOnly":false,"Mon":["10.50.10.100:6789","10.50.11.100:6789","10.50.12.100:6789"],"Id":"admin","Keyring":"/etc/ceph/keyring","Secret":"A KEY"}

Which appears to be valid; I'm guessing the file is incorrectly decoded and the []Mon is empty causing a INT % 0 and thus exception. A few things to note; as the rbd fencing code is not yet merged into a release (lives only in master branch) this kubenetes binaries i'm using (for testing :-) ) are built out of master .. 

    [jest@starfury kube]$ kubectl version
    Client Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-448-g73cb04ad6b49c9-dirty", GitCommit:"73cb04ad6b49c9dad641c2f69fa2e9725e766f72", GitTreeState:"dirty"}
    Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1464+2bfa9a1f98147c-dirty", GitCommit:"2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb", GitTreeState:"dirty"}

**Comment by a-robinson** [comment]
@rootfs @markturansky

**Comment by rootfs** [comment]
@a-robinson yes, the wrong struct is the problem. LGTM, thanks!
