### ISSUE TITLE
Proposal: Internal Dynamic DNS service

### ISSUE THREAD

**Issue by markllama** [GoogleCloudPlatform/kubernetes#1261]
There are instances where DNS is the best way to publish the presence of network resources.

Within a Kubernetes cluster minions, containers and services all have distinct IP addresses but in many cases these objects may need to migrate in a way which changes the IP.  Clients that are consuming these services can find the new IP if they use DNS names rather than IP address as the service handle.  The DNS records may change but the names will remain stable.

One specific case has raised this issue.

On each minion, when a new container is created the container is provded an environment variable SERVICE_MASTER.  This variable indicates the location of the Kubernetes service proxy to which the processes within the container should connect. The value of this variable is a hostname (FQDN) which should resolve _from within the container_ to the public IP address of the minion on which the container resides.  It is not possible for Kubernetes, through Docker to inject a value into /etc/hosts into the container.  It is possible for Docker to inject a nameserver IP address into /etc/resolv.conf. If the DNS service indicated correctly resolves the value of SERVICE_MASTER to the IP address of the hosting minion, then the processes within the container will connect properly to the minion proxy process.

Since Kubernetes is a dynamic service the DNS service must also be dynamic.  New minions may be added (for this particular case).  It may also be desirable to publish services with SRV records as well. As new IPs are allocated and names assigned, the Kubernetes service must be able to update the DNS name/address maps.

DNS service relies on several factors:

*  DNS server(s)
 * Must have stable IP address(s)
 * Must have allocated zones for dynamic update
 * Must respond to update queries
 * Should require signature on update queries

* DNS clients
 * must be provided the IP address of DNS servers
 * Must be provided the FQDN of names to be resolved (A, SRV, TXT, PTR records)
 * May be provided the zone names

Docker provides a means to inject the nameserver values for /etc/resolv.conf in new containers.

1. What values should be stored in DNS?
1. What components are aware of new IP allocation and hence able to initiate DNS updates?
1. How does one notify/configure the Kubernetes master/cluster about the presence of the DNS
 service?
1. How does one coordinate the sharing of update keys between the DNS service and Kubernetes?
1. When if ever is it acceptable to override the default nameserver injection into a new container?
1. What are the set of optimal DNS master/slave servers and how do we initialize and maintain them?

Solution proposals to follow.

**Comment by thockin** [comment]
Closing for now.  There's more to do, but I think the primary goal here has been achieved, no?
