### ISSUE TITLE
Write a shell script guideline for Kubernetes

### ISSUE THREAD

**Issue by filbranden** [GoogleCloudPlatform/kubernetes#1266]
So that I don't have to repeat the same issues on each code review :-)

**Comment by roberthbailey** [comment]
@filbranden Any progress on this? Or should we just point folks to https://google-styleguide.googlecode.com/svn/trunk/shell.xml and keep trying to reduce the amount of bash that we depend on?

**Comment by filbranden** [comment]
@erictune I agree that Google Style Guide is a good start and maybe that's all we need...

Reducing the amount of bash would be a great goal.

**Comment by erictune** [comment]
Closing for now to keep our open issue count manageable.
