### ISSUE TITLE
Configurable restart behavior

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#127]
Right now we assume that all containers run forever. We should support configurable restart behavior for the following modes:
1. run forever (e.g., for services)
2. run until successful termination (e.g., for batch workloads)
3. run once (e.g., for tests)

The main tricky issues are:
1. what to do for multi-container pods
2. what to do for replicationController

We should also think about how to facilitate implementation of custom policies outside the system. See also:
https://github.com/GoogleCloudPlatform/container-agent/issues/9

**Comment by bkeroackdsc** [comment]
"I have not been able to think of a single valid use case where containers within the pod should have different restart policies. It seems confusing, unnecessarily complex, and likely to promote misuse of the pod abstraction, such as with all proposed use cases in this issue."

My use case (#9836) involves an application which reads etcd for configuration--this configuration must be populated on pod startup, but will vary based upon execution environment (controlled by environmental variables set in the RC spec). I have a container which runs an application that writes a templated set of configuration data to etcd and then exits.

So the alternative to this pattern is to have a "configurator" pod, which is tightly bound to another "application" pod, and must discover it via service lookup? *That* seems unnecessarily complex and confusing to me.

**Comment by smarterclayton** [comment]
The alternative is a start-hook that does all this configuration before your main container is started.

----- Original Message -----

**Comment by thockin** [comment]
I don't think this issue should be re-opened.  There are a number of options for how to do this (some may be more implemented than others).

* Wrap your real app in a loader script that fetches config, writes it, then exec()s your app
* Implement an init-phase of a pod, wherein all init containers must exit successfully before all non-init containers can start
* Run a sidecar container that writes an "OK to go" file to a volume, block your app on the existence of that file
* Make your app wait until the etcd value you need exists, gracefully handle it not existing or being too old

I do not think that changing the restart policy to per-container is the right answer (and I argued for it earlier in this issue - I was wrong).

**Comment by davidopp** [comment]
> Implement an init-phase of a pod, wherein all init containers must exit successfully before all non-init containers can start

So implicitly, the restart policy for the init containers is always RestartPolicyOnFailure?

> Run a sidecar container that writes an "OK to go" file to a volume, block your app on the existence of that file

What is the restart policy for the sidecar container?

> Make your app wait until the etcd value you need exists, gracefully handle it not existing or being too old

How does the etcd configuration get populated?

**Comment by davidopp** [comment]
(I'll re-close the issue but am curious about the above.)

**Comment by bkeroackdsc** [comment]
@thockin My hack works for now, but I'm thinking option #1 (wrap application in loader script) is probably the best way forward if per-container restart policies are off the table. The pod init phase concept is interesting, though.

**Comment by thockin** [comment]
>> Implement an init-phase of a pod, wherein all init containers must exit successfully before all non-init containers can start
>
> So implicitly, the restart policy for the init containers is always RestartPolicyOnFailure?

Pretty much.

>> Run a sidecar container that writes an "OK to go" file to a volume, block your app on the existence of that file
>
> What is the restart policy for the sidecar container?

Same as the rest of the pod, idempotency is for the user to provide.

>> Make your app wait until the etcd value you need exists, gracefully handle it not existing or being too old
>
> How does the etcd configuration get populated?

By a side-car loader container.

**Comment by thockin** [comment]
yeah, I think an init phase is a pretty nice feature.

**Comment by bgrant0607** [comment]
If initializing a specific volume, then #831 is the way to go.

Otherwise, a pod-level pre-start hook.

This doesn't need to be reopened -- see also #9836 and #4282.

**Comment by maicohjf** [comment]
> @smarterclayton First, I think the master should delegate the basic restart policy to the slave: always restart, restart on failure, never restart. The master should only handle cross-node restarts directly. And, yes, the master should pull status from the slaves and store it (#156), as well as periodically check their health (#193). As scaling demands grow, that responsibility could indeed be split out to a separate component or set of components.
> 
> Reason for last termination (#137), termination message from the application (#139), time of last termination, and number of terminations should be among the information collected. State of terminated containers/pods should be kept around on the slaves long enough for the master to observe it the vast majority of the time (e.g., 10x the normal polling interval, or 2x the period after which an unresponsive node would be considered failed, anyway; explicit decoupling of stop vs. delete would also enable the master to control deletion of observed terminated containers/pods), but the master would record unobserved terminations as having failed, ideally with as much specificity as possible about what happened (node was unresponsive, node failed, etc.). A monotonically increasing count of restarts could be converted to approximate recency, sliding-window counts, rates, and other useful information by continuous observers. A means of setting or resetting the count is sometimes useful, but non-essential. Termination events could also be buffered (in a bounded-sized ring buffer with an event sequence number) and streamed off the slave and logged for debugging, but shouldn't be necessary for correctness, since events could always be lost.
> 
> Reasons for system-initiated container stoppages (e.g., due to liveness probe failures - #66) should be explicitly recorded (#137), but can be treated as failures with respect to restart policy. User-initiated cancellation should override the restart policy, as should user-initiated restarts (#159).
> 
> With more comprehensive failure information from libcontainer and Docker we could distinguish container setup errors from later-stage execution failures, but if in doubt, the slave (and master) should be conservative about not restarting "run once" containers that may have started execution.
> 
> Containers should have unique identifiers so the system doesn't confuse different instances or incarnations (#199).
> 
> Overall system architecture for availability, scalability, fault tolerance, etc. should be discussed elsewhere.

Create a Kubernetes Secret as follows:
 Name: super-secret
 Credential: alice or username: bob
Create a Pod named pod-secrets-via-file using the redis image which mounts a secret named
super-secret at /secrets
Create a second Pod named pod-secrets-via-env using the redis image, which exports credential
/ username as TOPSECRET / CREDENTIALS

kubectl create secret generic spuer-secret --from-literal=Credential=alice
apiVersion: v1
kind: Pod
metadata:
      name: pod-secrets-via-file
spec:
      containers:
      - name: pod-secrets-via-file
         image: redis
         volumeMounts:
         - name: super-secret
           mountPath: "/secret"
       volumes:
       - name: super-secret
         secret:
             secretName: super-secret

apiVersion: v1
kind: Pod
metadata:
    name: pod-secrets-via-env
spec:
    containers:
    - name: pod-secrets-via-env
       image: redis
       env:
       - name: TOPSECRET
         valueFrom:
            secretKeyRef:
                name: super-secret
                key: Credential
