### ISSUE TITLE
All remote resources should be fetched over HTTPS

### ISSUE THREAD

**Issue by kseifriedredhat** [GoogleCloudPlatform/kubernetes#128]
There's a whole lot of stuff being downloaded/connected to over HTTP instead of HTTPS, this should be either configurable or ideally done via HTTPS by default.

**Comment by a-robinson** [comment]
Is this meant to now refer to communication from the client rather than from the node components?  If not, then it and #129 are covering the same thing and this should be closed.

**Comment by kseifriedredhat** [comment]
If you replace all these with TLS via #129 then yes, that would cover this. Does your documentation specifically state that the intra cluster nodes need to have a trusted network, becauce if not this should probably be given a CVE.

**Comment by alex-mohr** [comment]
TODO: audit code for all usage of http instead of https and file separate issues for each non-benign one.  E.g. apiserver to same machine etcd is fine via http.

**Comment by erictune** [comment]
This audit was done and reported in #129

**Comment by roberthbailey** [comment]
I did a quick audit of the `cluster/` directory to see where I could find places that we are fetching grab resources over the internet and found the following:

In build scripts (Makefiles / Dockerfiles):
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/images/hyperkube/Makefile#L6
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile#L24
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/kibana-image/Dockerfile#L13
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/images/nginx/backports.list#L1

In cluster initialization scripts:
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L295-L296
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/libvirt-coreos/util.sh#L120
 1. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/rackspace/cloud-config/master-cloud-config.yaml#L121

**Comment by roberthbailey** [comment]
The intra-cluster audit was covered in #129 and I've done an audit over cluster initialization scripts here and sent PRs to fix a couple of easy cases and filed separate bugs for the remaining occurrences. Marking this issue as fixed.
