### ISSUE TITLE
Error messages from GetPodInfo of unscheduled pods causes confusion

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1285]
pod_cache.go:UpdateAllContainers passes CurrentState.Host directly to updatePodInfo, which immediately calls GetPodInfo:
```
err := p.updatePodInfo(pod.CurrentState.Host, pod.ID)
```

This results in obscure log messages like:
pod_cache.go: pod_cache.go:83] Error synchronizing container: Get http://:10250/podInfo?podID=apache: dial tcp :10250: connection refused

Note lack of host name.

This could be a symptom of a problem, such as the scheduler not running. Or, it's possible the pod just hadn't been scheduled yet. A clearer error message, such as "pod apache not yet scheduled" would make troubleshooting faster (or possibly unnecessary).

Example IRC discussion: https://botbot.me/freenode/google-containers/2014-09-11/?msg=21477410&page=8

**Comment by rsokolowski** [comment]
@bgrant0607 , is this still an open issue ? The code that computes PodStatus checks whether Host is empty and returns PodPending in this case without obscure error (https://github.com/GoogleCloudPlatform/kubernetes/blob/2ac6bbb7eba7e69eac71bd9acd192cda97e67641/pkg/master/pod_cache.go#L160)

**Comment by bgrant0607** [comment]
Probably not. Thanks.
