### ISSUE TITLE
Decision: Standardize on Rudder/Flannel for k8s networking?

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#1307]
Rudder could be built into a separable layer that takes various environments and has various techniques to make IP-per-pod a reality.

This is forked from the discussion in #1059.

cc: @thockin, @eyakubovich

---

Details on plumbing GCE advanced routing into Rudder:

From @eyakubovich:
> There's a PR in Rudder that adds an allocation mode (should get merged soon). It adds the ability to allocate a subnet but it doesn't do anything to the data packets. It just writes the allocation to /run/rudder/subnet.env and signals systemd that it has started. Another dependency could wait on that and issue the GCE command to setup its advanced routing. I would also be happy to create a GCE mode that would do that inside Rudder.

I actually think that for GCE would be a little more complicated.  Configuring routes in the GCE API would require permission to call out to the API.  I think that we need a "reconciler" that takes the IP ranges assigned to a node and mirrors that into the routes in the GCE API.

A quick sketch of what this might look like:
1. A new node is started in GCE and rudder is installed.  An CIDR is assigned (/24) to that node via the "try and allocate in etcd" method.
2. Rudder is knows that we are doing "simple" networking and no encapsulation is involved.  Instead, we ensure that all traffic to the wider IP space (e.g. 10.0.0.0/8) is put on the wire directly.  (Stuff outside that space would be NATd through the DHCP assigned host IP.
3. A centralized reconciler (running someplace with permission to talk to the GCE API) would pick up the fact that this /24 was assigned to a specific node.  It would in turn call the GCE API to ensure that all traffic to that /24 was forwarded to that node.
4. Furthermore, if a node goes away, this centralized reconciler will know to remove that route.

I think that this model might be necessary for other places where network gear needs to be programed based on dynamic allocations made by rudder.

**Comment by errordeveloper** [comment]
I believe that the original discussion here is mostly overtaken by the plugins introduced with #5069. The only question that still remains is whether there needs to a default plugin or not, but that's a separate discussion, I believe.

**Comment by kamalmarhubi** [comment]
Given @errordeveloper's comment above, should this issue be closed? Came across it and the current state is slightly ambiguous.

**Comment by bgrant0607** [comment]
Yes, thanks.
