### ISSUE TITLE
Kubernetes centos support

### ISSUE THREAD

**Issue by abilash222** [GoogleCloudPlatform/kubernetes#1328]
i dont find any documents for kubernetes to be installed in centos. it will be great if you can make it common to all linux os. i dont know whether this can be done, can you provide a docker file which will create a image with kubernetes installed and we will configure the minions through ui.

**Comment by HackToday** [comment]
@eparis, I hit same issue when following the ansible fedora guide.


Redirecting to /bin/systemctl start  kubelet.service
Failed to issue method call: Unit docker.socket failed to load: No such file or directory.


I checked your comment said:

 change it from enabling docker.socket to docker.service

But how to change that ? I am not clear about that.

is it systemctl start docker.service ? I tried this, it could not work.

**Comment by HackToday** [comment]
I have solved it by myself, it need manual change systemed files, and also need restart host, or else that change can not work correctly, maybe fedora bug.

**Comment by bgrant0607** [comment]
There is a CentOS getting started guide:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/centos/centos_manual_config.md

Is that not accurate?

**Comment by roberthbailey** [comment]
It sounds like this has been resolved. Please reopen if you are still encountering this issue.

**Comment by lostsnow** [comment]
what about centos6.x?

**Comment by DarkSkull91** [comment]
it doesn't seems that I can install on CentOS 6.5
