### ISSUE TITLE
GetReference shouldn't hardcode api prefix

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#1490]
#1475 assumes there is a fixed path prefixes in the apiserver and client, so that it can retrieve version like this:

```
var versionFromSelfLink = regexp.MustCompile("/api/([^/]*)/")
...
version := versionFromSelfLink.FindStringSubmatch(jsonBase.SelfLink())
```

But above assumption is not valid today, we should do something to enforce such assumption, or find another way to retrieve version. 

@smarterclayton

**Comment by bgrant0607** [comment]
I think this is prerequisite for #2098.

**Comment by nikhiljindal** [comment]
I dont see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/ref.go using that regex anymore. It is extracting the version from ObjectReference.
API prefix is not harcoded anywhere in that function or file.
