### ISSUE TITLE
Support attach

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1521]
Forked from #1503.

We should decide whether we will support [Docker attach to stdin and stdout](https://docs.docker.com/reference/api/docker_remote_api_v1.13/#attach-to-a-container). It would be convenient for interactive containers and, more importantly, short-running, run-once data-in/data-out containers, such as for configuration generators, workflow steps, cron jobs, etc.

Support would likely be similar to that required to support run in container (aka docker exec) and/or ssh (#1513).

/cc @vishh

**Comment by bgrant0607** [comment]
Port forwarding has been implemented.

**Comment by davidopp** [comment]
Blog post here:
http://blog.kubernetes.io/2015/03/weekly-kubernetes-community-hangout.html
