### ISSUE TITLE
Errors if more pods defined than minions

### ISSUE THREAD

**Issue by justinlindh** [GoogleCloudPlatform/kubernetes#1554]
I'm using gce provider, unsure of how this would affect others.

The apiservice rapidly throws errors, and I believe may be making a massive number of Google Compute Engine API requests, If more pods exist than minions to serve them.

Steps to reproduce:
1. kube-up.sh with a small number of workers defined in config.
2. tail the apiserver.log file on kubernetes-master (/var/log/apiservice.log)
3. Assign enough pods (using individual pods or replicationController of large enough size) so that the number of pods exceeds the number of minions
4. Check the logs for apiserver, and notice that it'll begin to flood with something like this:

E1002 23:13:53.185460 09112 gce.go:206] Failed to retrieve TargetInstance resource for instance:
E1002 23:13:53.185482 09112 rest.go:225] Error getting instance IP: &errors.errorString{s:"json: invalid use of ,string struct tag, trying to unmarshal \"projects/wf-lindh/zones/us-central1-a/instances\" into uint64"}

I believe the severity of the issue increases linearly for PODS_DEFINED - MINIONS_AVAILABLE. This issue could be considered critical if it is, in fact, abusing the GCE API. I believe this was the culprit in making me hit over 3 million API attempts in a 18 hour period.

**Comment by bgrant0607** [comment]
See also #4583

**Comment by thockin** [comment]
This seems resolved - can not repro
