### ISSUE TITLE
Docs should use relative links

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1571]
rather than https://github...kubernetes/...

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by bgrant0607** [comment]
Now more important since we're forking the docs for each release.
cc @nikhiljindal

**Comment by thockin** [comment]
I'm changing it all to minimal ../../foo and ./bar links, but as I finsih
it, I wonder if it would be easier to maintain if everything did ".." to
the root.   So ./foo might become ../../../docs/bar/foo - it's longer but
easier to grep for...  Thoughts?

**Comment by bgrant0607** [comment]
Backtracking to root: I can see the value, but think we have bigger fish to fry.

**Comment by bgrant0607** [comment]
cc @lavalamp re. link checker

**Comment by lavalamp** [comment]
It's easy to make the link script do whatever we want. I have it NOT
backtracking to root right now (or will when today's thockalamp changes
merge), since it was inconsistent before and that was most straightforward.
But I can put it the other way, too.
