### ISSUE TITLE
Add "go build" to travis CI

### ISSUE THREAD

**Issue by ghodss** [GoogleCloudPlatform/kubernetes#1581]
Several times over the past few months I've run into HEAD throwing compilation errors when doing `go build ./...`, which may not prevent proper functioning of kubernetes but makes some commands during development like `go get ./...` very hard to do. It would be great if we could add `go build ./...` to Travis CI to prevent this from happening.

**Comment by ghodss** [comment]
This should be re-opened. Travis still doesn't build *all* packages with `go build ./...` or `go install ./...` so HEAD still breaks. See https://github.com/GoogleCloudPlatform/kubernetes/pull/1641#issuecomment-58268281 for rationale.

**Comment by ghodss** [comment]
@lavalamp Do you mind reopening for now?

**Comment by lavalamp** [comment]
Sure. @goltermann the fix that was merged was for the specific problem, but this bug is about the general class of problems.
