### ISSUE TITLE
Examples should demonstrate best practices

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1603]
redis-master doesn't demonstrate best practices, with respect to Kubernetes and Redis.

Kubernetes: redis-master is a naked pod with no replication controller. If the node dies, the service is toast.

Redis: IIUC, redis-master doesn't take advantage of Redis's HA features, such as [sentinel](http://redis.io/topics/sentinel)

Persistence is more questionable, but that's another feature we could incorporate into the example, esp. once we support durable data.

We should also remove hostPort from examples

**Comment by jlowdermilk** [comment]
Should also use more useful labeling on resources to make cleanup easier and to see all the pieces of a service with one query. e.g. all resources that are part of the redis cluster get the label `app=redis` and all objects that are part of the frontend are labeled `app=frontend`.

**Comment by bgrant0607** [comment]
I'd also like to make one-command creation work:
```
kubectl create -f examples/guestbook
```

And we should nuke the host port.

**Comment by bgrant0607** [comment]
cc @rsokolowski

**Comment by bgrant0607** [comment]
@rsokolowski Sorry. See #4133.

**Comment by jlowdermilk** [comment]
I think #4133 only partially addresses this. There's a bit more cleanup, e.g. redis-slave controller is still using hostport, the frontend service should use an external load balancer, etc.

**Comment by ddysher** [comment]
@jlowdermilk Maybe update the title?

**Comment by jlowdermilk** [comment]
Didn't mean to load more work on you @ddysher :). Feel free to unassign yourself, I just didn't want this to get closed until the other items mentioned in comments are cleaned up.

**Comment by bgrant0607** [comment]
#1487 covered removing hostport, though I'm fine if we merge that into this issue.

**Comment by bgrant0607** [comment]
Ref #3671 to convert to v1beta3

**Comment by bgrant0607** [comment]
cc @rsokolowski

**Comment by rsokolowski** [comment]
I think issue is mainly addressed: guestbook uses RC for redis-master, frontend has service associated, hostPorts are removed, there is paragraph about Redis HA, but is not part of the example.
