### ISSUE TITLE
Proposal: scaling interface

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1629]
Auto-scaling has been discussed in many issues/PRs: #1007, #1178, #170, ...

This is about how an auto-scaler should be layered on the API.

In the case of auto-scaling, the currently desired number of replicas won't be statically configured by the user, and should not be among the fields diff'ed by the configuration system. #1201 addresses that problem.

It should be possible to auto-scale applications with multiple release tracks, and it should be possible to auto-scale and perform a rolling update (#1353) simultaneously. If the auto-scaler were tied to a specific replication controller, then it would at least need a label selector (or possibly reference to a service object, but I prefer direct use of label selectors) to identify the whole serving set in order to assess current capacity. 

Additionally, if the approach of creating a new replication controller were used to deploy new images, the auto-scaler would need to be updated to resize the new replication controller.

And, if we introduced higher-level API objects to manage multiple underlying objects or other new controller types (e.g., JobController - #1624), the auto-scaler would need to support all those API types.

Instead of declaratively manipulating all these object types directly, the auto-scaler should target a narrower API: an imperative resize "verb" (i.e., POST to a URL). Any API object capable of being auto-scaled (e.g., replicationController) could support that verb. The verb would update the desired replica count for that object.  With this approach, resizing could also be supported generically by the CLI (lots of discussion in #1325), would simplify client code more generally, and could simplify authorization logic.

Yes, verbs of all flavors are discouraged by REST purists, but this approach avoids per-object-type verb proliferation and facilitates metaprogramming, addressing their main concrete concerns. The alternative would be a generic declarative subobject containing (essentially) just the size. That seems like a lot of metadata and object-lifecycle overhead for little gain.

Details to be worked out:
* Whether everyone is ok with URL-encoded API verbs
* URL format for API verbs generally. Simple strawman proposal: collection or object URL followed by /.verb -- period prefix to avoid collisions with sub-collections/sub-objects (only unescaped punctuation across all RFCs are `-`, `_`, and `.`).
* Whether we support absolute and/or relative resizing -- either could work in most cases, though relative can be useful for pure reactive behavior
* Preconditions for resize (e.g., current size), which would be optional (though necessary for idempotence in the relative case)
* JSON vs. URL parameters for operation parameters. I like URL parameters, since they facilitate simple web hooks.

**Comment by davidopp** [comment]
Could someone explain the resize verb concept a little more? What object is the target? From some of the examples above it seemed the target was a pod (for example), but I don't understand what it means to horizontally resize a pod (wouldn't you just create a copy of it, or delete it)? Or maybe the target is some kind of meata-object?

**Comment by davidopp** [comment]
Sorry for being dense, I just figured out that the replication controller is the object with a resize verb. That makes sense.

**Comment by smarterclayton** [comment]
#5054 contains some fixes required to allow sub resources like /resize to work, as well as an example with /binding.  I made "Binding" generic to type, (it's a name, target, and an object reference to be bound to).

**Comment by bgrant0607** [comment]
Note that the current proposal is `/size`. See https://github.com/GoogleCloudPlatform/kubernetes/issues/2726#issuecomment-73177753

**Comment by bgrant0607** [comment]
After further thought, I'm thinking we should call this `/scale`, and rename `kubectl resize` to `kubectl scale`, in order to match standard terminology (auto-scaling), to distinguish from cpu/memory resizing/auto-sizing, and to be more similar to other systems (e.g., [CF](http://docs.cloudfoundry.org/devguide/deploy-apps/cf-scale.html)).

**Comment by bgrant0607** [comment]
In progress: #12217

**Comment by stormltf** [comment]
when atuoscaling can be done? do you need our team help to do this?

**Comment by fgrzadkowski** [comment]
Several issues here:
* /scale subresource is already done. See #12217
* Horizontal pod autoscaling is tracked in #12087
* Vertical pod autoscaling is tracked in #10782; currently we work on #12149 which is a first step
* Cluster autoscaling (adding/removing nodes) is tracked in #11748 (almost done; just wrapping up last things like documentation)

I think we should close this particular issue as it seems it's redundant.
