### ISSUE TITLE
Standardize kubelet working dir

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#1691]
As mentioned in #1644 and documented in #1690, the kubelet is started with a current working dir that is inconsistent across platforms, and non-standard in some cases.

On GCE the current working dir is `/`.  On CoreOS, I'm told it is `CWD=/home/core`.

This affects at least the location of the dockercfg, and may affect other things we haven't though of yet (where corefiles go, etc).

The root dir is almost certainly not the right place for various inputs and outputs of kubelet.  Is `/root` the right place?  If we change it, we should make a small announcement since it will affect a few users who are depending on the `.dockercfg` location.

**Comment by thockin** [comment]
Is this still an issue?  I thought it was fixed...

**Comment by erictune** [comment]
We look for dockercfg in several places.  Beyond that, I think that we
don't care what the kubelet working dir is.  Close it?
