### ISSUE TITLE
What are Volume builder root directory parameter requirements

### ISSUE THREAD

**Issue by skardach** [GoogleCloudPlatform/kubernetes#1726]
I've been hacking on Openshift and I've had some "issues" with ```CreateVolumeBuilder()``` in ```pkg/volume/volume.go``` and its parameter ```rootDir``` ([details here](https://github.com/openshift/origin/pull/203)). It doesn't say it in the comment for the function or anywhere in the package (or I've missed something) about whether it should be an absolute or relative path. If I however try to create the VolumeBuilder and then bind the volume I get an error saying that this path needs to be absolute (which is kind of too late, since the builder is already setup). So my question is what should be the requirement in terms of the API: ```rootDir``` needs to be absolute or ```CreateVolumeBuilder()``` should make it absolute?

**Comment by vishh** [comment]
It looks like this issue has been fixed on HEAD. Kindly reopen if that's not the case.
