### ISSUE TITLE
Document which in-place updates work and which ones don't

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1728]
It's non-obvious. See #1712.

**Comment by yujuhong** [comment]
This is fixed by #5073

**Comment by bgrant0607** [comment]
@yujuhong @vishh v1beta3 didn't get the "cannot be updated" annotations. Could one of you

**Comment by yujuhong** [comment]
I will do that.

**Comment by vishh** [comment]
Thanks @yujuhong for picking that up!
