### ISSUE TITLE
Support multiple CLI configuration profiles

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1755]
I should be able to have multiple clusters that I am auth'ed into that I can flip with a symbolic name.   Having a single auth for GCE is really painful when flipping between real and e2e clusters.  Having to set KUBERNETES_PROVIDER sometimes and KUBERNETES_MASTER other is somethign I easily forget.

Something like (obviously half-baked):

kubectl kube add timsgce https://1.2.3.4
kubectl kube add timse2e https://5.6.7.8
kubectl kube add vagrant

kubectl --kube=timsgce get pods
kubectl --kube=vagrant get pods

kubectl kube set timse2e
kubectl get pods

@ghodss for possible kubectl thinking.

**Comment by bgrant0607** [comment]
Done
