### ISSUE TITLE
Check other dirs for .dockercfg

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1767]
As per #1717

We should look for the .dockercfg in three places: ./.dockercfg, ~/.dockercfg, and $rootDir/.dockercfg

**Comment by thockin** [comment]
What ever happened with this idea?

**Comment by bcwaldon** [comment]
@thockin It never got high enough on my weekend TODO list :( I can keep telling myself that I need to do it, or we can find someone who has a bit more time than me.

**Comment by mikedanese** [comment]
I can probably get to this today.

**Comment by brendandburns** [comment]
Cool, thank you!
