### ISSUE TITLE
Vagrant e2e test should behave more like GCE e2e

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1780]
Ensure that VMs are updated prior to running and tear them down at the end.

**Comment by ixdy** [comment]
Is this still an issue?
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
I can make sure they are torn down.  Will get to this this week.  Assign to me.

**Comment by derekwaynecarr** [comment]
I am closing this issue now.

The e2e scripts call ```test-teardown``` which for vagrant calls ```kube-down``` which ultimately does a ```vagrant destroy -f```
