### ISSUE TITLE
Example: task queue

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#1788]
We should cook up an example that shows how a pool of workers could pull from a shared task queue, such as [Celery](http://www.celeryproject.org/) , or even raw [RabbitMQ](https://www.rabbitmq.com/tutorials/tutorial-two-python.html).

**Comment by kbeecher** [comment]
This example was merged. Can the issue now be closed?

**Comment by bgrant0607** [comment]
Yep. Thanks.
