### ISSUE TITLE
Replication controller should cache API objects

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#1795]
It should use the same technique used in the scheduler, leveraging the objects in client/cache.

Specifically, it should keep a cache/FIFO of replication controllers, and a cache of pods, both to reduce load on apiserver and to improve response time & code clarity.

For bonus points, could use a FIFO of pod changes to track replica counts instantly instead of with the delay from periodic syncing.

**Comment by bgrant0607** [comment]
@bprashanth

**Comment by bprashanth** [comment]
I can hack away at this as I touch related code, I'm guessing it isn't for 1.0 since it's a p3

**Comment by lavalamp** [comment]
@bprashanth did this.
