### ISSUE TITLE
Multi-Port Servers in Services v2

### ISSUE THREAD

**Issue by enisoc** [GoogleCloudPlatform/kubernetes#1802]
I'm running ZooKeeper, which requires every server to know about every other server at startup (this will be fixed in 3.5.0, but that's still in alpha). In addition, each server needs to expose two different ports: a leader port and an election port. I've been using a model in which every ZooKeeper instance gets two services -- one for each port. Each such service then has only one pod matching its selector.

For example:
```
pods/zk1
pods/zk2
...
services/zk1-leader
services/zk1-election
services/zk2-leader
services/zk2-election
...
```

With Services v2, I won't be able to do that, because if I create two services for one instance, they will have different IPs. There's no way to tell ZooKeeper to use a different IP to connect to the leader port vs. the election port of a given server.

Since a service in v2 will have its own IP address, can we maybe have the ability to define multiple ports on a single service? Or is there a better way to handle this kind of use case?

**Comment by Pindar** [comment]
+1

**Comment by bgrant0607** [comment]
Discussion is happening on #2585. We'd appreciate feedback from users with multi-port services, especially if you plan to query the Endpoints API to discover targets/peers of the multi-port service.

**Comment by thockin** [comment]
Multi-port services is in!  Happy zookeeping.

**Comment by phemmer** [comment]
Looks like this was implemented in #5939 & #6182 for anyone interested.

**Comment by jk-shah** [comment]
Great!! We just ran into this.. Which version of Kubernetes has this checkin? Any easy way to figure that out?

**Comment by mikedanese** [comment]
This is in the 0.15.0 release.

**Comment by jk-shah** [comment]
Thanks
