### ISSUE TITLE
New pod can be observed as "terminated"

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1820]
I created a new pod, and immediately did a 'list pods' and it showed as terminated.  Very confusing for users.

redis-master-pod                       gurpartap/redis             kubernetes-minion-3.c.thockin-dev.internal/146.148.49.171    name=redis,role=master                                                Terminated

**Comment by bgrant0607** [comment]
I doubt this exact symptom still occurs, since we introduced unknown. #1366 is implemented. #2726 is the real solution. Closing as dupe.
