### ISSUE TITLE
apiserver should not respect user-assigned UIDs

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1821]
I think?

**Comment by bgrant0607** [comment]
@smarterclayton What is the current status of this? It looks like FillObjectMetaSystemFields sets uid upon creation, but we don't issue an error if the user had set the value and I don't think we prevent the user from updating it.

**Comment by smarterclayton** [comment]
Updating it is fixed in my generate name pull - see ValidateObjectMetaUpdate.  I was torn on the create case - since it's not settable by a user, I don't know if there's a downside to ignoring it (to allow GET / POST).  In that pull everything should be correctly ignored / reset.

**Comment by bgrant0607** [comment]
I'm fine with that. I think we can consider this closed, this, once your PR is merged.

**Comment by bgrant0607** [comment]
Merged.
https://github.com/GoogleCloudPlatform/kubernetes/blob/3f28badae31b935aae72d33d63220923e2cac162/pkg/api/validation/validation.go#L158
