### ISSUE TITLE
Bad pod commandline causes feedback loop

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1823]
I started a replication controller with 1 replica.  The commandline was bad, so the container exited immediately.

Kubelet started the net container successfully, then started the app container, which died.

'kubecfg list pods' showed the pod as terminated, so replication controller started a new one.

Loop forever.  Each minion had 100+ "pause" containers, and 'list pods' showed hundreds of terminated pods.

a) Why did the pod show up as terminated?  If it was being restarted by kubelet, it should have show up as running...

b) If it *was* terminated, why did nobody  (e.g. replication controller) actually remove it?

**Comment by dchen1107** [comment]
The issue should be fixed a while back:

a) Pod should show up as RUNNING, not TERMINATED anymore
b) Pod in crashing loop should be detected and removed by controller, which was filed as a separate issue. I am closing this one.
