### ISSUE TITLE
External load balancer creation is buggy.

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#1836]
1. If you look at the code that creates it, you can see that there are paths involving updates which both fail to create it when necessary and fail to destroy it when necessary.

2. It spans all minions instead of only the pods in the service.

My proposed solution is to extract this code to a reconciliation loop, much like our replication manager. It should basically watch for service changes, monitor the GCE load balancers, and make changes accordingly.

**Comment by thockin** [comment]
@jszczepkowski is this issue resolved now?

**Comment by jszczepkowski** [comment]
Yes, issues with update (1) are solved by #4484.
