### ISSUE TITLE
Docker 1.3 deprecates the -r flag

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1838]
-r is deprecated in favor of per-container restart policies, which we do not use (yet?).  We need a plan to stop setting the -r flag, which will break backwards compat with 1.2

**Comment by thockin** [comment]
How many back-versions of docker do we want to be compatible with?  Current + 2 sounds reasonable to me.

**Comment by thockin** [comment]
Now that docker 1.3 is our baseline, we should remove this from our configs.

**Comment by bgrant0607** [comment]
Is this still an issue?

**Comment by brendandburns** [comment]
Nope.

**Comment by thockin** [comment]
We still have -r in our salt template for docker.  Fix is in flight.
