### ISSUE TITLE
Need better log or handling if newIPAllocator fails

### ISSUE THREAD

**Issue by deads2k** [GoogleCloudPlatform/kubernetes#1860]
service.newIPAllocator can return null.  If it does, then calls to service.REST.Create result in panics in the log due to nil pointer dereferences.  I would change it, but there's no clear way to return an error through the layers back into master.go.  Here is the stack:

I1017 13:05:08.641713 17383 handlers.go:37] APIServer panic'd on POST /api/v1beta1/services?labels=: runtime error: invalid memory address or nil pointer dereference
/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/handlers.go:37 (0x6d6317)
	func.002: glog.Infof("APIServer panic'd on %v %v: %v\n%s\n", req.Method, req.RequestURI, x, debug.Stack())
/usr/local/go/src/pkg/runtime/panic.c:248 (0x40f48d)
/usr/local/go/src/pkg/runtime/panic.c:552 (0x40ff3d)
/usr/local/go/src/pkg/runtime/os_linux.c:237 (0x40eb2e)
/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service/ip_allocator.go:71 (0x6edd9c)
	(*ipAllocator).AllocateNext: ipa.lock.Lock()
/home/deads/workspaces/openshift3/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service/rest.go:93 (0x6eede5)
	(*REST).Create: if ip, err := rs.portalMgr.AllocateNext(); err != nil {

**Comment by smarterclayton** [comment]
Fixing this by changing ip allocation for services
