### ISSUE TITLE
Provide easy debug network access to services

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#1863]
Right now when you start a service it is available on the service IP port from within the kubernetes cluster.  But hitting that service from the outside is really hard.

@lavalamp introduced an HTTP proxy through the master (`api/v1beta1/proxy/services/servicename`) but there will be times when a more direct access pattern is needed.

One solution is to claim a host port and look up what minion a pod landed on. That won't be stable if the minion gets rescheduled.

Another idea is to introduce an idea of a 'cluster debug port' and run a TCP proxy on perhaps the master that'll do TCP (and UDP?) forwarding to the service for that port.

**Comment by smarterclayton** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/5763 is setting the stage for making this easily secured via the bastion.
