### ISSUE TITLE
Modify usage of api.NewContext to api.AcrossNamespacesContext

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#1872]
It is confusing to code readers when a context is used to read across all namespaces versus in a particular namespace.  As a result, modify current uses of api.NewContext where a read happens across namespaces to have a method specific to that use case.

@lavalamp

**Comment by davidopp** [comment]
@derekwaynecarr Can we close this?

**Comment by derekwaynecarr** [comment]
I may come back and do more clean-up in this area, but for now, I will close the issue.
