### ISSUE TITLE
Document creating/using release tags and branches

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#1883]
***STOP: If you are reading this because it's been the canonical place to find release instructions for months, see the draft of [releasing.md](https://github.com/zmerlynn/kubernetes/blob/i1883/docs/devel/releasing.md) from #10709***

It has all been very error prone as we've done the 0.4 release branch.  Getting some clear instructions that minimize the amount of 'direct push' would be great.

Here are the steps that I can reconstruct (assuming that upstream is the main git repo)
Make sure you have a valid local clone that was created with "umask 022" so that "make release" will have world-readable files and directories:
 * fork GoogleCloudPlatform/kubernetes to e.g. $GITHUBUSER/kubernetes
 * umask 022
 * git clone https://github.com/$GITHUBUSER/kubernetes.git
 * cd kubernetes
 * git remote add upstream https://github.com/GoogleCloudPlatform/kubernetes.git

To build a new major/minor release (e.g. v0.x.0):
  * Run `./build/mark-new-version.sh v0.x` to mark the new release.  This will do the following:
    * Create a commit that sets `pkg/version/base.go` to the release version.
    * Create an annotated tag for that version
    * Create a commit that sets `pkg/version/base.go` to the post-release version (v0.x-dev)
  * Fetch that to a local client and check out at the actual release commit (`git checkout v0.x`)
  * Push this to the upstream repo (`git push https://github.com/GoogleCloudPlatform/kubernetes tags/v0.x`)  If you have a bogus value for `pushurl` in your git config, you'll have to comment it out while doing this.
  * Run e2e tests: `go run hack/e2e.go -v -build -up -test -down`; make sure they pass.
  * Build official binaries: `make clean ; git clean -xdf; make release` (Note: `git clean -xdf` cleans out your repo completely, including any stray backup files or whatnot you may have laying around. Use with some caution.)
  * Upload the binaries to Google Storage: `./build/push-official-release.sh v0.x`
  * Go to https://github.com/GoogleCloudPlatform/kubernetes/releases:
    * Create a new release based on the annotated tag
    * Summarize the changes from the previous release. The [release-notes tool](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/contrib/release-notes) will give you a list of changes as a starting point.
    * Upload `kubernetes.tar.gz`.  Fill in the md5 and sha1 for that file.

To cherrypick and cut a release branch (e.g. v0.x.1):
  * Navigate to the tag (`v0.x`) in the github UI. 
  * Create a branch.  Do this by hitting clicking the branch drop down and entering the new name in the box there where it says "Find or create a branch...".  Name this `release-0.x` and base it on tag `v0.x`.
  * On your local git clone:
    * `git fetch upstream`
    * `git checkout upstream/release-0.x`
    * `git checkout -b release-0.x`
    * `git push --set-upstream origin release-0.x`
  * Now for each commit you want to cherry pick into the release
    * `git cherry-pick -x <sha1>`
  * Now to cut a point release: `./build/mark-new-version.sh v0.x.y`
  * Push this all up to your personal fork:
    * `git push origin release-0.x`
  * Create a PR to merge this into the main release branch (e.g. navigate to your fork on github, view branch release-0.x, click Create Pull Request).  Make sure both the source and target are the release branch and not master.  Get this merged.
  * Push the tag to upstream as above.
  * Build and push a new release as above.

@filbranden Does this sound right?

**Comment by roberthbailey** [comment]
Chatting with @zmerlynn today he volunteered to take this over and finish it off. Look forward to an updated https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/releasing.md soon. :)

**Comment by filbranden** [comment]
Feel free to cc me in any code reviews or ask me questions about it since I wrote the first version of that document and the ugly diagram that goes with it :-)

Cheers,
Filipe

**Comment by zmerlynn** [comment]
Will do!

**Comment by alex-mohr** [comment]
Script to generate release notes: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/contrib/release-notes

I'll merge that into instructions after @zmerlynn drops edit lock
