### ISSUE TITLE
Distribute auth tokens to pods

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#1907]
Before allowing pods to make changes to the cluster state, we need to check their identity and verify that they're permitted to make changes.

An idea for checking identity: suppose we generate a token when a BoundPod is created. Kubelet passes this token into the pod via an ENV var. apiserver can then look up this token to verify identity.

Clearly there's some security implications; if the wrong actor is able to read the BoundPods endpoint, they could impersonate another pod.

**Comment by bgrant0607** [comment]
What's left to do here, now that Secret is in?

**Comment by smarterclayton** [comment]
I think with Jordan's latest change to allow keys and certs to be embedded in KUBECONFIG this is possible.  Further work should be tracked as part of automatic enablement via service accounts and token generation.

**Comment by erictune** [comment]
Current state:
  - we have a secrets resource.
  - we have a way to create "service accounts" at cluster startup, which is in use.
  - upcoming PRs by @liggitt will add a "service account" field to a pod and an automated way to create users, tokens, and to attach those to a pod's volumes based on that field.

Docs are a bit stale.
This is the closest thing we have.  
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/service_accounts.md
https://github.com/GoogleCloudPlatform/kubernetes/4126

Closing this issue, as I think it is no longer useful.
