### ISSUE TITLE
Decode should return a typed error for missing version and Kind so clients can display a better error

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#1908]
`modify.go` is checking an error like 

    err.Error() == "No type '' for version ''"

this should really be `runtime.IsMissingKind(err)` / `runtime.IsMissingVersion(err)` or some variant

**Comment by brendandburns** [comment]
@smarterclayton is this a little obsolete?  I can't see ```modify.go``` anywhere.

**Comment by smarterclayton** [comment]
I believe this was fixed a few months back.
