### ISSUE TITLE
Make object name validation consistent

### ISSUE THREAD

**Issue by vnugent** [GoogleCloudPlatform/kubernetes#1910]
I have client code that generates random IDs for pods and services.  I can created pods with ID longer than 26 characters; service id on the other hand can't be more than 24?  Please document these requirements.  Thanks.

**Comment by smarterclayton** [comment]
Starting to fix this in #3789

**Comment by bgrant0607** [comment]
Is there anything left to do here?

**Comment by smarterclayton** [comment]
No, other than document whether resources done in the Kubernetes style, but which represent more complex underlying types, can vary their name rules to fit their use cases.  I got Tim to say he didn't object but hadn't made a proposed change to api-conventions yet to argue about.  This can be closed.
