### ISSUE TITLE
Broken minion strategy

### ISSUE THREAD

**Issue by sevki** [GoogleCloudPlatform/kubernetes#1923]
So I have this minion that is not working properly, this is what the average minion looks like
![google_developers_console](https://cloud.githubusercontent.com/assets/429977/4713068/812eee08-58d9-11e4-8df4-492f31a6942e.png)
and this is what the broken one looks like, during the peak at the graph all its pods were "waiting"
![google_developers_console](https://cloud.githubusercontent.com/assets/429977/4713080/e2ad4c9c-58d9-11e4-8622-1762b7b65c78.png)

I was looking trough the documentation and I couldn't find anything on this, but when something like this happens, a misconfigured machine or maybe it's haunted, what should one do?

- Take that machine out of the minion pool?
- Redeploy that machine?
- Read the logs and try to fix the problem by sshing in to that one machine?
- Clone a working machine to replace that?

**Comment by lavalamp** [comment]
I know we have made some improvements re: detecting when docker doesn't start up properly. I'm going to close this due to age and lack of a clear action item-- please reopen or open new issues if you don't think that's OK.
