### ISSUE TITLE
Change UUID to docker-style randomness

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1944]
After discussing with docker folks, maybe it makes sense to standardize on docker-style IDs, rather than UUIDs?  Somewhat easier on the eyes, especially when the short-form is used in display.

**Comment by thockin** [comment]
Is there still value in considering this?  We treat UUIDs as opaque all over, so changing to something else is still viable and not even very hard.  Is it useful?

**Comment by smarterclayton** [comment]
I don't see any pressing need.  I don't know that we need more bits of
randomness, and until we have retrieve by uid most of the details are
fungible.

On Jul 9, 2015, at 1:36 AM, Tim Hockin <notifications@github.com> wrote:

Is there still value in considering this? We treat UUIDs as opaque all
over, so changing to something else is still viable and not even very hard.
Is it useful?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/1944#issuecomment-119824969>
.

**Comment by thockin** [comment]
The only real reason I can see for this at all would be to use shortened prefixes, which is purely a human thing, and humans should mostly use name.  I'm going to close this
