### ISSUE TITLE
All REST code should return api/errors types ONLY

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#1990]
e.g. REST.Update should never return an arbitrary error value.  Maybe we should change the return code to something stricter than generic error.

**Comment by bgrant0607** [comment]
FYI: #4347 is for remaining cases where the API doesn't return JSON/Status errors.

**Comment by brendandburns** [comment]
Re-opening this until we fix #4347

**Comment by bgrant0607** [comment]
I think etcd errors require more abstraction, also:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/errors/etcd/etcd.go#L37

**Comment by derekwaynecarr** [comment]
There are some admission control plugins that did not always follow that practice which I will resolve as part of #6830

**Comment by bgrant0607** [comment]
@nikhiljindal Are there any known instances of this remaining?

**Comment by nikhiljindal** [comment]
None that I know of.
