### ISSUE TITLE
allow for a display label on minions

### ISSUE THREAD

**Issue by kapilt** [GoogleCloudPlatform/kubernetes#1994]
currently minions are displayed by id, this value is currently required to be routable even though minions have a separate hostIP attribute which should nominally perform that role. either allowing id to be a display label and using hostIP for access, or separately having a displayName/label on minions would allow users to tag minion instances by a consistent / human interpretable naming scheme.

**Comment by bgrant0607** [comment]
@ddysher Is this done?

**Comment by ddysher** [comment]
Done.

#2547 and a few others.
