### ISSUE TITLE
Secret distribution in docker/k8s

### ISSUE THREAD

**Issue by stp-ip** [GoogleCloudPlatform/kubernetes#2030]
One missing piece of both guidelines and k8s is a way to distribute secrets.

There are multiple ways to go about it and I want to start the discussion not only to suggest a guideline for secret distribution, but to make it easier to be integrated into k8s. We could start by discussion the various ways and including them for usage in the documentation so that these "best practices" are available and furthermore work great with k8s. As a second step we should try to find one common way of doing it, integrate  it into k8s to make it as seamless as possible.  
There are two issues with secret distribution I find discussable. Sure there are many more as secret distribution is one of the huge problems. Not think about the perfect solution yet, but a start to make it easier for people to start using k8s or use it as reference for their docker installations.

The first issue concerns PWs and credentials for services. For example database PWs, AWS credentials etc.. 

The second kind of problems arise with key/file distribution. The issues come with multiple secret files, which need to be distributed. Mainly keys for de/encryption, ssl keys, vpn/ssh keys etc..

#### Pros:
  * Easy to use and implement

#### Cons:
  * Leakage of ENVs in various places -> seed secret needs to be shared anyway
  * Files/keys can't be distributed (correct me, if there is a way)

#### Pros:
  * Central control of credentials and secret files
  * Could be used with ssh auth against LDAP for hosts
  * Most environments run LDAP already
  * Finegrained control of secrets -> easily create one account per service/app

#### Cons:
  * Seed secret needed (username + pw for LDAP)
  * Relies on a central ldap service to retrieve runtime files (SPOF)
  * Custom logic to retrieve secrets from LDAP
  * Reliance on LDAP in all environments
  * No versioning (no rollback etc.)

#### Pros:
  * Versioned
  * Easy to distribute -> use docker registry
  * Easy to link to other containers

#### Cons:
  * Leakage of secrets -> worst case to public docker registry
  * Security need for intermediary services between build and runtime

#### Pros:
  * Versioned
  * Easy to distribute -> use docker registry
  * Easy to link to other containers
  * Throw away mentality due to encryption -> "unreadable" without seed secret
  * Can be switched with unencrypted containers in test/dev environments
  * Could be build in a separate "closed down" build environment

#### Cons:
  * Needs seed secret
  * Adds a dependency on decryption and seed secret distribution

#### Pros:
  * Distributed -> no SPOF
  * etcd already running with k8s

#### Cons:
  * No ACL yet -> will change (layer could be added from k8s for now)
  * Access to etcd of k8s could be a security risk -> separate etcd service?
  * No versioning
  * Issues with bigger files in a key/value store

#### Pros:
  * Distributed -> no SPOF
  * Seed secret needed to have access to files/secrets stored
  * etcd already running with k8s

#### Cons:
  * No ACL yet -> will change (layer could be added from k8s for now)
  * Access to etcd of k8s could be a security risk -> separate etcd service?
  * No versioning
  * Issues with bigger files in a key/value store

My favourite method would be to use encrypted Data Volume Containers. (Option 3b) This fits best with the modularity and reproducability of docker and makes it easy to switch out secret distribution later on. For example encrypted Volumes could be based on Ceph volumes instead of docker containers
I'm looking forward for your input.

[LDAP]: https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol
[Data Volume Container]: https://docs.docker.com/userguide/dockervolumes/
[etcd]: https://etcd.io
[consul]: https://www.consul.io
[crypt]: https://github.com/xordataexchange/crypt

**Comment by stp-ip** [comment]
Sorry for the long wait on an answer, but I got stuck with other things.

I agree that using the filesystem as an API is not perfect for dynamic stuff, but that is not the main advantage. In my opinion with containers and in general with versioned infrastructure (even versioning data and config) you do not want dynamic content appearing or disappearing without some sort of checkpoint ("docker/git commit" kind of thing). These non dynamic use cases are the focus here. Fully dynamic configuration is only one edgecase I was thinking about.

The main point I wanted to make was that for general supporting data/config, a common interface is essential. Mounting your (persistent) storage to /con/*{data,log,configuration} on each container is easier to work with. As different locations can be abstracted away by the application/container builder, which most likely knows the actual implementations better and therefore has the knowledge to abstract that away. Within a one process per container system one data, configuration location is possible and one of the ways to simplify deployment in my opinion. Additionally it abstracts away orchestration details (mount points) from the actual storage location used by an application/container.

Sure conventions are only ontop, but standards should not be forced upon, but agreed on. I see value in the discussion more than I see in my specific implementation.
That being said. I am using my proposal at docker/docker#9277 on various images and it is used by others too. Quite some simplifications could be seen during orchestration and deploy.

The advantage to use the filesystem is that applications can work with them now. It is easier to let them use what they know for now and therefore provide a filesystem implementation. Which could be backed by an underlying API. As seen in this proposal a lot of different tools came up and no standard API could be agreed upon. On the other hand most of these tools provide a way to export more or less the same config files. Or at least a SideContainer could provide this export, without adding custom code into the application container. Separating concerns is one thing I value in the container approach.

One thing considered was using tmp filesystems to minimize the attack surface for secrets laying around in the system.

LDAP was just one suggested solution and in my and your view it is not worth it. Additionally file distribution is not optimal and seeding LDAP credentials needs another solution again. 

It is not about choosing existing tools over new implementations. It is more about understanding existing tools and enable a more generalized solution for a broad usage area. The proposed tools are partly used in existing products/projects, that is one reason they were included. Additionally I am not a fan of proposing a new standard, which just ends up increasing the fragmentation in the ecosystem. I wanted to propose a standard, which enables a wide range of tools and applications to work with and in the same breath simplify orchestration and usage of containers. Moving the application details to the image builders and simplify the orchestration details.

I have to disagree, that using LDAP/consul or my filesystem proposal at docker/docker#9277 makes it more difficult to protect information. Right now most container users either use ENVs, which show up in their bash history, the process and are available to linked containers etc., or embed their credentials inside their container, which easily gets pushed to a public registry or is accessible in their private registry without any further ACL.
Using LDAP/consul or a specific solution shows at least some kind of thinking process into secret protection. Additionally I cannot agree that generic tools are more insecure by default. It depends on the usage. Leaking secrets is one important consideration and beginning to let users split config and secrets is the first step and will enable to move secrets to more secure tooling later on.

When someone can make the application read "wrong" files, one can also assume that they could inject code, rewrite API endpoints and use "wrong" ENVs. Making the application do malicious things is not a problem of filesystem interface usage, but a general issue to be considered.

One idea here was to make it possible to move from beginner cases to advanced cases easily as the backend implementation can be switched easily, but the interface stays the same. Right now the filesystem is one of the most used interfaces for applications, but it lacks some standardization inside docker and kubernetes. Moving to another specific implementation for advanced cases is something for the future and I would love to see secret distribution within kubernetes, which does not rely on bending tools, but that does not mean kubernetes cannot provide a common interface via the filesystem too. At least provide it until applications can actually use the proposed API natively. Adding glue code to each used application just moves the tool bending to another level, which I actually dislike even more.

**Comment by bgrant0607** [comment]
Status update @pmorie or @erictune?

Should this be closed, or more specific issues filed for unresolved issues?

**Comment by erictune** [comment]
I will document secrets and then close this with a link to that doc.

**Comment by erictune** [comment]
We now have secrets, which are distributed via a volume.  There is also an option to pass them in env vars.  This issue is still good reading on the design space, but it doesn't need to be an open issue.

**Comment by tamsky** [comment]
@erictune what is the status of secrets, and are they documented?

>I will document secrets and then close this with a link to that doc.

**Comment by erictune** [comment]
They are implemented and documented here:
http://kubernetes.io/v1.0/docs/user-guide/secrets.html

**Comment by tamsky** [comment]
Thanks!

**Comment by tamsky** [comment]
Thanks!
