### ISSUE TITLE
Return 201 when objects are created

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#2031]
Currently we return 200 when a new object is created, spec:

> If a resource has been created on the origin server, the response SHOULD be 201 (Created) and contain an entity which describes the status of the request and refers to the new resource

Extracted from #1782

**Comment by bgrant0607** [comment]
@smarterclayton Do you think it would be a problem to make this change in v1beta1?

**Comment by smarterclayton** [comment]
I don't think it would be a problem - all of the clients have dealt with 200/201 as "success" since 0.4 at least, and if a third party is assuming only 200 is ok they were broken on 202 Accepted before.

----- Original Message -----

**Comment by bgrant0607** [comment]
Fixed by #4263.
