### ISSUE TITLE
Excessive number of conversion functions in v1beta1/2

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#2040]
I just went to do something simple and found that there's an awful lot of conversion functions in v1beta1, which seem to be working around the fact that old TypeMeta needs to go two places because it got split. Except it doesn't really need to go two places, because we can remove the new TypeMeta from the internal, unversioned types. And then we just need to provide a way to teach the conversion package that old TypeMeta matches both new TypeMeta and new ObjectMeta, which shouldn't be too hard. Then we can get rid of these verbose conversion functions.

Action items:
1. Remove TypeMeta from internal unversioned objects (it remains the way it is in external objects in v1beta3)
2. Adjust conversion's field name matching strategy.
3. Remove verbose conversion functions.

Low priority, so filing an issue instead of fixing.

**Comment by nikhiljindal** [comment]
Now that v1beta1 and 2 are deleted, it seems to me that this issue can be closed.
@lavalamp Can you confirm?
