### ISSUE TITLE
remove "checkErr" function from pkg/kubectl

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#2146]
Everyone likes to make a function like this when they start out on go, but once you actually start seeing how unhelpful the error messages it gives are (how they don't include useful line numbers), it quickly becomes clear that it's actually best practice to just write the "if" statement all over.

**Comment by ghodss** [comment]
As the Go newb who created this function :smile:, the reason for its creation was that the Run function for Cobra commands does not let you return an error, like a main() function. So if you need to check an error several times in a Run function ([as we do](https://github.com/GoogleCloudPlatform/kubernetes/blob/35cc1b0c15fed3cdaf818e37b2589f37f5c650b5/pkg/kubectl/cmd/update.go#L52)), it helps to abstract out the functionality. However, it's possible it's become overused by other cmd helper functions, and refactoring those functions to not use checkErr and instead to return errors may be advisable.

**Comment by jlowdermilk** [comment]
Picking this up to use [proposed pattern](https://github.com/GoogleCloudPlatform/kubernetes/pull/5016#discussion_r25817768) for error handling as followup from #5016.
