### ISSUE TITLE
Namespace as own Kind

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#2159]
Need to be able to CRUD namespace resources.

Do during or after the query-parameter -> namespace-in-path transition.

A namespace object just contains the name of the namespace, and no other data that I can think of at this time.

An object cannot be created in a namespace unless the namespace object already exists. 

Reasons:
 - prevent accidental creation of new namespaces as a side effect of object creation with mistyped namespace name.
 - limit which users can create new namespaces, as there may be some policy around who can get which names.
 - to ease validation/warning about authorization policy, admission control policy, etc, which references namespaces.
 - to ease listing/watching namespaces in peripheral system components.

**Comment by derekwaynecarr** [comment]
I want to revisit this discussion if possible now that the Namespace in path transition is complete.  

I am biased to now agree that we need a mechanism to list namespaces to support traversal of the cluster, but I would like a ```Namespace``` to have some additional data than what @erictune proposed initially.

A ```Namespace```  object contains the following:

1. Name
2. Labels
3. Annotations

A ```Namespace``` object is not in a namespace, and is stored in a etcd key-space like ```/registry/namespace/{name}``` to ensure uniqueness.

```kubectl``` should support listing them.

HTTP semantics:

| Action | HTTP Verb | Path | Description |
| --- | --- | --- | --- |
| CREATE | POST |  /api/{version}/ns | Create namespace |
| GET | GET| | /api/{version}/ns/{ns} | Get namespace {ns} |
| UPDATE | PUT | /api/{version}/ns/{ns} | Update namespace {ns} |
| DELETE | DELETE | /api/{version}/ns/{ns} | Delete namespace {ns} |
| LIST | GET | /api/{version}/ns | List namespaces |
| WATCH | GET | /api/{version}/ns | Watch for namespace |

The only update supported is for labels and annotations.

Per @jbeda comment on not needing to reserve a label to use it, now that Admission Control is proceeding (see #3248), we could run with an admission control plug-in that optionally enforces that the namespace is defined.

This a rough sketch, but wanted to re-raise the topic after some further reflection on my part.

**Comment by thockin** [comment]
I like the simple semantic, rather than namespacing namespaces.  What you
describe feels "obvious"

**Comment by derekwaynecarr** [comment]
A little more detail after thinking on life-cycle:

A ```Namespace``` has:

1. Name
2. Label
3. Annotations
4. Status = Active / PendingDelete

If a ```Namespace``` is PendingDelete, we can reject all creation requests in that Namespace as part of admission control.  A control loop on kube-controller-manager can monitor for ```Namespace``` in PendingDelete and delete all content in the ```Namespace```.  Once all content is deleted, the ```Namespace``` itself is purged.

I think this handles all the basic life-cycle requirements around Namespace as Kind.

I will pull together the issues discussed into a PR to augment our existing namespace design if folks are ok with this, and then we can get a PR in place with the implementation.

**Comment by erictune** [comment]
You could also prevent creation of new things in a pending-delete namespace
by changing Policy.

**Comment by derekwaynecarr** [comment]
Yes - assuming policy is in etcd and writable.

**Comment by bgrant0607** [comment]
@derekwaynecarr Anything left to do here, or can this be closed?

**Comment by derekwaynecarr** [comment]
This can be closed.  Remaining work around the use case can be handled separately.
