### ISSUE TITLE
Services not working on OS X anymore

### ISSUE THREAD

**Issue by rawlingsj** [GoogleCloudPlatform/kubernetes#2170]
Hi, following a discussion https://github.com/openshift/origin/issues/328

It seems that after a recent commit services rely on the 'iptables' linux command.  This means that Kubernetes will not work on OS X where I've been successfully running Kube Services and boot2docker until now.

Is this a conscious design decision to not run on OS X or is this a bug that can be reverted or an alternative cross platform solution found?

**Comment by markturansky** [comment]
Volumes in boot2docker work but are fairly limited because b2d only mounts /Users into the VM.

So long as your volume lives beneath /Users, Kube on OS X w/ boot2docker works except for services.

**Comment by bgrant0607** [comment]
cc @vmarmol
