### ISSUE TITLE
Document API HTTP status codes in api-conventions.md and file bugs for inconsistencies in API implementation

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2174]
Status and error behavior is not well documented and @erictune has found it to be inconsistent, when writing auth_test.go. We need consistent behavior with respect to HTTP status codes and API errors so that clients can respond in a uniform manner regardless of the object kind, including API plugins.

One source to start with is:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/errors/errors.go

/cc @smarterclayton @lavalamp

**Comment by abonas** [comment]
@bgrant0607  this is also relevant to error codes:
https://github.com/GoogleCloudPlatform/kubernetes/issues/5491

**Comment by bgrant0607** [comment]
@abonas Please take a look at:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#http-status-codes

**Comment by bgrant0607** [comment]
This specific issue is done. We should still document the status codes in swagger -- filed #6167 for that.
