### ISSUE TITLE
Need a simple way to verify basic networking

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#2178]
Twice in the last two weeks I have dealt with "bugs" which turned out to be due to the fact that the fundamental requirements of pod networking were not being met.

We need a way for a user to very quickly verify that the basic assumptions are met: pods can talk to pods, master can talk to pods, pods can talk to master, services work, etc.

**Comment by lavalamp** [comment]
Remaining action item:

Write a go script (bash if you must) that runs the networking test from cmd/e2e/e2e.go against an existing cluster. Something that you can run via "go run" would be great, or adding flags to cmd/e2e/e2e.go such that you can run it with something like "_output/go/bin/e2e -test=network" would be great too.

**Comment by zmerlynn** [comment]
Reopening. Along the way in #4145, we're moving the e2e script. But I also noticed this is relying on test assets. If you're trying to ship something to users, `cmd/e2e` isn't something we ship to users.

**Comment by filbranden** [comment]
Running `hack/ginkgo-e2e.sh -t TestNetwork` will work after #4145.

We might end up renaming the test as part of the Ginkgo migration, in which case we can update this issue to indicate the correct invocation.

**Comment by brendandburns** [comment]
Closing this as #4273 is merged.
