### ISSUE TITLE
Provide a formal upgrade policy

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#220]
How often do we make breaking changes, and what does it look like to upgrade a running kubernetes cluster? Should we start cutting releases, with tags and things?

**Comment by roberthbailey** [comment]
This has all been addressed elsewhere:

* Breaking changes is covered by [versioning.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/versioning.md) which was recently merged. 
* Cluster upgrades has spawned lots of issues (see for example #2524).
* We now have releases, with fancy tags and things.
