### ISSUE TITLE
Multi-network interface systems

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#222]
In the case of a system with multiple network interfaces, how do we decide which interface to listen on? Is there value in letting users tell us directly?

From email to google-containers:
> ... Since my Docker hosts are multihomed, I need to specify the IP a port should be bind to. Given that I don't know the IP in advance, kubernetes would need to provide a way to specify the interface or network.

**Comment by thockin** [comment]
This should be resolved with the new chooseHostInterface
