### ISSUE TITLE
Need an integration test dashboard

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#2234]
We have a number of real platforms that claim to be supported, but it is VERY hard to test if a change breaks one of them.

I'd like to see a dashboard that shows test results for real e2e runs on each platform, such that partners can maintain an e2e hook which kicks off on every commit or every hour or something, and feed the results back to the dashboard.

At least I'll ex post facto if I broke vSphere or Vagrant or ovirt or ...

**Comment by roberthbailey** [comment]
Superseded by #4871.
