### ISSUE TITLE
Write CLI+config roadmap

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2235]
Need roadmap, main principles (e.g., rooted by API schema, declarative updates, composable generations/transformations), and full vision. Probably need much of #1007 and some of the [group discussion](https://groups.google.com/forum/#!topic/google-containers/lZcoeLAKYnY). Also see the [config-deployment](https://github.com/GoogleCloudPlatform/kubernetes/issues?page=1&q=is%3Aopen+is%3Aissue+label%3Aarea%2Fconfig-deployment) and [CLI](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Acomponent%2FCLI) labels.

**Comment by brendandburns** [comment]
This was closed by #3645
