### ISSUE TITLE
pause death hard to debug

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2252]
The go-based pause container sometimes dies on startup with "runtime: panic before malloc heap initialized", presumably due to lack of memory. This causes the pod startup to fail here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L717

```
E1109 18:21:41.437963 02142 kubelet.go:642] Error running pod e785b021-67d5-11e4-ab4c-42010af01b2d.etcd container plivo: API error (500): Cannot start container 025bf32a8acbae42a49ff46489913f2fc59371edce0a0fd50121f69726d197e3: cannot join network of a non running container: 5373f95a78468e2c3218dc5a7874f1edc5d77b6b74fe5fb00efa1ed28fa8e802
E1109 18:21:51.452491 02142 kubelet.go:642] Error running pod e785b021-67d5-11e4-ab4c-42010af01b2d.etcd container plivo: API error (500): Cannot start container 5a1ad55d55768c5234669a6de24cfb4a217b06bca2ed144bd24410cd4018c51f: cannot join network of a non running container: d476737e0b3b872b9038d7339c25ef840fc683a78e8156cde563f9416debad64
E1109 18:22:01.434824 02142 kubelet.go:642] Error running pod e785b021-67d5-11e4-ab4c-42010af01b2d.etcd container plivo: API error (500): Cannot start container 1d318088e5aeb59e1de5070fe83c4f33c16439a29cd6956ee4371e85c1237f88: cannot join network of a non running container: 8b206c720648aed6dbcb8de2be88a1af5549a9432b140071af175a48e6638c2c
E1109 18:22:11.521773 02142 kubelet.go:642] Error running pod e785b021-67d5-11e4-ab4c-42010af01b2d.etcd container plivo: API error (500): Cannot start container 596884b7c40a1a9cf49838a69309f35db04a65a9f70239cf2afa79003bdc1e1e: cannot join network of a non running container: 621ba6695261625d884fb4e5a02b76278ce7ad1ad711da04bd5ce1cc3f52f4eb
```

This is kind of obscure and hard to debug. There's no OOM kill in kernel logs, and the container logs get deleted, now that we do some kind of GC. Maybe a good use case for the new termination message mechanism. Also, is there a way we can protect these containers from this sort of problem, via oom_score_badness or some other way?

@maxhawkins stumbled across this problem:
https://botbot.me/freenode/google-containers/2014-11-09/?msg=25156508&page=3

His pods stayed in "waiting" at least for an amount of time that he thought it wasn't making progress.

It looks like FindPodContainer doesn't consider dead containers, so what should happen is that syncPod should find no pause (i.e., network) container on the next round and try to recreate the whole pod, including the pause container. Of course, the same thing might happen again, turning this into a crash loop.

/cc @vmarmol @vishh @dchen1107 @thockin

**Comment by thockin** [comment]
Is this still a worthwhile issue?

**Comment by dchen1107** [comment]
All efforts I listed above were done long time ago.
