### ISSUE TITLE
'int' in API types considered harmful

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#2264]
The go compiler is allowed to treat 'int' as either 32 or 64 bits. This is unacceptable for an API that may need to work on multiple systems, with binaries compiled by compilers with different ideas about the proper bit width for an int. Therefore, we need to use int64 or int32 in our API objects, not int.

I vote for int64 everywhere, because consistency. The extra bit width has basically no cost-- doesn't make a difference for json encoding, and if we ever switch to something like gob-- well, gob's number format doesn't emit any 00 high bytes, so no cost there either.

**Comment by a-robinson** [comment]
cc @fabioy

**Comment by brendandburns** [comment]
I'm going to pull this out of v1.0

**Comment by bgrant0607** [comment]
The most problematic uses of IntOrString will be eliminated by flipping to v1beta3.

**Comment by thockin** [comment]
v1b3 will keep IntOrString for ports, but resources become "real" things.

**Comment by thockin** [comment]
Other than IntOrString, is there anything left that is plain int?  Can this be renamed to "IntOrString" should use fixed-width ints?

**Comment by bgrant0607** [comment]
Can just be closed, I think.
