### ISSUE TITLE
It looks as if you don't have a compiled kubecfg binary

### ISSUE THREAD

**Issue by allencloud** [GoogleCloudPlatform/kubernetes#2284]
Hi, all

I hope to experience Kubernetes on my local machine. But some issue happens like below:

I installed etcd and it is running.
I run the script of ./local-up-cluster.sh, and it is indeed running.

But when I run cluster/kubecfg.sh list /pods , it shows:
        
       It looks as if you don't have a compiled kubecfg binary.

        If you are running from a clone of the git repo, please run
        './build/make-cross.sh'. Note that this requires having Docker installed.

        If you are running from a binary release tarball, something is wrong. 
        Look at http://kubernetes.io/ for information on how to contact the 
        development team for help.

And I run ./build/make-cross.sh, it shows:
        
        +++ Building Docker image kube-build:build-99dd8.
        +++ Building kubecfg for linux/386
        +++ Building kubecfg for linux/arm
        +++ Building kubecfg for darwin/amd64
        +++ Building kubecfg for darwin/386
        +++ Output directory is local.  No need to copy results out.

Then what should I do?  Is the binary kubecfg compiled OK?
when I try to find kubecfg, it is located at   kubernetes/_output/go/bin/kubecfg.
I copy it to /usr/bin, and the error still appears.

Then again, what should I do next to run kubernetes?

Anything helps. Thanks in advance.

**Comment by roberthbailey** [comment]
Hi Allen, I'm going to close this issue as obsolete (partly because we don't use kubecfg any longer -- it's been replaced by kubectl) and because it hasn't been updated in a couple of months.

**Comment by ChillarAnand** [comment]
I am facing the same issue(using kubectl) when trying to setup k8s on VM.

```
→ ./cluster/kube-up.sh
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-1' up with 'virtualbox' provider...
==> master: Clearing any previously set forwarded ports...
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2222 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: vagrant
    master: SSH auth method: private key
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
==> master: Configuring and enabling network interfaces...
==> master: Mounting shared folders...
    master: /vagrant => /home/chillaranand/sandbox/my-first-cluster/kubernetes
==> master: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> master: flag to force provisioning. Provisioners marked to run always will still run.
==> master: Running provisioner: shell...
    master: Running: /tmp/vagrant-shell20170124-9080-1xhkmos.sh
==> master: Prepare package manager
==> master: Provisioning network on master
==> master: Network configuration verified
==> master: It looks as if you don't have a compiled version of Kubernetes.  If you
==> master: are running from a clone of the git repo, please run 'make quick-release'.
==> master: Note that this requires having Docker installed.  If you are running 
==> master: from a release tarball, something is wrong.  Look at 
==> master: http://kubernetes.io/ for information on how to contact the development team for help.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

System info 
```
→uname -a 
Linux pavilion 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
(p35) 
chillaranand@pavilion:~/sandbox/my-first-cluster/kubernetes |
→lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
(p35) 
chillaranand@pavilion:~/sandbox/my-first-cluster/kubernetes |
→go version
go version go1.6.2 linux/amd64
```
