### ISSUE TITLE
Make the scheduler easily extensible

### ISSUE THREAD

**Issue by abhgupta** [GoogleCloudPlatform/kubernetes#2313]
In its current form, if one needs a slightly different scheduler behavior, two things are required:
1. A new predicate or priority function needs to be implemented (if not already available)
2. The plugin/factory code needs to be re-written to consume the new predicate/priority function.

None of this is a big deal, but I would suggest that we make the existing scheduler implementation easily extensible by allowing users (admins) to specify which predicate/priority functions should be used. This can be done by specifying the predicate/priority functions via configuration that is provided to the scheduler factory. In the absence of the configuration, the existing functions can be used as default to initialize the scheduler. 

The existing generic scheduler could then become the default platform-provided scheduler "engine" that did the following:
1. Filter the list of available minions based on constraints/requirements
2. Prioritize the filtered list 
3. Select a minion from the prioritized list

We should probably allow an array of functions to prioritize the minion list. These functions would perhaps be sequentially applied, but as long as the priority function is swappable, this is not a big deal. Finally, we could convert the mechanism of selecting a host (from the prioritized minion list) into a configuration-specified function. None of this would impact the out-of-the-box experience for users, but would greatly aid in handling a variety of use cases surrounding scheduling.

One concrete use case that is not handled today with the existing priority functions relates to regions/zones. We would like all pods within a service to be hosted on minions that are located within a certain region (identified by a node label). This can be handled today with NodeSelector labels on the pods. Within each region there are multiple non-affinity zones defined and there are multiple minions in each zone (think of a zone as a rack of servers/minions). The scheduler (in our use case) is expected to achieve non-affinity (good spread) across zones (a zone is specified using a label on minions as well). The existing spreading function does not have the ability to treat a group of minions within the same zone as same/similar and set host priority accordingly. For instance, if minion11 and minion12 are in zone1, and the service has a pod on minion11, then the priority function should be able to assign a low priority to both minion11 and minion12 and higher priority to the minions in other zones within the region.

**Comment by bgrant0607** [comment]
The initial version of this is done, and there's a separate issue for configurability.
