### ISSUE TITLE
Lack of coherent high level introductory documentation about Kubernetes

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#2334]
I tried to read a *single* *document* that explained the Kubernetes model to me in a coherent way. I could not really find anything: the information I sought seemed to be fragmented across many places. I think we need one document, page etc. which explains in a high level manner what Kuberentes is with a few supporting illustrative examples. I would view this as part of the current "UX" focus. I would be very happy to take a stab at this and to some extent started to do this in a draft document I wrote for a blog that explains how to do logging on Kubernetes.

**Comment by davidopp** [comment]
This was closed by #5063.

**Comment by satnam6502** [comment]
Where is the high level documentation about Kubernetes?

**Comment by davidopp** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/361c208a7dd3684a9130d1d8a91093a835fd1880/docs/overview.md

feel free to reopen this issue and assign to yourself if you are interested in pursuing it further. Realistically I don't think we're going to have more time to work on this in the near future given that we have > 100 open issues tagged with milestone 1.0.

**Comment by satnam6502** [comment]
Thanks. I have on my long list of TODOs to write an ACM Queue article about Kubernetes. I hope some of that material could be contributed back here.
