### ISSUE TITLE
Problem when running multiple kubernetes operations in a fast sequence

### ISSUE THREAD

**Issue by jeinwag** [GoogleCloudPlatform/kubernetes#2347]
We're currently experimenting with kubernetes v0.4.3 and etcd 0.5.0-alpha in a three node cluster, and there seems to be an issue when running multiple kubernetes operations in a fast sequence, for example when resizing a controller. I hope I'm in the right place here, this might as well be an etcd issue.

Let's say there a replication controller called apacheController with size zero. When I do a resize to six replicas, **four** pods show up in the pod list immediately and also get started.

This is what the log of the controller-manager is saying:

    14:06:08.077912 54381 replication_controller.go:198] periodic sync of apacheController
    14:06:09.065471 54381 replication_controller.go:120] Got watch: watch.Event{Type:"MODIFIED", Object:(*api.ReplicationController)(0xc20815b680)}
    14:06:09.065550 54381 replication_controller.go:130] About to sync from watch: apacheController
    14:06:09.067167 54381 replication_controller.go:159] Too few replicas, creating 6
    14:06:09.102498 54381 request.go:274] Waiting for completion of /operations/17
    14:06:09.106698 54381 request.go:274] Waiting for completion of /operations/19
    14:06:09.107238 54381 request.go:274] Waiting for completion of /operations/18
    14:06:09.111027 54381 request.go:274] Waiting for completion of /operations/20
    14:06:09.111382 54381 request.go:274] Waiting for completion of /operations/21
    14:06:09.115521 54381 request.go:274] Waiting for completion of /operations/22
    14:06:11.120430 54381 request.go:274] Waiting for completion of /operations/21
    14:06:11.122132 54381 request.go:274] Waiting for completion of /operations/22
    14:06:13.124210 54381 request.go:274] Waiting for completion of /operations/21
    14:06:13.124485 54381 request.go:274] Waiting for completion of /operations/22
    14:06:15.128620 54381 request.go:274] Waiting for completion of /operations/22
    14:06:15.129459 54381 request.go:274] Waiting for completion of /operations/21

So to me, it looks like the create operations for the remaining two pods are hanging.
A couple of minutes later, there's the following message:

    14:09:08.077612 54381 iowatcher.go:88] Unable to decode an event from the watch stream: unexpected EOF

The pods finally appeared a couple of minutes later:

    14:11:07.738044 54381 request.go:274] Waiting for completion of /operations/21
    14:11:09.763737 54381 replication_controller.go:198] periodic sync of apacheController
    14:11:19.902052 54381 replication_controller.go:198] periodic sync of apacheController
    14:11:28.093639 54381 replication_controller.go:198] periodic sync of apacheController

We're sometimes expriencing the same issue when multiple minions try to register at the nearly same time.

Any ideas on this?

**Comment by bgrant0607** [comment]
Closing as obsolete. Operations have been eliminated, so the precise symptoms described above shouldn't be possible. Please reopen if you still experience a problem with the latest release.
