### ISSUE TITLE
RESTStorage/Registry Update validation is inconsistent across resource types

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#2353]
We need to clarify where we anticipate validation of edits to occur.

In many objects, no validation occurs that the fields modified can be modified, see ReplicationController for an example.  In other objects, we appear to do some comparison of old with new resource - see Pod for example.

Comparison of oldPod with newPod happens in the registry implementation and not the service implementation.  Personally, I think this is wrong, and the registry tier should just be responsible for persistence of what is given, and not responsible for any higher order business logic on what fields can and cannot be edited.  

The current pattern makes swapping a different registry implementation less clear on the expected rules to follow for particular resource types.

We need to clean all of this up such that:
1. resources that support edits follow a consistent pattern for validating fields that can be edited
2. it should be obvious if I swap registry implementations what level of validation is expected to occur at each tier.

**Comment by bgrant0607** [comment]
@smarterclayton Does the new RESTUpdateStrategy fully resolve this?

**Comment by smarterclayton** [comment]
Yes, and all core resources are changed to use Validate*Update as distinct from create.  Since there are other issues covering upgrading storage this is closeable.
