### ISSUE TITLE
Error building kubernetes docker images 

### ISSUE THREAD

**Issue by jredl-va** [GoogleCloudPlatform/kubernetes#2378]
While following the documentation to build the kubernetes docker image:  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/local_docker.md

An error is encountered when executing: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/build/make-run-images.sh

```
exec: "build/build-image/make-binaries.sh": stat build/build-image/make-binaries.sh: no such file or directory2014/11/14 12:01:41 Error response from daemon: Cannot start container 28112fb62d1135832380e518f86a0ddf1b929cce68d5ceedac0d6495f5dd0836: exec: "build/build-image/make-binaries.sh": stat build/build-image/make-binaries.sh: no such file or directory
!!! Error in ./build/../build/common.sh:385
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: ./build/../build/common.sh:385 kube::build::run_build_command(...)
  2: ./build/make-run-images.sh:32 main(...)
Exiting with status 1
```

Unsure if the documentation is out of date or if there is a valid bug here.

**Comment by jbeda** [comment]
We are putting "kubernetes in docker" on the back burner and this code was removed in #3231.  When we pick this up again we'll track it in #19.
