### ISSUE TITLE
Stale docker artifacts on GCE minions

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#2411]
I suspect this is dues to the recent change to container VMs as the base image?  @dchen1107 

ifconfig docker0 - exists but should not.

iptables-save | grep docker - 4 docker rules that should not exist.

**Comment by bgrant0607** [comment]
Is this still relevant?

**Comment by zmerlynn** [comment]
`docker0` was still a containervm turd the last time I checked. It's just not causing any harm.

**Comment by thockin** [comment]
Yeah, no harm, just ugly.

**Comment by dchen1107** [comment]
I think we should remove the docker0 from minion nodes, but do we still need this for master node?

cc/ @ArtfulCoder

**Comment by dchen1107** [comment]
This is required by running etcd server as pod with flannel on gce nodes. @ArtfulCoder Please sync your cluster with this fix.
