### ISSUE TITLE
Kubelet send events to apiserver on all platforms

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#2439]
PR #2387 added ability for kubelet to make read/write call to apiserver, and in particular to send events about pod lifetime to apiserver.

I only added support for GCE.  This umbrella bug is to add support for all other cloud providers.

I'll make issues for each cloud provider so they can be individually assigned.

**Comment by ddysher** [comment]
What's the status now, I've ran a local cluster and the pod stays unknown, kubectl describe gives nothing helpful:

````
$ describe pods k8s-inspect-pod                                                                                                                                                                                         
Name:                           k8s-inspect-pod
Image(s):                       ddysher/k8s-inspect
Host:                           127.0.0.1/
Labels:                         name=k8s-inspect,role=test
Status:                         Unknown
Replication Controllers:        <none>
Events:
Time                            From            SubobjectPath   Reason          Message
Fri, 23 Jan 2015 16:34:21 -0500 {scheduler }                    scheduled       Successfully assigned k8s-inspect-pod to 127.0.0.1      %!v(MISSING)
```

Looks like kubelet doesn't send event.

**Comment by erictune** [comment]
I haven't converted the local cluster to send kubelet events.  I need to do that soon.

**Comment by erictune** [comment]
For all platforms whose config lives in our repo, this is done or a PR is under review.
