### ISSUE TITLE
Kubelet token distribution on AWS

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#2440]
Make #2387 work for AWS.

Suggested steps:
  1. add the same lines to cluster/aws/templates/create-dynamic-salt-files.sh as #2387 added to cluster/gce/templates/create-dynamic-salt-files.sh
  1. change `{% if grains.cloud == "gce" %}`  to `{% if grains.cloud in ["gce", "aws"] %}` in cluster/saltbase/salt/kube-apiserver/default and cluster/saltbase/salt/kube-apiserver/init.sls
  1. change `if provider != "gce"` to `if provider != "gce" and provider != "aws"  {` in cmd/e2e/e2e.go
  1. CLOUD_PROVIDER=aws hack/e2e-test.sh

**Comment by erictune** [comment]
I realized that there are actually several separate AWS getting-started guides.
There is docs/getting-started-guides/aws.md  which uses kube-up and there is docs/getting-started-guides/coreos.md which includes AWS.

**Comment by erictune** [comment]
At the same time as doing this work, also change the kube-proxy to set the flag:
 `--master=http://$APISERVER:7080`.

**Comment by justinsb** [comment]
For work-coordination: I'm going to start my day today by doing this, at least for AWS/Ubuntu.  I'm working in https://github.com/justinsb/kubernetes/tree/fix_aws

**Comment by erictune** [comment]
Awesome, thank

**Comment by bwahn** [comment]
Great news~

**Comment by erictune** [comment]
looks fixed
