### ISSUE TITLE
Salt Minions should be authenticated

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#2448]
Before kube-up-ping a cluster, generate keys for nodes.
Turn off auto_accept on the master so master verifies the minions that want to join.
That way someone cannot spoof being a kubernetes master to the salt master and then get the master's keys (or, pretend to be a minion, though this will be less impactful when the master has policies installed to limit what actions minions are authorized to do.)

This could be obsoleted if @jbeda proposal #2303 is implemented first.

**Comment by erictune** [comment]
@zmerlynn does your recent change "Change GCE to use standalone Saltstack config" make this bug obsolete?

**Comment by zmerlynn** [comment]
I hunted for this bug when I was looking for other master-kubelet securing
paths and didn't see it. Yeah, on GCE at least.

**Comment by wojtek-t** [comment]
Does it make sense to have an issue with milestone 1.0 and priority P3?
