### ISSUE TITLE
node.Name/minion.Name should not be used as an address

### ISSUE THREAD

**Issue by anguslees** [GoogleCloudPlatform/kubernetes#2462]
According to my git grepping, the cloudprovider.Instances().IPAddress() function is only used when finding *pod* hosts (ie: pod.getInstanceIP()), not when finding *minion* addresses (ie: minion.ResourceLocation()) for healthchecking, etc.

The result is that my (openstack) cloudprovider is called to find minions and returns a list of "names".  These names are neither literal IPs nor DNS names, so minion.ResourceLocation turns them into URLs that later fail to resolve, and the new minions never pass health checks.

I suggest minion.ResourceLocation should use code very much like pod.getInstanceIP to do name->address mapping via the cloudprovider plugin.  This would presumably involve moving getInstanceIP out into a common library/singleton somewhere so both callers can benefit from a shared cache (see getInstanceIP).

**Comment by alex-mohr** [comment]
Dup of now-fixed https://github.com/GoogleCloudPlatform/kubernetes/issues/4384

**Comment by anguslees** [comment]
Alas, the bug is not yet fixed.  We now have both internal and external addresses from the cloud provider, but those addresses are not being used in many places.  For example, see code like: https://github.com/GoogleCloudPlatform/kubernetes/blob/a8f2cee8c5418676ee33a311fad57d6821d3d29a/pkg/registry/minion/rest.go#L147

**Comment by ddysher** [comment]
correct, it's not used right now.  #4434 is one step toward the goal.  Replacing node.Name with different ip address involves more than just a field replace though.

**Comment by alex-mohr** [comment]
CJ, I think you're closest to which IP address is being used?  Also, hardening master<->kubelet communication might fix this as part of cert validation and proxy functions?

**Comment by alex-mohr** [comment]
And can you please update title with actual remaining issues?

**Comment by cjcullen** [comment]
The usages I know of:
https://github.com/GoogleCloudPlatform/kubernetes/blob/a8f2cee8c5418676ee33a311fad57d6821d3d29a/pkg/registry/minion/rest.go#L147
https://github.com/GoogleCloudPlatform/kubernetes/blob/8fa21ebd624ba39ec68b67ea301e6c54b9ffdc25/pkg/master/master.go#L615

**Comment by anguslees** [comment]
Btw (and apologies if this is obvious), but when changing Name -> IP in URLs, we need to also use net.JoinHostPort() because some of those IP literals might be IPv6 and need special quoting.   A simple `git grep 'https\?://%s'` catches several incorrect examples.

**Comment by cjcullen** [comment]
Definitely was not obvious to me. Thank you for pointing that out.

**Comment by roberthbailey** [comment]
We would also like an indicator of which node addresses are signed by the certificate on the node, so that we will be able to establish a secured TLS connection when contacting the node.

**Comment by roberthbailey** [comment]
The code in master.go is part of the /validate endpoint, which @fabioy is ripping out as part of #7092.

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by cjcullen** [comment]
#9155 removed the last place (that I could find) where we were using node.Name as an address.

**Comment by bgrant0607** [comment]
#9155 was reverted.

Also see #9267

**Comment by alex-mohr** [comment]
Closing #2462 via #9451
