### ISSUE TITLE
better logging for scheduler/kubelet

### ISSUE THREAD

**Issue by goern** [GoogleCloudPlatform/kubernetes#2471]
I have set up a master+2minions, on each minion the kubelet config file carried a `KUBELET_ADDRESS="--address=1.2.3.4"` and `KUBELET_HOSTNAME=""`. This resulted in a situation where the minions where watching for scheduled pods at `registry/nodes/localhost/boundpods` and the apiserver did put them on `registry/nodes/1.2.3.4/boundpods`.

Investigating the situation revealed some logs entries like
> Nov 19 20:50:52 localhost kube-scheduler: E1119 20:50:52.057822 00628 reflector.go:106] watch of *api.Pod ended with error: unexpected end of JSON input

on the master.

Maybe some better logging would help, as the situation was not analyzable by looking at the logs only (hard for remotees to debug).

**Comment by timothysc** [comment]
+1 for better logging, but also config.  
several people have now hit this issue.

**Comment by lavalamp** [comment]
> Nov 19 20:50:52 localhost kube-scheduler: E1119 20:50:52.057822 00628 reflector.go:106] watch of *api.Pod ended with error: unexpected end of JSON input

We should stop logging this because it has nothing to do with any actual problems but it's hard to convince people of this when they have a problem and this is sitting in their logs.

Anyway, we should add a check for this to the /validate handler (that kubelet thinks it's called what apiserver thinks it's called). It's a configuration error.

**Comment by lavalamp** [comment]
Events make it easy to see where scheduler assigned a pod, but they don't make it easy to see that kubelet is looking in the wrong place.

When we switch kubelet over to read pods from apiserver directly we could consider including some sort of check that generates an event or logs an error message (or returns a 401 or something) when a kubelet asks for pods not assigned to it.

**Comment by erictune** [comment]
@lavalamp revaluate next steps or close, now that boundPods gone.

**Comment by lavalamp** [comment]
Yeah. This error condition is no longer possible, I believe.
