### ISSUE TITLE
local-up-cluster.sh should start the proxy as root

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/kubernetes#2485]
It seems that since ip per service, the proxy require root in order to call iptable, so starting local-up-cluster with a non-root user currently fails, with the following error:
```
E1120 01:09:26.606120    5279 proxier.go:319] Failed to initialize iptables: error creating chain "KUBE-PROXY": exit status 3: iptables v1.4.19.1: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

**Comment by roberthbailey** [comment]
@proppy @smarterclayton Is this still an issue?

**Comment by markturansky** [comment]
local-up-cluster.sh runs everything with ```sudo``` these days.

**Comment by roberthbailey** [comment]
Thanks @markturansky! Marking this as fixed.
