### ISSUE TITLE
Better validation message

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#2486]
We now have pretty structured way of validating api object, but the error message to end user is not descriptive, e.g. when creating a replication controller with restart policy 'never', we get:
```
spec.template.restartPolicy: invalid value '{<nil> <nil> 0xe68308}
```
even as simple as label name, we shouldn't assume end-user is familiar with our requirement.

Apart from what is wrong, we'd better also give why it is wrong.

**Comment by lavalamp** [comment]
Orrrr we could switch to spew, which is already a dep.

**Comment by lavalamp** [comment]
Actually we're printing a reflect.Value there, which makes no sense at all. I will fix.
