### ISSUE TITLE
Kubelet doesn't kill old pods when BoundPods is empty

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2495]
To reproduce:
* Start a cluster via hack/local-up-cluster.sh
* Start some pods
* Kill the cluster
* "docker ps -a" should show the pod containers running still
* Start the cluster again
* "etcdctl ls /registry" should show that there is no boundpods directory -- only minions and services
* "docker ps -a" should show the old pod containers still running
* Start a new pod
* After, say, 10s, "docker ps -a" should show the old containers dead

/cc @dchen1107

**Comment by saad-ali** [comment]
I suspect the cause of this might be [```pkg/kubelet/kubelet.go#L1118```](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1118):
```GO
case <-time.After(kl.resyncInterval):
	glog.V(4).Infof("Periodic sync")
	if kl.pods == nil {
		continue
	}
```
which guarantees that the pod sync logic is never called if Kubelet.pods is nil.
Need to get a repro to confirm.
