### ISSUE TITLE
apiserver too many open files

### ISSUE THREAD

**Issue by mindscratch** [GoogleCloudPlatform/kubernetes#2521]
I have a 3 node etcd cluster, 1 kubernetes master and 6 minions which were running for 18 hours. I had no pods, services, etc deployed. When I tried to do a "kubecfg list {pods,minions,services}" the command just hung, which seemed odd.

Looking at the logs I saw the apiserver reported "too many open files". The ulimit is currently 1024 which might be low, but I was surprised considering the lack of activity on the system.

Doing some digging using netstat and lsof I found that the apiserver had 1015 connections open to two of the three etcd servers. The command was:
```
netstat -anp | grep <api server pid>
lsof -p <api server pid>
```
The hosts are running CentOS 6.5. I was using kubernetes 0.4.3 and etcd 0.4.4.

**Comment by bgrant0607** [comment]
Please reopen if you experience the problem with a newer version of Kubernetes.
