### ISSUE TITLE
kube-down.sh seems to delete master too early

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#2523]
After my aborted attempt to create a 1,000 node cluster (by `cluster/kube-up.sh`) and only getting as far as 73 or so machines I decided to tear down the cluster with `cluster/kube-down.sh`. This process failed with the error at the end of this transcript about not being able to detect the master node. Furthermore, many of the nodes have not been deleted. Now, I am going to write a script that goes through and deletes all the instances etc. that match kubernetes-minion-* since I can't bear the thought of manually deleting so many resources.

You can see the transcript at https://gist.github.com/satnam6502/eac1e34a4f7f6f57d0f2 since it is too long to include in an issue.

For the the build I used HEAD was at f57c072e4a1b37a107b2a1113f9b03344a1a5b39 (last commit at 13:34 Thu 20 Nov 2014).

**Comment by roberthbailey** [comment]
We still delete the master first (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L691) but since there haven't been any complaints about ordering lately I'm going to close this. Please reopen if you continue to run across this issue.
