### ISSUE TITLE
ReplicationController + crashlooping or invalid docker image = bad times

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#2529]
ReplicationController has no idea when the pods it is making will deterministicly fail. This can rapidly fill your cluster with pod objects.

Mitigation: throttle the rate at which rep. ctlrs. can make new pods.

Real fix? Make replication controller watch events & stop after N tries failed without any successes?

**Comment by lavalamp** [comment]
To recap.

While kubelet is restarting a pod, apiserver will list its status as "Failed", which will cause replication controller to make additional pods.

Action item here is to make apiserver give a reasonable amount of time (forever?) to kubelet to perform as many restarts as it wants, and during that time the pod should count as Running (if it ever ran) or Pending (if it never successfully started).

**Comment by lavalamp** [comment]
(Eventually we want to push pod status generation down into kubelet but I think it's worthwhile making this intermediate fix because this really hoses your cluster when it happens to you.)

**Comment by thockin** [comment]
I don't think it is about "reasonable amount of time" but having enough
information to make the correct observation.

**Comment by dchen1107** [comment]
@lavalamp  #2999 was merged a while back, and with that change, now PodCondition / PodStatus are determined by both ContainerStatus and RestartPolicy.

**Comment by lavalamp** [comment]
Dawn is right, this bug seems to be fixed and should probably be closed.

**Comment by bgrant0607** [comment]
There's still the broader issue of making replication controller do something useful (e.g., raising events, including number of pending pods in status) in this scenario.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/76370
