### ISSUE TITLE
Can not start controller-manager using controller-manager.service

### ISSUE THREAD

**Issue by asdfsx** [GoogleCloudPlatform/kubernetes#2562]
In docs/getting-started-guides/coreos/units/controller-manager.service, there is a parameter called etcd_servers. But in the latest version, controller-manager doesn't need this parameter any more. So may be the service file should also delete this parameter. @kelseyhightower

**Comment by bgrant0607** [comment]
Fixed:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml
