### ISSUE TITLE
Eliminate the need for namespaces with URI names

### ISSUE THREAD

**Issue by hapnermw** [GoogleCloudPlatform/kubernetes#2565]
Kubernetes has done a nice job simplifying cluster configuration and eliminating sources of conflict across separately developed services. Kubernetes namespaces are an attempt to apply this approach to naming within a cluster. Unfortunately, in this case, the result is to confuse rather than simplify cluster naming.
A good example of the confusion caused by namespaces is resource type naming. In the ‘Kubernetes-defined resource types’ section the predefined resource namespace is specified as resources.kubernetes.io. The predefined resource type names are all of the form kubernetes.io/resources/<resource-name>.  The redundancy of these shows the problem with this design. It is a microcosm of the problem that would exist if the web had used this design instead of URIs. 
IMHO, Kubernetes would be well-served by ditching its namespace-based naming design and replacing it with names that are URIs.

**Comment by smarterclayton** [comment]
Yet every api client ever written has to build a url to something, or walk through 8 layers of indirection (applying logical transformation in code at each step) to arrive at a url.  It's unrealistic to expect that no urls are ever constructed, so I'd attack it from the other perspective, which is that if someone gives you a URL, you should not transform or extract it.  Then you're only arguing about how many layers of resource indirection do you perform prior to getting a response, which most people prefer to be zero, but can grow over time (I believe we have everything needed except the resource -> path within a version transformation today to do the indirection).

Namespaces are part of the resource path so we can easily shard and apply proxy access control on top of them.  They have to be somewhere - the path is no better or worse than any other mechanism.

**Comment by derekwaynecarr** [comment]
It's impossible to follow this issue at this point.

Do we not like Kubernetes defining a Namespace to REST resource naming?

Or do we not like that compute resource names (ie memory and cpu) will require fully qualified names when wanting to limit vendor specific resource concepts (ie openshift.com/builds)?

Can we close this issue and either create the right one or two focused issues depending on where the complaint is directed?  Namespace as a scope for pods, services, etc or fully qualified resource name conventions for compute resources?

**Comment by bgrant0607** [comment]
Thank you for the background on URIs, but this isn't feasible to change at this point, and I don't see how URIs would solve the problems that are solved by the current URL structure.
