### ISSUE TITLE
Endpoints are not validated prior to persistence

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#2572]
In fixing up #2570, it came to my attention that we do no validation of an Endpoints object prior to persistence.  This seems like a problem, and at minimum, it should have a validateEndpoints method in validation.go like all other resource types.

**Comment by bgrant0607** [comment]
FYI @thockin

**Comment by gmarek** [comment]
I want to bump up @pmorie question: do we know what valid endpoint looks like? Some things are clear, like ports, some are more tricky:
- does IP currently is just an IPv4 address, or hostname/IPv6 is allowed (IPv4 only I guess)?
- IIUC endpoints are namespaced, but I want to double check?
- do we want any nontrivial validation, except adding validation for ObjectReference (#4651) when possible?
- which fields can be changed during update, and do we allow create on update? (I guess all of them)

I'll finish the logic, and write tests as soon as I know that we're on the same page.

**Comment by thockin** [comment]
For now I think IPv4 only, updates can change the endpoints list.  But I am
also working on a big change to endpoints, so maybe hold off on this just a
bit longer

**Comment by gmarek** [comment]
Sure - I noticed your PR yesterday.

**Comment by gmarek** [comment]
Fixed per #5709
