### ISSUE TITLE
Update getting-started-guides to to replace kubecfg commands with kubectl equivalents

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#2573]
[Getting started docs](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides) should direct users to run kubectl commands since kubecfg is being deprecated #2144.

**Comment by bgrant0607** [comment]
@MikeJeffrey By the end of today, kubectl will have all the necessary functionality to fully replace kubecfg. Certainly the syntax is settled. I'd like to move forward with updating all the docs.
