### ISSUE TITLE
Update examples to use kubectl

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#2575]
Cleanup related to #2144; need to replace kubecfg commands with kubectl equivalents in [kubernetes/examples](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples).

**Comment by jlowdermilk** [comment]
Examples now all use/refer users to kubectl.

**Comment by DreadPirateShawn** [comment]
As a note, the "Debugging FAQ" page still refers to kubecfg list events rather than kubectl get events.
https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ

(I didn't see a separate ticket for that, so apologies if I'm just blind...)
