### ISSUE TITLE
Set User-Agent in client library

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2596]
Forked from #2243.

@smarterclayton wrote: We've used `libname/<deep version>-commit (os: , runtime: )` in the past, and then changed libname to the executable name when used in a binary.  "os" helps catch wierd envs people care about but we didn't think to test, runtime has been useful for error reports, commit catches roll your own folks but won't work for us (since it's a compile time thing).

curl:
```
curl/7.26.0
```

Common browser/tool/bot settings are here:
http://www.useragentstring.com/pages/useragentstring.php

I still think it would be useful to set User-Agent, for monitoring purposes if nothing else, though I'm becoming less sure it could be used to customize default behavior.

**Comment by erjohnso** [comment]
+1

**Comment by smarterclayton** [comment]
Fixing this now
