### ISSUE TITLE
Clarification on private docker registry setup

### ISSUE THREAD

**Issue by silasdavis** [GoogleCloudPlatform/kubernetes#2603]
[These docs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md) state: "All users of the cluster will have access to any private registry in the .dockercfg."

Does this mean if I create a .dockercfg in the working directory of ANY minion or master node, all nodes will then have access to my private docker registry. Or do I need to create it in the master node? Or do I need to create it in all nodes?

**Comment by brendandburns** [comment]
This was effectively closed by:

https://github.com/GoogleCloudPlatform/kubernetes/blob/5450afdabc51876a24b9576b7df54ee149153c69/docs/user-guide/production-pods.md#authenticating-with-a-private-image-registry
