### ISSUE TITLE
Better errors on input validation

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#2617]
#2515 gives us a place to stick validation error details - we should use it throughout.

**Comment by bgrant0607** [comment]
Example problems we should catch: invalid port, volume, or volumemount names.

And we need to run the validation in kubelet as well as apiserver, for standalone uses.

**Comment by lavalamp** [comment]
Can I make the rule that whenever you make an error about a particular value, you also must make sure that value shows up in the error message? Otherwise people have no idea what the error is about and it's super frustrating.

**Comment by bgrant0607** [comment]
@lavalamp Agreed.

**Comment by bgrant0607** [comment]
I think #2486 is a specific instance of not correctly stringifying the value.

**Comment by brendandburns** [comment]
This appears to be fixed by #4174 If there is still a problem, re-open.
