### ISSUE TITLE
Reorganize documentation around specific audiences

### ISSUE THREAD

**Issue by MikeJeffrey** [GoogleCloudPlatform/kubernetes#2633]
This is a tracking bug for some documentation changes:

- Create a readme for each directory containing documentation:
  - docs/
  - docs/devel
  - docs/design
  - examples
- Should list all docs and a description of each.

- Move FAQs to the wiki
   - also any content that shouldn't have to go through code review, such as links to community projects
- Create placeholder pages in the repo to point to the wiki (eg. docs/faq.md with content pointing to wiki).

- Merge files where possible.

- Move any examples from the api/ directory into the examples/ directory
  - Update any tests relying on these examples

**Comment by bgrant0607** [comment]
Forked #7299 for remaining work.
