### ISSUE TITLE
Kubernetes pods empty but kubelet service keeps some containers running in minion

### ISSUE THREAD

**Issue by carlossg** [GoogleCloudPlatform/kubernetes#2657]
I have been creating and destroying pods, resizing replication controllers, in a Vagrant environment, and I've seen several times that I get to a point when there are docker containers running that don't show up in `kubecfg list pods`.
The master doesn't know anything about the pods, and if I go to the minion and kill the container it gets started again. Restarting the boxes doesn't fix it. 

I created a gist with the log output https://gist.github.com/carlossg/52185c5dd581c37fc8d6
From mailing list https://groups.google.com/forum/#!topic/google-containers/RbZMrGkFYJk

At this point it would be useful to know how to recover the cluster to a pristine status without destroying the boxes, what data to delete and services to restart, and what other logs may be useful to debug the issue in case it happens again.

**Comment by smreed** [comment]
Seeing this issue currently in a 0.8.1 cluster. Will try manual delete of bound pods from etcd.

**Comment by dchen1107** [comment]
From @smreed's last comment, looks like kubelet does the right thing here.

**Comment by dchen1107** [comment]
@carlossg @smreed are you guys still observing the same issue with 0.9 release. There are several fixes in to fix boundPod not being updated issue. etcd server crash issue is handled separately.

**Comment by smreed** [comment]
We haven't seen this in a while

**Comment by smreed** [comment]
Sorry that was vague. We did not see this at all with the 0.9 release.

**Comment by dchen1107** [comment]
Thanks for updates. I am closing the issue for now, please feel free to reopen it if you observed the same issue again. Thanks!
