### ISSUE TITLE
No support for Load Balancer on EC2

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#2659]
I'm planning on implementing load-balancer support for EC2, using ELB.  I'm opening this issue so that if there are any parallel efforts or other concerns, we can discuss them here.

**Comment by bakins** [comment]
@justinsb I see that #2672 was closed.  I see a few related PR's have been merged since then.  Wanted to check on the state of the ELB work and if you needed any help. I need to scratch the same itch.

**Comment by justinsb** [comment]
@bakins - #2672 was an early mega-patch, and I've been submitting smaller patches since then (many of which cover the same ground in more incremental stages).

This is current AWS LB PR that I'm working on:  #5225 

This is actually "next-up" for me - I should be able to spend a few hours on it today which - with any luck - will get it into a state for merging.  I believe the remaining problems are:
1) make sure this code to interact with ELB actually works (straightforwardish)
2) tweak the kube-proxy to work with the ELB NAT model (which is different from GCE, but the same as OpenStack, so hopefully not as hard as it was back in #2672)
3) check how the load-balancer endpoint is exposed (because ELB's endpoint is a DNS name, not an IP)  I think this should be OK.

We also have a failing e2e test for this (and the e2e tests are almost running completely against AWS), which is good.

I'm happy to collaborate if you'd like - I believe you have my email address!

**Comment by justinsb** [comment]
Patch is now available in #5225 :-)

**Comment by benmccann** [comment]
@justinsb i'm guessing this can be closed now that https://github.com/GoogleCloudPlatform/kubernetes/pull/8733 is merged?
