### ISSUE TITLE
Allow minions to be securely registered/deregistered

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#267]
Taken from #180:

> ... As this is written now, minions could use this API to add themselves. But we need to figure out some security stuff (How do minions trust the master? How does master trust the minions?) first before enabling that.

Adding/removing minions should be both abstracted (we'd like to use Mesos turtling to allocate new minions, for instance) and operators should be confident that the minion they're adding is trusted and that from a minion they're not getting MITM'd

**Comment by davidopp** [comment]
See also #3168

**Comment by roberthbailey** [comment]
As far as I can tell, this is entirely superseded by my proposal to get to static clustering in [#3168](https://github.com/GoogleCloudPlatform/kubernetes/issues/3168#issuecomment-74781577). 

Please re-open if you disagree.
