### ISSUE TITLE
Document API versioning policy and rationale

### ISSUE THREAD

**Issue by hapnermw** [GoogleCloudPlatform/kubernetes#2695]
Kubernetes is a great project and I would love to see it be wildly successful. If this does happen, it needs a practical api evolution strategy.

Below, I’m using the term ‘resource’ for the URIs a service presents and ‘representation’ for the data HTTP operations on resources accept/produce.

Kubernetes’ current approach of adding the apiVersion property to every representation it consumes and produces will quickly become problematic as it evolves.

The following explains why this is the case; and, what kubernetes should do to fix it. 

You likely already know most of this but indulge me in attempting to make my case :>).

The most important principle of REST service design (and internet design in general) is Postal’s Law - ‘be liberal in what you accept, and conservative in what you send’. This combined with the principle ‘clients must ignore what they don’t understand’ enables version-less service api evolution. Version-less apis require the service designer and implementor to work a bit harder but the result is a service that minimizes the complexity of evolving its clients. 

There is a lot of confusion/confabulation about REST service api evolution. Many service designers fall back to naively sticking ‘version’ on everything not realizing the future pain it will cause and the alternatives they have of avoid it.

Versions on protocols like TCP and HTTP work because they evolve slowly and are very general. Even with HTTP, its header follows the principles above - adding a new header does not require a new HTTP version.

REST is at the application protocol layer and, at this layer, REST provides the functionality to support version-less evolution.

Incremental change of a REST resource is done by careful addition of new properties to its representations. Old clients continue using old properties and they must actively ignore the new properties they don’t understand. Resources smoothly evolve and clients don’t have to deal with the complexity of ‘keeping up’ with an apiVersion they are forced by the service to manage.

Broader/deeper change Is handled by adding new service resources. Old clients continue using old resources. New clients use the new ones.

Why is this a better strategy than adding apiVersion to everything? 

1. apiVersion is a crutch for bad service design - smoothly evolving an api is harder than simply replacing it with a new ‘version’

2. apiVersion forces client upgrade flag days - using any new functionality requires that the client upgrade its code to the latest apiVersion; since the service has shielded itself with a new apiVersion, it can liberally mix backward compatible changes with those that are not

3. Clients don’t want their api replaced with a new version - they want functionality smoothly added to the api they are currently using

4. Often the service apiVersion facade is not complete - a service may not be able to determine what version of a representation to produce so it produces a version that clients aren’t expecting; this is ‘fixed’ by forcing clients to upgrade

5. In many cases, clients end up having to deal with evolution both within and across apiVersions so the meaning of what an apiVersion represents becomes completely muddied (assuming it had any meaning in the first place)

6. These are just a few of the problems apiVersion is likely to result in

**Comment by bgrant0607** [comment]
Done: #6391
