### ISSUE TITLE
kubectl should not need to talk to the master to run "help"

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#2702]
$ ./cluster/kubectl.sh help
ERROR: (gcloud.compute.instances.describe) Some requests did not succeed:
 - The resource 'projects/thockin-dev/zones/us-central1-b/instances/kubernetes-master' was not found

**Comment by bgrant0607** [comment]
The right solution to this is to nuke kubectl.sh

**Comment by zmerlynn** [comment]
Is there an issue to track nuking `kubectl.sh` once the `.kubeconfig ` changes settle? Though it's somewhat complicated, since right now it's choosing the latest compiled binary.

**Comment by bgrant0607** [comment]
Not for kubectl.sh. The same issue came up with kubecfg.sh: #834

**Comment by bgrant0607** [comment]
BTW, it seems to me that the "find the binary" problem would be more properly solved by PATH, symlinks, moving the binary to a /bin directory in the build/release process, etc.

**Comment by zmerlynn** [comment]
Agreed. But it's actually not that simple because the script chooses the most recent one, which is rather convenient.
