### ISSUE TITLE
etcd on master died due to running out of memory on day-old cluster with very little activity

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#2719]
Yesterday I spun up a cluster on GCE around 2pm using the 0.5.2 release. I scheduled two nginx pods on it with a replication controller, then ran kube-push using the 0.5.3 release to update the master. I then started 3 nginx pods on a different replication controller. Everything seemed to be working.

This morning I tried listing the pods and got an error from kubecfg:
F1202 11:11:14.120573   22165 kubecfg.go:428] Got request error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

On the master, etcd is no longer running, and the etcd logs indicate that it ran out of memory. Over night, it looks like snapshots were taken about every half hour, but nothing else is in the logs other than the stack traces:
[etcd] Dec  1 22:13:06.623 INFO      | kubernetes-master: state changed from 'follower' to 'leader'.
[etcd] Dec  1 22:13:06.623 INFO      | kubernetes-master: leader changed from '' to 'kubernetes-master'.
[etcd] Dec  1 23:33:51.960 INFO      | kubernetes-master: snapshot of 10006 events at index 10006 completed
[etcd] Dec  2 00:42:22.390 INFO      | kubernetes-master: snapshot of 10011 events at index 20017 completed
[etcd] Dec  2 01:41:25.973 INFO      | kubernetes-master: snapshot of 10001 events at index 30018 completed
[etcd] Dec  2 02:33:53.816 INFO      | kubernetes-master: snapshot of 10012 events at index 40030 completed
[etcd] Dec  2 03:21:15.942 INFO      | kubernetes-master: snapshot of 10005 events at index 50035 completed
[etcd] Dec  2 04:04:56.331 INFO      | kubernetes-master: snapshot of 10001 events at index 60036 completed
[etcd] Dec  2 04:45:31.110 INFO      | kubernetes-master: snapshot of 10004 events at index 70040 completed
[etcd] Dec  2 05:23:48.165 INFO      | kubernetes-master: snapshot of 10006 events at index 80046 completed
[etcd] Dec  2 06:00:05.639 INFO      | kubernetes-master: snapshot of 10015 events at index 90061 completed
[etcd] Dec  2 06:34:32.590 INFO      | kubernetes-master: snapshot of 10005 events at index 100066 completed
[etcd] Dec  2 07:07:29.809 INFO      | kubernetes-master: snapshot of 10002 events at index 110068 completed
[etcd] Dec  2 07:39:15.418 INFO      | kubernetes-master: snapshot of 10009 events at index 120077 completed
[etcd] Dec  2 08:09:46.621 INFO      | kubernetes-master: snapshot of 10007 events at index 130084 completed
[etcd] Dec  2 08:39:15.081 INFO      | kubernetes-master: snapshot of 10011 events at index 140095 completed
[etcd] Dec  2 09:07:46.872 INFO      | kubernetes-master: snapshot of 10010 events at index 150105 completed
[etcd] Dec  2 09:35:28.577 INFO      | kubernetes-master: snapshot of 10013 events at index 160118 completed
[etcd] Dec  2 10:02:19.479 INFO      | kubernetes-master: snapshot of 10007 events at index 170125 completed
[etcd] Dec  2 10:28:28.815 INFO      | kubernetes-master: snapshot of 10009 events at index 180134 completed
[etcd] Dec  2 10:53:59.705 INFO      | kubernetes-master: snapshot of 10016 events at index 190150 completed
[etcd] Dec  2 11:18:49.189 INFO      | kubernetes-master: snapshot of 10017 events at index 200167 completed
[etcd] Dec  2 11:43:06.186 INFO      | kubernetes-master: snapshot of 10020 events at index 210187 completed
[etcd] Dec  2 12:06:44.526 INFO      | kubernetes-master: snapshot of 10009 events at index 220196 completed
[etcd] Dec  2 12:29:58.950 INFO      | kubernetes-master: snapshot of 10003 events at index 230199 completed
[etcd] Dec  2 12:52:47.210 INFO      | kubernetes-master: snapshot of 10023 events at index 240222 completed
[etcd] Dec  2 13:15:14.640 INFO      | kubernetes-master: snapshot of 10025 events at index 250247 completed
[etcd] Dec  2 13:37:15.713 INFO      | kubernetes-master: snapshot of 10006 events at index 260253 completed
[etcd] Dec  2 13:58:56.031 INFO      | kubernetes-master: snapshot of 10018 events at index 270271 completed
[etcd] Dec  2 14:20:37.346 INFO      | kubernetes-master: snapshot of 10001 events at index 280272 completed
[etcd] Dec  2 14:42:04.366 INFO      | kubernetes-master: snapshot of 10021 events at index 290293 completed
[etcd] Dec  2 15:03:07.422 INFO      | kubernetes-master: snapshot of 10003 events at index 300296 completed
[etcd] Dec  2 15:23:50.334 INFO      | kubernetes-master: snapshot of 10016 events at index 310312 completed
[etcd] Dec  2 15:44:24.786 INFO      | kubernetes-master: snapshot of 10009 events at index 320321 completed
[etcd] Dec  2 16:04:47.581 INFO      | kubernetes-master: snapshot of 10010 events at index 330331 completed
[etcd] Dec  2 16:24:52.737 INFO      | kubernetes-master: snapshot of 10022 events at index 340353 completed
[etcd] Dec  2 16:44:43.265 INFO      | kubernetes-master: snapshot of 10005 events at index 350358 completed
fatal error: runtime: out of memory

**Comment by brendandburns** [comment]
Closing this as obsolete, with luck our soon-to-be-launched soak tests will catch any future problems.
