### ISSUE TITLE
Support VMWare in Vagrantfile

### ISSUE THREAD

**Issue by jameskyle** [GoogleCloudPlatform/kubernetes#2741]
It'd be nice to support vmware in the vagrant file. 

Pull request incoming.

**Comment by jameskyle** [comment]
I'm going to get this done. I got distracted by a new :baby: for a couple of weeks.

**Comment by posita** [comment]
@jameskyle Congratulations on your :baby:! I wanted support for Parallels, and thought I'd bang out both at the same time. I didn't see any branches addressing this issue in [jameskyle/kubernetes](/jameskyle/kubernetes), but I hope I didn't step on any toes. Check out PR #6879. I don't have VMWare, so perhaps you can help me test that part?

**Comment by jameskyle** [comment]
My toes are fully in tact. Apparently raising these little tykes takes significant time and can be a bit disruptive to plans. Who knew!

**Comment by posita** [comment]
@jameskyle, it looks like my PR was merged (that was fast), but please reopen this if there's something that I missed, especially on the VMWare side.

**Comment by derekwaynecarr** [comment]
If there are issues unique to the non VirtualBox provider, who is signing up to maintain that?  I am fine keeping the general Vagrant setup stable, but I am unable to debug issues specific to virtualization tool.

**Comment by posita** [comment]
> If there are issues unique to the non VirtualBox provider, who is signing up to maintain that?  I am fine keeping the general Vagrant setup stable, but I am unable to debug issues specific to virtualization tool.

Perhaps only VirtualBox will be "officially supported" and the rest will be "community supported"? This ain't my rodeo :horse_racing:, but it seems like with many aspects of Kubernetes, those making use of particular features can contribute to their maintenance? It appears that's how this issue and my attempt at a fix came about in the first place. The volume of this project is explosive (just look at the number of external merges in the past 24 hours :open_mouth:; it's *insane*). Don't underestimate the efficiency of emergent markets. :relaxed:

Between me and @jameskyle (when he's not busy being a :man: tending to his :baby:), we can probably make a pretty big dent in any issues that arise. Feel free to assign any non-VirtualBox Vagrant issues to me. If I can't handle them within a reasonable time, maybe someone else can take a stab?

Cc: @legal90 (hint, hint) :smirk:

**Comment by derekwaynecarr** [comment]
Thanks

**Comment by legal90** [comment]
@derekwaynecarr @posita Yes, I can help with issues related to Parallels Desktop for Mac and to the provider for Vagrant (["vagrant-parallels"](https://github.com/Parallels/vagrant-parallels))
