### ISSUE TITLE
boundPods can get out of sync

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#2794]
Concrete proof provided by @FlorianOtel

https://gist.github.com/FlorianOtel/fee8a5344d0c41688013

I started to look at fixing this on my plane flight on sat; but it's not clear the right approach.

* Delete boundPods entirely?
* Fix various error paths in delete/update/assign functions that could allow this to get out of sync?
* Add boundPods controller to keep this synced?

Compounding this, boundPods appears to not get served from the api (?!?!), so there's no way to fix this from a client.

**Comment by lavalamp** [comment]
Can we close this issue? Kubelet watches apiserver for pods now, correct?

**Comment by bgrant0607** [comment]
Yes, the solution is to nuke boundPods, and there is another issue for that.

**Comment by bgrant0607** [comment]
No longer writing boundpods as of #5320.
