### ISSUE TITLE
Fedora-Ansible installation sets subnetwork address as bridge address

### ISSUE THREAD

**Issue by skonefal** [GoogleCloudPlatform/kubernetes#2826]
In inventory we set:

> [minions]
> 192.168.121.84  **kube_ip_addr**=**10.0.1.0**
> 192.168.121.116 kube_ip_addr=10.0.2.0

kube_ip_addr is used in roles/network-hack-bridge/tasks/main.yml:
> - name: Create kubernetes bridge interface
>  command: nmcli connection add type bridge ifname kbr0 con-name kubernetes-bridge ip4 {{ **kube_ip_addr** }}/24

in the end, we have bridge in first minion:
> kbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet **10.0.1.0**  netmask 255.255.255.0  broadcast 10.250.4.255

Subnetwork address cannot be bridge address.

---

In Vagrant scripts in cluster/vagrant/provision-network.sh there is:
> BRIDGE_ADDRESS=${BRIDGE_BASE}.${MINION_ID}.1
> 29	BRIDGE_NETWORK=${BRIDGE_ADDRESS}/24

I this capability should be added to fedora-ansible scripts.

**Comment by eparis** [comment]
this is not a kube bug and is a kubernetes-ansible problem.  this issue should be closed.  @bgrant0607
