### ISSUE TITLE
API Server reporting incorrect status of running pod

### ISSUE THREAD

**Issue by stefwalter** [GoogleCloudPlatform/kubernetes#2828]
Kubernetes API Server is reporting the wrong status for a running pod. I have a single container pod scheduled, and as far as I can see it is running on the minion, but kubernetes is very confused about its state.

It shows as 'Pending':

```
[stef@falcon cockpit]$ kubectl get pods 
NAME                IMAGE(S)                HOST                    LABELS              STATUS
apache              fedora/apache           <unassigned>            name=apache         Pending
second-test         vbatts/fedora-varnish   minion.thewalter.lan/   name=Second Test    Running
```

But you can see that it's running:

```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                NAMES
75f4e4a862c0        fedora/apache:latest           "/run-apache.sh"    About an hour ago   Up About an hour                         k8s_master.92a78031_apache.default.etcd_1416906634_c673f516         
4ab706944e0b        vbatts/fedora-varnish:latest   "/srv/run.sh"       About an hour ago   Up About an hour                         k8s_varnish.ecd56c27_second-test.default.etcd_1417637612_ac61c488   
9e4313824d6c        kubernetes/pause:latest        "/pause"            About an hour ago   Up About an hour    0.0.0.0:80->80/tcp   k8s_net.e9a68336_apache.default.etcd_1416906634_496b6211            
744be56e11a5        kubernetes/pause:latest        "/pause"            About an hour ago   Up About an hour                         k8s_net.fadb6b63_second-test.default.etcd_1417637612_77cfd3a8       
```

The container is accessible on the machine.

**Comment by AshleyAitken** [comment]
@brendandburns I thought I read somewhere (in the source code?) that desiredState.manifest.id was deprecated.  I left it out of my config for that reason AND because I didn't know what it was for / what sensible value to give it (I'm not keen on giving different id the same value).

**Comment by lavalamp** [comment]
@stefwalter is this still happening to you?

**Comment by stefwalter** [comment]
Sorry for the delay, but my kubernetes setup has gone completely crazy. it has phantom minions that it's trying to connect to (as indicated in logs), but are not listed in 'kubectl get minions'. 'kubectl get pods' is failing with 'The requested resource does not exist.' ... anyway long story short I'm having a hard time figuring how to get it working again.

**Comment by stefwalter** [comment]
@lavalamp I just managed to upgrade to 68298f0 (post 0.8) ... and cannot duplicate this anymore.

**Comment by brendandburns** [comment]
Closing this, as it seems to be fixed?  Please re-open if you see problems.
