### ISSUE TITLE
Configuring the OOM Killer for processes managed by kubelet

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#2852]
We saw when kNode is overcommited, sys oom will pick up a process to kill. It is very difficult to debug such situation, especially when process picked by kernel is one of the daemon processes: docker, kublet, etc. We should configure oom_score_adj with proper value from -1000 to 1000, at least assigning daemon processes a smaller value, so that they wouldn't like to be picked up by kernel oom killer. 

Another use case is that we should config OOM Killer differently for container with proper resource request from the ones without proper request initiated. 

In a long run, we might want to config OOM Killer based on SLA / priority. 

Ideally docker should expose an API to handle this since it starts the application's root process (will file separate issue to docker, but not sure when we are going to have it). Also cadvisor is not a proper place to have this since it is read-only, and not control the lifecycle of cgroups.

**Comment by vishh** [comment]
Lowering the priority of this issue since the system daemons are now protected. The network container is still not protected, but since it gets restarted, it is not that bad.

**Comment by vishh** [comment]
The network container now has a lower oom score, thanks to recent changes by @vmarmol.
I am closing this issue. We can open a separate issue for supporting OOM priority for user containers.
