### ISSUE TITLE
Controller-manager should retry upon a connection lost to the api-server

### ISSUE THREAD

**Issue by nirmal070125** [GoogleCloudPlatform/kubernetes#2868]
It appears that controller manager never retries, if it lost the connection to the api server.

-- Logs begin at Thu 2014-12-11 18:37:57 UTC. --
Dec 11 18:38:17 master systemd[1]: Starting Kubernetes Controller Manager...
Dec 11 18:38:17 master systemd[1]: Started Kubernetes Controller Manager.
Dec 11 18:38:17 master kube-controller-manager[1172]: I1211 18:38:17.294687    1172 plugins.go:70] No cloud provider specified.
Dec 11 18:38:17 master kube-controller-manager[1172]: E1211 18:38:17.303476    1172 replication_controller.go:109] Unexpected failure to watch: Get http://127.0.0.1:8080/api/v1beta1/watch/replicationControllers?fields=&labels=&resourceVersion=: dial tcp 127.0.0.1:8080: connection refused
Dec 11 18:38:17 master kube-controller-manager[1172]: E1211 18:38:17.306522    1172 endpoints_controller.go:49] Failed to list services: Get http://127.0.0.1:8080/api/v1beta1/services?labels=: dial tcp 127.0.0.1:8080: connection refused

**Comment by bgrant0607** [comment]
I don't think this is a problem in practice, at least not any longer.
