### ISSUE TITLE
Logging with fluentd returns no results

### ISSUE THREAD

**Issue by Fandekasp** [GoogleCloudPlatform/kubernetes#2918]
I've followed the [fluentd-ek documentation](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/contrib/logging/fluentd-ek), and I have:

* kubernetes v0.6.2
* cluster on aws with coreos
* cloud-config downloads the [manifest](https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/v0.6.2/cluster/saltbase/salt/fluentd-es/fluentd-es.manifest) and the kubelet starts the k8s container

I start the elasticsearch & kibana pods&services once the cluster is ready, then access the kibana interface, but it's empty:

![kibana](http://i.imgur.com/GfE5Z4K.png)

When I try to look at the fluentd containers from a minions,  I notice 2 containers, one without logs, and one which I cannot get the logs from (trying to read a dir) : 

    core@ip-10-203-134-251 ~ $ docker ps
    CONTAINER ID        IMAGE                                     COMMAND               CREATED             STATUS              PORTS                    NAMES
    5b84d6b6b0c1        kubernetes/pause:go                       "/pause"              41 minutes ago      Up 41 minutes                                k8s_net.b5228d0a_f8ed9f29-8281-11e4-9762-22000b5d8b58.default.etcd_f8ed9f29-8281-11e4-9762-22000b5d8b58_f0d6a4be                        
    402d9280b5b3        google/cadvisor:0.6.2                     "/usr/bin/cadvisor"   41 minutes ago      Up 41 minutes                                k8s_cadvisor.b0dae998_cadvisormanifes12uqn2ohido76855gdecd9roadm7l0.default.file_cadvisormanifes12uqn2ohido76855gdecd9roadm7l0_12af549e 
    6ec0778b8095        kubernetes/fluentd-elasticsearch:latest   "/run.sh"             41 minutes ago      Up 41 minutes                                k8s_fluentd-es.f0eebcdc_fluentdesmanife2u464h05heqcpotoddodpnehjaqsde.default.file_fluentdesmanife2u464h05heqcpotoddodpnehjaqsde_8b796b69
    d2977ca519a7        kubernetes/pause:go                       "/pause"              43 minutes ago      Up 43 minutes                                k8s_net.dbcb7509_fluentdesmanife2u464h05heqcpotoddodpnehjaqsde.default.file_fluentdesmanife2u464h05heqcpotoddodpnehjaqsde_6d16c9c9      
    11b191014528        kubernetes/pause:go                       "/pause"              43 minutes ago      Up 43 minutes       0.0.0.0:4194->8080/tcp   k8s_net.a0f18f6e_cadvisormanifes12uqn2ohido76855gdecd9roadm7l0.default.file_cadvisormanifes12uqn2ohido76855gdecd9roadm7l0_ac3ef956      
    core@ip-10-203-134-251 ~ $ docker logs d2977ca519a7                                                                                                                                           
    core@ip-10-203-134-251 ~ $ docker logs 6ec0778b8095
    tail: error reading '/outerhost': Is a directory
    core@ip-10-203-134-251 ~ $

 Here is what my pods/services look like from the master:

    core@ip-10-157-93-30 ~ $ kubectl get pods
    NAME                                   IMAGE(S)                       HOST                LABELS                      STATUS
    kibana-pod                             kubernetes/kibana:latest       10.5.180.32/        app=kibana-viewer           Running
    f8ed9f29-8281-11e4-9762-22000b5d8b58   10.5.180.32:5000/database      10.203.134.251/     name=postgresql             Pending
    synthetic-logger-0.25lps-pod           ubuntu:14.04                   10.5.180.32/        name=synth-logging-source   Pending
    synthetic-logger-10lps-pod             ubuntu:14.04                   10.231.168.3/       name=synth-logging-source   Running
    heapster                               kubernetes/heapster            10.5.180.32/        name=heapster               Running
    elasticsearch-pod                      dockerfile/elasticsearch       10.231.168.3/       app=elasticsearch           Running
    docker-registry                        registry                       10.5.180.32/        name=docker-registry        Pending
    f8ee1e1c-8281-11e4-9762-22000b5d8b58   10.5.180.32:5000/database      10.231.168.3/       name=postgresql             Pending
    influx-grafana                         kubernetes/heapster_influxdb   10.231.168.3/       name=influxdb               Running
                                           kubernetes/heapster_grafana
                                           dockerfile/elasticsearch
    core@ip-10-157-93-30 ~ $ kubectl get services
    NAME                 LABELS               SELECTOR                                  IP                  PORT
    kubernetes-ro        <none>               component=apiserver,provider=kubernetes   172.28.33.120       80
    kubernetes           <none>               component=apiserver,provider=kubernetes   172.28.228.145      443
    influx-master        name=influxdb        name=influxdb                             172.23.189.52       8085
    elasticsearch        name=elasticsearch   app=elasticsearch                         172.16.44.9         9200
    kibana               name=kibana          app=kibana-viewer                         172.21.98.138       5601
    registry-service     <none>               app=docker-registry                       172.16.10.24        5000
    postgresql-service   name=postgresql      name=postgresql                           172.30.45.174       5432
    core@ip-10-157-93-30 ~ $

Any idea what the problem could be? How can I debug this issue?
Thanks in advance for your help

**Comment by Fandekasp** [comment]
In one week, then. Ok, sounds good. Thanks guys :)

**Comment by satnam6502** [comment]
I've verified that the fix produced by @thockin works. Once it gets merged then things should start to work again. The Docker image for the Fluent collector has already been updated and the other changes are in PR #3245.

**Comment by Fandekasp** [comment]
I verified that v0.8.0 had #3245 in it, then recreated a cluster. After 10 min, kibana still didn't show anything, and checking elasticsearch returns nothing:

```
core@ip-10-69-78-113 ~ $ curl -XGET 172.16.146.170:9200/_search?size=100
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}core@ip-10-69-78-113 ~ $
```

The issue hasn't changed for me after upgrading to v0.8.0. Any idea why?

**Comment by satnam6502** [comment]
Elasticsearch logging is not going to work in v0.8.0 because the PR I am working on has not been merged in time for this release. So I am sorry you will have to wait for the next cut, or wait for the PR to merge (hopefully today) and then build from head. I am very sorry about this.

**Comment by satnam6502** [comment]
If this is a big problem for you I could tell you what you need to do to make things work out. The root of the problem here is that I have renamed the Elasticsearch Kuberntes service from `elasticsearch` to `elasticsearch-logging` to avoid name clashes with other instances of Elasticsearch (likewise for Kibana) and this change is already reflected in the Docker images that are laid down on each node and in the Kibana configuration for the latest release. Here is a fix that could work:
1. You need to adjust the `es-service.yml` file in the `contrib/logging/flunted-ek` directory to name the service as `elasticsearch-logging`. 
2. You need a reverted version of the Kibana image (and adjust es-pod to refer to it). I could make such an image for you. Let me know.

When my PR merges the setup will change to automatically launch Elasticsearch and Kibana so you won't need to run them yourself form the contrib directory. This PR will also launch Elasticsearch and Kibana using replication controllers which makes them more robust (e.g. pods restarted after failure).

**Comment by satnam6502** [comment]
Scrub that. I've reset the :latest images for kubernetes/fluentd-elasticsearch and kubernetes/kibana so they should work with the v.0.8.0 release and for the new version I am using explicit version tags for the images so avoid this issue in the future. I check out v0.8.0 and make sure logging works out of the box.

**Comment by Fandekasp** [comment]
When my PR merges the setup will change to automatically launch Elasticsearch and Kibana so you won't need to run them yourself form the contrib directory.

I am running a custom cluster on aws from a cloudformation template, not using the kubernetes setup commands. Therefore, my creation script is starting the pods, services (and controllers when you'll add them).

I recreated a cluster. This time, I didn't use fluentd-ek-colo, but I used fluentd-ek since you referred to it. I haven't modify the files since you said you reset the :latest images to work with those, but it still fails.
```
core@ip-10-165-115-237 ~ $ curl -XGET 172.16.72.246:9200/_search?size=100
{"took":10,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}
core@ip-10-165-115-237 ~ $ curl -XGET 172.16.72.246:9200/_search?size=100
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}
core@ip-10-165-115-237 ~ $ curl -XGET 172.16.72.246:9200/_search?size=100
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}
```

Sorry to take so much of your time on this issue :(

**Comment by satnam6502** [comment]
No problem! I am very happy to help! Now, I have no experience of trying to get this setup to work on AWS with a custom cluster. However, I can try to help you in any way I can. Note that the logging setup I have produced for Fluentd -> Elasticsearch depends on our DNS support (SkyDNS) because that is how the Fluentd collector knows where to send the log information to by using the DNS name for Elasticsearch (which is `elasticsearch-logging.default` for the setup I have produced). 

I assume you want to do cluster level logging (application level logging can of course by done easily enough without any infrastructure support). The reason we need DNS for our logging scenario is that when the Fluentd->Elasticsearch pod is laid down at cluster creation time for node level logging (via a manifest file) we don't know anything about an Elasticsearch pod or service since none has been started at that point -- so we use the DNS name `elasticsearch.default` which is later resolved to an actual Elasticsearch service which is produced by regular `kubectl` commands during cluster level logging setup.

Now, if you have enough control, one thing you could do is to instantiate an Elasticsearch service *first* -- let's say this is called `elasticsearch` -- then you can lay down your Fluentd collector pods with a configuration which uses the env var to identify Elasticsearch i.e. `ELASTICSEARCH_SERVICE_HOST`. 

Does this make sense? Happy to help with any of this.

**Comment by Fandekasp** [comment]
Thank you ! I also start the fluentd containers before the service (cloudinit), because I do not know yet of another way to insure each instance has 1 and only 1 fluentd container.

I realized that I didn't have skydns installed and running, so I started installing it. I used the replicationController and the service files provided in the `cluster/addons/dns/` directory.
I used *DNS_SERVER_IP=172.16.1.0* (because my portal cidr is 172.16.0.0/16), but since docker is already running with cidr 172.24.0.0/16, I don't see how that could work (I should be running docker with `--dns 172.16.1.0`).
It doesn't seem easy to add skydns in an already running cluster and get already running pods/services to resolve their dns names. Do you have any suggestion ?

So I'm not sure how to get this setup working using a skydns controller&service, I was under the assumption that I had to install it via cloudinit during the master instance creation, and start docker with the proper dns.

I'll try to create a new cluster with `docker --dns-search`, then have the skydns controller/service started before everything else, and see if it magically resolves everything.

**Comment by satnam6502** [comment]
Exactly what image (including tag) are you running for fluentd-elasticsearch? Options: no tag, :latest or :1.0.

The image fluentd-elasticsearch:latest sends logs to elasticsearch.default but  fluentd-elasticsearch:1.0 sends to elasticsearch-logging.default

Perhaps the SkyDNS setup is wrong -- I defer to @thockin on this point.

**Comment by Fandekasp** [comment]
the manifest has no tags specified, hence it's using the cached version or fluentd-elasticsearch:latest when I create the cluster.

@thockin sorry to disturb you with that. Does something look wrong in my SkyDNS setup described above ? Thanks for your advices!

**Comment by Fandekasp** [comment]
Ok, I believe my skydns setup is working, you can see [all the containers logs](http://sprunge.us/aIaa).

Since I cannot install the dig/ns/nslookup tools on the coreos server, and cannot port forward udp through ssh, I'm looking for a way to verify the setup, and the logging stack using it, it should now be working, but it's not the case.

Here are the errors I can see from the kubelet:
```
I0203 09:07:23.094937   10849 event.go:117] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"file-6bb810db-ip-10-146-225-240.ec2.internal", Name:"cadvisor-agent", UID:"b361c431df58ff1e7426b20da9e3239f", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:""}): reason: 'failedValidation' Error validating pod cadvisor-agent.file-6bb810db-ip-10-146-225-240.ec2.internal from file, ignoring: [spec.volumes[0].source: invalid value '<*>(0xc2081446e0){HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> GitRepo:<nil>}': exactly 1 volume type is required, spec.volumes[1].source: invalid value '<*>(0xc208144760){HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> GitRepo:<nil>}': exactly 1 volume type is required, spec.volumes[2].source: invalid value '<*>(0xc2081447a0){HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> GitRepo:<nil>}': exactly 1 volume type is required, spec.containers[0].volumeMounts[0].name: not found 'varrun', spec.containers[0].volumeMounts[1].name: not found 'varlibdocker', spec.containers[0].volumeMounts[2].name: not found 'sysfs']
I0203 09:07:23.095015   10849 event.go:117] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"file-8cd71177-ip-10-146-225-240.ec2.internal", Name:"fluentd-to-elasticsearch", UID:"ba4517d131f21f70b4bf73716a2973be", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:""}): reason: 'failedValidation' Error validating pod fluentd-to-elasticsearch.file-8cd71177-ip-10-146-225-240.ec2.internal from file, ignoring: [spec.volumes[0].source: invalid value '<*>(0xc208150260){HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> GitRepo:<nil>}': exactly 1 volume type is required, spec.volumes[1].source: invalid value '<*>(0xc2081502a0){HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> GitRepo:<nil>}': exactly 1 volume type is required, spec.containers[0].volumeMounts[0].name: not found 'containers', spec.containers[0].volumeMounts[1].name: not found 'varlog']
```

The related manifests are:

* [cadvisor 0.9.1](https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/v0.9.1/cluster/saltbase/salt/cadvisor/cadvisor.manifest)
* [fluend-es 0.9.1](https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/v0.9.1/cluster/saltbase/salt/fluentd-es/fluentd-es.manifest)

Any idea why it fails with error volume type required, when each volume specified in the manifests have one and only one source, which is a valid hostDir ?

**Comment by Fandekasp** [comment]
@thockin since I upgraded to 0.10, the manifests issue has been resolved, but all my pods are constantly showing status Unknown:

```
core@ip-10-233-68-52 ~ $ kubectl get --no-headers pods | awk '{print $4" "$6}'
10.234.164.111/ Unknown
10.234.164.111/ Unknown

10.153.156.38/ Unknown
10.234.164.111/ Unknown
10.153.156.38/ Unknown
10.234.164.111/ Unknown


10.234.164.111/ Unknown

10.234.164.111/ Unknown
10.153.156.38/ Unknown
10.153.156.38/ Unknown

10.153.156.38/ Unknown
10.153.156.38/ Unknown

core@ip-10-233-68-52 ~ $ ps auxw|grep kubelet
root     14653  0.0  0.3 193576 13868 ?        Ssl  05:26   0:04 /opt/bin/kubelet --address=0.0.0.0 --port=10250 --config=/etc/kubernetes/manifests --hostname_override=10.233.68.52 --etcd_servers=http://127.0.0.1:4001 --cluster_dns=172.16.1.0 --cluster_domain=kubernetes.local --logtostderr=true
core     17857  0.0  0.0   4456   808 pts/0    S+   06:48   0:00 grep --colour=auto kubelet

core@ip-10-233-68-52 ~ $ kubectl get services skydns
NAME                LABELS              SELECTOR            IP                  PORT
skydns              name=skydns         app=skydns          172.16.1.0          53

core@ip-10-233-68-52 ~ $
```

Could it be due to skydns still being wrongly setup ? The logs look good to me though: http://sprunge.us/jOKC

**Comment by Fandekasp** [comment]
Unknown status issue is related to #4068

**Comment by satnam6502** [comment]
Hello. What's the most recent status here? Are you still unable to get logging to work? Is DNS the issue for you rather than the logging setup? It would be good to more accurately categorize this problem, thanks.

**Comment by Fandekasp** [comment]
For the Unknown issue, restarting the apiserver fixes the status. I still haven't figured why.

For the logging stack, I'm still unable to run it properly.
When trying to connect remotely through my cluster's nginx with htpasswd auth, I get a `/#/connectionFailed`, I think I need to set the route /elasticsearch/_nodes available without auth, and/or add a site to connect to the elasticsearch service via nginx.

When using ssh with port forwarding to kibana:5601  and elasticsearch:9200, I still see the empty dashboard.

```
core@ip-10-123-142-145 ~ $ kubectl get -l "name=elasticsearch-logging" services
NAME                LABELS                       SELECTOR            IP                  PORT
elasticsearch       name=elasticsearch-logging   app=elasticsearch   172.16.234.10       9200

core@ip-10-123-142-145 ~ $ curl -XGET 172.16.234.10:9200/_search?size=100
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}

core@ip-10-123-142-145 ~ $ kubectl get services skydns
NAME                LABELS              SELECTOR            IP                  PORT
skydns              name=skydns         app=skydns          172.16.1.0          53

core@ip-10-123-142-145 ~ $ kubectl get -l "app=skydns" pods                                                                                                                                   
POD                       IP                  CONTAINER(S)        IMAGE(S)                           HOST                            LABELS              STATUS
skydns-controller-fplln   172.24.96.4         etcd                quay.io/coreos/etcd:latest         10.230.140.143/10.230.140.143   app=skydns          Running
                                              kube2sky            kubernetes/kube2sky:1.0      
                                              skydns              kubernetes/skydns:2014-12-23-001


core@ip-10-123-142-145 ~ $ fleetctl ssh d
core@ip-10-230-140-143 ~ $ ps auxw|grep kubelet
root      9105  4.9  0.5 200044 22244 ?        Ssl  06:58  11:40 /opt/bin/kubelet --address=0.0.0.0 --port=10250 --config=/etc/kubernetes/manifests --hostname_override=10.230.140.143 --etcd_servers=http://127.0.0.1:4001 --cluster_dns=172.16.1.0 --cluster_domain=kubernetes.local --logtostderr=true
```

using kubernetes v0.10.0

**Comment by satnam6502** [comment]
I am working on a PR right now which will change how the cluster level logging services are accessed (to go via a proxy in the same way as the monitoring services) and I hope to avoid the use of the ngnix config.

**Comment by satnam6502** [comment]
PR #5269  for end to end test under review: when this is submitted perhaps you can use it help work out what is going in.

**Comment by satnam6502** [comment]
Closing on the assumption this is no longer an issue -- but please do reopen if it is not.
