### ISSUE TITLE
Kubernetes doesn't handle autoscaled minions properly

### ISSUE THREAD

**Issue by Fandekasp** [GoogleCloudPlatform/kubernetes#2922]
Using Kubernetes v0.6.2, on a AWS cloudformation stack:

    core@ip-10-51-176-7 ~ $ kubecfg list minions
    Minion identifier   Labels
    ----------          ----------
    10.51.182.3
    10.233.91.177

    core@ip-10-51-176-7 ~ $ kubecfg list replicationControllers
    Name                   Image(s)                      Selector            Replicas
    ----------             ----------                    ----------          ----------
    postgresqlController   172.16.92.180:5000/database   name=postgresql     2

    core@ip-10-51-176-7 ~ $ vim cfg/database-controller.yml  # Set 100 Replicas to trigger autoscaling policy
    core@ip-10-51-176-7 ~ $ kubecfg -c cfg/database-controller.yml update replicationControllers/postgresqlController
    I1214 00:12:37.981262    3925 restclient.go:133] Waiting for completion of operation 593
    Name                   Image(s)                      Selector            Replicas
    ----------             ----------                    ----------          ----------
    postgresqlController   172.16.92.180:5000/database   name=postgresql     100

Once a hundred pods has been triggered, here is what's happening:

1. Kubernetes deploys all 100 pods on the 2 minions
2. Minions are overloaded, check instance fails, and kubecfg cannot list minions anymore:

      ```
      core@ip-10-51-176-7 ~ $ kubecfg list minions
      F1214 00:20:33.822859    5827 kubecfg.go:428] Got request error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
      ```
3. within 2 min, a cloudwatch alarm is triggered, which starts a scaleUp policy and adds 2 more minions
4. kubecfg still fails, I have to manually terminate the instance which check fails, and the autoscale group respawns a new healthy instance
5. kubecfg can list minions, but timeout to list pods:
      ```
      core@ip-10-51-176-7 ~ $ kubecfg list minions
      Minion identifier   Labels
      ----------          ----------
      10.51.182.3
      10.144.223.221
      10.136.78.254
      10.178.161.113
  
      core@ip-10-51-176-7 ~ $ kubecfg list pods | grep 10.144.223.221
      ^C
      ```
6. Trying to scale down the number of pods gives weird results:
      ```
      core@ip-10-51-176-7 ~ $ kubecfg list replicationControllers
      Name                   Image(s)                      Selector            Replicas
      ----------             ----------                    ----------          ----------
      postgresqlController   172.16.92.180:5000/database   name=postgresql     10
  
      core@ip-10-51-176-7 ~ $ fleetctl list-machines
      MACHINE         IP              METADATA
      198ae00d...     10.178.161.113  role=minion
      ca92355c...     10.144.223.221  role=minion
      d8ee87a6...     10.51.176.7     role=master
      e85d5976...     10.136.78.254   role=minion
      fc7f7c31...     10.51.182.3     role=minion
      core@ip-10-51-176-7 ~ $ for machine in 1 c e f; do echo "$machine -> $(fleetctl ssh $machine "
      docker ps | grep postgres | wc -l")"; done
      1 -> 0
      c -> 0
      e -> 0
      f -> 39
      core@ip-10-51-176-7 ~ $ kubecfg list pods 
      ^C
      core@ip-10-51-176-7 ~ $
      ```

Here is the list of problems I believe happened:

* Kubernetes breaks if one of the registered minions becomes unavailable. I believe that when this happens, kubernetes should smartly reassign the unavailable node pods to other nodes, and a list could return:

      ```
      core@ip-10-51-176-7 ~ $ kubecfg list minions
      Minion identifier   Labels
      ----------          ----------
      10.51.182.3
      10.144.223.221
      10.136.78.254
       <unavailable>
      ```
* Kubernetes doesn't have policies (eg do not add another pod to an instance having CPU>90%). I'd really like to have something like this so it could wait for the new nodes to be available.
* Kubernetes doesn't assign pods to nodes correctly. When resizing my controller from 100 to 10, I am expecting each node to take on 2~3 pods, but here 39 (?) containers were listed in a single node (probably due to the precedent bug, since I'm still unable to list pods from master).
* I had also tried a ScaleDown policy in my autoscaling group, and when a node was removed, kubernetes would break as well, instead of removing the minion and reassigning pods to other ones.

Are those features work in progress, or planned for the future? Do you have any suggestion on how to handle this stack in the meanwhile?

**Comment by bgrant0607** [comment]
This is subsumed by other issues.
