### ISSUE TITLE
clarify usage of name vs. uid in REST api

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#2932]
all the entities when consumed by REST api return both "id" and "uid" properties.
1. it's quite confusing to have both.
2. id looks more like "name" - why isn't it called name? (especially since it looks like free text string and not numeric)
3. can "id" be changed via an update entity operation? (e.g. with PUT) I tried and got a failure. if it can't, were is it documented as a read only?
4. I'd expect in REST api to be able to query for a specific entity by its unique id like this:
http://localhost:8080/api/v1beta1/replicationControllers/<uid>
however in k8s api using "uid" returns "not found" error.
putting "id" in the url does work, however if the id can be changed (see item 3 above) it's not a good practice to query by it to an entity.

**Comment by bgrant0607** [comment]
@abonas You filed another issue with the same question: which fields can be updated (#3153). Let's use that issue to discuss that topic.

**Comment by smarterclayton** [comment]
It's worth calling out in our doc that kube "name" is a user specifiable ID as most other systems consider them.  Our uid is a true uuid.  Our "name" is immutable, but later "flexibleName" field could be introduced to allow mutation.  Two unique fields in the same pool of names, where you can only release a name via deletion, would solve the problems id/name/uid are traditionally used for (cheap rename).  True rename I think can be solved if someone wanted it, once uids are valid retrieval patterns.

**Comment by bgrant0607** [comment]
We have several docs on this. Immutability has also been documented. Maybe could be better, but good enough for now, I think.
