### ISSUE TITLE
PortalIP assignment

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#2934]
According to this page:
https://github.com/GoogleCloudPlatform/kubernetes/blob/5ef34bf52311901b997119cc49eff944c610081b/pkg/api/v1beta3/types.go

"PortalIP is usually assigned by the master. If specified by the user
// we will try to respect it or else fail the request. This field can
// not be changed by updates."
PortalIP string `json:"portalIP,omitempty"`

1. just to clarify the above - it means that user is allowed to assign it during creation of service, but not during update service - correct? why update is not supported as well?
2. what are the considerations for "we will try to respect it" - what validations are made (Except for addr already in use) ?
3. what exact error is returned when it can't be assigned?

**Comment by fgrzadkowski** [comment]
@bgrant0607 Brian - you added 1.0 milestone to this issue, but I'm not sure what is the action item here. Can you please explain what should be done?

**Comment by bgrant0607** [comment]
The action here is/was to verify the behavior and ensure it is documented correctly.

Thanks to @saad-ali we now have general status code behavior documented:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md

It doesn't say what happens in this specific case, though I don't know that it's possible to document every specific case, at least not in a way that's kept up to date.

I can confirm that 422 is returned in this case:
https://github.com/GoogleCloudPlatform/kubernetes/blob/cf68593fc29586f9c98ea4d59b605707ad022075/pkg/registry/service/rest.go#L105

It would be useful to document that users/clients can specify PortalIP in the services doc:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md

**Comment by brendandburns** [comment]
I'll take the update to services.md and then close this.
