### ISSUE TITLE
Invalidate pod state cache before events from kubelet are propagated

### ISSUE THREAD

**Issue by kostko** [GoogleCloudPlatform/kubernetes#2947]
Currently it can (sometimes) happen that when an event is observed in the `/api/v1beta1/watch/events` stream, the pod status that can be obtained by doing a GET on `/api/v1beta1/pods` is not yet updated and still shows the old value - for example it shows "Waiting" when the event of type "running" originating from the kubelet has already been received via the watched stream.

**Comment by bgrant0607** [comment]
This should be resolved by/after #4561
