### ISSUE TITLE
Kubelet sync loop should be lower impact

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#297]
An efficiency point.  We probably should not submit every pod on every sync loop.  Each source should be able to tell whether it's possible that a pod has changed.

For example, file source can use inotify or just hash the file and only submit the pod update if it has changed.

**Comment by roberthbailey** [comment]
@thockin @dchen1107 Is this still relevant?

**Comment by dchen1107** [comment]
This should be closed.
