### ISSUE TITLE
Systematically tag readonly API fields

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#2970]
Right now we have haphazard comments regarding which fields are read-only/output-only, and many, such as `uid` aren't documented at all.

Swagger 2.0 actually supports a `readOnly` property tag, but we're using Swagger 1.2, which does not, officially. The official meaning doesn't match what we want, though. `readOnly` fields must not be included in a PUT, which would be painful for clients. We could simply document our convention, however.

We should tag fields as readonly. Maybe we could have go-restful automatically add a comment to the description in that case.

**Comment by ghodss** [comment]
Are there any known obstacles with upgrading to 2.0?

**Comment by nikhiljindal** [comment]
go-restful (the framework that we are using to generate swagger-spec) does not support 2.0 yet: https://github.com/emicklei/go-restful/issues/157

**Comment by yujuhong** [comment]
Disclaimer: for the doc-fix it day, I will be adding the read-only information into the description. This partially resolves this issue, but not entirely. I will unassign myself after description is done.

**Comment by yujuhong** [comment]
Note: users can set the node status when creating a node. This is a bug and should be fixed. After fixing that bug, the corresponding description should be updated.
