### ISSUE TITLE
LIST minions is slow for large clusters

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#2973]
Bringing up a 500-node cluster I notice that the `LIST minions` operation is *very* slow (the operation took about 17 minutes). I hope to take a look at the implementation to see what can be done to speed up the listing of minions -- presumably by doing some kind of caching.

**Comment by lavalamp** [comment]
I've put out a temporary fix for this in #3374, since it was easy.
