### ISSUE TITLE
GCE: Forwarding Rules and Target Pools remain after kube-down

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/kubernetes#2984]
This, combined with the fact that the target pools are not updated when creating an external load balancer, means that your next cluster could have a misconfigured LB.

1. Create cluster set NUM_MINIONS=4
2. Create a service "foo" w/ external load balancer.
3. Tear down cluster with kube-down.
4. At this point you can still see your forwarding rules and target pools.
5. Repeat step 1 w/ NUM_MINIONS=6
6. Repeat step 2
7. Note the "foo" target pool only has 4 members. kubernetes-minion-{5,6} are missing.

Possibly addressed by a proper resolution to #1836?

**Comment by jasonkuhrt** [comment]
I just ran into this!

**Comment by jszczepkowski** [comment]
This is related to #4630 and I'm working on it.

**Comment by roberthbailey** [comment]
Closing as a dupe of #4630.
