### ISSUE TITLE
Strip out Status and other readonly fields from user's POST/PUT 

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#3005]
Forked from #1370 

We need to strip out Status info that users's POST/PUT. We've seen examples of users doing this, and config solutions will make it even more common to POST/PUT data returned by GET, including Status.

cc/ @bgrant0607

**Comment by brendandburns** [comment]
@nikhiljindal are you working on this?

**Comment by bgrant0607** [comment]
Not yet, AFAIK.

**Comment by nikhiljindal** [comment]
Yes not working on this right now.
I have a few other P1s that I am looking at right now.
Will pick up this one if no one has picked it by the time I get others done.

**Comment by ddysher** [comment]
I was planning to work on similar things once #3733 goes in.   Also see #2726.

If we drop out Status info, then we'll need to figure out how to convey status information from k8s component, e.g. controller -> apiserver (for node status), kublet -> apiserver (for pod status), etc.  We probably need another endpoint, or filter based on authorization policy.

**Comment by smarterclayton** [comment]
I've got part of this (creates) that I'm working on.  Update is harder

**Comment by ddysher** [comment]
@smarterclayton Any pointer to your work?  so I can stand on the shoulders of giants : )

**Comment by smarterclayton** [comment]
Going to rebase shortly, Tim had some feedback I'm trying to address.

----- Original Message -----

**Comment by smarterclayton** [comment]
I'm in here anyway, I think I'm going to do the bare minimum and clean it up now.  Will appreciate review.

----- Original Message -----

**Comment by smarterclayton** [comment]
Finding some horrible things as I test this... as in, pod updates can change names under the covers if it hasn't been scheduled yet, you can clear PortalIP on a Service update (it *looks* intentional, but seems bad), and we apparently depend on some subset of the pod status info being stored in etcd.

----- Original Message -----

**Comment by derekwaynecarr** [comment]
Can we chat on this tomorrow?  I am currently using a Status on an object to update the status of another in #3796.  I can easily make it that a spec of object A is what is used to update the status object B if we truly intend to block Status on all PUT.  If we go that route, we basically always require a mirror object pattern where spec of one object is status of other.

**Comment by smarterclayton** [comment]
I don't think my initial changes will be as strict as described here.  I think we need to reach closure among authz of updates, proper api behavior, and patterns before we fix this or introduce more status writing.  Let's circle these wagons.

**Comment by smarterclayton** [comment]
#3789 adds a framework for create that allows each type to specify its reset rules on create.  We can now add a similar behavior on update.

**Comment by smarterclayton** [comment]
#4248 is the first bit of allowing PUT /status

**Comment by smarterclayton** [comment]
This is fixed
