### ISSUE TITLE
kubectl only allow top-level namespace

### ISSUE THREAD

**Issue by josselin-c** [GoogleCloudPlatform/kubernetes#3055]
Not sure if it should be allowed or not but I can't switch to sub-namespace with kubectl:

```
[joss-c@~]$ kubectl namespace "dev.team1"
Set current namespace to dev.team1
F1219 11:53:55.471569    9941 namespace.go:57] namespace dev.team1 is not a valid DNS Label
```

**Comment by thockin** [comment]
FWIW, I noticed that validation code already allows DNSSubdomain for
Namespace fields.  I don't see a good reason to disallow it.

**Comment by bgrant0607** [comment]
I think this is infeasible now that we include the namespace in the DNS hierarchy.
