### ISSUE TITLE
Embed doc URLs in swagger documentation

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#3059]
We should embed links to github docs in the API documentation. I think there's a swagger field for that.

/cc @nikhiljindal

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by bgrant0607** [comment]
We also want to translate the links to release-specific links, for releases.

**Comment by bgrant0607** [comment]
See also #10690

**Comment by JanetKuo** [comment]
I'm adding doc url to descriptions of swagger fields. e.g., 

type Container struct {
Image string '.... description:...**; see http://releases.k8s.io/HEAD/docs/Images.md**' 
}
