### ISSUE TITLE
Protect pod network containers from OOM kills

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#3067]
As of now, the pod network container is susceptible to OOM kills due to system memory pressure. By setting the oom_score_adj to be a value lesser than '0', which is the default for docker containers, we can protect the network container. There are a couple of ways to solve this.

In the short term, we will have the kubelet update the oom_score_adj of the network container's 'pause' process after the container gets created by docker. This approach is not robust, but this will help alleviate the current state of the node.

After this, we will investigate either using a docker pre-start hook (cc @vmarmol) or expose a 'oom_score' option in docker, to apply oom scores.

Having memory limits set on all containers will be a better long term solution. But until we get there, the above mentioned solutions will keep the node stable.

cc @dchen1107 @rjnagal @bgrant0607

**Comment by vmarmol** [comment]
Small update as I start on this, we will update the OOM score of the POD container after it starts but before the other containers are started. We ensure the other containers aren't doing any heave work before we're ready and if the POD container dies before we start the other containers, we can catch it. This will be robust enough where we don't need pre-hooks.
