### ISSUE TITLE
PUT fails with an obscure error if resourceVersion is not specified

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3085]
PUT request on a service fails when the body contains 'id' (of itself):
URL: http://localhost:8080/api/v1beta1/services/redis-master1001234
Example body:
 {
      "id": "redis-master1001234",
      "apiVersion": "v1beta1",
      "port": 6379,
      "containerPort":6379
 }

Failure message:
{
  "kind": "Status",
  "creationTimestamp": null,
  "selfLink": "/api/v1beta1/services/redis-master1001234",
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "service \"redis-master1001234\" cannot be updated: 105: Key already exists (/registry/services/specs/default/redis-master1001234) [14]",
  "reason": "Conflict",
  "details": {
    "id": "redis-master1001234",
    "kind": "service"
  },
  "code": 409
}

I would expect that if entity contains its own id (which is easy to know by comparing it to current id and to the url which also contains the id), that it won't fail and the request will succeed.

**Comment by abonas** [comment]
@smarterclayton can you elaborate regarding the use cases when PUT should do create?

**Comment by nikhiljindal** [comment]
I agree with abonas. I dont think that we should interpret a PUT request as a create.
I can send a PR if others agree that the fix here is to return an error saying something like "missing resourceVersion" and not go the create path.

**Comment by bgrant0607** [comment]
@nikhiljindal That makes sense to me. Seems like we should return 404 NotFound. That would be safer in the case of a race with a delete, for example.

@smarterclayton If the client behavior we want is "ensure this object exists", we can implement that logic in the client:
* in the case of forced update, try to update and create if not found
* in the case of a safe/merging update, get the object, then create if not found, update otherwise

Seems workable, at least for "reconcile"-style updates.

Also seems compatible with automatic retries by the client, and with idempotent re-execution after failure.

**Comment by smarterclayton** [comment]
To be truly idempotent, the default http / rest pattern for put is "overwrite".  It's only optional to qualify your put (hence conditional put).

Examples of idempotent create/update usually are smaller and simpler objects where the relationship is "I want this to be this" and making multiple calls is not the desired behavior.  Two examples from Openshift (which we are exposing right now, and hence I would prefer our clients not break needlessly) are updating user info on login and setting the contents of a docker repository tag to a resource representing an image.

The updating user info case is "this user has logged in, here is their data from the identity provider".  That info may change each time we contact the identity provider, but the server accepts the data all the same.  The image tag case is similar, where it does not matter what the tag was prior to the PUT, only the observed order on the server.

**Comment by bgrant0607** [comment]
Ok, thanks for the examples. A brief survey of the web agrees. For example:
http://stackoverflow.com/questions/630453/put-vs-post-in-rest

Name uniquification should only be supported via POST, however, and a PUT create shouldn't specify resourceVersion.

Our api-convenions doc already reflects this behavior:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md

We should update the swagger to match.

**Comment by satnam6502** [comment]
I am starting work on this now. Step 1: produce a repo of the bug.

**Comment by satnam6502** [comment]
I did:
```
curl -X POST -k -u admin:4MGruM7twVVkvbBR https://146.148.81.158/api/v1beta1/services -d "
{
  "id": "redis-master",
  "kind": "Service",
  "apiVersion": "v1beta1",
  "port": 6379,
  "containerPort": 6379,
  "selector": {
    "name": "redis-master"
  },
  "labels": {
    "name": "redis-master"
  }
}"
```

followed by:

```
curl -X PUT -k -u admin:4MGruM7twVVkvbBR https://146.148.81.158/api/v1beta1/services/redis-master -d "
{
  "id": "redis-master",
  "apiVersion": "v1beta1",
  "port": 6379,
  "containerPort": 6502 
}"
{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "service \"redis-master\" is invalid: spec.portalIP: invalid value '': field is immutable",
  "reason": "Invalid",
  "details": {
    "id": "redis-master",
    "kind": "service",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "spec.portalIP: invalid value '': field is immutable",
        "field": "spec.portalIP"
      }
    ]
  },
  "code": 422
}
```

So this appears to be a different error message. @abonas @bgrant0607 : is this message good enough or does it need to be improved? Or do I need a better example to illicit the original error message? Thanks.

**Comment by bgrant0607** [comment]
@satnam6502 Could you do a GET, remove the resourceVersion field, change the containerPort, and try a PUT?

**Comment by satnam6502** [comment]
```
$ curl -X GET -k -u admin:3MGruM7twVVkvbBR https://146.148.82.158/api/v1beta1/services/redis-master
{
  "kind": "Service",
  "id": "redis-master",
  "uid": "3e74eb74-c83d-11e4-940d-42010af01a1f",
  "creationTimestamp": "2015-03-11T22:23:29Z",
  "selfLink": "/api/v1beta1/services/redis-master?namespace=default",
  "resourceVersion": 598,
  "apiVersion": "v1beta1",
  "namespace": "default",
  "port": 6379,
  "protocol": "TCP",
  "labels": {
    "name": "redis-master"
  },
  "selector": {
    "name": "redis-master"
  },
  "containerPort": 6379,
  "portalIP": "10.0.214.136",
  "sessionAffinity": "None"
}

$ curl -X PUT -k -u admin:3MGruM7twVVkvbBR https://146.148.82.158/api/v1beta1/services/redis-master -d "
{
  "kind": "Service",
  "id": "redis-master",
  "uid": "3e74eb74-c83d-11e4-940d-42010af01a1f",
  "creationTimestamp": "2015-03-11T22:23:29Z",
  "selfLink": "/api/v1beta1/services/redis-master?namespace=default",
  "apiVersion": "v1beta1",
  "namespace": "default",
  "port": 6379,
  "protocol": "TCP",
  "labels": {
    "name": "redis-master"
  },
  "selector": {
    "name": "redis-master"
  },
  "containerPort": 6502,
  "portalIP": "10.0.214.136",
  "sessionAffinity": "None"
}"
{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Service): couldn't get version/kind: error converting YAML to JSON: yaml: line 5: found unexpected ':'",
  "reason": "BadRequest",
  "code": 400
}
```

**Comment by bgrant0607** [comment]
@satnam6502 Look at your quoting. You can't embed " in a double-quoted string.

That said, the server shouldn't be converting YAML to JSON...

**Comment by bgrant0607** [comment]
FYI/FWIW, apparently #1004 hasn't yet been implemented.

**Comment by satnam6502** [comment]
Can we Post YAML?

**Comment by bgrant0607** [comment]
@satnam6502 The problem in your example was your quoting.

Yes, YAML can be posted for now, but we should remove that capability, as per #1004..

**Comment by satnam6502** [comment]
```
$ cat put.json
{
  "kind": "Service",
  "id": "redis-master",
  "uid": "3e74eb74-c83d-11e4-940d-42010af01a1f",
  "creationTimestamp": "2015-03-11T22:23:29Z",
  "selfLink": "/api/v1beta1/services/redis-master?namespace=default",
  "apiVersion": "v1beta1",
  "namespace": "default",
  "port": 6379,
  "protocol": "TCP",
  "labels": {
    "name": "redis-master"
  },
  "selector": {
    "name": "redis-master"
  },
  "containerPort": 6502,
  "portalIP": "10.0.214.136",
  "sessionAffinity": "None"
}

$ curl -X PUT -k -u admin:4MGruM7twVVkvbBR https://146.148.83.158/api/v1beta1/services/redis-master --data put.json
{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Service): couldn't get version/kind: error unmarshaling JSON: json: cannot unmarshal string into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" }",
  "reason": "BadRequest",
  "code": 400
}
```

I am on call on Thursday and Friday so I will return to this on Monday.

**Comment by satnam6502** [comment]
Should I PUT with a version number in it work? I tried:
```
$ cat put2.json 
{
  "kind": "Service",
  "id": "redis-master",
  "uid": "3e74eb74-c83d-11e4-940d-42010af01a1f",
  "creationTimestamp": "2015-03-11T22:23:29Z",
  "selfLink": "/api/v1beta1/services/redis-master?namespace=default",
  "resourceVersion": 598,
  "apiVersion": "v1beta1",
  "namespace": "default",
  "port": 6379,
  "protocol": "TCP",
  "labels": {
    "name": "redis-master"
  },
  "selector": {
    "name": "redis-master"
  },
  "containerPort": 6502,
  "portalIP": "10.0.214.136",
  "sessionAffinity": "None"
}
$ curl -X PUT -k -u admin:3MGruM7twVVkvbBR https://146.148.82.158/api/v1beta1/services/redis-master --data put2.json
{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Service): couldn't get version/kind: error unmarshaling JSON: json: cannot unmarshal string into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" }",
  "reason": "BadRequest",
  "code": 400
}
```

**Comment by satnam6502** [comment]
After discussion with @bgrant0607 I propose to do the following the following when I get to this:

* When a PUT occurs without a resource version, perform a GET on the same resource to get the current resource version and then PUT at that version ("push -f").

Is it possible that an interleaving PUT might cause this perform a PUT at a version which is not the most recent? In which case, is it possible to perform an atomic GET and PUT?

**Comment by bgrant0607** [comment]
@satnam6502 What you're essentially asking for is PUT without precondition. Note that in the case of a partial update, we now have a patch implementation in kubectl.

For an example of precondition enforcement in apiserver, see:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L278

**Comment by satnam6502** [comment]
So are you saying that a PUT without version should be translated into a PATCH?

**Comment by bgrant0607** [comment]
Let's discuss IRL.

**Comment by satnam6502** [comment]
How does this relate to PATCH? #4706
Should a PUT without a resource version really be a PATCH?
In which case, rather change a PUT without a resource version into a PUT with the most recent resource version work, perhaps we should just return a more specific error message?
Or should such a PUT just be silently translated into a PATCH?

**Comment by bgrant0607** [comment]
No to all.

Let's just focus on the error message.

I'll take a look at #5690.

**Comment by smarterclayton** [comment]
The message looks better than it originally was - I noticed we weren't setting resourceversion on the conflict error, which we need to do.

**Comment by satnam6502** [comment]
Done via #5690
