### ISSUE TITLE
Clarify resourceVersion description text and refer to api-conventions.md

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3086]
It seems that the resourceVersion field is global per entity type and not per single entity - and it looks confusing.
So looking at a single entity (let's say service with id 'redis') and seeing that its resourceVersion=10, it might imply that this entity was changed 9-10 times (depends on its first resourceVersion)
however it seems that some entities are created with "running" resourceVersion based on another entity's resourceVersion, so first "version" of an entity could be resourceVersion=12.
Doesn't it make more sense that this versioning system will be per entity?

**Comment by bgrant0607** [comment]
This is done.
