### ISSUE TITLE
REST api - error messages should clearly explain the problem, 'invalid value' is too general

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3087]
For example, creating a service with id 'redis-master10012345678999' fails and the returned message contains the following:

"message": "service \"redis-master10012345678999\" is invalid: name: invalid value 'redis-master10012345678999'

'invalid value' is too general, users should understand exactly what is wrong with the input. 
for example -  is it too long? does it contain characters that are not allowed?

**Comment by fgrzadkowski** [comment]
I checked pkg/api/validation/validation.go and it seems there are only two errors that do not have detailed explanation. I'll send a PR to fix this.

**Comment by bgrant0607** [comment]
This is one:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L699

**Comment by fgrzadkowski** [comment]
Thanks for the pointer Brian! I'll send second PR to fix this one.

**Comment by fgrzadkowski** [comment]
Still second PR to be sent.
