### ISSUE TITLE
Cleanup systemd files to follow distribution policy, etc. 

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#3090]
Currently the systemd files reference /etc/kubernetes, given that all the files are enviornment override variables they belong in sysconfig per distribution spec: 

http://fedoraproject.org/wiki/Packaging:Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files 

Also, root group promotion is required in systemd for the kubelet, lest it will be given default priority = to all other services.

**Comment by goltermann** [comment]
Discussion happening on the PR for this.  #3091
