### ISSUE TITLE
Replace -machines with -whitelist

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#3103]
So it's pretty rare to see a CSV machine list for explicit cluster membership.

Typically there are wildcarded whitelists, and blacklists, something akin to: 
-whitelist=\*.mydomain.com
-blacklist=\*.tests.mydomain.com 
where exclusions are applied after inclusions.

Sometimes nodes are even added to a blacklist after some policy, e.g. failed to run 4 times.... 

The purpose of this issue is to focus on replacing -machines with -whitelist.

**Comment by goltermann** [comment]
Dupe of #2303
