### ISSUE TITLE
Err http://http.debian.net jessie-updates/main amd64 Packages

### ISSUE THREAD

**Issue by mdshuai** [GoogleCloudPlatform/kubernetes#3109]
[root@10 kubernetes]# docker build -t kube-build:build-acbfa /root/Documents/kubernetes/_output/images/kube-build:build-acbfa
Sending build context to Docker daemon 1.694 MB
Sending build context to Docker daemon 
Step 0 : FROM kube-build:cross
 ---> d81e49bafbe0
Step 1 : MAINTAINER Joe Beda <jbeda@google.com>
 ---> Using cache
 ---> 6911f2795cd8
Step 2 : ENV GOARM 5
 ---> Using cache
 ---> 32f261f7b24f
Step 3 : ENV GOOS linux
 ---> Using cache
 ---> 991896a5ea0f
Step 4 : ENV GOARCH amd64
 ---> Using cache
 ---> eaa30401c0d1
Step 5 : RUN go get golang.org/x/tools/cmd/cover github.com/tools/godep
 ---> Using cache
 ---> 50c90a19d35c
Step 6 : RUN apt-get update
 ---> Running in 35248796f8a1
Get:1 http://security.debian.org jessie/updates InRelease [84.1 kB]
Ign http://http.debian.net jessie InRelease
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [20 B]
Ign http://http.debian.net jessie-updates InRelease
Get:3 http://http.debian.net jessie Release.gpg [836 B]
Get:4 http://http.debian.net jessie-updates Release.gpg [836 B]
Get:5 http://http.debian.net jessie Release [190 kB]
Ign http://http.debian.net jessie-updates Release
Err http://http.debian.net jessie-updates/main amd64 Packages
  
Get:6 http://http.debian.net jessie-updates/main amd64 Packages [14 B]
Err http://http.debian.net jessie/main amd64 Packages
  
Err http://http.debian.net jessie/main amd64 Packages
  
Err http://http.debian.net jessie/main amd64 Packages
  
Err http://http.debian.net jessie/main amd64 Packages
  
Err http://http.debian.net jessie/main amd64 Packages
  404  Not Found
W: Failed to fetch http://http.debian.net/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Fetched 276 kB in 14s (18.6 kB/s)
2014/12/23 11:14:41 The command [/bin/sh -c apt-get update] returned a non-zero code: 100

**Comment by goltermann** [comment]
Fix is merged in.
