### ISSUE TITLE
Information about pod of a replication controller

### ISSUE THREAD

**Issue by GuillaumeM69** [GoogleCloudPlatform/kubernetes#3111]
I have a question about the basic usage. 
How can I get the list of members of a replication controller. 
The objective is to develop a shared cluster mongo on Kubernetes. 
To initiate a mongos node, i have to do this cmd with the list of mongo conf node in my replication controller (mongo-conf): 
mongos --configdb cfg0.example.net:27019,cfg1.example.net:27019,cfg2.example.net:27019 

What is the right way to get all member of the replication controller mongo-conf from my app pod ?

Thank you for your answer.

**Comment by brendandburns** [comment]
Closing this as completed.  Please open a new issue if you have more questions!

**Comment by bgrant0607** [comment]
See also #260.
