### ISSUE TITLE
Measure Kubernetes API performance

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#3124]
Develop synthetic workload tests to measure basic Kubernetes API performance. Since tests will run on shared resources (e.g. GCE) individual tests should be run N times to weed out any statistical outliers from the performance results.

**Comment by jeremyeder** [comment]
We created some "hello world" type container-pairs using Dockerfiles for app-stacks that are common for our customers.  The hello world pages take an argument/switch that optionally runs a db query.  i.e. http://host/index.php?DB=true.  Then we blow out N-number of these container pairs that use Docker links.  DB=true runs an un-cacheable query to model worst case performance scenario.  Then we fire http workload generators at it.

**Comment by davidopp** [comment]
@saad-ali This has some good ideas for the workload generator.

**Comment by dchen1107** [comment]
@timothysc  @rrati (please cc Jay too) Thanks for looking into Kubernetes performance related issue. You can use this issue to dump the information you guys collected recently.

**Comment by davidopp** [comment]
@wojtek-t @fgrzadkowski

**Comment by dchen1107** [comment]
cc/ @jayunit100

**Comment by timothysc** [comment]
I would like to /metrics and /debug from the api-server as options on some of the e2e tests.

**Comment by davidopp** [comment]
@timothysc if you want us to add new metrics in API server or other components, please reopen #1625 and list them there.

**Comment by davidopp** [comment]
This is very related to #3139 so I'm assigning to @piosz 

/cc @fgrzadkowski @wojtek-t

**Comment by fgrzadkowski** [comment]
We already have some metrics, e.g.:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L59
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L68

And code to verify them in e2e tests:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L780

**Comment by timothysc** [comment]
+1 to @fgrzadkowski , we're already gathering and plotting. 

Are there other metrics that folks are interested in?

**Comment by wojtek-t** [comment]
It seems we are measuring what we are currently interested in.
If we want to measure something else, we can create a dedicated new issue for it.
