### ISSUE TITLE
Create master upgrade tests

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#3135]
We need to get a good handle on upgrade/release policy, versions we're going to keep around, versions we're going to allow upgrade between, etc.

**Comment by mbforbes** [comment]
This is a pretty packed issue. Will decompose when I start working on this. For reference, node upgrade rollup: #6079

**Comment by mbforbes** [comment]
Changing to P1 because I don't believe we can claim upgrades work reliably without a test that exercises them. The other pieces of this issue—a thorough policy for retention, allowance, and testing—are very important, though we can debate their priority when this is broken down.

**Comment by alex-mohr** [comment]
For v1, we only need new binary rollouts via upgrade but not necessarily functionality -- that can land shortly afterwards.

**Comment by mbforbes** [comment]
I've got the binary rollout test plans in #7256—comments (esp. prioritization for 1.0) welcome!

**Comment by roberthbailey** [comment]
This issue is quite vague. @mbforbes - I saw that you created issues for various node upgrade test scenarios; is there an issue for testing master upgrades?

**Comment by mbforbes** [comment]
@roberthbailey No issue for master upgrade tests yet; was leaving that to @zmerlynn given our node/master split, though happy to hash out a draft when I've got a few cycles.

**Comment by roberthbailey** [comment]
Since you have the node upgrade issues sufficiently sussed out elsewhere, I'm going to repurpose this for master upgrade tests and re-assign to @zmerlynn.

**Comment by davidopp** [comment]
@roberthbailey and @zmerlynn will file more detailed issues for this (and mark them as 1.0).

**Comment by roberthbailey** [comment]
Split into #80801 and #8082.
