### ISSUE TITLE
Proposal: Rename `--ns-path` to `--namespace-path`

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#3148]
I think for simplicity and clarity `--ns-path` should be renamed to `--namespace-path`. This will visually and meaningfully sync it up with the existing flag `--namespace`. `ns` jargon and the noise it causes by differing from `--namespace` is a net loss even with the `7` characters saved in the current style.

**Comment by goltermann** [comment]
will be covered by #2861
