### ISSUE TITLE
PublicIP doesn't work with a minion host IP address.

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#3188]
See: https://twitter.com/braydenw/status/550826922179956736 for context.

My bet is that NAT for the same IP from/to doesn't make any sense.  We should just do port forwarding in this case.

**Comment by brendandburns** [comment]
Actually, I just tried this on a GCE cluster and it seemed to work correctly.  Will follow up with the bug reporter.

**Comment by roberthbailey** [comment]
Brendan, did you follow up with Brayden and if so what was the resolution?

**Comment by thockin** [comment]
Closing for lack of response
