### ISSUE TITLE
Container linking inside a pod

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/kubernetes#3189]
I was trying to create a pod with 2 containers, first one being depend upon second one, using docker container linking.
Could anyone suggest some sample json to create a pod with linked containers?

Thanks & Regards,
Sourav

**Comment by olalonde** [comment]
I've been told that Docker Swarm will allow this and that it's not currently possible with Kubernetes but I might be wrong.

**Comment by thockin** [comment]
I am not sure what you are trying to achieve, but containers within a pod
ate implicitly linked, sort of.  They always co-schedule.  They already
share localhost, so no discovery is required.  Can you detail what result
you want here that pods do not provide?

Tim

**Comment by sourav82** [comment]
@thockin, I want to create pods with linked docker containers, so that the dependent container port automatically updated into another (primary) container's environment block. Is there any json tag like "dependencies" in pod.json, so that all the dependent containers always starts before the primary container?

**Comment by derekwaynecarr** [comment]
Have you looked at services?

**Comment by sourav82** [comment]
@derekwaynecarr Thanks for the info. Looks like it might help. Will try with it,

**Comment by thockin** [comment]
Yeah, services sound like what you want.

**Comment by snailshen2014** [comment]
I can understand it.i meat this issue
