### ISSUE TITLE
kubernetes.tar.gz need contrib/dns/skydns-rc.yaml.in

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3190]
The build has been failing for the last several days because of this:

```
Installing cluster DNS
sed: can't read /jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/cluster/../cluster/gce/../../contrib/dns/skydns-rc.yaml.in: No such file or directory
Running: /jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/cluster/../cluster/gce/../../cluster/../cluster/gce/../../platforms/linux/amd64/kubectl create -f -
```

**Comment by zmerlynn** [comment]
@jbeda: Do you have an opinion on this one? @thockin's checkin basically introduced a dep on a random ass file in contrib, making the default for basiclally every provider out there to pull this file and turn on DNS. I actually agree with it, but I'm more inclined to take the file and put it somewhere else that's *not contrib* anymore, since `contrib`, by its name, says "we aren't officially supporting it`, and `kube-up.sh` shouldn't really be pulling from unsupported places.

**Comment by jbeda** [comment]
I'm going to move the file under `cluster`

**Comment by jbeda** [comment]
We do similar stuff for monitoring.  But that stuff happens to be in `examples` which we do package.  Ug.
