### ISSUE TITLE
Kubelet returns container logs from a random event

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#3205]
The kubelet logic for figuring out which docker container to use to show logs from is flawed.  It's currently returning a container uuid to actually look at somewhat randomly (especially when many attempts occur in a row because the pod is restarting).

A short term fix would be to use the most recent attempt.  In the long term, it would be more appropriate for the logs to be across attempts (perhaps delimited by the attempt id) with a more sophisticated set of parameters available for consumers to clarify which logs exactly they need.

**Comment by rjnagal** [comment]
I think the problem here is that kubelet is returning the logs based on container id cached in the PodStatus. If we need to get the most recent logs, we'll have to bypass the cache and get the latest status of containers.

**Comment by rjnagal** [comment]
I just tried it out with the changes in head. I think the recent Pod status changes fixed this logic. I see it returning logs from latest attempt now.

@smarterclayton do you want to give it another try?

**Comment by smarterclayton** [comment]
Pretty sure this was fixed when we last rebased.  Closing.
