### ISSUE TITLE
Kubelet's Container hash should use spew.*printf rather than fmt.

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3210]

**Comment by erictune** [comment]
Is this to follow pointers?

**Comment by saad-ali** [comment]
Context: #3041 
The [Spew library](https://github.com/davecgh/go-spew) follows pointers when printing. Unlike JSON marshaling/unmarshaling it also handles private fields.
```GO
spew.Printf("myVar: %#v", myVar)
```
