### ISSUE TITLE
Publish IP address of service host instead of hostname in container's environment

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/kubernetes#3212]
With Kubernetes services, it is noticed that the service host name is kept inside docker containers' environment block. But as DNS not set up, we can not ping that service host name from inside another docker container (pod). Is there any way to publish service host IP address instead of host name in environment block?

For example, below is from my docker container environment variables -
            "_SERVICE_HOST=animation",
            "_SERVICE_PORT=0",
            "_PORT=tcp://animation:0",
            "_PORT_0_TCP=tcp://animation:0",
            "_PORT_0_TCP_PROTO=tcp",
            "_PORT_0_TCP_PORT=0",
            "_PORT_0_TCP_ADDR=animation",
            "MYSQL_SERVICE_SERVICE_HOST=animation",
            "MYSQL_SERVICE_SERVICE_PORT=8001",
            "MYSQL_SERVICE_PORT=tcp://animation:8001",
            "MYSQL_SERVICE_PORT_8001_TCP=tcp://animation:8001",
            "MYSQL_SERVICE_PORT_8001_TCP_PROTO=tcp",
            "MYSQL_SERVICE_PORT_8001_TCP_PORT=8001",
            "MYSQL_SERVICE_PORT_8001_TCP_ADDR=animation"

 Is there any way to publish IP address of "animation" so that it can be accessed from another container?

**Comment by erictune** [comment]
A couple of things seem odd here.

There should not be env vars with a leading underscore.  That suggests a service is being created with an empty name.  If you `cluster/kubectl.sh get services` do you see a service with an empty name?

The second thing is that typically an IP address, not a hostname.
Are you by any chance creating a minion called "animation"?  You can do this, but you are responsible for making sure that "animation" is resolvable using your own DNS.  If you don't want to set up DNS, then you should name your kubelet with it's IP address.
 
If you have a It seems like a bug to me if you are getting an env

**Comment by erictune** [comment]
For debugging, I'd like to see the output of two commands:
 1.  ```cluster/kubectl.sh get services```
 1.  ```cluster/kubectl.sh get minions```

**Comment by sourav82** [comment]
@erictune Thanks a lot ! It helped me understanding the issue.
Basically, I was running kubernetes from mesos as a framework and mesos slave was advertising its hostname (not the ip) to the mesos master. Kubernetes was getting the mesos slave as a minion from mesos master and hence the minion was identified by its hostname, not the ip.

By starting the mesos slave with hostname as its ip address, now Kubernetes getting the IP address of the minion and working properly.

But the issue of empty service is still there. I executed "kubecfg list minions" and "kubecfg list services" -
root@animation:/EBS/examples# ../bin/kubecfg list minions
Minion identifier
----------
10.227.125.10

root@animation:/EBS/examples# ../bin/kubecfg list services
ID                  Labels              Selector            Port
----------          ----------          ----------          ----------
                                                            0
openldap-app                            name=openldap       8000
mysql-service                           name=mysql          8001
jboss-service                           name=jboss          8002

Here I'm getting an empty service always. Not sure if anything apecific to mesos.

Thanks & Regards,
Sourav

**Comment by erictune** [comment]
That is weird about the empty service.  If it is really bugging you I can walk you through how to fine the offending key in etcd and delete it.  That would probably fix the problem.

**Comment by sourav82** [comment]
Thanks @erictune. After installing latest kubernetes-mesos framework the issue with empty service is no more. Now it is working fine and also able to find kubernetes minions properly.
