### ISSUE TITLE
the hack/local setup build fails

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3214]
After fetching the latest code and doing 'hack/build-go.sh', it fails in the middle with the following error.
Please assist how to workaround/fix it to be able to run a local cluster.
This is on RHEL 6.5

# hack/build-go.sh
+++ Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    plugin/cmd/kube-scheduler
    cmd/kubecfg
    cmd/kubectl
    cmd/kubernetes
    cmd/e2e
    cmd/integration
# github.com/rackspace/gophercloud/pagination
Godeps/_workspace/src/github.com/rackspace/gophercloud/pagination/http.go:16: undefined: gophercloud.Result
# github.com/rackspace/gophercloud/openstack/identity/v3/tokens
Godeps/_workspace/src/github.com/rackspace/gophercloud/openstack/identity/v3/tokens/requests.go:16: undefined: gophercloud.ServiceClient
Godeps/_workspace/src/github.com/rackspace/gophercloud/openstack/identity/v3/tokens/results.go:12: undefined: gophercloud.Result
!!! Error in /home/abonas/kubernetes/kubernetes/hack/lib/golang.sh:303
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 2
Call stack:
  1: /home/abonas/kubernetes/kubernetes/hack/lib/golang.sh:303 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /home/abonas/kubernetes/kubernetes/hack/lib/golang.sh:238
  'kube::golang::build_binaries "$@"' exited with status 1
Call stack:
  1: /home/abonas/kubernetes/kubernetes/hack/lib/golang.sh:238 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1

**Comment by erictune** [comment]
make clean

**Comment by erictune** [comment]
I had the same issue and make clean fixed it.  Please reopen if still stick.

**Comment by abonas** [comment]
@erictune - make clean indeed helped, thanks!
