### ISSUE TITLE
boot2docker fails on bootstrapping cluster

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#3218]
After checking out latest source and merging #2455, I try to bootstrap k8s cluster:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock kubernetes-bootstrap
```

..but after an hour all I see is the recurring log:

I0105 17:52:26.958972      13 kubelet.go:1116] Periodic sync
I0105 17:52:26.959042      13 kubelet.go:991] Desired: []api.BoundPod{api.BoundPod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"podyamlknanuo2n7hsit0llel0774pkvpbr1j", Namespace:"default", SelfLink:"", UID:"podyamlknanuo2n7hsit0llel0774pkvpbr1j", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes/config.source":"file"}}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container{api.Container{Name:"etcd", Image:"coreos/etcd", Command:[]string{"/go/bin/app", "-vv", "-listen-client-urls=http://0.0.0.0:4001"}, WorkingDir:"", Ports:[]api.Port{api.Port{Name:"etcd-port", HostPort:4001, ContainerPort:4001, Protocol:"TCP", HostIP:""}}, Env:[]api.EnvVar(nil), Memory:0, CPU:0, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.LivenessProbe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", Privileged:false, ImagePullPolicy:""}, api.Container{Name:"kube-apiserver", Image:"kubernetes", Command:[]string{"/kubernetes/kube-apiserver", "-v=5", "-address=0.0.0.0", "-etcd_servers=http://127.0.0.1:4001", "-portal_net=10.0.0.0/24"}, WorkingDir:"", Ports:[]api.Port{api.Port{Name:"kube-apiserver-port", HostPort:8080, ContainerPort:8080, Protocol:"TCP", HostIP:""}}, Env:[]api.EnvVar(nil), Memory:0, CPU:0, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.LivenessProbe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", Privileged:false, ImagePullPolicy:"never"}, api.Container{Name:"controller-manager", Image:"kubernetes", Command:[]string{"/kubernetes/kube-controller-manager", "-v=5", "-master=127.0.0.1:8080", "-machines=172.17.0.16"}, WorkingDir:"", Ports:[]api.Port(nil), Env:[]api.EnvVar(nil), Memory:0, CPU:0, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.LivenessProbe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", Privileged:false, ImagePullPolicy:"never"}, api.Container{Name:"proxy", Image:"kubernetes", Command:[]string{"/kubernetes/kube-proxy", "-v=5", "-etcd_servers=http://127.0.0.1:4001"}, WorkingDir:"", Ports:[]api.Port(nil), Env:[]api.EnvVar(nil), Memory:0, CPU:0, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.LivenessProbe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", Privileged:false, ImagePullPolicy:"never"}, api.Container{Name:"scheduler", Image:"kubernetes", Command:[]string{"/kubernetes/kube-scheduler", "-v=5", "-master=127.0.0.1:8080"}, WorkingDir:"", Ports:[]api.Port(nil), Env:[]api.EnvVar(nil), Memory:0, CPU:0, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.LivenessProbe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", Privileged:false, ImagePullPolicy:"never"}}, RestartPolicy:api.RestartPolicy{Always:(*api.RestartPolicyAlways)(nil), OnFailure:(*api.RestartPolicyOnFailure)(nil), Never:(*api.RestartPolicyNever)(nil)}, DNSPolicy:"", NodeSelector:map[string]string(nil), Host:""}}}
I0105 17:52:26.965047      13 docker.go:307] Docker Container: /furious_euclid is not managed by kubelet.
I0105 17:52:26.965150      13 kubelet.go:1027] Skipping deletes, sources aren't ready yet.
I0105 17:52:26.970085      13 docker.go:392] Container inspect result: {ID:5be5785247f5d4d2c1ff0b69561abd6adb179f58d447d398bd84f14eae8e1fdc Created:2015-01-05 17:52:16.363577741 +0000 UTC Path:/kubernetes/kube-proxy Args:[-v=5 -etcd_servers=http://127.0.0.1:4001] Config:0xc20806cb40 State:{Running:false Paused:false OOMKilled:false Pid:0 ExitCode:255 Error: StartedAt:2015-01-05 17:52:16.584428052 +0000 UTC FinishedAt:2015-01-05 17:52:16.774745074 +0000 UTC} Image:84c5746a34f753b7589e9dc38a0493f947a55268f81aaddf473e79fc3d10bbcc NetworkSettings:0xc2081dd2c0 SysInitPath: ResolvConfPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/resolv.conf HostnamePath: HostsPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hosts Name:/k8s_proxy.f3238fce_podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file_podyamlknanuo2n7hsit0llel0774pkvpbr1j_52a1f95b Driver:aufs Volumes:map[/dev/termination-log:/var/lib/kubelet/podyamlknanuo2n7hsit0llel0774pkvpbr1j/proxy/5be5785247f5d4d2c1ff0b69561abd6adb179f58d447d398bd84f14eae8e1fdc] VolumesRW:map[/dev/termination-log:true] HostConfig:0xc20806cdc0}
I0105 17:52:26.972616      13 docker.go:392] Container inspect result: {ID:8b85e687dbd82c544f31aae8757c3f0e3b5280d00af2ede1e9b1116f3fd9760e Created:2015-01-05 17:49:39.536945307 +0000 UTC Path:/kubernetes/kube-scheduler Args:[-v=5 -master=127.0.0.1:8080] Config:0xc20806d180 State:{Running:true Paused:false OOMKilled:false Pid:6505 ExitCode:0 Error: StartedAt:2015-01-05 17:49:40.094359354 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:84c5746a34f753b7589e9dc38a0493f947a55268f81aaddf473e79fc3d10bbcc NetworkSettings:0xc2081dd860 SysInitPath: ResolvConfPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/resolv.conf HostnamePath: HostsPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hosts Name:/k8s_scheduler.18578dfe_podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file_podyamlknanuo2n7hsit0llel0774pkvpbr1j_f1dd14ac Driver:aufs Volumes:map[/dev/termination-log:/var/lib/kubelet/podyamlknanuo2n7hsit0llel0774pkvpbr1j/scheduler/8b85e687dbd82c544f31aae8757c3f0e3b5280d00af2ede1e9b1116f3fd9760e] VolumesRW:map[/dev/termination-log:true] HostConfig:0xc20806d2c0}
I0105 17:52:26.979887      13 docker.go:392] Container inspect result: {ID:95423ace1496c0e27f470867b88e63d38537262ff0645fd82c61de0f6a3b2786 Created:2015-01-05 17:49:38.237335729 +0000 UTC Path:/kubernetes/kube-controller-manager Args:[-v=5 -master=127.0.0.1:8080 -machines=172.17.0.16] Config:0xc20806d680 State:{Running:true Paused:false OOMKilled:false Pid:6479 ExitCode:0 Error: StartedAt:2015-01-05 17:49:38.762029782 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:84c5746a34f753b7589e9dc38a0493f947a55268f81aaddf473e79fc3d10bbcc NetworkSettings:0xc2081ddae0 SysInitPath: ResolvConfPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/resolv.conf HostnamePath: HostsPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hosts Name:/k8s_controller-manager.49f9b7d_podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file_podyamlknanuo2n7hsit0llel0774pkvpbr1j_458e6fbd Driver:aufs Volumes:map[/dev/termination-log:/var/lib/kubelet/podyamlknanuo2n7hsit0llel0774pkvpbr1j/controller-manager/95423ace1496c0e27f470867b88e63d38537262ff0645fd82c61de0f6a3b2786] VolumesRW:map[/dev/termination-log:true] HostConfig:0xc20806d7c0}
I0105 17:52:26.982443      13 docker.go:392] Container inspect result: {ID:e7a2a1cb101c648494f23e3565e18ab276ce7d7c847d693a46ed406a6d7ad84b Created:2015-01-05 17:49:37.542242455 +0000 UTC Path:/kubernetes/kube-apiserver Args:[-v=5 -address=0.0.0.0 -etcd_servers=http://127.0.0.1:4001 -portal_net=10.0.0.0/24] Config:0xc20806db80 State:{Running:true Paused:false OOMKilled:false Pid:6466 ExitCode:0 Error: StartedAt:2015-01-05 17:49:38.072067138 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:84c5746a34f753b7589e9dc38a0493f947a55268f81aaddf473e79fc3d10bbcc NetworkSettings:0xc2081ddd60 SysInitPath: ResolvConfPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/resolv.conf HostnamePath: HostsPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hosts Name:/k8s_kube-apiserver.2910c166_podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file_podyamlknanuo2n7hsit0llel0774pkvpbr1j_e85b011e Driver:aufs Volumes:map[/dev/termination-log:/var/lib/kubelet/podyamlknanuo2n7hsit0llel0774pkvpbr1j/kube-apiserver/e7a2a1cb101c648494f23e3565e18ab276ce7d7c847d693a46ed406a6d7ad84b] VolumesRW:map[/dev/termination-log:true] HostConfig:0xc20806dcc0}
I0105 17:52:26.984081      13 docker.go:392] Container inspect result: {ID:c323ed2cb3786bd2641ad4be4e724f7544ad643600ec2d63d4044d32acd07d14 Created:2015-01-05 17:49:37.099220576 +0000 UTC Path:/etcd Args:[/go/bin/app -vv -listen-client-urls=http://0.0.0.0:4001] Config:0xc2081c8140 State:{Running:true Paused:false OOMKilled:false Pid:6453 ExitCode:0 Error: StartedAt:2015-01-05 17:49:37.413370531 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:649a8540db5e75c4f097f3202cf4dfa3bb2d54ffc8f87bcc2ca8f9fc8cf0677d NetworkSettings:0xc20819c000 SysInitPath: ResolvConfPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/resolv.conf HostnamePath: HostsPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hosts Name:/k8s_etcd.c0b6a63c_podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file_podyamlknanuo2n7hsit0llel0774pkvpbr1j_fc27b045 Driver:aufs Volumes:map[/dev/termination-log:/var/lib/kubelet/podyamlknanuo2n7hsit0llel0774pkvpbr1j/etcd/c323ed2cb3786bd2641ad4be4e724f7544ad643600ec2d63d4044d32acd07d14] VolumesRW:map[/dev/termination-log:true] HostConfig:0xc2081c8280}
I0105 17:52:26.986045      13 docker.go:392] Container inspect result: {ID:18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0 Created:2015-01-05 17:49:36.251086656 +0000 UTC Path:/pause Args:[] Config:0xc2081c8640 State:{Running:true Paused:false OOMKilled:false Pid:6441 ExitCode:0 Error: StartedAt:2015-01-05 17:49:36.746499223 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27 NetworkSettings:0xc20819c280 SysInitPath: ResolvConfPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/resolv.conf HostnamePath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hostname HostsPath:/mnt/sda1/var/lib/docker/containers/18e37dc80b87f452462d475ade57e714dee24bd4dee3248e7576a2b0ade344b0/hosts Name:/k8s_net.90feb24a_podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file_podyamlknanuo2n7hsit0llel0774pkvpbr1j_37f48b71 Driver:aufs Volumes:map[] VolumesRW:map[] HostConfig:0xc2081c8780}
I0105 17:52:26.986158      13 kubelet.go:833] pod podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file container etcd exists as c323ed2cb3786bd2641ad4be4e724f7544ad643600ec2d63d4044d32acd07d14
I0105 17:52:26.986182      13 kubelet.go:833] pod podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file container kube-apiserver exists as e7a2a1cb101c648494f23e3565e18ab276ce7d7c847d693a46ed406a6d7ad84b
I0105 17:52:26.986199      13 kubelet.go:833] pod podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file container controller-manager exists as 95423ace1496c0e27f470867b88e63d38537262ff0645fd82c61de0f6a3b2786
I0105 17:52:27.010098      13 kubelet.go:890] Container with name podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file--podyamlknanuo2n7hsit0llel0774pkvpbr1j--proxy doesn't exist, creating api.Container{Name:"proxy", Image:"kubernetes", Command:[]string{"/kubernetes/kube-proxy", "-v=5", "-etcd_servers=http://127.0.0.1:4001"}, WorkingDir:"", Ports:[]api.Port(nil), Env:[]api.EnvVar(nil), Memory:0, CPU:0, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.LivenessProbe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", Privileged:false, ImagePullPolicy:"never"}
E0105 17:52:27.010277      13 kubelet.go:893] Couldn't make a ref to pod podyamlknanuo2n7hsit0llel0774pkvpbr1j, container proxy: 'selfLink was empty, can't make reference'
E0105 17:52:27.014747      13 kubelet.go:525] Couldn't make a ref to pod podyamlknanuo2n7hsit0llel0774pkvpbr1j, container proxy: 'selfLink was empty, can't make reference'
I0105 17:52:27.223278      13 kubelet.go:833] pod podyamlknanuo2n7hsit0llel0774pkvpbr1j.default.file container scheduler exists as 8b85e687dbd82c544f31aae8757c3f0e3b5280d00af2ede1e9b1116f3fd9760e
I0105 17:52:30.890922      13 server.go:324] GET /healthz: (9.147us) 200

**Comment by pires** [comment]
I can't stop the process with ^C or ^Z, as well.

**Comment by roberthbailey** [comment]
Paulo, is this still an issue or can we close it (since it's a month old and there have been no comments)?

**Comment by pires** [comment]
Never got back to it. So yeah, go ahead.
