### ISSUE TITLE
Pod - Pending - Multinode CoreOS GCE

### ISSUE THREAD

**Issue by georgepoenaru** [GoogleCloudPlatform/kubernetes#3222]
I tried to deploy a pod over a multinode CoreOS cluster in GCE but it remain in pending with the last message saying that the pod was assigne to the minion IP. 

kubectl get events didn't said nothing new, same message, the pod was assigned to the minion.

I loged into minion to try to debug there and I found that flee service is active but a  "$ fleetctl list-unit-files" returned me: 

"Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused"

I checked node.yaml and the etcd env was correct: 
 Environment="FLEET_ETCD_SERVERS=http://10.240.186.105:4001"

However "$ fleetctl list-unit-files" worked fine on the master, only on minion gave me the error. Does kubernetes need to use fleet client on minions or is it used only by the master ?

**Comment by erictune** [comment]
This seems to be specific to a CoreOS setup.  I wonder if @kelseyhightower has any idea about this.

**Comment by kelseyhightower** [comment]
@georgepoenaru What guide did you follow to get things setup?

**Comment by georgepoenaru** [comment]
I used the multinode guis from the kubernetes repo (however I used a newer coreos image name from gce list)

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md

**Comment by georgepoenaru** [comment]
However, I forgot to mention that I also used the last build of kubernetes (7.0) in master.yaml and node.yaml provision files. However right now I perform a test with the same coreos and kubernetes versions that are specified in the guide and it still not working.

**Comment by brendandburns** [comment]
I'm closing this as obsolete.  If you are still having the issue, please re-open.
