### ISSUE TITLE
Validation allows a pod with no containers - is this intended?

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3249]
It is not commented as specifically intended - we should decide if it is actually supported and meaningful, or whether we should reject it.

**Comment by bgrant0607** [comment]
We should support pods with no containers.  Pods contain volumes and will reserve resources in the future. I could easily imagine pods without containers being useful as a preparatory, intermediate, or cleanup state, and we shouldn't force users to run dummy containers.
