### ISSUE TITLE
Got error status on WatchServices channel

### ISSUE THREAD

**Issue by fishyumiao** [GoogleCloudPlatform/kubernetes#3258]
I set up 3 coreos machines cluster locally.
cloud-config.yml : https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/coreos/cloud-configs

abcuser@cynode001 ~ $ fleetctl list-machines
MACHINE         IP              METADATA
09749798...     192.168.1.11    role=cykube
9a44a5ed...     192.168.1.13    role=cykube
d3e8e2b2...     192.168.1.15    role=cykube

abcuser@cynode001 ~ $ kubectl get minions
NAME                LABELS
192.168.1.11        <none>
192.168.1.13        <none>
192.168.1.15        <none>

It looks like everything works fine. But there are some error logs in the tools. 
Containers cannot commumicate with each other very well.
After restart the service on all of my minions : sudo systemctl restart kube-proxy skydns. The tools works fine about several minites , after that the error logs appear again!!!

fleet error logs:
Jan 07 01:39:45 cynode001 fleetd[16314]: ERROR event.go:91: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 07 01:41:29 cynode001 fleetd[16314]: ERROR event.go:91: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input

kube-proxy error logs:
Jan 07 01:59:50 cynode001 kube-proxy[11118]: W0107 01:59:50.981090   11118 api.go:188] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/...
Jan 07 01:59:56 cynode001 kube-proxy[11118]: W0107 01:59:56.813594   11118 api.go:124] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v...

kube-controller-manager error logs:
Jan 07 02:03:00 cynode001 kube-controller-manager[16362]: E0107 02:03:00.937969   16362 replication_controller.go:128] unexpected object: &api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"/api/v1beta1/replicationControllers", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [117140/9806]) [118139]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}

kube-scheduler error logs: 
Jan 07 01:56:15 cynode001 kube-scheduler[16374]: E0107 01:56:15.735474   16374 reflector.go:114] watch of *api.Pod ended with error: 401: The event in requested index is outdated and cleared (the requested history has been cleared [116857/116828]) [117856]
Jan 07 01:58:25 cynode001 kube-scheduler[16374]: E0107 01:58:25.008348   16374 reflector.go:114] watch of *api.Pod ended with error: unexpected end of JSON input
Jan 07 02:01:16 cynode001 kube-scheduler[16374]: E0107 02:01:16.737465   16374 reflector.go:114] watch of *api.Pod ended with error: unexpected end of JSON input

skydns error logs:
Jan 07 02:05:13 cynode001 skydns[11216]: W0107 02:05:13.037896   11216 api.go:124] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name: Namespace: ...
Jan 07 02:05:16 cynode001 skydns[11216]: W0107 02:05:16.732176   11216 api.go:188] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name: Namespace:...

**Comment by lavalamp** [comment]
This should be improved at head: #3240 was merged a few hours ago.

**Comment by goltermann** [comment]
Please reopen if there are still issues.
