### ISSUE TITLE
Accessing services using IP and port - Kubernetes on Mesos

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/kubernetes#3266]
I had 2 minions - 10.227.125.10 & 10.227.125.3 and scheduled pods containing one docker container of a web app on these 2 minions. I kept 3 replicas of the pod. The container exposes port 80 and I mapped container port 80 to port 31020 on host. I created one service for these pods which binds to port 8000. I'm trying to access 10.227.125.10:8000 from IE.

Problem is, as the container port 80 mapped to host port 31020, there will be port conflict while trying to schedule 3rd replica of the pod in any one of those 2 minions. Could you please let me know any workaround here?

If I do not specify any host port in the pod template, then I'm not able to access the container application from IE. Do I always need to map container port to host port in podTemplate?

I read in the document, there is something called service IP. How can I set up the service IP and make it accessible from outside (on intranet)?

**Comment by thockin** [comment]
You almost never want HostPort for the exact reason you discovered.

Instead, you want to set up a Service that selects all of your pods.  Exposing services outside of a kubernetes cluster is a bit of a sore spot right now, but the easiest way is to set the Service.PublicIPs field (an array) to an IP that you can arrange to be routed some machine in your cluster.

For example, if your minion has a public IP, use that.  What should happen is that any in-bound traffic to a minion on the service port will get captured and redirected to the kube-proxy.

**Comment by thockin** [comment]
Closed in favor of #3267
