### ISSUE TITLE
Service takes host port (instead of container ports) to group pods - Kubernetes on Mesos

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/kubernetes#3267]
My service looks like below -

```json
{
"apiVersion": "v1beta1",
"kind": "Service",
"id": "app",
"selector": {
"name": "app"
},
"containerPort": 80,
"port": 8585,
}
```

I've pods created with below replication controller config -

```json
{
"id": "app",
"apiVersion": "v1beta1",
"kind": "ReplicationController",
"desiredState": {
"replicas": 3,
"replicaSelector": {"name": "app"},
"podTemplate": {
"desiredState": {
"manifest": {
"version": "v1beta1",
"id": "app",
"containers": [
{
"name": "app",
"image": "10.227.125.10:5000/app-kubernetes",
"ports": [{"containerPort": 80, "hostPort": 31020}]
}
]
}
},
"labels": {"name": "app"}
}
},
"labels": {"name": "app"}
}
```
After 3 pods created by this replication controller, I start the service. But not able to access the application using http://10.227.125.10:8585/ (10.227.125.10 is the IP of the system where I created the service).

But, if I change the service to use port 31020 as container port, then I am able to use the service from IE in port 8585. As per documentation, "containerPort" of service should have the port of the container inside the pods. In this example, container port inside pod is 80 and host port is 31020. But the service is behaving differently. Need your help here what wrong I am doing in setting it up.

**Comment by thockin** [comment]
You're missing the part where Services abstract the destination.  By hitting the 31020 port directly you are hitting one backend, and not balancing them.  The Service port is on a virtual IP, by default, which is only accessible in the cluster.  As per #3266, you need to set give your service a "public" IP.

First, get rid of HostPort.
Second, set Service.PublicIPs to [ "10.227.125.10" ].

From the other bug: 

You almost never want HostPort for the exact reason you discovered.

Instead, you want to set up a Service that selects all of your pods. Exposing services outside of a kubernetes cluster is a bit of a sore spot right now, but the easiest way is to set the Service.PublicIPs field (an array) to an IP that you can arrange to be routed some machine in your cluster.

For example, if your minion has a public IP, use that. What should happen is that any in-bound traffic to a minion on the service port will get captured and redirected to the kube-proxy.

**Comment by sourav82** [comment]
@thockin Thank you for explaining in great detail. Sorry to inform you I could not do the first part, i.e, "get rid of HostPort".
I created replication controller where I did not mention any "hostPort" and created a service where I used the "containerPort". I used named port. Below are the configs -

Service -
{
  "apiVersion": "v1beta1",
  "kind": "Service",
  "id": "app",
  "selector": {
    "name": "app"
  },
  "containerPort": "app",
  "port": 8585,
  "PublicIPs": [{"10.227.125.10"}]
}

ReplicationController -
{
  "id": "app",
  "apiVersion": "v1beta1",
  "kind": "ReplicationController",
  "desiredState": {
    "replicas": 2,
    "replicaSelector": {"name": "app"},
    "podTemplate": {
      "desiredState": {
        "manifest": {
          "version": "v1beta1",
          "id": "app",
          "containers": [
            {
              "name": "app",
              "image": "10.227.125.10:5000/app-kubernetes",
              "ports": [{"name": "app", "containerPort": 80}]
             }
          ]
        }
      },
      "labels": {"name": "app"}
    }
  },
  "labels": {"name": "app"}
}
But, if I do not put the "hostPort" part in replication config, I'm not able to access the application. 
Is there any way so that kubernetes will allocate any available host port if "hostPort" not specified?
I would like to have something like what docker does with "docker run -P <imageName> <command>" which allocates all the exposed port from the container to any available port in some port range on the host. If kubernetes could handle this, then there will be almost no port conflicts. Replicas of same container could be started on same host (with different host port allocated).

One point - I'm using kubernetes with mesos, kubernetes-mesos framework. Not sure though if there are any differences between kubernetes-mesos and just kubernetes. I posted the same question on kubernetes-mesos channel.  I got reply that dynamic host port is not yet supported - https://github.com/mesosphere/kubernetes-mesos/issues/115

**Comment by thockin** [comment]
> "PublicIPs": [{"10.227.125.10"}]

This should be an array or strings, not struct.  ["10.227.125.10"].
Sadly, go's JSON parser does not complain about this or even make it
possible to detect.  If you want to verify, read back your services as
JSON after you create it.

cluster/kubectl.sh get -o json service [name]

> But, if I do not put the "hostPort" part in replication config, I'm not able to access the application.
> Is there any way so that kubernetes will allocate any available host port if "hostPort" not specified?
> I would like to have something like what docker does with "docker run -P " which allocates all the exposed port from the container to any available port in some port range on the host. If kubernetes could handle this, then there will be almost no port conflicts. Replicas of same container could be started on same host (with different host port allocated).

This is NOT what you want. HostPorts map 1:1 with pods.  If you have a
service with more than one pod backing it, your host port is not going
to work correctly.  Additionally, randomized HostPorts are chosen by
docker, so would need to be plumbed back to the apiserver to be
reported and discovered.  And they can change if your container
crashes.  It is a very complex way to do things - there is a reason we
chose ip-per-pod as a fundamental principle :)

**Comment by sourav82** [comment]
Thanks for correcting me. Great help!
