### ISSUE TITLE
kubectl.sh does not seem to report error for bad arguments

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3300]
`kubectl` seems to fail silently.

```
$ cluster/kubectl.sh fodsfgdogdl
$
```

**Comment by wojtek-t** [comment]
I took a quick look into it. For me the problem seems to be this line:
detect-master &> /dev/null
Changing this to
detect-master > /dev/null
(which btw is the line in kubecfg) makes it fail with some error.

I will make a PR for it.

**Comment by bgrant0607** [comment]
Be careful that this doesn't break any of our many scripts that use kubectl.sh (e2e, turn-up scripts, etc.).

**Comment by wojtek-t** [comment]
Sure - I hope I checked everything (all the tests are passing).

**Comment by wojtek-t** [comment]
This PR seems to fix the problem - it's no longer silently failing.
