### ISSUE TITLE
container's failed to communicate from one host(minion) to other host (minion)

### ISSUE THREAD

**Issue by prateekarora151083** [GoogleCloudPlatform/kubernetes#3304]
I have installed kubernetes ( v0.6.2) on Ubuntu ( multi host) .

My Setup:
Master 10.23.48.79
Minion1 10.23.48.76
Minion2 10.23.48.77

My payment client container ("host": "10.23.48.76","podIP": "172.17.0.4" )try to communicate with payment server container ("host": "10.23.48.77","podIP": "192.168.5.3")

but getting following error:

proxier.go:112] Accepted TCP connection from 172.17.0.4:39803 to 172.17.42.1:56649
I0107 15:01:34.758474    3380 proxier.go:87] Mapped service "payment-server" to endpoint 192.168.5.3:8080
E0107 15:01:34.777217    3380 proxier.go:92] Dial failed: dial tcp 192.168.5.3:8080: no route to host

steps --

First launch container on Minion 1

{
  "id": "payment-server",
  "kind": "Pod",
  "apiVersion": "v1beta1",
        "desiredState": {
           "manifest": {
           "version": "v1beta1",
           "id": "payment-server",
           "containers": [{
              "name": "payment-server",
              "image": "payment_server_img",
              "ports": [
                {"containerPort": 8080,"hostPort": 8080},
                {"containerPort": 22,"hostPort": 4555}
              ]
            }]
          }
  },
  "labels": {
    "name": "payment-server"
  }
}

Output:
{
      "id": "payment-server",
      "uid": "edf8b714-96c0-11e4-a72d-001517f80c24",
      "creationTimestamp": "2015-01-07T15:00:09-08:00",
      "selfLink": "/api/v1beta1/pods/payment-server",
      "resourceVersion": 113368,
      "namespace": "default",
      "labels": {
        "name": "payment-server"
      },
      "desiredState": {
        "manifest": {
          "version": "v1beta2",
          "id": "",
          "volumes": null,
          "containers": [
            {
              "name": "payment-server",
              "image": "payment_server_img",
              "ports": [
                {
                  "hostPort": 8080,
                  "containerPort": 8080,
                  "protocol": "TCP"
                },
                {
                  "hostPort": 4555,
                  "containerPort": 22,
                  "protocol": "TCP"
                }
              ],
              "imagePullPolicy": ""
            }
          ],
          "restartPolicy": {
            "always": {}
          }
        }
      },
      "currentState": {
        "manifest": {
          "version": "",
          "id": "",
          "volumes": null,
          "containers": null,
          "restartPolicy": {}
        },
        "status": "Running",
        "host": "10.23.48.77",
        "podIP": "192.168.5.3",
        "info": {
          "net": {
            "state": {
              "running": {
                "startedAt": "2015-01-07T22:58:11.76921937Z"
              }
            },
            "restartCount": 0,
            "podIP": "192.168.5.3",
            "image": "kubernetes/pause:latest"
          },
          "payment-server": {
            "state": {
              "running": {
                "startedAt": "2015-01-07T22:58:12.007906102Z"
              }
            },
            "restartCount": 0,
            "image": "payment_server_img"
          }
        }
      }

Then  launch service  so other container can communicate with this pod.

{
  "id": "payment-server",
  "kind": "Service",
  "apiVersion": "v1beta1",
  "port": 8080,
  "containerPort": 8080,
  "selector": {
    "name": "payment-server"
  },
  "labels": {
    "name": "payment-server"
  }
}
Output :
{
      "id": "payment-server",
      "uid": "f4f69db0-96c0-11e4-a72d-001517f80c24",
      "creationTimestamp": "2015-01-07T15:00:21-08:00",
      "selfLink": "/api/v1beta1/services/payment-server",
      "resourceVersion": 113371,
      "namespace": "default",
      "port": 8080,
      "protocol": "TCP",
      "labels": {
        "name": "payment-server"
      },
      "selector": {
        "name": "payment-server"
      },
      "containerPort": 8080,
      "portalIP": "11.1.1.245"
    },

Endpoint:
  {
      "id": "payment-server",
      "uid": "fa43af76-96c0-11e4-a72d-001517f80c24",
      "creationTimestamp": "2015-01-07T15:00:30-08:00",
      "selfLink": "/api/v1beta1/endpoints/payment-server",
      "resourceVersion": 113372,
      "namespace": "default",
      "endpoints": [
        "192.168.5.3:8080"
      ]
    },

c. launch container on minion-2

{
  "id": "paymentclient1",
  "kind": "Pod",
  "apiVersion": "v1beta1",
        "desiredState": {
           "manifest": {
           "version": "v1beta1",
           "id": "paymentclient1",
           "containers": [{
              "name": "paymentclient1",
              "image": "payment_client",
              "ports": [{
                "containerPort": 22,
                "hostPort": 4528
                }]
            }]
          }
  },
  "labels": {
    "name": "paymentclient1",
    "uses": "payment-server",
  }
}

Output:
    {
      "id": "paymentclient1",
      "uid": "7620b329-96c1-11e4-a72d-001517f80c24",
      "creationTimestamp": "2015-01-07T15:03:58-08:00",
      "selfLink": "/api/v1beta1/pods/paymentclient1",
      "resourceVersion": 113378,
      "namespace": "default",
      "labels": {
        "name": "paymentclient1",
        "uses": "payment-server"
      },
      "desiredState": {
        "manifest": {
          "version": "v1beta2",
          "id": "",
          "volumes": null,
          "containers": [
            {
              "name": "paymentclient1",
              "image": "payment_client",
              "ports": [
                {
                  "hostPort": 4528,
                  "containerPort": 22,
                  "protocol": "TCP"
                }
              ],
              "imagePullPolicy": ""
            }
          ],
          "restartPolicy": {
            "always": {}
          }
        }
      },
      "currentState": {
        "manifest": {
          "version": "",
          "id": "",
          "volumes": null,
          "containers": null,
          "restartPolicy": {}
        },
        "status": "Running",
        "host": "10.23.48.76",
        "podIP": "172.17.0.4",
        "info": {
          "net": {
            "state": {
              "running": {
                "startedAt": "2015-01-07T23:01:34.484184568Z"
              }
            },
            "restartCount": 0,
            "podIP": "172.17.0.4",
            "image": "kubernetes/pause:latest"
          },
          "paymentclient1": {
            "state": {
              "running": {
                "startedAt": "2015-01-07T23:01:34.742966778Z"
              }
            },
            "restartCount": 0,
            "image": "payment_client"
          }
        }
      }

--------------------------------------------------------------------------------------------------------
Master configuration: 10.23.48.79

etcd : 
ETCD_OPTS="-listen-client-urls=http://10.23.48.79:4001"

kube-apiserver:
KUBE_APISERVER_OPTS="--address=10.23.48.79 \
--port=8080 \
--etcd_servers=http://10.23.48.79:4001 \
--log_dir=/tmp/ \
--v=3 \
--logtostderr=false \
--portal_net=11.1.1.0/24"

kube-controller-manager:
KUBE_CONTROLLER_MANAGER_OPTS="--master=10.23.48.79:8080 \
--machines=10.23.48.76,10.23.48.77 \
--log_dir=/tmp/ \
--v=3 \
--logtostderr=false"

kube-scheduler:
KUBE_SCHEDULER_OPTS="--logtostderr=false \
--log_dir=/tmp/ \
--v=2 \
--master=10.23.48.79:8080"

sudo service etcd restart
sudo service kube-apiserver restart
sudo service kube-controller-manager restart
sudo service kube-scheduler restart

---------------------------------------------------------------------------------------------------------
Slave configuration: 10.23.48.76

etcd -
ETCD_OPTS="-listen-client-urls=http://10.23.48.76:4001"

kubelet:
KUBELET_OPTS="--address=10.23.48.76 \
--port=10250 \
--hostname_override=10.23.48.76 \
--etcd_servers=http://10.23.48.79:4001 \
--log_dir=/tmp/ \
--v=3 \
--logtostderr=false"

kube-proxy:

KUBE_PROXY_OPTS="--etcd_servers=http://10.23.48.79:4001 \
--log_dir=/tmp/ \
--v=3 \
--logtostderr=false"

sudo service etcd restart
sudo service kubelet restart
sudo service kube-proxy restart

--------------------------------------------------------------------------------------------------------------

Slave configuration: 10.23.48.77
etcd -
ETCD_OPTS="-listen-client-urls=http://10.23.48.77:4001"

kubelet:
KUBELET_OPTS="--address=10.23.48.77 \
--port=10250 \
--hostname_override=10.23.48.77 \
--etcd_servers=http://10.23.48.79:4001 \
--log_dir=/tmp/ \
--v=3 \
--logtostderr=false"

kube-proxy:

KUBE_PROXY_OPTS="--etcd_servers=http://10.23.48.79:4001 \
--log_dir=/tmp/ \
--v=3 \
--logtostderr=false"

sudo service etcd restart
sudo service kubelet restart
sudo service kube-proxy restart

**Comment by thockin** [comment]
I think there is a setup problem:

On Wed, Jan 7, 2015 at 5:16 PM, prateekarora151083
<notifications@github.com> wrote:
>
> I have installed kubernetes ( v0.6.2) on Ubuntu ( multi host) .
>
> My Setup:
> Master 10.23.48.79
> Minion1 10.23.48.76
> Minion2 10.23.48.77
>
> My payment client container ("host": "10.23.48.76","podIP": "172.17.0.4" )try to communicate with payment server container ("host": "10.23.48.77","podIP": "192.168.5.3")

One pod is in 172... and one is in 192...  I'd be surprised if you had
your network set up like that on purpose.

It is a basic requirement that containers be able to reach each other
on the network.  To start, have a look at your docker0 (or whatever
the docker bridge is called on your minions.

**Comment by prateekarora151083** [comment]
Thanks thockin
you said "It is a basic requirement that containers be able to reach each other
on the network.  To start, have a look at your docker0 (or whatever
the docker bridge is called on your minions."

how docker container on different host reach to each other because they have private ip ?
As per my understanding kubernetes service will use as a bridge between containers thats why i am using kubernetes service .

**Comment by thockin** [comment]
Your understanding is a bit off.  Containers must be able to reach each
other.  There are a number of ways to achieve this - simple L2 networking,
GCE routing, overlays like OVS or flannel.  Services abstract sets of pods
so that clients of a pod do not need to know that pod's IP (since the IP
can move around).

On Wed, Jan 7, 2015 at 8:30 PM, prateekarora151083 <notifications@github.com

**Comment by prateekarora151083** [comment]
i have used flannel and now  container communicate with each other.  thanks thockin
