### ISSUE TITLE
API: ResourceName string values do not follow the "BumpyCaps" style

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3307]
I might buy an exception for these, as per resources.md, but I wanted to raise it.

**Comment by lavalamp** [comment]
Yeah, we can fix in v1beta3 if desired.

**Comment by thockin** [comment]
The resources.md file would need to be updated

**Comment by thockin** [comment]
@vishh since you're touching resource names.

**Comment by bgrant0607** [comment]
The resource strings currently following the same rules as labels.  That kind of makes sense, because they look similar to label selectors, which are used for node constraints.

**Comment by thockin** [comment]
agree,meant to close this
