### ISSUE TITLE
API: PullPolicy string values have "Pull" prefix, but no other string constants do that

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3308]
PodPhase: Pending, Running, etc

Protocol: TCP, UDP

DNSPolicy: ClusterFirst, Default

AffinityType: ClientIP, None

Even RestartPolicy { Always, Never }

PullPolicy is the lone odd man out.

**Comment by brendandburns** [comment]
I actually don't think this is bug.  In the Pull case it's descriptive

"PullIfNotPresent" is easier to understand than "IfNotPresent"

I don't think AffinityClientIP is easier to understand than ClientIP.

I could see the argument for converting to RestartAlways, RestartNever

**Comment by thockin** [comment]
RestartPolicy: { Always: {} } is pretty clear.

PullPolicy: IfNotPresent is pretty clear to me.

It's a minor point, but I thought worth filing to discuss a bit.

**Comment by lavalamp** [comment]
I vote with @thockin but maybe we've just both been infected by the go meme of omitting redundant parts of names...
