### ISSUE TITLE
The json from apiserver's route /swaggerapi/version/ and /swaggerapi/api nickname in it.

### ISSUE THREAD

**Issue by mingfang** [GoogleCloudPlatform/kubernetes#3310]
This Swagger-UI requires nicknames for all operations.
Otherwise it will break with the error "SwaggerOperations must have a nickname."

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/3298 fixes this.

**Comment by goltermann** [comment]
#3298 is merged
