### ISSUE TITLE
Salt, Hack, Net-Tools?

### ISSUE THREAD

**Issue by AshleyAitken** [GoogleCloudPlatform/kubernetes#3311]
I was running through this (on MacOSX), and got the cluster working fine but had two issues:

1. I don't have salt - is that needed on the user client?  Not really clear...

2. I don't have the hack directory for e2e testing - where is that?

3. I didn't know how to install net-tools but it seemed to all work ok.

Thanks for any assistance.

Cheers,
Ashley.

**Comment by brendandburns** [comment]
Ashley,
1) Salt isn't necessary on the client side

2) the hack directory is only present in the github repo/source release.
Its only necessary for development. If you want to do development, I'd
recommend using the git repo rather than a binary release.

3) net-tools should likewise be unnecessary unless you are running locally
on your machine via vagrant or the like.

Best
Brendan

**Comment by AshleyAitken** [comment]
Brendan,

Thanks for your post.

On 8 Jan 2015, at 3:04 pm, Brendan Burns <notifications@github.com> wrote:

> 1) Salt isn't necessary on the client side 

Ok, it’s just the “Get Started” guide seems to suggest it is - it asks us to use it etc.

No problem though, I could just ssh to the minion and do the command there.

> 2) the hack directory is only present in the github repo/source release. 
> Its only necessary for development. If you want to do development, I'd 
> recommend using the git repo rather than a binary release. 

Ok, thanks.  Not doing development.

> 3) net-tools should likewise be unnecessary unless you are running locally 
> on your machine via vagrant or the like. 

Now I was running locally on my machine using Vagrant, but it seemed to work.

I am on MacOSX.  Would it be installed already etc?

Thanks,
Ashley.


> 
> Best 
> Brendan 
> On Jan 7, 2015 10:38 PM, "Ashley Aitken" <notifications@github.com> wrote: 
> 
> > I was running through this (on MacOSX), and got the cluster working fine 
> > but had two issues: 
> > 
> > 1. 
> > 
> > I don't have salt - is that needed on the user client? Not really 
> > clear... 
> > 2. 
> > 
> > I don't have the hack directory for e2e testing - where is that? 
> > 3. 
> > 
> > I didn't know how to install net-tools but it seemed to all work ok. 
> > 
> > Thanks for any assistance. 
> > 
> > Cheers, 
> > Ashley. 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/GoogleCloudPlatform/kubernetes/issues/3311>. 
> >
> —
> Reply to this email directly or view it on GitHub.
> 

--
Dr Ashley Aitken - Principal
Running Code Productions
ashley@runningcode.com.au
http://www.runningcode.com.au
LinkedIn/Twitter/Skype: AshleyAitken
Perth, Western Australia (GMT + 8)
Mb (04) 1226-8159 (Preferred)
Ph (08)  9368-5505

**Comment by goltermann** [comment]
Should fix this in documentation.

**Comment by fabioy** [comment]
Updated Vagrant docs via PR #5077 to help Mac OS X users.
