### ISSUE TITLE
Avoiding accidental Elasticsearch cluster formations in same namespace or cluster

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3317]
Fluentd logging is being changed to refer to Elasticsearch with DNS (`elasticsearch.default`) and there is also an instance of Elasticsearch that is used for monitoring (but this currently does not use DNS). If we run Elasticsearch instances in the same namespace then I think they will 'interfere' with each other i.e. by default form a cluster.

We should be aware of this. I think we should either decide to use shared Elasticsearch clusters for things like logging and monitoring and put them in an appropriate namespace [I am not sure if this is what we really want to do] or we should be careful to put different distinct Elasticsearch clusters into different namespaces. So, for example, instead of `elasticsearch.default` we should perhaps use `elasticsearch.logging` and likewise for monitoring if there is every a need to move it over to DNS e.g. `elasticsearch.monitoring`. 

@vmarmol @vishh

**Comment by vishh** [comment]
I am in the process of getting rid of the elasticsearch dependency for
monitoring.

**Comment by satnam6502** [comment]
OK, I'll close this issue for now. But at some point we might like to think about how cluster forming services like Elasticsearch interact with replication controllers and make sure that everything works together well and to establish any best practices. The logging work is likely to drive some of this anyway as we move to using multiple Elasticsearch instances for ingesting the logs from large clusters.

**Comment by thockin** [comment]
Yeah, dodging it for now is fine, but we need to know if elasticsearch can
be run by two users in the same namespace/cluster, or whether they will
somehow find each other and cause trouble.
