### ISSUE TITLE
CHANGELOG release wrangling

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#3327]
Changelog for 0.6 & 0.7 do not have ticket information, which makes if difficult to trace backwards.  

Whoever is wrangling the next release, could they please add ticket details, as we start to have more formalized testing, they will trace backwards from the CHANGELOG. 

@jbeda | @vishh your names are last on the commit log for those branches.

**Comment by goltermann** [comment]
What do you mean by "ticket details"?  What is missing?

**Comment by brendandburns** [comment]
Closing this, I'm keeping CHANGELOG up to date with my release notes.  @timothysc if you need other info, let me know.

Best
--brendan
