### ISSUE TITLE
upgrade: Make node components upgradeable (at all possible)

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#3333]
@brendandburns (couldn't find alex m. or eric h. on github?) please correct/elaborate any details here...

There are different ways to skin this cat but I think the approach we decided on was:
- cron job on node looks for new version of {kubelet, proxy, ...} and when it finds one, kills currently running version (send a signal for clean shutdown first?) and starts new version [this can be made arbitrarily more complicated, like falling back to old version if new version doesn't work, but better to keep it simple for now]
- out-of-band mechanism to push new version of these components to the nodes (we didn't really talk about this -- how does this work? Salt?)

**Comment by davidopp** [comment]
Obviously related to #2524 

And to be clear, we're only talking about the Kubernetes components here. For example, upgrading Docker is outside the scope of this issue for now though, since IIUC it kills all the pods and requires nontrivial changes to fix that behavior.

**Comment by lavalamp** [comment]
> cron job on node looks for new version of {kubelet, proxy, ...} and when it finds one, kills currently running version (send a signal for clean shutdown first?) and starts new version [this can be made arbitrarily more complicated, like falling back to old version if new version doesn't work, but better to keep it simple for now]

I will be sad if this ends up as a tangled mess of bash scripts.

How can this be made to robustly work on multiple distros?

**Comment by thockin** [comment]
Discussed at lunch yesterday: One of the biggest pain points in upgrading
node components internally is being compatible with live state - think
cgroups, on-disk metadata layouts, etc.  If we could start with the premise
that upgrades require a drain, could we make it all simpler?

**Comment by davidopp** [comment]
I assume there are a subset of commands that work on all distros? For example, wouldn't just "kill process, mv staging_binary_node live_binary_name, start process" work on any distro using the exact same commands?

I think if we wanted to make the behavior more complicated then we need to think more carefully about it, but for now something like that seems sufficient.

**Comment by davidopp** [comment]
@thockin We were assuming that the upgrade would work in-place. Initially hopefully that assumption is reasonable? We should probably split this topic into a short-term and long-term solution.

I think the downside of requiring draining is that it creates a tradeoff between cluster utilization and maximum upgrade speed. For example if you always keep the cluster <= 50% utilized then there is no problem, but if the cluster has 100 machines and is 99% utilized then you can only upgrade one machine at a time. That said, there is the obvious benefit that you mentioned.

**Comment by thockin** [comment]
Let's not downplay just how painful it is to roll out state-breaking
changes.  We could get by with saying that only some changes need drains to
roll out, but then I am afraid the drain procedures will bit rot and not
work when they need to.

**Comment by lavalamp** [comment]
> subset of commands that work on all distros

It's more about different distros putting binaries in different places, having different ways of managing logs...

**Comment by lavalamp** [comment]
If we did all node updates as "provision a new node and kill an old node", that means we only have to test & verify the "provision" step for every platform. I think optimizing for fewer things that need maintenance for every platform is a good idea at this point.

**Comment by davidopp** [comment]
I can see that what you're suggesting is ideal from our standpoint, I'm just concerned about possible problems it could cause users. The need to keep spare free resources around is one. Another concern would be that even in an ideal world, draining is disruptive (unless we can completely hide it through something like container migration); it may be acceptable on the time scales associated with kernel upgrades and physical maintenance but not on the timescale associated with component upgrades. Actually I guess the second issue I mentioned could be mitigated by only declaring some upgrades to require draining.

**Comment by lavalamp** [comment]
Don't get me wrong, I'm OK with optionally supporting an optimized path that doesn't kill stuff to upgrade; I just don't think that should be the first thing we do.

**Comment by derekwaynecarr** [comment]
@smarterclayton - feel free to chime in here, but I viewed a valid upgrade plan as evict all pods from a running node, shoot the node in the head, and bring up a new one.

Per the distribution issue, for things like RHEL Atomic where we do entire upgrade of the OS image in a single step, I think this approach is the only valid one.

**Comment by smarterclayton** [comment]
Yeah - stop new scheduling, delete all the pods, delete node.  Optimally, if replication controller detects pod on dead/unschedulable/going-down node host, you could in theory have the rcs spin up new pods prior to the old ones getting deleted.

Ideally node failure and eviction look exactly the same to the rest of the system.

**Comment by brendandburns** [comment]
I really don't think we can get away with a "kill all the pods, kill the
node, build new node" strategy here.  I just don't think customers or
applications are in a place where this will make anyone very happy.

I agree it's easier to make it more robust, but we're at a place were 99%
of the world does in place, overwriting updates of software.  I think it's
reasonable to start at that place, and meet people where they are, rather
than forcing everyone to accept a new model.

**Comment by smarterclayton** [comment]
> On Jan 8, 2015, at 11:03 PM, Brendan Burns <notifications@github.com> wrote:
> 
> I really don't think we can get away with a "kill all the pods, kill the 
> node, build new node" strategy here. I just don't think customers or 
> applications are in a place where this will make anyone very happy. 
> 
> I agree it's easier to make it more robust, but we're at a place were 99% 
> of the world does in place, overwriting updates of software. I think it's 
> reasonable to start at that place, and meet people where they are, rather 
> than forcing everyone to accept a new model. 

Not sure what you mean - kill = graceful stop, then you delete the pod, and anything stateful has to be on network storage.  There's no other way to do an update for a rolling, and CRUI is way too immature to try to do in place moves.  I don't know of another evacuation plan beyond that (any other story for ops still involves app downtime).

**Comment by brendandburns** [comment]
Maybe there is a mis-communication, I was talking  making the node
components (e.g. the kubelet and kube-proxy) updateable, not the user's
container itself.

We can easily download a new kubelet, bring down the existing kubelet, let
any existing containers coast along while the kubelet is down, and then
restart the new kubelet and have it adopt the existing containers.

Likewise with the kube-proxy (although it is a little trickier since we
need to be careful about existing network connections)

--brendan

**Comment by davidopp** [comment]
I assume Brendan is arguing for an upgrade process for kubelet, proxy, etc. that doesn't require killing the running pods. You can always argue that users need to be able to handle pods being killed due to hardware failure or their own s/w updates or whatever, but that doesn't mean they're happy with us decreasing their MTTF if we can avoid it.

**Comment by smarterclayton** [comment]
Ah - I have no issue with that, but I doubt the kubelet / proxy would be updated any more frequently than, say, ssh, libc, or ssl/kernel.  So most of our assumptions are based on ops teams that are going to roll shellshock or heartbleed updates and roll the kernel or other large surface area lib at the same time.  To them evacuate will give the least downtime for users apps because they can potentially overlap N=1 components briefly, whereas with a reboot you get none of that.  It also lets them rebalance the cluster during an upgrade

**Comment by davidopp** [comment]
At Google we roll out a new node agent at least every month, and I think the goal is more often than that, so I was assuming a schedule like that. But if you think it's on the same timescale as a kernel upgrade (i.e. less often) then that's a different story. Anyway, I agree that starting on a new node is faster than rebooting but it does mean you have to reserve spare resources.

**Comment by erickhan** [comment]
@davidopp here i am. from my perspective*, I think we're talking about a mix of use cases:

- ongoing update: drain is great. mechanism, push/pull are all worthwhile and require more disc.
- emergency: no drain. someone can point out that a pull increment of sufficiently small value overlaps this.
- independent of OS: here I think we just need to clarify that the title "node components" is about kublet, svc proxy... not heartbleed.

**Comment by smarterclayton** [comment]
Good clarification.  I would *like* to have kubelet/proxy/Docker/* be able to update without requiring downtime or reboot.  But scheduling an update (with minimal perceived downtime), and emergency update (with reboot) are things everyone expects the platform to provide (or at least, documented and well thought through).

----- Original Message -----

**Comment by lavalamp** [comment]
I guess I was thinking that step 1 is get the reboot & re-provision mechanism working, and step 2 is to precede that by migrating pods to other nodes.

I agree that it's nicer to have a restart-only-kubelet/proxy/docker upgrade path, but I am thinking it will be very difficult to make it robust on all platforms. Maybe someone can convince me otherwise. I don't want to see a bunch of people in IRC mad because an upgrade hosed their cluster, which was running on some obscure platform.

**Comment by davidopp** [comment]
@mbforbes

**Comment by alex-mohr** [comment]
Summary: although it might simplify some things, I think it's a mistake to *require* users to throw nodes away or restart containers as part of kubelet and service proxy upgrades.

Details:
There's a contingent of users that expect VM uptimes of many months or even a year absent security-critical vulnerabilities in the kernel.  Installing a new version of e.g. nginx or nfsd on e.g. debian/ubuntu/redhat usually involves a handful to dozens of seconds of downtime as the existing processes are stopped and restarted, although there are certainly apps that take much longer to be useful after such a restart.  And of course, any network attached disks or local data on e.g. SSDs is preserved.

It would be great if users switching from VMs to containers on kubernetes could maintain at least similar expectations.

It would also be great if in hosted forms of Kubernetes, we could non-disruptively roll out new kmaster and kubelet features on once-a-{week,month} schedules instead of one-a-kernel-upgrade schedules.

**Comment by alex-mohr** [comment]
@lavalamp if nodes must all have dockerd capability already, would running kubelet and serviceproxy in containers make updating them reasonably-robust across platforms?

**Comment by lavalamp** [comment]
@alex-mohr Yes, it's a good idea. But there is a bootstrapping issue between kubelet & dockerd. Probably solvable.

**Comment by bgrant0607** [comment]
See also #1573

**Comment by dchen1107** [comment]
Based on the recent discussion with cluster-lifecycle team, this is a stretch goal for v1.

**Comment by dchen1107** [comment]
My bad. This one is for 1.0, I will move sibling one #1573 to v1.0-bubble

**Comment by mbforbes** [comment]
Just to link this discussion to the concrete worklist issues:
- #6082 is the issue to implement what this issue's title proposes: make node components upgradeable through *some* mechanism
- #6079 is the roll-up issue for node upgrades, which is a slightly broader scope than this issue in that it also considers Docker and the kernel/OS. It includes links to proposed improvements to the basic mechanism.

The main issues raised above in the comments seemed to be:
- [a tangled mess of bash scripts](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69270075)
- [leftover state on the nodes](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69270967)
- in-place upgrade, pods keep running _vs_ kill pods, provision new node
  - [provision is easier to build, test, and maintain](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69273264)
  - [but users don't want that](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69290541)
  - [well, it depends on use cases](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69296273)
  - [let's do reboot first, evacuate pods next](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69377552)
  - [don't forget about storage](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-70155336)

I think I captured these concerns in #6079 with the improvements to the basic mechanism; please edit/comment/ping me if not.
