### ISSUE TITLE
kube-apiserver manpage outdated

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#3340]
When running ```kube-apiserver``` (0.8.0)
```
$ /opt/bin/kube-apiserver --address=0.0.0.0 --port=8080 --etcd_servers=http://127.0.0.1:4001 --logtostderr=true
F0108 22:59:42.400928    3080 apiserver.go:99] No -portal_net specified
```

But manpage doesn't refer to said flag and what it does.

**Comment by thockin** [comment]
When did we grow man pages?  Yikes..

**Comment by pires** [comment]
@thockin you should now better :P #1759

**Comment by thockin** [comment]
Hmm, I feel pretty sheepish.  Man pages are great, but clearly we're not
keeping them in sync.  Are they worth the effort at this point in the
development cycle?

**Comment by davidopp** [comment]
Closing this in favor of #3924 which is more general; that is to say, fixing #3924 will fix this, and there's no real advantage to fixing this without examining the broader issue.
