### ISSUE TITLE
Running on Centos7?

### ISSUE THREAD

**Issue by AshleyAitken** [GoogleCloudPlatform/kubernetes#3348]
I'm trying to get kubernetes to run on Centos 7.

I tried to use only this Ansible config but that had issues, so I have used https://copr.fedoraproject.org/coprs/eparis/kubernetes-epel-7/ on all machines (master and minions).

I have run the Ansible config again but still issues. 

Which of these services need to be running on the minions (or is it ok for all of them to run)?

systemctl start docker.socket
systemctl start cadvisor.service
systemctl start etcd.service
systemctl start kube-apiserver.service
systemctl start kube-controller-manager.service
systemctl start kube-scheduler.service
systemctl start kube-proxy.service
systemctl start kubelet.service

I assume all can run on the master (when it acts as a minion as well).  I'm pretty sure docker.socket and kubelet.service need to run on minions but what about the others?

There was also an issue suggesting that Centos may have an older version of Docker and it needs to be changed from docker.socket to docker.service.  Is this correct?

Thanks.

**Comment by AshleyAitken** [comment]
Ok, found this on manual Fedora guide:

Master: This host will run the kube-apiserver, kube-controller-manager, and kube-scheduler. In addition, the master will also run etcd. 

Minions: The remaining host, fed-minion will be the minion and run kubelet, proxy, cadvisor and docker.

Still like to know about docker.socket vs docker.service...

**Comment by bgrant0607** [comment]
See also #1328

**Comment by roberthbailey** [comment]
The docker.socket vs. docker.service was discussed in #1328. It sounds like other than that question this has been resolved.
