### ISSUE TITLE
kubectl get pod <id> should have PodIP too

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#3369]
From IRC ...

Currently kubectl get pod <id> only list Host IP on which the pod bounds to, there is no PodIP information. The only way for the user to know PodIP is run the same command with "-o json" flag. This is confusion to the user. 

cc @thockin @jasonkuhrt

**Comment by dchen1107** [comment]
Already working on a PR for this.

**Comment by jasonkuhrt** [comment]
Yay.
