### ISSUE TITLE
Split up kubelet "source seen" logic 

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#3371]
Based on #3355
Currently kubelet will refuse to kill any containers unless all sources have been marked as "seen".

However, to be more robust, we should split up this logic so that a container can be killed as long as the source that created it has been "seen", regardless of the state of other sources.

**Comment by erictune** [comment]
Good point.

**Comment by thockin** [comment]
+10

**Comment by brendandburns** [comment]
Agree, but the precursor for this is actually tracking the source of the
pod, which I don't think we do right now...

Brendan

**Comment by thockin** [comment]
We do - it's in an annotation and in the docker name of the pod (albeit
hackily)
