### ISSUE TITLE
Kubelet config/file should read Pod

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3372]
Currently it assumes it can read ContainerManifest - it should try both

**Comment by dchen1107** [comment]
Why not hold on this until we have Kubelet-read-Pod in?

**Comment by thockin** [comment]
Also the HTTP source has the same problem.

**Comment by bgrant0607** [comment]
It should read Pod. Changed the title.

**Comment by bgrant0607** [comment]
Ideally, I'd like all Pods created directly via Kubelet to be added to etcd and surfaced via the API. If updates are made via the API, I'd like those to propagate back to the node. We can discuss whether the config file should be updated or ignored. At some point, I'd like Kubelet to persistently cache pods received from the apiserver, perhaps by just writing them all out as config files.

**Comment by bgrant0607** [comment]
#4090 is the issue to sync local pods back to apiserver.

**Comment by erictune** [comment]
@wojtek-t this is somewhat related to other issues we talked about.

**Comment by bgrant0607** [comment]
Detail: We want locally specified pods to be able to use YAML config files, but we also want to rip YAML out of the API server #1004. 

The config-file behavior should be as similar to the kubectl experience. Kubelet could use parts of the kubectl library to translate YAML to JSON.

Vision:

Eventually, I'd like Kubelet to use the apiserver library and support exactly the same Pod API as the master, at which time I'd like kubectl be able to create pods directly on Kubelets, as well as reading from config files. 

I also expect to have a per-node controller #2491. I'd like to be able to use the per-node controller to update pods started via config files (or direct kubectl->kubelet pods), overriding those original files. 

For availability and self-hosting, we'll eventually need local checkpointing #489, ideally just using serialized JSON for each object. If Kubelet used apiserver, this could be done using a custom registry implementation.

**Comment by wojtek-t** [comment]
I think that #5392 is a prerequisite for it.

**Comment by wojtek-t** [comment]
If noone picks it up, I'm going to start working on it tomorrow.

**Comment by erictune** [comment]
thanks, wojtek-t

**Comment by wojtek-t** [comment]
#5598 fixed it for http channel
