### ISSUE TITLE
Autogenerate docs/cli.md from kubectl source

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#3379]
Manually updated docs have a tendency to drift from actual implementation. It shouldn't be too hard to add a script to generate the markdown from a [pkg/kubectl/cmd/cmd.go NewFactory](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L68). We could then run the script manually or as a commit hook when changes are made to pkg/kubectl.

**Comment by brendandburns** [comment]
A big chunk of that is cut/paste from the help output anyway..

Brendan

**Comment by bgrant0607** [comment]
Why are we including the help output? Seems like cobra should do that, or we should just tell the user to ask for help if they want it.

**Comment by jlowdermilk** [comment]
It's useful to see generated markdown of help output for the full command tree, e.g. if you want to link to the syntax on irc or something. Anyway, this was quite easy to do, I'll have a PR shortly.
