### ISSUE TITLE
Update architecture picture to use kubectl instead of kubecfg

### ISSUE THREAD

**Issue by arun-gupta** [GoogleCloudPlatform/kubernetes#3383]
Architecture picture: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/DESIGN.md

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli.md says kubecfg is deprecated. The architecture picture should be updated to show kubectl instead of kubecfg.

**Comment by bgrant0607** [comment]
ref #2144 
/cc @jlowdermilk
