### ISSUE TITLE
Pods are scheduled to minions that are down

### ISSUE THREAD

**Issue by kostko** [GoogleCloudPlatform/kubernetes#3386]
With latest master it can happen that pods get scheduled on minions that are not up and get stuck in `Unknown` state.

Also the `kubectl get minions` command now also lists the down minions.

**Comment by ddysher** [comment]
Master now returns all minions, with minion status set.  Scheduler hasn't been updated yet.  I'll put a fix for this.

kubectl should return only running minions, and take a '-a' option to list all minions now.  This also needs to be fixed.

**Comment by davidopp** [comment]
On Sat, Jan 10, 2015 at 8:59 AM, Deyuan Deng <notifications@github.com>
wrote:

> Master now returns all minions, with minion status set. Scheduler hasn't
> been updated yet. I'll put a fix for this.
>
> kubectl should return only running minions, and take a '-a' option to list
> all minions now. This also needs to be fixed.
>
I realize you're mimicking Docker behavior here, but it might be better to
return all minions and just show the status for each, rather than hide the
ones that are not running.

**Comment by ddysher** [comment]
Yeah, the main concern is that minion status is not as clear as Pod, e.g. running minion may not be eligible to schedule a pod. I'm still trying to figure out the best way to convey the message to client.

**Comment by ddysher** [comment]
Re-open as `kubectl get minions` now list all minions, including down ones.

We should probabaly first filter out unhealthy ones in kubectl, before we can show any status.

**Comment by bgrant0607** [comment]
@ddysher What do you mean by "filter out"? We should be caching minion status in the apiserver. As @davidopp proposed, we should show all minions that exist, including unresponsive ones.

**Comment by ddysher** [comment]
I mean do not show down minions for now for consistency (users do not expect down minion to be listed).

I agree with what @davidopp proposed, but I'm trying to figure out how / what we convey the status message to user.   NodePhase + NodeConditions are essential for k8s components, but are we going to expose all such data?

**Comment by smarterclayton** [comment]
Why wouldn't users need to see down minions?  I would think as an admin i would want to see phase + conditions

**Comment by ddysher** [comment]
nvm

My original concern was that phase and conditions are meant to be used by k8s, so we may need some translation to make it easier to understand for admin.  Also, they are not fully populated, so I thought we may delay showing status *for now*.

I certainly have no problem showing down minions and adding status.   I've created a PR  #3504
