### ISSUE TITLE
Create test for default Elasticsearch and Kibana

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3388]
#3292 has no e2e test. We should possibly create one or extend `monitoring.sh` to cover it.

**Comment by satnam6502** [comment]
I am about to submit a PR that actually disabled node level and cluster level logging in config-default.sh for GCE because the cluster level logging setup slows down the cluster creation process. When we get around to working on this bug we will of course have to re-visit this decision.

**Comment by zmerlynn** [comment]
Congrats, this also qualifies for the next Fix-It. :)

**Comment by satnam6502** [comment]
Excellent. I am already on it :-)

**Comment by satnam6502** [comment]
End to end test proposed in #5269

**Comment by thockin** [comment]
Satnam says it is done
