### ISSUE TITLE
Can i set http_proxy/https_proxy to minion?

### ISSUE THREAD

**Issue by Leon-Liangming** [GoogleCloudPlatform/kubernetes#3390]
When I try to start the example GuestBook,  it was blocked. I get this log from docker.stderr.log

[5fd605c5] +job pull(10.175.100.157:5000/kubernetes/redis-slave, latest)
Invalid registry endpoint "http://10.175.100.157:5000/v1/". HTTPS attempt: Get https://10.175.100.157:5000/v1/_ping: dial tcp 10.175.100.157:5000: network is unreachable. HTTP attempt: Get http://10.175.100.157:5000/v1/_ping: dial tcp 10.175.100.157:5000: network is unreachable

Because I can't access the docker address directly, I need to set http_proxy/https_proxy to my minions.Did have a way to set the environment variables through the app‘json or other ways?

**Comment by jbeda** [comment]
Hi Leon,

This is happening from the docker container running on your host -- not
from within the container (I think).

My guess is that this is an error reported by Docker itself.  Make sure
that the proxy env variables are set for the docker process.  See:
http://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy
.

Joe

**Comment by goltermann** [comment]
If this is still an issue, please reopen.

**Comment by Leon-Liangming** [comment]
I use a internal Docker Registry to resolve this problem，thanks all the same
