### ISSUE TITLE
Better logging when creating new pods

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#3391]
Currently after creating a new pod I get this result when I try to check its logs shortly after:

```
$ kubectl --server=https://130.211.132.49 log cloud-api-stream             

Internal Error: container not found ("cloud-api-stream")
```

1. Instad of Kubernetes returning me an error about container not found it should say that the "container" `cloud-api-stream` is in the process of being deployed
2. It should show me the deploy logs and make it clear that these are not application logs but deploy logs

By showing deploy logs I would better understand why its taking a long time to deploy (long time in "pending" state). Maybe the docker registry being pulled from is just a long download or maybe something has gone wrong.

**Comment by jasonkuhrt** [comment]
Also why does the error say "container" instead of "pod". In other words should it not say this?

```
pod not found ("cloud-api-stream")
```

**Comment by dchen1107** [comment]
assign it to myself. Will take a look now.

**Comment by satnam6502** [comment]
@dchen1107  : any progress?

**Comment by saad-ali** [comment]
Closing with PR #4373 -- adds more detailedlogging

**Comment by vishh** [comment]
I think this issue is not fully resolved. I only fixed the logging part. I haven't looked at other parts of kubelet yet.

**Comment by vishh** [comment]
Closing this since separate issues exist for fixing other end points.
