### ISSUE TITLE
Swagger basePath is wrong

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#3411]
It's 127.0.0.1 regardless of the public address.

Looks like we need to set WebServicesUrl:
https://github.com/emicklei/go-restful/blob/master/swagger/config.go#L12

where we create the endpoint:
https://github.com/GoogleCloudPlatform/kubernetes/blob/4231f8757d21021cecaed90c22565ed8287047cb/pkg/master/master.go#L431

using PublicAddress:
https://github.com/GoogleCloudPlatform/kubernetes/blob/4231f8757d21021cecaed90c22565ed8287047cb/pkg/master/master.go#L98

and ReadWritePort:
https://github.com/GoogleCloudPlatform/kubernetes/blob/4231f8757d21021cecaed90c22565ed8287047cb/pkg/master/master.go#L95

**Comment by brendandburns** [comment]
In particular: https://github.com/GoogleCloudPlatform/kubernetes/issues/3411
