### ISSUE TITLE
Delete etcd support from kube-proxy

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3413]
- [x] decide if kube-proxy needs multiple update channels.
    - seems useful to make our components more composible.
    - could be useful for people who use GCE containerVM, but not kubernetes?
    - would we ever want to setup services/endpoints from file or http source instead of kube-apiserver, e.g. to help bootstrapping/layering?
 - If NO:
   - Drastically simplify code in `pkg/proxy/config` to only support one source.  See also #3412
     - Get all cloud-providers using api source instead of etcd source.
     - Delete `pkg/proxy/config/etcd*.go`.
     - Delete code in `pkg/proxy/config/config*.go` that is supporting merging of multiple sources.
     - further simplifications will probably follow. 
 - If YES:
   -  Deduplicate the "Merge Deltas from multiple sources" pattern of code.
     - `pkg/proxy/config/config.go` and `pkg/kubelet/config/config.go` are both trying to do this.
     - the pattern is to have a Mux which takes deltas from a set of sources and updates a store.
     - use a common generic (works with any Kind) implementation for `podStorage`, `endpointsStore`, `serviceStore`.
     - use of `NewBroadcaster` in proxy is probably not needed since only one thing is waiting for the merged updated.

**Comment by erictune** [comment]
Discussion on whether kube-proxy makes sense can start now. 
If the answer is yes, work may be better done with or after #3412.

**Comment by erictune** [comment]
While reading `cluster/rackspace/cloud-config/master-cloud-config.yaml` and `cluster/rackspace/cloud-config/minion-cloud-config.yaml`, I saw a style where etcd was used to distribute config to nodes, but etcd itself was decoupled from the programs that depended on it.  This allowed for a single etcd change to trigger a chain actions, respecting dependencies, and gave room for admins to hack in changes with bash scripting as needed.

That makes me lean more towards removing etcd-source support from kubelet and kube-proxy, and just supporting apiserver and file sources (and maybe http sources).

**Comment by thockin** [comment]
I vote simpler.

**Comment by erictune** [comment]
Decision: delete etcd support from kubelet and kube-proxy.

**Comment by erictune** [comment]
Remaining work is to Drastically simplify code in `pkg/proxy/config` to only support one source.  See also #3412
     - [ ] Get all cloud-providers using api source instead of etcd source.
     - [ ] Delete `pkg/proxy/config/etcd*.go`.
     - [ ] Delete code in `pkg/proxy/config/config*.go` that is supporting merging of multiple sources.
     - [ ] further simplifications will probably follow.

**Comment by erictune** [comment]
#5252 removes pkg/proxy/config/etcd.go

**Comment by erictune** [comment]
Remaining work covered by #3412
