### ISSUE TITLE
default port to 8080 for kubectl command line parameter

### ISSUE THREAD

**Issue by ouyanggh** [GoogleCloudPlatform/kubernetes#3425]
If the apiserver only listens on one physical IP, then you'd have to use kubectl --server to specify the host.
The help message says
```
'-s, --server="": The address of the Kubernetes API server'
```

1. Only specify the IP, connection refused:

```bash
[root@dhcp-9-197 ~]# kubectl --server=10.66.9.197 get pods 
F0113 13:52:30.178616   15213 get.go:75] Get http://10.66.9.197/api/v1beta1/pods?namespace=default:  dial tcp 10.66.9.197:80: connection refused
```

2. Specify both IP and Port, then ok:

```bash
[root@dhcp-9-197 ~]# kubectl --server=10.66.9.197:8080 get pods  
POD                 CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
```

So, is it possbile to default the port to 8080 if no port specified at command line or read it from the config file /etc/kubernetes/apiserver, which is 8080 too.

If it's impossible to default the port to 8080, it needs an update of the help message at least, like:
```
 '-s, --server="": The address and port of the Kubernetes API server' 
```
or add --port flag.

**Comment by vmarmol** [comment]
The options are:

1. Detect the port from `/etc/kubernetes/apiserver`
2. Detect the port by trying `:8080` if none is specified
3. Add a `--port` flag
4. Clarify the documentation

I think (4) is the way to go (I'm not lazy I swear). (1) requires access to the API server's filesystem which is off-limits. (2) seems like it'll work for some configs and is a default that may change. (3) is more verbose and adds yet another flag.

Will send a PR.
