### ISSUE TITLE
Explanation needed on the "net" section in pod current state

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3427]
After getting a pod that was defined with 2 containers in desired state section, the current state section contains in its "info" section actually 3 entries, one of them named "net" with image "kubernetes/pause:latest".
Is this documented somewhere/what is this  section for?  What should the users do with it?

    "currentState":{
        "manifest":{
            "version":"",
            "id":"",
            "volumes":null,
            "containers":null,
            "restartPolicy":{
            }
        },
        "status":"Waiting",
        "host":"127.0.0.1",
        "info":{
            "master":{
                "state":{
                    "waiting":{
                        "reason":"Image: dockerfile/redis is not ready on the node"
                    }
                },
                "restartCount":0,
                "image":""
            },
            "net":{
                "state":{
                    "termination":{
                        "exitCode":2,
                        "startedAt":"2015-01-13T08:47:55Z",
                        "finishedAt":"2015-01-13T10:06:29Z"
                    }
                },
                "restartCount":0,
                "image":"kubernetes/pause:latest",
                "containerID":"docker://e1b6a954398cd4fbc8727fc2dc436fcc796077acffdfe03128591dabb47fd8d6"
            },
            "php-redis":{
                "state":{
                    "waiting":{
                        "reason":"Image: kubernetes/example-guestbook-php-redis is not ready on the node"
                    }
                },
                "restartCount":0,
                "image":""
            }
        }
    }

**Comment by resouer** [comment]
@abonas "net" part is quite simple. 

Kubernetes use "container mode" of Docker network to share network namespace among the containers in a pod and also make the network persistent until the pod is deleted.

For example: if you define your container A in kuber to map 80 to 8001 on the host, that port map will not be applied to the container A, instead it will be mapped on a container named kubernetes/pause, so even A is broken or down, that port map will not be lost. Of course, that also means kuber is started A like this "docker run ... --net=container:NAME_or_ID_of_pause"

BTW  kubernetes/pause is just a very tiny container to "pause" when started, so the only function of that container is to apply network parameters of its peers.

**Comment by abonas** [comment]
@resouer  thank you. 
But why is this exposed as part of a pod current state? This is internal implementation decision of Kubernetes to handle this in this way, completely not related to the state of the containers that user intended to run.
What is the user supposed to do with this information exposed in the "net" section?

**Comment by resouer** [comment]
@abonas Well, as the 'pause' container is nothing different than normal user's containers, the POD's API will return all containers they know to any info request, just like exec `docker ps` on the minion. But this also make it possible to let user know the network info of that POD.

**Comment by thockin** [comment]
@dchen1107 - are we exposing 'net' here on purpose?  I'm not sure we should
- it's an implementation detail.  Also, we risk a collision if a user
provides a container named "net"

**Comment by abonas** [comment]
@thockin  +1, exactly , it's an implementation detail and it's confusing. user defined 2 containers in pod, then in the current state there are 3. and indeed if there's one named "net" it will have non clear implications.
And again, this is exposed to users, so what the user can do with this information? How's that beneficial to whoever consumes that?

**Comment by dchen1107** [comment]
@thockin we did expose that on purpose back then because that is the only way to have HostIP which a given ContainerManifest bound to. There was a TODO to remove it eventually. Now a lot of stuff are evolved, and I think we could get rid of it completely. 

But even we remove 'net' container from ContainerStatus, the risk of container name collision with 'net' will be still exist in ecosystem, like kubelet, and event management, etc. We could rename it to some more intuitive, like kubernetes-infrastructure, and reserve the name and report an error at validation stage.

**Comment by dchen1107** [comment]
Obviously I need more coffee today morning...

Clarify: 

s/have HostIP which a /have PodIP which a

**Comment by dchen1107** [comment]
Marked as dup of #3433
