### ISSUE TITLE
podIP appears twice in pod json

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3429]
podIP appears twice in the pod json. Once directly under "current state" section, and the second time under "net". Is there a reason for this duplication?

**Comment by jbeda** [comment]
Punting to @bgrant0607 wrt API questions.

**Comment by dchen1107** [comment]
The same reason I gave in #3427. Kubelet now only reports ContainerStatus. PodStatus / PodCondition is observed at master side based on a set of ContainerStatus. There is no other way to get PodIP except net container.

**Comment by bgrant0607** [comment]
@abonas This is a temporary state due to some problems with the implementation.

**Comment by brendandburns** [comment]
Closing this since I think it is working as intended (for now)
