### ISSUE TITLE
CoreOS multi-node AWS scripts not working at least for master

### ISSUE THREAD

**Issue by lanceblais** [GoogleCloudPlatform/kubernetes#3430]
Was on the irc channel trying to troubleshoot it with user `ppires`.

I've got an AWS VPC which allows ALL TRAFFIC on the inside. I've verified that the master and node can speak to each other and I've also tried the [single-node](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_single_node_cluster.md) setup (which worked no-problems).

I followed the [multi-node](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md) setup.

The CoreOS AMI I'm using is `CoreOS-stable-367.1.1 (ami-04a2766c)`.

What we noticed is that `etcd` wasn't started at all. After a few troubleshooting steps (run etcd, run fleet) we still couldn't run `fleetctl list-machines` without getting this error: 
```
E0113 14:31:36.477262 01379 fleetctl.go:141] error attempting to check latest fleet version in Registry: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error retrieving list of active machines: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

At this point, we decided it would make sense to open an issue with the project to see if anyone knows something about the [master.yml](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml) not working with AWS anymore.

I've got an AWS account and can try some stuff out to get more debug information, so just let me know if I'm using the wrong version of CoreOS or anything.

Thank you

**Comment by jbeda** [comment]
This sounds more like a CoreOS thing vs. a kubernetes thing.  It looks like you didn't even get to the kubernetes parts.

@kelseyhightower, where is the best place for @lanceblais to get some help on this?

**Comment by roberthbailey** [comment]
@lanceblais are you still having this issue?

**Comment by lanceblais** [comment]
It's been a while since I've worked on this. I moved on pretty quickly to other things.

**Comment by roberthbailey** [comment]
I'll close as obsolete then. Thanks for the quick response!
