### ISSUE TITLE
Make net container invisible to the end users. 

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#3433]
Kubelet now only reports ContainerStatus. PodStatus / PodCondition is observed at master side based on a set of ContainerStatus. There is no other way to get PodIP except net container for master side. 
This is very confusion to the end user, #3427, #3429, ...

Now we are finalizing on v1beta3 API, including PodStatus & ContainerStatus. We can make net container completely invisible to the end users by finishing the following steps:

1) Expose network related errors at API level
2) Generate PodStaus directly from Kubelet

**Comment by dchen1107** [comment]
3) once PodStatus generated by kubelet, PodIP can be removed from ContainerStatus.

**Comment by dchen1107** [comment]
@thockin @brendandburns @bgrant0607

**Comment by bgrant0607** [comment]
I think reporting PodStatus rather than just container status is most important. How hard is that?

**Comment by dchen1107** [comment]
@bgrant0607 Used to be hard since there are many dependencies when I first report Status back. Now it is totally feasible. I already started to write PRs for this. :-)

**Comment by dchen1107** [comment]
One more PR required to close this one.
