### ISSUE TITLE
GCE PDs don't detach in a timely fashion

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3437]
Somewhat related to #2578, but `pd.sh` has been flakey in part because even after the pod is dead and gone, the PD is still very much attached. I've played around with a modified version that had a 60s timeout after noticing the pod was no longer running, even after @brendanburns #3417.

Opening an issue, then writing a mitigation into `pd.sh` itself so we can stop flaking.

**Comment by cjcullen** [comment]
s/in a timely fashion/ever

We are miscalculating the path of the global mount point in DetachDisk. Parsing PD name from the symlinked device location is pretty gross and implementation dependent, and I'm guessing that switching to safe_format_and_mount broke it.

We define the global mount point path using the PD name in AttachDisk, so it is much safer to recover the PD name from there.
