### ISSUE TITLE
TestCacheExpire in ip_cache_test.go is flaky

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#3439]
Failed due to an apparently unrelated PR:
```
--- FAIL: TestCacheExpire (0.02s)
	ip_cache_test.go:41: Unexpected calls: [ip-address]
FAIL
coverage: 37.1% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/master	0.138s
```
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/46919298

**Comment by lavalamp** [comment]
Problem here is that I left a small chance of a double-call in my parallelized cache. Didn't realize this was being tested. Will fix.
