### ISSUE TITLE
hostname_override flag broken in kubelet

### ISSUE THREAD

**Issue by sym3tri** [GoogleCloudPlatform/kubernetes#3446]
Running the pre-built 0.8.0 binaries this flag does not work.
Looks like the [hostname is always getting set to empty string](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/util.go#L100)

**Comment by lavalamp** [comment]
I think that code happens only when setting up events, right? The hostnameOverride flag seems to still be there: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/kubelet.go#L111

@dchen1107 what do you think about making this function take hostnameOverride as a parameter? https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/util.go#L85

**Comment by dchen1107** [comment]
Yeah, it should fix the issue. Will fix it tonight.
