### ISSUE TITLE
Remove config-test.sh?

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3449]
Right now we have for GCE `config-default.sh` and `config-test.sh` and they are (after a recent PR of mine merges) isomorphic i.e. one is a duplicate of the other with some settings flipped. I think this makes it hard to maintain these files since they have to remain in sync.

I propose that we require the significant env vars in `config-default.sh` to be over-ridable from the enclosing environment. Then the test driver scripts and programs (e.g. for e2e) could set things like `INSTANCE_PREFIX` and `ENBALE_CLUSTER_LOGGING` as env vars and just source `config-default.h`

**Comment by chrishiestand** [comment]
Seems like a good idea to me, though I'm a new user.

**Comment by roberthbailey** [comment]
Less config duplication sounds good to me, and overriding config options from the environment sounds useful in other contexts as well.

**Comment by satnam6502** [comment]
Close in favour of a more general solution at some point.
