### ISSUE TITLE
make test on master fails.

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#3450]
$ git clean -xdf 
Removing Godeps/_workspace/pkg/
Removing _output/
[tstclair@tstclair-redhat upstream]$ make all test 
hack/build-go.sh 
+++ Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    plugin/cmd/kube-scheduler
    cmd/kubecfg
    cmd/kubectl
    cmd/kubernetes
    cmd/e2e
    cmd/integration
+++ Placing binaries
hack/test-go.sh  
ok  	github.com/GoogleCloudPlatform/kubernetes/contrib/podex	0.020s
ok  	github.com/GoogleCloudPlatform/kubernetes/examples	0.034s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api	3.462s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/errors	0.006s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/latest	0.036s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/meta	0.015s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource	0.032s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver	0.819s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta1	0.035s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta2	0.009s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3	0.007s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation	0.037s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/auth/authenticator/bearertoken	0.014s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/auth/authorizer/abac	0.014s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers	0.004s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/client	0.356s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/clientauth	0.026s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache	0.133s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd	0.022s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api	0.016s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/client/record	0.023s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws	0.015s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller	0.424s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/gce	0.008s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/openstack	0.006s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/ovirt	0.008s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/vagrant	0.008s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/config	0.017s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/constraint	0.014s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/controller	0.029s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/conversion	0.729s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/credentialprovider	2.018s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/credentialprovider/gcp	0.021s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/health	0.011s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/healthz	0.004s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/httplog	0.005s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubecfg	0.054s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl	0.053s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd	0.110s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/config	0.052s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource	0.054s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet	1.833s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/config	0.054s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/dockertools	0.010s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/envvars	0.014s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/labels	0.018s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/master	0.013s
--- FAIL: TestTCPProxy (0.00 seconds)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 24 [running]:
runtime.panic(0x7eacc0, 0xa762bc)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
testing.func·006()
	/usr/lib/golang/src/pkg/testing/testing.go:416 +0x176
runtime.panic(0x7eacc0, 0xa762bc)
	/usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.chooseHostInterface(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tstclair/work/spaces/kubernetes/upstream/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:781 +0x5cb
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.NewProxier(0x7ff72fd750f8, 0xc208026ed0, 0xc208000c60, 0x10, 0x10, 0x7ff72fd75130, 0xa7b060, 0x0)
	/home/tstclair/work/spaces/kubernetes/upstream/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:320 +0xed
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.TestTCPProxy(0xc2080281b0)
	/home/tstclair/work/spaces/kubernetes/upstream/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier_test.go:183 +0x2fc
testing.tRunner(0xc2080281b0, 0xa75860)
	/usr/lib/golang/src/pkg/testing/testing.go:422 +0x8b
created by testing.RunTests
	/usr/lib/golang/src/pkg/testing/testing.go:504 +0x8db

goroutine 16 [chan receive]:
testing.RunTests(0x90b958, 0xa75860, 0x17, 0x17, 0x7ff72fd74f01)
	/usr/lib/golang/src/pkg/testing/testing.go:505 +0x923
testing.Main(0x90b958, 0xa75860, 0x17, 0x17, 0xa80640, 0x0, 0x0, 0xa80640, 0x0, 0x0)
	/usr/lib/golang/src/pkg/testing/testing.go:435 +0x84
main.main()
	github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/_test/_testmain.go:91 +0x9c

goroutine 19 [finalizer wait]:
runtime.park(0x413330, 0xa7a330, 0xa78569)
	/usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa7a330, 0xa78569)
	/usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xa7c6e0)
	/home/tstclair/work/spaces/kubernetes/upstream/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x75
created by github.com/golang/glog.init·1
	/home/tstclair/work/spaces/kubernetes/upstream/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2b2

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7ff72fd74e68, 0x72, 0x0)
	/usr/lib/golang/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802c060, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802c060, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20802c000, 0x90ba70, 0x0, 0x7ff72fd735f0, 0xb)
	/usr/lib/golang/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803c018, 0x1, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803c018, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http/httptest.(*historyListener).Accept(0xc208026c60, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/http/httptest/server.go:48 +0x7e
net/http.(*Server).Serve(0xc208004540, 0x7ff72fd74f18, 0xc208026c60, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/http/server.go:1698 +0x91
created by net/http/httptest.(*Server).Start
	/usr/lib/golang/src/pkg/net/http/httptest/server.go:109 +0x2a3

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7ff72fd74db8, 0x72, 0x0)
	/usr/lib/golang/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802c1b0, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802c1b0, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).readFrom(0xc20802c150, 0xc208017000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0x7ff72fd735f0, 0xb)
	/usr/lib/golang/src/pkg/net/fd_unix.go:269 +0x3db
net.(*UDPConn).ReadFromUDP(0xc20803c020, 0xc208017000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/udpsock_posix.go:67 +0x129
net.(*UDPConn).ReadFrom(0xc20803c020, 0xc208017000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/pkg/net/udpsock_posix.go:82 +0x142
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.(*udpEchoServer).Loop(0xc208000b60)
	/home/tstclair/work/spaces/kubernetes/upstream/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/udp_server.go:32 +0xac
created by github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.init·1
	/home/tstclair/work/spaces/kubernetes/upstream/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier_test.go:135 +0x5c0
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/proxy	0.008s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/config	0.012s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/binding	0.021s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/controller	0.013s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/endpoint	0.009s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/etcd	0.375s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/event	0.013s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic	0.006s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd	0.013s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/minion	0.021s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/pod	0.035s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service	0.423s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/runtime	0.029s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/scheduler	0.019s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/service	0.057s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/tools	0.053s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util	2.022s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util/config	0.023s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util/errors	0.010s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util/exec	0.060s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util/iptables	0.008s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util/mount	0.004s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/util/wait	0.015s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/volume	0.009s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/watch	0.005s
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/watch/json	0.017s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/admission/admit	0.008s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/admission/deny	0.007s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/auth/authenticator/password/allow	0.004s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/auth/authenticator/request/basicauth	0.003s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/auth/authenticator/request/union	0.003s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/auth/authenticator/request/x509	0.007s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/auth/authenticator/token/tokenfile	0.004s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler	0.005s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider	0.004s
ok  	github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/factory	0.046s
?   	github.com/GoogleCloudPlatform/kubernetes/test/integration	[no test files]
!!! Error in hack/test-go.sh:153
  'xargs go test "${goflags[@]:+${goflags[@]}}" ${KUBE_RACE} ${KUBE_TIMEOUT} ${KUBE_COVER}' exited with status 0 123
Call stack:
  1: hack/test-go.sh:153 main(...)
Exiting with status 1
Makefile:44: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by thockin** [comment]
This might be the same error others have seen.  Can you run ifconfig and
post it here?

**Comment by thockin** [comment]
Obsolete, Travis is green.

**Comment by goltermann** [comment]
If you're still seeing this, can you reopen with details.
