### ISSUE TITLE
Rev Travis GoFmt version

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#3452]
Travis currently runs GoFmt only on Go v1.3 builds not 1.4. This is because GoFmt rules for 1.3 and 1.4 can conflict: for example, Go v1.4 no longer requires assignment in for-range loops, so the GoFmt optimizations differ for both versions (i.e. v1.3 expects ```_ = range blah``` 1.4 expects just ```range blah```).

This causes issues for those of us running 1.4 locally, because running GoFmt locally produces code that fails Travis 1.3 builds. And if we use v1.3 syntax, local commits are blocked because v1.4 GoFmt won't be happy (which can be overridden but is still annoying).

Recommendation: modify Travis to Run GoFmt on Go v1.4 builds instead of v1.3 builds.

**Comment by bgrant0607** [comment]
By definition, every time gofmt is changed, which happens on every single Go version, it breaks us. Maybe we should reconsider our hard requirement of running gofmt. 

Another possibility is to run every version of gofmt and accept any match as passing.

**Comment by lavalamp** [comment]
I'm very much against removing the gofmt requirement--it replaces a style guide and eliminates nearly all of that sort of argument.

I think we should switch to gofmt from 1.4 when we switch to using 1.4 in our builds. There's nothing blocking either item except for people to do it :)

**Comment by saad-ali** [comment]
I agree with @lavalamp: GoFmt is great for avoiding code style debates, and we should run GoFmt only on the newest version of Go that we support (i.e. 1.4 today).

**Comment by ixdy** [comment]
With #4663 gofmt is being run on 1.4. It seems like this issue is resolved?
