### ISSUE TITLE
Kubelet logs "container with name %s--%s--%s" in a few places

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3454]
-- is the old old format for names.

**Comment by commonlisp** [comment]
Just to be sure, is "pod [podFullName] container [container.Name]" the new preferred format? I also see some places comma separating that form.

**Comment by thockin** [comment]
The new form should either be a list of fields, a strict, or the result of
BuildDockerName(...)

**Comment by saad-ali** [comment]
Closed with #3552
