### ISSUE TITLE
Proxy: add headers to request

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#3484]
>X-Forwarded-Host: my.apiserver.com
>X-Forwarded-Proto: https
>
>http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#x-headers
>http://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields

Suggestion from Anthony Yeh, on the google-containers public mailing list.

**Comment by enisoc** [comment]
Here's some context for why I brought this up:

If the user accesses pod A through the apiserver proxy, and pod A wants to generate a page that links to pods B and C via the proxy, then pod A needs a way to know what address the user originally used to get to the apiserver.

Either that, or the apiserver proxy needs some way to know when a cross-host link generated by pod A is actually a link to another pod, and should be rewritten to go through the proxy. For example, if there were such a thing as per-pod DNS entries, then pod A could link to http://pod-name.pods.skydns.local/status and apiserver proxy could rewrite it to https://apiserver/api/v1beta1/proxy/pods/pod-name/status.

**Comment by bgrant0607** [comment]
Background discussion: https://groups.google.com/forum/#!topic/google-containers/o_VmRlcGan0

**Comment by dchen1107** [comment]
@nikhiljindal Can you take a look at this? Feel free to reassign it back to me.

**Comment by dchen1107** [comment]
Ahh, I didn't realize that Eric already has a PR for this, and the original code was written by me anyway. Reassign it back myself.
