### ISSUE TITLE
cmd/e2e/e2e.go work items

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#3490]
Recording these for posterity.

1. Remove TAP support from cmd/e2e/e2e.go; having it in hack/e2e.go is sufficient.
2. (short term) make cmd/e2e take a flag telling it which test to run; make a shell script it hack/e2e-suite for each cmd/e2e test.
3. (longer term) make cmd/e2e have a flag that lists all its tests; make hack/e2e.go use that to auto-run every test, without needing shell scripts. There are other ways of making this work, too, of course.

**Comment by lavalamp** [comment]
@satnam6502 @brendandburns

**Comment by thockin** [comment]
I'd rather move away from a monolithic test file into distinct files and
binaries that can be reasoned about somewhat independently.  This would
need to be driven by a framework that ensures the cluster is up and
sanitized between tests.

**Comment by lavalamp** [comment]
Agreed, but I think that's even longer term and not a contradictory goal.

**Comment by zmerlynn** [comment]
Linking relevant other thread: https://github.com/GoogleCloudPlatform/kubernetes/pull/3447#issuecomment-69866169

**Comment by satnam6502** [comment]
I am about to submit and update to my PR with all the Go tests split into
separate files now belonging to a package test/e2e.
This is still driven by cmd/e2e/e2e.go -- but in the following PRs we
should remove cmd/e2e/e2e.go and call these tests directly from hack/e2e.go
But I thought it made sense to split this into steps.

S

**Comment by zmerlynn** [comment]
Snazzy! I should get hopped up on DayQuil more often!

**Comment by satnam6502** [comment]
@thockin : I think it is fine (in fact, preferable) to have all the Go e2e tests in one package as long as we have a way to conditionally execute each test. Which is a feature that I (or someone else) will add shortly to our Go e2e tests.

**Comment by satnam6502** [comment]
Also, I am trying to chip away at the e2e tests with a view to getting them into shape for use with the Go `testing` framework -- also suggested by @filbranden -- which would be a great improvement.

**Comment by thockin** [comment]
Is this monolithic issue still needed?

**Comment by roberthbailey** [comment]
@zmerlynn @satnam6502 @filbranden 

Closing as obsolete.
