### ISSUE TITLE
Kubelet Build/Parse docker names should use a struct

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3511]
We have too many fields to be returning them individually

**Comment by AAzza** [comment]
I was looking in this one and need some advice to proceed. (disclaimer: I'm student who wants to apply for GSoC and want to become more familiar with the codebase by solving some issues. If it all looks pretty dump, don't be too stict :) )

It looks like a good task to do, but I am not sure, what to include in the struct.
The ParseDockerName signature looks like this:

    func ParseDockerName(name string) (podFullName string, podUID types.UID, containerName string, hash uint64, err error) 

and the signature of the BuildDockerName:

    func BuildDockerName(podUID types.UID, podFullName string, container *api.Container) string

 Apparently to make the struct looks nice and usable it it should look something like this:

    type DockerName{
        PodFullName string
        PodUID types.UID
        ContainerName string
        Hash uint64
    }

But surely it doesn' apply at all to be used in the BuildDockerName.  I see two options:

- use struct only for parsing and not for building (my preferred)
- move logic of hashing etc. out of BuildDockerName (but it sounds awful, like removing the essence of the function out of it)

By the way, there is only 1 (one) place where BuildDockerName is used, so we can be flexible enough.

If you have some ideas or pieces of advice, I would glad to hear it.

Links:
[parse] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L721
[build] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L709
[build-usage] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L775
