### ISSUE TITLE
Boilerplate checks stuck in 2014

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3513]
It's 2015 but our boilerplate checks insist on a 2014 date.

**Comment by dchen1107** [comment]
Shouldn't my PR #3225 fixed such issue for this year? Open to improvement, of course. :-)

**Comment by satnam6502** [comment]
Ah, yes, OK. I came across a boilerplate error yesterday when I used a 2015 header. I shall look out for another one.
