### ISSUE TITLE
Vagrant e2e is currently broken

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#3530]
Recent run:
```
$ NUM_MINIONS=3 KUBERNETES_PROVIDER=vagrant go run hack/e2e.go -v -test

2015/01/15 11:19:36 Passed tests: basic.sh[1/1] certs.sh[1/1] guestbook.sh[1/1] liveness.sh[1/1] monitoring.sh[1/1] pd.sh[1/1] private.sh[1/1] update.sh[1/1]
2015/01/15 11:19:36 Flaky tests:
2015/01/15 11:19:36 Failed tests: goe2e.sh[0/1] services.sh[0/1]
2015/01/15 11:19:36 2 test(s) failed.
```

**Comment by jbeda** [comment]
cc: @derekwaynecarr

**Comment by pmorie** [comment]
@jbeda @derekwaynecarr I think the fact that you have to set NUM_MINIONS to make sure that certain cases aren't broken right off the bat is a bug in and of itself.  Maybe the cloud provider should get a chance to apply some defaults to ensure you're running with enough resources to complete the tests?

**Comment by jbeda** [comment]
We should probably make sure that there are enough minions when starting the e2e run at the very least.

**Comment by derekwaynecarr** [comment]
e2e tests should not require more than 2 minions.

I get that we want 2 to test services across minions, but 3 is overkill.

----- Original Message -----

**Comment by derekwaynecarr** [comment]
I will have time tomorrow to dig in each of these failures.

----- Original Message -----

**Comment by zmerlynn** [comment]
It's actually worse than this. Several e2e tests require exactly two
minions. It's going to be a project to fix this.

**Comment by jbeda** [comment]
Things should mostly be working now with #3656
