### ISSUE TITLE
Add timeouts to HTTP health checks

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#3532]
We have some caches in the node (minion) rest object that depend on health checks. A health check that takes minutes waiting for the network could hold up requests indefinitely. (Also imagine a malicious kubelet that accepts the request but then never writes down the HTTP connection.) So we really need to change the health checker to take a timeout parameter; timing out should be a failure.

When we make this change, we should probably also require a few failed health checks before we call a node unhealthy.

**Comment by commonlisp** [comment]
By the a few failed health checks, are you saying that kubelet should see health#HealthCheck fail multiple times before it declares it unhealthy?

**Comment by brendandburns** [comment]
#3593 is merged.  Closing.
