### ISSUE TITLE
Reduce the number of calls to gcloud to determine project and zone

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3536]
Right now we make many more calls than we need to in order to determine the project and zone by calling the bash function `detect-project`. We should change the setup to work out the project and zone just once (e.g. in `gce\config-default.sh`) and then use this value throughout the scripts like `gce\util.sh`. This should also speed up cluster creation and tear-down.

**Comment by bgrant0607** [comment]
@satnam6502 Are you working on this? Is it done?

**Comment by satnam6502** [comment]
No, no. I'm working on the P1 Fixit for an end to end test for cluster logging from weeks ago which has taken up all my time. And once that is done I intend to start work on scalability which has been help up for almost a month now due to the Fixit.
