### ISSUE TITLE
Fix AWS + CoreOS + CloudFormation getting-started guide

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#3543]
See #3434 and @erictune request.

**Comment by pires** [comment]
@erictune what is you recommendation regarding the AMI images listed in that file?

**Comment by pires** [comment]
@brendandburns perhaps you wanna add something to this discussion? We're talking about updating https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloudformation-template.json with the same changes as the aforementioned PR. Thing is, in this case we'll have to decide with AMI version to set.

**Comment by brendandburns** [comment]
Yeah, the ami nonsense w/ Amazon is crazy... I don't understand why they don't have named image tracks like Google Compute Engine does :P

Let's just choose what works today.  Anyone sophisticated enough to use cloud-formation will hopefully be knowledgeable enough to know how to select the right image when that ami expires...

**Comment by pires** [comment]
@brendandburns deal.
