### ISSUE TITLE
New basic.go test is broken

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3547]
From `job/kubernetes-e2e-gce/1175/tapResults/`:

```
I0115 22꞉25꞉30.665095   18149 driver.go꞉83] Running test 8 TestBasic
I0115 22꞉25꞉30.769102   18149 basic.go꞉115] Pod 6a07f7f6-9d05-11e4-8d6b-42010af0d577 hostIP 
E0115 22꞉25꞉30.864558   18149 basic.go꞉134] From replica 1 expected response 6a07f7f6-9d05-11e4-8d6b-42010af0d577 but got 
    <!DOCTYPE html><html><head resURL="/static/d4fecd64">
    <title>Dashboard [Jenkins]</title><link rel="stylesheet" type="text/css" href="/static/d4fecd64/css/style.css" /><link rel="stylesheet" type="text/css" href="/static/d4fecd64/css/color.css" /><link rel="stylesheet" type="text/css" href="/static/d4fecd64/css/responsive-grid.css" /><link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/static/d4fecd64/favicon.ico" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/d4fecd64";</script><script src="/static/d4fecd64/scripts/prototype.js" type="text/javascript"></script><script src="/static/d4fecd64/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/d4fecd64/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/d4fecd64/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/d4fecd64/scripts/yui/dom/dom-min.js"></script><script src="/static/d4fecd64/scripts/yui/event/event-min.js"></script><script src="/static/d4fecd64/scripts/yui/animation/animation-min.js"></script><script src="/static/d4fecd64/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/d4fecd64/scripts/yui/container/container-min.js"></script><script src="/static/d4fecd64/scripts/yui/connection/connection-min.js"></script><script src="/static/d4fecd64/scripts/yui/datasource/datasource-min.js"></script><script src="/static/d4fecd64/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/d4fecd64/scripts/yui/menu/menu-min.js"></script><script src="/static/d4fecd64/scripts/yui/element/element-min.js"></script><script src="/static/d4fecd64/scripts/yui/button/button-min.js"></script><script src="/static/d4fecd64/scripts/yui/storage/storage-min.js"></script><script src="/static/d4fecd64/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/d4fecd64/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" type="text/css" href="/static/d4fecd64/scripts/yui/container/assets/container.css" /><link rel="stylesheet" type="text/css" href="/static/d4fecd64/scripts/yui/assets/skins/sam/skin.css" /><link rel="stylesheet" type="text/css" href="/static/d4fecd64/scripts/yui/container/assets/skins/sam/container.css" /><link rel="stylesheet" type="text/css" href="/static/d4fecd64/scripts/yui/button/assets/skins/sam/button.css" /><link rel="stylesheet" type="text/css" href="/static/d4fecd64/scripts/yui/menu/assets/skins/sam/menu.css" /><link title="Jenkins" rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><link title="Jenkins꞉All (all builds)" rel="alternate" type="application/rss+xml" href="/rssAll" /><link title="Jenkins꞉All (all builds) (RSS 2.0)" rel="alternate" type="application/rss+xml" href="/rssAll?flavor=rss20" /><link title="Jenkins꞉All (failed builds)" rel="alternate" type="application/rss+xml" href="/rssFailed" /><link title="Jenkins꞉All (failed builds) (RSS 2.0)" rel="alternate" type="application/rss+xml" href="/rssFailed?flavor=rss20" /><script src="/static/d4fecd64/scripts/yui/cookie/cookie-min.js"></script><script>
              YAHOO.util.Cookie.set("screenResolution", screen.width+"x"+screen.height);
```

(Whatever it did, it decided to hit the Jenkins URL itself, which is kind of hilarious.. and bizarre.)

Similar results in `job/kubernetes-e2e-gce/1177/tapResults/`

**Comment by zmerlynn** [comment]
For whatever reason, the `kubernetes-e2e-gke-ci` job is completely sunny on this test, yet the `kubernetes-e2e-gke` job is also getting plagued by the same flake the `kubernetes-e2e-gce` flake above.

**Comment by lavalamp** [comment]
Ah, I see-- HostIP is not set (pod not scheduled yet?) so it's dialing ":8080" and getting jenkins. Hilarious.

I think it just needs to re-get the pods after it calls waitForRunning.

BTW, @satnam6502-- I'm really digging the new test/e2e/ package. Looks great.

**Comment by zmerlynn** [comment]
I wonder if this is only a flake on Jenkins because it has an active :8080.
(i.e. @satnam6502 might not've even seen a flake because that connection
would've just failed.)

**Comment by lavalamp** [comment]
If jenkins weren't answering, presumably it would have gotten an HTTP transport error.

**Comment by satnam6502** [comment]
So should we disable the part of the test that checks for the host port on some providers?

**Comment by satnam6502** [comment]
Or should we use a port other than :8080 for the containers?

**Comment by satnam6502** [comment]
How can I get an email when an issue is assigned to me? I only noticed this by accident. Thanks.

**Comment by satnam6502** [comment]
@lavalamp : it does re-get the pods after waitForRunning -- that happens with the List call.

**Comment by satnam6502** [comment]
I will make a PR which either changes this test to use a different port number, or I will make an API call to get an available port number -- which is something we need to do anyway if we want to run multiple instances of such tests at the same time.

**Comment by brendandburns** [comment]
See:

https://github.com/settings/profile

then click on "Notifications"

You'll want to make sure that the "Participating" has email clicked, and
then you should get mail when an issue is assigned to you.

See:
https://help.github.com/articles/about-notifications/

for details.
--brendan

**Comment by zmerlynn** [comment]
No, @lavalamp is right, the problem is that the .HostIP field here is empty
for some reason, as you can see from the previous log message:

I0116 00꞉22꞉28.742283   25351 basic.go꞉115] Pod
c114468d-9d15-11e4-843a-42010af055d9 hostIP


So it's just dialing :8080, e.g. localhost:8080. Changing the port
numbers is only going to ensure you get an error back versus getting
Jenkins garbage back. Personally, the Jenkins garbage is kind of
amusing (and somewhat helpful.)

**Comment by satnam6502** [comment]
Then why is the hostPort value empty? Should it not always be set for GKE and GCE? I'll add a check for an empty hostPort and write out a more specific error message.

**Comment by satnam6502** [comment]
Thanks Brendan. I have those boxes already ticked. Hmm... I will try to be vigilant and also try to get to the bottom of this.

**Comment by satnam6502** [comment]
Another source of confusion is why the `basic.sh` test is not "a flake" but this one is -- since I just transliterated the line:
```
output=$(curl -s -connect-timeout 1 "http://${ip}:8080" || true)
```
to Go using the `http` package (without the connect timeout). So I would expect them to be equally flaky.

**Comment by zmerlynn** [comment]
Are you able to repro the flake locally? I haven't tried.

basic.sh also has a lame sleep 5 in it, then regrabs the ${ip}.

**Comment by satnam6502** [comment]
I'll re-write the test to make multiple attempts (with delay) to get the hostIP. PR after I run into work!

**Comment by zmerlynn** [comment]
I meant "outside of Jenkins", not necessarily literally locally.

There may be a product bug here. Why is `.Status.HostIP` not available after the pod is running?

**Comment by zmerlynn** [comment]
But yes, what I'd appreciate is a breakfix hack that gets around this issue to get the build back (more) sunny. The way you have it coded feels right, though, so it feels like you should just stick in a // TODO(issue: blah) to look at it further.

**Comment by bgrant0607** [comment]
This is worse than flaky. Every failed jenkins build I've looked at so far failed due to this test.

**Comment by bgrant0607** [comment]
The guilty PR: #3550

**Comment by zmerlynn** [comment]
I like the hardline approach. It does occasionally succeed, though. :) But yes, it's extremely distracting for looking at Jenkins right now, and I think it should either get reverted or fixed ASAP.

**Comment by satnam6502** [comment]
In the office, working on it.

**Comment by satnam6502** [comment]
I don't know why, but I've only just got this email now -- as well as a
load of other notifications.
I think something is wrong with the way GitHub sends out notification
emails.

S

**Comment by brendandburns** [comment]
Closing this, as I believe #3568 fixed it.
