### ISSUE TITLE
Add GitHub repo URL

### ISSUE THREAD

**Issue by dandv** [GoogleCloudPlatform/kubernetes#3553]
Example:

[![image](https://cloud.githubusercontent.com/assets/33569/4949884/c2b69bde-6651-11e4-88eb-8fdf8e8c9f0a.png)](https://github.com/dandv/meteor-jquery-rateit)

**Comment by jasonkuhrt** [comment]
I guess it should link to http://kubernetes.io?

**Comment by dandv** [comment]
That would be great.

**Comment by bgrant0607** [comment]
I do not understand what this issue is requesting.

**Comment by bgrant0607** [comment]
Ah, the box appears when editing the project description on github. Done.

**Comment by dandv** [comment]
Thanks @bgrant0607. As a fellow Googler, might I also suggest updating your GitHub profile, to lend more credibility to the project?
