### ISSUE TITLE
Is there any way to express service dependencies so that kubectl creates them in order?

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/kubernetes#3554]
I have 2 services. One containing 2 pod replicas for a web application which is dependent on another backend service having pod (2 replicas) for mysql containers.

Web application uses environment variables set by backend db service. I've all the json inside same directory.

Is there any way to express the dependencies so that kubectl always create (and run) backend pods and services before it starts the web application service?

**Comment by bgrant0607** [comment]
Short answer is not yet. Discussion is here: https://github.com/GoogleCloudPlatform/kubernetes/issues/1768#issuecomment-69665834

I recommend creating all services before any replication controllers.
