### ISSUE TITLE
Error: [...] peers are not reachable [...]

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#3557]
I am running into this error which doesn't make any sense to me:

```
⧑ kubectl get pods                                                                                                                                                     

F0116 09:05:41.406133   86102 get.go:75] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

What could be wrong; debugging ideas?

**Comment by jasonkuhrt** [comment]
I've tried both without any effect:

```
$ gcloud compute ssh k8s-littlecloud-1-master
$ sudo service kube-apiserver restart
```

```
$ gcloud compute ssh k8s-littlecloud-1-node-1
$ sudo service kube-proxy restart
```
^ Repeated for each node.

**Comment by bgrant0607** [comment]
How is kubectl finding the master?

**Comment by dghubble** [comment]
I'm also having this issue. Newer GKE Kubernetes cluster behaved normally for a few days, but not list commands fail through gcloud and through kubectl. 
Kubernetes API version 0.8.1

Client Version: version.Info{Major:"0", Minor:"7+", GitVersion:"v0.7.0-dirty", GitCommit:"ad44234f7152e9c66bc2853575445c7071335e57", GitTreeState:"dirty"}
Server Version: &version.Info{Major:"0", Minor:"8+", GitVersion:"v0.8.1-dirty", GitCommit:"a137096158b3aa55f4e8e1140140d14e7cb68e7e", GitTreeState:"dirty"}

I tried restarting etcd and kube-proxy on the nodes, but I still can't perform the operations I need to do.

**Comment by jasonkuhrt** [comment]
@bgrant0607 What do you mean?

**Comment by erictune** [comment]
I'm not sure where to start with debugging this.  Can @brendandburns take a look?

**Comment by dghubble** [comment]
This repeats over and over in the kubelet.log

    etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/k8s-vulcan-node-3.c.MYCLUSTER.internal/boundpods?consistent=true&recursive=false&sorted=false
I0120 11:09:59.224489    
    etcd DEBUG: send.request.to    http://10.240.176.72:4001/v2/keys/registry/nodes/k8s-vulcan-node-3.c.MYCLUSTER.internal/boundpods?consistent=true&recursive=false&sorted=false | method GET
    etcd DEBUG: network error:Get http://10.240.176.72:4001/v2/keys/registry/nodes/k8s-vulcan-node-3.c.MYCLUSTER.internal/boundpods?consistent=true&recursive=false&sorted=false: dial tcp 10.240.176.72:4001: connection refused
    etcd_tools_watch.go:171] watch was unable to retrieve the current index for the provided key ("/registry/nodes/k8s-vulcan-node-3.c.MYCLUSTER.internal/boundpods"): 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

Also, Kubernetes services no longer resolve to pods matching their selectors which effectively brings down all the services. The containers themselves are still running.

**Comment by cyberstip** [comment]
I'm experiencing a similar thing now. I don't believe etcd is running on the master VM, but I don't know where etcd logs to debug why it's not running.

**Comment by cyberstip** [comment]
Ah, found it in /var/log/etcd.log.

'fatal error: runtime: out of memory'

I'm on a g1-small, which should have 1.7G of ram. I'm guessing g1-smalls are too small to run a cluster on?

**Comment by dghubble** [comment]
I created a new cluster 2 days ago (I use g1-small too) and started the same pods. As before, it worked for some time and this issue arose again today. After your note, I checked my /var/log/etcd.log on master and see the same out of memory error you see.

I'd need to learn more about the role etcd is playing in Kubernetes and how it is used, but I suspect using a larger instance would just buy more time before this error is encountered.

**Comment by bgrant0607** [comment]
I blame events: #3329.

**Comment by deanputney** [comment]
I'm having this issue as well. If a cluster has been running for more than 24 hours or so, I get these results:

    $ gcloud preview container services list
    ERROR: F0126 10:04:36.119432   92444 get.go:75] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

    $ gcloud preview container pods list
    ERROR: F0126 10:04:27.606135   92423 get.go:75] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

I'm running f1-micro instances, just as a test. That could be making it run out of memory faster. I'm also seeing a lot of errors mentioning "Unable to write event" in /var/log/kubelet.log:

    E0126 18:16:53.411256    5158 event.go:75] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"cadvisor-agent.13bd02ded5299638", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:""}, Condition:"", Reason:"failedSync", Message:"Error syncing pod, skipping: API error (500): Cannot start container c106636cbe50e96ce9f830d812afca4e7d61527c98e2f4bd7a76b2d4c959be04: Bind for 0.0.0.0:4194 failed: port is already allocated\n", Source:api.EventSource{Component:"kubelet", Host:"k8s-svg2gcode-node-1.c.glowforge-1.internal"}, Timestamp:util.Time{Time:time.Time{sec:63557893013, nsec:0x17ea0438, loc:(*time.Location)(0x1005420)}}}': '501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]' (will not retry!)

**Comment by thockin** [comment]
Must investigate memory pressure from events

**Comment by brendandburns** [comment]
Closing due to more specific bugs: #3853 and #3852
