### ISSUE TITLE
Define supported version skew between apiserver and components that use the apiserver

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3560]
Upgrades are described broadly in issue #2524.  This issue is about defining our support window for a specific case in upgrades.

Typically a user starts a cluster with all the software components built at the same version.
Then the user wants to do an upgrade.  The user may need to upgrade one component before the others, (e.g. master before the nodes).  Reasons include:, perfectly synchronized and simultaneous upgrades are infeasible; the user may want to stage work; user error; etc.

Therefore, "nearby" versions of components must work with each other.  However, kubernetes developers can't be expected to maintain compatibility between very different software versions.  

We should define how far apart we allow versions of components to be.

Options:
  - any components that share the same api-version will work together.  E.g if master support v1beta1 and kubelet supports v1beta1, then they will work together.
  - one minor revision:  e.g. v0.8.5 master will work with v0.9.9 kubelet and v0.7.1 kubelet  but not with v0.6.5 or v0.10.1
  - compatibility matrixes, or deprecation schedules

**Comment by erictune** [comment]
This came up in issue #2483

**Comment by zmerlynn** [comment]
I think this is also useful to nail down for #3334, since it can help define the necessary "memory" for tests.

**Comment by zmerlynn** [comment]
(But that's a slightly different case, too.)

**Comment by roberthbailey** [comment]
I believe that this was addressed at the contributor conference last week and the summary is presented in #4855. Re-open if you disagree.
