### ISSUE TITLE
Jenkins builds on pull requests

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3561]
It's clear from the churn in head that we really need a way to test PRs. I know @brendanburns got this close to working on his old server. The new flow is quite different, and now we're multiplexing to 3 different downstream projects, but it should still be feasible. It's worth spending some time investigating - it would keep our agility higher.

**Comment by brendandburns** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

is what you want to use, I never quite got it working (and it was kind of
spammy)

--brendan

**Comment by zmerlynn** [comment]
Yeah, that part I knew. (Just forgot to put it in the issue.)

The interesting part is actually the Jenkins flow now. I think what we're want to do is to drop the PR into a new build build which then pushes to GCS directory `/pr/1234/` or whatever, then we actually need a parameterized build job that can take arbitrary strings to build (instead of always building latest GCS CI).

**Comment by roberthbailey** [comment]
Can we parameterize on the git hash of the commit in the pull request?

**Comment by zmerlynn** [comment]
@roberthbailey: Yes, basically. But it should probably be in a separate dir from the `/ci/` dir, which is effectively tracking head.

**Comment by zmerlynn** [comment]
@ixdy actually did this already.

And it's awesome.

Closing.
