### ISSUE TITLE
Move all cloud providers to apiserver source for kubelet and kube-proxy

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3566]

**Comment by erictune** [comment]
This is one of the remaining work items in #2483

**Comment by erictune** [comment]
Wow, there are a lot of getting-started guides.  Proposed 3578 to narrow what set of things we promise to maintain and how we communicate changes to getting-started-guide maintainers.

**Comment by timothysc** [comment]
@erictune, are you planning to remove etcd.go from the kubelet?

**Comment by erictune** [comment]
Yes, after converting the most-used config files and sending a warning email.

**Comment by bgrant0607** [comment]
We need to set a deadline, then just break any not converted. This is causing real problems (see #4176).

**Comment by erictune** [comment]
This work is done.  See #4334 for summary.
