### ISSUE TITLE
Cleanly split core services and schedulers

### ISSUE THREAD

**Issue by tristanz** [GoogleCloudPlatform/kubernetes#357]
I've been looking at Kubernetes with interest and chatted @brendanburns on IRC, who has been extremely helpful. I wanted to write down some thoughts while the Kubernetes design was still in flux.  I'm structuring it as a proposal, just to make things concrete, not to pretend I know what's best.  Take it for what it's worth!

## Overview 

One of the main motivations for Mesos and Omega is to split the core cluster processes from schedulers.  Both provide a way to run many schedulers with different specialties and user-facing APIs on single cluster.  The Omega paper provides strong arguments for this approach as does the success of Stark, Storm, Chronos, and Aurora on Mesos.

Internally, Kubernetes has split design and uses optimistic concurrency control, similar to Omega.  The core of the cluster is the kubelet agent and etcd.  The kubelet monitors a single etcd key per node and keeps the `CurrentState` and `DesiredState` in sync.  Like Omega, schedulers can independently use `CompareAndSwap` to atomically schedule pods on hosts and `WatchKey` to track state changes.  This design is less flexible than Omega, due to the limited form of optimistic concurrency control etcd provides, but the spirit is similar.

This core idea is incredibly simple and flexible.  It allows near-optimal cluster-wide scheduling.  With just etcd and kubelet, it would be easy to port Spark, Storm, and Chronos to Kubernetes!

Given this, I propose making the split between core services and schedulers much more explicit.  I believe the core should provide **no** scheduling.  This split should be publicly documented and embraced with reference to Omega.  Users should be encouraged to port popular tools like Spark and Chronos to Kubernetes.  While Kubernetes can and should provide its own schedulers, they should be built on the same primitives as other schedulers.  The bias should be for multiple small, tailored schedulers, over a monolithic scheduler.

### Kubernetes Core

Kubernetes Core should provide a small, easy to understand set of services for clients and schedulers to target. There should be **zero** scheduling in the core. The minimum core components are therefore just:

1. etcd 
2. kubelet
3. (optional) Kubernetes Core API

For simplicity, core services should run on every node, even if they just act as proxies. Etcd and kubelet provide all that's required to do scheduling and monitor state.  

The optional Kubernetes Core API provides a cleaned up version of whats in etcd.  Ideally it would have `Watch` support with `waitIndex` and `CompareAndSwap`, since these are critical for schedulers.  This API is optional because clients and schedulers could talk directly to etcd, which would obviate the need to write another API.  However in the long run it would be nicer to provide a unified API with no direct access to etcd by clients or schedulers.

To ensure atomic scheduling, all pod data for a host should be stored in a single etcd key, as is done currently.    Schedulers can ack requests by storing data in etcd before scheduling, but this should not be part of the core (#354).  All node state should live in one place.  A top priority is publicly documenting this state and how it is updated.

To enable schedulers to cooperate more effectively, the data should include CPU (as a cgroup array of shares) and memory requests.  Following Omega, it could also include a pod priority level [0,10], which should be respected by schedulers doing preemption.  To the degree possible given etcd constraints, the Core API could enforce some of these restrictions to avoid misbehaved schedulers wreaking havoc, but to start this could remain a convention that schedulers try to respect themselves.

A key missing feature to support different types of schedulers is configurable restart behavior (#127).

Besides etcd and kubelet, everything else is not strictly necessary.  A scheduler could, if it desired, start the Kubernetes Proxy servers, cAdvisor, and other helpers using just the functionality offered by etcd and kubelet.  Many schedulers don't need these services.  That being said, it may make sense to add other components to the core over time. Possible core components include:

3. Proxy
4. cAdvisor
5. Logging
6. Metrics
7. VPN/SecurityGroups

Again these could start as independent APIs and later be unified behind a single Core API. Note that the current `apiserver` includes scheduling, in violation of the key principle I'm proposing.

###  Kubernetes Schedulers

This design is meant to support multiple schedulers operating completely in parallel.  No scheduler is privileged.

Everything currently related to scheduling and replication should be moved out of Kubernetes Core into a separate scheduler.  To make this line clear, this scheduler should have a name like *Compass*.

Schedulers should use the public Core API or documented etcd state if the API is not available yet.  As an example, the current Kubernetes scheduler would get service information from the core API, inject that into the pod manifest, examine the cluster state, and then try to make a scheduling decision, retrying on failure.  It would then monitor state changes and react accordingly.

Every scheduler, including Compass, should provide users a distinct API.  No scheduler API should be incorporated into the Core API.  These APIs will be designed for the application at hand.  For instance, a Chronos like scheduler should not be merged with a scheduler for long running services like Compass.  Kubernetes should favor many smaller schedulers with simple APIs over a monolithic scheduler with tons of features for all use cases.

### Conclusion

Splitting the core and schedulers is consistent with the internals of Kubernetes and lessons of Omega, but is not entirely consistent with the current codebase or documentation.  This split could be **the** principle behind Kubernetes.  The simplicity and flexibility of this design should be trumpeted from the rooftops.

Obviously I'm leaving out lots of details and repeating a lot of what already exists, but hopefully the general idea is clear.  I believe Kubernetes is quite close to this but it's hard to see from first glance.  My basic goal is to make it really easy to write schedulers and then write some interesting ones with super user-friendly APIs.

**Comment by lavalamp** [comment]
Kubernetes scheduler has been separate for quite some time now. There will be more modularization in the future ("component plugins"), but I'd prefer to track those efforts in their own issues.
