### ISSUE TITLE
Proposal for reorganizing getting started guides

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3578]
Ideally, users would like instructions that were precise, short, and work with all their existing infrastructure.  But there are too many possibilities, and the kubernetes-dev team can't reasonably update and test across all possibilities.  So, we need to simplify somehow.  This is a proposal/start-of-discussion on how to do that.

Assume users fall into three broad categories:
  1. I want as few steps as possible, and I'm flexible on infrastructure as long as it is cheap and easy.
  1. I want to try on my existing infrastructure and I can't easily change certain choices (e.g. must use RHEL).  I'm used to having to adapt new things to my existing infrastructure, so I can follow longer instructions.
  1. Those who want to develop on kubernetes.

For the first category of user, I suggest we have a couple (3 max) "Quick Start Guides" which:
  - we ensure are always up-to-date, perhaps somehow testing with each release.
  - are designed to get people to the point of being able to work the `examples/` as quickly as possible.

I propose that the two "Quick Start Guides" are:
  - GKE: 
     - for people comfortable signing up for something.
     - leverages existing Google documentation and support
     - problem of secret distribution and config distribution is solved by Google.
  - Vagrant + VirtualBox + Fedora:
    - the existing vagrant getting-started-guide and Vagrantfile.
    - for people who don't want to signup for anything or pay anything, or can't access Google Cloud for some reason.
    - vagrant and virtualbox are pretty easy to install, works on win/os2/linux
    - problem of secret distribution and config distribution is easy because it is on one physical machine.

For the second category of user, we would have two types of things:
  - config templates
     - can be updated by kubernetes devs without fear of breaking a getting-started-guide
     - getting started guides copy and specialize these templates
     - example: cluster/saltbase/salt/*
     - example: docs/getting-started-guides/coreos/cloud-configs/*
  - a range of specific Getting-started-guides 
     - not officially maintained by kubernetes team
     - tailored to specific cloud provider, OS, config, and networking choices.  
     - example: docs/getting-started-guides/rackspace.md
     - example: docs/getting-started-guides/fedora/fedora_manual_config.md
     - each one has its own copy of any config files it uses
     - owners periodically review any changes to the "config templates" and apply those to their getting-started-guide.

Developers would typically use the GCE getting-started-guide.

**Comment by erictune** [comment]
@erickhan  we talked about this just now

**Comment by derekwaynecarr** [comment]
The current Vagrant setup is Fedora.

I see no value in changing the distribution and we volunteer the expertise to fix/maintain. 

Otherwise, this LGTM.

**Comment by derekwaynecarr** [comment]
I see you updated the original issue text so ignore previous comment.  I had the original issue text in email.

**Comment by erictune** [comment]
@bgrant @mikejeffery I'm willing to update the docs.  

What I was looking for in this issue was grunts of agreement from folks like @smarterclayton @brendanburns @thockin about this change in policy.  

The the proposed policy change is:
 - at each commit, we expect the GKE, GCE, and Vagrant + VirtualBox + Fedora setups to still work.  
 - all the other setups ("getting started guides") are maintained on a best effort basis and may slowly rot.

**Comment by smarterclayton** [comment]
grunt

----- Original Message -----

**Comment by thockin** [comment]
ACK.  GCE/GKE, Vagrant+Fedora, AWS+CoreOS should be our 1-2-3

**Comment by bgrant0607** [comment]
Copying @proppy's text from #2840:

- Split between:
  - “cluster setup” (per platform)
  - “quick start” (hello world on a local cluster)
  - “using it” (common tour of kubernetes functionally)
- Make an inventory of existing samples, qualify overlap and deprecate
- Provide individual directory or repo with manifests example for each tutorial
- moving out of date docs between /docs and /contrib
  - put onus on each provider’s maintainer, and ensure it works every release, if it works 3 times, keep it a first class, if not demote it to contrib

Part of #2633

**Comment by bgrant0607** [comment]
Sounds fine. Ideally there wouldn't be much to do with respect to cluster setup in the getting started guides, but fixing that is a bigger problem.

**Comment by erictune** [comment]
basically implemented in the new docs/getting-started-guides/README.md
