### ISSUE TITLE
Pod cache (probably) causes basic.go e2e to flake

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3582]
The original version of the basic.go e2e test sometimes failed because `hostIP` was an empty string for a pod that was in the Running state. After discussion with @bgrant0607 it seems this is probably due to our strange pod cache implementation which wipes the state after the TTL period and then re-fetches data. This means that it is possible to incorrectly observe an empty string for the `pod.Status.HostIP` field (and other fields) and this is what caused (I think) the stricter Go basic test to fail whereas the bash test was happy to accept any value from ":8080".

We should improve the behaviour of the pod cache implementation.

**Comment by satnam6502** [comment]
Let me emphasize that I am far from certain that this is the source of test flakes.

**Comment by brendandburns** [comment]
Closing this, as I believe that this should now be fixed by #3927  (we'll see...)
