### ISSUE TITLE
Finalizers Concept

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#3586]
Read #3585 too.

We should have a general framework for a pod or other object to be POST'ed in an incomplete state, and persisted to etcd, and then subsequently to be handled by a series of "finalizers" that fill in missing fields.  Once all are filled in, the object can be picked up by a kubelet and run.

#### Use cases 
Use cases for filling in fields in pods after they are stored.
  - Set default resource limits on pods
  - Schedule pods to nodes (the existing scheduler sets the HostIP field)
  - custom allocator for PodIP addresses (and setup vlans, etc; #3350)
  - pod limit auto-adjuster.  sets unspecified cpu and memory limits
  - pod template. a permanently underspecified pod could be a template for a replication controller

#### Availability

Availability of the cluster limited by the finalizers, so they need to be replicated.  Fortunately, because they typically act on one object at a time, and can use resource versioning, it should be easy to parallelize them.

#### Bootstrapping
 There has to be some way to get pods onto minions without waiting for finalizers to act on them, when turning up a cluster, or upgrading a finalizer.  The scheduler is a special case of this.

Some options:
  - allow privileged user to write Pods to apiserver with all fields finalized, including HostIP, so that kubelets pick them up immediately
  - talk directly to a particular kubelet an make it start a pod.  We should make kubelets accept pods to run in "api.Pod" format.
  - do rolling updates of finalizers wherever possible, so that there is always at least one good one around to help out. 

#### State and sequence
  - what phase/condition/reason pods have are in as they work their way through finalizers
  - sequencing and composing multiple finalizers; how finalizer knows when it is its turn to act.

**Comment by derekwaynecarr** [comment]
I guess I wonder if this is a ```Pod``` specific problem, or does the same apply to other resource types?  

At some level, I view what we do in ```kube-controller-manager``` as a pseudo finalizer as well.

**Comment by erictune** [comment]
@derekwaynecarr agree

**Comment by davidopp** [comment]
Sorry, I made some comments relevant to this in #3585. Would it be better to just combine the two issues?

**Comment by bgrant0607** [comment]
Yes, let's comment on #3585.

**Comment by bgrant0607** [comment]
Copied issue text over.
