### ISSUE TITLE
"id" appears twice in pod definition - why is it needed?

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3605]
looking at the example https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook-go/redis-master-pod.json
the id "redis-master-pod" appears as part of pod definition (which makes sense), but also inside the "desired state" part - why is it needed to be specified there too? 
the user can even input there another value, what's its purpose in "desired state"?

**Comment by thockin** [comment]
This is an artifact of v1beta1, fixed in v1beta3.

Dup of #294
