### ISSUE TITLE
Simplify restartPolicy: change to string

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3607]
In the pods in both v1 and v3 api, the restart policy looks like this:

"restartPolicy": {
          "always": {}
        }

Why is this a hash inside hash? Shouldn't it be a simple key "restartPolicy" with string value one of: RestartPolicyAlways, RestartPolicyOnFailure, RestartPolicyNever ?

**Comment by thockin** [comment]
The assumption was that the various policies would soon grow parameters,
which would live in those inner objects.  Given that this has not happened
yet, maybe we should reconsider this design for v1beta3?

@dchen1107 - will we grow params here?  E.g. max number of restarts or
specific failure types?

**Comment by bgrant0607** [comment]
@thockin : My answer is no, we will not expand these policies.

**Comment by bgrant0607** [comment]
I'd be happy to have this simplified in v1beta3.

**Comment by thockin** [comment]
Really?  You know the 800 knobs that we have internally - none of them are
useful?

I'd be happy to see this simplify to a string like the other *Policy
fields, but the conversions and testing will have to be written carefully
(as I discovered this week :)

**Comment by bgrant0607** [comment]
Really.

**Comment by dchen1107** [comment]
Ok, I will clean up this one next week. And we can add  knobs later if someone come up with real good reasons.

**Comment by bgrant0607** [comment]
I'd like to get this into v1beta3 asap.

**Comment by dchen1107** [comment]
@yujuhong is working on #4623, and there might be some overlaps between two issues.
