### ISSUE TITLE
private.sh broken

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3609]
It's either the interaction of running both the `goe2e.sh` version and the normal version or something changed, but `private.sh` is failing way more than it used to. @satnam6502, mind taking a look? I don't mind if our answer now is to yank the test back out if we're comfortable that the new Go test is actually working well - we have a weekend of test runs to look at if you want to glance through logs.

**Comment by zmerlynn** [comment]
Sometimes, as you pointed out in email, it fails like so:
```
F0119 16꞉42꞉42.888678   31789 kubecfg.go꞉494] Error꞉ replicationController "my-hostname" already exists
```
which is a failure that the new Go test is actually resilient to. There are eiher times it's actually failing just waiting for pods to come up, though, and those times are weirder.

**Comment by satnam6502** [comment]
Yes, it is running both the Go tests and the basic.sh and private.sh tests that is likely to be the issue because basic.sh does not clean up properly after itself. I can prepare a modification to basic.sh to make it delete the replication controller `my-hostname` (and ignore errors) before it tries to create it.

**Comment by satnam6502** [comment]
Another thing we could to to avoid flakes for e2e tests is to delete all resources at the beginning of a batch of tests. Then when a batch of tests are done, list all resources and if there are any then these are stragglers which should have been cleaned up so we can then identify which tests need to be fixed.

**Comment by zmerlynn** [comment]
Yup. The driver could have a "check hermetic between tests" thing.

One of the reasons the hack/e2e driver does the deterministic random order
is to make sure tests *might* perturb each other if they're *not* hermetic,
but it's nuisance to debug, certainly.

**Comment by satnam6502** [comment]
Right now I am in the mountains with limited email access and also quick sick. When I get home this evening I will try to prepare a PR to harden `basic.go` or `private.go`. A quick fix would be a kubectl command with `|| true` at the end which deletes the replication controller `my-hostname`.

**Comment by zmerlynn** [comment]
It can actually survive for a bit. Jenkins is partially cloudy and only a
bit noisy.

**Comment by satnam6502** [comment]
Also,  the associated pods need to be deleted too.  This really is too much
effort for the shell tests IMHO.

**Comment by roberthbailey** [comment]
Looking at recent Jenkins runs, private.sh does not appear to be failing any longer.
