### ISSUE TITLE
kubelet locks devicemapper (preventing docker pull from cli)

### ISSUE THREAD

**Issue by markllama** [GoogleCloudPlatform/kubernetes#3611]
The kubelet process on a minion appears to be locking a resource which prevents a user logged onto the minion from sucessfully pulling or running a container outside kubernetes.

I found this first when pods were failing to start, remaining in the "waiting: image not available on minion" state.  I attempted to pull an image manually and docker failed with this message:

    6cece30db4f9: Error pulling image (20) from fedora, Driver devicemapper failed to get image parent
    782cf93a8f16d3016dae352188cd5cfedb6a15c37d4dbd704399f02d1bb89dab: Unknown device
    782cf93a8f16d3016dae352188cd5cfedb6a15c37d4dbd704399f02d1bb82015/01/19 15:26:37 Error
    pulling image (20) from fedora, Driver devicemapper failed to get image parent
    782cf93a8f16d3016dae352188cd5cfedb6a15c37d4dbd704399f02d1bb89dab: Unknown device
    782cf93a8f16d3016dae352188cd5cfedb6a15c37d4dbd704399f02d1bb89dab

Recent retests indicate the pods are created correctly but CLI attempts to pull images fail as indicated.  Stopping the kubelet process allows docker pull to complete successfully.

Kubelet operation should not prevent other users from performing allowed docker operations.

**Comment by erictune** [comment]
@dchen1107 PTAL

**Comment by erictune** [comment]
If it happens again, it could help if someone could grab `/proc/$pid/stacks` for all kubelet and dockerd threads (`ps -eLf`).  That would allow us to determine if anyone is currently blocked in the kernel in a devicemapper-related system call.

**Comment by brendandburns** [comment]
My bet is that its a blocked call to the Docker API, and dockerd itself is
the one holding the devicemapper.  We should audit, and make sure we're
setting timeouts on all of our calls to dockerd.

I can't think of anything else that we're doing that would be holding the
devicemapper (well, maybe mounting disks, but I think that isn't the case
here...)

On a side note, we should probably add some timeouts there too :P

--brendan

**Comment by dchen1107** [comment]
Which version of kubernetes / kubelet are you running?

**Comment by markllama** [comment]
@erictune I'm not quite sure how to "grab /proc/$pid/stacks for all kubelet and dockerd threads (ps -eLf)."

- with dockerd and kubelet running
  - snapshot???
  - docker pull fedora:20
  - snapshot???

@dchen1107 it's been occurring since a commit on Dec 20 2014.  I'm slicing now to try to find two commits in a row with pass -> fail.

**Comment by erictune** [comment]
@markllama I think my request is obsolete now that @dchen1107 has done a repro.  But, what I meant was something like this as root on your kubelet machine:
```
interestingpids=$(ps -eLf | grep "kubelet\|dockerd" | awk 'print $2')
(for p in $interestingpids
 do
  echo "PID: $p"
  echo -n "cmdline:"
  cat /proc/$p/cmdline
  echo "stacks:"
  cat /proc/$p/stacks
 done
) > debug
```

**Comment by dchen1107** [comment]
@markllama, thanks for prompt response. 

I just updated #3617 with my latest reproduce on aufs. I highly suspect they are the same issue caused by Image GC recently introduced. And you mentioned that the issue started occurring since Dec 20 2014,  which kindly prove my hyperthesis since I remembered Image GC was introduced around the same time.

**Comment by dchen1107** [comment]
Ok, I believe this is dup of #3617, and will update over there together.
