### ISSUE TITLE
[Question] Will containers in the same Pod compete/conflict with each other?

### ISSUE THREAD

**Issue by resouer** [GoogleCloudPlatform/kubernetes#3621]
I really buy the idea that Docker containers should run as a atomic POD!

But the question is, will these containers in one POD compete with each other?

For example, I have a batch of apps running in a POD, but one of my poor coded app has memory leak, and finally it eats up all the memory resource in the POD and kills other containers (apps)?

Any explanation from namespace sharing view and cgroup stuff will be helpful!

**Comment by abonas** [comment]
@resouer I think your title meant to say "in the same pod" and not "in the same port"

**Comment by thockin** [comment]
Isolation today can only apply to containers and not pods, because that is
all docker gives us (for now).  If you assign memory or CPU limits yo
containers in your pod, we will pass that on to docker.

Keep in mind that anything that is NOT isolated on the same node could leak
and destroy all your other plans.  Isolation is still very much optional.

Eventually we have plans for much tighter isolation.  See LMCTFY for
details on some of what we do internally.

Tim

**Comment by resouer** [comment]
@thockin 
`In the future, pods will share IPC namespaces, CPU, and memory (LPC2013).`

So in current stage, kuber only share net namespace to "hold the network" by setup network container, but why do we still wanna to share cpu, memory, etc namespaces?

My understanding is that thus we can  allocate resource (like 4G MEM) with two tasks T1 (1G) and T2 (3G), furthermore, we can allocate task by its resource sensitivity.

If it is the case, then there is no resource conflicts between T1 & T2, POD is managing that. right?

**Comment by thockin** [comment]
Putting containers under a common parent (ie. A cgroup for the pod) let's
you do things like share some memory between containers without going over
a common limit.

There are all sorts of ways this can be useful in a world where EVERYTHING
has limit applied.

**Comment by resouer** [comment]
@thockin So the only question is then why kuber try to share cpu mem etc in the future?

**Comment by brendandburns** [comment]
There are a number of use cases where you want to restrict the total amount
of resources a group of containers consume, but leave it to the individual
containers to sort things out.  For example, you may want your main server
to have 2.0 cores, but then have an extra 0.5 cores left around for
multiple auxillary processes to use without having to give resources to all
auxillary processes.

So you reserve 2.5 for the Pod, within the pod you reserve 2.0 for the
webserver, and you let the remaining containers fight over the 0.5 that is
left over.

Note that Docker currently doesn't support this sort of container
hierarchy, so until it does, it's kind of a moot point.

--brendan

**Comment by thockin** [comment]
Right - static apportionment is naturally inefficient.  Many apps inside Google make great use of a hard limit for the pod, but softer limits for the containers within.

A hard outer shell and a gooey center, you might say.

That's not to say you can't set up limits for the containers such that they don't impact each other - we also make great use of that.  There are a lot of different apps out there.

I'm going to close this issue - if you think there's still an issue, please re-open.

**Comment by resouer** [comment]
@thockin @brendandburns  Thanks a lot, especially for your example, I think I have got the idea finally.
