### ISSUE TITLE
feature request - REST api - need to be able to get list of relevant pods for each service

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3623]
Currently there is a selector on each service that based on its query language the service knows which pods are relevant.
However :
1. the query language is not documented, which operators are supported/what's the right syntax.
2. even if the query language is known and clear, the resolving of each service to pods relationship need to be resolved all over again by the clients.

So it will be much better to have a possibility for a REST request to get per each service the list of its relevant pods (or at least their uid or name)

**Comment by stefwalter** [comment]
Ditto for anything else involving labels, such as replication controllers.

**Comment by abonas** [comment]
@stefwalter definitely, I was about to open a separate one for rc but perhaps your comment is suffice :)

**Comment by erictune** [comment]
The query language for selectors is documented here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md

We have a REST interface that lists all the PodIPs which are part of a service, at `api/$VERSION/ns/$NAMESPACE/endpoints/$SERVICE_NAME`.  

If you needed the pod names instead of PodIPs, you could do something like (not tested):
```
sel=$(curl $MASTER/api/v1beta3/ns/$NAMESPACE/service/$SERVICE_NAME | jq .spec.selector)
for s in sel
do
  curl "$MASTER/api/v1beta3/ns/$NAMESPACE/pods?labels=$s&fields=name,uid"
done
```

**Comment by abonas** [comment]
@erictune based on the labels.md doc, it's not clear how do you specify in json file that serves as input for REST api  the relevant operators for selector.

for example, the selector specified here : 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook-go/redis-master-service.json
a. how can someone know which operator is between key/value? is it "=" ? is it "!=" ?
b. what is the operator between the 2 key/value pairs? it is AND? is it OR?  is it "not in"?

**Comment by erictune** [comment]
(a) it is "="
(b) it is AND
Agree this could use clarification in the documentation.

It doesn't appear that there is a way to use an operator other than the implied `=` with  json ( `"selector": { "name:", "foo", "value": "bar"}` format).

@bgrant0607 is it intentional that you cannot use operators with json selector?

**Comment by abonas** [comment]
@erictune yes I got that those are probably "=" and AND, but given that there are so many other options in the docs that you referenced, it's really obvious it greatly lacks documentation and examples. perhaps we should dedicate a separate issue for this one?  since it was not the original question in this thread.
can you somehow split it out?

**Comment by erictune** [comment]
I forked two issues.  I answered some questions.   I think that covers the questions in this issue.   Closing.  Feel free to reopen if I missed something.

**Comment by abonas** [comment]
@erictune I tried to use the endpoints api:
http://localhost:8080/api/v1beta3/ns/default/endpoints/redis-master
the pod_ip is really inconvenient to work with to resolve it to pod id/name.

The other procedure you specified, when you say it's untested, does that mean that I completely can't rely on it? so it might completely not work but also be removed ?

How clients are supposed to visualize the relationships between rc to pod and service to pod, if there's no good way to get that info from kubernetes? 

regardless, is there documentation for endpoints api?

**Comment by abonas** [comment]
so @erictune I would reopen this issue regarding being able to get pods followed by a service and get a standard way to get this information.
one of a standard ways to get it in REST is to have rel links to pods as part of the service json body.

**Comment by simon3z** [comment]
@erictune isn't getting the services and then getting the pods raceful? Can't the selector be changed on an existing service? Can't the labels be modified on a pod?

If it can, one inconsistency that I can think of is a pod that will appear in two different selectors queries because its label was changed during the two REST requests.

**Comment by erictune** [comment]
@abonas 
What I meant when I said the procedure was "untested" is that I didn't actually execute the command that I suggested against my cluster.  It may container a typo.     However, you can rely on that command, or a typo-corrected version of it, to work as long as v1beta3 is supported by your apiserver, and probably much longer, with a tweak to the api version portion of the URLs.

**Comment by erictune** [comment]
@abonas
regarding: *How clients are supposed to visualize the relationships between rc to pod and service to pod, if there's no good way to get that info from kubernetes?*
 I think we hope that users will use the primitive operations that we have provided in the REST API, and then build whatever views or joins of the data that they are most interested in.  That may require making multiple calls to the REST api and joining information on the client side.

**Comment by erictune** [comment]
@simon3z 
Yes, there could be inconsistencies such as you mention.   Here are some ways a client could deal with that:
 - just display the potentially inconsistent information, and let the user reload the view on those rare occasions when there was a race.
 - validate the information and re-fetch it if it appears inconsistent
 - verify that the resource version of the service has not changed after getting the pods.  retry the sequence of calls if it has
 - use a watch on both services and pods and update the view any time a change is seen.  Inconsistent states should thus be transient and not obvious to users.

**Comment by erictune** [comment]
@abonas 
I filed https://github.com/GoogleCloudPlatform/kubernetes/issues/3676 about links to related objects.

**Comment by bgrant0607** [comment]
Reverse label lookup #1348 is the intended solution for looking up services targeting a pod.

#341 is about generalizing selectors in the API.
