### ISSUE TITLE
Update node.yaml to support graphdriver: overlay

### ISSUE THREAD

**Issue by preillyme** [GoogleCloudPlatform/kubernetes#3626]
Update https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/node.yaml Docker Application Container Engine section to support graphdriver: overlay instead of graphdriver: btrfs

As of CoreOS Alpha 561.0.0 graphdriver: btrfs produces fatal prerequisites for driver not satisfied (wrong filesystem?)

**Comment by erictune** [comment]
I think this was working before.  Do you know if this is an intentional or accidental change in CoreOS?

**Comment by preillyme** [comment]
@erictune: I believe this was an intentional change made in CoreOS. But @kelseyhightower would know best.

**Comment by goltermann** [comment]
Appears fixed in #3625
