### ISSUE TITLE
Descriptions missing from v1beta3

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3628]
Filing this as a remind to come back to it.

**Comment by bgrant0607** [comment]
Planning to do this once the API is more or less settled.

**Comment by bgrant0607** [comment]
Ref #1519

**Comment by bgrant0607** [comment]
FWIW, this was previously filed as #1724.

**Comment by vishh** [comment]
This issue is not fully resolved yet.
