### ISSUE TITLE
kubernetes json format issue

### ISSUE THREAD

**Issue by prateekarora151083** [GoogleCloudPlatform/kubernetes#3633]
i want to execute command of docker container using kubernetes.

{
  "id": "hdfs-master",
  "kind": "Pod",
  "apiVersion": "v1beta1",
        "desiredState": {
           "manifest": {
           "version": "v1beta1",
           "id": "hdfs-master",
           "containers": [{
              "name": "hdfs-master",
              "image": "hadoop_hdfs",
              "command":[
                {"/etc/run.sh"},
                {"-master"},
                ]
              "ports": [
                {"containerPort": 22,"hostPort": 4347},
                {"containerPort": 50070,"hostPort": 4348},
                {"containerPort": 9000,"hostPort": 9000},
                ]

            }]
          }
  },
  "labels": {
    "name": "hdfs-master"
  }
}

but it show
F0120 10:06:18.326828   21398 resource.go:290] couldn't get version/kind: error converting YAML to JSON: yaml: line 15: did not find expected ',' or '}

can anybody help me to find right syntax .

**Comment by erictune** [comment]
I like to use the `jq` command to verify the syntax of my json.  It pretty-prints it if it is correct and has better error messages than kubectl.

For your example, I pasted your json into this command:
```
$ cat | jq .`
```
and got this error message
```
parse error: Objects must consist of key:value pairs at line 13, column 15
```

I fiddled around with it and got this, which should work:
```
{
  "id": "hdfs-master",
  "kind": "Pod",
  "apiVersion": "v1beta1",
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "hdfs-master",
      "containers": [
        {
          "name": "hdfs-master",
          "image": "hadoop_hdfs",
          "command": [
            "/etc/run.sh",
            "-master"
          ],
          "ports": [
            {
              "containerPort": 22,
              "hostPort": 4347
            },
            {
              "containerPort": 50070,
              "hostPort": 4348
            },
            {
              "containerPort": 9000,
              "hostPort": 9000
            }
          ]
        }
      ]
    }
  },
  "labels": {
    "name": "hdfs-master"
  }
}
```

**Comment by prateekarora151083** [comment]
Thanks my issue is resolved now
