### ISSUE TITLE
Collect & publish crash report data

### ISSUE THREAD

**Issue by kmerker** [GoogleCloudPlatform/kubernetes#3635]
Allow k8s users to opt in to crash & error collection, and publish the data back to github as new issues or in some other collection form. This would allow us to see real-world usage trends that may not appear as bug reports. I can help with the privacy policy.

**Comment by dchen1107** [comment]
#3500 proposed to add kubectl dump command.

**Comment by goltermann** [comment]
#3500 does cover this one.
