### ISSUE TITLE
Services should not create their own firewall rules

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3636]
Fallout from https://github.com/GoogleCloudPlatform/kubernetes/issues/3579#issuecomment-70707833 and #3601: It would be nice if services could create their own firewalls rules. This is the last remaining wart on #3601 that prevents all the "add on objects" from just getting created by the master after cluster creation.

cc @cjcullen

**Comment by erictune** [comment]
@thockin

**Comment by thockin** [comment]
I am torn on this one.  I am not actually convinced that we should be
opening firewall rules at all.  I understand this becomes "friction", but
tat the same time, it is a liability that we're opting users into.  I want
to fall on the side of caution.

@vishh @satnam6502 - what if we didn't open firewall rules by default, but
just printed a link or instructions or something?

**Comment by satnam6502** [comment]
We would have to print different instructions for each provider, right?
Sure, we could print the instructions or even generate a script that the user could run or modify and run.
Not such a great out of the box experience, but perhaps the least worst option right now.

**Comment by satnam6502** [comment]
Also, note that right now the cluster level logging prints out a URL for the log information that can be accessed by anyone (it is not username/password protected like the monitoring dashboard). This is a temporary measure while the service proxy route is worked out / implemented but we should be aware of the issues this poses.

**Comment by thockin** [comment]
I am just concerned that a bug or 'sploit in one of these services would be
really bad, especially if the user did not realize it was exposed.

**Comment by zmerlynn** [comment]
It's already bad. :/ The master has the scopes to do it today, there's not
a whole lot stopping a dedicated attacker. Is your argument that you're
giving them a faster playbook?

**Comment by zmerlynn** [comment]
Oh, sorry. In one of the exposed services, not an attack on the master
itself.

**Comment by vishh** [comment]
@thockin: In the case of monitoring a firewall rule would not be necessary if the apiserver proxy were to be working for Grafana. What is our long term answer to user facing applications?

**Comment by thockin** [comment]
Long term it needs to be relatively simple, but I don't know how far
outside the kubernetes cluster boundary we want to reach.  Firewall is
pretty far outside.

**Comment by erictune** [comment]
If I don't have an external load balancer, and I just want to expose a service to the internet, should I be able to do that?  If so, won't I need to add a firewall rule for that?  How is a firewall rule a different security story than automatically creating an external load balancer?

**Comment by zmerlynn** [comment]
+1 to Eric's question. It's actually weird that we do one and not the other.

**Comment by alex-mohr** [comment]
I think this is a great case where a specific example would help.  What would it take to use Kubernetes to run a public web server on e.g. GCE or AWS?  If Kubernetes exposes config for load balancers, it would seem odd to exclude required dependencies.

**Comment by thockin** [comment]
Opening firewall for loadbalancers is one thing.  Opening firewalls for
anything else is suspect, IMO

**Comment by thockin** [comment]
I don't think we should automatically open firewalls unless the user has explicitly asked for external access.

Retargetting this bug to mean "stop doing that" - @vishh @satnam6502 @zmerlynn can we ensue that nobody is doing this?

**Comment by zmerlynn** [comment]
We automatically open firewalls in kube-up.sh for both monitoring and
logging today. Are you proposing that we claw that back, since it may not
be what the user wants, or that we document the heck out of the fact that
they're opening up service ports, or what?

**Comment by satnam6502** [comment]
So you mean the step in the cluster level logging that sets up a firewall should be removed? From cluster/gce/util.sh:
```
function setup-logging-firewall {
  # If logging with Fluentd to Elasticsearch is enabled then create pods
  # and services for Elasticsearch (for ingesting logs) and Kibana (for
  # viewing logs).
  if [[ "${ENABLE_NODE_LOGGING-}" != "true" ]] || \
     [[ "${LOGGING_DESTINATION-}" != "elasticsearch" ]] || \
     [[ "${ENABLE_CLUSTER_LOGGING-}" != "true" ]]; then
    return
  fi

  detect-project
  gcloud compute firewall-rules create "${INSTANCE_PREFIX}-fluentd-elasticsearch-logging" --project "${PROJECT}" \
    --allow tcp:5601 tcp:9200 tcp:9300 --target-tags "${MINION_TAG}" --network="${NETWORK}"
}
```

**Comment by thockin** [comment]
I am suggesting we stop doing that, and instead print something to the
effect of "you may need to open the firewall for this to be useful".

Argue with me?

**Comment by satnam6502** [comment]
Very poor user experience.

**Comment by vishh** [comment]
+1 to Satnam's comment. How about providing an option to disable opening
firewalls automatically?

**Comment by thockin** [comment]
Only of the default is closed.  We currently open 6 ports to all minions.  I have no indication of the security of those 6 ports or even what they are for.  This represents a real risk, I think, and I would rather err on the side of caution.

@brendandburns  seemed to be in agreement.  @bgrant0607 or @jbeda or @alex-mohr care to weigh in?  It's a trade-off of friction vs safety.

**Comment by brendandburns** [comment]
I actually think that using the master as uber proxy is the right answer
for this.

Don't open firewalls, use the master's auth for security and single point
of access.

**Comment by satnam6502** [comment]
Yes, that would be great, and I've always viewed the firewall as a temporary solution.

**Comment by vishh** [comment]
The proxy through the master has never worked for Grafana. +1 for the proxy
being a long term solution.

**Comment by erictune** [comment]
Needed if proxy is long term solution: #2380

**Comment by erictune** [comment]
Related:
Expose externally proxied service addresses #2382

**Comment by bgrant0607** [comment]
Some kind of [VPN](https://cloud.google.com/compute/docs/vpn) is probably part of the long-term solution.

I'm fine with using /proxy for cluster add-on services in at least the short/medium term. That would also (theoretically) allow us to enforce namespace-level visibility for the add-ons.

Other third-party services need external IPs.

**Comment by alex-mohr** [comment]
There seem to be two issues here.  One is that firewall rules and routes are created by kube-up.sh but some think that should be moved into k8s -- I totally agree with that because the current approach isn't amenable to k8s monitoring its dependencies and reporting whether those are healthy, and it doesn't play well with an upgrade story.  Regardless of what we do for logging and monitoring, we'll still have to configure those.  The other is whether we should require default logging and monitoring in particular to use a proxy or whether they can be directly available.

I don't think we need to re-invent auth and firewalls and only allow proxied access to some services as part of core kubernetes.  That's a platform story, not an IaaS story, which means it must be possible for users to directly connect to such things without going via a master proxy.  IMO, we must allow users to configure both intended-to-be-externally-accessible services and loadbalancers to actually be so via k8s, and it's k8s's job to coordinate the underlying infrastructure provider's objects into doing that.

Potentially related: if we want to configure some form of default monitoring and logging, we should use the same facilities available to customer-provided forms of those things.

I still haven't seen a concrete example, so I acknowledge my comments above are philosophy unburdened by reality.  But I suspect that if we take as requirements (a) service Foo must be externally accessible and (b) service Foo can use whatever protocol/auth/transport it wants, we end up with something where there's either a flavor of service or an equivalent-to-bool makeExternallyAddressable: t/f somewhere, which seems both reasonable and expedient to me.

**Comment by vishh** [comment]
Monitoring setup does not create firewall rules anymore. Monitoring services can now be accessible via the proxy on the api server. 
I believe @satnam6502 has done similar changes to logging. I will let him confirm that.

**Comment by vishh** [comment]
I am closing this issue. Re-open if there is more to this issue in addition to removing firewall configs from kube-* scripts.

**Comment by satnam6502** [comment]
Yes, cluster logging now uses the proxy path and does not create ELBs or firewalls.
