### ISSUE TITLE
Round robin load balancer can overwhelm first pod behind service

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/kubernetes#3640]
This is particularly easy to do with a new cluster.

Create a service `S` and deploy `N` pods behind it. Start up `M` pods which create a persistent connection to service `S`.

Because the round robin load balancer always starts at the 0th endpoint, and the endpoint list is consistent cluster-wide, you will see that you now have `M` connections to Pod 1, and 0 connections to all other pods 2 through N.

Perhaps the the round robin load balancer should start off at a random index [0,N) when the list of endpoints changes.

(Concretely: we had 3 instances of twemproxy behind a "redis" service, fired up a bunch of worker pods (which happen to connect once, do all of their work, then exit), and each worker pod connected to the same instance of twemproxy, with the other 2 remaining completely idle.)

**Comment by smreed** [comment]
I'm working on a PR for this, and the unit tests need a ton of changes. Before I spend too much time, does this seem like a decent solution? Or would the project maintainers rather solve this in another way?

**Comment by bgrant0607** [comment]
I'd go farther and suggest the list be randomly shuffled.

**Comment by bgrant0607** [comment]
http://golang.org/pkg/math/rand/#Perm

**Comment by smreed** [comment]
Sounds good. I'll give this a shot. The unit tests currently expect a specific order, they'll have to change to simply ensure each endpoint gets returned every round.

**Comment by smreed** [comment]
@thockin suggested in #3651 an alternative approach where the load balancer just chooses a random index into the slice.

Happy to submit another PR if that's the preferred approach but it would change the way the LB works, allowing for two or more consecutive connections to the same pod.

**Comment by thockin** [comment]
It would be net simpler, but it would add some non-determinism for things like the service test, which assumes that it will get a hit to each distinct backend within a small number of queries to the service.

We could choose a random seed instead, but that still risks accidental phase-lock between nodes - do we think that is a problem?
