### ISSUE TITLE
Resolve the form of special "verbs" in the api for v1beta3

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#3652]
Currently, we support custom "verbs" such as proxy, redirect, and watch. These prefix the object paths, such as /api/v1beta1/watch/... (Note that proxy doesn't follow the actual path convention: api/v1beta1/proxy/minion/minion1:10250 -- note that minion is singular, and the port number.) See #3548 and #3612 for more examples. 

More verbs are proposed, such as stop (#1535), resize (#1629), and clone (#170).

In order to be more compatible with REST/OO style, to simplify auth, and to facilitate discoverability and shardability, I propose we change these to SUFFIX api paths, in the standard collection/instance pattern. Something like: *object_path*/methods/verb_name. Note that some "verbs" (e.g., resize) require the ability to GET as well as POST, which is somewhat different than our REST objects.

@smarterclayton @lavalamp

**Comment by derekwaynecarr** [comment]
Doesn't this make the verb names invalid resource names?

For example,

/api/v1beta3/ns/default/pods/watch

Am I asking for a pod named watch or am I watching all pods in the default namespace?

Or maybe I misunderstand example, but if you are suggesting

/api/v1beta3/ns/default/pods/methods/watch


Am I watching for changes to the pod named methods or for all pods in namespace?

**Comment by bgrant0607** [comment]
@derekwaynecarr Fair point. Currently they conflict with object Kinds, which are less numerous and under our control. We could insert a character that couldn't be used in object names but is legal in URLs. For example:
`/api/v1beta3/ns/default/pods/~/watch`

That said, I have to admit that watch, proxy, and redirect have a very different flavor than stop, resize, and clone. Maybe it makes sense to handle them differently.

**Comment by smarterclayton** [comment]
I think having seen a lot of other attempts to make this work.... that treating them higher in the chain actually makes it cleaner in the long run.  They look a bit out of place, but if HTTP clients and servers supported truly flexible verbs we would use them for this.  In the meantime, ns/foo/watch/pods is pretty clear.

----- Original Message -----

**Comment by bgrant0607** [comment]
Ok, I'm fine with that. Thanks.

**Comment by smarterclayton** [comment]
Thinking about bindings, ideally you name the last segment of the path the resource type you are posting.  In this case a pod can have only a single binding, so you are `POST /pods/foo/binding`.  You can clone, restart, stop, start many times, so that's `POST /pods/foo/method/clone` or `POST /pods/foo/op/clone`

**Comment by smarterclayton** [comment]
I changed my mind about watch.  Starting to feel like that's a different mime type/query param on LIST and GET.  Proxy of wildcard never made sense (so that is going to always be a subresource).  Redirect can be a query param or subresources.

If we do that we don't need global verbs anymore.

**Comment by bgrant0607** [comment]
Yeah!

**Comment by derekwaynecarr** [comment]
I prefer the use of a query param.

**Comment by bgrant0607** [comment]
@derekwaynecarr A query param vs. what? And why?

**Comment by derekwaynecarr** [comment]
I prefer that a WATCH was done by the following:

```
GET /namespaces/namespace/pods?watch=true
GET /pods?watch=true
```
over
```
GET /namespaces/namespace/pods/watch
GET /pods/watch
```

It's closer to the behavior in etcd where I can convert any get/list query to a watch by passing ?wait=true

**Comment by bgrant0607** [comment]
That works for me.

**Comment by erictune** [comment]
Tell me if this is a correct summary of what was decided:
  - watch is not a special verb.  it is a content-type.  
  - the watch content-type is requested via a query paramter
  - resize, stop, and clone are special verbs.  They still go as the last path component.

**Comment by erictune** [comment]
Once this is settled, I need to figure out implications for mapping requests to policy verbs (#2877).

**Comment by smarterclayton** [comment]
They are resources - "pod/size" is a resource, with the verb "GET" (show me the current size) and "PUT" (change the current size).  So the verb would stay a verb, but the resource would be a different resource.  "pod" and "pod/status" are not the same resource.

----- Original Message -----

**Comment by smarterclayton** [comment]
Generic proxy would probably just be a path (non-API) while "pod/proxy", "service/proxy", "pod/logs" are all separate resources.

----- Original Message -----
