### ISSUE TITLE
services.sh e2e test is busted with Vagrant

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/kubernetes#3655]
It looks like the network is broken in some way that is non-obvious.  I spent most of a day digging in and without deeper OVS knowledge, I'm not sure what is going on.

Perhaps we want to switch to flannel here for networking?  It'd be simpler to set up.

I'm going to disable the test for vagrant as part of #3530.

**Comment by thockin** [comment]
I ran into this same issue with the spanning-tree propagation delay in OVS.

**Comment by derekwaynecarr** [comment]
@smarterclayton - is Mrunal the right person to help here?

**Comment by smarterclayton** [comment]
Yes, or @rajatchopra

**Comment by derekwaynecarr** [comment]
This issue should be closed.  It was resolved.

**Comment by roberthbailey** [comment]
Thanks!
