### ISSUE TITLE
Announce that v1beta1 and v1beta2 are going away when v1beta3 is exposed by default

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3670]
it's impossible to GET replication controllers on v3. on v1 on the same server it works fine.

example request: GET on http://localhost:8080/api/v1beta3/replicationControllers returns 404

http://localhost:8080/api/v1beta1/replicationControllers returns 200

**Comment by derekwaynecarr** [comment]
v1beta3 moved to all lower case URL

Would give that a try first

**Comment by abonas** [comment]
looks like it's working. but it breaks backwards for clients who worked with v1. 
For instance, in my gem https://github.com/abonas/kubeclient I can't now smoothly work with both versions because I need to treat the name of the resource differently.
why don't at least redirect those who call replicationControllers to the lowercase too?
Also, there's no way to know which resources are available and their names.
A lot of REST api on their most top level at least publish the links to main resources, but if I call:
http://localhost:8080/api/v1beta3/ it returns 404

**Comment by smarterclayton** [comment]
Because we are actively trying to drop support for mixed case prior to 1.0, I did not continue supporting the old url paths.  If you look at the go client, we have a "legacy" flag we use to control this and a few other behaviors.

**Comment by abonas** [comment]
@smarterclayton well yes, but breaking backwards creates more work for the users... more "if this version ..." kind of stuff.

**Comment by smarterclayton** [comment]
We got v1bet1/2 wrong and don't want to carry it forever.  Stopping it early before v1 is our priority.

**Comment by abonas** [comment]
@smarterclayton ok :(
are the REST apis going through any kind of design review or code review?

**Comment by bgrant0607** [comment]
@abonas v1beta1 is really an alpha quality API. It grew organically and did not go through any kind of design review, as evidenced by the many issues you've filed. We want to get rid of it ASAP. We intend v1beta3 to be the "release candidate" for the v1 API, which will be the stable API.

As for knowing what exists, you can now browse `/swagger-ui` or GET `/swaggerapi/api/v1beta3`. Additionally, pull #3548 is in progress, and will return a list of valid paths to GET `/api/<version>`.

**Comment by abonas** [comment]
@bgrant0607  thanks. will check swagger for now
