### ISSUE TITLE
Random values for API types is duplicated

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3691]
We have a number of tests which randomize values for API types, and each of them has their own table of functions for "special types" that have limited valid values.

pkg/api/serialization_test.go
pkg/api/validation/schema_test.go
pkg/api/latest/latest_test.go

These should all get folded together.

**Comment by yujuhong** [comment]
I was going to grab this one, but found some code in serialization_test.go that I was unsure of (see #3890).
