### ISSUE TITLE
Rewrite update.sh end-to-end test in Go

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3694]
Part of issue #3130 
Re-write test in Go, generate unique names for top level resources, ensure test is idempotent, clean up all resources at end of test.

**Comment by zmerlynn** [comment]
I was just glancing at this test to see how crunchy it was to port. One of the sad things would be abandoning `kubectl rollingupdate`, so if we do port this, I think we should definitely go through the `RollingUpdater` to make sure it stays tested.

**Comment by roberthbailey** [comment]
That reminds me... @jlowdermilk Do we have an issue yet to add an e2e test to specifically test kubectl?

**Comment by jlowdermilk** [comment]
We do now: #4389

**Comment by roberthbailey** [comment]
Thanks.

**Comment by satnam6502** [comment]
I am unassigning myself from this for now. I expect to be working on the fixit for cluster level logging for several days so I'd rather not have this assigned to me while I can't give it attention. If it is still open later then I may try to take a crack at it.
