### ISSUE TITLE
Rewrite liveness.sh end-to-end test in Go

### ISSUE THREAD

**Issue by filbranden** [GoogleCloudPlatform/kubernetes#3696]
Part of issue #3130.

Re-write test in Go, generate unique names for top level resources, ensure test is idempotent, clean up all resources at end of test.

I'm taking this one now.

@satnam6502 @zmerlynn

**Comment by filbranden** [comment]
@rrati who is also interested.

**Comment by filbranden** [comment]
Implemented in #3715

**Comment by zmerlynn** [comment]
liveness.sh is still in tree. Are we happy with the Go test?

**Comment by filbranden** [comment]
I am :-)

As another added bonus, the Go test is using namespaces now so it's really unlikely to run into conflicts even for labels etc.

Any objections to removing the shell liveness.sh test?

**Comment by zmerlynn** [comment]
Nope. I'm sitting here itemizing the shell tests and comparing to remaining
#3130 subitems to make sure we have them all.

**Comment by ixdy** [comment]
We haven't removed the liveness.sh e2e test because the Go test is apparently not as reliable (#4501, #4406). Should we reopen this issue until the shell test is removed?

**Comment by roberthbailey** [comment]
The Go tests now appear to have the same reliability as the shell test, so I'm going to remove liveness.sh.
