### ISSUE TITLE
pod containers local network

### ISSUE THREAD

**Issue by Fandekasp** [GoogleCloudPlatform/kubernetes#3708]
Considering a controller running 2 replicas for a pod using a rabbitmq container and a webservice container. Let's say replica 1 has containers mq1 and web1, and replica 2 uses mq2 & web2.

How can I make sure that web1 will connect to mq1 and mq1 only ? using the service POD_SERVICE_HOST could redirect web1 to either mq1 or mq2.

Shouldn't there be an environment variable for containers within the same pod to see each other ?

**Comment by thockin** [comment]
The "variable" you want is "localhost".  Containers in a pod share a network namespace.

**Comment by Fandekasp** [comment]
got it, had forgotten about it. Thanks!

**Comment by bgrant0607** [comment]
localhost isn't working for some reason.

* connection error: http://sprunge.us/faeB
* pod: http://sprunge.us/ZbBN
* connection reset: http://sprunge.us/SBeb
* docker ps: pause exists: http://sprunge.us/UPfd
* rabbitmq log: http://sprunge.us/eOVh

**Comment by Fandekasp** [comment]
cloud provider: AWS
OS: CoreOS 557.0.0
Kubernetes v0.8.0

**Comment by thockin** [comment]
Docker inspect everything.

Run netstat inside the container?

How "localhost" could not work is beyond me.

**Comment by bgrant0607** [comment]
I get the connection failure even from within the rabbitmq container:
```
$ sudo docker exec 92165e4093d6 curl localhost:5672
curl: (56) Recv failure: ConnectiAMQP   on reset by peer
```

**Comment by bgrant0607** [comment]
netstat inside the rabbitmq container:
```
sudo docker exec cd08790de407 netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:41080         localhost:epmd          ESTABLISHED
tcp6       0      0 localhost:epmd          localhost:41080         ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
```

**Comment by bgrant0607** [comment]
```
sudo docker exec cd08790de407 netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:15672                 *:*                     LISTEN     
tcp        0      0 *:25672                 *:*                     LISTEN     
tcp6       0      0 [::]:amqp               [::]:*                  LISTEN     
tcp6       0      0 [::]:epmd               [::]:*                  LISTEN     
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
```
curl localhost:15672 works. This container isn't listening on 5672.

**Comment by bgrant0607** [comment]
The rabbitmq log says:
```
=INFO REPORT==== 22-Jan-2015::07:38:48 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 22-Jan-2015::07:38:48 ===
Management plugin started. Port: 15672
```
Note that the [ampq protocol](http://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) isn't http, so I wouldn't expect curl to work on the message queue port.

Port 25672 is apparently RABBITMQ_DIST_PORT.

Not sure why rabbitmq is not listening on 5672 when its logs say it should be. Maybe the weird hostname we set?

**Comment by Fandekasp** [comment]
It seems like my problem was unrelated. My script was doing a basic_ack to the wrong rabbitmq server, hence future messages couldn't be processed.

I think we can close this ticket again

**Comment by bgrant0607** [comment]
Glad you figured it out.
