### ISSUE TITLE
Go tests share one client causing rate limits to be exceeded

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3710]
The Go end to end tests share one client and this often causes the rate limits to be exceeded and the end to end tests to fail (the shell tests have a client per invocation of `kubectl`). We should change the Go tests to use a fresh client for each test. This would also help to identify individual tests that exceed rate limits. Related to #3667 @bgrant0607 @filbranden @zmerlynn @roberthbailey

**Comment by roberthbailey** [comment]
@satnam6502 has this been done? Are the rate limits applied via the Go clients or on the server side?

**Comment by satnam6502** [comment]
The rate limits are applied by the server. So, actually, using separate clients does not make a difference (w.r.t. limits).

**Comment by satnam6502** [comment]
But yes, I changed the tests in #3720 to use a fresh client. We can keep doing this -- or revert to a shared client. I don't think it makes much of a difference.

**Comment by zmerlynn** [comment]
I don't think the tests should recycle the client - the existing way is fine.
