### ISSUE TITLE
clarifications needed on REST v3 node entity

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#3711]
I'd like to get clarification on the following json sections representing a node:

  "spec": {
    "capacity": {
      "cpu": "1",
      "memory": "3Gi"
    }
  },
  "status": {
    "hostIP": "127.0.0.1",
    "conditions": [
      {
        "kind": "Ready",
        "status": "Full",
        "lastTransitionTime": null
      }
    ]
  }

1. what does 'spec' mean here? those are original parameters that the node was created with? not the current status?
2. why is there a section named conditions? conditions of what?
3. where there are 2 fields named status? a section named status and a field named status?
4. what does "status = Full" mean?
5. what does "kind = Ready" mean?
6. why the IP is part of the status and not a property of the node itself?

if any of the above are bugs, pls split them to a separate issue or let me know and I'll split them. 
thanks

**Comment by ddysher** [comment]
I'll update the docs. To answer your question:

1. 'spec' defines the attrubutes of a node, including the original params. it's not current status
2, 'conditions' describes the condition of the node, i.e. is it ready to schedule pod, can I reach the node, etc.  
3. They have different meanings, see below.
4,5.  'kind' specify the kind of condition, like Ready, Reachable, etc. and status means if the node is in that kind, e.g. {kind=Ready, status=Full} means node is ready and {kind=Ready, status=Non} means not ready.
6. IP can change, and there is public ip, private ip, dynamic ip (DHCP), etc, it makes more sense to be a status other a spec.
