### ISSUE TITLE
kube-down.sh fails on v0.9.0

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#3741]
The bug is in 'teardown-logging' function in cluster/gce/util.sh where the 'PROJECT' variable is undefined. 
_/tmp/0.9.0/kubernetes/cluster/../cluster/gce/util.sh: line 832: PROJECT: unbound variable_

This bug has been fixed on HEAD by #3620.

**Comment by satnam6502** [comment]
Do you mean `teardown-logging-firewall` ?
This has a `detect-project` call in it: so I am confused about why the project is not set?

**Comment by dchen1107** [comment]
@brendandburns Should we patch 0.9 release with the fix for this issue too?

**Comment by dchen1107** [comment]
Also shouldn't this failure detect by e2e test?

**Comment by zmerlynn** [comment]
I actually requested a cherry pick of #3601 (for GKE), which would also fix this, yes?

**Comment by vishh** [comment]
@satnam6502: Look at the version of gce/util.sh released as part of v0.9.0.
@zmerlynn: Yup. #3601 should fix it.

**Comment by zmerlynn** [comment]
@brendanburns: I know you're OOO, but okay to cherry-pick #3601 for 0.9.1?

@dchen1107: It should be caught by e2e. I'm not clear what's going on there, and was a little mystified as to why it was working when I changed it. (I assumed it was getting picked up by a sourced script from previously.)

**Comment by goltermann** [comment]
Already in 0.9.1.
