### ISSUE TITLE
Remove master ip cache or stop querying cloudprovider

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#3750]
Master used to cache ip address of node, to update pod.status.hostIP; and when cache expires, it is refreshed by querying cloudprovider.

We should stop querying cloudprovider and just get node status; or better yet, remove the master ip cache if necessary.

**Comment by bgrant0607** [comment]
As discussed in #2726 and maybe elsewhere, we should never evict anything from our "caches". This state should be stored in etcd and refreshed periodically.

**Comment by ddysher** [comment]
Yes, but it doesn't make sense to just cache ip, which is only part of node status now.

At least, we should stop querying from cloudprovider, and instead, querying from etcd to refreshe periodically.
