### ISSUE TITLE
Swagger using type where $ref should be used

### ISSUE THREAD

**Issue by iantw89** [GoogleCloudPlatform/kubernetes#3756]
'type' is used in place of '$ref' when referring to models within a Json Schema 'properties' section.

**Comment by iantw89** [comment]
Repro:
Use the steps outlined here to stand up a cluster on GCE: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md

View the swagger docs at https://{kubernetes master}/swaggerapi/api/v1beta2
An example of this issue can be found at line 2547

**Comment by bgrant0607** [comment]
This can now be viewed statically here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/gh-pages/swagger-spec/api/v1beta1/index.html

**Comment by bgrant0607** [comment]
The Swagger spec discussing this is confusing, as it says that a type may refer to a model id.

However, in describing "property objects", it says that `$ref` is required:
https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#529-property-object

It looks like `$ref` is chosen over `type` only in the case of an array:
https://github.com/emicklei/go-restful/blob/master/swagger/model_builder.go#L180

If we want different behavior, we'll need to file an issue on go-restful (or submit a PR).

**Comment by brendandburns** [comment]
Fixed by #5938
