### ISSUE TITLE
Swagger using $ref where type should be used

### ISSUE THREAD

**Issue by iantw89** [GoogleCloudPlatform/kubernetes#3757]
When an array contains primitives, '$ref' is referring to Json primitives where 'type' should be used.

**Comment by iantw89** [comment]
Repro:
Use the steps outlined here to stand up a cluster on GCE: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md

View the swagger docs at https://{kubernetes master}/swaggerapi/api/v1beta2
An example of this issue can be found at line 2604

**Comment by dchen1107** [comment]
@nikhiljindal Could you take a look at this one?

**Comment by nikhiljindal** [comment]
Apologies for not looking at this earlier.
The swagger spec has changed a lot since then and I am not sure now what was at line 2604 then.
@iantw89 Can you please post a snippet or a screenshot of the spec that you are referring to.

**Comment by iantw89** [comment]
Hi Nikhil,

Sorry for the delay. One can find it by looking at the 'models' section in any swagger API document. https://{kubernetes_master}/swaggerapi/api/v1beta1 (or v1beta2, etc).

It looks as though array element types are always specified by $ref and non-array properties are always specified by 'type'. $ref is intended to be used for non-primitive, schema-defined types while type indicates primitives.

I think this is a problem in the library being used to generate the swagger docs. Perhaps this is fixed by the library update you made just an hour ago...

**Comment by nikhiljindal** [comment]
Yes. This will be fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/5938
Thanks!

**Comment by iantw89** [comment]
Rock on!
