### ISSUE TITLE
etcd-waiter.service "not-found"

### ISSUE THREAD

**Issue by rAy82** [GoogleCloudPlatform/kubernetes#3762]
Hello,
I've just finished building a CoreOS cluster using the new cloud-config files and the latest stable version of CoreOS (522.5.0). I noticed that in the master.yaml there is a "write_files" command to write a waiter.sh file in /opt/bin directory and after there is a definition for etcd-waiter.service, that will using that file.
I have 2 problems:
- after the boot I can't find any waiter.sh file in /opt/bin
- entering the command "systemctl status etcd-waiter.service" results in:
"Loaded: not-found (Reason: No such file or directory)   Active: inactive (dead)"

Looking at the etcd-waiter.service definition in master.yaml I look at its dependencies and I see that:
        Wants=network-online.target
        Wants=etcd.service
        After=etcd.service
        After=network-online.target
        Before=flannel.service
        Before=setup-network-environment.service
How can it be executed BEFORE setup-network-environment.service and AFTER etcd, if etcd REQUIRES setup-network-environment.service?

Please be patient with me, I'm new in Linux world but I'm really interested in kubernetes and its potential. Thanks.

**Comment by dchen1107** [comment]
cc/ @kelseyhightower any idea?

**Comment by erictune** [comment]
@pires just changed this in #3639 or #3556

**Comment by pires** [comment]
Even though it seems @rAy82 is right about the misleading entry ```Before=setup-network-environment.service```, CoreOS should have written that file to the filesystem. But it didn't. So it should be something else. May I ask you to try this with beta or alpha version of CoreOS and let me know?

**Comment by rAy82** [comment]
You're right, those are two distinct problems.
I've installed a fresh master VM running the latest CoreOS alpha release (571.0.0) but nothing seemed to have changed: no waiter.sh file or even /opt/bin directory. But these weren't the only things that the system wasn't writing... look at this:
![immagine](https://cloud.githubusercontent.com/assets/8778205/5930262/ab85a3d4-a68d-11e4-8af9-5d58790be03d.png)
The system wasn't writing any of the unit from the cloud-config. Then I tried to remove the three hyphens at the beginning of the master cloud-config, rebooted... et voilà!
- /opt/bin directory created and waiter.sh file in it
- all the units correctly written on the system
BUT...
all the processes are inactive
![immagine2](https://cloud.githubusercontent.com/assets/8778205/5930514/c20d2002-a690-11e4-90ca-f078ca74aba9.png)
seeing the dependencies between all the processes, it seems to depend on the network-online.target that has not started (I don't know why). The only thing I could verify is that entering the "systemctl restart systemd-networkd" command the network-online.target starts and so all the other processes start automatically.
Putting all together:
- it seems that the three hyphens at the beginning of the cloud-config were preventing the system to parse the whole config file
- the network-online.target unit does not start automatically within the system boot
- the 
I hope that my analysis will be useful to help solving my issues

**Comment by pires** [comment]
Where are you assembling your CoreOS cluster? I've just tested this successfully both with Vagrant and GCE.

**Comment by pires** [comment]
Could it be that the files weren't downloaded because of some networking issue? Kubernetes binaries and some helpers like ```setup-network-environment``` are always downloaded? Or could it be that when you SSH to the node the files are not yet written? Not sure.. but this seems like a VM provisioning issue rather than Kubernetes or the provided cloud-configs.

**Comment by rAy82** [comment]
I'm testing the coreos cluster with kubernates on two distinct and separated environments: a bare-metal coreos cluster in my office and a VMware Workstation environment with coreos VMs to test kubernetes when I'm not at work.
The issue has been opened because of my problems on my VM platform, but I'm having the same issue with network-online.target on both the environments. That prevents the other processes to start and therefore to download the various components, unless I restart the systemd-networkd process.
I don't think this issue could be due to a real networking problem because even though the network-online.target is inactive, I can ping internet URLs without any problem.
I exclude that the files are "not ready" when I ssh to the machine, because I wait some minutes but the situation doesn't change.
I'll try focus my tests on the conditions on which the network-online.target starts on not: have you some info on it?
Perhaps that argument is going out of topic, should we close that issue and open a new one?

**Comment by pires** [comment]
Not sure how to proceed since many things may be happening in your environments that are out of scope of this project. Also, I've got no access either to VMware or bare-metal CoreOS.

I'd recommend you to try out a Vagrant solution that I do maintain (https://github.com/pires/kubernetes-vagrant-coreos-cluster), or GCE or AWS, and close this issue.

**Comment by rAy82** [comment]
Ok, thank you for your help.
