### ISSUE TITLE
Return resources in deterministic order

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#3772]
kubectl returns resources in a random order, which makes it hard to look for things when users have a lot resources.  Returning resources in deterministic order should be a helpful and trivial change (hopefully).  

We have an issue about pagination #2349, but that's a larger and separate issue.

**Comment by smarterclayton** [comment]
We should be cause to not do this on the * namespace - I think thats a special case.  No disagreement for other list calls

**Comment by derekwaynecarr** [comment]
What is the default etcd response order?  Last created or last modified?

**Comment by ddysher** [comment]
I think the order is by key if sort param is given.  If not given, the order is by last created (maybe, but we shouldn't trust it).

It seems we are not trying to get sorted result from etcd.

**Comment by smarterclayton** [comment]
Today, I think it's random order in the child key space in etcd (because the node structure uses a map), so you get golang map iteration order without sort.  I don't know if sort on server is any cheaper than sort on client today, so we may want to do this in rest / registry rather than by passing etcd.

**Comment by ddysher** [comment]
Apart from performance, sorting in clients means we can also take control
of how responses are sorted, so for * namespace, we can sort by namespace,
then by resource ID.

On Sun, Jan 25, 2015 at 11:22 AM, Clayton Coleman <notifications@github.com>
wrote:

> Today, I think it's random order in the child key space in etcd (because
> the node structure uses a map), so you get golang map iteration order
> without sort. I don't know if sort on server is any cheaper than sort on
> client today, so we may want to do this in rest / registry rather than by
> passing etcd.
>
>
> > On Jan 25, 2015, at 9:55 AM, Deyuan Deng <notifications@github.com>
> wrote:
> >
> > I think the order is by key if sort param is given. If not given, the
> order is by last created (maybe, but we shouldn't trust it).
> >
> > It seems we are not trying to get sorted result from etcd.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/3772#issuecomment-71379535>
> .
>



-- 
*Deyuan Derrick Deng*
*Master of Electrical and Computer Engineering*
*Carnegie Mellon University*

**Comment by smarterclayton** [comment]
We can always hint sort to the registry storage layer in the future, so sorting on the client now won't kill us.

**Comment by ddysher** [comment]
Just took a closer look at our rest/registry code to implement the sort (in client), but implementation-wise, it seems much easier to pass sort to etcd (one line change).  Also, namespace is a prefix on resource, so sort across all namespace with etcd key will essentially sort resources by namespace then by Name.

If we are to implement sort on client side, we can either:
1. use sort package:
    1. have each list object, ie.e PodList, ControllerList, implement sort interface. (We won't do this).
    2. have ListMeta implement sort interface, if there is a way to find enclosing structs (so we can use items field)
    3. have api.Object implement sort interface, verify object is list before sorting.
2. implement sort algorithm ourself, and do it in rest.

Is there other golang or kubernetes idom that I haven't been aware of that can be applied to this use case?

**Comment by smarterclayton** [comment]
----- Original Message -----
> Just took a closer look at our rest/registry code to implement the sort (in
> client), but implementation-wise, it seems much easier to pass sort to etcd
> (one line change).  Also, namespace is a prefix on resource, so sort across
> all namespace with etcd key will essentially sort resources by namespace
> then by Name.

I think sorting it on etcd is fine for now - that's the simplest possible thing that works.

**Comment by derekwaynecarr** [comment]
Is there any material perf impact in etcd to enable it?

**Comment by smarterclayton** [comment]
Probably not material.  Can always switch away if necessary

**Comment by derekwaynecarr** [comment]
Famous last words :-)

**Comment by smarterclayton** [comment]
Got my hat ready
