### ISSUE TITLE
Rate Limiter has initialization race condition

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3773]
I've been looking into why the TestROService Go end-to-end test often fails with a rate limit error. It only makes one API call but it makes that call pretty much immediately:
```
func TestKubernetesROService(c *client.Client) bool {
	svc := api.ServiceList{}
	err := c.Get().
		Namespace("default").
		AbsPath("/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/services").
		Do().
		Into(&svc)
```
Now that a fresh client is created for each test, we can encounter a race where the channel used to represent tokens for service availability are not yet pre-charged before a client can make a call. Here is the code in handler.go that checks for tokens:
```
// RateLimit uses rl to rate limit accepting requests to 'handler'.
func RateLimit(rl util.RateLimiter, handler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if rl.CanAccept() {
			handler.ServeHTTP(w, req)
			return
		}
		w.WriteHeader(http.StatusServiceUnavailable)
		w.Header().Set("Retry-After", "1")
		fmt.Fprintf(w, "Rate limit exceeded.")
	})
}
```
The problem is the `cl.CanAccept()` can be called before the token channel is populated. The rate limiting is done in throttle.go and here are some relevant snippet.

First, the code that creates the ticker. This will insert tokens into the `ticker` channel at the QPS rate.
```
func NewTokenBucketRateLimiter(qps float32, burst int) RateLimiter {
	ticker := time.Tick(time.Duration(float32(time.Second) / qps))
	rate := newTokenBucketRateLimiterFromTicker(ticker, burst)
	go rate.run()
	return rate
}
```

The initialization will pre-charge the channel to provide a window in which a burst is permitted as long as the QPS is not violated over a window that is the size of the burst.
```
func newTokenBucketRateLimiterFromTicker(ticker <-chan time.Time, burst int) *tickRateLimiter {
	if burst < 1 {
		panic("burst must be a positive integer")
	}
	rate := &tickRateLimiter{
		tokens: make(chan bool, burst),
		ticker: ticker,
		stop:   make(chan bool),
	}
	for i := 0; i < burst; i++ {
		rate.tokens <- true
	}
	return rate
}
```
The problem is that there is a short period where neither the first tick nor the pre-charge have been executed but a request could already have been made -- which would be rejected (incorrectly) for rate limit reasons.

Hopefully the Retry-After PR #3704 that I submitted will mask this situation.
@filbranden

**Comment by brendandburns** [comment]
I don't actually see what the race condition is here, we fill up the channel with tokens before we return the rate limiter, so the channel has to be full of tokens to be used up.  How can the pre-charge not have finished, we run it in a for loop before we return the rate limiter?

**Comment by satnam6502** [comment]
Good point: I mis-understood the code to think that the rate limit could be accessed earlier -- but no -- it has to be returned before it is used. Which then makes the ROService behaviour even more mysterious. How can a test that makes exactly ONE API call run foul of the rate limiter? Will look more closely.

**Comment by satnam6502** [comment]
@brendandburns Let me explain a but more my confusion. This is where you return the rate limiter:
```
func NewTokenBucketRateLimiter(qps float32, burst int) RateLimiter {
	ticker := time.Tick(time.Duration(float32(time.Second) / qps))
	rate := newTokenBucketRateLimiterFromTicker(ticker, burst)
	go rate.run()
	return rate
}
```
What pre-charges the channel with tickeds? The goroutine that asynchronously runs `rate.run()` relative to this function. So I thought the returned rate could be used before the goroutine had a chance to fill up the channel.
