### ISSUE TITLE
kubelet balks at certain repo url formats in .dockercfg

### ISSUE THREAD

**Issue by tyrannasaurusbanks** [GoogleCloudPlatform/kubernetes#3797]
I'm running kubernetes on a private cloud in-conjunction with my company's quay.io repository and I've noticed that kubelet was failing create my pod templates because it was having auth issues when attempting to pull down images.
This confused me, since the .dockercfg I'd made available to kubelet was indeed being picked up by the process, and was working fine externally - by this I mean I could use it to manually pull down the same images ok.

Problematic .dockercfg:
```
{
"https://quay.io/v1/": { ... }
}
```

I thought the `v1` stood out so I checked quay.io's documentation, found no mention of it and so removed it
```
{
"https://quay.io/": { ... }
}
```

This .dockercfg continued to auth correctly with the docker client and also now allowed kubelet to create my pod templates. :+1: 

I'd expect to see consistency here: if a .dockercfg is good for manually pulling down images, then I'd expect it to also work for kubelet. Please shout or close this issue if there is a reason why this is not the case.

I'd like to try and submit a PR for this if I find time this week; I thought I'd raise this issue incase anyone stumbled upon this discrepancy in the meantime.

Ioan

**Comment by mattmoor** [comment]
It looks like the docker client uses whatever you pass to "docker login":
https://github.com/docker/docker/blob/0f5eba68fbe4904090532a709e7f3769059bc0aa/api/client/commands.go

Quay.io seems to document "docker login quay.io" (no v1), can you confirm this changes how it is written out?
http://docs.quay.io/solution/getting-started.html

That said, the way the DockerPuller resolves images should likely be reconciled with the logic here:
https://github.com/docker/docker/blob/8b95ad230e2ee76450ceb9a80aa8e942a56bb397/registry/auth.go#L451

Feel free to assign to me, and I'll try to submit a PR in the next few days.

**Comment by dchen1107** [comment]
@mattmoor, unfortunately I cannot assign it to you directly, but thank you for looking into this, and a PR is very welcome.

**Comment by mattmoor** [comment]
@bcwaldon FYI, since this is in the code for looking up a credential on the keyring.

**Comment by mattmoor** [comment]
FYI: https://github.com/GoogleCloudPlatform/kubernetes/pull/3813

**Comment by brendandburns** [comment]
Just merged the fix for this.  Closing.

**Comment by tyrannasaurusbanks** [comment]
Sweet, thanks @mattmoor :bow: :star:
