### ISSUE TITLE
Calling 'vagrant up' directly is not supported

### ISSUE THREAD

**Issue by maksym** [GoogleCloudPlatform/kubernetes#3798]
**Interacting with your Kubernetes cluster with Vagrant** section in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md has lines:

```
vagrant halt
vagrant up
```
responce is:
```
Calling 'vagrant up' directly is not supported.  Instead, please run the following:

  export KUBERNETES_PROVIDER=vagrant
  ./cluster/kube-up.sh
```

**Comment by derekwaynecarr** [comment]
Doc needs update.  Will submit a PR.

**Comment by JasonGiedymin** [comment]
Master has been updated. Shouldn't this be closed?

**Comment by derekwaynecarr** [comment]
Agree
