### ISSUE TITLE
Some resource files use `hostDIr ` directive

### ISSUE THREAD

**Issue by taisukeh** [GoogleCloudPlatform/kubernetes#3799]
`hostDir` was renamed to `hostPath` (https://github.com/GoogleCloudPlatform/kubernetes/pull/3517), but some resource files still reflect the old name as follows.

- cluster/saltbase/salt/cadvisor/cadvisor.manifest 
- cluster/saltbase/salt/fluentd-es/fluentd-es.manifest 
- cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.manifest 
- cluster/rackspace/cloud-config/minion-cloud-config.yaml

**Comment by thockin** [comment]
hostDir is still correct in the v1beta1 and v1beta2 APIs.  When we change to v1beta3 (#3671) we will fix this.

Closing as dup of #3671
