### ISSUE TITLE
The 'nodeSelector' doesn't work when a pod is created from replication controller's pod template

### ISSUE THREAD

**Issue by peter-braun** [GoogleCloudPlatform/kubernetes#3801]
It seem that the 'nodeSelector' functionality doesn't work when a pod is created from a replication controller's pod template.

I would need to separate set of worker nodes (let's say DB and service) to which two separate set of pods are supposed to be scheduled. So pods which carries out service logic goes to 'service' type of nodes, and DB goes to DB nodes.

Initially made two nodes:

    # kubectl get nodes
    NAME                LABELS              STATUS
    kube-node-1         nodetype=db         Ready
    kube-node-2         nodetype=srvc       Ready

I created replication controller. It includes the pod template from which the replication controller is supposed to create pods.

    # cat db-rc-2.json
    {
        "kind": "ReplicationController",
        "apiVersion": "v1beta3",
        "metadata": {
            "name": "db-rc",
        },
        "spec": {
            "replicas": 2,
            "selector": {
                "name": "db-pod"
            },
            "template": {
                "metadata": {
                    "creationTimestamp": null,
                    "labels": {
                        "name": "db-pod"
                    }
                },
                "spec": {
                    "volumes": null,
                    "containers": [
                        {
                            "name": "db-blocker",
                            "image": "db-blocker",
                            "memory": "5M",
                            "cpu": "500m",
                            "imagePullPolicy": "PullIfNotPresent"
                        }
                    ],
                    "restartPolicy": {
                        "always": {}
                    },
                    "dnsPolicy": "ClusterFirst",
                    "nodeSelector": {
                        "nodetype": "db"
                    }
                }
            }
        }
    }
    
    # kubectl create --api-version="v1beta3" -f db-rc-2.json
    
    # kubectl get rc
    CONTROLLER          CONTAINER(S)        IMAGE(S)            SELECTOR            REPLICAS
    db-rc               db-blocker          db-blocker          name=db-pod         2

I use API version v1beta3, because only this version of the API make it possible to specify `nodeSelector` in replication controller's pod template.

Despite of specifying the `nodeSelector` as `"nodetype": "db"` above, the replication controller seems to schedule the pod to the worker node with `nodetype=srvc` label as well.

    # kubectl get pod
    POD                                    IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
    0a890ab3-a574-11e4-812f-5254005f00dc   172.17.0.5          db-blocker          db-blocker          kube-node-1/        name=db-pod         Running
    0a892adb-a574-11e4-812f-5254005f00dc   172.17.0.63         db-blocker          db-blocker          kube-node-2/        name=db-pod         Running

Beside this, when I query back the replication controller I've just created, the result doesn't contain the `nodeSelector`.

    # kubectl get --api-version="v1beta3" -o json rc db-rc
    {
        "kind": "ReplicationController",
        "apiVersion": "v1beta3",
        "metadata": {
            "name": "db-rc",
            "namespace": "default",
            "selfLink": "/api/v1beta3/ns/default/replicationcontrollers/db-rc",
            "uid": "0a882a21-a574-11e4-812f-5254005f00dc",
            "resourceVersion": "186",
            "creationTimestamp": "2015-01-26T16:57:33+01:00"
        },
        "spec": {
            "replicas": 2,
            "selector": {
                "name": "db-pod"
            },
            "template": {
                "metadata": {
                    "creationTimestamp": null,
                    "labels": {
                        "name": "db-pod"
                    }
                },
                "spec": {
                    "volumes": null,
                    "containers": [
                        {
                            "name": "db-blocker",
                            "image": "db-blocker",
                            "memory": "5M",
                            "cpu": "500m",
                            "imagePullPolicy": "PullIfNotPresent"
                        }
                    ],
                    "restartPolicy": {
                        "always": {}
                    },
                    "dnsPolicy": "ClusterFirst"
                }
            }
        },
        "status": {
            "replicas": 2
        }
    }

Is this a feature or some nasty bug?

The version I'm using is quite recent:

    # kubectl version
    Client Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.1-dirty", GitCommit:"3623a01bf0e90de6345147eef62894057fe04b29", GitTreeState:"dirty"}
    Server Version: &version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.1-dirty", GitCommit:"3623a01bf0e90de6345147eef62894057fe04b29", GitTreeState:"dirty"}

Do you have any workaround to solve this issue?

Peter

**Comment by dchen1107** [comment]
@ddysher

**Comment by brendandburns** [comment]
My guess is that something is getting lost in the JSON parsing.  I'll try
to validate this in a unit test.

Sorry!
--brendan

**Comment by ddysher** [comment]
Yeah, that's likely the issue.  I can take a look if @brendanburns is not working on it.

**Comment by brendandburns** [comment]
I'm on it.

**Comment by brendandburns** [comment]
Ok, I think that I see one problem.  The replication controller manager (a system binary) uses v1beta1 to talk to the apiserver, not v1beta3, so the information is getting dropped from the replication controller subsystem.

If you set --api_version=v1beta3 on the kube-controller-manager binary, and reload it, (```/etc/default/kube-controller-manager```) that _may_ fix things.

However, you seem to be not even getting it out of the api server, which is kind of funny, I'll dig into that some more.

And I'll migrate the replication controller to use v1beta3

**Comment by bgrant0607** [comment]
It shouldn't be necessary for the controller manager to speak v1beta3. The nodeSelector field is present in v1beta1. The conversion logic must be broken.

**Comment by brendandburns** [comment]
It's not broken (exactly) it's an API mis-match.  nodeSelector is in Pod in
v1beta1, but the replication controllers deal in PodTemplates which don't
have NodeSelectors anywhere in there.  We could add it there, if we think
that's the right answer.

**Comment by bgrant0607** [comment]
Yes, that's the right answer.

**Comment by peter-braun** [comment]
Thanks guys for the quick response.

@brendandburns it seems it doesn't work if I set `--api_version=v1beta3` on kube-controller-manager.

    [root@kube-master v3]# systemctl status kube-controller-manager -l
    kube-controller-manager.service - Kubernetes Controller Manager
       Loaded: loaded (/usr/lib/systemd/system/kube-controller-manager.service; enabled)
       Active: active (running) since Tue 2015-01-27 08:52:30 CET; 5min ago
         Docs: https://github.com/GoogleCloudPlatform/kubernetes
     Main PID: 965 (kube-controller)
       CGroup: /system.slice/kube-controller-manager.service
               +-965 /usr/bin/kube-controller-manager --logtostderr=false --log_dir=/var/log/kubernetes --v=0 --master=http://kube-master:8080  --machines=kube-minion-1,kube-minion-2  --api_version=v1beta3

The symptom is the same.

By the way, a small comment: it's quite confusing that you use `--api_version` everywhere except for kubectl, where it is called `--api-version`. It would be nice to use the former option name there as well. Otherwise one should remember this exception.

**Comment by brendandburns** [comment]
Hey Peter,
This should now be fixed at head.  v1beta1 should support ```nodeSelector``` for replication controllers now.

Please let us know if it's not working.
--brendan

**Comment by brendandburns** [comment]
I filed:  https://github.com/GoogleCloudPlatform/kubernetes/issues/3839 to cover the --api-version flag

I believe the other issue is fixed, so closing.  Please re-open if that's not the case.
