### ISSUE TITLE
Manifest file format changes from 0.8.0 -> 0.9.0

### ISSUE THREAD

**Issue by bmo** [GoogleCloudPlatform/kubernetes#3815]
hostDir key seems to have changed to hostPath for volumes[].source; other possibilities for this object mentioned in error logs (like GitRepo, GCEPersistentDisk) are not detailed in the link to the currently-linked manifest format:

https://cloud.google.com/compute/docs/containers/container_vms#container_manifest

**Comment by brendandburns** [comment]
@thockin

**Comment by thockin** [comment]
hostDir is still correct in api v1beta1.  There was a short window after we
made the change to internal API but before we realized that the kubelet
file-reading code was bypassing the versioned->internal conversion during
which the 0.9 snapshot was cut.  We should maybe cherry pick that in.

Sorry for missing it.

@dchen1107 - who is driving 0.9 releases?

**Comment by roberthbailey** [comment]
@zmerlynn did the 0.9.1 release.

**Comment by zmerlynn** [comment]
@dchen1107 made a cherrypick-0.9 label, so maybe we should use it for 0.9.2.

@zmerlynn <https://github.com/zmerlynn> did the 0.9.1 release.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/3815#issuecomment-71593300>
.

**Comment by thockin** [comment]
#3701 is the fix

**Comment by zmerlynn** [comment]
@brendanburns: Are you handling the release? Saw the assign, didn't see the unassign. :)

**Comment by zmerlynn** [comment]
(I won't be able to get to it until tomorrow anyways.)

**Comment by brendandburns** [comment]
The fix was cut into 0.9.2, closing
