### ISSUE TITLE
Add a shutdown timeout config setting for replication controllers 

### ISSUE THREAD

**Issue by epsniff** [GoogleCloudPlatform/kubernetes#3819]
We have a service we would like to move to k8s but it takes one minute to shutdown.   This could be an issue with the current replication controller's logic,  because the k8s call to [dockerclient's StopContainer](https://github.com/GoogleCloudPlatform/kubernetes/blob/dd452461504ca373ca59dde2e667c50ae984e6fa/pkg/kubelet/kubelet.go#L864), has the stop timeout hardcoded at 10 seconds.  

As a feature request would it acceptable to add a shutdown timeout field to the ReplicationController's struct?  

Ref: [Replication Controller resize code](
https://github.com/GoogleCloudPlatform/kubernetes/blob/fd52ba96cef160c64bcb9492886e34d1e915314f/pkg/controller/replication_controller.go#L188)
[StopContainer code in the go-dockerclient](https://github.com/fsouza/go-dockerclient/blob/d19717788084716e4adff0515be6289aa04bec46/container.go#L390)

**Comment by epsniff** [comment]
FYI: could try putting together a patch for it, if others don't have the time.

**Comment by brendandburns** [comment]
Please note that we have a PreStop lifecycle hook.  That should get called prior to the pod being stopped, and it should block stopping until it is complete.  Will that work for you?

**Comment by epsniff** [comment]
That looks like it could work.   Is it safe to kill the `entrypoint` process within the PreStop Hook?  If so we could write a script that sends a SigTerm signal and handle the timeouts our self.   Im hoping there isn't a race condition here the replication controller starts up new pods, because the process died during PreStop.

**Comment by epsniff** [comment]
So after some discussion we are pretty sure the `PreStop` hook will work for us.    Thank you! 

FYI: The serivce in question uses a distributed task managment framework called [metafora](https://github.com/lytics/metafora).   We decided we're going to add a `drain` command to the framework so it signals a node to: a) stop taking new tasks, and b) start releasing tasks back to the task pool.   After the `PreStop` hook returns, the node should be sitting there with no work waiting to be killed.

**Comment by bgrant0607** [comment]
Actually, I think we should make the sigterm timeout configurable eventually, for applications that already use sigterm for graceful termination.
