### ISSUE TITLE
Username and password for default azure setup

### ISSUE THREAD

**Issue by nterry** [GoogleCloudPlatform/kubernetes#3828]
So I have now successfully created a default azure kube setup, but I cannot log into https://kube-366aa00.cloudapp.net/api/v1beta1/pods?namespace=default or anything else as it is prompting for a username and password. I have no clue what these default to...

Also, ive imported the azure.pem cert to my login keychain and given it always trust permissions, (im using OSX) but i still get the following error:

    x509: certificate signed by unknown authority

Any ideas?

**Comment by nterry** [comment]
Sweet, after some more code-perusing, I found the .kubernetes-auth file in my local machine's user's $HOME directory.... But what about the cert issues?

**Comment by roberthbailey** [comment]
Are you trying to log in with your web browser? Have you run kubectl against your cluster to see if it can connect?

**Comment by nterry** [comment]
i get the 
    x509: certificate signed by unknown authority
error when i use kubectl

**Comment by roberthbailey** [comment]
The kubernetes api server uses a self signed certificate, and kubectl should be checking the certificate when connecting to it. If you look at your .kubernetes-auth file, does it reference a certificate file (in addition to containing the username/password)?

**Comment by nterry** [comment]
nope

**Comment by roberthbailey** [comment]
If you want to bypass certificate checking in kubectl, you can pass --insecure-skip-tls-verify=true on the command line. This doesn't solve the underlying issue, but will at least allow you to make progress.

**Comment by roberthbailey** [comment]
By the way, this is the part of the cluster initialization that should be copying the cert files down from the azure VMs: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/azure/util.sh#L439

**Comment by nterry** [comment]
Right, but i want certs. Whats the missing key for the auth file. My file is thus:

    {   
      "User": "admin",
      "Password": "illNeverTell"
    }

**Comment by roberthbailey** [comment]
Does ${HOME}.kubecfg.crt exist?

**Comment by roberthbailey** [comment]
Can you run those ssh commands manually (maybe without redirecting stderr to /dev/null so that you can see if they work properly)?

**Comment by nterry** [comment]
yep, but its empty

**Comment by nterry** [comment]
So i manually ssh'd and scp'd the files down and set the values in my auth file. Any clue as to why it failed the first time?

**Comment by roberthbailey** [comment]
Unfortunately I don't. I'm not very familiar with the azure start up scripts or the reliability of scp'ing files down from VMs (as an aside, all of the provider implementations can fail on the scp step and leave you in this state -- that should definitely be fixed, hopefully by doing something better than scp rather than just wrapping it in retries).

**Comment by nterry** [comment]
right... well, so far ive got a working instance.... so yay!!!!! ill look into this tomorrow. Thanks for the quick replies!

**Comment by roberthbailey** [comment]
Sure... feel free to look for help on IRC tomorrow if you get stuck.

**Comment by nterry** [comment]
What's the url for irc?

**Comment by roberthbailey** [comment]
We hang out on the [#google-containers channel on freenode.net](http://webchat.freenode.net/?channels=google-containers)

**Comment by alex-mohr** [comment]
Closing for now; please do reopen if there's anything else you'd like us to look into or answer.
