### ISSUE TITLE
kubectl doesn't handle creating nodes properly...

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#3831]
It forces the namespace to be 'default' when nodes have no namespace.

We need to special case the handling of Nodes in kubectl.

**Comment by derekwaynecarr** [comment]
I am working on a solution for handling resources that have a cluster scope versus a namespace scope differently on both server and client as prereq to #3613.

**Comment by jlowdermilk** [comment]
Fixed by #3944
