### ISSUE TITLE
Error handling for services that don't match ports on containers is opaque.

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#3838]
We allow ContainerPort to be empty, but this integrates poorly with Pods that have no explicit Ports.  It's hard to validate a priori, since the ports may not exist.

We should at the very least throw some errors into the event log.

**Comment by thockin** [comment]
I propose to change the semantics - if you omit the destination port in your service, we should use the same port as your service port.

**Comment by bgrant0607** [comment]
@brendandburns @thockin Was one of you planning to work on this?

**Comment by thockin** [comment]
I'll wrap this up in the service reorg work IF we can come to a decision about compat.  Basically, if we change this we are breaking compat.

**Comment by brendandburns** [comment]
This was fixed by #4801
