### ISSUE TITLE
Improper reference to Kind versus Storage Path

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#3864]
admission control and authorizer
both provide an attributes record that has a GetKind() operation.

They are actually returning the ResourcePath used in URLs, and not meta.Kind().

We should update each interface to avoid confusion to either return Kind as reflected in meta.Kind (i.e Pod) or relabel it StoragePath (pods).

I think for Admission Control, I want to make both fields available in case we support different semantics if post a Pod to /pods differently than if you post a Pod to /podstatuses

Handlers utility function KindAndNamespace is also inconsistent in terminology.  That function should actually be renamed StoragePathAndNamespace

@erictune @deads2k @smarterclayton

**Comment by etune** [comment]
@derekwaynecarr I think you meant to mention @erictune instead of me.

**Comment by smarterclayton** [comment]
Are we passing the api version with the resource path (or kind)?  Because both need to be present for either value to mean anything

**Comment by derekwaynecarr** [comment]
Fixed in #3931
