### ISSUE TITLE
The container.env doesn't work correctly

### ISSUE THREAD

**Issue by zbhlove100** [GoogleCloudPlatform/kubernetes#3865]
I use kubenetes to run a mysql server,and I want to set the root password.
With docker I set -e MYSQL_ROOT_PASSWORD=xxxx.
Here is my  configure file used in kubernetes:
{  
  "id": "mysql",  
  "kind": "Pod",  
  "apiVersion": "v1beta2",  
  "desiredState": {  
    "manifest": {  
      "version": "v1beta2",  
      "id": "mysql",  
      "containers": [{  
        "name": "mysql",  
        "image": "dockerfile/mysql",  
	"ports": [{  
          "containerPort": 3306,  
          "hostPort": 3306  
        }],
	"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"xxxxxx"}]
      }]  
    }  
  },  
  "labels": {  
    "name": "mysql"  
  }  
}  
But ,after the pod have been created mysql doesn't have a password.

I use docker exec to look into the pod.I find the $MYSQL_ROOT_PASSWORD is there.
So why during mysql installation it can't get $MYSQL_ROOT_PASSWORD.

**Comment by bgrant0607** [comment]
What do you mean "during mysql installation"?

If you `kubectl get pod mysql`, does it show you the environment variable?

You can also take the containerID from the containerStatus and do `docker inspect` on the node to see whether the variable is passed to Docker.

**Comment by zbhlove100** [comment]
I use the official mysql repository in docker hub.
I only use docker with the command:
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=xxxxx -d mysql.
Dcoker will start a mysql database and set the root's password to xxxxx.

If I use kubernetes with the configuration I'v posted.
kubernetes will start amysql database but the root have no password.

And I  do docker inspect on the node,the variable have been padded to Docker.

**Comment by thockin** [comment]
After you create the pod, if you do ' kubectl get -o json pod [name] ', do
you see then env var?

**Comment by zbhlove100** [comment]
Yes,do ' kubectl get -o json pod [name] ' then I can see what I'v set to env.

**Comment by thockin** [comment]
So it's getting set, but your process can't getenv() on it?  Is that right?

Next debug step would be to log into the machine it is assigned to and run
'docker inspect' on the container and see if the env var is there.

**Comment by bgrant0607** [comment]
@thockin See https://github.com/GoogleCloudPlatform/kubernetes/issues/3865#issuecomment-71958581

**Comment by thockin** [comment]
Ahh.  I missed that.  So the variable is passed to docker?  With the correct value?  What does it mean to not have the password - the variable is there, unless docker is broken.

Does your mysql have a shell in the image?  You could `docker exec -ti [container id] /bin/sh` and look at the environment yourself...

**Comment by zbhlove100** [comment]
I think maybe you need to have a look at the official mysql dockerfile.Here parts of it:

    ENTRYPOINT ["/entrypoint.sh"]

    EXPOSE 3306
    CMD ["mysqld"]

It use entrypoint.sh to do something.
Here is part of entrypoint.sh:
    
    CREATE USER 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' ;

It should create user root with password.
-----------------------------------
Answer your question:
After use kubenetes to create the pod.I use 'docker exec -ti [container id] /bin/sh' to login the docker.
' echo $MYSQL_ROOT_PASSWORD ' can get the environment.

**Comment by thockin** [comment]
So you have confirmed that the environment variable is present and
available.  What's the problem?

**Comment by zbhlove100** [comment]
Emmm....
Sorry,Maybe my words mislead you.
First,kubernetes works fine.It set the environment variable.
What I want to discuss with you is I think it  doesn't work at the right time.

My purpose is use the environment variable in entrypoint.sh,but can't get it.
I curious about when did kubernetes set the environment.

**Comment by zbhlove100** [comment]
Ohhhhh.......I'm sorry.
I've made a so stupid mistake.
Thank you for your patiently answers.

**Comment by thockin** [comment]
Whew, I was starting be worried that there was something DEEPLY broken.

**Comment by bgrant0607** [comment]
What was it? Wrong variable name?

**Comment by suyuan1203** [comment]
@zbhlove100 I wonder what your 'stupid mistake' is? Did you forget to delete files on the persistent volume? I recently encounter the same problem.

**Comment by afshinm** [comment]
I have the same issues but removing / creating the pod doesn't help. Looks like Docker uses some sort of caching or something like this to avoid repeating some steps again.

**Comment by suyuan1203** [comment]
@afshinm removing/creating the pod will not remove anything on the persistent volume, which means the new mysql pod will load the old 'mysql data file' from the persistent volume, include the 'mysql.user' table which has the old username and password and that's why the 'ROOT_PASSWORD' env doesn't work. So you have to manually remove those files on persistent volume. It seems Kubernetes can automatically remove old files from persistent volume by some configuration.

**Comment by afshinm** [comment]
@suyuan1203 yeah correct, I remove the storage as well, I'm using Azure file storage.
