### ISSUE TITLE
Exec probe "success" - change it or document it

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3873]
It seems that exec probes must emit "ok" to be considered success, rather than return 0.  If this is what we really want, we should document it somewhere.

**Comment by brendandburns** [comment]
This is (was?) a limitation of docker exec, which didn't return the code.

Brendan

**Comment by bgrant0607** [comment]
The doc says it looks at exit status, so we need to fix one or the other.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/container-environment.md

**Comment by alex-mohr** [comment]
@dchen1107 for kubelet

**Comment by bgrant0607** [comment]
@vishh for exec

**Comment by dchen1107** [comment]
@vishh could you take a look at this? Feel free to re-assign it back to me.

**Comment by thockin** [comment]
FWIW the current behavior isn't SO bad, and it makes clear a failure in the
thing that probed vs a failed probe.  Just saying, we don't NECESSARILY
need to change it.

**Comment by vishh** [comment]
With docker 1.5 we can go back to using the exitCode instead of "ok"
string. OOM kills will also have special exitCodes in docker 1.5.

**Comment by brendandburns** [comment]
ok, I'm going to change the docs for now, we can change back when we standardize on 1.5...
