### ISSUE TITLE
Investigate log rotation for kube-proxy.log

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3879]
Currently we have log rotation for `/var/log/kubelet.log` @vishh reported that `/var/log/kube-proxy.log`  is causing problems. Are we sure that log rotation for `kube-proxy.log` is working?

**Comment by satnam6502** [comment]
@vishh reported problems with a cluster getting bricked because of this.

**Comment by satnam6502** [comment]
Hmmm... we should be truncating it...
```
/var/log/kube-proxy.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
```

**Comment by satnam6502** [comment]
And I do see it working on one of my nodes:
```
satnam@kubernetes-minion-1:/var/log$ ls
alternatives.log  debug.1     kern.log.2.gz        kube-proxy.log.2.gz  messages            syslog.2.gz
apt               dmesg       kubelet.log          kube-proxy.log.3.gz  messages.1          syslog.3.gz
auth.log          dmesg.0     kubelet.log.1.gz     kube-proxy.log.4.gz  messages.2.gz       syslog.4.gz
auth.log.1        docker.log  kubelet.log.2.gz     kube-proxy.log.5.gz  news                syslog.5.gz
auth.log.2.gz     dpkg.log    kubelet.log.3.gz     lastlog              ntpstats            syslog.6.gz
btmp              faillog     kubelet.log.4.gz     lpr.log              salt                syslog.7.gz
daemon.log        fsck        kubelet.log.5.gz     mail.err             shutdownscript.log  unattended-upgrades
daemon.log.1      google.log  kubelet.log.pos      mail.info            startupscript.log   user.log
daemon.log.2.gz   kern.log    kube-proxy.log       mail.log             syslog              wtmp
debug             kern.log.1  kube-proxy.log.1.gz  mail.warn            syslog.1
satnam@kubernetes-minion-1:/var/log$ 
````
@vishh : is there a kube-proxy.log.pos file? If yes, how many rotated out files do you have and are they filling up your disk?

**Comment by vishh** [comment]
I don't see a 'kube-proxy.log.pos'. I can try updating my cluster again and see if this issue appears again.

**Comment by satnam6502** [comment]
Yes, I also did not see the pos file on a new-ish cluster that I created -- but I did see it on old clusters.

**Comment by vishh** [comment]
I did a few cluster updates using `kube-push`. Not sure if that might have led to the disappearance of `kube-proxy.log.pos`.

**Comment by satnam6502** [comment]
I am going to close this issue because I think there is something else going on in this specific situation where a lot of information is put into this log (perhaps to do with log levels?). We can re-open if @vishh has this problem again.

**Comment by fzu-huang** [comment]
I don't know how to use log rotation.Can you teach me ,plz?
I start a cluster by running binary files with args. Is it right?   Should  I  do something else?
