### ISSUE TITLE
Switch kubernetes default etcd implementation to etcd 2.0

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#3892]
@brendandburns writes: As we start looking into etcd and event memory pressure [#3853], we should look into switching over to etcd 2.0 which was released today.

**Comment by dchen1107** [comment]
cc/ @ArtfulCoder

**Comment by thockin** [comment]
+1

**Comment by alex-mohr** [comment]
My long-running cluster tests #3936 resulted in a hard-crash on etcd: https://github.com/coreos/etcd/issues/2187

We should move to 2.0 ASAP in the hopes of (a) fixing the issue and if not (b) prioritizing the fix since we'll be complaining about head.

@ArtfulCoder Abhi, is this something you can pick up and drive to land in O(days) please?

**Comment by alex-mohr** [comment]
Calling this P0 as it blocks further long-running cluster stability testing.

**Comment by brendandburns** [comment]
I will do this today.
