### ISSUE TITLE
Create a cloud provider support matrix 

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#3912]
Proposing we create and check-in a "cloud provider support matrix" that has each provider, its last tested version, a nominal "owner" for that provider, and notes (what seems to be currently broken for that provider, or for, in some cases, maybe what setups are known to clearly work and what clearly doesn't.)

Right now it's exceedingly hard for anyone who's coming into the project to figure out whether a given cloud provider should "just work". If they were to pick up `azure` today, they might assume it would work without effort. Will it? Doubtful. I certainly wouldn't guess that it would as of 0.9.2, but maybe?

I proposed a table format, then @erictune took it a mile further in #3926, so let's argue that one. :)

**Comment by zmerlynn** [comment]
I'd actually like a separate table for the different "Getting Started Guides", too, since they have their own special bitrot as well.

**Comment by erictune** [comment]
Need provider x is sparse matrix.  Willing  to help.

**Comment by derekwaynecarr** [comment]
Ack.

**Comment by zmerlynn** [comment]
@erictune Couldn't quite parse that. :)

**Comment by mbforbes** [comment]
Ack. This is an excellent idea.

This would also make me more comfortable updating the project's README (many people's first intro to k8s, I would assume), which says "Kubernetes can run anywhere! *However*..."

**Comment by alex-mohr** [comment]
Seems reasonable to me -- thanks Zach.

**Comment by erictune** [comment]
The format I had in mind is  #3926

**Comment by erictune** [comment]
There are several styles of AWS.
There is the AWS that uses kube-up, and debian, which appears to be stuck a kubernetes v0.5.0.  I think we might want to delete that.

Then there is the AWS that uses CoreOS.  There are two competing versions of that, but they have been updated in the last week.  We should keep that one.

**Comment by justinsb** [comment]
I have on my plate this week to get Kubernetes head running on AWS/Ubuntu.  I have a few patches queued up on my machine, but I'd like to get it actually all working again before I start submitting them to keep the workload sensible for everyone.

I would love to see AWS/CoreOS and AWS/Ubuntu both stay in-tree.

I can look after AWS/Ubuntu (at least for the next six months).  I'm a big fan of CoreOS, but need Ubuntu too!

**Comment by zmerlynn** [comment]
@erictune: Are you saying that that the `aws` that actually works using the `KUBERNETES_PROVIDER` / `kube-up` pattern is currently ripe for deletion, but that the CoreOS Cloud Formation pattern is fine right now?

I think we need to really consider splitting the `cluster/` directory up into "assets that happen to accompany deployment guides" and "things that actually work with automatic `kube-up` deployments for the right scenarios, which we document here". Because the latter is actually code that we support pretty directly, and the former is in a slightly different class, honestly, that needs to be made more into the latter *somehow*.

It's obviously totally unclear from the names (`gce`, `aws`, etc.) what node type we're handing out, too.

**Comment by pires** [comment]
+1

**Comment by erictune** [comment]
@zmerlynn 
kube-up is not the only valid way to start a cluster.   For example docs/getting-started-guides/aws-coreos.md uses Amazon CloudFormation, but not kube-up.   So, not sure about the split you mention.

**Comment by zmerlynn** [comment]
There's a set of stuff you don't get with it, though. As an example, e2e
doesn't know how to form clusters using anything but kube-up right now, for
better or worse. It would be nice if e2es could tear down clusters in the
middle if things fail, for hermetic reasons, to reset state, so it may not
always be sane to say "run it on what's there" (though we should allow that
as well). So it comes down to what's supported dynamically versus
statically.

**Comment by brendandburns** [comment]
This is now covered by https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md
