### ISSUE TITLE
kubectl ClientForVersion ignores resource mapping

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#3919]
I stumbled across this while experimenting with kubeconfig load order/merging. There are various helpers constructed from a Factory that use [clients.ClientForVersion](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L348), however this always uses the same default ClientConfig because [ClientConfigForVersion](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L325) doesn't use the passed in version param:
```go
// ClientConfigForVersion returns the correct config for a server (version never used?)
func (c *clientCache) ClientConfigForVersion(version string) (*client.Config, error) {
	if c.defaultConfig == nil {
		config, err := c.loader.ClientConfig()
		if err != nil {
			return nil, err
		}
		c.defaultConfig = config

		if c.matchVersion {
			if err := client.MatchesServerVersion(config); err != nil {
				return nil, err
			}
		}
	}

	// TODO: have a better config copy method
	config := *c.defaultConfig
	client.SetKubernetesDefaults(&config)
	return &config, nil
}
```
Am I missing something or is this a bug?

/cc @smarterclayton, @deads2k

**Comment by smarterclayton** [comment]
Looks like a bug, clientforversion should accept "" (which can provide a default) and SetKubernetesDefaults has the final fallback protection (by using latest.Version).  If version != defaultConfig.Version, we should copy defaultConfig, set version, then apply kubedefaults.

The reason we take version here is if a resource is specified via file which only exists in a newer version, ie user says:

--api-version=v1beta1 -f file_with_newresource.json

RESTMapper can handle that newresource is only valid for v1beta3 and apply the right override, then ask for client.

--api-version is expected to bubble up via default config.
