### ISSUE TITLE
Semantic DeepEqual passes objects with unexported fields, when it probably shouldn't

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3928]
https://github.com/thockin/kubernetes/tree/semantic_eq

This tree has a commit that demonstrates two obviously different objects that should not pass the semantic DeepEqual but do.

@lavalamp

**Comment by satnam6502** [comment]
What shall we do with this issue for triage? Labels? Priority?

**Comment by thockin** [comment]
P2 @lavalamp for when he returns

**Comment by lavalamp** [comment]
OK I am now sufficiently worried about this. Fixes incoming.
