### ISSUE TITLE
postStart hook doesn't work

### ISSUE THREAD

**Issue by halacs** [GoogleCloudPlatform/kubernetes#3930]
I would like to make a pod (pod definition: http://pastebin.com/VVqRQpZm) with postStart but I got the following error message. I think it could be a bug.

[kubelet.go:811] Error running pod apache.default.etcd container master: failed to call event handler: docker server version missing from server version output - &[Arch=amd64 GitCommit=5bc2ff8/1.4.1 GoVersion=go1.3.3 KernelVersion=3.11.10-301.fc20.x86_64 Os=linux Version=1.4.1 ApiVersion=1.16]

Related stackoverflow page: http://stackoverflow.com/questions/28151921/using-kubernetes-hooks/28164639#28164639

**Comment by bgrant0607** [comment]
What Docker version and OS distribution?

/cc @vishh

**Comment by halacs** [comment]
Docker version 1.4.1, build 5bc2ff8/1.4.1
Fedora release 20 (Heisenbug)
Linux host12 3.17.8-200.fc20.x86_64 #1 SMP Thu Jan 8 23:26:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vishh** [comment]
Commit [3a0d16ff35e7797456091d74dadbf10068c336fc](https://github.com/GoogleCloudPlatform/kubernetes/commit/3a0d16ff35e7797456091d74dadbf10068c336fc) should have fixed this issue. The fix is available in kube releases v0.8.0+. Can you try upgrading your cluster to a more recent release?

**Comment by halacs** [comment]
It should be in the Fedora 20's yum repo? If not, can you give me a link where I can found the correct binary? Thanks.

**Comment by vishh** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.8.4

**Comment by halacs** [comment]
Thanks. I will try this release tomorrow (in office hours).
Are you plan to upgrade Kubernetes in yum repo or it is worth to use binary/source instead of yum install?

**Comment by vishh** [comment]
@brendandburns: who is maintaining external repos for kubernetes?

**Comment by brendandburns** [comment]
The RedHat folks (@eparis?) are the ones building RPMs...

---brendan

**Comment by eparis** [comment]
should be updated to 0.9.1 in the next couple of days (at least updates-testing).  0.9.1 is in the rawhide repo right now (although it might not be to all mirrors)

**Comment by goltermann** [comment]
Should be fixed in new version, reopen if you still see this bug.
