### ISSUE TITLE
Use case: clusters must be able to run for a long time

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#3936]
This is a master issue to track issues encountered by long-running active clusters.  We need to drive those to be reliable and usable.  I'll mention this issue from any more-specific issues.  Exit criteria for closing this issue: we're convinced long-running active clusters are ready for production use.

As a first cut to find low-hanging fruit, I'm creating a cluster with 1 master and 1 node using GKE, then running a script to repeatedly schedule a pause pod, wait for it to be running, then delete it.  And then running some number of those in parallel for more throughput.

> #!/bin/bash
> ATTEMPTS=999999
> for count in $(seq -f "%06.0f" 1 $ATTEMPTS); do
>   POD=pause-pod-$(openssl rand -hex 4)
>   echo `date`: ${count}: creating $POD
>   gcloud preview container pods --cluster=${PROJECT} create --name=$POD --image=kubernetes/pause --port=3009
>   echo `date`: ${count}: checking for running $POD
>   until gcloud preview container pods --cluster=${PROJECT} list | grep $POD | grep Running; do
>     echo `date`: ${count}: container pending or unknown: $POD
>     sleep 3
>   done
>   echo `date`: ${count}: container running so deleting $POD
>   gcloud preview container pods --cluster=${PROJECT} delete $POD
> done

**Comment by davidopp** [comment]
Can we dupe this with #3137?

**Comment by alex-mohr** [comment]
> Can we dupe this with #3137?
I'd prefer not to.  That describes an implementation (create a soak test), but this is an exit criteria to track work necessary to meet the use case of long running clusters actually work.

As such, treat this as a master issue and #3137 as a dependent blocker?

**Comment by alex-mohr** [comment]
We'd like to see the open issues go to zero, so we need to decide what the criteria are to close this issue for v1.  Are there specific work items?

**Comment by davidopp** [comment]
No specific work items left, so closing this issue.
