### ISSUE TITLE
kubectl get minions takes a long time to output

### ISSUE THREAD

**Issue by jmreicha** [GoogleCloudPlatform/kubernetes#3938]
I noticed this behavior after I began removing old nodes from a v0.8.2 cluster using kubectl v0.9.1.

After running a `kubectl get minions`, the command will hang for quite some time ( haven't timed it yet) but will eventually spit back the current nodes in the cluster.  Other kubectl commands seem to work as the should (get service/rc/pod, etc) it just seems to be the get minions that has problems.

I'm not sure what to make of this or how to fix.  Thanks!

**Comment by satnam6502** [comment]
See  #2973 which reports some progress here.
How many minions are you trying to list?

**Comment by jmreicha** [comment]
@satnam6502 I have 12 minions that I am trying to list.  I was able to like 20ish very quickly but after removing the first node, I noticed the time increase.

**Comment by satnam6502** [comment]
Yes, well, I've been trying to list 1,000 minions. Imagine how miserable that is. I am going to ask @davidopp to take a look (or to forward this to someone else.)

**Comment by ddysher** [comment]
Did we already cache all minions?  Maybe we are not if it only happens after you take down a node.

I believe it will be fixed by #3733.  Can you verify it once that is in?

**Comment by goltermann** [comment]
#3733 appears merged.  You'll need to upgrade to a more recent version of kubernetes for your cluster.

**Comment by satnam6502** [comment]
I'm still have problems listing minions. #4078

**Comment by ddysher** [comment]
#4078 is likely a different issue from this one.

**Comment by satnam6502** [comment]
Agreed.
