### ISSUE TITLE
apiserver should clarify which peers it's unable to contact

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#3939]
@davidopp for apiserver.
I had a cluster where etcd became nonfunctional.  The apiserver's error messages weren't amazingly helpful in figuring out which component was having issues -- it should report which peer isn't contactable.

% gcloud preview container pods --cluster=${PROJECT} list
ERROR: F0129 10:20:43.796366   29535 get.go:158] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

Separate issue tracking kubectl reporting #3937.  Part of long-running clusters #3936.

Extended log from /var/log/kube-apiserver.log
I0129 18:33:10.977679    5006 handlers.go:104] GET /api/v1beta1/pods?fields=DesiredState.Host%21%3D: (634.881us) 500
goroutine 2136125 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20b3783c0, 0x1f4)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9c
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f7ce12efa78, 0xc208044b20, 0x7f7ce12efc18, 0xc20c593500, 0x7f7ce13049a8, 0xc20b3783c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:307 +0x239
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7f7ce12f2a50, 0xc20d097aa0, 0x7f7ce12efa78, 0xc208044b20, 0x7f7ce13049a8, 0xc20b3783c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:314 +0xa4
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*RESTHandler).handleRESTStorage(0xc20801b7c0, 0xc20df06130, 0x1, 0x1, 0xc20a5544e0, 0x7f7ce13049a8, 0xc20b3783c0, 0x7f7ce12f2b28, 0xc208045ea0, 0xb0fef0, ...)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:169 +0x797
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*RESTHandler).ServeHTTP(0xc20801b7c0, 0x7f7ce13049a8, 0xc20b3783c0, 0xc20a5544e0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:56 +0x2fc
net/http.func·012(0x7f7ce13049a8, 0xc20b3783c0, 0xc20a5544e0)
        /usr/src/go/src/pkg/net/http/server.go:1267 +0xc4
net/http.HandlerFunc.ServeHTTP(0xc208118440, 0x7f7ce13049a8, 0xc20b3783c0, 0xc20a5544e0)
        /usr/src/go/src/pkg/net/http/server.go:1235 +0x40
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·001(0xc20d097680, 0xc20a7814f0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes
I0129 18:33:10.978652    5006 errors.go:52] An unchecked error was received: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

**Comment by bgrant0607** [comment]
That message might come from the etcd client library.

**Comment by brendandburns** [comment]
This is straight from etcd.  Created https://github.com/GoogleCloudPlatform/kubernetes/issues/4036 and closing this.
