### ISSUE TITLE
Investigate if cadvisor can be replaced with docker stats. 

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#3947]
I suspect so, but just need to verify once it's released upstream. 

https://github.com/docker/docker/pull/9984

@rrati ^ FYI

**Comment by tobegit3hub** [comment]
I think it's possible to use docker remote API to get metrics of containers, but not replacing cAdvisor. It's the tool to collect and display metrics and `docker stats` is just the command to use for one time or others.

**Comment by vishh** [comment]
cAdvisor may adapt the docker metrics API once that is available. However
cAdvisor servers a purpose that is beyond just collecting docker container
metrics!

**Comment by goltermann** [comment]
Going forward, we will be using cAdvisor for stat collection.  If there are specific stats missing, open bugs on cAdvisor for those.
