### ISSUE TITLE
Kubernetes killing running pods instead of unassigned when reducing replicas

### ISSUE THREAD

**Issue by jseaidou** [GoogleCloudPlatform/kubernetes#3948]
I've noticed a issue where if you have multiple replicated slave pods that don't have a HOST assigned and you reduce the number of replicas in the replicationController definition for those pods, sometimes the currently assigned (and running) pods get killed and the unassigned pod will get assigned to run in the killed pods place.
The issue can be reproduced using the guestbook example provided in the repo.

**Steps to reproduce**: (Note this is not always deterministic and may need multiple attempts)

1. Create the master pod 
        
        #create the pods
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh create -f examples/guestbook/redis-master.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/redis-master.json
        redis-master
    
        #query for pods
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get pods
        ./cluster/../_output/local/bin/linux/amd64/kubectl 
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
        POD                 CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
        redis-master        master              dockerfile/redis    127.0.0.1/          name=redis-master   Running
2. Create the master service
           
        #create the service
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh create -f examples/guestbook/redis-master-service.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/redis-master-service.json
        redis-master
        
        # query for services
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get services
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get services
        NAME                LABELS                                    SELECTOR            IP                  PORT
        kubernetes          component=apiserver,provider=kubernetes   <none>              10.0.0.82           443
        kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.0.0.204          80
        redis-master        name=redis-master                         name=redis-master   10.0.0.90           6379
3. Create the replicated slaves

        #create the slaves
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh create -f examples/guestbook/redis-slave-controller.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/redis-slave-controller.json
        redisSlaveController

        #query for number of replication controllers. Note we have 2 replicas for this controller
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get replicationControllers
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get replicationControllers
        CONTROLLER             CONTAINER(S)        IMAGE(S)                   SELECTOR            REPLICAS
        redisSlaveController   slave               brendanburns/redis-slave   name=redisslave     2

        #query the pods. Note that POD: 51149bbc-a7fb-11e4-a34c-0800279696e1 is unassigned and has pending STATUS
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get pods
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
        POD                                    CONTAINER(S)        IMAGE(S)                   HOST                LABELS                              STATUS
        51149bbc-a7fb-11e4-a34c-0800279696e1   slave               brendanburns/redis-slave   <unassigned>        name=redisslave,uses=redis-master   Pending
        redis-master                           master              dockerfile/redis           127.0.0.1/          name=redis-master                   Running
        34fc5e81-a7fb-11e4-a34c-0800279696e1   slave               brendanburns/redis-slave   127.0.0.1/          name=redisslave,uses=redis-master   Running

4. Edit the Slave Controller definition to only have 1 replicas
5. Update the Slave Controller with new definition

        #update with new definition
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh update -f examples/guestbook/redis-slave-controller.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl update -f examples/guestbook/redis-slave-controller.json
        redisSlaveController

        #query for number of replication controllers. Note we have 1 replicas for this controller now after update
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get replicationControllers
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get replicationControllers
        CONTROLLER             CONTAINER(S)        IMAGE(S)                   SELECTOR            REPLICAS
        redisSlaveController   slave               brendanburns/redis-slave   name=redisslave     1

        #query for pods. Note that POD 51149bbc-a7fb-11e4-a34c-0800279696e1 which was previously PENDING with no associated host is now running and the previously running pod has been killed
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get pods
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
        POD                                    CONTAINER(S)        IMAGE(S)                   HOST                LABELS                              STATUS
        redis-master                           master              dockerfile/redis           127.0.0.1/          name=redis-master                   Running
        51149bbc-a7fb-11e4-a34c-0800279696e1   slave               brendanburns/redis-slave   <unassigned>        name=redisslave,uses=redis-master   Pending

The expected behavior should be that the scheduler is able to determine that unassigned pods are more viable candidates when reducing number of replicas. It seems to be more likely that since this issue is not deterministic, the ordering in which the `./cluster/kubectl.sh get pods` command returns result is not always deterministically in the same order

**Comment by satnam6502** [comment]
@dchen1107 : please can you look at this or suggested someone else? Thank you.

**Comment by dchen1107** [comment]
Unassign myself from this bug since I cannot get working on this soon. Also remove kubelet from the label since it is not kubelet issue.

This is obviously a replicaController issue. cc/ @bgrant0607  Instead of destroying pod in pending state, replicaController unbound running pod from a node. Kubelet running on such node has this new desire state and kill unwanted pod to match it.

**Comment by bgrant0607** [comment]
Yes, the replication controller should be smarter, taking into account Phase, Readiness, recency, ... 

This will be a significant problem for auto-scalers, but I expect manual scaling to be infrequent.

I doubt we'll get to this soon. A PR would be welcome. Place to change is here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/controller/replication_controller.go#L183

**Comment by swaprp15** [comment]
Hi,

I am final year Master's student of International Institute of Information Technology, Hyderabad. I am familiar with docker and containers. I have basic understanding of Go language with some hands on Docker API. This project seems interesting and a solution to this will also be a good addition to Kubernetes. So I would like to pick this as my GSoC project.

I have started reading about Replication Controller and Pods and going though the code. I would appreciate if someone has any inputs for me on this.

Thanks,
Swapnil Patil
