### ISSUE TITLE
CGE Daily Quota Exceeded by 'idle' 500-node cluster

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#3971]
I've had a 500-node GCE cluster up for a few days. The last two days I have been locked out of my Google Developer Console with the message `We are unable to display this page. You have exceeded daily quota for Compute Engine API` and I can't ssh into the machines -- even though I myself have not been issuing any/much in the way of API calls. Is a largely idle cluster on GCE issuing GCE Compute Enginer API calls in its steady state that are proportional to the number of minions?

**Comment by smreed** [comment]
See also #3643

**Comment by satnam6502** [comment]
Right. But I seem to have managed to exceed quota by not doing anything proactive e.g. issuing any commands myself.

**Comment by erictune** [comment]
Right.  Node controller is doing it.  Read the aforementioned issue.

**Comment by satnam6502** [comment]
Daily quota changes by GCE I think address this issue now.
