### ISSUE TITLE
idea: make e2e tests use namespaces

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#3973]
If each e2e test runs in a namespace, then cleanup is way easier - at the end of eaach test, just nuke the whole namespace.

**Comment by brendandburns** [comment]
seems reasonable.  Although I don't think our current flakiness is due to
bad cleanup...

**Comment by satnam6502** [comment]
Right now it is not due (much) to bad cleanup but that does become and issue if you want to run tests N times back to back (so we can tell who the real falkes are) (or in parallel) but in that case it is perhaps a bit heavy handed to nuke the namespace after each invocation of the same time.

**Comment by derekwaynecarr** [comment]
+1

**Comment by thockin** [comment]
When DNS test times out it leaves turds that have to be manually cleaned
up.  This is stupid.  Nuke it from orbit.

**Comment by zmerlynn** [comment]
+1 for the cases where this is all that matters. We already have tests that
need cleanups that aren't bound by namespaces (pd.sh for now), or tests
that are poking kubelet things (like services.sh) that should probably have
kubelet verification functions before the test exits. (That test is also an
interesting example of "hard to run in parallel".)

**Comment by erictune** [comment]
We need ability to e2e test things like reboot master VM.  That will be a
per cloudprovider function.  So might as well support a wipeEtcd function
too and use for cleanup at end of test.

**Comment by filbranden** [comment]
How do I nuke a namespace???

**Comment by thockin** [comment]
I don't think there's a single way to nuke a namespace, but you can simply
iterate over all members..

**Comment by derekwaynecarr** [comment]
Once #3613 lands, I would like to do a follow-on PR to nuke a namespace in the next 2-3 weeks ;-)
