### ISSUE TITLE
Move Node.HostIP to node status in v1beta1 and v1beta2

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#3985]
Plan to do the change, but need to make sure if there is any historical reason.

/cc @smarterclayton @bgrant0607

**Comment by dchen1107** [comment]
I am a little bit confused here. Shouldn't we plan to move v1beta3 soon and HostIP is in Status already? Also HostIP here is referring to the one associated with Pod or Minion / Node? But no matter what, both APIObject don't have separate Spec and Status in v1beta1 and v1beta2, right?

**Comment by ddysher** [comment]
It's Node.HostIP.  By Spec in v1beta1/2, I mean things outside of Status.  Sorry for confusion.

When are we going to deprecate v1beta1/2?

**Comment by bgrant0607** [comment]
We're trying to wrap up v1beta3 asap. v1beta1/2 will then be deprecated, but we'll retain support for some amount of time.

**Comment by ddysher** [comment]
ok, looks like it will still exist for a few months.  I'll try to evaluate the work.

**Comment by davidopp** [comment]
@ddysher Do you think you'll be able to do this soon, or should we reassign?

**Comment by bgrant0607** [comment]
Probably not worth doing. Let's just wrap up v1beta3.
