### ISSUE TITLE
Improve documentation for /redirect and /proxy

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#3996]
Right now, /redirect and /proxy accept requests with all methods - GET, PUT, POST and DELETE.

While GET definitely makes sense, I am not sure why we need to support PUT, POST and DELETE.

@bgrant0607 @smarterclayton

**Comment by smarterclayton** [comment]
Redirect should only accept GET.

Proxy is more nuanced - it's a true http proxy, and makes no decisions about the content.  In theory you can use proxy to connect to http servers running on services in your infrastructure.

----- Original Message -----

**Comment by bgrant0607** [comment]
In general, we should rationalize these with the bastion proposal  #3481  and with #3763.

@smarterclayton Are you relying on /redirect and /proxy for anything specific, or do you mainly use them for debugging?

**Comment by bgrant0607** [comment]
The redirect handler enforces that it's GET only:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/redirect.go#L42

**Comment by nikhiljindal** [comment]
Thanks for the quick replies. Looks like we definitely dont need to support all methods for /redirect.
Updated https://github.com/GoogleCloudPlatform/kubernetes/pull/3999 to handle only the GET method on /redirect.

**Comment by bgrant0607** [comment]
These should also be documented in api-conventions.md, while we're at it.

redirect handler: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/redirect.go#L33
proxy handler: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/proxy.go#L83

ResourceLocation implementations:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/minion/rest.go#L157
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/pod/rest.go#L192
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/service/rest.go#L254

The pod implementation always picks the first port on the pod currently.
The service implementation picks a random endpoint.

It looks like redirect doesn't support namespaces, so probably nodes only?
It looks like proxy requires namespaces, so pods and services only?
The custom path parsing in both makes me sad.

I'll cite #2585 for tracking.

**Comment by bgrant0607** [comment]
Ref #1863

**Comment by bgrant0607** [comment]
Looked at pod's ResourceLocation again. It looks like the user can specify a port number. There's a TODO to do lookup by port name. The first port is used only if no port is specified.

**Comment by bgrant0607** [comment]
The more I think about it, the more I think that proxy and redirect shouldn't be considered part of the API. They're really just convenience mechanisms provided by the apiserver.

**Comment by bgrant0607** [comment]
Leaving this open to write better docs.

**Comment by satnam6502** [comment]
I have decided to assign this bug to myself for the doc fixit.
How should I work out what `/redirect` and `/proxy` are for and what they are meant to do?
Is there someone I could bug over IM etc?

**Comment by bgrant0607** [comment]
Done.

**Comment by smarterclayton** [comment]
Do we remember why we supported TRACE beyond completeness?

**Comment by nikhiljindal** [comment]
I dont remember why I added TRACE.
It is causing problems while using swagger-codegen since swagger does not support TRACE (https://github.com/swagger-api/swagger-codegen/issues/877#issuecomment-112391320).

Is it fine to remove it?

**Comment by smarterclayton** [comment]
We patched it out of openshift and replaced it with options - I have no objections to removal.
