### ISSUE TITLE
Unknown flag --replicas

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#4014]
This fails
```
⧑ kubectl resize --replicas 2 rc cloud-api-stream                                                                                                                                             
unknown flag: --replicas
```

This works

```
⧑ kubectl resize --replicas=2 rc cloud-api-stream                                                                                                                                             
resized
```

Both should work, no?

**Comment by jasonkuhrt** [comment]
Version:

```
⧑ k version                                                                                                                                                                                    
Client Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.0-389-gaf25c3c671d592", GitCommit:"af25c3c671d592bf8643d65d24fb8b37b3aec994", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.2-dirty", GitCommit:"013a97ea6e2a143f763035defdbcbcdc1b6d3411", GitTreeState:"dirty"}
```

**Comment by bgrant0607** [comment]
I don't think so:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl.md

/cc @jlowdermilk @brendandburns

**Comment by jlowdermilk** [comment]
I believe pflags requires the format --flag-name=value.

**Comment by jasonkuhrt** [comment]
Ok, happy to close then. Its a bit surprising as most-all other CLIs I use do not enforce this restrict, or if they do, I haven't noticed.

**Comment by thockin** [comment]
I second the notion that this is surprising and unfortunate.

**Comment by jasonkuhrt** [comment]
Its surprising even within the context of `kubectl` itself:

This works, surprisingly *surprisingly*:
```
$ kubectl get pods -l name=cloud-api-stream
```

: (

**Comment by jlowdermilk** [comment]
This isn't the first time I've been surprised by behavior of the pflag [parser](https://github.com/ogier/pflag/blob/master/flag.go#L406). It looks like for long arguments, the parser expects and requires `--flag-name=value`, but short flags (-f, -a, -s) are parsed as `-c arg`.

I agree this behavior is surprising and unfortunate. If we are sufficiently unhappy with it, we can fork pflag and/or submit patches.

**Comment by thockin** [comment]
+1 to patches

**Comment by brendandburns** [comment]
jbeda actually has committer rights on the pflag library, so send him
patches!
