### ISSUE TITLE
Is it possible for Kubernetes to accept a Dockerfile and build the image and start the container?

### ISSUE THREAD

**Issue by sourav82** [GoogleCloudPlatform/kubernetes#4018]
I could see to create a pod in Kubernetes we need to pass a docker image. Is is possible to pass it a path to a Dockerfile so that Kubernetes will build the image from the Dockerfile and create the container?

**Comment by thockin** [comment]
At the moment there is no build-and-run macro.

**Comment by sourav82** [comment]
Thanks @thockin.

**Comment by bgrant0607** [comment]
BTW, this was previously requested here: #1294

And, you may want to check out Openshift, which does support building.

**Comment by brendandburns** [comment]
I think that the right way to support this is as a container that runs on
k8s, not part of k8s proper.  We'd happily accept a contrib. that does that.

Brendan
