### ISSUE TITLE
etcd arguments are different for systemd vs non-systemd

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#4024]
kubernetes/cluster/saltbase/salt/etcd/default (used for systemd) and kubernetes/cluster/saltbase/salt/etcd/initd (used for initd) have diverged; in particular DAEMON_ARGS has a different bind_addr.

Also, I'm not sure whether etcd.conf is still used at all, but it has another value for the bind addresses (hard-coded to 0.0.0.0).

**Comment by a-robinson** [comment]
@davidopp Want to take a look at this?

**Comment by justinsb** [comment]
etcd is now run in a container, ensuring consistent arguments;  closing
