### ISSUE TITLE
Kubernetes configuration file schema

### ISSUE THREAD

**Issue by arun-gupta** [GoogleCloudPlatform/kubernetes#4040]
The schema understood by the Kubernetes configuration file is not described any where. The current practice mostly is copy/paste existing samples (for example https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook) and edit them. There is a need to define a comprehensive list of elements, and their documentation, so that other examples can leverage them.

**Comment by bgrant0607** [comment]
Configuration files specify exactly our API objects.
See: http://kubernetes.io/third_party/swagger-ui/

**Comment by arun-gupta** [comment]
This is exactly what I was looking for but not easily googlable, or documented clearly.

**Comment by bgrant0607** [comment]
@nikhiljindal Could you please put a link to the swagger UI here?
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/README.md

**Comment by brandond** [comment]
The only mention in the public docs is here: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ which links directly to the struct definition on github. 

It appears that the Swagger docs have been deprecated, and I'm unable to find any documentation for the KubeletConfiguration resource kind in the new docs. It's referred to in at least one place, but is still not actually covered: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#configmapnodeconfigsource-v1-core
