### ISSUE TITLE
Automatically detected hostnames might be case sensitive

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#4044]
NodeController is unable to register the value of `hostname -f`, because it contains mixed case from the OS (in this case OSX).  I'm not positive that all Linux systems are guaranteed to lowercase hostname -f, but it's likely that automated processes may end up collecting hostnames from sources that preserve case and passing that to the kubelet or master.  I believe we should lowercase names detected from hostname -f and the values the node controller users - it's a minor thing, but internally we can guarantee that we treat node names as insensitive and in their canonical interior form.

```
nodecontroller.go:120] Error registrying node Claytons-MacBook-Pro.local, retrying: minion "Claytons-MacBook-Pro.local" is invalid: metadata.name: invalid value 'Claytons-MacBook-Pro.local': name must be lowercase letters and numbers, with inline dashes or periods
```

**Comment by bgrant0607** [comment]
cc @ddysher

**Comment by ddysher** [comment]
I'll take a look tmr.
