### ISSUE TITLE
How to add type to nodes and process it by pods?

### ISSUE THREAD

**Issue by cnaize** [GoogleCloudPlatform/kubernetes#4047]
Hello! I'm a new one in `kubernetes`.
I want to add `type` to `nodes`, for example, `node` with huge hard, `node` with small RAM, etc.
Then I need to check the `nodes` `type` and add `pods` to `nodes` depends on the `type`.
Can I get some help, what is the best way to do this?

**Comment by thockin** [comment]
Why no just spec your pods as needing particular resources, and let the
scheduler sort out which nodes to use?  If yo need 16 GB of memory for a
particular pod, just say that.  If you are busy considering which nodes
jobs should run on, you aren't really experiencing the full power of the
system.

**Comment by a-robinson** [comment]
I'm working on adding an example doc on how to pin pods to nodes in #2406

**Comment by cloudlinux** [comment]
Some nodes might have specific characteristics and be non-uniform (like nodes with SSD, or GPU nodes). It would be nice to be able to specify that POD needs specific type of node (like SSD/GPU) -> and that is where scheduler would kick in and schedule them for node of specific type.

**Comment by a-robinson** [comment]
Check out the new example showing how to do this - https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/node-selection
