### ISSUE TITLE
Standardize capitalization rules for labels

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#4082]
What are the intended capitalization rules for labels? I wouldn't be surprised if it's that both the keys and values should be all lower case, but I don't see it defined anywhere, unless it's assumed that the identifiers.md doc about names applies to them as well.

I bring this up because the validation applied to labels on pods seems to be more strict than that applied to labels on nodes. I was able to attach a label "diskSize: massive" to a node, but got errors (very unhelpful ones, at that) when trying to attach the same label to a pod or in a pod's nodeSelector:
`ERROR: F0203 13:18:17.236041    6515 create.go:78] pod "nginx" is invalid: spec.nodeSelector: invalid value 'diskSize'`

I think there's 3 things to do here:
1. Pick a capitalization policy and document it - presumably in one of the two labels docs.
2. Improve the error message for users not following the policy.
3. Ensure it's validated consistently for different resource types.

**Comment by thockin** [comment]
Currently all label keys are supposed to be "qualified name" - all
lowercase, etc.  See validation.go.  If that is different on nodes, it is a
bug.

We don't currently validate label keys at all.  That could be debated.

As for error messages in general - huge known issue. :)

**Comment by a-robinson** [comment]
"We don't currently validate label keys at all.  That could be debated."

I'm guessing you mean we don't validate label values at all?

**Comment by thockin** [comment]
yes, thanks :)

**Comment by a-robinson** [comment]
I should have mentioned in the first place -- I was testing this at 0.9.2 rather than at head because I was having trouble getting a cluster to come up successfully. After looking at the code and retrying at head, I see the inconsistent validation has already been fixed by Clayton's recent validation.go improvements.

I'll send out a quick PR making sure we have test coverage and adding a pointer to the requirement in the labels doc, but this issue isn't needed.
