### ISSUE TITLE
Volumes not torn down on pod delete

### ISSUE THREAD

**Issue by nelcy** [GoogleCloudPlatform/kubernetes#4086]
Volumes are not getting teared down on pod delete. I see the following error in kubelet log.

Couldn't sync containers: remove /var/lib/kubelet/pods/f936e991-abed-11e4-96a8-00266cf650e0/volumes/kubernetes.io~dw-vol/redisvol2: device or resource busy

We are trying to clean up pod directory before cleaning up volumes. Reversing 'kubelet.cleanOrphanedPods' & 'kubelet.cleanupOrphanedVolumes' in kubelet.go fixes the issue.
I have the patch available, if we are ok to commit.

**Comment by thockin** [comment]
What is dw-vol - is it a new kind of plugin?  Can you explain what exactly
is happening?

I think flipping the order is probably correct.

**Comment by brendandburns** [comment]
I saw this as well in our PD testing. I'm also adding in: https://github.com/GoogleCloudPlatform/kubernetes/pull/4076 which makes sure that the containers are down before attempting to unmount.

But yes, your PR sounds reasonable, please send it along (and you'll need to sign our CLA if you haven't already.)

Many thanks!
--brendan

**Comment by nelcy** [comment]
Thanks Thockin & Brendan.
I am just trying out the plugin infra. It is actually bind mount in the backend as of now.

**Comment by thockin** [comment]
Yeah, the real problem is that we try to tear down the pod but don't rcurse
that into the pod's volumes.  Oops.

**Comment by nelcy** [comment]
Thanks Brendan. Signed and sent out the corporate CLA.

**Comment by brendandburns** [comment]
I believe this is now fixed (though pd.sh is still somewhat flaky _sigh_)
