### ISSUE TITLE
Jenkins builds not creating clusters due to incorrect cluster validation

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4094]
We've been failing Jenkins builds for a few hours due to #4034. After some debugging by @jlowdermilk, it looks like it's because the `get-password` in `validate-cluster.sh` is just wrong. Fix incoming.

We got here because Jenkins actually starts from a clean state. Anyone actually starting with an old `.kubernetes_auth` file would use the cached version.

**Comment by zmerlynn** [comment]
cc @brendanburns

**Comment by jlowdermilk** [comment]
I actually broke this with #4034, but the break was hidden when running locally because of a cached `~/.kubernetes_auth` file. Fix in progress.

**Comment by brendandburns** [comment]
Thanks to Zack for the debugging, and Jeff for the fix.

Let's update hack/test-e2e.sh to blow away credentials before each run.

Brendan

**Comment by zmerlynn** [comment]
Honestly, I just stared at the test runs and annoyed Jeff until he came
over and wondered aloud with me why it was breaking. So I guess it was
delegated debugging.

**Comment by jlowdermilk** [comment]
Cluster validation problem is fixed. The last gce e2e run was green, but there are some remaining items to cleanup that I'm still working on: #4100, #4111
