### ISSUE TITLE
Random(ish) 1 second delay requesting HTTP through kube-proxy

### ISSUE THREAD

**Issue by shakefu** [GoogleCloudPlatform/kubernetes#4096]
Hi,
We're working on a new production deployment, and when we try requesting pages through kubernetes, we see a (random?) 1-second delay inserted into the responses. 4 responses will be good, and the 6th will respond with exactly one extra second of response time.

Is there some rate limiting or some configuration that might affect this? We're seeing it across multiple applications, AZs, hosts, etc.

**Comment by satnam6502** [comment]
The read only port of apiserver has always had a throttler of 1 QPS with a burst of 20 and recently this was increased to 10 QPS with a burst of 200 and we started to return 429 TooManyRequests response codes when that was exceeded. The server returns a Retry-After header with a value of 1 second and this is observed and honored by the Go client library. But I suspect you might be running into something else?

**Comment by shakefu** [comment]
Thanks! Please leave this issue open for a bit in case we can narrow it down more. I'll close it in a bit.

**Comment by brendandburns** [comment]
Note that he is talking about the kube-proxy, not the apiserver.

I have also noticed significant long tail latency (see
https://github.com/GoogleCloudPlatform/kubernetes/issues/3734)

but that's at the 99%, not the 20% :P

Is it possible that one of the pods in your service is sick?  The proxy
attempts to connect and then if the connection fails, it will connect to
the next pod in the list, so if you have a sick pod, where connections are
timing out, then that would explain the behavior.

I will try to repro. on one of my clusters.  What are you running for the
webserver?

Thanks
--brendan

**Comment by thockin** [comment]
Did you or someone mess with iptables?  I noticed a 1 second lag when
iptables was set up to LOG some packets...

**Comment by shakefu** [comment]
We're using a Python webserver - but we have several variations of that and they're equally affected. (One is Pylons, the other Bottle.py).

What would be the best way to check if the pod is sick?

**Comment by brendandburns** [comment]
kubectl get pods <pod-name> -o json

Find the PodIP, and try to connect to it directly.

--brendan

**Comment by brendandburns** [comment]
kubectl get pods -o yaml

should also work for this.

**Comment by satnam6502** [comment]
Or perhpas `cluster/kubectl.sh  describe pods <pod name>`
Or, if you are using GCE, ssh into the node that has the pod and poke around the Docker containers to see what they are doing.

**Comment by shakefu** [comment]
To add to the mystery: We have 3 python apps that all experience random delays, different codebases. We have 1 node.js app that doesn't have this issue, works fine.

**Comment by brendandburns** [comment]
Are they all replicated?

**Comment by shakefu** [comment]
Yeah they are.

Good news! Using ./kubectl get pods, and then hitting the IPs directly allowed us to identify some pods that were not responsive in our Python apps.

**Comment by brendandburns** [comment]
Cool, https://github.com/GoogleCloudPlatform/kubernetes/pull/4048 adds
readiness checks, that would get rid of the delay in these cases (of course
it would also mask your failing pods...)

We should probably surface better information in the event stream about
these failures.  I've filed
https://github.com/GoogleCloudPlatform/kubernetes/issues/4101 to add these
events.

**Comment by shakefu** [comment]
Thanks for your help! We've managed to get it all working and implemented some rudimentary health checks in the meantime using `./kubectl get pods` and hitting the IPs directly.
