### ISSUE TITLE
kubectl version doesn't print local version before erroring out.

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#4098]
```
$ kubectl version
Couldn't read version from server: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connection refused
```

We should at least print the local client version before we try to create a server client for version checking.

**Comment by roberthbailey** [comment]
+1. It took me quite a while to figure out that kubectl version -c was the magic incantation to only print the client version.

**Comment by vmarmol** [comment]
Sorry, didn't realize it was assigned until after I had the PR ready :P
