### ISSUE TITLE
ImportError: No module named "yaml"

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4100]
@jlowdermilk: This has an obvious fix on Jenkins, but I have mixed feelings ..

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named yaml
Running: /jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/cluster/../cluster/gce/../../cluster/../cluster/gce/../../cluster/../cluster/gce/../../platforms/linux/amd64/kubectl config view --global
```

We don't have a clear place to list python deps right now, and it's apparently not a base library (unlike json, which appears in other inlines and is.)

cc @brendanburns

**Comment by zmerlynn** [comment]
Regression from #4097

**Comment by brendandburns** [comment]
Is that file actually yaml?  or is it json.  because if it's json...

**Comment by jlowdermilk** [comment]
It's yaml, unfortunately. I forgot pyyaml isn't a base library.

**Comment by zmerlynn** [comment]
I went ahead and installed python-yaml on Jenkins, but I'm leaving this issue open because it's a sort of odd dep, and I'm not sure if we have a place to list it. (If we had standard packaging files, I'd be asking you to adding it to .debs and .rpms, etc.)

**Comment by zmerlynn** [comment]
(I think my objection to is partially just that there's nothing really early testing for this .. you're kind of randomly in the middle of `kube-up.sh` and bam, `ImportError`.

**Comment by brendandburns** [comment]
Ok, I think the right thing to do here is to add something to kubectl that knows how to parse yaml and dump out the relevant data.

--brendan

**Comment by zmerlynn** [comment]
Someone should write an arbitrary yaml to json slinger, then it would be
parseable with base libs. :)

**Comment by jlowdermilk** [comment]
> Ok, I think the right thing to do here is to add something to kubectl that knows how to parse yaml and dump out the relevant data.

I think the ideal way to do this is to make, `kubectl config view` take a  `--output` flag so it can print the config as yaml|json|template.

**Comment by jlowdermilk** [comment]
This is now fixed. `kubectl config view` now takes `--output=json|yaml|template` (#4147). The inline python in cluster/gce/util.sh that triggered this pyyaml dependency was replaced with `kubectl config view --o template` (#4205)
