### ISSUE TITLE
Binding annotations should be preserved alongside Host assignment

### ISSUE THREAD

**Issue by jdef** [GoogleCloudPlatform/kubernetes#4103]
Recap of related tangent in #2483 follows.

Use case:  I need to implement mesos task reconciliation in the kubernetes-mesos scheduler. If it crashes and then restarts, I want to be able to recover things like taskID, slaveID, offerID, etc. so as to rebuild the internal state of the scheduler. Once state is recovered, I can reconcile the against the tasks that the mesos master knows about.

If I can't use binding annotations for this, then I need to store state some other (super inconvenient) way. Currently the etcd registry assignPod() implementation drops binding annotations on the floor. It should not, and instead they should be preserved for later access.

Proposal: Store binding-related annotations in a new field: Pod.Status.Annotations
* When setting Pod.Status.Host="{some-host-name}" via assignPod(), binding annotations are copied in from Binding
* When cloning Pod.Status.Host in UpdatePod() (for an already-scheduled pod), the Pod.Status.Annotations are also cloned.

I don't think /bindings has to be a readable apiserver endpoint, as long as the binding metadata is exposed some other way, as proposed above.

I'd also like to propose that once binding annotations are "bound" to Pod.Status they become read-only. So they're essentially write-once, just like Pod.Status.Host is meant to be.

cc @smarterclayton @bgrant0607 @erictune 
xref https://github.com/mesosphere/kubernetes-mesos/issues/73

**Comment by bgrant0607** [comment]
There is one situation where we probably want to clear Host, actually: in the case that the pod can't actually be materialized on the selected node for some reason, such as #4135.

**Comment by jdef** [comment]
Any objection to a PR implementing my proposal? I'm happy to do the work.

**Comment by smarterclayton** [comment]
You'll probably want to do it on top of #4248 (or after it lands) since that code path is changing significantly.

**Comment by bgrant0607** [comment]
Though it is also represented in PodStatus, Host is properly a field in the PodSpec.

Status must be completely reconstructable based on observations. The proposed Pod.Status.Annotations would not be. Furthermore, I don't think we should introduce another annotations field to Pod. I'd prefer to add a podAnnotations field to Binding, and then merge them into the pod. As for clearing the annotations, I'd prefer to simply fail a pod that was rejected by a node so as not to have to deal with that.

Also note the discussion here re. moving binding to a pod subresource: https://github.com/GoogleCloudPlatform/kubernetes/issues/2726#issuecomment-73313472

**Comment by bgrant0607** [comment]
See also #4375.
