### ISSUE TITLE
kubectl expose: help suggests no selector is needed, but error

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4107]
F0203 23:52:17.434029   14210 expose.go:80] Parameter: selector is required

**Comment by brendandburns** [comment]
Looking @ the code, this shouldn't be required if you specify a replication controller, it should automagically grab it from there.

I'll add some unit testing...

**Comment by brendandburns** [comment]
This is obsolete (and fixed)
