### ISSUE TITLE
kubectl resize: checkErr triggered with empty error

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4114]
$ ./cluster/kubectl.sh resize --replicas=1000 rc hostnames
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl resize --replicas=1000 rc hostnames
F0204 09:10:12.115515   27492 resize.go:64] 

Yet, if I get that RC, I see 1000 replicas.

**Comment by bgrant0607** [comment]
Actually, I think this is similar to #4095 (create service). I suspect error aggregation.

**Comment by brendandburns** [comment]
If the update timed out, but actually succeeded behind the scenes, this is what I'd expect to see.

Not sure what the correct behavior in an http timeout case should be.  (I'm surprised that we didn't get a clean error print out of the error, though...)

**Comment by roberthbailey** [comment]
Has anyone seen this recently? If not, we should close as obsolete.
