### ISSUE TITLE
enable_cluster_dns test for kubelet service is broken

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#4118]
https://github.com/GoogleCloudPlatform/kubernetes/blame/master/cluster/saltbase/salt/kubelet/default#L32

That test should be ```{% if pillar.get('enable_cluster_dns', '').lower() == 'true' %}```, like here: https://github.com/GoogleCloudPlatform/kubernetes/blob/55793ac2066745f7243c666316499e1a8cf074f0/cluster/saltbase/salt/kube-addons/init.sls#L12

The boolean vs string situtation here does not fill me with joy, but we need to do a string-comparison, not a boolean-test here.

**Comment by thockin** [comment]
This pattern also appears in cluster/saltbase/salt/top.sls for monitoring and logging

**Comment by zmerlynn** [comment]
Sorry, I meant to file this bug when I did the add-on work. Yeah, this is
all broken because of the use of "quoted true".
