### ISSUE TITLE
Configure master node same as slave node

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#4128]
This is pre-requirement for running all master components in a pod. #3853 was filed to run etcd as a pod. To make sure we really run etcd as a pod using Kubernete network model without specifying HostPort from spec, we need config the master node:

1) create networking bridge called cbr0 
2) config docker run with "--bridge cbr0 --iptables=false"
3) add default route for master node (on GCE). Need to figure out other cloud providers.

**Comment by dchen1107** [comment]
cc/ @ArtfulCoder @thockin

**Comment by zmerlynn** [comment]
Or finally switch to flannel. :)

**Comment by brendandburns** [comment]
This is now done for GCE and GKE.  We need to do it for AWS (and others?)

**Comment by brendandburns** [comment]
Marking this done, as of #5892 we now configure AWS, GCE and GKE this way.
