### ISSUE TITLE
Gracefully fail a rolling update?

### ISSUE THREAD

**Issue by jmreicha** [GoogleCloudPlatform/kubernetes#4140]
I accidentally created an entry in the new replication controller to pull an image that doesn't exist.

The rolling update is killing the known good containers and stuck trying to pull down the nonexistent image.

Is there a way to gracefully fail a rolling update if an image can't be pulled?

**Comment by cjcullen** [comment]
@jlowdermilk

**Comment by jlowdermilk** [comment]
It is safe to kill the rollingupdate command (running kubectl) at any time. Unfortunately, easy rollback is not yet implemented, but will be soon. In the meantime you can manually revert a partially completed rollingupdate by killing the rollingupdate command and then running
```
kubectl resize <original-controller> --replicas=<original-size>
kubectl stop <new-controller>
```

**Comment by jmreicha** [comment]
@jlowdermilk That's pretty much what I was thinking.  Glad to see that this functionality will be added in soon!

**Comment by jlowdermilk** [comment]
Just as an aside, roll forward does work. i.e., you can kill an in-progress rollingupdate then issue the same command and it should pick up where it left off.

**Comment by jmreicha** [comment]
@jlowdermilk working so far. It is a little slow but that's okay for me at this point :)

**Comment by bgrant0607** [comment]
We should document this.

**Comment by jlowdermilk** [comment]
@jmreicha, the default rate-limiting on rollingupdate is naive and overcautious. It waits 1min for the new pod to come up before each update round. You can adjust this via the `--update-period` flag. See `kubectl rollingupdate -h` for details (apologies the flag is buried; that's another issue #4142).

**Comment by jmreicha** [comment]
@jlowdermilk great thank you!

**Comment by bgrant0607** [comment]
@brendandburns is working on rollback/abort.
