### ISSUE TITLE
Delete guestbook example (php)

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#4144]
#4133 change guestbook-go to use replication controller for redis master.  I'm too lazy to change guestbook.  Here is what I wanna do instead:

* Delete guestbook
* Change e2e to use guestbook-go
* Create a new folder under examples, possibly `api-resources/`.  It should contains various resources, e.g. pod-restartpolicy.json, node-label.json, service-dnspolicy.json, etc.  This is super user-friendly.
* Change our tests to unittest against api-resources insteand

Any other AI or dependencies?

**Comment by bgrant0607** [comment]
@brendandburns Are you ok with this?

**Comment by rsokolowski** [comment]
I think that (3) and (4) should be done regardless of (1) and (2). In fact I've already started working on this while working on #1603. 

If guestbook gets deleted then I would suggest to rename guestbook-go to just guestbook. The "go" suffix is IMHO redundant and misleading.

**Comment by bgrant0607** [comment]
I think we need at least one PHP example. Do we have another?

I'd like all of the examples to be able to use `kubectl create -f <directory>`, so a subdirectory for the json makes sense to me.

**Comment by brendandburns** [comment]
Please don't delete the php example.  PHP developers >>> Go developers.

**Comment by rsokolowski** [comment]
What's the consensus on the issue ? If we want to keep the guestbook example then I can make the changes to use replication controller as I've already planned.

**Comment by bgrant0607** [comment]
Keeping it. Yes, please make the changes.
