### ISSUE TITLE
Kubernetes - Export performance data for debugging and monitoring

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#415]
We should export some performance data in both Kubelet and Kubenete
master to help the users understand specific problem. For example, in
this long create /pods example case, several performance data could be
exported and aggregated:

* VM boot time
* image loading time
* docker image pulling time
* docker container creation time
* kubenete scheduling round-trip time
* ...

**Comment by roberthbailey** [comment]
Monitoring of the master is covered by #1625.

**Comment by wojtek-t** [comment]
@vmarmol added a bunch of metrics to Kubelet:
#4753 #4792 #4818 #4901 #4904 #4905 #4906

What else should be done as part of this effort?

**Comment by vmarmol** [comment]
Closing this in favor of #1625 since that has more discussion (and is the same issue really).
