### ISSUE TITLE
Create a services test suite

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#4162]
Create a ginkgo suite to test services.  Initially this could contain the following tests:

TestClusterDNS
TestKubernetesROService

**Comment by rrati** [comment]
Part of the ginko-ization of the e2e tests
https://github.com/GoogleCloudPlatform/kubernetes/issues/3837

**Comment by cjcullen** [comment]
@zmerlynn

**Comment by zmerlynn** [comment]
Fixed by #4163.
