### ISSUE TITLE
Pod is not re-scheduled from failed node

### ISSUE THREAD

**Issue by peter-braun** [GoogleCloudPlatform/kubernetes#4166]
I have 3 identical nodes, 1 replication controller with 2 replicas of a pod. I simulate failure of one of the nodes to where pods have been scheduled by simply unplugging the node. Kubernetes realizes that the node has failed, but the pod gets not re-scheduled to the another available node.

The documentation at http://git.io/buSm says the following:

> "replication controller replaces pods that are deleted or terminated for any reason, such as in the case of node failure"

and 

> "replication controller replaces pods that are deleted or terminated for any reason, such as in the case of node failure"

So is that a mistake in the documentation or a missing or a bug? I use v0.10.

**Comment by brendandburns** [comment]
That's definitely a bug, and something that used to work correctly.  I will
investigate today, and follow up on this bug.

Thanks for the report.

Brendan

**Comment by bgrant0607** [comment]
Actually, it's really a missing feature -- #1366. I believe the last of the mechanisms we needed were added ~last week. @ddysher said he would start on it.

**Comment by bgrant0607** [comment]
@ddysher Is there a rudimentary solution that we could get in quickly, and then improve next week?

**Comment by brendandburns** [comment]
Just sent a simple PR with the fix.

**Comment by brendandburns** [comment]
Note that this issue is about a replication-controller set of pods.  This isn't #1366 which is a broader "fix pods on failed nodes in general" issue.

**Comment by bgrant0607** [comment]
Ah, a cache bug. Will take a look.

**Comment by brendandburns** [comment]
Re-opening this, because I reverted the relevant code in the replication controller with #4208

**Comment by ddysher** [comment]
@bgrant0607 I'll comment on the other thread later.  Sorry I was out yesterday.  I'm a bit free this weekend and should be able to work on the problem for at least one day.

**Comment by bgrant0607** [comment]
Fixed by #4241. Re-open if not fixed.

**Comment by davidopp** [comment]
Brian said this issue is fixed, though I didn't see any direct comment to that effect after Brendan's re-opening (and I haven't had a chance to test it).

**Comment by bgrant0607** [comment]
#4241 was merged a few days ago. It referenced #1366, but not this issue.
