### ISSUE TITLE
Eliminate service env. vars. from BoundPods

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#4176]
Service env. vars. are generated by Kubelet:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/envvars/envvars.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L775

They shouldn't be added to BoundPods:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/pod/bound_pod_factory.go#L71

This is causing our BoundPods objects to get too big and fail to write to etcd.

This will introduce a small race, but I think it's acceptable for now.

/cc @thockin @satnam6502 @brendandburns @dchen1107 @erictune

**Comment by pmorie** [comment]
@bgrant0607 For context, the reason we left the injection in the `BoundPodFactory` was that when the service env var injection was moved into the kubelet, not all cloud providers configured the kubelet with coordinates for the master.

**Comment by dchen1107** [comment]
@pmorie, can you elaborate more detail here? Which cloud providers? What is the workflow here then?

**Comment by bgrant0607** [comment]
Thanks @pmorie. Will comment on #3566.

**Comment by pmorie** [comment]
@dchen1107 I will see if I can dig up stuff from my notes.

**Comment by satnam6502** [comment]
@dchen1107 : any update on this? It would be good to know where we stand for this item for the fixit. Thanks.

**Comment by erictune** [comment]
When #4359 merges, boundPods won't have service env vars, which will reduce the size of boundPods.  Subsequent PRs will remove boundPods code entirely.

**Comment by erictune** [comment]
still more work to do on cleaning up boundpods, but the specific target of this bug is fixed.
