### ISSUE TITLE
Unable to automatically login to a private docker registry

### ISSUE THREAD

**Issue by heytrav** [GoogleCloudPlatform/kubernetes#4180]
Docker seems unable to automatically login to a private docker registry when re-starting a vagrant-coreos cluster.

When I re-start my vagrant-coreos cluster that I built the previous day, all of the pods hang in `Pending`. Looking at the `journalctl -f` output, I see lots of 

    Feb 05 19:41:49 node-01 docker[578]: time="2015-02-05T19:41:49Z" level="info" msg="+job pull(docker.domarino.com/rabbitmq-tiny, latest)"
    Feb 05 19:41:55 node-01 docker[578]: Authentication is required.

* I have a `/home/core/.dockercfg` file that is templated in from `node.yaml`
* When I login to the private registry from within the minion using `docker login <registry>`:
```
core@node-01 ~ $ docker login docker.domarino.com
Username (travis):
Login Succeeded
```

* If I try `docker pull <container>:latest`, I get:
```
Repository docker.domarino.com/rabbitmq-tiny already being pulled by another client. Waiting.
```

**Comment by brendandburns** [comment]
We can't find your .dockercfg for some reason.  The kubelet looks in the following locations:

```${HOME}/.dockercfg```
```/.dockercfg```
```${PWD}/.dockercfg```

Since you said it is in ``/home/core/.dockercfg``` is your location, but the kubelet runs as the root user, so you either need to copy it to ```/``` or the root user's ```${HOME}```

**Comment by heytrav** [comment]
Sorry, I should have indicated that I was following [these instructions](https://coreos.com/docs/launching-containers/building/registry-authentication/).

**Comment by brendandburns** [comment]
Yeah, I guess this is a delta between vanilla docker on CoreOS and Kubernetes on CoreOS, we don't use the docker client, we talk the docker API directly to the docker daemon, so we don't use the same paths apparently.

That said, someone (@kelseyhightower ?) should probably update the CoreOS config to make /home/core/.dockercfg work with kubernetes on CoreOS...
