### ISSUE TITLE
Idea: don't show cluster internal resources by default

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#4231]
There are quite few cluster internal resources (pods, services) that are not very interesting from kubctl user point of view. I think it would be good to not list them by default while using kubectl get command and add an optional flag that would also list them.
An alternative is to use namespaces for user resources and limit the scope of get command with --namespace flag.

**Comment by jlowdermilk** [comment]
I think putting them in a kubernetes.something namespace is what we planned to do. cc @satnam6502

**Comment by thockin** [comment]
I feel the opposite way - if you dont want to see them, you should make
your own namespace.

**Comment by rsokolowski** [comment]
Tim, I agree with you that user should make their own namespace and I'm
happy to update some examples to expose that.
However, for getting started experience where one has a simple project with
few services and doesn't really need to use namespaces present of internal
resources is disturbing, especially when combined with the fact that
results come in random order, plus new internal resources are being added.

2015-02-06 19:08 GMT-08:00 Tim Hockin <notifications@github.com>:

**Comment by jlowdermilk** [comment]
cc @bgrant0607

**Comment by vmarmol** [comment]
There was some discussion about having a "cluster-services" namespace to run this under. Do we consider that a good solution for this?

**Comment by satnam6502** [comment]
The agony that @jlowdermilk and I are discussing at #4298 is perhaps relevant.
How about for each cluster:
* A distinct network for the "system" cluster level services like monitoring and logging? This would allow us to instantiate multiple clusters in the same GCE project (perhaps similar arguments for other providers?).
* A separate namespace for cluster "system" services?

S

**Comment by bgrant0607** [comment]
@erictune 

This has been discussed before, with respect to the kubernetes service: #3293

**Comment by derekwaynecarr** [comment]
The API now has a Namespace object.  The server currently mandates the existence of the "default" namespace.  We could mandate the existence of two namespaces "cluster-services" and "default".  I see no issue there.  I actually tend to agree with @thockin that if you just don't want to see it, create a different one.  If we create that different one by default, sure, no big deal.

One thing I would like to see is that we turn on the "namespace must exist prior to usage" across all clusters via admission control.  Right now, I think only the Vagrant provider is requiring the namespace to be created prior to sticking namespace scoped resources in it.

**Comment by thockin** [comment]
I think the idea that cluster stuff is in "default" is a ship that has set sail, left the harbor, and is probably well over the horizon.

**Comment by derekwaynecarr** [comment]
@thockin - I am ok with that.  I do think if we update our examples to use a different namespace, that we need to turn on provisioning the namespace prior to usage requirement.

**Comment by bgrant0607** [comment]
Will we have a mechanism for cross-namespace operations once authorization is enforced? If not, then cluster services will be out of luck, regardless which namespace they are in.

**Comment by bgrant0607** [comment]
Closing in favor or #9356
