### ISSUE TITLE
kubectl get has random output order

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#4236]
If one lists all objects using "kubectl get" the output is random each time. This makes it very hard to read output if user is listing objects repeatedly (e.g. waiting until pod is running).

I think it'd be better UX if the order is deterministic (e.g. alphabetically by pod id).

**Comment by bgrant0607** [comment]
Hmm. We sort some things. For instance, describe sorts:
https://github.com/GoogleCloudPlatform/kubernetes/blob/8eeb2d1358d952004606f5b166d15d733780c10a/pkg/kubectl/describe.go#L133

I agree that sorting is more user friendly. PR would be welcome. :-)

**Comment by ddysher** [comment]
dup of #3772, and fixed in #3812

Which version are you using?

**Comment by fgrzadkowski** [comment]
I must have been synced to an old version.
