### ISSUE TITLE
Endpoints should be namespace scoped

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#4242]
Missed this when we landed the scope changes.

**Comment by derekwaynecarr** [comment]
Should or should not?

**Comment by smarterclayton** [comment]
Should, just like services

**Comment by derekwaynecarr** [comment]
I'm confused how they are not namespaced already but code review on phone is less than ideal.  We can synch tomorrow.

**Comment by smarterclayton** [comment]
They're showing up in the api docs as cluster scoped - maybe they're not in the list of kinds with cluster scope

**Comment by derekwaynecarr** [comment]
I enabled v1beta3 and looked at swagger output and see endpoints in namespace scope as expected.

I see following endpoints as expected:

GET /v1beta3/endpoints
GET, POST /v1beta3/namespaces/{namespace}/endpoints
GET, PUT, DELETE /v1beta3/namespaces/{namespace}/endpoints/{name}

**Comment by smarterclayton** [comment]
Ah, that's "all endpoints"

**Comment by derekwaynecarr** [comment]
right ;-)

**Comment by smarterclayton** [comment]
It's so clean I thought it was wrong.  Good job refactoring that.
