### ISSUE TITLE
infer containerPort in pod manifest from image EXPOSE metadata

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/kubernetes#425]
The `containerPort` attribute in the pod manifest could be inferred from the image metadata when not supplied by the developer.

That way developers won't have to duplicate the information they already put in EXPOSE in their Dockerfile.

This information looks available through the remote API on `/image` resources under the `PortSpecs` attribute:
https://docs.docker.com/reference/api/docker_remote_api_v1.13/#inspect-an-image

**Comment by jayunit100** [comment]
quick question, how is -p equivalent to containerPort?  Im confused on the exact semantics of containerPort, as it only takes (i think) one parameter, where as -p has two (-p 8000:8000)

**Comment by thockin** [comment]
Docker's -p flag publishes a port and allocates a host port at the same
time.

This is what kubernetes Ports[] used to do (but doesn't any more)

Docker's --expose flag and EXPOSE directive in Dockerfile just declares the
existence of a port.  This is what our Ports[] does today, though you can
OPTIONALLY allocate a host port.  So Ports[] can be used as -p or --expose.

**Comment by bgrant0607** [comment]
Due to our IP-per-pod model, you normally shouldn't need a host port, however.

**Comment by thockin** [comment]
Yes, sorry.  Almost nobody needs host ports.  If you think you need a host
port, call me and I will explain why you don't need a host port.

**Comment by proppy** [comment]
> Also, implementor would need to pull the image first (since docker registry still does not expose remote metadata, which is an issue that needs to be pushed at upstream).

Just a clarification that you can get that info without pulling the image, we do it in podex https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/podex/podex.go#L174

**Comment by smarterclayton** [comment]
Yeah - I started here: https://github.com/smarterclayton/go-dockerregistryclient from upstream but haven't had the time to wire in proper local auth lookup using the existing code, so it's  still public only.

**Comment by bgrant0607** [comment]
This is obsolete.

**Comment by bronger** [comment]
Sorry for coming late to the party but what was the result of the above mentioned "design discussion on EXPOSE vs PUBLISH"?  Does Dockerfile's EXPOSED have any meaning in the Kubernetes world?

**Comment by smarterclayton** [comment]
It has no effect at runtime.  Tools sometimes use it to generate services
or pods (podex, compose2kube, Openshift)

On Oct 2, 2015, at 11:00 AM, Torsten Bronger <notifications@github.com>
wrote:

Sorry for coming late to the party but what was the result of the above
mentioned "design discussion on EXPOSE vs PUBLISH"? Does Dockerfile's
EXPOSED have any meaning in the Kubernetes world?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/425#issuecomment-145051614>
.
