### ISSUE TITLE
test-cmd.sh should test resizing replication controller

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#4250]
The `test-cmd` script currently does not test resizing replication controllers; this is a central use-case and should have coverage in that script.

**Comment by zmerlynn** [comment]
This is already tested in the guestbook e2e, which is getting rewritten in Go as part of #4389. We need to figure out how `test-cmd.sh` fits into the world at some point.

**Comment by pmorie** [comment]
@zmerlynn clarify what you mean by 'the world' ?

Also, I think @sdminonne recently did this in #4649.

**Comment by sdminonne** [comment]
@pmorie @zmerlynn yeah... and Lenaic today did this https://github.com/GoogleCloudPlatform/kubernetes/pull/4773 as part of our `kubectl

**Comment by zmerlynn** [comment]
I was more commenting that it seems duplicative to test much in both places, but the e2e test has its place, too.

**Comment by zmerlynn** [comment]
It sounds like this issue should be closed. :)

**Comment by pmorie** [comment]
@zmerlynn I wondered about the wording 'the world', because there's a use-case for us downstream wherein we want to run a sanity check of OpenShift against upstream's test-cmd or something like it:

https://github.com/openshift/origin/issues/739
