### ISSUE TITLE
Move liveness tests to the pods suite

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#4253]
Park of ginkgo-ization
https://github.com/GoogleCloudPlatform/kubernetes/issues/3837

**Comment by zmerlynn** [comment]
Per IRC, @rrati is working on this

**Comment by rrati** [comment]
@zmerlynn

**Comment by rrati** [comment]
Pushed an update yesterday to address comments.

@zmerlynn

**Comment by a-robinson** [comment]
@rrati what's the status of this? There's an issue open to de-flake this test (#4501), but it's tough to do that if the code is in the middle of being moved to ginkgo.

**Comment by rrati** [comment]
This has been merged.
