### ISSUE TITLE
Apply for GSoC 2015

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#4259]
Could you apply for [Google Summer of Code 2015](https://www.google-melange.com/gsoc/homepage/google/gsoc2015)? I've seen some students over at IRC looking for hints on how to contribute. @thockin replied to a guy who was speaking in his name and of two others, so there should be interest in this.

I'd be more than willing to pass on the word :-)

**Comment by bgrant0607** [comment]
Good idea.

**Comment by mbforbes** [comment]
FYI the "Org Application Deadline" is February 20 at 19:00 UTC (11am PT).

**Comment by mbforbes** [comment]
Unsure exactly how to triage this. If anyone would like to claim it would simplify.

**Comment by pires** [comment]
Just a reminder, 6 days to go.

**Comment by davidopp** [comment]
I don't understand -- what would we need to do here?

**Comment by bgrant0607** [comment]
@brendandburns @thockin 

I submitted the application. I created a github label for the project idea list:
https://github.com/GoogleCloudPlatform/kubernetes/labels/kind%2Fgsoc

If you have ideas for projects, file an issue and add the label or, if you can't, mention the issue here and I'll add the label.

**Comment by thockin** [comment]
Top of my head:

JobController and tooling

Kubelet work (goroutine per pod or other large reworks)

kube-proxy as pure iptables

more complex demo apps

I have an intern this summer too, so the same list applies there :)

Performance and de-pessimization

Make DNS work from the node

service pre-declaration (if we can come to agreement on it :)

using docker stuff - ulimits, extra GIDs

new docker stuff - parent cgroups, shared PID and user namespaces, network
plugins, etc

**Comment by bgrant0607** [comment]
JobController and replacing proxy with iptables are good ideas. I think the project needs to be better defined than most of the other things -- it's not quite the same as an intern, IIUC. Maybe "parallelize kubelet and/or apiserver" could work.

**Comment by bgrant0607** [comment]
GSoC application is now complete. Let me know if you have more project ideas.

**Comment by bgrant0607** [comment]
Started a wiki: https://github.com/GoogleCloudPlatform/kubernetes/wiki/Google-Summer-of-Code-(GSoC)

**Comment by bgrant0607** [comment]
Galaxy listed Kubernetes integration as a project: https://wiki.galaxyproject.org/Develop/GSOC/2015Ideas

**Comment by rashmimargani** [comment]
Hi, @bgrant0607  , i'm GSOC 2015 applicant.. I'm willing to work on pod based networking models. my project idea is to enable multicloud integration of Kubernetes through pod based networking model. I started reading  docs related to pod based.... Please suggest me to do few more task, so that i'll able to come with good project proposed and be efficient candidate to team.

**Comment by xudifsd** [comment]
@thockin @bgrant0607 hi, goroutine per pod in kubelet interested me, but I failed to find any issue related with it, is there any?
BTW, it is **so** hard to find any idea that no one is working on

**Comment by bgrant0607** [comment]
@xudifsd Goroutine-per-pod was implemented #4895. Sorry. Yes, the project is moving quickly.

AFAIK, nobody is working on the per-node controller #1518, or job controller #1624, or converting replication controller to a plugin #3058.

Efficient label queries, reverse label lookups, field-based selection, and field filtering would all be great to have, also.

A Kubelet UI would be great to have -- very useful for debugging, and for standalone kubelet scenarios.

**Comment by satnam6502** [comment]
Are we doing a per-node controller? The thread seems cool on the idea
(Tim's comments). If I thought this is something we definitely wanted then
I would have jumped on it earlier.

S

**Comment by bgrant0607** [comment]
@satnam6502 Yes, we are. Tim developed a prototype #2491.

**Comment by bgrant0607** [comment]
@rashmimargani Networking is a complex topic. Take a look at #3760 or #260. If you just want to get your feet wet, take a look at #15 (yes, 2 digits).

**Comment by thockin** [comment]
I was won over.

**Comment by volyihin** [comment]
Is this issue #3692  still actual? Can I take part in designing this feature during gsoc?

**Comment by you-n-g** [comment]
Hi
Could you tell me how many slots have been allocated to k8s  in gsoc 2015? I'm really concerned about it.

**Comment by bgrant0607** [comment]
@you-n-g We'll be selecting projects next week. It's true that we have more proposals than slots (and mentors).
