### ISSUE TITLE
kubectl.sh crashes unhelpfully

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4264]
When run in a Makefile an error exit status is reported (not no more information). When run on the command shell the command returns no output and does not report an error.

```
$ make
../../../cluster/kubectl.sh get pods
make: *** [all] Error 1
$ ../../../cluster/kubectl.sh get pods
$
```

**Comment by satnam6502** [comment]
I've reported this before.

**Comment by satnam6502** [comment]
This happened when I had the wrong zone in my `config-default.sh` file (my fault).
However, we should give a better error message.

**Comment by bgrant0607** [comment]
What version of kubectl.sh are you running? Do you have pull #4175?

@wojtek-t

**Comment by wojtek-t** [comment]
hmm - it worked for me with #4175. If not can you please write how to replicate this issue - I'm happy to work on it.

**Comment by satnam6502** [comment]
Create a cluster.
Change the zone in config-default.sh to some other zone.
Run kubectl.sh get pods

Thanks

**Comment by wojtek-t** [comment]
That's strange - it works for me. What I've done is:
1. run kubernetes in us-central1-b
2. change cluster/gce/config-default.sh to point to us-central1-a
3. ran ./cluster/kubectl.sh get pods

Here is the output:
wojtekt@wojtekt-work:~/kubernetes$ ./cluster/kubectl.sh get pods
Project: groovy-sentry-504
Zone: us-central1-a
ERROR: (gcloud.compute.instances.describe) Could not fetch resource:
 - The resource 'projects/groovy-sentry-504/zones/us-central1-a/instances/kubernetes-master' was not found

I think that this error is quite helpful (and it's definitely not crashing silently for me).
Can you please check that you're synced to  #4175 ?

**Comment by satnam6502** [comment]
I build from head < 30 minutes ago.
Never mind. I will close this and re-open if it happens again. Thanks for your help.
```
commit 122124f9e10bfb2ce94ba8df1b9ed31ee1730f8a
Merge: b08bd86 9d9bca9
Author: Jeff Lowdermilk <tiro.jeff.ml@gmail.com>
Date:   Thu Feb 5 14:58:24 2015 -0800

    Merge pull request #4175 from wojtek-t/kubectl_silent

    kubectl doesn't fail silently with no k8s master
```
