### ISSUE TITLE
kubectl.sh create service crashes unhelpfully

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4270]
I've reported this before.

```
$ ../../../cluster/kubectl.sh create -f serve-hostnames-service.yaml
Running: ../../../cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl create -f serve-hostnames-service.yaml
F0209 17:34:34.126307   30570 create.go:78] 
```

**Comment by satnam6502** [comment]
From a Makefile I get exit status 255.
```
Running: ../../../cluster/../cluster/gce/../../_output/dockerized/bin/linux/amd64/kubectl create -f serve-hostnames-service.yaml
F0209 17:38:36.236419   31616 create.go:78] 
make: *** [create] Error 255
```

**Comment by mbforbes** [comment]
Just to be clear (sorry for the basic question), are you saying that when the service `.yaml` file is malformed the crash is unhelpful for debugging? Or that creating any/all services using `kubectl.sh` is currently broken?

**Comment by satnam6502** [comment]
The YAML file is not malformed. I think there was something perhaps not quite right about firewalls/rules etc. and this caused kubctl.sh to crash unhelpfully.
