### ISSUE TITLE
0.9.3 Linux binaries not released

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#4277]
When trying to update to 0.9.3 I noticed there's no build in the usual place. For instance, [kube-apiserver 0.9.3](https://storage.googleapis.com/kubernetes-release/release/v0.9.3/bin/linux/amd64/kube-apiserver) is not available.

0.10.1 is, though.

**Comment by brendandburns** [comment]
Oops... I guess that slipped through the cracks.  (we need to automate this whole thing better, it's still pretty manual.)

You can download the full release here: https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.9.3

Given that 0.10.1 is out, I'm not planning on pushing out 0.9.3 unless there is a strong need.

Closing this issue, if you need the 0.9.3 binaries pushed, please re-open.

Thanks! (and sorry for the mess up)

--brendan

**Comment by pires** [comment]
Just moved to 0.10.1 and am happy with it, so far ;-) thanks
