### ISSUE TITLE
Pod init hooks

### ISSUE THREAD

**Issue by cnaize** [GoogleCloudPlatform/kubernetes#4282]
Hello!

I'm looking for `restart policy` for `pod`'s `containers`.
Something like this: 
https://github.com/GoogleCloudPlatform/kubernetes/pull/1147
https://github.com/GoogleCloudPlatform/kubernetes/issues/127
but for `containers` in `pods`.

Is it possible? Is it in plans?

**Comment by bgrant0607** [comment]
The restart policy applies to all containers within the pod.

Are you asking for the ability to specify a different restart policy for each container? If so, what is your use case? 

We aren't currently planning to support that directly, in a general form, but will likely support a specialized form, such as for volume initialization (#831).

This is something we debated early in the project -- see #127.

**Comment by pythonpowerd** [comment]
bgrant0607, we need this for easily specify run-once containers, not only for db or volume initialization but for run-once in general.
P.S. cnaize from our team too)

**Comment by bgrant0607** [comment]
Specify `"restartPolicy": { "never": {} }` in your pod manifest.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pod-states.md

We should create an example, such as:
http://georgkunz.com/blog/2014/11/18/one-off-tasks-with-kubernetes/

cc @dchen1107

**Comment by pythonpowerd** [comment]
We considered about this, but restart policy = Never  means that all other containers will not be auto-restartable too. In our case we need one or more container with policy = never and other with policy = always.
For example, I create pod with db, myapp, redis, and one container that makes some garbage collection for my containers or gather statistics, never mind, it must run-once, and after some time I will run it again via docker start... maybe few times.

**Comment by thockin** [comment]
Would it be sufficient to have it go to sleep instead of exit?  It could
even listen for signals when to re - run, rather than someone using docker
start directly.

**Comment by pythonpowerd** [comment]
@thockin Listening to signals it's a nice idea anyway(thanks for it!), but that containers belongs to our customers so we don't have any access to them and even don't know what exactly they do, we just need to provide functionality to our users to make in pod some containers that "run and exit" and "run on demand in this pod".

**Comment by bgrant0607** [comment]
@pythonpowerd This kind of sometimes-running, sometimes-not scenario doesn't fit well with our declarative model, unless there are well-defined trigger criteria, in which case we could potentially create a hook to invoke it. We've talked about doing that for initialization containers #831, for instance, and for pod-local cron #2156.

If you're going to run the container by hand, you might be interested in #3763. You could also expose the Docker socket into the pod and add a container that periodically launches the user's container.

**Comment by bgrant0607** [comment]
cc @bkeroackdsc

**Comment by thockin** [comment]
Dup of #1589
