### ISSUE TITLE
Proxier and LB are not namespace aware

### ISSUE THREAD

**Issue by pweil-** [GoogleCloudPlatform/kubernetes#4288]
Currently, the proxier and loadbalancer code is not namespace aware.  They use an internal caching structure that is keyed based on the service name.  

For example: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/proxier.go#L466
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/config/config.go#L225
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/roundrobin.go#L212

This results in a 'last in wins' behavior when creating service portals.  Two services with the same name, in different namespaces results in the first service having its portal closed when opening the portal for the second service.

```
I0210 11:23:10.265653    6654 proxier.go:556] Opened iptables from-containers portal for service "database" on TCP 172.30.17.233:5434
I0210 11:23:10.279412    6654 proxier.go:567] Opened iptables from-host portal for service "database" on TCP 172.30.17.233:5434
I0210 11:23:10.415849    6654 rest.go:88] Creating deploymentConfig with namespace::Name: ns1::database
I0210 11:23:11.571004    6654 proxier.go:579] Closed iptables portals for service "database"
I0210 11:23:11.589418    6654 proxier.go:556] Opened iptables from-containers portal for service "database" on TCP 172.30.17.15:5434
I0210 11:23:11.610391    6654 proxier.go:567] Opened iptables from-host portal for service "database" on TCP 172.30.17.15:5434
I0210 11:23:11.758293    6654 rest.go:88] Creating deploymentConfig with namespace::Name: ns2::database
```

Suggested fix: refactor these components to use the namespace aware cache/reflector pattern or adjust the caching mechanism to use the namespace as part of the key.  

/cc @ncdc @ironcladlou @bparees @pmorie

**Comment by pmorie** [comment]
I don't think there's an appropriate reflector store yet to be used here, since the store has to deliver deletes (or allow you to infer them).  I suppose we could use `UndeltaStore`, but I personally would rather implement the concept that @erictune and I discussed in #3521 (not my port of the origin `EventQueue`, but Eric's proposed store).

Any thoughts, @erictune?

**Comment by roberthbailey** [comment]
There's a great detailed description of this problem in #4293 (which I've closed as a dupe).

**Comment by quinton-hoole-google** [comment]
@erictune Your thoughts about pmorle's suggestion above, before I dive in and try to fix this bug?  In summary which of the following approaches would you prefer?

1. Use the existing UndeltaStore?
2. Implement the Store proposed by you in #3521?
3. Do some other simplistic adjustment to the caching to incorporate the namespace into the cache key.

Note that I'm very new to the code base, so the above questions might not even make sense, in which case feel free to say so :-)

**Comment by thockin** [comment]
I think the simplest fix is to just extend "name" to be "namespace/name" in
those keys?  I *think* that should suffice, no?

**Comment by quinton-hoole-google** [comment]
Yes, I was hoping that someone would confirm that.  I'll get going on the
basis of that assumption.

**Comment by lavalamp** [comment]
I think we need, in a very general, obvious place, something like:

```go
type Identifier struct {
  Namespace, Name string
}
```

Which can be used for things like keys to maps. Appending stuff with slashes in a string is asking for bugs in the future.

**Comment by thockin** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/3731

**Comment by derekwaynecarr** [comment]
I am fine with the key func approach in cache store

**Comment by quinton-hoole-google** [comment]
@lavalamp, agreed, except that "Identifier" is probably not right, as it's ambiguous with UID, which is a different thing entirely. 

https://github.com/GoogleCloudPlatform/kubernetes/blob/556e59b5127ba5b3eef7a6c4a3f0d34db8924d9c/docs/identifiers.md

Perhaps FullyQualifiedName rather than Identifier?  QualifiedName?

**Comment by lavalamp** [comment]
QualifiedName works for me.

**Comment by quinton-hoole-google** [comment]
QualifiedName it is, unless someone objects soon.

**Comment by thockin** [comment]
We have a concept of qualified name already which does not QUITE match this.

Qualified name is:

 [ DNS_SUBDOMAIN "/" ] DNS_LABEL

This would be DNS_SUBDOMAIN "/" DNS_SUBDOMAIN - no optional prefix.

We have another half-deprecated concept of "fullname" which is
name.namespace, which is also not what we want here.

We could prefactor to s/FullName/JoinedName/g and then claim "FullName".

Or we could go with NamespacedName or somethng.

**Comment by quinton-hoole-google** [comment]
NamespacedName works for me.  It's explicit and unambiguous.

**Comment by erictune** [comment]
Fine with fixing it the expedient way and later refactoring to a common library.  The bug that covers the latter is https://github.com/GoogleCloudPlatform/kubernetes/issues/3412.

**Comment by erictune** [comment]
@pmorie agree that you could use Reflector and UndeltaStore here, or the pattern discussed in #3521

**Comment by pweil-** [comment]
@quinton-hoole-google - If it helps in your fix, I actually hacked up the keys locally to add a namespace to validate the issue but didn't submit it so there could be a design discussion: https://github.com/pweil-/origin/pull/16/files  I can't guarantee that I hit all the spots but I was able to test multiple services manually afterwards.

**Comment by quinton-hoole-google** [comment]
Cool, thanks pwell.  That definitely helps.

**Comment by mikesimons** [comment]
@quinton-hoole-google There are failing tests for this linked on #4695 if they are of any use :)

**Comment by thockin** [comment]
Quinton: status on this fix?

**Comment by quinton-hoole-google** [comment]
It's done.  Just need to self review before submitting a PR tomorrow.

**Comment by thockin** [comment]
status?

**Comment by thockin** [comment]
Fixed

**Comment by pweil-** [comment]
:beers:
