### ISSUE TITLE
Scheduler configuration via config file

### ISSUE THREAD

**Issue by abhgupta** [GoogleCloudPlatform/kubernetes#4303]
A series of enhancements have been made to the scheduler to make it easily extensible. Admins can select/specify the algorithm provider, thereby selecting a predefined list of predicates/priorities/weights. Additionally, admins can also customize the scheduler by selecting a custom set of predicates/priorities/weights. 

The former (specifying an algorithm provider) is something that can be done using a flag on the scheduler command line. The latter (specifying custom set of predicates/priorities/weights) is something that the admin cannot specify today without changing the code.

I propose that we allow admins to specify a configuration file for the scheduler that provides all this information. We can start with a configuration file and if later we feel that this information is best captured/stored in etcd (or some other mechanism), then the switch should be fairly easy. I haven't given any thought to the format of the configuration file content except it being a JSON file. 

However, I had a question regarding the existing command line flag for algorithm provider. 
1. Should we remove this flag and allow admins to specify it in the cofig file alone with the default being the DefaultProvider?
2. Should we retain this flag in the command line and introduce the concept of "CustomProvider"? If this "CustomProvider" is selected, the scheduler could then expect the configuration file for the list of predicates/priorities/weights.

**Comment by bgrant0607** [comment]
Configuration is definitely where we want to go.

We should remove the flag, but announce it on kubernetes-dev. A search doesn't show anyone using it, fwiw.

**Comment by abhgupta** [comment]
@bgrant0607 I had initially favored removing the algorithm provider flag from the CLI as well. However, my current implementation (PR linked) still retains that as I found that it leaves the configuration file to just deal with predicates and priorities, and it does not have to worry about algorithm providers.

**Comment by abhgupta** [comment]
Closing this issue since the implementation PR #4674 has been merged.
