### ISSUE TITLE
apiserver proxy stopped accepting namespaces

### ISSUE THREAD

**Issue by enisoc** [GoogleCloudPlatform/kubernetes#4304]
The apiserver proxy rewrites links to the form "/proxy/ns/default/...":

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/proxy.go#L162

But this form stopped working recently, seemingly around https://github.com/GoogleCloudPlatform/kubernetes/commit/18609e17062ad4a56c3533f80014299815bfee76. The "/proxy/ns/default/..." form always returns "404: Page Not Found", similar to the problem seen in https://github.com/GoogleCloudPlatform/kubernetes/pull/4283. If you remove "/ns/default" from the URL, it works.

**Comment by derekwaynecarr** [comment]
I can investigate this as well.

**Comment by derekwaynecarr** [comment]
I see the issue, sending a PR.

**Comment by derekwaynecarr** [comment]
The proxy path needs to be built with knowledge of the apiversion of the incoming proxy request, and it needs to be updated to use the knowledge from the restmapper.  This is a little trickier than I have time for right now, but it should definitely not be hardcode appending the /ns form.

Not clear why this is not also caught by our test case.  I can try and look at this more in the AM unless someone else wants to take a look in interim.

/cc @smarterclayton

**Comment by lavalamp** [comment]
Let me steal this one from you, I think I can fix it.

**Comment by derekwaynecarr** [comment]
Have at it.  /cc me on your PR

**Comment by lavalamp** [comment]
Sorry, I see you've already got a PR out!

**Comment by derekwaynecarr** [comment]
No problem.

I would be happy if you finished my PR relative to the commit I started.  It will be a few days before I can go back to looking at this issue.

I think v1beta1/v1beta2 proxy urls in go-restful need to always but the namespace scope in the path as the ultimate fix.

I do want the proxy to have access to the restmapper per my PR.

----- Original Message -----

**Comment by vishh** [comment]
Any updates @lavalamp ?

**Comment by vishh** [comment]
This is breaking monitoring since it requires the proxy. Bumping up the priority to P0.

**Comment by lavalamp** [comment]
Sorry for dropping this. Working on a fix.
