### ISSUE TITLE
Instances::IPAddress - internal or external IP?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#4324]
I'm not entirely clear whether Instances::IPAddress should return the internal IP or the external IP for an instance (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L61).

On GCE, it is `res.NetworkInterfaces[0].AccessConfigs[0].NatIP`, which is the external IP (right?) https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/gce/gce.go#L290

On AWS, it is currently `resp.Reservations[0].Instances[0].PrivateIpAddress`, which is the internal IP https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws.go#L145

There's also a meta-question on whether we need a richer model here (whether we should expose multiple IP addresses; at least on EC2 it is cheaper/faster/better to use the internal IP for internal communication, I think the same applies on GCE?)

**Comment by roberthbailey** [comment]
That part of the interface was added by @brendandburns so he might be able to provide more insight than the comment that is on the function.

**Comment by alex-mohr** [comment]
I think Instances::IPAddress should always return the primary private IP, and we should have another method for ::ExternalIPAddress that may or may not be present.

**Comment by justinsb** [comment]
The API now exposes a rich IP address model; closing
