### ISSUE TITLE
Retry handling in queue-based controllers is flawed

### ISSUE THREAD

**Issue by ironcladlou** [GoogleCloudPlatform/kubernetes#4330]
## Fee-FIFO-fum

The Kubernetes `plugin/scheduler` follows a pattern which has become canonical downstream in OpenShift. The pattern employes the `api/cache` package thusly:

1. Combine a `Reflector` with a `FIFO` to drive a state reconciling controller
2. Handle a single unit of work in the controller, where the work unit is a single resource returned from the `FIFO`
3. Defer errors to a handler

This pattern is dependent on the event compression characteristics of `FIFO`: newer resources added to the queue will be compressed with an existing older resource in the queue, so that the result of the add operation is a single, newer queue entry.

The semantics of `FIFO` presents error handling challenges in the context of the state reconciling controller pattern described. If a recoverable error occurs when processing a resource from a `FIFO`, it's almost always desirable to retry processing (according to some policy: for the sake of this discussion, we'll assume the policy is to retry forever).

The most intuitive approach to implementing a retry is to simply re-queue the resource into the `FIFO`; however, simply re-queueing the resource can lead to undesirable interactions with the compression behavior. For example, consider this timeline:

1. Given a queue, `Q=[A.1, B.1, C.1, D.1]`
2. Controller consumes `A.1`, `Q=[B.1, C.1, D.1]`
3. Concurrently, a `Reflector` receives an update to `A` , now `Q=[B.1, C.1, D.1, A.2]`
4. Controller fails to process `A.1` and re-queues, now `Q=[B.1, C.1, D.1, A.1]`

The `A.2` state has been lost and will not be processed until the controller is restarted (which will result in the `FIFO` being initially seeded with the latest state of all resources).

To account for the compression interaction, there's a small fix (demonstrated in [the Scheduler factory](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L225)): Prior to re-queue, the resource (`A` in the example) is re-acquired from a client call. This ensures that:

1. Any older resources still enqueued will be (desirably) updated during re-queue
2. Any changes to the re-queued but yet-to-be-processed resource will be (desirably) updated to a newer state

At a glance, this neatly solves the original problem. However, the fix itself introduces another problem: the retry logic itself can fail. The retry logic now has an external/volatile dependency in the re-acquisition call. I believe I've established it's unsafe to re-queue a stale resource, and that any retry logic must itself be able to retry failures (to retry).

## Solutions

One possible approach (not very well thought out) is to introduce the notion of versioning into the `FIFO` to allow the rejection of stale resources, which would alleviate the need to refresh the resource prior to a re-queue. The `Add` would no-op if a "newer" resource already exists in the queue. This seems like even more complexity to a set of structures which are rapidly growing (e.g. key functions, indexing). My fear is introducing more subtle bugs.

Another approach is to sidestep the problems by replacing the use of `FIFO` with periodic `Store` reconcilers. Taking the scheduler as a convenient example: if a `Store` of all Pods were periodically reconciled, then any Pods which failed to process on the previous iteration would simply be re-processed using the latest resources obtained during the next interval's list. One drawback is a loss of efficiency as the controller potentially churns through no-ops for most of the Pods in the `Store` which were successfully processed last time; however, there's room for optimization at this level (for example, by tuning the `ListWatcher` implementation to only provide un-bound Pods). Are there gaps in this approach?

I'd like to discuss whether the current or future `FIFO` is the appropriate construct to use in this class of controller.

**Comment by ironcladlou** [comment]
Downstream effects: https://github.com/openshift/origin/issues/824

**Comment by ironcladlou** [comment]
cc @smarterclayton @pmorie @pweil- @derekwaynecarr @lavalamp

**Comment by smarterclayton** [comment]
Does this have an impact on scheduling today?

**Comment by ironcladlou** [comment]
@smarterclayton 
>Does this have an impact on scheduling today?
I need to write a test, and surely somebody can correct me on this offhand, but my reading of the code suggests that if a pod fails to be scheduled due to an apiserver connectivity issue, and then fails on the retry due to a connectivity, no further attempts will be made to schedule the pod until the controller is restarted (triggering a `ListWatcher` list call to seed the queue).

**Comment by brendandburns** [comment]
I don't think this is true.  The scheduler constantly re-polls the state of
pods, and schedules things that have an empty Host field.  I'll re-check
the code when I get back to my laptop.

Brendan

**Comment by ironcladlou** [comment]
@brendanburns 
>I don't think this is true.  The scheduler constantly re-polls the state of
pods, and schedules things that have an empty Host field.  I'll re-check
the code when I get back to my laptop.

I poured back over `plugin/pkg/scheduler` and couldn't see any supplementary polling, but I assume I'm just missing something. I'll follow up tomorrow. Thanks!

**Comment by smarterclayton** [comment]
I think we were only polling status, but we don't translate that into FIFO events.

----- Original Message -----

**Comment by smarterclayton** [comment]
The replication controller is resynchronizing everything every <time> in order to avoid this problem as well.

----- Original Message -----

**Comment by bgrant0607** [comment]
@davidopp

**Comment by erictune** [comment]
What was the resolution on this issue, if any?

FWIW, I definitely endorse the Store with reprocessing approach.  The requeue seems subject to subtle errors.

**Comment by bgrant0607** [comment]
Presumably should be addressed in @lavalamp's controller framework.

All controllers and async. initializers, including schedulers, must be level-based. Edge-based approaches, such as watch/queuing, must be reducible to performance optimizations -- effectively notification of what state has changed and when to re-check level-based reconciliation of desired state and current state. 

I agree that the same object shouldn't be enqueued more than once, and that the most recent state available should be used when an object is processed.

I don't think anyone on our side looked at the scheduler closely enough to confirm or deny the reported potential problem.

**Comment by smarterclayton** [comment]
Necessary support is in the core objects. Here's the Openshift side code:
https://github.com/openshift/origin/blob/master/pkg/controller/controller.go

And an example: https://github.com/openshift/origin/blob/master/pkg/deploy/controller/deploymentconfig/controller.go

Controller is suitable for reuse.  Scheduler is protected by the fact it periodically reprocesses every pod.

**Comment by lavalamp** [comment]
I think the introduction of cache.Queue's AddIfNotPresent resolves the original concern.

Additionally, please see the pattern introduced in the new endpoints controller, and the queue it adds: #6943
