### ISSUE TITLE
High Availability for the scheduler and other K8s master components

### ISSUE THREAD

**Issue by abhgupta** [GoogleCloudPlatform/kubernetes#4331]
We need to have HA for the various Kubernetes master components. To allow the Kubernetes master to scale horizontally, we'll have to ensure that the various components that run on the master like the scheduler, deployment controller, replication controller, endpoints controller, etc can all work well in a scaled environment. Essentially,
1. they should be able to spread the work among themselves and not step on each other
2. the system should be resilient to one of the master going down
3. in the very least, there should be failover - a single master being active and another in hot standby, ready to take over when the active master dies

Today, the controllers make a local cache of the dataset they are working on and use that as a work queue and this creates an issue with scalability (since there is no central work queue). Again, I don't have a concreate proposal for this, but would like to have a discussion and gather some feedback on this issue.

**Comment by abhgupta** [comment]
I couldn't readily find an existing issue that dealt with this. If one exists already, please let me know.

**Comment by roberthbailey** [comment]
Parts of this have been discussed in #473.

**Comment by bgrant0607** [comment]
Yes, let's use #473

**Comment by roberthbailey** [comment]
Closing as a dupe.
