### ISSUE TITLE
what is the purpose of specifying containerPort in Service entity?

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#4332]
Since service is supposed to serve as a sort of proxy/redirect for clients/users/containers, it is important to configure on which port it's available. 
But what is the meaning of allowing to specify container port property? User is not customizing its underlying conf, no container is specified, etc.

**Comment by roberthbailey** [comment]
Reading through the documentation (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L737) I don't find the purpose of this field clear. 

Assigning to @thockin to clarify (and possibly update the docs).

**Comment by a-robinson** [comment]
ContainerPort is used to decide which of the container's ports should be used by the service in case a container has multiple ports. For example, in our Cassandra example, the [cassandra container](https://github.com/GoogleCloudPlatform/kubernetes/blob/180108b5f927327c309ed67ae9050648ad71d5d7/examples/cassandra/cassandra.yaml) opens up two different ports. The [service config](https://github.com/GoogleCloudPlatform/kubernetes/blob/180108b5f927327c309ed67ae9050648ad71d5d7/examples/cassandra/cassandra-service.yaml) then specifies the one that requests to the service should hit.

I can add on to the comments in the API files if that'll help.

**Comment by abonas** [comment]
@a-robinson thank you for the clarification and the fix. 

So the container port is actually the port on the "target" part, and not of the service itself, right?

**Comment by a-robinson** [comment]
Yes, precisely.

**Comment by bgrant0607** [comment]
v1beta3 hasn't had field descriptions added yet. That's another issue.

The v1beta1 description is:
`number or name of the port to access on the containers belonging to pods targeted by the service; defaults to the container's first open port`

What's not clear about that?
