### ISSUE TITLE
Remove HostPort from e2e pod configurations

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#4333]
Some of the e2e tests specify HostPort in their pod configurations.  This can cause issues running those tests if the port is already in use.

**Comment by roberthbailey** [comment]
We've been removing these over the last week and a half and I think that https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/rc.go#L89 may be the only one left remaining.

**Comment by alex-mohr** [comment]
We need to decide if HostPort is a supported use case for Kubernetes -- and if it's supported, then it needs e2e test coverage to ensure it remains functional.  Note that supported and not-preferred are orthogonal.  My understanding is that it's supported-but-not-preferred and that there are reasonable use cases for using it.
