### ISSUE TITLE
Tracking conversion of "Getting Started Guides" to use apiserver for kubelet and kube-proxy.

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#4334]

**Comment by erictune** [comment]
Email sent to kubernetes-announce:

We will soon commit some changes which may cause subsequently-built Kubernetes binaries to not work with some of the Cluster Setup Scripts.  "Cluster Setup Scripts" means the saltstack files, cloud-config files, cloudformation files, Vagrantfiles, and/or other files referenced by a "Getting Started Guide".  

The following Getting Started Guides should work fine for creating new clusters now and after the changes are committed:
- GCE (saltstack)
- GKE
- AWS (saltstack)
- Azure (saltstack)
- Vagrant (uses saltstack)

We will ask for community assistance to fixup other Cluster Setup Scripts, but won't hold up the commit for those fixes. If you use one of these other types, then you should stick with kubernetes release 0.10.x or earlier for now.

Additionally, if you attempt to upgrade the kubernetes binaries on a cluster without also using the latest Cluster Setup Scripts, the upgrade may fail.  

Progress will be tracked in this issue:
https://github.com/GoogleCloudPlatform/kubernetes/issues/4334

**Comment by erictune** [comment]
When #4359 merges, users on the lagging platforms will no longer get service env vars in their pods.

**Comment by pietern** [comment]
Thanks for the heads up, I'll check this out for vSphere before Monday.

**Comment by erictune** [comment]
All the salt-based providers are converted.
PRs are sent out for all remaining providers which have their flags in our repo.
I will not endeavor to fix distros which keep their flags elsewhere (e.g in an rpm).
This includes JuJu (@whitmo), Fedora (@eparis),  Centos (@coolsvap).

**Comment by erictune** [comment]
Related PRs: #5245 #5249 #5215 #5221
Probably lots others I could not find easily.

**Comment by resouer** [comment]
@erictune Thanks for he heads up, we'll fix ubuntu-cluster stuff in next week.

**Comment by chuckbutler** [comment]
@erictune I see this was opened 29 days ago. I've just completed iteration 1 of the juju cluster integration bits and curious if I've based it off a recent enough edition, I'm working off of a branched master, and things are working on our end. Relevant PR - is here: #5414

**Comment by erictune** [comment]
@chuckbutler 
I'm looking at https://github.com/whitmo/charm-kubernetes/blob/master/files/kubelet.upstart.tmpl and https://github.com/whitmo/charm-kubernetes/blob/master/files/proxy.upstart.tmpl

The flags you are using are out of date with respect to Kubernetes head, but they are acceptable with respect to v0.8.2, which you are packaging with it.
