### ISSUE TITLE
Is there a way to understand which containers "talk" to a service?

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#4335]
There might be several containers that talk to other containers through a service, and while it is possible to calculate via selector/labels the relationship between service to pod and its containers, it is not clear how can the users/consumers of a service be linked to it ? 
It is clear that some of the service callers are not part of the same kube deployment, but how can someone understand the relationships inside the same kube deployment?

in this diagram, I am interested in calculating the link between A to B:
A. containers ---> B. service ---> C. pod

**Comment by bgrant0607** [comment]
Please comment on #1768.

**Comment by roberthbailey** [comment]
Redirecting you to #1768.

**Comment by abonas** [comment]
@bgrant0607, @roberthbailey  I read #1768 but I don't understand why am I redirected there.
I'm not asking about creating or declaring a dependency.
I'm asking about the current design - is there a way to understand if a container/pod talks to a port that is declared by a service in a system? For instance, a user would like to "draw" or understand a multi layer application architecture, and as such to see which components are connected to each other.

**Comment by thockin** [comment]
The short answer is no - there is no place in the API where a pod
purposefully "imports" or "links to" a service.  #1768 is the discussion
about such a feature, which is not universally desired.
