### ISSUE TITLE
kubectl: should you be able to specify a file with -f for more commands?

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#4343]
The core set  of the kubectl commands (create, update, rollingupdate, and delete) allow you to use `-f <file>` to specify which resource you want to operate on. This is fantastic. So fantastic that when I run the other commands that don't support the -f flag I wish I could use it.

The most obvious one of these that I hit today was the stop command. Sure, it's just a composition of resize and delete, but if I can use -f for delete, why not for stop?

Since I've spent most of my time just using the basic CRUD commands I've gotten very used to specifying which resource I'm operating on using -f. I find it simpler than having to type in the resource type, realize I don't remember the resource ID, look it up from the file, and then copy it into the command. Even for things like get and describe I'd actually find it useful to use -f, so that all I have to change in my bash command after I've created or updated something is the kubectl verb.

cc @jlowdermilk

**Comment by jlowdermilk** [comment]
I don't know about adding -f for get/describe, but for stop I agree.

**Comment by bgrant0607** [comment]
Yes, the goal is to support this for all commands.

**Comment by piosz** [comment]
I think it was fixed in #4492

**Comment by bgrant0607** [comment]
Yep.
