### ISSUE TITLE
go-restful is emitting less helpful errors than resthandler

### ISSUE THREAD

**Issue by liggitt** [GoogleCloudPlatform/kubernetes#4347]
If go-restful detects a particular method is not allowed, it will return this error:
```
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8

405: Method Not Allowed
```

That is preventing useful methods that resthandler would generate from making it to the client. Expected response:
```
HTTP/1.1 405 Method Not Allowed
Content-Type: application/json

{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta3",
  "status": "Failure",
  "message": "update is not supported on resources of kind event",
  "reason": "InternalError",
  "details": {
    "kind": "event"
  },
  "code": 405
}
```

**Comment by liggitt** [comment]
triggered with `curl -X PUT $HOST/api/v1beta3/events/foo`

**Comment by derekwaynecarr** [comment]
Is the right fix to update the client to generate the message versus changing the server to allow the method and report the error?  My bias is to improve the client and not change the server as it makes reading our swagger doc easier to not see a bunch of verb unsupported entries.

**Comment by nikhiljindal** [comment]
My bias is also towards not changing the server to keep swagger spec
correct.

By changing the client, do you mean changing kubectl?

@Jordan: can you please clarify how is the json useful to client? It does
not contain any useful extra information.

**Comment by liggitt** [comment]
Returning an API response would allow clients that expect API status to get nice messages for free, instead of spitting this out:
```
F0212 13:00:35.181692    4547 update.go:94] request [&{Method:PUT URL:https://10.13.129.209:8443/api/v1beta3/events/foo Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:{Reader:} ContentLength:264 TransferEncoding:[] Close:false Host:10.13.129.209:8443 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (405) 405 Method Not Allowed: 405: Method Not Allowed
```

We can certainly put the burden of interpreting 405 errors on all clients, just seemed nice not to.

Also, since the resthandler code expected to be returning API status responses when the method wasn't supported, I wanted to make sure having go-restful intercept and return 405's instead wasn't left as an unintended and unconsidered side-effect.

**Comment by derekwaynecarr** [comment]
This was an unintended side effect, but I think the old behavior was an unexpected luxury?

I agree from the end-user perspective, the old message was nice, and it's great that the client was politely told that a given verb was not supported on the resource, but I don't agree that a server should appear to accept a method to only report that its not allowed.

----- Original Message -----

**Comment by liggitt** [comment]
If we want to leave go-restful returning that as an intended and considered side-effect, that's fine. Is the consensus that this issue should change to update kubectl to show a nicer message for that error?

**Comment by derekwaynecarr** [comment]
I think so, this is only going to get worse when we support specific types of verbs on specific resources.  In practice, it seems fine for kubectl to give a better error specific to the method not allowed response.

----- Original Message -----

**Comment by bgrant0607** [comment]
We could consider submitting a PR to go-restful to allow us to provide an error-generation function or interface implementation.

**Comment by smarterclayton** [comment]
Yeah, that seems reasonable.

**Comment by liggitt** [comment]
Opened https://github.com/emicklei/go-restful/pull/181

**Comment by bgrant0607** [comment]
Copying text from #5491:

Some errors return as json and some as plain text.

This causes overhead on client side when parsing the errors since need to recheck content type for every error in order not to parse plain text as json (some libraries fail on that).
The errors message format should be standardized.

Examples:
```
404: Page Not Found
Content-Type: text/plain; charset=utf-8

405 Method Not Allowed
Content-Type: text/plain

409 Conflict
Content-Type: application/json

500 Internal Server Error
Content-Type: application/json
```

The text/plain errors are from go-restful.

cc @abonas @simon3z

**Comment by liggitt** [comment]
+1, thanks

**Comment by bgrant0607** [comment]
The status objects are always of the default API version, however, rather than the version requested, because the request object isn't available to the error handler.

**Comment by bgrant0607** [comment]
Rather than:
```
c.serviceErrorHandleFunc(ser, resp)
```
we need:
```
c.serviceErrorHandleFunc(ser, req, resp)
```

**Comment by smarterclayton** [comment]
Can we define an error handler on a web service?

**Comment by bgrant0607** [comment]
At the moment, it's at the container level:
https://github.com/emicklei/go-restful/blob/master/container.go#L58

**Comment by smarterclayton** [comment]
David and I talked about keeping the API lookup mechanism so we could use that in the error handler (apirequestinfo).  We still need it for some use cases (proxies) so it could be used here to identify the version and proposed resource if matched.
