### ISSUE TITLE
kube-addons may run before salt finishes writing templates

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4357]
I thought I had worked this out during development, but from an IRC report from @chromakode off a 0.10 GKE cluster, SkyDNS isn't starting. A bit of log trawling:

```
== Kubernetes addon manager started at 2015-02-11T21:19:44+0000 ==
++ addon /etc/kubernetes/addons/dns/skydns-rc.yaml started in pid 6208 ++
++ addon /etc/kubernetes/addons/dns/skydns-svc.yaml started in pid 6209 ++
F0211 21:19:44.321986    6208 create.go:51] unexpected end of JSON input
++ pid 6208 complete ++
skydns
++ pid 6209 complete ++
== Kubernetes addon manager completed with errors at 2015-02-11T21:19:44+0000 ==
```

Maybe I closed #3323 too early?

**Comment by zmerlynn** [comment]
@chromakode's gist with additional info: https://gist.github.com/chromakode/5896de3fde0ea5362be0

**Comment by zmerlynn** [comment]
(FWIW, this came up the next time, and we test this setup all the time using "Services should provide DNS for the cluster" https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/service.go#L41) but even if this is a low grade flake, I take a bit of a personal affront.)

**Comment by chromakode** [comment]
The cluster where SkyDNS didn't come up was created via the console at https://console.developers.google.com/project/weeby-challenge/kubernetes/add. It was a cluster size of 2 on us-central1-b.
