### ISSUE TITLE
Multi-cluster setup in tension with fordwarding rules

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4365]
I have one cluster called `kubernetes` where I create a cluster which will create Kubernetes services like `elasticsearhc-logging` and `kibana-logging` with forwarding rules of the same name. Now I create another cluster `k20` in the same project but it also creates services for `elasticsearhc-logging` and `kibana-logging` and forwarding rules (in the same project) of the same name (as before). Is this not a problem now? Surely the generated forwarding rules need to be distinct e.g. by qualifying by the cluster prefix? @jlowdermilk

**Comment by roberthbailey** [comment]
I recall this being a known issue, but I'm failing to find the github location where this is documented...

**Comment by jlowdermilk** [comment]
In order to have 2 working clusters in the same gce project, you either need to manually specify distinct MINION_IP_RANGES, or else put them in different networks. This is the workaround that allows a kubernetes and e2e cluster to coexist within one project (kubernetes cluster runs on 'default' network, e2e cluster on 'e2e' network). If the clusters are in different networks they can have identically named firewall rules. This is not a great solution as there is a lower cap on #networks a gce project can have.

cc @cjcullen

**Comment by jlowdermilk** [comment]
That wasn't really an answer. In answer form:

Yes, if the forwarding rules need to be distinct if the clusters are in the same network. However, putting 2 clusters in the same network breaks anyway, unless you manually assign distinct MINION_IP_RANGES for them.

That being said, it's probably still worth qualifying forwarding rules with the cluster prefix if it's not too hard.

**Comment by satnam6502** [comment]
Well then we should document "only instantiate one Kubernetes cluster in
one GCE project" or do special things yourself at your own risk. Or make
these special things easier to do and supported (and then things like e2e
can benefit from them).

For me, it's annoying not being able to run multiple clusters in one
project. I have one specific project with large negotiated quota and it is
the only project I can use to test large clusters -- and it can be helpful
to have -- say -- 2 x 100 node clusters in the same GCE project.

Satnam

**Comment by jlowdermilk** [comment]
I agree. It's an issue we solved for GKE, but we should make it easier on GCE, even if just for dev purposes.

**Comment by satnam6502** [comment]
Using a separate network for each cluster might be the least worst of all
the evils.

S

**Comment by roberthbailey** [comment]
It's certainly the least work, as you can see from how little had to change to get the e2e cluster isolated.

**Comment by roberthbailey** [comment]
@satnam6502 Is this covered by #4430?

**Comment by satnam6502** [comment]
Yes.
