### ISSUE TITLE
kubectl run should support run-once commands

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#4366]
When I run the simplest form of `run-container`:

```
$ kubectl run-container vmarmol-secret vmarmol/secret:latest
```

I expected this to be a one-time pod (it is a command I was running to test HTTPS connections and exits quickly). However, in reality it created a replicaController pod. According to the examples in kubectl.sh:

```
    $ kubectl run-container nginx --image=dockerfile/nginx
    // Starts a single instance of nginx.

    $ kubectl run-container nginx --image=dockerfile/nginx --replicas=5
    // Starts a replicated instance of nginx.
```

I was expecting to need to use the `--replicas` flag in order to get that behavior. Is this intended? The implementation currently takes the default of `--replicas=1` which probably explains the behavior.

**Comment by brendandburns** [comment]
It is intentional.  Without a replication controller, a machine failure
would permanently kill the pod.  I believe the replication controller more
closely matches the user's expectations.  (And is consistent with the
--replicas=n behavior)

Brendan

**Comment by jlowdermilk** [comment]
IMO, that behavior is intentional and desired. `kubectl run-container` is supposed to provide a friendly default. Creating a pod that disappears if e.g., the node goes away, is not a friendly default.

I would be open to adding a flag to make run-container create a single-use pod though; `--no-restart` as a strawman.

**Comment by vmarmol** [comment]
Intended usecase SGTM. I will send a PR to specify a "single-replica instance" in the example.

+1 to a single-use pod. The intended usecase was that the single-use pod "finish" and I could use its output, in my case to verify the behavior. By default we'd restart pods that "finish" so this may not work as I expected anyways.

I'm fine with closing this issue or re-purposing it for the single-use usecase.

**Comment by bgrant0607** [comment]
Feel free to repurpose this issue.

When we add a controller for restart-on-failure pods #1624, run-container should create that controller as appropriate, as well.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
Job proposal is in progress #11746. However, we could go forward with this before that lands.
