### ISSUE TITLE
IPAddresses reported by the Cloud Providers are ignored

### ISSUE THREAD

**Issue by simon3z** [GoogleCloudPlatform/kubernetes#4384]
Currently nodecontroller uses the node name to check the health:

    // checkNodeReady checks raw node ready condition, without transition timestamp set.
    func (s *NodeController) checkNodeReady(node *api.Node) *api.NodeCondition {
            switch status, err := s.kubeletClient.HealthCheck(node.Name); {

is this by design? How many other parts of kubernetes are making this assumption?

This basically means that the nodes id can be only an hostname.

What is the purpose of IPAddresses implemented by the Cloud Providers?

Thanks.

**Comment by smarterclayton** [comment]
In the long run, I would assume node names would ideally be a bit more stable than hostname - maybe we should add an optional spec field to Node which is a string or set of strings representing the address it's reachable on.  Or maybe we should just add Node health checks (liveness probes) like Pods do, and force the code to do that probe.

**Comment by simon3z** [comment]
+1 for reporting a set of strings representing the addresses

**Comment by ddysher** [comment]
The IPAddress right now is used to set Pod.HostIP.  (Feel like this is the only usage for now).  

+1 for a set of addresses.  Also see #4324, which points out we need clarify different IPs.

**Comment by justinsb** [comment]
This is indeed problematic: the e2e tests match pods by name (e.g. instanceprefix-minion-1...), but those names aren't resolvable on EC2 (where only ip-nnn-nnn-nnn-nnn works).  So the minion health checks fail.

I think we definitely need the internal IP (for the health check).  I'm pretty sure we also need the external IP: both for the e2e tests, and also because GCE uses the external IP.  The Name is also currently checked by the e2e tests, but only GCE enforces a uniqueness constraint on these names, so this feels a little risky.  Finally, it would also be handy to track the cloud-provider unique id (e.g. the EC2 instance ID).

One option that might work until we can fix the data model would be to change the health check to ask the cloud provider for the correct hostname/IP to use; I'll probably do this just so I can make progress on AWS.

**Comment by bgrant0607** [comment]
I agree that it makes sense to use Node.HostIP for the node controller to contact Kubelet.

With respect to #4324: We can add fields to v1beta1/2, and we can fix the field in v1beta3, in the internal representation, and in the internal cloudprovider interface.  A list of structs containing address and addressKind ("internal" or "external") SGTM. That would allow for multiple of each (e.g., v4 and v6), and even for new kinds in the future.

**Comment by ddysher** [comment]
Node.HostIP on gce is external IP right now.  I'd like to defer the change to health check a little bit.  It might increase latency and request count.

I'll start a PR to fix our ip data model.  Hopefully start on tmr if things work well with my project at work.

Related issues #4324, #2462, #3985

**Comment by simon3z** [comment]
@smarterclayton  @bgrant0607 using ip addresses to contact kubelet instead of the hostname could be problematic for the certificate validation? (which specifies the hostname)

**Comment by smarterclayton** [comment]
Fair point - communication to the kubelet from the master should be able to respect properly signed certs.  Ultimately it may be that the masters need to know what cert to validate the kubelets with, but that wouldn't be configured on the node unless we wanted that to be end user configurable.

----- Original Message -----

**Comment by bgrant0607** [comment]
More weight behind #156.

**Comment by justinsb** [comment]
@ddysher did you start a PR?  This is blocking me now, so I'd love to figure out what's happening and help if I can.

**Comment by ddysher** [comment]
@justinsb I've started a PR #4434.  I'll speed up the process.

**Comment by bgrant0607** [comment]
Kubelet will contact the master rather than vice versa.

**Comment by brendandburns** [comment]
#4434 is merged so I'm closing this.

**Comment by anguslees** [comment]
Note #4434 is not sufficient to address this issue.  The internal and external addresses are now being collected from the cloud provider (yay) ... and _then_ being ignored (afaics).  As the code currently stands, nodes names are still required to be resolvable hostnames.

**Comment by ddysher** [comment]
Mark dup of #4384

**Comment by ddysher** [comment]
Mark dup of #2462

**Comment by smarterclayton** [comment]
@liggitt this is relevant for the kubelet security story you've been working on.

----- Original Message -----
