### ISSUE TITLE
Write an e2e test that specifically tests kubectl functionality

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#4389]
As #3130 nears completion, we want to make sure that kubectl coverage isn't lost by moving to go tests.

**Comment by zmerlynn** [comment]
This is probably a P1 after all the shell tests are ported.

**Comment by zmerlynn** [comment]
@jlowdermilk and I talked about this for a little while, and would like the kubectl e2e to be:
* We test `kubectl` with two existing shell tests, and keep those in the tree. If we have to, we can just collapse them into one shell test.
* #3693 becomes: `guestbook.sh` becomes a real test
* #3694 becomes: Clean up `update.sh`
* We ensure that the shell tests have everything covered once. (@jlowdermilk mentioned that `kubectl log` isn't covered by either right now, for instance.)

**Comment by zmerlynn** [comment]
cc @filbranden @roberthbailey, because I'm sure there will be opinions here.

**Comment by roberthbailey** [comment]
Can we at least consider replace the shell parts of these tests with a Go driver that exec's kubectl instead?

I think keeping them as separate tests makes sense, as update.sh can be specifically targeted to test the kubectl rollingupdate command and we want finer grained tests.

**Comment by zmerlynn** [comment]
We talked about using Go for exec, and it wasn't clear there was a huge
benefit. I think the biggest benefit is that in Go, you also have access to
a real client, so you could perform more rigorous checks easily than you
could in bash (or rather, more easily do these checks).

I'm not against that path, thought, certainly.

**Comment by roberthbailey** [comment]
@satnam6502 found when he converted some of the shell tests to Go that the shell tests were not doing a good job of rigorously checking return values and cleaning up properly. I think it will be much easier for us to verify these properties if the driver is written in Go and it will also be nice to have a single language for all of the tests (and will likely be better encouragement for people to keep the kubectl tests up to date). Just my 2cc.

**Comment by satnam6502** [comment]
Let me add my two pence to Robby's two cents.

**Comment by jlowdermilk** [comment]
We now have `test/e2e/kubectl.go` which inherited the update test. Once the guestbook test is ported in as well (#5045) we can close this.

**Comment by jlowdermilk** [comment]
Closed by #5439
