### ISSUE TITLE
Automagic kubectl config merging causes hair loss

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#4397]
I've been pulling my hair out trying get kubectl talk to my local cluster.
It seems that kubectl merges the local `.kubeconfig` file with values pulled down from the cloud.

I've done the following:
```
export KUBERNETES_PROVIDER=local
kubectl=_output/local/bin/darwin/amd64/kubectl
$kubectl --kubeconfig=.kubeconfig config use-context local
# Cat local file and see that the change had effect
$kubectl --kubeconfig=.kubeconfig config view | grep current-context
current-context: e2e-test-etune
```
The `current-context` I just set is silently overridden.

Questions:
  - is this documented anywhere?
  - should kubectl merge in my GCE cluster when I set my cloud-provider to something else?
  - should kubectl override my previously set current-context?

**Comment by erictune** [comment]
workaround is to use `--context=` flag to override the config file value.

**Comment by erictune** [comment]
but not a goot UX long term

**Comment by erictune** [comment]
@jlowdermilk

**Comment by jlowdermilk** [comment]
Someone else hit this as well: #4310. Better fix is to have the local-up script set a context, which I will try to add today. As for the overwriting behavior, it's documented in [docs/kubeconfig-file.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubeconfig-file.md), but based on what you describe, the intended load order is not working; local .kubeconfig should overwrite global. cc @deads2k

**Comment by deads2k** [comment]
That sounds infuriating.  I'll take a look this morning.
