### ISSUE TITLE
Introduce container runtime abstraction

### ISSUE THREAD

**Issue by yifan-gu** [GoogleCloudPlatform/kubernetes#4404]
In order to support other container runtime implementations like Rocket, we need to introduce a layer of abstraction for ```ContainerRuntime```.

Currently we have the ```DockerInterface``` as an abstraction for the Docker runtime. But the input/output parameters are very Docker specific. 

IMO, we can refactor the ```DockerInterface``` to change its input/output, making them docker-unrelated. And then based on this, we can have the ```ContainerRuntimeInterface```.

(For example. 
``` go
ListContainers(options docker.ListContainersOptions) ([]docker.APIContainers, error)
```
takes a docker.ListContainersOptions, but can be easily replaced with a boolean. )

I am currently working on integrating Rocket into k8s (#2725), so I'd like to hear your opinions and advices on this.

Thank you!

**Comment by thockin** [comment]
SGTM

**Comment by bgrant0607** [comment]
SGTM, too.

We should also discuss API changes necessary to accommodate multiple container formats. We're about to finalize v1beta3.

**Comment by yifan-gu** [comment]
@bgrant0607 So I just added a container runtime interface in kubelet/container. By now it is same to DockerInterface. I think we can inspect each of the them to design the API we need.

**Comment by pires** [comment]
Looking forward for this one, since as an user I'm getting really sick & tired about [Dockers direction](https://github.com/docker/docker/pull/10776#issuecomment-74346219).

**Comment by bgrant0607** [comment]
@pires I appreciate the support, but please keep the discussion technical.

**Comment by yifan-gu** [comment]
cc/@dchen1107

**Comment by smarterclayton** [comment]
One issue that needs to be discussed is how image references are used throughout our API objects.  Right now `Image` is a string, and is opaque to all callers.  We also assume there is only one container runtime in operation.  For backwards compatibility we must assume that a valid Docker pull client pull spec in that field corresponds to the Docker type.  Rocket is currently using URLs with a runtime scheme in a few places in the ACI spec (docker:, ...).  

* Is multiple active runtimes a likely configuration in the near term (<6 months)?  I think not.
* Code that looks at the current Image value needs to treat it as an opaque value (the :latest PullAlways behavior needs to be nuked anyway) for forward safety
* The more specific an image reference is, the better (automated systems will prefer absolute / exact specifiers, and deployments / rolling updates depend on that predictability).  
* We need to decide whether this is a structured ObjectReference (Kind: "DockerImage"...), a URL, or a new reference type (ImageReference).  
* Other data about images will eventually be useful to know by the scheduler if placement decisions must be made - the runtime type (docker/aci), arch (Windows / Linux32 / Linux64 / z-p mainframe).  That data ideally would be in the Pod definition, but requires specificity of image reference.

**Comment by vmarmol** [comment]
Closing this as the runtime has been introduced and is used by rkt. Some of the open questions (like image format) have other open issues.
