### ISSUE TITLE
Liveness probes busted

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4406]
`Pods should be restarted with a /healthz http liveness probe (Failed 5 times in the last 9 runs. Stability: 44 %)`
`Pods should be restarted with a docker exec "cat /tmp/health" liveness probe (Failed 3 times in the last 9 runs. Stability: 66 %)`

This test was ported in #4280. However, as much as I wanted to blame that hunk of code (because the stability of `TestLivenessExec` and `TestLivenessHttp` were pretty strong), even after reverting #4280, I still liveness probes busted.

As best I can tell, these went unstable sometime around `v0.10.0-419-g7d43971` (this is the `git describe` in the build for `job/kubernetes-e2e-gce/2158/ ` on our jenkins server, and before #4280 went in). Unfortunately, because it's a flake, though a really solid one, it could also be `v0.10.0-409-g371349f`. Seems likely that it was somewhere in that vicinity, though.

cc @brendandburns 

This is basically P0, because it wrecks our CI.

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by brendandburns** [comment]
I noticed that in at least one of the failed runs, we tried to join the
network container of the pod that we had just killed.  There's something
weird going on, as we shouldn't even be killing the network container in
the first place.  I'm going to dig in a little more on this...

(And yes, the readiness refactor is a potential cause, will dig more...)

**Comment by smarterclayton** [comment]
Also be aware of #4462 which can lead to instability due to read races in the Kubelet, even if #4410 was the proximate cause.

**Comment by zmerlynn** [comment]
Actually, there's something fishy here .. it's possibly the Go test (but it has nothing to do with @rrati's port). I just noticed we still have `liveness.sh` in the tree, and it's doing fine: `Shell tests that liveness.sh passes (Failed 1 times in the last 100 runs. Stability: 99 %)`

**Comment by mbforbes** [comment]
I believe this is resolved.
