### ISSUE TITLE
Successfully ran containers restarting after purging oldest containers

### ISSUE THREAD

**Issue by nelcy** [GoogleCloudPlatform/kubernetes#4413]
Successfully ran containers with "onFailure" restartPolicy are restarting after purging oldest docker containers.

Kubelet purges/removes oldest containers periodically from docker.  After purging, we loose the exit code and history of previously ran containers and restart containers as if they were never run.

**Comment by nelcy** [comment]
Thanks @dchen1107 & @vmarmol.

I can help fix this. Let me know. Thanks

**Comment by vmarmol** [comment]
Thanks for reporting @nelcy! Just to make sure I understand the issue:

You ran some containers with an "onFailure" restartPolicy. When the Kubelet purged old containers the container was restarted (unexpectedly).

**Comment by vmarmol** [comment]
Ah, after reading again I think the issue is that after the containers are purged, when the container exits successfully it get restarted although it shouldn't. Is that correct?

**Comment by vmarmol** [comment]
After reading through the code I found a bug in the implementation that is most likely causing this error. Should have a PR soon.

**Comment by nelcy** [comment]
Yes. Correct. After initial container run, it should never be run again, since it already ran to completion.
Will wait for your PR.

**Comment by vmarmol** [comment]
@nelcy PR #4433 is out. This should fix the issue. Feel free to test if you can :)
