### ISSUE TITLE
0.10.1 and a lot of pods in Unknown state

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#4415]
One of my best test-cases for each Kubernetes release is to assemble and query an [Elasticsearch cluster](https://github.com/pires/kubernetes-elasticsearch-cluster). Right now, with ```0.10.1``` I see a lot of pods in ```Unknown``` state but assigned to minions. Curiously enough, I ssh into minions and look for Docker logs and I see some containers that ran once but shouldn't have run in the first place, since kube API states that it was assigned to a different host.

With ```0.9.2``` it works flawlessly. Can't try with ```0.9.3``` because the [binaries weren't released](https://github.com/GoogleCloudPlatform/kubernetes/issues/4277).

**Comment by brendandburns** [comment]
Will dig into this and try to repro.  0.10.1 passes our e2e tests...
Though we have found and fixed some bugs in pod status recently.

If you want the 0.9.3 binaries, I can def. push them today, let me know.

Brendan

**Comment by pires** [comment]
@brendanburns just for the sake of testing with 0.9.3 and limit the changelog window for future debugging, yeah do it, please.

**Comment by brendandburns** [comment]
v0.9.3 is pushed to the usual locations.

**Comment by pires** [comment]
Thanks. Will try and let you know.

**Comment by pires** [comment]
0.9.3 works as well.

**Comment by pires** [comment]
Once again, tried 0.10.1 and the issue is present.

**Comment by brendandburns** [comment]
If I send you a release tarball at head, can you test that?

Brendan

**Comment by pires** [comment]
I could build my own but for the sake of Friday laziness, please do.

On Fri, Feb 13, 2015 at 9:46 PM, Brendan Burns <notifications@github.com>
wrote:

> If I send you a release tarball at head, can you test that?
>
> Brendan
> On Feb 13, 2015 1:19 PM, "Paulo Pires" <notifications@github.com> wrote:
>
> > Once again, tried 0.10.1 and the issue is present.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/issues/4415#issuecomment-74328668
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/4415#issuecomment-74332463>
> .
>



-- 
Paulo Pires

**Comment by brendandburns** [comment]
http://storage.googleapis.com/kubernetes-release/ci/v0.10.0-506-gb23230e/kubernetes.tar.gz

**Comment by pires** [comment]
With this build the error doesn't show up *but* now I have no env vars in my containers. I'm probably needing some sleep and am messing up... but all I did was to recreate the cluster with the provided binaries.

**Comment by pires** [comment]
```
core@master ~ $ /opt/bin/kube-apiserver --version
Kubernetes v0.10.0-506-gb23230e616ac56-dirty
core@master ~ $ /opt/bin/kube-controller-manager --version
Kubernetes v0.10.0-506-gb23230e616ac56-dirty
core@master ~ $ /opt/bin/kube-scheduler --version
Kubernetes v0.10.0-506-gb23230e616ac56-dirty
```

```
core@node-02 ~ $ /opt/bin/kube-proxy --version
Kubernetes v0.10.0-506-gb23230e616ac56-dirty
core@node-02 ~ $ /opt/bin/kubelet --version
Kubernetes v0.10.0-506-gb23230e616ac56-dirty
```

**Comment by pires** [comment]
Related to #4462?

**Comment by dchen1107** [comment]
I think my PR #4376 should fix most of Unknown state here unless the node status is unreachable.

**Comment by roberthbailey** [comment]
@pires  Is there anything left here or can I mark this as closed?

**Comment by pires** [comment]
Works with 0.11.0.
