### ISSUE TITLE
Allow cluster resources to be subdivided

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#442]
Currently Kubernetes supports a single global scope for all resources.  This works well for single/small deployments where a small group of admins are coordinating changes.  There are two other important use cases that we would like to solve with Kubernetes:

* Use case 1 - Tenant visibility: Allow multiple administrative teams to subdivide the resources in the infrastructure for separate applications with visibility isolation to prevent conflicts between distinct uses (service names are unique only within a tenant, tenant 1 cannot see the resources of tenant 2)
* Use case 2 - Quota: Allow infrastructure to be finely divided among many users, with upper limits on the resources / locations / capabilities they can consume - allow resources to fungibly be divided between small and large teams with hard and soft limits.
* Use case 3 - Exclusion: Prevent resources from one tenant from being collocated with the resources (pods, services, traffic) of another tenant.  A less common scenario.

At best, the two additional use cases would not complicate the simple scenario (an administrator can start a cluster without having to configure subdivision).  In addition, a consumer of the pod/controller/service APIs should be agnostic to the subdivision.

Assumptions about subdivision:

* Most infrastructure use cases involve one to several related groups of containers/services performing a set of related functions (one, two, or many related "applications")
* As with most development, the natural unit of coordination on infrastructure is a team - a set of people who have similar roles and are working on related functionality
* While coordination across teams is not unusual, the relationships between these teams and functions is likely more formal - perhaps a versioned API, or a schema in a shared resource 
* This is modeled in many IaaS and related software as a "project" (or a "tenant") - a group of physical or virtual resources that are managed by a set of human or machine actors with predefined roles (which limit the actions those people/machines may perform), typically devoted to a common goal or set of goals
* There usually exists an owning relationship to an account/organization that pays/allocates physical resources - an owning entity may have multiple projects, may choose to assign individuals specific roles across those projects, and usually has an elevated level of privilege to those projects that users within the project cannot access (typically the right to set/alter limits on usage)
* It's rarely necessary to nest projects, which is typically done for further subdividing resources - instead, being able to easily assign groups of users (a "team") into roles on that project means projects can easily be split.   
 * There is still value in being able to categorize / organize large numbers of projects, which concepts like labeling can have value 
* As the number of managed resources grows, it becomes valuable to offer individual users the ability to query the resources they have access to across projects.  The base design should allow these broader scopes to be introduced at a later point. 

Straw-man proposal:

* Define a **project** resource (arbitrarily chosen name) which is the sole unit of access control and subdivision of pods, controllers, services, and other infrastructure resources
 * Limits and constraints on the number, size, and placement options available to pods are managed at the project level
* Allow the Kubernetes API concepts to work scoped to a project
 * In the default case, it should be easy for a solo admin to ignore the existence of the project resource - perhaps through a default singleton project with no imposed limits
* Limits and constraints must be available to be imposed when a pod is scheduled - the relationship between the scheduled pod, the containing project, and the acting user needs better definition, but either the storage or the scheduler interface (or both) must have the ability to influence / reject placement.
* Scope and define the following concepts in Kubernetes (#443):
 * **identity** - a way of tracking the actors of the API
 * **authentication** - how the identity of an actor is determined and checked
 * **authorization** - which actions an identity can take in which context

Thoughts?

**Comment by bgrant0607** [comment]
@smarterclayton @derekwaynecarr @erictune What else needs to be done on this issue? Do we have an overview doc that describes this area?

**Comment by smarterclayton** [comment]
Other than the individual efforts for authz, authn, and identity which continue elsewhere, the primary objective of this issue is satisfied.  I'd be ok with closing and letting those issues stand on their own
