### ISSUE TITLE
Sync status of replication controller via api server

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#4429]
As part of #2726, everytime we create or delete a pod in the replication controller we should sync with the api server. Currently the api server recomputes this information, ideally it should just read and serve from memory.

@smarterclayton @bgrant0607

**Comment by bgrant0607** [comment]
Depends on #4248.

**Comment by bgrant0607** [comment]
Even more motivation to do this: The etcd watch code is wrong. I missed it when I updated GET:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/etcd/etcd.go#L362

**Comment by smarterclayton** [comment]
Was this closed by a fix?

**Comment by bprashanth** [comment]
yeah https://github.com/GoogleCloudPlatform/kubernetes/pull/4751
