### ISSUE TITLE
Forwarding rules for services need to be qualified within project

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4430]
Now that I am working on an end to end test for cluster level logging we can easily get into the situation where there is a `elasticsearch-logging` service (and forwarding rule) for a regular user cluster *and* then one also is (attempted to be) created for the e2e cluster. Since the names are the sames this then causes a breakage and users end up taking to the wrong cluster. We need to agree on a way to name forwarding rules etc. to permit more than one cluster in a GCE project that allows services of the same name in both clusters.

**Comment by satnam6502** [comment]
I propose that I change the API server to use `INSTANCE_PREFIX` to qualify the name of the generated forwarding rule for the GCE platfrom.

**Comment by thockin** [comment]
Maybe pass it in to API server as --cluster-name or something?  Also
consider s/INSTANCE_PREFIX/CLUSTER_NAME/g

**Comment by zmerlynn** [comment]
Yeah, can we please start standardizing on something akin to "cluster name"
rather than "instance prefix"?

**Comment by thockin** [comment]
Also #2292

**Comment by satnam6502** [comment]
One of the PRs I am working on for end to end testing for cluster logging adds a `--cluster_name` flag to the apiserver.

**Comment by roberthbailey** [comment]
This looks finished. @satnam6502 please reopen if there is still more to do.

**Comment by satnam6502** [comment]
Ah, yes, indeed, finished, and does not seem to have broken anything.
