### ISSUE TITLE
Add confirmation for bulk delete operations in kubectl

### ISSUE THREAD

**Issue by mfojtik** [GoogleCloudPlatform/kubernetes#4457]
Right now, if I do:

```
$ kubectl delete pods # without identifier
```

the kubectl will remove all pods, without confirmation. I can imagine situations where this might be potentially dangerous. The kubectl should warn you when you are going to execute operations like this and there should be `--force` option to bypass the confirmation.

@smarterclayton fyi^

**Comment by soltysh** [comment]
:+1: Generally I think it make sense to ask user for confirmation (either interactively or using some sort of flag) when doing sensitive operations such as delete.

**Comment by sdminonne** [comment]
@mfojtik is going to be fixed once https://github.com/GoogleCloudPlatform/kubernetes/pull/4381 will be integrated

**Comment by smarterclayton** [comment]
There's a --dry-run proposal somewhere.  Delete is a very low level command, like 'rm'.

----- Original Message -----

**Comment by bgrant0607** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli-roadmap.md

**Comment by goltermann** [comment]
We think this is fixed via #4381, can you confirm, then close?

**Comment by smarterclayton** [comment]
This is fixed.

**Comment by chicagobuss** [comment]
It'd be nice if you were deleting a whole namespace at a time if it gave you a list of what it was about to delete before doing so - ala `terraform apply`

**Comment by Vickey-Wu** [comment]
Yes! It's really dangerous, though `kubectl delete` is a low level command, but it is a big disaster once you execute and delete resources in production environment. So, strongly recommend add an option `-i : prompt before every removal` for `kuberctl delete`
