### ISSUE TITLE
Kubelet is not synchronizing access to the "pods" member, which is bad

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#4462]
The member `pods` on the kubelet needs to be synchronized, because server.go can access it from other threads and there is no memory barrier in place.  Probably manifests as unrecreatable problems in production.

"pods" needs to be behind an accessor that guarantees thread safety, and the sync loop should be the only writer.

**Comment by brendandburns** [comment]
This was fixed by #4494
