### ISSUE TITLE
Remove cmd from kubectl/cmd/factory arguments

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#4470]
@jlowdermilk I think the need for this argument to the factory methods has passed - it means that callers who want to provide configurable behavior have to do it through the factory itself, which is acceptable.  

We can remove it whenever.

**Comment by TamerTas** [comment]
I removed most of the unused arguments. But, There are a few methods still using the `cmd` argument. Namely, `factory.Validator`, `PrintObject`, `PrinterForMapping` and `ClientMapperForCommand`. Before proceeding any further I wanted to ask what should be done about these methods? Deprecated/Refactored/Removed ?

**Comment by smarterclayton** [comment]
The factory methods were the most important. The pattern before was people using the flags by name (cmd.Flags().Get("foo")), but now factory methods must use pointer flag vars, so there's nothing that should need the command there.

The printer methods are optional units that can be used when you add the flags for them to your command.  Unless we refactor the definition of those flags to use pointers and return a printer struct (something I had started a while back and never finished), it's not worth changing them right now.

The other consumer of factory is OpenShift - we wrap the factory to add our additional types (implementations of things like describers, action verbs, etc): https://github.com/openshift/origin/blob/master/pkg/cmd/util/clientcmd/factory.go - but we will pick up and remove use of cmd when we rebase.

**Comment by TamerTas** [comment]
I've cleaned the `factory.Validation` as well. Printer API still stands I might do that next.

**Comment by bgrant0607** [comment]
cc @krousey

**Comment by bgrant0607** [comment]
Looks like this was done by PR #6144
