### ISSUE TITLE
Integration test panics in dockertools.ParseDockerName

### ISSUE THREAD

**Issue by mikedanese** [GoogleCloudPlatform/kubernetes#4472]
I've seen various panics in integration tests over the past few days caused by `runtime error: index out of range` in  dockertools.ParseDockerName.
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/50980094
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/50971293
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/50903684

**Comment by mikedanese** [comment]
#4433 might be related

**Comment by dchen1107** [comment]
@xiang90 is actively looking at the issue too.

**Comment by dchen1107** [comment]
Just comfirmed that the issue is limited to integration tests only. Lower the priority to P1 too.
