### ISSUE TITLE
Unit test coverage report dashboard

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4510]
Right now, we execute unit tests in Travis with `-cover`, and you can see the results on each line:

```
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/api	19.821s	coverage: 41.7% of statements
```

but we don't have an easy place to go browse our code and figure out what's covered and what isn't. Is there some awesome way to do this? At the very least, can we get the actual line-by-line coverage results integrated into our CI build process so we can poke at these somehow?

**Comment by zmerlynn** [comment]
cc @roberthbailey

**Comment by ixdy** [comment]
I'm willing to take a look into this to at least see if something is possible.

**Comment by ixdy** [comment]
Looking into using Coveralls; there are a few other teams at Google already using this.
https://coveralls.io/r/Google
https://coveralls.io/r/GoogleCloudPlatform

Integration with Travis and Go are supported with the goveralls package: https://github.com/mattn/goveralls

**Comment by ixdy** [comment]
Unit test coverage can now be viewed at https://coveralls.io/r/GoogleCloudPlatform/kubernetes - both master push builds and PRs will be shown there; additionally, Coveralls will update the status and post comments on PRs with coverage stats. (If we find these too spammy, we can disable either or both.)

The top-level README.md also has a badge/link to the coverage dashbaord.
