### ISSUE TITLE
Can't create a cluster because kube-up fails with unhelpful error message

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4513]
I did a fresh build against HEAD and then ran `kube-up.sh` on GCE and got this unhelpful error message. 

```
$ cluster/kube-up.sh 
Starting cluster using provider: gce
... calling verify-prereqs
... calling kube-up
Project: kubernetes
Zone: us-central1-b
Creating gs://kubernetes-staging-b76e9
Creating gs://kubernetes-staging-b76e9/...
BadRequestException: 400 Invalid argument.
```

**Comment by satnam6502** [comment]
This is blocking me from working on e2e testing on GCE so I would appreciate whoever made recent changes to the cluster creation code dealing with this ASAP, thanks. I've just deleted all my GCE clusters  and I can't seem to make any more :-(

**Comment by satnam6502** [comment]
One theory: the new cluster creation code is not robust w.r.t. existing forwarding rules etc.

**Comment by jlowdermilk** [comment]
Just tried at head, and didn't see it. Are you still getting the error? It's possible it was a transient gcs problem.

**Comment by jlowdermilk** [comment]
Only other thing I can think of is if you had multiple kube-up scripts running at the same time (on the same project), they could race to create the bucket. If one creates the bucket just as another is checking for existence of said bucket, the second create attempt would fail. From the above paste the error looks to be coming from [`gsutil mb <bucket>`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L125).

**Comment by satnam6502** [comment]
Existing forwarding rule.

**Comment by satnam6502** [comment]
I tried to create a cluster in a different empty GCE project except for the forwarding rules that did not get deleted by kube-down.sh and got the same error. I then manually deleted the forwarding rules and then the cluster was created fine. The kube-up process is then -- perhaps -- thrown off by an existing forwarding rule(s) which then perhaps causes this error message? The rules I deleted manually were for elasticsearch-logging and kibana-logging.

Separately I am working on creating and destroying forwarding rules qualified by `INSTANCE_PREFIX` as part of the the fixit from last week to support e2e testing of cluster level logging.

In any case, kube-up should not be tripped up by such things and be robust about them or at least give a better error message.

**Comment by satnam6502** [comment]
Now I am not so sure this is due to forwarding rules. In the second project I did a `kube-down.sh` which deleted everything excerpt the forwarding rules. Then I did a `kube-up.sh` and that worked -- so the existing forwarding rules were not causing a problem. So perhaps this is due to something else e.g. gsutil command mentioned by @jlowdermilk 

Switching back to my original project I still get the same error.
```
$ cluster/kube-up.sh 
Starting cluster using provider: gce
... calling verify-prereqs
... calling kube-up
Project: kubernetes
Zone: us-central1-b
Creating gs://kubernetes-staging-b76e9
Creating gs://kubernetes-staging-b76e9/...
BadRequestException: 400 Invalid argument.
```

**Comment by satnam6502** [comment]
So it was the wrong project name. I do this all the time: I use the wrong project name and then get a strange error. We should check to make sure the project exists before attempting any operations.
