### ISSUE TITLE
Vagrant provider latest kube-up not working

### ISSUE THREAD

**Issue by uruddarraju** [GoogleCloudPlatform/kubernetes#4522]
Here are the logs:

Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
Validating minion-2
Validating minion-3
Validating minion-4
Validating minion-5
Validating minion-6
............
Waiting for each minion to be registered with cloud provider
cluster/../cluster/vagrant/util.sh: line 166: cluster/../cluster/vagrant/../../cluster/kubectl.sh --kubeconfig=/Users/uruddarraju/.kubernetes_vagrant_kubeconfig: No such file or directory

I see .kubernetes_vagrant_kubeconfig in my home directory, so that is not a problem here.

And also, I was able to run get minions and get the following output:

LM-SJN-00877661:kubernetes uruddarraju$ cluster/kubectl.sh get minions
current-context: "vagrant"
Running: cluster/../cluster/vagrant/../../_output/dockerized/bin/darwin/amd64/kubectl --kubeconfig=/Users/uruddarraju/.kubernetes_vagrant_kubeconfig get minions
NAME                LABELS              STATUS
10.245.1.3          <none>              Ready
10.245.1.4          <none>              Ready
10.245.1.5          <none>              Ready
10.245.1.6          <none>              Ready
10.245.1.7          <none>              Ready
10.245.1.8          <none>              Ready

I think this is caused by: https://github.com/GoogleCloudPlatform/kubernetes/commit/a0cb252d400ecca8168055754225256085fe2a1a

When I rolled back the line 166 change in vagrant/util.sh, all worked good.

**Comment by derekwaynecarr** [comment]
The file is auto generated. 

You should see it created during kube-up.  

https://github.com/GoogleCloudPlatform/kubernetes/pull/4468

**Comment by uruddarraju** [comment]
I get that. And I have that too. But I still get this.

**Comment by derekwaynecarr** [comment]
So the cluster comes up, just kube-up is blocked when it verifies the cluster returns back all the minions?  I am trying to see what is unique in your case, and why line: https://github.com/GoogleCloudPlatform/kubernetes/commit/a0cb252d400ecca8168055754225256085fe2a1a#diff-b19d3d93456020e2168c7f304f722969R166 is causing a problem...

I cant tell if the error in your case is that kubectl is not found, or if the kubeconfig file is not being found from that line.  The intent of that line is to do the exact thing that ```cluster/kubectl.sh get minions``` does and is working for you.

**Comment by uruddarraju** [comment]
I don't see this happening now. Will close this for now and will re-open if I see this again. Thanks for the support
