### ISSUE TITLE
"Events should be sent by kubelets" flaky

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4533]
We need to figure out if this is the test or the product: `Events should be sent by kubelets and the scheduler about pods scheduling and running (Failed 9 times in the last 100 runs. Stability: 91 %)`

**Comment by davidopp** [comment]
I believe this is referring to test/e2e/events.go

**Comment by fabioy** [comment]
There were two pull requests that should help with the flakiness issue:
#4631 Move the various "defer" calls before the creation in pods.go e2e test.
#4609 Clean up events.go test by removing HostPort

Closing issue.
