### ISSUE TITLE
`Pods should be updated` flaky

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4535]
`Pods should be updated (Failed 8 times in the last 100 runs. Stability: 92 %)`: Test or product?

Actually, this one's disturbing, since it looks new?

**Comment by davidopp** [comment]
This appears to be referring to test/e2e/pods.go

**Comment by davidopp** [comment]
Some possibly-related discussion on #4528

**Comment by davidopp** [comment]
This seems to have been fixed by #4587, as there are no recent failures. There are still a bunch of flaky e2e tests though, so that was not the only cause of flakiness. Re-open this issue if the problem recurs.

**Comment by davidopp** [comment]
This is actually still flaking.

**Comment by roberthbailey** [comment]
I looked at all of our jenkins projects and this test hasn't flaked any time recently (last 30 runs) on any of them. Marking as fixed.
