### ISSUE TITLE
update.sh is busted

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4537]
`Shell tests that update.sh passes (Failed 33 times in the last 100 runs. Stability: 67 %)`

See also #3694, #2580, though. I don't want to invest a ton of time here, but this is busted

**Comment by brendandburns** [comment]
Already fixed last night (unless we already broke it again...)

**Comment by zmerlynn** [comment]
It failed again in #2415 waiting for a replica to come up.

**Comment by a-robinson** [comment]
Closely tied to #3694

**Comment by roberthbailey** [comment]
update.sh currently uses host ports. If a previous test in the test suite uses the same host ports and doesn't clean up properly, then the pods started in update.sh will never get scheduled. There are a couple of PRs in flight to remove host ports in other tests (which may help the reliability of this test) and I'm going to see if we can also remove them here.

**Comment by brendandburns** [comment]
We should almost certainly be able to remove them, by using the proxy on
the apiserver instead.

Thanks!
--brendan

**Comment by roberthbailey** [comment]
Roger that. Will investigate in that direction first.

**Comment by roberthbailey** [comment]
Status update: 
 - update.sh has been removed
 - the kubectl suite of tests no longer uses any host ports (which should help scheduling) and instead uses a local proxy through the apiserver to reach the pods

I'll keep an eye on jenkins over the next couple of days to see what the flakiness of the go tests is before closing this issue.

**Comment by roberthbailey** [comment]
The kubectl tests seem to be a bit flaky. @jlowdermilk has opened #4996 to track fixing them and since this issue was about the shell test (which has been removed) I'm going to close it.
