### ISSUE TITLE
API (types.go) does not pass API documentation pre-commit hook

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#4542]
The pre-commit hook runs `hooks/description.sh` to test `pkg/api/v*/types.go`

If the following line exits with status zero for the files, the documentation is considered incomplete.
  `grep json: "${FILE}" | grep -v ,inline | grep -v -q description:`

The problem is that there are many lines in each types.go that violate this requirement (i.e., description is missing). We should either update the files or revise the pre-commit hook.

@bgrant0607, who added the hook.

**Comment by bgrant0607** [comment]
We should ensure the hook runs on travis, so that PRs that break it don't get merged.

**Comment by bgrant0607** [comment]
Note that v1beta3 doesn't yet have descriptions. There's an issue filed for that already.

**Comment by yujuhong** [comment]
@bgrant0607, yes, I noticed that v1beta3 wasn't checked by the hook.

Here is a list of *matches* in v1beta1 and v1beta2:
```
	Kind   PodConditionKind `json:"kind"`
	Status ConditionStatus  `json:"status"`
	Spec NamespaceSpec `json:"spec,omitempty"`
	Status NamespaceStatus `json:"status,omitempty"`
	Items []Namespace `json:"items"`
	Type LimitType `json:"type,omitempty"`
	Max ResourceList `json:"max,omitempty"`
	Min ResourceList `json:"min,omitempty"`
	Limits []LimitRangeItem `json:"limits"`
	Spec LimitRangeSpec `json:"spec,omitempty"`
	Items []LimitRange `json:"items"`
	Hard ResourceList `json:"hard,omitempty"`
	Hard ResourceList `json:"hard,omitempty"`
	Used ResourceList `json:"used,omitempty"`
	Spec ResourceQuotaSpec `json:"spec,omitempty"`
	Status ResourceQuotaStatus `json:"status,omitempty"`
	Status ResourceQuotaStatus `json:"status,omitempty"`
	Items []ResourceQuota `json:"items"`
```
+ @derekwaynecarr since he added most of them :)

**Comment by bgrant0607** [comment]
PodConditionKind and ConditionStatus are my fault, for not catching them in review. @mikedanese, could you please submit a PR to add descriptions to those fields?

**Comment by bgrant0607** [comment]
Hmm. Travis should be running the check:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/.travis.yml#L12

So, why isn't it causing build failures?

**Comment by yujuhong** [comment]
There seems to be a bug in `verify-description.sh`. It always returns 0.

**Comment by derekwaynecarr** [comment]
I will add descriptions tomorrow morning.  I agree it would be good to have a tool remind me to do this in the future :-)

**Comment by bgrant0607** [comment]
There is a presubmit hook and travis check, but at least the latter was broken.

**Comment by yujuhong** [comment]
The pre-commit hook works. That's how I discovered the issue :)

**Comment by bgrant0607** [comment]
@derekwaynecarr Everyone who touches the types.go files currently fails the presubmit hooks. Will you be able to add the descriptions on Friday?

**Comment by derekwaynecarr** [comment]
@bgrant0607 - doing this now

**Comment by bgrant0607** [comment]
Fixed.
