### ISSUE TITLE
Missing AWS getting started link?

### ISSUE THREAD

**Issue by benmccann** [GoogleCloudPlatform/kubernetes#4554]
Feel free to close if there's a reason this was done intentionally.

On the getting started page (http://kubernetes.io/gettingstarted/) there's links to all the guides, but [the AWS guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws.md) isn't listed.

**Comment by yujuhong** [comment]
I am not sure who maintains the page. Assigning to @brendandburns to triage.

**Comment by vmarmol** [comment]
I think it is an oversight since the webpage is on the harder side to fix. Assigning to myself and will send a PR to fix it. Thanks for reporting @benmccann!

**Comment by vmarmol** [comment]
I meant to send a PR, but I didn't do it correctly and just pushed directly :package: 

This is now fixed on the site.
