### ISSUE TITLE
unable to create resources in v0.10.1 with v1beta3 api

### ISSUE THREAD

**Issue by sym3tri** [GoogleCloudPlatform/kubernetes#4558]
I've been using the v1beta3 API. I just upgraded from Kubernetes v0.9.2 to v0.10.1 and can no longer create resources in the default namespace. Is this a bug or intentional design choice to now require a namespace?

This is what I'm seeing with v0.10.1:

```
POST /api/kubernetes/v1beta3/pods
405: Method Not Allowed
```

v0.10.1 v1beta3 swagger json (note lack of POST operation)
```json
{
  "path": "/api/v1beta3/pods",
  "description": "API at /api, version v1beta3",
  "operations": [
   {
    "type": "void",
    "method": "GET",
    "summary": "list objects of kind Pod",
    "nickname": "listPod",
    "parameters": [],
    "responseMessages": [
     {
      "code": 200,
      "message": "OK",
      "responseModel": "v1beta3.PodList"
     }
    ],
    "produces": [
     "application/json"
    ],
    "consumes": [
     "*/*"
    ]
   }
  ]
}
```

v0.9.2 v1beta3 swagger json
```json
 {
  "path": "/api/v1beta3/pods",
  "description": "API at /api, version v1beta3",
  "operations": [
   {
    "type": "void",
    "method": "POST",
    "summary": "create a Pod",
    "nickname": "createPod",
    "parameters": [
     {
      "type": "v1beta3.Pod",
      "paramType": "body",
      "name": "body",
      "description": "",
      "required": true,
      "allowMultiple": false
     },
     {
      "type": "v1beta3.Pod",
      "paramType": "body",
      "name": "body",
      "description": "",
      "required": true,
      "allowMultiple": false
     }
    ],
    "produces": [
     "application/json"
    ],
    "consumes": [
     "*/*"
    ]
   },
   {
    "type": "void",
    "method": "GET",
    "summary": "list objects of kind Pod",
    "nickname": "listPod",
    "parameters": [],
    "responseMessages": [
     {
      "code": 200,
      "message": "OK",
      "responseModel": "v1beta3.PodList"
     }
    ],
    "produces": [
     "application/json"
    ],
    "consumes": [
     "*/*"
    ]
   }
  ]
}
```

**Comment by derekwaynecarr** [comment]
V1Beta3 has different URL path structure.

Post /namespaces/default/pods

This is by design.

**Comment by derekwaynecarr** [comment]
If you look at the swagger output you can see the new path semantics and verb support

**Comment by sym3tri** [comment]
@derekwaynecarr Thanks for the feedback, that makes sense. I just wasn't sure if it was a bug or intentional. 

Follow up question:
So is the idea that the operation `GET /api/v1beta3/pods` will return all pods regardless of namespace?

**Comment by derekwaynecarr** [comment]
Correct.

Resources that are in a namespace to do creation, update, delete require namespace in path.

Getting all of a resource independent of namespace is just GET /resource, like GET /pods.

Note Namespace is an actual object, but mandating its creation before sticking content in it is not enforced in providers other than Vagrant.  I would like to fix that soon.  In that mode GET /namespaces list all namespaces.  Get /namespaces/default returns the default namespace.  Etc.

**Comment by sym3tri** [comment]
@derekwaynecarr Thanks, that clears things up. Closing this issue since it's not a bug.
