### ISSUE TITLE
Kubelet to POST node status to apiserver

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#4562]
Split off #156 as a smaller more specific work item.

In the kubelet, once every N sync loops, it should POST `/api/$VERSION/nodes/$NAME/status`.  It would in particular set 
```
NodeStatus.Condition[
 {
  Kind: NodeReachable,
  LastProbeTime: $NOW
},
{
  Kind: NodeReady,
  LastProbeTime: $NOW
},
]
```

The kubelet would do this if enabled by a flag, and emit a warning if it failed to POST the update.

The kubelet would ideally handle a 429 by retrying after the Retry-after header

**Comment by dchen1107** [comment]
cc/ @ddysher

**Comment by ddysher** [comment]
Apart from NodeCondition, node status also includes node IPs (currently HostIP, but we need to support more) and node phase.  Who will be responsible to update these status?  I'd like to have a single component does all the status update.

Another issue is what happens during startup or adding new node.  Node controller will register all nodes on startup and create new node.  It's possible that kubelet trying to post status to a node that is not known to the master.  Should we allow auto-registration, or retry on 404?

I can start with making node controller more configurable to ease the function shift.

**Comment by fgrzadkowski** [comment]
This seems like a nice, self-contained task. If nobody is working on changing kubelet I'm happy to work on this.

**Comment by erictune** [comment]
fine with me.

**Comment by dchen1107** [comment]
@fgrzadkowski Do you mind to take a look at #4561, and let @dysher take this one since he is working on node controller / nodeStatus / nodeCondition?

**Comment by fgrzadkowski** [comment]
I've already spent quite some time on reading/understanding the code, but it's probably not a wasted time anyway :) I'll look at #4561

**Comment by timothysc** [comment]
Do you plan on modifying the NodeController polling loop then?

**Comment by ddysher** [comment]
@jszczepkowski is working on that. #4808

Both node controller polling loop and kubelet POST will be disabled before integration.

**Comment by zmerlynn** [comment]
Will the NodeController need the static list of nodes configured by salt after this change? I have a change that I'm about to land that makes the GCE config for that a lot more static (I'm turning salt standalone on GCE), but this looks like the missing link.

**Comment by lavalamp** [comment]
Wait why is kubelet posting the node status? What if kubelet goes down? Seems like something else should post the node status (node manager?)

**Comment by timothysc** [comment]
IMHO Status updates should have TTL set so etcd can self clean.

**Comment by fgrzadkowski** [comment]
@lavalamp What good is a node if kubelet is not running? Also node controller checked nodes by querying kubelet's /healthz.

@timothysc I don't think there should be any logic in etcd. IMO such cleanups should be done by an external controller such as node controller.

**Comment by ddysher** [comment]
@fgrzadkowski I think the change made there is to not have node controller query kubelet's /healthz.  But agreed etcd does not involve in the logic, something else needs to do the cleanup.

**Comment by lavalamp** [comment]
@fgrzadkowski if kubelet is not running, it cannot phone home to tell apiserver it is not running. Therefore, something other than kubelet must report node status.

**Comment by lavalamp** [comment]
Actually scratch that...

I just chatted with @erictune and the request here is that kubelet phones home with statuses, and node controller checks the timestamp of the last phone-home and sets it to unreachable if it's been too long; the goal being that nothing has to be a client of kubelet (desirable for reasons). So my apologies for not understanding what was being asked here.

**Comment by erictune** [comment]
We don't have NodeUnreachable NodeConditionType, but we could add that and do as lavalamp says.

**Comment by ddysher** [comment]
This is done.  See other issues for remaining items: #6077 #6073 #6072 #5953

**Comment by zmerlynn** [comment]
So just so it's not dropped on the table, which work item eventually drives a stake in `--machines` in the [Salt configuration](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kube-controller-manager/default)? I rather drastically limited broke dynamic clustering with the standalone Salt changes by [making the node names fixed at initialization](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L598), but thought the #156 umbrella, and in particular #4561 + #4562 was going to cover this.

**Comment by bgrant0607** [comment]
@zmerlynn Self-registration was covered by #2435 and #2303, which were both closed. #3168 was cited as related, but I don't think it fully covers the issue.

**Comment by roberthbailey** [comment]
@bgrant0607 Max and I agreed that self registration wasn't obviously covered by #3168 and we created #6087 today, which may be what you are looking for.
