### ISSUE TITLE
Apiserver to support disabling pod status probes

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#4564]
Split off #156 as a smaller more specific work item.

Apiserver should have a flag that makes it not attempt to GET `/podInfo` from kubelets.  
This would be used in conjunction with #4561.

After we have converted the top N Getting-started-guides to the new style, we can rip out the kubelet client from the apiserver altogether.

**Comment by fgrzadkowski** [comment]
This is tightly related to #4561 so I'll take it.
