### ISSUE TITLE
Many flaky tests caused by blocking on large image pulls

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#4566]
Docker v1 daemon serializes pull requests per https://github.com/docker/docker/issues/150
"v1 (which is what is used when you pull coderpad/coderpad) doesn't [support parallel pulls], and is unlikely to feature parallelism (the way it is designed prevents it)"

That causes many of our tests that include timeouts to fail when a test with a small timeout and a small image is blocked on a pull by a large image.  E.g., on cluster setup, we run a pod for elasticsearch-logging.  If a small image, e.g. serve_hostname gets scheduled 2nd, it won't pull until the elasticsearch-logging image finishes, which can take minutes on GCE.  Of course, once the big image finishes the pull, the 2nd smaller image runs quite quickly.

% kubectl get pods
POD                                                IP                  CONTAINER(S)            IMAGE(S)                           HOST                                                                        LABELS                       STATUS
elasticsearch-logging-controller-gziey             10.245.1.6          elasticsearch-logging   dockerfile/elasticsearch           e2e-test-mohr-minion-1tmg.c.mohr-instance-manager.internal/130.211.163.89   name=elasticsearch-logging   Pending
send-events-00814060-b7c1-11e4-b03c-10604b6be770   10.245.1.10         p                       kubernetes/serve_hostname          e2e-test-mohr-minion-1tmg.c.mohr-instance-manager.internal/130.211.163.89   name=foo,time=299941735      Pending

We should consider one or more of the following:
- to test actual functionality and exclude the variability of pull times, pre-pull all images as part of test infrastructure creation
- before starting a test, list pods and don't start until any pods are in Pending.
- use Really Big Timeouts on all tests.
- figure out why pulls of large images are slow.

Brendan had a CL with a list of images and an idea of how to pre-pull them, so passing to him for now.

**Comment by zmerlynn** [comment]
One of the ways we talked about doing this was adding a script/utility/something that still goes through the product that get all the pulls done, then getting that done before ginkgo-e2e.sh runs, but after cluster turn-up. It becomes then more a matter of up-or-down infrastructure rather than a test.

It's important that it still goes through the product, though - something that results in pulls across all nodes - so that we're at least vaguely making sure the later e2es are at all testing a later cluster state that was achieved using the product, versus a synthetic state.

**Comment by alex-mohr** [comment]
FWIW, I think it's important that *a* test go through the usual docker pull -- a test specifically for that -- but all the others can use injected images if that's more reliable.

**Comment by mbforbes** [comment]
Just my two cents: I think that this point you mentioned,

> - before starting a test, list pods and don't start until any pods are in Pending.

with `s/util/while/`, is the correct way to fix the tests; pre-pulls and faster pulls will then be optimizations that will speed up the tests. The correctness of a test shouldn't depend on the quickness of a pull, I think.

I'll be doing this in #4501, so if that sounds good then we can assign this to me, then create separate issues for the other items?

**Comment by brendandburns** [comment]
@mbforbes the problem with this, is then you end up with tests that may never complete, we need some sort of timeout to catch this.

**Comment by mbforbes** [comment]
Good point; I'll make sure there's a timeout for this check.

**Comment by jlowdermilk** [comment]
#5106 standardized the pod start timeout to 5 minutes, which mostly solves timeouts from slow image pulls. I'm going to propose we close this and push on making the e2e tests use gcr.io (#5007) as a better long-term solution.

**Comment by zmerlynn** [comment]
Closed via #5135
