### ISSUE TITLE
Add PATCH verb to apiserver resources

### ISSUE THREAD

**Issue by mikedanese** [GoogleCloudPlatform/kubernetes#4578]
Currently kubectl has logic to apply partial updates to resources. This responsibility logically seems like it should belong to the CRUD rest server. More concretely, if this responsibility is moved into the apiserver, it would allow clients that use the api directly to benefit from this feature. An obvious interface would be to follow [RFC7368](https://tools.ietf.org/html/rfc7386) and implement resources that respond to requests with HTTP `PATCH` method and `Content-Type: application/merge-patch+json`.

**Comment by bgrant0607** [comment]
Totally agree in principle. Need to look at the RFC.

See also #2726, #3112, #1459.

cc @smarterclayton

**Comment by ghodss** [comment]
One note is that the only way this works in apiserver is first converting the server-side object to JSON, applying the JSON patch, and then converting the object back to the native API type. In other words, you can't convert the patch to a versioned API Go object first and then try to do the merge that way. If you try, you lose two important pieces of information: you lose fields that are omitted and fields that are null, both of which have implications in patching the object. As per [RFC7368](https://tools.ietf.org/html/rfc7386), omitted fields should be ignored and null fields should be explicitly deleted (and thus reverted back to defaults).

Fortunately merging patch JSON into object JSON is already implemented in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/merge/merge.go, although I wonder if this code could be replaced with https://github.com/evanphx/json-patch.

**Comment by mikedanese** [comment]
@ghodss I agree with the path of the api conversion, we would need to follow the same path as we currently do in kubectl. Do you see any benefit of moving to evanphx/json-path? Is RFC6092 something we want to support or will RFC7368 be enough? I have not stumbled upon evanphz/json-path before and I'm willing to consider pulling it in but I do like how MergePatch currently fits in less than 20 lines of code.

I'm planning to give this some time this weekend.

**Comment by ghodss** [comment]
My only thought would be if there's better test coverage in evanphx/json-path or if we get benefits from having less code in util, but if we think neither of those are true in any significant way, we can totally skip it.

**Comment by mikedanese** [comment]
I think that [RFC6092](https://tools.ietf.org/html/rfc6902) might actually be useful to solve #4561 and #4562 without creating separate endpoints in apiserver. Not sure if RFC7368 would sufficiently cover those use cases.

**Comment by smarterclayton** [comment]
The primary reason for a separate status endpoint is access control.  I'm still a little uncomfortable with per field access, but at least with patch the intent is explicit.

**Comment by ghodss** [comment]
Another reason for evanphx/json-path is that I will probably need the [CreateMergePatch](https://github.com/evanphx/json-patch/blob/master/merge.go#L150) function in config reconciliation to update server resources (#1702).

**Comment by mikedanese** [comment]
I particularly like RFC6902 for expressing intent. A patch to update NodeStatus would look like:
```json
{ "op": "replace", "path": "/status", "value": {"conditions":[{"status":"Full","kind":"Ready"}]} }
```
Where the intent is explicit in the op and path.

It would also be reasonable to move status into a separate endpoint as they have a separate "lifecycle" from the resource they are associated with. I would also think that status would move to a separate key/value in etcd if we were to move status into a new endpoint.

@ghodss I'm convinced. I also like evanphx/json-path a bit more. I have a branch that removes pkg/util/merge and another that is a continuation of #4706 that implements both RFC7368 and RFC6902 PATCH in the apiserver.

**Comment by smarterclayton** [comment]
----- Original Message -----
> I particularly like RFC6902 for expressing intent. A patch to update
> NodeStatus would look like:
> ```json
> { "op": "replace", "path": "/status", "value":
> {"conditions":[{"status":"Full","kind":"Ready"}]} }
> ```
> Where the intent is explicit in the op and path.
> 
> It would also be reasonable to move status into a separate endpoint as they
> have a separate "lifecycle" from the resource they are associated with. I
> would also think that status would move to a separate key/value in etcd if
> we were to move status into a new endpoint.

It doesn't have to - in fact we know want to mutate status and annotations at the same time.  Also, we want people to be able to watch pods.  We can talk about this more when we talk about status but there are advantages to having one stored object and two virtual objects pointing to it.

**Comment by bgrant0607** [comment]
I agree we should think about splitting spec and status in etcd. I commented on #2726. I agree that simultaneous annotation updates are an issue. If we had true multi-object transactions, we could implement each object as 3 records: metadata (would need to factor out resourceVersion), spec, status.

**Comment by smarterclayton** [comment]
I'm pretty sure most people who want to watch etcd objects want to see updates on status and spec.  I think there is definitely the potential for user intent changes to get lost in the much larger history of status changes... but I don't see how separating them makes the outcome better for most naive cases.
