### ISSUE TITLE
Pods constantly pending

### ISSUE THREAD

**Issue by rajitha-wijayaratne** [GoogleCloudPlatform/kubernetes#4582]
Hello,

I have installed the latest kubernetes binaries on CoreOS running on GCE.  The cloud-config is as per instructions on "getting started guides".

After I installed 3 Pods, the state on all were constantly "pending".  I looked around but none of the previous solutions worked.  

After messing around a lot for 3 days it turned out to be the following line. I had 3 in pending status now one Pod is "successful" the others are "running".

Change the config for docker daemon from

ExecStart=/usr/bin/docker -d -s=overlay -H fd:// --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}

To

ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}

**Comment by brendandburns** [comment]
Usually this means that you have a scheduling conflict.  What does

```kubectl get events```

print?

My guess is that you have ```hostPort``` set on your pods, and you have more replicas than you have machines, and so some pods can not schedule due to hostPort conflicts.

**Comment by rajitha-wijayaratne** [comment]
The event dump as follows.  

FIRSTSEEN                         LASTSEEN                          COUNT               NAME                KIND                SUBOBJECT           REASON              SOURCE              MESSAGE
Wed, 18 Feb 2015 13:29:28 +0000   Wed, 18 Feb 2015 13:29:28 +0000   1                   log-collector       Pod                                     scheduled           {scheduler }        Successfully assigned log-collector to 127.0.0.1
Wed, 18 Feb 2015 14:09:17 +0000   Wed, 18 Feb 2015 14:09:17 +0000   1                   log-publisher       Pod                                     scheduled           {scheduler }        Successfully assigned log-publisher to 127.0.0.1
Wed, 18 Feb 2015 14:12:34 +0000   Wed, 18 Feb 2015 14:12:34 +0000   1                   tree1-server        Pod                                     scheduled           {scheduler }        Successfully assigned tree1-server to 127.0.0.1

I have the entire cluster in a stand alone machine.  The cloud-config is this one .https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/standalone.yaml

One of the Pod specification is here.  The others a similar to this.  I haven't set hostPort anywhere. 

{
  "id": "log-collector",
  "kind": "Pod",
  "apiVersion": "v1beta2",
  "desiredState": {
    "manifest": {
      "version": "v1beta2",
      "containers": [
        {
          "name": "fluentd-es",
          "image": "kubernetes/fluentd-elasticsearch",
          "volumeMounts": [
            {
              "name": "common-log-collector-storage",
              "mountPath": "/var/lib/docker/containers",
              "readOnly": false
            }
          ],
          "labels": [
            {
              "name": "fluentd-es",
              "selectorname": "fluentd-es"
            }
          ]
        }
      ],
      "restartPolicy": {
        "onFailure": {}
      },
      "volumes": [
        {
          "name": "common-log-collector-storage",
          "source": {
            "hostDir": {
              "path": "/var/lib/docker/containers"
            }
          }
        }
      ]
    }
  },
  "labels": {
    "name": "log-collector",
    "environment": "testing"
  }
}

**Comment by satnam6502** [comment]
So it looks like you are trying to get node level logging up using Flunetd -> Elasticsearch? Let me know if there is something I can do to help. satnam@google.com

**Comment by rajitha-wijayaratne** [comment]
satnam,

I will contact you if I have any questions with Flunetd -> Elasticsearch.  

Much appreciated.

**Comment by pires** [comment]
The CoreOS instructions are borked for 0.10.x or 0.11.x. Will PR changes today.

**Comment by pires** [comment]
Actually, @rajitha-wijayaratne changed the layer driver from ```overlay``` to ```btrfs``` which means he's using an older version of CoreOS. I can't reproduce this behavior with CoreOS 593/598 and Kubernetes 0.9.3, 0.10.1 or 0.11.0.

**Comment by rajitha-wijayaratne** [comment]
I am using coreos-beta-584-0-0-v20150218 .

Perhaps a warning should go on getting-started-guides to say it only applies to CoreOS after 593.0.0/598.0.0.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/standalone.yaml
