### ISSUE TITLE
Scheduler should report why scheduling failed. (aka "why pending?")

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#4583]
Currently we report that we couldn't find a fit for the pod, but we don't determine which predicate failed.  This makes end-user debugging harder than it needs to be.  We should figure out why things don't fit.

**Comment by pires** [comment]
+1

**Comment by mml** [comment]
I see #4765 added logging info.  Is there any useful way to access this info programmatically?  E.g., "why is pod foo pending right now?"
