### ISSUE TITLE
Repo renamed to kubernetes_copy

### ISSUE THREAD

**Issue by sunyal** [GoogleCloudPlatform/kubernetes#4593]
Is there a reason that the project was renamed to kubernetes_copy?

**Comment by gmarek** [comment]
Nope, my mistake

**Comment by thockin** [comment]
to reduce this sort of error I have a git alias for push which is "po" -
push origin.  That way I never accidentally type "push upstream"

**Comment by bgrant0607** [comment]
I have never typed "push upstream". The set of people who need to do that is small.
