### ISSUE TITLE
http://kubernetes.io/ responds with 404

### ISSUE THREAD

**Issue by sunyal** [GoogleCloudPlatform/kubernetes#4594]
The website no longer works and responds with 404.  Could this be related to the kubernetes_copy repo name change?

**Comment by vmarmol** [comment]
This is most likely due to the rename. Our domain forwarding records are
broken.

**Comment by gmarek** [comment]
Sorry for that. I did that by mistake when trying to merge my accounts.

**Comment by sunyal** [comment]
I am still receiving the 404 response code for http://kubernetes.io  Is this going to take time to propagate out?

**Comment by vmarmol** [comment]
Looks like http://googlecloudplatform.github.io/kubernetes is also down.
Let me try to do a push.

**Comment by vmarmol** [comment]
Looks like the gh_pages branch was deleted by whatever change was done :-\

**Comment by vmarmol** [comment]
Forced a push, site is back. Thanks for reporting!

**Comment by sunyal** [comment]
Great!  Thanks.
