### ISSUE TITLE
Instrument Kubelet for monitoring

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#4604]
There are a few areas of the Kubelet that we should instrument to allow us to monitor them for v1. This will also be very useful to measure and meet our scalability goals.

* Pod startup latency histogram (from sync to running)
* Run container histogram
* Image pull histogram
* Current tasks counter
* Restarts per task counter

We should use Prometheus metrics as the master has started to use them too (see @a-robinson's PRs in that area).

**Comment by dchen1107** [comment]
Also see #1625 for more discussion

**Comment by vmarmol** [comment]
We'll use this issue for the node components of that umbrella issue.

**Comment by pires** [comment]
+1

**Comment by vmarmol** [comment]
After the slew of PRs, this should be complete. The Kubelet now exports a /metrics endpoint with a slew of metrics tracking the timing of certain operations and the counds of pods, containers, and containers per pod.
