### ISSUE TITLE
Vagrant provider kubectl proxy service returning 404

### ISSUE THREAD

**Issue by uruddarraju** [GoogleCloudPlatform/kubernetes#4607]
I have been following the instructions here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/ui.md to try to explore the kube UI.

by executing: 
```cluster/kubectl.sh proxy -www=$PWD/www```

I get the following which shows it successfully started:
```
current-context: "vagrant"
Running: cluster/../cluster/vagrant/../../_output/dockerized/bin/darwin/amd64/kubectl --kubeconfig=/Users/uruddarraju/.kubernetes_vagrant_kubeconfig proxy -www=/Users/uruddarraju/go/src/github.com/GoogleCloudPlatform/kubernetes/www
I0219 10:14:26.049033   21299 proxy.go:36] Starting to serve on localhost:8001
```

When I try to access the page ```http://localhost:8001/```

I get a 404: ```404 page not found```

**Comment by yujuhong** [comment]
@uruddarraju, could you try running `cluster/kubectl.sh proxy --www=$PWD/www`?

I believe `-www` is a typo of `--www`

**Comment by yujuhong** [comment]
Also, try accessing `http://localhost:8001/static` instead.

**Comment by uruddarraju** [comment]
thanks
