### ISSUE TITLE
Pod containers with no environment variables set

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#4614]
Possibly related to #4415 

Since 0.10.1 - and just confirmed with 0.11.0 - containers from pods do not have any Kubernetes related env vars set.
```
$ vagrant ssh node-01
CoreOS alpha (593.0.0)
Update Strategy: No Reboots
core@node-01 ~ $ docker ps
CONTAINER ID        IMAGE                        COMMAND                CREATED             STATUS              PORTS               NAMES
0522aeebbdda        pires/elasticsearch:master   "/usr/bin/runsvdir -   47 minutes ago      Up 47 minutes                           k8s_elasticsearch-master.6d831f7e_elasticsearch-master-fplln.default.etcd_f40cf7be-b848-11e4-895a-080027aeee49_a251d366
823d55b2770c        kubernetes/pause:go          "/pause"               58 minutes ago      Up 58 minutes                           k8s_POD.8f3eed67_elasticsearch-master-fplln.default.etcd_f40cf7be-b848-11e4-895a-080027aeee49_017ece96
core@node-01 ~ $ docker exec 0522aeebbdda env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=elasticsearch-master-fplln
HOME=/root
JAVA_HOME=/usr/lib/jvm/java-8-oracle
ES_PKG_NAME=elasticsearch-1.4.2
```

@sub-mod is facing the same issue and we both can confirm that 0.9.x works well.

**Comment by brendandburns** [comment]
Ok, we've had multiple reports of this.  I don't really understand what is going on, but clearly there is an issue.  I'm pretty positive that the problem is stemming from:

https://github.com/GoogleCloudPlatform/kubernetes/pull/4359

But I don't fully understand why.

I will dig in and see if we can figure it out, and possibly revert that PR if necessary.

Does this happen for all pods?  Or just some pods?

Thanks
--brendan

**Comment by brendandburns** [comment]
Also, can you check the kubelet log for errors?

Thanks
--brendan

**Comment by brendandburns** [comment]
Also, can you try hitting the DNS address for the service and see if it is there?

Thanks
--brendan

**Comment by brendandburns** [comment]
Ok, I think I see the problem.  I'm betting you don't have ```--api_servers``` set on your kubelet.

This used to be semi-optional and we deferred back to etcd, but now it is pretty much required in the kubernetes environment.

Can you try setting ```--api_servers=<ip>:<port>``` where <ip>:<port> is your master?

I bet that fixes it.

I'll do a PR to make that more obvious and scream more.

**Comment by sub-mod** [comment]
@brendanburns  It happens to all pods as of now.I have only tried guestbook + a simplecontroller+service example
no errors in kubelet log , bit it complains abt not finding apiserver
so may be u are correct , let me check

**Comment by thockin** [comment]
I turned up a cluster from head just now, and I can 'docker inspect' the
kube2sky container and see service env vars

**Comment by sub-mod** [comment]
--api_servers=<ip>:<port> 
solved the issue
Thanks @brendanburns  :)

**Comment by dchen1107** [comment]
@thockin what is your cloud provider? I think it hurts the clusters on non-gce provider.

cc/ @ArtfulCoder This might be the problem you hit to test etcd docker image on vagrant?

**Comment by pires** [comment]
Ah, so ```--etcd_servers=``` is gone from 0.10.x onwards, is it?

**Comment by brendandburns** [comment]
deprecated, but not removed, afaik.

(and yes, we should have probably just straight-up removed it)

--brendan

**Comment by pires** [comment]
OK, it works. Going to try it in my test-cluster as well and in case it works will update CoreOS related doc.

**Comment by timothysc** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/4643

**Comment by pires** [comment]
Works in my test-cluster. Will update CoreOS doc next and then close this.
