### ISSUE TITLE
Cluster services need a common label

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4620]
As per https://github.com/GoogleCloudPlatform/kubernetes/pull/4417#discussion_r24957829 we should add a common label to all of our add-on pods: DNS, logging, monitoring, etc.

The proposal is to add "kubernetes.io/cluster-service": "true" for now.

@vishh @satnam6502

**Comment by thockin** [comment]
FWIW "true" has to be quoted in YAML

**Comment by goltermann** [comment]
Can you close this one once it's completed.
