### ISSUE TITLE
Kubelet to fail pods that have hostPort conflicts, etc

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#4623]
Although the scheduler tries not to coschedule pods with hostPort conflicts, there could still be a conflict:
  1. once #4619 goes in, the kubelet could still maybe get pods with conflict. 
  1. file based pods could conflict with apiserver-based pods.

Right now, kubelet can detect a conflict, via the code in syncLoop, in pkg/kubelet/kubelet.go, where it calls filterHostPortConflicts().    However, two things need to change in that loop.

First, instead of just ignoring one of the two conflicting pods, the kubelet should immediately set the pod status to Failed with an event with a useful Reason.  It should do this even for pods which requested restarting.

Second, it should do this in a deterministic way.  Right now, it is based on the order of the items as they come out of the config code.  Maybe it should iterate through the pods by creation timestamp.

**Comment by erictune** [comment]
This would be a good project for someone who wants to get started in kubelet.

**Comment by erictune** [comment]
You could e2e test this as follows.  Create a pod in the API that requests the same hostPort as is already used by the file-based cadvisor container.  The pod should fail and there should be an appropriate reason.

**Comment by erictune** [comment]
@dchen1107 we just talked about this.

**Comment by erictune** [comment]
in future we might use this to fail due to out of resources, or other setup errors.

**Comment by thockin** [comment]
Might need some way to poison the node from future scheduling decisions - tricky.

**Comment by pmorie** [comment]
+1 to this, do want

**Comment by erictune** [comment]
@thockin 
there are two cases:
  1. two schedulers racing to start a pod on the same node
    - one pod will get the the node first, 
    - the second will be kicked off by the kubelet
    - the rc for the second pod makes a new pod
    - there should not be a race the second time because all the schedulers know about the first pod now.
  1. file pod versus apiserver pod on the same node.
    - once #4090 is fixed, this won't happen because the schedulers will see the file pod hostPorts.

**Comment by thockin** [comment]
Oh, I thought this was getting rid of HostPort conflict checking entirely?
Is that ALSO happening somewhere else?

**Comment by bgrant0607** [comment]
This is needed in order to eliminate BoundPods.

**Comment by yujuhong** [comment]
kubelet now sorts the pods before filtering, and also records an event on host port conflict. To actually *reject* such pods, we will need to kubelet to post pod status back to apiserver (#4561)

**Comment by erictune** [comment]
The scheduler still checks.  This handles parallel scheduler races and file
based pods.

**Comment by brendandburns** [comment]
There should be no parallel scheduler races, we use resource versions and
optimistic concurrency to ensure correctness.

Brendan

**Comment by bgrant0607** [comment]
Re. atomicity -- I don't buy that we need it. I commented here: https://github.com/GoogleCloudPlatform/kubernetes/issues/2483#issuecomment-76502738

**Comment by yujuhong** [comment]
@erictune, do you mean that we should still set the pod status to "failed" so that when the scheduler check, it can get the accurate pod status back? I had thought about it, but the pod statuses are computed on the fly (by checking the containers) as of now. Without the ability to directly set the status, we need to cache this information somewhere. Since there are people touching the same code/file, I'd rather wait until #4561 is fixed.

**Comment by erictune** [comment]
@brendandburns 
perhaps parallel was the wrong word, but a scheduler race appears possible.  the cache of pods it uses is not updated atomically with binding pods.  It appears the scheduler could:
  1. successfully do a /binding of pod A with hostPort N to host H
  1. read the cache and see A not bound
  1. consider binding B with hostPort N to host H, and not see a conflict.
  1. successfully do a /binding of pod B with hostPort N to host H
  1. later, the cache notices that A is bound to H

**Comment by yujuhong** [comment]
@erictune and I discussed offline, and we decided to create a map to store the rejected pod->status, so that the failed status will be correctly reports when polling happens. By doing this, this issue is no longer blocked by any other issues.

I will write up a PR to implement this.
