### ISSUE TITLE
vagrant ssh {master,minion-1} does not work

### ISSUE THREAD

**Issue by jameskyle** [GoogleCloudPlatform/kubernetes#4633]
The Vagrantfile requires that ENV['KUBE_TEMP'] is set. If it is not, any vagrant command will fail as the file cannot be parsed. The error received is:

    There are errors in the configuration of this machine. Please fix
    the following errors and try again:

    shell provisioner:
    * `path` for shell provisioner does not exist on the host system: /master-start.sh

This is contrary to the suggested method of interaction in the documentation found at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md which says:

    To access the master or any minion:

        vagrant ssh master
        vagrant ssh minion-1

**Comment by jameskyle** [comment]
Looking at the scripts, this temp directory is set on script run and cleaned up on EXIT by a trap.

I've wrapped a conditional around the provision statement which allows the other commands to work, but outputs a warning that the vm will not have a provisioner set.

Pull req incoming.

**Comment by derekwaynecarr** [comment]
Cc me on your PR and I will review.  I have been swamped on other topics so it's possible something regressed.
