### ISSUE TITLE
hack/test-cmd.sh doesn't work on clean client while working on Travis due to different environment

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#4661]
The test is currently broken (some of kubectl invocations are lacking "${kube_flags[@]}"). It should run as a part of PR presubmit. 
The test itself is being fixed as a part of #4267 .

**Comment by ixdy** [comment]
This should be as easy as adding a line to .travis.yml.

**Comment by wojtek-t** [comment]
I think that what @rsokolowski wanted is to run those tests when the PR is being merged, not when it is being submitted for the review since this doesn't guarantee that we won't break the tests while merging the PR.

**Comment by rsokolowski** [comment]
@wojtek-t, actually I just wanted to run the test as a part of PR submit as @ixdy mentioned.
@ixdy is the Travis environment different than just clean Kubernetes repository ? While running from command line the commands in the test needs to have "${kube_flags[@]}" arg (current code in head doesn't pass):
$ git clone https://github.com/GoogleCloudPlatform/kubernetes.git
$ cd kubernetes
$ make
$ hack/test-cmd.sh
...
+++ Testing kubectl(:pods)
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
redis-master
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
redis-master                            master              dockerfile/redis    <unassigned>        name=redis-master   Pending
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
redis-master                            master              dockerfile/redis    <unassigned>        name=redis-master   Pending
redis-master
redis-master
redis-master
No resources found
redis-master
F0223 16:31:54.792212   17585 delete.go:80] you must provide one or more resources by argument or filename
hack/test-cmd.sh: line 154: delete: command not found
redis-master
redis-master
F0223 16:31:55.797153   17649 get.go:166] pods "redis-master" not found
!!! Error in hack/test-cmd.sh:161
  'kubectl get pod --namespace=other redis-master' exited with status 255
Call stack:
  1: hack/test-cmd.sh:161 main(...)
Exiting with status 1
+++ Clean up complete

**Comment by zmerlynn** [comment]
Isn't this because it's just broken right now? I swear I just saw a PR on the naked `delete` command here:

```
  kubectl get pods "${kube_flags[@]}" -lname=redis-master | grep -q 'redis-master'
  [ ! $(delete pods --all pods -l name=redis-master "${kube_flags[@]}" ) ]   # not --all and label selector together
  kubectl delete --all pods "${kube_flags[@]}" # --all remove all the pods
```

**Comment by rsokolowski** [comment]
It isn't just this. For me it always breaks if kubectl is not invoked with "${kube_flags[@]}".

**Comment by rsokolowski** [comment]
It seems that @fgrzadkowski just encountered similar problem I had. The test wasn't working locally due to apparently different environment on Travis and on workstation.

**Comment by brendandburns** [comment]
@rsokolowski is this still relevant?

**Comment by brendandburns** [comment]
Closing this as obsolete.  @rsokolowski please re-open if this is still a problem.
