### ISSUE TITLE
Can we create a kubernetes cluster with different OS?

### ISSUE THREAD

**Issue by claire-w** [GoogleCloudPlatform/kubernetes#4666]
I would like to create a kubernetes cluster, with different OS on the manager and the minions. Is that possible?

**Comment by vmarmol** [comment]
Yes, this is very much possible. There is no strong dependency on the host image and we've seen setups with many different distros. (Assuming you mean OS == Linux distros :) )

If you run into any problems, feel free to file issues or ping us on IRC.

**Comment by claire-w** [comment]
thanks a lot, your quick answer has helped :-)

**Comment by vmarmol** [comment]
Great to hear! I'll close for now, feel free to open a new issue if you run into any problems.
