### ISSUE TITLE
Coveralls comments a little spammy

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#4671]
@ixdy, any idea why the triple spam in e.g. #4647?

**Comment by vmarmol** [comment]
I believe those were turned off because they were spammy. No idea why 3 though...

**Comment by ixdy** [comment]
There were two Travis builds for #4647, which resulted in two coverage reports:
https://coveralls.io/builds/1961512
https://coveralls.io/builds/1961527

I don't know why Coveralls commented twice for the second build; I'd expect either one comment per job, or one comment per build, but it seemed to do both.

In any case, these comments seemed a bit noisy, so I'm having it update the status checks only now. (The same place where Travis, the CLA bot, and Shippable update.)
