### ISSUE TITLE
Service deletion on GCE removes forwarding rules but not target pools

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4689]
When a service is deleted on the GCE provider any load balancers associated with it are also deleted i.e. the forwarding rules are removed. However, the target pools still linger. To cleanly delete a cluster on GCE the target pools should also be removed.

**Comment by a-robinson** [comment]
Do you have any logs from this happening? It looks like the code for bringing down a load balancer should be deleting the target pool as well:
https://github.com/GoogleCloudPlatform/kubernetes/blob/dff727c50b96034ce7acb3b40b53d8885836a456/pkg/cloudprovider/gce/gce.go#L263

**Comment by gmarek** [comment]
The problem here is that we do not wait for ForwardingRule to be deleted. GCE api calls return when Operation is "scheduled", e.g. pending. This causes delete of TargetPool to eventually fail with error RESOURCE_IN_USE_BY_ANOTHER_RESOURCE. I'll fix this first thing tomorrow.

**Comment by satnam6502** [comment]
@a-robinson : I've noticed because I am creating and destroying clusters back to back for e2e testing (for the cluster level logging test). These tests become sensitive to poor cleanup between phases. To make the cluster level logging test e2e robust as possible I am keen for us to properly clean up resources. I notice this informally when during the e2e cluster level logging test fails while running in the second cluster (and there might have been a few error messages during cluster creation).

@gmarek : thank you. Another thing to consider is to delete a target pool if it already exists (perhaps after checking to make sure it is not the target of any forwarding rules).

**Comment by roberthbailey** [comment]
A quick scan through the code also doesn't reveal any retries around the attempts to delete the load balancers or target pools. Each of these requests should be retried to survive a transient error in GCE during tear down.

**Comment by gmarek** [comment]
I believe PR #4770 solved this problem.
