### ISSUE TITLE
Kubectl fails cryptically when it can't update a key

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#4691]
If you hit a single etcd key repeatedly from multiple locations, some updates are bound to fail. When this happens, kubectl dies with something like:

```
 Running: cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl resize --replicas=1 rc my-nginx
 F0220 17:34:02.420311    4984 resize.go:66] replicationController "my-nginx" cannot be updated: 101: Compare failed ([188 != 189]) [189]
```
..which is kind of cryptic. I believe the `Compare` it's complaining about is etcd's CAS which happens via `client/replication_controller`. You can trigger this condition pretty easily be creating an rc, and running a while true loop from 2 shells to resize the rc.

**Comment by bgrant0607** [comment]
The error message is cryptic, which we should fix, but the real fix to this is to retry.

**Comment by bprashanth** [comment]
If I was writing an app external to kube that was polling rc count in this way (eg loadbalancer) I would find last write wins a little unexpected, but maybe I'm overthinking this.

**Comment by bprashanth** [comment]
Hrm, I guess no load balancer would shell out to kubectl

**Comment by bgrant0607** [comment]
Re. "last write wins": That's what the preconditions are for (look at resize flags).

**Comment by lavalamp** [comment]
kubectl itself should do the retry loop for this command, I think. Since you've just asked it to clobber whatever was in the replicas field.

**Comment by bgrant0607** [comment]
Sorry, yes, that's what I meant.

**Comment by bprashanth** [comment]
I'm taking this, it needs to happen before https://github.com/GoogleCloudPlatform/kubernetes/issues/4429

The plan is to implement a simple, synchronous, retry loop in kubectl that gets the object, verifies preconditions and tries the update.

**Comment by bprashanth** [comment]
This should be fixed
