### ISSUE TITLE
'make test' is really slow

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4713]
Our test-go.sh script invokes 'go test' serially for each pkg - currently taking 2 minutes on my laptop.  Running a single 'go test' for all pkgs cuts the time down to 45 seconds.  Even running with -race is only 1:15.

As far as I can tell, the only time we HAVE to run serially is when coverage is on.

Does anyone have time to fix this?

**Comment by ixdy** [comment]
I'd created #4686 on Friday to fix this, though it's not yet been reviewed.

**Comment by thockin** [comment]
I cobbled together #4717 but I'll review yours since it is probably better
:)
