### ISSUE TITLE
cannot link persistent disks

### ISSUE THREAD

**Issue by yawnt** [GoogleCloudPlatform/kubernetes#4720]
Hi,

i'm trying to deploy a Docker container on GKE which uses persistent disks, but I can't seem to get them to work. I tried with a minimal example and it failed, so I followed [this](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/README.md), with the exact same .yaml and I get the same error

```
Mon, 23 Feb 2015 09:21:42 +0000   mysql               BoundPod                                                failedSync          {kubelet k8s-demo-node-1.c.$PROJECT.internal}   Error syncing pod, skipping: invalid argument
```
Last friday it kept giving an error about failing to attach disks, but that doesn't seem to be the case anymore, maybe it was related with the Google Cloud outage

any ideas? Thank you very much

**Comment by roberthbailey** [comment]
What is your cluster version (run ```gcloud preview container clusters list``` and look at the ```clusterApiVersion``` for the cluster you are having trouble with)?

**Comment by yawnt** [comment]
sorry for the late reply, it looks like after the gcloud sdk update it works.. it now says started, although i still occasionally get 

```
Mon, 02 Mar 2015 18:20:54 +0000   mysql                                   BoundPod                                                failedSync          {kubelet k8s-demo2-node-1.c.trovamoda.internal}   Error syncing pod, skipping: Could not attach disk: Timeout after 10s
```
my cluster api version is 0.11.0 by the way

thanks!

**Comment by roberthbailey** [comment]
@cjcullen has been looking at PD support recently; maybe he has run across this error?

**Comment by cjcullen** [comment]
Kubernetes 0.11.0 had an issue (#3437) with detaching persistent disks, and with attaching PDs as read only. 0.12.0 should be getting cut soon, and it will be supported in GKE shortly after. Until then, you should be able to get things working by only mounting PDs as read-write, and manually detaching them when tearing down a pod.

**Comment by roberthbailey** [comment]
@yawnt have you had a chance to test this again with a 0.12.x cluster (0.12.2 is the latest)?

**Comment by yawnt** [comment]
Sorry, no I wasn't aware 0.12.x had been rolled out. I can't test right now but will in the future. If you prefer we can close this (given what @cjcullen said) and I can reopen in case I hit the same problem?

Thanks!

**Comment by roberthbailey** [comment]
I'm happy to leave it open for a while if you think you'll find time to test because we'd really like to know that PDs are working properly and we've fixed the bug you encountered. If you don't think you'll get to it any time soon then we can close this and see if anyone else reports a problem with PDs.

**Comment by yawnt** [comment]
Let's close it then, unfortunately the deploy was set back a bit to focus on ironing out some parts of the code, so that's where my focus will be. Thanks for your help anyway, I will make sure to report as soon as I get back to using GKE.

ps: something that would be really really nice would be heterogeneous cluster support ;P

**Comment by roberthbailey** [comment]
> ps: something that would be really really nice would be heterogeneous cluster support ;P

Definitely agree. :)
