### ISSUE TITLE
Incorrect grafana address printed by kube-up.sh

### ISSUE THREAD

**Issue by jszczepkowski** [GoogleCloudPlatform/kubernetes#4721]
After starting kubernetes cluster on GCE with ./kube-up.sh, I cannot connect to grafana dashboard.

**Comment by piosz** [comment]
It might be related to #4648

**Comment by vishh** [comment]
How are you trying to access the dashboard @jszczepkowski - via the proxy or using the nodeIP ?

**Comment by jszczepkowski** [comment]
I'm trying to access grafana via host ip of the node. This is the address written by kube-up.sh:
``Grafana dashboard will be available at http://XXX.''
Is there a proxy for grafana? AFAIK, we have services with forwarding rules only for elasticsearch and kibana.

**Comment by piosz** [comment]
We also tried to connect api proxy (http://localhost:8001/api/v1beta1/proxy/services/monitoring-grafana) and we also sth weird like "{{allert.title}}".

**Comment by brendandburns** [comment]
That looks like angular crashed part way through.  What does the javascript
console in your browser show?

Brendan

**Comment by piosz** [comment]
monitoring-grafana:8 GET http://localhost:8001/api/v1beta1/proxy/ns/default/services/monitoring-grafana/css/grafana.dark.min.21253ffa.css 
monitoring-grafana:11 GET http://localhost:8001/api/v1beta1/proxy/ns/default/services/monitoring-grafana/app/app.496fdc2e.js 
monitoring-grafana:13 Uncaught ReferenceError: require is not definedmonitoring-grafana:13 (anonymous function)
monitoring-grafana:19 GET http://localhost:8001/api/v1beta1/proxy/ns/default/services/monitoring-grafana/css/grafana.light.min.81a2958f.css

**Comment by piosz** [comment]
@vishh is it still possible to connect to grafa using nodeIP?

**Comment by vishh** [comment]
Yes. It should still be possible. The firewall rules are setup on GCE by
default to access Grafana. I assume you are running on GCE.

**Comment by vishh** [comment]
Can you check if firewall rules are setup to access Grafana?

**Comment by piosz** [comment]
I set up cluster using hack/dev-build-and-up.sh. In Google Developer Console under Compute->Network Load Balancing->Forwarding Rules I can see only the following entries:

elasticsearch-logging     us-central1     104.154.82.11     TCP/9200     elasticsearch-logging
kibana-logging      us-central1     104.154.82.224     TCP/5601     kibana-logging

**Comment by vishh** [comment]
Can you look at "Firewall rules"?

On Tue, Feb 24, 2015 at 10:20 AM, Piotr Szczesniak <notifications@github.com

**Comment by jszczepkowski** [comment]
OK. Seems that grafana is working fine, it is available at:
https://<masterIP>/api/v1beta1/proxy/services/monitoring-grafana/
Message printed by kube-up.sh is bit incorrect, I'll fix it.

**Comment by vishh** [comment]
Thanks for the fix @jszczepkowski. Closing this issue!
