### ISSUE TITLE
Add section on Constants to api-conventions.md

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#4723]
The api conventions document should provide guidance on values for constants and naming of `Kind`-like fields like [`PodPreconditionKind`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L506).

**Comment by bgrant0607** [comment]
Yes, apparently we didn't document the CamelCase rule.
