### ISSUE TITLE
RestartPolicyNever leaves infra pods running forever

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#4731]
Pods with RestartPolicyNever are leaving behind infra pods.  Those infra pods should be nuked as soon as the last successful run is completed.

For people with lots of successful / failed never pods this consumes IP addresses which is bad when IP addresses are in use.

I suspect this is because we don't have another marker that the pod has completed, but we probably need to get that fixed before 1.0.

**Comment by gmarek** [comment]
I can work on it, if no one is already.

**Comment by gmarek** [comment]
I will work on in later, as I don't want to duplicate the work @wojtek-t is doing while parallelizing kubelet. 

I thought about it, and I can't see any 'cheap' way of checking if infra container should be killed. Namely I believe that we have to check that nothing's running and nothing will be restarted, i.e.
for each container defined in pod.Spec there exist a "recent container" in Docker which succeeded (for OnFailure RestartPolicy) or died in any way (for Always RestartPolicy). 

I don't think there's any weaker condition that is sufficient and necessary, with most common corner case being an event in which Node goes crazy, and decided to kill everything running on it - such case has to be distinguished from starting a pod on a Node first time.

It's more or less what syncPods is doing right now, with the exception of applying the changes (starting/killing containers). Wojtek is already splitting this method into 'analysis' and 'application' parts, which will make change needed to fix this bug much simpler.

**Comment by brendandburns** [comment]
I think the right thing to do here is to kill the pause container, if nothing else is running and the pause pod is older than N minutes (where N is something long, like 10 minutes)

In the worst case (e.g. a really slow image pull(, we'll just re-create a pause container, when the pull completes and we try to start the other container.

**Comment by gmarek** [comment]
I think killing is easy, figuring out if it needs to be started is harder. The way I understand the flow, it starts in syncLoop, which calls GetBoundPods, getting all the pods bound to the given Kubelet, no matter the status. Afterwards SyncPods is called on them. In SyncPods we go through each pod, and add all of them to workers which in turn run syncPod in parallel.

The whole logic of figuring out what to start is in syncPod method, but first thing it does is checking if infra container is running and starting it if it's not. After this it goes through containers and checks if anything needs to be started. Which is exactly what I meant: we need to separate analysis and starting/stopping pods.

Am I missing something, like some earlier mechanism of checking if a pod requires attention at all? Or do you mean that we should keep a timestamp of last container event (start/failure/whatever) and kill the infra container iff nothing's running and last event occurred more than X minutes ago, as a proxy for 'everything's dead for good'?

**Comment by vmarmol** [comment]
@gmarek +1 to separating analysis from action in syncLoop(). You should also sync with @dchen1107 who is taking a look at #4787. I suspect changes for both of these issues are very related.

**Comment by smarterclayton** [comment]
One more related case - I was starting to look at graceful delete and the kubelet would need to know whether to restart based on the metadata persisted with the pod (a pod in graceful termination should not restart on exit).  So having separate analysis will be important there.

**Comment by gmarek** [comment]
I started working on a PR today, but I didn't manage to finish it. I got stuck under multiple different 'Container' structs and translating ones into others. 

@dchen1107 are you working on #4787 now? It'll be probably much easier with my change.

**Comment by gmarek** [comment]
I believe this was fixed by the PR #5094.

**Comment by vmarmol** [comment]
Closing as per @gmarek's PR. Thanks!
