### ISSUE TITLE
Reconsider the value of named container ports

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4737]
Allowing a service to target a port by name-or-number brings some complexity to a number of places in our codebase.  Is it worthwhile?  I am no longer convinced.  Discuss..

**Comment by bgrant0607** [comment]
More detail: IntOrString is used in Service.ContainerPort and in HTTPGetAction and TCPSocketAction.

I'm in favor of getting rid of IntOrString for Service.ContainerPort. 

It seems less of a problem for the hooks/probes, and would be more tedious to keep those port values in sync.

**Comment by thockin** [comment]
If we keep named ports at all it feels bad to not support them
consistently..

**Comment by bgrant0607** [comment]
Fair enough. At least all ports in a pod could be updated atomically.

We may want to keep port names for informational purposes if nothing else.

**Comment by bgrant0607** [comment]
I think we agreed to change the ones in containers to descriptions.

**Comment by thockin** [comment]
keeping
