### ISSUE TITLE
elasticsearch-logging-controller depends on dockerfile/elasticsearch[:latest]

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#4746]
The elasticsearch addon depends on dockerfile/elasticsearch.  That's :latest, and not a specific version, so an upstream push can break k8s logging.  It should instead depend on a known-good version that we know will work.
@satnam6502 perhaps?

**Comment by satnam6502** [comment]
Yes, I know, and it is on my plate to make a kubernetes/elasticsearch which has a well chosen base image, explicit image task etc. I hope to do this soon as part of the P1 fixit for Elasticsearch end to end testing. #3388 
I was thinking of filing this issue myself this morning :-)

**Comment by satnam6502** [comment]
Fixed.
