### ISSUE TITLE
Document process for upgrading a running cluster 

### ISSUE THREAD

**Issue by rjnagal** [GoogleCloudPlatform/kubernetes#4747]
I couldn't find one - feel free to close with a pointer.
Just saying we can't + a roadmap would be enough.

**Comment by pires** [comment]
+1

/cc @jasonkuhrt

**Comment by alex-mohr** [comment]
P2 -- blocked by P1s implementing upgrade.

**Comment by fgrzadkowski** [comment]
@alex-mohr do we still have some issues not resolved regarding cluster upgrade?

**Comment by alex-mohr** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/upgrade.sh has usage notes.  It's not the most discoverable of "docs" and we don't have an equivalent for other distros, but it's there.
