### ISSUE TITLE
Update node with --patch fails for api version v1beta1/v1beta2

### ISSUE THREAD

**Issue by pravisankar** [GoogleCloudPlatform/kubernetes#4752]
Node manifest:
{
"kind":"Minion",
"id":"10.245.1.3",
"apiVersion":"v1beta1",
"hostIP":"10.245.1.3",
"resources":{"capacity":{"cpu":1,"memory":3221225472}},
}

Tested on k8s vagrant environment (repo HEAD 74c0dd179e7c789bcf5cb2):
[kubernetes]$ cluster/kubectl.sh update nodes 10.245.1.3 --patch='{"apiVersion": "v1beta1"}'
F0223 16:12:38.180732   20375 update.go:123] error unmarshaling JSON: json: cannot unmarshal number 3.221225472e+09 into Go value of type int

[kubernetes]$ cluster/kubectl.sh update nodes 10.245.1.3 --patch='{"apiVersion": "v1beta2"}'
F0223 16:12:38.180732   20375 update.go:123] error unmarshaling JSON: json: cannot unmarshal number 3.221225472e+09 into Go value of type int

[kubernetes]$ cluster/kubectl.sh update nodes 10.245.1.3 --patch='{"apiVersion": "v1beta3"}'
10.245.1.3

**Comment by rjnagal** [comment]
@vishh can you take a look?

**Comment by vishh** [comment]
Ack.

**Comment by bgrant0607** [comment]
The value specified for memory is not a legal 32-bit integer.

**Comment by vishh** [comment]
@bgrant0607: This could be related to #4041. I think the 'int' there could be 32 or 64 bit based on architecture as mentioned in that issue.

**Comment by vishh** [comment]
This seems like a bug in our update logic. The yaml round tripping seems to be working fine. Un assigning myself to see if someone else wants to pick up this issue and triage it. If not, I will get to it soon.

**Comment by bgrant0607** [comment]
Actually, we changed memory to int64. I suspect the json encoder and/or decoder.

**Comment by a-robinson** [comment]
I'm unable to reproduce at head (d12f989e98b8ddcc3c8e79daab8c4d90b95dd5db). There have been some large changes to the update.go command file since 16 days ago. Is this still happening for you @pravisankar?

```
arob-macbookpro:fork-kubernetes arob$ ./cluster/kubectl.sh update node kubernetes-minion-5eb2.c.arob-frogger.internal --patch='{"apiVersion": "v1beta2"}'
current-context: "arob-frogger_kubernetes"
Running: ./cluster/../cluster/gce/../../_output/dockerized/bin/darwin/amd64/kubectl update node kubernetes-minion-5eb2.c.arob-frogger.internal --patch={"apiVersion": "v1beta2"}
kubernetes-minion-5eb2.c.arob-frogger.internal
arob-macbookpro:fork-kubernetes arob$ ./cluster/kubectl.sh update node kubernetes-minion-5eb2.c.arob-frogger.internal --patch='{"apiVersion": "v1beta3"}'
current-context: "arob-frogger_kubernetes"
Running: ./cluster/../cluster/gce/../../_output/dockerized/bin/darwin/amd64/kubectl update node kubernetes-minion-5eb2.c.arob-frogger.internal --patch={"apiVersion": "v1beta3"}
kubernetes-minion-5eb2.c.arob-frogger.internal
arob-macbookpro:fork-kubernetes arob$ ./cluster/kubectl.sh update node kubernetes-minion-5eb2.c.arob-frogger.internal --patch='{"apiVersion": "v1beta1"}'
current-context: "arob-frogger_kubernetes"
Running: ./cluster/../cluster/gce/../../_output/dockerized/bin/darwin/amd64/kubectl update node kubernetes-minion-5eb2.c.arob-frogger.internal --patch={"apiVersion": "v1beta1"}
kubernetes-minion-5eb2.c.arob-frogger.internal
```

The relevant node details:
```
{
    "kind": "Node",
    "id": "kubernetes-minion-5eb2.c.arob-frogger.internal",
    "apiVersion": "v1beta1",
    "resources": {
        "capacity": {
            "cpu": "1",
            "memory": 3892043776
        }
    },
}
```

**Comment by bgrant0607** [comment]
Actually, Capacity is IntOrString, which is still int.

Apparently, the reason we used IntOrString was to allow float values.

This representation is pretty hopeless, IMO.

**Comment by a-robinson** [comment]
I talked about this with @fabioy and we're wondering if perhaps the server you're running is older than the client version you were running, since the server shouldn't have been returning memory in the "3.221225472e+09" form.

**Comment by pravisankar** [comment]
I no longer able to reproduce the problem on latest k8s code. Yay issue fixed.
