### ISSUE TITLE
kubectl expose demands a selector and hates my --port

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4758]
thockin@freakshow kubernetes plural_30_endpoints /$ ./cluster/kubectl.sh expose hostnames --port=80 --container-port=9376
F0223 17:48:27.036475    1770 expose.go:84] Parameter: selector is required

thockin@freakshow kubernetes plural_30_endpoints /$ ./cluster/kubectl.sh expose hostnames --port=80 --container-port=9376 --selector run-container=hostname

unknown flag: --port

Kubectl: why do you hate your users?

**Comment by bgrant0607** [comment]
I think it's complaining about the wrong flag. Your selector flag is bad (no `=`).

**Comment by thockin** [comment]
Damn, I *have* to use an = in long flags?  What is happening to this world?

And you're right - what an utterly useless error message

**Comment by bgrant0607** [comment]
See:
#2862
https://github.com/ogier/pflag/issues/14

**Comment by ogier** [comment]
I notice you are using `flag "github.com/spf13/pflag"`. Is it possible there's something downstream of my repo that is causing this? Happy to try to find the cause, but I can't reproduce the bug: https://github.com/ogier/pflag/blob/issue_13/flag_test.go#L355

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubernetes/kubernetes.go#L50

**Comment by brendandburns** [comment]
Yes, I think that this is due to Cobra Commander trying to extract args
before parsing flags.

--brendan

**Comment by brendandburns** [comment]
See: https://github.com/spf13/cobra/pull/65 for the cobra commander fix.

**Comment by brendandburns** [comment]
fixed by #5464
