### ISSUE TITLE
Rectify "Kind" and "Type" in the API

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4761]
Specifically because "kind" is used by typemeta.

Several objects have SomethingType.  Others have SomethingKind.  Would be nice to choose one style and do it all over.

**Comment by bgrant0607** [comment]
I now think it was a mistake to proliferate use of "kind" for node and pod conditions, since "type" is much more common in the API. @ddysher @mikedanese

**Comment by mikedanese** [comment]
The {Node,Pod}ConditionKinds seem like the only types where Kind was used unnecessarily. Is this just a rename?

**Comment by bgrant0607** [comment]
@mikedanese This was forked from #4653. In particular, see:
https://github.com/GoogleCloudPlatform/kubernetes/pull/4653#issuecomment-75613081

**Comment by bgrant0607** [comment]
Done.

**Comment by thockin** [comment]
What about StatusDetails.Kind ?

**Comment by bgrant0607** [comment]
Doh! Missed that one.

**Comment by mikedanese** [comment]
StatusDetails.Kind is the kind attribute of the resource associated with the status StatusReason, which seems like the same usage of "Kind" in TypeMet". I think it makes sense to leave it.

**Comment by thockin** [comment]
Ahh, yes.  I can buy that.

**Comment by bgrant0607** [comment]
Ok, good. Re-closing.
