### ISSUE TITLE
PodInterface should support Watch

### ISSUE THREAD

**Issue by alml** [GoogleCloudPlatform/kubernetes#4777]
PodInterface should have Watch method behaving in the same way as ServiceInterface.Watch does.

Use case: a monitoring system (namely Prometheus) expects to get the list of monitored servers performing a  DNS-SD query. Special service (similar to kube2sky shipped with Kubernetes) mirrors status of running Pods into etcd, which is in turn monitored by SkyDNS server and exported as DNS-SD. Schematically the data flow looks like this: Kubernetes -> kube2sky -> etcd -> SkyDNS -> Prometheus.

The biggest challenge is to deliver list of all running pods from Kubernetes to kube2sky. Currently kube2sky can only poll Kubernetes with PodInterface.List() each N seconds, which is not efficient. Having a Watch method would be much better.

**Comment by vishh** [comment]
cc @lavalamp: Do you know why we do not support watch?

**Comment by bgrant0607** [comment]
Every object should support Watch.

**Comment by bgrant0607** [comment]
Watching status doesn't currently work -- that's #2726.

**Comment by lavalamp** [comment]
I agree with OP. This is just an accident of history; some boilerplate in the client isn't completely filled out. As Brian mentions, not every field is currently watchable but that's being addressed elsewhere.

**Comment by pmorie** [comment]
@sdminonne This is relevant to your interests potentially w/ your work on #560

**Comment by lavalamp** [comment]
This is a pretty simple change if someone wants to get their feet wet. :)

**Comment by jszczepkowski** [comment]
I'll work on it.
