### ISSUE TITLE
Host IP missing from pod 

### ISSUE THREAD

**Issue by jonlangemak** [GoogleCloudPlatform/kubernetes#4785]
While debugging Heapster we noticed that the host IP field in a pod status isnt being set....

host:192.168.10.65 HostIP: PodIP:10.10.40.6

My setup is bare metal so Im sure it's a little different than on GCE but I would think it should still be reported.  Below are some outputs for debugging...

Logs from the Heapster container (newest v.8) running debug
https://gist.github.com/jonlangemak/17bd4cad02b8d4647fcd

Output of get pods (in YAML)
https://gist.github.com/jonlangemak/e82fdeab2158c489715c

Output of get minions (in YAML)
https://gist.github.com/jonlangemak/fba5fdb350b7a8953f88

This is my first issue I've ever filed for let me know if Im doing something wrong here.  

Thanks - Jon

**Comment by vishh** [comment]
cc @ddysher

**Comment by dchen1107** [comment]
I identified this is the issue causing integration test flakiness, but haven't looked into it in detail yet.

**Comment by ddysher** [comment]
@jonlangemak Is this a reproducible on your setup?

**Comment by jonlangemak** [comment]
Yes - The logs I pulled were from my lab setup this AM.  I'd be glad to do any testing you'd like, just let me know!

**Comment by ddysher** [comment]
Thanks @jonlangemak 

Pod.HostIP is updated in pod cache:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/pod_cache.go#L161

Can you add some more logs in the pod cache, especially log the content of NodeStatus?  And post kube-controller-manager.log and kube-apiserver.log?

**Comment by jonlangemak** [comment]
Yep, hoping to get to this tonight.  Will keep you posted

**Comment by lavalamp** [comment]
@dchen1107 Is this the same thing that happened to you yesterday?

**Comment by dchen1107** [comment]
Yes, once a while, I will run into this issue. Also our users reported several failure cases due to the same cause.

**Comment by bprashanth** [comment]
@jonlangemak @dchen1107 do either of you have steps to a reproducible scenario? Is there a particular integration test more prone to this?

**Comment by dchen1107** [comment]
I observed the same failure in both test against the real cluster and integration test.

**Comment by jonlangemak** [comment]
Apologies for the delay - Yes this is reproducible in my lab setup.  I should likely rebuild the lab using the new code and ensure that Im still seeing this.  The code Im currently running is a month old at this point.  Was there any other debug related data you wanted before I rebuild?

**Comment by bprashanth** [comment]
Thanks for responding. While you have a reproducible setup there are some log hanging fruit we can tick off. It's very possible the issue will disappear with a rebase but I'd recommend scraping this information before doing so, because, why not:

1. Please upload your kube* logs (apiserver, controller, let, scheduler)

2. Are your kubelets health?
`http://$minion:10250/healthz`

3. Do they consistently responding to podInfo?
`curl http://$minion:10250/api/v1beta1/podInfo?podID=$podname\&podNamespace=$pod namespace`

4. Does etcd have the hostip for a minion (run etcdctl on master)?
`etcdctl get /registry/minions/$minion`

5. Does etcd have the hostip for a pod (on your version of the code the answer to this should be no)? 
`etcdctl get /registry/pods/default/$podname`

From this point we're going to have to modify source a little bit, so I'd understand if you just want to rebase and see if the problem goes away :)

6. Is the hostip in the node cache?
7. Do we properly decorate the hostip in the pod retrieved from cache?
https://github.com/GoogleCloudPlatform/kubernetes/compare/master...bprashanth:host_ip_dbg

How did you setup your cluster? IIRC we use Host for anything important, is the lack of a HostIP actually causing problems, are were you just confused by its absense?

**Comment by jonlangemak** [comment]
For sure - Lets try and sort this out before I rebase.  To be clear, I noticed this issue when I was troubleshooting an issue with Heapster with one of the Heapster developers.  It had no impact on the cluster before I tried to implement the most recent Heapster code.  

1 - Can you specify which logs in specific you want?  You want like the journalctl entries for each service from each host both minion and master?  
2 - I assume so, I get an 'ok' response when checking each.
3 - Yes, I tried querying a pod running on each node in this manner and got results
4 - Yes, etcd is running just on the master node.  A query for the host using it's name (which is the IP) returns the 'HostIP' field showing the correct IP (same as the name).
5 - I dont see that field -> https://gist.github.com/jonlangemak/1e544a8924d0fcca30e3

To be honest, I dont know what the node cache is but I'd be glad to check if you fill me in.  

Let me know how else I can help!

**Comment by bprashanth** [comment]
Thanks, that eliminates several possibilities. 

1. The logs should be under /var/log/kube-controller-manager.log (and kube-apiserver, kubelet, kube-scheduler), or depending on how you bootstrapped your local cluster, they might be on tmpfs.

Yep, can you apply the logging statements and give me your logs as it's happening? The node cache is literally just an in memory cache of the status of a node as returned by the apiserver. How did you bootstrapped your local cluster?

**Comment by jonlangemak** [comment]
Ah ok - It looks like I need to figure out why Im not getting log files.  I built the cluster by scratch but Im trying to move towards using salt.  My service files dont specify a log_dir but I cant find the log file for any of the services.  I set the logging directory to /var/log and the service starts but it's still not generating a log file.  Here's an example of the api-server service file that I added the log_dir setting to...

https://gist.github.com/jonlangemak/fbc218164e517f11300e

**Comment by bprashanth** [comment]
Just pipe it :)
https://github.com/GoogleCloudPlatform/kubernetes/blob/a862c37b293fc1325667d728750d718a93aed4b8/cluster/saltbase/salt/kube-apiserver/initd#L52

How did you register your minions with the master?

**Comment by jonlangemak** [comment]
The minions have their kubelet service pointed toward the etcd service running on the master...

https://gist.github.com/jonlangemak/b799802cd349d4b7c19e

I'll work on getting the logs, it appears that some of the services are logging correctly the the log_dir configuration.

**Comment by jonlangemak** [comment]
I fixed my log issue.  I have a tar from each server with all of the logs.  Whats the best way to get them to you?

**Comment by bprashanth** [comment]
Whatever works for you, paste them to a gist or share them on gdrive?

**Comment by bprashanth** [comment]
I'm mostly just looking for the kube* logs, not all of /var/log

**Comment by jonlangemak** [comment]
Oh for sure, I ended up putting the kube logs into a different directory so this is just all kube logs from all 5 servers. Let me know if that link doesnt work.  

I rebooted the servers rather than restarting all the services so some of the early errors in the logs could be because of that.  Things appear to be running normally after everything came back up.  

https://drive.google.com/folderview?id=0ByjeauU5Fw17fm5LSUktRG1XVW5wSU5VOHN6a2hxZ3BTaDRpNU5QWUs5N25mVkJMaE5HTFk&usp=sharing

**Comment by bprashanth** [comment]
Thanks for the logs, though I don't have enough to help you debug, since they all truncate within a few minutes. From what I can tell your node controller is confused, which probably means something is wrong with your setup. The kube-controller log is filled with:

```
15 E0311 10:26:20.851646     844 endpoints_controller.go:75] Failed to find an IP for pod default/monitoring-influx-grafana-controller-4yyp7
 16 E0311 10:26:21.568671     844 nodecontroller.go:125] Error registrying node 10.20.30.62, retrying: minion "10.20.30.62" already exists
 17 E0311 10:26:23.070484     844 nodecontroller.go:125] Error registrying node 10.20.30.63, retrying: minion "10.20.30.63" already exists
 18 E0311 10:26:23.076389     844 nodecontroller.go:125] Error registrying node 192.168.10.64, retrying: minion "192.168.10.64" already exists
 19 E0311 10:26:23.081312     844 nodecontroller.go:125] Error registrying node 192.168.10.65, retrying: minion "192.168.10.65" already exists
 20 E0311 10:26:31.052014     844 endpoints_controller.go:75] Failed to find an IP for pod default/monitoring-influx-grafana-controller-4yyp7
```

And your apiserver has:
```
 68 E0311 10:33:53.526538     843 pod_cache.go:249] Error getting info for pod default/monitoring-influx-grafana-controller-4yyp7: Get http://192.168.10.65:10250/api/v1beta1/podInfo?podID=monitoring-influx-grafana-controller-4yyp7&podNamespace=default: dial tcp 192.168.10.65:10250: i    /o timeout
 69 E0311 10:34:28.540943     843 pod_cache.go:249] Error getting info for pod default/monitoring-influx-grafana-controller-4yyp7: Get http://192.168.10.65:10250/api/v1beta1/podInfo?podID=monitoring-influx-grafana-controller-4yyp7&podNamespace=default: dial tcp 192.168.10.65:10250: i    /o timeout
```

1. The node controller is not able to figure out ips for nodes
2. The apiserver doesn't seem to be able to talk to your kubelet to figure out the podinfo

So I'm not surprised your nodes don't have an ip. For 2, I can't tell if this was just while/before the kubelet was starting up because the logs end too soon. This is what a *normal* node controller log would look like: https://gist.github.com/bprashanth/34ab77977ea32fef98fb. 

Fyi just provisioning a new node and pointing the kubelet at the apiserver isn't enough. You need to start the nodecontroller with a static list of minions via --machines or --minion_regexp. Did you use the configure script described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu_multinodes_cluster.md ?

@jonlangemak

**Comment by bprashanth** [comment]
Getting back to missing HostIPs, when a node is unhealthy we don't immediately evict its pods, we wait around for an eviction timeout https://github.com/GoogleCloudPlatform/kubernetes/blob/9aa744925e210c13f8c98b26a9b33c659dff52ec/pkg/cloudprovider/controller/nodecontroller.go#L245. During this time, if the apiserver can't talk to the kubelet, it will leave the pods hostip field blank even if the nodecontroller populates the hostip of the node. 

This can happen when a node is still alive from the point of view of the cloud provider, but dead to kubernetes (ie the kubelet is dead, or podinfo responds with 500). In such a state the pod flips to `Unknow`, has a Host (for upto 5 minutes) but no hostip. If the kubelet comes back up in 5 minutes the pod will flip to `Running` again and take on the hostip of the same node.

This might be the flake described by @dchen1107 https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/rc.go#L145

I'm going to upload a PR to always update the podstatus with the hostip from the node, even if the rest of the pod status is unknown, as long as the host field of the pod is set.

**Comment by jonlangemak** [comment]
Im wondering if I just need to rebuild and see if this is still happening.  Like I said, this is my lab setup and it's been through quite a lot in the last month and a half.  I'll do that and see what comes of it.  Do you want to let me know when the PR you are submitting goes through and I can rebuild then?

Also - To clarify, my nodes were listed under the nodecontroller service, I failed to mention that earlier.

**Comment by brendandburns** [comment]
@jonlangemak checking back in: is this still occurring?

**Comment by jonlangemak** [comment]
It looks like since my upgrade to Kubernetes .12 the host IP is now being reported correctly...

Host:10.20.30.63 HostIP:10.20.30.63 PodIP: 

Interestingly the pod IP is no longer reporting as it was before.

**Comment by vishh** [comment]
The Pod IP missing bug was fixed recently in Kubelet. The latest Kube
release should fix that.
