### ISSUE TITLE
Handle POD infra container updates better

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#4787]
We fixed #4759 but there are still some edge cases if we need to restart more than 1 container in the same pod. We need to improve our handling of these cases. Any time we have to restart the POD infra container, we must restart *all* containers in the pod. This may run against restart settings.

**Comment by gmarek** [comment]
Do we need to restart everything because we use Docker ID of infra container as a 'namespace', or is there any other reason? If not, is there a strong reason for using this ID, or it's used because it's convenient?

I think that we shouldn't be restarting tasks that have Never RestartPolicy, so we should either prevent them from being restarted (easy), or stop restarting tasks when infra container dies (if it's possible in the current architecture).

I can write the first option quickly, but I'd prefer to go the second way if possible, but then I'm afraid that I don't know enough about container naming. Will it be enough to use some other deterministic 'key' common for all containers?

**Comment by vmarmol** [comment]
We need to restart everything because all the containers share the network namespace of the pod infra container. If that goes away then the containers can't access the network.

It would not be possible to not restart tasks if the pod infra container dies (which should be a *very* rare event). This should be treated as a task failure similar to a system OOM or a loss of disk.

I agree that we should not restart containers that have a Never policy. We should only need to restart the pod infra container when the network configuration changes. Today we do it more often than that. We should stop doing that. In the case we do need to restart the pod infra container and there is a Never container in the pod, we should fail the update and surface an event.

**Comment by thockin** [comment]
It's actually more nefarious than not being able to access the network.
Namespaces are reference counted.  The POD container ensures that as
containers die and restart, they have a single rally point.  Consider this
timeline:

T0: POD container starts with namespace X
T1: app container C1 starts and joins the POD container's namespace X
T2: app container C2 starts and joins the POD container's namespace X
T3: C1 and C2 see each other as localhost in namespace X
T4: POD container crashes and restarts with namespace Y
T5: C1 and C2 still see each other as localhost in namespace X
T6: C1 crashes and restarts, and joins the POD container's namespace Y
T7: C1 and C2 can no longer see each other.

We could nominate one of the app containersto hold the namespace, but it
gets complicated very quickly, especially with containers that actually
"finish".

**Comment by dchen1107** [comment]
I am going to look into this one.

**Comment by vmarmol** [comment]
There is some discussion in Docker docker/docker#10462 but no conclusion. Seems to be leaning towards keeping the applications like Kubelet doing the work. Worth keeping an eye on if it reverses.

**Comment by gmarek** [comment]
#5022 WIP PR addresses some of those issues, namely it prevents restarting RestartPolicy::Never Containers, when Infra Container is being recreated.

It does not change the logic behind updates, and exactly as previously if any container is changed, Infra Pod is being recreated (variable was erroneously called 'podChanged' before, now it's 'containerChanged' as it reflects the semantics better).

**Comment by gmarek** [comment]
I'm looking for something not too complex to work on - is this still an issue?

**Comment by vmarmol** [comment]
I believe this is complete. The restarting only happens when the pod needs to be restarted and we only restart the pod container when we actually need to. @dchen1107 is there anything you think is still missing?

**Comment by dchen1107** [comment]
Yes, this is fixed due to recent refactory.
