### ISSUE TITLE
Improve content of scheduler events 

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#4788]
The existing event when ever scheduling fails for a pod is not informative.
`failed to find a fit for pod: <pod spec>`
The system should provide specific reasons for failing scheduling.

**Comment by vishh** [comment]
cc @brendandburns

**Comment by yujuhong** [comment]
This looks like #4583

**Comment by vishh** [comment]
Yup. Looks like a dup. Closing this.
