### ISSUE TITLE
"kubectl get events" returns empty unless namespace is specified

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#4796]
```kubectl get events``` returns no results unless namespace is specified.

If no namespace is specified, it should return all events recursively.

(@preillyme ran in to this)

**Comment by gmarek** [comment]
AFAICT it returns events from 'default' namespace, not no results. I'm not convinced that current behavior is bad. If anything I'd consider adding explicit --all_namespaces flag or sth, but I'm not sure if even this is a good idea.

**Comment by saad-ali** [comment]
```kubectl get events``` (without specifying a namespace) returns only the ```default``` namespace events.
The REST call ```api/v1beta1/events``` (without specifying a namespace) returns events for all namespaces.

The behavior should be consistent between the two, whether it is to return all or default name space only.

**Comment by saad-ali** [comment]
Spoke with @thockin, and he agrees with @gmarek, this is functioning as intended.

For the REST calls (```api/v1beta1/events```, ```api/v1beta1/pods```, etc.) returning all events/pods/etc. (regardless of namespace) is intended behavior. For ```kubectl``` commands, when no namespace is specified, returning the ```default``` namespace is intended behavior. 

Closing issue.

**Comment by derekwaynecarr** [comment]
In the future, I am supportive of passing * as a way of asking to run the across all namespace calls, but it should only be allowed on kubectl get.

----- Original Message -----
