### ISSUE TITLE
"kubectl get events" hangs

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#4797]
@preillyme ran in to an issue where "kubectl get events" and the get events API call just hang indefinitely.

Need to get a reliable repro.

**Comment by gmarek** [comment]
I tried to reproduce this problem on 4 single-hyperthread nodes and 1 single-hyperthread master without any success. I was playing with pods and replication controller heavy load. Maybe services behave differently?

**Comment by saad-ali** [comment]
@preillyme have you run in to this again?

**Comment by preillyme** [comment]
@saad-ali: Yes it's still happening on our test cluster.
I can add you to that project if you want to observe?

**Comment by saad-ali** [comment]
@preillyme Sure, let's sync up tomorrow.

**Comment by brendandburns** [comment]
@preillyme @saad-ali did this sync-up happen?  Is this still an open issue?

Thanks

**Comment by saad-ali** [comment]
Not yet. I reached out to @preillyme offline, awaiting response.

**Comment by dchen1107** [comment]
I am closing this one. We are dumping events during each e2e test cycle, but never hear any reports on
"kubectl get events" hangs. 

@preillyme If you still observed such issue, please re-open the issue and including the following information:

1) kubectl clusterinfo
2) kube-apiserver.log
3) etcdctl ls /registry/events

and directly assign the issue to me. Thanks!
