### ISSUE TITLE
cAdvisor should run as part of the Kubelet

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#4798]
The Kubelet dependency on cAdvisor has been increasing as it's data and functionality is further integrate into it. To ease deployment as well as make the dependency easier to handle we've considered running cAdvisor as part of the Kubelet. This should be feasible and simple to accomplish.

Marking as a P1 for node since this has been a source of issues recently and having this dependency will help with current performance work.

**Comment by pires** [comment]
This would make it easier to deploy monitoring so +1 for that.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/18
