### ISSUE TITLE
kubelet standalone fails on fedora when hostname is fqdn (ex. test.novalocal)

### ISSUE THREAD

**Issue by rabi** [GoogleCloudPlatform/kubernetes#4805]
Kubelet standalone fails to remove pods after the pod manifests are removed with the following error.

Feb 25 04:29:03 test-vm.novalocal kubelet[814]: E0225 04:29:03.424109     814 types.go:84] found a podFullName ("192e6acb13a38ef77691bf98c9ed4387.file-07561bf6-test-vm.novalocal.file") with too few fields: expected 3, actual 4

It seems the issue is how the podFullName is created for file source.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/file.go#L197

pod.Namespace = fmt.Sprintf("file-%08x-%s", hasher.Sum32(), hostname)

In os variants of fedora/rhel  hostname returns the fdqn and is used for namespace, which then fails at:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/types.go#L84

**Comment by vishh** [comment]
@vmarmol @abhgupta can one of you take a look at this issue?

**Comment by craigbox** [comment]
I also have a report of this running on GKE, K8s version 0.11.0.

As a result of the rolling update of a RC running container v0.7 to run container v0.8, there are v0.7 containers left running:

```
❯ gcloud preview container kubectl get pods
POD                             IP                  CONTAINER(S)        IMAGE(S)                                HOST                                                          LABELS                   STATUS
chat-rc-0.8-lvrcr               10.200.1.22         chat                gcr.io/customer_chat/container:0.8   k8s-chat-node-2.c.customer-chat.internal/130.211.63.54     name=chat,version=0.8    Running
chat-rc-0.8-musz4               10.200.2.22         chat                gcr.io/customer_chat/container:0.8   k8s-chat-node-3.c.customer-chat.internal/130.211.98.246    name=chat,version=0.8    Running
chat-rc-0.8-togsi               10.200.0.21         chat                gcr.io/customer_chat/container:0.8   k8s-chat-node-1.c.customer-chat.internal/146.148.121.255   name=chat,version=0.8    Running

rs@k8s-chat-node-1:~$ sudo docker ps
CONTAINER ID        IMAGE                                   COMMAND                CREATED             STATUS              PORTS                    NAMES
7428573490ab        gcr.io/customer_chat/container:0.8   "./container -api-li   21 hours ago        Up 21 hours                                  k8s_chat.ae34263d_chat-rc-0.8-togsi.default.api_7f48cc30-c6f9-11e4-80cc-42010af0c6f2_39ef4d2e                       

rs@k8s-chat-node-1:~$ sudo docker ps
CONTAINER ID        IMAGE                                   COMMAND                CREATED             STATUS              PORTS                    NAMES
7428573490ab        gcr.io/customer_chat/container:0.8   "./container -api-li   21 hours ago        Up 21 hours                                  k8s_chat.ae34263d_chat-rc-0.8-togsi.default.api_7f48cc30-c6f9-11e4-80cc-42010af0c6f2_39ef4d2e                       

rs@k8s-chat-node-3:~$ sudo docker ps
CONTAINER ID        IMAGE                                   COMMAND                CREATED             STATUS              PORTS                    NAMES
5fbf8b5fa05a        gcr.io/customer_chat/container:0.8   "./container -api-li   21 hours ago        Up 21 hours                                  k8s_chat.ae34263d_chat-rc-0.8-musz4.default.api_93e5b7c7-c6f9-11e4-80cc-42010af0c6f2_290c206b                       
980f05ac63f0        gcr.io/customer_chat/container:0.7   "./container -api-li   21 hours ago        Up 21 hours                                  k8s_chat.ab59263c_chat-rc-0.7-u93vv.default.api_fd1d88e6-c6f6-11e4-80cc-42010af0c6f2_8fe0ddb8                       
20fe52ba9001        gcr.io/customer_chat/container:0.7   "./container -api-li   21 hours ago        Up 21 hours                                  k8s_chat.ab59263c_chat-rc-0.7-c3o94.default.api_e87d412e-c6f6-11e4-80cc-42010af0c6f2_27a77220                       
```

Does not seem to be related to hostname:
```
user@k8s-chat-node-2:~$ hostname
k8s-chat-node-2
```

Some log output from the kubelet.log around the RC time: https://gist.github.com/craigbox/c053fb664600a61720ee

**Comment by dchen1107** [comment]
We recently introduced a naming schema change in Kubelet which introduces the following workflow:

1) When node first bootstrap, it has containers running with old format
2) kubelet is upgrade, and kill old containers
3) GC periodically queries the dead containers with k8s prefix, and found those containers with old format, and throw log message.

I think #5395 introduced later should fix above issue by removing those unidentified k8s containers properly.

**Comment by craigbox** [comment]
@vmarmol 

Does GKE update the Kubelet on running nodes? I thought that would only happen if you asked the cluster to upgrade.  (This report was on a GKE cluster which, I would have assumed, always had the same version of the Kubelet running on its nodes.)

**Comment by zmerlynn** [comment]
GKE does not upgrade binaries (yet)
