### ISSUE TITLE
Monitoring (heapster) doesn't work

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#4809]
While trying to [run monitoring](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/cluster-monitoring)..

* InfluxDB: OK
* Grafana: OK
* Heapster: ERROR
```
core@node-02 ~ $ docker logs 814c468118e7
+ EXTRA_ARGS=
+ '[' '!' -z ']'
+ '[' '!' -z ']'
+ '[' '!' -x ']'
+ HEAPSTER='/usr/bin/heapster  '
+ '[' '!' -z 10.100.0.1 ']'
+ INFLUXDB_ADDRESS=
+ '[' '!' -z 10.100.235.159 ']'
+ INFLUXDB_ADDRESS=10.100.235.159:80
+ /usr/bin/heapster --kubernetes_master 10.100.0.1:80 --sink influxdb --sink_influxdb_host 10.100.235.159:80
I0225 14:04:19.906504      11 heapster.go:44] /usr/bin/heapster --kubernetes_master 10.100.0.1:80 --sink influxdb --sink_influxdb_host 10.100.235.159:80
I0225 14:04:19.906636      11 heapster.go:45] Heapster version 0.8
I0225 14:04:19.906694      11 heapster.go:46] Flags: alsologtostderr='false' bq_account='' bq_credentials_file='' bq_id='' bq_project_id='' bq_secret='notasecret' cadvisor_port='8080' coreos='false' external_hosts_file='/var/run/heapster/hosts' fleet_endpoints='http://127.0.0.1:4001' kubelet_port='10250' kubernetes_insecure='true' kubernetes_master='10.100.0.1:80' listen_ip='' log_backtrace_at=':0' log_dir='' logtostderr='true' max_procs='0' poll_duration='10s' port='8082' sink='influxdb' sink_influxdb_buffer_duration='10s' sink_influxdb_host='10.100.235.159:80' sink_influxdb_name='k8s' sink_influxdb_password='root' sink_influxdb_username='root' sink_memory_ttl='1h0m0s' stderrthreshold='2' v='0' vmodule=''
I0225 14:04:19.906726      11 kube.go:211] Using Kubernetes client with master "http://10.100.0.1:80" and version v1beta1
I0225 14:04:19.906734      11 kube.go:212] Using kubelet port "10250"
I0225 14:04:19.906752      11 influxdb.go:255] Using influxdb on host "10.100.235.159:80" with database "k8s"
E0225 14:04:49.913162      11 influxdb.go:272] Database creation failed: Post http://10.100.235.159:80/db?u=root&p=root: read tcp 10.100.235.159:80: connection reset by peer
E0225 14:04:49.913243      11 heapster.go:52] Post http://10.100.235.159:80/db?u=root&p=root: read tcp 10.100.235.159:80: connection reset by peer
```

But the service seems to be available:
```
core@node-01 ~ $ curl "http://10.100.235.159/db?u=root&p=root"
[{"name":"k8s"},{"name":"grafana"}]
```

Hints?

**Comment by pires** [comment]
Since ```k8s``` database is already created when provisioning InfluxDB & Grafana, why does [createDatabase == true](https://github.com/GoogleCloudPlatform/heapster/blob/master/sinks/influxdb.go#L270)?

**Comment by vishh** [comment]
It looks like the InfluxDB service endpoint is not reachable. Most likely restarting the 'kube-proxy' should solve the issue. As for the 'createDatabase' part, it verifies if the necessary databases exist before attempting creation. In your case, the verification stage itself failed since the influxdb service endpoint wasn't reachable.

**Comment by pires** [comment]
I beg to disagree. The node running Heapster pod can access the service as detailed before, by listing existing databases
> core@node-01 ~ $ curl "http://10.100.235.159/db?u=root&p=root"
> [{"name":"k8s"},{"name":"grafana"}]

How is the service not accessible to a container of a node that can access said service?

Anyway, I've connected to the pod container running Heapster and it can access InfluxDB HTTP API
```
root@monitoring-heapster-controller-sb5qi:/# curl "http://10.100.235.159/db?u=root&p=root"
[{"name":"k8s"},{"name":"grafana"}]
```
As you can see for yourself, it also lists ```k8s``` database.

**Note**: I made sure InfluxDB was up & running before provisioning Heapster pod.

**Comment by vishh** [comment]
The error you noticed in heapster might have been a transient one. Either the kube-proxy wasn't setup fully or the influxdb container wasn't up. 
But the heapster app needs to be resilient to this and attempt db creation once the influxdb service is accessible. I filed an [issue against heapster](https://github.com/GoogleCloudPlatform/heapster/issues/130) for that part.

**Comment by brendandburns** [comment]
I'm pretty sure that this is actually due to heapster having a bad pod selector (see the recent issue on this subject)

Should be fixed soon.

**Comment by vishh** [comment]
@brendandburns: This issue is about the connectivity between heapster and Influxdb service and transient errors observed. 
@pires: The more recent versions of heapster should check for the existence of required databases before attempting creation. Some users have their own custom InfluxDB setup and creating the databases from heapster helps their use case. 
Do you still observe this error?

**Comment by pires** [comment]
I've said this previously so I'm going to repeat myself, `influxdb` **is running** and is accessible. `heapster` error has nothing to due with `influxdb`.

**Comment by vishh** [comment]
@pires: I did notice your previous post. But this error `Post http://10.100.235.159:80/db?u=root&p=root: read tcp 10.100.235.159:80: connection reset by peer` sounds more like a networking issue than an application issue.
Is there any specific behavioral change in heapster that you are trying to point out here?

**Comment by pires** [comment]
@vishh you tell `heapster` to go through API server -> proxy service -> `influxdb`. That didn't work for me! But when I executed a shell in the Heapster pod, I can access `influxdb` HTTP API in the service IP. **10.100.235.159**.
```
root@monitoring-heapster-controller-sb5qi:/# curl "http://10.100.235.159/db?u=root&p=root"
[{"name":"k8s"},{"name":"grafana"}]
```

**Comment by vishh** [comment]
@pires: The proxy is used only for external access to heapster, Influxdb or
Grafana. Inside the cluster heapster uses environment variable based
service discovery or DNS in that order of preference.
https://github.com/GoogleCloudPlatform/heapster/blob/master/deploy/run.sh#L36

**Comment by pires** [comment]
@vishh I'm having trouble making myself clear. I added logs that show you that `heapster` fail to write to `influxdb` 
```
I0225 14:04:19.906752      11 influxdb.go:255] Using influxdb on host "10.100.235.159:80" with database "k8s"
```
but that the `hipster` container can access the service in the **same** IP and **port**.

**Comment by vishh** [comment]
@pires: heapster -> Influxdb is tested continuously as part of e2e tests in Kube. I believe it works. As for the race during startup, I have patched heapster to retry database creation instead of failing in the first try. The next release of heapster should have that fix.
As for access to InfluxDB, it is useful for debugging and also for looking up events once heapster starts pushing into Influxdb. Until that happens, I will remove external access to InfluxDB by default. 
I hope this is clear. If not feel free to poke me on IRC.

**Comment by pires** [comment]
It's OK @vishh. Thanks for sharing your ideas and knowledge.
