### ISSUE TITLE
Rename createExternalLoadBalancer

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#4811]
Observed in #4585.

createExternalLoadBalancer is imperative, which doesn't fit with our declarative API. The name shouldn't contain a verb. How about just `external` or `public`?

**Comment by thockin** [comment]
given that I hope to revamp this who facet of the API eventually, I am reluctant to make this less obvious.  I could live with "public" to match "publicIPs", if you care enough to squeeze this in.

**Comment by bgrant0607** [comment]
We also need to make our terminology consistent. In some places, we use "external" and in others we use "public".

**Comment by bgrant0607** [comment]
Potentially subsumed by #7447

**Comment by bgrant0607** [comment]
Replaced by Type in the v1 API.
