### ISSUE TITLE
skydns not resilient to pod restarts

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#4814]
While working on #4812 I've noticed that sometimes dns wouldn't work. I wasn't able to reproduce that from head since I think it requires some (bad)luck and quite a lot of manual work. 
I think that in case if kube2sky starts before etcd the code that initializes EtcdClient (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go#L73) will just produce broken client that won't fix itself.
I might be completely wrong and the issue observed might be just due to error in #4812. I hope that someone familiar with etcd client setup will be able to answer easily.

**Comment by vishh** [comment]
@thockin should be able to help you @rsokolowski
