### ISSUE TITLE
kube2sky closes services watch every 5 minutes

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#4837]
Environment: GCE
watchLoop seems to restart every 5 minutes (go to the minion running kube2sky and do sudo docker logs kube2sky-container). This isn't that harmful except that all services are read every 5 minutes. I'm not sure whether the issue is on the kube2sky side or the watch implementation on api server.

**Comment by thockin** [comment]
I'm not at all surprised if the watch implementation is less than perfect that was a quick hack.  Please help.  @lavalamp and @erictune were discussing a single lib for watching that was properly debugged and robust.

**Comment by rsokolowski** [comment]
Given that I'm still looking at skydns setup I will also look into the issue of watch being restarted every 5 minutes.

**Comment by lavalamp** [comment]
Watches have a 5 minute timeout. It's not an error.

**Comment by lavalamp** [comment]
P.S. The code I'm writing for #4877 should be super easy to use for SkyDNS.
