### ISSUE TITLE
kubectl log terminates with unexpected EOF

### ISSUE THREAD

**Issue by josselin-c** [GoogleCloudPlatform/kubernetes#4844]
When using kubectl to watch logs in follow mode (-f) it stops after ~5min with ```F0226 18:17:15.255839   16187 log.go:85] unexpected EOF```. My pod is in a namespace.

**Comment by bgrant0607** [comment]
kubectl should retry. apiserver drops connections after 5 minutes.

**Comment by fabioy** [comment]
A retry logic would be good, except that "docker logs" doesn't support an offset option, so it'd be very difficult to maintain a seamless "follow" experience to the end-user. 

Filed issue #11337 with docker to extend their logging functionality (https://github.com/docker/docker/issues/11337).

**Comment by bgrant0607** [comment]
Same issue as #9013, I'm guessing.
