### ISSUE TITLE
Need a health check for DNS pod

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4852]
I have observed the DNS pod sometimes getting stuck.  Need a health-check that tries to do a lookup or something like that.

**Comment by thockin** [comment]
also DNS should probably come up with N=2 by default

**Comment by bgrant0607** [comment]
Why is this attached to 1.0 if it's P3? One of those is wrong.

**Comment by thockin** [comment]
@rsokolowski

**Comment by bgrant0607** [comment]
Health checks I can believe. We're in the process of doing that for everything else -- @dchen1107.

Nothing else is HA, so I don't buy N=2 for DNS but not for other components.

**Comment by thockin** [comment]
Other components are somewhat harder to make HA.  DNS is trivially
HA-able.  But not too important, it's available after the fact, too.

**Comment by piosz** [comment]
@bgrant0607 so you mean a generic solution for health checking, or just you are adding health check for other service. In other words should I start adding health check for DNS?

**Comment by thockin** [comment]
I'd still like to see a health-check for DNS, but I am not sure what is
appropriate, though.  Maybe have kube2sky open an HTTP server and answer
/healthz iff it can complete a non-existing DNS query?

Better ideas?

It seems the collected other fixes add up to a more stable DNS server?

**Comment by bgrant0607** [comment]
@piosz I assume this is about adding liveness probes to one or more of the containers in the dns pod:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in

Is dig in the skydns image? We could use an exec probe to perform a DNS query.

**Comment by thockin** [comment]
duh, exec probe is obviously better :)  But it doesn't need to get a name,
it just needs to complete and not hang.

so something like sh -c "alarm 5 nslookup foobar" maybe?

**Comment by piosz** [comment]
leaving unassigned since I'm not working on it right now

**Comment by brendandburns** [comment]
@vishh are you currently working on this?  If not, I'll grab it.

Thanks!
--brendan

**Comment by roberthbailey** [comment]
I think that @a-robinson was looking into this today.

**Comment by a-robinson** [comment]
Yeah, I sat on it a little today due to not being able to get it to actually work, but I'm pretty sure it wasn't working because exec liveness probes as a whole are broken (#7618).

Sent PR #7619 to resolve this once exec probes are functional.
