### ISSUE TITLE
Add density test

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#4861]
Add an e2e test to test running 100 pods per node

**Comment by timothysc** [comment]
@zmerlynn | @roberthbailey | @satnam6502  
Who can we assign for review on this one?

**Comment by satnam6502** [comment]
@zmerlynn | @roberthbailey : feel free to take this over if you want to.

**Comment by roberthbailey** [comment]
I won't have a chance to look at this in the next week.

**Comment by timothysc** [comment]
@lavalamp - this one can be closed as https://github.com/GoogleCloudPlatform/kubernetes/pull/4862 is merged.
