### ISSUE TITLE
Replication Controller looping parallelization

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#4866]
Inside of the replication controller if the replica-count is off it will fork a go routine to increment or decrement the # of pods.  This is pretty inefficient and could probably be boiled down to a single api call with a count.  

e.g. submit replication 1000 ... 1000 concurrent api calls.

**Comment by derekwaynecarr** [comment]
+1.  The current pattern causes problems with quota enabled as each pod create competes with atomic updates of quota usage tracking.  Outside of this being an easy way to overload the apiserver with traffic, I think the current pattern prohibits back off patterns when errors occur.  @lavalamp - I know you are looking at common controller, but I hope you agree spawning N go routines is not right pattern here

**Comment by piosz** [comment]
@lavalamp are you going to work on it?
@davidopp what do you think about it?
I'm happy to work on it.

**Comment by bprashanth** [comment]
Out of curiosity, is the ask for a single batched create endpoint or a batched insert into etcd as well? Sounds like the latter if you have contention on pod create.

**Comment by lavalamp** [comment]
Bulk updates (like @bprashanth says) probably will make sense in the future, but I think they're a post-1.0 item. It does seem prudent to limit the number of outstanding requests in the meantime. It might make sense to put such a mechanism in pkg/client's RESTClient, since it's likely to be widely useful.

**Comment by lavalamp** [comment]
@piosz feel free to send a PR. I recommend using the rate limiter that's in pkg/util.

**Comment by bprashanth** [comment]
1000 concurrent calls sounds like a lot, but I'm sadly unable to define exactly what *a lot* is. It would be great if we could benchmark/e2e-test api server qps in terms of pod creates (sounds like @timothysc might already have this data, if not I can file an issue), since you will probably have to do something like that to rate limit anyway.

**Comment by timothysc** [comment]
In the case of replication, are there limitations on why we can't just add a replica(s) field to the Pod type.  

So 'create pod' ... yadda yadda replica=1000 ?

**Comment by lavalamp** [comment]
@timothysc the pod object represents a single running pod in the system. When you ask for N pods, what you're providing is a pod template, not a pod. Our current replication controller design is basically that.

**Comment by timothysc** [comment]
So maybe it's me, but the api always seems to always deal in one of the following: 

1. Single Items 
2. Arrays 

In reality what I want in almost all cases for groups of PODs is a map.  For example, in this case we send the same POD 1000 times, when in reality I would like to send a PodList that contained

map[Pod]int .

**Comment by lavalamp** [comment]
@timothysc I think you're asking for bulk creation; it's a desired thing but not urgent yet.

The PodTemplate object will also enable something similar, when we start using it.

**Comment by lavalamp** [comment]
(Assuming you're talking about the replicationController <-> apiserver communication path; you really *don't* want to start 1000 pods without something actively babysitting them...)

**Comment by derekwaynecarr** [comment]
I vote for keeping it simple and remove all concurrent calls and just increment 1 by 1.  When a quota is applied to a Namespace, the concurrent calls here compete incrementing the quota.  I think we should do something fancier when we have bulk support so quota could also do the right thing.

**Comment by derekwaynecarr** [comment]
At least do 1x1 on the size up case.  I am fine doing all at once on the size down case.

**Comment by lavalamp** [comment]
Work item: figure out if #6203 fixes this.

**Comment by timothysc** [comment]
We'll run through verification now given the new knobs, but those may require tuning.

**Comment by timothysc** [comment]
Closing now post https://github.com/GoogleCloudPlatform/kubernetes/pull/6635 . 

Limits on the clients are listed and we have updated defaults a while back on system.unit files.
