### ISSUE TITLE
Consider replacement json marshalling system

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#4872]
I thought there was an issue for this, but I can't seem to find it.

Off the top of my head, there's two compelling reasons to consider this:
* Generate errors on finding a disallowed field
* Performance - we spend most of our time marshalling/converting/unmarshalling.

I just ran across this, which may be relevant: https://github.com/rainingclouds/autobindings

**Comment by thockin** [comment]
+1

**Comment by thockin** [comment]
Do you think this is plausible for 1.0?  Instinct says not/...

**Comment by lavalamp** [comment]
IMO, post 1.0.

**Comment by bgrant0607** [comment]
Dupe of #3338
