### ISSUE TITLE
Proxy can be used to make apiserver dos itself

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#4875]
Visiting the following link once per second is enough to exhaust the 10 QPS rate limit for everyone. I don't think this is important to fix right now but I thought I'd document it.

```https://<your apiserver ip address>/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro/api/v1beta1/proxy/services/kubernetes-ro```

**Comment by thockin** [comment]
http://i3.kym-cdn.com/entries/icons/original/000/012/367/evilest.gif

**Comment by lavalamp** [comment]
This is no longer possible now that the ro service has been removed.
