### ISSUE TITLE
Controller framework

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#4877]
There are pitfalls when using the watch + list pattern. Many of our controllers use this pattern, and we expect many future pieces of code to use this pattern. Therefore, we'd like to provide a framework/example which lets you fill out three functions (list, watch, and process) to get a shiny new bug-free (at least the list+watch part) controller.

This can be modeled after/mostly copied from the scheduler.

**Comment by markturansky** [comment]
+1 for this.

@ironcladlou and I were discussing something similar, building on #4453.

I have 2 recon loops in a manager (differently named than controller to differentiate it from a resource), so I made a small framework to avoid duplication of the loop.  Additionally, I used a ListFunc/WatchFunc approach that needs to be refactored to use #4453.

I would refactor to whatever framework was put in place, but here's the relevant bits of what I was doing (unfinished, still requires spit and polish):

https://github.com/GoogleCloudPlatform/kubernetes/pull/4055/files#diff-9b431cb2e728ea46d3c639144d9df7e1R184

**Comment by ironcladlou** [comment]
You may be interested to see how we approached this in origin recently:

https://github.com/openshift/origin/pull/1091

That PR includes the framework and a single reference implementation, which are further refined during with this followup containing a mass refactor of other controllers:

https://github.com/openshift/origin/pull/1170

**Comment by pmorie** [comment]
@lavalamp Did you imagine something that processed deletes or just add/update events?  I've been doing some thinking about controllers that need to process deletes and how to do retries and full recons in them -- the kube-proxy and OpenShift router are controllers like this, as examples.  I was going to open an issue for that, but I will hold off while we scope this out a little more.

**Comment by lavalamp** [comment]
@pmorie I was not planning for that case but I will think about it-- maybe it can be accomodated.

@ironcladlou thanks I will look at that.

**Comment by markturansky** [comment]
@pmorie @lavalamp I think deletes are important.  Resources (say, persistent volumes) can be deleted and removed from the system.

**Comment by derekwaynecarr** [comment]
You cannot guarantee delivery of a delete, and so we need to make sure we always support a full reconciliation of the state.

**Comment by pmorie** [comment]
@markturansky @lavalamp @derekwaynecarr Here's the sketch I've been working on on and off this week.

https://gist.github.com/pmorie/8617951a7275e847b2f7

@bparees has pointed out a couple flaws that I've carried over EventQueue which are no longer applicable; for instance, you may now get a delete followed by an add for the same object.  I need to address these but thought it might save some time to share what I have at this moment.

**Comment by lavalamp** [comment]
@markturansky @derekwaynecarr 

I think for deletes to be handled properly during a full resync, you have to have a model of "what objects do I currently know about", which is not stored in a FIFO. But I think we can make a FIFO that a) tracks operation (add, delete, update/resync) and b) when Pop() is called, it updates a map of "objects that we think exist". The latter could be used to turn a full resync into a set of add/update/delete operations.

Error handling makes it a little more complicated. My first piece of code for this issue won't have this, but I think it can be added with minimal damage to the code in a follow-up.

**Comment by pmorie** [comment]
@lavalamp Agree re: deletes.  You have to be able to reconcile from reality during a resync.

**Comment by markturansky** [comment]
@lavalamp @pmorie sounds good, and I wasn't thinking we'd get a delete event specifically.  My loops do full resync each time.  I am not using FIFO.

**Comment by ironcladlou** [comment]
I thought of a possible way the reflector could reconstitute deletes in the event of a connectivity loss/full resync.

My premise is that ListWatcher gives the Reflector one side (A) of he basis of comparison for delete  detection via List (e.g. list all routes from etcd), and your controller knows how to get the other side (B) (e.g. list all the routes from the external router). On re-initialization (full resync, as in #4923), the reflector could call ListWatcher.List, call a new function (F) you specify that returns B, and for each entry in B but not in A, synthesize a delete event.

This would make the keep the resync scenario totally transparent to the controller (which is IMO an important feature of #4923's approach).

Thoughts?

**Comment by pmorie** [comment]
@ironcladlou isn't that what we've been discussing all week?

**Comment by ironcladlou** [comment]
>isn't that what we've been discussing all week?

Not exactly: I'm talking about a new injection point to Reflector and maybe adding a means for Pop to return deletes (e.g. a bool indicator), not a new queue structure.

**Comment by lavalamp** [comment]
I've been thinking about this a little bit, and I think there's three different use cases that we want to support.

1. Process everything once, and process the most recent item only. Don't process deleted items. (scheduler)
2. Process everything once, and periodically reprocess everything. When things are deleted, process the last version of the item before it was deleted to put it in its final state. (replication controller)
3. Maintain a correspondence, meaning add/update/delete things in system B when they change in system A.

I think the difference between 2 & 3 is primarily in the way the queue handles things, and my thinking was along the same lines as @ironcladlou's.

I think it's tricky to collapse sequences of add/update/deletes and be sure you didn't lose something meaningful. Instead I'm thinking of just grouping them together in a list for case 3 above.

**Comment by pmorie** [comment]
@lavalamp Can you add a little more detail about this?

> I think it's tricky to collapse sequences of add/update/deletes and be sure you didn't lose something meaningful. Instead I'm thinking of just grouping them together in a list for case 3 above.

**Comment by lavalamp** [comment]
@pmorie @ironcladlou I did a little more work on this. Not ready for a PR yet but maybe you want to look: https://github.com/GoogleCloudPlatform/kubernetes/compare/master...lavalamp:fix7?expand=1

@pmorie Suppose you have a sequence of changes {Add foo, Update foo', Update foo'', Delete foo''}. Is that equivalent to {Add foo'', Delete foo''}, or {}, or {Add foo, Update foo'', Delete foo''}? I can think of use cases for all of the above. It gets even more complicated when you throw a re-list in the middle.

**Comment by pmorie** [comment]
@lavalamp that's what I thought you meant.  I've been thinking about it.  I
think there are probably use-cases that want different compression
strategies - perhaps we should start without compression and then add it in
a pluggable way later?

**Comment by lavalamp** [comment]
@pmorie yeah that's what my change I linked above is doing.

**Comment by pmorie** [comment]
@lavalamp so it is!

**Comment by ironcladlou** [comment]
@lavalamp 
>I did a little more work on this. Not ready for a PR yet but maybe you want to look: https://github.com/GoogleCloudPlatform/kubernetes/compare/master...lavalamp:fix7?expand=1

Looks pretty interesting so far- I put a couple of small comments on the commits.

**Comment by bgrant0607** [comment]
@lavalamp Scheduler will need to process deleted items. #1517

**Comment by lavalamp** [comment]
@bgrant0607 I don't really see how that follows, but if so, then this component will be usable for that.

**Comment by pmorie** [comment]
@lavalamp I added a couple comments to commits.

**Comment by lavalamp** [comment]
@pmorie @ironcladlou thanks for the early feedback, I will tag you again when I get this ready for another pass.

**Comment by lavalamp** [comment]
@pmorie @ironcladlou I've put the next round into #5270 for ease of commenting.

**Comment by lavalamp** [comment]
This is in now.
