### ISSUE TITLE
kubernetes apiserver service broken in v0.11.0

### ISSUE THREAD

**Issue by Fandekasp** [GoogleCloudPlatform/kubernetes#4892]
Here is my kubeconfig file:

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://example.com
  name: aws
contexts:
- context:
    cluster: aws
    user: circleci
  name: aws-context
current-context: aws-context
kind: Config
preferences:
  colors: true
users:
- name: circleci
  user:
    token: myToken
```

And the error that appears in v0.11.0  (while it worked fine with v0.10.0):

```
$ kubectl get services
F0227 19:35:52.593494   27735 get.go:158] Get
https://example.com/api/v1beta1/services?namespace=default: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Do I need to edit my nginx config by any chance? Here is the current one:

```
server {
    listen 443 ssl;
    server_name example.com;

    root /usr/share/nginx/www;
    index index.html index.htm;

    ssl on;
    ssl_certificate /etc/nginx/certs/kube-apiserver.crt;
    ssl_certificate_key /etc/nginx/certs/kube-apiserver.key;
    # don't use SSLv3 because of POODLE
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
    ssl_prefer_server_ciphers on;


    location / {
        #auth_basic            "Restricted";
        #auth_basic_user_file  /usr/share/nginx/htpasswd;
        # Auth done with Token on apiserver itself
        auth_basic off;

        # Proxy settings.
        proxy_buffering off;  # disable buffering so that watch works
        proxy_pass http://APISERVER:443/;
        proxy_connect_timeout 159s;
        proxy_send_timeout   600s;
        proxy_read_timeout   600s;
        proxy_buffer_size    64k;
        proxy_buffers     16 32k;
        proxy_busy_buffers_size 64k;
        proxy_temp_file_write_size 64k;

        # Disable retry
        proxy_next_upstream off;

        # Support web sockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by thockin** [comment]
Looks nasty.  @lavalamp for triage or redirect

**Comment by roberthbailey** [comment]
I saw a similar error trying to build kubernetes on my local machine when boot2docker got too out of date and I think it was related to a change in certificate handling (or ssl) between the docker client and the docker daemon. 

Do we still run the apiserver behind nginx on gce or do we terminate ssl connections directly?

**Comment by lavalamp** [comment]
> Do we still run the apiserver behind nginx on gce or do we terminate ssl connections directly?

We still run behind nginx.

**Comment by lavalamp** [comment]
> malformed HTTP response "\x15\x03\x01\x00\x02\x02"

Seems like this is what you get when you try to talk HTTP to an HTTPS endpoint. I think this indicates a client problem.

**Comment by lavalamp** [comment]
@jlowdermilk Does this seem like something that a messed up ~/.kubernetes directory could cause?

**Comment by jlowdermilk** [comment]
I'm not sure how well the token auth works, given that gce still uses basic. Can you hit the endpoint with curl?

**Comment by lavalamp** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/nginx/kubernetes-site#L47

We indeed have basic auth on by default. Worth trying, maybe, but I would expect a different error if that were the case.

**Comment by jlowdermilk** [comment]
I think you still need client certs to create the transport, even if insecure-skip-tls-verify is true
```
users:
- name: circleci
  user:
    token: myToken
```
Would expect to `client-key` and `client-cert` paths specified for the user. The files are generated on the server and stored under `/srv/kubernetes/`. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/util.sh#L498 has a step to copy them down.

**Comment by Fandekasp** [comment]
@lavalamp I have no ~/.kubernetes directory, nothing messed up there.
`this is what you get when you try to talk HTTP to an HTTPS endpoint. I think this indicates a client problem.`: The client is kubectl. The releases says "Fix kubectl patch behavior", and I tried to read the diff for pkg/kubectl between v0.10 and v0.11, but couldn't find the relevant part.

@jlowdermilk was the key/cert checking inforced in the code between 0.10 and 0.11 ? It was working fine without before, and I didn't add the files creation logic in my cloudformation template. I'll look into adding this stuff.

**Comment by jlowdermilk** [comment]
It's possible stricter cert checking was added on the apiserver. To be honest, I've never tried running kubectl with no client certs; the fact that it worked before may have been a bug. cc @brendandburns

**Comment by lavalamp** [comment]
Yeah what I'm suggesting is that your setup is somehow triggering a code path in kubectl that is talking HTTP to an HTTPS server.

@jlowdermilk I think cert check failing should produce a different error message.

@Fandekasp I misremembered, it's actually a ```~/.kube/``` directory. It should have cluster info and certs in it.

**Comment by jlowdermilk** [comment]
@Fandekasp, I was digging into client config loading rules for another issue, and can confirm that kubectl does default to loading `$HOME/.kubernetes_auth`. So your setup was probably working before because you/some tooling was writing a valid .kubernetes_auth file to your home directory. This behavior is confusing and unintended; you should specify all config you want to use in kubeconfig. Opened #4956 to clean up the old loading rule.

**Comment by lavalamp** [comment]
@jlowdermilk would you like to own this issue? :)

**Comment by Fandekasp** [comment]
The doc [kubeconfig doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubeconfig-file.md#example-kubeconfig-file) seems outdated, example shows *blue-user* setup with token only, when v0.11 now forces to use client-certificate and client-key in addition to token

**Comment by Fandekasp** [comment]
Getting error:

```
more than one authentication method found for  circleci.  Found [token clientCert], only one is allowed
```

The doc is correct after all, and since I'm using token, I shouldn't need any cert & key files.

**Comment by jlowdermilk** [comment]
That appears to directly contradict testing in [kubectl](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/config/config_test.go#L185).

Also, I can't see how that error output could ever happen. `clientCert` is not one of the validation methods specified in [validation.go](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/clientcmd/validation.go#L128).

@deads2k, can you comment on this? I thought token or basic auth was orthogonal to client key/cert?

**Comment by deads2k** [comment]
> I thought token or basic auth was orthogonal to client key/cert?

It's orthogonal now, but for a long time we restricted you to either/or.  It changed here: https://github.com/GoogleCloudPlatform/kubernetes/commit/abb38cf7932c72ba3cce0c4cdd2b821d069531f0#diff-fbd622d8ea20a063301bb500db6290b2L143 as part of https://github.com/GoogleCloudPlatform/kubernetes/pull/4517.

I think that 0.11 was cut before both were allowed.  0.12 should allow both token and client certs.

**Comment by jlowdermilk** [comment]
Ok, so looking at the validation rules at 0.11, token auth with `insecure-skip-tls-verify` is broken, since you can't specify both certs and token, and kubectl will not create a tls transport unless you provide a cluster CA and/or client cert/key for the user. The correct config (which should work with 0.12) is to specify `insecure-skip-tls-verify` on the cluster, but provide client key/cert on the user.

@Fandekasp, there are some workarounds you can try to make this work with 0.11:
* Use a CA for the cluster. Change your `cluster` config to
```
- cluster:
    certificate-authority: /path/to/kubernetes.ca.crt
    server: https://example.com
  name: aws
```
  That should prompt kubectl to create a tls transport. You can pull `kubernetes.ca.crt` from `/srv/kubernetes/` on the master.
* Use `auth-path` in addition to token. Put the client key and cert in a file like so:
```
$ cat /path/to/kubernetes_auth
{
  "CertFile": "/usr/local/google/home/jeffml/.kube/jeffmltest_kubernetes/kubecfg.crt",                http://sigma/job/ie/cloud-kubernetes-staging/staging.cloud_kubernetes.cluster_apiserver.pkgpreloader
  "KeyFile": "/usr/local/google/home/jeffml/.kube/jeffmltest_kubernetes/kubecfg.key"
}
```
and change your `user` config to
```
- name: circleci
  user:
    token: myToken
    auth-path: /path/to/kubernetes_auth
```
I think the merge rules will allow token with client cert/key when they are pulled from a legacy auth file.

**Comment by Fandekasp** [comment]
I upgraded to v0.12, and `insecure-tls-verify` still didn't work.

I went on the server and generated my CaFile, CertFile and KeyFile, as follow:
```
$ ./easyrsa --batch "--req-cn=kube.example.com@`date +%s`" build-ca nopass
$ ./easyrsa --subject-alt-name=DNS:kube.example.com build-server-full kubernetes-master nopass
```
Moved those files to `/srv/kubernetes/`, and copied them on my client, with **certificate-authority** in my kubeconfig cluster part, the **auth-path** in the user part, and CertFile/KeyFile in my kubernetes_auth.

It fails with error:
```
F0304 11:51:40.556729   31187 get.go:166] Get https://kube.example.com/api/v1beta1/pods?namespace=default: x509: certificate signed by unknown authority
```

Any idea why it fails ?

**Comment by jlowdermilk** [comment]
The master already generates ([via salt](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/saltbase/salt/generate-cert)) a CaFile, CertFile and KeyFile when you turn up the cluster, and copies them to `/srv/kubernetes`. You don't need to generate them yourself, and afaik, doing so doesn't replace the ones used by the apiserver. You'll want to copy down the salt-generated ones from the master. Sorry for the misunderstanding.

**Comment by Fandekasp** [comment]
As said [here](https://github.com/GoogleCloudPlatform/kubernetes/issues/4892#issuecomment-76671932), I'm creating my cluster via an aws cloudformation template, and it's not using salt. This is [one of the recommended ways](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws-coreos.md) to create a cluster on aws, and I've been using kubernetes this way for the past 3 months.

I've just copied the commands down from `cluster/saltbase/salt/generate-cert/make-ca-cert.sh` and `cluster/saltbase/salt/generate-cert/make-cert.sh`, so I'd expect it to work the same way. Minor difference: instead of signing the ip of the master, I'm signing a dns `--subject-alt-name=DNS:kube.example.com`

**Comment by jlowdermilk** [comment]
I missed that you're using cloudformation. To verify you have the right cert files copied down, can you try hitting the apiserver manually?
```
curl https://<server-ip> --cacert=path/to/your/cafile
```
Should return `401 Authorization Required`.

**Comment by jlowdermilk** [comment]
replace <server-ip> with example.com, since you are using a signed dns.

**Comment by Fandekasp** [comment]
hmm I think I'm not running apiserver properly. I mistakenly used the `--kubelet_certificate_authority` for the CAFile.
Looking in the apiserver help, I can see:

```
      --tls_cert_file="": File containing x509 Certificate for HTTPS.  (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls_cert_file and --tls_private_key_file are not provided, a self-signed certificate and key are generated for the public address and saved to /var/run/kubernetes.
```

So I did just that, concatenated my cafile content after the cert content in the CertFile file, and restarted apiserver.

When trying to curl it:

```
$ curl https://kube.example.com --cacert etc/ca.crt
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I'm wondering if another problem isn't the fact that the request goes through nginx. Nginx redirects the request to the kubernetes service ip, so when apiserver receives it, the request should have the service ip and not the dns.

**Comment by jlowdermilk** [comment]
> I'm wondering if another problem isn't the fact that the request goes through nginx. Nginx redirects the request to the kubernetes service ip, so when apiserver receives it, the request should have the service ip and not the dns.
Possibly. All the examples we have sign the ip of the master, not a dns. @brendandburns can probably answer that better.

**Comment by jlowdermilk** [comment]
@Fandekasp, are you still encountering this issue with kubectl > 0.12.0?

**Comment by jlowdermilk** [comment]
Closing as obsolete from discussion on irc.
