### ISSUE TITLE
Can pull  kubernetes/pause image  from private docker-registry?

### ISSUE THREAD

**Issue by ldpc** [GoogleCloudPlatform/kubernetes#4896]
For security reasons, in our lab servers cannot access the Internet, therefore in the experiment we use private  repository rather than docker-hub.When i play  kubernetes, found that it pull kubernetes/pause image  from the docker-hub.Cant we push kubernetes/pause iamge to our private  repository,then let 
kubernetes pull the images from private  docker-regitry?

**Comment by thockin** [comment]
@dchen1107 

At some point in the past we discussed a flag or something to tell kubelet what the 'pause' container was.  e.g. --docker_pod_image=kubernetes/pause or something

**Comment by dchen1107** [comment]
Yes, it should be easy to add this support.

**Comment by dchen1107** [comment]
cc/ @ArtfulCoder

**Comment by iano123** [comment]
Im having the same issue

**Comment by vmarmol** [comment]
This flag already exists on the Kubelet: `--pod_infra_container_image`. You can set this flag on the Kubelet to the private registry and that image will be used instead.

Closing this, feel free to open another issue if you run into any troubles with this :)

**Comment by ZPerling** [comment]
> This flag already exists on the Kubelet: `--pod_infra_container_image`. You can set this flag on the Kubelet to the private registry and that image will be used instead.
> 
> Closing this, feel free to open another issue if you run into any troubles with this :)

How can I do this settings in kubeadm config?
