### ISSUE TITLE
Report resource limits and usage of Kubelet and other daemons

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#490]
Issue #147 was filed for QoS tiers. But to really guarantee QoS for services / PODs / Containers, we need to enforce daemons' resource limits, at least tracking their usages. Currently cAdvisor is running inside a docker container, we could put Kubelet and other daemons into their own docker containers, then rely on cAdvisor to monitor and report their usages.

**Comment by bgrant0607** [comment]
@ArtfulCoder

**Comment by dchen1107** [comment]
We are running master components in pod, which resource usage will be picked up by cAdvisor and heapster automatically. But we need put kubelet, kube-proxy and docker to cgroups, so that cAdvisor can monitor their usages. cc/ @vmarmol

**Comment by vishh** [comment]
Is this required for v1.0?

**Comment by ArtfulCoder** [comment]
I spoke offline with Victor.
I can try and put kube-proxy in a pod. I can atleast do a quick test to make sure that it works.
#5419

**Comment by dchen1107** [comment]
Both Kubelet and Kube-proxy are in resource container already.

**Comment by ArtfulCoder** [comment]
ah , ok. so, nothing to be done here..

**Comment by vmarmol** [comment]
The argument was that if we got the Kube-proxy in a container we'd get the
starts automatically. Otherwise we need to export them in Heapster. Since
we were looking to place the Kube-proxy in a container, this route may not
be too bad.

**Comment by ArtfulCoder** [comment]
putting in a pod, we would get the stats just the way we get it for other
pods..
Is that ok with you Dawn ?

**Comment by dchen1107** [comment]
@ArtfulCoder We need resource container for docker no matter what. @vmarmol is doing that. We can put kube-proxy into a pod, but not kubelet itself. Kubelet can run as a container, but not as pod today. There is a chicken egg issue anyway.
