### ISSUE TITLE
test-cmd.sh failed on master HEAD

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#4908]
```
$ test-cmd.sh
....
...
+++ Testing kubectl(:pods)
E0227 14:29:00.817800   23923 server.go:315] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
E0227 14:29:15.817965   23923 server.go:315] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
F0227 14:29:16.110382   23988 get.go:151] Get https://104.154.64.102/api/v1beta1/pods?namespace=default: dial tcp 104.154.64.102:443: i/o timeout
!!! Error in /usr/local/google/home/deyuan/code/source/go-workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/test.sh:34
  'res=$(kubectl get $object -o template -t "$request")' exited with status 255
Call stack:
  1: /usr/local/google/home/deyuan/code/source/go-workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/test.sh:34 kube::test::get_object_assert(...)
  2: hack/test-cmd.sh:143 main(...)
Exiting with status 1
+++ Clean up complete
```

This works:
```
$ sudo test-cmd.sh
...
...
frontend-controller
redis-slave-controller
Successful get rc {{range.items}}{{.id}}:{{end}}: 
+++ Testing kubectl(v1beta3:nodes)
Successful get nodes {{range.items}}{{.id}}:{{end}}: 127.0.0.1:
frontend-controller-cegta
frontend-controller-ckn42
frontend-controller-v5drx
redis-slave-controller-gb50a
redis-slave-controller-nxnds
+++ TEST PASSED
+++ Clean up complete
```

Are we using /var/run for testing?

**Comment by ixdy** [comment]
Curiously travis shows a similar error message regarding /var/run/kubernetes, but it isn't failing:

```
+++ Testing kubectl(:pods)
Successful get pods {{range.items}}{{.id}}:{{end}}: 
valid-pod
Successful get pods {{range.items}}{{.id}}:{{end}}: valid-pod:
Successful get pod valid-pod {{.id}}: valid-pod
Successful get pods {{range.items}}{{.id}}:{{end}}: valid-pod:
valid-pod
Successful get pods {{range.items}}{{.id}}:{{end}}: 
Successful get pods {{range.items}}{{.id}}:{{end}}: 
E0228 00:57:55.256740   16044 server.go:309] Unable to generate self signed cert: mkdir /var/run/kubernetes: permission denied
E0228 00:57:55.256789   16044 server.go:315] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
valid-pod
Successful get pods {{range.items}}{{.id}}:{{end}}: valid-pod:
Successful get pods {{range.items}}{{.id}}:{{end}}: valid-pod:
valid-pod
...
```

I suspect the /var/run/kubernetes issue is not what's causing the failure here.

**Comment by ixdy** [comment]
However, I am able to reproduce the failure on my machine.

I note that in your case, the fatal error says
`F0227 14:29:16.110382   23988 get.go:151] Get https://104.154.64.102/api/v1beta1/pods?namespace=default: dial tcp 104.154.64.102:443: i/o timeout`

For me, it says
`F0227 17:26:30.505929   18618 get.go:151] Get https://23.236.58.135/api/v1beta1/pods?namespace=default: dial tcp 23.236.58.135:443: i/o timeout`

The ip addresses showing through here (which appear to be in the GCE space?) are worrying.

**Comment by fgrzadkowski** [comment]
It seems it still failing. I've run it locally and it failed with the following error:

  FAIL!
  Get pods {{range.items}}{{.id}}:{{end}}
    Expected: 
    Got:      elasticsearch-logging-controller-fplln:kibana-logging-controller-gziey:kube-dns-oh43e:
  
  143 ./hack/test-cmd.sh

The aforementioned line:

  # Pre-condition: no POD is running
  kube::test::get_object_assert pods '{{range.items}}{{.id}}:{{end}}' ''

I think it is expected that there are some pods started by k8s (e.g. elasticsearch). Does it mean the test has a bug?

**Comment by fgrzadkowski** [comment]
Strangely the same code (#4810) passes tests on travis (https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/52755393)

**Comment by zmerlynn** [comment]
I think you're reading it backwards. The test is expecting no pods to be started, but finding the k8s add-on pods, which is normal if it were running against a normal master.

In Travis, it's a synthetic environment with no add-ons.

This should be assigned to whoever added the checks (on mobile.. I know I merged the PR but don't remember who :)). We need to exclude the add-ons (perhaps by finally getting around to putting them in a separate namespace).

**Comment by ixdy** [comment]
@lhuard1A added the assertions, so CC'ing for comment.

**Comment by fgrzadkowski** [comment]
I looked into this with @rsokolowski and it seems that test-cmd.sh may fail locally depending on the kubeconfig. Some commands are using defaults for kubectl and thus sometimes they contact another cluster. I'll send a PR to fix this.
