### ISSUE TITLE
Limit number of pods that are allowed to run per machine

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#4910]
From the [networking notes](https://docs.google.com/document/d/1CIrbYl-tzu91sPNx43MoI6qhGSEm-mfqmQbl17M-1kI/edit) at the the 2015-02 kubernetes contributor conference.

**Comment by bgrant0607** [comment]
The right way to do this isn't to track IPs. It's to create a new resource requirement by default for every pod.

**Comment by bgrant0607** [comment]
Or, even better, @abhgupta suggested just adding a scheduler config parameter:
https://github.com/GoogleCloudPlatform/kubernetes/issues/367#issuecomment-75620779

**Comment by thockin** [comment]
I very much want the ability to schedule to opaque counted resources.  If
nodes publish that they have N "kubernetes.io/pod-ip" resources and we know
that each pod has an implicit need for 1 pod-ip, we can just make it the
common case.

We will have to reconcile that with the budding network plugins, one use of
which is for out-of-band IP address management, but we can cross that
bridge later.

**Comment by gmarek** [comment]
I'm looking for the next thing to work on. Do you think this one is OK? I haven't looked at the resources closely yet, but IIUC they are defined in types.go as ResourceList, with ResourceName being defined there as well and having the quantity. So the whole generic machinery is there, what's needed is to defined 'ip_addresses' (or sth) resource name and plug it to all interested parties (Node and Scheduler). Right?

**Comment by bgrant0607** [comment]
Yes, this is a fine thing to work on. 

The node should report how many pods and/or addresses it could handle in NodeStatus.Capacity (#5030).

**Comment by gmarek** [comment]
I started looking on this issue and it looks simple with one small exception. Namely you suggest that it should be per Node. If by 'Node' you mean 'Kubelet' everything's easy, number of available IPs can be put into KubeletConfig, Kubelet then fills NodeStatus.Capacity with this number when asked for it. But if by Node you mean Node, and for some reason you want this number be a parameter for Node configuration, then things get more tricky, as IIUC generally the data flow is in the other way.

**Comment by thockin** [comment]
We have discussed this topic before (implicit resource requirements) but I
don't think I ever saw a final design - design doc?

**Comment by gmarek** [comment]
OK, I'll try to write something today.

**Comment by gmarek** [comment]
I wrote a short proposal #5507. I'm not sure how such document should look like though, so please let me know if there's some established norm.

**Comment by lavalamp** [comment]
Is this issue about (A) limiting the number of pods per machine, or about (B) doling out ports from a specific external IP address on a node?

These are completely orthogonal issues as far as I can tell.

**Comment by bgrant0607** [comment]
(A)

**Comment by gmarek** [comment]
Renamed the issue, and slightly changed #5547

**Comment by davidopp** [comment]
I propose to remove this from 1.0 milestone. Any objections?

**Comment by davidopp** [comment]
@bgrant0607 agreed with moving to 1.0, so I'm going to do that now, and if someone objects they can comment.

**Comment by davidopp** [comment]
Sorry I mean moving to post-1.0.

**Comment by bgrant0607** [comment]
The problems introduced by #5547 must be fixed.

**Comment by bgrant0607** [comment]
Or it should be reverted.

**Comment by davidopp** [comment]
Working on a fix now.

**Comment by davidopp** [comment]
@lavalamp suggested that this should be specified as max # of pods per core rather than max # of pods per node. This would address the problem that it doesn't scale with size of the node. That would be a useful change to make post-1.0. It might even allow us to stop using LimitRange for that purpose. So I'm reopening this issue and marking it 1.0-post.

Also, we should finish up #8669 so we can do an e2e test of the feature (again, post-1.0).

**Comment by bgrant0607** [comment]
Max pods as a function of cores makes total sense, but this will not replace LimitRange. Only setting initial resource requirements intelligently could replace the LimitRange default value, in which case we might also/instead want to apply a minimum.

**Comment by davidopp** [comment]
> Max pods as a function of cores makes total sense, but this will not replace LimitRange

I'm not arguing it would replace LimitRange in general, but I was thinking it would replace the use of LimitRange to limit the number of pods per node. Is there any other reason we have a LimitRange in the default namespace today?

I agree that setting initial resource requirements is better, but I was assuming this discussion was in the absence of that feature.

**Comment by bgrant0607** [comment]
Is there anything else we're planning to do here? Scale the max. by node resources?

**Comment by davidopp** [comment]
Yes, I think we want to do that, also we need to deal with #8802 so we can get e2e test for this feature.

**Comment by bgrant0607** [comment]
What problems does LimitRange address: https://github.com/GoogleCloudPlatform/kubernetes/issues/10242#issuecomment-115875181

**Comment by gmarek** [comment]
Opened #12069 for scaling max-pods. Closing this issue.
