### ISSUE TITLE
Need validation for Lifecycle structs

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#4917]

**Comment by mikedanese** [comment]
Beyond the current validation? Is that the type you are talking about?
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L474
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L522

**Comment by thockin** [comment]
Hmm, I must have grepped badly.  My fault.
