### ISSUE TITLE
Kubelet should report last terminated container status

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#4919]
Currently kubelet reports current status only. If pod's restart policy is not never, the last terminated container status will be override by the latest status, and lost. We should report last terminated container status. 

I am going to update our v1beta3 api first, but will hold the implementation until we have #4561

**Comment by wojtek-t** [comment]
@dchen1107 did you have a chance to start working on it?
IIUC, to support this we need to change the api (pkg/api/v1beta3/types.go), which IIUC from what @bgrant0607 wrote in some other thread should be done this week. I'm happy to help with it if you want me to help.

**Comment by bgrant0607** [comment]
@wojtek-t Only breaking changes have a deadline. Additive changes can be done at any time.

**Comment by dchen1107** [comment]
I am working on this. PR should be ready today or tomorrow.

**Comment by dchen1107** [comment]
Also agree with @bgrant0607 This is not part of API breakage.

**Comment by wojtek-t** [comment]
Thanks for answers & clarifications @bgrant0607 and @dchen1107
