### ISSUE TITLE
Evaluate whether we should eliminate the source component in kubelet

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#4922]
This is forked from #3453.

We want to sync all the pods on kubelet (whether from file source or http source) back the the apiserver (#4090). It seems reasonable to eliminate the `source` component that is used internally in the kubelet as part of the pod full name.

To maintain the readability (i.e. for users to recognize the source of the pod), we can incorporate the source as part of the pod name. E.g. `*-file-*` or `*-api-*`

**Comment by davidopp** [comment]
I think it's valuable to know the source of the container for debugging. I'm not sure it's essential that it be visible at the node level, as long as you can get it from the API server. But what you proposed sounds reasonable to me.

**Comment by erictune** [comment]
did you mean `*-file-*` or `*-http-*`?
I don't think we'd want to change the name for apiserver-source pods.

**Comment by yujuhong** [comment]
@erictune, I meant `*-http-*". Thanks for the correction.

We settled on the naming scheme in #5103. This issue is obsolete.
