### ISSUE TITLE
REST api - POST service fails in v1beta3 with "method not allowed"

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#4940]
In latest k8s built from source, 
sending a create (POST) request on /services fails with error "method not allowed":

The json used is from here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/v1beta3/redis-master-service.json
Using v1beta1 (with another json that fits that format) works OK.

The error in kube-apiserver.log:
I0302 16:04:36.229378   23907 handlers.go:108] POST /api/v1beta3/services: (100.444us) 405
goroutine 436 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2086453e0, 0x195)
        /home/abonas/kubernetes/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9c
github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc208474cd0, 0x195, 0xccd150, 0x17, 0x0, 0x0)
        /home/abonas/kubernetes/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:192 +0x5f
github.com/emicklei/go-restful.func·004(0xc20845df50, 0xc208474cd0)
        /home/abonas/kubernetes/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:175 +0xda
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20845def0, 0xc20845df50, 0xc208474cd0)
        /home/abonas/kubernetes/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa1
github.com/emicklei/go-restful.(*Container).dispatch(0xc208148c40, 0x7f7e5e62b028, 0xc2086453e0, 0xc208375d40)
        /home/abonas/kubernetes/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:179 +0x673
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f7e5e62b028, 0xc2086453e0, 0xc208375d40)
        /home/abonas/kubernetes/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:76 +0x44
net/http.HandlerFunc.ServeHTTP(0xc2082c89f0, 0x7f7e5e62b028, 0xc2086453e0, 0xc208375d40)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc20814a8a0, 0x7f7e5e62b028, 0xc2086453e0, 0xc208375d40)
        /usr/lib/golang/src/pkg/net/http/server.go:1511 +0x1a3
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·009(0x7f7e5e62b028, 0xc2086453e0, 0xc208375d40)
        /home/abonas/kubernetes/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/handlers.go:147 +0x4c5
net/http.HandlerFunc.ServeHTTP(0xc20836f2c0, 0x7f7e5e62b028, 0xc2086453e0, 0xc208375d40)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
github.com/GoogleCloudPlatform/kubernet

**Comment by bgrant0607** [comment]
v1beta3 isn't enabled by default yet. Did you enable it?

Instructions are here:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook/v1beta3

**Comment by abonas** [comment]
@bgrant0607 
GET requests work on v1beta3, so it seems like it's enabled.
If it's disabled, wasn't I supposed to get 404 on any url starting with v1beta3?
Is it supposed to be disabled when running from source too? (hack/local cluster) why?

**Comment by bgrant0607** [comment]
How are you generating/sending the requests? Some of our clients do auto-magic conversions.

Yes, it's disabled by default. The reason is that we're still developing the API and we don't want anyone to depend on it yet. Hopefully it will be enabled by default in a couple weeks.

**Comment by abonas** [comment]
@bgrant0607 plain http, REST client browser addon. no magic conversions. just json in the request body. and again, it does work with GET, and it works with POST to v1 from the same client.

**Comment by bgrant0607** [comment]
`GET /api` returns what?

**Comment by bgrant0607** [comment]
Also, did you use a v1beta3 schema? 

See:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook/v1beta3

**Comment by abonas** [comment]
@bgrant0607 (as the initial comment in this PR says):
a. I used a v1beta3 example from this repo:
The json used is from here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/v1beta3/redis-master-service.json

b. GET on /services under v1beta3 returns the services correctly.

**Comment by nikhiljindal** [comment]
As per the swagger spec (http://kubernetes.io/third_party/swagger-ui/), POST on /api/v1beta3/services is not allowed, while GET is.
You need to POST on: /api/v1beta3/namespaces/{namespaces}/services

Seems Working as intended.

**Comment by abonas** [comment]
@nikhiljindal if that's the case, it's breaking backwards comp, and it worked couple of weeks ago...

**Comment by nikhiljindal** [comment]
Apologies for that abonas.
We are still making changes to v1beta3 and it is possible that it might have been working a few weeks ago but is not allowed now.
It should get stable soon.

**Comment by bgrant0607** [comment]
Good catch. Default namespace must be specified explicitly.

**Comment by abonas** [comment]
fyi @itamarh @simon3z 

@nikhiljindal  any timelines that you can share regarding freezing the api to become stable?

**Comment by bgrant0607** [comment]
@abonas We're working on it. Hopefully no more than a few weeks. Last big planned incompatible change is #4742.

**Comment by abonas** [comment]
@bgrant0607 , @nikhiljindal  so from what I see, v1beta1 still works the old way where no need to provider a namespace during POST, is that correct?
if so, it means double work for clients who support both api versions, or is the v1beta1 is about to be deprecated soon? 
And btw, is the v1beta3 will be also renamed for 1.0 to some other name?
thanks

**Comment by bgrant0607** [comment]
@abonas Yes, we plan to eliminate v1beta1/2, and will rename v1beta3 for 1.0. As soon as we enable v1beta3 by default (next week?), v1beta1 will be deprecated.

The intent is that most clients should only need to use one API version. It's just generic client libraries and tools that need to support multiple versions.

Namespaces are specified using URL params in v1beta1/2, and use the "default" namespace implicitly by default.
