### ISSUE TITLE
SecretVolumeSource and namespace validations / defaults

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#4954]
We have a couple nits to work out with `SecretVolumeSource`:

1.  Having to specify the namespace for the target secret is cumbersome for use-cases where you want a pod template to be namespace-agnostic; it would be convenient to default the namespace for the secret to the namespace the pod is created in.
2.  Currently there's no validation to prevent you from referring to a secret in another namespace from a `SecretVolumeSource`; should there be?  At least until we have a strong cross-namespace story?

I know @liggitt has some opinions about this.

**Comment by pmorie** [comment]
@erictune @thockin @bgrant0607

**Comment by liggitt** [comment]
if namespaces are the ACL boundary, letting a pod reference secrets outside its namespace seems not great, especially since they get resolved by the node, which will likely have broader permissions than the user that created the podspec.

**Comment by erictune** [comment]
There needs to be a check whether the pod creator is allowed to use the secret.  Suggest filing a new issue for that.  

This applies even if we say that you can only reference within the same namespace, because we won't want to give everyone in the namespace access to every secret.

**Comment by erictune** [comment]
I filed: #4957

**Comment by liggitt** [comment]
It feels a little odd to imply ACL to the secret is based on the pod creator, when the ACL that actually matters is the node's permissions at resolve time. That means if you revoke the pod creator's access to the secret, the pod can keep getting scheduled and resolving the secret just fine.

**Comment by liggitt** [comment]
To be clear, I'm not advocating basing the ACL at secret resolve time on the pod creator. If I have permission in a namespace, create some pods, then leave the company and my permissions get revoked, those pods should continue working for other people in the namespace to manage. I just think it's weird to base the check at pod creation time on the pod creator.

**Comment by pmorie** [comment]
@deads2k

**Comment by erictune** [comment]
hoping to make this just about whether namespace is required/validated, and make #4957 about checking permission to use a secret.  Copying @liggitt comments there.

**Comment by pmorie** [comment]
I propose that a namespace not be required and that an empty namespace should signify the namespace of the pod.

I started prototyping the above tonight and realized that we will need to expose the pod namespace  in the arguments to `volume.Plugin.newBuilder`.  It seems like it would be acceptable to widen the arguments to this function to:

```go
newBuilder(spec *api.Volume, pod *api.Pod) (volume.Builder, error)
```

Any thoughts on that @erictune @liggit @thockin ?

**Comment by markturansky** [comment]
@pmorie I would be able to use that method as well.

**Comment by smarterclayton** [comment]
I think the pod (and it's annotations) should be visible to volume plugins

**Comment by liggitt** [comment]
do we want to limit this to the pod ObjectMeta at first? pod name, namespace, labels, and annotations  seem reasonable. I wonder what hacks access to the entire pod will lead to (volumes that do different things depending on what other volumes are configured in the pods, etc)

**Comment by liggitt** [comment]
also want to make sure volume builders don't mutate anything in the pod object

**Comment by smarterclayton** [comment]
A volume in theory has root access to the pod at runtime anyway (the same way in Linux creating bind mounts effectively is root) because you can put untrusted code into the execution path.  Also, a volume plugin runs as root today.

Agree it shouldn't be able to mutate the pod, and there are reasonable limits on what should be visible.  However, at some point the volume will want to see resource limits, or know what mount it will get.  I'd rather not be changing the interface for volume plugins every time that happens.

**Comment by pmorie** [comment]
Agree @smarterclayton re: changing interface. Also agree re: mutation.

**Comment by pmorie** [comment]
@derekwaynecarr what say you?

**Comment by derekwaynecarr** [comment]
I think a pod should not be allowed to reference a secret not in its namespace.

**Comment by smarterclayton** [comment]
Jordan's notes cover a lot of this, but essentially cross namespace references are not required for the vast majority of solutions right now, and we should default to not allowing them for features until we have a concrete need to allow them.

Ie pod templates will not be cross namespace.

**Comment by derekwaynecarr** [comment]
agree with @erictune that ability to reference a secret in the same namespace should be resolved in a separate issue and discussion.

**Comment by markturansky** [comment]
@derekwaynecarr have you seen #5122?  @pmorie and I both need to access things in the same namespace from within our volumes.

**Comment by pmorie** [comment]
@erictune @derekwaynecarr @liggitt Once #5122 goes in we can resolve this.  I suggest:

We change the `SecretVolumeSource` to:

```go
type SecretVolumeSource struct {
  SecretName string
}
```

**Comment by pmorie** [comment]
Will make a PR for this later tonight if I have time.

**Comment by smarterclayton** [comment]
Making it a reference isn't terrible (strong typing can be good), it's just we should be doubly certain how it is used.

**Comment by pmorie** [comment]
@erictune @smarterclayton @derekwaynecarr @liggitt @mfojtik Starting a branch now to use a name instead of an object reference so there will be no need to specify a namespace and secrets will come only from the pod's namespace.

@erictune I'll update the docs you added.

**Comment by pmorie** [comment]
I believe we can close this issue now, since we have refactored `SecretVolumeSource` to use a simple Name field.
