### ISSUE TITLE
Apiserver proxy requires a trailing slash

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4958]
This works:
```
 https://130.211.129.169/api/v1beta1/proxy/services/monitoring-grafana/
```
but this does not:
```
 https://130.211.129.169/api/v1beta1/proxy/services/monitoring-grafana
```

We should somehow emphasize the need for the trailing slash for now, and then work out what is going wrong (client side scripting?) to fix this (our fault in the proxy or Grafana's?)

@vishh

**Comment by satnam6502** [comment]
Likewise for Kibana. #4959

**Comment by satnam6502** [comment]
For the Kibana case, I observe a sequence of correctly proxied GETs e.g. to:
```
fontawesome-webfont...
/api/v1beta1/proxy/services/elasticsearch-logging/font
```
but then I see:
```
app.js
/api/v1beta1/proxy/services/app
```
which fails because I assume what was really needed is:
```
app.js
/api/v1beta1/proxy/services/kibana-logging/app
````
and a curl against that gives a pile of plausible Javascript.

**Comment by lavalamp** [comment]
After a little thought, I think what's going on here is that web clients can't tell that ```kibana-logging``` is a directory without the trailing slash. One thing we could potentially do to help is to redirect (301) from ```kibana-logging``` to ```kibana-logging/```, since I don't think the former is useful for anyone.

**Comment by vishh** [comment]
cc @nikhiljindal

**Comment by nikhiljindal** [comment]
How are we generating that URL? Can we append a "/" at the end while generating the URL?
Doing a redirect or auto-adding "/" in the proxy for all requests could break other requests.

**Comment by vishh** [comment]
The URL is not generated anywhere. It is assumed that
'/proxy/service/<service name>' would work.

**Comment by nikhiljindal** [comment]
I discussed this with @vishh and @lavalamp.
To clarify, proxy server does not require a trailing slash. It works as expected (gives the same response with or without a trailing slash)
The client code, on the other hand, expects it to be rendered on a path with a trailing slash and breaks when that is not the case.
Ideally, we should fix the client code.
For now, we decided to update proxy to send a 301 redirect from a path without a trailing slash to a path with a trailing slash.
I will send a PR for this.

**Comment by satnam6502** [comment]
By "client code" do you mean things like Elasticsearch and Kibana?

**Comment by nikhiljindal** [comment]
Yes. The code being rendered on those paths.

**Comment by lavalamp** [comment]
I agree with what @nikhiljindal said, I just want to clarify that it's not necessarily a "broken" client, just one with different expectations. Adding the 301 redirect seems like an easy way to satisfy such clients and reduce user pain.

**Comment by piosz** [comment]
Not fixed because of #6114

**Comment by nikhiljindal** [comment]
On GCE, the redirection is still not happening because the request is upgraded before we get a chance to redirect https://github.com/GoogleCloudPlatform/kubernetes/issues/6264

On localhost, the redirection works fine but we are unable to load the css and js files because of https://github.com/GoogleCloudPlatform/kubernetes/issues/5339#issuecomment-88291854

**Comment by ddysher** [comment]
@nikhiljindal Is proxy still supported in v1beta3?  I vaguely remember that we wanted to remove it.

I tried this: `https://ip/api/v1beta3/proxy/namespace/default/services/monitoring-grafana/` but got NotFound error.

**Comment by satnam6502** [comment]
Access to cluster-level logging components depends on the proxy so avoid making ELBs.
Elasticsearch and Kibana are accessed via the v1beta3 service proxy.

**Comment by satnam6502** [comment]
Although the trailing slashes are no longer required.
````
Kubernetes master is running at https://104.197.12.87
elasticsearch-logging is running at https://104.197.12.87/api/v1beta3/proxy/namespaces/default/services/elasticsearch-logging
kibana-logging is running at https://104.197.12.87/api/v1beta3/proxy/namespaces/default/services/kibana-logging
kube-dns is running at https://104.197.12.87/api/v1beta3/proxy/namespaces/default/services/kube-dns

```
