### ISSUE TITLE
Web page thumbnail not generated for Kibana via proxy URL

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4968]
The thumbnail icon for Kibana is not generated now that we access Kibana via paths like `https://104.154.76.190/api/v1beta1/proxy/services/kibana-logging/` 
In the previous setup (using an external load balancer and public IP) the thumbnail was properly served and this made it easier to idetnify the tab in the browser that contains Kibana.

**Comment by bgrant0607** [comment]
What does the kibana html look like? Are the URLs being rewritten? Was it a relative or absolute URL? Was it pulling the image via https or http?

**Comment by satnam6502** [comment]
I'll revert to the previous setup and work the answer to these questions by observing what is going on in my Chrome console. I guess we re-write URLs and we are now using HTTPS (before it was HTTP).

**Comment by satnam6502** [comment]
Thanks David. No idea off the top of my head how to fix this. I am sure if I hacked away at it enough I could get to the bottom of it :-)

**Comment by satnam6502** [comment]
The move to Kibana 4 makes this work.
