### ISSUE TITLE
Node status is stuck as Unknown

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#4989]
I see the following in the kube-controller-manager log:

```shell
Mar 03 17:54:31 kubernetes-master kube-controller-manager[3535]: E0303 17:54:31.439747    3535 nodecontroller.go:221] error updating node 10.245.1.3: minion "10.245.1.3" is invalid: update contains more than labels or capacity changes
Mar 03 17:54:31 kubernetes-master kube-controller-manager[3535]: I0303 17:54:31.437298    3535 nodecontroller.go:218] updating node 10.245.1.3
```

@dchen1107 - This is happening to me on HEAD and is the reason why pod status is always showing unknown even when they are scheduled and running.

**Comment by derekwaynecarr** [comment]
This is with the vagrant cloud provider.

It looks like the delta between the new and old minion is the Node.Spec.ExternalID is being set on the incoming minion but is not set in the originally created minion.

**Comment by derekwaynecarr** [comment]
I am not sure how this is not affecting other cloud providers.

It looks to me that NodeController populated the node ExternalID here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L273

It looks like the Kubelet provided value is missing the ExternalID

**Comment by derekwaynecarr** [comment]
Actually, I am now confused on what the NodeController may or may not be doing here that is causing the status to not get updated.

**Comment by derekwaynecarr** [comment]
It looks like the client is passing an ExternalID on the incoming request, but the original value that is in etcd does not have an ExternalID set.  Not sure what changed that would have caused this issue to appear.

**Comment by derekwaynecarr** [comment]
I think this causes problems: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L175

The memory is re-used in a for-loop by Go so referring to a pointer value in a map here will cause problems I think.

**Comment by derekwaynecarr** [comment]
Ok, the referenced line is the problem.  Sending a PR.

**Comment by derekwaynecarr** [comment]
Well, I go back on that now.

A simple way to reproduce this is to delete all the minions in your cluster, and verify the node controller is able to add them back.  For me, this is causing the node controller to add them back in an unknown status, and then all updates to the node fail.  The update fails because the node controller is not setting an ExternalID on the original object.

**Comment by dchen1107** [comment]
I am looking into this now. cc/ @ddysher too

**Comment by derekwaynecarr** [comment]
Related issue opened while debugging this: #4992

**Comment by derekwaynecarr** [comment]
Debugged through here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L142

I can via manual fmt see that the object has an ExternalID set prior to the call Create.

When I look at etcd, I end up with this persisted:

```shell
 {
                        "createdIndex": 8,
                        "dir": true,
                        "key": "/registry/minions",
                        "modifiedIndex": 8,
                        "nodes": [
                            {
                                "createdIndex": 10,
                                "key": "/registry/minions/10.245.1.3",
                                "modifiedIndex": 10,
                                "value": "{\"kind\":\"Minion\",\"id\":\"10.245.1.3\",\"uid\":\"14dcbfd9-c1da-11e4-b6da-0800279696e1\",\"creationTimestamp\":\"2015-03-03T19:18:32Z\",\"apiVersion\":\"v1beta1\",\"resources\":{\"capacity\":{\"cpu\":\"1\",\"memory\":3221225472}},\"status\":{}}"
                            }
                        ]
                    }
```

Note: it is missing an ExternalID somehow ;-)

**Comment by derekwaynecarr** [comment]
Ok, I think I see the issue

Nodes returned from here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L407

Do not have an ExternalID

Which can make Nodes created from here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L181

End up without an External ID.

Having two different nodeClient.Create() paths in this code is confusing.

Also we are doing bad things in maps holding pointers to memory allocated in for-loop.

We need to fix that ;-)

**Comment by dchen1107** [comment]
Yeah, this is bug we should fix. Thanks for looking into this. If you already have a potential fix, please feel free to grab the issue from me.

**Comment by derekwaynecarr** [comment]
I think I have a PR that should fix.  Testing that now.  Will cc you on the PR.

**Comment by justinsb** [comment]
Thanks for fixing - it did end up affecting AWS as well (AWS isn't in a fully working state just yet, particularly with node discovery).
