### ISSUE TITLE
kubectl.go tests failing with timeouts, panic

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#4996]
Almost certainly due to #4963. It's at least passing some of the time so I don't think we're leaking proxy jobs any more, but it looks like at least one of the 3 tests is failing on every run.

**Comment by jlowdermilk** [comment]
I take it back, this doesn't seem to be caused by #4963. After digging into logs a bit, the timeouts are caused by slow docker image pulls. I'm seeing > 1min to pull `kubernetes/update-demo:nautilus`, which exceeds the 60s timeout. I don't know if increasing the timeout is what we actually want, as it's likely the image pull is getting stuck in the queue.

Still looking into what's causing panics.

**Comment by roberthbailey** [comment]
As a temporary work-around, can we bump the timeout up to 10 minutes? In the normal case the test will still pass quickly and when the image pull is slow we won't give up before giving docker a chance to do its thing. We can reduce it to a 30 second timeout once #4566 is implemented.
