### ISSUE TITLE
Example running OpenShift Origin on Kubernetes was prematurely merged

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#4997]
This PR was prematurely merged:
https://github.com/GoogleCloudPlatform/kubernetes/pull/4591

Need to update the PR based on the actual steps that were needed to get what was demonstrated at the public Kubernetes meet-up last week.

**Comment by erictune** [comment]
Any chance you can get rid of the hostPort from the example?

**Comment by derekwaynecarr** [comment]
@erictune - depending on the Kubernetes provider, yes.

For Vagrant based provider, I think I still need the hostPort because I do not have routes.
For the GCE provider, I should be able to get rid of it because I have routes.

In both providers, there were a number of setup steps that did not make the merged PR.

For those that are tracking this issue (which I know folks have pinged me on separately)

1. Docker needs to be configured to allow privelaged containers
2. Docker needs to be configured to allow pushing to an insecure registry (this is point in time)

Ideally, I could use a ReplicationController in the example to load balance OpenShift, but until we can provide a pattern to run etcd as a pod, I am unable to do this and need to use the embedded etcd we end up running.

**Comment by derekwaynecarr** [comment]
Note: I will resolve this issue in 2 phases.

1. Fix Vagrant (which was demonstrated)
2. Augment to document using GCE (which has some additional steps on firewall rules)

**Comment by derekwaynecarr** [comment]
Turns out OpenShift Origin is too secure now ;-)

This is blocked until OpenShift Origin allows you to mint certs on the client, and then supply the certs on startup as a secret to the pod.  

This feature is coming soon.

/cc @deads2k

**Comment by derekwaynecarr** [comment]
I now have all the required pieces to get this to work.  I hope to get a PR submitted to fix this issue by end of this week.
