### ISSUE TITLE
Application release management: rollouts, rollbacks

### ISSUE THREAD

**Issue by ntquyen** [GoogleCloudPlatform/kubernetes#500]
I'm new to Kubernetes and trying to make a comparison between Kubernetes and Deis. So I have a question: Does Kubernetes have the ability to rollback application to previous release?

I looked at the live update example, It's cool, however I wonder about the way applications are deployed. It seems to me that Kubernetes deploys app directly from docker image, not from Dockerfile. And it doesn't manage app releases.

**Comment by bgrant0607** [comment]
Rolling update is implemented. Rollback is covered by #1353. #503 and #1743 cover related issues. Closing this one as redundant.
