### ISSUE TITLE
Change /bindings to /binding pod subresource

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#5000]
Forked from #2726.

@smarterclayton @lavalamp

**Comment by smarterclayton** [comment]
We fine with supporting both and deprecating /bindings in v1beta3?

**Comment by bgrant0607** [comment]
Yes. I don't think this is gating for v1beta3, anyway. It's more in the "nice-to-have" category.

**Comment by lavalamp** [comment]
Yeah I think subresources will be cool but let's cut 1.0 before we go crazy with them.

**Comment by smarterclayton** [comment]
Even if we don't introduce subresources, we need to get the common fixes in.  I'll split those if we don't want to do bindings pre 1.0z

**Comment by smarterclayton** [comment]
Actually, the subresources and client code are a small part of the pull.  I'll disable those, but I think we should make the change to binding for v1 so we can use it for other types.

**Comment by lavalamp** [comment]
@smarterclayton if you're doing the work I have no objections :)

**Comment by bgrant0607** [comment]
Sorry, I ran a doc fixit yesterday and am behind on PR reviews. Will try to get to this soon.

I would actually like to experiment with some subresources in v1beta3, so we can get experience with them. /binding should be pretty easy.
