### ISSUE TITLE
Emit more debugging info in our start-up scripts

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#5006]
It can be a pain digging into clusters that have failed to start up properly. If we make it easier to debug such events, we make it easier to improve the scripts to make future failures less frequent.

**Comment by gmarek** [comment]
I'll try to make it a bit better for GCE. Though I must say that I never had any problem in figuring out what went wrong, as it usually is a problem with some leftover GCE resources. @a-robinson: do you have any particular problem that should be reported better?

**Comment by a-robinson** [comment]
I think the GCE resource problems you've experienced have been part of the kube-up commands that run on your local machine, right?

As an example of something that would be useful, it'd be great if we checked whether commands that could fail actually succeeded or failed rather than always assuming they succeeded and continuing.

I opened this issue after getting frustrated from spending a couple hours digging into start-up script output on the VMs in clusters that failed to come up properly. The clusters had failed to come up because various downloads weren't completing successfully, with different downloads failing in different ways on different clusters. The output contained a lot of noise and it was difficult to find useful signal to focus in on.

In these particular cases, one common failure was that [this loop](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L144) for downloading and installing salt tars would fail because part of the file would download but not all of it, so download-or-bust would think the file was there, but then dpkg would fail because the entire file wasn't.

**Comment by gmarek** [comment]
OK, thanks for the clarification. First thing I'm working on is actually removing some things that are printed during turnup. I find quite a lot of info printed on the screen to be rather useless (e.g. multiple kubectl Running:...  logs)

**Comment by zmerlynn** [comment]
This got cleaned up a lot in 0.13, when I made the startup script `errexit`, and changed the `motd` so that it made it clear that the node setup was borked if you logged into a node that was incomplete. Now this situation is pretty clear if the node setup is broken: you login, and it tells you tail the startup script, which *should* have the error. That's not always the most educational, but it's damn good. This probably is about the best we're going to do.

That said, what we really need is a "broken cluster diagnosis" tool, not just this.

**Comment by zmerlynn** [comment]
Oh, and for what it's worth, I think @a-robinson was referring to the on-node startup script (now `cluster/gce/configure-vm.sh`), versus `kube-up.sh`

**Comment by gmarek** [comment]
Right. I got it mixed up. Too many overloaded terms around:/

**Comment by roberthbailey** [comment]
It sounds like this can be closed then?

**Comment by zmerlynn** [comment]
Closing. I had a pie-in-the-sky idea about "node phone home and then terminate" that would work especially well for MIGs, but I think we can leave that for a future revision.
