### ISSUE TITLE
Use gcr.io private docker registry for e2e tests

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#5007]
The majority e2e test flakes have had slow docker pulls as a root or contributing cause. The sooner we can move to a private docker registry the better.

**Comment by justinsb** [comment]
Agree with the idea.  But I'm working on AWS, and I don't know how to auth to the gcr.io images.  Does gcr.io allow public images?

**Comment by zmerlynn** [comment]
It does now.

**Comment by justinsb** [comment]
Hooray!  Now we just need to make unqualified docker image names default to gcr.io ;-)

**Comment by jlowdermilk** [comment]
@ixdy, can you look into this?

**Comment by jlowdermilk** [comment]
iiuc, this entails uploading the images we use for e2e into gcr.io on the kubernetes-jenkins project, and then modifying the image references for all e2e pod specs. [GCR docs](https://cloud.google.com/tools/container-registry/#using_the_container_registry_with_google_cloud_platform) have more detail.

**Comment by roberthbailey** [comment]
We had a series of red dots in Jenkins tonight during the docker hub outage.

**Comment by mattmoor** [comment]
@ixdy LMK if I can help get this going, or how I can help.

**Comment by ixdy** [comment]
I haven't had a chance to look into this. If anyone has spare cycles and wants to work on it, feel free to assign to yourself.

One concern I heard from some folks is how this change would affect those running e2e tests not on GCE - in particular, there were some concerns about bandwidth usage and charges, though I don't know all of the details.

**Comment by jlowdermilk** [comment]
I actually started working on this yesterday. The plan is to pull kube addon and e2e images from gcr.io only for clusters running on gce/gke. Other providers would continue to pull from docker hub.

**Comment by mattmoor** [comment]
@jlowdermilk I am curious why?

**Comment by mattmoor** [comment]
@ixdy Can you loop me into any threads on this?

**Comment by jlowdermilk** [comment]
@mattmoor, do you mean why only gcr.io for gce/gke? Due to the above mentioned concern about egress cost for clusters running elsewhere, mainly on aws.

**Comment by jlowdermilk** [comment]
Seems like the extra cost was a complete misunderstanding on my part. There is no added cost for pulling from gcr.io regardless of cluster location. Opened #6030 to pull cluster addon images from gcr.io. Will follow up with the same approach for e2e test images.
