### ISSUE TITLE
Architecture Diagram improvements

### ISSUE THREAD

**Issue by jbayer** [GoogleCloudPlatform/kubernetes#501]
CA Advisor runs inside docker containers, but I don't believe it's correct to show the Kubelet and Proxy processes as inside the docker box on the minion.

Also, shouldn't the internet->firewall-> really load balance across minion proxies instead of be connected to just one SPOF minion, treating that connection more like a logical connection across all minion proxies?

**Comment by bgrant0607** [comment]
We should just review the diagram and make it correctly reflect the state of 1.0.
