### ISSUE TITLE
Design: Build docker images for master components for dev cluster on the fly

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#5011]
@ArtfulCoder has pending PR to run etcd_server in a pod, which is pretty much ready to go any minutes. 

Now we want to have other master components running inside a pod / pods. For GKE, this should be easy since it only upgrades to a proper release, from which we could build docker image and push to some repository. But there are the issues for dev cluster. @ArtfulCoder and I discussed this, and now we have two proposals on the table, and both have pros and cons:

**Idea 1:** Build docker images for each release build and tag it with kubernete-dev version bit, and push those images tar file through salt:

pros: 
* The same building process could be re-used for GKE and other cloud provider for production release.
* We can use salt to push docker image directly to master node without complicated feature supported in kubelet.

cons: 
* Everytime when we build a development release, we have to update manifest file for those mater component with new image tag from version bit. 
* More dependency on salt which we want to get rid of

**Idea 2:** Build docker images on master node at runtime. Kubelet is watching a managed directory, and get inotify on changes. When new binary is pushed to master node, kubelet is notified, and create image from scratch, and tell docker to reload newly created image, then restart containers.

pros:
* No update to manifest file for master components for each build

cons:
* It is pretty complicated when I were typing the idea. 
* It requires some special code in kubelet and other components. 

Any more ideas? or suggestions? or objections? 

cc/ @alex-mohr @bgrant0607 @thockin @davidopp

**Comment by bgrant0607** [comment]
Run a registry? #1319

**Comment by davidopp** [comment]
Option 1 seems pretty reasonable. (BTW I think we've given up on getting rid of salt for the time being.)

IIUC running a local registry would obviate the need for salt, but you'd still need a way to tag which image version to load. So it does seem like a good idea, but still requires other aspects of @dchen1107 's proposal.

**Comment by dchen1107** [comment]
Option 1 is pretty much what I suggested to the user a while back at: https://github.com/GoogleCloudPlatform/kubernetes/issues/1317#issuecomment-55704491

@bgrant0607 thanks for the link to local registry issue. I tried to find that one earlier, but failed. For GKE use case, it is going to use gcr.io the private docker registry. But for dev cluster, like what @davidopp pointed out, to upgrade a cluster with new changes, a developer has to do the following steps: 
1) build the binary, 
2) build the image, 
3) tag the image with its unique tag number, 
4) push it to registry, 
5) update manifest with the latest tag and push it through salt
6+) rest of steps are similar

**Comment by alex-mohr** [comment]
Re: registry usage, fwiw, I think if we're relying on manually pushing a version of the docker image to the machine for the dev flow, we could potentially skip publishing to a registry?

But if our image is ~10MB static go binary, not clear how much it matters whether we push via registry or not -- gcr.io seems comparable to scp to me.  Start simple and optimize if the flow is slow?

And having just 1 cluster upgrade path used by both prod + dev is also a win re: complexity + maintenance cost.

**Comment by dchen1107** [comment]
We are going to option1 for dev cluster for now since it goes along with private register later in first several steps. We can change it later.

**Comment by ArtfulCoder** [comment]
I brainstormed with @thockin who suggested using the md5sum of the binary as the tag for the corresponding image that has the binary.
I think that is a good way to go about it.

**Comment by dchen1107** [comment]
that is a good optimization here to avoid unnecessary restart for each push.

**Comment by dchen1107** [comment]
cc/ @bgrant0607

**Comment by ecnahc515** [comment]
I suggested this in #4885, but you should look into the Alpine Docker image. It would simplify your build process while still maintaining your minimal image size. It avoids the need for using salt, or pre-building binaries since it can all be done in the image while still getting 5-10Mb images (most of which is the Go binary size).

**Comment by roberthbailey** [comment]
If you are building the binary on your machine, why not use the (short) git-hash from the dev environment? Then it would be easy to trace an image back to a particular source revision.

**Comment by roberthbailey** [comment]
I played with gcr.io this week and it's a really easy way to distribute the images (assuming you are running your dev cluster on GCE). It also has the advantage that if you are pushing the same image to multiple clusters in your GCP project that you only need to upload to google once and the pulls will be fast. The current dev flow uploads a .tgz to google storage so it wouldn't be adding any new dependencies.

**Comment by dchen1107** [comment]
cc/ @fgrzadkowski on master components upgrade for 1.0

**Comment by fgrzadkowski** [comment]
@marekbiskup

**Comment by dchen1107** [comment]
cc/ @timstclair @kubernetes/sig-node-feature-requests Tim this is what I proposed on how to build kube-system images, especially for master components long time ago. 

Also you can see there is an open issue #24123. If you plan to move down to this direction for kube-system images in production, you have to make sure CRI has image loading functionality too. That is a new request for CRI API.

**Comment by timstclair** [comment]
@ixdy - fyi, see Dawn's comment above.
