### ISSUE TITLE
kube-down.sh should remove entries from ./kube/...

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#5040]
When a cluster is torn down the corresponding cluster information under ./kube/... should be removed.

**Comment by satnam6502** [comment]
@jlowdermilk if you like you can re-assign this to me and I can do it for GCE.

**Comment by jlowdermilk** [comment]
If you have cycles to work on it now, have at it. Otherwise I can get to it later this afternoon.

**Comment by satnam6502** [comment]
Oh, not today, I am totally focused on the doc fixit.
