### ISSUE TITLE
Port guestbook.sh to ginkgo

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#5045]
Implement guestbook test as a kubectl-driven test in `test/e2e/kubectl.go`. @piosz, this should be a fairly straightforward follow up from #4588, if you are interested/have cycles.

**Comment by piosz** [comment]
As I wrote in the email the plan is:
1. Fix problem w guestbook example (#5091).
2. Make guestbook.sh test becomes actual test (#3693).
3. Port it do ginkgo.

Should be done this week, but it depends on how fast 1. can be done.
