### ISSUE TITLE
Enable streaming remote command execution and port forwarding on GCE nodes

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#5046]
Forked from #3253 and more discussion in pr #3763:

1) nsenter is not in the kubelet's PATH by default. It's installed in /usr/local/bin but the path is /sbin:/usr/sbin:/bin:/usr/bin

2) the minions don't have socat. We should install it to containerVM image by default. 

cc/ @filbranden Filipe, can you have socat installed in this release of containervm.

**Comment by filbranden** [comment]
Trying to add socat.

You still using nsenter? Shouldn't you use `docker exec` instead?

If nsenter is really needed, I can create a symlink in `/usr/bin` so that you'll find it without tweaking the path...

Cheers,
Filipe

**Comment by dchen1107** [comment]
Here is the reason answered by @thockin in #3763 

Regarding nsenter - I forgot that the process eunning in the container is literally a child of docker's daemon.

**Comment by vishh** [comment]
By going with `nsenter` will have to re-implement any bug fixes and features being added to `docker exec`. The features that are currently being planned are sub cgroups for exec jobs, improved exec process cleanup, permissions, etc.

**Comment by ncdc** [comment]
The problem with `docker exec` is that all input and output is proxied through the Docker daemon. There is more discussion about it in #3763, such as https://github.com/GoogleCloudPlatform/kubernetes/pull/3763#issuecomment-73633990.

I should also mention that using tooling such as `nsenter` and `socat` potentially can be abstracted to support multiple methods, so if `nsenter` isn't available, `docker exec` could be used, etc.

cc @smarterclayton

**Comment by smarterclayton** [comment]
Ultimately proxying through the daemon is not a scalable solution.  I agree with @ncdc that we should support exec as a target mode, but it's not something we'd advocate at scale.  My preference is that we investigate the equivalent of nsinit but upstreamed with docker for exactly these sorts of scenarios.

**Comment by dchen1107** [comment]
With latest containervm image for gce, socat is included and proper symlink to nsenter is created. 

Close the issue.
