### ISSUE TITLE
Document default restart policy in description tag

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5057]
Neither the docs/ nor swaggerui document what the default `restartPolicy` is.  

`pkg/api/types.go` does state that the default is Always.  

I get why this is the default: replication controllers aren't supposed to work with anything but "Always".  But, that is also a default which may not be obvious to users.  *Why would you want to restart something that exited with success* they may rightly ask.  Of course, changing that default would be a pain since it would break all the existing pod definitions.  Perhaps something to consider for a future API version, once we have a runToCompletionController.

**Comment by bgrant0607** [comment]
We should just document the default.

**Comment by bgrant0607** [comment]
This will be easier to do if we convert this to a string field. #3607
