### ISSUE TITLE
Replication controller doesn't reject updates with a modified resourceVersion

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#5086]
Setting the resource version to something arbitrary will fail the CAS, but doing something like:
```
for i := 10; i < 100; i++ {
  controller.ResourceVersion = strconv.Itoa(i)
  rc.Update(controller)
}
```

Will work if the latest version is < 100. Fix:
1. Teach `ValidateObjectMeta` to overwrite the resource version like it does creation timestamp
2. Modify the rc's Update method to call `ValidateReplicationControllerUpdate` with the current version of the object (it currently calls `ValidateReplicationController` with just the update).

This should tie in well with moving the entirety of rc validation into a strategy (https://github.com/GoogleCloudPlatform/kubernetes/issues/4973).

@bgrant0607 @lavalamp since we discussed this today

**Comment by lavalamp** [comment]
I don't understand-- that code should fail until it overtakes the current version, then it will succeed every time?

2 is a valid bug though.

**Comment by bprashanth** [comment]
I feel like having a field that will mess with database consistency if modified, and not having a way to check if it's been modified, is generally brittle. I guess I did a bad job of explaining that with my example. If I have a resource version set to the future, it could clobber all the updates that occurred while it was in flight. Allowing that update right till the CAS phase sounds like a bad idea. If someone hasn't fully understood how resource version works I can see them doing exactly this (i.e modifying the object and incrementing the version by hand).

1. why `ResourceVersion` and not `resourceVersion`? 
2. If we must expose it, can we add a pinnedResourceVersion field to the ObjectMeta that we use to overwrite it in `ValidateObjetMeta`?

..of course we could just solve this with documentation.

**Comment by bprashanth** [comment]
Hrm, I can create an rc through the update method by specifying a ResourceVersion of 0, which is slightly confusing because they now have the same selectors. This case is a little far fetched though, since I actually have to change the name of the rc (so less likely that someone did so by accident).

**Comment by bgrant0607** [comment]
See #2210

**Comment by lavalamp** [comment]
> I feel like having a field that will mess with database consistency if modified

Oh, I think I see the misunderstanding. ResourceVersion field is not actually writable. It is not stored in etcd; instead, it is generated from etcd's "EtcdIndex", which should monotonically increase every time you write to the object. It's part of the metadata that *etcd* keeps about the object. Look inside the etcd_tools.Helper object to see how that happens.

To update (PUT), you set ResourceVersion in the metadata to indicate which version of the object your changes are supposed to apply to. If the server knows about a more recent version of the object, it should reject your changes.

**Comment by lavalamp** [comment]
> Hrm, I can create an rc through the update method by specifying a ResourceVersion of 0,

Yeah, it should actually return HTTP status 201 indicating that you created something when you do that.

**Comment by lavalamp** [comment]
Another way to say this: we use the ResourceVersion to implement optimistic concurrency. http://en.wikipedia.org/wiki/Optimistic_concurrency_control

**Comment by bprashanth** [comment]
IRL we decided to reject non-matching resourceVersions in validateUpdate instead of waiting for a CAS failure

**Comment by lavalamp** [comment]
I thought we decided that it didn't really matter either way. :)

**Comment by lavalamp** [comment]
(And it's important that a mismatch in ResourceVersion returns a Conflict error as opposed to an invalid field error or whatever.)

**Comment by bgrant0607** [comment]
Would switching to the generic etcd implementation solve this problem?

**Comment by bprashanth** [comment]
Generic/etcd will enforce the pattern of calling `BeforeUpdate->strategy.ValidateUpdate(update, obj)` on update, but currently the rcStrategy doesn't know how to validate an update. I'm planning to teach the rcStrategy how to validate an update, invoke it by hand like we do today from `controller/rest`, and figure out the generic/etcd migration piecemeal.

As far as the actual validation, I'm just going to do a GET for the current obj and invoke strategy.ValidateUpdate with it. This will prevent the [create via update bug](https://github.com/GoogleCloudPlatform/kubernetes/issues/5086#issuecomment-77312559) by ensuring the name is immutable. If someone bumps up the ResourceVersion they can win a CAS anywhere, so that's outside the scope of this bug. 

I can also investigate a solution for #2210 while I'm in the space.

**Comment by lavalamp** [comment]
I think the title on this bug is inaccurate. Downgrading priority. @bprashanth can you put a TL;DR here and/or change the title?

**Comment by lavalamp** [comment]
Is this redundant with #4973?

**Comment by bprashanth** [comment]
yes I think we can just dupe validation bugs to https://github.com/GoogleCloudPlatform/kubernetes/issues/4973 so I'm closing this one
