### ISSUE TITLE
Cannot link container

### ISSUE THREAD

**Issue by inovout** [GoogleCloudPlatform/kubernetes#5090]
os:coreos 557.2
cloud config :https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/standalone.yaml

core@lab11 /opt/bin $ kubectl get pods
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                  LABELS              STATUS
tomcat-server-pid   10.244.68.28        tomcat-server-cid   tomcat              127.0.0.1/127.0.0.1   name=tomcat         Running

core@lab11 /opt/bin $ docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS               NAMES
d8ed1f186dca        tomcat:8              "catalina.sh run"   48 minutes ago      Up 48 minutes                           k8s_tomcat-server-cid.28bf13f6_tomcat-server-pid.default.api_ea367802-c304-11e4-9989-0800278ee1da_900cd81b   
437262593e0b        kubernetes/pause:go   "/pause"            48 minutes ago      Up 48 minutes                           k8s_POD.f5ace97e_tomcat-server-pid.default.api_ea367802-c304-11e4-9989-0800278ee1da_1d79e38e              

core@lab11 /opt/bin $ sudo docker run -it --rm --link k8s_tomcat-server-cid.28bf13f6_tomcat-server-pid.default.api_ea367802-c304-11e4-9989-0800278ee1da_900cd81b:tomcat centos /bin/bash
FATA[0000] Error response from daemon: Cannot start container 81ad33e408a465fca8f4d33ad75f11d3648ab13775c801371180c2819efd9b9f:  (exit status 2)

**Comment by erictune** [comment]
You should not need to explicitly use `docker run` with kubernetes.  And, in particular, you should not need to use `--link`.  A properly setup kubernetes cluster has network connections between all the containers. See https://github.com/thockin/kubernetes/blob/docs2/docs/cluster/networking.md

**Comment by inovout** [comment]
in production,should not need to explicitly use docker run.
but, I want to enter the Container,so i know the details, in order to better learning

**Comment by dchen1107** [comment]
You can use docker exec -i to enter a container

**Comment by inovout** [comment]
thank you!
