### ISSUE TITLE
kubelet initialization error

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#5092]
I launched a cluster that was unhealthy and was trying to diagnose why when I ran across an interesting kubelet error. 

On the master, The validate endpoint is showing that the single node in the cluster cannot be reached:

```
$ curl 127.0.0.1:8080/validate
[
  {
    "component": "scheduler",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "etcd-0",
    "health": "success",
    "msg": "{\"action\":\"get\",\"node\":{\"dir\":true,\"nodes\":[{\"key\":\"/registry\",\"dir\":true,\"modifiedIndex\":3,\"createdIndex\":3}],\"modifiedIndex\":3,\"createdIndex\":3}}\n",
    "err": "nil"
  },
  {
    "component": "node-0",
    "health": "unknown",
    "healthCode": 2,
    "err": "Get http://xxxxx.internal:10250/healthz: dial tcp 10.240.230.53:10250: connection refused"
  },
  {
    "component": "controller-manager",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  }
]
```

From ```/var/log/kubelet.log``` on the node I see:
```
E0305 08:44:41.696593    4616 server.go:299] Failed to create kubelet: API error (500): engine is shutdown
```
and the kubelet appears to keep running but never recovers.

**Comment by roberthbailey** [comment]
If I manually kill the kubelet (```sudo kill -TERM <pid>```) and then run ```salt '*' state.highstate``` on the master (to restart it) then it runs without re-printing the above error and the master's validate endpoint shows that the node is healthy. 

It would be much nicer if the kubelet could recover on its own without needing me to manually intervene.

**Comment by roberthbailey** [comment]
I encountered this a second time this evening but with a slightly different error in the kubelet.log file

```
E0305 10:23:48.452861    4787 server.go:299] Failed to create kubelet: dial unix /var/run/docker.sock: connection refused
```

The symptoms and remediation were the same.

**Comment by roberthbailey** [comment]
This was on the 0.12.0 release.

**Comment by dchen1107** [comment]
Ok, the initial error reported above is due to docker is not running. The issue here is not kubelet is not running, instead of docker is shutdown. Why docker is shutdown here? because we upgrade to 1.5 docker?

**Comment by dchen1107** [comment]
I lowered the priority to P1.

@roberthbailey We recently added monit to babysitting both docker and kubelet. Monit will check both docker and kubelet if running every 5 mins (#2884). In your failure case, docker should be restart by monit. We can discuss the interval here. Maybe reduce it to 1 min.

**Comment by bgrant0607** [comment]
Reducing the monitoring period SGTM.

**Comment by dchen1107** [comment]
@roberthbailey How long you have wait when you query /validate? If it takes too long for a cluster being initialized, that is a separate issue and we should fix.

**Comment by dchen1107** [comment]
Ok, #4592 introduced DockerCache in kubelet, which makes thing worse. Basically it constructs a DockerCache at kubelet initialization time. If docker is not running, kubelet bailed out too. 

@wojtek-t I am assigning this to you. I think we shouldn't fail kubelet initialization here just because of docker is shutdown. Kubelet should report NodeStatus including docker's status.

**Comment by dchen1107** [comment]
I will address the monit' s period issue in #5102

**Comment by roberthbailey** [comment]
Trying to address your questions in order:

> Why docker is shutdown here? because we upgrade to 1.5 docker?

We have intermitent issues with docker not starting. @a-robinson is working on tracking it down (see #5102).  

> We recently added monit to babysitting both docker and kubelet. Monit will check both docker and kubelet if running every 5 mins (#2884). In your failure case, docker should be restart by monit.

On these nodes docker was running as was the kubelet, but the kubelet wasn't reachable by the master because it wasn't listening on the expected port. What does monit check? That the process is alive? Can it be configured to make sure it is "healthy" (for some definition of healthy)? If it just checks that the process is up, maybe kubelet should exit when it can't initialize properly and let monit restart it. 

> How long you have wait when you query /validate? If it takes too long for a cluster being initialized, that is a separate issue and we should fix.

We wait up to 10 minutes for /validate to report that all cluster components are healthy. The cluster is "initialized" in the sense that all components are running, but the cluster isn't functional because all components are not healthy. In this case manually bouncing the kubelet process pretty much immediately moved the node to healthy making the entire cluster functional. I did the manual checks 20-30 minutes after the initial 10 minute timeout, meaning that even at a 5 minute interval monit had plenty of chances to rectify the broken kubelet (and appeared to not do so).

**Comment by roberthbailey** [comment]
Another data point: I just looked at a cluster that was launched at 8:23 this morning (5 hours ago) using version 0.12.0 and it has this same problem. I killed the kubelet and waited a couple of minutes, after which it was restarted and running happily (as reported by the master's /validate endpoint).

**Comment by roberthbailey** [comment]
@dchen1107: @wojtek-t appears to be out of office the rest of this week and this is causing a significant number of cluster creation failures. Is there someone else who can own this and drive it to completion sooner?

**Comment by dchen1107** [comment]
cc/ @vmarmol Can you take a quick look at this?

**Comment by dchen1107** [comment]
@roberthbailey what do you mean cluster creation failure? How big your cluster is? 

If you run 0.11 release, we should upgrade docker. also @wojtek-t 's pr ((#4592) is not in 0.11 release. But 0.11 release doesn't have monit yet. We all observed sometimes docker daemon couldn't restart. With 0.11 that node is gone when docker failed to restart. 

For 0.12 release, monit is installed and configured to take care both docker and kubelet processes. @wojtek-t's pr is just making kubelet initialization failed when docker is not running. But both docker and kubelet are monitored by monit, eventually they are coming up. Things is definitely better than 0.11.

**Comment by roberthbailey** [comment]
> What do you mean cluster creation failure?

After 10 minutes the master's /validate endpoint is not reporting that all components are healthy

> How big your cluster is?

1 master, 1 node.

I have only observed this on the 0.12.0 release. 

My question about monit is whether is does anything more than keep the process running. I have observed that it will restart the kubelet if the process exists (restoring it to working order) but it seems content to leave a broken kubelet process running for hours, making the cluster unusable.

**Comment by vmarmol** [comment]
I will take a look and send a fix, assigning to myself.

@roberthbailey I believe that it only checks whether the PID is alive. I will file a separate issue for using /healthz or an alternative (#5107).

**Comment by bgrant0607** [comment]
It looks like monit is capable of health checking:
http://mmonit.com/wiki/Monit/ConfigurationExamples#zope

**Comment by dchen1107** [comment]
Monit just detects if process is running or not today, but we could config it to do so.

**Comment by dchen1107** [comment]
Please just handle issue introduced by DockerCache here. We are going to handle healthcheck and interval in separate issue.

**Comment by vmarmol** [comment]
+1 @dchen1107  :)

**Comment by wojtek-t** [comment]
Thanks a lot for taking this issue @vmarmol and sorry for introducing the problem.
