### ISSUE TITLE
Work around issue of docker often not restarting cleanly

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#5102]
For context, see [the issue I opened against docker](https://github.com/docker/docker/issues/11181) about restarting docker being flaky.

I've personally observed this a handful of times, and it looks like it may be behind #5092 as well. We could work around docker's slow termination in at least a couple different simple ways:
1. Kill docker immediately when the VM starts, such that when salt tries starting it later it won't have to shut it down first
2. Re-run salt.highstate periodically for at least a couple times after the initial startup, if not forever.
3. Rely on monit? It doesn't seem to be working at the moment (edit: it just wasn't merged soon enough to be on these clusters)

**Comment by a-robinson** [comment]
cc @dchen1107

**Comment by dchen1107** [comment]
Here is my understanding related to the issues / questions you listed above:

>>1. Kill docker immediately when the VM starts, such that when salt tries starting it later it won't have to shut it down first

We all observed sometimes docker daemon failed to start before. But #5092 reported is different one. Current version of containerVM image is running docker 1.4.1, and OSS one is configured with 1.5 for testing. Please note that I asked Filipe to build a new one with 1.5 now. In this case, when you initially bringing up a cluster on GCE, it will upgrade to docker 1.5, which involves shutdown. I am not sure how long it takes to upgrade a docker daemon here. But this is why yesterday I insisted for a time being, GKE should treat docker upgrade same as kernel / image upgrade. 

>>>2. Re-run salt.highstate periodically for at least a couple times after the initial startup, if not forever.

I don't think this might at all. See reply below. 

>>>3. Rely on monit? It doesn't seem to be working at the moment.

I tested monit with killing docker and kubelete before, and it works. But I do feel the interval is too long here.

**Comment by bgrant0607** [comment]
Is the problem that we aren't waiting for Docker to shut down cleanly before attempting to restart it?

**Comment by dchen1107** [comment]
There is a file lock for docker process, attempting restarts during shutdown will fail.

**Comment by dchen1107** [comment]
I will reduce monit's period to 1 min here.

**Comment by a-robinson** [comment]
Great, I expect monit will alleviate this - these were clusters running 0.11.0, which was cut before we were using monit to keep docker running.

**Comment by a-robinson** [comment]
Closing, given that having monit running at all fixes this problem 99% of the way. Changing the period is just an extra optimization.
