### ISSUE TITLE
Unhealthy Kubelet should be restarted

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#5107]
We've run into issues like #5092 where the Kubelet was up but not healthy. The monit monitoring for Kubelet should ensure it is "healthy" rather than just alive. We need to define what healthy means in this context and monitor it based on that. An alternate option is for the Kubelet to exit when it gets into a situation it can't serve from. This may lead to crashloops so we'd need to be careful going this route. The answer is probably a bit of both.

**Comment by vmarmol** [comment]
Courtesy of @bgrant0607, healthchecking with monit: http://mmonit.com/wiki/Monit/ConfigurationExamples#zope

**Comment by dchen1107** [comment]
Health check is under this umbrella issue: #2884

**Comment by dchen1107** [comment]
Will send a PR shortly.
