### ISSUE TITLE
kubelet --docker_endpoint argument ignored

### ISSUE THREAD

**Issue by Symmetric** [GoogleCloudPlatform/kubernetes#5108]
I'm trying to get my kubelet to talk to Docker through Powerstrip, and to do that I need kubelet to send all docker API requests to a specific tcp port on localhost.

Digging through the code, I've found the --docker_endpoint option on the kubelet binary. I've tried setting that, but kubelet is ignoring it when creating pods; requests still hit the default unix:// socket. (I'm verifying this by running socat at /var/run/docker.sock, in addition to logging any requests that hit my http server).

Looking at the kubelet logs, I do see the "Connecting to docker on tcp://127.0.0.1:2377" log made by GetDockerEndpoint (in util/node.go), so my overridden endpoint config does appear to be making it into the running kubelet.

[Here's](https://gist.github.com/Symmetric/0365560984b32d6ca8b8) a gist with my kubelet log output (from `journalctl -u kubelet`). The pod I'm starting is "demo-busybox".

Is this flag expected to work? `kubelet --help` doesn't mention any other requirements for setting the docker_endpoint, and my reading of the code suggests that this flag should work.

**Comment by vmarmol** [comment]
This sounds like a bug in that the flag is not being respected.

**Comment by thockin** [comment]
I think this is something we should fix for 1.0 - without it, people can not customize their nodes fully (e.g. power strip).

**Comment by vmarmol** [comment]
@Symmetric what requests are you seeing going to the normal socket? Looking at the code I can't see how and your log seems to show all requests failing initially and then recovering and never failing again?

I'll start a setup and report back.

**Comment by vmarmol** [comment]
@Symmetric I made a similar setup:

- Made Docker listen elsewhere
- `socat` on `/var/run/docker.sock`
- Started Kubelet with `--docker_endpoint`

The Kubelet worked as expected and no requests were sent to the socket. Are you able to reproduce the issue? Maybe something else was sending the requests?

**Comment by Symmetric** [comment]
@vmarmol confirmed that this is a false alarm, the packets were being dropped elsewhere in the pipeline.
