### ISSUE TITLE
Change GCE to use standalone SaltStack configuration on each node

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#5112]
For GKE, we have a goal of securing the node -> master communication completely, and eliminating it where we can. Rather than head down the rathole of making sure Salt is secure, I decided to look and see how hard it would be just to convert each VM to a standalone SaltStack configuration, ala: http://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html

It turns out, this that isn't hard at all, and completely eliminates node -> master Salt communication. It also spells doom and gloom for any "dynamic configuration story" using Salt, but I fixed up `kube-push` for GCE in the process as well, at least, so there's that.

**Comment by erictune** [comment]
Is there any plan to make the other salt-based distros to use standalone too?  It is convenient to have them consistent.

**Comment by zmerlynn** [comment]
I have no plans to do this work. If others want to follow, that's awesome.
For now, it's actually not a huge delta, and the change to the Salt mine
was actually meant to be a giant alarm bell on any mine.get action (so it
would be an obvious break ... I think)
