### ISSUE TITLE
 etcd: listen tcp XX.XX.XX.XX:2380: bind: cannot assign requested address

### ISSUE THREAD

**Issue by Jerry-HQG** [GoogleCloudPlatform/kubernetes#5128]
Hi,
I use Kubernetes deployed on multiple ubuntu nodes, when i run "sudo service etcd start", appears the below issue:
`2015/03/06 21:08:39 no data-dir provided, using default data-dir ./infra1.etcd
2015/03/06 21:08:39 etcd: listen tcp XX.XX.XX.XX:2380: bind: cannot assign requested address
`
and when I try to verify if the network setting is correct with running:
`/opt/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'`

it meets the below error:
`Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001`

does anybody know this issue, thanks much!

**Comment by Jerry-HQG** [comment]
issued by GFW

**Comment by tobegit3hub** [comment]
We have the same problem and please list your solution :smiley:

**Comment by horizon365** [comment]
in my case ,i find can't  `ping 127.0.0.1` , so i run `ifconfig lo up` ,it works !

**Comment by horizon365** [comment]
in my case ,i find can't  `ping 127.0.0.1` , so i run `ifconfig lo up` ,it works !
