### ISSUE TITLE
PersistentDisk: one per cloud, or one for all clouds?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#5129]
Currently we have "GCEPersistentDisk", and this name is exposed via the API.  I am working on adding support for AWS EBS, which is very similar to GCEPersistentDisk.

Should I add another type AWSPersistentDisk, or should we try to make GCEPersistentDisk work for any PD/EBS/Cinder style cloud-block device?  (And presumably rename GCEPersistentDisk to CloudPersistentDisk or something similar)

On EC2, EBS volumes are bound to a specific AZ, so I think we'll likely have a "cloud location" specifier even if we have AWSPersistentDisk (cloudLocation: us-west-2b).  I'm thinking if we're going to do that, we might as well have "cloudLocation: aws/us-west-2b", in which case there seems less reason to have the different types.

My personal preference would be to have one PersistentDisk type for all the clouds, to avoid code duplication; it also feels like a simpler API to consume.

**Comment by markturansky** [comment]
Even if you had one PD type for all clouds, you would then need an interface (to work with clouds generically) and implementation (to work with AWS specifically).  IMHO, this is a net gain in complexity, not reduction.

Common mounting utilities recently moved to pkg/util/mount to reduce some of the duplication we saw after introducing NFS and iSCSCI plugins.  Surely there will be other common code that can be refactored to promote reuse, but there still needs to be one volume plugin per provider.

I am doing a lot of work in volumes and Red Hat is producing many types of volume plugins for storage.  Feel free to reach out to me.  I'm happy to work with you.  I'm in the #google-containers IRC channel.

**Comment by bgrant0607** [comment]
I don't want cloud-specific objects (including GCEPersistentDisk) in the API. 

@thockin

**Comment by markturansky** [comment]
@bgrant0607 agreed and understood.  See #5105.

**Comment by thockin** [comment]
Right - the place for cloud-specific PD implementations is in the
persistent-volume structs, not in the volume-source struct (and I'll be
happy to put a bullet in the GCEVolumeSource).

But to the original question, I think we want 1 PD type per implementation,
not one uber-abstractions.

**Comment by justinsb** [comment]
So, to confirm, I am copying-and-pasting "persistentDisk" in VolumeSource of pkg/api/types.go, to "awsPersistentDisk".  And copying-and-pasting GCEPersistentDiskVolumeSource -> AWSPersistentDiskVolumeSource.  For now, API callers will need to know whether they are running on GCE / AWS / OpenStack / VMWare / Azure, and populate the correct field.

#5105 (when it lands) will then refactor this and replace persistentDisk / awsPersistentDisk / nfs with a single PersistentVolume type, so users will not have to know what type of cloud they're running on.

Is that correct?

**Comment by markturansky** [comment]
Cut/Paste "persistentDisk" and refactor to suit the AWS provider.  This provides the volume to Kubernetes.  

The struct pointer can go in either/both VolumeSource and PersistentVolumeSource.  The former allows pod authors to use it directly to access a known EBS volume.  The latter makes it a provisionable resource by a cluster admin.

**Comment by markturansky** [comment]
After copying from GCE, you'll want to change your volumes GetAccessModes method.  EBS only supports ReadWriteOnce, I believe, while GCE has two modes (adds ReadOnlyMany).

**Comment by thockin** [comment]
clone and customize, but yes :)

**Comment by justinsb** [comment]
We've implemented the "one per cloud" API model, so closing.

**Comment by bgrant0607** [comment]
PersistentVolumeClaim is the "one for all clouds" abstraction.

PersistentVolumeSource is "one per cloud" currently, but eventually we'd like to convert it to a plugin.
