### ISSUE TITLE
Question about portal nat'ing

### ISSUE THREAD

**Issue by brenton** [GoogleCloudPlatform/kubernetes#5133]
It seems that if something drops the kubernetes nat'ing rules nothing will trigger it to be automatically rebuilt.  Is that true?

If so, is there a way to tell the kube proxy to rebuild the nat rules?

**Comment by mikedanese** [comment]
The proxy sync loop should ensure that the portals rules are open every five seconds. Deleteing and recreating a service, or restarting kube-proxy would trigger a rsync of the rules. Are you observing that this is not the case?

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/proxier.go#L363

**Comment by brenton** [comment]
Something defintely appears to be wrong with my OpenShift environment (we embed a fairly recent version of kubernetes).

Anyway, thanks for pointing me to the code.  I see the "Periodic sync" log messages firing in my environment roughly every 30 seconds.  I'll probably add some more debugging in my environment to make sure it's functioning the same as standalone kubernetes.
