### ISSUE TITLE
Add README.md to limit range and resource quota examples

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#5149]
Since #5142 will enable the plug-ins on all salt based providers, I need to author a README to document how each example is used.

Open issue to track

**Comment by derekwaynecarr** [comment]
I will look to augment the examples derived from document here:

https://github.com/openshift/origin/pull/2039

**Comment by derekwaynecarr** [comment]
The documentation for resource quota example is updated in this PR:
https://github.com/GoogleCloudPlatform/kubernetes/pull/9096

**Comment by bgrant0607** [comment]
@derekwaynecarr can this be closed?

**Comment by derekwaynecarr** [comment]
When #9264 merges this will close automatically.
