### ISSUE TITLE
kubectl create -f service almost always times out

### ISSUE THREAD

**Issue by thompsonja** [GoogleCloudPlatform/kubernetes#5156]
I'm trying to bring up a service and pod (https://github.com/youtube/vitess/examples/kubernetes/vtctld-up.sh).  The service has createExternalLoadBalancer: true.  The call nearly always returns:
ERROR: F0306 15:59:47.443762   17632 create.go:81] Timeout: request did not complete within allowed duration.

I then proceed to create a firewall rule (created successfully) and access the service, which occasionally works.  Note the non-determinism:
1. I nearly always get the timeout error (> 90%).
2. Even if I get the timeout error, I can still create the firewall rule and it's a toss-up whether I can access the service or not.
3. If I automate these steps in a script (bring up cluster, bring up service, create firewall rule), I am virtually never able to access the service using the forwarded IP and port.

Our thoughts are that adding the external load balancer makes bringing up the service take longer, putting it at risk of timeout.  I couldn't find a way to increase the timeout threshold in kubectl create.

In addition there may be some hidden steps or waits between steps that are needed since the automation never works, but running the steps manually sometimes does.

Also of note is that this seems to be new behavior.  Prior to 3/5/2015, I hadn't seen any issues (if the timeout error occurred, it didn't have any impact), automation worked completely fine.

**Comment by smarterclayton** [comment]
More evidence why we need to separate portalIP and external load balancer allocation from synchronous create.

**Comment by satnam6502** [comment]
I can't follow https://github.com/youtube/vitess/examples/kubernetes/vtctld-up.sh
I assume this is for GCE?

**Comment by thompsonja** [comment]
Apologies, yes this is for GCE.  I've been automating the steps outlined here:
https://github.com/youtube/vitess/blob/master/examples/kubernetes/README.md

**Comment by bgrant0607** [comment]
@smarterclayton I agree. They need to be moved to the async model, similar to scheduling. The Service would start in Pending. ServiceStatus needs a ServicePhase.

**Comment by bgrant0607** [comment]
@smarterclayton Did you say you (or someone on the RH side) were working on this?

**Comment by quinton-hoole** [comment]
If not, I can take a look at it now.

**Comment by smarterclayton** [comment]
It was me but I won't get to it anytime soon.  Please do

----- Original Message -----

**Comment by quinton-hoole** [comment]
Looks like @brendandburns jumped on it on #5180

**Comment by a-robinson** [comment]
Closing in favor of #5180.
