### ISSUE TITLE
Apiserver receives unsupported field label

### ISSUE THREAD

**Issue by kazegusuri** [GoogleCloudPlatform/kubernetes#5168]
Apiserver continuously logs following errors in current HEAD.
```
errors.go:66] apiserver received an error that is not an api.Status: field label not supported: Status.Host
```

This is caused by receiving a request like `/api/v1beta1/pods?fields=Status.Host%3D172.17.8.102&namespace=` from kubelet. And it is fixed by just adding `Status.Host` case [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/conversion.go#L1336), but I'm not sure that's right.

**Comment by nikhiljindal** [comment]
This is because the v1beta1 version of Pod (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/types.go#L510) does not have a Status field.
You should use DesiredState.Host instead of using Status.Host in the URL.

**Comment by nikhiljindal** [comment]
Dup of https://github.com/GoogleCloudPlatform/kubernetes/issues/5202
