### ISSUE TITLE
namespace design seems out of date

### ISSUE THREAD

**Issue by xudifsd** [GoogleCloudPlatform/kubernetes#5172]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/namespaces.md haven't update for a long time, and it even using `kubecfg`, the usage of `kubectl`, shows namespace is SUPERCEDED. Maybe you should update the doc.

**Comment by derekwaynecarr** [comment]
I am working on updated docs

**Comment by thockin** [comment]
We need to make a policy - do we update design docs, or are they historical
artifacts that should be replaced by "real" docs that are kept up to date?

**Comment by derekwaynecarr** [comment]
Agree, but in this case, I have updates to the design doc to capture delete semantics.

**Comment by smarterclayton** [comment]
The audience for a design doc and regular doc may not be the same.  Agree we should be transforming proposals into more concrete documents that describe the underlying intent, the targeted use cases, alternatives considered, etc.  That's "historical" but still relevant.

**Comment by derekwaynecarr** [comment]
Updates to design are here: https://github.com/GoogleCloudPlatform/kubernetes/pull/5195

**Comment by derekwaynecarr** [comment]
Updates were made.

**Comment by xudifsd** [comment]
@derekwaynecarr thank you
