### ISSUE TITLE
Daylight savings time change broke node controller

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#5183]
After the DST change:

```
E0309 15:39:48.081198   25506 nodecontroller.go:213] error updating node openshiftdev.local: minion "openshiftdev.local" is invalid: metadata.creationTimestamp: invalid value '2015-03-08 18:27:34 -0400 -0400': field is immutable
E0309 15:39:58.170146   25506 nodecontroller.go:244] Can't get ip address of node claytons-macbook-pro.local: lookup claytons-macbook-pro.local: no such host
E0309 15:39:58.173485   25506 nodecontroller.go:213] error updating node claytons-macbook-pro.local: minion "claytons-macbook-pro.local" is invalid: metadata.creationTimestamp: invalid value '2015-03-08 20:25:50 -0400 -0400': field is immutable
```

We should be ignoring creationTimestamp on update.

**Comment by bgrant0607** [comment]
@smarterclayton Could you please explain the cause of the failure in more detail? Do we not normalize the timezone in the representation used in the API?

**Comment by smarterclayton** [comment]
When we serialize to JSON we are using a value that has a timezone embedded in it (time.Time).  As a result the representation changed.  We should normalize it as well during serialization, but in general creationTimestamp should not prevent an update since it can safely be ignored.

**Comment by bgrant0607** [comment]
I think we should allow creationTimestamp to be empty and also convert time to UTC() before marshaling.

**Comment by bgrant0607** [comment]
More specifically:

We'd also want to change:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/time.go#L92
to
```
	return json.Marshal(t.UTC().Format(time.RFC3339))
```
and
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/time.go#L81
to
```
	t.Time = pt.UTC()
```

**Comment by smarterclayton** [comment]
Makes sense to me - clients should always control their timezone and with distributed masters you might see different values.

----- Original Message -----

**Comment by smarterclayton** [comment]
I'll own the follow up on this.

----- Original Message -----

**Comment by liggitt** [comment]
+1 for UTC serialization

**Comment by smarterclayton** [comment]
Opened #5416 to marshal to utc when serializing
