### ISSUE TITLE
Missing service environment variables while starting pod

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/kubernetes#5184]
While debugging #5091 I noticed that when I'm creating guestbook application by running `./cluster/kubectl.sh create -f examples/guestbook` there is a chance that frontend pods come up before information about environment variables of redis is propagated. In such case frontend can't connect to database during its whole life.

It's actually more general problem, since most of complex application might be affected by this. Also I think create a set of resource (especially by specifying the directory of their config files) should just work no matter of the order of creation.

I can see few solutions of such problem:
1. Get rid off HOST:PORT stuff and start using DNS service instead.
2. Add ability to wait for such information being propagated.
3. Injecting environment variables to container somehow(?).

**Comment by piosz** [comment]
@brendanburns @bgrant0607 @thockin Any comments?

There is a new example [k8petstore](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/k8petstore) added by @jayunit100 which uses HOST:PORT environment.

**Comment by bgrant0607** [comment]
Known problem: #1768, #4245.

Even if we ensured the services were created first (which is a hack that might actually work pretty well), I'm not entirely sure that's sufficient to absolutely guarantee the Kubelet will see the services before it sees new pods that depend on them.

I would eventually like to get rid of the environment variables, but changing to DNS won't entirely eliminate the need for sequencing/dependencies in legacy apps.

Let's discuss further on #4245.

**Comment by erictune** [comment]
Crash and restart until you get your service env vars.

**Comment by piosz** [comment]
I don't agree with you Eric. It would be problematic for users to handle the case in each application they are using. The internal cluster problems should not be visible for the users.

Moreover relying on IPs is actually not the best idea since IPs are rather temporary than permanent. The user don't want to watch env variable for changes. For example the issue #4914 was caused by changed IP.

**Comment by bgrant0607** [comment]
Closing this as a duplicate.
