### ISSUE TITLE
Validate ips of a node 

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#5188]
Since we append hostips to the list on every node controller run invocation which happens at 10s intervals, this list grows pretty large pretty soon: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L111 

Maybe:
```
type NodeAddress string
map[NodeAddresses]NodeAddressTypes
```

would still satisfy the requirements? 
@ddysher

**Comment by ddysher** [comment]
Fix is here #5116

I think we generally use list instead of map

**Comment by lavalamp** [comment]
This could have been P1, but I just merged a fix so I'll leave at P2.

Remaining work to do:
* Add to validation something that limits the number of IP addresses. (and maybe checks dups?)

**Comment by ddysher** [comment]
Yeah, I'll add validation later.
