### ISSUE TITLE
CoreOS instructions for GCE don't say how to connect to master 

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5191]
Tried out
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md
with GCE.
It doesn't say how you should connect to your master with kubectl.

For AWS, it appears that one would run kubectl on one's desktop and it would be able to communicate  to the master over the VPC because of the VPC rules.  There is no equivalent instructions for GCE.

Maybe someone familiar with GCE networking can add some.

**Comment by alex-mohr** [comment]
Looks like https://github.com/GoogleCloudPlatform/kubernetes/pull/5204 fixed?  Please reopen if not!  And thanks Eric!
