### ISSUE TITLE
Be consistent with the case for field selectors

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#5206]
We use capitals for Pod fields (ex: Status.Host) and camelCase for Event fields (ex: involvedObject.resourceVersion).

We should be consistent.
Should it be capitals? camelCase? Or should we be case insensitive?

@lavalamp @bgrant0607

**Comment by lavalamp** [comment]
IMO, we should use camelCase for pod fields, to match the way it's serialized in JSON.

**Comment by bgrant0607** [comment]
I agree with @lavalamp. The goal here is to be consistent with the API, not with the internal Go representation.

**Comment by bgrant0607** [comment]
I'd like to fix this before v1beta3 is cast in stone.

**Comment by nikhiljindal** [comment]
ok. Event field selectors are correct then.
I will update the selectors for pods to make them camelCase.

**Comment by nikhiljindal** [comment]
I am wondering if I should change this only for v1beta3 or for 1 and 2 as well?
This will be a breaking change for beta1 and 2 if we decide to do that.

**Comment by bgrant0607** [comment]
v1beta3 only, though that's hard, we should reconsider. We're contemplating another "breakage day", and I doubt this is widely used.
