### ISSUE TITLE
AWS ELB uses DNS names, can't return an IP from CreateTCPLoadBalancer

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#5224]
AWS ELB produces an external endpoint which is not an IP address, but is instead a DNS name (e.g. myLB-1234567890.us-east-1.elb.amazonaws.com); more info here http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/using-domain-names-with-elb.html

This is because (under the covers) ELB assigns multiple IP addresses, and it changes the IP addresses dynamically (e.g. in response to load).

Users must then either cname the name (which doesn't work for the apex, so www.foo.com is OK, foo.com is not).  Or they can move their domain to Route53, which is ELB aware.

To make AWS ELB work, I think we have two choices:

1) We could change the return type of CreateTCPLoadBalancer from (net.IP, error) to (string, error).  string would either be an IP address or a hostname.  We could do something strongly typed, but I don't think this is necessary.

2) We could change things around so that we manage DNS as well, so that Kubernetes makes the mapping completely automatic.

Option 2 is a huge change, so I'm going to explore option 1 first.

**Comment by benmccann** [comment]
@justinsb looks like you implemented option #1 in https://github.com/GoogleCloudPlatform/kubernetes/pull/5228. should we close this issue now?

**Comment by justinsb** [comment]
Yes, I believe this is fully implemented now (although we haven't merged ELB support itself quite yet).  Closing - thanks!
