### ISSUE TITLE
Nodes showing ready despite SSL errors

### ISSUE THREAD

**Issue by sdodson** [GoogleCloudPlatform/kubernetes#5250]
A node shows as ready as long as /healthz returns a 200, however if I've done something like rebuild my certificate store and I haven't propagated the new CA to the node it cannot reach the API and should not be marked as ready.

I imagine /healthz should not return a 200 if a node is unable to reach the master.

**Comment by dchen1107** [comment]
cc/ @ddysher

**Comment by bgrant0607** [comment]
@sdodson You suspect master-to-node communication should be broken, node-to-master communication should be broken, or both?

We're in the process of making Kubelet post node status to the master: #4562, #5265. In your scenario, the update should fail, which would cause the Node Controller to update readiness accordingly. 

Closing this as a dupe.

**Comment by sdodson** [comment]
node-to-master was definitely broken as the node was spewing invalid CA errors.

I suspect master-to-node was as well but I don't understand k8s well enough to know when the master connects to a node other than to fetch kubelet's healthz.

I'll watch the two referenced issues, thanks.
