### ISSUE TITLE
Add k8PetStore load generator application.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#5260]
We now have ported the Apache BigTop data generator to work as an independent container, in an architecture which leverages guestbook's redis k/v sink, and visualizes throughput in a web app. 

As per
https://groups.google.com/forum/#!topic/google-containers/cRe7Wo6xFr0

The work done will be:

- The original Dockerfiles + content for all images
- An e2e test that validates that it is working
- The documentation itself (obviously)

**Comment by timothysc** [comment]
@satnam6502 here is your soak test.

@dchen1107 during testing we brought down etcd via the other bug reported.

**Comment by satnam6502** [comment]
+1

**Comment by timothysc** [comment]
exposed - https://github.com/GoogleCloudPlatform/kubernetes/issues/5290

**Comment by jayunit100** [comment]
https://github.com/jayunit100/bigtop/commit/be48aa96647603d299f3f753678781201319b06d I've now merged the load generators into upstream.  Attaching PR tonight of an initial implementation.  Here is a screenshot of the dashboard . 
![screen shot 2015-03-11 at 10 38 58 am](https://cloud.githubusercontent.com/assets/826111/6604156/0091d88a-c7fd-11e4-983a-c414e92220cd.jpg)

**Comment by jayunit100** [comment]
The PR for this is now available....  https://github.com/GoogleCloudPlatform/kubernetes/pull/5447

**Comment by jayunit100** [comment]
Okay closing, as per #5447 being merged ...   The app can now be run from here https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/k8petstore ....  ill iterate on it some more shortly, but for now it will graph throughput and can be used to create heavy load and visualize plateaus, and so on
