### ISSUE TITLE
Support multiple kinds on kubectl command line

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#5277]
Forked from #3233.

We should support multiple kinds of objects on a single command line, such as by using URL suffixes. For instance:
```
kubectl describe replicationcontrollers/foo services/foo-service
```

**Comment by bgrant0607** [comment]
I think this is mostly done (though perhaps not for describe #5905). @smarterclayton ?

**Comment by smarterclayton** [comment]
I need to do describe and make sure the remaining commands switch to resource builder.

**Comment by andronat** [comment]
Is this still open?

**Comment by bgrant0607** [comment]
Looks like #6571 should have fixed it.
