### ISSUE TITLE
apiserver crash from build on 2015-03-11

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#5290]
initial trace on panic
--------------------------

Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/master/pod_cache.go:268 +0x71
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: github.com/GoogleCloudPlatform/kubernetes/pkg/master.func·004()
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/master/pod_cache.go:163 +0x5a
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: github.com/GoogleCloudPlatform/kubernetes/pkg/master.(*PodCache).updatePodStatus(0xc20801b6d0, 0xc2083eace8, 0x0, 0x0)
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/master/pod_cache.go:208 +0x7ae
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: github.com/GoogleCloudPlatform/kubernetes/pkg/master.(*PodCache).computePodStatus(0xc20801b6d0, 0xc2083eace8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/kubelet.go:114 +0x2dd
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: github.com/GoogleCloudPlatform/kubernetes/pkg/client.(*HTTPKubeletClient).GetPodStatus(0xc208130700, 0xc208600400, 0x34, 0xc2085518a0, 0x7, 0xc208551830, 0xd, 0x0, 0x0, 0x0, ...)
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: runtime.panic(0xc19660, 0x15e68b3)
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: goroutine 95 [running]:
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: [signal 0xb code=0x1 addr=0x10 pc=0x5a53fd]
Mar 11 14:42:36 host18-rack11.fqdn kube-apiserver[17661]: panic: runtime error: invalid memory address or nil pointer dereference

**Comment by eparis** [comment]
@aveshagarwal  can you take a look?

**Comment by aveshagarwal** [comment]
Sure

**Comment by eparis** [comment]
the whole file is gone, the problem was temporary.

**Comment by timothysc** [comment]
Temporary transient issue..  Closing now, will reopen if seen again.
