### ISSUE TITLE
Typo in contrib/init/systemd/environ/kubelet

### ISSUE THREAD

**Issue by cnaize** [GoogleCloudPlatform/kubernetes#5300]
Where is a typo in contrib/init/systemd/environ/kubelet.
`KUBELET_API_SERVER="--api_server=127.0.0.1:8080"`
should be
`KUBELET_API_SERVER="--api_servers=127.0.0.1:8080"`
otherwise
`No api server defined - no events will be sent.`

**Comment by eparis** [comment]
fixed in #5307
