### ISSUE TITLE
watch of *api.Pod ended with error: very short watch

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#5311]
From https://groups.google.com/forum/#!topic/google-containers/Icdzt0iWTik

> Yesterday all worked fine. Today i tried to get minions list by "systemctl status scheduler" and got this error:

> Mar 11 14:03:16 coreos-1 systemd[1]: scheduler.service: main process exited, code=exited, > status=2/INVALIDARGUMENT
> Mar 11 14:03:16 coreos-1 systemd[1]: Unit scheduler.service entered failed state.
> Mar 11 14:03:16 coreos-1 systemd[1]: scheduler.service failed.
> Mar 11 14:03:16 coreos-1 systemd[1]: Starting Kubernetes Scheduler...
> Mar 11 14:03:16 coreos-1 systemd[1]: Started Kubernetes Scheduler.
> Mar 11 14:08:16 coreos-1 kube-scheduler[4659]: E0311 14:08:16.808349    4659 reflector.go:118] > watch of *api.Service ended with error: very short watch
> Mar 11 14:08:16 coreos-1 kube-scheduler[4659]: E0311 14:08:16.811434    4659 reflector.go:118] > watch of *api.Pod ended with error: unexpected end of JSON input
> Mar 11 14:08:16 coreos-1 kube-scheduler[4659]: E0311 14:08:16.847595    4659 reflector.go:118] > watch of *api.Pod ended with error: unexpected end of JSON input

> What does it mean? And how can i fix this?

**Comment by nikhiljindal** [comment]
The error seems to be from here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/cache/reflector.go#L213

**Comment by lavalamp** [comment]
It means apiserver accepted the watch request but then immediately terminated the connection.

If you see it occasionally, it implies a transient error and is not alarming. If you see it repeatedly, it implies that apiserver (or etcd) is sick.

**Comment by Suvitruf** [comment]
I have same error. But 'systemctl status' said that apiserver works fine.

I asked it here https://groups.google.com/forum/#!topic/google-containers/Icdzt0iWTik

But still don't understand how can i fix etcd (if it's etcd fault actually).

**Comment by lavalamp** [comment]
Sorry I missed your last comment. Unless you see this message very frequently, I don't think there's actually anything wrong.
