### ISSUE TITLE
apiserver doesn't restart if it crashes

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#5312]
When you step on a bug like #5301, it crashes and doesn't restart. I expect this will be fixed when we start running master components in pods on kubelet, but it seems worth documenting.

**Comment by lavalamp** [comment]
I think @ArtfulCoder is already working on putting master components in pods?

**Comment by ArtfulCoder** [comment]
Yes, I am working on putting apiserver in a pod.

**Comment by wojtek-t** [comment]
@ArtfulCoder @lavalamp I think this was fixed by #6785 - can we close it now?

**Comment by dchen1107** [comment]
Yes, it works.
