### ISSUE TITLE
pkg/proxy/proxier_test.go crash on OSX

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5317]
pkg/proxy/proxier_test.go crashes on macos

ChooseHostInterface() returns an error and so NewProxier is nil, so stuff crashes.

**Comment by erictune** [comment]
`E0311 13:09:27.857647   90434 proxier.go:324] Failed to select a host interface: open /proc/net/route: no such file or directory`

**Comment by erictune** [comment]
There is no such thing as /proc on OSX.

I'd like it if unit tests worked on OSX.

**Comment by erictune** [comment]
Ideally, unit tests would not interact with actual OS files like this.  Maybe interface needs to be an arg to NewProxier.

**Comment by thockin** [comment]
@sub-mod tests should not be accessing /proc directly - must have missed that case.  Can you take a look?  I'm not immediately sure what the right fix is.

AFAIK there is no way tepo tell whether your code was built into a test or a real bin.

**Comment by sub-mod** [comment]
@erictune do you run kube on Mac ? or do you just build it and run it in Linux ?
@thockin the util_test is not accessing it.It is the proxier_test. Will change proxier_test.go

**Comment by erictune** [comment]
I run unit and integration tests directly on Mac.

**Comment by markturansky** [comment]
@sub-mod I run kube and the unit tests on OS X, if I can be of help. 

I've since updated from master and this is failing for me, too :)

**Comment by sub-mod** [comment]
@erictune @markturansky first of all apologies i didnot know about folks using mac.
I am just pushing my fix , pls wait. I ofcourse would need ur help

**Comment by markturansky** [comment]
@sub-mod I will test it for you.  Ping me here or on IRC.

**Comment by sub-mod** [comment]
@markturansky 5400 has my fix , can u kindly check

**Comment by sub-mod** [comment]
@erictune i this is now fixed with 5400 . @markturansky  kindly confirm here to close this thread.

**Comment by markturansky** [comment]
This issue can be closed.
