### ISSUE TITLE
0.0.0.0 and 127.0.0.1 should be rejected as a  publicIP fields for kube services.   

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#5319]
When spinning up VMs w/ kube, I attempted to use `publicIPs=["0.0.0.0"]` but this fails.

ironically, 127.0.0.1 succeeds (internally you can then access a kube service via `curl 127.0.0.1:3000`, for example, but you *cannot* do this if you try to bind to 0.0.0.0.

- binding works to 127.0.0.1, but is a horrible idea (since this IP wont be reachable by the outside world), so in that case kube should print a clear message on *why* this is the case and fail. 
- binding to 0.0.0.0 fails right out of the bat, so in this case, also, kube should fail immediately.

To be clear, im suggesting that these should fail at the service submission layer.

Possibly a module for validating logic of submitted services/pods , which extends syntactical validation is in order if one doesn't already exist?

**Comment by fgrzadkowski** [comment]
Please also see #4897

**Comment by fgrzadkowski** [comment]
Since this is very similar to #4897 I'm gonna take this.
