### ISSUE TITLE
Not able to set readyOnly to true for persistent disk, wherever the config is placed.

### ISSUE THREAD

**Issue by ifuller1** [GoogleCloudPlatform/kubernetes#5326]
Hi Guys,

See valid config here: http://pastebin.com/raw.php?i=8GeV4jrD (I redacted my image / drives)

With replicas set to 1 this works, greater than 1 I get the following error:

```
ERROR: F0311 19:31:00.973206   42192 create.go:78] ReplicationController "node-master-controller" is invalid: spec.template.spec.volumes.GCEPersistentDisk.ReadOnly: invalid value 'false': ReadOnly must be true for replicated pods > 1, as GCE PD can only be mounted on multiple machines if it is read-only.
```

The pastebin has several incorrectly placed readOnly flags but no matter where I place them I still get this error.

Thanks,

Ian

**Comment by vmarmol** [comment]
Assigning to myself since I started to take a look. Thanks for reporting @ifuller1!

**Comment by vmarmol** [comment]
@ifuller1 I am sad to report that the problem is a typo. It seems like you're using "readyOnly" instead of "readOnly". I can't believe it took us this long to notice :P once the typo is fixed all works as expected

**Comment by vmarmol** [comment]
Closing this issue, but feel free to open new issues if you run into any trouble.

Sorry it took so long to find a relatively simple problem. I +1'd #3338 which looks to improve the experience when this type of error occurs.

**Comment by ifuller1** [comment]
Right. Can we remove this issue from the internet...
