### ISSUE TITLE
Event logging should show one up the callstack

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5328]
`I0311 14:09:35.984662   99741 event.go:138] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"test", Name:"nginx-controller-133ol", UID:"ebe57781-c832-11e4-b233-b8f6b11c8883", APIVersion:"v1beta1", ResourceVersion:"", FieldPath:""}): reason: 'hostPortConflict' Cannot start the pod due to host port conflict.`

This would be more useful if it showed the file/line of the caller.

**Comment by dchen1107** [comment]
@quinton-hoole Do you want to take a look at this?

**Comment by quinton-hoole** [comment]
Sure, will do.

**Comment by quinton-hoole** [comment]
@erictune Probably a dumb question, but you're presumably not wanting the caller of the function at event.go:138

https://github.com/GoogleCloudPlatform/kubernetes/blob/99a5ab4cfac971b44ae6e6a401e2507973c93f43/pkg/client/record/event.go#L138

 ... but rather the creator of the event being logged?  i.e. in your example, the code that's whining about the host port conflict, namely this?

https://github.com/GoogleCloudPlatform/kubernetes/blob/ce7658a302efc35d66fbc0ab4ac8e597773c9b3a/pkg/kubelet/kubelet.go#L1671

**Comment by quinton-hoole** [comment]
If so, I wonder how useful this really is, given how easy it is to search the source code for the event message (as I did above)?  Either way, this sounds like a P3?

**Comment by erictune** [comment]
This is a one line change if you use
http://godoc.org/github.com/golang/glog#InfoDepth

**Comment by quinton-hoole** [comment]
I don't think that works, given that event.go#L138 and kubelet.go#L1671 are in different go routines, on opposite ends of a channel.  I suspect that the creator of the event will have to jam it's code location into the event object.

**Comment by erictune** [comment]
You are quite right.
