### ISSUE TITLE
Predeclared network for k8s cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#5329]
@davidopp @roberthbailey 

During talks with a potential client we've noticed a pretty common scenario that we do not support properly. If a client has some services outside of GCE (e.g. in a private datacenter) and some running on k8s cluster he'd want to have all of them discoverable. This can be achieved using VPN. The problematic part is that k8s cluster (on GCE and GKE) chooses a random subnet of 10.0.0.0 to be used for pods/services. That makes it pretty hard to preconfigure VPN and make sure there are no conflicts between GCE and private/other datacenter.

A simple solution would be to allow a user to specify a subnetwork that k8s cluster should use. From a brief discussion with @roberthbailey this should pretty easy to do using current APIs.

**Comment by zmerlynn** [comment]
This is actually more or less doable today using the GCE startup scripts, and slightly trickier on GKE, but all the pieces are there.

**Comment by roberthbailey** [comment]
To be clear, the GCE startup scripts don't choose a random subnet -- it's specified via environment variable (and fixed for all clusters unless you know how to tweak it). 

For GKE, we allow a user to launch more than one cluster in a project & network by selecting a /14 that doesn't overlap with any of the existing routes in the project. Right now we return this /14 to the customer, but it wouldn't be too difficult to allow the customer to request a specific subnet to use for their cluster.

/cc @cjcullen

**Comment by eparis** [comment]
@mrunalp @rajatchopra I know you two are working on a more sane networking model which would hopefully some day work on these 2 platforms and want to make sure you see any discusison here.

**Comment by mrunalp** [comment]
@eparis The bridging between private / public cloud is a good use case for isolated networks, so different clients can use whatever subnets that they want in the public cloud without worrying about their requested subnets overlapping with each other.

**Comment by davidopp** [comment]
@mrunalp Can you explain? It seems to me that the simplest model for bridging private/public clouds is to put them in the same address space and make everything routable between the two. This makes it easy, for example, to contact a service or pod running in an on-prem cluster from a cloud datacenter, or vice-versa. It's painful to have to set up an ExternalLoadBalancer for every service (or, worse, pod) that you want to be visible across the divide.

**Comment by alex-mohr** [comment]
Since OSS k8s supports this via (admittedly nasty?) util.sh environment variable, I've filed a separate GKE bug to track customer-supplied subnets.

Presumably https://github.com/GoogleCloudPlatform/kubernetes/issues/5472 will make OSS better too.

**Comment by chaten** [comment]
We have a VPN tunnel from AWS to GCP on a 10.0.0.0 subnet. We cannot use GKE as it is possible that it will conflict with our subnets inside of AWS. This makes it very difficult to migrate to GCP.

**Comment by alex-mohr** [comment]
@cjcullen owns the GKE network provisioning bits.  And we want to get those upstreamed to OSS Kubernetes too.

Some ideas re: avoiding @chaten's VPN conflict:
* Look at existing routes (including VPNs) as part of auto-allocation
* Add support for a whitelist (or blacklist?) of IP ranges that GKE uses (or avoids) -- perhaps via a metadata field if we can't get first-class GCE networking support for it in the short term.
* Allow users to specify an IP range as part of cluster creation.

**Comment by roberthbailey** [comment]
@alex-mohr for OSS kubernetes you can already specify the cluster CIDR as part of cluster creation. We should do the same thing for GKE since it isn't too difficult.

**Comment by roberthbailey** [comment]
If you update to today's gcloud release there's a new command line flag that allows you to pick a CIDR when creating a GKE cluster.
