### ISSUE TITLE
Just erase host but don't fail pod

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5334]
@brendandburns pointed out that it is a bad user experience to show a pod as failed if it never actually started (due to HostPort conflict).  He asked if kubelet could just clear Host so that it always shows as pending.

@yujuhong can this work?

@bgrant0607 are you okay with a Pod being bound to host A, never starting, and then being bound to host B, and then starting (same UID).  Phase transition diagram is still acyclic.

**Comment by erictune** [comment]
Never mind, this is not easy because kubelet cannot modify the Spec.

**Comment by erictune** [comment]
@lavalamp

**Comment by dchen1107** [comment]
If reset Pod phase to pending, how upstream layer will determine it is pending due to pull images? or pending due ot port conflicts?

**Comment by bgrant0607** [comment]
@erictune No, I'm not ok with it. Marking the pod as failed is the right thing to do. Pods can fail at any time for any reason -- hostport conflict, out of disk, out of memory, out of cpu, broken dockercfg, ... If users want to ensure success, they need a controller. If we need a solution for RestartOnFailure pods, we should build a job controller already. Pods are a system primitive. Users shouldn't create them directly unless they know what they are doing.

Besides, almost nobody should be using host ports, and I thought we claimed that this kind of conflict shouldn't happen in practice.
