### ISSUE TITLE
Scheduler to optimistically use binding info

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5336]
The scheduler binds a pod A to machine M.
Then it tries pod B to machine M.
In trying this second binding, it uses stale information about A, in particular, that it is not yet bound to a machine.  
Sometime later, it "learns" about A being bound to M via watch.

It should assume all bindings it makes happen so as to avoid conflicts.

It will be very common for the scheduler to miss hostPort conflicts once I remove the check.

Also, spreading will work poorly.  It may put A and B on same machine.

(Note that optimism is bad for anti-conflicts, but we don't have those I think).

**Comment by erictune** [comment]
@lavalamp

**Comment by lavalamp** [comment]
I am working on this. Hope to have something out tomorrow.

**Comment by bgrant0607** [comment]
+1 to this change.
