### ISSUE TITLE
Pod doesn't get rescheduled when node dies

### ISSUE THREAD

**Issue by ravigadde** [GoogleCloudPlatform/kubernetes#5340]
I created a pod with replication controller (1 replica). The node on which the pod was scheduled died after sometime. Pod transitions to Unknown state and doesn't get scheduled on to another healthy node.

**Comment by dchen1107** [comment]
cc/ @ddysher

**Comment by ddysher** [comment]
Can I ask which version are you using, and how long have you waited?  k8s wait a few minutes before reschedule.

**Comment by bgrant0607** [comment]
5 minutes, specifically. It's changeable by flag on the node controller.

**Comment by ravigadde** [comment]
@ddysher @bgrant0607 

Yes I am on older code which doesn't have pod eviction support. I am curious though why SyncNodeStatus and EvictTimedOutPods are mutually exclusive. Does EvictTimedOutPods rely on health registry being enabled in apiserver to update the node status?

**Comment by ddysher** [comment]
SyncNodeStatus will do node status update as well as pod eviction.   We are changing our model to kubelet posting node status now, so we want to disable node status sync but still keep pod eviction.

**Comment by ravigadde** [comment]
@ddysher 

Thanks for your response. I will try out the latest code. Closing this issue also.

**Comment by purpleidea** [comment]
It would be great to have an example of how to set this. I'm assuming you have to add it somewhere in the metadata.json file, but building those is still a mystery!

**Comment by ddysher** [comment]
@purpleidea Do you want to set pod eviction timeout? It's a flag in controller manager.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/man/kube-controller-manager.1.md
We should probably mention it in node.md or pod.md...

**Comment by purpleidea** [comment]
@ddysher I suppose... Is that what I want?
If I have two pods on machine2, and i shutdown machine2, what is it that will cause them to start running on machine3?

**Comment by bprashanth** [comment]
@purpleidea the scheduler should do that for you, you're probably hitting https://github.com/GoogleCloudPlatform/kubernetes/issues/7222

**Comment by ravigadde** [comment]
@purpleidea 

Currently that only happens if you deployed your pods with a replication controller.

**Comment by purpleidea** [comment]
Ah, well I'm not quite an expert in this area yet, but here's some more information...

I'm the primary author on a development environment called Oh-My-Vagrant [1], which just recently added kubernetes support. I just today made a screencast and blogged about that integration point [2].

As an initial "kickstart" for new developers, I've provided an extremely simplistic "simple app" [3] (much simpler than the guestbook).

I suspect new users might hit some of these issues, so if there are fixes that I can incorporate into these projects, please let me know (or send patches) and in any case, thank you for your time.

[1] https://github.com/purpleidea/oh-my-vagrant
[2] https://ttboj.wordpress.com/2015/05/02/kubernetes-clusters-with-oh-my-vagrant/
[3] https://github.com/purpleidea/kube-simple1

**Comment by purpleidea** [comment]
@bprashanth I'm not sure, but thanks for the reference.

@ravigadde Perhaps I didn't set up the app.json file correctly, but I thought I had. ( https://github.com/purpleidea/kube-simple1 )

(Please see my previous comment.)

Thanks!
