### ISSUE TITLE
nodeInfo errors spamming kubelet.log

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#5354]
The log file is drowned in nodeInfo check failures. This can be easily reproduced by starting a local cluster and check kubelet.log. Since I only started seeing this today, the suspects are by PRs merged today or the day before.

```
I0311 19:03:57.016589    7689 server.go:675] GET /healthz: (476.722µs) 0 [[Go 1.1 package http] 127.0.0.1:43613]
I0311 19:03:57.017150    7689 server.go:139] HTTP InternalServerError: Internal Error: unable to get "machine info" from "http://127.0.0.1:4194/api/v1.2/machine": Get http://127.0.0.1:4194/api/v1.2/machine: dial tcp 127.0.0.1:4194: connection refused
I0311 19:03:57.017228    7689 server.go:675] GET /api/v1beta1/nodeInfo: (301.169µs) 500
goroutine 59 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20822c8a0, 0x1f4)
        /snp/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fdbe26691e8, 0xc20822c8a0, 0xc208256180, 0xb3, 0x1f4)
        /usr/local/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc208224080, 0x7fdbe26691e8, 0xc20822c8a0, 0x7fdbe264aac0, 0xc2080b4a50)
        /snp/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:140 +0x213
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleNodeInfoVersioned(0xc208224080, 0x7fdbe26691e8, 0xc20822c8a0, 0xc208210340)
        /snp/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:351 +0x87
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleNodeInfoVersioned)·fm(0x7fdbe26691e8, 0xc20822c8a0, 0xc208210340)
        /snp/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:119 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20821c110, 0x7fdbe26691e8, 0xc20822c8a0, 0xc208210340)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2082280c0, 0x7fdbe26691e8, 0xc20822c8a0, 0xc208210340)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc208224060, 0x7fdbe26691b0, 0xc20830e0a0, 0xc208210340)
        /snp/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:674 +0x125
net/http.serverHandler.ServeHTTP(0xc2082c8060, 0x7fdbe26691b0, 0xc20830e0a0, 0xc208210340)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208294140)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
 [[Go 1.1 package http] 127.0.0.1:43614]
```

**Comment by bgrant0607** [comment]
@simon3z

**Comment by bgrant0607** [comment]
@yujuhong What is your cluster configuration? Are you running cadvisor?

**Comment by yujuhong** [comment]
I used the basic configuration, i.e., running `hack/local-up-cluster.sh` with no additional changes.

As far as I know, the script does not start cadvisor because of the lack of cadvisor.manifest file. If cadvisor is required for getting nodeInfo, this setup would certainly fail. If that's the case, perhaps kubelet should fail more gracefully without the spamming?

**Comment by bgrant0607** [comment]
Yes, I agree.

**Comment by bgrant0607** [comment]
There are also plans to integrate cadvisor into Kubelet. @vmarmol may know more about that.

**Comment by simon3z** [comment]
This is weird because I can understand the "tcp 127.0.0.1:4194: connection refused" part (cadvisor not running). But I don't know where the stacktrace is coming from (not happened to me yet). Looking into it.

**Comment by bgrant0607** [comment]
@simon3z There were at least 2 problems -- one of which was unrelated to your change and was just fixed.

**Comment by vishh** [comment]
#5308 is out to integrate cadvisor into kubelet. @simon3z: kubelet might dump a stack trace on all http errors.

**Comment by simon3z** [comment]
@bgrant0607 what do you think it should be the correct behavior. For me logging a failed connection to cadvisor is important (even though I understand that it's probably too much verbose).

At this time I think that having cadvisor running should be mandatory.
Do you think we should have a configurable somewhere? (apiserver) What would be the default?

**Comment by vmarmol** [comment]
#5308 will make it a known and existing dependency. I think that PR should fix this issue.

**Comment by dchen1107** [comment]
This should be fixed. Close it.

**Comment by jayunit100** [comment]
Just leaving a note for folks getting this I found that I got this `127.0.0.1:4194: connection refused` when starting with no api-server version flag `KUBE_API_ARGS="--runtime_config=api/v1beta1"` fixed it for me.

**Comment by vmarmol** [comment]
@jayunit100 this is an error you saw on the apiserve logs?
