### ISSUE TITLE
Add more detailed settings in the doc on how to build kubernetes

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#5358]
I was tring to build kubernetes following /kubernetes/build/README.md. But failed for some times. I looked into the error and found it's because I'm behind a proxy. Then I edited the dockerfile under build/build-image/ folder, added some proxy settings into it and solved the problem.

Though it may not be a problem for experienced guys. Would it be better for the beginners to describe these detaied settings in the document? Can I add the proxy settings I found into the doc?

I'm new to kubernetes and need your opinion.

**Comment by gmarek** [comment]
Yes, please, by all means. Please describe your problem and the solution in the doc and send a PR.
