### ISSUE TITLE
kubectl log -f doesn't appear to work

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#5360]
Running ```kubectl log <pod>``` produces container output. Then, expecting to see new output, we ran ```kubectl log -f <pod>``` and waited while watching an empty screen. A while later, we killed that kubectl and ran ```kubectl log <pod>``` again and saw the output we'd been expecting. 

Based on the documentation, I expected that passing the -f flag would cause a streaming log to be printed to the local console.

**Comment by jsdir** [comment]
I wasn't able to reproduce this issue from b3413ea.

**Comment by roberthbailey** [comment]
I was using `gcloud alpha container kubectl log -f <pod>` which I just verified is still broken. But using the kubectl that comes distributed with gcloud (0.13.1) this works fine. So it looks like a gcloud bug rather than a kubectl bug.
