### ISSUE TITLE
hack/e2e.go -build -push doesn't do push new binaries on GCE

### ISSUE THREAD

**Issue by jszczepkowski** [GoogleCloudPlatform/kubernetes#5361]
On GCE, when I run `go run hack/e2e.go -v -build -push` to push new binaries to e2e cluster, the binaries are not pushed.

**Comment by jszczepkowski** [comment]
I lost a lot of time due to this bug today. I was debugging failing e2e tests, and I was using this command often. I took me some time before I realized it doesn't work and I need to do `e2e.go -up` each time.

**Comment by satnam6502** [comment]
@zmerlynn

**Comment by zmerlynn** [comment]
Can you be specific? I verified apiserver push at least, and I manually
inspected kubelet, but it's fidgety to test push.

**Comment by jszczepkowski** [comment]
The scenario:
1. I compiled the old version and installed it with e2e.go -v -build -up;
2. I run some e2e tests, cluster with the old version was running;
3. I changed source code of some files in pkg/apiserver or pkg/registry/pod;
4. I compiled the new version and was trying to install it with e2e.go -v -build -push;
5. I run some e2e tests, hoping the new version of apiserver was deployed.
However, the old version was still running during step 5. It seemed that step 4. compiled the new version, but didn't deploy it. To deploy the new version I needed to run e2e.go -up.

**Comment by zmerlynn** [comment]
I did tests to verify that I was no longer seeing version mismatches after
a push (which is a good sign that a push succeeded in bonking the
apiserver), but I'll see if I can do more rigorous testing soon. To be
honest, the master push hasn't changed much - the node deployment was the
part that changed much more radically with the Salt changes. So I'm not
exactly sure what you're seeing here.
