### ISSUE TITLE
Pod template labels in replication controller should be automatically populated

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#5366]
It doesn't make sense to define pod template with a set of labels that is strict subset of replicaSelector (or at least I can't find an use-case). For that reason I think that the labels in pod template part of replication controller should be optional and user should care about them only if he wants to define a superset of what replicaSelector already defines.

**Comment by fgrzadkowski** [comment]
I've heard the same comments from a client.

I think that it'd be more intuitive if we always specify pod labels in the template (so that we can copy&paste pod definition), and replicaSelector is optional (by default pod labels).

**Comment by bgrant0607** [comment]
It would be reasonable for the selector to be a subset.

I'm fine with intelligent defaulting but we need to be careful not to conflate the 2 concepts, which I think would increase the amount of confusion.

**Comment by bgrant0607** [comment]
Setting RC selector from pod template labels SGTM. Any concerns @smarterclayton? It wouldn't have to work with separate templates, though it would be desirable if it did. 

It would be nice if we could add preconditions based on other objects (resource version of pod template in this case) to etcd transactions.

**Comment by smarterclayton** [comment]
I think we agreed in another issue that defaulting the selector from the pod template labels is reasonable.  No argument from me.  One problem with pod templates is that we lose the strict relationship between selector and template, so if you change the template the RC needs to behave intelligently (I refuse to create more pods because the template selector doesn't match mine, etc)

**Comment by bgrant0607** [comment]
We should do this, and we should default replicas to 1. We could also consider defaulting replication controller labels from pod template labels. That way, essentially the only thing that would need to be specified for a singleton RC would be the pod template.

**Comment by brendandburns** [comment]
I don't think we can default replicas to 1, since we can't tell the difference between an explicit zero and a default zero, and I think there are lots of reasonable cases where you want to set replicas == 0 on create.  (esp. in the context of socket activation)

**Comment by bgrant0607** [comment]
Responded on the PR: We can distinguish default from 0 if we make it a pointer.
