### ISSUE TITLE
Semantics of delete vs. stop for ReplicationController are non-obvious

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#5370]
When someone explains it, it makes sense, but the semantics are not "discoverable" from the names. Is there a use case for deleting a RC without removing its pods? If not, @roberthbailey suggested (and I agree) that we should not have a stop operation and instead make delete do what stop does today.

**Comment by satnam6502** [comment]
What team does this belong to?

**Comment by satnam6502** [comment]
Specifically, you mean right now one has to resize a replication controller to 0 and then delete it?

**Comment by davidopp** [comment]
Today "stop" resizes to 0 and then deletes the rc. "delete" just deletes the rc and leaves the pods running. But nobody would guess that from the names.

**Comment by ghodss** [comment]
> Is there a use case for deleting a RC without removing its pods?

I believe so - especially since the idea of replication controllers is that they are only loosely coupled to the pods they manage through labels. For example you may want to replace one RC with another by deleting it then creating a slightly modified one but with the same selector. That would be a case where you wouldn't want the RC to go to 0 first.

**Comment by ghodss** [comment]
If the outcome of this PR is that `delete` == `stop`, does it just make sense to make stop an alias to delete in this PR?

**Comment by bgrant0607** [comment]
There's no question that the ability to delete a replication controller without deleting the pods is useful. For example, we're using that capability in the new "renaming" rolling update. It's just less common than wanting to also delete the pods.

**Comment by bgrant0607** [comment]
Now that delete does stop by default this is less critical.

**Comment by bgrant0607** [comment]
We're going to get rid of stop #11384, which will resolve this issue. Closing as a dupe.
