### ISSUE TITLE
Kubelet log filled with errors

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#5372]
W0312 15:24:56.615757     792 docker.go:725] found a container with the "k8s" prefix, but too few fields (5): "k8s_cadvisor.8d424740_cadvisor-agent.file-6bb810db-kubernetes-minion-oazg.file_f67a53c9f0b87f76b175e512efee1def_43b09df6"

These are all brand new pods - they should not be invalid

**Comment by thockin** [comment]
@dchen1107 @yujuhong

**Comment by vmarmol** [comment]
I've been tracking this issue, this seems to be old, not new containers. Typically happens when a GCE cluster is started (static pods are brought up by the old Kubelet) when the new Kubelet comes up it kills the old pods but we can't GC them because we can't recognize them. The log is from GC.

Assigning to myself and I'll fix today.

**Comment by dchen1107** [comment]
dup of #5209?

**Comment by vmarmol** [comment]
Thanks @dchen1107, closed that in favor of this.

**Comment by yujuhong** [comment]
@vmarmol, thanks for handling this. Let me know if there's anything I can help. We should GC them as long as the container name starts with k8s.

**Comment by thockin** [comment]
I saw it today on a brand new cluster.

**Comment by vmarmol** [comment]
@thockin that should be expected. The first Kubelet that comes up is the Kubelet we have built-in the Container VM image and it doesn't do the new names yet.

**Comment by thockin** [comment]
No, it keeps happening, even later.  I manually updated kubelet, it keeps
popping up

**Comment by vmarmol** [comment]
@thockin taking a look

**Comment by dchen1107** [comment]
@yujuhong indicates what happened above:

1) When node first bootstrap, it has containers running with old format
2) kubelet is upgrade, and kill old containers
3) GC periodically queries the dead containers with k8s prefix, and found those containers with old format, and throw log message.

How to fix? just GC them.

**Comment by dchen1107** [comment]
Or simply lower down the log level to VLOG(4) since it should be a short-term thing.

**Comment by vmarmol** [comment]
Just sent out #5395 with the fix. The issue was container GC.

- Old Kubelet created containers
- New Kubelet comes up and kills old containers
- GC runs, but since the containers don't have a UID we don't remove them (repeat)

Verified on a new cluster.
