### ISSUE TITLE
Remaining cleanups for BoundPods

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#5384]
Starting a new issue since the old ones have lots of history.
I'm perfectly willing to do this work, but putting it in an issue in case anyone else wants to grab instead.

 1. Delete BasicBoundPodFactory reference in pkg/master/master.go
   1. Now `NewREST` in pkg/registry/pod/etcd/etcd.go line 42 no longer needs the second argument.  Fix that.
   1. Now pkg/registry/pod/bound_pod_factory.go and pkg/registry/pod/bound_pod_factory_test.go are unused.  Delete them.
   1. I think there were some other dead code and simplifications but can't remember exactly what.

**Comment by erictune** [comment]
@wojtek-t @rsokolowski  @jszczepkowski you might be interested or know someone who is.

**Comment by satnam6502** [comment]
What team and component does this belong to? Thanks.

**Comment by wojtek-t** [comment]
I will start working on that today.
