### ISSUE TITLE
kube-push.sh broken?

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#5402]
"MASTER_IP_RANGE: unbound variable" at least sounds like an issue.

```
Using master: e2e-test-dbsmith-master (external IP: 146.148.62.15)
MINION_NAMES=e2e-test-dbsmith-minion-ui0h e2e-test-dbsmith-minion-y2in
current-context: "crested-analogy-671_e2e-test-dbsmith"
Running: /usr/local/google/home/dbsmith/code/k/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl config view -o template --template={{$dot := .}}{{with $ctx := index $dot "current-context"}}{{$user := index $dot "contexts" $ctx "user"}}{{index $dot "users" $user "username"}}{{end}}
current-context: "crested-analogy-671_e2e-test-dbsmith"
Running: /usr/local/google/home/dbsmith/code/k/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl config view -o template --template={{$dot := .}}{{with $ctx := index $dot "current-context"}}{{$user := index $dot "contexts" $ctx "user"}}{{index $dot "users" $user "password"}}{{end}}
+++ Staging server tars to Google Storage: gs://kubernetes-staging-9fbf6/devel
/usr/local/google/home/dbsmith/code/k/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/util.sh: line 436: MASTER_IP_RANGE: unbound variable
Updated [https://www.googleapis.com/compute/v1/projects/crested-analogy-671/zones/us-central1-b/instances/e2e-test-dbsmith-master].
Pushing to master (log at /usr/local/google/home/dbsmith/code/k/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/../_output/logs/kube-push-e2e-test-dbsmith-master.log) ...
2015/03/12 13:40:38 Error running push: exit status 1
2015/03/12 13:40:38 Error pushing e2e cluster. Aborting.
```

**Comment by satnam6502** [comment]
@zmerlynn

**Comment by zmerlynn** [comment]
The `MASTER_IP_RANGE` was actually @brendanburns, but the problem is that it's trying to pull from a `kube-env` that just doesn't have that variable in it.

**Comment by zmerlynn** [comment]
(I would care about this right, but I'm trying to get GKE back settled first.)

**Comment by brendandburns** [comment]
Yeah, you're going to have to delete your old cluster and rebuild.

We can't ensure that kube-push.sh will work consistently across arbitrary code changes (at least until we have update working properly, and possibly not even then)

**Comment by zmerlynn** [comment]
The weird thing is that `util.sh` in `kube-push` does a `write-master-env`, then does do an `add-instance-metadata-from-file` on the master, so it *should* have updated your master kube-env before attempting to blast configure-vm. If you feel like debugging for a little while, it's worth poking at. I'm not going to have time this afternoon because someone else was complaining about binaries not getting pushed.

**Comment by zmerlynn** [comment]
Oh! e2e? @brendanburns just noticed it's not in config-test.

**Comment by brendandburns** [comment]
Ah, also, I realized that I forgot to add the variable to the test config,
so e2e will fail!  PR coming.

Sorry!
--brendan

**Comment by zmerlynn** [comment]
Haha. We've been failing cluster creates on Jenkins for 2 hours. Thanks for the bug. :)

**Comment by zmerlynn** [comment]
Can you update past #5406 and try the push again? I'm curious, because I thought I actually planned for this case.

**Comment by lavalamp** [comment]
@brendanburns I accept the occasional kube-push.sh failure as par for the course but it shouldn't fail this much.

@zmerlynn Yeah apparently I can't even start a cluster without that.

**Comment by zmerlynn** [comment]
Note that I doubt *just* a push is enough here, because startup is actually creating a route to the master as well. But I don't think it'll hang in the same way. We aren't doing anything with that route yet, so you'd probably end up fine for a few days. ;)

**Comment by lavalamp** [comment]
-push worked for me just now. Thanks for the fix.
