### ISSUE TITLE
kube-down.sh can't delete master-pd

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#5405]
kube-down.sh gave me this error the past two times I've turned down a cluster.

```
ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
 - The resource 'projects/crested-analogy-671/zones/us-central1-b/disks/e2e-test-dbsmith-master-pd' was not found
```

**Comment by zmerlynn** [comment]
It's normal for down to give errors about resources that don't exist?

**Comment by zmerlynn** [comment]
(It did finish, yes?)

I added that code because it's obnoxious when kube-up creates the PD but then fails to create the VM, yet there's no script to clean up. So this is either a non-bug, or you just want someone to /dev/null it.

**Comment by zmerlynn** [comment]
Oh, I see the misunderstanding. I just re-read the title. This isn't the bug. I'm changing the title.

By the time `kube-down.sh` is trying to actually delete the PD, it passed `--delete-disks all` to `gcloud compute instances delete`. So it had one shot to delete the master PD already. The second attempt is just to delete a lonely PD if there was no PD.

Closing for now. Reopen if you really want the spam fixed.

**Comment by lavalamp** [comment]
I see. Thanks for explanation.
