### ISSUE TITLE
kube-push.sh and dev-build-and-push.sh do not update kube-apiserver binary

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#5408]
I made several attempts to update the apiserver (i.e. `kube-apiserver` on the master) using `kube-push.sh` and `dev-build-and-push.sh` but they failed to update the binary. I noticed the same PID on the master for `kube-apiserver` and a long uptime. If I tore the cluster down and rebuilt it then I could see the change I made to the apiserver.

**Comment by satnam6502** [comment]
@dchen1107 @davidopp @zmerlynn

**Comment by zmerlynn** [comment]
I'm actively working on it.

**Comment by dchen1107** [comment]
I noticed exact the same issue today by update my kubelet binary.

**Comment by zmerlynn** [comment]
Push is broken, sorry. I thought I tested it, but the binaries aren't getting bonked appropriately.

**Comment by zmerlynn** [comment]
kubelet binary push actually worked before? That path looked dubious at
best.

**Comment by zmerlynn** [comment]
I would appreciate external testing. I have done some sniff testing, but
push is a really broad use-case.

**Comment by dchen1107** [comment]
reopen this since the fix is reversed.
