### ISSUE TITLE
`hostname -i` doesn't work in running container

### ISSUE THREAD

**Issue by galvez** [GoogleCloudPlatform/kubernetes#5410]
I have this pod: http://pastebin.com/GJzkLybV

	# docker ps
	CONTAINER ID        IMAGE                                             COMMAND                CREATED             STATUS              PORTS                    NAMES
	6719460ecb83        gcr.io/analytical_rig_823/reachsocket-db:latest   "/opt/reachsocket/ma   56 minutes ago      Up 56 minutes                                k8s_mongodb-failover.823d621c_db.default.api_4891486b-c906-11e4-b624-42010af00e4a_acc28418

But:

	root@k8s-reachsocket-node-2:~# docker exec -it 671 bash
	root@db:/tmp/redis-stable# hostname -i
	hostname: Name or service not known

**Comment by satnam6502** [comment]
@thockin -- who else can help with this?

**Comment by satnam6502** [comment]
Continuing from IRC, @galvez wants to know the IP address of the container (pod).
`hostname` works, but `hostname -i` does not.

**Comment by brendandburns** [comment]
```hostname -i``` has worked for me in other containers.  Is this OS dependent?

**Comment by galvez** [comment]
My containers' base image is Ubuntu 14.04.

**Comment by brendandburns** [comment]
See:
http://askubuntu.com/questions/185070/why-i-get-hostname-name-or-service-not-known-error

perhaps?

/etc/hosts might be borked (or DNS somehow?)

**Comment by satnam6502** [comment]
The container I ran `hostname -i` on was also Ubuntu 14.04.

**Comment by brendandburns** [comment]
Jonas, can you try just running a vanilla docker container and seeing if
hostname -i works?

**Comment by galvez** [comment]
Guys, hostname -i doesn't work... but -I does:

  # hostname -I
  10.132.1.23

**Comment by satnam6502** [comment]
Strange that asking for all addresses for the hostname works (-I) but asking for the IP (-i) does not.

**Comment by galvez** [comment]
Note: `/etc/hosts` is empty on all running containers.

**Comment by thockin** [comment]
/etc/hosts should not be empty.

docker run -ti busybox cat /etc/hosts
172.17.0.11 0eb34aecf94d
127.0.0.1 localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by satnam6502** [comment]
I'd like to try and make progress on this issue. @galvez : please can you:
* Tell us exactly what version of Kubernetes you are using (a release? built from HEAD?).
* We're assuming GCE
* We're assuming nothing special has been done to the config
If you have a regular config you should have some pods running for cluster level services e.g. for logging. Can you docker exec into either the Elasticsearch logging or Kibana logging container and run `hostname -i` and also look at /etc/hosts? Can you view the Grafana dashboard for monitoring? Or the Kibana dashboard for logging? That would let us know that networking must be working to a good degree and then we can focus on the OS setup in the containers you are deploying.
Thank you kindly.

**Comment by thockin** [comment]
I dont think docker will create an empty hosts file - that's the fun part...

**Comment by galvez** [comment]
@satnam6502 You've made the right assumptions. No special config other than the pod file I shared earlier. Let me know if you still need a copy. I'll take a look at the other bits later today and update the issue.

**Comment by thockin** [comment]
This is almost 3 weeks old.  I'm going to close it, but please reopen if it is still a problem
