### ISSUE TITLE
kube-proxy: needs monit

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#5412]
% ls /etc/monit/conf.d/
docker  kubelet

We need kube-proxy there too?

**Comment by vmarmol** [comment]
I'll take a look.

**Comment by dchen1107** [comment]
Actually I am thinking about run it as pod not like docker and kubelet. Eventually I even want kubelet running as a docker container, but not for v1.0, so that Node upgrade / cluster upgrade will be much simplier.

**Comment by vmarmol** [comment]
@dchen1107 and I spoke offline, we're gonna close this in favor of #5419 which will run kube-proxy in a Docker container. We will work on that soon.
