### ISSUE TITLE
Integration test should not be in the cross-compile list

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#5421]
Today we have server, client, and test binaries. We expect the server ones to only build in Linux, but the client and test ones we expect to be able to build and run in Linux, Mac OS X, and Windows.

Server binaries:
- kube-proxy
- kube-apiserver
- kube-controller-manager
- kubelet
- hyperkube
- kube-scheduler

Client binaries:
- kubectl
- kubernetes (busybox)

Test binaries:
- e2e
- integration
- gendocs
- denman

Arguably "kubernetes" should be in server and I sent out #5420 for that. The other interesting case is "integration" since that creates a local apiserver and Kubelet. By our division above, "integration" should not be in the cross-compile list. I know of at least one person (@erictune) who runs the integration test on a Mac. This would break that usecase.

The downside to not making this change is that every Linux-specific change in the server components needs to stub out that logic. @thockin hit this with tmpfs and I hit it with cAdvisor integration.

There was some push-back last time I suggested this so I wanted to file an issue and discuss :)

/cc @thockin @bgrant0607 @lavalamp

**Comment by bgrant0607** [comment]
This is a short-term / long-term tradeoff.

Today, our repo is Linux-only and Docker-only. 

Fabric8 (JVM) is in a separate repo. Rocket, novm, LXC, lmctfy, etc. haven't been integrated.

What about when Windows Docker support becomes available? CBSD?

I'm all for short-term expedience, provided we don't think it would be excessively hard to generalize later. We've taken that approach with etcd, for instance -- minimize exposed surface area, but don't generalize prematurely.

That said, I believe there are quite a few people that build on macs -- search for the issues that talk about iptables and MacOs, shell tool (tar, grep, ...) command-line differences, etc.

cc @smarterclayton @eparis

**Comment by erictune** [comment]
Integration creates kubelets with fake docker.  If it is not too hard, then
there should also be a way to make a fake mounter, or whatever is needed
for tmpfs.

**Comment by smarterclayton** [comment]
Yeah, we have a few fake mounters in places already for unit tests.

I'd say there are at least 4-5 active contributors on Mac.

**Comment by vmarmol** [comment]
We make the fakes today for those tests. The argument was the work required to maintain those (and alternate implementations of things). There are also a lot of incompatibilities that aren't detected at compile time (access Linux-specific parts of /proc, iptables, cgroups). There does seem to a good number of developers on Mac which may make it worthwhile. I'm not sure the pain today is bad enough to force them to use Linux.

**Comment by smarterclayton** [comment]
From an engineering perspective, forcing ourselves to clearly identify (via interfaces, fakes, etc) those dependencies is beneficial in general - it makes us recognize coupling and break it, introduce interfaces for specific behaviors, and make general sub components that can be swapped out. Given that an integration fake (emulating a mount failure) is valuable, the slightly more work to make certain things use the fake is helping us, not hurting.

As an example, I always run as non-root specifically to force assumptions to the surface.  Not everyone has to do it, but the people who do are exposing hidden assumptions.

**Comment by erictune** [comment]
We know it is useful to have the ability to do lightweight simulations of
clusters.  That is another reason to ensure kubelet remains able to run as
non-root.

**Comment by vmarmol** [comment]
Alright, I think there is consensus :) Closing this issue, thanks everyone for the discussion!

**Comment by thockin** [comment]
Kubelet running as non-root is a dead-end IMO.  There are too many things
we want to be able to do that just won't work.  Futzing with namespaces,
cgroups, network interfaces, sysctls, kernel knobs, tmpfs, etc.  It's a
giant waste of time.

I'm fine with saying "we build for Windows specifically to flush out
Linux-isms" as long as we don't pretend Windows or MacOS will actually
WORK.  Running unit tests is one thing, and you really should not need root
to run those, and they really should be fakeable across OSes.  Integration
testing is sketchy for all the same reasons I listed above.

**Comment by smarterclayton** [comment]
The implication being that it's not worth it to have non-root integration fakes, for say, being able to test lots and lots of kubelets talking to the apiserver from a travis test?  I would think that's the best reason in the world to ensure the Kubelet remains stubbable.

**Comment by thockin** [comment]
Look,I am big proponent of dependency injection, but the more levels you
have to inject through the higher the cost of keeping it working is.

Injecting a fake mounter at the very top means a lot of plumbing and a lot
of the top-level test understanding how the bowels of the app work.  For
every subsystem that does anything privileged, we pass some number of fakes
in from the very top of the app.  How many such subsystems can that
sustain?  In my experience, this is a difficult exercise for a non-trivial
app.  It just doesnt return enough value to justify the ongoing maintenance.

And anyway, integration test should be testing REAL code, not fakes.  Our
"integration" test is weird and it is lucky that it limps along.

I would much rather invest in real integration tests that exercise the
edges between kubelet, kernel, proxy, etc.  How is that different from
e2e?  Not sure it is.
The implication being that it's not worth it to have non-root integration
fakes, for say, being able to test lots and lots of kubelets talking to the
apiserver from a travis test? I would think that's the best reason in the
world to ensure the Kubelet remains stubbable.


> On Mar 15, 2015, at 5:56 PM, Tim Hockin <notifications@github.com> wrote:
>
> Kubelet running as non-root is a dead-end IMO. There are too many things
> we want to be able to do that just won't work. Futzing with namespaces,
> cgroups, network interfaces, sysctls, kernel knobs, tmpfs, etc. It's a
> giant waste of time.
>
> I'm fine with saying "we build for Windows specifically to flush out
> Linux-isms" as long as we don't pretend Windows or MacOS will actually
> WORK. Running unit tests is one thing, and you really should not need
root
> to run those, and they really should be fakeable across OSes. Integration
> testing is sketchy for all the same reasons I listed above.
>
> On Fri, Mar 13, 2015 at 10:02 AM, Eric Tune <notifications@github.com>
> wrote:
>
> > We know it is useful to have the ability to do lightweight simulations
of
> > clusters. That is another reason to ensure kubelet remains able to run
as
> > non-root.
> >
> > On Fri, Mar 13, 2015 at 9:57 AM, Clayton Coleman <
notifications@github.com
> > >
> > wrote:
> >
> >
> > > From an engineering perspective, forcing ourselves to clearly
identify
> > > (via interfaces, fakes, etc) those dependencies is beneficial in
general
> > -
> > > it makes us recognize coupling and break it, introduce interfaces for
> > > specific behaviors, and make general sub components that can be
swapped
> > > out. Given that an integration fake (emulating a mount failure) is
> > > valuable, the slightly more work to make certain things use the fake
is
> > > helping us, not hurting.
> > >
> > > As an example, I always run as non-root specifically to force
assumptions
> > > to the surface. Not everyone has to do it, but the people who do are
> > > exposing hidden assumptions.
> > >
> > > > On Mar 13, 2015, at 11:53 AM, Victor Marmol <
notifications@github.com>
> > > wrote:
> > > >
> > > > We make the fakes today for those tests. The argument was the work
> > > required to maintain those (and alternate implementations of things).
> > There
> > > are also a lot of incompatibilities that aren't detected at compile
time
> > > (access Linux-specific parts of /proc, iptables, cgroups). There does
> > seem
> > > to a good number of developers on Mac which may make it worthwhile.
I'm
> > not
> > > sure the pain today is bad enough to force them to use Linux.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
https://github.com/GoogleCloudPlatform/kubernetes/issues/5421#issuecomment-79131072
> > >
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/GoogleCloudPlatform/kubernetes/issues/5421#issuecomment-79136023>

> > .
> >
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/5421#issuecomment-81306501>
.

**Comment by brendandburns** [comment]
I (as a developer on OS X) would like integration tests to work as best as
possible.  We should chose the places to stub where there is minimal effort
for maximum coverage in developing stubs, even if that means that OS X
integration tests are not as complete as Linux integration tests.

Basically, I just need my development environment to "mostly work".  I'm
fine if we disable a few tests, or they are not as comprehensive.  Travis
can always catch those, and I can switch to a Linux environment in those
rare cases.

--brendan

**Comment by thockin** [comment]
I'm fine keeping integration as long as it provides some value.  I really
think the value will be minimal, especially once e2e is more reasonable.

**Comment by smarterclayton** [comment]
I really want there to be a class of test between full blown e2e (stand up a cluster) and pure unit (I have a package).  Tests of the etcd libs against etcd, tests of the client against the api, tests of docker and rocket abstractions against those interfaces.  That's fairly hard to argue against.  I think all we're arguing is how decoupled the kubelet is - can it be driven via tests to verify its core flows against a) docker and b) the apiserver?  If more extensive whole system testing sits above that, so much the better.  The bare minimum is some reasonable sanity checks - if I change the api, does the kubelet break?  That should take <1s to answer.  E2e will never come close to that.

If you're not against the former I'm not against the latter.. :)

**Comment by bgrant0607** [comment]
It's all a question of where to do the stubbing for what kinds of tests.

Many cluster-level tests will want to stub more of kubelet. Examples:

* Master scalability stress tests and benchmarks w/ many more "kubelets" than we'd normally run with
* Distributed robustness/consistency tests that disrupt communication between components
* In particular, tests of master replication, failover, etc. once we support HA
* Scheduling quality tests/simulations

OTOH, tests of Kubelet behavior might want to just fake/mock parts of Kubelet. For example, it might be useful to be able to test the behavior in the case of a mount hanging for an extended period of time.
