### ISSUE TITLE
Request timeout while creating guestbook example

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/kubernetes#5431]
When I'm creating guestbook application I often get a timeout with following error message:
```
 F0313 13:41:45.095711    4181 create.go:50] Client error processing command: Timeout: request did not complete within allowed duration
```

It happens in all cases
* manual creation
* in guestbook.sh e2e test
* in kubectl.go e2e test (I'm working to port guestbook.sh to ginkgo, #5045)

**Comment by roberthbailey** [comment]
Piotr - have you tracked this down yet?

The create/patch/update/delete functions in [resthandler.go](https://github.com/GoogleCloudPlatform/kubernetes/blob/19b6c85fa50f22c0f7a5cffd8f81e3b359448d17/pkg/apiserver/resthandler.go) all timeout if the request hasn't completed sufficiently quickly. The default timeout is [30 seconds](https://github.com/GoogleCloudPlatform/kubernetes/blob/19b6c85fa50f22c0f7a5cffd8f81e3b359448d17/pkg/apiserver/apiserver.go#L261), and I wouldn't be surprised if it takes longer than that for the guestbook example to create an external load balancer.

**Comment by piosz** [comment]
So about about increasing it to 2 minutes or so?

**Comment by quinton-hoole** [comment]
#5156 aims to make external load-balancer creation asynchronous.  I'd suggest filing an issue to revert this change as soon as #5156 is fixed.

**Comment by hansedong** [comment]
I encountered a similar problem，and finally, I found this problem was caused by initializer（istio initializer in fact） in k8s。I reinstalled the istio components and solved the problem。Hope this help someone.
#51883
