### ISSUE TITLE
In e2e test cluster in GCE Route for master is not being deleted during --down

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#5434]

**Comment by ddysher** [comment]
firewall is also not deleted

**Comment by brendandburns** [comment]
I believe that the problem w/ the route is deleted by #5448

Also, what firewall?  There was no new firewall added...

**Comment by satnam6502** [comment]
Perhaps this is related to my woes in #5451

**Comment by zmerlynn** [comment]
I think this is fixed. Please reopen if there's still an issue.
