### ISSUE TITLE
Killing machine doesn't migrate the pod immediately

### ISSUE THREAD

**Issue by ehacke** [GoogleCloudPlatform/kubernetes#5435]
I'm running kubernetes on top of coreos machines inside of vagrant.

It looks like if I deploy some pods into a cluster with 1 master and 4 minions, and then kill one of the vagrant machines running a given pod, kubernetes does not immediately migrate the pod to another machine. It seems to take about 13 minutes to notice that the machine is dead. During that time, if I run `kubectl get pods` it still shows the pod as "running", even though the machine is gone and has been for awhile.

Eventually it does migrate the pod, but the last time I tried this it took 13 minutes to notice the machine died before doing so.

I originally raised the issue [here](https://github.com/pires/kubernetes-elasticsearch-cluster/issues/6#issuecomment-78895023) on the chance that it was an issue that is specific to the implementation. But it seems like @pires believes this to be an issue he's seen before with kubernetes.

I tried it a number of times with both 0.11.0 and 0.12.1, and the issue continues.

I searched through the issues and couldn't find an obvious reference to this. Is this a known issue?

Is there anything else I can do to help debug it? It's easy for me to reproduce.

**Comment by roberthbailey** [comment]
I think this has to do with our notion of "forgiveness" when a node disappears. @erictune?

**Comment by erictune** [comment]
I don't think that anything has been implemented around "forgiveness".  We just talked about that.

**Comment by roberthbailey** [comment]
Interesting. I did a similar test the other day and had just assumed that was what was going on. Any ideas what could actually be happening then?

**Comment by erictune** [comment]
`PodEvictionTimeout:      5 * time.Minute`

I don't see how we are getting to 13 minutes.

**Comment by ehacke** [comment]
@erictune I got the 13 minutes by observing the difference in pod created time. I'll reproduce the issue right now and double check that.

In addition, prior to the eviction timeout expiring, should the pod be reported as 'running' when it's missing entirely? I guess that's a different issue.

**Comment by vmarmol** [comment]
We've been working on pushing pod status to the master from the machines. We'd need a mechanism through which the master can see when the statuses have not been updated in EXPECTED_TIME and reflect that.

**Comment by ddysher** [comment]
Right now, it should be Unknown

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/pod_cache.go#L199

**Comment by erictune** [comment]
@ehacke Oh, I believe you.  I just don't have any idea why yet.

**Comment by ehacke** [comment]
@erictune I'm not sure I believe me, so I'm double checking.

**Comment by ehacke** [comment]
So it's possible I could have just done bad math for the 13 minute case, because it does look like it's ~5 minutes in the three cases I just tried.

In terms of status, it does continue to report as 'Running' even if the machine is dead. Though it seems like if I bring the formerly dead machine back with the same IP, the reporting updates to 'Unknown'.

**Comment by bgrant0607** [comment]
Look at the node.status.conditions. You should see a condition with kind==Ready with the status, last probe time, etc.

If you want to change the 5-minute default, you can set --pod_eviction_timeout=<duration> on the controller-manager command line.

@ddysher

**Comment by lhuard1A** [comment]
I encountered the same issue and found that the POD was evicted `pod_eviction_timeout` seconds after the minion is considered not ready anymore.
The problem is that if the minion is totally unresponsive, its status is not updated.

Here is what I observe if I pause the VM hosting the minion 192.168.10.3 :
```
$ cluster/kubectl.sh get minions
NAME                LABELS              STATUS
192.168.10.2        <none>              Ready
192.168.10.3        <none>              Ready
192.168.10.4        <none>              Ready
```
```
$ cluster/kubectl.sh get minions -o yaml | grep lastProbeTime:
      lastProbeTime: 2015-03-16T08:55:27Z
      lastProbeTime: 2015-03-16T08:43:39Z
      lastProbeTime: 2015-03-16T08:55:29Z
```

**Comment by ddysher** [comment]
@lhuard1A This is a similar, but different issue.  The unresponsive vm is due to the fact we switched node status update from controller to kubelet itself.

PR is here #5399; I think we need to get that in this week.

@bgrant0607 @dchen1107
