### ISSUE TITLE
Cap dead containers at a global max

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#5457]
From @bgrant0607:

>User on IRC just reported OOD due to too many dead containers from different dead pods:
>http://paste.kismatic.io/view/a13c5e16#t15QhxeWR8MVIHhEKle50JpFhJjA9op4
>
>@brendandburns @dchen1107

**Comment by dchen1107** [comment]
Yes, there is a known issue. If I remembered correctly, there is even a TODO for this.
