### ISSUE TITLE
Shippable Continuous Integration Logs Broken Link

### ISSUE THREAD

**Issue by TamerTas** [GoogleCloudPlatform/kubernetes#5463]
The `details` link provided by the `googlebot` for `shippable` CI leads to their homepage. I've checked a bunch of failed pull requests and it's same for them as well. I think it's bugged.

**Comment by zmerlynn** [comment]
They actually don't, you just have to login (on the upper right) with your github before you can view the results.

**Comment by TamerTas** [comment]
Thanks

**Comment by zmerlynn** [comment]
FWIW, we've complained to them about this behavior, because Travis CI doesn't actually require a login before viewing results. We're trying to get it changed.

**Comment by TamerTas** [comment]
That's what confused me. Also the redirection wasn't even a log-in page redirection just a homepage.
