### ISSUE TITLE
Image on design page is unreadable

### ISSUE THREAD

**Issue by PhilAndrew** [GoogleCloudPlatform/kubernetes#5483]
Take a look.

![image]
(https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/docs/architecture.png)

https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/docs/architecture.png

From this page.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/DESIGN.md

**Comment by satnam6502** [comment]
Assigning to Brendan. Strange: the image looked fine to me when I reviewed the PR. Sorry about this.

**Comment by PhilAndrew** [comment]
I think Kubenetics is great, just want to understand it more

**Comment by a-robinson** [comment]
The diagram should be fixed now. Thanks for reporting the issue, @PhilAndrew!
