### ISSUE TITLE
/watch stream filter

### ISSUE THREAD

**Issue by PavelPrischepa** [GoogleCloudPlatform/kubernetes#5486]
Is it possible to filter /watch stream by timestamp or index (as in etcd waitIndex)?
If no it we'll be great to have.

**Comment by simon3z** [comment]
@PavelPrischepa @a-robinson we are already tracking this at https://github.com/GoogleCloudPlatform/kubernetes/issues/5130

**Comment by a-robinson** [comment]
Thanks @simon3z, I'll close this in favor of #5130.
