### ISSUE TITLE
TestSyncPodsDeletesWithNoPodInfraContainer is flaky

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#5496]
Seeing random failures.

```
I0316 00:07:11.888567   20733 kubelet.go:1288] probe success: bar2
--- FAIL: TestSyncPodsDeletesWithNoPodInfraContainer (0.00s)
	kubelet_test.go:110: expected []string{"list", "list", "list", "list", "inspect_container", "inspect_container", "stop", "create", "start", "inspect_container", "create", "start"}, got []string{"list", "list", "list", "stop", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}
W0316 00:07:11.888986   20733 kubelet.go:1014] No ref for pod '1234'
W0316 00:07:11.889004   20733 kubelet.go:1014] No ref for pod '9876'
W0316 00:07:11.889395   20733 kubelet.go:1014] No ref for pod '1234'
W0316 00:07:11.889407   20733 kubelet.go:1014] No ref for pod '9876'
```

**Comment by dchen1107** [comment]
Looks like lately refactory makes docker API requests are not deterministic. Will look into it.

**Comment by nikhiljindal** [comment]
Any update? It seems to be failing a lot.

**Comment by yifan-gu** [comment]
@dchen1107 
I just looked into this and found that `TestSyncPodsDeletesWithNoPodInfraContainer` is the only test that there are two pods in the []*api.Pod
I think podworker was syncing the two pods in parallel, this causes non-deterministic behaviour

**Comment by dchen1107** [comment]
@yifan-gu Yes, that is what I believe here, but never have time working on it. Thanks for looking into this, and re-assign it to you.

**Comment by yifan-gu** [comment]
@dchen1107 I saw your old PR for this, I think we still need to keep the parallel sync here. Just need to create a `verifyUnorderedCalls`  for this case :)
