### ISSUE TITLE
Proposal: Move nodecontroller to pkg/controller

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#5505]
Current location, i.e. cloudprovider/controller does not seem very natural to me. Can we move it to 'controller' folder or is there a good reason for it to be in cloudprovider?

**Comment by jlowdermilk** [comment]
It makes sense to me that it would be cloudprovider, as creating/healthchecking/etc of nodes requires provider specific logic. `pkg/controller` houses replication controller logic, which is unrelated. cc @thockin, @davidopp

**Comment by thockin** [comment]
I have not paid attention to what all code is in there, but my instinctive
split is that pkg/controller (or something like it) holds the main body of
the logic, and calls into cloudprovider interfaces.  Generic code in a
generic place, specific code in specific places.

**Comment by dchen1107** [comment]
cc/ @ddysher @bgrant0607 for more background on the current location.

**Comment by bgrant0607** [comment]
I have no idea why it is where it is. I am in favor of moving it. It contains generic health-checking logic.

See also #4851.

**Comment by derekwaynecarr** [comment]
If we make this change, then the open question I have is if all of our controller code should go in pkg/controller

**Comment by bgrant0607** [comment]
Putting everything in pkg/controller is not the right solution, IMO. Let's discuss on #4851.
