### ISSUE TITLE
Service Creation request is getting failed every second time!! 

### ISSUE THREAD

**Issue by siddhsuper** [GoogleCloudPlatform/kubernetes#5509]
Hi,

I am trying to create a service through api, its getting failed every second time. It's not stable and if I am trying it again its getting passed.

And another thing is in the response body "status" will not come if it is successful.

Failure Response Body:
 {
    "kind": "Status",
    "creationTimestamp": null,
    "apiVersion": "v1beta1",
    "status": "Failure",
    "message": "service \"myservice-service\" not found",
    "reason": "NotFound",
    "details": {
      "id": "myservice-service",
      "kind": "service"
    },
    "code": 404
  }

Successful Response Body:
{
    "kind": "Service",
    "id": "myservice-service",
    "uid": "c114ce64-cbec-11e4-aa98-42010af0f77b",
    "creationTimestamp": "2015-03-16T14:57:24Z",
    "selfLink": "/api/v1beta1/services/myservice-service?namespace=default",
    "resourceVersion": 53236,
    "apiVersion": "v1beta1",
    "namespace": "default",
    "port": 3000,
    "protocol": "TCP",
    "selector": {
      "name": "homeweb"
    },
    "createExternalLoadBalancer": true,
    "publicIPs": [
      "104.199.136.98"
    ],
    "containerPort": "http-server",
    "portalIP": "10.227.254.45",
    "sessionAffinity": "None"
  }

**Comment by jlowdermilk** [comment]
Hi @siddhsuper. I take it you are hitting the apiserver directly via js or something. Can you post the request body and the url you are hitting?

**Comment by siddhsuper** [comment]
Hi,

@jlowdermilk , I am trying through JS and directly through Rest Client also,

URL: https://107.167.181.94/api/v1beta1/services

BODY:
{
  "apiVersion": "v1beta2",
  "kind": "Service",
  "id": "enterpriseweb-service",
  "port": 3000,
  "containerPort": "http-server",
  "selector": {
    "name": "enterpriseweb"
  },
  "createExternalLoadBalancer": true
}

**Comment by brendandburns** [comment]
Is this a post or a put?

Brendan

**Comment by siddhsuper** [comment]
Hi Brendan,

Its POST.

**Comment by jlowdermilk** [comment]
Is that a typo, or are you trying to create an object with a v1beta2 schema via the v1beta1 api endpoint?

**Comment by jlowdermilk** [comment]
I'm actually now a bit curious if that behavior is expected. @lavalamp, does anything in the request/response look amiss to you? The apiserver returning 404 service not found on that first request seems intentional.

**Comment by siddhsuper** [comment]
Hi All,

Apologies for the late reply!

I have tried the same again with the below details through JS and same is happening in the second attempt its creating the Services.

But trying through REST Client : It's working good!

URL: https://104.155.222.182/api/v1beta1//services
Body:
{
  "apiVersion": "v1beta1",
  "kind": "Service",
  "id": "enterpriseweb-service",
  "port": 3000,
  "containerPort": "http-server",
  "selector": {
    "name": "enterpriseweb"
  },
  "createExternalLoadBalancer": true
}

**Comment by jlowdermilk** [comment]
Hi @siddhsuper. Sorry for the delay getting back to you, and glad to hear the RESTClient is working for you. 

I did some testing with service schema you posted above, and I believe the reason it's failing on the first request is because you have "createExternalLoadBalancer": true, which tends to take a longer time. I was able to create the same service without an ELB using plain js thru the api, and it was succeeding on the first try. I think the action item here is to make sure that the error code returned reflects the actual problem if resource creation is delayed creating provider-specific resources (i.e. external load balancer for services).

**Comment by siddhsuper** [comment]
Thanks @jlowdermilk I have already tried with the ELB = false, 
But we need some error code/message to proceed.

**Comment by quinton-hoole** [comment]
Issue 5180 should fix this real soon now by deferring external load balancer creation to be asynchronous w.r.t. the k8s API call.  cc @a-robinson in case he wants to add anything here.

**Comment by siddhsuper** [comment]
Thanks :+1:

**Comment by a-robinson** [comment]
This should be better for all new clusters built from head (or a version >= 0.16.0) now that #6271 is in.
