### ISSUE TITLE
kubectl should return non-zero exit code for invalid parameters

### ISSUE THREAD

**Issue by fabioy** [GoogleCloudPlatform/kubernetes#5513]
Kubectl returns an exit status of 0 (zero) on parameters validation error. For example:

> gcloud preview container kubectl --cluster=mycluster service-name-is-too-long-and-will-fail --port=80 --container-port=8000 --selector="name=foo"
ERROR: F0316 10:45:59.801908   12777 expose.go:98] Service "service-name-is-too-long-and-will-fail" is invalid: metadata.name: invalid value 'service-name-is-too-long-and-will-fail': must have at most 24 characters and match regex [a-z]([-a-z0-9]*[a-z0-9])?

> echo $?
0

Any non-successful execution of the command should return a non-zero exit status code.

**Comment by fabioy** [comment]
Forgot the version strings:

> gcloud preview container kubectl --cluster=my-cluster version
Client Version: version.Info{Major:"0", Minor:"12", GitVersion:"v0.12.0", GitCommit:"ecca42643b91a7117de8cd385b64e6bafecefd65", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"11+", GitVersion:"v0.11.0-dirty", GitCommit:"18ddff0eb6bc069b41832ce47d19b5b89cfb26e3", GitTreeState:"dirty"}

**Comment by zmerlynn** [comment]
Run this raw, without gcloud?

**Comment by jlowdermilk** [comment]
This is a gcloud bug. The same command returns an error if you run standalone `kubectl`. I'll open a bug internally.
