### ISSUE TITLE
`hack/build-go.sh` broken for Mac

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#5514]
### Cleaning (ok)
```bash
~/go/src/github.com/mbforbes/kubernetes$ make clean
build/make-clean.sh
+++ Verifying Prerequisites....
!!! Build image not built.  Cannot clean via docker build image.
+++ Removing data container
+++ Cleaning out local _output directory
+++ Deleting docker image kube-build:build-c987c
+++ Cleaning all other untagged docker images
rm -rf _output
rm -rf Godeps/_workspace/pkg
```

### Building (not ok)
```bash
~/go/src/github.com/mbforbes/kubernetes$ ./hack/build-go.sh
+++ Building go targets for darwin/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/kubernetes
    cmd/e2e
    cmd/integration
    cmd/gendocs
    cmd/genman
go install runtime: mkdir /usr/local/go/pkg/darwin_amd64_cgo/: permission denied
!!! Error in /Users/maxforbes/go/src/github.com/mbforbes/kubernetes/hack/lib/golang.sh:284
  'CGO_ENABLED=0 go install -installsuffix cgo "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 1
Call stack:
  1: /Users/maxforbes/go/src/github.com/mbforbes/kubernetes/hack/lib/golang.sh:284 kube::golang::build_binaries(...)
  2: ./hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in ./hack/build-go.sh:26
  'kube::golang::build_binaries "$@"' exited with status 1
Call stack:
  1: ./hack/build-go.sh:26 main(...)
Exiting with status 1
```

The error is `go install runtime: mkdir /usr/local/go/pkg/darwin_amd64_cgo/: permission denied`; I haven't mucked with my `/usr/local/go/` files, so I think this isn't something I did? Do I just have to nuke something and start over?

**Comment by brendandburns** [comment]
I ran:

sudo chmod -R a+rw /usr/local/go/pkg/darwin_amd64_cgo


and it fixed things...

**Comment by jlowdermilk** [comment]
I just hit this on linux as well. The above solved it for me, but I had to create the directory first.

**Comment by preillyme** [comment]
I just saw this as well with testing. It appears to be fixed with @brendanburns workaround.

I was seeing similar output to: http://paste.k6c.io/view/d5265a8d as reported by @satnam6502

**Comment by satnam6502** [comment]
No so on my machine since the error is:
```
go install runtime: mkdir /usr/lib/google-golang/pkg/linux_amd64_cgo/: permission denied
```
but
```
ls /usr/lib/google-golang/pkg/
linux_amd64  linux_amd64_race  tool
```

**Comment by satnam6502** [comment]
After reading @jlowdermilk 's comment above I am now golden.
Will I need to do this every time I create a repo?

**Comment by jlowdermilk** [comment]
@satnam6502 , nope. should just need to do that once on your workstation/laptop.

**Comment by thockin** [comment]
What changed appears to be the building of static binaries, but why does it need to be writable?

**Comment by thockin** [comment]
Ah, what seems to be happening is that go is rebuilding the stdlib with new flags.

sudo make; sudo make clean

now mortals can run make.

**Comment by mbforbes** [comment]
(This might be useful to document somewhere, or do programmatically, rather than relying on people to find this issue.)

**Comment by bprashanth** [comment]
I'd surface it better in the build failure, @ArtfulCoder since it was because of static binaries

**Comment by derekwaynecarr** [comment]
I think we should separate our build calls from some script that says you must first install these go tools.  In general, our scripts should verify any go tools are available prior to trying to install and run them.
