### ISSUE TITLE
Cadvisor test failures

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#5517]
We've seen this a few times on GCE now, and I saw it flake on `gke-ci` now as well (cc @vish @ixdy):

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cadvisor.go:45
Failed after retrying 10 times for cadvisor to be healthy on all nodes. Errors:
[request [&{Method:GET URL:https://130.211.153.101/api/v1beta1/proxy/minions/e2e-test-jenkins-minion-b3p4.c.kubernetes-jenkins.internal/stats/?timeout=5m0s Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:130.211.153.101 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (500) 500 Internal Server Error: Internal Error: cAdvisor is unsupported in this build
 request [&{Method:GET URL:https://130.211.153.101/api/v1beta1/proxy/minions/e2e-test-jenkins-minion-qshm.c.kubernetes-jenkins.internal/stats/?timeout=5m0s Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:130.211.153.101 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (500) 500 Internal Server Error: Internal Error: cAdvisor is unsupported in this build
]
```

**Comment by vishh** [comment]
cc @vmarmol. Victor integrated cadvisor into the kubelet. I wonder if a fake version of cadvisor gets integrated into kubelet in the case of `gke-ci` builds.

**Comment by zmerlynn** [comment]
I noticed this first on GCE. (FWIW, GKE uses the same binaries as GCE.)

**Comment by ixdy** [comment]
Jenkins shows the following four changes for the build where this test started consistently failing:

Commit d5e0054eb039e90defc55464a2d938bc38fddb0d by mattmoor
Enable usage of a "json key" for authenticating with gcr.io.

Commit 992d78a32e41348c9c599739a5257afa4a6682d9 by dbsmith
Add a system modeler to scheduler

Commit 34e9c82c703c4655c01eb0b5641c9539dd031fb4 by dawnchen
Convert RestartPolicy to string for v1beta3.

Commit 4b24aa2d7f3b348ae4fb4fdab8de12d918855b06 by abshah
Build statically linked binaryies. With the change to go 1.4, we probably were generating dynamically linked binaries accidentally.

**Comment by zmerlynn** [comment]
If I had to guess, I would take a stab and say it was 4b24aa2, #5479. cc @ArtfulCoder.

**Comment by zmerlynn** [comment]
Feel free to revert by 5pm if no fix.

**Comment by vmarmol** [comment]
I believe @zmerlynn and @vishh  are correct, #5479 makes the build not use cgo which places a fake cAdvisor in the binary and that fails. Looking into the fix.

**Comment by vmarmol** [comment]
#5527 is out, it is a revert of the old one along with a plan for not needing static binaries.
