### ISSUE TITLE
Fluentd failure on startup (and other Fluentd comments)

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#5523]
In testing out the Fluentd to Google Cloud Logging feature, I found that logs weren't being collected for any new containers I ran. This led me to investigate what was going on with the Fluentd container. I found a few things worth noting:

1. There's no way to look at the Fluentd logs without attaching to the running docker container. I can see why we don't want to send its logs to remote storage, but it may be better to write its logs into the mounted hostdir?
2. There's two log files for it? One at `/var/log/google-fluentd.log`, which is empty, and one at `/var/log/google-fluentd/google-fluentd.log`.
3. There's a failure in the `/var/log/google-fluentd/google-fluentd.log` log file ([excerpt](http://pastebin.com/4X8WvqTY)) from just after the agent started up and configured itself.
4. There's no sign of it restarting in any of the log files in the container's filesystem, but `ps xa` shows an instance of it running, so I guess it restarted but didn't output any of its normal startup configuration info? Or it just never properly died?
```
    1 ?        Ss     0:00 /bin/sh -c /usr/sbin/google-fluentd -qq > /var/log/google-fluentd.log
    7 ?        Sl     0:00 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -qq
    9 ?        Sl     0:36 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -qq
```

cc @satnam6502

**Comment by satnam6502** [comment]
Thanks. Perhaps this happened when I changed the setup recently to use a more recent Fluentd to GCP pluging that @mr-salty told me about (I thought I tested it...). I shall get the most recent plug and investigate.

**Comment by a-robinson** [comment]
To be specific, this is using kubernetes/fluentd-gcp:1.0, which looks like it's the most recent version.

**Comment by mr-salty** [comment]
Is this running on a GCE machine?  It looks like it's failing to contact the metadata server that's supposed to be running on the machine.

I don't think anything has changed about this, but we should probably fail more gracefully.

**Comment by a-robinson** [comment]
Yes, it's on GCE, and the machine has the cloud logging write scope enabled. It may be related to the fact that the project didn't have the Cloud Logging API enabled until a few minutes after the VM started running, though.

**Comment by mr-salty** [comment]
ok - I have never seen that problem with fetch_metadata, I'm not sure what would have caused it.  I assume you can manually fetch metadata from that machine, like curl -H 'Metadata-Flavor: Google' http://metadata/computeMetadata/v1/instance/id

I do wonder if it's in some bad state where it logged that it was exiting but didn't actually exit, which would explain the rest.

Also, /var/log/google-fluentd.log comes from Kubernetes - looks like it's just the stdout of the process, which may just be empty since fluent does its own logging to the other file (btw, should that also include stderr?  i don't know if you'd get any more info that way, but): https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/logging/fluentd-gcp-image/Dockerfile#L25

**Comment by satnam6502** [comment]
In my experience all output goes to stdout and nothing to stderr but it
can't hurt to pipe both. Will make the change in the next rev.

S

**Comment by a-robinson** [comment]
I tried restarting the google-fluentd service within the container. It actually ended up killing the entire container and restarting anew, but the new instance failed in the same way. I've been able to get the instance ID from the metadata server from within both containers, so I don't think that's the issue.

**Comment by satnam6502** [comment]
Hmmm.... I created a new cluster on GCE with Cloud Logging and I was able to observe logs being ingested.... I will confer with @a-robinson

**Comment by a-robinson** [comment]
Downgrading to a P2, since fluentd still seems to be working even though its logs say it failed.

The reason my logs weren't being collected is just that the pod I was testing only logs at while it's starting up, and for some reason our Fluentd image misses the first N lines from each containers output, for varying values of N. We need to open a new issue for that if there isn't one already.

**Comment by a-robinson** [comment]
Opened #5528 for the missing logs issue.

**Comment by satnam6502** [comment]
Submitted #5529 to address #5528

**Comment by satnam6502** [comment]
I think we can close this.
