### ISSUE TITLE
Remove PodIP from ContainerStatus

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#5524]
Now kubelet reports PodStatus including PodIP through PodStatus completely, there is no need to have PodIP in ContainerStatus for network container anymore.

I am going to send a pr fixing it shortly. Otherwise, someone free to pick it up.

**Comment by bgrant0607** [comment]
Note: This should only be removed from v1beta3 and from the internal rep (api/types.go).

**Comment by dchen1107** [comment]
Offline dicussion with @bgrant0607 Since We already completely hid network container from the user, there is no way for anyone access PodIP from ContainerStatus directly. It is safe to remove PodIP from all api versions.
