### ISSUE TITLE
Label Selector to match if label exists

### ISSUE THREAD

**Issue by hobti01** [GoogleCloudPlatform/kubernetes#5578]
The documentation for [labels.Parse](https://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/labels#Parse) shows that an "exists" Selector can be created like this:
```
s, err := labels.Parse("mylabel")
```
But this does not match labels unless there is also a matching value.

I've also tried to use [labels.NewRequirement](https://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/labels#NewRequirement):
```
r, err := klabels.NewRequirement("mylabel", klabels.ExistsOperator, nil)
```
but it seems that Requirement does not implement the Empty() method of the labels.Selector interface.

How should I create a Selector that tests if a label key exists?

**Comment by nikhiljindal** [comment]
cc @sdminonne

**Comment by sdminonne** [comment]
@hobti01 In theory you shouldn't need to create a `Requirement` and the `func Requirement.Emtpy() bool` func should return always `false`.

For the non matching I think the misunderstanding is about the definition of label. A label is a key/value pair. And the `exists` operator check the existence of the key
So when you say `s, err := labels.Parse("mylabel")` I'not sure what do you mean..
 
May you try this?

```
if s, err := labels.Parse("mykey"); err == nil {
  s.Matches(labels.Set{"myKey": "myValue"}) // this should match
  s.Matches(labels.Set{"yourkey": "myValue"}} // this should not
}
 ```
And the first line of the code gives you a way to build a labels.Selector with only a `Exists` operator.

**Comment by hobti01** [comment]
Yes, we were not using the same definition of label, I should have said "mykey".  I can confirm your test and have traced the issue further.

List() returns an error:
```
if s, err := labels.Parse("mykey"); err == nil {
  podList, listErr := myKubernetesClient.Pods(api.NamespaceAll).List(s)
  // listErr == "invalid selector: 'mykey'; can't understand 'mykey'"
}
```
The selector is translated into a URL query parameter.  Should this be a valid request?  If not, how is "key exists" queried?
```
<apiserver>/api/v1beta3/pods?labels=mykey
```
```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "invalid selector: 'mykey'; can't understand 'mykey'",
  "code": 500
}
```
The same message is provided by kubectl, and again, how is "key exists" queried:
```
$ kubectl get --selector="mykey" pods
F0318 08:37:49.081037   28653 get.go:166] the provided selector "mykey" is not valid: invalid selector: 'mykey'; can't understand 'mykey'
```

**Comment by sdminonne** [comment]
@hobti01 can you run `version` command?

**Comment by hobti01** [comment]
```
Client Version: version.Info{Major:"0", Minor:"12", GitVersion:"v0.12.1", GitCommit:"7a98dc0145574f79409f6051b2b1fe8da9d2df47", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"12", GitVersion:"v0.12.1", GitCommit:"7a98dc0145574f79409f6051b2b1fe8da9d2df47", GitTreeState:"clean"}
```

**Comment by sdminonne** [comment]
If you manged to have my tests working you should have the new requirements parsing code. But it looks your error code comes from an old version of kubectl.

I can't understand. Can you give more details about the environment you're working on?

**Comment by hobti01** [comment]
Thank you very much for the suggestion.  I did have different versions running and after updating all of them to 0.13.1 this is resolved.
