### ISSUE TITLE
Enhance kubectl return messages.

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#5579]
When I was using kubectl commands, I found whether I'm using `create` or `delete`, they return same message, that is only the pod id.  I think we can enhance the messages to provide more information to users.

**Comment by smarterclayton** [comment]
It's partially that way so the user can feed those to `xargs`.  But it needs to support multiple types.

**Comment by hurf** [comment]
Sorry I may not expressed myself clearly. I mean when I'm creating a pod, what appears in the screen is like:
	
	$ kubctl create -f pod1.yaml
	www
	$

The message 'www' is really confusing. If it is like this:

	$ kubctl create -f pod1.yaml
	Pod: www is successfully created.
	$

Would that looks better?

**Comment by smarterclayton** [comment]
It's sending www because that allows someone to do:

    kubectl create -f resources.json | xargs kubectl get pods

The gap right now is that it would be better to include the type and to support type/name via get/delete/describe so you could show multiple types at once.

**Comment by hurf** [comment]
@smarterclayton - thanks, does that mean if I want to return a message like 'Pod: www is successfully created.' I should also modify get/delete/describe to allow them extract 'www' as a parameter from the above message?

And I'm not quite clear what do you mean by 'you could show multiple types at once', can you give me an example?

BTW, I doubt the necessity of using commands like `kubectl create -f resources.json | xargs kubectl get pods`. Though creating a container is fast, it still needs seconds, and 'kubectl create' is returned asynchronously, so the command `kubectl get pods` would not contain useful information as IP. In my test, I had to wait for a few moment and use `kubectl get pods www` again to get the IP address.

**Comment by derekwaynecarr** [comment]
@hurf - creating a pod is fast.  what happens after a pod is created can take indeterminate amoutn of time - scheduling a pod to a kubelet, kubelet pulling the image, and having a running container as pod.  there are plenty of things I can get right away from a pod after its created that makes feeding it into xargs useful.  It's uid is an immediately valuable thing for one.

For other resource types that build around kubectl we DO want to be able to feed into xargs right away and be able to do useful things (namespace, quota, limits, replication controller, service, etc.)

**Comment by hurf** [comment]
@derekwaynecarr - thanks derek, the first part is exactly what I want to say. And the second part shows me the necessity of using xargs.

But is my understanding on modify get/delete/describe to resolve args from messages correct?

**Comment by derekwaynecarr** [comment]
I think the implication was that it would be good to return "pods www" so you could take the result and pass it into kubectl get, and have it be equivalent to "kubectl get pods www".  @smarterclayton chime in if I misunderstood

**Comment by smarterclayton** [comment]
pods/www was proposed.

**Comment by eparis** [comment]
pods/www would have been nice under kubecfg, but kinda stinks for kubectl.  There's not great way with kubectl and xarg....

Personally, I'd rather have the human readable behavior @hurf suggests.  with a -o option which would be useful for xarg type operations....

**Comment by smarterclayton** [comment]
Why does it stink for kubectl?  We're not talking about removing the existing syntax.  Resource Builder was specifically designed to allow this.

**Comment by eparis** [comment]
It stinks because it doesn't work...

# kubectl get pods/redis-master-controller-nyxxv 
F0319 21:51:40.065046   10219 get.go:67] Client error processing command: no resource "pods/redis-master-controller-nyxxv" has been defined

Although you're right, it could be changed to understand that older behavior, absolutely.  Anything is possible.

**Comment by smarterclayton** [comment]
That's the discussion we are having now and in the other thread - supporting that new syntax, to allow xargs.

**Comment by smarterclayton** [comment]
And also to allow -a on get, so you can just get the ids as pods/foo, grep, and feed them back into get.

**Comment by hurf** [comment]
@smarterclayton - delivering pods/www to following command looks fine. But still unfriendly to humans. What about messages like 'Creating pod www', in a format of action/type/id? I think that would be easy to understand by human and also can be handled by the machine.

**Comment by smarterclayton** [comment]
I've spawned https://github.com/GoogleCloudPlatform/kubernetes/issues/5906 which I think covers the important case you mention - if we have a '-q' (scriptable output) we can make the default output be more verbose:

    $ kubectl create -f stuff.json
    Created pod myfoo with images foo/bar:base
    Created service myfoo over labels baz=biz
    Created replication controller brave

and still have scriptability

    $ kubectl create -f stuff.json -q
    pod/myfoo
    service/myfoo
    replicationController/brave
