### ISSUE TITLE
Permission denied errors building master

### ISSUE THREAD

**Issue by ncdc** [GoogleCloudPlatform/kubernetes#5599]
On my system (Fedora 21), I'm now unable to successfully build master. I get permission denied errors trying to write to `/usr/lib/golang/pkg/linux_amd64_cgo/`.

```
$ ./hack/build-go.sh cmd/kube-apiserver
    cmd/kube-apiserver
go install runtime: mkdir /usr/lib/golang/pkg/linux_amd64_cgo/: permission denied
!!! Error in /home/vagrant/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:328
  'CGO_ENABLED=0 go install -installsuffix cgo "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}"' exited with status 1
Call stack:
  1: /home/vagrant/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:328 kube::golang::build_binaries(...)
  2: ./hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /home/vagrant/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:252
  '( set -x; kube::golang::setup_env; local version_ldflags; version_ldflags=$(kube::version::ldflags); local host_platform; host_platform=$(kube::golang::host_platform); local goflags; eva
l "goflags=(${KUBE_GOFLAGS:-})"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -* ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local platform; for platform in "${platforms[@]}";
do
    kube::golang::set_platform_envs "${platform}"; kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; if [[ -n ${use_go_build:-} ]]; then
        local output_path="${KUBE_GOPATH}/bin"; if [[ $platform != $host_platform ]]; then
            output_path="${output_path}/${platform//\//_}";
        fi; for binary in "${binaries[@]}";
        do
            local bin=$(basename "${binary}"); if [[ ${GOOS} == "windows" ]]; then
                bin="${bin}.exe";
            fi; if kube::golang::is_statically_linked_library "${binary}"; then
                CGO_ENABLED=0 go build -installsuffix cgo -o "${output_path}/${bin}" "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}";
            else
                go build -o "${output_path}/${bin}" "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}";
            fi;
        done;
    else
        for binary in "${binaries[@]}";
        do
            if kube::golang::is_statically_linked_library "${binary}"; then
                CGO_ENABLED=0 go install -installsuffix cgo "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}";
            else
                go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}";
            fi;
        done;
    fi;
done )' exited with status 1
Call stack:
  1: /home/vagrant/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:252 kube::golang::build_binaries(...)
  2: ./hack/build-go.sh:26 main(...)
Exiting with status 1
```

It looks like this comes from #5574. Could someone please take a look? Thanks!

**Comment by ncdc** [comment]
@ArtfulCoder @vmarmol FYI

**Comment by vmarmol** [comment]
Do a `make clean` and try again. This usually solves it for me since the configuration is stale. Let us know how that works.

**Comment by ncdc** [comment]
@vmarmol no luck - it still gives me permission denied. Here are the golang rpms I have:

golang-pkg-bin-linux-amd64-1.3.3-1.fc21.x86_64
golang-cover-0-1.0.hgd32b5854c941.fc21.x86_64
golang-vet-0-1.0.hgd32b5854c941.fc21.x86_64
golang-src-1.3.3-1.fc21.noarch
golang-1.3.3-1.fc21.x86_64
golang-pkg-linux-amd64-1.3.3-1.fc21.noarch

**Comment by vmarmol** [comment]
Hmm another potential fix it so `sudo rm /usr/lib/golang/pkg/linux_amd64_cgo/` and on the next build the binaries should be places somewhere accessible

**Comment by ncdc** [comment]
@vmarmol that doesn't help either - that directory didn't exist to begin with

**Comment by vmarmol** [comment]
Huh, that I haven't run into. Will investigate further.

**Comment by vmarmol** [comment]
I can replicate this locally, will get a fix. In the meantime, the workaround for a single binary is to use straight-up cgo: `godep go build github.com/GoogleCloudPlatform/cmd/kube-apiserver`

Sorry for the churn!

**Comment by vmarmol** [comment]
I think the issue is that these scripts were not meant to be called in this way. These scripts try to "install" the binary which by default Go tries to install in the GOROOT. This fails today because we started appending "cgo" to those paths. It succeeds when run inside the Docker build container though:

```
$ ./build/run.sh ./hack/build-go.sh cmd/kube-apiserver
```

and those get copied out as expected. I'm not sure this is worth fixing as things like `hack/build-cross.sh` fail in a similar way. Would one of the two workarounds work for your usecase? I'm guessing you're trying to get a one-off binary for testing?

**Comment by ncdc** [comment]
I normally just run `make` and then `hack/local-up-cluster.sh`. So this definitely hinders my typical workflow.

**Comment by ncdc** [comment]
That said, if there's a better way to get the same results (i.e. your build/run.sh example?) I can switch.

**Comment by derekwaynecarr** [comment]
I ran into this yesterday as well.

I had to manually install cgo (which was also a pain to do for some reason dealing with permissions).

I think the ./build/run.sh script is fine, but I don't think we actively document that approach anywhere on the Kubernetes repo as an example.

----- Original Message -----

**Comment by derekwaynecarr** [comment]
I am in favor of letting folks run hack/build-go.sh on their host if at all possible.

----- Original Message -----

**Comment by vmarmol** [comment]
Ah `make` is failing, that we'll need to fix. Will look into it.

**Comment by ncdc** [comment]
Yeah, it's `hack/build-go.sh` via `make`

**Comment by vmarmol** [comment]
@ncdc after that, you expect the binaries to be in `_output` I'm guessing?

**Comment by ncdc** [comment]
@vmarmol correct, in `_output`

**Comment by jlowdermilk** [comment]
The fix that worked for some of us for the permission denied errors is in #5514

**Comment by vmarmol** [comment]
A fix (as @jlowdermilk points out) is to manually create that directory (`sudo mkdir /usr/lib/golang/pkg/linux_amd64_cgo/`), but that feels wrong...I guess we can surface that suggestion when we hit the error and continue from there.

**Comment by ncdc** [comment]
I can't say I'm particularly interested in using `sudo` or making the dir world writable.

**Comment by derekwaynecarr** [comment]
We need to make the script verify the user has installed the necessary go tools as a prereq to running the script.  We need to them make a script to actually tell the user to run X in order to install the prerequisite go tools.

**Comment by vmarmol** [comment]
@derekwaynecarr what Go tools are missing? and what platform are you running on? In Linux, the default Go installation includes everything.

**Comment by derekwaynecarr** [comment]
@vmarmol I am on Fedora 20 ... I had to manually install cgo yesterday to get around the problem.

**Comment by vmarmol** [comment]
@derekwaynecarr interesting I didn't know cgo was a thing to install. Do you mean gccgo?

**Comment by derekwaynecarr** [comment]
@vmarmol - I had to manually run $go install -installsuffix cgo with a user that had authority to write to the directory this PR mentions.  Which meant I had to sudo and ensure my sudo user had the GOPATH set right.

----- Original Message -----

**Comment by ArtfulCoder** [comment]
I am checking if we can have go install create the cgo library in a different non-root-protected path.

@derekwaynecarr @vmarmol @thockin

**Comment by derekwaynecarr** [comment]
I think if you set $GOTOOLS to a different location, it will use that, but I have not tried.

----- Original Message -----

**Comment by thockin** [comment]
This keeps biting me too.  Can we just rollback the CGO change and only use
it when building a release?  Is that viable?

Have I ever mentioned how much I despise the go tools?  I just want them to
do something reasonable and NOT try to write to their own base dir.

**Comment by thockin** [comment]
try this as a one-time fix:

sudo CGO_ENABLED=0 go install -a -installsuffix cgo std

**Comment by ncdc** [comment]
I was trying to avoid having to use sudo to install to a system-owned location if possible

**Comment by thockin** [comment]
The go team says there is no way to rebuild the standard library and
install it to a private place.  Bug has been filed with them, but don't
hold your breath - it might be a while.

**Comment by ncdc** [comment]
Ok, then I guess as long as this is documented somewhere, we can close.

**Comment by thockin** [comment]
Leave this open until we have a useful error message and docs.  Abhi is on
it.

**Comment by rrati** [comment]
Since the change that brought this in affects a simple make, can we do what @thockin suggested and conditionalize the cgo stuff?  Having make install anything to a system directory seems a very bad practice.  Built binaries should be located in the build tree with either a separate action to install them or a completely manual step (like make install)

**Comment by smarterclayton** [comment]
I'm also seeing this fairly consistently (different error)

```
$ hack/build-go.sh --use_go_build
+++ Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/e2e
    cmd/integration
    cmd/gendocs
    cmd/genman
    examples/k8petstore/web-server
# github.com/ghodss/yaml
Godeps/_workspace/src/github.com/ghodss/yaml/yaml.go:10: import /data/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/pkg/linux_amd64/gopkg.in/yaml.v2.a: not a package file
# github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource/quantity.go:26: import /data/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/pkg/linux_amd64/github.com/spf13/pflag.a: not a package file
# github.com/GoogleCloudPlatform/kubernetes/pkg/util/fielderrors
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/fielderrors/fielderrors.go:23: import /data/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/pkg/linux_amd64/github.com/GoogleCloudPlatform/kubernetes/pkg/util/errors.a: not a package file
# github.com/GoogleCloudPlatform/kubernetes/pkg/probe/http
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/probe/http/http.go:26: import /data/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/pkg/linux_amd64/github.com/GoogleCloudPlatform/kubernetes/pkg/probe.a: not a package file
# github.com/GoogleCloudPlatform/kubernetes/pkg/version/verflag
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/version/verflag/verflag.go:26: import /data/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/pkg/linux_amd64/github.com/GoogleCloudPlatform/kubernetes/pkg/version.a: not a package file
# github.com/GoogleCloudPlatform/kubernetes/pkg/util
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/diff.go:26: import /data/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/pkg/linux_amd64/github.com/davecgh/go-spew/spew.a: not a package file
!!! Error in /data/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:318
  'go build -o "${output_path}/${bin}" "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}"' exited with status 2
Call stack:
  1: /data/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:318 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /data/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:252
  '( kube::golang::setup_env; local version_ldflags; version_ldflags=$(kube::version::ldflags); local host_platform; host_platform=$(kube::golang::host_platform); local goflags; eval "goflags=(${KUBE_GOFLAGS:-})"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
```

**Comment by vbatts** [comment]
//cc @vbatts

**Comment by vbatts** [comment]
for the record, this issue has come up before in the fedora build. The issue is due to packages that are built across the x86, x86_64 and arm builders are then collated. Some of these non-arch-specific packages are identical and therefore clobbered by the last builder to finish. The rpm `golang-src-1.3.3-1.fc20.noarch` is likely from the arm builder, so the timestamps in that rpm can be older than the `cgo.a`  provided by `golang-pkg-bin-linux-amd64-1.3.3-1.fc20.x86_64`.
Depending on the build process, something like `go install` will see the `cgo.a` as outdated, and attempt to reinstall it. It is a pain.
For reference: http://koji.fedoraproject.org/koji/buildinfo?buildID=582075

**Comment by filbranden** [comment]
Just happened to me on a fresh checkout. Quite annoying.

If we start having more dependencies (like "cgo", assuming the issue is I don't have "cgo" on my new workstation), maybe the build script should check for that and warn if it's not available? Much better than throwing an ugly build error on me...

**Comment by thockin** [comment]
Abhishek is supposed to be getting us a better error message :)

**Comment by brendandburns** [comment]
Marking down to P2.  It's annoying, but the fix is documented.  Developer experience == P2, we need to focus on users using binaries.

**Comment by Zempashi** [comment]
Same here, trying to make a PKGBUILD for archlinux. As makepkg (packager in Arch) cannot be run as root anymore, we cannot have kubernetes in AUR (https://aur.archlinux.org/packages/) ...

**Comment by thockin** [comment]
Are you willing to use non-static binaries?  We could maybe add YET ANOTHER
flag to do non-static if asked for

**Comment by Zempashi** [comment]
I just look to libs needed by kubernetes, and none of them are already package in AUR. It also means that you will receive bug report that something don't work because old lib has been used, or newer than kubernetes might expect. As far I understand (I'm not Go expert, so I'm not getting kind of packaging all those lib myself), I think that will raise much more problem that it will solve. I'll try to make a build dependency with cgo to make the /usr/lib/golang/pkg/linux_amd64_cgo available just before the build of kubernetes it-self

**Comment by eparis** [comment]
//cc @eparis

**Comment by eparis** [comment]
Instead of refusing to let things work, why not just use go build, which takes longer, but should at least work for people....

https://github.com/GoogleCloudPlatform/kubernetes/pull/6953

**Comment by ArtfulCoder** [comment]
Does e2e pass with your changes ?

**Comment by davidopp** [comment]
@ncdc Please re-open if this is still an issue.
