### ISSUE TITLE
Proposal: Support cluster info via API

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#5608]
It would make end to end tests much saner if we could have programs ask the cluster they are connected to about its characteristics:
* The provider.
* What add-ons are enabled (e.g. monitoring, logging, DNS).

etc.

How about something like:
```
GET <host>/api/v1beta3/clusterinfo
```
to retrieve a JSON object that contains such information?

Then we can blow away lots of information in flags and environment variables.

**Comment by satnam6502** [comment]
@zmerlynn @ixdy @quinton-hoole

**Comment by zmerlynn** [comment]
I'd actually like to get this as part of #5472. Some way for things to query the existing "as deployed" state.

**Comment by zmerlynn** [comment]
Though that obnoxiously does mean it's a real API object, versus just a client side versioned object as originally proposed. Hrm.

**Comment by zmerlynn** [comment]
But, separately, I don't think the tests want to query a monolithic cluster object. As I've ranted before, I think the tests in general want to query for fine grained *capabilities*, and we have coarsely lumped these in with very specific providers that are currently able to provide them (sometimes variably!). For example, it's only whimsically that gce providers most of the services for most of the tests - most of the checks for provider == gce are actually bogus and could/should be rewritten in a provider agnostic fashion.

As for the add-ons, it's actually not hard to query that they're running. We can just check that the system pods are on running or not. After #5135, this is true before e2e tests start.

**Comment by satnam6502** [comment]
Seems like @zmerlynn has this in hand.
