### ISSUE TITLE
Create a pod manager in kubelet to manage internal pods and mirror pods

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#5615]
This is resulted from the discussion of #5401 and #5555.

Kubelet keeps an array of pods internally and use a lock to protect its access. The same lock is used to protect the access of the internal mirror pod map, as this map needs to be in sync with pods.  We should create a pod manager which manages all such data structures for code clarity and to prevent obscure bugs from being injected.

We may also consider incorporating pod status map into the pod manager.

/cc @vmarmol

**Comment by wojtek-t** [comment]
+1 - I think it will simplify the code a lot
