### ISSUE TITLE
Allow DNS names to be used in service publicIP's list

### ISSUE THREAD

**Issue by jmreicha** [GoogleCloudPlatform/kubernetes#5626]
I am working on automating Kubernetes deployments and was wondering how difficult (if it is even possible even) to add support for DNS names in the service publicIP definition.

For example, I am spinning up nodes dynamically so I often don't know the IP in advance which makes it difficult to script.  My thought was that referencing a DNS name there might make automation easier.

So instead of this:

```
"publicIPs": [
      "1.2.3.4",
      "1.2.3.5"
    ],
```

something like this:

```
"publicIPs": [
      "server1.domain.internal",
      "server2.domain.internal"
    ],
```

**Comment by thockin** [comment]
The problem here is that the resolution of a DNS name can change over
time.  Accepting a DNS name here implies that we will respect DNS TTL and
refresh the resolved IP periodically.  That's some work we would rather
avoid.  It's not SUPER difficult it's just not something we do today.

**Comment by jmreicha** [comment]
@thockin I understand :)

The other thing I'm working out how to do right now is how to handle if a server goes down that is hosting a service.  Right now I am just deleting the service by hand and recreating it with updated IP addresses.  Is there a better way to do this?

**Comment by thockin** [comment]
A service in general should be independent of any one host.  This is only
not true if you have your publicIPs set to a single host IP.  You should be
able to put all of your host IPs into publicIPs and get rid of the SPOF.

**Comment by hobti01** [comment]
Like @jmreicha I want to dynamically or periodically change the PublicIPs as Nodes join or leave the cluster.   I've noticed that the iptables rules are only changed if the service is deleted and re-created.  @thockin is this intended?

**Comment by thockin** [comment]
iptables rules should be updated if the set of public IPs changes.  If that
isn't true, it's a bug.  I just tested on a fairly recent cluster and it
works.
