### ISSUE TITLE
Update pkg/kubelet/config to v1beta3

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#5630]
This isn't strictly blocking v1beta3 enablement #5475, nor did it block elimination of BoundPods. However, at some point prior to 1.0 we're going to nuke ContainerManifest and v1beta1. Kubelet should start consuming v1beta3 sooner rather than later.

Additionally, pkg/kubelet/config/http_test.go serializes api.ContainerManifest in several places. The internal representation should never be serialized. This is blocking removal of the json tags from pkg/api/types.go #3933.

**Comment by yujuhong** [comment]
There is a WIP PR for reading pods: #5598. BoundPods have been removed in kubelet already.

#5632 to fix http_test.go

**Comment by wojtek-t** [comment]
Thanks for the http_test.go fix @yujuhong !

cc @vmarmol 
As for this issue, I think that #3372 is a prerequisite for this. I'm currently working on adding a support for reading Pods via http source (#5598). Once done with it, I will also modify the file channel.

As soon as both are done, I think we can start thinking of getting rid of support for ContainerManifest from there. I'm also happy to work on it.
@bgrant0607 : What deprecation policy do we have? Can we just simply remove support for ContainerManifest (obviously assuming that all tests & scripts are working correctly) or should we do something before it?

**Comment by vmarmol** [comment]
@wojtek-t since the Container VM relies on, and we publish examples using, the ContainerManifest I don't think we can remove our ability to take it in just yet. We should at least announce the deprecation in Container VMs and change all our examples. A tool to change manifests would be nice too, I think we can do that today easily as well.

**Comment by wojtek-t** [comment]
Thanks Victor. Just few questions:
1. How/where should we announce deprecation?
2. Can you point me to Container VM code/examples so that I can change them?
Once Kubelet supports reading pods via http & config file, I'm happy to start changing our examples (and also create such tool).

**Comment by bgrant0607** [comment]
@vmarmol @wojtek-t ContainerVM is not a product. It is used by internal teams. However, we're not committed to continuing to improve and evolve ContainerVM for them. We should announce the deprecation of ContainerVM ASAP. We're definitely going to nuke it along with the rest of v1beta1 if not sooner.

**Comment by dchen1107** [comment]
@bgrant0607 That is what I thought for a while until EricH pointed me this public page: https://cloud.google.com/compute/docs/containers/container_vms

Sounds like we talked about it, but no real action is performed.

**Comment by wojtek-t** [comment]
As soon as #3372 is done (all necessary PRs are already under review), Kubelet will support reading both Pods and ContainerManifest. I looked through the Kubernetes codebase and it seems that there are no references to ContainerManifest anywhere.

So I think that the only remaining work here would be related to ContainerVM. However, from the internal discussions it seems that there is still no consensus what we're going to do with ContainerVM. So I'm not sure if we can do anything about it right now.

**Comment by wojtek-t** [comment]
pkg/kubelet/config currently supports v1beta3 (in addition to ContainerManifest).
Since there is no clear plan what to do with ContainerManifest (and since removing is part of getting rid of v1beta1), I'm closing this one as fixed.
