### ISSUE TITLE
Heapster collects node and pod events

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#5638]
Events are helpful for traceability and system performance analysis. Long term storage of event data will be in a monitoring/storage backend of user's choice. Heapster is well suited for being an events proxy since it is built to handle multiple backends.

**Comment by dchen1107** [comment]
cc/ @saad-ali is doing some similar work. Let's not duplicated the efforts on this.

**Comment by saad-ali** [comment]
Good idea @vishh. My vision for events is an event proxy that can pipe events to a swapable persistent store--which aligns with what you're proposing here. Current proposal for event handling is outlined in #4432. I'm working on part b of that proposal right now. I'll sync up with you once I'm done with that.

**Comment by saad-ali** [comment]
Sync'd with @vishh offline, we agreed that we have the same long term goals (an event proxy able to pipe events to any persistent store), and so it makes sense to align our efforts early (and avoid duplicating work). I will be pivoting my proposal in #4432 to use heapster instead of creating a separate process inside a container that uses the API server to fetch events and stores them to a log on disk. I should be able to reuse most of the code that I've written so far.

**Comment by thockin** [comment]
Can we calrify the bounds of what is required for 1.0 vs what can be handled after?

**Comment by dchen1107** [comment]
+1 on including this for 1.0

**Comment by saad-ali** [comment]
For 1.0 I'd like to see Heapster able to store events to one persistent store (basically for 1.0 we should have a story for retrieving historical events that have timed out of the etcd temp storage).

**Comment by dchen1107** [comment]
@saad-ali I am assigning this to you since you already worked on this very topic.

**Comment by vishh** [comment]
+1 to @saad-ali's statement. Immediate goal is to enable long term storage of events. Post 1.0 the plan is to transition events completely out of etcd, cache them in some persistent store and provide access via the apiserver.

**Comment by a-robinson** [comment]
Note that it's frustrating that we currently completely drop events on the floor after 2 hours. Adding some sort of persistence (even just a stop-gap fix of logging to disk on the master) soon would be very appreciated.

**Comment by saad-ali** [comment]
@a-robinson Agreed, I'm working on this at the moment.

**Comment by vishh** [comment]
@a-robinson: What is the use case for events? How much do we rely on events for introspection or debugging? I am assuming events are meant for traceability and performance analysis.

**Comment by a-robinson** [comment]
Events are the [first debugging mechanism listed in our wiki](https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ#by-symptom) for debugging pods not running.

**Comment by vishh** [comment]
There are two parts to this issue. 
1. Storing events
2. Easy access to events
I think '1' is required for v1.0. '2' probably a stretch for v1.0. `kubectl get events` falls under '2'. Our logging infrastructure should capture events as part of log files. So if everything fails, events are at-least available as part of logs for introspection purposes.
@dchen1107: Any thoughts on priorities?

**Comment by dchen1107** [comment]
I agreed with @vishh on priority of issues.

**Comment by saad-ali** [comment]
Closing with PR #7751 - Enable GCM and GCL instead of InfluxDB on GCE
