### ISSUE TITLE
Services seem broken in 0.13.x

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#5647]
* Deploy a `replicationcontroller` (you can use `examples/cassandra`) with `replicas=2`
* Deploy a `service`
* Try to access the service, or you can check `iptables -t nat -L` and look for `KUBE-PORTALS-HOST` chain

On `0.12.2`
```
Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             10.100.0.2           /* kubernetes */ tcp dpt:https to:10.0.2.15:41532
DNAT       tcp  --  anywhere             10.100.0.1           /* kubernetes-ro */ tcp dpt:http to:10.0.2.15:36123
DNAT       tcp  --  anywhere             10.100.4.232         /* monitoring-influxdb */ tcp dpt:http to:10.0.2.15:54264
DNAT       tcp  --  anywhere             10.100.127.106       /* monitoring-grafana */ tcp dpt:http to:10.0.2.15:47723
DNAT       tcp  --  anywhere             10.100.140.15        /* monitoring-heapster */ tcp dpt:http to:10.0.2.15:37965
```

On `0.13.{1,2}`
```
Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination
```

* Now, try to `resize --replicas=4 replicationcontroller cassandra`
And check for pods being in state `UNASSIGNED`.

**Comment by pires** [comment]
You can also try to run a naked pod and just access `KUBERNETES_RO_SERVICES_HOST`. See https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/50

**Comment by thockin** [comment]
Can you clarify what isn't working?  I can spin up a GCE cluster and ping
from pod-to-pod and hit services.

Could it be a flannel thing on CoreOS?

**Comment by pires** [comment]
I'm testing CoreOS 681.0.0 and doesn't work with `0.13.x` but works with `0.12.2`. The only difference I'm spotting here is that the iptables rules are not set correctly when using `0.13.x`, as stated in the issue description.

Will try and gather more feedback.

**Comment by thockin** [comment]
Ah, I missed the iptables bit.

Is kube-proxy runnign?  Can you show me what flags it is running (ps auxw |
grep kube-proxy)?

Can you send me the logs from kube-proxy?

**Comment by pires** [comment]
I spotted the difference. In `0.13.x` the flag `--etcd_servers` is gone in favor of `--master`.

Will try and close if it works.

**Comment by pires** [comment]
Why the usage of `--master` in `kube-proxy` and `--api_servers` in `kubelet`? `--help` also doesn't specify the URL format (or it it's an URL at all).

**Comment by pires** [comment]
Works with `--master` but will leave this since I'm seeing some people discussing this on IRC as well. Feel free to close it.

**Comment by thockin** [comment]
We're moving away from direct etcd access in favor of going through our API
server
