### ISSUE TITLE
apiserver server non-responsive

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#5650]
**Issue:** 
With recent changes, we've shifted the burden from a collective hammering of etcd to shift the hammering through the apiserver.  As a result we're now seeing the apiserver go non-responsive at times.  This is fairly easy to reproduce: 

**Setup:**
23 Node x 40 core per node cluster 
Client Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-912-g52e1ee9d5b96c8", GitCommit:"52e1ee9d5b96c878d0bb9beb698dd3f5b7318110", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-912-g52e1ee9d5b96c8", GitCommit:"52e1ee9d5b96c878d0bb9beb698dd3f5b7318110", GitTreeState:"clean"}

**Repro:** 
Submit guestbook example but change redis-slave-controller.json to replicate 1000 

**Results:**
\# kubectl get pods | grep Pending | wc -l 
217
\# kubectl get pods | grep Pending | wc -l 
217
\# kubectl get pods | grep Pending | wc -l 
0
\# kubectl get pods | grep Pending | wc -l 
204
\# kubectl get pods | grep Pending | wc -l 
203
\# kubectl get pods | grep Pending | wc -l 
0
\# kubectl get pods | grep Pending | wc -l 
F0319 13:32:38.952402   29676 get.go:67] Error received from API: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
0
\# kubectl get pods | grep Pending | wc -l 
123

**Expected Results:**
Steady linear progression

**Comment by derekwaynecarr** [comment]
The replication controller needs to not make 1000 concurrent requests and needs to rate limit how quickly it spawns pods.  There is a separate issue on this that I need to find, but I continue to believe we are better served not being fancy and just size up in sequence until we have bulk pod creation.

**Comment by timothysc** [comment]
@derekwaynecarr it's more then the rc now, there is a feedback loop in the system from the nodes now.

**Comment by vmarmol** [comment]
On the node side #5624 should significantly lower the load on the master. I think that is the bulk of the problem. We should have a separate issue (or this one) for the rc rate-limiting.

**Comment by lavalamp** [comment]
Someone is working on rate-limiting requests, but I can't recall who. I think there's an issue already open for it.

**Comment by lavalamp** [comment]
What is the timing between the `get pods` calls? Note that the number of pending pods isn't that informative, since you don't know if it's the same pods that are pending; you really want to know how many are pending vs. running vs failed.

**Comment by davidopp** [comment]
@lavalamp Are you thinking of #3312?

**Comment by derekwaynecarr** [comment]
@davidopp - no, different issue.

**Comment by timothysc** [comment]
@lavalamp ~2-4 seconds between calls.  Yes, Ideally I would like to know the complete status, right now I'm just doing basic verification. 

@derekwaynecarr are you referring to *this: #4866

**Comment by derekwaynecarr** [comment]
@timothysc  - yes!

----- Original Message -----

**Comment by bprashanth** [comment]
Most times I've seen "Error received from API: 501: All the given peers are not reachable ..." its been etcd oom. The apiserver would just connection refuse, or some other form of weird html looking trace if nginx is up and your go code segfaulted.

If you have a cluster in this state it would be great to have:
1. sudo service etcd status 
2. your /var/log/etcd.log
3. ls -lhR in your etcd data dir (ps shold tell you where it is, probably `/var/etcd/data`)

If nothing, this will clear my doubts. 501 is a misleading error code for this condition, but I believe the apiserver is just reacting to the etcd error code.  Maybe https://github.com/GoogleCloudPlatform/kubernetes/pull/5782 will help with that.

**Comment by wojtek-t** [comment]
I agree that this might be related to etcd errors. In particular we need to fix:
1. #6053
2. "too many open files" errors coming from etcd

**Comment by timothysc** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/5650

**Comment by wojtek-t** [comment]
cc @fgrzadkowski

**Comment by fgrzadkowski** [comment]
#6351 is tracking "too many open files" problem

**Comment by wojtek-t** [comment]
Another change that should significantly reduce the "read" load on etcd is #6349

**Comment by wojtek-t** [comment]
I was trying to reproduce this problem and failed.
I'm going to wait for the new release of etcd (with fix to #6059) and spend more time trying to replicate this problem with it.

**Comment by lavalamp** [comment]
Last update is 20 days old. Please reopen if you can still reproduce.

**Comment by timothysc** [comment]
ack, so much has shifted.
