### ISSUE TITLE
If provider flag not given to e2e tests, exits(1) with misleading message.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#5653]
running ` go run ./cmd/e2e/e2e.go` directly from source without `--provider`, you get a message that conformance test is going to run, but then, it kube just exits(1).

We should notify that its a failure and we are exiting, shouldn't we?

**Comment by zmerlynn** [comment]
You should be running this using the wrapper(s). See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md

**Comment by jayunit100** [comment]
possibly saying "run with wrappers..." would be better if explicit in the main method.
