### ISSUE TITLE
Add a cloud provider config option on kubelet

### ISSUE THREAD

**Issue by spothanis** [GoogleCloudPlatform/kubernetes#5667]
Similar to cloud provider config flag on the Kubernetes Api Server, it will be great if there is a way to do same at the kubelet level through some flag. This will allow us to do any interactions with the cloud provider at kubelet level

**Comment by vmarmol** [comment]
What cloud-provider interactions do you envision from the Kubelet? (Just curious what you had in mind, we don't do any today AFAIK)

**Comment by spothanis** [comment]
I was trying write a volume plugin for cinder and wanted to do some operations such as attach and detach volume to instance

**Comment by ashw7n** [comment]
Basically we need the ability to authenticate against Openstack and get some information about the current minion for the purposes of attaching a block device (from the cinder block storage subsystem) on the minion. We could distribute this config (among others) through salt at the provisioning time and could include keys/credentials to access the cloud apis.
