### ISSUE TITLE
kubectl get pod returns running for a pod that is dying

### ISSUE THREAD

**Issue by jmreicha** [GoogleCloudPlatform/kubernetes#5668]
Don't know if there is another ticket open for this, apologies if there is.  This is on version 0.13.1.

I noticed that if I run `kubectl get pod` I get a pod status of running even though the container I am attempting to start is constantly stopping and starting.  I'm wondering if it would be better to have the default behavior be something else if the container is stuck in a state where it is having trouble staying up, and have kubectl report it as having a problem?

**Comment by mbforbes** [comment]
From my limited knowledge, it seems like for whatever is getting pod state to know the behavior of a pod across time (e.g. that it is stopping and starting) it would have to compare its state across several observations and reason about possible patterns. This seems nice to have, but might be a bit far off feature wise.

If anyone from the node team can give an answer it'd likely be much better than my intuition.

**Comment by yujuhong** [comment]
Closing this one since there has been more discussion in #5927
