### ISSUE TITLE
Kubelet fails to provide stats for static pods

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#5688]
Since static pods are now exposed via the apiserver, users (heapster) naturally expect kubelet to provide stats for the static pods.
This is breaking heapster.

cc @yujuhong

**Comment by yujuhong** [comment]
I am not familiar with stats collection in kubelet. What type of status are you referring here?

**Comment by dchen1107** [comment]
Not status, it is resource related stats here. This is one of initial reason I want to sync static pods back to master.

**Comment by yujuhong** [comment]
I think we'll need to support pod translation for the following functions.
```
GetContainerInfo()
GetKubeletContainerLogs()
```
I will work on that.

**Comment by vmarmol** [comment]
On a side note, is Heapster breaking, breaking? Or just complaining loudly?

**Comment by vishh** [comment]
@vmarmol: Heapster fails stats collection all together if kubelet errors out. I have a filed a
heapster [issue](https://github.com/GoogleCloudPlatform/heapster/issues/170) to fix that.

**Comment by dchen1107** [comment]
@vishh how come the monitor e2e test couldn't detect such failure at the first place?

**Comment by vishh** [comment]
The e2e test looks for all monitoring pods to be present. I went the way of
looking for all pods to be picked up heapster, but was told that the pods
in the cluster could be very dynamic in the future and so the test should
only look for the pods it controls. The test cannot launch any static pods
and so it did not catch this issue.

**Comment by vishh** [comment]
One option is to run the monitoring test serially and then run other tests in parallel. @zmerlynn do you think it is possible to never run the monitoring e2e test in parallel with other e2e tests?

**Comment by zmerlynn** [comment]
We currently don't run any e2e tests in parallel, but presumably we'll have to make such exceptions at some point. Why, though?

**Comment by vishh** [comment]
I intend the monitoring e2e test to ensure all the pods existing in the
cluster irrespective of , to be captured by the monitoring pipeline.
