### ISSUE TITLE
when i run  " curl -sS https://get.k8s.io | sh" ,i get error   sh: 44: set: Illegal option -o pipefail

### ISSUE THREAD

**Issue by Jamlee** [GoogleCloudPlatform/kubernetes#5689]
I get error about set.the error information  is "sh: 44: set: Illegal option -o pipefail".my  environment is ubunt 14.10 and docker version is 1.5

**Comment by zmerlynn** [comment]
What shell? We're probably assuming bash. :)

**Comment by Jamlee** [comment]
@zmerlynn you are right

**Comment by cfrezier** [comment]
I also got this error.
Changing from "curl -sS https://get.k8s.io | sh" to "curl -sS https://get.k8s.io | bash" solved it for me.
