### ISSUE TITLE
tag 0.13.0 中ubuntu_cluster安装脚本kubelet 错误

### ISSUE THREAD

**Issue by decker502** [GoogleCloudPlatform/kubernetes#5691]
tag: 0.13.0 的
cluster/ubuntu-cluster/default_scripts/kubelet 脚本的11行，应将：

--etcd_servers=http://127.0.0.1:4001 \

改为：
--api_servers=http://MASTER_IP:8080 \

**Comment by xiang90** [comment]
@decker502 Most of the developer are more comfortable with english. Also you can send a pull request to fix this kind of small issue.

```
ubuntu_cluster installation script for kubelet is incorrect.

tag: 0.13.0
cluster/ubuntu-cluster/default_scripts/kubelet line#11：

--etcd_servers=http://127.0.0.1:4001 \ should be --api_servers=http://MASTER_IP:8080 \
```

**Comment by decker502** [comment]
@xiang90 Ok, I am doing for it.

**Comment by xiang90** [comment]
@decker502 Thanks!

**Comment by erictune** [comment]
@decker502 I think your issue is fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/5245

**Comment by decker502** [comment]
@erictune Thanks!
