### ISSUE TITLE
First timer tick for a pod status update takes too long

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#5693]
It appears that the first pod status update tick is fired on average 1/2 pod status frequency duration.  This is unnecessarily long - I don't know if we have an existing issue to cover this, but it makes many small, simple pods take up to a minute to report ready (on their first time).  @vmarmol added a note to convert this to a better mechanism, but I wanted to make it obvious.

Some thoughts:

* The first transition between Pending and Running is the one that should fire with minimal latency - we should look to send these ASAP, in preference over all other status updates
* Subsequent updates can come at lower priority
* We should probably poll/check/update pod status at different intervals (inversely proportional to their age up to a cap), since most failures will happen in the first seconds of launch

**Comment by vmarmol** [comment]
Nice catch! @fgrzadkowski is working on #5624 which should alleviate this issue and is probably the right behavior.

**Comment by fgrzadkowski** [comment]
I hope to fix this by #5624.

**Comment by fgrzadkowski** [comment]
Fixed by #5624
