### ISSUE TITLE
Need gcc installed by default for vagrant auto install vbguest

### ISSUE THREAD

**Issue by netroby** [GoogleCloudPlatform/kubernetes#5696]
I am trying to setup kubernetes demo with vagrant, but i got problem with mount share folders.

I usually install vagrant-vbguest to auto update vbguest inside the guest machine.

i suggest kubernetes can installed gcc , that vbguest can compile and install vbugest for us

```
GuestAdditions versions on your host (4.3.26) and guest (4.3.20) do not match.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 4.3.26 - guest version is 4.3.20
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.26 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.3.26 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
The gcc utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.

Building the main Guest Additions module[FAILED]
(Look at /var/log/vboxadd-install.log to find out what went wrong)
Doing non-kernel setup of the Guest Additions[  OK  ]
Installing the Window System drivers
Could not find the X.Org or XFree86 Window System, skipping.

```

if you want vbguest plugin auto install vbguest for you , you need install 

```
 yum install -y yum-plugin-fastestmirror && yum update -y && yum install -y kernel-devel dkms build-essential
```

**Comment by derekwaynecarr** [comment]
Can you elaborate your intended usage of shared folders?

Are you looking to reference the examples files from the master and run kubectl there?

In general, we have recommended to run kubectl from your host machine using the cluster/kubectl.sh script.

We have not needed shared folders with code deploys because of kube-push.sh doing that differently.

I guess I am ok adding more packages to install as part of provisioning a node in the vm, but I want to understand why as people complain that initial cluster up is slow which is mostly blocked by package installs.

**Comment by netroby** [comment]
The box (fedora 20 from chef) built in with vbguest 4.3.20, but it is out of date. and when we boot up kubernetes with vagrant , it will failed and hang up, due to the boot can not success without warning.


I guess we can update the box we using to boot up by vagrant (Including the latest vbguest agent)

**Comment by derekwaynecarr** [comment]
I have trouble following the issues you open and close and if you resolve a problem or not.  

I have not experienced issues you at describing.

What host operating system are you using and can you elaborate why you needed shared folders?

I would like to improve the experience using the environment, but it's hard to do without more detail on intended use.

**Comment by bearnard** [comment]
I'm experiencing this too.

Fresh install of vagrant
```
Vagrant 1.7.2
curl -sS https://get.k8s.io | bash

...

Removing installed version 4.3.20 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
The gcc utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.
```

**Comment by Davonchy** [comment]
How can I use gcc with vagrant machine
