### ISSUE TITLE
Add colors to output of kubectl clusterinfo command

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/kubernetes#5698]
As requested in #5694

**Comment by satnam6502** [comment]
Thank you! That was quick!

**Comment by brendandburns** [comment]
See: https://github.com/mgutz/ansi for a utility library for terminal colors.

**Comment by piosz** [comment]
I found this one https://github.com/daviddengcn/go-colortext.

**Comment by satnam6502** [comment]
I love the
```
} // if
```
lines in the source code :-)

**Comment by alahijani** [comment]
Is there a way to disable this when TERM does not support colors? :-(

**Comment by andristeiner** [comment]
Would be nice to see NO_COLOR support here: https://no-color.org/

**Comment by pglass** [comment]
For people arriving here from google, looking to disable colors for the cluster-info command, try setting `TERM=dumb`.

```bash
TERM=dumb kubectl cluster-info
```

This works for me as of kubectl v1.16.2. 

Seems an odd way to disable colors, but source for that is here: https://github.com/daviddengcn/go-colortext/blob/186a3d44e9200d7eb331356ca4864f52708e1399/ct_ansi.go#L11-L13
