### ISSUE TITLE
kubernetes on vagrant boot up error message

### ISSUE THREAD

**Issue by netroby** [GoogleCloudPlatform/kubernetes#5699]
```

==> master:     True
==> master: kubernetes-master:
==> master:     Data failed to compile:
==> master: ----------
==> master:     The function "state.highstate" is running as PID 1455 and was started at 2015, Mar 20 05:47:51.213713 with jid 20150320054751213713
```

**Comment by Jamlee** [comment]
I also occur it. @netroby  wuhan china

**Comment by derekwaynecarr** [comment]
Can you give list of steps you followed?

$ make release
$ export KUBERNETES_PROVIDER=vagrant
$ cluster/kube-up.sh

??

Can you vagrant ash master and look in journalctl -ru salt-master and see if there are any errors?

**Comment by netroby** [comment]
@derekwaynecarr yes, absolutely as the getting started guide told me.

**Comment by uruddarraju** [comment]
@netroby can you let us know if you fixed this, if yes, how ?

**Comment by netroby** [comment]
Not fix it . just gave up trying. so close it .
maybe after a while ,somebody may fixes it .

**Comment by derekwaynecarr** [comment]
If you still have the issue, then leave it open.

Can you ssh into the master and append any error output you see when doing journalctl -ru salt-master.

**Comment by derekwaynecarr** [comment]
I see the same message, but it does not prevent provisioning of the cluster.  Will look into why salt highstate is happening twice.

**Comment by derekwaynecarr** [comment]
I just tried to reproduce from HEAD this afternoon and was no longer able to reproduce.

Closing issue, but feel free to re-open if you encounter it again.

**Comment by ntquyen** [comment]
I'm getting the same error at when calling ./cluster/kube-up.sh:

```
....
==> master: ‘/srv/salt-new/reactor’ -> ‘/srv/reactor’
==> master: /home/vagrant
==> master: Executing configuration
==> master: kubernetes-master:
==> master:     True
==> master: kubernetes-master:
==> master:     Data failed to compile:
==> master: ----------
==> master:     The function "state.highstate" is running as PID 2629 and was started at 2015, Aug 14 01:05:35.850225 with jid 20150814010535850225
```

The master is up, but the minion-1 is not. There's no log in master:
```
$ journalctl -ru salt-master
Hint: You are currently not seeing messages from other users and the system.
      Users in the groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Tue 2015-02-24 15:28:11 UTC, end at Fri 2015-08-14 01:12:11 UTC. --
```

**Comment by qwang1** [comment]
@netroby @ntquyen

I met the same issue today, I deleted old vms in VirtualBox and used "vagrant destroy" to clean up the cluster, and then "./cluster/kube-up.sh" worked well. 
Hope that helps.

**Comment by Bretto** [comment]
I am getting the same and I don't know how to fix it, every time I need to "vagrant destroy" to restart...

**Comment by sangwonl** [comment]
I'm getting the exactly same issue. I found a self-answered question from stackoverflow. http://stackoverflow.com/questions/24357058/vagrant-provision-with-salt-the-function-state-highstate-is-running

> I figured out the problem.

> The minion configuration file had the startup_states: key set to highstate so the highstate command was run when the minion was booted. To fix the issue, I commented out the line in the configuration and now everything works!"

But I couldn't catch what exactly he did. Someone helps me what to try..?
