### ISSUE TITLE
Rename ConditionFull to ConditionTrue and rename ConditionNone to ConditionFalse

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#5701]
The current names seem confusing. Is there any reason why the more standard True and False wouldn't be better? Since this is in the API, if we are going to change this we need to do it ASAP.

**Comment by ddysher** [comment]
We've discussed this here
https://github.com/GoogleCloudPlatform/kubernetes/pull/2315#discussion_r21650614

Basically, @bgrant0607 proposed we might have intermediate conditions

**Comment by davidopp** [comment]
I discussed with Brian offline and he was OK with the renaming I proposed. He just didn't want the field to be a bool, which would preclude intermediate conditions. Can you please implement the renaming when you get a chance? I think it will make the code much easier to understand.

**Comment by bgrant0607** [comment]
Yes, I'm fine with the renaming. If you want it in v1beta3, please make the change by Wednesday.

**Comment by davidopp** [comment]
It's not going to be possible to do this by Wednesday since we need to wait for #5399 to be submitted (otherwise it will be a really annoying merge). Would Friday be OK, or is there some reason why there's a Wednesday cutoff for changes to v1beta3?

**Comment by bgrant0607** [comment]
I'm hoping to be able to enable v1beta3 by default next week. I don't know exactly when it will happen. If you're sure it can be done by Friday, that's probably fine.

**Comment by ddysher** [comment]
I'll move my 20% ahead to accommodate the change.  Instead of waitting for #5399, we can let this in first, I don't expect too much conflict.

**Comment by gmarek** [comment]
This is done and everything seems to be working. Closing this issue.
