### ISSUE TITLE
Can not build kubernetes

### ISSUE THREAD

**Issue by netroby** [GoogleCloudPlatform/kubernetes#5706]
```

package golang.org/x/tools/cmd/cover: unrecognized import path "golang.org/x/tools/cmd/cover"
package github.com/tools/godep
        imports github.com/kr/fs
        imports golang.org/x/tools/go/vcs: unrecognized import path "golang.org/x/tools/go/vcs"
time="2015-03-20T20:20:09+08:00" level="info" msg="The command [/bin/sh -c go get golang.org/x/tools/cmd/cover github.com/tools/godep] returned a non-zero code: 1" 

To retry manually, run:

docker build -t kube-build:build-bcbf5 /home/netroby/cluster/kubernetes/_output/images/kube-build:build-bcbf5

!!! Error in build/../build/common.sh:362
  'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:362 kube::build::build_image(...)
  2: build/release.sh:31 main(...)
Exiting with status 1
Makefile:94: recipe for target 'release' failed
make: *** [release] Error 1

```

**Comment by mbforbes** [comment]
Could you please provide a bit more information about your environment or setup? And maybe the full paste of your command and what happened? I'm wondering:
- what OS you're using
- whether you've correctly setup the Go directory structure (e.g. `~/go/src/github.com/<uname>/kubernetes/...`)
- what docker setup you have (e.g. if you're on a Mac, whether `boot2docker` is setup correctly)
- whether the _"To retry manually, run: ..."_ command from the output you pasted succeeds
- whether `make clean` and `godep restore` helps

Someone who has looked at more builds could probably give more specific help than I can from looking at what you pasted.

**Comment by derekwaynecarr** [comment]
I would say run:

```shell
$ make clean
$ make release  (or make release-skip-tests)
```

and report back with what you are seeing.

**Comment by brendandburns** [comment]
I think this is a golang thing.  Are you building with golang 1.4?

I seem to recall the path for the cover tool moved incompatibly between
golang versions.

Brendan

**Comment by netroby** [comment]
I guess the problem is can not download file from golang.org/ 

the packages can not download.

Any other solutions can download packages ? 

Such as Maven repository for java , does golang have a centre packages repository?

**Comment by mbforbes** [comment]
If you try now, does it work? I'm wondering if this could have been caused by #5708.

Otherwise, I'm not sure whether there is any other way to download Go packages. Maybe others will know.

Again, more info/output helps us debug.

**Comment by endrjuskr** [comment]
On latest version I encountered similar issue:
```
$ make release
build/release.sh
+++ Verifying Prerequisites....
+++ Setting boot2docker clock
+++ Setting boot2docker env variables
Writing /Users/askrodzki/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/askrodzki/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/askrodzki/.boot2docker/certs/boot2docker-vm/key.pem
+++ Building Docker image kube-build:cross.
+++ Building Docker image kube-build:build-a53f8.
+++ Docker build command failed for kube-build:build-a53f8

Sending build context to Docker daemon 5.402 MB
Sending build context to Docker daemon
Step 0 : FROM kube-build:cross
 ---> fd407ffd2f17
Step 1 : MAINTAINER Joe Beda <jbeda@google.com>
 ---> Using cache
 ---> aeaf62101822
Step 2 : ENV GOARM 5
 ---> Using cache
 ---> 78475a66562c
Step 3 : ENV GOOS linux
 ---> Using cache
 ---> 372f96e19899
Step 4 : ENV GOARCH amd64
 ---> Using cache
 ---> f3ec7061e402
Step 5 : RUN go get golang.org/x/tools/cmd/cover github.com/tools/godep
 ---> Running in 2167a1d95c55
package golang.org/x/tools/cmd/cover: unrecognized import path "golang.org/x/tools/cmd/cover"
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': Could not resolve host: github.com
package github.com/tools/godep: exit status 128
time="2015-03-25T21:58:57+01:00" level="info" msg="The command [/bin/sh -c go get golang.org/x/tools/cmd/cover github.com/tools/godep] returned a non-zero code: 1"

To retry manually, run:

docker build -t kube-build:build-a53f8 /Users/askrodzki/studies/kubernetes/_output/images/kube-build:build-a53f8

!!! Error in build/../build/common.sh:300
  'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:300 kube::build::build_image(...)
  2: build/release.sh:31 main(...)
Exiting with status 1
make: *** [release] Error 1
```

OS - Mac OS 10.10.2
Go version - 1.4.2
`make clean & make release` didn't work for me

**Comment by mbforbes** [comment]
It looks like the problem is that where it is being built, it can't access the Internet:

```bash
fatal: unable to access 'https://github.com/tools/godep/': Could not resolve host: github.com
package github.com/tools/godep: exit status 128
```

**Comment by endrjuskr** [comment]
'godep' is already installed on system and machine is connected to internet.

I was able to build kubernetes about one week ago on same machine.

**Comment by mbforbes** [comment]
This could be wrong, but I think sometimes the build happens inside a docker container (this shouldn't be hard to verify).

If you're inside a docker container, can you access the Internet?

**Comment by preillyme** [comment]
I'm seeing the following with vagrant: 
```
preilly@vagrant:~/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes$ docker build -t kube-build:build-9cd2f /home/preilly/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/images/kube-build:build-9cd2f
Sending build context to Docker daemon 8.501 MB
Sending build context to Docker daemon
Step 0 : FROM kube-build:cross
 ---> 10ca51b404aa
Step 1 : MAINTAINER Joe Beda <jbeda@google.com>
 ---> Using cache
 ---> c5b1d351012a
Step 2 : ENV GOARM 5
 ---> Using cache
 ---> 4ac8f728615d
Step 3 : ENV GOOS linux
 ---> Using cache
 ---> 77dbc9316de4
Step 4 : ENV GOARCH amd64
 ---> Using cache
 ---> 71a74d6d6775
Step 5 : RUN go get golang.org/x/tools/cmd/cover github.com/tools/godep
 ---> Running in 0e429565df3d
package golang.org/x/tools/cmd/cover: unrecognized import path "golang.org/x/tools/cmd/cover"
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': Could not resolve host: github.com
package github.com/tools/godep: exit status 128
INFO[0060] The command [/bin/sh -c go get golang.org/x/tools/cmd/cover github.com/tools/godep] returned a non-zero code: 1
```

**Comment by thockin-cc** [comment]
When I saw this it was because my build machine was misconfigured such that
docker containers could not access internet or could not do DNS lookup.

docker run -ti busybox ping github.com

**Comment by preillyme** [comment]
@thockin-cc it turned out to be a networking restriction on my vmware fusion vm while working remotely. Once I was back at the office everything worked as expected.

**Comment by ethiraj** [comment]
I am running into exact same error on my ubuntu-14.04.2(its VM created using VMware workstation). Also I tried ping but I am getting "ping:bad address 'github.com'". Based on the previous reply's it looks like network restriction(docker containers could not access internet or could not do DNS lookup). Does any one know how to resolve this issue or any suggestions?

**Comment by ddxgz** [comment]
Facing the same problem. 
Since it seems like a network problem, will it probably be that golang.org is banned by Chinese GFW? So it cannot download the packages inside the container. Are you guys who facing this problem all inside GFW?

**Comment by shenshouer** [comment]
I have the same issue. and no banned by Chinese GFW.
I execute go get golang.org/x/tools/cmd/cover on my local pc, and report as follow:
go install golang.org/x/tools/cmd/cover: open /usr/local/go/pkg/tool/darwin_amd64/cover: permission denied
So I think the problem is golang.org/x/tools/cmd/cover is moved. and integration to installer.
But how to resolve this issue?

**Comment by razvip91** [comment]
If you are running behind a proxy, you must enter the proxy environment variables in the Dockerfiles of the image in question. It worked for me.

**Comment by MarcoLotz** [comment]
This happens if you are under proxy. Your docker daemon may reach the outside network, but not your containers. The solution is to add the proxy information on the dockerfile.

Go to the image folder for kubernetes:
<code>cd kubernetes/_output/images/ </code>

Enter in the dir that looks like a build image, in my case was:
<code>cd kube-build:build-276235eaff</code>

Add proxy information on the very beginning of the docker file:
```bash
[...] more comments before this
# This file creates a standard build environment for building Kubernetes

FROM kube-build:cross
MAINTAINER  Joe Beda <jbeda@google.com>

# Add this proxy section below:
ENV http_proxy 'host:port'
ENV https_proxy 'host:port'
ENV HTTP_PROXY 'host:port'
ENV HTTPS_PROXY 'host:port'
```

Run:
<code>docker build -t kube-build:build-276235eaff kubernetes/_output/images/kube-build:build-276235eaff</code>

Should work now.
