### ISSUE TITLE
Changed version of Go in Godeps.json

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#5708]
#5447 committed a changed version of go into godeps.  Was this deliberate?  I don't see any discussion of it (@jayunit100).

I've almost done this by mistake as well, so I'm inclined to think it was just an oversight.

(I think this is giving me errors building, but I'm not yet 100% sure this is the cause)

**Comment by mbforbes** [comment]
Hmm, this is a good point. It does look to be accidental. I don't know. I think @brendandburns and @lavalamp would have context though I believe they are out— @smarterclayton, do you know offhand whether this is probably an accident? I guess were talking specifically about `Godeps/Godeps.json` in the [changed files](https://github.com/GoogleCloudPlatform/kubernetes/pull/5447/files).

**Comment by smarterclayton** [comment]
I believe it's an accident.

**Comment by mbforbes** [comment]
Thanks, @smarterclayton. The linked PR should fix this (assuming I don't have to do anything else with Godeps).

**Comment by a-robinson** [comment]
This was almost certainly an accident. Whenever I've updated godeps it's changed automatically to 1.3 and I've had to adjust it back manually.

**Comment by jayunit100** [comment]
Actually, jeff lowdermilk was super helpful and showed me how to update the
deps on this PR.  it was his commit which I merged into my PR, so not sure
it it was accidental or not.

Fortunately, now that k8petstore is in the go build, we will know if it
breaks anything when you revert the version back.

Thanks for noticing this.

On Fri, Mar 20, 2015 at 5:38 PM, Alex Robinson <notifications@github.com>
wrote:

> Closed #5708
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/5708> via #5733
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5733>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/5708#event-260827156>
> .
>



-- 
Jay Vyas
http://jayunit100.blogspot.com
