### ISSUE TITLE
Fails to install Kubernetes locally on ubuntu (both master and minion on one host)

### ISSUE THREAD

**Issue by Dekarti** [GoogleCloudPlatform/kubernetes#5768]
I am following the Ubuntu getting started guide (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu_single_node.md) but etcd service falls immediately after starting.

$ sudo service etcd restart
etcd stop/waiting
etcd start/running, process 29050
$ sudo service etcd status
etcd stop/waiting

**Comment by decker502** [comment]
You can check the etcd log (in '/var/log/upstart/etcd.log')  to see if there are some hints help debugging.

**Comment by Dekarti** [comment]
...
Usage: /opt/bin/etcd {start|stop|restart|status}
Usage: /opt/bin/etcd {start|stop|restart|status}
...

Only such messages`

**Comment by decker502** [comment]
Is there not `etcd` command in `/opt/bin`?

**Comment by Dekarti** [comment]
*/opt/bin* folder contains all scripts from *kubernetes/cluster/ubuntu/initd_scripts* including *etcd*

**Comment by jainvipin** [comment]
@Dekarti - initd_scripts should not be in /opt/bin, rather in /etc/init, /etc/initd/ and /etc/default directories. Can you please confirm if these files are copied there appropriately? If you ran util.sh it should have...

What version of etcd are you running? And, from what I know etcd start options haven't changed. It would also help if you can check quickly start etcd natively using `/opt/bin/etcd` and see if it pops up the same error message (which seems to be an upstart message, rather)
> Usage: /opt/bin/etcd {start|stop|restart|status}

**Comment by Dekarti** [comment]
> Copy the kube binaries into /opt/bin or a path of your choice

This guide line led me astray. All works, all thanks.
