### ISSUE TITLE
Kubernetes/pause image is platform dependent

### ISSUE THREAD

**Issue by bketelsen** [GoogleCloudPlatform/kubernetes#5770]
I'm running a K8s cluster on my Pi cluster this weekend, and one workaround I am doing right now is to build a new pause docker image for arm.  The kubelet source code has the pause image hard-coded as "kubernetes/pause:latest" which works great on amd64, but won't work on any other platform.  Would be nice to have a platform dependency here to determine the correct image, and have pause images for other architectures.

Very low priority.

**Comment by thockin** [comment]
What's an other architecture?  I thought docker only supported amd64? or
has the finally been fixed?

**Comment by bketelsen** [comment]
I don’t know what’s officially supported, but I’m running Docker on Raspbian (debian wheezy) on my Raspberry Pi cluster.  Perfect k8s test bed.
There are very few docker images for this arch though.  Nearly everything written in Go works, though.

**Comment by thockin** [comment]
Is there a way to arch-tag docker images or is it purely manual?

**Comment by bketelsen** [comment]
I’m not aware of any way to tag with architecture information.  Seems like a glaring hole in the Docker plan.

**Comment by bketelsen** [comment]
also - skynetservices/skydns-arm is the arm image for skydns.  Almost running a single node k8s “cluster”

**Comment by smarterclayton** [comment]
I believe we were discussing using LABEL on the image to track architecture - at a minimum I know Red Hat packaging and release control was planning on decorating that onto the Label in the absence of an ARCH section.

**Comment by bketelsen** [comment]
--pod_infra_container_image="kubernetes/pause:latest": The image whose network/ipc namespaces containers in each pod will use.
Just saw this in kubelet --help
So maybe I could just use that instead, but I don't see it being parsed in the kubelet source.  Will investigate further.

**Comment by thockin** [comment]
That flag should work.

**Comment by smarterclayton** [comment]
We use it (and the underlying infra works).

**Comment by bketelsen** [comment]
closing this - it works.

**Comment by vmarmol** [comment]
A work item for us may be to support official multi-arch images on the kubernetes repo.

**Comment by thockin** [comment]
I really think doing this without Docker would be a bad idea :)

**Comment by vmarmol** [comment]
Sorry, I was referring to having tags for other archs in the Docker Hub. We
won't use them by default, but they're there for others who may want to use.
