### ISSUE TITLE
Accessing stats using time range in kubelet does not work

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#5777]
Cadvisor API support querying stats between a `Start` and a `Stop` timestamp. That interface does not work via the kubelet. Is there anything special about the way cadvisor is setup when run inside kubelet?

cc @vmarmol

**Comment by vmarmol** [comment]
We don't have the right version of cAdvisor included :) will send a PR now to update it.

**Comment by vishh** [comment]
This issue is still not-fixed on HEAD.
