### ISSUE TITLE
Need validation of template field names.

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#5781]
I used following definition to create a pod:

	{
	  "id": "containermanifest",
	  "kind": "Pod",
	  "apiVersion": "v1beta1",
	  "desiredState": {
	    "manifest": {
	      "version": "v1beta1",
	      "id": "containermanifest",
	      "containers": [{
	        "name": "heapster",
	        "image": "kubernetes/heapster",
	      }],
	      "restarPolicy": {"never": {}}
	    }
	  },
	  "labels": {
	    "name": "containermanifest"
	  }
	}

The creation succeeded. But I found the restartPolicy remained to be `always`. I was confused and look again and again into the code and template. Finally I found I made a typo `restarPolicy`. It seems the engine ignored this line and used the default value of `restartPolicy`.

It's a small mistake but took me a lot of time. So I think we should validate each field of the template and warn the user about those unrecognized fields.

**Comment by gmarek** [comment]
You're 100% right, and you're by far not the first one who spent more time that is should be necessary when debugging typo. There's an open issue #3338 for finding a better JSON parser, and one of things we want from it is catching this kind of things. @smarterclayton 

Closing in favor of #3338.

**Comment by hurf** [comment]
Sorry for duplication. Though I've searched issues by the keyword 'validate', it returned too many results and I didn't find #3338.
