### ISSUE TITLE
Implementing 'Balanced Resource Utilization' algorithm in scheduler

### ISSUE THREAD

**Issue by HaiyangDING** [GoogleCloudPlatform/kubernetes#5783]
Current algorithm is simple when considering the resource and may lead to imbalanced resource utilization. Balanced Resource Utilization algorithm can be introduced as a new PriorityFunction so that users could choose to enable it when implementing custom algorithm_provider. 

See post at [Implementing Balanced Resource Utilization in kubernetes scheduler? - Containers at Google](https://groups.google.com/forum/#!topic/google-containers/d9WjncfciEg)

**Comment by lavalamp** [comment]
This was implemented a while ago.
