### ISSUE TITLE
Update "Getting started on Google Compute Engine" docs

### ISSUE THREAD

**Issue by ihmccreery** [GoogleCloudPlatform/kubernetes#5796]
I'm a recent user of Kubernetes, and I struggled a bit to get it up and running on GCE.  It looks to me like the Getting started on Google Compute Engine]() doc is a bit out of date.  I've updated the doc with what I think it should look like, and I'll link the PR here.

The main issues I found are:

- The "Getting VMs" section could be clearer, and some of the docs linked to are out of date.
- I believe `gcloud preview`  is now required for `kube-up.sh`.
- Failure is messy with `kube-up.sh`, so a note to run `kube-down.sh` in case of failure before re-running `kube-up.sh` would be helpful.

**Comment by roberthbailey** [comment]
Isaac - thanks for these fixes! (we've been a bit negligent about making sure all of our documentation stays up to date as the underlying source/examples have been churning so quickly).
