### ISSUE TITLE
"Getting started" guides should point to 'examples/' rather than have their own individual examples

### ISSUE THREAD

**Issue by ihmccreery** [GoogleCloudPlatform/kubernetes#5799]
I spent a good chunk of last week working through the "Getting started" guide for GCE and the Guestbook example.  It seems to me it would be wise to integrate these two resources more.

Right now, the [Getting Started with GCE](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md) guide has its own example to work through involving Nginx on two containers.  The docs would be more maintainable if this instead linked to a universal example, (since it doesn't depend on the provider you're using,) either involving Nginx or not, e.g. the [Guestbook example](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook).

**Comment by bgrant0607** [comment]
Totally agree. We might as well do this as part of #3671 and #6584.

**Comment by bgrant0607** [comment]
And we should document this in docs/devel/writing-a-getting-started-guide.md, which we should perhaps move to docs/getting-started-guides

**Comment by bgrant0607** [comment]
The GCE guide has been fixed, but many guides still contain API examples.

**Comment by nikhiljindal** [comment]
Hi @RichieEscarez,
Wanted to confirm that you are working on this.
Its one of the last remaining tasks for https://github.com/GoogleCloudPlatform/kubernetes/issues/5475

**Comment by RichieEscarez** [comment]
Hi @nikhiljindal , yes, ill start on this next.

**Comment by bgrant0607** [comment]
@RichieEscarez We need this done now. Reassigning.

**Comment by bgrant0607** [comment]
cc @krousey Feel free to help.

A quick search for v1beta1 shows that the following providers need to be updated:
* azure
* mesos
* juju
* fedora
* coreos/bare_metal_offline

**Comment by nikhiljindal** [comment]
Looks like updating the mesos guide is the only remaining task here.
@caesarxuchao Is that correct?

**Comment by caesarxuchao** [comment]
Yes, there is a PR #8882 for mesos.

To be clear, some getting started guides still have their own individual examples, but they are at least updated to v1beta3 now.

**Comment by bgrant0607** [comment]
Azure.

```docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-28-      printf '{
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-29-        "id": "%s",
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-30-        "kind": "Minion",
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml:31:        "apiVersion": "v1beta1",
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-32-        "labels": { "environment": "%s" }
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-33-        }' "${minion_id}" "${env_label}" \
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-34-        
```

**Comment by bgrant0607** [comment]
This is done.
