### ISSUE TITLE
Guestbook example README should point to Getting Started, not SETUP.md

### ISSUE THREAD

**Issue by ihmccreery** [GoogleCloudPlatform/kubernetes#5802]
Working through the [Guestbook example](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook), I was confused about how to get setup with an initial binary and cluster.  I think the [Step Zero: Prerequisites](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook#step-zero-prerequisites) section should point to the [getting-started guides](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides), rather than the [SETUP.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/SETUP.md) document.  SETUP.md relies on `hack/`, which is being deprecated, and just points to the getting-started guides anyway.

**Comment by roberthbailey** [comment]
LGTM.
