### ISSUE TITLE
Cannot bring up a new cluster on GCE due to failing to retrieve metadata KUBELET_TOKEN

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#5811]
I sync-ed my branch to HEAD this morning, and tried to bring up a new cluster. The operation is failed because the following error: 

Broken (or in progress) GCE Kubernetes node setup! Suggested first step:
  tail /var/log/startupscript.log

```
root@kubernetes-master:/home/dawnchen#  tail /var/log/startupscript.log
Mar 23 21:34:13 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:16 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:19 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:22 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:25 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:28 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:31 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:34 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:37 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
Mar 23 21:34:40 kubernetes-master startupscript: Waiting for metadata KUBELET_TOKEN...
```

**Comment by dchen1107** [comment]
cc/ @zmerlynn Zach, is this the one you mentioned in earlier meeting?

**Comment by roberthbailey** [comment]
FYI this log line is from: https://github.com/GoogleCloudPlatform/kubernetes/blob/4877f4504d7e056b44d3782fe399f6292660825d/cluster/gce/configure-vm.sh#L62

/cc @zmerlynn who was recently mucking with the startup scripts.

**Comment by dchen1107** [comment]
After more than half hour waiting, I kill that process, and restart it twice. Now it works. Looks like it is a transient issue.

**Comment by dchen1107** [comment]
I lowered the issue to P1 since after retrying twice, it resolved itself.

**Comment by zmerlynn** [comment]
Cluster creation on GCE has been green for a while (the red dot I see is from a timeout abort). If you see this again, please go into the cloud console and check for "kube-token" metadata on the metadata, or do `gcloud compute instances describe <master name> <appropriate zone and project flags>`  and see if the the kube-token is indeed not set.

That variable gets set [here](https://github.com/coreos/etcd/releases/download/v2.0.5/etcd-v2.0.5-linux-amd64.tar.gz) after waiting for the master to be created, and we loop in `add-instance-metadata` until we can actually bonk the variable, so off casual inspection I'm failing to see how it got in this state. I would be happy to look at a running cluster if you get it in this state again, though.
