### ISSUE TITLE
Flakey e2e test "kubectl update-demo should do a rolling update of a replication controller"

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#5821]
kubectl update-demo should do a rolling update of a replication controller

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:95
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../platforms/linux/amd64/kubectl [kubectl --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/.kubeconfig rollingupdate update-demo-nautilus --update-period=1s -f examples/update-demo/v1beta1/kitten-rc.yaml] []  <nil> Creating update-demo-kitten
Updating update-demo-nautilus replicas: 1, update-demo-kitten replicas: 1
F0323 11:42:22.425281     766 rollingupdate.go:54] Error received from API: replicationController "update-demo-nautilus" cannot be updated: 101: Compare failed ([1271 != 1295]) [1301]
[] <nil> 0xc208106e60 exit status 255 <nil> true [0xc2081244e0 0xc208124510 0xc208124530] [0xc2081244e0 0xc208124510 0xc208124530] [0xc208124508 0xc208124528] [0x615e20 0x615e20] 0xc20813b9e0}:
Command stdout:
Creating update-demo-kitten
Updating update-demo-nautilus replicas: 1, update-demo-kitten replicas: 1

stderr:
F0323 11:42:22.425281     766 rollingupdate.go:54] Error received from API: replicationController "update-demo-nautilus" cannot be updated: 101: Compare failed ([1271 != 1295]) [1301]

**Comment by quinton-hoole** [comment]
This test is failing several times a day in Jenkins:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/
I'm gonna have a shot at fixing it.

**Comment by quinton-hoole** [comment]
I've reproduced this on a private GCE test cluster.  Looks pretty straightforward to fix:

    F0323 17:49:33.086047    1898 rollingupdate.go:54] Error received from API: replicationController "update-demo-nautilus" cannot be updated: 101: Compare failed ([2767 != 2804]) [2815]

My first guess is that the resource version numbers on the update don't match?  Retry required?

**Comment by roberthbailey** [comment]
This seems like a bug with the code rather than with the test (for once).

**Comment by quinton-hoole** [comment]
Error comes from here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/6c5f7f7f64a1d86f8a1149ff51d30b9cd7ff62d4/pkg/api/errors/errors.go#L132

**Comment by bprashanth** [comment]
Its failing because something else is updating the same key at the same time (most likely the replication controller manager): https://github.com/GoogleCloudPlatform/kubernetes/blob/6e242739378fd830a62afb1375c80ad24254a85b/pkg/kubectl/rolling_updater.go#L164
It should retry the update like other parts of kubectl. Essentially you'll need to create a true/false condition that wraps around the update operation, and polls till a timeout, eg: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/stop.go#L78

**Comment by quinton-hoole** [comment]
Cool, thanks.  Yes, that's what I assumed.

**Comment by roberthbailey** [comment]
This issue hasn't been as prevalent on the GCE CI builds lately but I'm seeing it quite frequently (>20% of the time) on a different CI that we are running.

**Comment by quinton-hoole** [comment]
PR #6194 fixes this.  Out for review.
