### ISSUE TITLE
Failed to start container: unable to sethostname when calling 

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#5829]
The e2e tests started failing sometime this afternoon because docker was not able to set the hostname.

Sample e2e run: go/k8healthz/job/kubernetes-e2e-gce/3797/consoleFull
The log is full of sethostname errors:
```
Error syncing pod, skipping: API error (500): Cannot start container 48c57647f75fba98c3ed7d82574e3fdad936d87c4f352773bf7c5a1b7fe6d5c1: unable to sethostname "fluentd-to-elasticsearch-e2e-test-jenkins-minion-4gnu.c.kubernetes-jenkins.internal": invalid argument
```
kubelet uses `pod.name` as the container hostname (I am not sure why). In the example above, the hostname is 83 characters, which has exceeded the max length of 64 on the system.

The cause of this is that static pods (i.e., pods from file/http sources) use `podName-hostname` as the actual pod name so that we can distinguish pods from different nodes. #5775 replaced os.Hostname() with kubelet.Hostname. This led to the change of hostname from
`e2e-test-jenkins-minion-4gnu` to `e2e-test-jenkins-minion-4gnu.c.kubernetes-jenkins.internal`, thus exceeding the limit.

**Comment by vmarmol** [comment]
Assigning to myself, will send a quick path capping the hostname size so that we unblock the night crew :) we should get a better fix in later.

**Comment by brendandburns** [comment]
Upgrading this to P0, tests are breaking.
