### ISSUE TITLE
The Linux username 'root' is invalid.

### ISSUE THREAD

**Issue by vijayshinvabk** [GoogleCloudPlatform/kubernetes#5835]
##### Following the basic Azure guide at 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md

##### Keep getting error message "The Linux username 'root' is invalid." when running kube-up.sh
>info:    Executing command vm create
>warn:    --vm-size has not been specified. Defaulting to "Small".
>+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB
>+ Looking up virtual network
>+ Looking up cloud service
>info:    cloud service kube-3d9d745 not found.
>+ Creating cloud service
>+ Retrieving storage accounts
>+ Configuring certificate
>+ Creating VM
>+ Deleting cloud service
>info:    Error information has been recorded to /root/.azure/azure.err
>error:   The Linux username 'root' is invalid.
>error:   vm create command failed

##### The azure.err file has the following output

>Tue Mar 24 2015 06:22:33 GMT+0000 (UTC):
>{ [Error: The Linux username 'root' is invalid.]
>  code: 'BadRequest',
>  statusCode: 400,
>  requestId: '18b083862d6388d68bf936f445c97f57' }
>Error: The Linux username 'root' is invalid.
>    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
>    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
>    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
>    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:129:22)
>    at Request.EventEmitter.emit (events.js:98:17)
>    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:873:14)
>    at Request.EventEmitter.emit (events.js:117:20)
 >   at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:824:12)
>    at IncomingMessage.EventEmitter.emit (events.js:117:20)
>    at _stream_readable.js:920:16

**Comment by vijayshinvabk** [comment]
This was happening because I had run **sudo su**

**Comment by roberthbailey** [comment]
Does that mean this is no longer an issue?

**Comment by vijayshinvabk** [comment]
Yes you can close it. Running **kube-up.sh** after **sudo su** had caused the issue.

**Comment by roberthbailey** [comment]
Great! I'm glad you were able to find a fix.
