### ISSUE TITLE
Allow one yaml file contain multiple resources

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#5840]
As discussed in [https://groups.google.com/forum/#!topic/google-containers/vA8vIfZ7WUA](https://groups.google.com/forum/#!topic/google-containers/vA8vIfZ7WUA), we can make some small changes to allow one yaml file contain multiple resources to reduce the file amount of a complex system.

**Comment by bgrant0607** [comment]
Already supported:
```
$ cd examples/guestbook/v1beta3
$ cat *services.json | ../../../kubectl.sh create -f -
services/frontend
services/redis-master
services/redis-slave
```

**Comment by bgrant0607** [comment]
How are you separating distinct yaml objects?

**Comment by bgrant0607** [comment]
Ok, works for json, but is broken for yaml. `---` and `...` don't appear to work.
@ghodss

**Comment by bgrant0607** [comment]
Ah:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/Godeps/_workspace/src/gopkg.in/yaml.v2
  Multi-document unmarshalling is not yet implemented,

**Comment by bgrant0607** [comment]
Actually, this works if one creates an array of items:
```
apiVersion: v1beta3                                                                              
kind: List                                                                                       
items:                                                                                           
  - #list of API objects
```

**Comment by jiangyaoguo** [comment]
@bgrant0607 Make a separate resources list file?

**Comment by bgrant0607** [comment]
@yaoguo What do you mean by "separate"? The point is to put multiple objects into one file.

**Comment by bgrant0607** [comment]
Hmm. Apparently this is supposed to work:

**Comment by bgrant0607** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/e14d5f3416801306ff2855456cf6a656e8a58403/pkg/util/yaml/decoder.go#L67

**Comment by jiangyaoguo** [comment]
@bgrant0607  Oh, I see.
 Maybe My idea was off the topic.  I thought we could have a new file to declare all the resources to be created, just like what "top.sls" file do in saltstack.  Further we can use this new file to describe  resoueces order, dependence, and so on.

**Comment by andronat** [comment]
I just tested this issue by transforming `examples/guestbook/frontend-controller.json` and `examples/guestbook/frontend-service.json` into **one** yaml file and then running: `cat test.yaml | ~/gopath/bin/kubectl create -f -` and `cat test.yaml | ~/gopath/bin/kubectl delete -f -`. Both command worked with the merged yaml file. 

I also tried `cat test/* | ~/gopath/bin/kubectl create -f -` by having 2 **separated** yaml files and still works.

Is there any other scenario that fails? Because I can't find any change relevant to this issue on the kubectl's code after Jan 14. I also rolled back in a commit in Arp 24 and still works there too.

**Comment by hurf** [comment]
@andronat - I think it works fine. The issue is about json files contain `{}` as a seperator, but yaml files don't, so I don't know how to seperate multi resources in one yaml file. Now we know we can use `---` as a seperator in yaml files.

**Comment by bgrant0607** [comment]
@andronat Without a separator, multiple YAML objects are treated as a single map.

**Comment by andronat** [comment]
Do we want to enable it without `---` separator?

**Comment by andronat** [comment]
@bgrant0607 do we want to support plain object concatenation like this?
```
  kind: "ReplicationController"
  apiVersion: "v1beta3"
  metadata:
     .........
  kind: "Service"
  apiVersion: "v1beta3"
  metadata:
     .........
```
Or it is just a matter of writing documentation or warning to users to use the proper YAML syntax of ```---``` to separate their objects?

**Comment by erictune** [comment]
I don't think we'd be able to clearly draw a line between a single object
which erroneously contains several duplicate keys and several objects.
 So, supporting object concatenation is out for yaml.  Could be supported
for json.

Doing something like `warning: duplicate key 'kind' in single object.
Hint: separate multiple objects with '---'` seems fine?

**Comment by bgrant0607** [comment]
Last time I tried, `---` worked for some input sources but not others (e.g., files). Stdin is handled differently than actual files, IIRC.

**Comment by andronat** [comment]
This is done. It can be closed

**Comment by bgrant0607** [comment]
FYI, the right way to make that happen is to write `Fixes <issue>` in the PR description.
