### ISSUE TITLE
v1beta3 service api is not supporting containerPort anymore

### ISSUE THREAD

**Issue by simon3z** [GoogleCloudPlatform/kubernetes#5850]
It seems that the v1beta3 service is not supporting the `containerPort` attribute anymore, I had to change my service definition using `targetPort`:

     metadata:
       labels:
         name: monitoring-influxdb
         kubernetes.io/cluster-service: "true"
       name: monitoring-influxdb
     spec:
    -  containerPort: 8086
    +  targetPort: 8086
       port: 80
       selector:
         name: influxGrafana

I am pretty sure I was using containerPort few days ago, I didn't bisect because I don't think it's worth spending time on this before knowing if `containerPort` is still supported and if it should be converted sever-side to `targetPort`. Thanks.

**Comment by saad-ali** [comment]
@thockin made the change in PR #5729 to rename Service.ContainerPort to TargetPort

**Comment by simon3z** [comment]
@saad-ali thanks! I actually just found it. So it seems that `containerPort` is gone for good with no plan of backward compatibility (internal conversion to `targetPort`). Which means that a bunch of scripts in the wild should be updated (e.g. heapster, etc...). Is that correct @thockin ?

**Comment by simon3z** [comment]
Please let's at least fail hard on creation, rather then silently ignore `containerPort` and then generate a wrong endpoint.

**Comment by thockin** [comment]
Only in v1beta3 which is not even on by default.  We could be compatible
here, but I know @bgrant0607 was hoping to go out clean in v1b3.

**Comment by abonas** [comment]
cc @itamarh

**Comment by thockin** [comment]
Put another way there are still a few changes cooking for v1b3

**Comment by simon3z** [comment]
@thockin fine by if there are hard-failures where possible. This seems one of those cases where you can: any idea why specifying a containerPort is not failing? (It should be an unknown attribute).

**Comment by abonas** [comment]
@thockin I'd be happy to learn what are the changes (especially the backwards incompatible ones) and what is their timeline.
I thought that v1b3 is about to be enabled this week based on this comment, is that still correct?
https://github.com/GoogleCloudPlatform/kubernetes/issues/4940#issuecomment-82130607

**Comment by thockin** [comment]
@abonas - mad scramble to get last changes in - hoping for this week

@simon3z - the go JSON parser ignores unknown data.  We don't hard-stop on invalid data anywhere.

@bgrant0607 as an idea for breaking changes like this, we could leave "traps" for old field names.  E.g. if you specify containerPort we fail validation.

**Comment by simon3z** [comment]
@thockin you probably meant "we don't hard-stop on *unknown* data" (known data is parsed and partially validated, e.g. missing names, etc.)

Generally ignoring unknown data is "nice" because you don't get bothered about other less useful keys that are changed and that are going unoticed, but it creates these traps.

Also you don't know how many old recipes there could be out there that are silently working with missing nits. And in the future someone may even be able to run newer formats on old api and maybe important keywords will be ignored.

In general I'd vote for a stricter policy on unknown fields.

**Comment by abonas** [comment]
> @thockin you probably meant "we don't hard-stop on unknown data" (known data is parsed and partially validated, e.g. missing names, etc.)
> 
> Generally ignoring unknown data is "nice" because you don't get bothered about other less useful keys that are changed and that are going unoticed, but it creates these traps.
> 
> Also you don't know how many old recipes there could be out there that are silently working with missing nits. And in the future someone may even be able to run newer formats on old api and maybe important keywords will be ignored.
> 
> In general I'd vote for a stricter policy on unknown fields.

:+1:

**Comment by bgrant0607** [comment]
Try `kubectl --validate` to catch unknown field names.

We really shouldn't have any unknown field names in an existing API version, since we only make incompatible changes in new API versions.

**Comment by bgrant0607** [comment]
Yes, all the v1beta3 examples need to be updated.
https://github.com/GoogleCloudPlatform/kubernetes/search?utf8=%E2%9C%93&q=v1beta3+containerport

**Comment by bgrant0607** [comment]
cc @nikhiljindal since some of the v1beta3 tests may fail now.

**Comment by thockin** [comment]
damn, I don't know how I missed the examples.  Mea culpa, I hang my head in shame.  PR coming ASAP

**Comment by thockin** [comment]
ah, actually I got all the examples but one.  Your query also catches ContainerPort structures.

**Comment by thockin** [comment]
Even better - the example I thought I missed was v1beta1.  I did it right.  I hold my head with pride :)

**Comment by thockin** [comment]
As for strict input, we simply can't have it until we replace the JSON parser.

**Comment by bgrant0607** [comment]
Not true. We have a validation pass that compares with the swagger pulled from the server, which is preferred to baking in a schema into the client.

**Comment by simon3z** [comment]
So even in the long-term the client-driven validation (probably not all clients have this functionality) is preferred to server-side validation?

**Comment by bgrant0607** [comment]
@simon3z The client-side validation has the benefit of existing today. We should probably also do better server-side validation, but need to think through version-skew cases. Programmatic clients may have different assumptions than generic clients like kubectl.

**Comment by brendandburns** [comment]
Closing as the parse ignoring unknowns is working as intended given --validate, and the moving of examples to v1beta3 is documented elsewhere.

**Comment by abonas** [comment]
@brendandburns , @bgrant0607 what about REST api users? they can't pass --validate

**Comment by bgrant0607** [comment]
@abonas: @simon3z filed #5889 for server-side validation.
