### ISSUE TITLE
kubectl log spits out "Unexpected path for command running" when only a pod name is specified

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#5861]
On a cluster running 0.13.2, I ran `kubectl get pods`, picked out the name of a pod that only contains a single container, let's call it foo, and then ran `kubectl log foo`. It prints nothing other than the message "Unexpected path for command running". If I add on the container name (`kubectl log foo container`), then it prints nothing, presumably because the pod has no logs.

The docs for kubectl log say that the container name is optional if the pod only has one container, so I wouldn't expect this response.

**Comment by mbforbes** [comment]
+1, we're having to work around this on guides

**Comment by a-robinson** [comment]
@jlowdermilk
