### ISSUE TITLE
Race condition in integration test cases "FAILED: mirror pod has not been created" error

### ISSUE THREAD

**Issue by multilinear** [GoogleCloudPlatform/kubernetes#5872]
The bug is around line 261 in "cmd/integration/integration.go"
It seems that the test is expecting a file just written to have appeared immediately, and that doesn't seem to actually occur.
Here's the chunk of code I'm talking about:

podName := fmt.Sprintf("%s-localhost", desc)
      namespace := kubelet.NamespaceDefault
      if err := wait.Poll(time.Second, time.Minute*10,
        podRunning(c, namespace, podName)); err != nil {
        if pods, err := c.Pods(namespace).List(labels.Everything()); err == nil {
          for _, pod := range pods.Items {
            glog.Infof("pod found: %s/%s", namespace, pod.Name)
          }
        }
        glog.Fatalf("%s FAILED: mirror pod has not been created or is not running: %v", desc, err)
      }

When run on *some* systems (it seems to depend on something like filesystem, exact arch, whether you're in boot2docker, etc.) this eventually outputs the following error:

F0324 19:38:20.698010     696 integration.go:368] static-pod-from-manifest FAILED: mirror pod has not been created or is not running: Pod status is "Unknown"
!!! Error in hack/test-integration.sh:43
 '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1"' exited with status 255
Call stack:

When I add "time.Sleep(30 * time.Second)" it works, on at least one system that it did not work on previously. If a sleep fixes it, it must be a race. I'm not sure of the best solution, the sleep works, but is of course absolutely horrid.

thanks!

**Comment by yujuhong** [comment]
Hi @multilinear, thanks for reporting the bug!

The test was supposed to poll every second until the 2 minutes timeout, so the extra sleep should not be needed. There was a bug causing problems, and it was fixed by #5775 yesterday. Are you running HEAD? If not, could you try running again with HEAD? Thanks!

**Comment by fgrzadkowski** [comment]
Actually I think there is a bug in podRunning method. It never waits for PodRunning phase - it returns error on the first check. I'll send PR to fix this.

**Comment by multilinear** [comment]
Indeed... my hostname is "slate", all lower-case, and this is on linux. I should've mentioned that.

But, it looks like you already caught the real race. Thanks for the fix!
