### ISSUE TITLE
Scheduler should look at the tuple of <HostIP, HostPort Number, Protocol> while scheduling pods

### ISSUE THREAD

**Issue by ArtfulCoder** [GoogleCloudPlatform/kubernetes#5874]
Kube-Scheduler should look at the tuple of <HostIP, Port Number, Protocol> while determining which nodes are available to run a  pod.
Today, we only look at the Port Number and a result, are over-aggressive in disallowing a pod from being run on a node.

For e.g if pod1 is using udp on port 8080, and pod2 is using tcp on port 8080, both pods can go on the same host and hostIP.
But today, pod1 and pod2 would not be scheduled on the same node.

@thockin

**Comment by davidopp** [comment]
This seems more like P3 than P2, yes?

**Comment by erictune** [comment]
I don't think we want people to use hostPort except in cases when they are setting up cluster infrastructure. In that case, they can probably work around this.

**Comment by erictune** [comment]
Clarification:
Agree that what the OP said is correct and possible.

The scheduler already checks fpr hostPort conflicts.  This ensures no conflicts.  It is pessimistic because it ignores possibility of protocol being different.  I think the priority for fixing this pessimism is P4, a.k.a closed.

**Comment by eatnumber1** [comment]
This can't be worked around when running NFS from a pod. Linux does not allow the NFS port (2049) to be changed, and the Portmap port (111) also cannot be changed. Additionally, you can't separate the UDP from the TCP ports.

Can the priority on this be increased?

**Comment by erictune** [comment]
@eatnumber1 
Are you trying to put all the nfs daemons into one pod?  If so, then I don't quite understand how resolving this issue would help you.  Maybe you can elaborate.  

If they are not all in the same pod, can you perhaps put them all in the same pod?

**Comment by bprashanth** [comment]
@erictune https://github.com/GoogleCloudPlatform/kubernetes/issues/8372 for context

**Comment by erictune** [comment]
Looks like you already concluded in #8372 that the problem is in the validation, not in the scheduler, so this is not the right bug.

**Comment by eatnumber1** [comment]
My mistake, I'm only using one pod and misunderstood the context of this bug.
