### ISSUE TITLE
update getting-started-guides/fedora/ ansible instructions.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#5879]
I recently went through the ansible instructions, and I got them working using [https://github.com/eparis/kubernetes-ansible/blob/master/old-network-config/hack-network.yml](this old recipe which doesnt use flannel, but instead, uses network manager).  

Looks like the flannel directions is the preferred way.  Just noting this and maybe @eparis can help to revise my README updates

**Comment by roberthbailey** [comment]
@jayunit100 Do you have a PR in flight to update the README?

**Comment by jayunit100** [comment]
no i dont.

**Comment by jayunit100** [comment]
okay, i just created a pull for this, a quick note to disambiguate.    #5979

**Comment by roberthbailey** [comment]
Fixed by #5979.
