### ISSUE TITLE
Improve replication controller manager performance

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#5884]
This is an umbrella issue to address replication controller/manager performance that might matter for 1.0. In broad strokes:
* Performance of `stop` Is limited by a 3s polling interval. This needs to be a watch. We cannot currently watch specific fields of an rc (https://github.com/GoogleCloudPlatform/kubernetes/issues/5745). We *could* also watch a subresource endpoint (https://github.com/GoogleCloudPlatform/kubernetes/issues/4909).
* The rc currently uses a 5-10s polling interval (https://github.com/GoogleCloudPlatform/kubernetes/blob/c12303eaa373a34dccb9fb25898e13c38ab93630/pkg/controller/replication_controller.go#L60).
    - It could be 10s before it notices inadequate pods
    - It could be 20s before its `status.Replicas` reflects this    
        - Even after fixing (1) it could be 20s before `stop` notices anything
* The controller manager lists all pods for each rc (it uses a selector filter, but that doesn't really matter to the apiserver: https://github.com/GoogleCloudPlatform/kubernetes/blob/c12303eaa373a34dccb9fb25898e13c38ab93630/pkg/controller/replication_controller.go#L194). With (https://github.com/GoogleCloudPlatform/kubernetes/pull/5746), the filter is at least performed server-side. We could use a reflector/fifo/controller framework to watch for changes to pod status  (https://github.com/GoogleCloudPlatform/kubernetes/pull/5555). 

@lavalamp thoughts (on specifically the last one, since it overlaps with your controller PR)?

**Comment by davidopp** [comment]
@bgrant0607 can you remind me which of these you were telling me yesterday you thought was the most important (or maybe it's something that isn't on the list). I've forgotten.

**Comment by bprashanth** [comment]
There's also an alternative to 3, which is list all pods *once* per tick instead of once per controller per tick. Feels like we're close enough to the watch-pod-status solution that we should just go for that (we default to using the podcache today but it's feature flagged: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L384).

**Comment by bgrant0607** [comment]
Whether indexed or not, we shouldn't be doing a list of all matching pods per replication controller.

Whether watching pod status or listing pods once per tick, we need to move to a model where the appropriate replication controller's count is updated based on the existence (or deletion) of a particular pod. 

@fgrzadkowski Is posting of pod status from kubelet really conditional?

**Comment by bprashanth** [comment]
`Status.Replicas` is already updated upon creation/deletion of a replica in the controller manager. The posting of the pod status isn't conditional if I've understood this PR correctly (https://github.com/fgrzadkowski/kubernetes/blob/336525a27d3a815954bf67792ae83d88c5e33096/pkg/kubelet/kubelet.go#L571), the use of the pod cache is (@fgrzadkowski correct me if I'm wrong). I'd rather not have to guess if our match filters are applied before or after decorating the status, so if removing status from the pod cache isn't on someones plate I'll get to first.

**Comment by fgrzadkowski** [comment]
@bprashanth is right. Use of pod_cache is conditional, but kubelet already updates pod status when it changes (PR #5714). I've already sent PR #5854 to delete pod_cache completely.

**Comment by bprashanth** [comment]
A strawman for the third problem:
* Use the controller framework to watch for updates to replication controllers
* Also watch for updates to *all* pods, through a separate reflector (memory issues?)
* Periodically wake up the controller manager: 
  - list pods from *local* store (based off `Phase` index?) 
  - build a map[selector]{InActive pod-count} 
  - list all rcs from *local* store, get pod count from map, do what we do today (i.e schedule/kill pods and update Status.Replicas)

Avoiding the periodic sync of the controller manager will make the system incremental, and thereby more fickle to things like network flake.

**Comment by fgrzadkowski** [comment]
I already started working on this. So assigning to myself.

**Comment by bprashanth** [comment]
So am I (I'd just forgotten to assign to myself), I'm just waiting on @lavalamp's reflector framework to start on this :)

Though if you *really* want this go ahead and I can find something else, or the otherway around

**Comment by fgrzadkowski** [comment]
I hoped to finish this today, but didn't make it. Since I'll be OOO until
Mon feel free to jump in. Just let me know.

-- sent from a mobile device
9 kwi 2015 17:45 "Prashanth B" <notifications@github.com> napisał(a):

**Comment by bprashanth** [comment]
Yeah I'm doing it, the controller framework mentioned isn't merged yet https://github.com/GoogleCloudPlatform/kubernetes/pull/6546, so unless there's some urgency to get this in we might as well work on different things, and might as well wait till the framework is in to reduce churn

**Comment by fgrzadkowski** [comment]
@bprashanth What's the ETA for this change? Without this change it's hard for me to move forward with profiling bottlenecks for large clusters.

**Comment by bprashanth** [comment]
@fgrzadkowski got sidetracked writing benchmarks to prove this isn't going to have a negative impact on perf. I have a pr ready, will upload tomorrow (at least for the pod part, seems like the controller framework still has some kinks that need ironing out).

**Comment by wojtek-t** [comment]
@bprashanth what is the current status of this PR?

**Comment by wojtek-t** [comment]
@bprashanth - is it fixed now?

**Comment by bprashanth** [comment]
Yep, `stop` is still slow because kubectl uses polling but that has nothing to do with the replication manager.
