### ISSUE TITLE
Asked for passphrase while creating cluster

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#5888]
```
Using master: kubernetes-master (external IP: 104.199.138.201)
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-scale/regions/asia-east1/addresses/kubernetes-master-ip].
NAME                 REGION     ADDRESS         STATUS
kubernetes-master-ip asia-east1 104.199.138.201 IN_USE
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

Kubernetes cluster created.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
```

**Comment by zmerlynn** [comment]
I presume you use screen or some other civilized terminal manager (or this was in a window). Do you know what was asking for the passphrase? I have never seen this and have no repro (Jenkins is green).

**Comment by satnam6502** [comment]
This was in `screen` of course.

S

**Comment by satnam6502** [comment]
Repo? I am King of the Unreproduceable.

**Comment by zmerlynn** [comment]
When it asked for a passphrase, did you ps to see what the heck was running? It's almost acting like `ssh-keygen` or that ilk, but I can't see anything that would act like that.

**Comment by satnam6502** [comment]
No. Life is too short.

**Comment by satnam6502** [comment]
@erictune

**Comment by roberthbailey** [comment]
What happens if you run `gcloud compute ssh <instance>`? I'm guessing that your ssh key went missing and gcloud is trying to regenerate it because right after we create a cluster we use gcloud to scp the SSL keys down so that we can verify the self signed cert presented by the server when connecting with kubectl.

**Comment by a-robinson** [comment]
Yeah, this is gcloud at work. It's happened to me a bunch in the past.
