### ISSUE TITLE
TestGetSetPods is flaky

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#5891]
--- FAIL: TestGetSetPods (0.00 seconds)
	pod_manager_test.go:73: pods are not set correctly; expected []api.Pod{api.Pod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"taco", GenerateName:"", Namespace:"default", SelfLink:"", UID:"999999999", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes.io/config.source":"api"}}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"", DNSPolicy:"", NodeSelector:map[string]string(nil), Host:"", HostNetwork:false}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Host:"", HostIP:"", PodIP:"", Info:api.PodInfo(nil)}}, api.Pod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"bar", GenerateName:"", Namespace:"default", SelfLink:"", UID:"123456789", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes.io/config.source":"file"}}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"", DNSPolicy:"", NodeSelector:map[string]string(nil), Host:"", HostNetwork:false}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Host:"", HostIP:"", PodIP:"", Info:api.PodInfo(nil)}}}, got []api.Pod{api.Pod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"bar", GenerateName:"", Namespace:"default", SelfLink:"", UID:"123456789", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes.io/config.source":"file"}}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"", DNSPolicy:"", NodeSelector:map[string]string(nil), Host:"", HostNetwork:false}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Host:"", HostIP:"", PodIP:"", Info:api.PodInfo(nil)}}, api.Pod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"taco", GenerateName:"", Namespace:"default", SelfLink:"", UID:"999999999", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes.io/config.source":"api"}}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"", DNSPolicy:"", NodeSelector:map[string]string(nil), Host:"", HostNetwork:false}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Host:"", HostIP:"", PodIP:"", Info:api.PodInfo(nil)}}}

**Comment by dchen1107** [comment]
cc/ @yujuhong

**Comment by yujuhong** [comment]
I just noticed that. The order of pods in the list is non-deterministic and should not be compared directly. Will upload a fix soon.
