### ISSUE TITLE
No error message for creating a pod with an incorrect image name

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#5904]
When putting in a bad image name (like "docker/busybox") there is no actionable error. Instead, the pod's status stays at pending indefinitely. 

/cc @MikeJeffrey

**Comment by gmarek** [comment]
I believe we don't want to contact docker/some other cache when starting new container, so it probably should be reported by Kubelet in Pod status. Or do we want to make this validation in master?

**Comment by yujuhong** [comment]
This should be surfaced once #6014 is fixed.
