### ISSUE TITLE
`kubectl describe` should be using resource.Builder so you can describe multiple things

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#5905]
For debugging it would be useful to be able to

    $ kubectl describe pods --all

or

    $ kubectl describe pods,services -s mylabel=value

Just needs to support resource.Builder

**Comment by smarterclayton** [comment]
This has been fixed I believe, @kargakis right?

**Comment by bgrant0607** [comment]
Should be fixed by #7467, but the fixes/closes notes weren't put in the PR description.
