### ISSUE TITLE
`kubectl get` etc. should support a `-o name` (or similar option) for showing only kind/name, and make mutations more verbose by default

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#5906]
With #5903 commands will support "resource/name" as an arg, which means having -q (show only type/name) becomes valuable for chaining:

    $ kubectl get pods -q | grep "-builder" | xargs kubectl delete

**Comment by smarterclayton** [comment]
If we have -q, then we can make the default "create"/"update"/"delete"/"stop" commands be more verbose about what they are creating, which addresses #5579

**Comment by bgrant0607** [comment]
We should document xargs usage somewhere.

We might as well also use this issue for making the default output more verbose.

**Comment by bgrant0607** [comment]
Currently kubectl just prints object names without the kind. If they output kind/name instead, that would be more useful for this purpose.

**Comment by smarterclayton** [comment]
For get, you mean?

**Comment by bgrant0607** [comment]
Hmm. kubectl sort of prints the kind now.

If I create a file, say, with a v1beta3 RC and a service and do `kubectl create -f unified.yaml`, the output is:
```
replicationControllers/nginx-controller
services/nginx-example
```
I thought it didn't include the kind, but it does now, except that replicationControllers shouldn't be camelCase, esp. for v1beta3.

**Comment by smarterclayton** [comment]
The default resource name output hasn't changed yet, probably due to ordering in latest.RESTMapper.  Will take a look at that.

**Comment by bgrant0607** [comment]
Maybe this could just be another output format, like -o name.

**Comment by smarterclayton** [comment]
Sounds like it.

**Comment by bgrant0607** [comment]
Discussion of script output vs. human-oriented output: https://github.com/GoogleCloudPlatform/kubernetes/issues/3894#issuecomment-71953420

**Comment by bgrant0607** [comment]
The default terse output was cited as a source of confusion in our usability study. People didn't know whether it meant success, failure, a tool bug, or something else.

**Comment by bgrant0607** [comment]
We should probably spawn another issue for this, but putting here for expedience and consistency...
Feedback from user: Output of success is just the name of the resource (services/redis-slave) Would be friendlier as "Service 'redis-slave' created successfully"

**Comment by satnam6502** [comment]
What's the status here? Shall we go ahead and add a `-q` flag that reports resources in the resource/name format for use with xargs? If yes happy to take this on.

**Comment by smarterclayton** [comment]
I think brian's proposal was an alternate output mode ("-o simple" or "-o quick") handled by the printer.  Then change the default output to *not* be xargs compatible but be friendlier.

----- Original Message -----

**Comment by bgrant0607** [comment]
@smarterclayton is correct. I suggest `-o name` or `-o id` to request the kind/name format, both for mutations and for get.

**Comment by smarterclayton** [comment]
Name makes a lot of sense.

**Comment by JanetKuo** [comment]
@bgrant0607 `-o` isn't supported in all kubectl commands. Should we use `-q name` instead to make it work for both get and mutations?

**Comment by smarterclayton** [comment]
I think we should eventually support -o on all commands - it's mostly that
we haven't gone back to create/update/delete since they were the first
commands.

On Jun 30, 2015, at 5:24 PM, Janet Kuo <notifications@github.com> wrote:

@bgrant0607 <https://github.com/bgrant0607> -o isn't supported in all
kubectl commands. Should we use -q name instead to make it work for both
get and mutations?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/5906#issuecomment-117348470>
.

**Comment by JanetKuo** [comment]
Discussed with @bgrant0607 and decided to add the following changes to only mutations*:
* Add `-o name` (prints current output)
* Make default output more verbose/understandable (such as `[object_name] [operation] successfully`)

*Mutations include: create, delete, expose, label, patch, replace, rollingupdate, run, scale, stop

**Comment by bgrant0607** [comment]
cc @deads2k

**Comment by bgrant0607** [comment]
Later PRs can:
* add `-o name` to get
* add `-o json|yaml|template` to mutations (applied to status object in apiserver response)

**Comment by deads2k** [comment]
I like the idea of human readable by default and a separate flag for machine readable output flag.  `-o name` sounds fine, but how well will this play with `--all-namespaces`?   I'll get back a list of `kind(resource?)/name`, but that won't be sufficient to lookup when it gets piped.  Can we choose a machine readable format that is fully qualifying?

**Comment by bgrant0607** [comment]
@deads2k I agree that --all-namespaces is problematic. That's a separate issue -- #3731. The form kubectl accepts on its command line would need to be extended with namespace if we wanted to add namespace to the output.

**Comment by JanetKuo** [comment]
Some mutations (`label`, `run`, `expose`, `rollingupdate`) use `-o` flag and print the object like `get` does. I'll add `-o name` to other mutations (`create`, `delete`, `stop`, `replace`, `patch`, `scale`) first and deal with those mutations later.

**Comment by bgrant0607** [comment]
@JanetKuo points out that label, run, expose, and rolling-update commands don't adhere to the same output conventions as other mutations. We'll want to fix that. For instance, label is just another kind of patch, basically.

**Comment by bgrant0607** [comment]
When writing the user guide, it was definitely jarring that `run` and `expose` produced `get` output.
