### ISSUE TITLE
Find portalIP automatically while updating a service

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#5907]
When I tried to update a service to change its port. Kubectl said `spec.portalIp: invalid error ""`

I viewed detailed information of the service and added `portalIp` with the same value as current service in the template and solved the problem.

But since the `portalIp` is automatically allocated when the service is created. Why users must provide `portalIp` explicitly while updating? And also the `portalIp` can not be changed while updating.

**Comment by bgrant0607** [comment]
Please see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md. PUT doesn't support partial updates. In general, you need to do a GET, change just what you want to update, and then PUT.

You could try PATCH, which was recently added. You may also be interested in a new merge strategy being implemented -- see #6027.

**Comment by bgrant0607** [comment]
And, yes, the description string on the field should say that the field "cannot be updated" -- @thockin.

**Comment by hurf** [comment]
@bgrant0607 - Thanks Brian, I'm not asking to allow `portalIp` be changed while updating, but  allow users not giving `portalIp` explicitly in the template. I write a small patch to do so and will submit it soon.

**Comment by bgrant0607** [comment]
@hurf Thank you for offering to make a change, but the change will not be accepted. If you just want to update certain fields in the object, please use PATCH.

**Comment by bgrant0607** [comment]
I also recommend trying kubectl update --patch:
https://github.com/GoogleCloudPlatform/kubernetes/blob/bc4a082f7a5d1ec58a05c2f1a6fb1af9e5622079/docs/kubectl-update.md#L26

**Comment by thockin** [comment]
The description does say "cannot be updated".

**Comment by bgrant0607** [comment]
So it does.

**Comment by hurf** [comment]
@thockin @bgrant0607 - Sorry for the description mentioned "can not be updated" and not expressed myself clearly.

What I want to say is when I'm creating the pod, I didn't provide the `portalIP` in the template. But when I want to update the pod, I'm not going to change `portalIP` and it is not allowed to change it, why should I address it explicitly? I just feel inconvenient about this.

Anyway thanks you can discuss with this issue.

**Comment by bgrant0607** [comment]
@hurf I understand. The solution underway is #1702.
