### ISSUE TITLE
Where to keep Nodes Capacity

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#5908]
Currently it's being kept in NodeSpec, and it is being "updated" (hopefully always to the same value, but who knows) in tryUpdatePodStatus in Kubelet. In https://github.com/GoogleCloudPlatform/kubernetes/issues/2726#issuecomment-85896037 it is said, that we want to move Status update to post through subresource, which alone makes a lot of sense.

The question is what to do with Capacity. We can either assume it's immutable and leave it in Spec (may be problematic if we'll want to do vertical node scaling + I'm not sure if it's really immutable), say that it's not the part of the NodeSpec, but NodeStatus (it can make sense if seen from a correct angle), or hack around subresources for Nodes and allow updating Spec in this case (easiest, without visible external changes, but kind of ugly).

@davidopp @bgrant0607 @ddysher

**Comment by bgrant0607** [comment]
Capacity should be 100% observable from other sources: machine database, cloud provider, the node itself. Therefore, it should just be in NodeStatus.

**Comment by gmarek** [comment]
Ok, I'll write a PR moving it to Status tomorrow.
