### ISSUE TITLE
If RC's ID contains a period, container continues to run after RC is stopped 

### ISSUE THREAD

**Issue by rculbertson** [GoogleCloudPlatform/kubernetes#5918]
If a replication controller's ID contains a period, the docker container will continue run after you stop the controller. It will also continue to run if you instead resize the number of replicas to 0.

Steps to reproduce:
1. Take the guestbook example's [json file](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/redis-master-controller.json), and replace the ID's first dash with a period (i.e. `"id": "redis-master-controller"` becomes `"id": "redis.master-controller"`). 
2. gcloud preview container kubectl create -f redis-master-controller.json
3. gcloud preview container kubectl stop rc redis.master-controller
4. Query for all RC's and pods to see it is gone:
```
$ gcloud preview container kubectl get rc,pod
POD                 IP                  CONTAINER(S)        IMAGE(S)                           HOST                                                               LABELS              STATUS              CREATED
skydns-fplln        10.40.0.3           etcd                quay.io/coreos/etcd:latest         k8s-ryan-test-2-node-1.c.prefab-wave-844.internal/130.211.82.125   k8s-app=skydns      Running             13 days
                                        kube2sky            kubernetes/kube2sky:1.0
                                        skydns              kubernetes/skydns:2014-12-23-001
CONTROLLER          CONTAINER(S)        IMAGE(S)                           SELECTOR            REPLICAS
skydns              etcd                quay.io/coreos/etcd:latest         k8s-app=skydns      1
                    kube2sky            kubernetes/kube2sky:1.0
                    skydns              kubernetes/skydns:2014-12-23-001
```
Run `sudo docker ps` on the node to see the redis container is still running:
```
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED              STATUS              PORTS                 
7b8c9c522343        dockerfile/redis:latest   "redis-server /etc/r   About a minute ago   Up About a minute                         
8115706a8b09        kubernetes/pause:go       "/pause"               About a minute ago   Up About a minute                         
d72bbf3d8f71        google/cadvisor:0.8.0     "/usr/bin/cadvisor"    2 minutes ago        Up 2 minutes                              
a059ba7c25f2        kubernetes/pause:go       "/pause"               2 minutes ago        Up 2 minutes        0.0.0.0:4194->8080/tcp  
```

**Comment by yujuhong** [comment]
@rculbertson, thanks for filing the issue!

What version of kubernetes did you use? Issue #4920 should have fixed this issue (kubelet doesn't accept all valid pod names/namespaces), and I could not reproduce at HEAD.

**Comment by roberthbailey** [comment]
It looks like he's running on GKE (from the gcloud commands) so I'd hazard a guess that it's at 0.11. Which release did #4920 make it into?

**Comment by yujuhong** [comment]
Uh..I missed the GKE part completely.

The commit is in release-0.13

**Comment by rculbertson** [comment]
Ah, great. Sorry for the dupe then. I didn't realize that bug was the same issue. I am using GKE. Can work around the issue until the fix is rolled out. Thanks!

**Comment by roberthbailey** [comment]
@rculbertson - 0.13.2 is now available on GKE. There is not yet any upgrade path, so you'll need to create a new cluster at which point you should no longer see this bug.

**Comment by rculbertson** [comment]
@roberthbailey I recreated the cluster, and everything worked. Thanks for the help!

**Comment by roberthbailey** [comment]
Yay!
