### ISSUE TITLE
Include domain name or not in the static pod names

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#5936]
Static pods (pods from file/http sources) are named as `podName-hostname`. Because hostname can include the domain name or not, the actual pod name varies.
E.g.
`fluentd-to-elasticsearch-e2e-test-jenkins-minion-4gnu` vs
`fluentd-to-elasticsearch-e2e-test-jenkins-minion-4gnu.c.kubernetes-jenkins.internal`

Pod names are shorter and easier to read if we do not include the domain name. The downside is that we would not be able to handle nodes on different domains (would that be something we need to support)?

**Comment by thockin** [comment]
How do you get the node name from hostname?  The hostname spec is unclear
whether it includes domain or not.  You could just take the first token, I
suppose.

**Comment by yujuhong** [comment]
Kubelet uses `hostname -f` to get the fully qualified domain name, but user can also override the hostname if they want by passing it to the config.

My question was more about whether we should grab the first token, or we should consider the possibility of nodes from different domains :)

**Comment by thockin** [comment]
I think it's reasonable to assume (and document) that hostnames must be in
the same domain or else the user must override.

I *think* that is sane..
