### ISSUE TITLE
`validate-cluster.sh` should be using `/validate`: wants `kubectl healthy`?

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#5946]
We have a `/validate` endpoint that GKE has been using to validate the health of running clusters after the API server is available, similar to the `kube-up.sh` flow of `validate-cluster.sh`. There's no reason that `validate-cluster.sh` should actually do this work manually anymore - we should just go through common source. We should probably introduce a `kubectl healthy` or `kubectl healthcheck`?

**Comment by fabioy** [comment]
PR #6597 should have fixed this.
