### ISSUE TITLE
Kubelet publish node components' version

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#5948]
Forked from #4855, and required for rolling upgrade: 

Kubelet should report cross-products version, such kernel, docker, kubelet, kube-proxy, image, etc. to API server. 

cc/ @zmerlynn

**Comment by zmerlynn** [comment]
So now that it's in `NodeSystemInfo`, is it queryable easily from `kubectl` at all?

**Comment by mbforbes** [comment]
+me

**Comment by mbforbes** [comment]
Awesome, thanks Dawn!
