### ISSUE TITLE
etcd on the master should only be accessible from localhost

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#5962]
Forked from #129. 

Right now it binds to 0.0.0.0.

**Comment by kelseyhightower** [comment]
@roberthbailey Is the goal to run a single etcd instance private to the Kubernetes API server?

**Comment by zmerlynn** [comment]
Kelsey - Yeah, that's the goal. (This obviously might differ on Core
setups, but you still could imagine having a separate etcd just for
separation of concerns between fleet / k8s.)

**Comment by kelseyhightower** [comment]
@zmerlynn The more I think about it, I think that is the right thing to do out of the box. If users really want to share etcd clusters, they can make the configuration changes.

**Comment by roberthbailey** [comment]
@ArtfulCoder was this fixed by #6417?

**Comment by ArtfulCoder** [comment]
yes, PR #6422
