### ISSUE TITLE
cAdvisor should only be accessible from localhost

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#5967]
Forked from #129.

Right now it binds to 0.0.0.0.

**Comment by roberthbailey** [comment]
@vishh mentioned that the port is currently open because it's useful to see the cAdvisor UI.

**Comment by vishh** [comment]
Yup. The cAdvisor's UI is still useful. The kubelet can act as a proxy if cadvisor needs to run in localhost.
In any case why is this required for v1.0?

**Comment by vmarmol** [comment]
There was also concern that there are existing users (and container VM) that access the information in this API directly.

**Comment by vmarmol** [comment]
Kubelet exports the same information via its own (non-localhost) API, so we should make sure our stories sync up there :)

**Comment by vmarmol** [comment]
I think we should send an e-mail to our dev list, make sure no-one is using it. If they are, encourage them to switch to Kubelet (they support pretty much the same data access). After that, we can turn down the endpoint and only worry about the Kubelet one.
