### ISSUE TITLE
E2E tests for kubectl should be runnable outside cloud providers (WLOG,  maybe other tests as well) ?

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#6028]
lets distill some of the testing based on their exact declarations (in e2e) a little more.

without loss of generality, for example, the *kubectl.go* test declaration of "should be able to start/stop a service" , shouldn't be hindered by the fact that im running tests w/o a cloud provider locally.

**Comment by erictune** [comment]
You should be able to do this with `hack/conformance-test.sh`.  Let me know if that doesn't work.  Read the comments in that shell script.

**Comment by jayunit100** [comment]
hi eric.  do you think that decoupling the tests is probably  a good solution.....  even if there is a current workaroudn in `hack/conformance-test.sh` ?  I'd like to , for example, have the test of guestbook not rely on cloud provider semantics, and test cloud provider stuff in a separate test... given that its not a gauranteed feature to be in every kube system.
