### ISSUE TITLE
Add filename in the error message when parsing error occured

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#6036]
When using kubctl to create a pod, an parsing error occured. The error message looks like：

    client error processing command: unable to parse : yaml: line 1: did not find expected key.
    
Need to add the source name for create command make the message look like:

    client error processing command: unable to parse my_pod.yaml : yaml: line 1: did not find expected key.

**Comment by piosz** [comment]
closed by #6037

**Comment by piosz** [comment]
closed by #6037
