### ISSUE TITLE
kubectl error for large cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#6053]
I set up large cluster (90 nodes). Few times I've noticed the following error:

$ ./cluster/kubectl.sh get pods
current-context: "ivory-honor-865_e2e-test-filipg"
Running: ./cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl get pods
F0327 12:25:31.913390   26283 get.go:70] Error: Get http://127.0.0.1:4001/v2/keys/registry/pods/default?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: cannot assign requested address

@wojtek-t observer similar error for 50-node cluster. I haven't seen for small ones.

**Comment by wojtek-t** [comment]
This is not related to kubectl - while running soem performance tests, I'm observing that error in Kubelet logs, e.g.:
E0327 13:41:40.496608    4712 kubelet.go:1729] error updating node status, will retry: error getting node "e2e-test-wojtekt-minion-0jxm.c.groovy-sentry-504.internal": Get http://127.0.0.1:4001/v2/keys/re
gistry/minions/e2e-test-wojtekt-minion-0jxm.c.groovy-sentry-504.internal?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: cannot assign requested address

**Comment by wojtek-t** [comment]
BTW, the 4001 port suggests this might be a problem with etcd

**Comment by wojtek-t** [comment]
As @fgrzadkowski suggested, this issue might be related to saturated network within a single machine (connections between etcd and apiserver). Decreasing the load on etcd from apiserver might help (e.g. #6349)

**Comment by davidopp** [comment]
Has this problem gone away? If so, please close this issue.

**Comment by dchen1107** [comment]
Please run 'kubectl clusterinfo' when you run into this issue? I noticed that the context you have is talking about "ivory-honor-865_e2e-test-filipg", but sounds like you tried to retrieve information from different cluster: much larger ones?

**Comment by wojtek-t** [comment]
This is still happening:
wojtekt@wojtekt-work:~/kubernetes$ cluster/kubectl.sh get rc
current-context: "groovy-sentry-504_e2e-test-wojtekt"
Running: cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl get rc
Error: Get http://127.0.0.1:4001/v2/keys/registry/controllers/default?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: cannot assign requested address

**Comment by satnam6502** [comment]
A while back I put a **lot** of effort into creating large GCE clusters (1,000 nodes) and this resulted in many PRs (I worry that some of them are being undone without due concern about large clusters). So I think the issues around bringing up large clusters is something we need to keep an eye on and keep constantly ensuring is working. I had adapted how we assigned IP addresses to ensure nodes in large clusters got good IP addresses.

**Comment by fgrzadkowski** [comment]
@dchen1107 My e2e cluster was just much larger (if it's name that suggests that it's small)

@satnam6502 I agree that we should be careful, but for now let's only make sure that 100 node cluster works, not 1'000.

**Comment by satnam6502** [comment]
@fgrzadkowski : OK. It's a shame to throw away the work I did for big clusters.

**Comment by fgrzadkowski** [comment]
@satnam6502 : I agree! That's why I said we should be careful :) But I don't think it's reasonable to expect that everybody will test something on 1000 node cluster. Let's just look for PRs that can break what you have fixed!

**Comment by satnam6502** [comment]
Well some of what I "fixed" has been obsoleted anyway (for the better) e.g. by the move to M.I.G. The remaining things relate to routes, firewalls, IP allocation, rate of calls to the apiserver etc.

**Comment by davidopp** [comment]
@fgrzadkowski and @wojtek-t say this is fixed.

**Comment by hsaputra** [comment]
I am sorry, so how does this issue actually fixed?
