### ISSUE TITLE
Suspicious logic in proxier.go

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#6061]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/proxier.go#L480-L483

I think this is:
```
if A & B & C {
continue
}
if A & (!B || !C || !D) {
do something
}
```

I think the !D can never be a factor in the second if statement.  !D only comes in to play if A & B & C, but in that case the first if statement would have been hit.

I'm thinking that the first if statement should be `if A & B & C & D`.  And that then we can just reduce the second one to `if A`, in this case `if exists`

@thockin - looks like you touched this last?  Do you agree?

**Comment by justinsb** [comment]
Ah - it looks like https://github.com/GoogleCloudPlatform/kubernetes/commit/909f82f463180dd360a2108aa525547ea603b05c went in around the same time, and removed a condition (`info.isActive()`) from the first if statement.  So that's probably how this happened.

**Comment by thockin** [comment]
I agree with your assessment and solution.

**Comment by a-robinson** [comment]
Agreed. I sent PR #6123 on Friday to fix this same issue, albeit without the simplification of the second condition. I'll update it to include the simplification.

**Comment by thockin** [comment]
I also fixed it in the multi-port PR.  I'll check yours, merge it, and
rebase mine
