### ISSUE TITLE
Move NodeStatus update to subresources

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#6063]
I started to do it today, but I didn't manage to finish it.

**Comment by bgrant0607** [comment]
Adding missing team label.

**Comment by davidopp** [comment]
This is marked P1 and 1.0, but IIUC requires an API change. Am I correct? If so, I assume we're not actually going to do it for 1.0?

**Comment by bgrant0607** [comment]
The API change would be additive, not break compatibility.

Feel free to reprioritize if you think this won't improve performance or simplify node controller and/or kubelet status posts.

**Comment by gmarek** [comment]
FYI: I don't believe it'll have any performance impact. Even when using subresources we send "whole" objects though the network, so that we'll be able to check objects version id. I see it only as a cleanup for now.

**Comment by gmarek** [comment]
e2e is green
