### ISSUE TITLE
Node IPAddresses is not refreshed

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#6072]
Node IPAddresses is part of node status.  It is previously read from cloudprovider and posted by node controller.  Now that we post node status from kubelet, which doesn't include ip address, it means we never refresh them.

The initial IPAddress is posted from node controller at cluster startup.

We can either:
1. post ip addresses from kubelet too
2. post ip addresses from node controller, merge node status somewhere
3. move ip addresses to spec instead of status.

@davidopp @bgrant0607 @gmarek

**Comment by zmerlynn** [comment]
Is this what's necessary for me to remove the `--machines` configuration from Salt? I'm very keen to get of that, because it's blocking dynamic clustering / MIGs / etcetc. (I thought #4562 was going to get me that, but it was just closed, and the Salt config is untouched.)

**Comment by ddysher** [comment]
If you are running on cloudprovider, then `--machines` need not to be passed.  In particular, if you pass both `--cloud_provider` and `--match_regexp`, then `--machines

**Comment by zmerlynn** [comment]
I'll send a PR soon.

**Comment by bgrant0607** [comment]
If Kubelet isn't merging its updates into NodeStatus, it's not doing the right thing

**Comment by bgrant0607** [comment]
From email discussion:

All components MUST have a resync and retry loop. Updates aren't allowed without a matching resourceVersion, and in general there will need to be fields that need to be merged.

We could create disjoint Node subresources for Kubelet and the Node controller to which they could POST, and the apiserver would perform the merges.

There was work underway to create a /status subresource, but I'm not sure what happened to it.

**Comment by davidopp** [comment]
I think option 2 is OK since we already have to merge NodeStatus (for example, Kubelet sets NodeReady true/false while NodeController sets NodeReady unknown).

**Comment by gmarek** [comment]
@bgrant0607 I don't know what happened with previous work, but I started it on Friday. It's mostly done, but I don't know if it won't get preempted by other tasks today (like adding aforementioned retry loop).

**Comment by gmarek** [comment]
@justinsb PR solved this. Thanks!

**Comment by ddysher** [comment]
The problem is not solved.  Node addresses are stil not refreshed.  @justinsb 's solution is a workaround for newly added nodes.

**Comment by roberthbailey** [comment]
I think this may end up being fixed as a side-effect of my PR to have nodes self register (#6949). As part of that change, I recompute the node addresses on each status update.

**Comment by gmarek** [comment]
Yes, Roberts change should fix this problem when merged. But I believe that we're still not sure if host IPs can change during runtime for any cloud provider. AFAIK in GCE they can't, and I'll be rather surprised if it's possible anywhere.

**Comment by davidopp** [comment]
OK, in that case I'm going to remove this from the 1.0 milestone. @roberthbailey (or anyone else) please speak up if you think we need to support node changing its IP address without first being removed from the cluster-provider, recognized as gone by the master, and then re-added (for 1.0).

**Comment by roberthbailey** [comment]
Re-adding with a different IP sounds reasonable for v1.0 to me.

**Comment by gmarek** [comment]
@roberthbailey @davidopp @bgrant0607 
Do we believe this should be fixed, or we're happy with the current behavior?

**Comment by roberthbailey** [comment]
I think this is fixed. As [reported by a user](https://groups.google.com/d/msg/google-containers/P4Cx7RMHOzI/i7R9IkmbJgAJ) (who wasn't necessarily happy with this behavior), the kubelet checks for it's current IP address on each status update so it gets refreshed. 

Please reopen for discussion if you disagree.

**Comment by zmerlynn** [comment]
Arguably the behavior reported by that user is a bug that we should also fix. If there's a transient error reaching the cloud provider endpoint, we should just coast rather than assume we have no IPs.

**Comment by roberthbailey** [comment]
Agreed (it should have a different issue). But it actually re-enforces the fact that this issue is resolved.
