### ISSUE TITLE
Babysitting for kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#6078]
We appear to have monit babysitting of all processes other than the kube-controller-manager and kube-scheduler that run on the master. Is there any reason we don't have it for them?

@dchen1107

**Comment by roberthbailey** [comment]
@davidopp - I heard mention that we were moving these into pods so that they would be babysat by the kubelet instead of by monit. Is that correct?

**Comment by dchen1107** [comment]
Yes, we are moving them into pod, including apiserer, ngnix. They shouldn't be babysat by monit. Here is the issue #5011 related to this effort. @ArtfulCoder is working on this. 

I also filed #6047 for healthchecking master component pod.

**Comment by a-robinson** [comment]
Closing, since this is covered by other issues.
