### ISSUE TITLE
Allow nodes to dynamically join a running cluster

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#6087]
We want to allow nodes to dynamically join a kubernetes cluster after the cluster has been created. For version 1.0, we will implement "Static Clustering" as defined in [clustering.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/clustering.md). 

For reference, in #3168 (securing node &rarr; master communication), @roberthbailey proposes [an implementation plan](https://github.com/GoogleCloudPlatform/kubernetes/issues/3168#issuecomment-74781577), step 2 of which entails this.

**Comment by fgrzadkowski** [comment]
cc-ing @jszczepkowski who is working on autoscaling

**Comment by jszczepkowski** [comment]
I'm currently working on updating external load balancers (target pools) for external services when cloud nodes are changed. I'm just adding an extra call in NodeController.SyncCloudNodes method to reconcile external services. I think this is a part of this issue.

**Comment by jszczepkowski** [comment]
@mbforbes @roberthbailey @tkulczynski
Issue #5246 (Node Pod's IP ranges configured by nodecontroller) also seems to be a part of this issue.

**Comment by mbforbes** [comment]
Yes, definitely, thanks for linking here. #5246 is hopefully the last issue needed to make this possible; afterwards, @roberthbailey will be making it explicit and secure.

**Comment by mbforbes** [comment]
This is theoretically complete and upgrades are unblocked, though this needs to be verified.

**Comment by roberthbailey** [comment]
I just created a GCE cluster, resized my MIG to add 2 new nodes, and then watched the nodes go from `Unknown` to `Ready` and verified that I could schedule work on the new nodes.

**Comment by benmccann** [comment]
Yay, that's awesome. The other thing to do here would be to document this procedure. Should we leave this open or file a new bug to track that?

**Comment by roberthbailey** [comment]
Well, right now this only really works on GCE. Maybe we should leave it open until #6949 goes in (which is a more general solution).

**Comment by bcbroussard** [comment]
+1 for both documentation and leaving this open until #6949 is ready. Awesome work on this, very excited to try it out.

**Comment by timothysc** [comment]
seconded. 
+1 to leave open + docs.

**Comment by roberthbailey** [comment]
#6949 is now merged (and the rollback of the rollback is also merged) so I think all that remains here is to add the appropriate documentation.

**Comment by alex-mohr** [comment]
I think now that PR #8982 is merged (thanks @erictune !) we now have the doc fixes -- closing.
