### ISSUE TITLE
no monit for nginx

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#6102]
We should run monit on nginx.  I know we plan to run that in a pod, but right now it crashes somewhat often, so we should monit it to keep it up.

**Comment by ArtfulCoder** [comment]
I will be moving nginx etc to its own pod so that we wont need monit..

**Comment by davidopp** [comment]
@ArtfulCoder what is the ETA? Should we implement this in the mean time? If the ETA is soon, please close this issue.

**Comment by brendandburns** [comment]
I'm taking this over from @ArtfulCoder ...  This will also include the version update to make websockets work for us.

**Comment by ArtfulCoder** [comment]
Thanks Brendan!
You can use the net=host feature for this one.

**Comment by brendandburns** [comment]
Closing this as it was fixed by #6334
