### ISSUE TITLE
Kubelet should keep the original PodStatus.Host when posting the status

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#6124]
I am seeing pod status update failures due to empty `Host` field. This prevents the pod status from being updated in some cases. Kubelet should always keep the original host.

**Comment by yujuhong** [comment]
In the case I saw, all containers of that pod has exited with 1, and the restart policy was never. There seems to be two issues.

1. kubelet queried docker and [couldn't find the containers] (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1900): "No pod infra container exists for this pod"
2. kubelet decided to [return a pending status with no host set](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1905)

(2) triggered a status update which attempted to clear the host field. This should not be allowed.

**Comment by yujuhong** [comment]
#6127 is a quick fix for 2. There is a broader question about whether "pending" is the best status to return in this case.

Whey kubelet won't report failed (1) still needs more investigation.

**Comment by bgrant0607** [comment]
I'd be happy if PodStatus.Host were eliminated from v1beta3 and just populated from PodSpec in v1beta1/2.

**Comment by yujuhong** [comment]
@bgrant0607, yes, I thought someone was working on that. Filed a issue just in case #6165.
