### ISSUE TITLE
Document API/system design principles and patterns

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#6133]
Related to #5476, #2003, #1007, #5620, and other issues.

The PR creation rate and number of contributors are both growing. In order to scale the effort, we need to better document the patterns we want additions to the system and API to follow, so that we can better parallelize the design and review effort. I'm filing this issue to solicit important principles and patterns to document. I volunteer to create the actual document and/or presentation slides.

What do you think isn't sufficiently covered by existing design docs and/or isn't sufficiently discoverable? What principles/patterns do you find yourself explaining over and over again? What properties would you be unhappy to have violated/degraded/changed by new PRs? 

I'm thinking more about reasonably general issues rather than implementation-oriented invariants that apply to very specific/narrow parts of the code. 

Examples (some areas, some principles):
* Declarative APIs, desired state and current state
* Level-based operation: Functionality must be level-based, meaning the system must operate correctly given the desired state and the current/observed state, regardless of how many intermediate state updates may have been missed. Edge-based behavior must be just an optimization.
* Status must be 100% reconstructable by observation. Any history kept must be just an optimization and not required for correct operation.
* Phase, Reason, Message, Conditions, etc. vs. a single state machine with lots of states
* Composable, a la carte functionality
* Transparent, no glass to break
* More generally, [Eric Raymond's 17 UNIX rules](https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond.E2.80.99s_17_Unix_Rules)
* Only the apiserver should communicate with etcd/store, and not other components (scheduler, kubelet, etc.).
* Compromising a single node shouldn't compromise the cluster (not that we've achieved that yet)
* Components should continue to do what they're told in the absence of new instructions.  
* Open world assumption: continually verify assumptions and gracefully adapt to external events and/or actors (example: we allow users to kill pods under control of a replication controller; it just replaces them)
* Don't assume a component's decisions will not be overridden or rejected, nor for the component to always understand why. For example, etcd may reject writes. Kubelet may reject pods. The scheduler may not be able to schedule pods.
* When to use labels vs. annotations vs. object references
* Watch vs. polling
* Bootstrapping-related principles

Let's brainstorm first, and argue and prioritize afterward.

@smarterclayton @derekwaynecarr @thockin @erictune @lavalamp

**Comment by lavalamp** [comment]
* Master operations must be constant time.
* Cluster-wide invariants are difficult to get right. Try not to add them. If you must have them, don't enforce them atomically in master components, that is contention-prone and doesn't provide a recovery path in the case of a bug allowing the invariant violation. Instead, provide a series of checks to reduce the probability of a violation, and make every component involved able to recover from an invariant violation. Example: scheduler assigning pods to kubelet.
* Self-healing components. For example, if you must keep some state (e.g., cache) the content needs to be periodically refreshed, so that if an item does get erroneously stored or a deletion event is missed etc, it will be soon fixed. Ideally on timescales that are shorter than what will attract attention from humans.

**Comment by bgrant0607** [comment]
Status and spec principles: https://groups.google.com/forum/#!topic/kubernetes-dev/HKg8OD_PNfw

**Comment by bgrant0607** [comment]
Other things I noticed missing from api-conventions.md:
* adequate documentation of watch
* subresources
* delete options, deletionTimestamp, and graceful termination
* list options
* object references
* selfLink
* events

**Comment by bgrant0607** [comment]
And pod-states.md is woefully out of date (e.g., it references "PodStatus" rather than "PodPhase").

**Comment by bgrant0607** [comment]
Working on API-visible conventions first.

**Comment by bgrant0607** [comment]
Another principle: all relevant API info should be represented in json. Relevant HTTP header fields should mirror the json fields. One example that came up just now: status codes (which are represented in Status). We've previously discussed using Etags and If-Match, also. We're going in this direction for URL query parameters, also.
