### ISSUE TITLE
DNS integration instructions are broken due to missing Docker images

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#6134]
When following the current instructions
```
Mar 28 12:08:32 node-01 docker[1122]: No such image: gcr.io/google-containers/kube2sky:1.1
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="-job image_inspect(gcr.io/google-containers/kube2sky:1.1) = ERR (1)"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="Handler for GET /images/{name:.*}/json returned error: No such image: gcr.io/google-containers/kube2sky:1.1"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="HTTP Error: statusCode=404 No such image: gcr.io/google-containers/kube2sky:1.1"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="GET /images/gcr.io/google-containers/skydns:2015-03-11-001/json"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="+job image_inspect(gcr.io/google-containers/skydns:2015-03-11-001)"
Mar 28 12:08:32 node-01 docker[1122]: No such image: gcr.io/google-containers/skydns:2015-03-11-001
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="info" msg="-job image_inspect(gcr.io/google-containers/skydns:2015-03-11-001) = ERR (1)"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="Handler for GET /images/{name:.*}/json returned error: No such image: gcr.io/google-containers/skydns:2015-03-11-001"
Mar 28 12:08:32 node-01 docker[1122]: time="2015-03-28T12:08:32Z" level="error" msg="HTTP Error: statusCode=404 No such image: gcr.io/google-containers/skydns:2015-03-11-001"
```

**Comment by thockin** [comment]
Satnam6502 was touching this, I think.

**Comment by pires** [comment]
@thockin I was stupid -> https://github.com/GoogleCloudPlatform/kubernetes/pull/6136

**Comment by thockin** [comment]
I'm sorry, I don't understand.  I can pull from that image just fine.  I do not know the ins-and-outs of the gcr.io auth model, but I did not do anything special to my local docker config.

@jlowdermilk who has the 'git blame'

**Comment by zmerlynn** [comment]
Also cc @mattmoor, who may be able to help.

**Comment by mattmoor** [comment]
gcr.io accepts anonymous access for GCS buckets that are readable by "AllUsers", which includes the bucket for "google-containers".

I was just able to docker pull without a .dockercfg file:
$ docker pull gcr.io/google-containers/kube2sky:1.1
Pulling repository gcr.io/google-containers/kube2sky
011d96737112: Download complete 
511136ea3c5a: Download complete 
075370067b29: Download complete 
fc26c11e2ffe: Download complete 
281435a08148: Download complete 
Status: Downloaded newer image for gcr.io/google-containers/kube2sky:1.1

What version of Docker are you using?  If pre-1.5, you need to use "gcr.io/google_containers/..."

**Comment by pires** [comment]
I'm using Docker 1.5.0 bundled with CoreOS 633.1.0.

On Sat, Mar 28, 2015 at 10:34 PM, mattmoor <notifications@github.com> wrote:

> gcr.io accepts anonymous access for GCS buckets that are readable by
> "AllUsers", which includes the bucket for "google-containers".
>
> I was just able to docker pull without a .dockercfg file:
> $ docker pull gcr.io/google-containers/kube2sky:1.1
> Pulling repository gcr.io/google-containers/kube2sky
> 011d96737112: Download complete
> 511136ea3c5a: Download complete
> 075370067b29: Download complete
> fc26c11e2ffe: Download complete
> 281435a08148: Download complete
> Status: Downloaded newer image for gcr.io/google-containers/kube2sky:1.1
>
> What version of Docker are you using? If pre-1.5, you need to use "
> gcr.io/google_containers/..."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/6134#issuecomment-87324011>
> .
>



-- 
Pires

**Comment by thockin** [comment]
Can you manually pull this?

**Comment by satnam6502** [comment]
Let me know if I can help. Although I produced and pushed some images to gcr.io I did not do kube2sky -- I **think** @jlowdermilk helped with that one.

**Comment by jlowdermilk** [comment]
I also just pulled both the kube2sky and skydns images on my laptop without any special docker config. Is there any reason why pulling from gcr.io repo would be broken just for CoreOS?

**Comment by pires** [comment]
Not for CoreOS itself, but for my installation it seems. I run a private registry as a mirror and now I believe it's the culprit here.

```
ExecStart=/usr/bin/docker run -d --restart always --net host --name docker-registry \
          -e STANDALONE=false \
          -e GUNICORN_OPTS=[--preload] \
          -e MIRROR_SOURCE=https://registry-1.docker.io \
          -e MIRROR_SOURCE_INDEX=https://index.docker.io \
          -e MIRROR_TAGS_CACHE_TTL=1800 \
```

@antoniomeireles careful with this one. Ideas?

Sorry guys for the waste of time.

**Comment by AntonioMeireles** [comment]
@pires - plain docker-registry is only (so far by design) able to mirror/cache from docker's registry, not from 3rd party private or public repos (so no caching from quay.io or gcr.io, etc). OTOH this shouldn't be a 'big' problem as in those cases the docker-registry acting as cache would be working as just a transparent proxy, without any cache at all. in general, and as far as i can tell,  this shouldn't cause issues other than those alleviated by the existence of a cache in first place...

**Comment by pires** [comment]
@antoniomeireles so, the questions is: what happened then?

**Comment by mattmoor** [comment]
Can you reproduce this with debug-logging (-D) enabled in the Docker daemon, so we can get a clearer picture of what's going on?

**Comment by pires** [comment]
@mattmoor it works now. There was probably a glitch with GCR at the time. I tried to look for the image at the time, but it seems GCR doesn't have a public search UI, does it?

**Comment by mattmoor** [comment]
@pires I'm not aware of any problems on our side, but I'll dig in a little bit around the times in your logs and see if I can find any 404s talking to google-containers.


#### Regarding search

The docker client doesn't properly authenticate search API requests (haven't scouted the 1.6 rc yet).  So since our focus has been on private hosting, we simply haven't tackled this yet.

#### Regarding UI

We have no UI at all yet...  :)

Still our initial UI will be very focused on private image hosting...

**Comment by mattmoor** [comment]
To follow up on 404s...

In the past week, the only 404 GCR has served for "google-containers" (as part of a "docker pull") was for the typo: "kube3sky"

Looking a bit more carefully at your log output, the API endpoints mentioned in tandem with the 404 look more like the docker daemon's REST API than the Registry API:
   https://gist.github.com/mmdriley/0ed2129a93fd0c15ff36#life-of-a-docker-pull

So in this context, I believe the 404 was the docker daemon telling the client that it doesn't have that image locally, not that GCR doesn't have it.  


Perhaps this segment of the log precedes the pull?

**Comment by pires** [comment]
I don't think so. It stood there for a couple hours and the images were not
downloaded. Weird. If I do `docker pull` on the terminal it works, but it
fails in the replication controller.

On Sun, Mar 29, 2015 at 11:16 PM, mattmoor <notifications@github.com> wrote:

> To follow up on 404s...
>
> In the past week, the only 404 GCR has served for "google-containers" (as
> part of a "docker pull") was for the typo: "kube3sky"
>
> Looking a bit more carefully at your log output, the API endpoints
> mentioned in tandem with the 404 look more like the docker daemon's REST
> API than the Registry API:
> https://gist.github.com/mmdriley/0ed2129a93fd0c15ff36#life-of-a-docker-pull
>
> So in this context, I believe the 404 was the docker daemon telling the
> client that it doesn't have that image locally, not that GCR doesn't have
> it.
>
> Perhaps this segment of the log precedes the pull?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/6134#issuecomment-87487788>
> .
>



-- 
Pires

**Comment by jlowdermilk** [comment]
@pries, is your kubernetes installation still failing to bring up the kube2sky pods? You closed the issue but seem to still be having trouble.

**Comment by pires** [comment]
@jlowdermilk I'm using `kubernetes` repo on Docker Hub and not `gcr.io/google-containers` so i's working alright.

**Comment by pires** [comment]
@AntonioMeireles is this working on your fork?

**Comment by AntonioMeireles** [comment]
@pires yup. both with  gcr.io/google-containers/... and with kubernetes/... only difference being that from gcr.io things are a *bit* slower as there is no caching at all. anyway in this regard i don't think this has anything to do with our trees. either this is some transient net issue or is related to something in the middle - between gcr.io and docker client that messes things. (i've seen in the past 'interesting' corner cases related with firewalls, VPNs vs docker and messed up http transfers)

**Comment by mattmoor** [comment]
@AntonioMeireles where are you running?

**Comment by AntonioMeireles** [comment]
@mattmoor  - most of the testing is plain vagrant on a mac.

**Comment by danielschonfeld** [comment]
Was there any further understanding as to why this happens? I have the same thing happening to me as the OP does with CoreOS 675.0.0 running on a bunch of VMs in GCE.

I can pull fine manually SSHing into the VM but using the replication controller i see in the docker logs that the image isn't found and `kubectl get pods` just hangs waiting for the images never realizing they aren't being downloaded

**Comment by mattmoor** [comment]
I just provisioned a GCE VM with CoreOS 675.0, and can pull just fine (providing no authentication):
```
$ docker pull gcr.io/google-containers/pause:1.0
Pulling repository gcr.io/google-containers/pause
6c4579af347b: Download complete 
511136ea3c5a: Download complete 
e244e638e26e: Download complete 
Status: Downloaded newer image for gcr.io/google-containers/pause:1.0
```
So unless someone can point me to evidence of problems pertaining to the registry, I'm going to defer to the Kubernetes folks to take point on this, but I'm happy to help.

**Comment by pires** [comment]
As Daniel and I put it before, docker pull works but not from Kubernetes.
@antoniomeireles, i guess this was related to docker MTU or some flannel
config, right?

On Thu, May 14, 2015 at 5:02 PM, mattmoor <notifications@github.com> wrote:

> I just provisioned a GCE VM with CoreOS 675.0, and can pull just fine
> (providing no authentication):
>
> $ docker pull gcr.io/google-containers/pause:1.0
> Pulling repository gcr.io/google-containers/pause
> 6c4579af347b <http://gcr.io/google-containers/pause6c4579af347b>: Download complete
> 511136ea3c5a: Download complete
> e244e638e26e: Download complete
> Status: Downloaded newer image for gcr.io/google-containers/pause:1.0
>
> So unless someone can point me to evidence of problems pertaining to the
> registry, I'm going to defer to the Kubernetes folks to take point on this,
> but I'm happy to help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/6134#issuecomment-102084514>
> .
>



-- 
Pires

**Comment by AntonioMeireles** [comment]
@pires not that i'm aware. what we/you had hit were some issues that arise when one was running local registries and were passing the docker registry auth coordinates (referring explicitly "localhost") to the k8s env ence breaking the registry. in the general case things just work as they should afaict (both to docker hub and gcr.io)

**Comment by danielschonfeld** [comment]
@mattmoor looks like I was misled by the 'error' showing in `kubectl get pods`.  It said it was waiting for the image so that led me to look right away into docker's logs.  However in my case the problem was the lack of secret `dns-token` since I don't use salt or the automated cluster builder scripts.

@thockin has opened a bug for that omission in the docs and we'll have that closed.

bottom line, disregard my call for help.

**Comment by geetachauhan** [comment]
I am getting 403 Server error while trying to pull k8s images. Running on Ubuntu 14.04 LTS. Problem persist even after upgrading to latest version of docker:

$ docker pull gcr.io/google-containers/kube2sky:1.1
Pulling repository gcr.io/google-containers/kube2sky
011d96737112: Error pulling image (1.1) from gcr.io/google-containers/kube2sky, Server error: 403 trying to fetch remote history for 011d967371125f32038886a290eb28a157fea02aad0336Error pulling image (1.1) from gcr.io/google-containers/kube2sky, Server error: 403 trying to fetch remote history for 011d967371125f32038886a290eb28a157fea02aad033645a68ed5dde29a5220
$ docker pull gcr.io/google-containers/pause:1.0
Pulling repository gcr.io/google-containers/pause
6c4579af347b: Error pulling image (1.0) from gcr.io/google-containers/pause, Server error: 403 trying to fetch remote history for 6c4579af347b649857e915521132f15a06186d73faa62145eError pulling image (1.0) from gcr.io/google-containers/pause, Server error: 403 trying to fetch remote history for 6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27

$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.7.0-rc1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 395cced
OS/Arch (server): linux/amd64

**Comment by satnam6502** [comment]
I am very sorry to hear that. Seems to work for me. Perhaps open a new support issue rather than comment on a closed issue? Thank you kindly.
```
$ docker pull gcr.io/google-containers/kube2sky:1.1
Pulling repository gcr.io/google-containers/kube2sky
011d96737112: Download complete
511136ea3c5a: Download complete
075370067b29: Download complete
fc26c11e2ffe: Download complete
281435a08148: Download complete
Status: Downloaded newer image for gcr.io/google-containers/kube2sky:1.1
satnam-macbookpro2:kubernetes satnam$ date
Tue Jun  2 11:10:40 BST 2015
satnam-macbookpro2:kubernetes satnam$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by mattmoor** [comment]
On a second look I happened to notice that you are running 1.7.0-rc1 of Docker.

You are almost certainly hitting this, for which we have an open PR: https://github.com/docker/docker/issues/13649

@jvgogh FYI

**Comment by dalanlan** [comment]
@AntonioMeireles  I wonder whether you were pointing out that we cannot set up a mirror registry for gcr.io as for docker hub. And still the same by now? ;-)
>plain docker-registry is only (so far by design) able to mirror/cache from docker's registry, not from 3rd party private or public repos/registrys (so no caching from quay.io or gcr.io, etc).

**Comment by pires** [comment]
@dalanlan if you're using `docker-registry`, [then yes](https://github.com/docker/docker-registry#mirroring-options) it still applies.

**Comment by dalanlan** [comment]
Uhh.. I didn't realize that gcr.io is a private registry at the very beginning ;( 
Is docker hub the only public registry known to us all?

**Comment by thockin** [comment]
You can make images public on gcr.io - all the kubernetes images are hosted
there.

**Comment by dalanlan** [comment]
Ic.
Let me make it clear. I was wondering if I can set up a mirror registry for gcr.io, since i was suffering networking issues ( GFW, if it sounds familiar, maybe). 
And it's not gonna happen for now since v2 registry is still not ready for that (possibility for building a mirror registry for private registry). So what i can do is just waiting for the new feature:(
OR What else do you have in mind maybe? ;-)

**Comment by thockin** [comment]
waiting for v2 is the right thing to do.
