### ISSUE TITLE
REST api - selflink is incorrect when accessing entities without namespace in url

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#6154]
Accessing entities without namespaces in the url makes the selflink to look corrupted (has namespace missing):

Example - invoking:
http://localhost:8080/api/v1beta3/services/

returns entities with this selflink (note the part after namespaces)
  "selfLink": "/api/v1beta3/namespaces/%7Bnamespaces%7D/services/guestbook"

**Comment by bgrant0607** [comment]
I thought accessing namespaced objects without the namespace was just disallowed in v1beta3.

@derekwaynecarr ?

**Comment by bgrant0607** [comment]
Oh, probably list is allowed for components that need to watch all objects across all namespaces, such as kube-proxy. 

In that case, the selfLink looks broken, yes.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - right.

I will look into the self link this afternoon to see what's going on.  Self assigning.

**Comment by abonas** [comment]
> Oh, probably list is allowed for components that need to watch all objects across all namespaces, such as kube-proxy.
> 
> In that case, the selfLink looks broken, yes.

The api has to allow fetching all objects cross namespaces without specifying namespace, otherwise it will cause multiple requests to the api - per namespace, big overhead for clients.
