### ISSUE TITLE
Eliminate PodStatus.Host in v1beta3

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#6165]
PodSpec.Host sets the node that the pod should be running on. PodStatus.Host should be eliminated in v1beta3; it should be populated from PodSpec.Host in v1beta1/2.

/cc @bgrant0607

**Comment by bgrant0607** [comment]
cc @jszczepkowski

**Comment by piosz** [comment]
Why do we actually want to do it? The meaning of the PodSpec.Host (the request for scheduler to schedule on that host) is different than PodStatus.Host (the host to which this pod is bound to). In the current semantic of scheduling those fields are equal only when PodSpec.Host is not empty and the pod is already scheduled.

Also PodStatus.Host is widely used across the system to check on which node given pod runs. I think users may also find this information useful.

**Comment by bgrant0607** [comment]
The meaning is not different. PodSpec.Host indicates the host on which the pod should run. It shouldn't matter who sets the field. As it stands, PodStatus.Host is entirely redundant.

**Comment by piosz** [comment]
And what about the case when there is no PodSpec.Host specified but users rely on PodStatus.Host? There is also a bunch of kubernetes code that rely on that field in internal representation like https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/controller/nodecontroller.go#L638

**Comment by bgrant0607** [comment]
PodStatus.Host would continue to be set in v1beta1/2, initialized from PodSpec.Host. Components that use the internal representation obviously would need to be changed if the internal representation were changed.

**Comment by piosz** [comment]
So you suggest to also remove PodStatus.Host from internal representation?

**Comment by yujuhong** [comment]
Yes, IIUC, PodStatus.Host should only exist in v1beta1/2 and should not be used in the internal representation at all.

**Comment by piosz** [comment]
Thank for explanation. I'll prepare PR.

**Comment by bgrant0607** [comment]
This is technically a breaking change now that v1beta3 is enabled, but I think it's ok to just slip it in.

**Comment by csrwng** [comment]
When a Host is not specified in the spec, is there a way to get at the current pod Host? The issue is that given a pod, I need to talk to the node using its canonical hostname (must match node's TLS cert). If spec.Host is not set, all I have is the status.HostIP.

**Comment by bgrant0607** [comment]
spec.Host is set by the scheduler.
