### ISSUE TITLE
Support health (readiness) checks

### ISSUE THREAD

**Issue by dbcode** [GoogleCloudPlatform/kubernetes#620]
GCE network load balancers can be configured with health checks (periodic HTTP requests to a user-defined endpoint), such that instances are removed from the pool if they don't respond to the health checks promptly with a 200 status code.

Kubernetes should be able to reuse the same health checks, such that if a user has created a service that they wish to use from Kubernetes, their health checks will do what they expect them to do: cause any unhealthy instances to be removed from the load balancing pool until healthy again.

Ideally, if N frontends talk to M backends, this should *not* result in N x M health check HTTP requests per interval (i.e. each of the N frontends independently health checking each of the M backends).  If that's not possible, maybe Kubernetes could transparently create and use a GCE network load balancer for each service that has more than a certain number of replicas (whether marked as "external" or not), instead of trying to do its own load balancing.

**Comment by bgrant0607** [comment]
Readiness has been implemented. Yeah! Kudos to @mikedanese.
