### ISSUE TITLE
Conversion should recognize primitives and bypass lookups

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#6209]
E.g., it calls Convert() for every byte of a slice of uint8.

E0330 22:15:23.079682    5352 converter.go:449] TIM: converting bool
E0330 22:15:23.079690    5352 converter.go:449] TIM: converting []v1.NamedExtension
E0330 22:15:23.079698    5352 converter.go:376] TIM: converting *[]v1.NamedCluster
E0330 22:15:23.079704    5352 converter.go:449] TIM: converting []v1.NamedCluster
E0330 22:15:23.079711    5352 converter.go:376] TIM: converting *v1.Cluster
E0330 22:15:23.079717    5352 converter.go:449] TIM: converting v1.Cluster
E0330 22:15:23.079734    5352 converter.go:449] TIM: converting string
E0330 22:15:23.079741    5352 converter.go:449] TIM: converting string
E0330 22:15:23.079747    5352 converter.go:449] TIM: converting bool
E0330 22:15:23.079754    5352 converter.go:449] TIM: converting string
E0330 22:15:23.079760    5352 converter.go:449] TIM: converting []uint8
E0330 22:15:23.079775    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079864    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079871    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079877    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079884    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079890    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079897    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079903    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079909    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079915    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079921    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079927    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079933    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079939    5352 converter.go:449] TIM: converting uint8
E0330 22:15:23.079945    5352 converter.go:449] TIM: converting uint8
... thousands of these.

**Comment by lavalamp** [comment]
There's an easy fix for this :/
