### ISSUE TITLE
a note about documentation/communication/change management workflow 

### ISSUE THREAD

**Issue by AntonioMeireles** [GoogleCloudPlatform/kubernetes#6213]
i know that the project is growing like mad, it's still in its early days, and that scalling is always an issue but...
... regardeless of that i think that there are small steps that could taken to smooth things a lot, and avoid some to feel lost or alienated too fast. 
-  for releases and RCs ship with *real* release notes, that point at least the new features, or feature/flag/behavioural changes
- make sure that anytime a new PR gets merged that changes/adds behaviour _shortly_ the docs get updated to match it, as right now there are too much 'assymetry' in the docs as it's very, very hard, (without ending to have to dig in to the source too many times)  to know which specific rev they are targeting/refering to. (heck - i suspect that even the googlebot could get trained to flag/open issues for a good chunck of that ...) 
- as a stop gap it *may* make sense to, also, add some sort of 'tag' field / header to all docs/examples stating explicitly which version they are last know to work with (we already have that in https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/README.md but i would go further and embed that in *every* doc/examples page/file (as often one lands on them via Google, the Search Engine))

imho gradually implementing those small steps would help a lot a lot of people :smile:

**Comment by pires** [comment]
+1

**Comment by zmerlynn** [comment]
Regarding release notes: I'm still compiling release notes for 0.14.0, and
that process is actually getting worked out. I should've marked the notes
as unfinished, but the release itself is still RC, so my apologies.

**Comment by bgrant0607** [comment]
Examples of breakages would help us prioritize what to fix.

We have a table that documents which getting-started guides were known to work when:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides

If any examples in /examples are broken, that's a bug. We have tests to help ensure they stay working.

**Comment by bgrant0607** [comment]
Sorry, I now see your suggestion that the table contents are propagated to the individual pages.

We're working on making the turn-up machinery more maintainable. One necessary element is continuous testing. The new policy is here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/writing-a-getting-started-guide.md

**Comment by AntonioMeireles** [comment]
(as afaict there isn't another way for plain mortals to *link* related (sub)issues)
- GoogleCloudPlatform/kubernetes#6282
- GoogleCloudPlatform/kubernetes#6272
- GoogleCloudPlatform/kubernetes#6212
- GoogleCloudPlatform/kubernetes#6157

(those just the very latest that come to sight)

**Comment by bgrant0607** [comment]
@AntonioMeireles Thanks.

FWIW, I believe anyone can link related issues just by mentioning them, even across github projects.

**Comment by AntonioMeireles** [comment]
@bgrant0607 i know (that's what i ended doing anyway :smile: ).

my point is that *afaik* there are only 2 ways, right now, to relate issues (either labels) or referencing them from another issue/PR. formally this is a github limitation, as unlike - say jira, GH does not provide high *altitude* ways to relate issues/PRs (Blocks/BlockedBy,Depends/Requires,Supercedes,etc) but as the project grows imho one should think in ways to provide some sort of high-level view on what's going on (we all aggree that browsing several hundereds of (open) issues and PRs manually is not exactly a great way...). 

One 'cheap' thing, that possibly could be done quickly with current available (GH) infrastructure could be, thinking loud, to 'train' the googlebot to crawll all the GH issues/PRs and draw somewhere a nice interactive page where one could see the tree that relates all (PRs/issues). it would not be a strict dep tree as the only tangible thing we 'd have afaict is the time, but it would be a start. that way if issue A references, say, a pending PR B, which references issue C, anyone who hits either A or C would get to know about the other. 

Again, just thinking *loud* :smile:

**Comment by bgrant0607** [comment]
@AntonioMeireles Thanks for the idea. We've been making a list of various GH improvements we'd like to see.

**Comment by bgrant0607** [comment]
cc @brendandburns @thockin @davidopp @dchen1107 @erictune

**Comment by bgrant0607** [comment]
cc @timothysc in case he has other suggestions

**Comment by preillyme** [comment]
+1

**Comment by davidopp** [comment]
LGTM. For me the biggest issues are
* make sure release notes link to PRs and/or issues; I'd eve go as far as to say I'd rather have a confusing release note with a link to the PR/issue than a well-written release note with no link
* documentation: like you said, require people to update docs with the code changes, and also I like the idea of adding a "last modified" date on the doc that would only be updated when the doc is updated to match the reality in the codebase (i.e. would not be modified because someone found a typo). This may be simpler than writing "verified with version 0.14" or whatever

**Comment by AntonioMeireles** [comment]
(not doing a PR yet, to avoid splitting this at this stage :smile:)

@davidopp, et al. 
what about starting with something along this ?...
```patch
diff --git a/docs/devel/releasing.md b/docs/devel/releasing.md
index 4cdf882..125355c 100644
--- a/docs/devel/releasing.md
+++ b/docs/devel/releasing.md
@@ -150,3 +150,16 @@ not present in Docker `v1.2.0`:
+## Release Notes
+
+No official release should be made final without properly matching release notes.
+
+There should be made available, per release, a small summary, preamble, of the
+major changes, both in terms of feature improvements/bug fixes and notes about
+functional feature changes (if any) regarding the previous released version so
+that the BOM regarding updating to it gets as obvious and trouble free as possible.
+
+After this summary, preamble, all the relevant PRs/issues that got in that
+version should be listed and linked together with a small summary understandable
+by plain mortals (in a perfect world PR/issue's title would be enough but often
+it is just too cryptic/geeky/domain-specific that it isn't).

```

**Comment by bgrant0607** [comment]
@AntonioMeireles Your text LGTM.

**Comment by davidopp** [comment]
I think what you wrote may be a little too heavyweight. I think the release notes should just list the main user-visible changes in human-understandable descriptive text, with a link to the related PR and/or issue. I'm not particularly religious about how we define "user-visible" in this context.

**Comment by bgrant0607** [comment]
We're merging on the order of 40 PRs a day on weekdays. 

I decided to try to browse commits in the release branch at the tag to see if that was at all a reasonable thing to expect people to do.

First page:
https://github.com/GoogleCloudPlatform/kubernetes/commits/v0.14.1

Last page:
https://github.com/GoogleCloudPlatform/kubernetes/commits/v0.14.1?page=21

More than 20 pages, at more than 30 commits per page.

Some human filtering and/or summarization is necessary, but filtering purely after the fact seems infeasible.

I think we need to ask the person who reviewed or merged the PR to label a PR that needs to be surfaced in release notes, and a way to then automatically cull release notes from those selected PRs.

**Comment by davidopp** [comment]
> I think we need to ask the person who reviewed or merged the PR to label a PR that needs to be 
> surfaced in release notes, and a way to then automatically cull release notes from those selected PRs.

+1

In fact we could also ask them to write the description that should appear in the release notes. Then the person preparing the release notes just needs to copy-paste and link to the PR/issue.

**Comment by rjnagal** [comment]
+1 for release-note label.

**Comment by timothysc** [comment]
So I think at this point we're in the middle of the hurricane for 1.0.  I almost think post 1.0 there needs to be a massive cleaning & documentation festivus, but I don't see a policy shift being viable until that point.   

+1 for release-note label but gate the merge on release note, post 1.0.  

IMHO a k8's contributor meetup ~ Dockercon to define policy would be super useful.

**Comment by AntonioMeireles** [comment]
guys... fwiw the release notes for [0.15.0](https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.15.0) are, in this scope, heaven on earth. **thanks** to all involved!

**Comment by davidopp** [comment]
+1, major kudos to @roberthbailey . We should use those release notes as the canonical guide for how to do it in the future.

**Comment by thockin** [comment]
+1 looks great

On Tue, Apr 14, 2015 at 3:11 PM, David Oppenheimer <notifications@github.com

**Comment by timothysc** [comment]
awesome @roberthbailey!

**Comment by pires** [comment]
I agree. Could the next step be adding migration docs? Would be very useful
for people that use the CoreOS stuff, for instance.
I for one feel the pain of having my stuff broken pretty much on every
release. Makes it really hard to update getting started guides.

**Comment by bgrant0607** [comment]
FYI: I just created a release-note label for PRs making user/admin-visible changes that should be mentioned in the release notes:
https://github.com/GoogleCloudPlatform/kubernetes/labels/release-note

**Comment by roberthbailey** [comment]
Thanks @bgrant0607. Consistent use of that label will make generating release notes significantly easier going forward.
