### ISSUE TITLE
Most ValidateFooUpdate don't call ValidateFoo

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#6219]
This results in it being possible to update all sorts of fields to illegal values.

@smarterclayton I think we want to either make all ValidateFooUpdate() call ValidateFoo() or else make REST objects call both sets of Validate functions.  What think?

**Comment by smarterclayton** [comment]
So certain things are legal on create that are illegal on update.  The REST object definitely is the final arbiter of calling the right method which does the right thing.  I'm think it would work if individual REST strategies call validateX before validateXUpdate, but we should be sure that validate* now stops mutating the resource (which a few did before PrepareBeforeUpdate was added).

----- Original Message -----

**Comment by thockin** [comment]
So you think the REST object should call `ValidateFoo(new);
ValidateFooUpdate(old, new)` in their own ValidateUpdate() methods?

Why would it not be correct to call `strategy.Validate(new);
strategy.ValidateUpdate(old, new)` in `BeforeUpdate()`?  It seems to me
that every updated object must also be a valid object.

That also make it very clear what  ValidateUpdate() should be checking and
what it should not.

**Comment by smarterclayton** [comment]
> On Mar 31, 2015, at 3:03 PM, Tim Hockin <notifications@github.com> wrote:
> 
> So you think the REST object should call `ValidateFoo(new);
> ValidateFooUpdate(old, new)` in their own ValidateUpdate() methods?
> 
> Why would it not be correct to call `strategy.Validate(new);
> strategy.ValidateUpdate(old, new)` in `BeforeUpdate()`? It seems to me
> that every updated object must also be a valid object.
> 
> That also make it very clear what ValidateUpdate() should be checking and
> what it should not.

Part of the reason ValidateUpdate was separate to allow that decision to be made by the strategy.  I would prefer to keep that factoring, because they are separate.

**Comment by lavalamp** [comment]
@thockin Where does this currently go wrong? I know I asked for both to get called when I reviewed a change for rep. ctrls.

**Comment by thockin** [comment]
Until I fixed it, for example, ValidateServiceUpdate() allowed through
perfectly invalid services.
