### ISSUE TITLE
Can we use gcr.io/google_containers instead of gcr.io/google-containers in path to GCR images?

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#6229]
I cant bring up the monitoring addons on my local cluster after https://github.com/GoogleCloudPlatform/kubernetes/pull/6030.
I turns out that thats because I am using an older version of docker which does not allow "-" in namespaces.
I get `Invalid namespace name (google-containers), only [a-z0-9_] are allowed, size between 4 and 30` error on running `$docker pull gcr.io/google-containers/heapster`.

@thockin suggested that we can change the path to use google_containers instead of google-containers since that works for all versions of docker.
Using google-containers only works for docker versions 1.5+
Filling this issue to hear what others think about this.

**Comment by nikhiljindal** [comment]
@vishh @satnam6502 @mattmoor @jlowdermilk

**Comment by mattmoor** [comment]
SGTM

**Comment by jlowdermilk** [comment]
Fine with me. I'm working on moving the e2e images, can make this change at same time.

**Comment by satnam6502** [comment]
SGTM. Take note @dchen1107

**Comment by thockin** [comment]
please double and triple check to get everything :)

**Comment by dchen1107** [comment]
@satnam6502 Thanks for heads-up. I am in the middle of pushing kubernetes/pause and etcd_server to gcr.io. Will make sure use the right path here.

**Comment by AntonioMeireles** [comment]
fwiw added GoogleCloudPlatform/kubernetes#6301 to *complement* already merged PRs...
