### ISSUE TITLE
Add an etcd soak test.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#6230]
This is optional, and I'm open to opinions on wether or not we should/shouldn't have an etcd soak test.  I found it useful in an experiment this week, so im happy to PR it if we like the idea.

Given that erroneous  etcd deployments can  lead to  nodes being split brained (not an etcd issue necessarily, just a general distributed systems issue that can crop up due to network partitions or other infrastructure problems) , we can add an etcd soak test to optionally run periodically on kube clusters...  I have one such test psuedo code is below...

```
//TEST: That each the WRITE from any server is READABLE from any OTHER server.
//given an integer n, which is the # of writes to test.
for each i in n
   write key $i to etcd to a random server

for each i in n
   for each server s
       read key $i from s
       if key not there, fail.

for each i in n
   delete key
//pass test.
```
concretely, 

```
for etcd servers s1, s2, s3
if n = 7
write 
  server1->(k1,k1)
  server2->(k2,k2)
  server2->(k3,k3) 
  server3->(k4,k4) and so on, until we write k7,

then 
  on server1
      read k1,k2,k3,....k7 (fail if one is unreadable)
  on server2
      read k1,k2,k3,....k7 (fail if one is unreadable)
   ... and so on
```

**Comment by roberthbailey** [comment]
I think it would make more sense for an etcd soak test in the etcd github repo rather than in the kubernetes repo. A kubernetes specific soak test (#3137) will test the etcd instance used by the master with our particular usage patterns. 

That being said, kubernetes seems like a great platform on which to build an etcd soak test, since you can easily schedule etcd pods and load testing pods around a cluster to do the soak test.

**Comment by jayunit100** [comment]
Im happy to close this.  Just wanted to bring up  in case folks were interested.

**Comment by xiang90** [comment]
@roberthbailey @jayunit100 

We have a flexible testing suite in etcd repo. https://github.com/coreos/etcd/tree/master/tools/functional-tester

It would be great if you want to add more test cases into it. It is fairly simple to add a test case: 
https://github.com/coreos/etcd/blob/master/tools/functional-tester/etcd-tester/failure.go#L40-L57
