### ISSUE TITLE
Host kubernetes/pause on gcr.io

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#6231]
I believe this just requires changing the image name [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L861), but I wanted to check that there isn't other work to do before we move it. IIRC, the pause pod is cached on containervm, so we should make sure the `gcr.io/google_containers/pause` tag is also cached.

cc @vmarmol, @dchen1107

**Comment by dchen1107** [comment]
kubernetes/pause is cached in ContainerVM image, should we remove it after gcr.io host kubernetes/pause?

**Comment by dchen1107** [comment]
I am going to do this, since I plan to push etcd_server to gcr.io today.

**Comment by jlowdermilk** [comment]
@dchen1107, I think we still want to cache it in ContainerVM image, just with the gcr.io tag.
