### ISSUE TITLE
pkg/cloudprovider/controller unit tests flake

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#6236]
Data race in TestSyncProbedNodeStatusEvictPods, most recently [in this build](https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/56610116).

**Comment by pmorie** [comment]
@zmerlynn FYI

**Comment by vmarmol** [comment]
Dup of #6199 so I will close in favor of that :)

This is apparently going away which will be the fix.
