### ISSUE TITLE
EmptyDir volume tmpfs mounts should have the correct selinux context set

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#6238]
Tmpfs mounts done by the `EmptyDir` volume plugin will by default receive a different security context than the kubelet root dir.  This results in AVC denials on reads from the container's selinux context while selinux is enforcing.  We should change the EmptyDir volume plugin to set the `rootcontext` option of the mount based on the selinux context of the kubelet rootdir.

Eventually this will touch the [security context work](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/security_context.md).

**Comment by pmorie** [comment]
@pweil- FYI since I know security contexts are relevant to your interests.

**Comment by pmorie** [comment]
@thockin

**Comment by pmorie** [comment]
@erictune @thockin

Taking a look at this I think the biggest question I have when porting my code from #5162 in is how the `EmptyDir` plugin should find out about the kubelet's `rootDir`.  It seems like the cleanest thing to do is to have a method in the `volume.Host` interface that exposes it:

```go
type Host interface {
  // other methods omitted
  GetRootDir() string
}
```

Then, the `emptyDir` plugin can use libcontainer to read the selinux context of the root dir and pass it to `mount`.  It seems pretty hacky, but it's the cleanest way I can think of at the moment.  We will eventually have to include security context to use in the `Builder` interface; at that point, we can remove this function from the plugin.  Thoughts?

**Comment by pmorie** [comment]
@jiangyaoguo FYI

**Comment by pmorie** [comment]
@jiangyauguo For the test image, you can follow the pattern for the network tester and entrypoint tester in `contrib/for-tests`

**Comment by thockin** [comment]
In general I dislike the solution of exposing the root dir, and prefer
answering the actual question: "get me the security context"

**Comment by pmorie** [comment]
@thockin Does this change your LGTM on my other pull?

**Comment by thockin** [comment]
LGTM was provisional on your intent to do it right Real Soon :) and remove
that Host method - did I misinterpret?

**Comment by pmorie** [comment]
@thockin yeah -- and honestly I would prefer that Real Soon was before it went in.  I'm going to sync up with @pweil- today and see if we can make a sketch that will grow into security contexts without having to change all the plumbing in that PR.

**Comment by dchen1107** [comment]
#6379 was merged, can we close this one now?

**Comment by pmorie** [comment]
@dchen1107 yep
