### ISSUE TITLE
`kubectl create -f -` stops on first error (it should continue)

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#6255]
Something broke with EagerVisitorList and stream handling.  Probably an ordering issue.  Create should try to create all so that you can run it multiple times in a row and hopefully make progress.

**Comment by smarterclayton** [comment]
And it needs a test case to make sure it doesn't regress.

**Comment by bgrant0607** [comment]
I'd take this for 1.0 if you want to try to get it in.

**Comment by smarterclayton** [comment]
I fixed this a while back.
