### ISSUE TITLE
Upgrade header being added implicitly

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#6264]
Forked from: https://github.com/GoogleCloudPlatform/kubernetes/pull/6175

I started a cluster on GCE and sent a simple GET request at `https://104.155.58.27/api/v1beta1/proxy/services/monitoring-grafana` via browser and printed the request received by proxy.go.
This is the output:

```
&{GET /api/v1beta1/proxy/services/monitoring-grafana 
HTTP/1.1 1 1 
map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8] 
User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36] 
Accept-Encoding:[gzip, deflate, sdch] 
Accept-Language:[en-US,en;q=0.8] 
Connection:[upgrade] 
Authorization:[Basic YWRtaW46SGY4d1BNSHloU3Q0cFJsZg==]] 
0x1329250 0 [] false 127.0.0.1:8080 map[] map[] <nil> map[] 127.0.0.1:40439 /api/v1beta1/proxy/services/monitoring-grafana <nil>}
```

The request has a `Connection:[upgrade] ` header even tough the original request did not have it.
Clearly someone is adding this header. @lavalamp suggested that this is unexpected. No one should be modifying request headers.
The header is not added when the cluster is running on localhost

The Request headers in Network tab of Chrome are:
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Basic YWRtaW46SGY4d1BNSHloU3Q0cFJsZg==
Cache-Control:max-age=0
Connection:keep-alive
Host:23.251.148.110
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
```

**Comment by davidopp** [comment]
@ncdc This seems to be related to the proxy feature you added. Is there some other criteria besides the Upgrade header that should be checked before starting the SPDY proxy?

**Comment by ncdc** [comment]
This is actually not related to my proxy work. This is coming from the nginx configuration here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/nginx/kubernetes-site#L64 (from #1203 in September 2014). Please see http://nginx.org/en/docs/http/websocket.html for details on why this is required for websocket and the exec & port forward features I added.

**Comment by jimmidyson** [comment]
@nikhiljindal If you build a new cluster is this still happening? Wondering if this was happening on a cluster using the old nginx proxy which was adding this header to every request, but is now no longer used.

**Comment by nikhiljindal** [comment]
I tried it right now and it works fine. Closing the issue.
Thanks @jimmidyson!
