### ISSUE TITLE
Formalize/document changelog update policy

### ISSUE THREAD

**Issue by lyda** [GoogleCloudPlatform/kubernetes#6282]
Sorry, but I'm wondering what the deal is with CHANGELOG.md? Will it be updated or is there somewhere else I should be looking?

**Comment by bprashanth** [comment]
Fair point, looks like we haven't updated it in a while. What exactly are you looking for?

**Comment by lyda** [comment]
Well, 0.14 just got released and I was curious what was in it since I just spun up a 0.13 cluster on AWS. If 0.14 has AWS improvements, I'm guessing now would be a good time to try them! But I can just read a git log between 0.13 and 0.14 - but a summary would be nice.

Also, a pony. :)

**Comment by bprashanth** [comment]
Ah, so this boils down to a release notes problem. In that case you want to follow #6213. We'll have more luck pushing that since it's a P1.

**Comment by dt-rush** [comment]
The current changelog stops at 0.9... what's up with that?

**Comment by bgrant0607** [comment]
The plan is being hashed out in #6213.

Our release notes have been posted on the releases page:
https://github.com/GoogleCloudPlatform/kubernetes/releases

**Comment by roberthbailey** [comment]
Fixed by #7096.
