### ISSUE TITLE
kubernetes is not correctly removing nodes in faulty state

### ISSUE THREAD

**Issue by Andre-Freitas** [GoogleCloudPlatform/kubernetes#6285]
in my kubernetes lab cluster (0.13.2) i'm having a issue where faulty nodes are not being changed to not ready status.
I only detected this because docker service wasn't working on that node (which depends on flannel.service [that depends on the network interface where 172.17.8.104 was configured])

```
$ date
Wed Apr  1 11:55:11 WEST 2015

$ kubectl get minion
NAME                LABELS              STATUS
172.17.8.102        <none>              Ready
172.17.8.103        <none>              Ready
172.17.8.104        <none>              Ready

$ kubectl describe minions 172.17.8.104
Name:	172.17.8.104
Conditions:
  Type		Status	LastProbeTime				LastTransitionTime			Reason					Message
  Ready 	Full 	Wed, 01 Apr 2015 10:12:22 +0000 	Mon, 01 Jan 0001 00:00:00 +0000 	kubelet is posting ready status 	
Addresses:	172.17.8.104
Capacity:
 cpu:		1
 memory:	1021908Ki
Pods:		(0 in total)
```

**Comment by bprashanth** [comment]
Maybe the kubelet should report an unhealthy node status when it can't syncpods?

**Comment by dchen1107** [comment]
In this case, one NodeCondition to indicate if docker running happily on the node should be introduced. NodeController should change NodeStatus based on the NodeCondition.

**Comment by davidopp** [comment]
Action Item: Kubelet should set NodeStatus=False when docker is dead.
