### ISSUE TITLE
"failed to find fit for pod" when creating  pod, but works as RC

### ISSUE THREAD

**Issue by nickjj** [GoogleCloudPlatform/kubernetes#6286]
#### Kubernetes version
v0.13.2

#### Setup
I was trying to get postgres up and running on a coreos/kub cluster under vagrant.

The vagrant setup was taken from your docs:
https://github.com/pires/kubernetes-vagrant-coreos-cluster/

The postgres setup was taken from @kelseyhightower's recent talk:
https://github.com/kelseyhightower/cfgmgmtcamp-2015/blob/master/demo/pods/postgres.json

The only change I made was switching the `nodeSelector` to `master` so it matched the vagrant setup.

I created it with this command:
`kubectl create -f pods/postgres.json`

#### Expected

A pod to be `running` after a reasonable amount of time.

#### Actual

It hung indefinitely at `pending` and after digging through the journal logs I was able to find this error:

```
Mar 31 19:48:18 master kube-scheduler[897]: E0331 19:48:18.369693     897 factory.go:248] Error scheduling default postgres: failed to find fit for pod: {{ } {postgres  default /api/v1beta1/pods/postgres?namespace=default d7dda202-d7de-11e4-99d0-080027a81583 12954 2015-03-31 19:48:03 +0000 UTC map[name:postgres] map[]} {[{pgdata {0xc2080f87a0 <nil> <nil> <nil> <nil>}}] [{postgres postgres []  [{ 0 5432 TCP }] [{POSTGRES_PASSWORD coreos}] {map[]} [{pgdata false /var/lib/postgresql/data}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Always ClusterFirst map[role:master] } {Pending []     map[]}}Node 172.17.8.102: MatchNodeSelectorNode 172.17.8.103: MatchNodeSelector; retrying
```

#### Strange fix

I simply changed it from a pod to a replication controller and then it started fine. I was only able to connect to `psql` with docker exec from within the container postgres was running from, despite making a service out of it with a public IP but that's likely another issue of its own.

**Comment by bprashanth** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/6110 should fix the problem. If it doesn't please update with your postgres and rc manifest in a gist, if it does please close this issue.
