### ISSUE TITLE
Recording an event fails when cached but no longer exists in apiserver

### ISSUE THREAD

**Issue by simon3z** [GoogleCloudPlatform/kubernetes#6289]
Recording an event that is already cached (in the controller) fails when the object no longer exists in apiserver.

If you combine this with the fact that once in while all the events are flushed from apiserver, you'll end up with all the events that are cached in the controllers that will never be reported anymore.

    E0401 09:37:11.468342   17542 event.go:164] Server rejected event '&api.Event
    {TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:
    "vm-oshift02.13d0e74c348d36ff", GenerateName:"", Namespace:"", 
    SelfLink:"", UID:"", ResourceVersion:"86319", CreationTimestamp:util.Time{Time:
    time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil),
    Labels:map[string]string(nil), Annotations:map[string]string(nil)},
    InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"vm-oshift02",
    UID:"vm-oshift02", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"offline",
    Message:"Node vm-oshift02 is now offline",
    Source:api.EventSource{Component:"controllermanager", Host:""},
    FirstTimestamp:util.Time{Time:time.Time{sec:63563492196, nsec:0,
    loc:(*time.Location)(0xf6e6c0)}}, LastTimestamp:util.Time{Time:
    time.Time{sec:63563492231, nsec:453054355, loc:
    (*time.Location)(0xf6e6c0)}}, Count:2}':
    '100: Key not found (/registry/events/default/vm-oshift02.13d0e74c348d36ff) [86351]'
    (will not retry!)

**Comment by bprashanth** [comment]
AFAIK we don't aggregate events in the controller, so you're describing a race between recording an event and deleting the objects the event references?

**Comment by simon3z** [comment]
@bprashanth look at `pkg/client/record/events_cache.go`, the client side is used in the controllers.

**Comment by bprashanth** [comment]
Oh, you're probably right then, lets send this over to someone who actually knows events for triage @saad-ali

**Comment by simon3z** [comment]
@bprashanth @saad-ali fix is here: https://github.com/GoogleCloudPlatform/kubernetes/pull/6290
