### ISSUE TITLE
Include events in kubectl output for pods in <pending>

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#6302]
I was helping someone debug an issue on irc, the problem was obvious looking at events. The pod was stuck in pending because the kubelet was rejecting it, because the volume (a pd) wasn't created (it was actually created in a different zone). It sounds easy enough to include the events of pending pods, if any. Feel like !Pending would be less useful unless you were in a crashloop of running or something.

**Comment by yujuhong** [comment]
`kubectl describe pod <pod_name>` should show you the events associated with the pod. Are you suggesting we display events in the output of `get pods`?

I was thinking about maybe we could display the last event in a compact form in the output of `get pods`

**Comment by bprashanth** [comment]
the problem was i knew how to get events, they didn't

**Comment by bprashanth** [comment]
probably captured somewhere or the other

**Comment by dchen1107** [comment]
Here is a generic rule for our kubectl:

kubectl get resource includes the information from one resource. For example, kubectl get pods id only display the information from Pod object.

kubectl describe can include the information from various resources. For example, kubectl describe pods id includes the information from Pod object, and events.

**Comment by dchen1107** [comment]
cc/ @brendandburns since he is looking into some kubectl related issues?

**Comment by yujuhong** [comment]
I was going to suggest adding a new column `latest event message` in the output of `get pods` to show the latest event. This would help with clarity but would violate the rule @dchen1107  pointed out.

**Comment by bprashanth** [comment]
Naive question, do we really need 2? If we're talking about less vs more, we could just use -v.
