### ISSUE TITLE
Apiserver <> Node status update response time

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#6306]
When inspecting the messages sent on a single node status update, it appears to perform the following sequence: 

Get Node<>apiserver<>etcd 
Put Node<>apiserver, Get apiserver<>etcd, Put apiserver<>etcd

This total response time ~.1 seconds per update, which results in a couple of questions, but the most prominent one is: "Why are there excessive gets, if it's an update, why not just a 'Put' through?  

![screenshot from 2015-04-01 14 18 52](https://cloud.githubusercontent.com/assets/169553/6949570/be9be428-d87a-11e4-8722-b89819f9ebe8.png)

**Comment by bprashanth** [comment]
The apiserver needs to get the `current` version of the resource and compare it with the update for validation. You can expect to see additional gets on an update if something else is updating the same resource at the same time (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper.go#L317). there might still be some sort of excessive getting involved though, ive only spent a few seconds thinking about it. did you observe similar patterns on all updates or just node status?

**Comment by timothysc** [comment]
I saw similar patterns on all PUTS, but it still seems excessive imho.

**Comment by bprashanth** [comment]
validation (the update could contain total garbage) and retries (which would have to happen on the client otherwise, because we use optimistic concurrency https://github.com/GoogleCloudPlatform/kubernetes/blob/c9ad322ba97e448ddb462951821ab96c43ac6a96/docs/api-conventions.md#concurrency-control-and-consistency).

**Comment by timothysc** [comment]
The referenced document makes sense for multiple writers, but in the case of node-status there should be only one, and you could probably say the same thing for pod-status.

**Comment by davidopp** [comment]
@wojtek-t @fgrzadkowski

**Comment by bprashanth** [comment]
I should clarify. There's a base case of  2 Gets:
1. In the node controller, because you need to send a node object with the right resource version for the update to succeed (regardless of probability we're still not guaranteed to be the only ones updating the node at some point, even kubectl could update it, so we need the current resource versoin).
2. For validation

On top of this, *if* something conflicts (which might be rare), you will see additional gets.

**Comment by dchen1107** [comment]
cc/ me

**Comment by timothysc** [comment]
This particular use case of Node status updates, I see no reason why it should not be a single PUT.  I agree, that there may be other conditions where the extra checking makes sense, especially when there are multiple writers.  

However, I think making a couple of tweaks could turn down the api-server noise and we are also probably safe to back off the frequency of the updates.

**Comment by wojtek-t** [comment]
cc/ me

**Comment by mattf** [comment]
@timothysc is the issue that the api-server will need to scale to multiple write-active instances? in such a case etcd will not accept a PUT if it isn't updating the most recent version of the object. if you have a single apiserver is can cache the information stored in etcd and skip the GET, effectively treating etcd like a storage device.

**Comment by davidopp** [comment]
Sorry for replying late. NodeStatus actually has multiple writers. It was easier to do this than to change the API (partially sparking my rant #6363). Kubelet writes the True and False values of NodeRunning NodeCondition in NodeStatus, while NodeController writes the Unknown value of NodeRunning NodeCondition. You shouldn't see the Kubelet doing more than a Get followed by a Put, though. If you're seeing multiple Gets or Put, there may be something wrong. FWIW the code on Kubelet is updateNodeStatus() in pkg/kubelet/kubelet.go

We are planning to set the NodeStatus interval to 10 seconds soon (#5953).

**Comment by bprashanth** [comment]
There's a second get to validate the update apiserver side, we shouldn't blindly trust payloads. I'd need to collect more data before committing to optimize at this level of gets/puts.

**Comment by davidopp** [comment]
@bprashanth Can you point me to the code in the API server that is doing the get/put related to validation?

**Comment by bprashanth** [comment]
It should be a part of the update flow:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper.go#L163

It's how validateMinionUpdate gets the old minion (unless something's changed recently):
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L1045

**Comment by timothysc** [comment]
@davidopp decreasing the overall # of PUT's alone will have a significant impact.  Currently .09 of the .1 is spent on a put to etcd.

**Comment by timothysc** [comment]
I'm going to close this issue, b/c the excessive GET's for a PUT are only a fraction of the cost of the actual PUT to etcd and simply turning down the excessive PUT's will help some of the traffic issues.   Re: #5953
