### ISSUE TITLE
Add KUBERNETES_NAMESPACE variable to Pod containers

### ISSUE THREAD

**Issue by mfojtik** [GoogleCloudPlatform/kubernetes#6354]
If you want to make a REST calls from containers running in Pod to KUBERNETES_SERVICE, it would be handy to have the namespace that container is launched in available inside the container.

**Comment by mfojtik** [comment]
cc @derekwaynecarr

**Comment by bgrant0607** [comment]
We want to support passing this information to containers, but not by exposing Kubernetes-specific environment variables.

This is essentially the same issue as #386, #560, parts of #1768, https://github.com/GoogleCloudPlatform/kubernetes/issues/2316#issuecomment-86202868, and #5093. The most concrete discussion was in #2316, but the most appropriate issue to use is #386.

**Comment by pmorie** [comment]
@mfojtik I have a WIP that will encompass this; will tag you once it's PR'd

**Comment by derekwaynecarr** [comment]
@pmorie cc me as well.  I agree we need this information.

**Comment by pmorie** [comment]
@mfojtik Looks like #6739 will be merged; I think this can be closed.
