### ISSUE TITLE
Measure latency for client REST operations

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#6357]
Currently we do not measure latency for REST operations. This is important for any component that performs non-watch operations (scheduler, controllers, kubelet). This is also prerequisite to actually make sure that all API calls take less than 1 sec ( #4521).

@wojtek-t

**Comment by a-robinson** [comment]
The apiserver is already [instrumented with latency information](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver.go#L56), including for REST operations. You can scrape the metrics by hitting the /metrics HTTP endpoint.

**Comment by fgrzadkowski** [comment]
Sorry, I was not clear in the description. I'm more interested on the client side and with more details so that I can measure things like:
 * how long it takes to write bindings in scheduler
 * how long it takes to update status in kubelet
I'd think about it as a counterpart for apiserver stats.
