### ISSUE TITLE
update-swagger-spec.sh is not idempotent

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#6359]
Running it repeatedly will produce different results.  Specifically I see 

     "id": "v1beta3.Volume",
     "required": [
      "name",
+     "secret",
+     "nfs",
      "hostPath",
      "emptyDir",
      "gcePersistentDisk",
-     "gitRepo",
-     "secret",
-     "nfs"
+     "gitRepo"

The order of lines is chaging on each run.  Go map iteration problem?

This causes noise for anyone who wants to run it, and prevents it from being a commit hook.

**Comment by satnam6502** [comment]
Idempotency is not the property you want: it is determinism.

**Comment by thockin** [comment]
The pedant is right.  The code is still wrong :)

**Comment by bgrant0607** [comment]
This is pretty annoying. Reordering makes it difficult to tell what has been changed.

I assume we need to make go-restful sort the swagger output in order to fix this?

**Comment by brendandburns** [comment]
Removing this from v1.0

**Comment by nikhiljindal** [comment]
This is now fixed
