### ISSUE TITLE
Move to Kubelet on Master running Etcd in Pod broke Vagrant

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#6372]
Self-assigning as I work out a reliable fix.

**Comment by zmerlynn** [comment]
cc @ArtfulCoder

**Comment by derekwaynecarr** [comment]
Running into a few issues.

On GCE, did you guys block somewhere to wait for etcd to be running before reporting success on kube-up?

**Comment by dchen1107** [comment]
No, except there is a race between addson services, dns and etcd container. We introduced a retry logic on those services.

**Comment by derekwaynecarr** [comment]
I assume pulling the image is just so fast that you don't run into e2e errors, it looks like you guys block on wait-for-minions that uses glcloud, so I guess when minions are reported in etcd, then you know you are good...
