### ISSUE TITLE
Build failure when building kube-controller-manager image

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#6394]
+++ Building docker image: kube-apiserver
Sending build context to Docker daemon   158 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 511136ea3c5a
Step 1 : ADD kube-apiserver /kube-apiserver
 ---> 91666d674931
Removing intermediate container bac96bf20176
Step 2 : ENTRYPOINT /kube-apiserver
 ---> Running in f849d52ad47d
 ---> b0c583271bfc
Removing intermediate container f849d52ad47d
Successfully built b0c583271bfc
+++ Building docker image: kube-controller-manager
Sending build context to Docker daemon 181.7 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 511136ea3c5a
Step 1 : ADD kube-controller-manager /kube-controller-manager
 ---> 6e949bf7fab6
Removing intermediate container 705ec25e84d2
Step 2 : ENTRYPOINT /kube-controller-manager
 ---> Running in 89f9bf062c60
2015/04/02 16:43:48 Error mounting '/dev/mapper/docker-252:0-1048997-89f9bf062c607873c03bb8a0a111a1ca2600936544e0d168e38142dc2c48aa4a-init' on '/var/lib/docker/devicemapper/mnt/89f9bf062c607873c03bb8a0a111a1ca2600936544e0d168e38142dc2c48aa4a-init': no such file or directory
!!! Error in build/../build/common.sh:597
  'docker build -t "${docker_image_tag}" ${1}' exited with status 1
Call stack:
  1: build/../build/common.sh:597 kube::release::create_docker_images_for_server(...)
  2: build/../build/common.sh:564 kube::release::package_server_tarballs(...)
  3: build/../build/common.sh:509 kube::release::package_tarballs(...)
  4: build/release.sh:40 main(...)
Exiting with status 1
!!! Error in build/../build/common.sh:583
  '( local binary_name; for binary_name in "${KUBE_DOCKER_WRAPPED_BINARIES[@]}";
do
    echo "+++ Building docker image: ${binary_name}"; local docker_file_path="$1/Dockerfile"; local binary_file_path="$1/${binary_name}"; if [ -f ${docker_file_path} ]; then
        rm ${docker_file_path};
    fi; printf " FROM scratch \n ADD ${binary_name} /${binary_name} \n ENTRYPOINT [ \"/${binary_name}\" ]\n" >> ${docker_file_path}; local md5_sum=$(md5sum ${binary_file_path} | awk '{print $1}'); local docker_image_tag=gcr.io/google_containers/$binary_name:$md5_sum; docker build -t "${docker_image_tag}" ${1}; docker save ${docker_image_tag} > ${1}/${binary_name}.tar; echo $md5_sum > ${1}/${binary_name}.docker_tag; rm ${docker_file_path};
done )' exited with status 1
Call stack:
  1: build/../build/common.sh:583 kube::release::create_docker_images_for_server(...)
  2: build/../build/common.sh:564 kube::release::package_server_tarballs(...)
  3: build/../build/common.sh:509 kube::release::package_tarballs(...)
  4: build/release.sh:40 main(...)
Exiting with status 1
make: *** [release] Error 1

cc/ @ArtfulCoder

**Comment by dchen1107** [comment]
I did a make clean, then rebuild, still run into the same issue.

**Comment by ArtfulCoder** [comment]
http://kubekins.dls.corp.google.com/job/kubernetes-build/1399/console

The Jenkins build was a success

**Comment by dchen1107** [comment]
After re-run build a couple of times (3 times!), it went well. Close this for now.

**Comment by dchen1107** [comment]
```
$ docker images
REPOSITORY                                         TAG                                IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/google_containers/kube-scheduler            ac30d9ebddfba7c109c82eec14fbd18e   51deb4110b32        3 minutes ago       14.04 MB
gcr.io/google_containers/kube-controller-manager   447e93f7374c44f9edfc22accfa38194   4afbc94144a1        3 minutes ago       18.28 MB
gcr.io/google_containers/kube-apiserver            8aed215158ed58b279ba8845a832f123   3c1e1f1f19ef        3 minutes ago       23.69 MB
```
