### ISSUE TITLE
"Failed to watch *api.Node: No conversion function found for version v1beta1 and kind Node"

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#6395]
Error messages like this are spamming kubelet.log. See any recent integration test log for example or just open kubelet.log.

May be related to #6349, which changed how kubelet watched nodes.

**Comment by bprashanth** [comment]
@timothysc I missed what you were pointing out in irc today because I had a stale apiserver. 'Pologies.

**Comment by yujuhong** [comment]
Thanks @bprashanth for the fix. Closing this issue.

**Comment by timothysc** [comment]
Yup, this was the issue last week.
