### ISSUE TITLE
PD e2e tests are flakey

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#6399]
e.g. for "PD should schedule a pod w/ a RW PD, remove it, then schedule it on another host"

we intermittently see failures like:

"Error deleting PD".

Presumably it needs a retry.

**Comment by zmerlynn** [comment]
@cjcullen actually spent a while on this test and the underlying controller, and it was running rock solid for quite a while. If's flaky, it's probably because something broke. :/

**Comment by quinton-hoole** [comment]
For what it's worth, we're no longer seeing this specific error on Jenkins.  Not sure exactly what fixed it though.

**Comment by quinton-hoole** [comment]
We're seeing this again intermittently in Jenkins, e.g:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/4704/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/4705/

PD should schedule a pod w/ a RW PD, remove it, then schedule it on another host

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:113
Error creating PD
Expected error:
    <*exec.ExitError | 0xc2081680f0>: {
        ProcessState: {
            pid: 13567,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 428000},
                Stime: {Sec: 0, Usec: 80000},
                Maxrss: 46240,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 23222,
                Majflt: 0,
                Nswap: 0,
                Inblock: 0,
                Oublock: 40,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 82,
                Nivcsw: 30,
            },
        },
    }
    exit status 1
not to have occurred

===============


/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:176
Error creating PD
Expected error:
    <*exec.ExitError | 0xc208294468>: {
        ProcessState: {
            pid: 30582,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 444000},
                Stime: {Sec: 0, Usec: 60000},
                Maxrss: 46172,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 23206,
                Majflt: 0,
                Nswap: 0,
                Inblock: 0,
                Oublock: 40,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 81,
                Nivcsw: 30,
            },
        },
    }
    exit status 1
not to have occurred

====================

PD should schedule a pod w/ a RW PD, remove it, then schedule it on another host

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:113
Error creating PD
Expected error:
    <*exec.ExitError | 0xc2082dc3b8>: {
        ProcessState: {
            pid: 21005,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 472000},
                Stime: {Sec: 0, Usec: 44000},
                Maxrss: 46108,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 23206,
                Majflt: 0,
                Nswap: 0,
                Inblock: 0,
                Oublock: 40,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 85,
                Nivcsw: 26,
            },
        },
    }
    exit status 1
not to have occurred

=================

PD should schedule a pod w/ a readonly PD on two hosts, then remove both.

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:176
Error creating PD
Expected error:
    <*exec.ExitError | 0xc208038040>: {
        ProcessState: {
            pid: 27748,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 460000},
                Stime: {Sec: 0, Usec: 60000},
                Maxrss: 46252,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 23200,
                Majflt: 0,
                Nswap: 0,
                Inblock: 0,
                Oublock: 40,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 85,
                Nivcsw: 30,
            },
        },
    }
    exit status 1
not to have occurred

**Comment by quinton-hoole** [comment]
Closing as a dupe of #7972 where it is being actively debugged.
