### ISSUE TITLE
External Load Balancer Name Insufficiently Unique for GCE and GKE

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#6414]
A service `S` in a cluster with name (instance prefix) `C` has a load balancer generated with a name of the form `C-S` e.g. `kubernetes-mygreatservice`. However, this is insufficiently unique because we have to take into account namespaces. Assuming that `alpha` and `beta` are namespaces we could have services `alpha.mygreatservice` and `beta.mygreatservice` on the same cluster. Currently we would generate the same ELB name for these two services which would be a problem for our customers (the wrong thing will happen). If `N` is a namespace we could change the format for the ELB to be `C-N-S` so for the previous example we would have `kubernetes-alpha-mygreat-service` and `kubernetes-beta-mygreatservice`.

I am happy to do this if we feel that this is the right approach. Looking at the bigger picture, we need a better story for external IP access and we may come up with a scheme that makes this kind of approach redundant. However, until then we need something that does not expose customers to a risk of a ELB name clash.

@thockin for external IP
@alex-mohr for GKE

**Comment by thockin** [comment]
Agree.

**Comment by alex-mohr** [comment]
@satnam6502 we also need support for multiple clusters and zones and regions.  I think ELB and GCLB are regional?

I'd propose we end up somewhere like k8s-[$OPTIONAL_ZONE_SUFFIX_IF_RESOURCE_IS_REGIONAL]-$CLUSTERNAME-$NAMESPACE-$SERVICE?  And e.g. GKE might do gke-$ETC instead of k8s-$etc?

**Comment by satnam6502** [comment]
Ah, yes, good point. We could have two clusters both called `wombat` in different zones but in the same project.

**Comment by thockin** [comment]
we don't need a universal format do we?  Each CloudProvider will have their
own format that must be sufficiently unique.  No "optional" required?

**Comment by brendandburns** [comment]
We already handle namespaces and cluster names, see afaik.

https://github.com/GoogleCloudPlatform/kubernetes/blob/3354cffbf0307fd4c2702c7f6612919aeab52b86/pkg/registry/service/rest.go#L276

If this is somehow insufficient, please re-open.
