### ISSUE TITLE
Can't connect to the kubernetes service

### ISSUE THREAD

**Issue by roman-shuhov** [GoogleCloudPlatform/kubernetes#6415]
I'm trying to setup Kubernetes in OpenStack + CoreOS

I have issue with k8s service for redis. Service configuration is:

    {
      "id": "redis-primary",
      "kind": "Service",
      "apiVersion": "v1beta1",
      "port": 6379,
      "containerPort": 6379,
      "labels": {
        "name": "redis-primary"
      },
      "selector": {
        "name": "redis-primary"
      },
      "portalIP": "10.240.63.84"
    }

Please note that 10.240.63.84 is an IP of cluster master. When I create this service i see:

    redis-primary       name=redis-primary                        name=redis-primary   10.240.63.84        6379

And also the endpoint:

    redis-primary       10.244.56.5:6379

Where 10.244.56.5 is an IP of the pod with redis container.

I run flannel with the following configuration:

```
[Service]
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v0.11.0/bin/linux/amd64/kube-apiserver
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-apiserver
        ExecStart=/opt/bin/kube-apiserver \
        --address=0.0.0.0 \
        --port=8080 \
        --portal_net=10.240.0.0/16 \
        --etcd_servers=http://127.0.0.1:4001 \
        --public_address_override=$private_ipv4 \
        --logtostderr=true
        Restart=always
        RestartSec=10
```

So my issue is that i can connect to the 10.244.56.5:6379 , but can't connect to the service 10.240.63.84:6379 . What is wrong in my setup?

**Comment by yujuhong** [comment]
@roman-shuhov, a perhaps naive question because I am not familiar with flannel. Why do you need to specify the portalIP, and make it the same as the IP of the cluster master?

Some common reasons for choosing a portalIP:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#choosing-your-own-portalip-address

@ArtfulCoder, who has experiences with flannel?

**Comment by roman-shuhov** [comment]
my issue is that without portalIP it creates some random IP in 10.240.*.* network, which i can't map to the master

**Comment by roman-shuhov** [comment]
So far, looks like the issue is that k8s services are in different network and i don't have routes for them in my cluster, so k8s is not working properly

    kubernetes          component=apiserver,provider=kubernetes   <none>               10.100.0.2          443
    kubernetes-ro       component=apiserver,provider=kubernetes   <none>               10.100.0.1          80

**Comment by thockin-cc** [comment]
Kubernetes services are virtual.  Their IPs never hit the wire.  No routes
needed.  Mapping the portal IP to your master will NOT do what you want.

I am out today, but I'll be happy to help you next week, if you find me on
IRC.

In the mean time, just create a service, and let the master allocate you a
portal IP.  If you can not access that portal IP...

1) send me the result of 'iptables-save' on one of your nodes, as root.

2) read docs/networking.md and make sure you have the basic networking set
up correctly.

Tim

**Comment by ArtfulCoder** [comment]
@roman-shuhov Are you using flannel or did you mean to say kube-apiserver ? (In your comment, you mention that you are using flannel, but then, you have shown the apiserver cmdline flags)

If you are using flannel, what subnet has flannel assigned to the docker bridge running on the host with the redis container ?

**Comment by bprashanth** [comment]
fwiw I think @roman-shuhov 's problem was more fundamental than a single misconfigure service, the iptables on his minion had no redirect rules, kube-proxy wasn't even able to watch for new services.

**Comment by yujuhong** [comment]
@bprashanth, I don't think @roman-shuhov's `iptables` output shows the NAT tables.
https://gist.github.com/roman-shuhov/dfa87f244e0591c5b01e

`iptables -L -t nat` or `iptables-save' (as @thockin mentioned above) would give us more information.

**Comment by bprashanth** [comment]
yeah I just assumed they were empty, 'pologies @roman-shuhov if you did indeed run without -t nat because I forgot to mention it

**Comment by roman-shuhov** [comment]
will provide this information in 20 minutes. I've just destroyed my cloud and now i'm building it again

**Comment by roman-shuhov** [comment]
Could you please check issue https://github.com/GoogleCloudPlatform/kubernetes/issues/6311 i again stuck with this issue...

**Comment by thockin** [comment]
Roman, are you still having issues?

**Comment by roman-shuhov** [comment]
no, it can be closed, thanks
