### ISSUE TITLE
Unstable pod status in a large cluster

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#6430]
Seven `GET` operations in rapid succession on a 4 node GCE cluster with 500 pods per node.

```
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
900
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
900
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
900
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
899
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
887
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
878
$ kubectl get pods --namespace=serve-hostnames-3162 | grep Running | wc -l
839

```

**Comment by yujuhong** [comment]
@satnam6502, what status were the non-running pods in? It'd help to paste the relevant events and logs.

**Comment by satnam6502** [comment]
I only had a short moment before I had to dash so I thought it was worth mentioning this "for the record" even though I did not have time to gather all the related information. I shall attempt to to this again and and then re-file with more information.
