### ISSUE TITLE
POST request through Proxy with read only port doesn't work

### ISSUE THREAD

**Issue by kazegusuri** [GoogleCloudPlatform/kubernetes#6447]
ReadOnly port accepts [GET method only](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/handlers.go#L53), so other methods like POST to a service(pod) via api proxy does not work. I think proxy and redirect have no side effects to apiserver and allow all requests for those through ReadOnly port, right?

**Comment by goltermann** [comment]
This is by design: POST is inherently a write.   We're looking to get rid of the ReadOnly port as well.
