### ISSUE TITLE
Decide master VM size for our 1.0 performance goals 

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#6454]
Several people have brought this up (including @fgrzadkowski and @yujuhong). We have various performance/scalability goals (e.g. #4521, #3954, #3952) but we haven't stated what VM size we will use for the master when making these measurements. (I'm assuming we can just decide a GCE VM size, rather than a node configuration for every cloud provider we support.) 

We've been setting GOMAXPROCS in various places (#4605, #4675). I'm not sure we've been very systematic about it, but either way, or performance presumably depends on # cores of the master. I believe people have mostly been using 4-core masters for the performance measurements? (I can't remember if we've been measuring memory consumption vs. cluster size, but if not, we should to ensure the VM has enough memory for a 100 node cluster).

Unless someone objects, I'm going to assume we are going to use 4-core VM.

@filipg @wojtek-t @satnam6502 @roberthbailey @lavalamp @bgrant0607 @brendandburns

**Comment by davidopp** [comment]
@erictune

**Comment by satnam6502** [comment]
Rather than having a fixed size master, perhaps we need to assume that the size of the master will be related to the size of the cluster or the total number of pods in the cluster? Perhaps an n1-standard-1 is fine for a four node cluster with 200 pods but we might need a n1-highmem-16 for a 500-node cluster with thousands of pods? Or perhaps the size of the master is more related to the activity (w.r.t. cluster management operations) rather than cluster size? A cluster with a lot of churn will put much more stress on the master than one which after configuration makes very rare adjustments?

**Comment by davidopp** [comment]
I just meant what size will we use for the 100-node/30-pods-per-node goal for 1.0. I agree in general we need to scale the size of the master with the size of the cluster and the operation workload, but that's outside the scope of what I was intending for this issue.

**Comment by bprashanth** [comment]
2 suggestions:
1. Can we decided 1.0 goals for all vm sizes we offer? I'm fairly certain we won't scale linearly with resources on the master (this is the c10k problem)
2. Can we say a cluster with X homogenous nodes can support this QOS, instead of singling out the master?

We could point out that the master is probably a bottleneck if ther're nothing but no-op pause pods on a node. IMHO encouraging a heterogenous cluster will put-off more users than it wins over.

**Comment by lavalamp** [comment]
To be fair, GOMAXPROCS should only make a big difference if there's CPU bound parallelizable stuff--network bound stuff should be parallel anyway.

We do run multiple binaries on the master, though. 4 cores sounds like it should be more than enough.

@bprashanth what specifically won't scale?

**Comment by bprashanth** [comment]
I meant generally, it isn't safe to assume that the server on a machine will get twice as fast with double the resources.  People typically benchmark speed in terms of something like qps. If the master has 200 qps that each take 1s there will probably be 200 pending requests/concurrent connections. Most webservers create a thread to handle each connection and you'll hit a point where the os can't handle it, so performance falls off a cliff. 

This is a hypothetical situation, anything in that software stack could crumble (specifically the parts we don't control, like etcd). It would be nice for users to not have to extrapolate our results to different instance-price points and figure this out the hard way.

**Comment by bgrant0607** [comment]
cc @timothysc

**Comment by bgrant0607** [comment]
1. We need data before we can make a decision: a plot of master cpu vs. number of nodes under a load scaled proportionally to the number of nodes
2. If a fairly beefy machine is required for 100 nodes but not for 10 nodes, we'll likely need to scale the master size with cluster size, for cost reasons

**Comment by lavalamp** [comment]
>Most webservers create a thread to handle each connection and you'll hit a point where the os can't handle it, 

We should measure. Go multiplexes goroutines over OS threads, so our go server won't have this problem (we can have related problems like running out of file handles). nginx I'm not sure about, but I'd like to get rid of that at some point anyway.

**Comment by davidopp** [comment]
> We need data before we can make a decision: a plot of master cpu vs. number of nodes under a load
> scaled proportionally to the number of nodes

I think we need a realistic workload generator for that. I don't think anyone has started working on that yet as we are still benchmarking with fairly simple, unrepresentative workloads (which is totally the right thing to be doing right now).

**Comment by roberthbailey** [comment]
@lavalamp I am working up a PR to remove nginx it from the GCE deployment (it's working locally, just need to clean up the salt stuff).

**Comment by davidopp** [comment]
Nobody screamed, so I think we should say from now on all perf experiments for the 1.0 milestones (see first entry in this bug) should use n1-standard-4 GCE VMs. Does this sound reasonable?

**Comment by a-robinson** [comment]
SGTM

**Comment by fgrzadkowski** [comment]
Regarding graphs etc I'm looking into cpu usage of the master. It seems this is currently the main bottleneck for API calls latency. It seems most of the time we spend it pkg/conversion/.*. I need to dig deeper to show some data.

From my experience, requirements for the master are much higher for larger clusters, even with no pods. Thus scaling master with scaling the cluster size will be definitely needed.

4 core master is a reachable goal for 100 node cluster.

**Comment by wojtek-t** [comment]
@davidopp SGTM

**Comment by bgrant0607** [comment]
@thockin said he observed conversion routines being called for every byte of some arrays/slices. Could be some low-hanging fruit there.

**Comment by bprashanth** [comment]
@fgrzadkowski on an n1-highmem with 16vcpus:
```
$ cat /proc/cpuinfo | grep "core id" | sort | tail -1
core id		: 7
```

I remain skeptical (in a healthy sense) that we can reliably service close to 1000qps [1Get/Put node update/2s+(1Get/Put pod status/10s)x30)x100+watch overhead] and 3 heavy weight master components on 4vcpus. Let the games begin :)

@timothysc out of curiosity what's the profile of your master?

**Comment by yujuhong** [comment]
@lavalamp has already started working on optimizing []byte conversion (see #6435)

@bprashanth, not saying vcpu is enough, but your calculation is slightly outdated. The node status will be (or has been?) changed to post every 10 seconds, and pod status is only sent on actual change.

**Comment by bprashanth** [comment]
I checked before saying :)
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L86

though you're probably talking about https://github.com/GoogleCloudPlatform/kubernetes/issues/5953.  Node status only leads to 1qps*100 in that calculation though, and there's a whole lot of unaccounted watching overhead+queries from controller manager and scheduler I'm not accounting for.

**Comment by bprashanth** [comment]
I stand corrected about pod status if this is not the code sending it:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1631

But if I've read that right it should be once every 10s?

**Comment by bprashanth** [comment]
Hrm, I rescind that 6qps metric, we only send it every 10s on *update* so it would only really be a once every 10s if the pod is crashlooping

**Comment by davidopp** [comment]
We've done what the title of this issue says, and I think we should move any followup discussion to one of other the dozen or so performance-related issues we have open. Closing.

**Comment by xiang90** [comment]
@davidopp We are doing continuous etcd testing on GCE. Is it possible to tell me how many resource would you like to allocate to etcd? So we can help to run under that env and find problems early to ensure etcd can deliver what k8s needs for 1.0/

**Comment by davidopp** [comment]
Hmm, that's an interesting question. I assume the question is for CPU only, not memory and disk. Maybe try 2 cores if you're running etcd by itself? It would be helpful if we knew during regular Kubernetes workloads what is the % of the CPU used by each of the components, so we could use that as a basline. (For example if etcd typically uses 50% of the CPU, then 2 cores would be reasonable.)

@wojtek-t @satnam6502

**Comment by wojtek-t** [comment]
@xiang90 
My current experiments show that currently huuuuge majority of CPU is consumed by Kubernetes apiserver (i.e. I didn't observe etcd as a bottleneck). However there are few parallel efforts to reduce amount of work apiserver is doing (see e.g. #6800 #6518 #6562) so hopefully this will be significantly improved.
But still - I think that 2 cores for etcd is too much (i.e. I mean that 2 cores for apiserver + scheduler + controllers is to low requirement for 100-node cluster).
Can we start we the assumption that etcd is allowed to use 1 core? Or is it unrealistic goal?

cc @fgrzadkowski

**Comment by fgrzadkowski** [comment]
I completely agree with @wojtek-t. Based on CPU profiles etcd is currently using it should not be a bottleneck for a long time. One thing to consider when running etcd tests on GCE is using fast drives (either large PD or SSD PD). Currently k8s setup on GCE uses one of the smallest regular PD, which has insanely small IOPS (we use 10G disk; see https://cloud.google.com/compute/docs/disks/persistent-disks#pdperformance)

**Comment by davidopp** [comment]
@xiang90 Does that answer your question? Sounds like you should use an n1-standard-1 and 10G PD.

**Comment by xiang90** [comment]
@davidopp Yes. Thanks!
