### ISSUE TITLE
The return value is defined as "void" make Python client code to fail

### ISSUE THREAD

**Issue by madhuri-rai07** [GoogleCloudPlatform/kubernetes#6455]
The return type of some the APIs are defined as "void" which make no sense in python. The python client code fail with error "not defined".

**Comment by brendandburns** [comment]
See: https://github.com/swagger-api/swagger-codegen/issues/594

I think swagger-codegen should respect ```"type": "void"```

(at the same time we don't specify return types in lots of places where we should, I'm correcting that in a separate PR.

**Comment by bgrant0607** [comment]
Related: #6167

**Comment by brendandburns** [comment]
Closing as fixed by #6613 (and not actually a bug in this code to begin with...)
