### ISSUE TITLE
Model IDs with dots in them cause Python generated code to fail

### ISSUE THREAD

**Issue by madhuri-rai07** [GoogleCloudPlatform/kubernetes#6456]
The class name in python can't contain dots "." which make the generated code to fail.

**Comment by nikhiljindal** [comment]
We got this fixed in swagger codegen for Java https://github.com/swagger-api/swagger-codegen/issues/567
cc @brendandburns

**Comment by madhuri-rai07** [comment]
Yes, but seems not fixed in Python. Right?

**Comment by nikhiljindal** [comment]
It was fixed for Java for sure (I see that the tests were updated).
I dont see any tests for Python at all: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/test/scala. Hence, I cant tell if it was fixed for python or not.

I see that you have filed an issue https://github.com/swagger-api/swagger-codegen/issues/593. That should help get this fixed.
Thanks!

**Comment by goltermann** [comment]
Closing, will be followed in the swagger-codegen issue above.

**Comment by madhuri-rai07** [comment]
Hi Nikhil,

Imo this is our swagger-spec issue. The swagger-codegen just takes the class name from spec. So we should correct the class name in our spec file. I just tested for api/swagger-spec/v1beta3.json and this also have the problem.
For example:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1beta3.json#L6361

Hence reopening the issue.
