### ISSUE TITLE
'exec' keyword isn't obfuscated in Python

### ISSUE THREAD

**Issue by madhuri-rai07** [GoogleCloudPlatform/kubernetes#6458]

**Comment by nikhiljindal** [comment]
Which version of swagger-codegen are you using Madhuri?
This seems to have been fixed upstream: https://github.com/swagger-api/swagger-codegen/issues/570
cc @brendandburns

**Comment by madhuri-rai07** [comment]
I will check with latest master branch.

**Comment by goltermann** [comment]
@brendanburns  says this is already fixed.  (re-open the bug on swagger-codegen if you still see this)

**Comment by madhuri-rai07** [comment]
On master branch I didn't get this error.
Thanks!
