### ISSUE TITLE
make release now requires very new version of docker (1.5)

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#6463]
I think #6369 now means that 'make release" builds docker images using the -f flag to "docker build".  That was only added in Docker 1.5.  Worse, the failure is silently ignored (make release exits with 0)

I'm currently figuring out how to upgrade docker on Debian Jessie, but I suspect we should do some or all of:

Document that we require Docker 1.5
Detect old version of Docker and warn early
Maybe see if we can get away without using the -f flag?
Change make release so that docker build failures are detected (whatever the cause)

**Comment by justinsb** [comment]
This is kind of tangential, but maybe related to "document that we require Docker 1.5"

Docker was removed from Debian Jessie: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781554 https://lists.debian.org/debian-release/2015/03/msg00685.html

I was able to install Docker 1.5 on Debian Jessie:

```
# Uninstall old version
apt-get remove docker.io
# Install new version
curl https://get.docker.com/ | sh
# Unmask docker services
rm /etc/systemd/system/docker.service
rm /etc/systemd/system/docker.socket
systemctl daemon-reload
# Start docker
systemctl start docker
```

I don't understand systemd enough to know why docker.service & docker.socket are masked.  I also can't believe this is actually the best way of doing things.

**Comment by zmerlynn** [comment]
This wasn't intentional. I can try to figure out how to rework that section. We've been trying to support 1.4, but none of our build infrastructure actually runs old docker (which is probably an oversight), so we let stuff like this slip.

**Comment by justinsb** [comment]
This LGTM but unfortunately I can't easily test with an old version of Docker now, because the version I had installed has now been removed from Jessie...
