### ISSUE TITLE
AWS broken by #6326 - master now needs docker pre-installed

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#6465]
I think #6326 means that cluster/saltbase/install.sh now depends on docker being installed (on the master) before we run salt.

I think it used to be the case that we would install docker through salt.

I'm guessing the GCE image has (a version of) docker pre-installed?

Going to tweak the AWS script to install Docker, but I think this will likely cause problems for most providers...

**Comment by derekwaynecarr** [comment]
This also broke Vagrant.

**Comment by zmerlynn** [comment]
Reassigning to @ArtfulCoder. I've only been mucking around on the build side of that PR (because it hit my other PR). 

Abhi: I'd recommend just killing the entry from top.sls to make this dead code for now, but we need to address this.

(I'm OOO after today or I'd help out.)

**Comment by ArtfulCoder** [comment]
Will get to it. Thanks

**Comment by ArtfulCoder** [comment]
@justinsb I will fix it for all providers. Please don't make an AWS-specific change.

**Comment by justinsb** [comment]
Working now - thanks! Closing.
