### ISSUE TITLE
Some pods still intermittently stay Pending

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#6469]
The following e2e test currently fails about 10% of the time on Jenkins:

"should schedule a pod w/ a readonly PD on two hosts, then remove both"

The error consistently looks like this:

 Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m55.417877935s)

On successful runs, the pods enter running state within a few tens of seconds.  On failed runs they're still pending after 5 minutes (300 seconds). So I don't think that adjusting the timeout is going to help - I don't think that they ever enter running state.

An example log from a failed run is below.  It's fairly easy to replicate both a successful and a failed run locally for debugging purposes (or look in your favorite continuous integration tool).

============== snip snip ===============
PD 
  should schedule a pod w/ a readonly PD on two hosts, then remove both.
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:171
[BeforeEach] PD
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:55
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/.kubeconfig
[It] should schedule a pod w/ a readonly PD on two hosts, then remove both.
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:171
STEP: creating PD "e2e-7dea7303-dc15-11e4-bdd6-42010af01555"
STEP: submitting rwPod to ensure PD is formatted
STEP: waiting up to 5m0s for pod pd-test-7dea76e8-dc15-11e4-bdd6-42010af01555 status to be running
INFO: Waiting for pod pd-test-7dea76e8-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3.915811ms)
INFO: Waiting for pod pd-test-7dea76e8-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (5.009327231s)
INFO: Waiting for pod pd-test-7dea76e8-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (10.014741501s)
STEP: submitting host0ROPod to kubernetes
STEP: submitting host1ROPod to kubernetes
STEP: waiting up to 5m0s for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 status to be running
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (15.63595ms)
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (5.020564429s)
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (10.026824747s)
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (15.033867832s)
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (20.039204352s)
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (25.044015771s)
INFO: Waiting for pod pd-test-7dea7a07-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (30.050154545s)
STEP: waiting up to 5m0s for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 status to be running
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3.706949ms)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (5.008401436s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (10.013678066s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (15.018904187s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (20.024900609s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (25.030912641s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (30.046204243s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (35.051419037s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (40.058850777s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (45.065823592s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (50.071860731s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (55.078050601s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m0.083776508s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m5.089198537s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m10.105209541s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m15.11032494s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m20.12115436s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m25.127158256s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m30.132187181s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m35.13846507s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m40.144456758s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m45.151273162s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m50.156347396s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (1m55.161827077s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m0.167277591s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m5.173298011s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m10.182188145s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m15.188055545s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m20.193118365s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m25.198565912s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m30.204584458s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m35.210786249s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m40.21751876s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m45.223585759s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m50.229100291s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (2m55.235248555s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m0.241794932s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m5.248582101s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m10.257862902s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m15.266852307s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m20.275113729s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m25.283441193s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m30.291584503s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m35.296956839s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m40.305680556s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m45.313869184s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m50.322375377s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (3m55.33000387s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m0.337795083s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m5.346088953s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m10.35514917s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m15.363857516s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m20.374048158s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m25.380129101s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m30.385612431s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m35.392807942s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m40.399068915s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m45.405451133s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m50.411002577s)
INFO: Waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 in namespace default status to be "running" (found "Pending") (4m55.417877935s)
STEP: cleaning up PD-RO test environment

• Failure [360.738 seconds]
PD
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:172
  should schedule a pod w/ a readonly PD on two hosts, then remove both. [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:171

  Expected error:
      <*errors.errorString | 0xc208837f30>: {
          s: "gave up waiting for pod pd-test-7dea7d05-dc15-11e4-bdd6-42010af01555 to be running after 300.00 seconds",
      }

**Comment by quinton-hoole** [comment]
Given that this sort of error seems to be limited to the PD e2e tests at the moment, I would speculate that the fact that pods sometimes never transition from Pending to Running state is somehow related to the mounting of the persistent disk to the container.  But I have not yet confirmed this in the node logs.

**Comment by wojtek-t** [comment]
Is this still a problem? I haven't seen any PD-related failure recently.

**Comment by quinton-hoole** [comment]
Yes, I haven't seen any either, for about a week.  Closing.
