### ISSUE TITLE
kubelet node watch should work in all api versions

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#6495]
My #6423 broke it for v1beta3, then #6442 fixed it for v1beta3 and broke it for v1beta1. I'm working on a fix.

**Comment by lavalamp** [comment]
Honestly I'm very surprised that more people aren't complaining-- integration test logs are full of noise because of this.

**Comment by lavalamp** [comment]
Exact text of error log is "Failed to watch *api.Node: field label not supported: metadata.name"

**Comment by wojtek-t** [comment]
cc @wojtek-t
