### ISSUE TITLE
Mirror pod failures with hostnameoverride

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#6499]
If I start 2 kubelets with hostnameoverride=130.XX they both try to create the same mirror pod because of: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/common.go#L38 leading failures like:
```
E0407 01:45:20.206334   32657 kubelet.go:1332] Failed creating a mirror pod "fluentd-to-elasticsearch-130_default": &errors.StatusError{ErrStatus:api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"pods \"fluentd-to-elasticsearch-130\" already exists", Reason:"AlreadyExists", Details:(*api.StatusDetails)(0xc2085f5940), Code:409}}
```

For the second. Kubectl output shows the first pod:
```
$ ./cluster/kubectl.sh get pods 
current-context: "kubernetesdevgce_e2e-test-beeps"
Running: ./cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl get pods
POD                                                   IP            CONTAINER(S)            IMAGE(S)                                             HOST                                                                     LABELS                                                                      STATUS    CREATED
fluentd-to-elasticsearch-130                                        fluentd-es              gcr.io/google_containers/fluentd-elasticsearch:1.3   130.211.132.165/                                                         <none>                                                                      Pending   7 minutes

```

@yujuhong

**Comment by bprashanth** [comment]
@jonlangemak who was confused about this over irc

**Comment by yujuhong** [comment]
The code was changed to use the first part of the hostname in #5936. If we want to support arbitrary hostname override, perhaps it's easier to revert the PR. @thockin, what do you think?

**Comment by bprashanth** [comment]
I haven't followed the static pods conversation too closely so apologies if this has already been discussed, why not just use labels and allow auto generation of names? Feels like unique names are difficult to achieve without consensus in a distributed environment.

**Comment by dchen1107** [comment]
PR #6466 is talking about removing FQDN name even more.

**Comment by thockin** [comment]
We stayed with FQDN because of so many unknowns.  Is it unreasonable to say
that we require hosts to have unique hostnames?  My own experience here is
"of course that is sane", but @smarterclayton seems to have other
experience...

**Comment by smarterclayton** [comment]
I forget the context under which I said that, consider my opinion invalid.

----- Original Message -----
> We stayed with FQDN because of so many unknowns.  Is it unreasonable to say
> that we require hosts to have unique hostnames?  My own experience here is
> "of course that is sane", but @smarterclayton seems to have other
> experience...
>

**Comment by thockin** [comment]
If that is the case, then Prashanth's initial proposition is invalid -
right?  Don't create 2 kubelets with the same name.

**Comment by bprashanth** [comment]
It's taking the first octet right (in the linked code)?

**Comment by yujuhong** [comment]
@bprashanth, having a deterministic name makes checking whether the pod has been created or not easier. We could of course use labels like replication controllers, but it seems unnecessarily complicated? Don't we need something to uniquely identify a node anyway?

Besides that, there are two issues here.
1. Whether hostname (not FQDN) alone is enough to uniquely identity a node
2. What's allowed to be passed to override hostname? E.g. is IP address allowed?

**Comment by dchen1107** [comment]
I think we shouldn't allow 2 nodes in a cluster with the same name. Name here is short-version of hostname, nbot FQDN one.

I think once we have node auto-join a cluster feature, when node with existing name should be rejected to join the cluster.

**Comment by bprashanth** [comment]
I think we shouldn't use hostname to refer to a host because dns resolution could fail, however using host ip has its own problems (unsure how often hostip changes in various cloudproviders) so this is just a fairly insipid coment

**Comment by thockin** [comment]
I agree with Dawn - nodes can not have the same name.  We define name as
the first token of the FQDN or the hostname override.

Now, should we apply the same "first token" rule to the hostname override
as we do to FQDN?  for simplicity, we should just go with YES, I think

**Comment by dchen1107** [comment]
@thockin Yes then. :-)

**Comment by smarterclayton** [comment]
The machine id from the host is really intended to solve part of this problem.  In most places machine id would be considered better than the host name or ip.

**Comment by dchen1107** [comment]
@smarterclayton naive question related to NodeSpec, what is the difference between MachineID and ExternalID?

**Comment by thockin** [comment]
If we design everything to handle DNS resolution failing, we only really
have IPs to fall back on.  I don't think we want to ident everything by its
IP, do we?

**Comment by bprashanth** [comment]
I think if someone *knows* they're in a hostile dns environment and they're running on bare metal and want to use ips, we should provide an escape hatch that allows them to do so via hostoverride

**Comment by smarterclayton** [comment]
I have no idea, I just know what machine id is supposed to do :).  Federico would have more insight

**Comment by thockin** [comment]
What is a machine ID?

Prashanth: I could live with the override preserving dots, and the default
machine name being first token of hostname.

**Comment by smarterclayton** [comment]
http://www.freedesktop.org/software/systemd/man/machine-id.html

**Comment by yujuhong** [comment]
#7910 uses the first token of `uname -n` as the hostname, but reserves the full string of the override if it is given. This should solve the naming conflict problem that this issue targets.

I am closing this issue and let the discussion of node identification continues in #6557.
