### ISSUE TITLE
Delete by label across all resources

### ISSUE THREAD

**Issue by kargakis** [GoogleCloudPlatform/kubernetes#6511]
Isn't this something that Kubernetes should support? I know that in every kubectl command we have to specify at least one resource so I was wondering which is the best way to implement it. Probably use all registered resources? eg.

```go
var arg string
for kind := range api.Scheme.KnownTypes(version) {
    arg += kind + ","
}
```

and pass `arg` as a resource to `delete`? Any other ideas?

**Comment by kargakis** [comment]
Skimming through Kubernetes code, I stumbled across [this](https://github.com/GoogleCloudPlatform/kubernetes/blob/b6f6de150afe566da8305e224d776d6dc7a6ce6e/pkg/registry/generic/etcd/etcd.go#L143) call. Is it somehow exposed on the client side? It could do the trick as I would just list all the resources matching the specified label right away. Sorry if this is pretty obvious as I am not very familiar with Kube.

**Comment by vishh** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
I agree kubectl should support operations across all kinds of resources. This issue is discussed in #5278 (not just for delete but also for other operations). Could we please move this discussion to that issue?

**Comment by kargakis** [comment]
> Could we please move this discussion to that issue?

Sure, no problem.
