### ISSUE TITLE
Integration tests are failing consistently with "FAILED: pods never started running timed out waiting for the condition"

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#6525]
On my local test cluster: 

E0407 17:08:46.338567     752 reflector.go:143] Failed to watch *api.Node: field label not supported: metadata.name
I0407 17:08:46.681162     752 integration.go:267] Check whether pod nginx-controller-tdiha.test exists on node ""
I0407 17:08:46.681835     752 integration.go:269] Pod nginx-controller-tdiha.test is not bound to a host yet
I0407 17:08:46.892656     752 integration.go:285] Error on creating endpoints: endpoints "service1" not found
I0407 17:08:47.680573     752 integration.go:267] Check whether pod nginx-controller-tdiha.test exists on node ""
I0407 17:08:47.680722     752 integration.go:269] Pod nginx-controller-tdiha.test is not bound to a host yet
I0407 17:08:47.894832     752 integration.go:285] Error on creating endpoints: endpoints "service1" not found
I0407 17:08:48.679410     752 integration.go:267] Check whether pod nginx-controller-tdiha.test exists on node ""
I0407 17:08:48.679497     752 integration.go:269] Pod nginx-controller-tdiha.test is not bound to a host yet
F0407 17:08:48.679523     752 integration.go:436] FAILED: pods never started running timed out waiting for the condition
!!! Error in hack/test-integration.sh:47
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1"' exited with status 255
Call stack:
  1: hack/test-integration.sh:47 runTests(...)
  2: hack/test-integration.sh:60 main(...)
Exiting with status 1
+++ [0407 17:08:48] Integration test cleanup complete
!!! Error in /Users/quinton/code/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:405
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: /Users/quinton/code/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:405 kube::build::run_build_command(...)
  2: /Users/quinton/code/go/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/../build/release.sh:36 main(...)
Exiting with status 1
2015/04/07 10:08:53 Error running build-release: exit status 1
2015/04/07 10:08:53 Error building. Aborting.
exit status 1

**Comment by quinton-hoole** [comment]
This is the version I'm running:

commit ef3cdb2f18d9bfb1c6fd35f631d68a78694a778d
Merge: 621e41e ba1ad9f
Author: Victor Marmol <vmarmol@google.com>
Date:   Tue Apr 7 11:00:16 2015 -0700

    Merge pull request #6491 from yifan-gu/depreciate_getkubeletdockercontainers
    
    kubelet: Refactor RunInContainer/ExecInContainer/PortForward.

**Comment by quinton-hoole** [comment]
Curiously travis does not seem to be running into the same problem:

https://travis-ci.org/GoogleCloudPlatform/kubernetes/builds/57520499  Succeeded.

**Comment by vishh** [comment]
@vmarmol: Can you take a look at the failure?

**Comment by vmarmol** [comment]
Taking a look.

**Comment by vmarmol** [comment]
Passes locally with `hack/test-integration.sh` but fails when running before the e2e. Taking a deeper look.

**Comment by yujuhong** [comment]
Could be related to #6495

**Comment by vmarmol** [comment]
I believe @yujuhong is correct. The error logs are spammed with:

```
E0407 19:43:13.848128     749 reflector.go:143] Failed to watch *api.Node: field label not supported: metadata.name
```

While the success ones don't have any traces of it. The failure also happens when I sync before the PR in question.

**Comment by vmarmol** [comment]
Will run one more test to verify and close as a dup.

**Comment by vmarmol** [comment]
Closing as a dup of #6495

**Comment by yujuhong** [comment]
I don't think this is related to the node watch issue because the test just failed on my desktop with v1beta3 (which should be the working version).

Some relevant messages from the log:
```
I0407 19:56:09.611047    1366 kubelet.go:1294] Creating pod infra container for "nginx-controller-6qgot_test"
I0407 19:56:09.611476    1366 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"nginx-controller-6qgot", UID:"124c545c-dd60-11e4-b87f-0242ac110251", APIVersion:"v1beta3", ResourceVersion:"201", FieldPath:"implicitly required container POD"}): reason: 'pulled' Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
I0407 19:56:09.611880    1366 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"nginx-controller-6qgot", UID:"124c545c-dd60-11e4-b87f-0242ac110251", APIVersion:"v1beta3", ResourceVersion:"201", FieldPath:"implicitly required container POD"}): reason: 'created' Created with docker id /k8s_POD.d41d03ce_nginx-controller-6qgot_test_124c545c-dd60-11e4-b87f-0242ac110251_cd431e36
I0407 19:56:09.611908    1366 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"nginx-controller-6qgot", UID:"124c545c-dd60-11e4-b87f-0242ac110251", APIVersion:"v1beta3", ResourceVersion:"201", FieldPath:"implicitly required container POD"}): reason: 'started' Started with docker id /k8s_POD.d41d03ce_nginx-controller-6qgot_test_124c545c-dd60-11e4-b87f-0242ac110251_cd431e36
I0407 19:56:09.612329    1366 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"nginx-controller-6qgot", UID:"124c545c-dd60-11e4-b87f-0242ac110251", APIVersion:"v1beta3", ResourceVersion:"201", FieldPath:"spec.containers{nginx}"}): reason: 'created' Created with docker id /k8s_nginx.bbc10af3_nginx-controller-6qgot_test_124c545c-dd60-11e4-b87f-0242ac110251_b0c11156
I0407 19:56:09.612410    1366 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"test", Name:"nginx-controller-6qgot", UID:"124c545c-dd60-11e4-b87f-0242ac110251", APIVersion:"v1beta3", ResourceVersion:"201", FieldPath:"spec.containers{nginx}"}): reason: 'started' Started with docker id /k8s_nginx.bbc10af3_nginx-controller-6qgot_test_124c545c-dd60-11e4-b87f-0242ac110251_b0c11156
I0407 19:56:10.016397    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:10.016451    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
I0407 19:56:11.016362    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:11.016389    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
I0407 19:56:11.621338    1366 kubelet.go:1124] No Infra Container for "nginx-controller-k3n14_test" found. All containers will be restarted.
...
I0407 19:56:12.016385    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:12.016459    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
I0407 19:56:13.016337    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:13.016395    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
I0407 19:56:14.016284    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:14.016327    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
E0407 19:56:14.729656    1366 event.go:182] Server rejected event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"127.0.0.1.13d2d37c162a5914", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"online", Message:"Node 127.0.0.1 is now online", Source:api.EventSource{Component:"kubelet", Host:"127.0.0.1"}, FirstTimestamp:util.Time{Time:time.Time{sec:63564033361, nsec:731148052, loc:(*time.Location)(0x19a3020)}}, LastTimestamp:util.Time{Time:time.Time{sec:63564033361, nsec:731148052, loc:(*time.Location)(0x19a3020)}}, Count:1}': 'the server responded with the status code 405 but did not return more information (post events)' (will not retry!)
I0407 19:56:15.016332    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:15.016397    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
I0407 19:56:16.016290    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:16.016321    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
I0407 19:56:17.016399    1366 integration.go:267] Check whether pod nginx-controller-6qgot.test exists on node ""
I0407 19:56:17.016480    1366 integration.go:269] Pod nginx-controller-6qgot.test is not bound to a host yet
F0407 19:56:17.016508    1366 integration.go:436] FAILED: pods never started running timed out waiting for the condition
```

Note that `nginx-controller-6qgot.test` has already started on kubelet (see the events about staring containers), but the integration test still did not see the `Host` filed set on the pod.

**Comment by yujuhong** [comment]
I am not familiar with the list&watch usage. Could it be that at the time of listing, the Host of the pods were not set yet? @lavalamp 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/integration/integration.go#L430

**Comment by lavalamp** [comment]
#6495 is unrelated

**Comment by lavalamp** [comment]
@yujuhong yeah that code is subtly broken; the replication controller can now count pods before they've been assigned. So that list is getting a pod with a "" for its host, and then the podsOnMinions function will never meet its goal.

Possible fix: change podsOnMinions to first wait for the pods to be assigned. Or do that in a separate step.

**Comment by bprashanth** [comment]
I suspect https://github.com/GoogleCloudPlatform/kubernetes/issues/6525#issuecomment-90719360 is a race that has always existed, and not the reason the test is suddenly failing consistently. The rc never waited for host assignment to count toward its replicas, even in the fillCurrentState world we just did a list for the selectos followed by filter active pods (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/controller/replication_controller.go#L182). So it shouln't be suddenly failing for that list race condition?

**Comment by lavalamp** [comment]
This is the most common flake now that I've been looking at these all day.

**Comment by lavalamp** [comment]
There may be more than one cause.

**Comment by vmarmol** [comment]
@lavalamp really? I've been unable to replicate this for about a day. Can you provide some logs (or links) for the failures to help debugging?

**Comment by yujuhong** [comment]
@lavalamp, #6582 did not fix the race condition?

**Comment by lavalamp** [comment]
Here's a recent example: https://app.shippable.com/builds/552704855cb2750c00d8b0ff

It probably has a different cause.

**Comment by yujuhong** [comment]
@lavalamp, there is no message such as `is not bound to a host yet` in that build, so it should be a different bug. In fact, it's likely just another manifestation of the performance/timeout problem in #6651. I just submitted a PR to (hopefully) address that by limiting the number of concurrent tests. We can probably move the discussion over there, unless there is evidence suggests otherwise (e.g. kubelet's dropping pods, etc).

**Comment by lavalamp** [comment]
More examples:

https://app.shippable.com/builds/552865b0892aba0c00bd682e
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/58030039

**Comment by lavalamp** [comment]
Wait, those are both from my PR and I think I caused that. It's been a long day...
