### ISSUE TITLE
Is TestForwardPorts test flaky?

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#6529]
I0407 16:48:52.984645   18026 portforward.go:228] Forwarding from 6000 -> 6000
--- FAIL: TestForwardPorts (0.02s)
	portforward_test.go:289: 2: Error reading data: read tcp 127.0.0.1:5000: connection reset by peer
FAIL
coverage: 57.4% of statements
FAIL	 github.com/GoogleCloudPlatform/kubernetes/pkg/client/portforward	0.168s

https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/57509181

**Comment by vishh** [comment]
cc @lavalamp

**Comment by dchen1107** [comment]
@ncdc Andy, can you take a look at this one?

**Comment by ncdc** [comment]
I've been unable to reproduce locally (Fedora 21 VM) but I will look again.
