### ISSUE TITLE
Starting a container in privileged mode

### ISSUE THREAD

**Issue by tshrklr** [GoogleCloudPlatform/kubernetes#6530]
From https://github.com/GoogleCloudPlatform/kubernetes/pull/1288 it looks like kubernetes supports  starting containers in privileged mode. However I couldn't find any info in either the docs or `kubectl run-container -h` on how to actually run a container with privileged mode enabled.

Additionally, I would like to know if kubernetes allows for host networking mode in a container (--net=host option in docker run)?

**Comment by vishh** [comment]
To run a container in privileged mode, you need to set ['Container.Privileged'](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/types.go#L461) to true. You will have to update your Pod config.

Kubernetes does not allow running container in the host net namespace as of now. I am curious to understand your use case. Why does the current kube networking model not work for your use case?

**Comment by rjnagal** [comment]
In addition, you'll also need to set --allow_privileged flag on all kubelets.

**Comment by tshrklr** [comment]
@vishh I want to be able to run services such as libvirt in my container. Libvirt actively manages the network on the host for running VMs, and therefore requires host net namespace.

**Comment by vmarmol** [comment]
FWIW, you can run with --net=host with the HostNetwork option. You will need to enable it similar to his privileged needs to be enabled.

**Comment by vishh** [comment]
+1 to what @vmarmol mentioned. There are plans to support scheduling system
daemons in the future. Until then, you will have to run a custom setup.

**Comment by tshrklr** [comment]
@vishh @vmarmol  Thanks. When I add the HostNetwork option I see "pod with UID "x" specified host networking, but is disallowed". What flag do I need to add to kubelet to allow host networking? Is it "--host_network_sources"? If yes, what exactly goes in that list?

**Comment by vmarmol** [comment]
@tshrklr that lists sources from which the Kubelet supports HostNetworking. Possible values are: http, file, apiserver, *.

- http: Kubelet receives from HTTP
- file: from the local filesystem
- apiserver: from the apiserver

I'm guessing you're looking for apiserver?

**Comment by tshrklr** [comment]
I first tried adding "--host_network_sources="\"*\"" flag to kubelet as mentioned here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/app/server.go#L167, but doesn't looks like I am using it right as I get "unknown flag: --host_network_sources" error. 

I used "hack/local-up-cluster.sh" to set up my local cluster and added the flag here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/local-up-cluster.sh#L140. Let me know if that doesn't sound right. Thanks.

**Comment by vmarmol** [comment]
@tshrklr are you running Kubernetes from head? The error you're getting is in the Kubelet logs?

**Comment by tshrklr** [comment]
No, turns out I wasn't on the latest master. Ran into some build issues once I pulled in the latest changes. Now my localhost minion is in "NotReady" state, and a kubectl describe on it says `Kubelet never posted node status.`.
Not sure if it's related but I see this in kubelet logs: 
```
Error trying to work out if we can hande /system.slice/system-serial\x2dgetty.slice: error inspecting container: No such container: system-serial\x2dgetty.slice
```

This only seems to happen when I pass the  "--host_network_sources="\"*\"" flag, not otherwise.

**Comment by vmarmol** [comment]
The error should be unrelated (it's cAdvisor working out how to handle the container). If you're still seeing this, can you post the Kubelet logs please?

**Comment by ajit-sarnaik** [comment]
Has this feature of exposing host network devices in a privileged pod been implemented please?

**Comment by RohanKurane** [comment]
I am running into a issue where if I specify ```privileged:true``` in my Pod deployment file and I use CRI-O runtime, the container does not appear to start with privileged status. 
Is there a workaround ?

**Comment by zoobab** [comment]
I do the following:

```
$ kubectl run babeld --image=zoobab/babeld-in-docker --replicas=10 --overrides='{"spec": {"template": {"spec": {"containers": [{"name": "babeld", "image": "zoobab/babeld-in-docker", "securityContext": {"privileged": true} }]}}}}'
```
See here: http://www.zoobab.com/howto-run-a-privileged-container-with-kubectl
