### ISSUE TITLE
Suspicious code in fuzzer.go

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#6536]
This looks like a git merge problem (?):

https://github.com/GoogleCloudPlatform/kubernetes/blob/c1ef9be2616b0798dd376ccb833e5bd6f47ae7f5/pkg/api/testing/fuzzer.go#L174-L177

```
			fuzzOneOf(c, &vs.HostPath, &vs.EmptyDir, &vs.GCEPersistentDisk, &vs.GitRepo, &vs.Secret, &vs.NFS, &vs.ISCSI)
			fuzzOneOf(c, &vs.HostPath, &vs.EmptyDir, &vs.GCEPersistentDisk, &vs.GitRepo, &vs.Secret, &vs.NFS, &vs.ISCSI, &vs.Glusterfs)
```

I don't see why glusterfs gets the special treatment...  is it an error, or is there something funky about glusterfs?

**Comment by thockin** [comment]
No, you're right.  Merge error.  @vishh @rootfs

**Comment by rootfs** [comment]
my bad, thanks!
