### ISSUE TITLE
Elasticsearch e2e test fails consistently due to duplicate log entries

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#6537]
e.g. http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/4289/

**Comment by quinton-hoole** [comment]
The error message is:
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/es_cluster_logging.go:45
Got incorrect count for node 0 index 0: 3

**Comment by bprashanth** [comment]
isn't this a dupe of https://github.com/GoogleCloudPlatform/kubernetes/issues/6517 ?

**Comment by satnam6502** [comment]
This error means that too many occurrences of a log line were observed. I deliberately put in this check to look out for the situation when a synthetic logger pod is erroneously restarted (the pods are one-shot pods with a restart never policy). I shall look into this further, but my first guess is that something has been broken and this test is doing its job i.e. exposing a fault in our underlying system. Again :-)

**Comment by bprashanth** [comment]
There must be a simpler way to confirm one shot pods are not restarting. not saying you should do it, but it might alleviate this pain if you did :)

**Comment by quinton-hoole** [comment]
The error started occurring very reliably at Apr 6, 2015 2:31:33 PM on our Jenkins CI.

The new commits that went in immediately before  the errors started are:

Commit 952ff24f0bc58280de86ae8c77bf710044f948a1 by aml
Do not log net.errClosing error when StreamWatcher is stopping.

Commit d194af6b4f1721cd4fe719ba8ea81b520386ccae by james.defelice
allow for more easily customized kubelet creation and initialization

Commit a8c02412b22932857436ade029a5e38f8846989d by yifan.gu
kubelet: Remove GetRecentDockerContainersWithNameAndUUID().
Use the pod status to get the recent stopped containers in
shouldContainerBeRestarted().

The last one smells fishy, given that the duplicate log messages seem to be the result of pod restarts.

**Comment by quinton-hoole** [comment]
And yes Prashath, it's a dupe of #6517 .  My apologies.  I've closed that one.

**Comment by quinton-hoole** [comment]
I'm going to try to roll back  a8c0241 and see if it fixes the problem.

**Comment by satnam6502** [comment]
@bprashanth I like the way the test is written as-is because it catches all the cases (whenever they occur) which lead a log line being emitted too many times due to a pod being restarted. I could perhaps check the number of restarts but a restart could occur immediately after I check but before I check the log lines? This way I gather the state of the system w.r.t. logging and then make sure it is coherent before making any judgements about a test passing, and I avoid a bunch of cases where I would otherwise give a false positive.

**Comment by satnam6502** [comment]
@quinton-hoole if that PR is not the source of the problem then let me know. I will then change this test to write out all the unexpected node count values rather than stopping and failing at the first. This would re-confirm the erroneous node restart problem.

**Comment by quinton-hoole** [comment]
Reverting #6470 fixes the problem.  Closing.

**Comment by satnam6502** [comment]
To help with debugging, I think the two likely causes are:
1. A pod being restarted when it should not be.
2. The Host constraint for pinning pods not being honored.

**Comment by quinton-hoole** [comment]
Yes, you were correct :-)  See #6470

**Comment by satnam6502** [comment]
Thank you: I am glad to see that this test which was a bloodbath to write for me has proved to be so useful on several occasions :-)
Tears well spent.
