### ISSUE TITLE
v1beta3: ContainerStatuses in PodStatus

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#6551]
From ```https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L773```
```
	// This output format is *not* final and should not be relied upon.
	// TODO: Make real decisions about what our info should look like. Re-enable fuzz test
	// when we have done this.
       ContainerStatuses []ContainerStatus
```

Is this comment still valid?

@bgrant0607 @smarterclayton

**Comment by nikhiljindal** [comment]
fwiw, map (as in v1beta1) seems better than the array (in v1beta3), as it was possible to get a particular container status via kubectl using name as the index.
Example from ```https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L228```
```
kubectl get pods <podId> -o template --template={{(index .currentState.info <containerName>)}}
```

**Comment by bgrant0607** [comment]
The comment is obsolete and should be deleted. For better or worse, the decision was list.

It is possible to write templates using lists. See https://github.com/GoogleCloudPlatform/kubernetes/issues/5625#issuecomment-83537834 for an example.

FWIW, we're planning to change the template syntax: #4348.

We could also just pipe the json into jq in a docker container.
