### ISSUE TITLE
Replication controller issues too many lists

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#6562]
Currently RC has the following logic:

MainLoop():
1. Watch for new RC and sync them immediately
2. Every 5 sec list all RC and sync them

SyncRC():
1. List all pods matching selector for RC
2. Add/Remove pods

This is suboptimal on both layers. We should use watch for both RC and pods. Current implementation generates very high load in apiserver.

**Comment by fgrzadkowski** [comment]
cc @wojtek-t @davidopp @lavalamp

**Comment by davidopp** [comment]
@bprashanth

**Comment by bprashanth** [comment]
I believe this is addressed in https://github.com/GoogleCloudPlatform/kubernetes/issues/5884

**Comment by lavalamp** [comment]
Changing assignee since @bprashanth is actually working on this.

**Comment by wojtek-t** [comment]
@fgrzadkowski @bprashanth - what's the current status of it? Is it fixed now?

**Comment by fgrzadkowski** [comment]
I think this is done. Currently most lists come from kubelet which is expected.

**Comment by wojtek-t** [comment]
Thanks for confirmation (that was also my observation).
