### ISSUE TITLE
Salt-master not initiating on aws

### ISSUE THREAD

**Issue by tanmaybinaykiya** [GoogleCloudPlatform/kubernetes#6570]
I have an ec2 instance on AWS where I've been trying to instantiate a kubernetes cluster. 

The error occurs at  wget -q -O - https://get.k8s.io | bash
...
Waiting for master to be ready
Attempt 1 to check for master node [master not working yet]
Attempt 2 to check for master node [master not working yet]
Attempt 3 to check for master node [master running @54.186.91.217]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
...
..
.
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
salt-master failed to start on 54.186.36.23. Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)

I logged in to the master node and checked the logs in cloud-init-output.log

...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
^M 0 0 0 0 0 0 0 0 --:--:-- --:--:
-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 6 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 5 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 4 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 3 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 2 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 1 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: s3-None.amazonaws.com
md5sum: kubernetes-server-linux-amd64.tar.gz: No such file or directory
Downloading file (*https://s3-None.amazonaws.com/kubernetes-staging-b4dbf2fcedd5fc30900f899c6ab96b5a/devel/kubernetes-server-linux-amd64.tar.gz*)
 ...

The URL here contains "None".

**Comment by vishh** [comment]
cc @justinsb

**Comment by morganon** [comment]
+1

**Comment by tanmaybinaykiya** [comment]
This was a mistake on my part. There was an issue with the ssh key. Fixed it.

**Comment by andrew-jones** [comment]
@tanmaybinaykiya how did you fix this?  I have a similar issue.

**Comment by ghostshark** [comment]
@tanmaybinaykiya @andrew-jones Same problem.

**Comment by justinsb** [comment]
If the master is not starting on AWS, I think it would probably be easiest if you opened a new issue with the output.  Unless the output is actually exactly the same!

I think the original problem here was that your local SSH key must match the key named "kubernetes" in AWS.  We don't check they are the same - I probably should, but I don't yet, but if there are lots of people hitting the problem then naturally I'll be very motivated to fix it!

I also just found #8114.  If that is your problem (you can see in `/var/log/salt/minion` on the master), then do comment there.  I'm working on that issue now.

**Comment by pk-git** [comment]
@justinsb - I am facing the same issue. 

Starting Master
Adding tag to i-ab839856: Name=kubernetes-master
Adding tag to i-ab839856: Role=kubernetes-master
Adding tag to i-ab839856: KubernetesCluster=kubernetes
Waiting for master to be ready
Attempt 1 to check for master node [master not working yet]
Attempt 2 to check for master node [master not working yet]
Attempt 3 to check for master node [master running @52.5.170.115]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
Attempt 5 to check for salt-master [salt-master not working yet]
Attempt 6 to check for salt-master [salt-master not working yet]
Attempt 7 to check for salt-master [salt-master not working yet]
Attempt 8 to check for salt-master [salt-master not working yet]
Attempt 9 to check for salt-master [salt-master not working yet]
Attempt 10 to check for salt-master [salt-master not working yet]
Attempt 11 to check for salt-master [salt-master not working yet]
Attempt 12 to check for salt-master [salt-master not working yet]
Attempt 13 to check for salt-master [salt-master not working yet]
Attempt 14 to check for salt-master [salt-master not working yet]
Attempt 15 to check for salt-master [salt-master not working yet]
Attempt 16 to check for salt-master [salt-master not working yet]
Attempt 17 to check for salt-master [salt-master not working yet]
Attempt 18 to check for salt-master [salt-master not working yet]
Attempt 19 to check for salt-master [salt-master not working yet]
Attempt 20 to check for salt-master [salt-master not working yet]
Attempt 21 to check for salt-master [salt-master not working yet]
Attempt 22 to check for salt-master [salt-master not working yet]
Attempt 23 to check for salt-master [salt-master not working yet]
Attempt 24 to check for salt-master [salt-master not working yet]
Attempt 25 to check for salt-master [salt-master not working yet]
Attempt 26 to check for salt-master [salt-master not working yet]
Attempt 27 to check for salt-master [salt-master not working yet]
Attempt 28 to check for salt-master [salt-master not working yet]
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
salt-master failed to start on 52.5.170.115. Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)

**Comment by andrew-jones** [comment]
@pk-git I had a very similar output.  My issue was I messed with the ssh keys.  I didn't debug much, but removing ~/.ssh/kube_ssh_key* (it's called something like this) and the kubernetes key pair from the aws console then setting AWS_SSH_KEY=kube and running kube-up.sh again seems to work.  Without setting AWS_SSH_KEY I couldn't get it to work.

**Comment by pk-git** [comment]
Thanks! I was able to get past this one. But ran into another issue #8131 . Looks like its fixed, based on that discussion thread not sure if its available in latest release?

**Comment by andrew-jones** [comment]
It's on the master branch but the last release was the day before #8131 was merged.

**Comment by kushortiz** [comment]
getting this

Attempt 1 to check for SSH to master [ssh to master working]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
Attempt 5 to check for salt-master [salt-master not working yet]
Attempt 6 to check for salt-master [salt-master not working yet]
Attempt 7 to check for salt-master [salt-master not working yet]
Attempt 8 to check for salt-master [salt-master not working yet]
Attempt 9 to check for salt-master [salt-master not working yet]
Attempt 10 to check for salt-master [salt-master not working yet]
Attempt 11 to check for salt-master [salt-master not working yet]
Attempt 12 to check for salt-master [salt-master not working yet]
Attempt 13 to check for salt-master [salt-master not working yet]
Attempt 14 to check for salt-master [salt-master not working yet]
Attempt 15 to check for salt-master [salt-master not working yet]
Attempt 16 to check for salt-master [salt-master not working yet]
Attempt 17 to check for salt-master [salt-master not working yet]
Attempt 18 to check for salt-master [salt-master not working yet]
Attempt 19 to check for salt-master [salt-master not working yet]
Attempt 20 to check for salt-master [salt-master not working yet]
Attempt 21 to check for salt-master [salt-master not working yet]
Attempt 22 to check for salt-master [salt-master not working yet]
Attempt 23 to check for salt-master [salt-master not working yet]
Attempt 24 to check for salt-master [salt-master not working yet]
Attempt 25 to check for salt-master [salt-master not working yet]
Attempt 26 to check for salt-master [salt-master not working yet]
Attempt 27 to check for salt-master [salt-master not working yet]
Attempt 28 to check for salt-master [salt-master not working yet]
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
(Failed) output was:

salt-master failed to start on 54.200.150.130. Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)

Any help ? Any issue with ssh keys ? how to fix it ? anyone can please share the steps ?? thanks in advance

**Comment by afathima94** [comment]
Hi,
I am also facing the same issue

Attempt 26 to check for salt-master [salt-master not working yet]
Attempt 27 to check for salt-master [salt-master not working yet]
Attempt 28 to check for salt-master [salt-master not working yet]
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
(Failed) output was:

salt-master failed to start on "---master-ip----". Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)

Can anyone help me out with this

**Comment by Sam-666** [comment]
Hi Gus ,

I am also having the same problem as afathima94. Master is connecting but the salt master is not . Any help is very much welcome
