### ISSUE TITLE
Provide an option on the apiserver to specify apiserver address for services

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#6572]
Trying to load-balance apiservers through an external proxy/load-balancer results in the apiservers having a war trying to set the endpoint address for the kubernetes and kubernetes-ro services.  We need to be able to specify what the endpoint address should be for these services.

**Comment by rrati** [comment]
This is part of supporting high availability clusters #473

**Comment by timothysc** [comment]
PR inflight.

**Comment by smarterclayton** [comment]
@liggitt FYI

**Comment by smarterclayton** [comment]
This is the equivalent of master address for internal, I think we're covered since we have public master and master.

**Comment by rrati** [comment]
@smarterclayton Is this referring to #6572? If so, I don't think bind or public_address will work because both of them require the ip to actually exist on the apiserver

**Comment by smarterclayton** [comment]
It's referring to what we do in Openshift, just asking Jordan in that same issue.

**Comment by lavalamp** [comment]
I'm going to repair the endpoint generation function.
