### ISSUE TITLE
v1beta1->v1beta3 storage translation tool

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#6583]
Forked from https://github.com/GoogleCloudPlatform/kubernetes/issues/5475

Before ripping out v1beta1 code, we need to ensure that everyone has upgraded their stored objects in etcd to v1beta3.
Filling this issue to discuss how we want to go about this.
We can build a translation tool or can ask them to restart their cluster :)

@bgrant0607 @lavalamp @smarterclayton

**Comment by smarterclayton** [comment]
We will eventually need a tool that trawls the objects in etcd, reads them, fixes anything, then writes them back.  It can run once or many times, and have fairly arbitrary operations executed on resources or sets of resources.  It should have a mode which is dry run only (warn on errors) or apply over errors.

Might be the right time.

**Comment by bgrant0607** [comment]
It should use the registry/storage layers, not trawl over etcd directly, though.

**Comment by lavalamp** [comment]
Yes, we need to make a tool that will upgrade your stored objects. One would run this tool after one is definitely not rolling back. It probably needs to be built into master/apiserver, for the reason @bgrant0607  says; it'd be run on an RPC or commandline flag, I guess.

**Comment by bgrant0607** [comment]
Current proposal is simply a script that touches every object.

**Comment by bgrant0607** [comment]
via the API
