### ISSUE TITLE
Move docs/examples to v1beta3

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#6584]
List of tasks based on grep "v1beta1"

- [x] Reorganize yaml files in examples/ to bring v1beta3 ones at the top, and remove v1beta1.
- [x] Reorganize yaml files in cluster/addons/ to bring v1beta3 ones at the top, and remove v1beta1.
- [ ] Remove references to "v1beta1" in docs/getting-started-guides/ (#5799)
- [x] Remove references to "v1beta1" in docs/ (replace by v1beta3)
- [x] Remove references to "v1beta1" in test/integration/ (https://github.com/GoogleCloudPlatform/kubernetes/pull/6724)
- [x] Remove references to "v1beta1" in test/e2e/ (https://github.com/GoogleCloudPlatform/kubernetes/pull/6790)
- [x] Remove references to "v1beta1" in hack/e2e-suite/services.sh (https://github.com/GoogleCloudPlatform/kubernetes/pull/6790)
- [x] Remove references to "v1beta1" in hack/test-cmd.sh (https://github.com/GoogleCloudPlatform/kubernetes/pull/6790)
- [x] Remove references to "v1beta1" in cluster/
- [x] Remove references to "v1beta1" in contrib/
- [x] Remove references to "v1beta1" in pkg/tools/etcd_helper_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/6603)
- [x] Remove references to "v1beta1" in pkg/client/request_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/client/restclient_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/client/record/event_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/6603)
- [x] Remove references to "v1beta1" in pkg/client/record/events_cache_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/6603)
- [x] Remove references to v1beta1.Codec in pkg/watch/json/encoder_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/6603)
- [x] Remove references to "v1beta1" in pkg/api/ref_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/6603)
- [x] Update pkg/api/validation/schema_test.go to test both versions based on testapi.Version (https://github.com/GoogleCloudPlatform/kubernetes/pull/6849)
- [x] Remove references to "v1beta1" in pkg/apiserver/handlers_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/kubelet/container/ref_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/kubelet/config/ (http_test.go and file_test) (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/config/ (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/kubectl/resource_printer_test.go (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)
- [x] Remove references to "v1beta1" in pkg/kubectl/cmd/ (https://github.com/GoogleCloudPlatform/kubernetes/pull/7128/)

**Comment by nikhiljindal** [comment]
Oops, pressed enter by mistake :)
Still editing the issue description.

**Comment by nikhiljindal** [comment]
The list is complete now

**Comment by dchen1107** [comment]
cc/ @caesarxuchao

**Comment by bgrant0607** [comment]
We should remove references to v1beta1 in the getting-started guides by removing examples of starting pods/rcs/services and linking to examples in /examples. #5799.

**Comment by bgrant0607** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/accessing-the-cluster.md is covered by #7094.

**Comment by bgrant0607** [comment]
The walkthrough has an indentation bug in its v1beta3 yaml:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/walkthrough/v1beta3/replication-controller.yaml#L23
I was going to submit a PR, but ran into a problem with gendocs, so mentioning it here in case someone can do it before I get to it.

**Comment by nikhiljindal** [comment]
Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/7284 to fix that. Verified that rc is created fine using that yaml.

**Comment by bgrant0607** [comment]
still v1beta1:
* examples/guestbook-go
* examples/storage
* examples/glusterfs
* examples/gce-pd
* examples/liveness
* contrib/git-sync

**Comment by preillyme** [comment]
@bgrant0607: what's the current status of this? Do the various yaml file(s) you referenced still need to be changed?

**Comment by bgrant0607** [comment]
Still plenty of work to be done, yes. Search for v1beta1 in the codebase if you want to help.

**Comment by bgrant0607** [comment]
And see also #8087

**Comment by preillyme** [comment]
@bgrant0607: Okay sounds good. Thanks!

**Comment by caesarxuchao** [comment]
Hi @preillyme, I have updated all the examples to v1beta3, though some PR are still waiting to be merged.

**Comment by preillyme** [comment]
@caesarxuchao thanks for the update.

**Comment by caesarxuchao** [comment]
conversion of contrib/git-sync is paused because of #8327

**Comment by bgrant0607** [comment]
kubectl proxy and kubectl update also still use v1beta1 examples

cc @jlowdermilk @krousey

**Comment by bgrant0607** [comment]
libvirt-coreos still uses v1beta1 @lhuard1A

**Comment by bgrant0607** [comment]
@wojtek-t pkg/api/node_example.json needs to be updated to v1beta3

**Comment by bgrant0607** [comment]
@wojtek-t Nevermind. The problem is that the selfLink is wrong. https://github.com/GoogleCloudPlatform/kubernetes/issues/6596#issuecomment-95718519

**Comment by bgrant0607** [comment]
#7629 should have fixed that problem, but we need to update the selfLinks of `pkg/api/*_example.json` files.

**Comment by bgrant0607** [comment]
libvirt-coreos is in progress -- #8273

**Comment by wojtek-t** [comment]
@bgrant0607 - thanks for heads up - #8909 is sent out for review

**Comment by caesarxuchao** [comment]
postpone update of `kubectl proxy` due to #8943

**Comment by bgrant0607** [comment]
@caesarxuchao Postpone what, exactly?

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/5799 is, I think, the last remaining task here.
@caesarxuchao @bgrant0607 Any other remaining item?

**Comment by bgrant0607** [comment]
Move everything to v1 now? :-)

I'm hoping that could be done by a shell script.

@krousey

**Comment by bgrant0607** [comment]
Closing this issue.
