### ISSUE TITLE
Static pod versioning management

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#6594]
Forked from #6580 

Today when a user push a new updated manifest file to kubelet, Kubelet cannot really reject the update even it is invalid. 

cc/ @yujuhong @bgrant0607 @thockin

**Comment by bgrant0607** [comment]
Kubelet should reject it and just continue running what it was running before.

**Comment by yujuhong** [comment]
Kubelet does not persist its state, so it will blindly accepts any update after restarting.

I just checked the code. Actually, kubelet generates the UID by hashing the entire pod. This makes the modified pod file effectively a new pod which happens to have the same name and namespace as the old pod. Theoretically, kubelet would treat it like a completely new pod. If we are okay with this model (treating any update as a new pod), maybe this is a non-issue?

**Comment by bgrant0607** [comment]
Treating the updated pod as a new pod is fine. The new pod should pass validation, though.

**Comment by yujuhong** [comment]
Kubelet does validate the pod when reading the file. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/common.go#L127

**Comment by yujuhong** [comment]
Closing this since it's a non-issue. Please re-open if you think otherwise.
