### ISSUE TITLE
[AWS][CoreOS] Issues with minions initializations

### ISSUE THREAD

**Issue by roman-shuhov** [GoogleCloudPlatform/kubernetes#6598]
I have issues with minions initialization. I'm trying to run the following command:

    aws ec2 run-instances --count 3 --image-id ami-323b195a --region us-east-1 --security-groups kubernetes --key-name venezia-k8s-keypair --instance-type m3.medium --user-data file://node.yml

It creates 3 instances but fails to apply node.yml config.

The content of config is https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloud-configs/node.yaml (i changed <master-private-ip> to the master ip)

1. So i have 2 issues with this config. The first one is that it tries to use "eth1" interface for flannel and it fails, because all machines have only eth0 interface defined. I changed it to "eth0" and looks like it solved the issue.

2. Next issue is that etcd is marked as "masked"  in minion config:

    - name: etcd.service
          mask: true

For this reason flannel fails to start. The out of systemctl status flanneld is:

````
● flanneld.service - Network fabric for containers
   Loaded: loaded (/usr/lib64/systemd/system/flanneld.service; static; vendor preset: disabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           └─50-network-config.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2015-04-08 22:24:07 UTC; 18ms ago
     Docs: https://github.com/coreos/flannel
  Process: 5594 ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config {"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}} (code=exited, status=2)
  Process: 5586 ExecStartPre=/bin/bash -c until curl http://10.41.143.48:4001/v2/machines; do sleep 2; done (code=exited, status=0/SUCCESS)
  Process: 5585 ExecStartPre=/usr/bin/touch /run/flannel/options.env (code=exited, status=0/SUCCESS)
  Process: 5584 ExecStartPre=/usr/bin/mkdir -p /run/flannel (code=exited, status=0/SUCCESS)
  Process: 5582 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
````

I can fix this issue by changing etcd to :

        - name: etcd.service
          command: start

and looks like flannel starts after that, but i'm pretty sure that's a wrong fix, and, moreover, i'm getting more network issues after that. You can see them at http://stackoverflow.com/questions/29401765/kubernetes-unable-connect-to-any-pod-from-master

**Comment by vishh** [comment]
cc @jmreicha

**Comment by roman-shuhov** [comment]
flanneld logs - https://gist.github.com/roman-shuhov/9b028a48968ee1bea1ca

**Comment by hobti01** [comment]
The second issue can be resolved by pointing the node at etcd on the master as raised in https://github.com/GoogleCloudPlatform/kubernetes/issues/6555 and PR https://github.com/GoogleCloudPlatform/kubernetes/pull/6611

**Comment by hobti01** [comment]
+1 to remove eth1

Also asked here: 
https://github.com/GoogleCloudPlatform/kubernetes/commit/7bc7f47c3e21b4368a69fbfadcece9591a7cca7a#commitcomment-10643593

**Comment by roman-shuhov** [comment]
I'm still getting an error using the #6611 change. Flanneld fails to execute

    /usr/bin/etcdctl -C 10.136.75.108 set /coreos.com/network/config {"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}

    /usr/bin/etcdctl -C 10.136.75.108 set /coreos.com/network/config {"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}
Error:  Cannot sync with the cluster using peers 10.136.75.108

Where 10.136.75.108 is my master IP

**Comment by hobti01** [comment]
I had this issue too until I added the port: `/usr/bin/etcdctl -C 10.136.75.108:4001...`

**Comment by roman-shuhov** [comment]
Yeah, nice catch, it helped me. But now i have another issue, flanneld is working on master and minions, but kubernetes master doesn't see minions...

**Comment by roman-shuhov** [comment]
as i see master shows error for all minions:

    error health checking 10.99.162.78: Get http://10.99.162.78:10250/healthz: dial tcp 10.99.162.78:10250: connection refused

where 162.78 is a minion ip

**Comment by roman-shuhov** [comment]
So, i believe my current issue is described here https://github.com/kelseyhightower/setup-network-environment/issues/1. Not sure how to fight it

**Comment by roman-shuhov** [comment]
now i have kubernetes up and running, thanks!
