### ISSUE TITLE
Decide if current ETCD Update semantics is correct.

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#6626]
While having fun with subresources I found out that we have somewhat unexpected logic in etcd_helper.go AtomicUpdate (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper.go#L311). Namely, IIUC, there's an inbuilt retry loop in case of precondition failure, so effectively we do not have an 'optimistic locking' on updated and each update will eventually go through.

I'm not saying that this is wrong - it just was a bit surprising for me, and other people in Warsaw as well. Is this by design, and everyone was aware of that? I'm asking before I'm afraid that it will cause race conditions and all the fun they generate.

@wojtek-t @thockin @lavalamp @davidopp @brendanburns

**Comment by lavalamp** [comment]
Our server code can use the AtomicUpdate pattern to do something like patch, where it can tell which changes the client doesn't care about and retry. Alternatively, it can be used for resources which are internal bookkeeping (e.g., boundPods when we had that, or maybe the IP address allocation data). In these cases the server is the client.

Ordinary update requested by a downstream client (e.g. kubect) in the server should NOT go through AtomicUpdate; the retry loop needs to happen in the client.

**Comment by lavalamp** [comment]
I think there's nothing that needs to change here. I'll leave this open if you want to argue :)

**Comment by gmarek** [comment]
I think it may be problematic in a case when two components read and write the same status, and the thing they read impact the things they write (e.g. NodeController and Kubelet writing NodeStatus). Currently it's not a problem (I believe), but I saw e.g. @bgrant0607 mentioning optimistic locking somewhere, and this semantics overrides it.

**Comment by lavalamp** [comment]
This implements optimistic concurrency as long as it is used correctly.

The stuff you do inside the function must compute a delta, NOT overwrite the entire object.

**Comment by davidopp** [comment]
@gmarek I agree with @lavalamp 's take on this. IIUC, tryUpdate() receives a copy of the latest version of the object each time it is called (even if the loop is executed more than once). So it can adapt what it tries to write based on the current object (which, as you observe, may change across invocations of tryUpdate() due to competition from other writers). I would slightly re-phrase what @lavalamp said as "The stuff you do inside the function must take the current state of the object it is trying to modify into account when deciding what to write as the new object." I'll send out a PR to make that clear in a comment. But in any event, it's still "optimistic locking" IMO.

**Comment by davidopp** [comment]
I guess one thing I am confused about is why this is called an "atomic" update. Aren't all single-object updates to etcd atomic?

**Comment by davidopp** [comment]
In other words, the property I would call out in the name of the function is that the update is guaranteed to succeed, not that it is atomic.

**Comment by wojtek-t** [comment]
>
I would slightly re-phrase what @lavalamp said as "The stuff you do inside the function must take the current state of the object it is trying to modify into account when deciding what to write as the new object." I'll send out a PR to make that clear in a comment. But in any event, it's still "optimistic locking" IMO.

SGTM

>
In other words, the property I would call out in the name of the function is that the update is guaranteed to succeed, not that it is atomic.

+1
