### ISSUE TITLE
"kubectl delete namespace" has odd stateful behaviour.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#6633]
There is a funny subtle behvaiour in get namespaces, in  which if i call `kubectl delete ns...` more than one time, it seems that the removal from **Terminating** state is accelarated.  

It seems this might indicate a bug, or **maybe its not a bug and the eventual semantics** of `kubectl get ****` is a little funny sometimes.

in any case, **here's what we are seeing** : 

1) when i **delete a namespace the first time** usning kubectl, we get a state change  to `(Terminating)`.  that is correct, of course.

2) but ... if make the call a **second time**,  then the same status line `(Terminating)` is immediately **removed** from `kubectl get namespaces`.

Expected behaviour : **A second call to "kubectl delete ..." shouldn't have any effect on the timing of removal  of a namespace from 'Terminating' state**... So i guess there is some "eventual consistency" subtle bug that is resolved by repeated calls to `kubectl delete ...`

**Comment by jayunit100** [comment]
@rrati  suggests this may not be e bug, maybe its just the etcd eventual deleter thingy.

**Comment by rrati** [comment]
Looks to definitely be a bug.  The 2nd delete seems to have interrupted the delete process and artifacts (like events) from the namespace still exist in etcd.

**Comment by derekwaynecarr** [comment]
investigating...

**Comment by derekwaynecarr** [comment]
oops, see the error, will submit a fix.

**Comment by derekwaynecarr** [comment]
I have a fix, but need a test case, will submit PR tomorrow AM
