### ISSUE TITLE
kube-scheduler returns "404" for "/healthz" requests

### ISSUE THREAD

**Issue by fabioy** [GoogleCloudPlatform/kubernetes#6644]
Found this by calling the "/validate" end point on the master:

root@kubernetes-master:/var/log# curl 127.0.0.1:8080/validate
<snip>
  {
    "component": "scheduler",
    "health": "failure",
    "healthCode": 1,
    "msg": "404 page not found\n",
    "err": "unhealthy http status code: 404 (404 Not Found)"
  },
</snip>

Seems like any requests to it return a 404:

root@kubernetes-master:/var/log# netstat -p -l | grep kube-scheduler
tcp        0      0 localhost:10251         *:*                     LISTEN      4105/kube-scheduler
root@kubernetes-master:/var/log# curl 127.0.0.1:10251/healthz
404 page not found
root@kubernetes-master:/var/log# curl 127.0.0.1:10251
404 page not found

**Comment by roberthbailey** [comment]
I'm not seeing this on my 0.14.1 cluster:

$ curl http://127.0.0.1:8080/validate
{
"component": "scheduler",
"health": "success",
"msg": "ok",
"err": "nil"
},

$ curl http://127.0.0.1:10251/healthz
ok

**Comment by yujuhong** [comment]
This is happening on HEAD. #6623 seems to have caused this.
/cc @wojtek-t

**Comment by fabioy** [comment]
Could we rollback this PR?

**Comment by timothysc** [comment]
is this only on the scheduler?

**Comment by fabioy** [comment]
Yes. The change basically broke the /healthz mapping in kube-scheduler, so the health pings are failing. The "validate-cluster.sh" doesn't hit it, but the master's "/validate" does. This is causing the internal cluster validation checks to fail.

**Comment by roberthbailey** [comment]
GKE relies on the /validate endpoint on the master (since it can't run the validate-cluster.sh script) and this has broken our GKE-CI build since it was merged this morning.

**Comment by yujuhong** [comment]
I think we can revert the PR and let profiling break for now. @vmarmol, what do you think?

**Comment by vmarmol** [comment]
SGTM, sorry for the breakage.

**Comment by dchen1107** [comment]
Ahh, you guys already revert the commit? The fix should be very simple. Let me send PR shortly to fix this.

**Comment by wojtek-t** [comment]
Thanks for the fix @dchen1107 and sorry for the breakage
