### ISSUE TITLE
Slow memory leak around clients

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#6645]
https://github.com/openshift/origin/issues/1530#issuecomment-91318297

![memoryprofileofclient](https://cloud.githubusercontent.com/assets/29690/7073843/2f15ed12-dec4-11e4-8ec9-7bbf8b59f0c0.png)

The replication controller seems to imply something is being kept active - however 25% of total memory being held on to.

DoRaw() is leaking request because of a defer (I believe)

```
defer r.resp.Body.Close()
```

is not safe in a loop, because r.resp is changed after every request.  However, I could be wrong.

**Comment by wojtek-t** [comment]
Definitely defer r.resp.Body.Close() in a loop is an error - defer is run when it exits the function, not when it exists its scope. So I'm pretty sure that #6671 would fix this issue. Thanks!

**Comment by smarterclayton** [comment]
Believe this is fixed
