### ISSUE TITLE
Multi-master issue with master services

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#6672]
From #6572 

@rrati said

> If you have multiple apiservers running in a load balanced setup they fight against what the endpoint address should be for the kubernetes[-or] services. Each apiserver is expecting the endpoint address to be its ip, and you can't use the existing settings (when I first looked, haven't looked at the refactoring) because they are used other places to actually perform a bind. Without a way to set a constant address for the endpoing the apiservers will continually duel. Additionally when you are running multiple apiserver you probably want to redirect all traffic to those services are load-balanced like other apiserver requests.

I said 

> The real fix is to make the master services actually hold both/all master IPs

@rrati said

> It depends on what that ip is. It could be the ip of a specific master or it could be the ip of a proxy that load balances the requests to all masters in the system. The simplest route to take to allow multiple apiservers in the system for load-balancing/ha seems to be having a proxy (haproxy) actually handing the work distribution. You could point everything at the proxy, including the cluster service endpoints, and let it distribute to the apiservers/masters.

We could decide on a more complicated ha scheme at some point where we make sure all apiservers know about each other etc. That would be a more impactful change. This should allow us to start heading down the load-balancing/ha path.

I said

> Who runs this haproxy?  Is it a pod or some other external thing?  It's a plausible answer, but it needs some design

**Comment by timothysc** [comment]
@abhgupta , @danmcp , @smarterclayton ^ 

We were going the baby-step approach for HA.  Simply load balancing the api-server seems like a modest thing to do as a 1st step.    How exactly one load balances the api-server is slightly orthogonal.   (HAProxy, Some GCE or AWS load balancer ... ) 

The rest of the master daemons are a different story and we would likely create a quorum of standby daemons, but I believe that was well outside the scope of rob's initial change.

**Comment by smarterclayton** [comment]
We have an HAProxy that is programmable to endpoints, but does not yet program its output based on services.  If we need to add that, I'd prefer to make what we have already more generic, rather than have to reinvent the other wheel (since it solves a wider range of problems, like being able to reuse the same code for different proxy types).

**Comment by lavalamp** [comment]
Please copy me on all HA master PRs.

**Comment by davidopp** [comment]
Me too. :)

**Comment by quinton-hoole** [comment]
cc: quinton-hoole

**Comment by timothysc** [comment]
Per discussion on wed, we'll attach do a HA.md proposal PR by tomorrow.

**Comment by timothysc** [comment]
Please close this one, and we'll rally on #6995
