### ISSUE TITLE
REST api - Creating an entity on a non existing namespace works

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#6673]
Tried to create a service on a namespace 'staging' which doesn't exist on my k8s.
Creation succeeded which is odd enough :)
Then navigating to the entity also works:
GET on
/api/v1beta3/namespaces/staging/services/redis-service

Navigating to the namespace itself produces 404 'namespaces \"staging\" not found':
/api/v1beta3/namespaces/staging/

Getting all namespaces also doesn't list that namespace which sounds reasonable given the above.

I'd expect one of the two:
1. most standard approach: a clear error that this namespace doesn't exist when attempting to create an entity on it.
2. less preferred imo, but better than nothing: creating silently behind the scenes that namespace

cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
Sounds like an error configuring your environment.  Is this using a standard provider environment or did you install your own?

The kube-Apiserver needs the following flags set for admission_control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,ResourceQuota

In your case NamespaceAutoProvision must not be running.

**Comment by derekwaynecarr** [comment]
Admission control option

NamespaceExists does your goal for 1.  It is what OpenShift uses.  

NamespaceAutoProvision does 2.  It is used upstream right now, but I think upstream should switch to NamespaceExists and require explicit creation, but that is harder to enable for things like e2e until more work is done.

**Comment by abonas** [comment]
> Sounds like an error configuring your environment. Is this using a standard provider environment or did you install your own? The kube-Apiserver needs the following flags set for admission_control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,ResourceQuota In your case NamespaceAutoProvision must not be running.

@derekwaynecarr 
this is the hack/local-up-cluster.sh
I didn't find the admission_control set there at all, 
perhaps it's a bug in that particular setup?
