### ISSUE TITLE
Services ports validation bug. Kubernetes v0.14.2

### ISSUE THREAD

**Issue by pythonpowerd** [GoogleCloudPlatform/kubernetes#6677]
```bash
[root@master ~]# cat service.yaml 
kind: Service
apiVersion: v1beta3
metadata:
  name: nfs-server
spec:
  ports:
    - port: 2049
  selector:
    role: nfs-server

[root@master ~]# kubectl create -f service.yaml 
F0410 07:50:24.784551    8972 create.go:50] Client error: Service "nfs-server" is invalid: spec.port: invalid value '0': must be greater than 0 and less than 65536

[root@master ~]# kubectl --api-version=v1beta3  create -f service.yaml 
F0410 07:50:26.706638    8978 create.go:50] Client error: Service "nfs-server" is invalid: spec.port: invalid value '0': must be greater than 0 and less than 65536
```

**Comment by pythonpowerd** [comment]
I also have tried this json from examples and result was the same error message.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/v1beta3/frontend-service.json

**Comment by thockin** [comment]
Are you sure you rebuilt kubectl?  `spec.port` is the old field name.  That
error string is part of validation, and the only way you would have gotten
it is if something was using the old schema from a couple weeks ago (before
v1beta3 was officially enabled).

Try `make clean all` ?

**Comment by pythonpowerd** [comment]
Problem 100% not in kubectl, because I have tried to do POST requests like that in other apps... for example...
```bash
[root@master]$ http POST http://localhost:8080/api/v1beta3/namespaces/default/services < service3.json 
HTTP/1.1 422 status code 422
Content-Length: 516
Content-Type: application/json
Date: Fri, 10 Apr 2015 16:18:56 GMT

{
    "apiVersion": "v1beta3",
    "code": 422,
    "details": {
        "causes": [
            {
                "field": "spec.port",
                "message": "spec.port: invalid value '0': must be greater than 0 and less than 65536",
                "reason": "FieldValueInvalid"
            }
        ],
        "id": "frontend",
        "kind": "Service"
    },
    "kind": "Status",
    "message": "Service \"frontend\" is invalid: spec.port: invalid value '0': must be greater than 0 and less than 65536",
    "metadata": {},
    "reason": "Invalid",
    "status": "Failure"
}
```
P.S. "http" is a good curl-like utility

I will check fresh build kubernetes-0.14.2-0.1.gitfce3e5a soon... may be fixed there

**Comment by thockin** [comment]
Yeah, then it could be that your apiserver is not updated.  Please let me
know.  Obviously this was tested before commit, but it's always possible to
miss a case :)

**Comment by pythonpowerd** [comment]
```bash
[root@master ~]# kube-apiserver --version
Kubernetes v0.14.1-538-g2719194154ffd3
```
Works as expected)

**Comment by istalker2** [comment]
The same behavior is constantly reproduced on a fresh installation on clean VM in both 0.14.1 and 0.14.2.
I am able to create Node and ReplicationController using v1beta3 but not Service. Getting the same error message eve for guestbook example

root@murano:/var/run/murano-kubernetes# /opt/bin/kubectl version
Client Version: version.Info{Major:"0", Minor:"14", GitVersion:"v0.14.2", GitCommit:"3ffb6193b5152fc3a2e2a4a12111130f4b531110", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"14", GitVersion:"v0.14.2", GitCommit:"3ffb6193b5152fc3a2e2a4a12111130f4b531110", GitTreeState:"clean"}
root@murano:/var/run/murano-kubernetes# /opt/bin/kube-apiserver --version
Kubernetes v0.14.2
root@murano:/var/run/murano-kubernetes# /opt/bin/kubectl --api-version=v1beta3 create -f svc2.json
F0414 00:27:18.293477    2257 create.go:50] Client error: Service "frontend" is invalid: spec.port: invalid value '0': must be greater than 0 and less than 65536
root@murano:/var/run/murano-kubernetes# cat svc2.json
{
   "kind":"Service",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"frontend",
      "labels":{
         "name":"frontend"
      }
   },
   "spec":{
      "ports": [
        {
          "port":80,
          "targetPort":80,
          "protocol":"TCP"
        }
      ],
      "selector":{
         "name":"frontend"
      }
   }
}

**Comment by thockin** [comment]
The only way this can happen is if you have someone using validation code
for v1beta3 that was built before v1beta3 was finalized and is parsing JSON
that is using the final v1beta3 syntax, which you are.  0.14 released just
before the multi-port support went in.
