### ISSUE TITLE
Create a cache in apiserver to improve its performance

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#6678]
## Background
 While running Kubernetes on 100-node cluster, the main bottleneck is the apiserver.
For example, starting a replication controller with 3000 pods (100 nodes, 30 pods per node) on the empty cluster lasts almost 20 minutes, and the CPU of 4-core master is 100% saturated for all that time.

 Looking at the profiles, more than 50% of CPU is spent on decoding objects coming from etcd (i.e. decoding jsons). I don't think we can do much with decoding itself, but what we can do is to limit the number of decodings we perform.

 For example, imagine a 100-node cluster and say one pod has just changed. What happens currently (which I think is reasonable) is that all Kubelets are listening to pods that are assigned to them. This however translates to opening watch for all pods, and filtering them at the apiserver based on the label/field selectors. This means that the particular change of a pod will be read from etcd 100 times, each time we independently decode it, apply labels and send it (to at most one Kubelet).
 Note that we're decoding the same pod read from etcd 100 times, which is a clear waste of resources.

# PROPOSAL
  My proposal is to create some kind of cache in the apiserver. The approach I am suggesting is:
1. The cache is used only for reading (writing doesn't read or modify cache)
2. The cache is storing decoded api objects (whether we will be storing all objects or just objects of some particular types is TBD) together with their etcd index (ModifiedIndex)
3. The cache is storing at most one version of the object with a given key (the newest one).
4. When we read an object from etcd (either via Get or Watch) we:
- send a request to etcd
- if the returned version (response contains ModifiedIndex value as an explicit field) is the same as currently stored in cache, we don't need to decode it and simply return the value from the cache
- if the returned version is newer (ModifiedIndex is monotonically increasing) we decode it an update the cache with the new version (the old version)
- if the returned version is older, we simply have a cache miss and decode it without using cache

What do you think about this proposal? If you think that's worth doing I'm happy to run some experiments to check how much it would help (I think the gain would be huge for bigger clusters).

@thockin @smarterclayton @fgrzadkowski @davidopp @lavalamp @timothysc

**Comment by smarterclayton** [comment]
> On Apr 10, 2015, at 10:02 AM, Wojciech Tyczynski <notifications@github.com> wrote:
> 
> Background
> 
> While running Kubernetes on 100-node cluster, the main bottleneck is the apiserver.
> For example, starting a replication controller with 3000 pods (100 nodes, 30 pods per node) on the empty cluster lasts almost 20 minutes, and the CPU of 4-core master is 100% saturated for all that time.
> 
> Looking at the profiles, more than 50% of CPU is spent on decoding objects coming from etcd (i.e. decoding jsons). I don't think we can do much with decoding itself, but what we can do is to limit the number of decodings we perform.
> 
Our decodings and conversions are personably an order of magnitude more inefficient in cpu and memory than they need to be.  That doesn't mean this issue is not worthwhile, but it is absolutely something else we need to investigate.
> For example, imagine a 100-node cluster and say one pod has just changed. What happens currently (which I think is reasonable) is that all Kubelets are listening to pods that are assigned to them. This however translates to opening watch for all pods, and filtering them at the apiserver based on the label/field selectors. This means that the particular change of a pod will be read from etcd 100 times, each time we independently decode it, apply labels and send it (to at most one Kubelet).
> Note that we're decoding the same pod read from etcd 100 times, which is a clear waste of resources.
> 
> PROPOSAL
> 
> My proposal is to create some kind of cache in the apiserver. The approach I am suggesting is:
> 1. The cache is used only for reading (writing doesn't read or modify cache)
> 2. The cache is storing decoded api objects (whether we will be storing all objects or just objects of some particular types is TBD) together with their etcd index (ModifiedIndex)
> 3. The cache is storing at most one version of the object with a given key (the newest one).
> 4. When we read an object from etcd (either via Get or Watch) we:
> 
> send a request to etcd
> if the returned version (response contains ModifiedIndex value as an explicit field) is the same as currently stored in cache, we don't need to decode it and simply return the value from the cache
> if the returned version is newer (ModifiedIndex is monotonically increasing) we decode it an update the cache with the new version (the old version)
> if the returned version is older, we simply have a cache miss and decode it without using cache
> What do you think about this proposal? If you think that's worth doing I'm happy to run some experiments to check how much it would help (I think the gain would be huge for bigger clusters).
> 
Why not target this specifically at watch, and allow watches to be aggregated?  That's similar to your proposal, but doesn't require the same complexity in changes to the code (essentially, emulate etcd.Watch centrally underneath watch.Interface).

**Comment by thockin** [comment]
I think this would go a long way towards making the pain manageable.  Why
would etcd ever return an old version?  Wouldn't that indicate a real
problem?

**Comment by smarterclayton** [comment]
I think it would mean the cluster has been rolled back, in which case that rollback probably needs to trigger resyncs down the chain.

----- Original Message -----
> I think this would go a long way towards making the pain manageable.  Why
> would etcd ever return an old version?  Wouldn't that indicate a real
> problem?
> 
> On Fri, Apr 10, 2015 at 7:02 AM, Wojciech Tyczynski <

**Comment by wojtek-t** [comment]
@thockin Can we explain what exactly did you mean - I'm afraid I didn't understand your thought.

**Comment by davidopp** [comment]
I think think this is a great idea. @thockin and I discussed a more complicated version of something vaguely like this with @lavlamp last week (write-through cache in API server) but your proposal is simpler because it's not in the write path at all, and just relies on fetching etcd version number to know whether its cached version is up-to-date. It might be one step on the path to a full write-through cache, but going all the way may not be necessary, and it seems that what you described would help for the reasons you mentioned.

[BTW when we talked about server-side caching with @lavalamp he preferred sever-side index to avoid the pattern of iterating and decoding all objects just to find ones that match a particular non-key field, plus client-side caching, but I think all of these ideas are complementary.] 

I did have the same question as Tim, namely how can "if the returned version is older" ever happen. Since writes go to etcd and not to the cache, it seems that the cache can never be fresher than etcd.

**Comment by smarterclayton** [comment]
What's the total work on this?  It seems if we can get significant improvements in decode / conversion efficiency, this becomes less valuable.  Doubling the efficiency of conversion improves watch and list operations - does that outweigh the value of this?  

Do we have to copy things out of the cache for safety?  If we do, then our only copy mechanism today is based on encode/decode/conversion, so every get call is still going to result in a decode.

**Comment by davidopp** [comment]
@smarterclayton what do you mean "Do we have to copy things out of the cache for safety?" IIUC the cache only serves information that is already in etcd.

**Comment by lavalamp** [comment]
Please see my design here for a cache/indexer: https://github.com/GoogleCloudPlatform/kubernetes/issues/4817#issuecomment-89437368

It's a lot of work.

**Comment by smarterclayton** [comment]
I mean a deep copy out of the cache so no one accidentally corrupts the cache.

Also remember, you still have to run conversion before returning the object to the client, so you probably end up doing the same number of total conversions.

Based on that, I'm not sure this actually reduces the cost of doing conversions:

Today: read from etcd, convert to internal, convert to external, write to response

With this: read from etcd, check cache, deep copy out of cache, convert to external, write to response.

**Comment by lavalamp** [comment]
@wojtek-t my design I linked is basically a more detailed version of your proposal.

**Comment by lavalamp** [comment]
@wojtek-t actually, your proposal:

> 3. The cache is storing at most one version of the object with a given key (the newest one).

This isn't possible if you want to support watch; you have to keep some history.

**Comment by lavalamp** [comment]
@wojtek-t (sorry for separate comments but I keep seeing things)

> 4. When we read an object from etcd (either via Get or Watch) we:

There's no point of a cache if you're still going to make an etcd request. Instead, just allow the cache/indexer to lag. clients will still get the latest version of things, at a slight delay.

**Comment by thockin** [comment]
There is some value in unmarshalling, even if it hits etcd to confirm.

As for watch history - I want to ask a dumb question: does that really
matter?  How important is it really to be able to get historical
play-by-play changes as opposed to current state + future changes?

**Comment by lavalamp** [comment]
@thockin: yes, you really need it to support current state+future changes.

Imagine: At T=0 a cilent lists. at T=1 something changes. at T=2 you finally get the client's watch request. Network latency means this is the common case.

**Comment by davidopp** [comment]
Can we implement an atomic "list and start watching" operation so that you don't miss anything? That actually seems like it might be useful even without this cache thing.

**Comment by lavalamp** [comment]
**NOTE: I think this should be a post-1.0 work item, and I think we can meet our performance goals in other ways.** Namely, we should optimize conversion/marshalling, and I think there's still more to do in making lists not list all nodes when only one is needed.

**Comment by thockin** [comment]
Set up the watch first, then list.  This is a common pattern for waitqueues
since forever.  Or make wtach always produce current state before sending
any deltas (which is how internal Watch RPCs work, if I recall)

On Fri, Apr 10, 2015 at 1:36 PM, David Oppenheimer <notifications@github.com

**Comment by lavalamp** [comment]
@davidopp I think we could. We did it that way at first, but badly. It has to be very clear to the client what comes from the list and what comes from the watch.

**Comment by lavalamp** [comment]
@davidopp but preventing the old behavior would be a pretty serious breaking change.

**Comment by smarterclayton** [comment]
I agree.

----- Original Message -----

**Comment by lavalamp** [comment]
On speeding up conversion: I just had an idea while chatting with @thockin. Suppose take our conversion funcs, and we do a compile-time step of generating copy functions (source code generation). So then, at runtime, conversion doesn't do any reflection. I think that would probably speed it up quite a bit.

**Comment by smarterclayton** [comment]
I agree.  We can do copy and conversion and defaulting together.  We can test the two side by side and then switch over.

We should keep decoding decoupled, but we may also want to consider down the road the other JSON proposals.

----- Original Message -----

**Comment by smarterclayton** [comment]
As per my comment https://github.com/GoogleCloudPlatform/kubernetes/issues/3338#issuecomment-84819373

----- Original Message -----

**Comment by davidopp** [comment]
@lavalamp I'm trying to compare @wojtek-t 's proposal with the one you proposed (https://github.com/GoogleCloudPlatform/kubernetes/issues/4817#issuecomment-89437368)

IIUC, the differences are
* you have an index, he doesn't
* you might store only keys, he would store keys and values

The second one seems like the biggest difference. If you don't store values, then your approach get speedup based on reducing the number of objects you need to iterate through, while his approach gets speedup based on reducing the latency to fetch objects. If you do store values, then I guess his approach is isomorphic to your approach if you only index one key (and it maps to every object).

**Comment by gkeramidas** [comment]
> My proposal is to create some kind of cache in the apiserver. The approach I am suggesting is:
> 1. The cache is used only for reading (writing doesn't read or modify cache)
> 2. The cache is storing decoded api objects (whether we will be storing all objects or just objects of some particular types is TBD) together with their etcd index (ModifiedIndex)
> 3. The cache is storing at most one version of the object with a given key (the newest one).
> 4. When we read an object from etcd (either via Get or Watch) we:

Are there cases where apiserver would care for 'historical' versions of an object?  If not, this can be a significant speed improvement, since it avoids all the cost of un-marshaling the same etcd json response every time someone looks at it.  In a different application, which needs to keep track of a set of json-serialized data stored in ZooKeeper I used a similar scheme with the following layers:

    +----------------------+
    |                      |
    |      ZooKeeper       |
    |                      |
    +----------------------+
          |     |     |
          |     |     |  Patch Watches
          v     v     v
    +--------------------------------------+
    |  ZkNodeCache {                       |
    |  Data         map[string][byte]      |
    |  Listeners    []ZkNodeCacheListener  | ------.
    |  }                                   |       |
    +--------------------------------------+       |
           ^                                       |  publish(ZkNodeEvent)
           |                                       |    ZkNodeCreated(path  string, []byte)
           | AddListener(ZkDecodedCache)           |    ZkNodeDeleted(path  string, []byte)
           |                                       |    ZkNodeModified(path string, []byte)
    +--------------------------------------+       |
    |  ZkDecodedCache                      | <-----'
    |    Data        map[string][UserType] |
    |    Listeners   []ZkDecodedListener   | ------.
    +--------------------------------------+       |
           ^                                       | publish(ZkDecodedEvent)
           |                                       |    ZkDecodedCreated(path  string, []byte)
           | AddListener(ZkDecodedSubscribed)      |    ZkDecodedDeleted(path  string, []byte)
           :                                       |    ZkDecodedModified(path string, []byte)
                                                   v

This worked remarkably well for that particular project, because the flow of information was indeed expected to only be unidirectional (always something gets updated in ZooKeeper, and the "subscribers" of each layer have to either decode the new data or pull entries out of their cache and notify their listeners).

> send a request to etcd
> if the returned version (response contains ModifiedIndex value as an explicit field) is the same as currently stored in cache, we don't need to decode it and simply return the value from the cache
> if the returned version is newer (ModifiedIndex is monotonically increasing) we decode it an update the cache with the new version (the old version)
> if the returned version is older, we simply have a cache miss and decode it without using cache

... and still cache the decoded data we just parsed?

Or have some mechanism to punch write-through holes to the cache, invalidating only those parts of it which should be refreshed from etcd either $right_now or on first access later.

I think that could work, yes.

**Comment by wojtek-t** [comment]
Sorry for late response. I'm addressing few of the questions below:

@smarterclayton 
>
Our decodings and conversions are personably an order of magnitude more inefficient in cpu and memory than they need to be.  That doesn't mean this issue is not worthwhile, but it is absolutely something else we need to investigate.

I completely agree that if we can speedup conversion that's definitely worth doing. But I'm not sure we can get huge benefits from it (i.e. we won't speedup decoding json from string and I think this will be significant factor of the work we're doing)

>
Why not target this specifically at watch, and allow watches to be aggregated?  That's similar to your proposal, but doesn't require the same complexity in changes to the code (essentially, emulate etcd.Watch centrally underneath watch.Interface).

Yes - that's definitely a reasonable approach. And I think that this even might be the first step (I mean if it appears to be not enough, we can generalize it to support also get/list and most of the work should be reusable). So I think this might be a good idea.

@lavalamp 
>
Please see my design here for a cache/indexer: #4817 (comment)

Thanks for the link (I didn't find it before). However, I think that you are trying to address a slightly different problem. Basically you're trying to reduce the amount of requests that are sent to etcd. This wasn't my goal (as I didn't observe etcd to be the main bottleneck).
And I really think that my proposal (especially if we decide to support only watches as @smarterclayton suggested) is much simpler than yours (because it tries to solve a different problem).

>
There's no point of a cache if you're still going to make an etcd request. Instead, just allow the cache/indexer to lag. clients will still get the latest version of things, at a slight delay.

This is something I don't agree - sending a request to etcd only adds a latency to the request whereas processing it in the apiserver adds the load on apiserver. Thus I think it makes sense.

Also, I think that not having a history in the cache makes it simpler in terms of implementation and it will solve (I think) 90%+ cases.

**Comment by smarterclayton** [comment]
----- Original Message -----
> Sorry for late response. I'm addressing few of the questions below:
> 
> @smarterclayton
> >
> Our decodings and conversions are personably an order of magnitude more
> inefficient in cpu and memory than they need to be.  That doesn't mean this
> issue is not worthwhile, but it is absolutely something else we need to
> investigate.
> 
> I completely agree that if we can speedup conversion that's definitely worth
> doing. But I'm not sure we can get huge benefits from it (i.e. we won't
> speedup decoding json from string and I think this will be significant
> factor of the work we're doing)

It really isn't - JSON pure decoding is probably < 5% of the total cost of our decode.

**Comment by wojtek-t** [comment]
Thanks @smarterclayton - I'm doing to profile the decoding function then.

**Comment by smarterclayton** [comment]
There are benchmarks (or were) in the conversion tests that you can look at.  We do ~10x the memory allocations and it takes ~10x the time to do a decode to internal as to decode to JSON raw, mostly because of the reflection API use.  We create a lot of throwaway small objects in the reflection steps - it's likely most of them could be converted to stack values and save a significant amount of allocations on the heap.

----- Original Message -----

**Comment by lavalamp** [comment]
@davidopp @wojtek-t 

If you read my thing again, you'll note that I say that I think to really do list correctly I have to store values, not just keys. Which I considered unfortunate, but is a feature for this purpose.

@wojtek-t the proposal is this issue is predicated on our decoding code being very slow, and it won't make sense if we make that code reasonable. I just can't believe that, in the limit once we make the changes @smarterclayton and I have suggested, it will be slower to decode text than it will be to make a network RPC.

A more serious problem with this proposal is that it handles only gets of single items, not lists, and not watches. Why? When you return a list, you have to give a resource version at which the list is correct. Since in this proposal items are individually added to your cache, you have no idea if the combination of those items is collectively correct for any particular resource version. (You can't even just use the most recent item's resourceVersion!)

Since gets are (I think) a small fraction of read load on etcd compared to listing and watching, I really don't think this is going to improve things much.

**Comment by wojtek-t** [comment]
@lavalamp 
Assuming that we can really speedup Decode (which I'm going to look deeper into starting tomorrow), I agree this probably won't give us much.
But I don't understand why do you think that it can't be used for watch - can you please explain? (I agree it won't work for List).

**Comment by lavalamp** [comment]
How do you make a watch go through this cache? I mean, I can see how you can use a get from this cache to start a single-item watch, but the watch won't go through the cache and that won't offer any reduced computational load to apiserver.

(multi-item watch can't work if list doesn't work)

**Comment by timothysc** [comment]
Aren't a lot of these performance issues around the apiserver entirely an issue of our own creation?  
What problem(s) have we solved in putting etcd behind the apiserver, vs. issues we've created?

It seems like we've shifted the problem around... 
FWIW I'm not a fan of creating another cache, and imho addressing marshaling should be a higher priority.

**Comment by wojtek-t** [comment]
Thanks a lot for the feedback - I've created #6800 and decreasing the priority of this one.

**Comment by fgrzadkowski** [comment]
Currently most decoding comes from many list requests (covered by #6564). Once we reduce it we should be fine with the load in a large cluster (<100 nodes).
Obviously improving decoding code is also very important, to meet 1.0 latency goal (all API calls < 1s) for clusters with many objects.

**Comment by wojtek-t** [comment]
Yes - but there are also a bunch of decoding coming from watch will won't disappear.

**Comment by xudifsd** [comment]
relevant to https://github.com/GoogleCloudPlatform/kubernetes/issues/5548

**Comment by wojtek-t** [comment]
Since @fgrzadkowski is currently working on adding some cache to apiserver, I'm reassigning this issue to him.

**Comment by fgrzadkowski** [comment]
Added in #7559
