### ISSUE TITLE
guestbook e2e test needs to run in a clean namespace (and clean up better after itself)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#6690]
kubectl guestbook should create and stop a working application

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:108
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../platforms/linux/amd64/kubectl [kubectl --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/.kubeconfig create -f examples/guestbook] []  <nil> replicationControllers/frontend-controller
replicationControllers/redis-master-controller
services/redis-master
replicationControllers/redis-slave-controller
services/redis-slave
Error: The resource 'projects/kubernetes-jenkins/regions/us-central1/targetPools/e2e-test-jenkins-default-frontend' already exists
[] <nil> 0xc20856b100 exit status 1 <nil> true [0xc20864c040 0xc20864c088 0xc20864c0a8] [0xc20864c040 0xc20864c088 0xc20864c0a8] [0xc20864c060 0xc20864c0a0] [0x624600 0x624600] 0xc208390300}:
Command stdout:
replicationControllers/frontend-controller
replicationControllers/redis-master-controller
services/redis-master
replicationControllers/redis-slave-controller
services/redis-slave

stderr:
Error: The resource 'projects/kubernetes-jenkins/regions/us-central1/targetPools/e2e-test-jenkins-default-frontend' already exists

**Comment by wojtek-t** [comment]
cc @piosz

**Comment by quinton-hoole** [comment]
Dupe of #6451
