### ISSUE TITLE
E2E ... Kubectl tests should grab the --api-server args

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#6707]
It appears at a breif glance that the kubectl tests aren't appending the `--api-server` arguments, and fail fast if the api-server isnt available. 
Right now the args set are:

- clientcmd.RecommendedConfigPathFlag
- certificate-authority
- client-certificate
- client-key

i don't see any others....  will confirm whats going on later.  but at first glance, im guessing kubectl.go tests will only pass if we run em on teh **api-server**.  

as this is probably important for alot of e2e test scnearios maybe I  put a PR in this wknd if i get some downtime .... unless someone beats me to it :)

**Comment by lavalamp** [comment]
What tests? I don't really follow.

**Comment by jayunit100** [comment]
Kubectl.go which uses util.go in test/e2e

**Comment by timothysc** [comment]
@jayunit100 merged so you can close this one.

**Comment by jayunit100** [comment]
yup closing !
