### ISSUE TITLE
Updating a service fails with error about PortalIP being invalid

### ISSUE THREAD

**Issue by invino4** [GoogleCloudPlatform/kubernetes#6714]
Consider a simple service def:

```
{
  "apiVersion": "v1beta1",
  "kind": "Service",
  "id": "myservice",
  "port": 80,
  "containerPort": "myservice",
  "selector": { "name": "myservice" }
}
```

Attempting to first create this service and then update it with the exact same file fails:

```
$ cluster/kubectl.sh create -f myservice.json

$ cluster/kubectl.sh update -f myservice.json
Client error: service "myservice" is invalid: spec.portalIP: invalid value '': field is immutable
```

**Comment by hobti01** [comment]
You need to get the current service first and then update it.
`kubectl get se myservice`

The portalIP and some other fields must match what was assigned after creation in order to update

**Comment by thockin-cc** [comment]
Update is not a PATCH operation, so what you are specifying is technically
a change to the portal IP.  I know it is a bit awkward in this case, but in
general there are many such fields - set by the server(s) - and we don't
want to try to special-case them all.  We do have actual PATCH support in
the works.

**Comment by invino4** [comment]
Is an update intended to be a PUT or a PATCH.  I assumed it was PUT.  If so, a PUT is always a REPLACE

**Comment by thockin** [comment]
That's correct - update is a PUT, not a PATCH.  If you try to PUT "" onto a
field that was initialized by the master (as in portalIP) we see that as a
request to change the value.  That field happens to be immutable.

Is there a reason to re-open this, or was it just for clarification?

**Comment by invino4** [comment]
Wouldn't the PUT replace the entire resource?  As such computed fields of
the previous resource are irrelevant.  The new service being defined by the
PUT would replace the previous service.  Even if the previous service has a
PortalIP as a computed field, the new service is replacing the old and so
will have its own computed PortalIP field that might not be the same.  Why
does it matter if the old service's PortalIP is an immutable field?  Its
the whole resource that is being replaced not any individual field.

**Comment by thockin** [comment]
The semantic is that the object is the same therefore you are updating it,
not replacing it.  The portalIP is defined as an immutable field - it can
not be updated.  The "fix" is easy - read the object first.

**Comment by invino4** [comment]
I would expect a PUT to be a replace operation (
https://tools.ietf.org/html/rfc7231#section-4.3.4).  Isn't the purpose of a
PATCH operation to be a modify operation while a PUT is a replace?  From
RFC 5789:

In a PUT request, the enclosed entity

is considered to be a modified version of the resource stored on the

origin server, and the client is requesting that the stored version

be *replaced*.  With PATCH, however, the enclosed entity contains a set

of instructions describing how a resource currently residing on the

origin server should be *modified* to produce a new version.


Its not a big deal, just caught me off guard I guess.

**Comment by thockin** [comment]
Yeah, I hear that, but the semantics of replacement are sort of awkward.
Should I terminate all open connections to that Service and allocate a
whole new Portal IP (that's what a blank value means, after all).  I don't
think that is what OP wants to happen.  I don't think that's what ANYONE
wants to happen, so we made that field immutable.

We could instead say "blank means don't change", but that's semantically
identical to PATCH.

**Comment by invino4** [comment]
Got it.  Thanks for the clarification.
