### ISSUE TITLE
Not building on raspberry pi 2 (arm)

### ISSUE THREAD

**Issue by ajazam** [GoogleCloudPlatform/kubernetes#6730]
I've tried to build kubernetes on  raspberrypi 2. I copied the current source from github and did a make release. I got the following
```bash
$ make release
build/release.sh
+++ [0411 19:38:30] Verifying Prerequisites....
+++ [0411 19:38:31] Building Docker image kube-build:cross.
+++ Docker build command failed for kube-build:cross

Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon
Step 0 : FROM golang:1.4
 ---> 121a93c90463
Step 1 : MAINTAINER Joe Beda <jbeda@google.com>
 ---> Using cache
 ---> 2dc6d945cac2
Step 2 : ENV KUBE_CROSSPLATFORMS linux/386 linux/arm   darwin/amd64 darwin/386   windows/amd64 windows/386
 ---> Running in 78becbb99a4b
 ---> 0ffb8c0e394f
Removing intermediate container 78becbb99a4b
Step 3 : RUN cd /usr/src/go/src && for platform in ${KUBE_CROSSPLATFORMS}; do GOOS=${platform%/*} GOARCH=${platform##*/} ./make.bash --no-clean; done
 ---> Running in 85428e3d9f57
time="2015-04-11T19:38:58+02:00" level="info" msg="exec format error"

To retry manually, run:

docker build -t kube-build:cross /root/kubernetes/_output/images/kube-build:build-b9cb2/cross

!!! Error in build/../build/common.sh:369
  'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:369 kube::build::build_image_cross(...)
  2: build/../build/common.sh:326 kube::build::build_image(...)
  3: build/release.sh:31 main(...)
Exiting with status 1
make: *** [release] Error 1
```
Obviously this isn't critical as I was only trying to build it on a toy system, but I have eight of these raspberrypi 2's and would like to, if possible, have a working kubernetes system running on arm.

**Comment by thockin** [comment]
If you just run 'make' does it complete?  The error is "exec format error"
suggesting we don't have a build for the platform or something similar

**Comment by ajazam** [comment]
On the first attempt running make crashed the raspberrypi. It stopped responding to pings. On the second attempt I got

$ make
hack/build-go.sh
+++ [0412 21:23:43] Building go targets for linux/arm:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/e2e
    cmd/integration
    cmd/gendocs
    cmd/genman
    examples/k8petstore/web-server
# github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet
/root/go/pkg/tool/linux_arm/5l: running gcc failed: Cannot allocate memory
# github.com/GoogleCloudPlatform/kubernetes/cmd/kubernetes
/root/go/pkg/tool/linux_arm/5l: running gcc failed: Cannot allocate memory
# github.com/GoogleCloudPlatform/kubernetes/cmd/hyperkube
/root/go/pkg/tool/linux_arm/5l: running gcc failed: Cannot allocate memory
# github.com/GoogleCloudPlatform/kubernetes/cmd/e2e
/root/go/pkg/tool/linux_arm/5l: running gcc failed: Cannot allocate memory
!!! Error in /root/kubernetes/hack/lib/golang.sh:316
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /root/kubernetes/hack/lib/golang.sh:316 kube::golang::build_binaries_for_platform(...)
  2: /root/kubernetes/hack/lib/golang.sh:441 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /root/kubernetes/hack/lib/golang.sh:359
  'kube::golang::build_binaries "$@"' exited with status 1
Call stack:
  1: /root/kubernetes/hack/lib/golang.sh:359 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
make: *** [all] Error 1

Current free memory is 749MB

**Comment by thockin** [comment]
It sounds like Go itself is failing.  Not sure what to do about that.

**Comment by ajazam** [comment]
Ive done following

$ taskset 3 make
hack/build-go.sh
+++ [0413 00:41:42] Building go targets for linux/arm:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/e2e
    cmd/integration
    cmd/gendocs
    cmd/genman
    examples/k8petstore/web-server
+++ [0413 00:44:47] Placing binaries

So make works.

but make release with tasket 3 does 

$ taskset 3 make release
build/release.sh
+++ [0413 00:45:57] Verifying Prerequisites....
+++ [0413 00:45:58] Building Docker image kube-build:cross.
+++ Docker build command failed for kube-build:cross

Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon
Step 0 : FROM golang:1.4
 ---> 121a93c90463
Step 1 : MAINTAINER Joe Beda <jbeda@google.com>
 ---> Using cache
 ---> 2dc6d945cac2
Step 2 : ENV KUBE_CROSSPLATFORMS linux/386 linux/arm   darwin/amd64 darwin/386   windows/amd64 windows/386
 ---> Using cache
 ---> 0ffb8c0e394f
Step 3 : RUN cd /usr/src/go/src && for platform in ${KUBE_CROSSPLATFORMS}; do GOOS=${platform%/*} GOARCH=${platform##*/} ./make.bash --no-clean; done
 ---> Running in 341b7843d2d8
time="2015-04-13T00:45:59+02:00" level="info" msg="exec format error"

To retry manually, run:

docker build -t kube-build:cross /root/kubernetes/_output/images/kube-build:build-b9cb2/cross

!!! Error in build/../build/common.sh:369
  'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:369 kube::build::build_image_cross(...)
  2: build/../build/common.sh:326 kube::build::build_image(...)
  3: build/release.sh:31 main(...)
Exiting with status 1
make: *** [release] Error 1


Ive also upgraded gcc to 4.8.4 to build the go binaries.

Not sure what else todo.

**Comment by thockin** [comment]
Innnnnnteresting..

**Comment by thockin** [comment]
AFAIK none of the core team has these machines around, so this might be a while before we can get a chance to look into it...

**Comment by ajazam** [comment]
No problem

**Comment by ajazam** [comment]
Can't help myself ;)

I've just done a git update of my copy of kubernetes from github and 

taskset 2 make

and I have no errors. So I've made progress. The most recent commit I have is eb1ea269954da2ce557f3305fa88d42e3ade7975

**Comment by thockin-cc** [comment]
Well that's good... Bug closed?

**Comment by ajazam** [comment]
yes, thanks
