### ISSUE TITLE
kube-proxy UDP timeout is too long

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#6738]
Given DNS usage, it's possible that a lot of sockets will be open waiting for timeout.  This should probably be O(10) seconds instead.

**Comment by xiang90** [comment]
@thockin It looks like the current timeout is 60 second, which is O(10). Isnt it?

**Comment by thockin** [comment]
Pedantically, I guess 60 is O(10), but since we're talking time I think of
seconds and minutes as orders of magnitude.

**Comment by xiang90** [comment]
@thockin Shall we close this one?
