### ISSUE TITLE
Status: 502:  (unhandled http status [Temporary Redirect] with body []) [0]

### ISSUE THREAD

**Issue by onorua** [GoogleCloudPlatform/kubernetes#6748]
I've updated to v0.14.2, everything seem to be working for some time, but recently I've got following error in apiserver log:
```
I0413 05:55:41.685861       1 publish.go:153] setting endpoints for master service "kubernetes" to &{{ } {kubernetes  default  5f39aaaf-e117-11e4-8f67-0242ac11000c 8 2015-04-12 13:25:22 +0000 UTC <nil> map[] map[]} [{[{172.17.0.15 <nil>}] [{ 6443 TCP}]}]}
I0413 05:55:41.728154       1 publish.go:153] setting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default  5f48fd89-e117-11e4-8f67-0242ac11000c 9 2015-04-12 13:25:22 +0000 UTC <nil> map[] map[]} [{[{172.17.0.15 <nil>}] [{ 7080 TCP}]}]}
E0413 05:55:41.785785       1 publish.go:45] Can't create rw endpoints: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
E0413 05:55:41.835536       1 publish.go:70] Can't create ro endpoints: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
E0413 05:55:42.145563       1 errors.go:66] apiserver received an error that is not an api.Status: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
E0413 05:55:42.352224       1 errors.go:66] apiserver received an error that is not an api.Status: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
```
I can read from api-server what was already there, but can't neither change nor add anything. 
I can see that the problem seems to be due to connection to etcd, but I can change values in etcd with etcdctl. So there is something in between kubernetes and etcd.

**Comment by onorua** [comment]
As a workaround I had to remove both etcd and kubernetes clusters, is there any way to get it working without complete system recreation?

**Comment by davidopp** [comment]
Sorry for the delay in responding.

Are you trying to run etcd separately from Kubernetes? This isn't really supported at the moment, but was it working at one point for you and later stopped working?

Also, can you clarify your last question? If you have removed the etcd and kubernetes clusters, what is left of the system that you would like to not have to re-create?

**Comment by jfoy** [comment]
I'm also running into this issue with a local dev environment. The stack is kubernetes 0.14.2 running as a set of fleet units on a coreos 647.0.0/etcd 0.4.9 cluster, all in turn running on a set of vmware fusion VMs managed by vagrant. The issue is exactly as described above: the initial deployment just works, but subsequent changes like bouncing the kubelet will fail.

These are the errors on master:

      Apr 17 00:28:51 core-01 kube-apiserver[1245]: E0417 00:28:51.918638    1245 errors.go:66] apiserver received an error that is not an api.Status: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
      Apr 17 00:28:51 core-01 kube-controller-manager[1276]: E0417 00:28:51.920353    1276 nodecontroller.go:503] error updating node 172.17.8.101: 502:  (unhandled http status [Temporary Redirect] with body []) [0]

These are the errors from the minion:

      Apr 17 00:28:50 worker-01 kubelet[11357]: I0417 00:28:50.611376   11357 event.go:138] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"172.17.8.101", UID:"172.17.8.101", APIVersion:"", ResourceVersion:"", FieldPath:""}): reason: 'online' Node 172.17.8.101 is now online
      Apr 17 00:28:50 worker-01 kubelet[11357]: E0417 00:28:50.616068   11357 event.go:127] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"172.17.8.101.13d5a5985f35f118", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"172.17.8.101", UID:"172.17.8.101", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"online", Message:"Node 172.17.8.101 is now online", Source:api.EventSource{Component:"kubelet", Host:"172.17.8.101"}, FirstTimestamp:util.Time{Time:time.Time{sec:63564827330, nsec:610983192, loc:(*time.Location)(0x16b3760)}}, LastTimestamp:util.Time{Time:time.Time{sec:63564827330, nsec:610983192, loc:(*time.Location)(0x16b3760)}}, Count:1}': '502:  (unhandled http status [Temporary Redirect] with body []) [0]' (will not retry!)
      Apr 17 00:28:50 worker-01 kubelet[11357]: E0417 00:28:50.617382   11357 kubelet.go:1729] error updating node status, will retry: 502:  (unhandled http status [Temporary Redirect] with body []) [0]

**Comment by davidopp** [comment]
Are you running etcd separately, or are you allowing it to be started up by the Kubernetes startup scripts?

At the time you are seeing these errors, are you able to contact etcd, for example does
curl -L http://<etcd host:port>/version
and
curl -L http://127.0.0.1:4001/v2/keys
work?

**Comment by jfoy** [comment]
We tracked this down to the etcd cluster losing quorum. It's not a kubernetes issue.
