### ISSUE TITLE
Create "scalability" test suite running continuously on Jenkins

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#6753]
cc @fgrzadkowski @ixdy @zmerlynn @quinton-hoole

**Comment by davidopp** [comment]
It would be good to collect and archive this data on, say, a weekly basis so we can chart our performance/scalability progress over time. (This was originally suggested by @brendandburns).  For a historical retrospective perspective, I think we'd be interested latency of some common operations (time to start running one pod in isolation, total time to start running N pods, time to list all pods when there are N pods) vs. cluster size (1, 10, 100, 1000?).

Also relevant is #3139 and there was some other issue with a suggested list of operations (e.g. creating services, etc.) but I can't find it. Anyway I don't think it's hard to re-create as the number of operations we support isn't very large.

**Comment by bprashanth** [comment]
I'm writing some of the more isolated bechmarks. They're runnable via go test -bench=. and you can specify all the normal go things (like -cpu, parallelism etc) and go will just take care of handing your tests different values and stopping at the point they've run for long enough. They run against a single instance master/etcd started just like we start it in the integration tests. I currently have one for basic listing, watching (reflector vs etcd) and rc performance.

@wojtek-t wdyt about integration this with your work? It would be nice if we could run these more basic benchmarks with every pr with a more intense post checking suite sometime later. They'd also red-flag, eg, a slow watch on shippable that causes test timeouts.

**Comment by davidopp** [comment]
Ah, the issue I was thinking of is #3124

**Comment by davidopp** [comment]
Also, from the issue that was discussing what VM size we should use for the master, "a plot of master cpu vs. number of nodes under a load scaled proportionally to the number of nodes" was suggested.

**Comment by davidopp** [comment]
@quinton-hoole @timothysc

Tim I think you were the one asking about this this morning -- if not, please let me know and I'll try harder to remember who it was. :)

@wojtek-t Quinton and Tim were interested in knowing what database (or whatever) we'll use to store these results over time.

**Comment by wojtek-t** [comment]
@davidopp so far I didn't think about it at all - Jenkins is storing those results and it's configurable how long it should store them (we should probably change it to be long enough).

**Comment by fgrzadkowski** [comment]
One of the options is to use prometheus service that will collect some metrics and store them. It will allow us to query this data and create some dashboards. See #6753.

**Comment by timothysc** [comment]
@wojtek-t fwiw- I would like to move some "scalability" tests out of density, b/c they currently fail and IMHO are conflated.

**Comment by wojtek-t** [comment]
@timothysc: those tests are flaky, but I think that's because the system is not very reliable for big clusters. But I see a significant different with what was happening 5 days ago.

**Comment by quinton-hoole** [comment]
fgrzadkowski@ no objection to trying to use prometheus to store and present data here.  I have not yet had time to figure out whether there are any better options yet.

**Comment by timothysc** [comment]
@fgrzadkowski do you have other options to compare against?

**Comment by quinton-hoole** [comment]
@wojtek-t can we close this issue yet?  It seems that the basic "Create "scalability" test suite running continuously on Jenkins" is done?  Perhaps create more specific issues for the remaining improvements?

**Comment by wojtek-t** [comment]
I think that's fine. We already have something to start with and we can create more sophisticated tests under a different issue.
