### ISSUE TITLE
controller/framework test is flaky

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#6777]
From shippable, I noticed there are several failed cases, for example, 

https://app.shippable.com/builds/552bfb376206490c009730c3

E0413 17:34:38.400974   17931 reflector.go:158] watch of *api.Pod ended with: Stop requested
--- FAIL: Example (0.61s)
got:

want:
a-hello
b-controller
c-framework
FAIL
coverage: 85.9% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework	7.652s

cc/ @lavalamp

**Comment by dchen1107** [comment]
another example:

https://app.shippable.com/builds/552bfdfa6206490c009730eb

**Comment by lavalamp** [comment]
ah-- this is a different thing. I will fix this, too.

**Comment by ddysher** [comment]
I'm seeing this from an unrelated change

```
E0413 16:50:08.658895   18560 reflector.go:158] watch of *api.Pod ended with: Stop requested
--- FAIL: TestUpdate (2.02 seconds)
	controller_test.go:317: observed transition "to" -> "from" for a-0-0
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/controller/framework	3.220s
```

**Comment by lavalamp** [comment]
Yeah I think that's the one I expected to see.
