### ISSUE TITLE
Profile & optimize decoding read from etcd

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#6800]
Forked from #6678 

@smarterclayton @lavalamp @davidopp @timothysc

From @smarterclayton 
>
Our decodings and conversions are personably an order of magnitude more inefficient in cpu and memory than they need to be.  That doesn't mean this issue is not worthwhile, but it is absolutely something else we need to investigate.

**Comment by wojtek-t** [comment]
I did some a bit deeper analysis and here are the most interesting findings:
1. ~10% is spent on deferring the type of the object, basically: DataVersionAndKind() function:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/decode.go#L31
2. ~20% is spent on unmarshalling json
3. most of the remaining time (~70%) is spent in convertKV method:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/converter.go#L679
where
- 5-10% is spent on checkField()
- 5-10% is spent on tagOf()
- majority is spent on kvValue::value()

However, I don't have any clear ideas how to improve it yet.

**Comment by smarterclayton** [comment]
If you look at a memory allocation profile you'll see a huge amount of allocations of things like conversion.State and reflect.*, which will burn CPU in garbage collection as well.

> On Apr 14, 2015, at 9:12 AM, Wojciech Tyczynski <notifications@github.com> wrote:
> 
> I did some a bit deeper analysis and here are the most interesting findings:
> 1. ~10% is spent on deferring the type of the object, basically: DataVersionAndKind() function:
> https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/conversion/decode.go#L31
> 2. ~20% is spent on unmarshalling json
> 
Does this include both unmarshals or just the second one?  We unmarshal twice (once above), so I just want to verify.

**Comment by wojtek-t** [comment]
>
Does this include both unmarshals or just the second one?  We unmarshal twice (once above), so I just want to verify.

It's just the second one. So basically, we spent ~30% of time on both unmarshallings.

**Comment by smarterclayton** [comment]
In an ideal world, if we had more control over unmarshalling, we would be able to do both in a single pass (scan and buffer until we find the type/version keys, then reset and run on the known type).  Also, it's worth remembering that the JSON unmarshal time is *probably* dominated by reflection and reflection related unmarshalling.  A generated code approach to unmarshalling and conversion would target both of those.

----- Original Message -----

**Comment by wojtek-t** [comment]
Yes - I completely agree that "type-specific-unmarshaling" would be much much more effective. Do you think it makes sense to do it now? (it seems to be a lot of work to do it, because it requires writing json parser, right?)

**Comment by erictune** [comment]
Improving encoding/decoding speed seems much better than adding caching.  Caching always adds bugs which are hard to reproduce.  There may be bugs with a new encoder/decoder, but they should be easy to repro and side by side testing and fuzz testing can work a lot of the bugs out of a new decoding scheme.

Now that apiserver is the sole client of etcd, would it make sense to persist the data in etcd a more efficiently decodable form, such as a gob?

**Comment by timothysc** [comment]
Anyone considered other libs?  https://journal.paul.querna.org/articles/2014/03/31/ffjson-faster-json-in-go/

**Comment by smarterclayton** [comment]
The investigation in https://github.com/GoogleCloudPlatform/kubernetes/issues/3338 pointed to ugorji which can generate a static unmarshaller for a known type (no one has tried it yet though).  The dynamic type unmarshal is valuable in some places (clients, tools) but in the APIServer in many cases we know the exact type, so an unmarshal to the wrong type can be a type error (DecodeInto).  We can always optimize the dynamic type unmarshal later (tokenizing scanner over the byte array that gets passed to decode) after optimizing the known type unmarshal.

Another possible source of inefficiency in the client side of watch, which needs to break a stream into JSON chunks (the []byte passed to Decode()), and it reuses the json.Decoder logic to do that.  I'm not sure that is zero copy, but it should be possible to get that down to zero copy (the tokenizer in encoding/json is pretty efficient, so essentially we just need to keep growing the buffer until we see a closed JSON object or get a decode error).  

Conversion is of course the dominant factor right now, so I don't want to imply that the unmarshalling is the most important problem right now.

----- Original Message -----

**Comment by smarterclayton** [comment]
ugorji is better than ffjson for most practical considerations I've seen (without actually trying it) as referenced in the other thread.

----- Original Message -----

**Comment by wojtek-t** [comment]
>
Conversion is of course the dominant factor right now, so I don't want to imply that the unmarshalling is the most important problem right now.

I agree, but if we have a dedicated per-type unmarshaling, we can unmarshal it directly to api objects (and omit json on this path) which should be much more efficient, right?

**Comment by smarterclayton** [comment]
We still have to do a conversion when reading from etcd - what's in etcd has to be versioned as well.

**Comment by lavalamp** [comment]
@timothysc: garbage collection is due to the massive amounts of allocation done by decode/conversion. Unfortunately.

> A generated code approach to unmarshalling and conversion would target both of those.

+1000

**Comment by wojtek-t** [comment]
@lavalamp 
 Do you think that it's worth creating code-generators responsible for type-specific unmarshaling and conversion now? It seems to be a lot of work and it's hard to estimate the exact gains of it.

**Comment by wojtek-t** [comment]
To be clear - I'm happy to work on that, but I want to ensure that we have agreement that it's worth doing now.

**Comment by wojtek-t** [comment]
I did some quick experiment and added few dedicated conversion functions for Pod, TypeMeta and  ObjectMeta (to avoid using the reflect package). It seems that just this gives us more than 5% of gain, so I'm pretty sure that having a dedicate conversion functions for all types from api would have a huge impact.
Do you think that adding them makes sense? [I mean adding some code generator that based on the given types, will generate such conversion functions]. I can start working on it tomorrow.

**Comment by smarterclayton** [comment]
I'm ok with the approach as long as the generation is flexible and well factored (takes a runtime.Scheme with conversion funds and generates code).  I know we have good tests around conversion, so I'm less worried about the impact.

**Comment by lavalamp** [comment]
@wojtek-t Yes, I think it's worth doing. It is going to be a bit tricky to do correctly, though-- the caveat in your update isn't going to fly :) We can chat if you want to discuss some approaches to this. I think you may need to write a program that parses pkg/api/ and pkg/api/v1betaX, and outputs reflection-free code that does all the things in v1betaX/conversion.go. But there may be a few steps we want to do before that.

**Comment by erictune** [comment]
5% improvement doesn't seem like much.  If you expand this to all (less common) types, do you expect like 10% or 15%?  That still seems quite low for the added complexity.

**Comment by wojtek-t** [comment]
I expect this to be 40% (this is just some guess, but definitely more than 10-15%)

**Comment by timothysc** [comment]
@wojtek-t how should we validate "goodness", compare /metrics ?

**Comment by smarterclayton** [comment]
In this case I'd accept an encode decode benchmark showing a few thousand cycles, as well as a demonstrated reduction in allocations (number and bytes).

**Comment by timothysc** [comment]
I also think gating e2e on this would be good, as to detect performance regressions.

**Comment by wojtek-t** [comment]
@timothysc : I agree with @smarterclayton - I think the easiest way is to have some decoding/conversion benchmarks (the pkg/api/serialization_test.go is pretty good one). But exposing it in /metrics also sounds like a good idea.

**Comment by wojtek-t** [comment]
Thank a lot for all kind of feedback.
I'm starting to work on the code to automatically create conversion functions that doesn't use reflection.

**Comment by wojtek-t** [comment]
I've started writing some code for it on Friday and spent some time today on it. I will try to send out some WIP PR tomorrow to start more technical discussion on it.

**Comment by lavalamp** [comment]
Looking forward to it :)

**Comment by smarterclayton** [comment]
Slightly related to this, at least in terms of structure, is that I'm considering a different approach for unrecognized objects embedded in Lists and config formats that would allow better consumption by generic tools using swagger info.  https://github.com/GoogleCloudPlatform/kubernetes/issues/7070 proposes using map[string]interface{} internally for any unknown types, which we can then manage opaquely.  Whatever conversion code we evolve for this would be useful for that context as well.

**Comment by wojtek-t** [comment]
This is mostly done - (at least at the v1.0 scope).
The only remaining thing is to update the documentation.
I will send a separate PR to fix it and close this issue later this week.
