### ISSUE TITLE
REST api - why is the namespace status so nested?

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#6802]
Currently it looks like this:
 "status": {
        "phase": "Active"
      }

why not just "status" : "Active" ?

**Comment by derekwaynecarr** [comment]
It is intended to be consistent with Node and NodeStatus.

see: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L1101

There may be other fields in NamespaceStatus in the future.
