### ISSUE TITLE
GCE, AWS and other Volume sources should be optional in the VolumeSource struct

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#6841]
They are all required right now: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L203
Need to add the omitempty tag.

**Comment by nikhiljindal** [comment]
cc @bgrant0607 who pointed it out.

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by markturansky** [comment]
I imagine we would apply this same thing to the PersistentVolumeSource?

Also, probably tangential to this issue, what volumes live in which VolumeSource?  Many new plugins were recently added that should probably only be PersistentVolumes.

The ability to have the volume live in just 1 volume source was just merged yesterday.  The volumes can now be separated as appropriate.

**Comment by bgrant0607** [comment]
@markturansky Yes, the same thing applies to PersistentVolumeSource.

We need the persistent volume API to be fully operational and get experience with it before we deprecate the direct volume sources.

**Comment by thockin** [comment]
What denotes them as required?  In reality they are "one of"

**Comment by bgrant0607** [comment]
Lack of "omitempty".

We don't have "one of".

**Comment by thockin** [comment]
I know we don't have one-of, I was just saying.  But yes, these could all
be omitempty

**Comment by nikhiljindal** [comment]
Fixed via #8338
