### ISSUE TITLE
Vagrant testing loops foerever

### ISSUE THREAD

**Issue by runseb** [GoogleCloudPlatform/kubernetes#6856]
Hi, when trying the Vagrant environment. The nodes start but the validation of the minion loops forever.
How can I terminate it properly and get a working k8s cluster ?

    $ ./cluster/kube-up.sh 
    Starting cluster using provider: vagrant
    ... calling verify-prereqs
    ... calling kube-up  
    Using credentials: vagrant:vagrant
    Bringing machine 'master' up with 'virtualbox' provider...
    Bringing machine 'minion-1' up with 'virtualbox' provider...
    ==> master: VirtualBox VM is already running.
    ==> minion-1: VirtualBox VM is already running. 
    Each machine instance has been created/updated.
      Now waiting for the Salt provisioning process to complete on each machine.
      This can take some time based on your network, disk, and cpu speed.
      It is possible for an error to occur during Salt provision of cluster and this could loop forever.
    Validating master
    Validating minion-1
    .............................................

**Comment by derekwaynecarr** [comment]
Ctrl-C and then run 

$ cluster/kube-push.sh

Which will cause the salt process to re-run and hopefully resolve any issue that flaked the first time.

**Comment by runseb** [comment]
upgrading to vbox 4.3.26 seems to have solved the issue. thanks for the tip

**Comment by derekwaynecarr** [comment]
Note to self and check my vagrant version

**Comment by pducic** [comment]
neither upgrading nor re-running helped in my case.
however, deleting problematic VM did!
