### ISSUE TITLE
`kubectl delete $TYPE $NAME` does a GET before DELETE

### ISSUE THREAD

**Issue by liggitt** [GoogleCloudPlatform/kubernetes#6859]
This code fails if the GET fails, and never tries the DELETE:
```
	mapper, typer := f.Object()
	r := resource.NewBuilder(mapper, typer, f.ClientMapperForCommand()).
		ContinueOnError().
		NamespaceParam(cmdNamespace).DefaultNamespace().
		FilenameParam(filenames...).
		SelectorParam(cmdutil.GetFlagString(cmd, "selector")).
		SelectAllParam(cmdutil.GetFlagBool(cmd, "all")).
		ResourceTypeOrNameArgs(false, args...).
		Flatten().
		Do()
	err = r.Err()
	if err != nil {
		return err
	}
```

This means if you don't have authorization to `get`, but do have permission to `delete`, you cannot use `kubectl delete`

**Comment by smarterclayton** [comment]
When latest is not specified there should never be a get.  Probably something should be using the lazy resolver.

**Comment by liggitt** [comment]
Named resources were always being fetched, which is almost always what you want, but not in the case of a delete. Opened a PR with an option to skip that fetch, and used it from `kubectl delete` (with a test)
