### ISSUE TITLE
Version of status kind is incorrect for the requested api version

### ISSUE THREAD

**Issue by jcantrill** [GoogleCloudPlatform/kubernetes#6876]
While retrieving a resource from a specific versioned endpoint (e.g. v1beta1) received a status with a version that is not expected.  Would expect to receive a v1beta1 status kind which breaks our OpenShift Eclipse tooling
```
[vagrant@openshiftdev sample-app]$ curl -k -H "Authorization:Bearer MWVkYzMzYWMtZjUyYy00MzRmLWJjM2YtNWU3Y2JjZWExYWVm" https://localhost:8443/api/v1beta1/services/ruby-helloworld-sample{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "\"/api/v1beta1/services/ruby-helloworld-sample\" is forbidden because jcantril cannot get on services with name \"ruby-helloworld-sample\" in default",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

**Comment by erictune** [comment]
@smarterclayton @bgrant0607 @lavalamp

**Comment by bgrant0607** [comment]
That is certainly a bug. errToAPIStatus produces an object in the internal representation, which is then passed to writeJSON, without specifying a version. Instead, it uses the default version, which we just changed to v1beta3.

cc @nikhiljindal

**Comment by bgrant0607** [comment]
@nikhiljindal points out that this instance of the problem is in Openshift:
https://github.com/openshift/origin/blob/8c99516105e53696957ce3ec6e2a43c6692c7557/pkg/cmd/server/origin/master.go#L612
```
output, err := klatest.Codec.Encode(&forbiddenError.ErrStatus)
```

@smarterclayton

**Comment by smarterclayton** [comment]
Sorry about that - shouldn't have been opened here.  @deads2k, this is an issue against the forbidden handler.
