### ISSUE TITLE
Endpoint controller never deletes an endpoint

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#6877]
So we'll leak them and/or reuse them perhaps inappropriately. I imagine this could be pretty hard on kube-proxy after a while.

Discovered while working on #6518. @bgrant0607 was suggesting implementing a generic delete-when-parent-is-deleted mechanism, so I may not try to fix this 100% with my current work on #6518.

**Comment by bgrant0607** [comment]
Generic mechanism proposal was here: https://github.com/GoogleCloudPlatform/kubernetes/issues/1535#issuecomment-91413501

**Comment by fgrzadkowski** [comment]
I think it should be enough to check if endpoints match services once just after we initialize, right?

**Comment by lavalamp** [comment]
@fgrzadkowski Yeah that should be enough to close this. Although the general mechanism would be nice, too.
