### ISSUE TITLE
No such image: gcr.io/google_containers/redis

### ISSUE THREAD

**Issue by BlueShells** [GoogleCloudPlatform/kubernetes#6888]
I run followed "https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/README.md"

but after I run "kubectl create -f examples/guestbook/redis-master-controller.json"

redis-master-controller-e0zho             redis-master   gcr.io/google_containers/redis   fed-node/   app=redis,name=redis-master   Pending   6 minutes

it is always pending ,and I checked the log on the node ,here are the errors,what did I miss when I build the example?thanks

Apr 16 10:35:41 fedora docker: time="2015-04-16T10:35:41+08:00" level="info" msg="+job image_inspect(gcr.io/google_containers/redis)"
Apr 16 10:35:41 fedora docker: No such image: gcr.io/google_containers/redis
Apr 16 10:35:41 fedora docker: time="2015-04-16T10:35:41+08:00" level="info" msg="-job image_inspect(gcr.io/google_containers/redis) = ERR (1)"
Apr 16 10:35:41 fedora docker: time="2015-04-16T10:35:41+08:00" level="error" msg="Handler for GET /images/{name:.*}/json returned error: No such image: gcr.io/google_containers/redis"
Apr 16 10:35:41 fedora docker: time="2015-04-16T10:35:41+08:00" level="error" msg="HTTP Error: statusCode=404 No such image: gcr.io/google_containers/redis"
Apr 16 10:35:41 fedora kubelet: E0416 10:35:41.606815    7380 kubelet.go:1990] Cannot get host IP: Host IP unknown; known addresses: []
Apr 16 10:35:41 fedora kubelet: E0416 10:35:41.606867    7380 pod_workers.go:103] Error syncing pod cc1f1c78-e3e0-11e4-b8f6-fa163ebba90c, skipping: image pull failed for gcr.io/google_containers/pause:0.8.0, this may be because there are no credentials on this request.  details: (API error (500): Invalid registry endpoint https://gcr.io/v1/: Get https://gcr.io/v1/_ping: dial tcp 74.125.203.82:443: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry gcr.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/gcr.io/ca.crt
Apr 16 10:35:41 fedora kubelet: )
Apr 16 10:35:41 fedora kubelet: I0416 10:35:41.606966    7380 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-controller-e0zho", UID:"cc1f1c78-e3e0-11e4-b8f6-fa163ebba90c", APIVersion:"v1beta3", ResourceVersion:"13546", FieldPath:"implicitly required container POD"}): reason: 'failed' Failed to pull image "gcr.io/google_containers/pause:0.8.0": image pull failed for gcr.io/google_containers/pause:0.8.0, this may be because there are no credentials on this request.  details: (API error (500): Invalid registry endpoint https://gcr.io/v1/: Get https://gcr.io/v1/_ping: dial tcp 74.125.203.82:443: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry gcr.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/gcr.io/ca.crt
Apr 16 10:35:41 fedora kubelet: )

**Comment by BlueShells** [comment]
it seems that I can't ping gcr.io,How can solve this problem?

**Comment by erictune** [comment]
When I run `ping gcr.io` on my desktop (non-kubernetes-node) machine, I get a response.  If you don't then you would need to figure out why -- I doubt I could help with that.  If you can ping it from your desktop, but not from the kubernetes node, then I may be able to help debug.

**Comment by ddysher** [comment]
@BlueShells is blocked by GFW, you need to find a way out :)

**Comment by BlueShells** [comment]
@ddysher @erictune  thanks guys,I just install kuber on the other servers out of GFW,it works now ,so if you have method to solve the GFW problems ,better,if not ,that's all right ,thanks all the same

**Comment by ddysher** [comment]
Thanks for confirming this.  I think we can close the issue now.

**Comment by vmarmol** [comment]
Would it be useful to maintain the images in the Docker Hub as well for cases like these? I imagine it could be possible that should get blocked too and we'd be out of luck :)

**Comment by tobegit3hub** [comment]
Moving to docker hub is much helpful. Please do it :sob:

**Comment by ReSearchITEng** [comment]
please move to docker hub...
Especially in intranets, people get:
2700 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"demo11", Name:"webserver-controller-ychel", UID:"d310777e-2958-11e5-be96-4437e6a56f8a", APIVersion:"v1beta3", ResourceVersion:"274474", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: image pull failed for gcr.io/google_containers/pause:0.8.0, this may be because there are no credentials on this request.  details: (Error pulling image (0.8.0) from gcr.io/google_containers/pause, Get https://storage.googleapis.com/artifacts.google-containers.appspot.com/containers/images/2c40b0526b6358710fd09e7b8c022429268cc61703b4777e528ac9d469a07ca1/ancestry: Forbidden)

**Comment by ReSearchITEng** [comment]
WORKAROUND (unofficial SOLUTION) when you cannot connect to google, but you can connect to docker.io:

docker pull docker.io/kubernetes/pause
docker tag kubernetes/pause gcr.io/google_containers/pause:0.8.0
docker tag gcr.io/google_containers/pause:0.8.0 gcr.io/google_containers/pause

Tested and working for me.

**Comment by xuedihualu** [comment]
@ReSearchITEng
Hi:
I do as you said ,But still have the problem. Is not to start a container from gcr.io/google_containers/pause

**Comment by ReSearchITEng** [comment]
@xuedihualu
if the image is already available on the node where it is supposed to start the container, it will not fail trying to get it. 
are you able to do:   
`docker run  gcr.io/google_containers/pause` on the problematic host?

**Comment by yxy12a** [comment]
start the kubelet like below will solve the issue that when you cannot connect to google, but  can connect to docker.io:
kubelet --pod-infra-container-image="docker.io/kubernetes/pause"

**Comment by adaiguoguo** [comment]
@yxy12a .Thank you.Your workaround seems to be much better

**Comment by jean0313** [comment]
@yxy12a It works for me. thanks.

**Comment by netroby** [comment]
+1 please move to docker.io

**Comment by laugimethods** [comment]
@dims @yujuhong : Those workarounds do work only when you **do know where are located** the equivalent images on DockerHub...
I try to follow by the book [Kubernetes' Spark example](https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/spark) and this example fails because of "Failed to pull image "gcr.io/google_containers/spark:1.5.2_v1": image pull failed... ".
Now, which Spark image from DockerHub (or whatever repo) should I use, especially since not official one does exist? I cannot guess it since I don't have access, even through a regular Web Browser, to [https://gcr.io/google_containers/](https://gcr.io/google_containers/) ("404. That’s an error. The requested URL /google_containers/ was not found on this server.").
So please make sure that the provided Docker Images are reachable by anyone...

**Comment by dims** [comment]
@laugimethods : Here's what i usually do

`docker search gcr.io/google-containers/spark` : To check if there are spark images in the remote repository

`docker pull -a gcr.io/google_containers/spark` : Pull ALL tags from remote repository to local docker

`docker images | grep spark` : Check what tags are present for the images and then pick a specific one to use

At this moment, here's what i see
```
gcr.io/google_containers/spark                   1.5.2_v1            22712970844d        3 months ago        989.9 MB
gcr.io/google_containers/spark                   latest              22712970844d        3 months ago        989.9 MB
gcr.io/google_containers/spark                   1.5.1_v3            c5b3aa1efb63        4 months ago        989.8 MB
```

**Comment by laugimethods** [comment]
@dims: Thanks for your useful tips. However, it doesn't provide the tag of those images on DockerHub (if they do exist there), like it is suggested in `docker pull docker.io/kubernetes/pause`...

Btw, I'm able to pull the `spark:1.5.2_v1` image directly using `docker`...
```
bash-3.2$ docker pull gcr.io/google_containers/spark:1.5.2_v1
1.5.2_v1: Pulling from google_containers/spark
7268d8f794c4: Already exists
a3ed95caeb02: Pull complete
...
b7c7aa68a4cf: Pull complete
Digest: sha256:13e0d3a652957af617ad4b7fe0a8e04e6c08ae8892e9efec6765d7afa388539c
Status: Downloaded newer image for gcr.io/google_containers/spark:1.5.2_v1
```
but not through K8s (even after pulling the image thanks to the previous docker command):
```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  18m		18m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned spark-master-controller-vpu57 to 192.168.64.2
  18m		3m		6	{kubelet 192.168.64.2}	spec.containers{spark-master}	Normal		Pulling		pulling image "gcr.io/google_containers/spark:1.5.2_v1"
  16m		1m		6	{kubelet 192.168.64.2}	spec.containers{spark-master}	Warning		Failed		Failed to pull image "gcr.io/google_containers/spark:1.5.2_v1": image pull failed for gcr.io/google_containers/spark:1.5.2_v1, this may be because there are no credentials on this request.  details: (API error (500): unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: Temporary failure in name resolution
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io: Temporary failure in name resolution
)
  16m	1m	6	{kubelet 192.168.64.2}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "spark-master" with ErrImagePull: "image pull failed for gcr.io/google_containers/spark:1.5.2_v1, this may be because there are no credentials on this request.  details: (API error (500): unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: Temporary failure in name resolution\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io: Temporary failure in name resolution\n)"

  16m	13s	25	{kubelet 192.168.64.2}	spec.containers{spark-master}	Normal	BackOff		Back-off pulling image "gcr.io/google_containers/spark:1.5.2_v1"
  16m	13s	25	{kubelet 192.168.64.2}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "spark-master" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/spark:1.5.2_v1\""
```

**Comment by dims** [comment]
@laugimethods : very weird. are the docker commands run on the same box as the kubelet? ("Temporary failure in name resolution" seems to imply a DNS problem?)

**Comment by laugimethods** [comment]
@dims: Yes, very same CLI... BTW, I'm running the beta version of native Docker on Mac.
```
  FirstSeen	LastSeen	Count	From			SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  18m		18m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned spark-master-controller-vpu57 to 192.168.64.2
  18m		3m		6	{kubelet 192.168.64.2}	spec.containers{spark-master}	Normal		Pulling		pulling image "gcr.io/google_containers/spark:1.5.2_v1"
  16m		1m		6	{kubelet 192.168.64.2}	spec.containers{spark-master}	Warning		Failed		Failed to pull image "gcr.io/google_containers/spark:1.5.2_v1": image pull failed for gcr.io/google_containers/spark:1.5.2_v1, this may be because there are no credentials on this request.  details: (API error (500): unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: Temporary failure in name resolution
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io: Temporary failure in name resolution
)
  16m	1m	6	{kubelet 192.168.64.2}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "spark-master" with ErrImagePull: "image pull failed for gcr.io/google_containers/spark:1.5.2_v1, this may be because there are no credentials on this request.  details: (API error (500): unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: Temporary failure in name resolution\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io: Temporary failure in name resolution\n)"

  16m	13s	25	{kubelet 192.168.64.2}	spec.containers{spark-master}	Normal	BackOff		Back-off pulling image "gcr.io/google_containers/spark:1.5.2_v1"
  16m	13s	25	{kubelet 192.168.64.2}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "spark-master" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/spark:1.5.2_v1\""
bash-3.2$ docker images
REPOSITORY                                                TAG                 IMAGE ID            CREATED             SIZE
...
gettyimages/spark                                         1.6.0-hadoop-2.6    3a3dcc25744a        3 months ago        709.1 MB
gcr.io/google_containers/spark                            1.5.2_v1            22712970844d        3 months ago        989.9 MB
gettyimages/spark                                         1.5.2-hadoop-2.6    6bc6862a4701        6 months ago        655.8 MB
gcr.io/google_containers/spark-master                     latest              d594b00c063a        6 months ago        989.5 MB
```

**Comment by laugimethods** [comment]
FYI, I tried another example ([Java EE Application using WildFly and MySQL](https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/javaee)), which is based on images hosted on Docker Hub, with the same outcome:
```
  FirstSeen	LastSeen	Count	From			SubobjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  1m		1m		1	{default-scheduler }				Normal		Scheduled	Successfully assigned mysql-pod to 192.168.64.2
  1m		54s		2	{kubelet 192.168.64.2}	spec.containers{mysql}	Normal		Pulling		pulling image "mysql:latest"
  1m		19s		2	{kubelet 192.168.64.2}	spec.containers{mysql}	Warning		Failed		Failed to pull image "mysql:latest": Error while pulling image: Get https://index.docker.io/v1/repositories/library/mysql/images: dial tcp: lookup index.docker.io: Temporary failure in name resolution
  1m		19s		2	{kubelet 192.168.64.2}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "mysql" with ErrImagePull: "Error while pulling image: Get https://index.docker.io/v1/repositories/library/mysql/images: dial tcp: lookup index.docker.io: Temporary failure in name resolution"

  1m	8s	2	{kubelet 192.168.64.2}	spec.containers{mysql}	Normal	BackOff		Back-off pulling image "mysql:latest"
  1m	8s	2	{kubelet 192.168.64.2}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "mysql" with ImagePullBackOff: "Back-off pulling image \"mysql:latest\""
```

**Comment by dims** [comment]
@laugimethods : dumb question again - does "curl https://index.docker.io/v1/repositories/library/mysql/images" work? (trying to tease out if there's a bug in the code)

**Comment by laugimethods** [comment]
@dims:
```
bash-3.2$ curl https://index.docker.io/v1/repositories/library/mysql/images
[{"checksum": "", "id": "326c2d52b176ec389c8d5fcc9d44310b8a214b661f39f6b05a07c715f6936318"}, {"checksum": "", "id": "4543f37883b5b5158b6b11c5420faec6fa5f0913c76b5991f5eb30ebc1c18ffb"}, .... 
```

**Comment by laugimethods** [comment]
(Take note that I'm definitively new to K8s)
I'm using the CLI provided by [Kube-Solo](https://github.com/TheNewNormal/kube-solo-osx).
```
bash-3.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```
I just also tried to deploy an image through the Web Interface... Same issue...

![deployacontainerizedapp](https://cloud.githubusercontent.com/assets/16766201/16091076/0c6750f8-3300-11e6-83f3-a33fb4cf6a5e.png)
<img width="421" alt="myownsql" src="https://cloud.githubusercontent.com/assets/16766201/16091079/1265b148-3300-11e6-9269-278270c438e8.png">

**Comment by dims** [comment]
@laugimethods next logical thing to do is run kubelet with more verbose logs i think.

**Comment by laugimethods** [comment]
@dims Unfortunately Kube-Solo did crash while trying to get more verbose logs and I was not able to recover it (even after a reinstallation)... I'll try to use another tool, which hopefully will solve the Docker image fetching issue. Thanks for your help.

**Comment by NickCao** [comment]
gcr.io is unaccessable in China, please fix that use mirrrors

**Comment by bbnnt** [comment]
Images did got pushed correctly to google container registry

```
docker login -e mygcloud@email.tld -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://eu.gcr.io
```

plus (in case)

```
gcloud auth login
cat ~/.docker/config.json # listing correctly all google registry endpoints
```

then 

```
docker pull eu.gcr.io/my-project-id/my-image # it works superfine
```

Having the kind of following in a kubernetes deployment :

```
kind: Deployment
apiVersion: "extensions/v1beta1"
metadata:
  name: "my-image-app"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "my-image-app"
    spec:
      containers:
      - name: "my-image-app"
        image: "eu.gcr.io/my-project-id/my-image"
        ports:
        - containerPort: some_port
```

and running `kubectl create -f the_file_containing_what-s_above.yaml` followed by `kubectl get pods` always returned some errImagePull 403 unhautorized etc…

Restarted both docker-machine and minikube, in case. same.

People advising above turning to dockerhub, is it the definitive answer ? Or do we all miss something right here ?

**Comment by bbnnt** [comment]
In the end, this SO response was the issue : http://stackoverflow.com/a/36286707/102133
But that's the only place it could clearly be explained

**Comment by buzai** [comment]
@chinglinwen 
thank u repley me .
```
 Type     Reason                 Age                 From                Message
  ----     ------                 ----                ----                -------
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "xtables-lock"
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "lib-modules"
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "kube-proxy-token-zvktx"
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "kube-proxy"
  Normal   BackOff                42m (x4 over 43m)   kubelet, k8s-node3  Back-off pulling image "k8s.gcr.io/kube-proxy-amd64:v1.10.2"
  Normal   Pulling                41m (x4 over 44m)   kubelet, k8s-node3  pulling image "k8s.gcr.io/kube-proxy-amd64:v1.10.2"
  Warning  Failed                 41m (x4 over 43m)   kubelet, k8s-node3  Failed to pull image "k8s.gcr.io/kube-proxy-amd64:v1.10.2": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed                 41m (x4 over 43m)   kubelet, k8s-node3  Error: ErrImagePull
  Warning  Failed                 3m (x158 over 43m)  kubelet, k8s-node3  Error: ImagePullBackOff
```
i had set a proxy for docker, and i can use docker pull some images, but it has a error like this.
i think k8s will sen a request to gcr.io for ensure the image is right?

**Comment by chinglinwen** [comment]
Say kube-proxy-amd64, you can setup https_proxy, run docker pull k8s.gcr.io/kube-proxy-amd64:v1.10.2 ( on every node ),  if pod status doesn't change you can delete that pod, it will re-create it.
