### ISSUE TITLE
the container data lost when restart k8s cluster env

### ISSUE THREAD

**Issue by huangqg** [GoogleCloudPlatform/kubernetes#6893]
hi,
I meet some questions when use kubernetes cluster, please kindly help me if you know the reason.
1.The pod container's data lost when restart k8s cluster, I find replicatorController will create a new pod other than restart the pod container when start the cluster. I set the "restartPolicy" for replicatorController, but failed.

2.how to link containers in k8s? define a service for the pods? it's likely different with docker.

thanks

**Comment by thockin** [comment]
On Wed, Apr 15, 2015 at 8:36 PM, huangqg <notifications@github.com> wrote:
>
> hi,
> I meet some questions when use kubernetes cluster, please kindly help me if you know the reason.
> 1.The pod container's data lost when restart k8s cluster, I find replicatorController will create a new pod other than restart the pod container when start the cluster. I set the "restartPolicy" for replicatorController, but failed.

What do you mean restart the cluster?

> 2.how to link containers in k8s? define a service for the pods? it's likely different with docker.

Links are either containers in a pod or services.  It is different
than plain Docker - this is better :).  Containers in a pod are
tightly coupled and always deployed together.  Services allow for
many-to-one relationships.

**Comment by huangqg** [comment]
1. I mean I shut down the machine, then start it again, the pod will create a new container, not just start the existing one,  so the data will be lost. how to keep replicatorController/pod using the existing container in docker?  does "restartPolicy" helps?

**Comment by thockin** [comment]
Got it.  When a machine goes down the pod should be scheduled somewhere
else in the cluster.  The old machine is dead - how is the data going to
survive?  We don't store everything on a distributed filesystem, by
default.  More than that, though, what you are seeing is part of the
kubernetes semantic.  A pod starts, runs, and dies.  It is not reborn
somewhere else.  If a pod dies, the replication controller creates a new
one - it is not the same identity as the old one.

**Comment by thockin** [comment]
If you do a reboot fast enough, you should see the pod restart on the same machine with volume data surviving (except tmpfs) but the per-container "writeable layer" would be gone.

If anything I think this might be a bug.

@dchen1107 specifically, when a machine is running pod P, then reboots, then still finds pod P is assigned to it, it will also see that it has volumes for P.  But not all volumes can survive reboot - tmpfs won't, and I am not 100% sure that PD or other blockdevs will (I think they will but not sure).  The question is - should they?  Or should kubelet nuke all that state on reboot?  Is it better or worse for pod P to "resume" after reboot with some volumes intact and some not?

**Comment by thockin** [comment]
For example, make /var/lib/kubelet/pods/ be a tmpfs that holds symlinks to real dirs.  That way, when the machine reboots, the symlinks are lost, and kubelet can GC at startup.

/var/lib/kubelet/pods/xyz123 -> /var/lib/kubelet/pod-dirs/xyz123

or better make them bind mounts, so you can just do this at kubelet start:

```
for d in /var/lib/kubelet/pod-dirs/*; do rm -rf $d 2>/dev/null; done
```

Or you could be smarter and safer, but you get the idea. If you don't get what I am asking, let's talk tomorrow :)

**Comment by huangqg** [comment]
thanks thockin, per my understanding, using the persistentVolumes will keep the data if reboot. and the k8s mechanism is: always create new pod and container by replicatorController after reboot.

Ps: thus coming another question, does k8s can collect and remove the dead containers(the garbage) now. 

thanks much.

**Comment by thockin** [comment]
Persistent volumes will actually survive machine outages - they are
explicitly designed to be durable :)

Yes, we do garbage collect old containers on disk.

**Comment by nkwangleiGIT** [comment]
Hi thockin,
About the statement "If you do a reboot fast enough, you should see the pod restart on the same machine with volume data surviving", how do we define 'fast enough" here for k8s, seconds, minutes or hours? :)
And if the pod P was already created on other machines before the dead machine can recover it, how k8s will handle this case?
Anything else you can suggest to keep the data volume always on the same machine as the pod?

Thanks a lot for your help!

**Comment by thockin** [comment]
On Thu, Apr 16, 2015 at 6:25 AM, WangLei <notifications@github.com> wrote:
>
> Hi thockin,
> About the statement "If you do a reboot fast enough, you should see the pod restart on the same machine with volume data surviving", how do we define 'fast enough" here for k8s, seconds, minutes or hours? :)
> And if the pod P was already created on other machines before the dead machine can recover it, how k8s will handle this case?

A machine has a timeout before we can declare it dead and delete all
the pods on it.  If you can reboot in less time than that, it will
come back and find that it is still supposed to be running those pods.
I have not tested this.

**Comment by nkwangleiGIT** [comment]
How about the question below?
"Anything else you can suggest to keep the data volume always on the same machine as the pod?"
After all, any data sensitive application requires to keep the data volume when the app container  will be created anywhere.
Thanks!

**Comment by thockin** [comment]
What you want is PersistentVolumes, which is in development right now.

In the mean time you have 2 options.  You can use a HostPath volume, which
you can reclaim regardless of which pod, as long as it is the same node.
Or you can use something like GCE Persistemt Disk, NFS, iSCSI, AWS EBS, etc
which gives you access to storage that outlives your pod.

**Comment by huangqg** [comment]
thockin, thanks very much for your kindly answers. :-)

**Comment by nkwangleiGIT** [comment]
thockin, thanks for your kindly help, your comments are really helpful for us!

**Comment by thockin** [comment]
You are very welcome, I hope it helps.
