### ISSUE TITLE
Rename PodSpec.Host to PodSpec.NodeName

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#6895]
It's minor, but now that I see it, I can't unsee it.

@bgrant0607

**Comment by bgrant0607** [comment]
We also still have LOTS of references to "minion".

Eventual consistency is the best we can hope for. :-/

**Comment by abonas** [comment]
@thockin you just saved me from opening this exact issue :)

**Comment by ghodss** [comment]
Should it be NodeID or NodeName (whichever it is)? Since Node could imply that it's the whole object.

**Comment by bgrant0607** [comment]
NodeName

**Comment by bgrant0607** [comment]
Part of the v1 API: #7018
