### ISSUE TITLE
kube-proxy makes pods slow?

### ISSUE THREAD

**Issue by wangxin201492** [GoogleCloudPlatform/kubernetes#6903]
I start a pod at minionA ,and the kube-proxy listen it on 60578.
when i visit minionA:60578 in chrome .it costs almost 1s.

and when i visit podIP:80 in chrome .it costs only 40ms maybe.

Does kube-proxy spend more performance,and make webserver slow?

**Comment by erictune** [comment]
@thockin I know you are busy.  Can you suggest someone else that knows networking to have a look at this?

**Comment by thockin** [comment]
@quinton-hoole might be able to help, but this does not at all match my own experience


# iptables-save | grep HOST | grep hostnames
-A KUBE-PORTALS-HOST -d 10.0.245.85/32 -p tcp -m comment --comment "default/hostnames:" -m tcp --dport 88 -j DNAT --to-destination 10.240.105.157:50318

# time curl 10.0.245.85:88
hostnames-tmyim

real	0m0.007s
user	0m0.004s
sys	0m0.000s

# time curl 10.0.245.85:88
hostnames-oar7h

real	0m0.008s
user	0m0.000s
sys	0m0.004s

# time curl 10.240.105.157:50318
hostnames-f0wim

real	0m0.007s
user	0m0.000s
sys	0m0.000s

# time curl 10.240.105.157:50318
hostnames-vquo5

real	0m0.008s
user	0m0.000s
sys	0m0.004s

**Comment by quinton-hoole** [comment]
Sure, I can take a look.

**Comment by quinton-hoole** [comment]
wangxin201492@ could you please try a TCP trace route from the machine you're running chrome on to your minion and pod IP addresses?  traceroute -P tcp should give you what you're after.  I would guess that there is a delay somewhere between you and your pod on your network.

**Comment by wangxin201492** [comment]
traceroute where i run chrome such as following:
[wangxin0@wangxin0 ~]$ sudo traceroute -P tcp 172.20.13.118
traceroute to 172.20.13.118 (172.20.13.118), 30 hops max, 60 byte packets
 1  A  1.142 ms  0.900 ms  1.296 ms
 2  B  0.581 ms  0.439 ms  0.464 ms
 3  C  0.372 ms  0.272 ms  0.333 ms
 4  D  0.904 ms  1.831 ms  0.724 ms
 5  172.20.13.118 (172.20.13.118)  0.554 ms !X  0.437 ms !X  0.475 ms !X

Ase you see:
minionA's ip is 172.20.13.118.

and i run follow at minionA(172.20.13.118):
[root@mobancentos70 ~]# curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n" 172.20.13.118:60578
time_connect: 0.001
time_starttransfer: 1.004
time_total: 1.004
[root@mobancentos70 ~]# curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n" 172.17.0.1
time_connect: 0.001
time_starttransfer: 0.002
time_total: 0.003

why does i get such delay time?
@quinton-hoole

**Comment by wangxin201492** [comment]
and i start kube-proxy using
/usr/bin/kube-proxy --logtostderr=true --v=0 --etcd_servers=http://172.20.13.185:4001

any problems？

**Comment by wangxin201492** [comment]
i get the solution!!
because i start 4 pods at 2 minions,and the pods in 2 minions can't visit each other cross host.
when i request minionA:randomPort ,kube-proxy will try to connect the 4 pods stored in etcd.but the network is unreached.
so i got a delay time.

i resized ReplicationController to 2 and made them in minionA.
now i request minionA:randomPort, the result as follow:

[root@mobancentos70 ~]#  curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n" 172.20.13.118:60578
time_connect: 0.000
time_starttransfer: 0.013
time_total: 0.013
[root@mobancentos70 ~]#  curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n" 172..17.0.1
time_connect: 0.000
time_starttransfer: 0.000
time_total: 0.000

does what i experience true?
and must i make pods visit each other cross host use some other tools such as flennal . ovs ?

**Comment by thockin** [comment]
It is a requirement of kubernetes that Pods on different hosts be able to
ping each other.  Please read docs/networking.md.  Flannel is a good start.

**Comment by wangxin201492** [comment]
thx,i'll have a try! @thockin
