### ISSUE TITLE
Ubuntu 14.04 make release (error)

### ISSUE THREAD

**Issue by jdavidmitchell** [GoogleCloudPlatform/kubernetes#6912]
I downloaded the most recent code from github, and I executed "make release".  The build failed.

It failed on "docker save ${docker_image_tag} > ${1}/${binary_name}.tar" (build/common.sh:621)

# docker info
Containers: 2
Images: 42
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 46
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
WARNING: No swap limit support

# make release
....
+++ [0416 10:39:26] Starting Docker build for image: kube-apiserver
+++ [0416 10:39:26] Starting Docker build for image: kube-controller-manager
+++ [0416 10:39:27] Starting Docker build for image: kube-scheduler
Sending build context to Docker daemon 15.05 MB
Sending build context to Docker daemon
Sending build context to Docker daemon 19.86 MB
Sending build context to Docker daemon
Sending build context to Docker daemon 25.11 MB
Sending build context to Docker daemon
2015/04/16 10:39:39 Error: mkdir /tmp/docker-export-462515189/gcr.io/google_containers/kube-scheduler:ab6feb8cac6a763395c744ff866e4521: no such file or directory
!!! Error in build/../build/common.sh:621
  'docker save ${docker_image_tag} > ${1}/${binary_name}.tar' exited with status 1
Call stack:
  1: build/../build/common.sh:621 kube::release::create_docker_images_for_server(...)
  2: build/../build/common.sh:572 kube::release::package_server_tarballs(...)
  3: build/../build/common.sh:509 kube::release::package_tarballs(...)
  4: build/release.sh:40 main(...)
Exiting with status 1
2015/04/16 10:39:40 Error: mkdir /tmp/docker-export-350534352/gcr.io/google_containers/kube-controller-manager:47b1def5551b4ca0ce7ecd447cdc07da: no such file or directory
!!! Error in build/../build/common.sh:621
  'docker save ${docker_image_tag} > ${1}/${binary_name}.tar' exited with status 1
Call stack:
  1: build/../build/common.sh:621 kube::release::create_docker_images_for_server(...)
  2: build/../build/common.sh:572 kube::release::package_server_tarballs(...)
  3: build/../build/common.sh:509 kube::release::package_tarballs(...)
  4: build/release.sh:40 main(...)
Exiting with status 1
2015/04/16 10:39:40 Error: mkdir /tmp/docker-export-273039343/gcr.io/google_containers/kube-apiserver:9d99764c4d1cf782de2dc0c620bba48b: no such file or directory
!!! Error in build/../build/common.sh:621
  'docker save ${docker_image_tag} > ${1}/${binary_name}.tar' exited with status 1
Call stack:
  1: build/../build/common.sh:621 kube::release::create_docker_images_for_server(...)
  2: build/../build/common.sh:572 kube::release::package_server_tarballs(...)
  3: build/../build/common.sh:509 kube::release::package_tarballs(...)
  4: build/release.sh:40 main(...)
Exiting with status 1
!!! [0416 10:39:40] previous Docker build failed
!!! Error in build/../build/common.sh:599
  '( local binary_name; for binary_name in "${KUBE_DOCKER_WRAPPED_BINARIES[@]}";
do
    kube::log::status "Starting Docker build for image: ${binary_name}"; ( local md5_sum; md5_sum=$(kube::release::md5 "$1/${binary_name}"); local docker_build_path="$1/${binary_name}.dockerbuild"; local docker_file_path="${docker_build_path}/Dockerfile"; local binary_file_path="$1/${binary_name}"; rm -rf ${docker_build_path}; mkdir -p ${docker_build_path}; ln $1/${binary_name} ${docker_build_path}/${binary_name}; printf " FROM scratch \n ADD ${binary_name} /${binary_name} \n ENTRYPOINT [ \"/${binary_name}\" ]\n" > ${docker_file_path}; local docker_image_tag=gcr.io/google_containers/$binary_name:$md5_sum; docker build -q -t "${docker_image_tag}" ${docker_build_path} > /dev/null; docker save ${docker_image_tag} > ${1}/${binary_name}.tar; echo $md5_sum > ${1}/${binary_name}.docker_tag; rm -rf ${docker_build_path} ) &
done; kube::util::wait-for-jobs || { kube::log::error "previous Docker build failed"; return 1; }; kube::log::status "Docker builds done" )' exited with status 1
Call stack:
  1: build/../build/common.sh:599 kube::release::create_docker_images_for_server(...)
  2: build/../build/common.sh:572 kube::release::package_server_tarballs(...)
  3: build/../build/common.sh:509 kube::release::package_tarballs(...)
  4: build/release.sh:40 main(...)
Exiting with status 1
!!! [0416 10:39:40] previous tarball phase failed
!!! Error in build/release.sh:511
  'return 1' exited with status 1
Call stack:
  1: build/release.sh:511 main(...)
Exiting with status 1
make: *** [release] Error 1

docker ps -a
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS                         PORTS               NAMES
498169e06c2b        kube-build:build-8c287   true                About an hour ago   Exited (0) About an hour ago                       kube-build-data-8c287
c3045a0142fd        ubuntu:latest            /bin/bash           About an hour ago   Up About an hour                                   silly_ritchie

**Comment by zmerlynn** [comment]
This is a little disturbing, because you're building in the same docker containers I am, in theory, and getting different results. Looking, since I added the code.

**Comment by zmerlynn** [comment]
I'm having trouble telling from first principals what's going on with your build. We do actually `mkdir -p ${docker_build_path}`, which encompasses `${1}` in the process. It actually seems to be the `docker save` itself that's failing. What version of docker are you trying this with? That could be the divergence.

**Comment by jdavidmitchell** [comment]
apt-cache show docker.io displays two versions of docker.io
1.0.1~dfsg1-0ubuntu1~ubuntu0.14.04.1
0.9.1~dfsg1-2
Initially, I did an "apt-get install docker.io"

David

**Comment by zmerlynn** [comment]
I'm sorry, but I think the problem is that you're running quite an old version of docker. We don't support anything below docker 1.4 right now, and even that's been a rough ride occasionally for people - 1.5 is where all the continuous testing is at right now.

**Comment by jdavidmitchell** [comment]
No problem.  I upgraded to:
ii  lxc-docker                          1.6.0                                amd64        Linux container runtime
ii  lxc-docker-1.6.0                    1.6.0                                amd64        Linux container runtime

I downloaded kubernets into a new folder, and now make release works.

Thanks.

**Comment by jdavidmitchell** [comment]
I spun up a new VM on AWS using ubuntu-trusty-14.04-amd64-server-20150325 (ami-d05e75b8)

I installed the latest version of docker (1.6).

Now, with "build release" I am getting the following:
ok      github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/auth/authenticator/token/tokenfile 0.010s
ok      github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler  0.010s
ok      github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider        0.008s
ok      github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/api/validation   0.006s
ok      github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/factory  0.022s
+++ [0418 15:40:44] Running build command....
FATA[0000] Error response from daemon: Cannot start container e74bd5db59fe376d1f74f4fca8c9b15040409f7c42e319e28d94df04b23093ee: Error getting container e74bd5db59fe376d1f74f4fca8c9b15040409f7c42e319e28d94df04b23093ee from driver devicemapper: Error mounting '/dev/mapper/docker-202:1-398132-e74bd5db59fe376d1f74f4fca8c9b15040409f7c42e319e28d94df04b23093ee' on '/var/lib/docker/devicemapper/mnt/e74bd5db59fe376d1f74f4fca8c9b15040409f7c42e319e28d94df04b23093ee': no such file or directory
!!! Error in build/../build/common.sh:432
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: build/../build/common.sh:432 kube::build::run_build_command(...)
  2: build/release.sh:36 main(...)
Exiting with status 1
make: *** [release] Error 1

**Comment by jdavidmitchell** [comment]
On my second try, it worked.
