### ISSUE TITLE
pkg/kubectl/cmd/config test fails due to reading clusters from my global kubeconfig file

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#6927]
This test has been failing locally for me, displaying some of my actual clusters interspersed with the test clusters. The test's success shouldn't really depend on the files in my environment.

@jlowdermilk

**Comment by yujuhong** [comment]
+1.  Saw this locally as well. Had to delete `~/.kube/.kubeconfig` to pass the test.

**Comment by jlowdermilk** [comment]
I'm unable to repro at head; looking at the test code, I think is fixed as a side affect of #6680. @a-robinson, could you try running `hack/test-go.sh pkg/kubectl/cmd/config` from head and see if you have the same failure?

**Comment by a-robinson** [comment]
Yup, I can confirm it works now, and I haven't changed any of my config files. Thanks!
