### ISSUE TITLE
Fix logrotate.conf for recent podifications

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#6946]
`cluster/saltbase/salt/logrotate/init.sls` says:
```{% set logrotate_files = ['kube-scheduler', 'kube-proxy', 'kubelet', 'kube-apiserver', 'kube-controller-manager'] %}```.

However, kube-scheduler, kube-apiserver, and (soon) kube-controller-manager run in pods so they can't be logrotated.  So:
  1. remove them from the salt file
  1. consider running logrotate as a sidecar within the pod, and perhaps sending them to the logging storage thing if present.

**Comment by ArtfulCoder** [comment]
I will remove this.

The logs from these new pods should be extracted by fluentd just the way users' pods logs get extracted out.

**Comment by ArtfulCoder** [comment]
Currently,  kube-scheduler, kube-apiserver, and  kube-controller-manager run in pods and still write to log files on the host filesystem using mount.
closing this issue.
