### ISSUE TITLE
restart-apiserver function does nothing when apiserver is in a pod

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#6960]
hack/e2e-suite/services.sh is sole caller of restart-apiserver.

It is defined in cluster/*/util.sh

I can't see that the current shell code does anything after the apiserver-in-a-pod changes.

**Comment by erictune** [comment]
Fixed by #7141

**Comment by roberthbailey** [comment]
Ah, I didn't see this when I opened #7120. Closing as a dupe of that issue (which has the relevant PRs linked).
