### ISSUE TITLE
Panic in apiserver

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#6982]
When I've just synced to head I get the following panic in apiserver built from a clean client:

E0417 15:22:34.410713       1 master.go:357] recover from panic situation: - runtime error: invalid memory address or nil pointer dereference
    /usr/src/go/src/runtime/asm_amd64.s:401
    /usr/src/go/src/runtime/panic.go:387
    /usr/src/go/src/runtime/panic.go:42
    /usr/src/go/src/runtime/sigpanic_unix.go:26
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/tools/etcd_helper.go:168
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd/etcd.go:153
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd/etcd.go:142
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:214
    /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:214
    /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:86
    /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19
    /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:216
    /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:90
    /usr/src/go/src/net/http/server.go:1265
    /usr/src/go/src/net/http/server.go:1541
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/handlers.go:227
    /usr/src/go/src/net/http/server.go:1265
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers/handlers.go:47
    /usr/src/go/src/net/http/server.go:1265
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/requestcontext.go:101
    /usr/src/go/src/net/http/server.go:1265
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/requestcontext.go:101
    /usr/src/go/src/net/http/server.go:1265
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/handlers.go:136
    /usr/src/go/src/net/http/server.go:1265
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/handlers.go:80
    /usr/src/go/src/net/http/server.go:1265
    /usr/src/go/src/net/http/server.go:1703
    /usr/src/go/src/net/http/server.go:1204
    /usr/src/go/src/runtime/asm_amd64.s:2232

**Comment by roberthbailey** [comment]
This should be fixed by #6938.
