### ISSUE TITLE
Add support for new Docker 1.6 cgroup parent flag

### ISSUE THREAD

**Issue by guenter** [GoogleCloudPlatform/kubernetes#6991]
Docker 1.6 allows setting the parent cgroup which allows us to set the parent for pods, see #5671

**Comment by guenter** [comment]
I am planning to work on this.

**Comment by ConnorDoyle** [comment]
Could someone add the Mesos integration tag?

**Comment by roberthbailey** [comment]
When you say upgrade the dependency, as you implying that we will only support Docker 1.6+ going forward? I think we have quite a few users that are using older version of Docker on their systems that would still like to run kubernetes.

**Comment by ConnorDoyle** [comment]
@roberthbailey As mentioned in the description, a major motivation is to use the new `--cgroup-parent` flag.  I agree, there's no reason to break compatibility with older versions of Docker.  The docker interface... interface already exposes a `Version()`, so we should be able to detect whether the intalled docker supports the new flags.  @guenter, maybe this issue should be renamed to "Add support for new Docker 1.6 flags".

**Comment by roberthbailey** [comment]
Thanks. Just want to make sure we aren't going to stop supporting older versions.

**Comment by bgrant0607** [comment]
Which use of cgroup_parent do you intend? Just to put a box around all pods run by Kubernetes?

cc @vishh @vmarmol 

See also #147 and #5980.

**Comment by ConnorDoyle** [comment]
@bgrant0607 I think so, provided a top-level container (and a kubelet flag to set it) be a worthwhile first pass compatible with future plans.  WDYT?

**Comment by vishh** [comment]
Our immediate goal are:
1. limit the total resource consumption of all containers that do not have any limits specified (batch), 
2. limit system daemon resources usage.

Pod level resource isolation will land after that. 

IIUC, what is required for Mesos is to configure kubelet to run itself and all the pods under a configurable cgroup hierarchy. That sounds fine.

**Comment by ConnorDoyle** [comment]
@vishh @bgrant0607 cool, I think we're on the same page.

**Comment by bgrant0607** [comment]
Pod limits is #168, btw.

**Comment by guenter** [comment]
Implemented by #7277
