### ISSUE TITLE
Proposal: High Available for Kubernetes Daemons

### ISSUE THREAD

**Issue by rrati** [GoogleCloudPlatform/kubernetes#6993]
@quinton-hoole @lavalamp @bgrant0607 @thockin @davidopp 

#473 #6672 

The associated PR serves as a design proposal for high availability of kubernetes master daemons

**Comment by ConnorDoyle** [comment]
Tracking issue for related scheduler HA work in the Mesos integration (completed): https://github.com/mesosphere/kubernetes-mesos/issues/15

CC @jdef @guenter @joerg84
