### ISSUE TITLE
Create Fluentd image that can be easily used as a sidecar container for collecting log files

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7006]
We should provide a dockerfile for a pre-configured Fluentd image that can be passed file paths to collect logs from. We'll likely want one for exporting to elasticsearch and one for exporting to Google Cloud Logging, as we have today for the per-node stdout/stderr collectors.

How to collect log files from within a container is a question that comes up occasionally (including [a couple days ago](https://groups.google.com/forum/#!topic/google-containers/1o4GWFp3U20)), and it provides a strong example of the usefulness of sidecar containers.

cc @satnam6502 @mr-salty

**Comment by satnam6502** [comment]
A controller that keeps one instance of a pod alive on each node would be useful for this. Shall I go ahead and write such a controller?

**Comment by a-robinson** [comment]
Would it be? This is intended to run as a sidecar container in a pod with the user's actual application. I think a pod-per-node controller is orthogonal (and is being discussed in #1518 and #3058).

I'll create the actual Dockerfile, and a quick example of how to use it.

**Comment by satnam6502** [comment]
Sorry, my rush to catch up I think I mis-understood this thread.
