### ISSUE TITLE
e2e test pod update test flaw

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#7013]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/pods.go#L304

This is wrong because something else could have updated the pod in the mean time, invalidating your resource version. (Specifically, kubelet writes statuses.) It should do a get/update loop that retries as long as it gets a conflict error.

@quinton-hoole to find an owner

**Comment by quinton-hoole** [comment]
PR almost ready - just struggling to get e2e tests to run :-)

**Comment by quinton-hoole** [comment]
At last.
SUCCESS! -- 5 Passed | 0 Failed | 1 Pending | 34 Skipped I0424 09:04:47.963304   90988 driver.go:96] All tests pass
PR incoming in a few minutes.
