### ISSUE TITLE
Create the v1 API

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#7018]
We're still finishing loose ends on v1beta3, but we need to clone it into the v1 API soon, and stop making breaking changes to v1beta3. As with v1beta3, v1 shouldn't be exposed by default and shouldn't be the latest API version until we freeze it.

**Comment by thockin** [comment]
Do we have a list of candidate changes for v1 as compared to v1b3?

**Comment by bgrant0607** [comment]
Mostly this is intended to be a rename of the API.

Possible changes:
* cleanup ContainerStatus/ContainerState (`s/termination/terminated/`, reconsider use of "State", key vs. value #6979)
* eliminate Phase #6951
* eliminate most volume sources
* split API into multiple prefixes #3806

**Comment by thockin** [comment]
Can I add "make some optional fields into pointers for clearer denotation" ?

I am torn on volume sources.  I am reviewing PV stuff still, I am just
nervous about how new it is..

**Comment by derekwaynecarr** [comment]
I would like to see us support 

delete /namespace/foo/pods

This would delete all pods in namespace foo.

It would literally delete the folder node that contained all pods in that namespace in etcd.

**Comment by bgrant0607** [comment]
Maybe another pass on /containerstatuses, which was prematurely merged #6597.

**Comment by bgrant0607** [comment]
We shouldn't need to wait until v1 in order to change the Go structs.

**Comment by thockin** [comment]
I was specifically thinking about #6735 which would change the default
value of replication controller.

**Comment by bgrant0607** [comment]
Ah right, default of 1 replica rather than 0 replicas.

There's also the issue of changing the default cleanup behavior of replication controllers, as discussed in https://github.com/GoogleCloudPlatform/kubernetes/issues/1535#issuecomment-91413501

**Comment by bgrant0607** [comment]
Deduplication of SecurityContext-related fields (#6287) in Pod. cc @erictune

**Comment by bgrant0607** [comment]
StatusDetails ID field should be name: #7333

**Comment by thockin** [comment]
ServiceStatus should have a Phase

**Comment by bgrant0607** [comment]
Or nothing should have a Phase. :-)

**Comment by bgrant0607** [comment]
As suggested in #6910, perhaps we should eliminate the term "portal".

**Comment by thockin** [comment]
VIP ?  But it might not always be Virtual - you could imagine an "internal"
load balancer that worked better - HAProxy or something - and using real
IPs.  Just IP, maybe?

**Comment by thockin** [comment]
#6979 proposes rejiggering some of the named-one-of fields.  better API, but requires cusotm JSON unmarshalling code.

**Comment by bgrant0607** [comment]
Another possible issue: expanded image spec: #7203

**Comment by bgrant0607** [comment]
api.Pod.Host vs. Node: #6895

**Comment by bgrant0607** [comment]
Generalized label selectors: #7053 / #341

**Comment by bgrant0607** [comment]
Created a new issue for replacement of phase with condition: #7856.

**Comment by bgrant0607** [comment]
Clarification: Replacement of phase is almost certainly out for v1. I just referenced it for completeness.

**Comment by bgrant0607** [comment]
We might want to reconsider use of ObjectReference in the API.

For cases in object specs where kind, namespace, and api version are fixed and where uid, resource version, etc. aren't supported for stronger consistency, it's simpler to just specify an object name, as in the service account PR: #7101.

I still feel that ObjectReference is probably easier for clients to deal with generically when comprehending objects, though, so we should use it in status, where necessary.

**Comment by bgrant0607** [comment]
Load balancer changes: #7447

**Comment by bgrant0607** [comment]
Any PV/PVC changes: #7438.

**Comment by bgrant0607** [comment]
We're very inconsistent on naming of time-related fields -- search for util.Time.
* FooTimestamp: CreationTimestamp, DeletionTimestamp, FirstTimestamp, LastTimestamp
* FooTime: LastHeartbeatTime, LastTransitionTime
* FooAt: StartedAt, FinishedAt

"Time" seems best.

**Comment by bgrant0607** [comment]
Speaking of which, there's also the proposal to use time.Duration: #6013. That's not just a rename, though.

**Comment by rjnagal** [comment]
Replication controller default to 1: #6700 - requires breaking change to make the field a pointer.

**Comment by sym3tri** [comment]
- More filtering options for Events (e.g. by start & end timestamps, by resource id, by event type)
- Ability to Watch more than one resource type (https://github.com/GoogleCloudPlatform/kubernetes/issues/1685)
- Swagger Sepc: Fix all descriptions (specifically incorrect enum names), erroneous `required` param values, etc.
- Allow deep field selectors, e.g. for events: `source.host=xxx` (this may work now, but did not when last tried)
- ReplicationControllerStatus only contains number of replicas. Action state would also be nice (e.g. "replicating", "deleting", "ok")

**Comment by bgrant0607** [comment]
Field selectors is #1362

**Comment by sym3tri** [comment]
Also in the watch APIs...

A *resourceVersion* can be provided to watch from, which is great. Each object in the stream has a *resourceVersion*, but with lists of resources there's no way to know what version the list watcher is currently on. So if my websocket gets disconnected I may want to auto-reconnect and watch from the last received *resourceVersion* (of the list itself, not the objects within).

For example with `/pods?watch=true`
The current payload looks like:
```
{
  "type": "MODIFIED",
  "object": {...}
},
{
  "type": "MODIFIED",
  "object": {...}
}
```

I propose the addition of a *resourceVersion* to each watch event:
```
{
  "resourceVersion": "123",
  "type": "MODIFIED",
  "object": {...}
},
{
  "resourceVersion": "122",
  "type": "MODIFIED",
  "object": {...}
}
```

**Comment by derekwaynecarr** [comment]
Given the TTL limits on events, do we need to promote as much in the Api for filtering for v1?  Is the filtering to support a specific describer?

**Comment by ae6rt** [comment]
Sorry if this observation is too small for inclusion here, or if this is by design, but should the name of the JSON node for the field Conditions in PodStatus here

https://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3#PodStatus

be named "condition" and not "Condition".   I found the uppercase Condition to be surprising, as other nodes tend to have lowercase names.

**Comment by bgrant0607** [comment]
@ae6rt See #8052

**Comment by bgrant0607** [comment]
Finish standalone pod templates or remove them for now: #170, #8109.

**Comment by bgrant0607** [comment]
@sym3tri Previous discussion of watch versioning was #6480. Agree that current solution has issues. If an object is actually modified, the resourceVersion will be contained in the object's metadata. The bigger problem is the case where it isn't modified, in which case the client isn't notified that the sequence has advanced.

**Comment by bgrant0607** [comment]
We've also discussed per-object sequence numbers for RAW and WAW consistency: #7328

**Comment by sym3tri** [comment]
> Given the TTL limits on events, do we need to promote as much in the Api for filtering for v1?  Is the filtering to support a specific describer?

I guess I lack some of the context around the event TTLs and the future plans. Mostly what I want to do is list events only for specific pods, nodes, label queries etc.

**Comment by bgrant0607** [comment]
Reconsider command vs. entrypoint: #8235

**Comment by bgrant0607** [comment]
Rename "createExternalLoadBalancer": #4811

**Comment by bgrant0607** [comment]
Secret key validation: #8236

**Comment by bgrant0607** [comment]
Some discussion on ObjectReference vs. names started here: https://github.com/GoogleCloudPlatform/kubernetes/pull/7974#issuecomment-102199970

An argument could be made that any cross reference that doesn't need more than name (e.g., namespace, kind, field) should just be a name. ServiceAccount.Secrets, ReplicationControllerSpec.TemplateRef, and Binding.Target would likely change in that case. But it would require more intelligence in code that was trying to understand object relationships.

I'd be more inclined to go the other direction: Pod.Host and Pod.ServiceAccount would become ObjectReferences, as would PersistentVolumeClaimVolumeSource.ClaimName, GlusterfsVolumeSource.EndpointsName, and SecretVolumeSource.SecretName. In PersistentVolumeClaimVolumeSource and SecretVolumeSource the ObjectReferences could be inlined, since there isn't much else in those structs. Namespace, APIVersion, and Kind would be filled in by default. Kind and APIVersion would need to be converted to the appropriate API version.

Obviously this would be much more verbose, but would be more consistent and simpler for clients.

Another consideration: We've discussed using multiple API prefixes/groups (#3806) and possibly even into higher-level groupings (https://github.com/GoogleCloudPlatform/kubernetes/issues/7111#issuecomment-97461106).

* Pods, Secrets, and PersistentVolumeClaims are end-user core objects, albeit low-level ones.
* Services are more directly end-user-facing core objects, at least for now. They'll somehow need to span multiple clusters, though.
* Controllers such as ReplicationController will be plugins. Deployment may need to be multi-cluster.
* Endpoints and Events are relevant to users, but they won't typically create them or even look at them directly.
* Namespace, LimitRange, ResourceQuota, and ServiceAccount are the purview of app admins.
* Node and PersistentVolume are cluster admin / infrastructure.

Regardless what the precise breakdown is, ObjectReference seems even more appropriate for cross-apigroup references.

We could also create a slimmed-down ObjectReference (no uid, resourceVersion, field) for non-event cross references.

**Comment by markturansky** [comment]
Inlined object references are nice.  It removes a redundant word from at least these two:

```
persistentVolumeClaim.claimName
persistentVolumeClaim.Name

secret.SecretName
secret.Name
```

Inlining makes it seem like you're dealing directly with Secret or PVC instead of a volume.

**Comment by bgrant0607** [comment]
Changes I think we should make in v1, which should all be pretty easy and the cost will be too high to change them later:
* Default ReplicationControllerSpec.Replicas to 1: #6700
* Dedupe fields that are in SecurityContext: #8298
* StatusDetails ID field should be name: #7333
* api.Pod.Host should be changed to Node: #6895
  * Change to ObjectReference TBD
* Time field cleanup (suggest "Time" rather than "Timestamp" or "At"): https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-99749177
* Cleanup ContainerStatus/ContainerState: `s/termination/terminated/`, reconsider use of "State", key vs. value #6979
* Finish standalone pod templates or remove ReplicationControllerSpec.TemplateRef for now: #170, #8109
* Secret key validation: #8236

Other changes I'd like to see:
* Generalized label selectors -- I think this is now or O(never), since it breaks all API versions: #341
* Service changes
  * PublicIPs mitigation (and maybe deprecation, with or without replacement): #8139
  * createExternalLoadBalancer rename: #4811, but aligned with the direction we decide for #7447
  * rename "PortalIP": #6910
  * whatever other parts of #7447 that overlap with current functionality, so that the rest can be added later
* Expanded image spec: #7203

I need to think more about ObjectReference vs name.

Elimination of volume sources and creation of multiple api prefixes are punted to v2 #8190. Phase elimination and time.Duration -- not now. Changes that can be made in a backward-compatible fashion can be done later.

**Comment by bgrant0607** [comment]
Resolution on names vs. ObjectReference:
* Existing names will use the pattern KindName. So, PodSpec.Host will become PodSpec.NodeName.
* After v1, we'll add specialized versions of ObjectReference with just the necessary fields, similar to ObjectFieldSelector
* We can then add additional fields of these specialized types in a backward-compatible manner.

**Comment by bgrant0607** [comment]
And, require explicit namespace creation (though this affects all api versions).
`s/NamespaceAutoProvision/NamespaceExists/`
in all the places that configure admission control plugins.

**Comment by bgrant0607** [comment]
Container image rep is #8702

**Comment by bgrant0607** [comment]
#6700, #8298, and #7333 are done.

The service changes are going in today and/or Tuesday.

I think we have to punt on the Time field cleanup.

**Comment by bgrant0607** [comment]
@sym3tri Events support more sophisticated filtering than other objects already.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/event/rest.go#L126
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/events_test.go#L36

**Comment by bgrant0607** [comment]
#6895 is in progress.

**Comment by bgrant0607** [comment]
PortalIP rename is in the merge queue: #8740

**Comment by bgrant0607** [comment]
There's no way we can finish it, but we need to wean ourselves off "minion": #1111

**Comment by bgrant0607** [comment]
A number of tests that currently test v1beta1 need to be updated to test v1. For example:
pkg/api/serialization_test.go

**Comment by bgrant0607** [comment]
Generalized label selector (#341) is punted to v2.

**Comment by bgrant0607** [comment]
v1 is enabled by default, is the preferred API version, and is tested as much as v1beta3.

Docs/examples are covered by #9286.
