### ISSUE TITLE
Want create-or-update command for kubectl

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#7047]
If you want to build a shell script to reconcile a config file with the state on the apiserver, it is convenient to be able to do "create or update" in a single command.

**Comment by bgrant0607** [comment]
See also #1702

**Comment by JeanMertz** [comment]
:+1: for this.

I'm using something like this:

```bash
#!/bin/sh
set -e

if [ "$1" = "rc" ]; then
  kubectl get rc "$2" &>/dev/null
  if [ "$?" = "0" ]; then
    echo "$3" | kubectl rolling-update "$2" -f -
  else
    echo "$3" | kubectl create -f -
  fi
elif [ "$1" = "service" ]; then
  kubectl get service "$2" &>/dev/null
  if [ "$?" = "0" ]; then
    echo "$(kubectl get service "$2" -o json)" | kubectl update -f -
  else
    echo "$3" | kubectl create -f -
  fi
fi
```

**Comment by bgrant0607** [comment]
In addition to declarative config (#1702), we also plan to make PUT create or update in the API -- #2114.

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by bgrant0607** [comment]
Closing as redundant with the other 2 issues I cited above.
