### ISSUE TITLE
Want to pull logs from master components, but node not found

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#7049]
```
$ kubectl log kube-apiserver-kubernetes-master kube-apiserver
Error from server: minion "kubernetes-master.c.causal-jigsaw-637.internal" not found
```

That is because we don't register the master node.
We should register the master node, but somehow make it unable to schedule normal work, such as marking it unschedulable.

**Comment by erictune** [comment]
@ArtfulCoder who worked on the apiserver in a pod

@roberthbailey who is working on node registration.

**Comment by dchen1107** [comment]
This is a known issue: #6428
