### ISSUE TITLE
API server should export usage metrics

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#7069]
Feature request: it'd be nice to have apiserver export various API usage metrics.
- How many QPS each client-id is generating.
- How many QPS of each request and resource type (possibly broken down by client-id to differentiate between various automated components and external users?)
- Time since (or timestamp of?) last API call by a client id.

Filing this as a tracking item -- feel free to add more in.

@a-robinson was adding similar things, I think?  Perhaps we already have most of the above?

**Comment by wojtek-t** [comment]
cc @fgrzadkowski

**Comment by a-robinson** [comment]
We have QPS per request and resource type, but nothing by client ID at the moment.

**Comment by fgrzadkowski** [comment]
I've added this locally for my experiments, so I can sens a PR with this.

-- sent from a mobile device
21 kwi 2015 19:24 "Alex Robinson" <notifications@github.com> napisał(a):
