### ISSUE TITLE
Update Condition-related description tags

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#7085]
PodCondition and NodeCondition description strings were not updated when changing Full/None to True/False, nor when removing the Schedulable condition.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L746
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1140

cc @davidopp @gmarek

**Comment by ddysher** [comment]
part of it is leftover from my previous pr.  I'll do a quick clean up.
