### ISSUE TITLE
Why pull from "gcr.io" registry when I create pod?

### ISSUE THREAD

**Issue by lokikiller** [GoogleCloudPlatform/kubernetes#7090]
I appointed the key-values as follows:
"image": "docker.io/redis"

and the minion also have the redis image

but when I cat the logs:
"Failed to create pod infra container: image pull failed for gcr.io/google_c..."

I can't understand it

**Comment by roberthbailey** [comment]
If you want to pull an image from the public dockerhub, you don't need to add a domain name prefix. You can just say "image": "redis".

**Comment by lokikiller** [comment]
thanks for your answering, but it also can not take effect when i change it to "image":“redis”, it also pulling from gcr.io @roberthbailey

**Comment by fgrzadkowski** [comment]
For each pod we also create an infra container that is used to workaround some docker limitation. This artificial container uses image gcr.io/google_container/pause:go (or something similar). From your error message I assume this step failed. Do you have some more logs about this failure?

**Comment by lokikiller** [comment]
As you say, I see the logs carefully, and find it really the "gcr.io/google_container/pause" image can not pull, is there any other way to pull the image? @fgrzadkowski Thanks a lot

**Comment by fgrzadkowski** [comment]
What's your environment? Where do you start your cluster?

**Comment by lokikiller** [comment]
I am in China, the environment is in my laboratory with some Blade servers using centos7.

**Comment by fgrzadkowski** [comment]
Can you ping gcr.io? This seems similar to https://github.com/GoogleCloudPlatform/kubernetes/issues/6888

**Comment by lokikiller** [comment]
Thank you very much~ @fgrzadkowski

**Comment by gl328518397** [comment]
这是docker的日志：
Oct 11 16:13:52 mg1 docker-current: time="2016-10-11T16:13:52.267336913+08:00" level=error msg="Handler for GET /images/gcr.io/google_containers/pause-amd64:3.0/json returned error: No such image: gcr.io/google_containers/pause-amd64:3.0"
Oct 11 16:13:58 mg1 docker-current: time="2016-10-11T16:13:58.267522810+08:00" level=error msg="Handler for GET /images/gcr.io/google_containers/pause-amd64:3.0/json returned error: No such image: gcr.io/google_containers/pause-amd64:3.0"
Oct 11 16:14:06 mg1 docker-current: time="2016-10-11T16:14:06.267927214+08:00" level=error msg="Handler for GET /images/gcr.io/google_containers/pause-amd64:3.0/json returned error: No such image: gcr.io/google_containers/pause-amd64:3.0"
Oct 11 16:14:12 mg1 docker-current: time="2016-10-11T16:14:12.272394436+08:00" level=error msg="Handler for GET /images/gcr.io/google_containers/pause-amd64:3.0/json returned error: No such image: gcr.io/google_containers/pause-amd64:3.0"

**Comment by pigletfly** [comment]
@gl328518397  ```gcr.io``` is blocked by GFW

**Comment by ledzep2** [comment]
When you start kubelet you can specify an alternative pause image using `--pod-infra-container-image=`. I uploaded a copy of pause to Aliyun China registry sometime ago. You can use it if you want. The address is `registry.aliyuncs.com/archon/pause-amd64:3.0`

**Comment by upccup** [comment]
@fgrzadkowski sorry to bother you

is there way wirh not  create an infra container that is used to workaround some docker limitation?

**Comment by fgrzadkowski** [comment]
AFAIK it's not possible.

**Comment by gbraad** [comment]
Just for information, the following discussion was related: https://stackoverflow.com/questions/29764612/failed-to-pull-images-from-dockerhub-in-kubernetes-0-15

The OP is in China and can therefore not pull from gcr.io (as this is hosted by Google), thanks to the GFW.
