### ISSUE TITLE
PreStop in Lifecycle does not work

### ISSUE THREAD

**Issue by njuicsgz** [GoogleCloudPlatform/kubernetes#7091]
PreStop in Lifecycle is a very excited feature that I want it so much. With it, I can do some clean work before killing the Pod/Container, for example, I need this container stop receiving requests first, then complete processing its requests already received before it is killed. However It does not work as PostStop now. And I have checked the latest code and found it is still not implemented. Could anyone give a time point on it?

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L843

**Comment by bgrant0607** [comment]
Sorry, prestop hasn't been implemented yet. See discussion in #6804.

**Comment by piosz** [comment]
I'll implement it once #6804 is finished

**Comment by njuicsgz** [comment]
thanks, I will also subscribe #6804

**Comment by davidopp** [comment]
Moved to post-1.0

**Comment by bgrant0607** [comment]
PR #7421 is in flight.

**Comment by brendandburns** [comment]
#7421 was merged.  We should add an e2e test, though.

**Comment by njuicsgz** [comment]
Tried by E2E, it works! And it can be closed.
Well done.
