### ISSUE TITLE
Update accessing-the-cluster.md

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#7094]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/accessing-the-cluster.md is out of date. Please update for the current location/contents of the `kubeconfig` file and v1beta3. Once #6618 is submitted we should also update the examples to show to to curl using bearer tokens instead of basic auth credentials.

**Comment by bgrant0607** [comment]
We're working on scrubbing the docs and examples of references to v1beta1 (#6584) prior to deleting that API, so it would be good to have this in soon.

**Comment by satnam6502** [comment]
@jlowdermilk : let me know if you want to punt this back to me -- now that I have some clue again about how to access an cluster (assuming I can _create_ a cluster!).

**Comment by jlowdermilk** [comment]
Punting back to you. Getting the auth credentials is accomplished via
```
$ kubectl config view --minify --context=$CONTEXT
```
But I think you have a better idea how to curl with token auth than I do.
