### ISSUE TITLE
service-create API failed with v1beta3 request format on Kubernetes 0.11.0 release

### ISSUE THREAD

**Issue by madhuri-rai07** [GoogleCloudPlatform/kubernetes#7157]
When trying to create service with v1beta3 request format on Kubernetes 0.11.0 release, it failed with below error.

$ kubectl create -f v1beta3_service.yaml
F0422 09:10:55.645949   32648 create.go:83] Service "frontend" is invalid: spec.port: invalid value '0': must be greater than 0 and less than 65536

$ cat v1beta3_service.yaml
{
"kind":"Service",
"apiVersion":"v1beta3",
"metadata":{
"name":"frontend",
"labels":{
"name":"frontend"
}
},
"spec":{
"ports": [
{
"port":80,
"targetPort":80,
"protocol":"TCP"
}
],
"selector":{
"name":"frontend"
}
}
}

**Comment by fabioy** [comment]
Can you try it with the "--api-version=v1beta3" flag? Also, even though the file extension is .yaml, you meant it to be JSON, right?

**Comment by nikhiljindal** [comment]
This works fine on head. 0.11 does not fully support v1beta3.
Its supported after v0.15+
