### ISSUE TITLE
Too much time spent in net.(*netFD).dial

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#7160]
When evaluating results of #6877 I have noticed a very strange behavior of apiserver when running density tests on a 100 node cluster with 30 pods per node. It seems that sometimes we spent more than 40% of CPU time in net.(*netFD).dial function.

My suspicion is that it's because after each watch message we terminate old connection to etcd and create a new one. With multiple watchers and many update this can be very expensive.

@davidopp @lavalamp @wojtek-t @xiang90

**Comment by fgrzadkowski** [comment]
![net_profile](https://cloud.githubusercontent.com/assets/10820726/7273675/6aecc626-e8f6-11e4-8c22-e1b463d32af8.png)

**Comment by lavalamp** [comment]
Does the etcd client not reuse HTTP connections? I thought the go http client did that by default?

**Comment by lavalamp** [comment]
Actually looking at that chart I see it stuck in write, not dial-- am I blind?

**Comment by xiang90** [comment]
@lavalamp I think it is write... The number on dail is confusing though...

**Comment by fgrzadkowski** [comment]
@lavalamp There is a small, but very heavy branch on the left of the chart with "dial" path".

**Comment by xiang90** [comment]
@fgrzadkowski But it shows `0.03s of 22.90s`. It does not show where is the other 22.87s.

**Comment by fgrzadkowski** [comment]
@xiang90 The way I read this profile (might wrong though) is that for 28.90s dial was in the stack, but was not the "top" function for 22.87s

@lavalamp I tried to verify that etcd client reuses HTTP connection and I think it doesn't. I added simple log line here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go#L387
In empty 100 node cluster it got called ~10k times in ~3.5 min. This gives 45 dials per second
@xiang90 Do you have a theory why we create so many connections? After adding cache in #7288 this is responsible for a biggest chunk of CPU time.

**Comment by fgrzadkowski** [comment]
I also run density test to check how correlated this is with the load. Results below (first column is number of dials per minute, second column is time):

$ sudo docker logs a9374dd44497 2>&1 | grep FFF | tr -s " " | cut -d" " -f 2 | cut -d":" -f-2 | sort | uniq -c
   1839 13:12
   4737 13:13
   1942 13:14
   1184 13:15
    836 13:16
    949 13:17
   1360 13:18
    880 13:19
    770 13:20
   1127 13:21
    682 13:22
  18953 13:23
  34813 13:24
  22377 13:25
  29917 13:26
  25207 13:27
  22117 13:28
  22701 13:29
  22060 13:30
  24797 13:31
  22575 13:32
  23313 13:33
  22190 13:34
  23338 13:35
  22061 13:36
  24249 13:37
  22953 13:38
  24566 13:39
  21788 13:40
  18880 13:41
  26141 13:42
  24083 13:43
  22552 13:44
   1314 13:45
    244 13:46

Performance test started at 13:23 and finished around 13:44. Correlation is quite obvious. Note also that in the peak it was generating 560 dials per second!

**Comment by wojtek-t** [comment]
@xiang90 @lavalamp 

I think that we have a victim for it. What we've done is that we changed the Transport in go-etcd client:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go#L194
but setting:
MaxIdleConnsPerHost: 10000 (from default 2)

**This speeded up the test by ~35%**
I think that 10000 is some exaggeration, but it definitely proves that increasing this value solves the problem.

My hypothesis why it solves the problem:
1. we have 100 opened watches( watching for the same changes (which definitely happens in 100-node cluster) and all of them are from apiserver (a single client)
2. a change that is interesting is written to etcd
3. etcd is responding to all of them at the same time
4. all those connections become iddle (or most of them) before the new request is send, and thus most of them are closed (we can have only 2 of them opened for a single client)
5. for the next requests within a watch we need to create new connections

**Comment by fgrzadkowski** [comment]
Number of dials after change described by @wojtek-t :+1: 

~$ sudo docker logs 6c7a949241ff 2>&1 | grep FFF | tr -s " " | cut -d" " -f 2 | cut -d":" -f-2 | sort | uniq -c
    335 14:29
    200 14:30
      5 14:31
     28 14:32
     65 14:33
    145 14:34
     69 14:35
    121 14:36
     59 14:37
    202 14:39
    140 14:40
    112 14:42
     77 14:43
    190 14:44
    104 14:45
      5 14:46
      4 14:47

(this includes run of performance test)

**Comment by wojtek-t** [comment]
Just a silly question: are we allowed to change files under Godeps/ directory? If not what is the best way to fix it?

**Comment by xiang90** [comment]
@wojtek-t Call https://github.com/GoogleCloudPlatform/kubernetes/blob/master/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go#L178 instead.

**Comment by xiang90** [comment]
@fgrzadkowski @wojtek-t is probably right. If you only use one transport, there is a maxIdelConn limitation.

**Comment by wojtek-t** [comment]
thanks @xiang90 !
Assigning to myself - I will prepare a PR for it.

**Comment by lavalamp** [comment]
@wojtek-t cool, this is great. 10000 max idle is probably a little high-- we don't want to use all of apiserver's available FDs for this. Does, say, 500 still get most of the benefits?

(I think if we multiplexed watches that might also help a lot, but obviously it's much easier to keep more idle connections.)

(If you really had needed to modify a file in the godeps/ directory, the proper way to do that is to send a PR to the downstream repo, and the update the dependency once they accept it.)

**Comment by wojtek-t** [comment]
>
@wojtek-t cool, this is great. 10000 max idle is probably a little high-- we don't want to use all of apiserver's available FDs for this. Does, say, 500 still get most of the benefits?

I completely agree 10000 is too much. I didn't have time to make more experiments today, but my feeling is that 500 or 1000 should also be enough. I will come up with more accurate number on Monday.

>
(I think if we multiplexed watches that might also help a lot, but obviously it's much easier to keep more idle connections.)

Yes - but this would be much bigger change. I don't think it's worth doing now.

>
(If you really had needed to modify a file in the godeps/ directory, the proper way to do that is to send a PR to the downstream repo, and the update the dependency once they accept it.)

It seems it's ot needed. We just need to initialize the client properly. I will create a PR for it.
