### ISSUE TITLE
Slow list makes it impossible to start watching

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#7162]
If a list operation takes long time it's impossible to start watching, because our resource versions is already out of etcd buffer.

I observed this in 100 node cluster with 3000 pods. As a result we kubelets were continuously sending pod lists, which are insanely expensive making apiserver even more overloaded. I observed many pod lists to take more than 30s:

I0422 14:08:01.783828       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-hvgh: (42.808459681s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.17
I0422 14:08:01.812388       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-jh7f: (43.756788196s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.96
I0422 14:08:01.813304       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-y1m8: (41.041777437s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.24
I0422 14:08:01.901427       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-8e7t: (43.461893075s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.33
I0422 14:08:01.941860       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-qy86: (41.648806735s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.25
I0422 14:08:01.996754       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-8w3j: (43.801560116s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.87
I0422 14:08:02.068549       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-cdo0: (37.313218617s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.21
I0422 14:08:02.175080       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-2npx: (44.088909018s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.25
I0422 14:08:02.186602       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-nyjl: (43.894586081s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.13
I0422 14:08:02.223779       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-minion-rs0k: (35.839257952s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.21
I0422 14:08:02.264810       1 handlers.go:137] GET /api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-master: (38.060668477s) 200 [[kubelet/v0.15.0 (linux/amd64) kubernetes/21788d8] 10.240.109.214

In those 30 seconds it's not that hard to generate 1000 changes in etcd (e.g. 100 nodes updating status every 10 s gives 300 updates in that time).

I see two options:
1. Increase buffer size in etcd (10'000?)
2. Make list much faster (hard)

Any other ideas are welcomed :)

**Comment by fgrzadkowski** [comment]
@wojtek-t @davidopp @lavalamp

**Comment by wojtek-t** [comment]
cc @xiang90 
1. Has anyone ever measured the impact on memory (and possibly on performance) of increasing buffer side of etcd to 10000 in Kubernetes?

2. The whole #6800 effort should significantly help with it.

**Comment by lavalamp** [comment]
etcd's buffer size is hard-coded and not parameterizable IIRC, we'd need a new build.

But I think that's the wrong way to fix this. We have to get this number down. I think we can either cache/index, or we could also consider serving all outstanding pod list requests with the result of the etcd list. So a batching system where instead of doing an etcd list per request, we only allow one concurrent list-- everyone else waits. This would at least reduce load.

@fgrzadkowski could you do some stats on that log file? like what is the median and 95th percentile amount of time for a list? Just so we know how bad this problem is.

**Comment by xiang90** [comment]
@lavalamp 

In the future, etcd needs to solve this problem completely. We will keep entire history until a user-driven compaction. We are actively working on it.

But in the current design, increasing the 1000 limitation is not helpful. (You can image that someone wants to have 100k soon. The memory overhead and snapshot pausing is huge right now, it can easily kill today's backend). 

@wojtek-t If you really need a quick fix to reach the short-term goal, yea, probably we can give it a try.

**Comment by lavalamp** [comment]
@xiang90 Yeah, that's what I thought, thanks for confirming.

@fgrzadkowski I thought of another way to possibly ameliorate this. What if we made a type that just unmarshalled the labels. Then a list would only need to fully unmarshall and convert only the desired objects. Since conversion is probably the majority of the time and each of these lists is actually only interested in a few objects, that might speed it up a lot?

**Comment by smarterclayton** [comment]
Also we are *forcing* lists every 5 minutes right now, where we probably don't want to.

**Comment by derekwaynecarr** [comment]
Are we locked to keeping NodeCondition.LastHeartbeatTime in etcd?  Could we keep that in a separate in-memory cache, and only update NodeCondition.Status in etcd if the node's status actually changed?  Would that keep writes down?

**Comment by bprashanth** [comment]
Why not just setup reflectors in the apiserver for all pods/nodes and serve from this? I relize this is very similar to the index discussed, but feels easier to just plug in. 
fyi https://github.com/GoogleCloudPlatform/kubernetes/issues/6770

**Comment by wojtek-t** [comment]
>
But in the current design, increasing the 1000 limitation is not helpful. (You can image that someone wants to have 100k soon. The memory overhead and snapshot pausing is huge right now, it can easily kill today's backend).

If the overhead is huge now (that's unfortunately what I expected), I think we shouldn't do it (at least for now). I agree with others that we have different ways to go.

**Comment by timothysc** [comment]
@bprashanth if you served out of reflectors on the apiserver, what would happen if you we're running many api-servers, that would be a heck of a lot of updates.

**Comment by timothysc** [comment]
Doesn't this just boil down to write-through semantics, and hot-tracking/smart caching in etcd itself?

**Comment by fgrzadkowski** [comment]
I'm working on a simple cache (similar to #6678, but simpler) to see if it helps. I should have a working version tomorrow.

**Comment by lavalamp** [comment]
@fgrzadkowski please tag me in your cache PR :)

**Comment by lavalamp** [comment]
The thing @bprashanth is talking about *might* be possible, but you'd have to take extremely great care to provide correct ResourceVersion values for the list. The value must have the property that if a client watches with that ResourceVersion, it is *guaranteed* not to miss any updates to any of the items in the list. Or another phrasing, when you return a list to a client, none of the objects may have changed between the object's ResourceVersion, and the list's resource version.

This might be an easier requirement to satisfy with a cache.

**Comment by fgrzadkowski** [comment]
Thanks to all recent performance-related changes (faster conversions, etcd cache, fixed too many dials) lists are now much faster (few seconds at most).

Fixed.
