### ISSUE TITLE
Kibana dashboard broken since basic auth turned off and won't work with proxy

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7196]
I turned up a cluster and did

```
$ ./cluster/kubectl.sh proxy
Starting to serve on localhost:8001

```

and then I tried to visit http://localhost:8001/api/v1beta1/proxy/services/kibana-logging/ but I got a broken window which fails in the same way as when the trailing slash is missing from the URL. So right now Kibana access is logs is broken.

@roberthbailey

**Comment by satnam6502** [comment]
Grafana UI is also broken in a similar way.

**Comment by bgrant0607** [comment]
Team? Milestone?

**Comment by satnam6502** [comment]
Visiting the v1beta3 URL http://localhost:8001/api/v1beta3/proxy/namespaces/default/services/kibana-logging I got a bit further but this still fails because in the browser Kibana wants to connect to the service proxy running at the master.

**Comment by zmerlynn** [comment]
To clarify, the problem here is just the UIs, right? The elasticsearch e2e seems to be fine.

**Comment by vishh** [comment]
Yes. Intra-cluster access via the apiserver proxy works AFAIK!

**Comment by satnam6502** [comment]
Intra-cluster access  via the service proxy at the master does not seem to work for me even using v1beta3 i.e. Kibana can't access Elasticsearch and the clientside Jabascript fails to download files e.g.

GET https://130.211.123.231/api/v1beta3/proxy/namespaces/default/services/kibana-logging/app/panels/histogram/img/load_big.gif 404 (Not Found)

Using an extension to my browser I can register a bearer token and that will let me visit the Elasticsearch page or the Kibana page using v1beat3. However, Kibana has the issue shown above and it can't seem to access Elasticsearch using a v1beta3 master service proxy address.

**Comment by satnam6502** [comment]
@zmerlynn this e2e works because Elasticsearch is accessed via the service proxy at the master and the e2e will be run with an authenticated client.

**Comment by roberthbailey** [comment]
> We do not have an e2e for Kibana.

We probably should, because that would have caught this problem before it was submitted.

**Comment by satnam6502** [comment]
How would we write such a test? I don't know of any API calls I can make to its web UI to check if it is working?

**Comment by satnam6502** [comment]
What we could do is to write a test which emulates the client side calls from a browser and checks that they work.

**Comment by satnam6502** [comment]
After my PR #7123 Kibana logging now works.

**Comment by roberthbailey** [comment]
Awesome! Is there anything else that you've noticed stopped working after the removal of basic auth?

**Comment by satnam6502** [comment]
Not yet. Let me update the documentation for logging etc. and prepare the
example for a logging blog post and I shall see if I come across anything.
Thanks to everyone for their help.
