### ISSUE TITLE
OpenStack's CreateExternalLoadBalancer implementation returning errors

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7199]
Reported by @tonanhngo via IRC. Apparently @tonanhngo's attempts to create an external load balancer by setting "createExternalLoadBalancer: true" in a service config are failing with errors from his OpenStack Neutron load balancer complaining that the value lb_method cannot be empty, but must be one of the value ['ROUND_ROBIN', 'LEAST_CONNECTIONS', 'SOURCE_IP']

@anguslees do you think you could fix this up in the OpenStack cloud provider implementation?

**Comment by cloudsan42** [comment]
Hi,

I'm running Kubernetes cluster in Openstack but when  I specify service type as Load balancer it is showing empty externtel Ip.
NAME        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
guestbook   10.8.8.8                 3000/TCP   4m
can you please tell how to get externel IP?

**Comment by a-robinson** [comment]
Run `kubectl get events` for messages that will tell you what's going on with your external load balancer.

**Comment by cloudsan42** [comment]
Hi Robinson,
There was  no events  related to load balancer.does kubernetes give externel IP in when using openstack ? if yes should I need to  change any settings in Openstack?

**Comment by VMTrooper** [comment]
Hello @a-robinson,

+1 on no external IP displayed as well as no clues from the events output.

Does Kubernetes OpenStack provider support both Neutron LBaaS v1 and v2 APIs? or just one or the other?

Thanks!

**Comment by a-robinson** [comment]
If there aren't any events, then you're probably running in a configuration that doesn't support load balancers. Do you know what `--cloud-provider` your cluster's kube-controller-manager was configured to use? The controller manager won't attempt to do anything for services of `type=LoadBalancer` unless the cloud provider specified supports it. If the specified provider doesn't support it, then there should be a log entry in the controller manager's log saying that a prerequisite for supporting load balancers isn't met (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L161).

**Comment by VMTrooper** [comment]
My controller manager is configured to use the OpenStack provider.

I tried deploying Kubernetes on two different clouds: one with the load balancing as a service version 1 API and another with the version 2 API.

I will try looking at the controller manager logs tomorrow to see if I find any helpful hints.

Thanks!

**Comment by anguslees** [comment]
@VMTrooper: Any hints in the logs?  What cloud provider config are you using?  Have you specified `floating-network-id`?  (See https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L80 for the various values supported - depending on which version of k8s you're using)

**Comment by VMTrooper** [comment]
Thank you for follow-up @anguslees, one of the BlueBox folks (@vmtyler) pointed out the additional config required for the openstack provider, and I was able to get it working.

I will keep the openstack code you mentioned bookmarked for future releases in case any of the supported values change!
