### ISSUE TITLE
patch service error 415

### ISSUE THREAD

**Issue by jiaweizhou** [GoogleCloudPlatform/kubernetes#7214]
Hi, when I patch my service using url /api/v1beta3/namespaces/developmentwangzhe/services/frontend    with body {"apiVersion":"v1beta2"} to change the apiVersion,but the response is 
"415: Unsupported Media Type".
Anyone can give me some advise,thank you!

**Comment by davidopp** [comment]
Can you please give more details on how you set up your service initially (the YAML file and the command you ran) and what command you are running to patch the service? Thanks!

**Comment by jiaweizhou** [comment]
ok, I create a service with curl like this:
 curl http://10.10.103.86:8080/api/v1beta3/namespaces/developmentwangzhe/services -XPOST -d '{"kind":"Service","apiVersion":"v1beta3","metadata":{"name":"frontend","labels":{"name":"frontend"}},"spec":{"ports":[{ "port":80,"targetPort":80,"protocol":"TCP"}],"selector":{"name":"frontend"}}}'

Then I want to patch the apiVersion to v1beta1, I send the command like this:
curl http://10.10.103.86:8080/api/v1beta3/namespaces/developmentwangzhe/services/frontend -XPATCH -d '{"apiVersion":"v1beta3"}'

but  what the api return back is "415: Unsupported Media Type".

**Comment by wangzhezhe** [comment]
I have the same problem when I use the PATCH remote API , It seem that the format of request is not clear in: http://kubernetes.io/third_party/swagger-ui/#!/v1beta3/patchPod , Anyone could give me some suggestions in using PATCH API of k8s ?  Is there some tutorial about how to use the remote API of k8s? Thank you !

**Comment by lavalamp** [comment]
You can't use PATCH to change the version of a resource. If you want to see it in another version, you can just use the other version's URL, e.g., http://10.10.103.86:8080/api/v1beta1/services/frontend?namespace=developmentwangzhe

apiVersion must match the version in the URL.

**Comment by jiaweizhou** [comment]
thanks, but I also try to patch some other argument like the ports in the spec,but it return the same error .Can you give some examples that you patch resource？
thanks
