### ISSUE TITLE
v1beta3 namespace API error

### ISSUE THREAD

**Issue by wangzhezhe** [GoogleCloudPlatform/kubernetes#7217]
Hi , when I use remote API to create the namespaces , the config file like this:
{
  "apiVersion":"v1beta3",  
  "kind": "Namespace",
  "metadata": {
    "name": "development"
  },
  "spec": {},
  "labels": {
    "name": "development"
  }  
}

than in the master node , I use the kubectl get namespaces , the labels of devwangzhe is none , Is it some problems in v1beta3 remote API , what's the usage of labels of namespace on earth? Could any one give me some suggestions ? Thank you!

**Comment by wojtek-t** [comment]
cc @nikhiljindal

**Comment by nikhiljindal** [comment]
As per the API (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L102) "labels" should be inside "metadata". The following works fine for me:

```
{
  "apiVersion":"v1beta3",
  "kind": "Namespace",
  "metadata": {
    "name": "development",
    "labels": {
      "name": "development"
    }
  }
}
```
