### ISSUE TITLE
broken master provision by ETune

### ISSUE THREAD

**Issue by dimafujitsu** [GoogleCloudPlatform/kubernetes#7221]
https://github.com/GoogleCloudPlatform/kubernetes/commit/7475efbcfb6a2effa00d70cd152240d96ec25f0c#commitcomment-10865088

**Comment by roberthbailey** [comment]
@dimafujitsu Want to send a short PR to fix this? I think if you replace `local -r` with `declare -r` it should do the trick.

**Comment by dimafujitsu** [comment]
it is https://github.com/GoogleCloudPlatform/kubernetes/pull/7220

**Comment by erictune** [comment]
fixed by #7220
