### ISSUE TITLE
Persist CI e2e test cluster logs for debugging purposes

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#7236]
We need to be able to diagnose e2e test failures after the relevant test cluster has been shut down.

Right now this almost works, but not quite.

Fluentd can currently only be configured to send log files to one place, for example:

1. Google Cloud Logging, or
2. ElasticSearch (running as a pod in the e2e test cluster, and saved to local disk on the node).

With the current configuration in hack/e2e.go, logs typically go to ElasticSearch (and there is an e2e test to check that that works correctly), and tears down the e2e test cluster after each test run, so the logs are deleted.

The proposed solution is to have fluentd configurable to send to multiple log collector backends, and configure it as such to both Google Cloud Logging and ElasticSearch for CI e2e test runs to facilitate easier debugging.  Satnam6502@ has offered to sort this out.

**Comment by satnam6502** [comment]
Originally it was possible to send logs to both Elasticsearch **and** Cloud Logging but at some point this got made into a binary choice of one or the other (by @jbeda or @zmerlynn ?). I propose to undo this unless there are strong objections.

@zmerlynn : what do you think?

**Comment by zmerlynn** [comment]
I didn't turn it into a binary choice. :)

**Comment by satnam6502** [comment]
Yeah, pretty sure it was Joe. I am sure it was a wide decision at the time.

**Comment by bprashanth** [comment]
Would be nice to have these at maximum verbosity because when we need them we need them all, IIRC we currently only get V(2) on a kube-up cluster

**Comment by satnam6502** [comment]
I see this is marked as a post v1.0 milestone? If we don't want this urgently then I will un-assign myself for now.

**Comment by quinton-hoole** [comment]
There is a valid argument that we would not block the 1.0 release for lack of these persisted test logs, and hence the v1.0 milestone was tentatively removed.
There is a counter argument that we stand little chance of being able to debug the existing and still-to-be-found flaky test failures in the absence of log files, and that one or more of those bugs, if not fixed, will block the launch anyway.
I'd say that if there is nothing on the v1.0 milestone that you can sensibly work on, this one is fair game.

**Comment by bprashanth** [comment]
I would find it useful, and I suppose this should be on par with writing tests (of which we have a few 1.0: https://github.com/GoogleCloudPlatform/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3Av1.0+label%3Aarea%2Ftest)

**Comment by davidopp** [comment]
I'm not sure we'll be able to convince folks to move this to 1.0, but @bprashanth feel free to work on this, as it seems very valuable.

**Comment by satnam6502** [comment]
I thought about changing our setup to allow both Elasticsearch and Cloud Logging to be targeted. I've been a little hesitant because this could lead to a breakage (esp. for GKE) and we are getting close to 1.0 ...

**Comment by a-robinson** [comment]
I'd love to see this fixed soon to help debug flakes, but yes, it'd be nice to at least be cc'ed on env var changes.

**Comment by quinton-hoole** [comment]
Try again to have it added to the high priority list, as this is making debugging the system very difficult.

cc @fgrzadkowski @davidopp Who expressed interest.

**Comment by fgrzadkowski** [comment]
@brendanburns How do we access those logs? I tried to find them for gce-scalability jenkins suite, but didn't find it.
