### ISSUE TITLE
Phrase kubeconfig secrets in terms of master service.

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#7237]
Kubeconfig secrets currently state the host:port of the master.
They should instead use "https://kubernetes", and use the service DNS name.

There are a couple places where people need to override the kubeconfig value with a flag:
 - kube proxy has to use master VM IP, as is currently done, since service-ips are provided by kube-proxy
 - master components need to use master VM IP, until we have kube-proxy on master VM
 - anything that uses VM IP needs to be restarted if the master moves its IP.
 - kube2sky needs to use ServiceIP since it provides DNS.  It can survive master IP changes since it is using service IP.

**Comment by erictune** [comment]
@cjcullen we just figured this out.

**Comment by erictune** [comment]
Plan to run kube-proxy on master #7118 was cancelled, so all master component pods will need to use service-IP instead or service-DNS-name

**Comment by cjcullen** [comment]
They'll have to use the actual IP if they don't have kube-proxy, no?

**Comment by erictune** [comment]
Oh, right.  Hmm.
Maybe it is better to just omit the server entirely from the kubeconfig, and expect each user of the secret to find the master the best way it knows how (service-dns, service-ip-from-env, or vm-ip-from-salt)

**Comment by cjcullen** [comment]
PR #7275 changes the system secrets to point at "https://kubernetes:443" by default. Kube2sky then overrides that with values from the KUBERNETES_SERVICE env vars.

**Comment by erictune** [comment]
@cjcullen would you agree that this is fixed by #7275

**Comment by cjcullen** [comment]
Yep.
