### ISSUE TITLE
Are dockerfiles used in docker tutorial available?

### ISSUE THREAD

**Issue by slawosz** [GoogleCloudPlatform/kubernetes#7252]
I would like to see source of `gcr.io/google_containers/hyperkube` Dockerfile. It is used here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md
cc @brendandburns 

Thanks

**Comment by a-robinson** [comment]
Thanks for the interest in Kubernetes! The Dockerfile for hyperkube (standalone, single-machine kubernetes) is located [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/images/hyperkube/Dockerfile).

**Comment by slawosz** [comment]
Perfect, thanks a lot for so fast response!
