### ISSUE TITLE
Document best practices for Kubernetes users

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#7257]
We should document best practices for using Kubernetes, especially within the context of creating new examples (#4926), so that reviewers can check for the issues. This is a successor to #1603.

Off the top of my head:
* Use the latest stable API version (currently v1)
* Use YAML rather than JSON (more user friendly for config)
* Group related objects together in a single file. This currently requires a List object in YAML, but it's still better than separate files. Almost nobody knows about this feature.
* Create service before corresponding replication controllers so that the scheduler can spread the pods comprising the service. #11144 (or, create the RC without specifying replicas, create the service, then scale up the RC, which may work better in an example using progressive disclosure and may have benefits in real scenarios also, such as ensuring one replica works before creating lots of them)
* Use `kubectl create -f <directory>` where possible. Another little-known feature.
* Don't use hostPort unless absolutely necessary (e.g., for a node daemon). Use the apiserver proxying or port forwarding for debug/admin access, or a service for external service access. Though #1487 was closed, hostPort is still in several examples.
* Don't specify default values unnecessarily. Now that we default the selector and labels in RC, it should get slimmer. Eventually we'll need a user's guide that can cover more advanced topics, but we want examples to look simple, in general.
* We should establish a convention other than "name" for label keys. (#3394) Probably some combination of "app", "component", ... I put some examples in labels.md.
* Service should use a subset of the labels used by the replication controllers whose pods it targets. #8524
* Use kubectl run and expose where appropriate, at least presented as an alternative
* Use headless services where appropriate
* Use kubectl bulk operations (via files and/or labels) for get and delete
* Use kubectl delete rather than stop
* No naked pods, except for RestartNever scenarios. (A minimal Job is coming. #1624)
* Use Deployment (#1743) for RestartAlways services rather than RC directly, when we have that.
* In the meantime, put a version number or hash as a suffix to the name and in a label on a ReplicationController, to facilitate rolling update, as we do for [--image](https://github.com/GoogleCloudPlatform/kubernetes/blob/072137764665182394975e1e1459ade58ee25719/pkg/kubectl/rolling_updater.go#L112)
* Put object description in an annotation

cc @smarterclayton @thockin

**Comment by erictune** [comment]
Step 1: put above text into examples/README.md

**Comment by bgrant0607** [comment]
@erictune Yes, that's my plan. Plan to create a PR when I get a chance.

**Comment by smarterclayton** [comment]
> On Apr 23, 2015, at 5:45 PM, Brian Grant <notifications@github.com> wrote:
> 
> We should document best practices for using Kubernetes, especially within the context of creating new examples (#4926), so that reviewers can check for the issues. This is a successor to #1603.
> 
> Off the top of my head:
> 
> Use the latest stable API version (currently v1beta3)
> Use YAML rather than JSON (more user friendly for config)
> Group related objects together in a single file. This currently requires a List object in YAML, but it's still better than separate files. Almost nobody knows about this feature.
Add comments directly inline with JSON about important points in that single file.  We actually support multi-object json AND yaml (doesn't have to be on a list) from kubect -f

**Comment by bgrant0607** [comment]
@smarterclayton How would one put comments into JSON? 

Yes, -f supports multiple objects without List -- that's the next bullet. YAML requires List for multiple objects in the same file, because the yaml-to-json converter doesn't yet support the document separator (`---`).

**Comment by smarterclayton** [comment]
> On Apr 23, 2015, at 7:01 PM, Brian Grant <notifications@github.com> wrote:
> 
> @smarterclayton How would one put comments into JSON?
> 
In YAML, typo
> Yes, -f supports multiple objects without List -- that's the next bullet. YAML requires List for multiple objects in the same file, because the yaml-to-json converter doesn't yet support the document separator (---).
> 
We do support the stream separator in STDIN pipes and URLs today.  Would not be hard to add that to Paths (I thought it was)

**Comment by bgrant0607** [comment]
See #5840.

**Comment by bgrant0607** [comment]
cc @kelseyhightower for his input on best practices for using K8s

**Comment by kelseyhightower** [comment]
@bgrant0607 Just getting around to reviewing this.

**Comment by bgrant0607** [comment]
I wove many/most of these practices into the new user-guide content. A bullet list of guidelines in docs/examples would be useful, as well.

**Comment by mikedanese** [comment]
Creating this comment for notekeeping.
