### ISSUE TITLE
selflink is not updated to v1beta3

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#7260]
After setting up the cluster according to the instructions in [examples/cassandra](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/cassandra), when running
```
kubectl get endpoints cassandra -o yaml
```
In the response, the selflink is 
```
/api/v1beta1/endpoints/monitoring-influxdb-ui?namespace=default
```
which is the v1beta1 format.

**Comment by caesarxuchao** [comment]
@davidopp  Can I have a try?

**Comment by derekwaynecarr** [comment]
I was seeing the same behavior but did not yet have a chance to investigate the cause.

**Comment by davidopp** [comment]
Yes, by all means please feel free to debug this and send a PR to fix it!

**Comment by satnam6502** [comment]
See also #6596 and let me know if I should hold off working on this.

**Comment by caesarxuchao** [comment]
@satnam6502  I don't quite follow the other arguments in #6596, but I can try to update the v1beta1 format to v1beta3 format. It sounds like a good beginner's task.

**Comment by bgrant0607** [comment]
Satnam reported in https://github.com/GoogleCloudPlatform/kubernetes/issues/6596#issuecomment-96009427 that curl returns a v1beta3 selflink. This suggests that the v1beta1 selflink is being generated by kubectl.

**Comment by lavalamp** [comment]
@bgrant0607 You are too optimistic about the cause. :) I'll let @caesarxuchao fill in the details from our investigation into this.

**Comment by caesarxuchao** [comment]
@bgrant0607 @lavalamp 
The kubectl is sending GET requests to the v1beta1 URL. Here are some log entries from the apiserver's log:
```
{"log":"I0428 00:30:20.436576       1 handlers.go:135] GET /api/v1beta1/endpoints/kibana-logging?namespace=default: (633.353µs) 200 [[kubectl/v0.15.0 (linux/amd64) kubernetes/0f22b6f] 216.239.45.72:62625]\n","stream":"stderr","time":"2015-04-28T00:30:20.436589376Z"}
{"log":"I0428 00:30:20.499633       1 handlers.go:135] GET /api/v1beta1/endpoints/kube-dns?namespace=default: (920.551µs) 200 [[kubectl/v0.15.0 (linux/amd64) kubernetes/0f22b6f] 216.239.45.72:62625]\n","stream":"stderr","time":"2015-04-28T00:30:20.499657425Z"}
```
I will dig deeper to find the root cause. Thank you @lavalamp.

**Comment by bgrant0607** [comment]
Ok, that's at least still a kubectl problem. :-)

cc @nikhiljindal

**Comment by bgrant0607** [comment]
What does kubectl version report?

**Comment by caesarxuchao** [comment]
@bgrant0607 
```
Client Version: version.Info{Major:"0", Minor:"15+", GitVersion:"v0.15.0-809-g3c786597dcf701-dirty", GitCommit:"3c786597dcf701313efc941d0825a97d1e1905f5", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"15+", GitVersion:"v0.15.0-716-g0f22b6fc4d0e06-dirty", GitCommit:"0f22b6fc4d0e0667adb4c7003304485f2b866828", GitTreeState:"dirty"}
```

**Comment by caesarxuchao** [comment]
#7629 fixed this.
