### ISSUE TITLE
Feature request: Ability for kubelet to express different node capacity

### ISSUE THREAD

**Issue by nelcy** [GoogleCloudPlatform/kubernetes#7265]
Today, Kubelet reports all resources as Node capacity to Apiserver.
Looking for ability to reserve CPU & Memory for system and other tasks not managed by kubernetes and report the rest as Node capacity to Apiserver.

**Comment by nelcy** [comment]
@vmarmol

**Comment by derekwaynecarr** [comment]
I had expressed interest in something similar that would let me scale the meaning of cpu across a heterogeneous cluster.  In concept, if we had a cpuScalar that we could multiply to what cAdvisor reports you could meet both goals.  You could apply a scalar to let you reserve a percentage of cpu to your nodes system tasks.

**Comment by thockin** [comment]
By "scale the meaning of cpu" do you mean the idea of KCU as captured in
resources.md?  We just don't have any scaling factors but 1, for now.

**Comment by rjnagal** [comment]
What is being asked originally here is not scaling. Although scaling can be used as a workaround. The request is for keeping some resources on the machine free and not reported to the scheduler. These should not be controlled by kube. 

KCU is the right model for scaling.

**Comment by vmarmol** [comment]
I think this boils down to adjusting the reported size of the machine according to the usage by non-Kubernetes containers (or exporting these in a way the scheduler takes into account).

**Comment by nelcy** [comment]
Thanks Victor. You put it right. I want the ability to adjust the reported size of the machine.

**Comment by erictune** [comment]
Does the following work:
Create manifest-based pod that has a cpu and memory limit equal to the
amount you want set aside.
The Pod itself would use almost no memory and use no CPU (e.g. run the
kubernetes/pause:latest image).

The allocated resources would be reported to the scheduler, and so reserved
as you want.
Any system tasks in the root cgroup will still be able to use any memory
and cpu they want, which you want.

**Comment by nelcy** [comment]
Thanks Eric. That should work as a quick fix. I will give it a try and confirm.

**Comment by erictune** [comment]
Please let me know if it worked.  If it does, I will add it to the
documentation.

**Comment by erictune** [comment]
@nelcy 
Did you happen to try this suggestion, and did it work for you?

**Comment by nelcy** [comment]
@erictune 
Sorry Eric. Got stuck in other things for the last few days. Will make this the top priority and will get back to you by end of day.

**Comment by nelcy** [comment]
@erictune 
It works beautifully. Kubelet is registering pod with apiserver and the scheduler is making sure it counts these resources when scheduling pods..

Good workaround.. :)

Thanks

**Comment by erictune** [comment]
TODO(erictune): document this.
