### ISSUE TITLE
Remove the "Attempt N to check Docker and pause pod" loop from GCE turn-up

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#7266]
There's a section of code where it says "Sanity checking cluster" for GCE that I always assumed was in `validate-cluster.sh`, but is GCE OSS specific, here: https://github.com/GoogleCloudPlatform/kubernetes/blob/cf824ae5e07965ba0b4b15ee88e08e2679f36978/cluster/gce/util.sh#L697 . I believe after the addition of `getcomponentstatuses` and various Docker monitoring improvements, this entire section of code can just be gutted. Furthermore, I think that after the switch to cAdvisor in a pod, the code is actually buggy: I spun up a 10 node GCE cluster and logged into a node, and the `/pause` pod that I had was a `fluentd` related one, which isn't guaranteed to exist.

cc @fabioy @satnam6502

**Comment by satnam6502** [comment]
I think I discovered this problem by accident by messing up the manifest file for the Fluentd to Elasticsearch pod which then causes a cluster to be born with no running containers. It's good to see that occasionally some good comes out of my incompetence.

**Comment by zmerlynn** [comment]
That would do it!

**Comment by satnam6502** [comment]
My main concern is that we retain somewhere the ability to restart Docker because I don't think we can assuming running it just once per node is always going to be good enough. @dchen1107

**Comment by zmerlynn** [comment]
Docker is monitored by monit now, directly on the node: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/monit/docker . Additionally, GKE hasn't been using this shell code (and we can't), so we actually rely on monit and friends.

**Comment by dchen1107** [comment]
+1 on what @zmerlynn said here.

**Comment by satnam6502** [comment]
I'll do this.

**Comment by roberthbailey** [comment]
@satnam6502 - @zmerlynn sent #7269 to do this. Since you volunteered I assigned you as the reviewer. :)
