### ISSUE TITLE
kube-up.sh sometimes doesn't complete

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#7272]
This happened to me several times.
Kube-up got stuck at the "waiting for cluster initialization" step.
When I hit ctrl-c, the master was up and I could connect to it and get pods using a bearer token.
So, most likely, the KUBE_PASSWORD is incorrect.
Of course, it is lost when you press ctrl-c, so I can't verify this.  Will update if I find a way to debug more.

**Comment by zmerlynn** [comment]
That's confusing. If you ^C, it shouldn't even have a chance to create the `.kube/config`, should it? Unless it recycles a previous token? That sounds like a bad idea?

**Comment by roberthbailey** [comment]
I'd nuke (or at least temporarily move) your `~/.kube` directory and see if you can reproduce.

**Comment by roberthbailey** [comment]
I did a _ton_ of cluster up/down cycles with the bearer token change and never saw this. I also haven't seen it fail on Jenkins for GCE or GKE since the change went in.

**Comment by erictune** [comment]
it isn't creating the .kube/config.  
And I had previously tried what Robby suggested.

**Comment by erictune** [comment]
It appears there is a mismatch between the IP that kube-up thinks is right and the actual IP of the master.
I did kube-down, then kube-up.
During kube-up it says:
`Using master: kubernetes-master (external IP: 104.197.1.166)`.
But, if, concurrently, I do `gcloud compute instances list` I see:
`kubernetes-master      us-central1-b n1-standard-1 10.240.242.245 104.197.1.166  RUNNING`
Which is a different IP address.

**Comment by erictune** [comment]
Nevermind, those are the same.

**Comment by erictune** [comment]
Okay, I had kube-up print the command it is using to try and reach the master.
  - when run directly on the command line, it fails with 401 unauthorized.
  - when I use the crypt function to compare the password value I'm passing with the hash in the htpasswd file, it matches.
  - when I try to access the master using several of the tokens, it works.

So, the problem seems to be on the server's handling of basic auth.

**Comment by erictune** [comment]
Grr.  I'm on a branch prior to #6618

**Comment by satnam6502** [comment]
A `config` file is not being creates for me -- `.kubeconfig` is still there and different from the output of `kuvectl config view` @jlowdermilk
