### ISSUE TITLE
volume idea: "durable emptyDir"

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#7285]
Some of the discussions in #831 brought this out:

> I need reboot save volumes used to store mysql databases or webspace content. So lifetime needed is forever (not dependent on service / pod / host uptime). Changes should be saved directly.

Most docker containers today run as root, so you should be able to write to
a hostPath mount.  If you are running your containers as non-root (good for
you!) I would be amenable to some different tweak on the model that gave
you what you wanted.  For example, something like

```
"hostPath": { "path": "/tmp/mypod", "uid": 93, "gid": 76, "mode": 0700 }
```

...with well-defined semantics (e.g. only applies if the path does not
exist or already exists in the exact same config).  or even something
higher level to abstract the real host path away.

**Comment by thockin** [comment]
@pwfoo

**Comment by markturansky** [comment]
We need to discuss resource counting (a node is using 1 GCE slot, this pod w/ claim needs another) so we can enforce scheduling constraints for PV.

Is it possible for nodes to have their own distinct "slot name" such that NodeA has a "HostPath-0156" slot and that slot only exists on NodeA?  "HostPath-0157" slot only exists on NodeB, etc.

Then scheduling constraints can pair the pod with a node based on which node has a very specific available resource (HostPath-0156).

Persistent local storage?  Reliability is as good as the underyling storage.  Make Kubernetes can add snapshots and restoration capability in the future.

This idea has been in my head for a while now, but I need to learn the design for resource counting first to know if it's not too crazy.

**Comment by thockin** [comment]
This is roughly what @erictune proposed some months ago but backed away
from.  I don't know how important it is to really polish that use case -
the original inquiry was specifically "I have a one-node cluster"..

**Comment by bgrant0607** [comment]
This is a dupe of #598.

**Comment by bgrant0607** [comment]
@erictune's previous proposal was #1515.

**Comment by thockin** [comment]
Closing in favor of #598, thanks
