### ISSUE TITLE
rolling-update doesn't actually accept a file from stdin

### ISSUE THREAD

**Issue by calvinmetcalf** [GoogleCloudPlatform/kubernetes#7286]
attemting to run

```bash
gcloud alpha container kubectl rolling-update $PREV_VERSION -f - < config.json
```

throws and error with ERROR: Error: - does not specify a valid ReplicationController

```bash
Client Version: version.Info{Major:"0", Minor:"15", GitVersion:"v0.15.0", GitCommit:"831f3e60d7cd64c61a775d6c78acce1673dd8aa9", GitTreeState:"clean"}
```

**Comment by davidopp** [comment]
@jlowdermilk The documentation
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_rolling-update.md
is a little ambiguous, as the second example suggests that - should work but the Synopsis section does not. Could you either fix the documentation or the command?

**Comment by jlowdermilk** [comment]
Calvin, can you post the contents of config.json, and the schema of the original rc? There are some [requirements](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_rolling-update.md#synopsis) for the schema when providing a target from file, which may not be met.

**Comment by calvinmetcalf** [comment]
running `gcloud alpha container kubectl create -f - < config.json` works, I was interpreting the error message that it though - was a rc

**Comment by jlowdermilk** [comment]
`kubectl create -f - < file.json` will work for **any** object schema file. I.e, that is the same command you use to create a pod|service|replicationcontroller from file. The type being created is determined by the contents of the file. Looking back at the code, the error you saw indicates that config.json does not contain a replicationcontroller spec. If you can create it, that must mean it's something else; can you post/link the contents?

**Comment by calvinmetcalf** [comment]
yes I need to clean it up first

**Comment by calvinmetcalf** [comment]
```json
{
  "metadata": {
    "name": "controler-name",
    "labels": {
      "name": "label-name"
    }
  },
  "kind": "ReplicationController",
  "apiVersion": "v1beta3",
  "spec": {
    "replicas": 2,
    "selector": {
      "name": "frontend"
    },
    "template": {
      "metadata": {
        "labels": {
          "name": "frontend"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "app-name",
            "image": "gcr.io/project/app-name:1.0.0",
            "ports": [
              {
                "containerPort": 8080,
                "hostPort": 80
              },
              {
                "containerPort": 8443,
                "hostPort": 443
              }
            ],
            "env": [
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "GCLOUD_PROJECT_ID",
                "value": "project"
              },
              {
                "name": "GCLOUD_KEY",
                "value": "keyfile"
              }
            ]
          }
        ]
      }
    }
  }
}
```

**Comment by jlowdermilk** [comment]
That looks like a valid rc spec, but the labels may be insufficient for rollingupdate. In order to do a rollingupdate you need to have a label to control the update. Typically this would be a "version" label. Example
```
# existing rc spec:
{
  "kind": "ReplicationController",
  "apiVersion": "v1beta3",
  "spec": {
    "replicas": 2,
    "selector": {
      "name": "frontend",
      "version": "v1"
    },
   ...
}

# new rc spec{
  "kind": "ReplicationController",
  "apiVersion": "v1beta3",
  "spec": {
    "replicas": 2,
    "selector": {
      "name": "frontend",
      "version": "v2"
    },
   ...
}
```
Basically the selector for the old and new rc must share at least one label key with a differing value.

By the way, rollingupdate is currently getting a simplified version, which generates the new rc spec for you. This is wip that will be available in next week's GKE release. See #7268

**Comment by calvinmetcalf** [comment]
ah I see, I actually have a dynamic version in there so that will be easy
to do thanks

**Comment by calvinmetcalf** [comment]
so with an updated config

`gcloud alpha container kubectl rolling-update $PREV_VERSION -f - < config.json`

still does not work while 

`gcloud alpha container kubectl rolling-update $PREV_VERSION -f config.json`

does work with the first one still erroring out with `ERROR: Error: - does not specify a valid ReplicationController` so likely my missing selector issue was an unrelated issue

**Comment by jlowdermilk** [comment]
From your last comment, seems this is resolved. If you are still having trouble, lmk and I will reopen.

**Comment by calvinmetcalf** [comment]
still not fixed because I can't do

```bash
./createConfig.sh | gcloud alpha container kubectl rolling-update $PREV_VERSION -f -
```

**Comment by jlowdermilk** [comment]
I'm pretty sure that's a piping issue with the wrapper command that likely doesn't occur if you use kubectl directly. Try

1. `export KUBECONFIG=$HOME/.config/gcloud/kubernetes/kubeconfig`
2. `kubectl use-context "gke_$project_$zone_$clustername"`
3. `./createConfig.sh | gcloud alpha container kubectl rolling-update $PREV_VERSION -f -`

Note that steps 1,2 will be unnecessary with the next gcloud release; you will be able to use kubectl directly after creating a cluster.

**Comment by jlowdermilk** [comment]
With cloudsdk 0.9.60, standalone kubectl works by default with GKE clusters. The `gcloud alpha container kubectl` wrapper command is no longer needed and will be removed in a future release. Let me know if you have problems running
`kubectl rolling-update $PREV_VERSION -f - createConfig.sh`
against a GKE cluster.

**Comment by brosner** [comment]
I am running across this issue with a recent build of `kubectl`.

```
kubectl --validate rolling-update s1 --filename=- < rc.json
error: - contains a List not a ReplicationController

kubectl --validate rolling-update s1 --filename=rc.json
(works)
```

**Comment by calvinmetcalf** [comment]
`./createConfig.sh | kubectl rolling-update $PREV_VERSION -f - ` is still throwing errors with version 0.17 used directly (without wrapping)
