### ISSUE TITLE
Pods, Replication Controllers, Services etc. should be types and not concrete values

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7298]
I am sure this is all coming too late (concerning decisions made before I joined the project) but I can't help thinking that our pod specifications etc. should really be **types** rather than **concrete values**. When a pod is created we should specify the name for that instance (just like declaring a variable in a programming language). When we want to make a replication controller we should supply the type of the pod that needs to be managed (not a specific instance). I think if we had these specifications denote types rather than values we would be better able to express abstractions and perhaps a lot of template/string substitution code that emulates lambdas could be put to rest.

As I said, too late for now but perhaps something to think about for the future.

**Comment by thockin** [comment]
Not sure I follow - RC's pod template is sort of a type - it's a template
that we stamp out.

**Comment by bgrant0607** [comment]
Is this about implementation or API?

**Comment by satnam6502** [comment]
I think I mean API.
