### ISSUE TITLE
Reorganize documentation around specific audiences

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#7299]
Forked from #2633.

We should organize and customize our documentation around specific audiences and/or use cases. For example:
* Core/extension developers
* Porting to another platform
* Cluster turnup
* Cluster admin
* Apps admin
* App developer
* Kick-the-tires user
* Demo

**Comment by bgrant0607** [comment]
cc @RichieEscarez

**Comment by bgrant0607** [comment]
See also #2839

**Comment by RichieEscarez** [comment]
Im currently working on a site reorg and am defining a navigation structure for the docs around the two main (high-level) roles "app developer" and "cluster admin" (and then will migrate all doc around those roles over to the kubernetes.io site). I see that there are several open bugs related to this effort so Ill make sure to address them all in this effort.

**Comment by thockin** [comment]
For the 1.0 lauch I want to have something of a pow-wow and work out a
table of contents for the various audiences so we can start organizing docs
to that rather that the current random structure.

Specifcally a TOC for cluster admins and another kubernetes users.
 kubernetes developers are a third constituency, but less critical here.
We need to do this O(soon) and then get several people engaged in
re-organizing content and writing content to fill gaps.

**Comment by erictune** [comment]
What Tim wants already exists.
From:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/README.md
you see links to the cluster admin guide, the user guide, and the developer
guide.
Each of those is a table of contents pointing to individual topical docs.

**Comment by thockin** [comment]
That's a ToC of what we have, not necessarily what we want.

**Comment by bgrant0607** [comment]
@lavalamp is moving cluster admin docs to docs/admin in #11013

We're going to move user docs to docs/user-guide #11093

**Comment by bgrant0607** [comment]
Done
