### ISSUE TITLE
e2e.go --up needs to retry health checks

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#7302]
hack/e2e.go occasionally fails (or thinks that it fails) to being up a test cluster to test against. 

The log below suggests that as soon as it sees an unhealthy node it fails.  Seems like a few retries are in order.  This is causing continuous integration tests to fail to run about 10% of the time on our CI setup.

============= 

Running: /jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../platforms/linux/amd64/kubectl get cs
 [0;33mValidate output:[0m
NAME                 STATUS    MESSAGE   ERROR
controller-manager   Healthy   ok        nil
scheduler            Healthy   ok        nil
etcd-0               Healthy   {"action":"get","node":{"dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3}]}}
                     nil
node-0               Healthy     ok        nil
node-1               Unhealthy             Get https://e2e-test-jenkins-minion-ww4a:10250/healthz: dial tcp 10.240.198.5:10250: connection refused
[0;31mValidation returned one or more failed components. Cluster is probably broken.[0m
2015/04/24 11:20:39 Error running up: exit status 1
2015/04/24 11:20:39 Error starting e2e cluster. Aborting.
exit status 1
Build step 'Execute shell' marked build as failure
Recording test results

**Comment by quinton-hoole** [comment]
Actually, I lied.  Our CI setup is only failing like this <1% of the time.  Dropping priority of fixing this.

**Comment by zmerlynn** [comment]
Which build was that? That's the output of https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/validate-cluster.sh, which actually does several retries.

**Comment by zmerlynn** [comment]
Closing until there's a demonstration that we don't repeat the health checks. (See #7537 for counterexample.)

**Comment by zmerlynn** [comment]
(cc @fabioy)

**Comment by fabioy** [comment]
This should have been fixed by Robbie in PR #7460.

On Wed, Apr 29, 2015 at 6:10 PM, Zach Loafman <notifications@github.com>
wrote:

> (cc @fabioy <https://github.com/fabioy>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/7302#issuecomment-97624773>
> .
>



-- 
*-- Fabio Yeon*
