### ISSUE TITLE
REST api - wrong field 'id' instead of 'name' specified in error message

### ISSUE THREAD

**Issue by abonas** [GoogleCloudPlatform/kubernetes#7333]
When accessing a non existing entity (example - namespace), the message specifies the requested field as 'id', but it should be 'name'.

Example (see the details section)
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "namespaces \"staging\" not found",
  "reason": "NotFound",
  "details": {
    "id": "staging",
    "kind": "namespaces"
  },
  "code": 404
}

**Comment by nikhiljindal** [comment]
Yes. We should rename "id" to "name" in StatusDetails: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1357

Not sure if we can change v1beta3 API now.
cc @bgrant0607

**Comment by thockin** [comment]
You can add a new field and fill in both, and MAYBE remove ID in v1

**Comment by bgrant0607** [comment]
I suggest we fix it at most in v1 only. This is an annoying wart, but we could just fix the description string for now.

**Comment by bgrant0607** [comment]
If trivial, we should fix v1.
