### ISSUE TITLE
kubectl should expand ~ into home directory

### ISSUE THREAD

**Issue by ghodss** [GoogleCloudPlatform/kubernetes#7339]
On my Mac:

```
$ kubectl --kubeconfig=~/.kube/my-config get pods
Error: The config file ~/.kube/my-config does not exist
$ kubectl --kubeconfig=/Users/sam/.kube/my-config get pods
POD           IP            CONTAINER(S)   IMAGE(S)     HOST      LABELS       STATUS    CREATED
$
```

**Comment by ghodss** [comment]
So I dug a bit deeper to understand why the expansion isn't happening already. It looks like bash is the place that tilde expansion happens; see http://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html.

The reason bash isn't doing the expansion here is because the parameter in the command is prefixed by the name of the flag: `--kubeconfig=<path>`. In this situation bash does not expand the ~ because it is not the first character of the parameter. You can see this for yourself by typing `echo ~/file`, then try `echo --flag=~/file`. Unfortunately when using a long flag name in cobra, you need to use the = sign (i.e. you can't just use --kubeconfig <path>). So, the workaround here is to use a short flag (-k <path>), though currently that doesn't exist for kubeconfig.

We can implement this directly in Go, but you have to decide exactly how much expansion you want to do - see how complex the tilde expansion feature is in the bash documentation above. See [this debate](https://code.google.com/p/go/issues/detail?id=4140) against adding tilde expansion into GOPATH. While it looks like ill-advised to try to replicate bash's behavior, there is a counter-example in Ruby - see [File.expand_path](http://ruby-doc.org/core-1.9.3/File.html#method-c-expand_path). It performs tilde expansion (amongst other things). However, if you look at the [source for this function](https://github.com/ruby/ruby/blob/28ca0b0f20f877b1f00d246cb8d6d4d2fcf259b3/file.c#L3266), you can see that the implementation is non-trivial.

All in all, it looks like implementing ~ directly in the Go code is not ideal. It may be worth it at some point but I'm not going to argue for it now. In the mean time we could strive to have all filename parameters have a short flag to enable path expansion if someone wants to use it.

**Comment by nabadger** [comment]
This is still an issue right? Are there any plans to resolve this, or any suggested workarounds (that still make use of $HOME or ~ ?

At the moment the documentation for kubectl is wrong:

`kubectl config set-cluster --help`

suggests:

`kubectl config set-cluster e2e --certificate-authority=~/.kube/e2e/kubernetes.ca.crt`

which (if for example I'm in /tmp), results in:

`certificate-authority: /tmp/~/.kube/e2e/kubernetes.ca.crt`

**Comment by cgiroua** [comment]
A year late, but there is a workaround (not sure when it was introduced), you can use ${HOME}, but apparently not $HOME, or ~

**Comment by starplanet** [comment]
+1
