### ISSUE TITLE
NFS Storage Volume gets deleted on pod delete

### ISSUE THREAD

**Issue by plamer** [GoogleCloudPlatform/kubernetes#7360]
Environment:
CentOS 7 x64

On the master node:
   
    kubectl get pods

    POD       IP            CONTAINER(S)   IMAGE(S)       HOST                          LABELS    STATUS    CREATED
    nginx     172.17.0.62   nginx          nginx:latest   centos-minion/xx.77.xx.212   <none>    Running   14 seconds

NFS when starting pod:

    ll /data/nginx/index.html
    -rw-r--r-- 1 root root 4 Apr 27 17:15 /data/nginx/index.html

NFS after stoping:

    ll /data/nginx/index.html
    ls: cannot access /data/nginx/index.html: No such file or directory

On the minion node:
   
    docker ps

    CONTAINER ID        IMAGE                                  COMMAND                CREATED              STATUS              PORTS                  NAMES
    a219e5ac45ae        nginx:latest                           "nginx -g 'daemon of   About a minute ago   Up About a minute                          k8s_nginx.9fb62487_nginx_default_e5231baa-ece7-11e4-9d48-00163ef67d0f_ef12fce4
    2b33afff90dc        gcr.io/google_containers/pause:0.8.0   "/pause"               2 minutes ago        Up 2 minutes        0.0.0.0:8090->80/tcp   k8s_POD.f60e046f_nginx_default_e5231baa-ece7-11e4-9d48-00163ef67d0f_1dafd3de

mount:

    centos-master:/data/nginx on /var/lib/kubelet/pods/e5231baa-ece7-11e4-9d48-00163ef67d0f/volumes/kubernetes.io~nfs/data type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=xx.77.xx.212,local_lock=none,addr=xx.77.xx.220)

The pod:

    apiVersion: v1beta3
    id: nginx
    kind: Pod
    metadata:
      name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - hostPort: 8090
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: data
          nfs:
            server: centos-master
            path: /data/nginx

When started it gets the volume mounted in the pod and displays simple html index. When the pod is stopped the files from the directory are deleted too.

**Comment by markturansky** [comment]
Similar to the bug reported recently for gluster https://github.com/GoogleCloudPlatform/kubernetes/issues/7317

Thanks for submitting this.

**Comment by swagiaal** [comment]
I'll look into this

**Comment by markturansky** [comment]
@plamer this bug should be fixed by #7503.  Per our IRC chat, if you could build from source, I think you would be able to resolve this issue as fixed.

**Comment by plamer** [comment]
Thanks!

**Comment by HardikModha** [comment]
Are there any chances that somehow this issue is not still fixed? I faced this issue today when my NFS pod was evicted.

**Comment by jsafrane** [comment]
@HardikModha, it's very unlikely that it's the same bug. Please fill a new one and provide some details, mainly logs from controller-manager and volume-nfs provisioner.
