### ISSUE TITLE
iptables invocations fail if another process is modifying iptables rules

### ISSUE THREAD

**Issue by sdodson** [GoogleCloudPlatform/kubernetes#7370]
If another process is altering iptables rules at the time k8s attempts to add iptables rules it will fail with a locking error. k8s should use -w and retry after a delay.

Below, an external process (openshift-sdn-node) modifies iptables at roughly the same time and k8s fails without retrying.

```
Apr 27 11:40:20 ose3-master.example.com openshift-sdn-node[2058]: + iptables -t nat -D POSTROUTING -s 10.1.0.0/16 '!' -d 10.1.0.0/16 -j MASQUERADE
...
Apr 27 11:40:20 ose3-master.example.com openshift-sdn-node[2058]: + iptables -I INPUT 2 -i lbr0 -m comment --comment 'traffic from docker' -j ACCEPT
Apr 27 11:40:21 ose3-master.example.com openshift-node[2237]: E0427 11:40:21.661746    2237 proxier.go:337] Failed to initialize iptables: error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Apr 27 11:40:21 ose3-master.example.com openshift-node[2237]: E0427 11:40:21.661912    2237 node.go:245] WARNING: Could not modify iptables.  iptables must be mutable by this process to use services.  Do you have root permissions?
Apr 27 11:40:22 ose3-master.example.com openshift-node[2237]: I0427 11:40:22.147405    2237 failing_service_config_proxy.go:19] Failed to properly wire up services.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired: "kubernetes-ro, router, database, frontend, ruby-example, docker-registry, kubernetes"
```

Related to https://github.com/openshift/origin/issues/1922

**Comment by sdodson** [comment]
Sorry, I misunderstood the -w flag, with it retry logic wouldn't be necessary as it'd wait. Perhaps simply retrying is a better solution as -w flag may not exist everywhere we'd like.

**Comment by sdodson** [comment]
Looks like -w was added to iptables 1.4.20(August 2013).

**Comment by thockin** [comment]
Yeah, we have to be pretty back-compatible with iptables.  We always retry
after a few seconds - is there really a bug here?

**Comment by brenton** [comment]
It definitely seems like there is some sort of a problem.  We see this randomly on system startup.  In our environment OpenShift is launching kubernetes around the same time other systemd units are modifying the firewall config.  If one of these others units has the lock kubernetes will report the error Scott mentions and then will never create the required nat'ing for services.

Here's how to reproduce this:
~~~
# systemctl restart iptables
# yum install gdb
# debuginfo-install iptables-1.4.21-13.el7.x86_64
# gdb /usr/sbin/iptables
(gdb) b iptables/xshared.c:257
(gdb) run -L -t nat
Starting program: /usr/sbin/iptables -L -t nat

Breakpoint 1, xtables_lock (wait=wait@entry=false) at xshared.c:257
257                     return true;
~~~

At this point if you run `iptables -L -t nat` you will see the exact same error kubernetes reports.  It's probably not obvious why you have to set the breakpoint at 257 but if you set the breakpoint at 260 and then step through the code it appears that the compiler has optimized lines 263 and 257 to be the same.  In any case running `iptables -L -t nat` will verify if you have the lock or not.

~~~
255         /* If we can't even create a socket, fall back to prior (lockless) behavior */
256         if (xt_socket < 0)
257                 return true;
258 
259         while (1) {
260                 ret = bind(xt_socket, (struct sockaddr*)&xt_addr,
261                            offsetof(struct sockaddr_un, sun_path)+XT_SOCKET_LEN);
262                 if (ret == 0)
263                         return true;
264                 else if (wait == false)
265                         return false;
266                 if (++i % 2 == 0)
267                         fprintf(stderr, "Another app is currently holding the xtables lock; "
268                                 "waiting for it to exit...\n");
269                 sleep(1);
270         }
~~~

Once you've verified you have the lock just restart OpenShift (running kubernetes v0.14.1-582-gb12d75d):

~~~
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.591412   56125 proxier.go:332] Initializing iptables
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.612536   56125 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PROXY]
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.637896   56125 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PROXY]
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.649202   56125 iptables.go:186] running iptables -F [KUBE-PROXY -t nat]
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.659552   56125 iptables.go:186] running iptables -X [KUBE-PROXY -t nat]
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.669134   56125 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: E0429 11:21:36.679006   56125 proxier.go:337] Failed to initialize iptable : error creating chain "KUBE-PORTALS-CONTAINER": exit status 4: Another app is currently holding th
e xtables lock. Perhaps you want to use the -w option?
Apr 29 11:21:36 ose3-master.example.com openshift-node[56125]: E0429 11:21:36.679217   56125 node.go:245] WARNING: Could not modify iptables.  iptables must be mutable by this process to use services.  Do you have root permissions?
Apr 29 11:21:37 ose3-master.example.com openshift-node[56125]: I0429 11:21:36.906869   56125 failing_service_config_proxy.go:19] Failed to properly wire up services.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired: "kubernetes, kubernetes-ro, router, database, frontend, docker-registry"
Apr 29 11:21:37 ose3-master.example.com openshift-node[56125]: I0429 11:21:37.215690   56125 factory.go:68] Error trying to work out if we can hande /system.slice/iptables.service: error inspecting container: No such container: iptables.service
Apr 29 11:21:37 ose3-master.example.com openshift-node[56125]: I0429 11:21:37.215789   56125 factory.go:74] Factory "docker" was unable to handle container "/system.slice/iptables.service"
Apr 29 11:21:37 ose3-master.example.com openshift-node[56125]: I0429 11:21:37.215812   56125 factory.go:71] Using factory "raw" for container "/system.slice/iptables.service"
Apr 29 11:21:37 ose3-master.example.com openshift-node[56125]: I0429 11:21:37.216117   56125 manager.go:661] Added container: "/system.slice/iptables.service" (aliases: [], namespace: "")
Apr 29 11:21:37 ose3-master.example.com openshift-node[56125]: I0429 11:21:37.216534   56125 container.go:185] Start housekeeping for container "/system.slice/iptables.service"
~~~

Afterwards I will see output from cadvisor every once in a while, however the `iptables -L -t nat` will show the firewall is still blank:

~~~
Apr 29 11:22:08 ose3-master.example.com openshift-node[56125]: I0429 11:22:08.224719   56125 container.go:165] Raising housekeeping interval for "/system.slice/iptables.service" to 32s
Apr 29 11:28:01 ose3-master.example.com openshift-node[56125]: I0429 11:28:01.217363   56125 container.go:165] Raising housekeeping interval for "/system.slice/iptables.service" to 16s
Apr 29 11:28:17 ose3-master.example.com openshift-node[56125]: I0429 11:28:17.217107   56125 container.go:165] Raising housekeeping interval for "/system.slice/iptables.service" to 32s
Apr 29 11:30:04 ose3-master.example.com openshift-node[56125]: I0429 11:30:04.224563   56125 container.go:165] Raising housekeeping interval for "/system.slice/iptables.service" to 16s
Apr 29 11:34:02 ose3-master.example.com openshift-node[56125]: I0429 11:34:02.217480   56125 container.go:165] Raising housekeeping interval for "/system.slice/iptables.service" to 8s
~~~

I initially restarted Kubernetes with a blank firewall at 11:21 and yet at 11:38 I still have nothing:

~~~
# date
Wed Apr 29 11:38:26 EDT 2015
# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            
MASQUERADE  all  --  172.17.0.0/16       !172.17.0.0/16       

Chain DOCKER (2 references)
target     prot opt source               destination  
~~~

**Comment by brenton** [comment]
I probably should have made it more clear, I removed the lock by pressing 'c' in gdb to continue.  That's when I started waiting.

**Comment by thockin** [comment]
So something for a holding the lock? I am out of your office for the rest
of this week, but maybe you can figure out - is there a stale process
holding a lock? What kind of lock is it? Flock or semaphore or ... ?

**Comment by brenton** [comment]
What we're saying is that on startup it's fairly common for multiple systemd units to make firewall additions.  If one of them grabs the lock (rarely for more than a few seconds) it will cause kubernetes to fail to initialize iptables and it will never fix itself.  The lock only need be grabbed the microsecond kubernetes tries to initialize iptables for this bug to present itself.

We know exactly which program in our environment was concurrently making iptables updates.  The problem is that kubernetes doesn't appear to be retrying if it fails to initialize iptables.

**Comment by brenton** [comment]
On RHEL the lock is the xtables unix socket lock in iptables to allow multiple programs to update iptables concurrently.  Other platforms may use a flock since that is the default upstream.

To solve this kubernetes needs one more more of the following:

* pass the `-w` flag to `iptables` as scott and the logs mention (possibly only available on some platforms).  If kubernetes desides to wait for the lock it will need a timeout.
* retry the firewall initialization quickly and maybe backoff if it still can't get the lock

It's probably worth noting that if iptables on a platform doesn't have iptables lock support concurrency is likely broken already in other ways for that platform.

**Comment by thockin** [comment]
It does retry all up tables ops.  Unless it somehow gets pathologically
phase locked with your agent, or there is some deeper bug.  We have e2e
tests that prove you can delete tables and it will recreate them.

Are you saying that it never retries (did you set -v=4?) or that every
retry fails?

On RHEL the lock is the xtables unix socket lock in iptables to allow
multiple programs to update iptables concurrently. Other platforms may use
a flock since that is the default upstream.

To solve this kubernetes needs one more more of the following:

   - pass the -w flag to iptables as scott and the logs mention (possibly
   only available on some platforms). If kubernetes desides to wait for the
   lock it will need a timeout.
   - retry the firewall initialization quickly and maybe backoff if it
   still can't get the lock

It's probably worth noting that if iptables on a platform doesn't have
iptables lock support concurrency is likely broken already in other ways
for that platform.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/7370#issuecomment-97506585>
.

**Comment by brenton** [comment]
I can grab the lock for just the second that kubernetes needs it and then let it go.  The kube-proxy nat'ing will never be rebuilt without intervention (restarting kubernetes).  That seems like a bug to me and is what my original comment reproduces.

In addition, once the environment is in this state it won't even pick up new service nat rules.  Other nodes in my environment will pick them up but this one is dead.  I highly suspect it has to do with the fact that iptables initialization is failing.  We test all the time that once a system is up and running you can clean iptables and it will come back.  This is a slightly different case.

**Comment by smarterclayton** [comment]
This seems like a v1 blocker - we see this in every realistic environment we put the Kube-proxy in.  Disagreement?

**Comment by thockin** [comment]
I still don't understand this issue.  It is demonstrably true that the kube-proxy retries all of the iptables logic periodically.

```
root@kubernetes-minion-jrlj:/home/thockin# iptables-save | grep HOST.*kubernetes-ro
-A KUBE-PORTALS-HOST -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes-ro:" -m tcp --dport 80 -j DNAT --to-destination 10.240.7.69:38528
root@kubernetes-minion-jrlj:/home/thockin# iptables -t nat -F KUBE-PORTALS-HOST
root@kubernetes-minion-jrlj:/home/thockin# iptables-save | grep HOST.*kubernetes-ro
root@kubernetes-minion-jrlj:/home/thockin# sleep 10
root@kubernetes-minion-jrlj:/home/thockin# iptables-save | grep HOST.*kubernetes-ro
-A KUBE-PORTALS-HOST -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes-ro:" -m tcp --dport 80 -j DNAT --to-destination 10.240.7.69:38528
```

It's possible (given the mention of "won't even pick up new service nat rules") that this locking tickles a bug in kube-proxy, but I am having trouble reproducing it.

Can you run your kube-proxy with -v=4, trigger the bug, and then take a look at the logs?  If this is real, yeah it's a 1.0 blocker.

**Comment by brenton** [comment]
The problem is in the initialization process.  If you hold the lock while the kube-proxy tries to initialize itself then it will be wedged forever.  What you're showing is the kube-proxy can repair the iptables rules after the initialization code has run.

The logs I pasted earlier show that after the initialization fails at proxier.go:332 it will never try again.  I tend to run at loglevel 4 by default but I'll try to find time today to run through this again.

**Comment by thockin** [comment]
I have a fix coming - can you test the PR before commit?

**Comment by brenton** [comment]
I ran the exact same test as mentioned in my original comment.  While the debug lines have changed the end result is the same:

* grab the lock (at this point even `iptables -L -t nat` will fail)
* start the kube-proxy
* release the lock (at this point `iptables -L -t nat` works)
* wait..
* try creating another service
* wait..

The rules never come back.  Here are the logs:
~~~
[root@dev ~]# grep iptables node.log 
I0514 14:36:25.231727    8620 proxier.go:341] Initializing iptables
I0514 14:36:25.233397    8620 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PROXY]
I0514 14:36:25.235862    8620 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PROXY]
I0514 14:36:25.236936    8620 iptables.go:186] running iptables -F [KUBE-PROXY -t nat]
I0514 14:36:25.237953    8620 iptables.go:186] running iptables -X [KUBE-PROXY -t nat]
I0514 14:36:25.238889    8620 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
E0514 14:36:25.239834    8620 proxier.go:346] Failed to initialize iptables: error creating chain "KUBE-PORTALS-CONTAINER": exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
E0514 14:36:25.239853    8620 node.go:292] WARNING: Could not modify iptables.  iptables must be mutable by this process to use services.  Do you have root permissions?
I0514 14:36:25.330760    8620 failing_service_config_proxy.go:19] Failed to properly wire up services.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired: "docker-registry, kubernetes, kubernetes-ro"
I0514 14:38:57.446786    8620 failing_service_config_proxy.go:19] Failed to properly wire up services.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired: "docker-registry, kubernetes, kubernetes-ro, service1"

[root@dev ~]# osc version
osc v0.5.1-40-gc438ebd-dirty
kubernetes v0.17.0-144-g25d32ee
~~~

**Comment by brenton** [comment]
Sure, I'll test the PR.  I'm betting it will apply fairly cleanly on to my OpenShift codebase.  If not I'll launch Kubernetes directly.

**Comment by thockin** [comment]
Many of those log lines are not part of upstream.  In fact, what upstream has is a glog.Fatalf() which will kill kube-proxy, and when it restarts it will try again.

Did you guys break it by not actually exiting?

**Comment by smarterclayton** [comment]
Looks like we did.  We need to put it into a restart loop.

----- Original Message -----

**Comment by thockin** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8264 is teh fix, though I assert we should not need it, and if you need it this fix may not help you anyway.

I am still OK to commit this.

**Comment by smarterclayton** [comment]
Although NewProxier sucks because it doesn't return a usable error.  I'll take the todo to clean up that part.

----- Original Message -----

**Comment by thockin** [comment]
hey, it logs its error - nothing wrong with that :)

**Comment by smarterclayton** [comment]
:)

**Comment by smarterclayton** [comment]
Opened #8269 and will move the rest back to openshift.

**Comment by caneraydinbey** [comment]
I restarted docker and it worked
`sudo service docker stop`
then
`sudo service docker start`
