### ISSUE TITLE
Guestbook-go vagrant, no IP's in final step

### ISSUE THREAD

**Issue by PeterLamar** [GoogleCloudPlatform/kubernetes#7371]
Following the getting started instructions using vagrant, I get 0 IPs in the final step. How do I access the guestbook from the host?

$ cluster/kubectl.sh get services guestbook -o template --template='{{index . "publicIPs"}}'
current-context: "vagrant"
Running: cluster/../cluster/vagrant/../../cluster/../_output/local/bin/darwin/amd64/kubectl get services guestbook -o template --template={{index . "publicIPs"}}
<no value>

**Comment by a-robinson** [comment]
We discussed this a bit on IRC -- let me know if nothing I suggested there works out or if you need help with any of it.

I'm going to take this issue to mean that we need to improve the example to make it clear what to do if you're running vagrant, and I'll work on that when I have some spare time.

**Comment by a-robinson** [comment]
And for future reference, the ideas from IRC are:
a) Put the minions' IPs into the service's `publicIPs` field
b) Use [kubectl proxy](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_proxy.md) to talk to the service through the master.
c) Don't worry about the service, just hit the pod IP directly 

Using c is certainly easiest if you're just messing around to get a feel for using kubernetes. You could also probably configure vagrant to route the service's IP to one of the VMs, but that's getting outside the scope of kubernetes.

**Comment by PeterLamar** [comment]
Thanks again for your help! The cluster/kubectl.sh update -f foo.yaml &cluster/kubectl.sh get service frontend --output > foo.yml commands are really useful. I set the public IP in the service, but still cannot reach it from my host web browser. I keep looking into it and seeing if I can spot something.

**Comment by PeterLamar** [comment]
So it ended up being an issue with Mavericks (OSX 10.9.6) running virtualbox. Upgrading to Yosemite resolved it. I figured it out by observing flaky behavior with the network connections to Virtual Box itself, Host Only and DHCP occasionally going in and out of connection.
