### ISSUE TITLE
Monit dies trying to revive Docker; master borked

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#7376]
The cluster I created on Friday (at head) was running over the weekend, and when I tried to talk to it this morning, I couldn't.

```
max@mac$ ./_output/local/bin/darwin/amd64/kubectl version
Client Version: version.Info{Major:"0", Minor:"15+", GitVersion:"v0.15.0-728-g64b4ba688bbb56-dirty", GitCommit:"64b4ba688bbb56c60e0eca5e3da4b414bc42d41a", GitTreeState:"dirty"}
Couldn't read version from server: Get https://<master ip>/version: dial tcp <master ip>:443: connection refused
```

SSH'ing into the master, I couldn't hit `/validate`

```
maxforbes@e2e-test-maxforbes-master:~$ curl localhost:8080/validate
curl: (7) Failed to connect to ::1: Network is unreachable

maxforbes@e2e-test-maxforbes-master:~$ curl 127.0.0.1:8080/validate
curl: (7) couldn't connect to host
```

and Docker isn't running

```
maxforbes@e2e-test-maxforbes-master:~$ sudo docker ps -a
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

and neither is monit

```
maxforbes@e2e-test-maxforbes-master:~$ ps auxww | grep monit
1000     13515  0.0  0.1   7844  1972 pts/0    S+   17:57   0:00 grep monit
```

so what happened to monit?

```
maxforbes@e2e-test-maxforbes-master:~$ cat /var/log/monit.log
[UTC Apr 24 17:46:34] info     : monit: generated unique Monit id 07087e649065a353a1aeb843eee5e57d and stored to '/var/lib/monit/id'
[UTC Apr 24 17:46:34] info     : Starting monit daemon
[UTC Apr 24 17:46:34] error    : State file '/var/lib/monit/state': Unable to read magic
[UTC Apr 24 17:46:34] info     : 'system_e2e-test-maxforbes-master.c.mtestp1.internal' Monit started
[UTC Apr 24 17:46:35] info     : monit daemon with pid [4353] killed
[UTC Apr 24 17:46:35] info     : 'system_e2e-test-maxforbes-master.c.mtestp1.internal' Monit stopped
[UTC Apr 24 17:46:35] info     : Starting monit daemon
[UTC Apr 24 17:46:35] info     : 'system_e2e-test-maxforbes-master.c.mtestp1.internal' Monit started
[UTC Apr 24 17:48:35] error    : 'docker' process PID changed from 2011 to 5358
[UTC Apr 24 17:50:35] info     : 'docker' process PID has not changed since last cycle
[UTC Apr 25 08:46:58] error    : 'docker' failed protocol test [HTTP] at UNIX[/var/run/docker.sock] -- HTTP: Error receiving data -- Resource temporarily unavailable

[UTC Apr 25 08:46:59] info     : 'docker' trying to restart
[UTC Apr 25 08:46:59] info     : 'docker' stop: /etc/init.d/docker
[UTC Apr 25 08:49:23] info     : 'docker' start: /etc/init.d/docker
[UTC Apr 25 08:52:01] error    : 'docker' failed protocol test [HTTP] at UNIX[/var/run/docker.sock] -- HTTP: Error receiving data -- Resource temporarily unavailable

[UTC Apr 25 08:52:05] info     : 'docker' trying to restart
[UTC Apr 25 08:52:08] info     : 'docker' stop: /etc/init.d/docker
[UTC Apr 25 08:58:47] error    : 'docker' failed to stop
[UTC Apr 25 09:00:54] error    : 'docker' process is not running
[UTC Apr 25 09:00:55] info     : 'docker' trying to restart
[UTC Apr 25 09:00:55] info     : 'docker' start: /etc/init.d/docker
[UTC Apr 25 09:00:56] error    : Cannot fork a new process
```

@zmerlynn  found [where this happens](https://github.com/renard/monit/blob/master/src/spawn.c#L152) in monit. My questions are: "Why?" and "Should we try to debug this further?" @roberthbailey pointed out that a possible preventative measure is to have a cron job running that kicks monit if it's dead.

I left the cluster running, so if anyone would like me to run commands or would like to dig in more, please let me know.

**Comment by a-robinson** [comment]
I haven't thought much about this, but it may be related to Docker being slow at restarting?
https://github.com/docker/docker/issues/11181

As a side note, it seems like pretty poor design that monit dies if it fails to restart something.

**Comment by dchen1107** [comment]
@ArtfulCoder Could you please take a look at this? Thanks!

**Comment by ArtfulCoder** [comment]
@a-robinson 
1. When you started the cluster on Friday, could you connect to apiserver using kubectl ?
2. Did you see any errors in the startupscript.log file ?

**Comment by a-robinson** [comment]
cc @mbforbes

**Comment by mbforbes** [comment]
1. Yes, the cluster functioned on Friday; I was running tests against it. (If you look at the monit log I pasted above, it appears it was functioning for quite a while.)

2. I don't see any errors there, but I can dump it here if it would help (it's quite long, obviously).

**Comment by ArtfulCoder** [comment]
1.No out-of-memory errors seen/logged around the time when monit failed to fork a child process.
2. kubelet seems to consume 400m of memory. not sure why it is so high
3. maybe the fork did fail because of insufficient memory, but this is a guess and no logs to substantiate it

**Comment by mbforbes** [comment]
Just as an explicit followup, there were at least 8 out-of-memory errors that happened on that instance (a master) from the logs in ` /var/log/kern.log.1`—is this normal? I can provide several different logs or VM access for interested parties...

**Comment by roberthbailey** [comment]
Regardless of the cause of the problem (which I agree would be interesting to discover) it seems like we need a cron job or something to make sure that monit is always running. @ArtfulCoder can you look into how we can babysit our babysitter?

**Comment by dchen1107** [comment]
I will take a look this one today since there are several ones related to each other: #7815, #7795, ...
