### ISSUE TITLE
Issue when adding new minions to the cluster

### ISSUE THREAD

**Issue by roman-shuhov** [GoogleCloudPlatform/kubernetes#7381]
Hi,

I'm with kubernetes cluster in aws. 

I faced the issue with adding new minions to the cluster

    kubectl get minions

    NAME        LABELS    STATUS
    10.0.0.12   <none>    Ready
    10.0.0.13   <none>    Ready
    10.0.0.14   <none>    Ready
    10.0.0.15   <none>    Ready
    10.0.0.18   <none>    Ready
    10.0.0.19   <none>    Ready
    10.0.0.20   <none>    Ready
    10.0.0.21   <none>    Ready
    10.0.0.22   <none>    Ready

So, 12-18 minions are "old" and i added 4 "new" 19-22 minions. They looks healthy and listed as Ready. I'm able to schedule new pods on them. 

This is  the list of all pos running

```
kubectl get pods
POD                    IP             CONTAINER(S)   IMAGE(S)                           HOST                  LABELS                                                                                            STATUS    CREATED
web-v5.2-3nixs   10.244.80.9    php-hhvm       <secrect-image>       10.0.0.14/10.0.0.14   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   39 hours
                                      php-nginx      <secrect-image>
web-v5.2-66vf4   10.244.60.10   php-hhvm       <secrect-image>       10.0.0.13/10.0.0.13   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   39 hours
                                      php-nginx      <secrect-image>
web-v5.2-6zr18   10.244.90.9    php-hhvm       <secrect-image>       10.0.0.18/10.0.0.18   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   40 hours
                                      php-nginx      <secrect-image>
web-v5.2-7jmkx   10.244.59.3    php-hhvm       <secrect-image>       10.0.0.22/10.0.0.22   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-7rz32   10.244.7.3     php-hhvm       <secrect-image>       10.0.0.20/10.0.0.20   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-8i6fh   10.244.13.7    php-hhvm       <secrect-image>       10.0.0.12/10.0.0.12   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   40 hours
                                      php-nginx      <secrect-image>
web-v5.2-a9xu6   10.244.80.11   php-hhvm       <secrect-image>       10.0.0.14/10.0.0.14   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   2 hours
                                      php-nginx      <secrect-image>
web-v5.2-d78qi   10.244.90.8    php-hhvm       <secrect-image>       10.0.0.18/10.0.0.18   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   40 hours
                                      php-nginx      <secrect-image>
web-v5.2-f5ywu   10.244.7.4     php-hhvm       <secrect-image>       10.0.0.20/10.0.0.20   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-h5kcq   10.244.92.3    php-hhvm       <secrect-image>       10.0.0.21/10.0.0.21   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-j4ohv   10.244.59.2    php-hhvm       <secrect-image>       10.0.0.22/10.0.0.22   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-nfn3o   10.244.13.9    php-hhvm       <secrect-image>       10.0.0.12/10.0.0.12   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   2 hours
                                      php-nginx      <secrect-image>
web-v5.2-tei5u   10.244.92.2    php-hhvm       <secrect-image>       10.0.0.21/10.0.0.21   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-uk68h   10.244.13.8    php-hhvm       <secrect-image>       10.0.0.12/10.0.0.12   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   39 hours
                                      php-nginx      <secrect-image>
web-v5.2-v0f3n   10.244.60.8    php-hhvm       <secrect-image>       10.0.0.13/10.0.0.13   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   40 hours
                                      php-nginx      <secrect-image>
web-v5.2-vo2dg   10.244.60.9    php-hhvm       <secrect-image>       10.0.0.13/10.0.0.13   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   40 hours
                                      php-nginx      <secrect-image>
web-v5.2-vtme9   10.244.90.10   php-hhvm       <secrect-image>       10.0.0.18/10.0.0.18   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   2 hours
                                      php-nginx      <secrect-image>
web-v5.2-xt7o8   10.244.63.4    php-hhvm       <secrect-image>       10.0.0.19/10.0.0.19   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-zq0et   10.244.63.2    php-hhvm       <secrect-image>       10.0.0.19/10.0.0.19   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   About an hour
                                      php-nginx      <secrect-image>
web-v5.2-zq2ax   10.244.80.8    php-hhvm       <secrect-image>       10.0.0.14/10.0.0.14   app=web,name=web,uses=redis-primary-and-redis-managed-and-redis-gopher,version=v5.2   Running   40 hours
                                      php-nginx      <secrect-image>
kube-dns-4b16x         10.244.63.3    etcd           quay.io/coreos/etcd:latest         10.0.0.19/10.0.0.19   k8s-app=kube-dns,kubernetes.io/cluster-service=true                                               Running   About an hour
                                      kube2sky       kubernetes/kube2sky:1.0
                                      skydns         kubernetes/skydns:2014-12-23-001
redis-gopher-r2j8y     10.244.7.2     redis          redis                              10.0.0.20/10.0.0.20   app=redis,name=redis-gopher                                                                       Running   About an hour
redis-managed-m6mf8    10.244.90.5    redis          redis                              10.0.0.18/10.0.0.18   app=redis,name=redis-managed                                                                      Running   2 days
redis-primary-2oiyx    10.244.80.10   redis          redis                              10.0.0.14/10.0.0.14   app=redis,name=redis-primary                                                                      Running   3 hours
```

So the problem is that pods scheduled on "new" and "old" minions doesn't see each other

I found it in the following way:

login to 10.0.0.22, 10.0.0.19 (new minions) and 10.0.0.13, 10.0.0.14 (old minions)

we have pod 10.244.63.2 scheduled on 10.0.0.19 minions. let's try to telnet/ping it

### .22 host and .19 host

    PING 10.244.63.2 (10.244.63.2) 56(84) bytes of data.
    64 bytes from 10.244.63.2: icmp_seq=2 ttl=63 time=1.28 ms
    64 bytes from 10.244.63.2: icmp_seq=3 ttl=63 time=0.409 ms

### .13 host and .14 host

    ping 10.244.63.2
    PING 10.244.63.2 (10.244.63.2) 56(84) bytes of data.
    From 10.244.60.0: icmp_seq=1 Destination Host Unreachable
    From 10.244.60.0: icmp_seq=2 Destination Host Unreachable
    From 10.244.60.0: icmp_seq=3 Destination Host Unreachable

### .22 and .19

    Ncat: Version 6.40 ( http://nmap.org/ncat )
    Ncat: Connected to 10.244.63.2:80.
    sdf
    HTTP/1.1 400 Bad Request
    Server: nginx/1.6.2 (Ubuntu)
    Date: Mon, 27 Apr 2015 19:57:16 GMT
    Content-Type: text/html
    Content-Length: 181
    Connection: close
    
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx/1.6.2 (Ubuntu)</center>
    </body>
    </html>

### .13 and .14

    Ncat: Version 6.40 ( http://nmap.org/ncat )
    Ncat: No route to host.

Ok, weird, let's try to ping pod 10.244.60.10 scheduled on .13 minion:

### .22 and .19

    PING 10.244.60.10 (10.244.60.10) 56(84) bytes of data.
    ^C
    --- 10.244.60.10 ping statistics ---
    427 packets transmitted, 0 received, 100% packet loss, time 426020ms

### .13 and .14

    PING 10.244.60.10 (10.244.60.10) 56(84) bytes of data.
    64 bytes from 10.244.60.10: icmp_seq=1 ttl=64 time=0.048 ms
    64 bytes from 10.244.60.10: icmp_seq=2 ttl=64 time=0.041 ms

### .22 and .19

    Ncat: Version 6.40 ( http://nmap.org/ncat )
    Ncat: Connection timed out.

### .13 and .14 

    Ncat: Version 6.40 ( http://nmap.org/ncat )
    Ncat: Connected to 10.244.60.10:80.
    sdf
    HTTP/1.1 400 Bad Request
    Server: nginx/1.6.2 (Ubuntu)
    Date: Mon, 27 Apr 2015 20:02:09 GMT
    Content-Type: text/html
    Content-Length: 181
    Connection: close
    
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx/1.6.2 (Ubuntu)</center>
    </body>
    </html>

Let me know if you need any other information

**Comment by a-robinson** [comment]
Thanks for the extra details! How did you go about adding the new nodes? It's very possible that all the necessary routes didn't get added.

Check out how an AWS cluster is spun up from scratch, with a range of IPs assigned to each node and routes added between them: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/util.sh#L566

**Comment by roman-shuhov** [comment]
Yeah, it's probably didn't create routes for new minions

Do you want me to manually run this commands for every minion? Or is it possibleto fix that with master restart?

**Comment by a-robinson** [comment]
I can't say for sure if creating the routes will be enough, but it would be a good start.

Adding new nodes isn't something that's officially supported yet, so there may be other bumps along the way. On the plus side, work on making it reliable is almost done for GCE (e.g. #6949), so AWS shouldn't be far behind.

**Comment by roman-shuhov** [comment]
understood, thanks
