### ISSUE TITLE
Docs: Point out that PullPolicy won't update container images

### ISSUE THREAD

**Issue by colemickens** [GoogleCloudPlatform/kubernetes#7400]
I was not putting a version tag on my images in my RC's Pod template. As such, subsequent deleting and creating the replicationcontroller would cause "stale" images to be spun up.

I think I found something, somewhere that indicates that pull policy defaults to PullIfNotPresent and elsewhere I saw that adding ":latest" will force the image to be re-pulled.

I'm not sure, but I think this should be documented in a single spot. It seems like the Pods page would be the best place. Should I send a PR for adding a section about this there, or would somewhere else be more appropriate?

**Comment by a-robinson** [comment]
Out of curiosity, where do you see that adding :latest will force the image to be re-pulled?

If this is in fact how it works (I don't know without testing it), then it'd fit pretty well in docs/images.md

**Comment by colemickens** [comment]
Updating the rc config to include :latest was "fixed" the issue of a stale container image last night.

Reference for what made me try it: https://github.com/GoogleCloudPlatform/kubernetes/issues/504#issuecomment-68409467

**Comment by a-robinson** [comment]
Thanks for the pointer! Feel free to add that info to the images.md doc.

cc @dchen1107 just in case since she wrote the original comment.

**Comment by ggarson** [comment]
It's written directly into code https://github.com/GoogleCloudPlatform/kubernetes/blob/734663f8d883e596c9c01db2475fa1d7b0a61ba3/pkg/api/v1beta3/types.go line 639

	ImagePullPolicy PullPolicy `json:"imagePullPolicy" description:"image pull policy; one of PullAlways, PullNever, PullIfNotPresent; defaults to PullAlways if :latest tag is specified, or PullIfNotPresent otherwise; cannot be updated"`

**Comment by colemickens** [comment]
The PR is here:
https://github.com/GoogleCloudPlatform/kubernetes/pull/7484

I'm curious how this works: "Pull Policy is per-container, but any user of the cluster will have access to all local images." from that document.

That makes it sound like if I auth and docker pull an image onto a single machine in the cluster that it would be available to all machines in the cluster to spin up a container of that image. I presume that's not what it's meant to imply. Am I simply reading it wrong?

**Comment by erictune** [comment]
If you auth an pull an image onto a single machine in the cluster, then any pods that happen to land there will have access to that image.  

This behavior can be taken advantage of in several ways:
  - manually pull image on one node and then use a node constraint on your pod to force it to go to that node.
  - manually pull image on all nodes (need to have some way to repeat this step when adding new nodes).
