### ISSUE TITLE
Add doc about writing correct conversions

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#7448]
I've noticed that I spend a lot of time debugging serialization tests failures due to the quality of my conversion function implementations.  I've had a few people in the last couple days ask me about things related to conversion functions, and I've come to think it could use some doc with specific examples of conversion functions to give a beginner (or someone that touches it only often enough to forget everything in between instances).  It would make a good addition to the api changes doc.

**Comment by pmorie** [comment]
I'm doubling down on this one since 3 people have asked me in the last 8 hours about the new conversion generation.

**Comment by markturansky** [comment]
+1

**Comment by pmorie** [comment]
Closed out by https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/api_changes.md#changing-versioned-apis
