### ISSUE TITLE
Hundreds of open connections to etcd.

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#7451]
Observations: 

When doing nothing on an unloaded system with 23 nodes checking in, we have 
~126 open connections to etcd.   

When we start to load the system easily jumps to 400+.  

`lsof -p $(pgrep kube-apiserver)`

Other Notes: 
* http://stackoverflow.com/questions/17948827/reusing-http-connections-in-golang 
* I suspect issues in how we are using the etcd client library, which is currently not thread safe but we are using it in a multiplexed fashion.  

@wojtek-t @fgrzadkowski @smarterclayton

**Comment by smarterclayton** [comment]
----- Original Message -----
> Observations:
> 
> When doing nothing on an unloaded system with 23 nodes checking in, we have
> ~126 open connections to etcd.
> 
> When we start to load the system easily jumps to 400+.
> 
> Other Notes:
> *
> http://stackoverflow.com/questions/17948827/reusing-http-connections-in-golang
> * I suspect issues in how we are using the client library, which is currently
> not thread safe but we are using it in a multiplexed fashion.

HTTP or TLS connections from master to etcd?

Our transports *should* be reused on the master for HTTP - which only means bursts of traffic can push the pool size up.  Each watch is one concurrent connection on its own.  We probably need to verify we are sharing the underlying TLS transport (first culprit).  HTTP connections should be shared.  Could also be something in the etcd client library (we should only have one etcd client, but Go will manage the pool underneath it, so could be failure to reuse there).

Do you have stacks for the code which is holding it?

**Comment by timothysc** [comment]
HTTP, we're not using TLS.

**Comment by smarterclayton** [comment]
The number of connections is going to be ~ simultaneous users max, and should clear the pool over time afterwards.  I wouldn't necessarily be worried about 400 connections.  Maybe 40,000.

----- Original Message -----

**Comment by davidopp** [comment]
@lavalamp and @bprashanth say this is working as intended.

**Comment by timothysc** [comment]
It scales linearly with the nodes, it may not be an issue for 1.0 w/100 nodes, but it will certainly be an issue with 10^3 +

**Comment by fgrzadkowski** [comment]
@timothysc Each watch that apiserver handles is one connection with etcd. O(100) connection is expected (e.g. each kubelet watches pods and services, each kubelet proxy watches services and endpoints)

**Comment by timothysc** [comment]
@fgrzadkowski duly noted.  

However, the assertion still holds: That as folks trend towards O(10^3) nodes post 1.0, there will be issues.

**Comment by wojtek-t** [comment]
>
However, the assertion still holds: That as folks trend towards O(10^3) nodes post 1.0, there will be issues.

I agree. But I think there are plans to fight with it (e.g. having apiserver merging different watches into a single watch to etcd and dispatching it appropriately). Although we are not focusing on it at all before 1.0.

**Comment by timothysc** [comment]
@wojtek-t good to know!  Is there a issue that I missed?

**Comment by wojtek-t** [comment]
I'm not aware of any.

**Comment by lavalamp** [comment]
@timothysc for example, the issue on making an indexing system would cover this.

**Comment by davidopp** [comment]
Should we file a post-1.0 issue for apiserver to merge watches, and perhaps do other kinds of batching?

**Comment by bprashanth** [comment]
The batching should fallout naturally when we implement an index layer https://github.com/GoogleCloudPlatform/kubernetes/issues/4817

**Comment by davidopp** [comment]
In that case should we close this issue?

**Comment by bprashanth** [comment]
Lol, I think we already did on April 28

**Comment by davidopp** [comment]
Oops :)

**Comment by krmayankk** [comment]
i am seeing 2000 connections from apiserver to etcd  on a 215 node network. I am also seeing bi directional connection one fro apiserver to etcd which makes sense and i am also seeing a tcp6 connection from etcd to apiserver which doesnt make sense. This is in 1.7.4 . 

<img width="889" alt="screen shot 2018-01-25 at 4 49 04 pm" src="https://user-images.githubusercontent.com/16662068/35419952-bca4d9bc-01ef-11e8-97a8-9379cb26f6c0.png">


Was this fixed in 1.7.4 any other pointers @smarterclayton @bprashanth @wojtek-t @timothysc  ?

**Comment by smarterclayton** [comment]
It's probably best to open another issue.  Please indicate whether you are using etcd3 schema and the exact version of etcd.  It could be caused by bad pooling settings at a couple of levels, but with http2 in place you shouldn't have more than a handful of connections between api server and etcd.
