### ISSUE TITLE
Proper SRV for named ports

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#7471]
Given a service "svc" in namespace "ns", with a TCP port "foo", we should generate SRV records for _foo._tcp.svc.ns...

P2 because we COULD cut it, but easy as we do the other work, and enables a lot of standards-based stuff.

**Comment by vishh** [comment]
Reassigning to @ArtfulCoder!

**Comment by vishh** [comment]
xref #6666

**Comment by thockin** [comment]
I think we have to do this at least minimally - not having SRV is going to inhibit a lot of new-generation cloud development that understands SRV.  Openshift has similar constructs, and I think we need to document our DNS schema and it needs to include basic SRV.

**Comment by thockin** [comment]
Also it is almost done.

**Comment by ArtfulCoder** [comment]
resolved by #9073
