### ISSUE TITLE
pods stay on Pending

### ISSUE THREAD

**Issue by bengong2015** [GoogleCloudPlatform/kubernetes#7489]
Hi all.
I've tried to create a pod on master below: (master's ip: 202.120.11.50  minions's ip: 202.120.11.51)
[root@localhost pods]# kubectl create -f wildfly-pod.json
wildfly2

[root@localhost pods]# kubecfg list /pods
Name                Image(s)            Host                Labels              Status
----------          ----------          ----------          ----------          ----------
wildfly2            wildfly             202.120.11.51/      name=wildfly2       Pending

[root@localhost pods]# kubectl describe pod wildfly2
Name:				wildfly2
Image(s):			wildfly
Host:				202.120.11.51/
Labels:				name=wildfly2
Status:				Pending
Replication Controllers:	<none>
Events:
From		SubobjectPath	Status	Reason			Message
scheduler			Pending	scheduled		Successfully assigned wildfly2 to 202.120.11.51
scheduler			Pending	failedScheduling	Error scheduling: failed to find a fit for pod: {{ } {wildfly2 default /api/v1beta1/pods/wildfly2 aee8f06e-ed93-11e4-99b2-000c29226b9b 666 2015-04-28 18:45:27 +0800 CST map[name:wildfly2] map[]} {[] [{wildfly2 wildfly []  [{ 8180 8087 TCP } { 8280 9990 TCP }] [] 0 0 [] <nil> <nil>  false }] {0xa1fc78 <nil> <nil>} map[]} {Pending    map[]}}
...... ......
scheduler			Pending	scheduled		Successfully assigned wildfly2 to 202.120.11.51

I've tried to solve the problem by modifying /etc/sysconfig/iptables on minion in order to open the useful ports:

-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8180 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8280 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8087 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 9990 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 10250 -j ACCEPT

But the pods still stay on Pending. Any idea?

**Comment by bengong2015** [comment]
I've check the configuration of iptables and restart the service, then the exception gone.
But the pod still stay on pending:
[root@localhost pods]# kubectl create -f wildfly-pod.json
wildfly0
[root@localhost pods]# kubectl describe pod wildfly0
Name: wildfly0
Image(s): wildfly
Host: 202.120.11.51/
Labels: name=wildfly0
Status: Pending
Replication Controllers:  <none>
Events:
From SubobjectPath Status Reason Message
scheduler Pending scheduled Successfully assigned wildfly0 to 202.120.11.52

nothing more.
I run both master and minions on vmware, I test the network between vmwares by 'ping' and it passed. Any idea?

**Comment by andrewchambers** [comment]
pending means your docker image is not there. I had this problem because i had a typo in my container name.

**Comment by bengong2015** [comment]
I got solved this by modifying configuration of docker-registry -- detaching to local docker registry and minions pulling images successfully.
