### ISSUE TITLE
*DefaultRESTMapper.Add() in restmapper.go generates wrong mapping

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#7491]
@smarterclayton @derekwaynecarr 
IMHO, the "if _, ok := m.mapping[plural]; !ok" is problematic.
```
 func (m *DefaultRESTMapper) Add(scope RESTScope, kind string, version string, mixedCase bool) {
     plural, singular := kindToResource(kind, mixedCase)
     meta := typeMeta{APIVersion: version, Kind: kind}
     if _, ok := m.mapping[plural]; !ok {
         m.mapping[plural] = meta
         m.mapping[singular] = meta
         if strings.ToLower(plural) != plural {
             m.mapping[strings.ToLower(plural)] = meta
             m.mapping[strings.ToLower(singular)] = meta
         }
     }
     m.reverse[meta] = plural
     m.scopes[meta] = scope
 }
```
The init() function in latest.go calls this Add() function when looping over different "version" and "kind". Because of the aforementioned "if" condition, most entries in the "mapping" will stuck with v1beta1 "meta". This causes issue #7260. @nikhiljindal also found a related problem in latest_test.go in #6377.

@nikhiljindal and I think that we should use an array to keep all "meta" instead of filtering the "meta" using the "if" condition, so that users of the DefaultRESTMapper can consult the array and choose the latest API version if the array contains multiple "meta".

**Comment by smarterclayton** [comment]
the add should be invoked in the order of preferred versions first, but it looks like when we switched latest.Version we did not do that.  If we invoked add on v1beta3 first (it should be the reverse order of latest.Versions) that would also solve this issue if I understand your statements correctly.

**Comment by smarterclayton** [comment]
Actually, it would not be latest.versions, but the local versions in the init() block of latest.  We should add a comment there that the order should be in preferred API selection order.

**Comment by caesarxuchao** [comment]
Yes, carefully choosing the order of adding API versions will solve #7260, though I don't know if this is the best practice as it makes maintenance difficult. Comments are welcomed.

**Comment by caesarxuchao** [comment]
I will change the API registration order and make a commit tomorrow. Please let me know if you have other thoughts.

**Comment by smarterclayton** [comment]
----- Original Message -----
> Yes, carefully choosing the order of adding API versions will solve #7260,
> though I don't know if this is the best practice as it makes maintenance
> difficult. Comments are welcomed.

Agree, but it's not uncommon to have a priority order list in other parts of the code (for instance, RESTMapper takes a priority list on lookup) so it's at least internally consistent.

**Comment by caesarxuchao** [comment]
Hi @smarterclayton, could you tell me more about the logic here:
```
if strings.ToLower(plural) != plural {
             m.mapping[strings.ToLower(plural)] = meta
             m.mapping[strings.ToLower(singular)] = meta
}
```
This will make any resource composed of more than one word be mapped to a v1beta1 or v1beta2 meta, no matter how we change the order of "versions". Is this supposed to be the correct behavior? Could you point me to the related doc? Thanks.

**Comment by smarterclayton** [comment]
We should take a resource string passed to the mapper, lowercase it, and then look it up in the mapping.  Case only matters when a user needs to get the resource for `(ReplicationController, v1beta1)` (the opposite lookup), but other lookups (resource -> Kind) should be case-insensitive.

**Comment by caesarxuchao** [comment]
Does that mean both "replicationController" and "replicationcontroller" should both be mapped to a v1beta3 meta?

**Comment by caesarxuchao** [comment]
How about something like this:
```
 if _, ok := m.mapping[plural]; !ok {
         m.mapping[plural] = meta
         m.mapping[singular] = meta
         _, ok = m.mapping[strings.ToLower(plural)]
         if strings.ToLower(plural) != plural && !ok {
             m.mapping[strings.ToLower(plural)] = meta
             m.mapping[strings.ToLower(singular)] = meta
         }
}
```

This way when running "kubectl get replicationcontroller -o yaml", one will get a v1beta3 selfLink;
if running "kubectl get replicationController -o yaml", one will get a v1beta1 selfLink. Is this how it supposed to work? Thanks.

**Comment by nikhiljindal** [comment]
I think we should stop exposing anything in v1beta1 unless the request contains --api-version=v1beta1.
Hence "kubectl get replicationController" should return a v1beta3 selfLink. We can lowercase the resource name from kubectl get request before finding the mapping for that.

Note that if we do what you said, then in second case, the selfLink will be v1beta1, but the replicationController output will be in v1beta3 json, which seems odd. I am wondering why dont we convert the selfLink while converting objects from one apiVersion to another. Right now we just copy it as is: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/conversion.go#L71

**Comment by smarterclayton** [comment]
Self links being embedded in objects is a horrible mess.  I'm not sure I think self links should ever be present in internal objects - rather they should only be set on the way out of the apiserver as a final step.  Events are the one exception... but they already have object references.

----- Original Message -----

**Comment by nikhiljindal** [comment]
Setting selfLink only on versioned objects SGTM.
That will also fix this problem of printing a v1beta1 selfLink in a v1beta3 object (We still need to fix the problem of kubectl making a v1beta1 request instead of v1beta3)
cc @lavalamp : Any reason, why are we embedding selfLink in unversioned internal objects.

**Comment by caesarxuchao** [comment]
@nikhiljindal Or we can do it your way:
```
_, ok1 := m.mapping[plural]
_, ok2 = m.mapping[strings.ToLower(plural)]
if !ok1 && !ok2 {
         m.mapping[plural] = meta
         m.mapping[singular] = meta         
         if strings.ToLower(plural) != plural {
             m.mapping[strings.ToLower(plural)] = meta
             m.mapping[strings.ToLower(singular)] = meta
         }
}
```
Then "kubectl get replicationcontroller" give an v1beta3 selflink; and "kubectl get replicationController" returns a "no resource found" error. Is this ok? @bgrant0607 

On the other hand, "lowercase the resource name from kubectl get request before finding the mapping" will solve the problem for kubectl, but that requires other parties whoever use the mapping to do a lowercasing. So I don't think it's a good practice.

**Comment by smarterclayton** [comment]
> On Apr 29, 2015, at 5:12 PM, Chao Xu <notifications@github.com> wrote:
> 
> @nikhiljindal Or we can do it your way:
> 
> _, ok1 := m.mapping[plural]
> _, ok2 = m.mapping[strings.ToLower(plural)]
> if !ok1 && !ok2 {
>          m.mapping[plural] = meta
>          m.mapping[singular] = meta         
>          if strings.ToLower(plural) != plural {
>              m.mapping[strings.ToLower(plural)] = meta
>              m.mapping[strings.ToLower(singular)] = meta
>          }
> }
> Then "kubectl get replicationcontroller" give an v1beta3 selflink; and "kubectl get replicationController" returns a "no resource found" error. Is this ok? @bgrant0607
> 
> On the other hand, "lowercase the resource name from kubectl get request before finding the mapping" will solve the problem for kubectl, but that requires other parties whoever use the mapping to do a lowercasing. So I don't think it's a good practice.
> 
I meant do it inside RESTMapper.  Then everyone who uses RESTMapper is correct.

**Comment by caesarxuchao** [comment]
Hi @smarterclayton , I change the order of the API versions and lowcase the input string in VersionAndKindForResource(). Then I fail the TestGetUnknownSchemaObjectListGeneric() in get_test. Specifically, when "handles second specific version", object2 has APIVersion v1beta3 instead of the expected v1beta1. Could you give me some pointers on why object2 in second test case should have APIversion v1beta1? Thanks.

**Comment by smarterclayton** [comment]
I think you fixed a bug that the test encoded as "correct" but was really wrong.  Thanks!  :)

**Comment by smarterclayton** [comment]
Object2 should be v1beta3

**Comment by lavalamp** [comment]
>Setting selfLink only on versioned objects SGTM.
>That will also fix this problem of printing a v1beta1 selfLink in a v1beta3 object (We still need to fix the problem of kubectl making a v1beta1 request instead of v1beta3)
cc @lavalamp : Any reason, why are we embedding selfLink in unversioned internal objects.

I *strongly* disagree with this. Self link indicates the provenence of the object. It should tell you the URL that the object was retrieved from, no matter what you do to the object afterwards!! If this weren't the case, we would *not* have caught this bug where kubectl was secretly using v1beta1.

(I agree with @smarterclayton that we shouldn't store it in *etcd*. But everyone outside of apiserver should preserve the self link that they got.)

**Comment by brendandburns** [comment]
I agree w/ @lavalamp, ```selfLink``` should point back to the place where the object came from.  If I grab an object over the v1beta3 API, and then encode it v1beta1, it shouldn't change the selfLink.

**Comment by derekwaynecarr** [comment]
Are self links fully qualified?

**Comment by smarterclayton** [comment]
No, server relative.  Otherwise they'd break for proxies

**Comment by derekwaynecarr** [comment]
I guess I don't really follow the provenance argument if its not fully qualified.  Must be missing something.

**Comment by lavalamp** [comment]
If I have to make a choice, I'd vastly prefer fully-qualifying (breaking proxies) to making them untruthful about the source of the object.

What api version the object was originally stuffed through is valuable information about which of its fields can be relied upon to be set. (Imagine v1.2 adds a FooThrottler field but there's no equivilent in v1beta3; then if you see v1beta3 in the self link you know that field won't be set in your object *even though it's been re-written in v1.2 by kubectl*.)

**Comment by smarterclayton** [comment]
> On May 1, 2015, at 1:38 AM, Daniel Smith <notifications@github.com> wrote:
> 
> If I have to make a choice, I'd vastly prefer fully-qualifying (breaking proxies) to making them untruthful about the source of the object.
> 
> What api version the object was originally stuffed through is valuable information about which of its fields can be relied upon to be set. (Imagine v1.2 adds a FooThrottler field but there's no equivilent in v1beta3; then if you see v1beta3 in the self link you know that field won't be set in your object even though it's been re-written in v1.2 by kubectl.)
> 
Yeah, I definitely agree this is valuable... But parsing information out of urls has all of the problems with object versioning without a clear solution.  For humans to read, valuable, but it seems dangerous to advocate machines reading the URL.  For that use case, I agree having the server (even if wrong) is useful.

**Comment by lavalamp** [comment]
> But parsing information out of urls has all of the problems with object versioning without a clear solution.

Yeah, I would prefer if we never parsed it-- right now we do parse it to get the version out, which is very unfortunate.

**Comment by bgrant0607** [comment]
I agree that selfLink shouldn't be parsed. It's intended for generic REST clients that don't understand how to construct (nor parse, presumably) Kubernetes URLs.

For the most part, kubectl shouldn't be converting objects (#3955). When it does, it should probably just clear selfLink. It will construct the new URL to use from apiVersion, kind, namespace, name.

I also agree selfLink shouldn't be stored -- #2797.

It seems like apiserver should be able to set the hostname to the hostname used to contact the apiserver, taken from the Host header field.

Other selfLink issues: #6596.

**Comment by caesarxuchao** [comment]
#7629 fixed this.
