### ISSUE TITLE
What kind of aws roles do I need to prepare for kubernetes

### ISSUE THREAD

**Issue by skwokmag** [GoogleCloudPlatform/kubernetes#7493]
Hi,

iam has a few roles. Is it "Grant API access to SAML providers"?
Thank you.

skwok

**Comment by cjcullen** [comment]
@justinsb

**Comment by justinsb** [comment]
@skwokmag  I don't really understand the question - sorry.

`export KUBERNETES_PROVIDER=aws; cluster/kube-up.sh` will create two IAM roles for you (kubernetes-master for the master, kuberntes-minion for the minions).  This is just done through shell scripts, so you can see how it works in `cluster/aws/util.sh`,  and in particular you can see the IAM configuration files in `cluster/aws/templates/iam`.

**Comment by skwokmag** [comment]
@justinsb Thank you for your reply. I forgot to point to this: "You need an AWS instance profile and role with EC2 full access.", on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws.md (my apologies). I am new to kubernetes and aws role in aws (I don't have the privilege to set up roles at work), so I didn't know what exactly I had to do and executing `export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash` will just fail me. Thanks to my coworker, Dusty, who showed me the following way (according to him, there is more than 1 way to do it), and I am providing it here just in case there are other people who like me:
1. Log in aws console.
2. Select from the upper right hand corner <username>\Security Credentials.
3. Select Access Keys.
4. Click New Access Key.
5. Obtain the access key and secret access key.
6. Execute "aws configure" in a Terminal (on Mac).
7. When prompted, enter the "AWS Access Key ID" and "AWS Secret Access Key".
8. Optionally, go with the default region name and output format.

Then, one may execute the curl statements without error.
