### ISSUE TITLE
Automatically label every node with its hostname

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#7495]

**Comment by roberthbailey** [comment]
Where are the label applied? I might be able to do this with a one line change as part of #6949.

**Comment by davidopp** [comment]
I suspect that the anti-pet forces may not like this feature but I think it has proven very useful in Borg. The immediate motivation was #7340 but this is a generally useful feature.

The label goes in the ObjectMeta of the Node (in the field "Labels"). I would use something like key="hostname" (or maybe "kubernetes.io/hostname"?) value=<hostname>. And yeah, I think you could do this in registerNode() in your PR.

**Comment by roberthbailey** [comment]
I've added a commit to #6949 to do this.
