### ISSUE TITLE
Metadata fields incorrectly inlined in swagger

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#7501]
Metadata fields like name and labels are inlined into their enclosing types, such as v1beta3.Pod. I believe this is because we inline the Go structs but not the json. The use of the "inline" json tag qualifier apparently is non-standard. The presence of a json field name should indicate that the struct shouldn't be inlined. We'll need to fix this in go-restful.

Examples:
http://kubernetes.io/third_party/swagger-ui/#!/v1beta3/createReplicationController
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1beta3.json

**Comment by smarterclayton** [comment]
I believe I've fixed this with https://github.com/emicklei/go-restful/pull/203

**Comment by bgrant0607** [comment]
Yep. For example:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1beta3.json#L10849
