### ISSUE TITLE
Unable to mount secret volume with v1beta3

### ISSUE THREAD

**Issue by asautins** [GoogleCloudPlatform/kubernetes#7519]
Using the documentation in docs/secret.md as a guide (with some modifications which I believe are accurate for v1beta3 ), if I create a secret as follows:

```
{
  "apiVersion": "v1beta3",
  "kind": "Secret",
  "metadata": {
     "name": "mysecret"
  },
  "data": {
    "username": "dmFsdWUtMQ0K",
    "password": "dmFsdWUtMg0KDQo="
  }
}
```

Executing a v1beta3 pod as follows shows an empty volume in /etc/foo.

```
{
  "apiVersion":"v1beta3",
  "kind": "Pod",
  "metadata": {
     "name": "mypod"
  },
  "spec": {
     "containers": [{
       "name": "c",
       "image": "example/image",
       "volumeMounts": [{
         "name": "foo",
         "mountPath": "/etc/foo",
         "readOnly": true
        }]
      }],
      "volumes": [{
        "name": "foo",
        "source": {
          "secret": {
            "secretName": "mysecret"
          }
        }
      }]
  }
}
```

The following v1beta2 pod correctly mounts the secret in /etc/foo.

```
{
  "apiVersion": "v1beta2",
  "id": "mypod",
  "kind": "Pod",
  "desiredState": {
    "manifest": {
       "containers": [{
       "name": "c",
       "image": "example/image",
       "volumeMounts": [{
         "name": "foo",
         "mountPath": "/etc/foo",
         "readOnly": true
        }]
      }],
      "volumes": [{
        "name": "foo",
        "source": {
          "secret": {
            "target": {
              "kind": "Secret",
              "name": "mysecret"
            }
          }
        }
      }]
    }
  }
}
```

**Comment by pmorie** [comment]
Are these the actual artifacts you're using?  I ask because of the image `example/image`

**Comment by asautins** [comment]
Yes, I used the above.  I tried to mimic in the above the examples from docs/secrets.md which I'm not sure are fully ported to v1beta3 yet.  The above was tested with the image "centos:centos7" and a command of ["sleep", "1000"].  

If it would be helpful I could post the actual artifacts.

**Comment by derekwaynecarr** [comment]
I see this too.

It blocks: https://github.com/GoogleCloudPlatform/kubernetes/issues/4997

**Comment by pmorie** [comment]
@asautins, @derekwaynecarr and I were just talking about the need for a real secrets example.  I'll make a v1beta3 example and see if I can reproduce this locally.

**Comment by pmorie** [comment]
@asautins, Would you try out my example in #7523?

**Comment by pmorie** [comment]
For the record I was not able to reproduce this; perhaps I'm missing something.

@asautins, Could you provide some detail about which cloud provider you're using?

**Comment by asautins** [comment]
I am not using a cloud provider, but am using vagrant.

Note I was not able to reproduce with your example either.  Your example provided the expected results.

**Comment by asautins** [comment]
I think I understand.  Short answer is I believe the functionality works, but the documentation may be incorrect.  It appears there shouldn't be a "source" nesting for v1beta3 in the volumes section as currently shown in the documentation docs/secrets.md.

docs/secret.md shows the following for the secret volume in the v1beta3 example:

```
      "volumes": [{
        "name": "foo",
        "source": {
          "secret": {
            "secretName": "mysecret"
          }
        }
      }]
```

Note in the above example ( and in the example in this issue ) the source nesting.  

Your example shows without the nested source and appears to work:

```
        "volumes": [
            {
                "name": "secret-volume",
                "secret": {
                    "secretName": "test-secret"
                }
            }
        ],
```

In my above example if I remove the "source" nesting as follows it works for me as well.

```
{
  "apiVersion":"v1beta3",
  "kind": "Pod",
  "metadata": {
     "name": "mypod"
  },
  "spec": {
     "containers": [{
       "name": "c",
       "image": "example/image",
       "volumeMounts": [{
         "name": "foo",
         "mountPath": "/etc/foo",
         "readOnly": true
        }]
      }],
      "volumes": [{
        "name": "foo",
        "secret": {
          "secretName": "mysecret"
        }
      }]
  }
}
```

So from the above it would seem your example is extremely helpful and that the documentation in docs/secrets.md should be updated to a corrected representation of  v1beta3.

**Comment by pmorie** [comment]
@asautins, Excellent catch.  I'll update the docs.

**Comment by derekwaynecarr** [comment]
I had source as well.  Please make sure your example is yaml (if not already)

**Comment by asautins** [comment]
@pmorie shouldn't name be moved to the metadata section as well?

**Comment by aronchick** [comment]
+1 on removing "source" solving this.

**Comment by derekwaynecarr** [comment]
@pmorie I think this can be closed
