### ISSUE TITLE
Failed to create the cassandra Pod using kubectl create command

### ISSUE THREAD

**Issue by kcao3** [GoogleCloudPlatform/kubernetes#7571]
Hello,

First of all, I am quite new to Kubernetes and want to get some experience with this technology. So I followed the tutorial on the Cloud Native Deployments of Cassandra using Kubernetes as the starting point: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/cassandra

I learned that I would need a Kubernetes cluster installed and running before starting the tutorial. So, the first thing I did was to install and run a Kubernetes cluster. I selected AWS as my IaaS provider and CoreOS and the OS. Following the instruction obtaining from your Github website:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_single_node_cluster.md
I believe I successfully created a CoreOS single node Kubernetes cluster. However, when I ran the "kubectl get nodes" command, the output indicated that I have one single node with status "NotReady". I am not quite sure why it is the case. Also, going back to the Cassandra deployment example, when I attempted to create a single cassandra node using the "kubectl create" command, I got this exact error:
F0430 16:22:45.093906   12708 create.go:78] pods "" not found

The following shows the versions of the CoreOS and Kubernetes I installed on my virtual machine:

core@standalone ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=633.1.0
VERSION_ID=633.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 633.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@standalone ~ $
core@standalone ~ $ kubectl version
Client Version: version.Info{Major:"0", Minor:"10+", GitVersion:"v0.10.1-dirty", GitCommit:"c8b6b067dc784a729c1b42da050c8a9e69fc920b", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"11+", GitVersion:"v0.11.0-dirty", GitCommit:"18ddff0eb6bc069b41832ce47d19b5b89cfb26e3", GitTreeState:"dirty"}
core@standalone ~ $ kubectl get nodes
NAME                LABELS              STATUS
127.0.0.1           <none>              NotReady
core@standalone ~ $
core@standalone ~ $ cd cassandra/
core@standalone ~/cassandra $ kubectl create -f cassandra.yaml
F0430 16:22:45.093906   12708 create.go:78] pods "" not found
core@standalone ~/cassandra $

Could you please tell me what I have missed here? Thank you in advance for your time and support.

Best regards,

**Comment by cjcullen** [comment]
For the NotReady node, can you look at the docker logs of the kube_controller-manager container and see if anything is obviously wrong?

**Comment by kcao3** [comment]
Something goes terribly wrong with docker version 1.5.0 and the latest stable version of CoreOS: 633.1.0. For some unknown reason, all of the docker commands (even with the simplest commands such as docker version, docker ps, etc) seem to hang. Please see attached screenshot. There is a much older version of CoreOS available on Amazon EC2: CoreOS 310.1.0, which was released on May last year. I tested the Docker commands and they seem to work with this version of CoreOS. Please see attached screenshot. So, which version of CoreOS do you recommend I should use if I wish to test drive Kubernetes with CoreOS on EC2?
![dockerversioncommandhangsoncoreos-633 1 0](https://cloud.githubusercontent.com/assets/11382916/7431560/bf6510b6-efed-11e4-8829-34b713f90ed7.png)
![dockerversioncommandworksoncoreos-310 1 0](https://cloud.githubusercontent.com/assets/11382916/7431559/bf633048-efed-11e4-9264-f7f70bbb6bcc.png)

A General question from a Kubernetes newbie:
I have been watching a few Kubernetes presentation/demo on youtube. I think the technology is extremely cool and promising. At this point, I just wish to reproduce what have been shown in those demos. Despite the fact that the technology is rapidly changing every single second, do you know if Kubernetes has a stable working deployment environment that people can easily reproduce? I have used the ""getting-started-guides" as my starting point for exploring the technology. I have tried to stand up Kubernetes locally via Docker and a single Kubernetes node cluster on CoreOS. None
of them is working so far.

**Comment by erictune** [comment]
Google Container Engine

https://cloud.google.com/container-engine

Is the fastest, most tested way that I know of to get a Kubernetes cluster
up, so you can start running apps on it.

**Comment by kcao3** [comment]
It appears the instruction guides document was out of dated at some point last weeks. However, I believe it has recently been updated. After following the most recent updated versions of the instruction guides document, CoreOS 668.0.0, and Kubernetes v.0.17.0, I was able to create my Multi-node-CoreOS-Kubernetes cluster and run the cassandra example.
