### ISSUE TITLE
The exec LivenessProbe keys off of the output of the exec'ed command rather than its return code

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7587]
This was [mentioned](https://github.com/GoogleCloudPlatform/kubernetes/pull/3695#discussion_r23700142) by @thockin during an old PR review and I just ran into it today - he said he'd file an issue about it, but I wasn't able to find one.

The issue is that it's awkward that our exec liveness probes into docker containers are only considered successful if their stdout is the string "ok", rather than if they return a successful status code, which would seem much more intuitive (and also much easier to write commands for). Switching to using the status code would be an incompatible change, but seems as though it'd be a much better experience going forward.

Thoughts on changing this before v1?

@dchen1107

**Comment by a-robinson** [comment]
Our exec liveness probing doesn't currently work (and may not have worked for some time now, since our tests only ensure that it restarts unhealthy containers, not that it doesn't restart healthy containers - see #7618), so this may be a good chance to change the behavior.

**Comment by vishh** [comment]
We switched over to keywords since docker used to not return appropriate status codes for exec commands. But, docker has been updated since then, and it now returns status codes for exec commands. So +1 for switching over to status codes.

**Comment by roberthbailey** [comment]
@vishh Do you recall what version of docker this relies on?

**Comment by vishh** [comment]
Docker versions 1.4.0 onwards should support exec status.

**Comment by roberthbailey** [comment]
I recall somewhere that we only required docker 1.2+. If we switch to relying in this behavior we should make sure to update our minimum requirements.

**Comment by vishh** [comment]
Our [API](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L565) does not mention the need for exec probes to return an "ok" string BTW. So this change would not *break* the API in theory :) 

cc @bgrant0607

**Comment by bgrant0607** [comment]
The exec functionality has been so problematic that I don't know that anyone can depend on it. I wouldn't worry too much about breaking compatibility, though we should announce/ask on google-containers and kubernetes-announce.

Hooks follow the same rules as probes, and ok vs. not behavior is documented:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/container-environment.md

It would be great to document probes here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/containers.md

**Comment by brendandburns** [comment]
I think that we should use status code, now that it is supported by Docker.

We require Docker 1.4 at this point as well (and we'll soon require 1.6 for PreStop hooks to work).

@vishh are you working on this?  If not, I will do it and send a note to the mailing list about the behavior change.

**Comment by vishh** [comment]
@brendandburns: you can take this.

**Comment by brendandburns** [comment]
This was fixed by #8011

**Comment by bgrant0607** [comment]
Did we need to update probes of any of our addons, master components, examples, etc.?

**Comment by thockin** [comment]
DNS needed to be updated.
