### ISSUE TITLE
Proposal: make the kubectl --validate flag default to true

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7600]
As a follow-up to #7598, assuming --validate is functional, is there a reason that we don't validate user input against the API schema by default? Without it, unexpected fields are silently dropped, leading to tough-to-debug issues for folks who aren't familiar with the schema and happen to put something in the wrong place, misspell or mis-capitalize something, etc.

I wouldn't be surprised if there was a good reason not to do so, but the only downside I can think of currently is it could be frustrating if the API changes in a non-compatible way and kubectl is version-skewed from the master.

@brendandburns @jlowdermilk

**Comment by brendandburns** [comment]
We had a discussion about this when I first implemented the flag.  I had originally defaulted it to true, but @smarterclayton objected.

See:
https://github.com/GoogleCloudPlatform/kubernetes/pull/2517#issuecomment-64144899
for some context.

The concerns are:
   * what if swagger is disabled on the server
   * client side validation can be bad b/c it's not the ultimate source of truth.

Perhaps we should turn on validation in the server by default...

**Comment by smarterclayton** [comment]
I still feel the same, mostly because we have accomplished very few of the additions and decorations to swagger to let it manage our model on the server side.

**Comment by a-robinson** [comment]
Thanks for the pointer, that's good background. Would there be anything stopping us from validating that we aren't dropping input fields on the server?

**Comment by smarterclayton** [comment]
No, that's going to require a new JSON decoder.  Fortunately, the investigations around ugorji/go-codec show that we could potentially start flagging that (although we probably want to ignore input we don't understand so we don't break new clients against old servers)

----- Original Message -----

**Comment by a-robinson** [comment]
Ok, and it looks like server-side validation is covered by #5889, which is depressingly only a P3. Closing this in favor of that.

**Comment by bgrant0607** [comment]
Resurrected as #10555
