### ISSUE TITLE
Put Root CA Cert for cluster into all(ish) pods

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#7648]
We could put this into kubeconfig, which would be generated by TokenController, in response to a ServiceAccount (see #7647).

@roberthbailey suggested this in the discussion of #7444.

The alternative would be to automount this into a well-defined location in all pods, using a similar, but distinct admission controller that that used by service accounts.  But this would encourage other, more generic, tls clients (as compared to the special-purpose K8s client) to trust this CA cert.  I don't think I understand all the security risks there.

**Comment by roberthbailey** [comment]
@liggitt 

Here's what I think we should do. If you add a service account to your pod, you should get:

1. A secret file with a bearer token
1. A secret file with the cluster CA cert (if the master has it)
1. A secret with file a kubeconfig that includes the bearer token, the server's service address (e.g. https://kubernetes.svc.cluster.local), and either the CA cert (if the master has it) or set insecure-skip-tls-verify: true 

Creating a kubeconfig file will make it really easy for system level pods to get a client that can talk to the master (securely). 

Creating separate files with a bearer token & cluster CA cert will make it easier for non-kubernetes code to access the master (securely). For example, you could run `curl --cacert "/etc/kubernetes/ca.crt" -H "Authorization: Bearer $(cat /etc/kubernetes/token)" https://kubernetes.svc.cluster.local` to get a secure connection using curl.

**Comment by liggitt** [comment]
Agree in principle. Would you make the CA and kubeconfig part of the same secret as the token? I think the kubeconfig should be.

**Comment by liggitt** [comment]
Need to think about what happens if any of the inputs (just the CA content and service hostname, I guess) change.

**Comment by roberthbailey** [comment]
It should be treated the same as any secret. @pmorie

**Comment by roberthbailey** [comment]
@liggitt I think having three separate files would make it easier for non kubernetes software (that doesn't know how to parse a kubeconfig file) to use the bearer token and CA cert. I don't know enough about secrets to know if it would all be a single secret or if it would be three distinct secrets.

**Comment by liggitt** [comment]
Secrets have a `Data map[string][]byte` field. Each entry gets injected as a file into the pod when the secret is mounted. Three files in a secret is easy.

**Comment by liggitt** [comment]
I guess if the CA changed, you could restart the token controller with the new CA data, delete all the old service account token secrets, and new ones would get created automatically.

**Comment by pmorie** [comment]
@liggitt @roberthbailey expiry of cert sounds like a case for secrets
rotation to me.

**Comment by jimmidyson** [comment]
Mounting the CA certificate is pretty essential for this story as otherwise need to disable host verification which potentially could expose token to wrong service (through dns poisoning perhaps).

Is this going to be in 1.0?

**Comment by pires** [comment]
`cassandra` and `hazelcast` examples rely on the dangerous assumption that all certificates are valid. Would be great to have this pushed forward.

**Comment by roberthbailey** [comment]
This is not currently marked for the 1.0 milestone. I'll add the candidate tag so it will be given another look (although it's a bit late to be proposing changes....)

**Comment by davsclaus** [comment]
+1 to get this resolved
