### ISSUE TITLE
kubectl create -f ignores namespace in schema files

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#7656]
It's enforcing "default" when it should be picking up the namespace from the schema file, and only using default if namespace wasn't provided.

```
Running: cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl create -f test.yaml
Error: the namespace from the provided object "mynamespace" does not match the namespace "default". You must pass '--namespace=mynamespace' to perform this operation.
``

test.yaml:
```
apiVersion: v1beta3
kind: Pod
metadata:
  name: foo
  namespace: mynamespace
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
```

**Comment by derekwaynecarr** [comment]
I think this was intentional @smarterclayton ?

**Comment by smarterclayton** [comment]
Yes it's by "design" - we only create things in your CLI / config namespace.  I'm concerned about alt behavior because creating something in the wrong namespace could be very dangerous (privileged pod in default namespace).  So I'd consider that an attack vector.

**Comment by jlowdermilk** [comment]
Ok, makes sense. Namespaces don't constitute security scopes now, but reading doc, it looks like that is planned work. Working as intended. cc @satnam6502
