### ISSUE TITLE
kubectl get services does not display external IP of port

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7658]
When I do `kubectl get services` I am shown the external IP for one port but not the other yet both are exposed by an external load balancer.
@jlowdermilk 

```
$ kubectl get services --namespace=mytunes
NAME              LABELS    SELECTOR     IP                PORT(S)
music-db-server   <none>    name=music   10.0.164.220      9200/TCP
                                         107.178.215.205   5601/TCP
```
The service:
```
apiVersion: v1beta3
kind: Service
metadata:
  name: music-db-server
  namespace: mytunes
spec:
  selector:
    name: music
  ports:
  - name: db
    port: 9200
    targetPort: es
  - name: ui
    port: 5601
    targetPort: kibana
  createExternalLoadBalancer: true

```

**Comment by satnam6502** [comment]
If I expose a third port it does not seem to have an IP shown at all.
```
music-db-server   <none>    name=music   10.0.233.74       9200/TCP
                                         107.178.215.205   9300/TCP
                                                           5601/TCP
```

**Comment by jlowdermilk** [comment]
I believe that display is correct, but I think I understand your confusion. All containers in a pod share the same ip, so that display isn't telling you that the pod exposes 10.0.233.74:9200 and 107.178.215.205:9300, it's telling you that 9200,9300,5601 are exposed on *both* 10.0.233.74 **and** 107.178.215.205; they map to the same thing.

Does that make sense?

**Comment by jlowdermilk** [comment]
I think it would be less confusing if IP column was changed to IP(s). I.e. "your pod exposes these ports, and is available on these ips".

**Comment by satnam6502** [comment]
Right, I assumed that is what is going on -- but indeed, it is very confusing.
