### ISSUE TITLE
The Oh-My-Vagrant + Kubernetes environment could be mentioned in the docs

### ISSUE THREAD

**Issue by purpleidea** [GoogleCloudPlatform/kubernetes#7673]
This page: http://kubernetes.io/gettingstarted/ mentions a bunch of "getting started" guides for kubernetes. I wrote the following article+screencast, and I think it provides a good addition to what's already listed, and as such, feel free to link to it: https://ttboj.wordpress.com/2015/05/02/kubernetes-clusters-with-oh-my-vagrant/

I'm not going to send a docs patch, because you require a CLA :( but I figured it would still be friendly to refer you to the work in a ticket. HTH,

Cheers,
James

**Comment by jlowdermilk** [comment]
Thanks for the link. I believe the policy for including guides in http://kubernetes.io/gettingstarted/ is that they have a dedicated maintainer, as the project is moving fast enough that something that works now may no longer work in 1-2 months.

**Comment by purpleidea** [comment]
@jlowdermilk You're welcome!

I'm currently maintaining the project, and I don't see any chance of that changing in the near future.

In addition, because I'm aware of the project speed, the feature was designed to take an external set of templates to set up kubernetes. This template set is pulled in automatically by Oh-My-Vagrant, and can be updated easily, or a user can even substitute in their own templates. That's here: https://github.com/purpleidea/omv-ktemplates

I hope I've answered all your questions.

Cheers,
James

**Comment by jlowdermilk** [comment]
cc @erictune

**Comment by thockin** [comment]
I think Jeff's point was that we can not maintain all of the docs for
non-core setups ourselves. We need someone like you to step up for it. Is
there a problem with the CLA that you can't sign it?

**Comment by purpleidea** [comment]
@thockin If that was @jlowdermilk 's point (perhaps I misread it) then most of the docs needed are already available as part of the Oh-My-Vagrant (omv) project where I think it makes sense for them and I will continue to maintain with others. Similar to how I link to the relevant parts of the kubernetes docs for the kube things.

The big value add for both the kubernetes and omv projects is that by linking, in your "getting started guide", both projects will receive additional testing, and hopefully fewer bugs, due to more users. I also think Oh-My-Vagrant is the easiest ways I know to try out Kubernetes!

As for the requirement of a CLA, AFAICT this only exists to give Google a one-way patent grant to code. I think this is a huge mistake, in particular because (1) this especially shouldn't need to apply to documentation, (2) this is an ALv2 licensed project where google can "take the code" proprietary without a CLA anyways.

Hope this answers your questions!
Cheers!

**Comment by thockin** [comment]
On Sun, May 3, 2015 at 8:02 PM, James <notifications@github.com> wrote:
>
> @thockin If that was @jlowdermilk 's point (perhaps I misread it) then most of the docs needed are already available as part of the Oh-My-Vagrant (omv) project where I think it makes sense for them and I will continue to maintain with others. Similar to how I link to the relevant parts of the kubernetes docs for the kube things.
>
> The big value add for both the kubernetes and omv projects is that by linking, in your "getting started guide", both projects will receive additional testing, and hopefully fewer bugs, due to more users. I also think Oh-My-Vagrant is the easiest ways I know to try out Kubernetes!

We certainly want people to find and use easy answers.  I'm a bit
reticent to link to external docs and examples, but I'll leave that to
Eric who is arbitrating the docs here.

> As for the requirement of a CLA, AFAICT this only exists to give Google a one-way patent grant to code. I think this is a huge mistake, in particular because (1) this especially shouldn't need to apply to documentation, (2) this is an ALv2 licensed project where google can "take the code" proprietary without a CLA anyways.

Hmm, I think this is a bit bombastic.  It's an simply attestation that
you have the right to contribute the things you are contributing, and
a grant to everyone to be able to use your contribution and any
patents that you own that your contribution touches on.  We don't have
a separate "just copyright" CLA, but so long as your docs don't
infringe on any patents that you happen to own, there should be no
exposure here.  I just re-read it and it is quite simple and
reasonable.  But I won't try to convince you any further.

It's simply untenable for a company like Google to run a project like
Kubernetes without this.

**Comment by purpleidea** [comment]
> I just re-read it and it is quite simple and reasonable.

Perhaps I am looking at the wrong link. Is this the correct one: https://cla.developers.google.com/about/google-individual ?

If so, the requirements in there (# 2-4) don't seem to be aligned with an Apache V2 licensed project.

Secondly, it's not clear how you even "agree" to the CLA for _only_ this project, or even one commit, without unwittingly "signing" a CLA to _all_ google projects.

I don't mean to get into a legal discussion, I am merely trying to respectfully answer your question and contribute to the project in a manner which I believe is not unreasonable.

Cheers!

**Comment by erictune** [comment]
I added a link to your article here: https://github.com/GoogleCloudPlatform/kubernetes/wiki/Kubernetes-Community
