### ISSUE TITLE
v1beta3 Silently fails to label a pod if labels is not in metadata

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/kubernetes#7677]
Should fail on making the call, (or if backwards compatibility is desired, should successfully label the pod).

**Comment by thockin-cc** [comment]
This is yet another case of the JSON parser silently ignoring unknown
fields. We should have a canonical bug for this and close all of these as
dups.

**Comment by bgrant0607** [comment]
Yes, dupe of #7598. Even --validate doesn't catch this.
