### ISSUE TITLE
kube-apiserver gives 'Loaded: not-found' while using Vagrant

### ISSUE THREAD

**Issue by pcx** [GoogleCloudPlatform/kubernetes#7683]
I followed the vagrant guide from [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md). I have 1 master and 2 minions up. I am unable to find kube-apiserver service on master.

    $ vagrant status
    Current machine states:
    
    master                    running (virtualbox)
    minion-1                  running (virtualbox)
    minion-2                  running (virtualbox)
    
    This environment represents multiple VMs. The VMs are all listed
    above with their current state. For more information about a specific
    VM, run `vagrant status NAME`.
    $ vagrant ssh master
    Last login: Sun May  3 10:07:39 2015 from 10.0.2.2
    $ sudo systemctl status kube-apiserver
    kube-apiserver.service
       Loaded: not-found (Reason: No such file or directory)
       Active: inactive (dead)

Can be this be related to the issue #3326? I am using Vagrant 1.7.2 (cc: @derekwaynecarr).

       $ vagrant version
       Installed Version: 1.7.2
       Latest Version: 1.7.2
       
       You're running an up-to-date version of Vagrant!

**Comment by joeygibson** [comment]
I have the same issue on my Mac, running OSX 10.10.3. This is what I see immediately after doing this:

```
export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash
```

```
$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!

$ vagrant status
Current machine states:

master                    running (virtualbox)
minion-1                  running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

Here's the hosts file inside master:
```
[vagrant@kubernetes-master ~]$ cat /etc/hosts
127.0.0.1 kubernetes-master kubernetes-master
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.245.1.3 kubernetes-minion-1
127.0.0.1 localhost
```

And here's what I get for the six commands listed in the Setup section of https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

```
[vagrant@kubernetes-master ~]$ sudo systemctl status kube-apiserver
kube-apiserver.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

[vagrant@kubernetes-master ~]$ sudo journalctl -r -u kube-apiserver
-- Logs begin at Tue 2015-02-24 15:05:10 UTC, end at Thu 2015-05-07 11:52:13 UTC. --

[vagrant@kubernetes-master ~]$ sudo systemctl status kube-controller-manager
kube-controller-manager.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

[vagrant@kubernetes-master ~]$ sudo journalctl -r -u kube-controller-manager
-- Logs begin at Tue 2015-02-24 15:05:10 UTC, end at Thu 2015-05-07 11:52:52 UTC. --

[vagrant@kubernetes-master ~]$ sudo systemctl status etcd
etcd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

[vagrant@kubernetes-master ~]$ sudo systemctl status nginx
nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled)
   Active: active (running) since Thu 2015-05-07 11:38:33 UTC; 14min ago
 Main PID: 3503 (nginx)
   CGroup: /system.slice/nginx.service
           ├─3503 nginx: master process /usr/sbin/nginx
           ├─3504 nginx: worker process
           ├─3505 nginx: worker process
           ├─3506 nginx: worker process
           └─3507 nginx: worker process

May 07 11:38:33 kubernetes-master nginx[3499]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
May 07 11:38:33 kubernetes-master nginx[3499]: nginx: configuration file /etc/nginx/nginx.conf test is successful
May 07 11:38:33 kubernetes-master systemd[1]: Started The nginx HTTP and reverse proxy server.
```

**Comment by marcospedreiro** [comment]
I have the same issue as @joeygibson, exact same setup except am running Vagrant 1.7.0 as per issue #3326 "You can use a vagrant version >= 1.6.2 but < 1.7.1"

**Comment by derekwaynecarr** [comment]
I need to update documentation, the kube-apiserver is run as a pod on the master.

If you are attempting to use the Vagrant configuration right now, I strongly recommend you run from the lastest HEAD of the source tree as two major fixes went in this week that are not in prior release trees.

Given that we are trying to close down Kube 1.0 release requirements, I strongly recommend you run from HEAD right now, or until a release > 18.1 is cut since I do not plan on back-porting the Vagrant environment changes to earlier releases.

So from HEAD

```shell
$ make release
$ export KUBERNETES_PROVIDER=vagrant
$ export NUM_MINIONS=<your desired amount>
$ cluster/kube-up.sh
```

should work fine, and your master will run a kubelet, and start the apiserver, controller, and scheduler as containers.  logs are in /var/log/ directory for those components.

I will use this issue to track updating the documentation.

**Comment by pcx** [comment]
@derekwaynecarr OK, I will try using HEAD. Thanks for the update!
