### ISSUE TITLE
ControllerManager is consuming a lot of CPU on empty cluster

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#7697]
I've started a 100-node cluster and run Density test 3 times on this cluster:
```
go run hack/e2e.go -v --test --test_args="--ginkgo.focus=\[Performance suite\]"
```

10 minutes after all tests were finished (I've checked that there were no pods or replication controllers apart from the default ones (fluentd, heapster, etc.) kube-controller was constantly using around 1 core (btw apiserver was using 10-15% with rare bursts).

Note that this wasn't the case on clean cluster (before running those tests). So my feeling is that something is not being cleared correctly.

I've done some profiling - the graph is below:
![controller](https://cloud.githubusercontent.com/assets/10743879/7453027/4094d788-f265-11e4-871e-eb644a302f0c.png)

cc @bprashanth @lavalamp @fgrzadkowski

**Comment by bprashanth** [comment]
This is all 3 right (enddpoints, node and rc)? so even without pods and rcs there could be one of the other 2 acting funny. Will do some initial investigation and report back.

**Comment by wojtek-t** [comment]
I didn't observe any suspicious node-related activity. As for services, the test doesn't start any and thus after the test there are only those that are running in each cluster (kibana, elasticsearch, etc. - 9 in total).

**Comment by wojtek-t** [comment]
BTW - let me know if I can help you with that (since I'm in Warsaw this probably mean that if you don't finish this today you can update this thread so I can continue investigation tomorrow).

**Comment by wojtek-t** [comment]
cc @davidopp

**Comment by bprashanth** [comment]
so the RC is going to take the same amount of time it took to start up to shutdown, ~3m. Even after deleting the pods, it still needs some time to observe that the pods are gone. I have a cluster on which I ran density a while back and the top cpu consumer (according to atop) is currently the apiserver, so whatever it is, it does seem to die down. 

I also prevented density from cleaning itself up and ran it, then manually stopped the rc, but didn't have much luck observing the cpu spike. How are you measuring cpu? Is this 1 core/4 on an n1-standard-4 (so the apiserver was bursting upto 60% of a core from time to time)? fyi i was using both atop and ps.

**Comment by lavalamp** [comment]
I think we must be leaking timers, or creating too many. We must be making a *lot* of timers to make a heap consume all our time.

**Comment by wojtek-t** [comment]
>
so the RC is going to take the same amount of time it took to start up to shutdown, ~3m. Even after deleting the pods, it still needs some time to observe that the pods are gone.

sure - I know. But I was observing the same after 20 minutes and after an hour (which definitely isn't related to to it).

>
I have a cluster on which I ran density a while back and the top cpu consumer (according to atop) is currently the apiserver, so whatever it is, it does seem to die down.

hmm.. for me it seems to accumulate over time. I ran density test 3 or 4 times, and the most important thing here is that it was 100-node cluster

>
I also prevented density from cleaning itself up and ran it, then manually stopped the rc, but didn't have much luck observing the cpu spike. 

In my case it wasn't really a spike - I was constantly observing high cpu-usage of kube-controller.

>
How are you measuring cpu? Is this 1 core/4 on an n1-standard-4 (so the apiserver was bursting upto 60% of a core from time to time)? fyi i was using both atop and ps.

I was using "htop" (but I think it's more or less the same as atop).


>
I think we must be leaking timers, or creating too many. We must be making a lot of timers to make a heap consume all our time.

I think I agree with @lavalamp (basically I'm pretty sure we must be leaking something).

**Comment by lavalamp** [comment]
Specifically, the problem seems to be too many concurrent unfired timers. They get cleaned up after they fire. time.After(d) calls should be replaced with t:=time.NewTimer(d), with t.Stop() being called if we're not waiting the duration.

**Comment by bprashanth** [comment]
Top 3 culprits that come to mind:
1. We do a lot of hand checking of time in the expiration cache. But this is on Get by comparing current time with timestamp, not through a timer.
2. I suppose the time.Sleep we have in our runUntil uses timers. 
3. We also have the resyncChan timer in the reflector, which creates a new timer on every resync.

**Comment by lavalamp** [comment]
#7643 removes a Poll-- I wonder if that was causing this?

**Comment by bprashanth** [comment]
I plan to benchmark a little, that shouldn't be though, because in the described scenario we had no rcs and pods and the cpu was high upto an hour later.

**Comment by lavalamp** [comment]
Hm, that scenario really doesn't sound like there should have been timers open like that. Perhaps something else is wrong.

**Comment by bprashanth** [comment]
Another red herring is that we allow the expectations to expire naturally, each rc should not have > 1 expectation and we should just delete it when the rc is deleted. I'll get a pr up for that.

**Comment by lavalamp** [comment]
Yeah, but:
* those don't keep a timer around
* those would have all expired before the time period in question

**Comment by bprashanth** [comment]
Just mentioned so you don't waste your time on a red herring :)

**Comment by lavalamp** [comment]
I've started up a test cluster with my changes, running the density test. So far, looks good. I'll run it in a loop overnight.

**Comment by bprashanth** [comment]
You will 100% run into https://github.com/GoogleCloudPlatform/kubernetes/issues/7561#issuecomment-98729344 so make sure you ignore errors. I'm fairly certain I'm almost at the bottom of it but not quite.

**Comment by lavalamp** [comment]
Yeah, I saw that one. Four hours of looping the density test and kube-controller-manager is still using like 1% CPU according to top, so I think either my change fixes it or your previous change did.

**Comment by wojtek-t** [comment]
I've run fwe more experiments and it seems that (mostly #7643) fixed it. Thanks @bprashanth and @lavalamp

**Comment by lavalamp** [comment]
So after I stopped my loop, I waited O(hours) and tailed the log file; it seems that, even though there's no RCs in the system any more, kube-controller-manager is continuously creating and deleting multiple pods per second.

```
I0505 20:14:50.016707       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1ifyh3
I0505 20:14:50.216894       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1iufux
I0505 20:14:50.317849       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:50.416921       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1j4yox
I0505 20:14:50.717081       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1j9vku
I0505 20:14:50.864838       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1jhter
I0505 20:14:51.017543       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1jphkw
I0505 20:14:51.117672       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:51.164655       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1jtvu1
I0505 20:14:51.487498       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1k4yyk
I0505 20:14:51.569631       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 2
I0505 20:14:51.617062       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1kwhje
I0505 20:14:51.816869       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1kwpwj
I0505 20:14:51.964523       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1l54vb
I0505 20:14:52.116977       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1lcjbf
I0505 20:14:52.217431       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:52.264596       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1lzr3z
I0505 20:14:52.576779       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1m2hx4
I0505 20:14:52.716432       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1m5rcy
I0505 20:14:52.864846       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1mhk6j
I0505 20:14:52.969481       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:53.016732       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1mkp6y
I0505 20:14:53.317088       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1n71r4
I0505 20:14:53.464482       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1nbf27
I0505 20:14:53.616855       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1nmeob
I0505 20:14:53.717253       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:53.764587       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1nv9zg
I0505 20:14:54.077473       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1o07pg
I0505 20:14:54.169667       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 2
I0505 20:14:54.216765       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1ocylb
I0505 20:14:54.432851       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1og7su
I0505 20:14:54.564695       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1os3q3
I0505 20:14:54.717009       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1owt9m
I0505 20:14:54.817728       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:54.864833       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1p4r29
I0505 20:14:55.168811       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1p84vv
I0505 20:14:55.317275       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1qaecp
I0505 20:14:55.468812       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1qu2wp
I0505 20:14:55.569669       8 replication_controller.go:283] Too few "my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c12" replicas, creating 4
I0505 20:14:55.616700       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1qw276
I0505 20:14:55.932804       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1rsifa
I0505 20:14:56.065625       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1s8qfr
I0505 20:14:56.216483       8 nodecontroller.go:595] Delete pod my-hostname-density200-b3b5c53f-f30c-11e4-9038-10604b682c1seoxe
```

I expect this is the real culprit behind the symptom, and explains why @bprashanth's earlier change made the symptom go away.

**Comment by lavalamp** [comment]
Upping to P0 since this is a regression.

**Comment by lavalamp** [comment]
@bprashanth can you take a look?

**Comment by lavalamp** [comment]
Actually, nvm-- this is node controller and replication controller fighting because scheduler is not respecting the NotReady status.

**Comment by lavalamp** [comment]
So the good news is that our controllers fight very efficiently now...
