### ISSUE TITLE
Manual setup on CoreOS and AWS

### ISSUE THREAD

**Issue by bkeroackdsc** [GoogleCloudPlatform/kubernetes#7717]
@bakins 

I'm looking to set up k8s on AWS on top of CoreOS within an existing subnet and VPC in AWS. I've read the docs pretty carefully but I'm still not clear on exactly how the networking is supposed to work. If I have several nodes running N pods, I understand that k8s assigns a virtual IP to each pod. I'm not clear how that VIP is routed within AWS--each node will have a private IP, so I then use static VPC routes for the address spaces of the VIPs? Is that totally manual?

What is the best approach for standing up the cluster manually--not using the automated scripts?

Thanks for any help with this!

**Comment by roberthbailey** [comment]
@justinsb could probably shed some light here since he wrote many of the automated scripts.

**Comment by bakins** [comment]
@bkeroackdsc 

Two approaches:

1 - run [flannel](https://coreos.com/docs/cluster-management/setup/flannel-config/) - This is generally how I run kubernetes. For testing, the default UDP backend is fine, though you probably want to investigate using the `vxlan` backend for better performance.

2 - set up routing rules within the VPC.  This involves assigning a subnet per node and adding rules to route that subnet to that node, this also involves changing docker options so that it allocates IPs from that subnet. This is what the current [cluster scripts](https://github.com/GoogleCloudPlatform/kubernetes/blob/8eed8475624da9870f5550afcb817bb6b2bdcf29/cluster/aws/util.sh#L573) do on AWS on Ubuntu.  Note: flannel can also be used to set up [AWS routing](https://github.com/coreos/flannel/pull/155), though I have not personally tested this.

Flannel, using vxlan backend, is how I generally run.  It's fairly straight forward, but can be tricky depending on your experience with cloud-config, etc.

**Comment by bkeroackdsc** [comment]
That was helpful, thank you. I've gotten an initial cluster running via https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws-coreos.md -- despite the warning it appears to work OK.

I have the test pod running and it works:
```bash
$ kubectl get pods
POD       IP            CONTAINER(S)   IMAGE(S)                        HOST           LABELS                           STATUS    CREATED      MESSAGE
hello     10.244.80.2                                                  10.10.28.31/   environment=testing,name=hello   Running   38 seconds
                        hello          quay.io/kelseyhightower/hello
``` 

I can access the virtual IP of the pod on any of the k8s nodes (master or minion):
```bash
core@master ~ $ curl -XGET 10.244.80.2/
<h1>Hello version 1.0.0</h1>
```

However I'm not clear how I would be able to route traffic to the pod VIPs externally. The goal is to run multiple instances of a pod that all offer a service on the same port (eg, 80) and access them via the VIP--so we don't care which minion they are running on.

Would the preferable approach be to add static VPC routes manually? Perhaps use the aws-vpc flannel backend? Does it matter?

**Comment by bakins** [comment]
@bkeroackdsc You will need to setup a [service](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md) as that will handle the load balancing, etc.  Actually exposing that service on AWS is a bit of a pain, to be honest, and there are some PR's under review to make that easier.

**Comment by bkeroackdsc** [comment]
Cool, thanks, I definitely was missing something (the Service abstraction). After some searching, it looks like support for AWS ELB creation isn't merged yet (#5225).

Am I correct with the following general plan for externalizing a service?

1. Create a service object for a Pod, choose a random free port for ServicePort (externally tracked).
2. Populate publicIPs with the private IPs of all k8s nodes (nodes have no public IPs)
3. Create a new ELB with listeners on the desired ports (eg, 80/443), proxying to all k8s nodes on the high port chosen earlier.

The above would need to be externally orchestrated, which is OK, I just want to make sure I'm on the right track with my thinking.

Thanks

**Comment by bakins** [comment]
@bkeroackdsc yes - I've seen that approach (" publicIPs with the private IPs of all k8s nodes") done before, so it should work. I have not done it myself, however.

**Comment by bkeroackdsc** [comment]
@bakins Thank you. I just wanted to document here for anyone that comes here from searching that the procedure above works fine in AWS. I've tested with both internal and external (internet-facing) ELBs and it works for the test pod.

**Comment by bakins** [comment]
@bkeroackdsc  "the procedure above" - which procedure? Just want to be sure ;)

Glad it worked!

**Comment by bkeroackdsc** [comment]
Apologies for being unclear.

The following procedure worked to manually stand up a working k8s cluster on CoreOS in AWS (existing VPC and subnet(s)):

1. Created security group for k8s, allowing all traffic among members of that group, and SSH from our management machines.
2. Created subnets for the k8s cluster(s) in an existing VPC. One subnet per AZ, with the idea that each subnet will hold exactly one cluster. Clusters will not span AZs or subnets. High availability will be provided by multiple clusters in an active/standby model, and being careful that all stateful data used by the applications will be on external resources that can be shared among the clusters. Subnets have internet access via NAT only--no public IPs for the instances.
3. Picked an internal/private IP for the master, edited master.yml and node.yml to reflect this IP.
4. Used AWS CLI to create the master instance with the previously picked IP. Waited for instance to come up, SSHed in and verified no journal errors.
5. Used AWS CLI to create the minion nodes similarly to above.
6. Verified proper functioning of them all.
7. Created the test pod described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws-coreos.md
8. SSHed into the master and verified the pod was accessible via the flannel mesh network.
9. Created a service based on the pod:
```json
{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "hello-service",
        "labels": {
            "environment": "testing"
        }
    },
    "spec": {
        "selector": {
            "name": "hello"
        },
        "ports": [
            {
                "protocol": "TCP",
                "port": 53000,
                "targetPort": 80
            }
        ],
        "publicIPs": ["10.10.x.x"]
    }
}
```
10. Verified that this service port was accessible by our management machines via curling port 53000 on the private IP of one of the minion nodes.
11. Created an internal ELB with a listener on port 80, proxying to port 53000. Added the minion nodes as backend servers. Verified that we could access service by using curl on port 80 on the ELB DNS name.
12. Did the same as above, but created a public/internet-facing ELB and accessed it from a machine outside of AWS. This worked as well.

**Comment by roberthbailey** [comment]
@bkeroackdsc I'm glad you figured this out. Marking as resolved...
