### ISSUE TITLE
e2e tests failures and bugs on vanilla vagrant cluster

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/kubernetes#7719]
After bringing my local master up to date with https://github.com/GoogleCloudPlatform/kubernetes/commit/c1d1f95c21a04eb1df40ed07ef5d1691cdd25c03 and running: `export KUBERNETES_PROVIDER=vagrant` in a fresh terminal on OSX, I then ran: `go run hack/e2e.go -up -test -down -v`.

After leaving it running for a while and coming back i found it looping between sleep and single command:
`
Running: /Users/benjamin/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl get nodes -o template -t {{range.items}}{{.metadata.name}}:{{end}} --api-version=v1beta3
`
filling the terminal (I have unlimited scrollback enabled, but it goes back a _very_ long way of nothing but this command.

Previously I received errors seen here: https://github.com/GoogleCloudPlatform/kubernetes/pull/7032#issuecomment-98565526

**Comment by roberthbailey** [comment]
It seems like that is probably from [validate-cluster.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/validate-cluster.sh#L33) but then it should fail after 5 tries x 30 seconds = ~2.5 minutes.

**Comment by BenTheElder** [comment]
It was easily 500+ times when i came back, I pasted a chunk of them into a line counter and it came back 490. I'm going to tear down the cluster and let hack/e2e-test.sh run.

**Comment by BenTheElder** [comment]
It looks like maybe minion-2 isn't getting taken down by anything and is already up, and is somehow triggering the validation to fail.

I ran `go run hack/e2e.go -v -down` and then `vagrant destroy` before running `hack/e2e-test.sh` and saltstack provisioned master and minion then `==> minion-2: VirtualBox VM is already running.`
Then I get the same loop.

**Comment by BenTheElder** [comment]
Yep, for some reason vagrant destroy only sees the first minon and the master. I'll try killing all of the vbox headless and then getting boot2docker back up and starting from there and see what happens then.

**Comment by BenTheElder** [comment]
I'm getting a similar issue now.

````shell
[....Normal e2e building and provisioning preceeds...]

Wrote config for vagrant to /Users/benjamin/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
..Validating minion-2

Waiting for each minion to be registered with cloud provider
current-context: "vagrant"
Running: /Users/benjamin/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl get nodes -o template -t {{range.items}}{{.metadata.name}}:{{end}} --api-version=v1beta3
current-context: "vagrant"
Running: /Users/benjamin/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl get nodes -o template -t {{range.items}}{{.metadata.name}}:{{end}} --api-version=v1beta3
.current-context: "vagrant"
Running: /Users/benjamin/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl get nodes -o template -t {{range.items}}{{.metadata.name}}:{{end}} --api-version=v1beta3
.current-context: "vagrant"
Running: /Users/benjamin/code/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../cluster/../cluster/vagrant/../../cluster/vagrant/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl get nodes -o template -t {{range.items}}{{.metadata.name}}:{{end}} --api-version=v1beta3
.current-context: "vagrant"
```

the last command is run alternating with sleep continually until i ctrl+c.

**Comment by BenTheElder** [comment]
I'm still having issues with vagrant on OSX on the macbook but running hack/e2e-test.sh from https://github.com/GoogleCloudPlatform/kubernetes/commit/1b7749b8d94ad40db1d908df28ea80cee40a24ac on Fedora 21 on my desktop:
```shell
Ran 38 of 43 Specs in 678.275 seconds
SUCCESS! -- 38 Passed | 0 Failed | 1 Pending | 4 Skipped I0505 15:16:51.497160   24844 driver.go:96] All tests pass
````
I get all tests passing.

**Comment by roberthbailey** [comment]
@derekwaynecarr have you ever tried to run e2e on vagrant or is @BenTheElder treading new ground here?

**Comment by BenTheElder** [comment]
Opening Virtualbox (the managment gui) and deleting all of the master/minion boxes before running the tests again seems to improve how well the tests run, but i still get inconsistent errors. Running the tests fresh (new v-boxes) I seem to get 0-1 arbitrary failures (different tests failing) and the more times I run it without deleting them all the more failures I get. I'm thinking the performance is just bad enough on vagrant that the tests start to time out more and more, creating the inconsistent results.

The hardware I'm running on is pretty strong:  Fedora21 - 2TB hdd, 8gb 1866mhz ram, i5-2500k with the turbo maximum upped to 4.2 ghz (4 cores, no hyperthreading); and a summer 2013 macbook pro with a 2.4ghz (base clock) i7 (4 cores + ht), 250gb ssd and 8gb 1600mz ram.

I think it's possible that if the tests were given a little more time, they would all pass on vagrant when using new v-boxes.

**Comment by BenTheElder** [comment]
Looks like I can close this one for now #7978 seems to have solved it.
