### ISSUE TITLE
Coveralls fails too many PRs

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#7724]
E.g. https://github.com/GoogleCloudPlatform/kubernetes/pull/7643

Coveralls doesn't compute coverage in a way that reflects the reality of our tests, so its overall number is uncorrelated with anything we care about. Can we turn it off?

**Comment by lavalamp** [comment]
Or leave it on, but configure it to not fail PRs.

**Comment by ixdy** [comment]
"Coverage threshold for failure" is now set to 0%.

For future reference, I think anyone with ACLs on the GitHub project can adjust the Coveralls settings at https://coveralls.io/r/GoogleCloudPlatform/kubernetes.

**Comment by lavalamp** [comment]
ah, thanks-- did not know that. :)
