### ISSUE TITLE
External Load Balancer e2e tests completely broke on Sunday night (5/3 @10pm)

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#7726]
The following e2e tests are failing 100% of the time on our CI systems since 5/3/2015 22:00 PST.

There are no PR's in that vicinity that seem to be causing it.  Underlying GCE problems?

Identified problems

Services should correctly serve identically named services in different namespaces on different external IP addresses

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:401
Expected error:
    <*errors.errorString | 0xc208952040>: {
        s: "service s0 in namespace e2e-ns-2015-05-04t115826-0 doesn't have a public IP after 240.00 seconds",
    }
    service s0 in namespace e2e-ns-2015-05-04t115826-0 doesn't have a public IP after 240.00 seconds
not to have occurred

Services should be able to create a functioning external load balancer

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:352
Expected error:
    <*errors.errorString | 0xc208630030>: {
        s: "service external-lb-test in namespace e2e-ns-2015-05-04t114906-0 doesn't have a public IP after 240.00 seconds",
    }
    service external-lb-test in namespace e2e-ns-2015-05-04t114906-0 doesn't have a public IP after 240.00 seconds
not to have occurred

**Comment by quinton-hoole** [comment]
I have thus far utterly failed to reproduce this on a GCE test cluster.

**Comment by quinton-hoole** [comment]
PS: We saw this problem intermittently in #7306 , but now it's occurring 100% of the time in our CI environment.

**Comment by a-robinson** [comment]
The GCE project jenkins is running in has hit its quota for target pools, so all external load balancer related tests have been failing in all our e2e varieties.

I've deleted the old target pools (except for a half dozen I'm keeping around in case they may be useful for debugging), so the tests should go back to normal soon. The question we have to answer now is what caused all the old target pools to leak...

**Comment by a-robinson** [comment]
Closing this in favor of a bug explicitly about the target pool leak, now that the bleeding should be stopping.

**Comment by quinton-hoole** [comment]
Thanks Alex!

**Comment by quinton-hoole** [comment]
Still failing with the same errors:

May 4, 2015 8:10 PM:

Identified problems

Services should correctly serve identically named services in different namespaces on different external IP addresses

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:401
Expected error:
    <*errors.errorString | 0xc2089f4080>: {
        s: "service s0 in namespace e2e-ns-2015-05-04t202630-0 doesn't have a public IP after 240.00 seconds",
    }
    service s0 in namespace e2e-ns-2015-05-04t202630-0 doesn't have a public IP after 240.00 seconds
not to have occurred


Services should be able to create a functioning external load balancer

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:352
Expected error:
    <*errors.errorString | 0xc2089f4070>: {
        s: "service external-lb-test in namespace e2e-ns-2015-05-04t202230-0 doesn't have a public IP after 240.00 seconds",
    }
    service external-lb-test in namespace e2e-ns-2015-05-04t202230-0 doesn't have a public IP after 240.00 seconds
not to have occurred

**Comment by quinton-hoole** [comment]
We'll have to continue debugging in the morning.  Provisionally assigning to @a-robinson

**Comment by quinton-hoole** [comment]
cc @wojtek-t in case you or one of the Polish crew can take a look at this before we wake up.

**Comment by quinton-hoole** [comment]
Interestingly the test started to pass again consistently on both of our CI jobs tonight (5/4) at around 20:00.  No PR's were merged around that time. Need to dig through logs for the root cause, but for now at least the problem appears to be resolved.

**Comment by quinton-hoole** [comment]
I assume that it took a few hours for the quota to be replenished in GCE, but I don't have logs to confirm this.  Closing this bug as the tests continue to pass in our CI again.  We can re-open if we run into it again.

**Comment by a-robinson** [comment]
I'd believe that - I noticed yesterday evening that we hadn't leaked any more target pools yet ~1 hour after I deleted the old ones. I don't know whether we can see logs of target pool creation attempts though, since they unfortunately don't show up in the list of Operations.
