### ISSUE TITLE
hazelcast example is broken

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#7731]
I followed the instructions in the [tutorial] (https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/hazelcast) and got this output:
```
$kubectl get pods hazelcast
POD         IP           CONTAINER(S)   IMAGE(S)              HOST                                     LABELS           STATUS    CREATED         MESSAGE
hazelcast   10.244.0.5                                        kubernetes-minion-7jsw/130.211.122.180   name=hazelcast   Running   About an hour   
                         hazelcast      pires/hazelcast-k8s                                                             Running   9 seconds       last termination: exit code 1
```
Note the "last termination: exit code 1".

And [here] (http://pastebin.com/1mNt57Ps) is the log.

It seems to be a problem of hazelcast rather than Kubernetes. @pires @nikhiljindal

**Comment by nikhiljindal** [comment]
@pires: Cant assign the issue to you, but I assume you are the right person to look at this?

**Comment by pires** [comment]
@nikhiljindal I will take a look, yes but this has been changed recently, even by the user who just opened this ticket. How did his PR got merged without testing, I wonder?

@caesarxuchao what version of Kubernetes is this?

**Comment by caesarxuchao** [comment]
It's 0.16.0.

In that PR, I updated the .yaml files to use the latest API version (v1beta3). I tested the original .yaml files, which are using v1beta1 API, and it causes the same problem.

**Comment by pires** [comment]
@caesarxuchao my only question is why merge something that wasn't working in the first place? No harm done. I will try with your changes and without, but most probably it's something related to how the `apiserver` replies now and the library I'm using.

**Comment by caesarxuchao** [comment]
@pires I will take caution next time. Thanks.

**Comment by pires** [comment]
PR is up, please review.

**Comment by caesarxuchao** [comment]
aha, endpoints contain a list of subsets...that's why my fix to cassandra is not working yet

**Comment by pires** [comment]
@caesarxuchao yeah, tried to discuss that with you over IRC, but you don't seem to have received my messages.
