### ISSUE TITLE
v1beta2 serialization is broken on 32bit builds

### ISSUE THREAD

**Issue by chaten** [GoogleCloudPlatform/kubernetes#7745]
We have a pod which requires 2GB of memory. It looks like we are using a plain int instead of either a uint or int64 for memory requirements. 

The client is using v0.15.0 (32-bit) and the server is using v0.13.2 (64-bit)

$kubectl get pods
Error: json: cannot unmarshal number 2147483648 into Go value of type int

**Comment by roberthbailey** [comment]
Is this also broken in the v1beta3 api?

**Comment by roberthbailey** [comment]
In v1beta2 we used an IntOrString for resource quantities (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta2/types.go#L1084). In v1beta3 we use a `resource.Quantity` which is an infinite precision decimal value. So if you update to the v1beta3 api version this should no longer be a problem for you.

**Comment by chaten** [comment]
Yeah, resource.Quantity works fine and all v1beta3 uses of IntOrString are limited to port #s, which max out at uint16. So, this bug is at-least confined to old versions of the api.

**Comment by roberthbailey** [comment]
The old versions of the api have been deprecated and we plan to remove them in ~1 month as we transition to a stable v1 api.

**Comment by mikedanese** [comment]
@chaten v1beta2 no longer exists
