### ISSUE TITLE
Hyperkube image requires root certificates to work with cloud-providers (at least AWS)

### ISSUE THREAD

**Issue by viklas** [GoogleCloudPlatform/kubernetes#7750]
Testing hyperkube deployment (upgraded to v0.16.1) and I ran into an issue where controller-manager couldn't connect to the nominated cloud-provider (AWS in this instance) and threw lots of errors: "X509: failed to load system roots and no roots provided". 

Tried mounting host /etc/ssl/certs into kubelet and controller-manager pods...no good. Fixed by adding 'ca-certificates' to the apt-get command in the hyperkube dockerfile: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/images/hyperkube/Dockerfile

Happy to raise a PR for this if needed.

-Luke

**Comment by roberthbailey** [comment]
@viklas - sorry for the trouble; the hyperkube binary hasn't been tested much outside of the single and multi-node local docker getting started scenarios. 

PRs are certainly welcome!

**Comment by viklas** [comment]
Log file entry from controller-manager container for future reference.
<pre><code>E0504 05:04:37.047853       1 nodecontroller.go:175] Error syncing cloud: 
Get https://ec2.ap-southeast-2.amazonaws.com/?AWSAccessKeyId=XXX&Action=DescribeInstances&SecurityToken=XXX&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2015-05-04T05%3A04%3A37Z&Version=2014-06-15: x509: failed to load system roots and no roots provided
</code></pre>

**Comment by viklas** [comment]
This issue can be closed - PR merged successfully

**Comment by roberthbailey** [comment]
Fixed by #7755.
