### ISSUE TITLE
Target pool leak in GCE project running our jenkins e2e tests

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7753]
All of our external load balancer tests failed for the better part of a day due to the GCE project that our tests run in hitting its quota for number of target pools. While the target pools have been deleted, the fact that we hit our quota indicates that there must be a leak somewhere, and we need to plug it.

**Comment by a-robinson** [comment]
For reference, the previous issue was #7726

**Comment by quinton-hoole** [comment]
Could the leakage be related to #7681 ?  The quota exhaustion occurred about 22 hrs after that.

**Comment by a-robinson** [comment]
I'd guess that this is due to GetTCPLoadBalancer returning that the load balancer doesn't exist if the forwarding rule is gone, ignoring the target pool, while the service controller considers its deleting done if the cloud provider says that the load balancer doesn't exist. I added that logic to the cloud provider because the other implementations of DeleteTCPLoadBalancer weren't/won't be idempotent in the sense of returning ok if the LB doesn't exist.

To fix it, we'll either need to make sure all Delete implementations are idempotent and remove the Get call in the controller, or add a method along the lines of IsTCPLoadBalancerDeleted to ask the cloud provider whether all pieces of it have been completely cleaned up. We can't make GetTCPLoadBalancer check that because it's relied on to tell us whether or not the balancer is fully created.

**Comment by a-robinson** [comment]
Copying over my commentary from #8377 on why the GKE e2e tests are leaking so many forwarding rules and target pools vs the GCE tests:

> It's very odd that it's affecting GKE so disproportionately, though. After cleaning up the target pools whose forwarding rules were gone, all the non-soak-test target pools belonged to GKE, which indicates that GKE isn't just leaking target pools, it's also leaking forwarding rules.
> 
> The first thing that strikes me about that is that it's very possibly happening on the occasions when the services tests are the last ones run, and the cluster gets torn down before the service controller has had time to clean up. This is happening in GKE but not in GCE because GKE tears down all resources in parallel, while the GCE script synchronously waits for all nodes to be deleted before deleting the master.

**Comment by roberthbailey** [comment]
Is there a way for the services test to wait for the service controller to clean up the external resources before finishing (without just doing a sleep)?

**Comment by a-robinson** [comment]
Not without polling GCE directly for whether the resources still exist, although that may be worth it as a workaround.

What would be perfect is that clean-up-all-cloud-provider-resources API method that we talked about a couple months ago.

**Comment by quinton-hoole** [comment]
Can we not perhaps use GCE namespaces or projects as a cheap way of getting this here?

**Comment by a-robinson** [comment]
I don't believe so. We can't use projects due to the fact that projects can't be programatically created (they're intended to be long-lived). I'm not aware of anything along the lines of a GCE namespace other than networks, which won't work because target pools and forwarding rules unfortunately don't seem to be scoped to networks.

**Comment by a-robinson** [comment]
The target pool leak in the code might be fixed, but the forwarding rule + target pool leak from deleting GKE clusters too quickly is certainly still happening. Reopening for the sake of that half of the issue.

**Comment by a-robinson** [comment]
Can we just add a short sleep to jenkins after the last test has run before it deletes anything?

**Comment by quinton-hoole** [comment]
Yes, you could add a sleep to Ginkgo's AfterEachSuite():

http://onsi.github.io/ginkgo/#global-setup-and-teardown-beforesuite-and-aftersuite

But I'd be concerned about what the upper bound on the sleep period is.  Can we get the tests and code in sync with a 1 minute latency here? (e.g. if the controller garbage collects every 60 seconds, then the test only needs to sleep for 60 sec?)  And add a BEEG comment to the test's sleep config noting that increasing the sleep time will not improve things, otherwise I'm pretty sure that someone noting flakes in this test in future will think "maybe I should just increase the sleep period a little bit."

**Comment by quinton-hoole** [comment]
Actually, thinking about this a little more, it would be better to put the "sleep" logic in the k8s master teardown procedure (i.e. not in the e2e tests or in Jenkins), because otherwise users are going to run into the same resource leakage problems as we are.  So master deletion blocks on cleanup of backend cloud resources.

**Comment by roberthbailey** [comment]
There's no way to block master deletion from the master itself. The test framework (or user) just pulls the rug out from underneath the master. See https://github.com/GoogleCloudPlatform/kubernetes/issues/4630.

**Comment by a-robinson** [comment]
Robby's right -- #4630 is the real solution to this, but until we have that the best we can do is to have the wait happen elsewhere. The options seem to be:

1. in GKE itself
1. in Ginkgo's post-testing logic
1. in Jenkins' teardown logic

I don't like putting it in GKE, because arbitrarily slowing down our API makes for a poor experience for the majority of people that don't still have resources being deleted.

I'm not eager to put it in Gingko either, since won't that sleep also take effect whenever anyone runs an e2e test locally against a dev cluster?

Putting it in the Jenkins logic makes the most sense to me. I'll send a PR and cc you.

**Comment by a-robinson** [comment]
We may also want to change the kube-down logic to bring down the master and then nodes in parallel to both speed it up and more closely resemble GKE's teardown logic.

**Comment by a-robinson** [comment]
I've deleted the old forwarding rules and target pools from the project. I'll periodically check to see whether anything is leaked after this point. I apologize if the deletions affected any running tests - everything looked to only be from GKE and parallel e2e runs.
