### ISSUE TITLE
Kubelet does not start

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#7762]
I'm trying to start 100-node cluster. I got the following error in kubelet:

E0505 08:31:55.170878    5066 server.go:457] Failed to create kubelet: failed to initialize image manager: failed to start image manager: dial unix /var/run/docker.sock: connection refused

After ssh-ing I checked that docker is working by running ```sudo docker ps```. I guess it must be some kind of a race where kubelet starts before docker is ready.

When I start 3-node cluster it works just fine.

This happened to me 3 times in a row.

@wojtek-t @dchen1107 

@dchen1107 Please add this to 1.0 milestone if necessary.

**Comment by wojtek-t** [comment]
I've just faced exactly the same problem (when creating a 100-node cluster)

**Comment by fgrzadkowski** [comment]
@davidopp

**Comment by dchen1107** [comment]
This is a bug in our initialization logical. We initialize image manager which needs to talk to docker at very early stage before docker is up yet. Later kubelet does a wait to make sure docker is up. We should either delay the initialization of image manager or handle docker unavailable better. 

Kubelet will be restarted by monit eventually, but this definitely slow down node initialization. I mark this for 1.0. Should be a simple fix if we just simply delay the initialization of image manager.

**Comment by vmarmol** [comment]
I'll go ahead and fix it (since I am mainly to blame :) )

**Comment by davidopp** [comment]
Changed to P0 because @brendandburns asked us to only add P0 issues to v1.0 milestone.
