### ISSUE TITLE
Slow etcd

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#7767]
After recent performance fixes we are now not bound by CPU or disk IOPS. Apiserver during density test uses around 80% of CPU. Still we observe high request latency for pods, events, endpoints and sometimes other resources. I was able to narrow this down to slow etcd.

Etcd uses up to 80% of CPU. For some reason we see high latency of requests to etcd. Increasing disk (to increase IOPS) or number of cores doesn't help. In order to meet criteria defined in 1.0 roadmap (#4521) we have to make it much faster.

@xiang90 Do you have some suggestions how to debug this? Any ideas what could be the reason?

@wojtek-t @davidopp @xiang90

**Comment by wojtek-t** [comment]
@xiang90 a related question: from the etcd code it seems that etcd is exposing some metrics under /metrics handler:
https://github.com/coreos/etcd/blob/master/etcdserver/etcdhttp/client.go#L100
 However, when accessing this handler I'm getting 404 error (both with 2.0.9 and 2.0.10 etcd versions). Do you know what could be the reason?

**Comment by xiang90** [comment]
@fgrzadkowski @wojtek-t You can try with etcd 2.1.0-alpha0, which gives you a better performance, less CPU usage and the /metrics endpoint (though it is still expr).

**Comment by fgrzadkowski** [comment]
@xiang90 Thanks! We will give it a try. Does etcd export pprof data so that we can profile it for lock contention?

**Comment by wojtek-t** [comment]
>
@fgrzadkowski @wojtek-t You can try with etcd 2.1.0-alpha0, which gives you a better performance, less CPU usage and the /metrics endpoint (though it is still expr).

Thanks - we will try it. So far I downloaded it locally and indeed it has /metrics endpoint. Thanks!

**Comment by xiang90** [comment]
@fgrzadkowski Not really. If you have time, I think the first thing you can do is to switch the default json encoder to ffjson. 

Do you know how much performance do you actually need in terms of write/read?

**Comment by wojtek-t** [comment]
@xiang90 currently we are focusing more on latency. The issue that we observed is that when reading from etcd the whole directory (which is ~3000 entries, each entry of size ~2kB), it can take more than 2 seconds (which seems to be a lot).

**Comment by xiang90** [comment]
@wojtek-t Yea... That is probably caused by slow json encoding... :(

**Comment by fgrzadkowski** [comment]
@xiang90 If that's parsing json shouldn't it mean that there is high CPU usage?

**Comment by xiang90** [comment]
@fgrzadkowski 

```
Etcd uses up to 80% of CPU. For some reason we see high latency of requests to etcd. Increasing disk (to increase IOPS) or number of cores doesn't help.
```

This is what you told me. :) So I highly suspect it is caused by encoding after you gave me more context.

**Comment by fgrzadkowski** [comment]
So you're saying that this json encoding happens under lock so that we cannot use more CPU because other requests are blocked. Is my understanding correct?

Can you point us where this encoding happens?

**Comment by fgrzadkowski** [comment]
To clarify - by ```80% of CPU``` I meant ```80% of 1 core```. Sorry for not being clear

**Comment by xiang90** [comment]
@fgrzadkowski The encoding happens without holding any lock: https://github.com/coreos/etcd/blob/master/etcdserver/etcdhttp/client.go#L527.

You give etcd multiple cores, and it only uses 80% of one? Is this what you are saying? I still do not quite follow actually.

**Comment by quinton-hoole** [comment]
@xiang90 ffjson seems like a great improvement if the 2x benchmark comparisons vs golang json encoding materialize.  Thanks!

However I can't help noticing that that even ffjson is more than 30x slower than some protobuf implementations (according to the benchmarks published at https://journal.paul.querna.org/articles/2014/03/31/ffjson-faster-json-in-go/)

Have you considered adding a protobuf-based API to etcd to boost performance?

Obviously in the short term we might be able to simply "throw cores at the problem", but over time I think that this will become expensive, and a protobuf interface might make sense.

**Comment by xiang90** [comment]
@quinton-hoole Take a look at: https://github.com/coreos/etcd/pull/2675

**Comment by quinton-hoole** [comment]
Beautiful :-)

**Comment by fgrzadkowski** [comment]
@xiang90 Let me start from the beginning :)

In my test setup master is n1-standard-8 (i.e. 8 cores) machine with 2 PD-SSD disks each 200GB. Under high load generated by density tests total cpu utilization is about 50% (i.e. we use on average 4 cores out of 8). There are two biggest CPU consumers:
* apiserver -> usually up to 3 cores
* etcd -> usually up to 0.8 core (never above 1)

With this setup we observe high latency in requests to etcd that list directories with 3000 entries each ~2kB. For some reason etcd does not use all the cpu it could.

I tried to look if etcd changes GOMAXPROCS. It seems it doesn't:
https://github.com/coreos/etcd/search?utf8=%E2%9C%93&q=GOMAXPROCS&type=Code
Maybe this is the reason? As a result etcd cannot consume more than 1 core?

**Comment by quinton-hoole** [comment]
@xiang90 BTW, I would be careful not to conflate JSON and HTTP vs Protobuf and RPC.  e.g. One can do Protobuf over HTTP without RPC, and still get most of the performance gains.  I'll comment further in the etcd RFC.

**Comment by xiang90** [comment]
@fgrzadkowski Yes. You have to give more cores to etcd to let it use more.

**Comment by xiang90** [comment]
@quinton-hoole We plan to use gRPC, which is protobuf over http2 basically. But we might choose protobuf over plain http with a /rpc endpoint in the end. Not sure yet.

**Comment by bgrant0607** [comment]
cc @hchoudh

**Comment by fgrzadkowski** [comment]
@xiang90 Is it just a regular env variable? I've only changed this using https://golang.org/pkg/runtime/#GOMAXPROCS

**Comment by xiang90** [comment]
@fgrzadkowski Yes. It is.

**Comment by fgrzadkowski** [comment]
Perfect! I'll give it a try tomorrow.

**Comment by fgrzadkowski** [comment]
This improved stats a lot! The only offending ones (high percentiles above 1s) are listing pods and events:
```
apiserver_request_latencies_summary{resource="events",verb="LIST",quantile="0.5"} 3.97932e+06
apiserver_request_latencies_summary{resource="events",verb="LIST",quantile="0.9"} 5.502931e+06
apiserver_request_latencies_summary{resource="events",verb="LIST",quantile="0.99"} 6.830431e+06
apiserver_request_latencies_summary_count{resource="events",verb="LIST"} 49

apiserver_request_latencies_summary{resource="pods",verb="LIST",quantile="0.5"} 302178
apiserver_request_latencies_summary{resource="pods",verb="LIST",quantile="0.9"} 1.79934e+06
apiserver_request_latencies_summary{resource="pods",verb="LIST",quantile="0.99"} 2.244904e+06
apiserver_request_latencies_summary_count{resource="pods",verb="LIST"} 395
```
I'll look into this today.

**Comment by fgrzadkowski** [comment]
(Just to be clear - this is still on 8 core master with fast drives)

**Comment by xiang90** [comment]
@fgrzadkowski I guess 2 core is enough. Also the read latency has very little thing to do with seek latency. Everything in etcd is in memory for the moment.

**Comment by wojtek-t** [comment]
@xiang90 Regarding disk - out experiments confirm that seek latency doesn't really matter here.
I'm not sure what the difference will be between setting GOMAXPROCS e.g. to  2 and to 4 (we should check it).

**Comment by timothysc** [comment]
@fgrzadkowski so for clarity, did you: 
 
export GOMAXPROCS=`nproc`
etcd --myparams ?

**Comment by fgrzadkowski** [comment]
@timothysc Yes. For testing I've just hardcoded this. I'll send PR tomorrow that will automatically set this based on the number of cores.
One thing to mention that we still don't use all 8 cores. According to some further debugging now the bottle neck is on apiserver side. I'll debug more tomorrow.
