### ISSUE TITLE
Consider using ffjson instead of default encoding/json

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#7768]
Currently, unmarshaling jsons is a significant factor influencing the overall Kubernetes performance. 
We should investigate and consider replacing the default encoding/json with ffjson:
https://github.com/pquerna/ffjson

cc @fgrzadkowski @lavalamp @smarterclayton @davidopp

**Comment by smarterclayton** [comment]
ugorji/go-codec is strictly better than ffjson.

----- Original Message -----

**Comment by lavalamp** [comment]
We already have an issue on this- #3338. Please continue discussion there.
