### ISSUE TITLE
Adding Red Flag Performance Regression in e2e tests.

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#7790]
Currently e2e tests will pass based on overall behavior.  Currently we do track performance but we do not gate the overall tests.   It seems logical that we would want to have some baseline to detect regression and simply raise the red flag under those conditions.  

e.g. create a utility function that checks
1. if overall average falls below 10 pods/sec. 
2. if terminated pods > 2% of total pod count 
...

/cc @wojtek-t @fgrzadkowski @rrati @jayunit100 @roberthbailey

**Comment by wojtek-t** [comment]
@fgrzadkowski already started adding some expectations on performance (although we need to tune them) - see #7505

**Comment by timothysc** [comment]
@fgrzadkowski @wojtek-t  

It's been a while since we had our test day and we've noticed a fairly large drop in overall throughput.

**Comment by fgrzadkowski** [comment]
@timothysc We have also noticed, but couldn't find the reason. I plan to look more into it today.

**Comment by timothysc** [comment]
@fgrzadkowski just as a note of color, but we used the same technique outlined in https://github.com/GoogleCloudPlatform/kubernetes/pull/7573 to track and uncover the regression.

**Comment by timothysc** [comment]
At this stage in the cycle, I'm more inclined to have a script that runs independent of the e2es and the end rip through and check for regression then I am in adding new ways for the tests to fail.

**Comment by timothysc** [comment]
So we have scripts now that churn on the output from e2e to raise a flag when needed.
