### ISSUE TITLE
Kubectl lists resources in all namespaces with *

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#7793]
Would be nice if we could list all namespaces by doing eg: `get rc --namespace=*` as that's likely the first thing most people will try (at least true for @lavalamp and myself). When that didn't work I resorted to a bash script that parsed out the namespace from logs instead of reading up about kubectl, so there might be a way to achieve exactly the same with a different syntax but people might not discover it.

**Comment by derekwaynecarr** [comment]
see https://github.com/GoogleCloudPlatform/kubernetes/pull/7024

**Comment by bprashanth** [comment]
Closed via #7024
