### ISSUE TITLE
Grouping a list of unknown containers into a pod for container/image management

### ISSUE THREAD

**Issue by yujuhong** [GoogleCloudPlatform/kubernetes#7807]
The container runtime interface in kubelet sticks to the pod-level abstraction for most of the functions. There are two components that do not handle this interface well:
- `containerGC`: It needs access to all containers managed by kubelet in order to determine whether or not to remove them. This includes all containers starting with the `k8s_` prefix. Note that these containers may not have a valid pod name due to changes to the naming convention that are incompatible.  
- `imageManager`: It needs to know all the containers running on the node, whether managed by kubelet or not (e.g. if a image is used by any container, it cannot be removed).

The easier solution is to support retrieving a list of containers in the container runtime interface, but this is not clean. @vmarmol suggested that `GetPods` should return a single pod encompassing all the unknown containers. Based on the two requirements above, we'd need at least two different kinds of unknown pods (one for `k8s_` containers, and the other for the rest of the unidentified containers). If we go with this route, what UID/name should we use for the pods? We don't want naming conflict that'd affect user-created pods. Thoughts?

/cc @vmarmol, @dchen1107, @yifan-gu

**Comment by vmarmol** [comment]
I think you're the naming expert @yujuhong :) but maybe we can use unallowed characters?:

- "/unknown-kubernetes"
- "/unknown-containers"

**Comment by vmarmol** [comment]
We could also use this mapping for the killing in `SyncPod` so that can be parallelized too. Eventually, we'd probably extend the life of the podWorker to match that of the pod, but this is a start.

**Comment by yujuhong** [comment]
Assigning to me since I'm working on it. Thanks for the suggestions!

**Comment by yifan-gu** [comment]
SGTM

**Comment by yujuhong** [comment]
We've decided to let individual container runtime implements image management and container GC due to the drastic difference of abstraction in rkt and docker. Closing this issue.
