### ISSUE TITLE
nfs example link broken

### ISSUE THREAD

**Issue by thoraxe** [GoogleCloudPlatform/kubernetes#7810]
This page:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md

Links to this YAML:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/nfs/test.yaml

Which doesn't exist.

There are several examples now in the NFS folder:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/nfs

**Comment by mbforbes** [comment]
Thanks for reporting! Always happy to get docs up-to-date, especially to reduce friction. Please report / open PRs for any others. Also, if the examples / explanations aren't clear, we're happy to address issues for that as well.
