### ISSUE TITLE
missing public IP in examples/logging-demo

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#7818]
Hi @satnam6502 @nikhiljindal , I followed the instructions in examples/logging-demo, and there was no "external IP" field for elasticsearch-logging or kibana-logging, as shown below:
```json
../../_output/local/bin/linux/amd64/kubectl get services kibana-logging -o json
{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "kibana-logging",
        "namespace": "default",
        "selfLink": "/api/v1beta3/namespaces/default/services/kibana-logging",
        "uid": "9dc6f856-f358-11e4-a58e-42010af09a93",
        "resourceVersion": "31",
        "creationTimestamp": "2015-05-05T18:57:45Z",
        "labels": {
            "kubernetes.io/cluster-service": "true",
            "name": "kibana-logging"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "",
                "protocol": "TCP",
                "port": 5601,
                "targetPort": "kibana-port"
            }
        ],
        "selector": {
            "name": "kibana-logging"
        },
        "portalIP": "10.0.188.118",
        "sessionAffinity": "None"
    },
    "status": {}
}
```
I start up my cluster via cluster/kube-up.sh. Did I miss something or is it a bug? Thanks.

**Comment by satnam6502** [comment]
Correct. This demo does not create an ELB so there is no external IP address.
Access is via service proxy at the master.
Type:
```
$ kubectl cluster-info
```
and you should the URLs for Elasticsearch and Kibana.

**Comment by mbforbes** [comment]
@caesarxuchao please let us know whether:
  a. Satnam's comment resolves your issue
  b. the demo should be updated to prevent this misunderstanding
  c. the issue isn't resolved

Thank you!

**Comment by caesarxuchao** [comment]
Yes, Satnam's comment resolve the issue. I updated the demo in #7824.

**Comment by mbforbes** [comment]
Awesome, thanks for sending the patch! We'll discuss there. Always fantastic to have docs updated regularly by folks trying them.
