### ISSUE TITLE
`kubectl help get` is outdated

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#7842]
I know that you can get nodes / a node, but the help doesn't say you can or provide examples:

```
$ kubectl help get
Display one or many resources.

Possible resources include pods (po), replication controllers (rc),
services (svc), minions (mi), or events (ev).
```

To resolve this issue:

0. Update the help for this command to include nodes (and any other resources we're missing).

0. Can we generate the help text in a way that ensures this (and probably the many others that are drifting) don't get out of date? Or at least give us a heuristic as to whether this might be true, even if we have to fix it manually?

**Comment by andronat** [comment]
Can this be closed?

**Comment by jlowdermilk** [comment]
I'll close this one with #8240; we want to get rid of the minions (mi) resource name, since it doesn't work for v1beta3.
