### ISSUE TITLE
similar labels in replication controller file is getting a strange behavier on containers in minions 

### ISSUE THREAD

**Issue by Andre-Freitas** [GoogleCloudPlatform/kubernetes#7844]
Hi,

I tried to create a rc (http://fpaste.org/219062/09288701/) with these 2 labels as selectors

            "role": "lb",
            "role2": "logstash"

but when i try to `kubectl create -f` that rc ,  my minions start to have a lot of containers in status "Exited ..." and my pod, that is managed by this rc, is always being recreated (http://fpaste.org/219068/30929634/).

If i change that rc to use 2 different labels (http://ur1.ca/kb200)

      "elastic-role":"lb",
      "service":"logstash"

the pod creation works fine.

Should all labels be different from each other or is this a bug in the way that pods are managed by kubernetes?

**Comment by lavalamp** [comment]
This doesn't seem like expected behavior, and I'll be surprised if the labels are really the root cause. Can you look at log files from terminated containers to see if there are any clues?

**Comment by Andre-Freitas** [comment]
I have found the problem - same of labels defined to that rc where being used in another rc and that was causing the pods to be always spaning in pairs.
