### ISSUE TITLE
Proposal: configurable proxyPort for kube-proxy

### ISSUE THREAD

**Issue by jdef** [GoogleCloudPlatform/kubernetes#7846]
Currently the addServiceOnPort invocation specifies a random port.

https://github.com/GoogleCloudPlatform/kubernetes/blob/release-0.16/pkg/proxy/proxier.go#L431

When running on Mesos we need to account for all server (listening) ports. I'd like to propose a PortAllocator interface that we can leverage for this purpose:
```go
interface PortAllocator {
  AllocateNext() (int, error)
  Release(int)
}
```
A default implementation for allocating a `proxyPort` would simply have AllocateNext() always return 0 and Release() as a noop, maintaining current behavior. A range-based implementation would be configured with one or more port ranges and allocate from those. This would be configurable via kube-proxy flag.

It looks like someone has already started down the path of port allocation, albeit for portals.
https://github.com/GoogleCloudPlatform/kubernetes/pull/6684

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/257

**Comment by thockin** [comment]
You want this for all ports or just public ports?  The problem, of course,
is that once you do anything but "dear kernel, please choose for me" you
risk conflicts with any pod host ports that might be chosen

**Comment by jdef** [comment]
We want this for ports that the proxy will listen on because that consumes
host port resources.
The k8s-mesos integration is already handling accounting for pod host
ports, allocating them from mesos resource offers. The next biggest
"abuser" (allocating ports outside of resource offers) is the proxy.

Also, we can we label this "mesos" (port allocation is not mesos specific
concept, but we sure do want this).


On Wed, May 6, 2015 at 6:51 PM, Tim Hockin <notifications@github.com> wrote:

> You want this for all ports or just public ports? The problem, of course,
> is that once you do anything but "dear kernel, please choose for me" you
> risk conflicts with any pod host ports that might be chosen
>
> On Wed, May 6, 2015 at 10:35 AM, James DeFelice <notifications@github.com>
> wrote:
>
> > xref mesosphere/kubernetes-mesos#257
> > <https://github.com/mesosphere/kubernetes-mesos/issues/257>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/GoogleCloudPlatform/kubernetes/issues/7846#issuecomment-99546020
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/7846#issuecomment-99634583>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by thockin** [comment]
I'm not against this in principle.  Maybe a flag like
`--proxy-port-range=20000-29999` with a default of "0-0" or "".  We need to
reconcile this with the cluster-wide public service ports that @justinsb is
doing.

If you sent a patch to this effect, we could discuss.

**Comment by jdef** [comment]
closing this out since the related PR has been merger
