### ISSUE TITLE
rkt: Remove glibc dependency

### ISSUE THREAD

**Issue by vmarmol** [GoogleCloudPlatform/kubernetes#7850]
Splitting from #7805. It looks like when we include rkt we take in a dependency on `GLIBC_2.14` which we don't have on our Debian systems. It seems that this is due to some code in 

```
github.com/coreos/rkt/store
```

which we import. Is the dependency needed or can we replace it somehow with a rkt invocation?

@yifan-gu can you take a look?

/cc @dchen1107 @yujuhong @jonboulle @bakins

**Comment by yifan-gu** [comment]
Sure

**Comment by yifan-gu** [comment]
@vmarmol After a quick look, I think we can remove the dependency of `github.com/coreos/rkt/store` by using the new `rkt images` command.

**Comment by yifan-gu** [comment]
Let me fix this :)
