### ISSUE TITLE
The node status' LastHeartBeatTime should be set in the master

### ISSUE THREAD

**Issue by fabioy** [GoogleCloudPlatform/kubernetes#7866]
It looks like the NodeCondition's LastHeartbeatTime field is set from the kubelet (see "tryUpdateNodeStatus()" in pkg/kubelet/kubelet.go). This may give a greater variance if different nodes have different clocks times. This should be changed to be set at the master at the moment it receives the node status update.

Overall this may not be that big of a deal, but some monitoring decisions may be based upon this time, like determining if the last heartbeat time has "expired" (i.e. was too long ago). Using the master's clock for all nodes may provide more consistency.

**Comment by bprashanth** [comment]
fyi: https://github.com/GoogleCloudPlatform/kubernetes/issues/6159, https://github.com/GoogleCloudPlatform/kubernetes/issues/6193

**Comment by davidopp** [comment]
As @bprashanth mentioned, @gmarek fixed this in #6217. (Unless we're misunderstanding what you're talking about.) Please reopen this issue if you think it is still not fixed (and explain in more detail).
