### ISSUE TITLE
There should be a getting started guide for setting up Kubernetes from scratch

### ISSUE THREAD

**Issue by ghodss** [GoogleCloudPlatform/kubernetes#7871]
There should be a guide on how to take Kubernetes and run (and optionally package) it yourself. The current [Getting Started Guides](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides) mostly instruct on how to use cluster/kube-up.sh or give you a preconfigured set of steps, instead of teaching how to set up a Kubernetes cluster from scratch for your own environment. 

This guide would explain what binaries/Docker images need to run to have a functioning cluster and how to configure them for your environment. We're happy to take a stab at starting such a document but wanted to open this issue to get feedback on whether something like this existed, where it should go, how it should be structured, etc.

**Comment by thockin** [comment]
Each of the existing docs started that way :)  I think it would be a good
doc, but you'll have to be clear where there are choices and you are just
choosing one option (e.g. net)

**Comment by mbforbes** [comment]
This strikes me as:

0. a great idea
0. difficult to keep synced with the deployment process as it evolves
0. difficult to make clear because of branching options (as Tim mentioned)

I don't think 2 and 3 outweigh 1, though, and at the very worst case it would be an extremely useful blog post to have, at least for a snapshot of where Kubernetes is now.

**Comment by ghodss** [comment]
The best case is that this doc would be what the maintainers use as the primary way to communicate how the daemon interfaces and setup steps are evolving, and therefore be the guide for all the developers of the cluster scripts.

**Comment by erictune** [comment]
Some suggested content, copied from #8523:

--------
don't serve insecurely on 0.0.0.0. Remove the --public_address_override argument from your apiserver so it only serves the insecure port on 127.0.0.1, not 0.0.0.0 like it is now.
change kubelet to have --api_servers=https://kube-master:6443 argument.
Your kubelet doesn't need an --etcd_servers argument when it has a --api_servers argument.
Put a token in the apiservers known_tokens.csv, per docs/authentication.md
Put the token where the kubelet can use it, like this: echo "{\"BearerToken\": \"${KUBELET_TOKEN}\", \"Insecure\": true }" > /path/to/kubelet_auth.json
Tell kubelet to use that file, like --auth_path=/var/lib/kubelet/kubernetes_auth flag. 
```

**Comment by erictune** [comment]
working on this now.

**Comment by erictune** [comment]
Fixed by #10271
