### ISSUE TITLE
Need correct error message for v1beta1 template 

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#7877]
When using v1beta1 template, if there're errors occured, k8s will return error messages in other format. For example, if `containerport` in the v1beta1 template is out of range, the error message will say `targetport` is invalid. 

In the case above, at first I was confused for I looked into the whole template and didn't find a field named as `targetport`. After I looked into the code I found it's because the template is converted into internal structure, but would that be better to return error messages still in v1beta1 format?

Also for template in other versions, what I want to say is to return error message with names in the template instead of internal porperty names.

**Comment by mbforbes** [comment]
+cc @bgrant0607 is this an issue beyond v1beta1?

**Comment by nikhiljindal** [comment]
This is because the validation happens on internal structs. We have talked about doing versioned validation which should fix this: https://github.com/GoogleCloudPlatform/kubernetes/pull/4575#issuecomment-75172955

Closing this as dup of https://github.com/GoogleCloudPlatform/kubernetes/issues/3084

**Comment by bgrant0607** [comment]
Yes, this will soon be a non-issue for a while, since we're going to eliminate v1beta1. :-)
