### ISSUE TITLE
ReplicationController creation with replicas '0' should fail 

### ISSUE THREAD

**Issue by madhuri-rai07** [GoogleCloudPlatform/kubernetes#7882]
$ kubectl get rc frontend -o json
{
    "kind": "ReplicationController",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "frontend",
        "namespace": "default",
        "selfLink": "/api/v1beta1/replicationControllers/frontend?namespace=default",
        "uid": "d8eede77-f47e-11e4-97c8-fa163ef2733e",
        "resourceVersion": "9",
        "creationTimestamp": "2015-05-07T06:03:57Z",
        "labels": {
            "name": "frontend"
        }
    },
    "spec": {
        "replicas": 0,
        "selector": {
            "name": "frontend"
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "name": "frontend"
                }
            },
            "spec": {
                "volumes": null,
                "containers": [
                    {
                        "name": "php-redis",
                        "image": "kubernetes/example-guestbook-php-redis:v2",
                        "ports": [
                            {
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "imagePullPolicy": "IfNotPresent",
                        "capabilities": {}
                    }
                ],
                "restartPolicy": "Always",
                "dnsPolicy": "ClusterFirst"
            }
        }
    },
    "status": {
        "replicas": 0
    }
}

**Comment by nikhiljindal** [comment]
Sounds reasonable to me.
@bgrant0607 

I believe we need to update https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L1090 to fix this.

**Comment by nikhiljindal** [comment]
The default value of replicas is 0 right now, so we will have to update the default value to 1 before making the above change: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/defaults.go#L29

**Comment by bgrant0607** [comment]
@madhuri-rai07 Could you please explain why you would like this to fail? Would changing the default to 1 improve your experience? It's something we plan to do - #6700.

We can't make 0 invalid, however. We need to support that for a number of use cases, such as scaling down to 0 and rolling updates.

**Comment by madhuri-rai07** [comment]
@bgrant0607 Does creating a rc with replicas 0 make sense? If yes, then it should not fail and if it doesn't so should it should fail with error invalid value.
Other use cases that are being done after rc is created like scaling down to 0 or more make sense to have replicas 0.

And the default value should be 1.

**Comment by bgrant0607** [comment]
Yes, it does make sense.

I'm glad you agree with the change of default value.

Thanks.
