### ISSUE TITLE
Problem on updating pods with file 

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#7884]
I created a pod with 'pod1.yaml' under `examples/walkthrough` directory by `kubectl create -f pod1.yaml`,
then I modified 'pod1.yaml' changing `image: nginx` to `image: my/nginx`, then I tried to update the pod with `kubectl update -f pod1.yaml`
An error message returns which says:

    Error: Pod "www" is invalid: spec: invalid value '{Volumes:<nil> Containers:[{Name:nginx Image:my/nginx Command:<nil> Args:<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:map[] Requests:map[]} VolumeMounts:<nil> LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<*>(0xc2083c8360){Capabilities:<*>(0xc2086751d0){Add:<nil> Drop:<nil>} Privileged:<*>(0xc2081b98d8)false SELinuxOptions:<nil> RunAsUser:<nil>}}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:<nil> Host: HostNetwork:false}': may not update fields other than container.image

I tried to use `kubectl update pods www --patch='{"apiVersion": "v1beta1","desiredState": {"manifest": {"containers": [{"image": "my/nginx"}]}}}'` and `kubectl update pods www --patch='{"apiVersion": "v1beta3", "spec": {"containers": [{"image": "my/nginx"}]}}'`, they both returned the same error.

It seems that those fields which are not required while creating are required while updating. Can we use the existing value of old resources for those fields while updating? Actually I had a similar problem before, see #5907

BTW, use patch to update an resource isn't easy, look at the length of the commands, so I would prefer use `-f` option.

**Comment by nikhiljindal** [comment]
Not sure why patch is failing but update does require all the fields.
To update your object:
* Run ```kubectl get pods www -o yaml > /tmp/pod1.yaml``` 
* Modify /tmp/pod1.yaml as you want and then 
* Run ```kubectl update -f /tmp/pod1.yaml```

**Comment by nikhiljindal** [comment]
Re patch: What you want is a strategic merge patch as described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#strategic-merge-patch.
Unfortunately, you cant perform a strategic merge patch via kubectl.

**Comment by nikhiljindal** [comment]
cc @ghodss

**Comment by hurf** [comment]
@nikhiljindal - I missed the container name in the patch command, now I can update it with patch.

I also tried to export the pod to file, then modify it to update the pod. It works. But it seems the exported file can only be modified and used for only once because it contains version number of old resource. I think it prevents the template to be portable.

**Comment by nikhiljindal** [comment]
Yes you need to do a get each time before updating.

Re: patch. Can you please post the command that works for you. The following command gives me the same error:
```kubectl update pods www --patch={"apiVersion": "v1beta3", "spec": {"containers": [{"name": "www", "image": "my/nginx"}]}}```

**Comment by hurf** [comment]
@nikhiljindal - Actually in my office there're 2 enviroments for testing k8s, one standalone hosted on my pc and another one with multi minions on a cloud enviroment. When I want to update something and keep them synchronized in two enviroments, I had to export the file and modify it twice. That's why I say it prevents the template to be portable. I think maybe we can make some improvement on this update operation, from a user's sight.

About the patch command, it's almost the same as you given except the container name is 'nginx', 'www' is the pod's name.

**Comment by nikhiljindal** [comment]
Not sure if something broke recently, but I just tried the following and it failed
```./cluster/kubectl.sh update pods www --patch='{"apiVersion": "v1beta3", "spec": {"containers": [{"name": "nginx", "image": "my/nginx"}]}}'```

```
Error from server: Pod "www" is invalid: spec: invalid value '{Volumes:[{Name:default-token-5cpor VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:<*>(0xc2094f5990){SecretName:default-token-5cpor} NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaimVolumeSource:<nil>}}] Containers:[{Name:nginx Image:my/nginx Command:<nil> Args:<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:<nil> Requests:<nil>} VolumeMounts:<nil> LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<*>(0xc2094e8c20){Capabilities:<*>(0xc209aa2b10){Add:<nil> Drop:<nil>} Privileged:<*>(0xc2094f5985)false SELinuxOptions:<nil> RunAsUser:<nil>}}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:<nil> ServiceAccount:default Host:127.0.0.1 HostNetwork:false}': may not update fields other than container.image
```
