### ISSUE TITLE
Documentation on KUBE_ADMISSION_CONTROL, all configuration variables?

### ISSUE THREAD

**Issue by dermusikman** [GoogleCloudPlatform/kubernetes#7895]
As the title suggests, I can find no documentation on KUBE_ADMISSION_CONTROL (from the apiserver configuration), and I don't know golang well enough to determine the answer (yet) from the source code. Google search yields only 3 hits today, and all of them are copies of the configuration file itself with no commentary.

As an admin, I'd be grateful for simple documentation on all the variables, their possible settings, and what those really mean. If that already exists, please identify where it exists.

Though my formal issue is the documentation, the problem that leads me here is that my pods can't query the apiserver. Given the following, my connection is reset:
```
[root@my-pod-abcdef /]# env | grep KUBE
KUBERNETES_RO_PORT=tcp://10.250.0.1:80
KUBERNETES_RO_SERVICE_HOST=10.250.0.1
KUBERNETES_PORT=tcp://10.250.0.2:443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_RO_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT=443
KUBERNETES_RO_PORT_80_TCP_PORT=80
KUBERNETES_SERVICE_HOST=10.250.0.2
KUBERNETES_RO_PORT_80_TCP_PROTO=tcp
KUBERNETES_RO_PORT_80_TCP_ADDR=10.250.0.1
KUBERNETES_RO_PORT_80_TCP=tcp://10.250.0.1:80
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.250.0.2
KUBERNETES_PORT_443_TCP=tcp://10.250.0.2:443
[root@my-pod-abcdef /]# curl -v http://10.250.0.1:80/api/v1beta3/pods
* About to connect() to 10.250.0.1 port 80 (#0)
*   Trying 10.250.0.1...
* Connected to 10.250.0.1 (10.250.0.1) port 80 (#0)
> GET /api/v1beta3/pods HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.250.0.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
[root@my-pod-abcdef /]# curl -v https://10.250.0.2:443/api/v1beta3/pods
* About to connect() to 10.250.0.2 port 443 (#0)
*   Trying 10.250.0.2...
* Connected to 10.250.0.2 (10.250.0.2) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer
[root@my-pod-abcdef /]#
```

Any assistance would be greatly appreciated, though my formal issue remains the lack of thorough documentation on the configuration. I'll continue learning golang in order to try to figure out what my problem may be.

**Comment by derekwaynecarr** [comment]
I agree a document is needed, will look to put something together describing what each option does.

**Comment by dermusikman** [comment]
Thanks! :)

**Comment by derekwaynecarr** [comment]
That being said, I recommend we scope this issue to just documentation being needed, and if you need assistance with your other topic, treat it as a separate issue.

**Comment by dermusikman** [comment]
Quite reasonable! If you think that documentation will be added before the weekend, I'll wait until that's available and see if I can figure it out myself; otherwise, I'll make a separate issue for that.
