### ISSUE TITLE
make boilerplate more flexible

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#7898]
right now, boilerplate forces all sh scripts to be bash, from the `hooks/boilerplate.sh.txt` file, 

```
  1 #!/bin/bash
  2 
  3 # Copyright 2014 The Kubernetes Authors All rights reserved.
```

So the grep statement needs to be loosened up a little, i guess, to allow the top line to vary... maybe while we're at it we can consolidate all boilerplate files into a single string or regex

cc @eparis

**Comment by mbforbes** [comment]
I think this might be intentional (or at least a good side-effect)? That is, given the quantity of scripts we have in Kubernetes (Too Much&#8482;), we want them to be a consistent language so we don't have to support shell variants? I could be wrong here.

**Comment by jayunit100** [comment]
I fixed this in #7878  ... some docker files use sh scripts, after all ?

**Comment by jayunit100** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/commit/c192cfb3deda6633cb19104b2a20b25add67198b here's my proposed fix .  just a two liner.  and im happy to also implement logic which forces all files to be `bin/bash` if thats something we want to enforce?

**Comment by mbforbes** [comment]
Those who worked on the boilerplate should probably decide this (@eparis and @lavalamp)

**Comment by eparis** [comment]
I think that's I'm ok with the change, but I generally dislike any script that starts with /bin/sh.  Even if /bin/sh == /bin/bash on 99.9% of systems, there's got to be some nutter out there who changes the symlink. Which is what makes me like the "force /bin/bash" idea....

**Comment by lavalamp** [comment]
I guess we sometimes use /bin/sh in busybox images... Not too keen on allowing it generally, though. Shell is hard enough without variants.

**Comment by lavalamp** [comment]
@jayunit100 Why do you want to make this change?

**Comment by jayunit100** [comment]
@lavalamp simply because its the right thing to do.    

- There are easy workarounds, BUT 
- `verify-boilerplate.sh` shouldnt determine what shells we allow.  

HOWEVER i *totally* agree with eric, that we should enforce scripting types - but just not in verify-boilerplate.sh.

- shall we create `hack/verify-misc.sh` or something of the sort which verified miscellaneous things like using bash wherever possible?

makes sense now?

**Comment by lavalamp** [comment]
I guess I don't really see the point in splitting one verification script into two absent an immediate use case.

**Comment by eparis** [comment]
I know the jayunit 'stole' a script for prometheus that was #!/bin/sh and then couldn't use it in kube because of this requirement.  That's over in #7878 

we also enforce `#!/usr/bin/env python` in the python boilerplate

I'm not sure I see the value in having a separate new 'verify interpreter' script.  If we agree `always #!/bin/bash` and `always #!/usr/bin/env python` then we should leave them in the boilerplate.  If we need something more flexible, i'm ok with a separate tool...

**Comment by lavalamp** [comment]
Copied stuff should go in third_party somewhere, and then the boilerplate script shouldn't check it.

I think I'll close this, since @eparis seems to agree with me. Please reopen if there's a use case that requires this.

**Comment by jayunit100** [comment]
Briefly to clarify : that script was written by one of kube contributors... so it definetly goes in the main src.  I can layer some commits on top to change to bash to retest.

But in any case if we're going to use verify boilerplate to do more than boiler plate... we should at least output the correct error message... right?
