### ISSUE TITLE
Node upgrades: GCE instances start with only common metadata

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#7912]
Move the metadata to the MIG template (not instance-specific).

**Comment by roberthbailey** [comment]
Can you document which metadata is instance specific (so that we know how much needs to be removed and can discuss where it should go instead)?

**Comment by mbforbes** [comment]
I'm investigating this now. The instance metadata currently looks identical to the template metadata. (I believe this has changed since I last looked). This is fantastic news.

I now just need to confirm that the instance inherits the template meatadata into its own (rather than just referencing it), to ensure we aren't just writing the same metadata into the template and the instance. I looked through the startup script and I believe that we aren't pushing to the instance-specific metadata anywhere, so this is a good start. Will confirm.

**Comment by mbforbes** [comment]
Yep, the instances just inherit from the template, and we aren't writing directly. We only update instance metadata directly on a push/script-based upgrade.
