### ISSUE TITLE
getting-started-guides for coreos not working

### ISSUE THREAD

**Issue by guoshimin** [GoogleCloudPlatform/kubernetes#7913]
It seems "\<master-private-ip\>" in master.yaml needs to be replaced with the actual IP as well, whereas the current documentation says to only do the substitution for node.yaml. On the master I'm getting the following in journalctl:

```
May 07 20:11:08 master systemd[1]: Starting etcd2...
May 07 20:11:10 master etcd2[599]: 2015/05/07 20:11:10 etcd: listen tcp: lookup <master-private-ip>: no such host
May 07 20:11:10 master systemd[1]: etcd2.service: main process exited, code=exited, status=1/FAILURE
May 07 20:11:10 master systemd[1]: Unit etcd2.service entered failed state.
```

**Comment by MCyprien** [comment]
Yes you need to replace "<master-private-ip>" it is not a variable like $private_ipv4 or $public_ipv4 as you can see in this [coreos multinode guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md#edit-nodeyaml-1).

**Comment by guoshimin** [comment]
This issue is about master.yaml
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml.
The guide says to do the substitution only for node.yaml.

**Comment by guoshimin** [comment]
Fixed in https://github.com/GoogleCloudPlatform/kubernetes/pull/8015
