### ISSUE TITLE
validate-cluster.sh doesn't check that nodes are healthy

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#7920]
I just created a cluster (on GCE) and kube-up.sh finished successfully. I then immediately did a `kubectl get nodes` and noticed that one of the nodes is `NotReady`. I couldn't ssh into the VM and the serial console output has a bunch of lines like:

`May  7 20:54:10 (none) accounts-from-metadata: WARNING error while trying to update accounts: <urlopen error [Errno 101] Network is unreachable>`

(it finally succeeded after 246 attempts and then joined the cluster)

validate-cluster.sh should not be returning success if the cluster nodes are unhealthy. It should check that each node is in the `Ready` state. 

The output of

`kubectl.sh get nodes -o template -t $'{{range.items}}{{.metadata.name}}\n{{end}}' --api-version=v1beta3`

(from [validate-cluster.sh#L33](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/validate-cluster.sh#L33)) is just the names of the nodes and the check is that the number of them is correct rather than that they are healthy. 

/cc @fabioy

**Comment by roberthbailey** [comment]
@fabioy and I just discussed this and it's a regression introduced when we removed the node status from the component status endpoint. 

Bumping to P0.

**Comment by fabioy** [comment]
Should have been fixed by PR #7932. Closing.
