### ISSUE TITLE
rethinkdb example, cannot access UI if deployed on GCE

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#7930]
I followed the instructions [here] (https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/rethinkdb). Because I'm running my cluster on GCE, so I added a "createExternalLoadBalancer: true" in admin-service.yaml. But I cannot access the UI via the external IP (104.197.76.235:8080), I got a "ERR_CONNECTION_TIMED_OUT" error

```
NAME               LABELS        SELECTOR                  IP(S)            PORT(S)
rethinkdb-admin    db=influxdb   db=rethinkdb,role=admin   10.0.124.220     8080/TCP
                                                           104.197.76.235   
rethinkdb-driver   db=influxdb   db=rethinkdb              10.0.172.148     28015/TCP
```

Any suggestion? Thanks.

@nikhiljindal @antmanler

**Comment by antmanler** [comment]
Sorry GCE is blocked in China, I've not tested using createExternalLoadBalancer. I run rethinkdb on one of my local cluster, using publicIPs, and it works well.




if someone else can help to fix this on GCE? 



—

**Comment by caesarxuchao** [comment]
My bad. I forgot to set up the firewall rule on GCE. It works now : )
