### ISSUE TITLE
The apiserver read-only API leaks bearer tokens

### ISSUE THREAD

**Issue by stephenR** [GoogleCloudPlatform/kubernetes#7963]
From a minion:
  curl http://kubernetes-master:7080/api/v1beta3/secrets
will return the bearer tokens for all service accounts.

I'm not sure if this is already taken care of as part of #5921.

**Comment by roberthbailey** [comment]
The read-only port is only available within the cluster, which is currently assumed to be a secured, trusted network. 

We are working on removing the read-only port from the apiserver (e.g. #5921) which should take care of this.

**Comment by lavalamp** [comment]
The read-only port is going away in days; that should take care of this specific problem but not necessarily the general case.

@erictune the intention is to solve this with permissions?

**Comment by roberthbailey** [comment]
At least that will mean that you need cluster admin access (read/write) to see the cluster secrets (right now anyone who can reach the read-only endpoint can escalate to having read-write access to the cluster). Until we have a permissions model in the master, I think that's the best we can do.

**Comment by erictune** [comment]
After #5921 is done, then we won't have anything called readonly.  All
accounts (admin, default service account, etc) will be equally powerful.

Once we merge REST Policy, we will have differentiated permissions for
different roles.

**Comment by davidopp** [comment]
@lavalamp can you update the status on this?

**Comment by lavalamp** [comment]
This will be fixed when #8155 merges.
