### ISSUE TITLE
Enable certificate verification for all services

### ISSUE THREAD

**Issue by stephenR** [GoogleCloudPlatform/kubernetes#7964]
In a few places, certificate verification is still disabled:
* docker is started with --insecure-registry 10.0.0.0/8
* /var/lib/kubelet/kubernetes_auth includes "Insecure": true
* /var/lib/kube-proxy/kubeconfig sets "insecure-skip-tls-verify: true"

For reference: secure node -> master communication #3168

**Comment by roberthbailey** [comment]
That's fewer places than I thought were were skipping cert validation. :)

**Comment by roberthbailey** [comment]
@thockin - can you remind me why we pass `--insecure-registry 10.0.0.0/8` to docker? Is that something you think we could remove?

**Comment by thockin** [comment]
I think it was to allow private registries in your own project.  I'll do
some archaeology.

**Comment by thockin** [comment]
If we wanted to run a registry inside a kube cluster wouldn't we need this docker flag?

**Comment by brendandburns** [comment]
Yeah, you need that flag in order to run a service based, un-authenticated registry.

If we want to run our own registry, we need that flag.

**Comment by brendandburns** [comment]
Note that this is statically set in the Container VM as far as I can tell.  We should either add the 172 range or kill this, since as it stands half of GKE clusters won't work.

**Comment by roberthbailey** [comment]
As an update, the only certificate validation being skipped now is the flag being passed to docker.

**Comment by brendandburns** [comment]
I'm going to close this.  We're going to add the 172 range to container-vm, it is a necessary feature to enable running a registry on the cluster itself.

**Comment by brendandburns** [comment]
Actually, I took a closer look, this was in salt.  I'm going to re-open and fix this for real.
