### ISSUE TITLE
Secure kubelet port 10250

### ISSUE THREAD

**Issue by stephenR** [GoogleCloudPlatform/kubernetes#7965]
The kubelet exposes an unauthenticated endpoint on port 10250. The issues with this:
* there are the debug handlers /exec/ and /run/ that run code in any container on the host
* these debug handlers are enabled by default
* the code run in the container runs with full root capabilities (compared to docker's root with a capability bounding set)

**Comment by roberthbailey** [comment]
This is covered as part of https://github.com/GoogleCloudPlatform/kubernetes/issues/3168#issuecomment-74781577

**Comment by roberthbailey** [comment]
We can't get rid of port 10250 since the proxy functionality of the master connects to this port. What we need instead is to authenticate that we trust incoming requests (because the request presents a client SSL cert that is signed by a root CA that is trusted by the kubelet).

**Comment by goltermann** [comment]
This is in fact covered by #3168

**Comment by Wuzhibin05** [comment]
why my 
kubeadm join --token 1a03ed.c169a304c8d5217b  192.168.8.228:6443                ] 557.1 kB/102.8 MB
Loaded image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3
[root@node30 images]# kubeadm join --token 1a03ed.c169a304c8d5217b  192.168.8.228:6443
[preflight] Running pre-flight checks.
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 3.10.0-514.el7.x86_64
DOCKER_VERSION: 1.12.6
DOCKER_GRAPH_DRIVER: overlay
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Some fatal errors occurred:
	[ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: FATAL: Module configs not found.\n", err - exit status 1
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR FileAvailable--etc-kubernetes-pki-ca.crt]: /etc/kubernetes/pki/ca.crt already exists
	[ERROR FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
[root@node30 images]#
