### ISSUE TITLE
Automatically create a secret in the default namespace that contains cluster access auth info

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7979]
When a cluster is created automatically make a `kubernetes-auth` secret that contains the basic auth, bearer token auth and certs to allow applications running inside pods to access the apiserver etc.

**Comment by satnam6502** [comment]
@roberthbailey @zmerlynn

**Comment by roberthbailey** [comment]
Will #7101 do this for us automatically? @liggitt

**Comment by satnam6502** [comment]
I see that we already have:
```
$ kubectl get secrets
NAME                              TYPE      DATA
token-admin                       Opaque    1
token-kube-proxy                  Opaque    1
token-kubelet                     Opaque    1
token-system-controller-manager   Opaque    1
token-system-dns                  Opaque    1
token-system-logging              Opaque    1
token-system-monitoring           Opaque    1
token-system-scheduler            Opaque    1

```

**Comment by roberthbailey** [comment]
For GCE/GKE we do (@erictune added them to [cluster/gce/configure-vm.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L312-L316)).

**Comment by roberthbailey** [comment]
Note that these are all just bearer tokens and they don't contain the CA root cert which we need to distribute for #7964.

**Comment by liggitt** [comment]
#7101 will get automatically get you bearer tokens for service accounts, but that's it. There was discussion about following that with adding a kubeconfig key to the secret which bundled the ca cert and the token together

**Comment by erictune** [comment]
Let's not use the admin account for pods.  Secrets are for pods.  So let's
not put the admin secrets in secret resources.

**Comment by satnam6502** [comment]
@erictune : have I done the wrong thing in PR ##7988 ?

**Comment by erictune** [comment]
I created `token-system-logging` with the hope that it would be used for elasticsearch.   So I am a little sad that #7988 used `token-admin`.  :crying_cat_face:

**Comment by satnam6502** [comment]
Let me look into this and see if I can switch to `token-system-logging`

**Comment by thockin** [comment]
What's the status on this?  It seems that tokens are a big issue for many people but I guess a lot of it has to do with doing upgrades.  Do we think this issue is something we want to do?  If not, let's close it out.

**Comment by satnam6502** [comment]
I can't help thinking that we will keep wanting to make system pods that want to make Kuebernetes API calls but perhaps we should wait until there is a clear demand for this scenario.

**Comment by thockin** [comment]
Doesn't service accounts handle this?

**Comment by liggitt** [comment]
> Doesn't service accounts handle this?

Yes. Room for improvement (including the CA or a kubeconfig with the token as well), but yes... that's how pods get API credentials.
