### ISSUE TITLE
There should be a busybox-like volume plugin

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#7986]
To support scratch images (or just images that don't have a tool you want), the should be a volume plugin that provides a shell and busybox-like functionality.  Of course, it must have selinux compiled in, not like the mainline 'busybox' image.

@vmarmol @thockin

**Comment by thockin** [comment]
I am not understanding what busybox has to do with volume plugins.  What am
I missing?

**Comment by pmorie** [comment]
@thockin The idea is mount a shell into a container.  I can't think of a great way to do this as a sidecar.  Open to suggestions.

**Comment by thockin** [comment]
oh, you want a container as a volume?  #831 ish?

**Comment by pmorie** [comment]
@thockin yes, that is what I want.  I'll close this out and document the need there.
