### ISSUE TITLE
Find namespace of current pod.

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/kubernetes#8006]
If I am running within a pod I have no way currently to find the namespace of the pod, which means I have no way to retrieve additional metadata about the pod I might need (e.g. labels).

Something like an environment variable would be nice.

**Comment by thockin-cc** [comment]
@pmorie please enlighten us on the downward API for this!

@erictune do I recall a discussion of dropping a kubeconfg into pod secrets
that has their current namespace preset?

**Comment by pmorie** [comment]
@elibixby check out
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/downward_api.md

**Comment by pmorie** [comment]
@thockin, @liggit's work is going to generate a kubeconfig secret for a
service account that is injected into the pod in a volume

**Comment by liggitt** [comment]
Kubeconfig was a question/follow-up for #7101, not part of the PR currently

**Comment by pmorie** [comment]
@elibixby Let us know if that works for you

**Comment by elibixby** [comment]
@pmorie That looks great! Plans for labels to be supported in the same way potentially?
