### ISSUE TITLE
Make pod.Spec.Host unambiguous

### ISSUE THREAD

**Issue by pravisankar** [GoogleCloudPlatform/kubernetes#8007]
AFAIK, general principle is user desired intent is specified in the object spec and k8s platform will try to satisfy this intent. 
  User can restrict pod creation on a specific node with pod.Spec.Host=[node] and if this is empty, scheduler will choose the best node based on predicates/priorityfunctions.
Scheduler explicitly modifies pod.Spec.Host = best-fit-node (scheduleOne() in plugin/pkg/scheduler/scheduler.go)
So essentially looking at the pod entry in registry, we won't be able to differentiate if the pod.Spec.Host is specified by the user or decided by the scheduler. This differentiation is needed to decide whether this pod can be migrated to other node or not.

/cc @smarterclayton @abhgupta @bgrant0607

**Comment by bgrant0607** [comment]
Spec is not just user intent, but the desired state, in general:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#spec-and-status

Pods cannot be rescheduled. They must be replaced.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pods.md#durability-of-pods-or-lack-thereof

**Comment by bgrant0607** [comment]
See also #3949.

**Comment by bgrant0607** [comment]
And #6393

**Comment by smarterclayton** [comment]
> On May 8, 2015, at 8:28 PM, Brian Grant <notifications@github.com> wrote:
> 
> Spec is not just user intent, but the desired state, in general:
> https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#spec-and-status
> 
> Pods cannot be rescheduled. They must be replaced.
> https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pods.md#durability-of-pods-or-lack-thereof
> 
Yes, migration has no meaning in our model. If a user wants a pod to remain on a specific node regardless of the state of the node, they either create a replication controller that sets the pod to a host, or they would tune a forgiveness policy on the pod to indicate that the pod prefers to remain on a node for a period of time after a node is unreachable.  The node controller would take that policy into account during node deletion (the forgiveness policy of each pod determines when the pods are deleted from a node that has gone down), and possibly the scheduler might take that into account.

While we don't have that model yet, there is no concept of "this has to be on this node so don't migrate it".  There is only the request a pod makes to not be deleted rapidly.

**Comment by bgrant0607** [comment]
Forgiveness: #1574
