### ISSUE TITLE
kube2sky silently fails dns entry creation

### ISSUE THREAD

**Issue by vishh** [GoogleCloudPlatform/kubernetes#8010]
Since namespaces can be DNS names, it is possible to create services with different names and namespaces, that ends up colliding when it comes to dns entry creation. This is a limitation of skydns.
Example:
```
Service A:
namespace: kubernetes.default
name: serviceA
```

Our users have no clue about this failure now since kube2sky failures are not surfaced as of now.

**Comment by vishh** [comment]
cc @thockin @ArtfulCoder

**Comment by vishh** [comment]
Question: Can namespaces and names have be DNS labels? Is there a real immediate necessity for them to be DNS sub domains? @bgrant0607 @derekwaynecarr

**Comment by bgrant0607** [comment]
Please comment on #6666.

**Comment by bgrant0607** [comment]
DNS labels for namespaces seems reasonable to me, though.

**Comment by bgrant0607** [comment]
Could you please describe the problem in more detail, with an example conflict?

**Comment by thockin-cc** [comment]
Create a service s1 in namespace n. Now create a service s2 in namespace
s1.n. This will break skydns in particular and any wildcard DNS *.s1.n

I think it is reasonable to move namespaces to be DNS labels.

**Comment by thockin** [comment]
Fixed by #8140
