### ISSUE TITLE
Make template Deletion/Creation more robust

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#8014]
'kubernetes-soak-weekly-deploy' sometimes fails to deploy because the clean-up cluster `down` step fails to delete the template:
```
go run ./hack/e2e.go -v --down
...
Bringing down cluster
Managed instance group e2e-soak-minion-group is being deleted. Operation: operation-1431129917493-5159ae65c0f09-cd441be6-481553bf
ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
 - The instance_template resource 'e2e-soak-minion-template' is already being used by 'e2e-soak-minion-group'

```

Then the subsequent cluster `up` step fails to create the template, because it already exists:
```
go run ./hack/e2e.go -v --up
...
Created [...e2e-soak-master-https].
Created [...e2e-soak-master-pd].
Created [...e2e-soak-master-ip].
Created [...e2e-soak-minion-all].
Created [...e2e-soak-master].
...
Creating minions.
...
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins/global/instanceTemplates/e2e-soak-minion-template' already exists
...
[0;33mAttempt 1 failed to create instance template e2e-soak-minion-template. Retrying.
...
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins/global/instanceTemplates/e2e-soak-minion-template' already exists
```

It keeps retrying and failing, because the template already exists, until it times out and the deployment fails.

Suggested fixes:
* Cluster down should try harder to delete the template (maybe wait/retry).
* Cluster up should recognize that the template exists, and try to delete/recreate, or just re-use the existing.

**Comment by saad-ali** [comment]
Looks like `kubernetes-e2e-gce` ran in to this on Monday, May 11, 2015 around 1:00 PM PST.

I'll assign this to my self and take a crack at fixing it.

**Comment by quinton-hoole** [comment]
This is causing most of our e2e tests to fail in continuous integration as well as users private e2e test clusters.  Bumping to priority/p0 and v1.0 milestone.

Saad thinks he's figured it out, and is working on a fix as we speak.

**Comment by quinton-hoole** [comment]
In essence...

Saad: "I think what's happening is the previous clean up step to delete the managed instance group happens asynchronously, therefore, and there is a race condition to delete the template.  Working on a fix".
