### ISSUE TITLE
Vagrant saltstack failing to provision.

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/kubernetes#8019]
Running `make test_e2e` was working fine just last night, but now appears to be failing to provision.

````
*[lots of normal debug info precedes......]*

==> master:  *  INFO:  sh -- Version 2015.05.07
==> master: 
==> master:  *  INFO: System Information:
==> master:  *  INFO:   CPU:          GenuineIntel
==> master:  *  INFO:   CPU Arch:     x86_64
==> master:  *  INFO:   OS Name:      Linux
==> master:  *  INFO:   OS Version:   3.11.10-301.fc20.x86_64
==> master:  *  INFO:   Distribution: Fedora 20
==> master:  *  INFO: Installing master
==> master:  *  INFO: Found function install_fedora_deps
==> master:  *  INFO: Found function install_fedora_stable
==> master:  *  INFO: Found function install_fedora_stable_post
==> master:  *  INFO: Found function install_fedora_restart_daemons
==> master:  *  INFO: Found function daemons_running
==> master:  *  INFO: Found function install_fedora_check_services
==> master:  *  INFO: Running install_fedora_deps()
==> master:  *  INFO: Adding SaltStack's COPR repository
==> master: http://mirror.pnl.gov/fedora/linux/updates/20/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates
==> master: Trying other mirror.
==> master: http://fedora.mirror.lstn.net/updates/20/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates
==> master: Trying other mirror.
==> master: ftp://mirror.lstn.net/fedora/updates/20/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:ff68:1:42::10: Network is unreachable"
==> master: Trying other mirror.

*[lots of failed mirrors follow.......]*
````
Basically it runs through every mirror for repomd.xml failing on each one. I've run it a few times on two machines both with working internet access and each time it appears to try every mirror before giving:

````
==> master: http://mirror.csclub.uwaterloo.ca/fedora/linux/updates/20/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates
==> master:  * ERROR: Failed to run install_fedora_deps()!!!
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
2015/05/09 14:03:48 Error running up: exit status 1
2015/05/09 14:03:48 Error starting e2e cluster. Aborting.
exit status 1
make: *** [test_e2e] Error 1
`````

I'm not familiar with saltstack so if anyone could point me in the right direction to solving this I would appreciate it greatly.

**Comment by derekwaynecarr** [comment]
I saw this too.  Not sure the cause yet.  Have you checked if you can ssh into the box and just run a yum update to see if it can find any repo?  Basically, the salt stuff in its early steps is just trying to invoke yum

**Comment by BenTheElder** [comment]
ssh'ing and running `sudo yum update` gives the same issue with failing to find repomd.xml.

**Comment by BenTheElder** [comment]
This: (https://github.com/GoogleCloudPlatform/kubernetes/issues/1085) seems to suggest that it may be an issue with the Fedora mirrors.
Specifically this comment: https://github.com/GoogleCloudPlatform/kubernetes/issues/1085#issuecomment-53791984

**Comment by derekwaynecarr** [comment]
@puiterwijk is there a problem with Fedora infrastructure?  We are having problems doing yum update on Fedora 20 VM in Kubernetes.  #1085 makes me think you may know how to help.

**Comment by derekwaynecarr** [comment]
This makes me want to move to Fedora 21 this week.  I know we have OpenShift running on Fedora 21 now in Vagrant as an option so Kubernetes should be fine there, quicker to pick up Docker changes as well.

**Comment by BenTheElder** [comment]
I hopped on #fedora on freenode last night, didn't find any solution but found two users with out of date fedora 20 installs with the same issue. Looks like it probably is the mirrors acting up. I'm going to be out for a bit this morning but I'll check if the situation has changed later.

**Comment by yoanisgil** [comment]
I was trying to setup a cluster to play around with kubernetes but I ran into this very same issue.

**Comment by BenTheElder** [comment]
From #fedora today in a conversation by yoanis and Zord:

https://bugzilla.redhat.com/show_bug.cgi?id=1220056

**Comment by yoanisgil** [comment]
@BenTheElder I tried switching from fed20 to fed21 but that does not seem to be a one shot operation:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

service network restart
Stdout from the command:
Restarting network (via systemctl):  [FAILED]
Stderr from the command:
Job for network.service failed. See "systemctl status network.service" and "journalctl -xe" for details.
```
Looks like we're stuck until the fedora guys fix their repo.

**Comment by BenTheElder** [comment]
@yoanisgil Alright. I wound up kind of busy today. If someone else doesn't get to it first (I imagine they will though) I'll take a stab at getting vagrant working before tomorrow night.

**Comment by wshearn** [comment]
My fix is this: Save the contents of this gist as ~/fedora-updates.repo https://gist.github.com/wshearn/ad2d5e133297ab3ece70

Then in ~/kubernetes/Vagrantfile on line 118 add
```
    config.vm.provision "file", source: "~/fedora-updates.repo", destination: "fedora-updates.repo"
    config.vm.provision "shell", inline: "mv ~vagrant/fedora-updates.repo /etc/yum.repos.d ; restorecon /etc/yum.repos.d/fedora-updates.repo"
```

Then you should be able to do ./cluster/kube-up.sh

**Comment by yoanisgil** [comment]
@wshearn Thanks! Going to give it a try and let you know.

**Comment by yoanisgil** [comment]
@wshearn after applying your fix I'm able to run ./cluster/kube-up.sh, so this will do until F20 repo is fixed.

**Comment by derekwaynecarr** [comment]
The Fedora repo issues appear to be resolved.  I was able to kube-up the vagrant based cluster.

**Comment by fahadpolash** [comment]
Hello, 
I was trying to deploy kubernetes with vagrant yesterday as per the below link:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

But, I getting the following error:

[vagrant@kubernetes-master ~]$ sudo yum update


File contains no section headers.
file: file://///etc/yum.repos.d/saltstack-salt-fedora-20.repo, line: 1
'<HTML><HEAD>\r\n'

Any idea?
Thanks.

**Comment by derekwaynecarr** [comment]
Salt bootstrap was I hope temporarily failing last night.  

https://github.com/GoogleCloudPlatform/kubernetes/issues/9241

It had started to mess up around 6EST after working well so I am hoping its a temporary flake with bootstrap of Salt.  Will verify again today

**Comment by derekwaynecarr** [comment]
Salt repositories appear to be functioning again for me now.

**Comment by karux** [comment]
Has anyone tested with k8sV1.0? Similar failure occurring.

==> master:  *  INFO: Found function daemons_running
==> master:  *  INFO: Found function install_fedora_check_services
==> master:  *  INFO: Running install_fedora_deps()
==> master:  *  INFO: Adding SaltStack's COPR repository
==> master:  * ERROR: Failed to run install_fedora_deps()!!!


repo errors further up in the script:
==> master: Installing, enabling prerequisites
==> master: http://lug.mtu.edu/fedora/linux/updates/21/x86_64/repodata/50536d92e16bf49919a28a94db65dacbb34483c452b5373eab69e9c02f812c0b-primary.sqlite.xz: [Errno 14] HTTP Error 404 - Not Found
==> master: Trying other mirror.
==> master: http://mirror.chpc.utah.edu/pub/fedora/linux/updates/21/x86_64/repodata/50536d92e16bf49919a28a94db65dacbb34483c452b5373eab69e9c02f812c0b-primary.sqlite.xz: [Errno 14] HTTP Error 404 - Not Found
==> master: Trying other mirror.

**Comment by BenTheElder** [comment]
I've run it since the 1.0 merge but not on the latest master, i'll update and check back.

**Comment by BenTheElder** [comment]
Seeing this as well.

**Comment by BenTheElder** [comment]
It now seems to be hanging on:
````
==> master:  *  INFO: Adding SaltStack's COPR repository
```
This has happened twice now. I'll take another look in the morning.

**Comment by rajasaur** [comment]
From https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2827, its trying to fetch the repos.d file from copr.fedoraproject.org, which is not resolving for me now.

**Comment by yoanisgil** [comment]
I was just wondering if we could either use a different (possibly mirrored) repo? The truth is that over the last couple of months this has been a source of issue for some users, so maybe we should stop try to find a more permanent/stable solution.

**Comment by BenTheElder** [comment]
For me at least, this appears to be functioning correctly again today.

**Comment by karux** [comment]
working for me too (today).   stabilizing the repos would be a big sanity booster for newcomers like me

**Comment by aleks-f** [comment]
Following [instructions](http://kubernetes.io/v1.0/docs/getting-started-guides/vagrant.html), using:

Mac OSX 10.10.5
Vagrant 1.7.4
Parallels Desktop 10.2.2

When I run 

<pre>export VAGRANT_DEFAULT_PROVIDER=parallels
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh</pre>

*master* and *minion-1* windows pop up, apparently fully functional (I can ssh into them and everything seems to work) but the command line shows following problems for both master and minion:

<pre>==> master: Checking for Parallels Tools installed on the VM...
==> master: Parallels Tools installed on this VM are outdated! In most cases
==> master: this is fine but in rare cases it can cause things such as shared
==> master: folders to not work properly. If you see shared folder errors,
==> master: please update Parallels Tools within the virtual machine and 
==> master: reload your VM.
</pre>

<pre>master: Running: /var/folders/ng/8c3_08cd5nb8y8414tffrb980000gn/T/vagrant-shell20150904-29622-1bot2j5.sh
==> master: Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.
==> master: An error occurred. The error will be shown after all tasks complete.</pre>

I have applied @wshearn fedora repo fix above but it didn't help.

Any help appreciated.

**Comment by rmohr** [comment]
Just in case you see an error like
```
File contains no section headers.
file: file://///etc/yum.repos.d/saltstack-salt-fedora-21.repo, line: 1
```
since today when provisioning salt.

The reason is that copr.fedoraproject.org moved to copr.fedorainfracloud.org.

Pull request is here https://github.com/saltstack/salt/pull/30534.
A temporary workaround for vagrant is to use this gist: https://gist.github.com/rmohr/43941d0881f0682b99a7#file-bootstrap-salt-sh instead of http://bootstrap.saltstack.com/

by applying this diff:

```
diff --git a/cluster/vagrant/provision-utils.sh b/cluster/vagrant/provision-utils.sh
index c3a3d83..8875983 100755
--- a/cluster/vagrant/provision-utils.sh
+++ b/cluster/vagrant/provision-utils.sh
@@ -94,7 +94,7 @@ function install-salt() {
 
   if ! which salt-call >/dev/null 2>&1; then
     # Install salt binaries
-    curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com | sh -s
+    curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://gist.githubusercontent.com/rmohr/43941d0881f0682b99a7/raw/5b5e075e373cd81689e991eaef6cd95beb7b2d2a/bootstrap-salt.sh | sh -s
   fi
 }
```

**Comment by nicluo** [comment]
@rmohr Thanks! Worked for me

**Comment by henryon** [comment]
seems this issue exist on version 1.1.7.

**Comment by cyates81** [comment]
+1 on 1.1.7

**Comment by GeoffPurdy** [comment]
@rmohr Thank you for the workaround.  I edited both provision-master.sh and provision-minion.sh and replaced a total of three references to bootstrap.saltstack.com.

**Comment by uoryon** [comment]
@rmohr Thanks!

**Comment by clubanderson** [comment]
worked for me - replaced the salt bootstrap with the gist.

when is this going to be committed to a branch?
