### ISSUE TITLE
WWW / UI does not work

### ISSUE THREAD

**Issue by rimusz** [GoogleCloudPlatform/kubernetes#8043]
WWW/UI does not open on port 8001.
Any there any options need to be enabled on API Server?

**Comment by preillyme** [comment]
@rimusz I'm able to get it working with the following command: ```hack/local-up-cluster.sh``` then visiting ```http://127.0.0.1:8080/static/app/#/dashboard/``` in my web browser. I just tried it again as of commit a442918d314f4ab3de98a45512d2ef60e7939f94

What seems to be the issue that you're facing?

**Comment by rimusz** [comment]
I use CoreOS+Kubernetes, let me check via that link

**Comment by rimusz** [comment]
@preillyme cool, that works.
I think the www doc should be more clear how to use it.

**Comment by preillyme** [comment]
@rimusz yeah I completely agree. I'm working to make the documentation cleaner. Thanks for reporting your issue.

**Comment by rimusz** [comment]
@preillyme no worries. I will update my App https://github.com/rimusz/coreos-osx-gui-kubernetes-cluster with the new UI link, will stop using docker container for UI.

**Comment by rimusz** [comment]
so we can close this one I think

**Comment by preillyme** [comment]
@rimusz Okay sounds good.

**Comment by nikhiljindal** [comment]
@preillyme : Do you have a separate issue for updating the documentation or do you want to use this one?

**Comment by JeanMertz** [comment]
> will stop using docker container for UI

To be honest, when working on CoreOS (but any environment for that matter), it makes a lot of sense to have the UI running inside the container.

I've got all components of Kubernetes running inside containers right now, but the UI part is still missing. I see there are some pre-built non-google images in the Docker Hub, but it'd be great if there was some official documentation on how to run the UI inside a container.

**Comment by rimusz** [comment]
@JeanMertz as @preillyme mentioned above Kubernetes UI is part of API service and can very easily accesses via `http://api_server_ip:8080/static/app/#/dashboard/`.
Running Kubernetes for production you should not put it's components/binaries to Docker containers as binaries are standalone compiled go programs. Plus such setup brings more constrains to your setup as if your Docker daemon dies then even Kubernetes is dead.

**Comment by bcbroussard** [comment]
Updates to the documentation are being tracked in https://github.com/GoogleCloudPlatform/kubernetes/issues/7122 and the changes are in PR https://github.com/GoogleCloudPlatform/kubernetes/pull/9330. This issue can be closed.
