### ISSUE TITLE
SecurityContext is not copied correctly

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#8054]
DeepCopy doesn't work correctly for SecurityContext - after some debugging it seems that "privileged" field is not copied correctly.

To replicate this issue:
1. patch:
https://github.com/GoogleCloudPlatform/kubernetes/compare/master...wojtek-t:deep_copy_generator
2. run:
GOPATH=$(pwd)/Godeps/_workspace:$GOPATH go test ./pkg/conversion -test.run=XXXXX -bench=Copy

DeepCopy mechanism is extremely generic, so the issue must be somewhere in defaulting/conversion/initialization/etc.

cc @zmerlynn @pmorie @pweil

**Comment by bgrant0607** [comment]
cc @smarterclayton @pweil-

**Comment by pweil-** [comment]
will debug.  Thanks for the patch to help

**Comment by lavalamp** [comment]
The problem (and it's not isolated to SecurityContext, I think) is that we actually use *bool as a ternary field (not present, true, false) and gob encode/decode doesn't differentiate between nil and false (likewise 0 and nil for the *int64).

Kris, would you like to take this? Look at the blame history on the deep_copy.go file to see the history (summary: we're using gob for performance reasons).

**Comment by lavalamp** [comment]
Or @pweil- if you want to take this, that's fine too.

**Comment by smarterclayton** [comment]
Also be aware @wojtek-t was looking at generating deep copy correctly.  A quick workaround would probably be acceptable.

----- Original Message -----

**Comment by krousey** [comment]
It is definitely gob not differentiating between nil and false. This is unfortunate. The "quick" workaround might have to be writing a custom encoder/decoder for SecurityContext.

**Comment by krousey** [comment]
So I've looked at all the uses of the Privileged field in 875e83a7415a8fff5d3fa4645b93551f96b12c89, and it seems the only trickiness comes in when dealing/validating with the deprecated Privileged field on the container. 

SecurityContext itself is already optional (a pointer). Is there any reason that this bool should also be a pointer? If we could change it to not be one, that would both fix this and simplify a lot of code. 

[HasPrivilegedRequest](https://github.com/GoogleCloudPlatform/kubernetes/blob/875e83a7415a8fff5d3fa4645b93551f96b12c89/pkg/securitycontext/util.go#L23) suggests that nil is semantically equivalent to false anyway.

We could also update api.Semantic to treat them the same when compared.

Thoughts?

**Comment by pweil-** [comment]
@krousey - that's exactly what I was thinking and probably the best route.   We lose the ability to know which way to merge if someone submits both Container.SecurityContext.Privileged and Container.Privileged in defaults.go but I think in that case if either are true then we should set both to true and let the validation and kubelet's check kill the request if privileged containers are not allowed.

It is important in the case of the *int64 RunAsUser since there is a difference between requesting 0 or requesting nothing to fall back to the Dockerfile setting but I added an empty SecurityContext to pod_example.json that is used by the benchmark test and it ran successfully.

/cc @erictune @pmorie @smarterclayton @krousey @lavalamp - if everyone agrees I can have this submitted in the AM

**Comment by bgrant0607** [comment]
Do other pointers have the same problem? For example, what about TerminationGracePeriodSeconds?

**Comment by lavalamp** [comment]
I would expect all of the pointers of (simple) types to have this problem and I'm surprised by @pweil-'s post above that the int64 works.

**Comment by smarterclayton** [comment]
Is it an interaction with omitempty or is that json only?

**Comment by pweil-** [comment]
Actually, yes, I believe so.  I was writing a test case to double check my assertion above which I now retract.  It appears to not handle default values for the pointer types nicely:

```go
func TestPointerCopy(t *testing.T) {
	semantic := conversion.EqualitiesOrDie()
	trueBool := true
	falseBool := false
	zero := 0
	one := 1
	emptyString := ""
	setString := "foo"

	testCases := map[string]struct {
		I *int
		B *bool
		S *string
	}{
		"nils": {
			I: nil,
			B: nil,
			S: nil,
		},
		"defaults": {
			I: &zero,
			B: &falseBool,
			S: &emptyString,
		},
		"values": {
			I: &one,
			B: &trueBool,
			S: &setString,
		},
	}

	for name, obj := range testCases {
		obj2, err := conversion.DeepCopy(obj)
		if err != nil {
			t.Errorf("Error: %s couldn't copy %#v, %#v", name, obj, err)
			continue
		}
		if e, a := obj, obj2; !semantic.DeepEqual(e, a) {
			t.Errorf("%s expected %#v\ngot %#v", name, e, a)
		}
	}
}
```

which fails on the defaults test case with 

```
[pweil@localhost kubernetes]$ hack/test-go.sh pkg/conversion --test.run=TestPointerCopy
Running tests for APIVersion: v1beta1
+++ [0512 09:26:16] Running unit tests without code coverage
--- FAIL: TestPointerCopy (0.00 seconds)
	deep_copy_test.go:108: defaults expected struct { I *int; B *bool; S *string }{I:(*int)(0xc2080f3a78), B:(*bool)(0xc2080f3a70), S:(*string)(0xc2080f3a90)}
		got struct { I *int; B *bool; S *string }{I:(*int)(nil), B:(*bool)(nil), S:(*string)(nil)}
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/conversion	0.005s
!!! Error in hack/test-go.sh:156
  'go test "${goflags[@]:+${goflags[@]}}" ${KUBE_RACE} ${KUBE_TIMEOUT} "${@+${@/#/${KUBE_GO_PACKAGE}/}}"' exited with status 1
Call stack:
  1: hack/test-go.sh:156 runTests(...)
  2: hack/test-go.sh:214 main(...)
Exiting with status 1
```

**Comment by krousey** [comment]
So it seems that this needs to be fixed generically.

@wojtek-t are you still working on generating a proper deep copy? Is this code generation? Or something else?

In the meantime, I could work on a slow but correct reflection based solution. Does that sound ok?

**Comment by wojtek-t** [comment]
@krousey yes - I will be working on deep-copy based on code generation. 

>
In the meantime, I could work on a slow but correct reflection based solution. Does that sound ok?

SGTM

**Comment by krousey** [comment]
This also only seems to happen to basic types. The 0 values for structs are not omitted in encoding. I think going forward, it might be a good idea to avoid pointers to basic types in anything we want to encode/decode. At the very least avoid putting semantics on them.

Proto 3 did this in fact and it has greatly simplified it's API in a lot of languages.

**Comment by bgrant0607** [comment]
We need to be able to distinguish unset by client.

**Comment by krousey** [comment]
@bgrant0607 Pointers to structs seem to be fine in Go's encoding/decoding ecosystem. It's only pointers to primitives that cause this issue. Also, the use of pointers to primitives make complex struct literals impossible without helper functions, auxiliary variables, or additional assignment after the fact.

```go
type Foo struct {
	Blah *int
}

i := 4
_ = Foo{}
_ = Foo{&i}
_ = Foo{helper.Int(4)}
f := Foo{new(int)}
*f.Blah = 4
```

If you really need optionally specified primitives, you could wrap them in a struct. It seems wasteful, but it makes literals easier and would work well with with Go's encoding/decoding ecosystem.

```go
type Bar struct {
	Val int
}

type Foo struct {
	Blah *Bar
}

_ = Foo{}
_ = Foo{&Bar{4}}
```

I realize the boat has sailed on many of the existing occurrences of this, but I think it would be good if we could avoid adding more of these things in the future. Just my 2 cents.

**Comment by lavalamp** [comment]
@krousey Is that observation limited to gob (which we don't care about except instrumentally) or is it valid for json? Really our API is defined in terms of json; if we have to do contortions in go to make that work as desired, it's unfortunate but we'll do it.

(Also note that there's an outstanding issue for switching to a different json parser)

**Comment by bgrant0607** [comment]
As much as I hate myself for suggesting it, does a pointer to an embedded struct work?
```go
type Bar struct {
	Val int
}

type Foo struct {
	*Bar
}
```

I'm ok with struct wrapping so long as it doesn't change the json representation.

**Comment by krousey** [comment]
@lavalamp I think this observation doesn't apply to the standard library JSON parser. If we don't use gob or something that behaves similarly, then my suggestion is purely style.

**Comment by krousey** [comment]
My reflection solution only has to work for API types right? I'm trying to see if I can be lazy and ignore stuff like functions, interfaces, unsafe pointers, ...

Right now I'm handling numeric types, bool, strings, structs, maps, pointers, and slices (where the composite types only include these types as well).

**Comment by krousey** [comment]
So I've got a simple reflection solution. It needs cleaning up, which I can probably do tonight/early tomorrow. Here's before (gob) and after (reflection) benchmarks:

Gob
```
> godep go test -bench=Copy -benchmem -run=XXX
PASS
BenchmarkDeepCopy	    3000	    425423 ns/op	  102101 B/op	    2567 allocs/op
```

Reflect
```
> godep go test -bench=Copy -benchmem -run=XXX
PASS
BenchmarkDeepCopy	   10000	    203186 ns/op	   57903 B/op	    1213 allocs/op
```

It seems reflection is faster. Now I just have to find out what I did wrong.

**Comment by smarterclayton** [comment]
I'm not surprised - gob has to copy strings to bytes, while your version does not.  So ironically reflect is probably faster because reflect allocation is dominated by gobs format shifting.

**Comment by wojtek-t** [comment]
That's interesting - I think that relfection is extremely slow, but it seems there are things that are slower :) That's generally good since we're going into generating code direction which will be even faster.

>
@lavalamp I think this observation doesn't apply to the standard library JSON parser. If we don't use gob or something that behaves similarly, then my suggestion is purely style.

So I think we shouldn't change anything in the API.

**Comment by krousey** [comment]
Since this was merged, is it ok to close? Or do @smarterclayton or @wojtek-t want to deprioritize and hang on to this for their code generation efforts?

**Comment by smarterclayton** [comment]
It's fine to close

**Comment by wojtek-t** [comment]
To be clear - it's closed now because the issue is fixed. I will be auto-generating methods for deep-copies, but this is peforrmance optimization, not the correctness issue.
