### ISSUE TITLE
Spec out expected list latencies for density test

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#8086]
This appears to be the main cause of failure in our scalability tests: 

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:164
Expected
    <int>: 3
not to be >
    <int>: 0

INFO: WARNING - requests with too high latency: {verb:LIST resource:pods quantile:0.9 latency:16174717000}
INFO: WARNING - requests with too high latency: {verb:LIST resource:pods quantile:0.99 latency:23250610000}
```

Claiming that 16 and 23s respectively are too long to list 3000 pods from 100 nodes. I don't think this is cause for alarm:
* The test shouldn't fail based on tail latency
* 20ish seconds is normal for the kubelet list, it can be improved to ~14 ish, but that shouldn't effect the stability of the cluster

I wrote a benchmark to verify exactly this(https://github.com/GoogleCloudPlatform/kubernetes/pull/6694). Note that the benchmark doesn't account for a network hop because it runs everything on one machine. The raw etcd list takes 11s for 3000 pods listed from 100 parallel listers in the same way the kubelet does (host selector).

@fgrzadkowski @wojtek-t @rrati @lavalamp thoughts?

**Comment by lavalamp** [comment]
Our scalability issue actually is phrased in terms of tail latency, and requires 99% return < 1 second IIRC.

These lists should really be paged/indexed. I was hoping we could defer that until after 1.0.

**Comment by bprashanth** [comment]
yeah, that doesn't care about the 99% right? so why is the test failing? I get your point though, so essentially you're saying we should not only keep this in, but lower the threshold to 1s. We have work to do :)

since we know list is slow, can we get density to focus on cluster stability at 3000 pods? It would be nice to have it break and tell me something I don't know.

**Comment by lavalamp** [comment]
> yeah, that doesn't care about the 1% right?

Right, but if you do < 100 requests, even a single slow one violates.

But yeah it's totally reasonable to make it print the histogram or something and not fail until we believe we're actually hitting the goals.

**Comment by bprashanth** [comment]
Ah, so it looks like giving etcd as many cores as it needs definitely helps which clears out my confusion, so I'm closing this as WAI, because that 99%ile failure looks like actual cause for concern now.
