### ISSUE TITLE
Salt error (AWS?): container_bridge.ensure was not found 

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8114]
I saw this error in `/var/log/salt/minion` on the master after a failed cluster start:

```
2015-05-12 14:37:02,635 [salt.state       ][ERROR   ][4524] State 'container_bridge.ensure' was not found in SLS 'docker'
```

I'm looking into this, but I want to create a tracking issue as I think some other people may be hitting this.

**Comment by zmerlynn** [comment]
It's trying to bring up `cbr0` and failing: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls#L39

The weird thing is that neither that file nor the `_states` file have been modified that recently: https://github.com/GoogleCloudPlatform/kubernetes/commits/master/cluster/saltbase/salt/_states/container_bridge.py

**Comment by justinsb** [comment]
Yes, to me it looks like salt just isn't finding the plugin.  The last change did add `/usr/bin/env python`, but I've seen this succeed recently as well (http://kubernetes-dashboard.meteor.com/). 

I'm going to try this a few times, to try to figure out whether it is failing every time or not.  My guess is that it is failing semi-randomly, so it isn't related to the changes since last-fail.

**Comment by justinsb** [comment]
Aha... this is logged at debug level in `salt-minion -l debug`

```
[DEBUG   ] LazyLoaded ps.pkill
[DEBUG   ] LazyLoaded boto_dynamodb.exists
[DEBUG   ] Failed to import states container_bridge:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 951, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/states/container_bridge.py", line 20, in <module>
    import salt.utils.ipaddr as ipaddr
ImportError: No module named ipaddr
[DEBUG   ] Could not LazyLoad file.mod_init
```

I'm guessing it's a salt version mismatch... investigating.

**Comment by justinsb** [comment]
I guess AWS needs to lock salt versions like GCE does:

```
salt-minion --version
salt-minion 2015.5.0 (Lithium)
```

**Comment by justinsb** [comment]
Confirmed that this is because of upstream salt breakage:

salt.utils.ipaddr -> salt.ext.ipaddr https://github.com/saltstack/salt/pull/18245
salt.ext.ipaddr deprecated (?) https://github.com/saltstack/salt/pull/23253

Not sure what we should do here.  I can lock to the same version as GCE, but if we find a bug in that version of salt then we can't update without breaking this script.

**Comment by zmerlynn** [comment]
We don't write bugs.

**Comment by zmerlynn** [comment]
Can you just put this in an AWS-specific block? It seems like that should work.

**Comment by zmerlynn** [comment]
(And by "this" I mean "future Salt variable gunk")

**Comment by justinsb** [comment]
I think I'm going to try to lock AWS to the same version as GCE, and then think more about a long-term plan once AWS is working again!

**Comment by justinsb** [comment]
@derekwaynecarr from the looks of things I think vagrant will have the same problem (?)

(Note that I am in the process of developing / testing the branch above, so I don't think you can just copy-and-paste the fix - yet!)

**Comment by rhohan** [comment]
As a short term fix, using 2015.05 (ubuntu trusty salt ppa), was to change container_bridge.py:20 

from:
import salt.util.ipaddr as ipaddr
to:
import salt.ext.ipaddr as ipaddr

this actually seems to be working. salt.ext.ipaddr might be deprecated. but not in 2015.05.

why is there a container_bridge custom state at all btw? why not use network.managed and iptables.insert?

**Comment by justinsb** [comment]
@rhohan - I'm not sure we can just change the import, because I think we have to be compatible with GCE's version of salt also.

I'm not sure of why we did it this way vs other ways of doing things in salt

**Comment by justinsb** [comment]
Does this mean that the official k8s distribution is broken on AWS, BTW?  When is the next point release (and where are these discussed)?

**Comment by zmerlynn** [comment]
We cherry-pick into point releases as necessary, and it's been pretty informal and usually initiated by us (Google). I'd actually be happy to have a discussion about how to initiate it externally (we're going to need a policy for requesting such things). cc @goltermann

**Comment by zmerlynn** [comment]
FWIW, policy aside, I'm happy to cut a point release for this once you think #8131 is tested well enough.

**Comment by justinsb** [comment]
That would be great, thanks.  I'll be testing it pretty hard today, I think.

It has occurred to me that other clouds may also be broken.  By grepping, it looks like vagrant and vsphere use bootstrap.saltstack.com.  I am utterly unfamiliar with the vsphere implementation, and I think vagrant sidesteps the issue because on Redhat is skips the call to container_bridge.ensure.  It might be good to get confirmation that vagrant hasn't fallen in to a different trap though!

Let me test it out today (unless people start filing lots of issues, in which case I think we roll it out more urgently...)

**Comment by derekwaynecarr** [comment]
I will test out the Vagrant setup today, but I think we should be good because we do not use the same networking setup.

**Comment by zmerlynn** [comment]
@justinsb File a bug for a 0.17.1 to get this cherry-picked and assign it to me, as a reminder?

**Comment by stevesloka** [comment]
@justinsb @zmerlynn Do you know the status of 17.1? I'm seeing the same problems trying to AWS working, even tried an older release (e.g. v15), and have the same problem. My script looks 32 times on "[salt-master not working yet]" then gives up.

**Comment by zmerlynn** [comment]
We're cutting one today.

**Comment by stevesloka** [comment]
@zmerlynn I'm still seeing the same issue as before with the new release, my master starts then times out waiting for salt-master to start. Do you know some spots I can look at to help troubleshoot? Do you want a new issue created to track against?

**Comment by zmerlynn** [comment]
Please file a new issue and tag @justinsb, thanks. I'm sorry it didn't fix
things for you!
