### ISSUE TITLE
Scary warnings spinning up e2e on GCE

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8117]
This happens over and over.  Scary messages.

WARNING: Lists should be separated by commas, try "--allow=tcp,udp,icmp,esp,ah,sctp". If you intend to use udp, icmp, esp, ah, sctp for positional arguments, put them before the flag.
WARNING: Lists should be separated by commas, try "--scopes=storage-ro,compute-rw". If you intend to use compute-rw for positional arguments, put them before the flag.
WARNING: Lists should be separated by commas, try "--metadata-from-file=startup-script=/usr/local/google/home/thockin/src/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/../cluster/gce/configure-vm.sh,kube-env=/tmp/kubernetes.MURmzX/master-kube-env.yaml". If you intend to use kube-env=/tmp/kubernetes.MURmzX/master-kube-env.yaml for positional arguments, put them before the flag.
WARNING: Lists should be separated by commas, try "--disk=name=e2e-test-thockin-master-pd,device-name=master-pd,mode=rw,boot=no,auto-delete=no". If you intend to use device-name=master-pd, mode=rw, boot=no, auto-delete=no for positional arguments, put them before the flag.

**Comment by zmerlynn** [comment]
That's a new one. gcloud started getting a little more anal here. Exciting.

cc @jlowdermilk

**Comment by jlowdermilk** [comment]
They changed list argument syntax a while back, but the warnings are new. Time to update startup scripts I guess.
