### ISSUE TITLE
Disk fills up on GCE minion and renders VM unreachable and cluster unusable

### ISSUE THREAD

**Issue by kylelemons** [GoogleCloudPlatform/kubernetes#8126]
Apologies in advance for how scant this bug report is.  My attempts to resuscitate the minion wound up wiping its disk and travel has lost my screen scrollback.

I had a kubernetes 0.12.0 cluster running in GCE with 1 f1-micro master and 1 n1-standard-1 minion.  I got an alert that the website served by my cluster was down, so I went to investigate.  Sure enough, the pods were all pending.  The events log said that they were scheduling, and the pod log said unable to reach something (I assume the kubelet or etcd).  I tried to SSH into the machine both via my local SSH key and via the web, but no dice.  Expanded the serial console and I see a lot of errors from the GCE periodic job that updates SSH keys; apparently the disk is full!  I try to reboot the machine, but I still can't get into it afterward.  I try to stop the instance, hoping that I can extract something interesting by mounting the pd on the master, but to my surprise the instance disappears and a new one takes its place (taking its pd with it).  I have to assume this is some side-effect of using instance groups.  Unfortunately, now the new minion isn't getting set up correctly because the minion ip range variable isn't propagating (it looks like this bug has already been filed).  I tried and failed for a few hours to resurrect the cluster, but gave up and downed it.

I will not feel bad if you close this bug as not reproducible, but I wanted to document my experience in case these issues have not already been captured elsewhere.

Edit: I should also mention that the docker containers run fine without filling up their root disk normally, I'm not entirely sure why they're filling up the disk in kubernetes.

**Comment by roberthbailey** [comment]
@rjnagal

**Comment by rjnagal** [comment]
I am trying to fix this with #8108. Kubelet will try to keep a minimum disk space free on the machine. When diskspace gets low, it will start rejecting new pods.

This addresses only one part of the problem. Existing pods and workloads can still eat up all the disk space. We have some image and container GC to at least clean up stale stuff.

#4135 is the main issue to handle all out of disk scenario.

**Comment by rjnagal** [comment]
closing it as a dup of #4135 .
@kylelemons we would still like to know why the disk got full. If you do run into this again, please capture events from master.
