### ISSUE TITLE
Reduce scope of Service.Spec.PublicIPs

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8139]
The Service.Spec.PublicIPs field is VERY broad and I don't think we can reasonably go to 1.0 with it as-is.  Now that we understand better what most people do with it, I think we must find a better API that enables correct usage and eliminates dangerous and incorrect usage.

I will draft such a change and stick it here.

**Comment by lavalamp** [comment]
Isn't it enough to document that only IPs routed to your nodes or allocated by the cloud provider (or other service) are legal, and other IPs should be expected to stop paying validation without warning?

**Comment by thockin** [comment]
That's the bare minimum, I guess.  I think we can do a bit better.

**Comment by davidopp** [comment]
@thockin are you working on this? If not, we should find an owner.

**Comment by thockin** [comment]
I am working on it by proxy with Justin

On Tue, May 19, 2015 at 3:16 PM, David Oppenheimer <notifications@github.com
