### ISSUE TITLE
Repo cannot alone via ssh

### ISSUE THREAD

**Issue by linfan** [GoogleCloudPlatform/kubernetes#8147]
In the step 1) of docs https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

Clone repo kubernetes via ssh would fail:

```
$ git clone git@github.com:GoogleCloudPlatform/kubernetes.git
Cloning into 'kubernetes'...
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Better to change it to the [https one](https://github.com/GoogleCloudPlatform/kubernetes.git).

**Comment by WIZARD-CXY** [comment]
hello, I am not the owner of k8s, but I can clone vis ssh. Maybe it's your github key issue.

**Comment by BenTheElder** [comment]
In any case, the docs generally tell us to use https or https://get.k8s.io so I've opened a PR to change it to https.

**Comment by BenTheElder** [comment]
Hmm so I've just tested this from a computer that has not previously interacted with github (a little debian server). It fails similarly.
