### ISSUE TITLE
DNS healthcheck broken by new exec semantics

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8163]
#8011 went in, so I think the DNS healthcheck is broken now.

@vishh should be an easy fix.

**Comment by roberthbailey** [comment]
Was this caught by an e2e test? If not, why not?

**Comment by brendandburns** [comment]
No, e2e (on GCE at least) is green.  Do we e2e the DNS healthcheck?

**Comment by thockin** [comment]
It looks like the DNS healthcheck might never have worked as intended.

**Comment by thockin** [comment]
Specifically, it always emits "OK" and exits 0, as far as I can tell.

**Comment by vishh** [comment]
Looking into this issue now.

**Comment by thockin** [comment]
The fix is easy but we have no DNS e2e test (yet, Vish and I talked about it).  I'm inclined to push the fix for this even without e2e coverage, since it's legit busted right now.
