### ISSUE TITLE
Flannel doesnt Start

### ISSUE THREAD

**Issue by adarell** [GoogleCloudPlatform/kubernetes#8176]
Hi,

i tried to deploy a kubernetes Cluster with the "getting started" guide for ubuntu with the kube-up.sh.
The deployment stop at "validating root@<ip>" and paint dot every 3 seconds. i checked the log files on the minions and in the flanneld.log i found this: 
E0513 15:01:06.825805 05843 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [14]
E0513 15:01:07.827145 05843 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [14]
E0513 15:01:08.828509 05843 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [14]
E0513 15:01:09.829765 05843 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [14]
E0513 15:01:10.831155 05843 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [14]
E0513 15:01:11.832598 05843 main.go:171] Failed to create SubnetManager: 100: Key not found (/coreos.com) [14]

dont know why the flannel doesn't come up. I have only one Network interface on every minion and master. do i need another interface?
Here are my config:
master/minion1: 172.16.44.194
minion2: 172.16.44.195
minion3: 172.16.44.196

and here is my config-default.sh:

export nodes="root@172.16.44.194 root@172.16.44.195 root@172.16.44.196"
-# Define all your nodes role: a(master) or i(minion) or ai(both master and minion), must be the order same
export roles=("ai" "i" "i")
-# Define minion numbers
export NUM_MINIONS=${NUM_MINIONS:-3}
-# define the IP range used for service portal.
-# according to rfc 1918 ref: https://tools.ietf.org/html/rfc1918 choose a private ip range here.
export PORTAL_NET=10.11.1.0/24
-# define the IP range used for flannel overlay network, should not conflict with above PORTAL_NET range
export FLANNEL_NET=192.168.0.0/16

**Comment by rjnagal** [comment]
Looks like flannel didn't like the etcd keys in your configuration

@WIZARD-CXY can possibly help.

**Comment by WIZARD-CXY** [comment]
@adarell looks like flannel can't get net config from etcd properly.
Please check the `/var/log/upstart/etcd.log` for any error msg. If there isn't any, manually run the `reconfDocker.sh` on every minion. It is in the `~/kube` directory and see if it helps

**Comment by adarell** [comment]
Tank you very much,
it seems that Flannel is now running:
I0515 09:26:14.201913 14348 main.go:228] Using 172.16.44.194 as external interface
I0515 09:26:14.202707 14348 subnet.go:334] Picking subnet in range 192.168.1.0 ... 192.168.255.0
I0515 09:26:14.296748 14348 subnet.go:97] Subnet lease acquired: 192.168.85.0/24
I0515 09:26:14.300527 14348 main.go:245] UDP mode initialized
I0515 09:26:14.300723 14348 udp.go:212] Watching for new subnet leases
I0515 09:26:14.380478 14348 udp.go:237] Subnet added: 192.168.30.0/24
I0515 09:26:14.703583 14348 udp.go:237] Subnet added: 192.168.51.0/24

but the kube-up.sh keeps on to validate and paint dots.
The only thing i see in the log files is:

Kube-controller-manager.log:
I0515 09:34:08.655688   14351 nodecontroller.go:577] Evicting pods2: 2015-05-15 09:34:08.655675824 +0200 CEST is later than 2015-05-15 09:34:08.655674177 +0200 CEST + 4m20s
I0515 09:34:09.206182   14351 nodecontroller.go:577] Evicting pods2: 2015-05-15 09:34:09.206168667 +0200 CEST is later than 2015-05-15 09:34:09.206166657 +0200 CEST + 4m20s
I0515 09:34:09.259258   14351 nodecontroller.go:577] Evicting pods2: 2015-05-15 09:34:09.259247235 +0200 CEST is later than 2015-05-15 09:34:09.259245653 +0200 CEST + 4m20s

kube-apiserver.log (seems ok to me):
I0515 09:25:44.251540   14349 server.go:330] Serving read-only insecurely on 0.0.0.0:7080
I0515 09:25:44.251672   14349 server.go:367] Serving securely on 0.0.0.0:6443
I0515 09:25:44.251788   14349 server.go:395] Serving insecurely on 0.0.0.0:8080
I0515 09:25:46.309221   14349 server.go:377] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
I0515 09:25:48.709197   14349 publish.go:152] setting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{172.16.44.194 <nil>}] [{ 6443 TCP}]}]}
I0515 09:25:48.781358   14349 publish.go:152] setting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{172.16.44.194 <nil>}] [{ 7080 TCP}]}]}

kube-scheduler.log:
E0515 09:25:43.937659   14347 reflector.go:123] Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1beta3/services: dial tcp 127.0.0.1:8080: connection refused
E0515 09:25:43.937749   14347 reflector.go:123] Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1beta3/nodes: dial tcp 127.0.0.1:8080: connection refused
E0515 09:25:43.937862   14347 reflector.go:123] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1beta3/pods?fieldSelector=spec.host%3D: dial tcp 127.0.0.1:8080: connection refused

etcd.log (seems ok to me):
2015/05/15 09:25:48 raft: 31cad35bacd312a4 received vote from 31cad35bacd312a4 at term 4
2015/05/15 09:25:48 raft: 31cad35bacd312a4 [logterm: 1, index: 3] sent vote request to 523c5eeb880ff7ee at term 4
2015/05/15 09:25:48 raft: 31cad35bacd312a4 [logterm: 1, index: 3] sent vote request to f74a8f355f4606f7 at term 4
2015/05/15 09:25:48 sender: the connection with f74a8f355f4606f7 becomes active
2015/05/15 09:25:48 raft: 31cad35bacd312a4 received vote from f74a8f355f4606f7 at term 4
2015/05/15 09:25:48 raft: 31cad35bacd312a4 [q:2] has received 2 votes and 0 vote rejections
2015/05/15 09:25:48 raft: 31cad35bacd312a4 became leader at term 4
2015/05/15 09:25:48 raft.node: 31cad35bacd312a4 elected leader 31cad35bacd312a4 at term 4
2015/05/15 09:25:48 etcdserver: published {Name:infra0 ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster c4a10c9c5e095c1a
2015/05/15 09:25:51 sender: the connection with 523c5eeb880ff7ee becomes active

i think it is know the kube-scheduler but i dont know how to fix....

Sry for my bad english!

**Comment by adarell** [comment]
hi all, 
sry for my blindness. Found an config failure in the config-default.sh.
i had to configure a cluster DNS.
After i configured that the Cluster comes up.
didnt fount that in the ubuntu.md guide.
Thank you all for your help!!!!

**Comment by rjnagal** [comment]
Thanks @adarell for letting us know.

@WIZARD-CXY or I'll take a pass on the guide to add dns details

**Comment by WIZARD-CXY** [comment]
@adarell please look at the `Deploy addons` section which include the dns setup.In the future, I will include monitoring and logging components.

**Comment by 121599386** [comment]
at Master run :
etcdctl mk /coreos.com/network/config '{"Network":"172.17.0.0/16"}' 
can slove your problem

**Comment by Icedroid** [comment]
How to fix it. I can't run etcdctl.
flanneld.service - Flanneld overlay address etcd agent
   Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled)
   Active: failed (Result: timeout) since 二 2015-07-07 17:13:43 CST; 52s ago
 Main PID: 12566

7月 07 17:13:36 uapi1 flanneld[12566]: E0707 17:13:36.421659 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [65]
7月 07 17:13:37 uapi1 flanneld[12566]: E0707 17:13:37.423273 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [65]
7月 07 17:13:38 uapi1 flanneld[12566]: E0707 17:13:38.425193 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [66]
7月 07 17:13:39 uapi1 flanneld[12566]: E0707 17:13:39.427008 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [66]
7月 07 17:13:40 uapi1 flanneld[12566]: E0707 17:13:40.428967 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [66]
7月 07 17:13:41 uapi1 flanneld[12566]: E0707 17:13:41.430955 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [66]
7月 07 17:13:42 uapi1 flanneld[12566]: E0707 17:13:42.432988 12566 main.go:151] Failed to create SubnetManager: 100: Key not found (/config) [66]
7月 07 17:13:43 uapi1 systemd[1]: flanneld.service operation timed out. Terminating.
7月 07 17:13:43 uapi1 systemd[1]: Failed to start Flanneld overlay address etcd agent.
7月 07 17:13:43 uapi1 systemd[1]: Unit flanneld.service entered failed state.

**Comment by ckleban** [comment]
On a fresh new build of k8 following this guide, I get these same errors. Seem like the kube-up script isn't handling this well. (i didn't follow the dns-add on package at all). Seems like networking is broken. 

I ran this command:
/opt/bin/etcdctl mk /coreos.com/network/config '{"Network":"172.17.0.0/16"}' 

which fixed the flannel error logs, but networking things still aren't working. (like connecting to a service when exposing a publicip).

**Comment by WIZARD-CXY** [comment]
@ckleban maybe some etcd issue occured during the deployment. You can run `reconfDocker.sh` in your ~/kube/ after you start flannel successfully.
