### ISSUE TITLE
Liveness probe failures should be logged by default

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8179]
It seems that the default v=2 logging does not include the fact that liveness probes failed or their output.  It should - this is significant.

Also all exec probes say "health check", even if it is a readiness check, I think.

**Comment by lavalamp** [comment]
do they at least file an event?

**Comment by yujuhong** [comment]
There is an event for failed readiness check, but not for liveness check.

**Comment by yujuhong** [comment]
@thockin has a PR for logging: #8238

**Comment by brendandburns** [comment]
This is closed by #8238 as far as I can tell.
