### ISSUE TITLE
Kubelet log: error creating mirror pod

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8180]
Failed creating a mirror pod "fluentd-elasticsearch-kubernetes-minion-jrlj_default": Pod "fluentd-elasticsearch-kubernetes-minion-jrlj" is forbidden: A mirror pod may not reference secrets

@yujuhong for prio and team assignment

**Comment by yujuhong** [comment]
The relevant secret account code was added in #7101. It prevents mirror pods from accessing secrets or service accounts. 

@satnam6502, I think this is why you didn't see your fluentd pods yesterday.

**Comment by yujuhong** [comment]
Add more people who participated in #7101 to see if secret should be used my mirror pods, and what the alternatives are: @erictune, @liggitt

@satnam6502, I assigned the issue to you since you practically own fluentd & elasticsearch. Feel free to reassign.

**Comment by satnam6502** [comment]
I am happy to take on this issue -- but I would like to talk to someone who can explain to me why the node level logging agents are not allowed to access the logging secrets that were created specifically for their use? Until then I can remove their use of secrets since I had not added yet the reason for their use (a refinement for getting label metadata that required apiserver access).

**Comment by liggitt** [comment]
If I understand correctly, mirror pods come from a manifest file given directly to a kubelet, and they should not assume the kubelet has a connection to the API at all (which it would need to resolve service account or secret references from the pod spec). If the goal is to run a pod on every node, I'm wondering if what is described in #1518 is a better path there.

The ServiceAccount admission controller is responsible for ensuring every pod has an associated service account, and (eventually) that the secrets referenced by the pod are allowed by the pod's service account.

In the case of a mirror pod, no modifications can be made to the pod spec by the admission chain, as indicated in the service account admission controller comment:
```
// Don't modify the spec of mirror pods.
// That makes the kubelet very angry and confused, and it immediately deletes the pod (because the spec doesn't match)
// That said, don't allow mirror pods to reference ServiceAccounts or SecretVolumeSources either
```

If we allow mirror pods (identified by the API only by the presence of an annotation) to skip serviceaccount/secret checks, then the secret-limiting ability of the admission controller is trivially circumvented by any arbitrary pod by the addition of an annotation.

**Comment by smarterclayton** [comment]
If mirror pods can ask for arbitrary secrets that means any one who can take control of a node can get all secrets from a namespace.  Seems dangerous

**Comment by yujuhong** [comment]
#8187 removed the secret usage in fluentd pods.

**Comment by satnam6502** [comment]
This is resolved by #8187.

**Comment by zhangguanzhang** [comment]
if you used an old version kubelet with a latest version kube-apiserver, will happend this

**Comment by thockin** [comment]
How much older?  We do support version skew, and I am never out of
sync more than one release.

**Comment by liggitt** [comment]
> if you used an old version kubelet with a latest version kube-apiserver, will happend this

are you trying to reference secrets from a static pod, or are you getting this message trying to run static pods that don't reference secrets?

**Comment by zhangguanzhang** [comment]
> How much older? We do support version skew, and I am never out of sync more than one release.
> […](#)
> On Thu, Jul 1, 2021 at 11:22 PM zhangguanzhang ***@***.***> wrote: if you used an old version kubelet with a latest version kube-apiserver, will happend this — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

My environment is kubelet: v1.15.5 kube-apiserver is v1.20.6. I see this problem occurred in the log

**Comment by zhangguanzhang** [comment]
> > if you used an old version kubelet with a latest version kube-apiserver, will happend this
> 
> are you trying to reference secrets from a static pod, or are you getting this message trying to run static pods that don't reference secrets?

there is no secres from a staticPod.

**Comment by thockin** [comment]
15 vs 20 is a very large version skew.  Generally we support 3 releases of skew: https://kubernetes.io/releases/version-skew-policy/

**Comment by yuanhuaiwang** [comment]
it happend when version is 1.18.3
My environment:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

log is 
 Failed creating a mirror pod for \"XX": pods \"XX is forbidden: a mirror pod may not reference secrets\n","stream":"stderr","time":"2021-09-01T13:20:13.221640873Z"}

**Comment by zhangguanzhang** [comment]
> it happend when version is 1.18.3
> My environment:
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> 
> log is
> Failed creating a mirror pod for "XX": pods "XX is forbidden: a mirror pod may not reference secrets\n","stream":"stderr","time":"2021-09-01T13:20:13.221640873Z"}

你的staticPod里使用了`imagePullSecret`或者`serviceaccount`了
