### ISSUE TITLE
Services failing to get a public IP on GKE 0.17.0

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#8184]
Also came up in our private testing of 0.17.0, I presume it may be showing up in GCE but haven't scoured the results analyzer yet. We have two tests flaking on on GKE jobs `Services should correctly serve identically named services in different namespaces on different external IP addresses` and `Services should be able to create a functioning external load balancer`. Both fail in the same way:

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:407
Expected error:
    <*errors.errorString | 0xc208182380>: {
        s: "service s0 in namespace e2e-ns-2015-05-13t053752-0 doesn't have a public IP after 240.00 seconds",
    }
    service s0 in namespace e2e-ns-2015-05-13t053752-0 doesn't have a public IP after 240.00 seconds
not to have occurred
```

So this might just be that the timeout needs to be bumped, but I worry there's a real problem.

cc @quinton-hoole @a-robinson @roberthbailey

**Comment by roberthbailey** [comment]
@a-robinson was looking into a low % failure rate for the creating external load balancer test.

**Comment by quinton-hoole** [comment]
For what it's worth, the flake rate for "Services should be able to create a functioning external load balancer" on our kubernetes-e2e-gce continuous integration is 7 failures out of the past 313 runs ~2.2%

**Comment by quinton-hoole** [comment]
For "Services should correctly serve identically named services in different namespaces on different external IP addresses" the flake rate is about 1% over the past 313 runs.

**Comment by quinton-hoole** [comment]
The flake rates for the above two tests on kubernetes-e2e-gke-test are not statistically different from kubernetes-e2e-gce.

**Comment by quinton-hoole** [comment]
@zmerlynn What flake rates are you referring to in the original issue report above.  Significantly higher than 1%?

**Comment by zmerlynn** [comment]
I could believe it's a 2% flake. They each flaked twice on both gke-test and gke-staging in the 0.17.0 window (which is a pain in the ass to figure out), for a total of 2/~50 runs on each test (roughly). So we saw an above average window, similar to the situation with #8113.

It made for a rather noisy release analysis.
