### ISSUE TITLE
Node coming up as master on G[C|K]E

### ISSUE THREAD

**Issue by zmerlynn** [GoogleCloudPlatform/kubernetes#8196]
```
$ kubectl get nodes
NAME                                                  LABELS    STATUS
k8s-staging-regtest-loop-2015-05-13-10-29-51-node-1   <none>    Ready
k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2   <none>    NotReady
k8s-staging-regtest-loop-2015-05-13-10-29-51-node-3   <none>    Ready
```

Node 2's kubelet logs:
```
E0513 17:35:31.557301   10906 kubelet.go:1298] error getting node: node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 not found
E0513 17:35:31.666994   10906 kubelet.go:1767] Cannot get host IP: cannot get node: node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 not found
I0513 17:35:31.667033   10906 manager.go:1222] Need to restart pod infra container for "etcd-server-k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2_default" because it is not found
E0513 17:35:31.667968   10906 kubelet.go:1767] Cannot get host IP: cannot get node: node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 not found
```

controller-manager side:
```
I0513 17:32:42.404862       7 nodecontroller.go:527] node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 is never updated by kubelet
I0513 17:32:47.422920       7 nodecontroller.go:537] node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 hasn't been updated for 1m5.422893194s. Last ready condition is: {Type:Ready Status:Unknown LastHeartbeatTime:2015-05-13 17:31:42 +0000 UTC LastTransitionTime:2015-05-13 17:32:42 +0000 UTC Reason:Kubelet never posted node status. Message:}
I0513 17:32:52.474976       7 nodecontroller.go:537] node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 hasn't been updated for 1m10.474968033s. Last ready condition is: {Type:Ready Status:Unknown LastHeartbeatTime:2015-05-13 17:31:42 +0000 UTC LastTransitionTime:2015-05-13 17:32:42 +0000 UTC Reason:Kubelet never posted node status. Message:}
I0513 17:32:57.492246       7 nodecontroller.go:537] node k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2 hasn't been updated for 1m15.492238494s. Last ready condition is: {Type:Ready Status:Unknown LastHeartbeatTime:2015-05-13 17:31:42 +0000 UTC L
```

I have a cluster to hand off if someone wants to debug. It's not a transient state: node 2 just failed to ever post a valid status.

cc @dchen1107 @davidopp 
cc @mbforbes @cjcullen (who looked at it briefly with me)

**Comment by dchen1107** [comment]
I will take a look soon.

**Comment by dchen1107** [comment]
Ok, why kubelet on node 2 talks to ip address of master instead of hostname? 

root@k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2:/var/log# ps -ef | grep kubelet
root     10906     1  3 17:35 ?        00:10:45 /usr/local/bin/kubelet --api_servers=https://10.240.49.47 --config=/etc/kubernetes/manifests --allow_privileged=False --v=2 --cluster_dns=10.51.240.10 --cluster_domain=kubernetes.local

It looks like a cluster up issue to me, not a node problem.

**Comment by roberthbailey** [comment]
It looks like `configure-vm.sh` failed to translate the master name into the fqdn (which is done [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L440-L450)).

**Comment by zmerlynn** [comment]
Fascinating. I think we're seeing instance-DNS flakiness, because that name is supposed to get converted ASAP.

But what's weirder is ... that's not even the master:
```
zml@k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2:~$ getent hosts k8s-staging-regtest-loop-2015-05-13-10-29-51-master
10.240.166.17   k8s-staging-regtest-loop-2015-05-13-10-29-51-master.c.cloud-kubernetes-dev.internal
zml@k8s-staging-regtest-loop-2015-05-13-10-29-51-node-2:~$ getent hosts k8s-staging-regtest-loop-2015-05-13-10-29-51-master | awk '{ print $2 }'
k8s-staging-regtest-loop-2015-05-13-10-29-51-master.c.cloud-kubernetes-dev.internal
```

**Comment by zmerlynn** [comment]
The `kube-env` is definitely right:
```
  KUBERNETES_MASTER_NAME: k8s-staging-regtest-loop-2015-05-13-10-29-51-master
```

**Comment by zmerlynn** [comment]
Okay, this is messed up. Here's node 1, which is happy:
```
$ cat /etc/salt/minion.d/grains.conf
grains:
  roles:
    - kubernetes-pool
  cbr-cidr: '10.48.1.0/24'
  cloud: gce
  docker_opts: '--insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --registry-mirror=''https://us-central1.docker-cache.clustermaster.net'''
  api_servers: 'k8s-staging-regtest-loop-2015-05-13-10-29-51-master.c.cloud-kubernetes-dev.internal'
```

Here's our unhappy node .... that decided to bring itself as a master:
```
$ cat /etc/salt/minion.d/grains.conf 
grains:
  roles:
    - kubernetes-master
  cbr-cidr: 10.48.0.0/24
  cloud: gce
```

**Comment by dchen1107** [comment]
@zmerlynn haha... I checked kube-env and did suspect unhappy node treat itself as master node based on those variables. But I didn't check salt state :-)

**Comment by zmerlynn** [comment]
I ... just can't get there. By the time we get here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L480, node-2 has `NODE_INSTANCE_PREFIX` set:

```
$ less /srv/salt-overlay/pillar/cluster-params.sls 
instance_prefix: 'k8s-staging-regtest-loop-2015-05-13-10-29-51'
node_instance_prefix: 'k8s-staging-regtest-loop-2015-05-13-10-29-51-node'
[...]
```

My best guess is that `$(hostname)` flaked here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L62 .

I think we're seeing a systemic issue where we're racing with GCE network configuration.

**Comment by zmerlynn** [comment]
I'm going to work up a PR that hopefully improves the reliability of this section to some extent.

**Comment by cjcullen** [comment]
<a href="https://imgflip.com/i/lgyf6"><img src="https://i.imgflip.com/lgyf6.jpg" title="made at imgflip.com"/></a>

**Comment by zmerlynn** [comment]
My working theory is that we raced with the configuration done normally by the GCE NetworkManager, leaving us in a bogus `$(hostname)` state when we made that check.

**Comment by roberthbailey** [comment]
Why are we relying on inferring the master/node status from the hostname. It should be obvious from the variables set in the kube-env if you are the master or not. Masters don't get passed `KUBERNETES_MASTER_NAME` so why not just check that? 

Making sure DNS is working is probably also good for reliability...

**Comment by zmerlynn** [comment]
On GKE, we actually pass the same kube-env on both sides for simplicity. We can obviously change that, but I was going for a change that didn't involve a deployment change on our side, too.
