### ISSUE TITLE
Unable to start kubelet - no space left on device

### ISSUE THREAD

**Issue by sub-mod** [GoogleCloudPlatform/kubernetes#8198]
Hi i am unable to start the kubelet
I am getting the following error
inotify_add_watch /sys/fs/cgroup/cpu,cpuacct: no space left on device
complete logs here : https://gist.github.com/sub-mod/bc4390ce648f315f4df6

kubectl version
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-3-g962f10ee580eea", GitCommit:"962f10ee580eea30e5f4ea725c4e9e3743408a58", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-3-g962f10ee580eea", GitCommit:"962f10ee580eea30e5f4ea725c4e9e3743408a58", GitTreeState:"clean"}

**Comment by rjnagal** [comment]
Dup of #7815

**Comment by sub-mod** [comment]
issue resolved
firefox was using lot of CPU, i killed firefox and few other applications and kubelet worka fine
Thants @rjnagal 
Kindly close this issue.

**Comment by rjnagal** [comment]
Good to know @sub-mod. Looks like the system was running out of global resources.

I think another problem here is that there are a huge number of raw cgroups being created by systemd and cadvisor is tracking them all.

@vmarmol we could run with --docker_only, but then it won't work for the new cgroups being created for docker-daemon, kube-proxy, etc. Would it be easier to inotify only on top-level containers and refresh subcontainers periodically?

**Comment by rjnagal** [comment]
closing this one for now. We can handle inotify issues in #7815
