### ISSUE TITLE
merge examples/storage into examples/persistent-volumes

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8212]
examples/storage is an example of how to configure NFS persistent volumes, we should move it into examples/persistent-volumes/volumes, and update the README in examples/persistent-volumes/simpletest. What do you think?

@markturansky @nikhiljindal

**Comment by nikhiljindal** [comment]
examples/storage wont exist once we submit https://github.com/GoogleCloudPlatform/kubernetes/pull/8073

**Comment by caesarxuchao** [comment]
Oh yes, the move is already done. The folder name 'simpletest' doesn't make much sense. How about move the files out of 'simpletest' and remove the folder?

**Comment by markturansky** [comment]
@caesarxuchao what do you recommend as the new name for "simpletest" or where would the files go?  If we want to have many scenarios/examples of people using PVs, then perhaps something like 'simpletest' (or with a better name) stays, but the /volumes and /claims folders are broken down and the files therein go to the appropriate scenario/example.

Currently, 1 volume and 1 claim are used with the single pod and service in 'simpletest'.   Together, they comprise a single scenario.  They are even used in the integration tests together.

**Comment by caesarxuchao** [comment]
@markturansky, on second thought, I think we should keep the simpletest folder, but let's move the README file one level up to examples/persistent-volumes/. It's nice for a user to be greeted by a README file when he/she opens an example. What do you think?

**Comment by markturansky** [comment]
@caesarxuchao Agreed that it's nice to open the directory with the full README.  Better user experience when learning this feature. I will submit a PR.

**Comment by caesarxuchao** [comment]
Thank you!

**Comment by vmarmol** [comment]
Closing since #8256 was merged. Feel free to reopen if I missed something :)

**Comment by markturansky** [comment]
@vmarmol thanks!

**Comment by caesarxuchao** [comment]
Thank you!
