### ISSUE TITLE
Regression: integration test failed from HEAD

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#8217]
E0513 22:55:45.078788     957 controller.go:121] unable to sync kubernetes RO service: endpoints "kubernetes-ro" cannot be updated: the resource was updated to 266
E0513 22:55:45.080181     957 controller.go:121] unable to sync kubernetes RO service: endpoints "kubernetes-ro" cannot be updated: the resource was updated to 266
E0513 22:55:48.496436     957 reflector.go:165] watch of *api.Secret ended with: Stop requested
E0513 22:55:48.496531     957 reflector.go:165] watch of *api.ServiceAccount ended with: Stop requested
E0513 22:55:48.496610     957 reflector.go:165] watch of *api.Namespace ended with: Stop requested
E0513 22:55:48.496679     957 reflector.go:165] watch of *api.ServiceAccount ended with: Stop requested
E0513 22:55:48.496755     957 reflector.go:165] watch of *api.Secret ended with: Stop requested
E0513 22:55:48.496829     957 reflector.go:165] watch of *api.ServiceAccount ended with: Stop requested
W0513 22:55:49.950696     957 controller.go:228] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 6443 TCP}]}]}
W0513 22:55:50.032123     957 controller.go:228] Resetting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 7080 TCP}]}]}
W0513 22:55:50.032675     957 controller.go:228] Resetting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 7080 TCP}]}]}
W0513 22:55:50.033190     957 controller.go:228] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 6443 TCP}]}]}
W0513 22:55:50.113191     957 controller.go:228] Resetting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 7080 TCP}]}]}
W0513 22:55:50.172132     957 controller.go:228] Resetting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 7080 TCP}]}]}
W0513 22:55:50.193833     957 controller.go:228] Resetting endpoints for master service "kubernetes-ro" to &{{ } {kubernetes-ro  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.0.0.22 <nil>}] [{ 7080 TCP}]}]}
E0513 22:55:50.394191     957 controller.go:92] unable to sync kubernetes service: endpoints "kubernetes" cannot be updated: the resource was updated to 279
E0513 22:55:50.395083     957 controller.go:121] unable to sync kubernetes RO service: endpoints "kubernetes-ro" cannot be updated: the resource was updated to 280
E0513 22:55:50.475196     957 controller.go:121] unable to sync kubernetes RO service: endpoints "kubernetes-ro" cannot be updated: the resource was updated to 280
E0513 22:55:50.476604     957 controller.go:121] unable to sync kubernetes RO service: endpoints "kubernetes-ro" cannot be updated: the resource was updated to 280
E0513 22:55:50.478775     957 controller.go:121] unable to sync kubernetes RO service: endpoints "kubernetes-ro" cannot be updated: the resource was updated to 280
W0513 22:55:51.538401     957 master.go:216] Portal net unspecified. Defaulting to 10.0.0.0/24.
I0513 22:55:51.538769     957 master.go:249] Will report 10.0.0.22 as public IP address.
E0513 22:56:00.274311     957 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0513 22:56:00.675185     957 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0513 22:56:00.877114     957 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0513 22:56:01.273530     957 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0513 22:56:08.076736     957 reflector.go:165] watch of *api.Secret ended with: Stop requested
E0513 22:56:08.076974     957 reflector.go:165] watch of *api.ServiceAccount ended with: Stop requested
E0513 22:56:08.077520     957 reflector.go:165] watch of *api.Namespace ended with: Stop requested
E0513 22:56:08.077759     957 reflector.go:165] watch of *api.ServiceAccount ended with: Stop requested
E0513 22:56:08.078025     957 reflector.go:165] watch of *api.Secret ended with: Stop requested
E0513 22:56:08.078269     957 reflector.go:165] watch of *api.ServiceAccount ended with: Stop requested
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/test/integration	111.315s

**Comment by liggitt** [comment]
Do we know which test is failing? The last messages in the log are from `test/integration/service_account_test.go`, but I don't actually see a test failure message printed, and I can't recreate any failures.

The "Unable to authenticate the request due to an error: Token has been invalidated" messages are expected since the test exercises attempting to use invalid tokens (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/integration/service_account_test.go#L304-L308)

Also, the "Stop requested" messages indicate that particular test completed and invoked the deferred stopFunc, which shuts down the controllers and closes the test server

**Comment by dchen1107** [comment]
Here is the failing test: 
--- FAIL: TestPersistentVolumeClaimBinder (3.45s)
	persistent_volumes_test.go:106: Expected claim to be bound: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:claim02 GenerateName: Namespace:default SelfLink:/api/v1beta1/persistentVolumeClaims/claim02?namespace=default UID:0e2d09c0-f9c3-11e4-96ec-02420a000016 ResourceVersion:172 CreationTimestamp:2015-05-13 22:54:47 +0000 UTC DeletionTimestamp:<nil> Labels:map[] Annotations:map[]} Spec:{AccessModes:[ReadOnlyMany ReadWriteOnce ReadWriteMany] Resources:{Limits:map[] Requests:map[storage:{Amount:5000000000 Format:BinarySI}]} VolumeName:} Status:{Phase:Pending AccessModes:[] Capacity:map[]}}

**Comment by liggitt** [comment]
@markturansky, you aware of the issue with TestPersistentVolumeClaimBinder?

**Comment by dchen1107** [comment]
I ran into above issue a lot.

**Comment by markturansky** [comment]
Sorry, hadn't seen this sooner. Lost in the flurry of email traffic.

I am looking into it now.

**Comment by markturansky** [comment]
I cannot reproduce on F20, Go 1.3.1

I'll try 1.4 next.  Any other info would be appreciated.

**Comment by dchen1107** [comment]
Here is the output of docker version from my desktop.

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

I started to run into this issue two days ago, and just ran into it half hour ago right after I sync-ed to HEAD again. Any more information you need here?

**Comment by markturansky** [comment]
Thanks :)

**Comment by markturansky** [comment]
I cannot reproduce this on F20, Go 1.4.2

Any runtime settings I might be missing?  I see hack/test-integration.sh is set to "-race" .
