### ISSUE TITLE
Expose kubelet events/status over channel

### ISSUE THREAD

**Issue by nqn** [GoogleCloudPlatform/kubernetes#823]
It would make it much easier to interact with the kubelet (and carry out pod updates) if there were a way to introspect the status of operations outside of the kubelet. For example any hick-ups from Docker or if pods have containers which are conflicting with the ones already running, or simply conflict with TCP ports between each other.

Ran into the problem when wiring up the Kubernetes-Mesos executor (https://github.com/mesosphere/kubernetes-mesos/blob/master/executor/executor.go#L51). Not that this should be a driving force, but thought it would be a useful feature in general.

I am eager ears if you already have plans on doing this (or exposing local container statuses in another way).

Cheers,
Niklas

PS I was thinking something along the lines of https://github.com/mesosphere/kubernetes/commit/5aa83b2356013123943886d1ca848f0fa61a8d76 
It is not done, but would love to help out if we could get to consensus around that kind of feature.

**Comment by bgrant0607** [comment]
@dchen1107 Can we close this now?

**Comment by karlkfi** [comment]
I'm assuming this doesn't need to still be open since #2439 was added last November... Feel free to reopen or recreate if you feel otherwise.
