### ISSUE TITLE
"command" sets Entrypoint rather than Command?

### ISSUE THREAD

**Issue by larsks** [GoogleCloudPlatform/kubernetes#8235]
I am running Kubernetes kubernetes-0.15.0 (git 0ea87e4) on RHEL 7.

I have a Dockerfile that contains:

    ENTRYPOINT ["/usr/bin/stress"]

I would normally call it, for example, like this:

     docker run larsks/stress --cpu 1

I have a replicationController that contains:

          containers:
            - name: stress
              image: larsks/stress
              command: ["--cpu", "1"]

The resulting containers fail to start.  When I inspect the
containers, I see:

    "Config": {
        "Entrypoint": [
            "--cpu",
            "1"
        ],

That's wrong.  The `command:` key should be setting the `Command`
field of the container, otherwise a variety of images that are
designed with a custom entrypoint will fail to run.

**Comment by thockin** [comment]
Use the args[] field.  We had to normalize to cover multiple runtimes, so
we settled on "command" and "args", which is unfortunately not the same as
docker.

@bgrant0607 this is our last chance to reconsider this.  I still find
Docker's names wonky, but I have had 2 or 3 people ask this same question.

**Comment by bgrant0607** [comment]
Yes, Docker's terminology is ... less than ideal, but there is also a cost to being different. Added to the list for consideration for v1: #7018

**Comment by bgrant0607** [comment]
App container spec is simpler: https://github.com/appc/spec/blob/master/SPEC.md#pod-manifest-schema

**Comment by bgrant0607** [comment]
Documentation:
http://kubernetes.io/third_party/swagger-ui/#!/v1beta3/createPod
command (array[string], optional): entrypoint array; not executed within a shell; the docker image's entrypoint is used if this is not provided; cannot be updated,
args (array[string], optional): command array; the docker image's cmd is used if this is not provided; arguments to the entrypoint; cannot be updated,

**Comment by pmorie** [comment]
:-/

**Comment by bgrant0607** [comment]
Not changing this in v1.

**Comment by caleblloyd** [comment]
It looks like args are not being individually quoted in their array, the container configuration:

        - image: redis:latest
          name: slave
          args:
            - redis-server
              --port 6380
          ports:
            - containerPort: 6380
              name: slave

Yields the docker command:

        /entrypoint.sh 'redis-server --port 6380'

This causes an error, because the args are all being passed to the /entrypoint.sh script as a single command, $1

Shouldn't the docker command generated from this configuration be:

        /entrypoint.sh 'redis-server' '--port 6380'

**Comment by thockin-cc** [comment]
From a glance, it is giving you the yaml you asked for. Try - --port - the
leading dash indicates a new entry in an array.

**Comment by caleblloyd** [comment]
oops, coming from a json backround :)

thanks

**Comment by testcaoy7** [comment]
I also ran into this problem. I use WebUI. How to individually quote args in their array? I tried to add leading dash in the "Run command arguments" field, but I got './entrypoint.sh - --args1 - --args2 ...' which is also wrong.

**Comment by Pardhu448** [comment]
Is it possible to provide named args in Kubernetes manifest (.yaml) file in container configuration section, as in below.
This is required for passing values to ARG field in the container's DockerFile, which takes values from args filed of manifest file.
```
 - image: redis:latest
      name: slave
      args:
        - name: redis-server
          value: redis-server
        - name: port 
          value: --port 6380
      ports:
        - containerPort: 6380
          name: slave
```
DockerFile of slave container:
```
ARG redis-server
ARG port
```
I couldnt find any documentation to initialize named args in kubernetes manifest file. 

Thanks in Advance for Help!

**Comment by thockin** [comment]
No, there's not an equivalent mechanism today

**Comment by Pardhu448** [comment]
Ok. Thankyou!
