### ISSUE TITLE
kubectl trying to use v1beta3 api for get minions

### ISSUE THREAD

**Issue by nebelpfade** [GoogleCloudPlatform/kubernetes#8240]
kubectl 0.17.0:
curl http://localhost:8080/api/v1beta3/minions
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}

master3 core # /opt/bin/kubectl get mi                       
master3 core #

kubectl 0.16.0:
uses: http://localhost:8080/api/v1beta1/minions
master3 core # ./kubectl get mi
NAME            LABELS    STATUS
192.168.10.70   <none>    Ready
192.168.10.71   <none>    Ready

in the same time curl http://localhost:8080/api/v1beta3/nodes works well.

**Comment by rjnagal** [comment]
Shall we just remove "minion" from kubectl now and throw an error?

**Comment by rjnagal** [comment]
@bgrant0607 remove "minions"?

**Comment by bgrant0607** [comment]
Yes, that should be part of #8087.

cc @nikhiljindal @caesarxuchao @krousey

**Comment by bgrant0607** [comment]
Presumably `kubectl get nodes` works?

**Comment by gmarek** [comment]
Assigning @krousey who's working on #8087

**Comment by bgrant0607** [comment]
Ref #1111

**Comment by bgrant0607** [comment]
@jlowdermilk Could you please take a look at this?
