### ISSUE TITLE
Doc use of secrets for skydns example

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#8250]
It is not clear from the doc that you have to create a secret named 'dns-token'.

**Comment by thockin** [comment]
@cjcullen is this something you can do?  I took a look at the script to do this, and it's not obvious to the uninitiated what's happening.  This is causing pain for everyone who is not on a first-tier supported platform

**Comment by cjcullen** [comment]
Yeah. I'll take a look a little later today.

**Comment by erictune** [comment]
The path we are going with for v1 is that you just use the token provides due to the default service account for the namespace.  SkyDNS should use pkg/client/helper.go NewInCluster.

@lavalamp implemented that new helper function.

**Comment by thockin** [comment]
self-assigning - I will get a new kube2sky built which does not depend on the extra token or at least falls back on inCluster without it.

**Comment by thockin** [comment]
Here's the doc.  As of #10150 You don't need anything special.
