### ISSUE TITLE
changing permissions broke the kubernetes-master charm

### ISSUE THREAD

**Issue by mbruzek** [GoogleCloudPlatform/kubernetes#8252]
We tried to deploy the kubernetes Juju bundle and found that the commit f416289a85c9e55fffb6f84bd85b7298733737db changed the permissions on some key python files that broke the deployment of the Juju cluster.

Specifically: cluster/juju/charms/trusty/kubernetes-master/hooks/hooks.py                          100755 → 100644  

@eparis I see that the commit was largely to add a copyright header.  Was the change in permissions on purpose?  For these charms to work with Juju some files have to be executable.

**Comment by vmarmol** [comment]
@mbruzek I think that was not intentional. Will send a PR to restore permissions.

**Comment by mbruzek** [comment]
@vmarmol Thank you for the response.  Not all files need to be executable (just the ones that were originally executable)!  We were working on creating our own PR to fix this problem.

**Comment by vmarmol** [comment]
This is fixed, closing.
