### ISSUE TITLE
How can I upgrade my Kubernetes cluster?

### ISSUE THREAD

**Issue by idosh** [GoogleCloudPlatform/kubernetes#8258]

**Comment by rjnagal** [comment]
See:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cluster_management.md

**Comment by idosh** [comment]
I couldn't find support for Azure + Weave based cluster

**Comment by rjnagal** [comment]
@idosh The doc covers updating all kube master components and kubelets - which should mostly be same for all platforms if you followed the platform specific setup guide. Are you trying to update Weave, or a particular component?

**Comment by idosh** [comment]
I'm trying to update kubernetes itself. I'll try to follow the docs.

**Comment by bkeroackdsc** [comment]
Where is one expected to run ``kube-push.sh`` from? The master? As root?

An opaque script is not the most friendly upgrade path.

**Comment by errordeveloper** [comment]
@idosh in Azure/CoreOS/Weave implementation you could probably parametrise `download-kubernetes.service` unit to pull version string for a URL on start, so restarting it could then trigger an upgrade. However, this is probably not ideal as flags may change between releases, I would look forward to 1.0 to implement a better solution.

**Comment by rjnagal** [comment]
@bkeroackdsc It'll work from the machine that holds your new binaries and have auth for the cluster.

It's mostly a developer flow right now. Definitely needs a tool to upgrade between released versions post 1.0.

**Comment by idosh** [comment]
When is the first release?

**Comment by rjnagal** [comment]
sometime this summer.

**Comment by rjnagal** [comment]
Closing this one in favor of other generic issues under label - area/upgrade

**Comment by bgrant0607** [comment]
cc @fgrzadkowski
