### ISSUE TITLE
Delete /podInfo /nodeInfo from kubelet

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#8280]
We can delete the /podInfo and /nodeInfo APIs from kubelet, since it now posts its status to APIserver.

cc @yujuhong

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by yujuhong** [comment]
/nodeInfo has already been removed by #6702.

I think /podInfo is only used by integration test, and should be safe to delete.

**Comment by bgrant0607** [comment]
Forked from #8087
