### ISSUE TITLE
kubectl e2e tests broken

### ISSUE THREAD

**Issue by ixdy** [GoogleCloudPlatform/kubernetes#8300]
Several of the kubectl e2e tests were broken today by #8249, which added a missing check of an err return value, all of which now fail when doing cleanup and calling `kubectl stop`.

Example:
```
kubectl guestbook should create and stop a working application

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:125
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../cluster/../platforms/linux/amd64/kubectl [kubectl --server=https://104.197.99.179 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/config stop -f examples/guestbook] []  <nil>  Error: [Resizing the controller failed with: replicationControllers "frontend" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-master" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-slave" not found; Current resource version Unknown]
[] <nil> 0xc2083e6860 exit status 1 <nil> true [0xc20803a3f8 0xc20803a438 0xc20803a470] [0xc20803a3f8 0xc20803a438 0xc20803a470] [0xc20803a430 0xc20803a468] [0x657730 0x657730] 0xc20841cc60}:
Command stdout:

stderr:
Error: [Resizing the controller failed with: replicationControllers "frontend" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-master" not found; Current resource version Unknown, Resizing the controller failed with: replicationControllers "redis-slave" not found; Current resource version Unknown]
```

I think this may have been originally broken in #6194. That change refactored the implementation of Stop, which started masking the error, but it also changed the order of code a bit.

Previously, the Stop implementation in `pkg/kubectl/stop.go` first queried for ReplicationControllers before creating the ResizeCondition; the first thing in the method was
```go
  rc := reaper.ReplicationControllers(namespace)
  controller, err := rc.Get(name)
```

After the change, this is done following the ResizeCondition in `pkg/kubectl/resize.go`:
```go
rc := &api.ReplicationController{ObjectMeta: api.ObjectMeta{Namespace: namespace, Name: name}}
```

Is it possible that we're trying to query for something that's already been deleted, and thus it will always fail?

cc @quinton-hoole @roberthbailey

**Comment by ixdy** [comment]
OK, it seems like that's not what's broken; the actual Resize seems like it might be the problem.

It could have broken anytime since April 2, unfortunately.

cc @kargakis as well.

**Comment by ixdy** [comment]
Looks like #7544 is the culprit. It moved the kubectl tests into separate namespaces, but the cleanup() method is calling `kubectl stop` with the default namespace. (Also, the namespace may have even been deleted by the time cleanup() is called - but not sure.)

Let's include everyone. @jayunit100

**Comment by jayunit100** [comment]
interesting find ; Looks like now *maybe* whats happening, is that namespaces are being deleted fast enough that this causes a error.  before NS deletion took a long time?

**Comment by derekwaynecarr** [comment]
The speed of deleting a namespace was improved when moving to new controller framework:

https://github.com/GoogleCloudPlatform/kubernetes/pull/6771

There previously was a 1 minute delay before noticing that a namespace could be purged.

----- Original Message -----

**Comment by quinton-hoole** [comment]
I love it when stuff makes sense :-)

**Comment by roberthbailey** [comment]
#8309 partially fixes this. `kubectl update-demo should do a rolling update of a replication controller` is still failing consistently.

**Comment by quinton-hoole** [comment]
@ixdy Can you keep digging on this one?  I'm busy on #8326. Provisionally assigning to you.

**Comment by ixdy** [comment]
So I actually mentioned this particular case in #8303, though I wasn't sure if it was expected or not.

The test creates update-demo-nautilus, then does a rolling update to update it to update-demo-kitten. We have the cleanup function try to delete both, in case something breaks in the middle of the test, but it's failing because update-demo-nautilus doesn't exist - as expected?

We can just remove the cleanup for this test case, since cleanup should be handled by the namespace deletion. I'm curious how this ever passed before, though.

**Comment by ixdy** [comment]
Created #8333 to remove the cleanup if we think that's a reasonable solution.

**Comment by roberthbailey** [comment]
@ixdy has this been fixed?

**Comment by ixdy** [comment]
I believe so, yes. It is at least not consistently failing anymore.
