### ISSUE TITLE
Wrong certificates in k8s cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/kubernetes#8315]
After syncing today I get the following errors in kubelet logs:

E0515 10:42:54.160745    3462 reflector.go:130] Failed to list *api.Pod: Get https://10.240.81.1/api/v1beta3/pods?fieldSelector=spec.host%3De2e-test-filipg-master: x509: certificate is valid for 104.155.29.206, not 10.240.81.1

I see a similar error for (almost) all requests.

@lavalamp This could be related to #8071

**Comment by fgrzadkowski** [comment]
@wojtek-t

**Comment by fgrzadkowski** [comment]
@jayunit100

**Comment by roberthbailey** [comment]
Did you kube-push? I admit that I didn't test that path but only the cluster create/delete flow....

**Comment by roberthbailey** [comment]
As an aside, if we expect kube-push to always work correctly, then we need to add an e2e test for it to verify that it isn't breaking from PRs.

**Comment by fgrzadkowski** [comment]
AFAIR first I only pushed, but then I did down & up.

Note that the certificate itself could be ok, it's just that we are using internal IP for connection, while certificate is generated for the external one. Has something changed with regard to this?

**Comment by roberthbailey** [comment]
The certificate on the master is signed with $MASTER_NAME and has the external IP as a SAN (subject alternate name). Before this change we were using salt to construct a fqdn for the master name but the fqdn isn't included in the cert. So the kubelet will be connecting to something like `https://kubernetes-master.c.project` and the cert is signed for `kubernetes-master`.

**Comment by fgrzadkowski** [comment]
I double checked where this happens, and it's only a problem in kubelet running on master machine.

**Comment by roberthbailey** [comment]
I wonder if this was actually broken as a combination of my change and #8009. In that change it looks like we caused the master to no longer write any auth data for the kubelet running on the master node.

/cc @mbforbes

**Comment by mbforbes** [comment]
This looks like the same issue I saw in #8207?

**Comment by mbforbes** [comment]
- I wonder why this happens only sometimes?
  - If it happens always, then me seeing it in #8207 was a red herring for the issue I was having.
  - Does this have any symptoms besides the errors in the kubelet log?
- Is the kubelet on the master a first-order citizen?
  - I thought it wasn't actually managing any pods, and the only pods that ran on the master are from startup. Please correct me if I'm wrong.
  - If I'm not, why is it running there?
  - If I am, we should probably put the kubelet token on the master too.

**Comment by bprashanth** [comment]
@mforbes the kubelet on the master is responsible for setting up the (static) pods the master components run in

**Comment by mforbes** [comment]
@bprashanth Please address @mbforbes instead.

**Comment by mbforbes** [comment]
I opened #8444 to (hopefully) address this. (Pending e2e runs.)

**Comment by mbforbes** [comment]
@roberthbailey's #6949 was supposed to fix this--anyone able to repro at head?

**Comment by fgrzadkowski** [comment]
@roberthbailey The certificate problem is solved, but now I get the following errors:
```
E0520 00:50:40.178050    3473 kubelet.go:1523] error getting node: node e2e-test-filipg-master not found
E0520 00:50:40.191870    3473 kubelet.go:2097] Cannot get host IP: cannot get node: node e2e-test-filipg-master not found
```

**Comment by roberthbailey** [comment]
Is that on the master? The kubelet on the master shouldn't be trying to talk to the apiserver any longer.

**Comment by brendandburns** [comment]
Is this still relevant/open?  It was marked P0 and there have been no updates in 5 days.

**Comment by roberthbailey** [comment]
This should have been fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/8164

**Comment by roberthbailey** [comment]
@fgrzadkowski is this still a problem or can it be closed?

**Comment by thockin** [comment]
Closing.  re-open if it pops up

**Comment by fgrzadkowski** [comment]
Sorry for not responding. I missed this issue. I don't see this error anymore. The only error message is:
```
E0608 14:08:16.941655    5968 kubelet.go:2111] Cannot get host IP: cannot get node: node e2e-test-filipg-master not found
```
