### ISSUE TITLE
kubectl command aliases/renames

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#8319]
We've discussed these a few times. Recording in an issue for discussion/triage.

The proposals are to use more conventional terminology in kubectl for "porcelain" commands:

1. "run" rather than (or in addition to) "run-container". (ok, my bad)
2. "scale" rather than (or in addition to) "resize". https://github.com/GoogleCloudPlatform/kubernetes/issues/1629#issuecomment-93776977

These would match the terminology used by Docker, [Heroku](https://devcenter.heroku.com/articles/one-off-dynos#formation-dynos-vs-one-off-dynos), [CloudFoundry](http://docs.cloudfoundry.org/devguide/deploy-apps/cf-scale.html), and others.

We've also had feedback that it's unintuitive that run-container pods run forever by default. That's not the case in these other systems. Run once should probably be the default #4366.

And it should be possible to specify the command on the run command line #5581.

cc @smarterclayton @ghodss @jlowdermilk @brendandburns

**Comment by smarterclayton** [comment]
SGTM

----- Original Message -----

**Comment by ghodss** [comment]
I'm happy with those names, though my strong preference here is still to rename, not add aliases. I think while we still have a chance we should avoid (non-deprecated) aliases, we should definitely take it. It will simplify the help text, general documentation, blog posts people write about using kube, etc.

**Comment by bgrant0607** [comment]
I'm fine with that.

**Comment by jlowdermilk** [comment]
sgtm. I still think it's nice to keep the old name as a deprecated alias for ~1 release to give people a chance to update scripts.

**Comment by thockin** [comment]
Is it really worth adding this to the 1.0 schedule to avoid aliases?  We're cramming as it is.  Are aliases so bad?

**Comment by bgrant0607** [comment]
What we did for rolling-update was add a deprecation message to the previous command. That seems fine for now.

**Comment by ghodss** [comment]
Yes, and we can even keep the deprecation warnings into 1.0. I'm more concerned with a single canonical way to do things to simplify learning and documentation (especially documentation or guides that others write). I believe most Linux commands follow this convention of not perpetually supporting multiple ways to run one subcommand - git, vagrant, etc.

**Comment by gmarek** [comment]
Renames tends to confuse people. Yesterday I had to answer a question on IRC on minion/node rename, as it turned out that people are still using 'minion'. 

For me ```resize``` is much more natural than ```scale```, but I agree that ```run``` is strictly better than ```run-container```

**Comment by bgrant0607** [comment]
@gmarek The biggest problem with the minion/node rename IMO is that we haven't finished it.

As mentioned above, scale is, by far, more common terminology than resize.

Anyway, this is done and awaiting merge.

**Comment by andronat** [comment]
This is done, I think it can be closed

**Comment by bgrant0607** [comment]
Fixed by #8596
