### ISSUE TITLE
kubelet reports pods status as not ready when a container terminates with exit code 0 

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8327]
This causes #8307. In contrib/git-sync demo, the `git-sync` container voluntarily exits and gets recreated to "periodically" sync the git repo, but the pod is then reported as not ready,
```
$ kubectl get pods blog-pod -o yaml
status:
    Condition:
    - status: "False"
      type: Ready
    containerStatuses:
    - containerID: docker://b334dd2a6dbb25b9513e7a3924800fa7b34861f5853876a9bc50491e762a6bdb
      image: caesarxuchao/git-sync
      imageID: docker://06b871b5d0e455538eeee600c70c3de0f3aa7571d09eaa060667b9ae2385a4a2
      lastState:
        termination:
          containerID: docker://52b7dce89bdcd87c33c752a9b633a85754a92f8ea27b796a6925c8f477d23249
          exitCode: 0
          finishedAt: 2015-05-15T17:33:10Z
          startedAt: 2015-05-15T17:33:05Z
      name: git-sync
      ready: false
      restartCount: 12
      state:
        running:
          startedAt: 2015-05-15T17:33:15Z
```
The end result is that the service targets at this pod does not get endpoints and thus not working.

Thanks to @lavalamp for helping with the debugging. 
@nikhiljindal

**Comment by yujuhong** [comment]
The `git-sync` container was not running when kubelet reported the status, hence it was considered not ready. Because the containers in a pod share the same fate, the pod was not perceived as not ready.

Having short-lived containers as a service endpoint may encounter problem like this. I am not really convinced that this is kubelet's problem. It sounds like `git-sync` should be a cron job...

**Comment by caesarxuchao** [comment]
Forgot to add @proppy

**Comment by caesarxuchao** [comment]
@proppy Is it alright if I modify git-sync to make it run a for-loop?

Also, about the git-sync [dockerfile] (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/git-sync/Dockerfile),
```
FROM golang:1.4-onbuild
VOLUME ["/git"]
ENV GIT_SYNC_DEST /git
ENTRYPOINT ["/go/bin/git-sync"]
```
why can it use the /go/bin/git-sync as an ENTRYPOINT without copying/building it first? I thought this binary should be built from the [main.go], isn't it? Thanks. (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/git-sync/main.go)

**Comment by proppy** [comment]
@caesarxuchao sure, but it would still be nice to able to have a way to have background containers restarting periodically in a pod w/o failing the service.

**Comment by caesarxuchao** [comment]
@yujuhong , will it be useful if we let the user to config which containers will be considered by kubelet when it reports the readiness of the pod?

**Comment by yujuhong** [comment]
I am not sure kubelet restart is the right mechanism to run periodic tasks, and in this case, recreating the container isn't particularly efficient.  FYI, there is a discussion for adding a controller for cron jobs in #2156.

**Comment by caesarxuchao** [comment]
Thanks @yujuhong. Let's forget about letting kubelet restart periodic tasks. In general, if some containers are not critical to a service, ignoring the status of these containers and keeping the service alive will increase the availability of the service.

**Comment by huggsboson** [comment]
we'd like to have sidecar containers that aren't critical to a pod's overall functioning. i.e. a sidecar which can crash or become unavailable without pulling the pod from the load balancer.  In our case it is a sidecar which delivers some configuration to disk from a notoriously flakey service.  We'd like the pod to stay up, the conf it needs is on disk.  Should I file a separate issue for this?
