### ISSUE TITLE
pkg/client/clientcmd/api shouldn't depend on pkg/api

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#8339]
`clientcmd/api` has a dependency on pkg/api for `TypeMeta`, which it embeds in `Config`. Is it doing that to take advantage of validation code, or can Config just declare `kind` and `apiVersion` directly and avoid the dependency?

@deads2k, @bgrant0607, @thockin

**Comment by deads2k** [comment]
A quick try (just declaring a `TypeMeta` in the `clientcmd/api` package) seems to work fine with `kubectl config`.  I only included those out of habit.

**Comment by deads2k** [comment]
Out of curiosity, is this just for a proper separate of packages or is there some functional issue as well?

**Comment by jlowdermilk** [comment]
@thockin mentioned encountering an issue with tests, but it's mostly just for proper separation of packages.

**Comment by yujuhong** [comment]
Related: Remove json tags from pkg/api/types.go #3933

**Comment by bgrant0607** [comment]
See also #5625

**Comment by bgrant0607** [comment]
Not done:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/clientcmd/api/v1/types.go#L29
