### ISSUE TITLE
Rip out kubecfg.sh

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#834]
It's causing problems and is kind-of GCE dependent anyway, we should just use the kubecfg binary, and document the environment variables it uses.

**Comment by bgrant0607** [comment]
Reopened since it still needs to be removed.
/cc @jlowdermilk

**Comment by bgrant0607** [comment]
Doh. Didn't mean to declare this fixed in that PR.

**Comment by brendandburns** [comment]
Closing this (again) as it is a dupe of #2144
