### ISSUE TITLE
Why must status round-trip to old API versions?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8345]
When adding a field to the API, why must the status round-trip to old versions (currently v1beta1 and v1beta2)?

I'm adding a field to ServiceStatus, and serialization_test.go roundTrip is complaining (line 71) because I haven't added it to the obsolete API versions.

I understand why this is important for Spec, but this seems like something we don't need to enforce for obsolete API versions for Status.

**Comment by thockin** [comment]
The data is stored in a versioned form, and we don't necessarily know which
form will be stored.  That said, v1beta1 and v1beta2 are on death row so do
as little as you can get away with.
