### ISSUE TITLE
Give better troubleshooting steps if kube-up.sh hangs

### ISSUE THREAD

**Issue by goltermann** [GoogleCloudPlatform/kubernetes#8350]
A bunch of the util.sh scripts spin loop on checking for the k8s API.  I had an cluster do this, and didn't know what to do.  We should give better suggestions (for example, for GCE, SSH to master and nodes and look at /var/log/startupscript.log).

**Comment by aronchick** [comment]
One additional layer to this is when kube-up fails halfway through. It's not obvious that I need to run kube-down.sh if it bails, because permanent disks/fw rules/etc have been created, and trying to kube-up.sh again fails if those are present.
