### ISSUE TITLE
Openstack load balancer improvements

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#8352]
As discussed in PR #7852, we'd like to make two changes with respect to openstack load balancers:

1. When deleting a pool, delete all monitors that were associated with it. Currently they're only disassociated, not deleted, and according to @anguslees this is a bug.
1. When deleting a load balancer, look up the pool by its name, rather than by its ID, which is only known by the VIP associated with it. This will enable us to delete pools whose VIPs have already been deleted rather than stranding them forever.

@anguslees can you take care of this?

**Comment by anguslees** [comment]
Rewording the above - tracking multiple underlying resources introduces a
new "partial failure" state.

How do I indicate that I'm in this state since "exists" and the result of
create/delete are now not simple booleans?
Can I rely on the caller retrying indefinitely?
Can the state machine go create->partial of failures>delete or
delete->partial-failure->create?

**Comment by anguslees** [comment]
Yep, will do.

Re (2) - the code currently assumes "k8s lb exists" is synonymous with
"openstack vip exists".  The vip must be deleted before the pool, so if the
pool deletion fails and we want to do something better than just abandon it:

- should we say the lb exists if *either* the pool or vip exists?  If the
vip doesn't exist then we *know* it isn't functional.

- what if we fail during create?  It's conceivable that pool creation
succeeds, but vip creation fails and the attempt to unwind/delete the pool
also fails.  What should create/exists return in this case?

- Gus

**Comment by a-robinson** [comment]
> - what if we fail during create?  It's conceivable that pool creation
> succeeds, but vip creation fails and the attempt to unwind/delete the pool
> also fails.?

See my response in [the other thread](https://github.com/GoogleCloudPlatform/kubernetes/pull/7852#discussion_r30484017). Effectively we shouldn't try to unwind, but instead make each step of creation idempotent.

> - How do I indicate that I'm in this state since "exists" and the result of
> create/delete are now not simple booleans?

Do we need to be able to indicate it? I don't think we do. This is how I see the three commands right now

* CreateTCPLoadBalancer - An error indicates that the load balancer may not have been successfully created. Can be called repeatedly until it succeeds. 
* EnsureTCPLoadBalancerDeleted - An error indicates that the load balancer may not have been successfully deleted. Should be called repeatedly until it succeeds when the underlying service is deleted to ensure all resources have been cleaned up.
* GetTCPLoadBalancer - The bool returned indicates whether the load balancer should be expected to be functional, not merely whether any individual underlying components of it exist.

I'll improve the documentation in cloud.go to make this clear if you think it's a reasonable model.

> - Can I rely on the caller retrying indefinitely?

Yes, under this model the caller *should* retry indefintely, or at least call EnsureDeleted indefinitely when it gives up.

> - Can the state machine go create->partial-failure->delete or
> delete->partial-failure->create?

It should definitely be able to go create->partial-failure->delete to avoid stranding resources. As long as we use UIDs for names, we shouldn't have to deal with the delete->partial-failure-> create case.

-Alex
