### ISSUE TITLE
Copy of binary to GCS for GCE kube-up.sh fails silently

### ISSUE THREAD

**Issue by goltermann** [GoogleCloudPlatform/kubernetes#8353]
I was running get.k8s.io, and somehow got in a state where the the salt gz/sha1 were in my GCE bucket, but not the server gz/sha1.  This meant the cluster never came up and it hung the client script.

In gce/util.sh, we're pretty careful about how this works.

upload-server-tars calls copy-if-not-staged, which calls already-staged to see if the if the file has been staged, otherwise copy-if-not-staged will gsutil the file up to GCS.

I think this weirdness can happen if...
- we get into copy-if-not-staged and echo the server hash into the .sha1
- the file upload hit a glitch, and the gsutil - m -q -h command doesn't in fact pass the hash check.  then GCS deletes the uploaded files (the policy for files that don't hashcheck), but we don't note the error

Then the master/nodes will try to install k8s from GCS, but never find it.

Even worse, if you ctrl-c, then bring the cluster down and back up, it fails again
- it looks like already-staged is comparing to the local .sha1 that was generated last time.  This will pass, since the hash was generated and still does match - it's that GCS never got the file

So, if I'm right about the above, I think the best fix is to compare the hash of the local binary to the saved hash in GCS, not just assume that the presence of the local hash file means that everything is in GCS.

**Comment by goltermann** [comment]
Saw this again.  Removing _output/release-tar/*uploaded*sha1 "fixed" it.

already-staged() also won't work if you've manually removed the bucket or files within, since it's looking locally for the sha1.

**Comment by zmerlynn** [comment]
Yeah, that last one is intentional. That bucket isn't really meant to be user addressed - I guess you just blew it away in your cloud console?

**Comment by zmerlynn** [comment]
(I mean, it's not intentional, but I knew it existed.)

**Comment by goltermann** [comment]
I blew it away, but when I first got to it, it was in a bad state:
- kubernetes-salt.tar.gz/sha1 were there
- kubernetes-server-linux-amd64.tar.gz/sha1 were not there

However, the server.sha1 was included on my local filesystem, so the script thought it was uploaded.

We don't need to fix this for "someone went through and started killing GCS objects", but it looks like I'm hitting an upload failure somehow here.

**Comment by goltermann** [comment]
@justinsb do you think your fix for #8903 fixed this?

**Comment by justinsb** [comment]
@goltermann  I think it solves the easiest to hit problem where if you interrupt the upload (or the upload fails) then the upload will not be reattempted next time because the SHA marker file is present.

If someone / something changes the file on GCS "behind our back" I don't think my patch fixes that.

**Comment by goltermann** [comment]
Thanks.  I think that's enough for now - we can't guard against every way someone could mess with dependent resources.  This solves the most confusing/common case.
