### ISSUE TITLE
kube-version-change doesn't copy secretName field

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8360]
When I convert a v1beta1 pod configuration in secrets.md to v1beta3, the spec.volumes.secret.secretName field is not copied and it's left empty, i.e.,
I get
```
"secretName": ""
```
instead of 
```
"secretName": "ssh-key-secret"
```
@lavalamp @krousey @nikhiljindal

**Comment by lavalamp** [comment]
Possibly this implies that there's a bug in the conversion functions. Perhaps write a test in v1beta1/conversion_test.go for secret conversion?

**Comment by caesarxuchao** [comment]
Ok. Let me take a look.

**Comment by caesarxuchao** [comment]
@lavalamp, can I close this because we don't support v1beta1 anymore?

**Comment by lavalamp** [comment]
SGTM
