### ISSUE TITLE
Missing step of install kubectl in ubuntu doc

### ISSUE THREAD

**Issue by linfan** [GoogleCloudPlatform/kubernetes#8373]
Though I have successfully installed kubernetes via [the ubuntu doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md) :smiley: , still want to point out this doc missing the step to install `kubectl`.

Thus, if user just follow the guide in the doc without having much knowledge about kubernetes, he/she would get error "__It looks as if you don't have a compiled kubectl binary__" during the `validate-cluster` step of `kube-up.sh`.

Manually install kubectl on at least master node should be necessary (suggest to let user also install on minion node for convenience), any way, the installation step is [pretty simple](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/kubectl.md).

**Comment by WIZARD-CXY** [comment]
@linfan.Sorry I forget to mention that.I will update the doc this weekend.stay tuned

**Comment by WIZARD-CXY** [comment]
@linfan I update the scripts in pr #8752, you can try it now. 
I copied the kubectl binary from the kubernetes release and put it in `cluster/ubuntu/binaries/`, so there is no extra step for user to manually download `kubectl` . 
Actually, in the first version of ubuntu k8s deployment, I copied the `kubectl` to every node, but I think it is an overhead, so I removed it.I think this is just enough.

**Comment by WIZARD-CXY** [comment]
Doc update : Move the kubectl into the PATH

**Comment by tobegit3hub** [comment]
Have the same issue, please update the doc ASAP.

**Comment by tobegit3hub** [comment]
Great job  :+1:  @WIZARD-CXY @saad-ali

**Comment by olalonde** [comment]
Also ran into this bug after recklessly running `mv ./platforms/darwin/amd64/kubectl ~/bin/` :)
