### ISSUE TITLE
TravisCI is broken

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8384]
e.g. https://travis-ci.org/justinsb/kubernetes/jobs/62847034

It looks like there's a circular dependency between k8s and kube2sky?

**Comment by thockin** [comment]
@vishh @artfulcoder

**Comment by vishh** [comment]
Looking into this.

**Comment by vishh** [comment]
I don't see any dependency issue on HEAD locally.

**Comment by justinsb** [comment]
Rebasing some of the problematic patches seems to have fixed it, so I'm going to close.  Sorry for false alarm.

**Comment by justinsb** [comment]
I think the issue is that the build fails on my fork, but then passes on the PR build.  It must be a setting in Travis on my fork, or something I messed up in my fork.
