### ISSUE TITLE
panic in servicecontroller.go

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8396]
In https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/servicecontroller/servicecontroller.go, I found a logic error (when I had a broken cloud implementation):

If createLoadBalancerIfNeeded returns err, then cachedService will have service = nil.  This causes updateLoadBalancerHosts to panic.

It would be easy to skip cacheService if service=nil, but I wasn't sure whether this should then be included in servicesToRetry or not. 

Another problem (by inspection) is that I think there's a race condition where updateLoadBalancerHosts can run immediately after getOrCreate, before the service field has been set.

**Comment by a-robinson** [comment]
Great catches, Justin, thanks! I believe that simply not processing cached services with a nil api.Service object in the node pool reconciler is the correct approach. A nil Service object implies that the load balancer reconciler still intends to process it, and the LB reconciler always uses the most up-to-date list of nodes. I'll send a PR ASAP.
