### ISSUE TITLE
kube-up with latest salt fails due to library change

### ISSUE THREAD

**Issue by ashw7n** [GoogleCloudPlatform/kubernetes#8398]
The latest version of salt `2015.5.0 (Lithium)` does not have the python module `salt.utils.ipaddr ` which is needed by https://github.com/GoogleCloudPlatform/kubernetes/blob/efb42b302d871f7217394205d84e5ae82335d786/cluster/saltbase/salt/_states/container_bridge.py and kube-up fails with this message on the salt-minion log on the nodes. 

```
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: [DEBUG   ] Failed to import states container_bridge:
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: Traceback (most recent call last):
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: File "/usr/lib/python2.7/site-packages/salt/loader.py", line 951, in _load_module
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: ), fn_, fpath, desc)
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: File "/var/cache/salt/minion/extmods/states/container_bridge.py", line 18, in <module>
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: import salt.utils.ipaddr as ipaddr
May 17 20:54:29 kubernetes-minion-1-7250 salt-minion[27734]: ImportError: No module named ipaddr
```

Looks like the salt folks have moved the file from https://github.com/saltstack/salt/blob/2014.7/salt/utils/ipaddr.py to https://github.com/saltstack/salt/blob/2015.5/salt/ext/ipaddr.py.  We have temporarily fixed it in our internal fork by moving the module to  `container_bridge.py`.  Don't know if its an isolated issue to our setup, but if Kube-up fails bringing up minions correctly and if the `salt-call state.highstate`  gives you the following message , you know what to do

```         
 ID: cbr0
    Function: container_bridge.ensure
      Result: False
     Comment: State 'container_bridge.ensure' was not found in SLS 'docker'
     Started:
    Duration:
     Changes:
```

**Comment by justinsb** [comment]
Is this on AWS, and running from a release?  I've fixed it in devel (for AWS), but I should open a ticket to ask for a dot-release if people are running from releases.

(I believe GCE/GKE/Azure lock to a particularly version of Salt; Vagrant was not affected.  The fix for AWS was to lock to a particular version of Salt).

**Comment by ashw7n** [comment]
Actually this was for an internal fork where we were we had the latest salt getting pulled. Looks like its handled correctly for other providers, so closing this. We fill fix our provider to be be also against a specific version of salt.
