### ISSUE TITLE
Enhance error message from kubectl when 'kind' is empty in the template

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#8401]
If 'kind' is not addressed in the template, the error message will be 'no object named "" is registered'. We should disallow 'kind' to be empty and make the error message more clear.

**Comment by bgrant0607** [comment]
Example to reproduce the problem?

We believe DataVersionAndKind should produce an error, and should be fixed if that's not the case.

**Comment by hurf** [comment]
@bgrant0607 - Any template without 'kind' field in it can reproduce the problem. I pulled the latest code, the error message changed to 'error: no objects passed to create', but I printed `err` and `kind` after `version, kind, err := m.DataVersionAndKind(data)` and found they are both nil.
