### ISSUE TITLE
Update about docker approach for deploying k8s

### ISSUE THREAD

**Issue by WIZARD-CXY** [GoogleCloudPlatform/kubernetes#8402]
@brendanburns What about using docker to deploy the k8s status? I see its support level is project.But it was just tested ok with version 0.14.1 while the latest version is 0.17.  I think it is a good idea for k8s to deploy and maybe I can give a hand.

**Comment by WIZARD-CXY** [comment]
noticed the 0.17 docker version.studying it...

**Comment by WIZARD-CXY** [comment]
so close.

**Comment by WIZARD-CXY** [comment]
I wonder if this docker approach can include some add-on services like skydns or logging system ? Now I am confused about from which version of k8s can user easily deploy this services because the secret token exists.

**Comment by erictune** [comment]
Currently, creation of tokens for addons is done in the per-cloud-provider
scripts.  Your provider may not have this yet.
Now that service-account automation is checked in, we can change the
addon-pods to use this, and there won't be any need for secret creation in
per-cloud-provider scripts.  But we haven't done this yet.

**Comment by WIZARD-CXY** [comment]
@erictune Is there any timetable or version in the future we can use add-on service-account automation?

**Comment by erictune** [comment]
We should have things sorted out by tomorrow.

**Comment by WIZARD-CXY** [comment]
looking forward to. THANKS

May the force be with you

**Comment by WIZARD-CXY** [comment]
Looking forward to
