### ISSUE TITLE
CoreOS setup-network-environment script is gone?

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#8405]
This is missing and will break all CoreOS related stuff
`https://storage.googleapis.com/k8s/setup-network-environment`.

/cc @antoniomeireles @kelseyhightower

**Comment by AntonioMeireles** [comment]
@pires looks so - i just did AntonioMeireles/kubernetes-vagrant-coreos-cluster@15190453fdec3ae4e7b281db89ca521f76930fee to get around it ... waiting a bit to see if it was transient or not before propagating it *urbi et orbi*.

**Comment by pires** [comment]
Well, I think it's better if we just use the upstream and not said missing URL.

**Comment by kelseyhightower** [comment]
@pires This is not resolved.

**Comment by pires** [comment]
I'm not sure I follow you @kelseyhightower. So you mean this binary is no longer needed?

I don't understand why the issue was closed.

**Comment by pires** [comment]
Nevermind closed by #8409
