### ISSUE TITLE
Gendocs failing CI

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#8419]
There are a couple files which are failing gendocs in PRs, but for which running the gendocs script in master produces no output:

- cluster/addons/dns/kube2sky/RELEASES.md
- examples/limitrange/README.md

Example: 

http://travis-ci.org/GoogleCloudPlatform/kubernetes/builds/63049476

**Comment by pmorie** [comment]
To be clear, the bug here is that these files aren't generated with the analytics link in master, but they are in branches.

**Comment by bgrant0607** [comment]
PR #8343 was merged even though it failed the check.
cc @nikhiljindal @caesarxuchao @derekwaynecarr

**Comment by bgrant0607** [comment]
Or should have failed, anyway.

**Comment by bgrant0607** [comment]
The analytics change was merged this morning: #8296

It looks like the other changes were tested without that change (and vice versa).

cc @vmarmol

**Comment by vmarmol** [comment]
This should be fixed.
