### ISSUE TITLE
Recurring error in kubelet log when cadvisor is not functional

### ISSUE THREAD

**Issue by csrwng** [GoogleCloudPlatform/kubernetes#8424]
The kubelet log fills up quickly with:
```
2755 kubelet.go:683] failed to record system OOMs - cAdvisor is unsupported in this build
```

**Comment by vmarmol** [comment]
How did you build the Kubelet btw? (on what platform). This particular problem happens when the Kubelet is not build in Linux as it does not allow us to build cAdvisor.

**Comment by csrwng** [comment]
It's built on Mac OS X, cross-compiled to Linux. I know that if I build on a Linux VM, cAdvisor works and I don't get that error. The point is that even if cadvisor is not functional, logging that error every time the kubelet syncs seems excessive.

**Comment by vmarmol** [comment]
Agreed :) Just wondering about your setup. Assigning to myself to fix.

**Comment by JeanMertz** [comment]
@vmarmol I got the same error, when using the `gcr.io/google_containers/hyperkube:v0.17.0`. Perhaps this one (or the instructions) needs to be updated to support cAdvisor?

**Comment by sroze** [comment]
@JeanMertz I've the same issue.

**Comment by WIZARD-CXY** [comment]
@JeanMertz @sroze I use 0.18.2 hyperkube the same error exists too

**Comment by sroze** [comment]
@WIZARD-CXY How did you build hyperkube ?

**Comment by WIZARD-CXY** [comment]
I didn't build it myself.I use the hyperkube image which pulled from gcr.io

**Comment by nlamirault** [comment]
+1 , using the Hypercube v0.18.2 image from gcr.io.

**Comment by sroze** [comment]
The `hyperkube` image from `gcr.io` is broken, it's built without CGO enabled, which means no cAdvisor client built.
Already alerted on that on IRC without answer Kubernetes guys ;-)

**Comment by dalanlan** [comment]
v1.0.0 same pb.@sroze 
Any way i could build my own hyperkube binary so that i can get rid of this annoying stuff?

**Comment by sroze** [comment]
In fact, you just have to not use the `hyperkube` binary but the `kubelet` binary itself, built with `--use_go_build`.

**Comment by William-Yeh** [comment]
When will this issue be resolved directly into `hyperkube`?

**Comment by dalanlan** [comment]
It should be now, at least it's ok with v1.0.5.

**Comment by olmoser** [comment]
@dalanlan you sure that cAdvisor support is ok in recent hyperkube builds? i just threw away all local images and pulled hyperkube v1.0.6 from gcr.io and still get the `cAdvisor is unsupported in this build` error

https://gist.github.com/olmoser/8cf94b02984ecca221fc

**Comment by dalanlan** [comment]
@olmoser 
It's verified by my co-worker. I didn't test it myself.
You can patch #11727 anyway.
