### ISSUE TITLE
'kubectl proxy' not working

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8432]
I started a k8s cluster on GCE, and then I ran
```
$ kubectl proxy
Starting to serve on localhost:8001
$ curl localhost:8001/api/v1beta1/pods
404 page not found
$ curl localhost:8001
404 page not found
```
Is this behavior abnormal or did I misuse the command? Thanks.

@jlowdermilk @nikhiljindal @bgrant0607

**Comment by bgrant0607** [comment]
Usage looks ok:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_proxy.md

Did `kubectl proxy` exit immediately? Maybe it didn't get the port, though there should have been an error message.

Try specifying a different port (see doc).

**Comment by bgrant0607** [comment]
You also may need to do `curl --insecure`

**Comment by caesarxuchao** [comment]
Thanks. Should `kubectl proxy` exit immediately? It stuck at `Starting to serve on localhost:xxxx` no matter what port I specified. I think it got the port, because I compare the `netstat --listen` result before and after I ran `kubectl proxy`. It showed the specified port entered `LISTEN` state after I ran the `kubectl proxy` command.

`curl --insecure` doesn't help.

**Comment by bgrant0607** [comment]
Does kubectl otherwise work?

**Comment by caesarxuchao** [comment]
Yes. I've run through several other examples with the same build of kubectl.

**Comment by jlowdermilk** [comment]
> It stuck at Starting to serve on localhost:xxxx no matter what port I specified. 

That is expected behavior. It spins forever running the proxy server on localhost until you kill it with ctrl-c. You shouldn't need `--insecure` to access the localhost proxy (that's kind of the point). What version are you running? I'm spinning up a cluster at head to see if I can repro.

**Comment by caesarxuchao** [comment]
```
kubectl version
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-471-ge41e5c65fc80fe-dirty", GitCommit:"e41e5c65fc80fe96a3cc2c1d933dd3e623b75a13", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-471-ge41e5c65fc80fe-dirty", GitCommit:"e41e5c65fc80fe96a3cc2c1d933dd3e623b75a13", GitTreeState:"dirty"}
```

**Comment by caesarxuchao** [comment]
updated to the head and had the same `404 page not found` response
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-535-g2c545408968e08-dirty", GitCommit:"2c545408968e0848b6b495f0b8b36800fcbb2c64", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-535-g2c545408968e08-dirty", GitCommit:"2c545408968e0848b6b495f0b8b36800fcbb2c64", GitTreeState:"dirty"}
```

**Comment by jlowdermilk** [comment]
I just spun up a cluster from head and it's working for me.

```
kubectl version
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-537-gc743011e195139", GitCommit:"c743011e19513949433e1b47ecb7c2f4ffa795cd", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.0-537-gc743011e195139", GitCommit:"c743011e19513949433e1b47ecb7c2f4ffa795cd", GitTreeState:"clean"}

curl localhost:8001/api/            
{
  "versions": [
    "v1beta1",
    "v1beta2",
    "v1beta3"
  ]
}
```

Are you running `kubectl proxy` in its own terminal window and `curl` in another? If `kubectl` commands work, the only thing I can think of is maybe url is misspelled. Note that `localhost:8001` will always return 404, as there is no index. `localhost:8001/api/` is a good test endpoint.

**Comment by caesarxuchao** [comment]
Thanks @jlowdermilk. It seems the problem is solved. `localhost:8001/api/` returns the expected output.
I still don't know why `$ curl localhost:8001/api/v1beta1/pods` returned 404 yesterday.

**Comment by sandyydk** [comment]
Kubectl proxy fails with the error

F0806 15:37:15.715395   10814 proxy.go:155] listen tcp 127.0.0.1:8001: bind: address already in use

Is there a way to bind proxy to another custom port? Thanks.
