### ISSUE TITLE
How can I add minion to kubernetes cluster ?

### ISSUE THREAD

**Issue by medhedifour** [GoogleCloudPlatform/kubernetes#8447]

**Comment by medhedifour** [comment]
How can I add node to ubuntu cluster ?

**Comment by kelseyhightower** [comment]
@medhedifour Assuming the node is already bootstrapped with the right Kubernetes components (docker, kubelete, kube-proxy) you can do the following:

```
kubectl create -f node.json
```

```
{
  "kind": "Node",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "$IP_ADDRESS"
  },
  "spec": {
    "externalID": "$IP_ADDRESS"
  }
}
```

You can also use the nodes FQDN if you have woking DNS.

**Comment by medhedifour** [comment]
@kelseyhightower,  thanks for the response 
I have created a new vm ,  brought kubernetes binaries to this machine, and executed the command above,
but , "kubelet get nodes" give me Not Ready STATUS for new minion.
Where is the problem ?

**Comment by vmarmol** [comment]
what is the output of `kubectl describe node <node that is not ready>`

**Comment by WIZARD-CXY** [comment]
@medhedifour  You may wait some time, less than 1 min.After that, if `not ready` still exists, please look at the node's kubelet log to see if something goes wrong

**Comment by medhedifour** [comment]
![nodeconsole](https://cloud.githubusercontent.com/assets/11192333/7698087/a915acca-fe0d-11e4-810e-7ca9b42a98e4.png)

**Comment by WIZARD-CXY** [comment]
Will you show some kubelet logs?@medhedifour

**Comment by medhedifour** [comment]
![node2](https://cloud.githubusercontent.com/assets/11192333/7698266/16ba0676-fe0f-11e4-8a3b-a8cc8d58fc60.png)

**Comment by WIZARD-CXY** [comment]
Do you start kubelet with `--hostname_override=hedi003`? But the name is ip address `92.222.90.75` in `kubectl get minions`

**Comment by medhedifour** [comment]
I recreated the node with name "hedi003" instead of "92.222.90.75"

**Comment by WIZARD-CXY** [comment]
Please make them consistent.I recommed using ip address.

**Comment by medhedifour** [comment]
unknown flag --hostname_override for kubelet

**Comment by medhedifour** [comment]
can you give a template for node file ?
where can I mark IPAddress ?

**Comment by WIZARD-CXY** [comment]
`KUBELET_OPTS="--address=0.0.0.0 --port=10250 --hostname_override=10.10.103.224 --api_servers=http://10.10.103.250:8080 --logtostderr=true"`
set the ip address  in the hostname_override and use 
`
kubectl create -f node.json
{
  "kind": "Node",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "$IP_ADDRESS"
  },
  "spec": {
    "externalID": "$IP_ADDRESS"
  }
}
`

**Comment by WIZARD-CXY** [comment]
hostname_override=IP and use kelseyhightower's node.yml which use IP as well

**Comment by medhedifour** [comment]
@WIZARD-CXY 
worked with new options of kubelet
thanks a lot

**Comment by medhedifour** [comment]
I tried with kubelet options manually,on it works.
In which file we can set kubelet options on ubuntu cluster



*--------------------------------*
Bien Cordialement,
Med Hédi FOURATI

2015-05-19 13:49 GMT+02:00 Xingyu Chen <notifications@github.com>:
