### ISSUE TITLE
kubectl exec is dissonant with other commands

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#8448]
@smarterclayton @ghodss @bgrant0607 @jlowdermilk 

consider:

```kubectl log <pod> <container>```

```kubectl describe pods <pod>```

vs

```kubectl exec -p <pod> -c <container>```

I propose changing to:

```kubectl exec <pod> <container>```

for continuity.

**Comment by smarterclayton** [comment]
Since containers don't fit with resources (not a top level object) can we do

    kubectl exec <pod> [-c <container>]

**Comment by bprashanth** [comment]
@smarterclayton why encode our resource hierarchy into the cli? (looking for an example where it would be useful, not refuting that it will be useful)

**Comment by smarterclayton** [comment]
I'm mostly referring to commands that deal with opaque objects, where we explicitly identity the object by a consistent pattern (type/name, maybe in the future namespace/type/name, or type/name@resourceversion).  The question mostly arises on whether we will ever support multiple execution for exec, such that being able to use that pattern to address multiple objects.  If we won't, then it's fine to make it more like logs (although logs raises the same question as to whether you want to client side multiplex logs).  If we do, keeping container distinct as a qualifier to the provided resource seems reasonable.

----- Original Message -----

**Comment by bgrant0607** [comment]
I agree w/ @smarterclayton. I could imagine applying exec and logs to corresponding containers (i.e., same container name) of multiple pods in the future.

**Comment by brendandburns** [comment]
I'm ok w/ ```-c <container>``` if only because I think most pods are size 1 and so most people will never need to use it.

I'm not sure that ```<pod> <container>``` precludes moving across multiple pods, or even multiple containers.  I would think to do that we'd actually want to use label syntax, e.g.

```kubectl exec -l stage=production,user=bburns``` or whatever.

**Comment by brendandburns** [comment]
I'll do a PR to adjust exec to ```<pod> -c <container>``` and do the same for logs.  We'll accept the old syntax for a while too, but print a deprecation warning, and deprecate w/ 1.0

**Comment by smarterclayton** [comment]
> On May 18, 2015, at 6:30 PM, Brendan Burns <notifications@github.com> wrote:
> 
> I'm ok w/ -c <container> if only because I think most pods are size 1 and so most people will never need to use it.
> 
> I'm not sure that <pod> <container> precludes moving across multiple pods, or even multiple containers. I would think to do that we'd actually want to use label syntax, e.g.
> 
It's mostly to not have to special case resource builder (yet).  Agree pod is the implicit type, although we have use cases where you want to exec in a job or build or deployment pod where there is another resource that maps to one or more pods.  So for instance today we have "osc build-logs", where there is an indirection between identifying the specific pod running your build. Being able to abstract that somehow might be eventually useful.  I don't think it's a strict requirement, but the deeper we go into args the harder it is to fix that later.  If we did a two argument version we'd have to force the type/name syntax later if you could fetch logs or exec into a job.

**Comment by pires** [comment]
I'm used to `kubectl COMMAND POD CONTAINER`, i.e. `kubectl log POD CONTAINER`. `kubectl exec` changes that. As a user, I'd suggest to chose one and stick with it, independently of the inner differences between each `kubectl COMMAND`.

**Comment by brendandburns** [comment]
So it turns out that ```kubectl exec <pod> <container> --- <cmd>``` is tricky to do correctly, because cobra doesn't distinguish between ```kubectl exec <pod> --- <cmd> <arg>``` vs ```kubectl exec <pod> <container> -- <cmd>```, so I stuck with ```-c container```

If folks want, I will adjust ```kubectl logs ...``` as well.

**Comment by smarterclayton** [comment]
Ugh, I wonder if that was a regression.

**Comment by bgrant0607** [comment]
Would it make sense to follow the same pattern for run when we add support for the command line?

**Comment by bgrant0607** [comment]
#8604 implements `kubectl exec <pod> <container> --- <cmd>`

**Comment by bgrant0607** [comment]
Sigh. Now exec requires `-c`, whereas log doesn't accept `-c`. Continue discussion in #10372.

**Comment by bgrant0607** [comment]
Ugh. port-forward has the same issue.
