### ISSUE TITLE
GenericEtcd not testing as expected

### ISSUE THREAD

**Issue by pweil-** [GoogleCloudPlatform/kubernetes#8451]
While creating a cluster scoped api resource I noticed that when I passed in a generate name on the object meta I was getting `resttest.go:180: Expected an error, but we didn't get one`.

This appears to be caused by the `rest.BeforeCreate` method removing the namespace for any strategy whose NamespacedScoped function returns false coupled with the test that tries to ensure a namespace on a NamespacedScope==false strategy is rejected.  https://github.com/pweil-/kubernetes/blob/6b3a6e6b983f967c88d14d26542ec6e30c49ebd3/pkg/api/rest/create.go#L60-60

While debugging I was looking at the minion tests since they are non-namespace scoped.  I noted two things

1.  It is not using the ClusterScoped version of the resttest
2.  It was not failing like my test was

The second point appears to be caused by https://github.com/pweil-/kubernetes/blob/6b3a6e6b983f967c88d14d26542ec6e30c49ebd3/pkg/registry/minion/etcd/etcd_test.go#L93.  The validation error returned from validation is actually `metadata.name: required value`, not a failure to validate that a namespace is rejected or is mismatched.

To recreate the first issue, modify the minion's etcd_test.go to pass in a GenerateName field and add ClusterScope() and you will receive a failure from `TestCreateRejectsNamespace`
```
func TestCreate(t *testing.T) {
	storage, fakeEtcdClient := newStorage(t)
	test := resttest.New(t, storage, fakeEtcdClient.SetError).ClusterScope()
	node := validNewNode()
	node.ObjectMeta = api.ObjectMeta{}
	node.ObjectMeta.GenerateName = "foo-"
	test.TestCreate(
		// valid
		node,
		// invalid
		&api.Node{
			ObjectMeta: api.ObjectMeta{Name: "_-a123-a_"},
		},
	)
}

[pweil@localhost kubernetes]$ hack/test-go.sh pkg/registry/minion/etcd 
Running tests for APIVersion: v1beta1 with etcdPrefix: registry
+++ [0518 18:15:53] Running unit tests without code coverage
--- FAIL: TestCreate (0.00 seconds)
	fake_etcd_client.go:115: generating index 1
	fake_etcd_client.go:201: creating /registry/minions/test, index 1 (ttl: 0)
	fake_etcd_client.go:115: generating index 2
	fake_etcd_client.go:201: creating /registry/minions/test-7g15a, index 2 (ttl: 0)
	fake_etcd_client.go:115: generating index 3
	fake_etcd_client.go:201: creating /registry/minions/foo-tafr2, index 3 (ttl: 0)
	resttest.go:196: Expected an error, but we didn't get one
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/minion/etcd	0.109s
!!! Error in hack/test-go.sh:156
  'go test "${goflags[@]:+${goflags[@]}}" ${KUBE_RACE} ${KUBE_TIMEOUT} "${@+${@/#/${KUBE_GO_PACKAGE}/}}"' exited with status 1
Call stack:
  1: hack/test-go.sh:156 runTests(...)
  2: hack/test-go.sh:216 main(...)
Exiting with status 1
```

To recreate the second issue, remove the ClusterScope() portion of the code above and the failure moves to the `TestCreateRejectsMismatchedNamespace` method:

```
[pweil@localhost kubernetes]$ hack/test-go.sh pkg/registry/minion/etcd 
Running tests for APIVersion: v1beta1 with etcdPrefix: registry
+++ [0518 18:16:52] Running unit tests without code coverage
--- FAIL: TestCreate (0.00 seconds)
	fake_etcd_client.go:115: generating index 1
	fake_etcd_client.go:201: creating /registry/minions/test, index 1 (ttl: 0)
	fake_etcd_client.go:115: generating index 2
	fake_etcd_client.go:201: creating /registry/minions/test-cwtn9, index 2 (ttl: 0)
	fake_etcd_client.go:115: generating index 3
	fake_etcd_client.go:201: creating /registry/minions/foo-qshk5, index 3 (ttl: 0)
	resttest.go:180: Expected an error, but we didn't get one
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/registry/minion/etcd	0.111s
!!! Error in hack/test-go.sh:156
  'go test "${goflags[@]:+${goflags[@]}}" ${KUBE_RACE} ${KUBE_TIMEOUT} "${@+${@/#/${KUBE_GO_PACKAGE}/}}"' exited with status 1
Call stack:
  1: hack/test-go.sh:156 runTests(...)
  2: hack/test-go.sh:216 main(...)
Exiting with status 1
```

**Comment by liggitt** [comment]
I actually caught some of these in https://github.com/GoogleCloudPlatform/kubernetes/pull/6201 and forgot to open a separate PR when I closed that one.

**Comment by derekwaynecarr** [comment]
@liggit do you want to pull relevant pieces from the past PR or shall I do it?

**Comment by liggitt** [comment]
I can
