### ISSUE TITLE
build sometimes fails with "mv: cannot stat 'e2e.test': No such file or directory"

### ISSUE THREAD

**Issue by ixdy** [GoogleCloudPlatform/kubernetes#8464]
My recent PR #8428 builds the e2e test as a binary and moves it into the output directory (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/golang.sh#L367-371).

This sometimes works without issue, and other times fails with this error message:
```
mv: cannot stat 'e2e.test': No such file or directory
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:371
  'mv -f "$(basename ${outfile})" "${outfile}"' exited with status 1
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:371 kube::golang::build_binaries_for_platform(...)
  2: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:468 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:31 main(...)
Exiting with status 1
```

I have no idea why this is flaky, but hoping that by opening an issue others can help debug (or mention if they have a more consistent repro case).

**Comment by ixdy** [comment]
I think I figured out what the problem is.

Since we need to support Go 1.3, we can't use the -o flag to control where the binary is placed from `go test -c`, and it is instead placed in the current working directory. As we are building all platforms in parallel, it's possible that two instances of `go test -c` will collide on each other.

**Comment by vmarmol** [comment]
@satnam6502 looks like you ran into this today too.

**Comment by satnam6502** [comment]
Yes. Although I was only doing one build at a time.

**Comment by ixdy** [comment]
@satnam6502 what command did you run when you ran into this issue?

I think I have a fix that'll work, but I want to make sure it fixes your situation, too, since it's hard to reliably reproduce this on my machine.

**Comment by satnam6502** [comment]
`builld/release.sh`

**Comment by ixdy** [comment]
Ah, `build/release.sh` will by default use Docker and build all of the platforms in parallel, which will exercise the bug as I understand it.

**Comment by ixdy** [comment]
Created #8473 to fix.
