### ISSUE TITLE
Configure Kube2Sky to talk to the master securely

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8480]
Sice kube2sky is part of cluster bootstrapping, it should use the same communication pathway as the kubelet and kube-proxy. 

@thockin @ArtfulCoder @vishh @cjcullen

**Comment by WIZARD-CXY** [comment]
yeah, looking forward to

**Comment by thockin** [comment]
Vish had an idea - could we just configure the token that kube-dns gets to
point to $KUBERNETES_MASTER rather than actually add a new flag for it?

**Comment by roberthbailey** [comment]
I was going to do the same thing we do with the kubelet (e.g. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L336-L379) where if there is a CA cert present, the salt will configure the kubeconfig file to use it instead of an insecure connection (with a fallback until GKE distributes certs the same way GCE does).

@WIZARD-CXY What platform are you using? I'm planning to make a targeted (and small) change for GCE to make this secure and I'm not sure how well it will translate to other cloud providers.

**Comment by WIZARD-CXY** [comment]
@roberthbailey I am the maintainer of kubernetes deployment on ubuntu.Recently I am studying how to add token support for addon services like dns or logging and want to include them in the new version of k8s deployment.Now I have a prototye [https://github.com/ZJU-SEL/kubernetes/commits/add-token]. I see the serviceAccount approach also.I am a little confused.

**Comment by roberthbailey** [comment]
Step 1 is to build a new kube2sky that does't forcefully [configure as connections to the master as insecure](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go#L198).

**Comment by thockin** [comment]
That only triggers without the kubecfg file flag, which we set.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in#L37

**Comment by roberthbailey** [comment]
Actually, it triggers when the kubecfg flag is set. The logic is:

if no kubeconfig file, use the --kube_master_url
else load the kubeconfig file, overriding the host to be the --kube_master_url and setting the connection to be insecure.

I'm proposing that in the else branch, as long as we are loading a kubeconfig file we should just use the settings in the file rather than overriding them.

**Comment by thockin** [comment]
oh man, I had it ass-backwards, sorry.  Shame on me.

@vishh

**Comment by vishh** [comment]
I had introduced the insecure override as an interim solution. I will remove it in a PR soon.

**Comment by roberthbailey** [comment]
Thanks! We will still be able to make the connection insecure (if we want) by setting the flag in the kubeconfig file, we just want the option of also making it secure if we have a copy of the cluster CA cert to give to kube2sky.

**Comment by vishh** [comment]
@roberthbailey are you working on this?

**Comment by alex-mohr** [comment]
I had thought @vishh was driving this via first #8718 and then some followup PRs, but after a chat, it seems those are separate and @roberthbailey has some in-flight PRs to fix this.  He's OOO this week and back on Monday, so we'll wait for him to get back and clarify status.
