### ISSUE TITLE
Regression in e2e tests.

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#8499]
As of last Friday our continuous integration started failing.  We purposefully run our continuous integration in a different configuration then upstream does in order to sus-out differences in deployment etc.  

1 definite issue is --host is now failing through the e2es possibly due to changes in kubeclient utils. 

/cc @rrati @roberthbailey @jayunit100 @quinton-hoole

**Comment by timothysc** [comment]
rollup of new failures that all previously passed, when running on host = master
http://fpaste.org/223340/43204412/

**Comment by timothysc** [comment]
@pmorie on inspection of logs on a recently updated Atomic 7.1.2 cluster w/Docker 1.6.0 we're seeing the following failure on the emptyDir tests: 

"Unable to mount volumes for pod "pod-cf5888d8-fe31-11e4-b097-ecf4bbc72674_default": invalid argument"

**Comment by pmorie** [comment]
After some debugging on IRC, it looks like the mount is failing because the rootcontext mount option is malformed:

```
pod cf58a9a7-fe31-11e4-bdb0-ecf4bbc72674: mounting tmpfs for volume test-volume with opts rootcontext="system_u:object_r:var_lib_t:s"
```

The context comes directly from `libcontainer.Getfilecon` -- it looks like this is a bug with that function.  I will open a libcontainer issue for this.

**Comment by jayunit100** [comment]
Also we need to roll back the minPods=1 option that got added... Some clusters don't necessarily run pods before starting e2es

**Comment by timothysc** [comment]
#8666

**Comment by timothysc** [comment]
*this is also a breaking change on relative paths: 
https://github.com/GoogleCloudPlatform/kubernetes/commit/bf1de72f4a19f2a1b684f9ab3d2d700fa8300238

**Comment by timothysc** [comment]
ok with #8666, we are green again with some caveats and possible workarounds for path issues.  We have other tickets open around the SELinux issue so closing this one.

**Comment by bgrant0607** [comment]
cc @dchen1107
