### ISSUE TITLE
Cluster level logging test broken: please revert change

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#8509]
Someone recently changed the cluster level logging test and it can now never pass.
In particular, the use of `expectNoError(wait.Poll(10*time.Second, graceTime, func() (bool, error)` is buggy. Please can the appropriate change be reverted? Thanks.

@quinton-hoole @roberthbailey @ixdy

**Comment by yujuhong** [comment]
@satnam6502, I assume you are talking about #8399. Assigning to @quinton-hoole (the main reviewer) to triage and revert.

**Comment by quinton-hoole** [comment]
Fixed by #8510
