### ISSUE TITLE
no output when curl elasticsearch

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8513]
The k8s cloud is running on gce. I created a synthetic logging pod by this [file](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/logging-demo/synthetic_0_25lps.yaml). `kubectl log synthetic_0_25lps-pod` shows the periodic logging message. 
Visiting the elasticsearch proxy on Chrome returns the following, which seems fine:
```
{
  "status" : 200,
  "name" : "Nut",
  "cluster_name" : "kubernetes-logging",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

However, 
```
curl -k -u admin:ZGp1MKpBWweShK2E https://104.154.61.231/api/v1beta3/proxy/namespaces/default/services/elasticsearch-logging
```
returns nothing. Any suggestion? Thanks. @satnam6502 @smarterclayton

**Comment by satnam6502** [comment]
Add a `/` as the end.

**Comment by caesarxuchao** [comment]
Aha, yes, I have seen this elsewhere. Thank you.

**Comment by satnam6502** [comment]
Apologies for the hassle. We should really fix this.
