### ISSUE TITLE
GCE quick start: warn about restarting VMs

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#8521]
It's not obvious that terminating the VMs, then restarting them, is a bad idea, but it is. (IP addrs can change in the interim, etc.)

**Comment by juliaferraioli** [comment]
Do you mean the [getting started guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md)? If so, how about putting a section in troubleshooting?

**Comment by kprobst** [comment]
Yes, exactly. 

I agree that a troubleshooting section will be good to have.

**Comment by juliaferraioli** [comment]
@briandorsey what's the status of this fix?

**Comment by briandorsey** [comment]
Apologies for the delay on this. It's on my list for this week.

**Comment by zmerlynn** [comment]
Wait, does this still not work? This should be the equivalent of a MIG resize, which should work now. (I'm not sure it worked when the issue was originally opened.)

**Comment by briandorsey** [comment]
Confirmed, after manually stopping an instance, the Managed Instance Group re-creates the instance after a few minutes and pods are successfully scheduled to it. (tested with a manual install of kubernetes release v0.19.3 to GCE)
