### ISSUE TITLE
Should provide more information on how to lock down a cluster

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#8523]
e.g.:
"""
  1. don't serve insecurely on 0.0.0.0.  Remove the --public_address_override argument from your apiserver so it only serves the insecure port on 127.0.0.1, not 0.0.0.0 like it is now.
  2. change kubelet to have --api_servers=https://kube-master:6443 argument.
  3. Your kubelet doesn't need an --etcd_servers argument when it has a --api_servers argument.
  4. Put a token in the apiservers known_tokens.csv, per docs/authentication.md
  5. Put the token where the kubelet can use it, like this: echo "{\"BearerToken\": \"${KUBELET_TOKEN}\", \"Insecure\": true }" > /path/to/kubelet_auth.json
  6. Tell kubelet to use that file, like --auth_path=/var/lib/kubelet/kubernetes_auth flag.
"""

**Comment by erictune** [comment]
This is one of the things that would be covered by a "Getting Started from Scratch Guide" (#7871).

**Comment by erictune** [comment]
Closing this in favor of that.
