### ISSUE TITLE
Should provide better information on how to select multiple labels

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#8524]
Abstractly, what you want to do is this:
  1) pod template in your first replication controller gives the pods it creates the label "version=v1"
  2) pod template in your second replication controller gives the pods it creates the label "version=v2"
  3) your service uses label selector "version=v1 OR version=v2"
However, we don't currently support OR in label queries. Therefore you need to do something like this:
  1) pod template in your first replication controller gives the pods it creates the labels "service=foo" and "version=v1"
  2) pod template in your second replication controller gives the pods it creates the labels "service=foo" and "version=v2"
  3) your service uses label selector "service=foo"

**Comment by bgrant0607** [comment]
This really should be part of best practices documentation -- #7257

**Comment by bgrant0607** [comment]
And in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md

**Comment by timstclair** [comment]
Couldn't you just use a set query in this case? `version in (v1, v2)`
It seems like this would only be an issue if you're trying to do a union over different keys (e.g. `version=v1 OR client-version=v1`)

**Comment by bgrant0607** [comment]
We need to finish #341 before that will be possible, but the issue description captures the right approach for the proposed scenario.

**Comment by bgrant0607** [comment]
Fixed by #11071

**Comment by woopstar** [comment]
How was this solved?
