### ISSUE TITLE
Feature request: make it easier to fetch the logs of a crashed container

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#8526]

**Comment by bgrant0607** [comment]
Did the user try log --previous? #7973

**Comment by bgrant0607** [comment]
See also #4640

**Comment by kprobst** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/4640 seems to sufficiently address this issue. Can we close this out as a dupe?

**Comment by brendandburns** [comment]
I think this is mostly a dupe, I'm going to add some troubleshooting documentation so that it is easier to discover this option.

**Comment by brendandburns** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9509 merged.  Closing this
