### ISSUE TITLE
Should have better information on using multi-port to support both http and https connections

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#8529]

**Comment by satnam6502** [comment]
Can I have a bit more detail about what this issue is about? If I knew then I might be able to work on it :-)

**Comment by RichieEscarez** [comment]
@kprobst Is the content that you are requesting already here (or is this where you want more info added): https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#multi-port-services

**Comment by juliaferraioli** [comment]
If that is the information, it sounds like maybe it's not surfaced in the pertinent locations?

**Comment by bgrant0607** [comment]
We should add an example to the new service section of the user guide, if there isn't one already.

**Comment by bgrant0607** [comment]
This is done. #11246
