### ISSUE TITLE
Merge Freeze: Stabilize end to end tests on May 19 2015

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#8534]
Individual detailed tracking bugs will be added here shortly.
Further detail on https://groups.google.com/forum/#!topic/kubernetes-dev/gGXraJNAcaw

**Comment by quinton-hoole** [comment]
Since 4AM today, our end-to-end continuous integration tests have failed 9 of 13 runs, for a variety of reasons.  Here is a sample of recent failures:

Shell tests that services.sh passes
Waiting for endpoints to propagate
Endpoints did not propagate in time
Stopping service 'service-8805'

kubectl guestbook should create and stop a working application

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:128
Frontend service did not start serving content in 600 seconds.


ReplicationController should serve a basic image on each replica with a public image

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:47
Did not get expected responses within the timeout period of 120.00 seconds.


Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/es_cluster_logging.go:46
Expected error:
    <*errors.errorString | 0xc208a46200>: {
        s: "failed to unmarshal Elasticsearch response: invalid character 'E' looking for beginning of value",
    }
    failed to unmarshal Elasticsearch response: invalid character 'E' looking for beginning of value
not to have occurred


kubectl update-demo should do a rolling update of a replication controller

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:106
Timed out after 300 seconds waiting for name=update-demo pods to reach valid state

**Comment by quinton-hoole** [comment]
#7972 is a known cause of occasional failures, but not a recent regression.

**Comment by quinton-hoole** [comment]
#7974 is a big change, merged at the time stability dropped significantly, and never had e2e tests run against it.  Busy evaluating whether to roll it back.

**Comment by dchen1107** [comment]
Most failures I saw is timeouts. Maybe some regression on our performance?

**Comment by quinton-hoole** [comment]
We have some evidence to suggest that the reboot test is contributing to overall e2e test flakyness:
That merged at 5:27pm PST on Friday.

https://github.com/GoogleCloudPlatform/kubernetes/pull/7580

**Comment by deads2k** [comment]
> #7974 is a big change, merged at the time stability dropped significantly, and never had e2e tests run against it. Busy evaluating whether to roll it back.

#7974 is significant, but it is focused exclusively on image pulls.  All the API changes are fully deterministic and optional.  I won't argue that it can't be the cause of the failures, but is there anything more probative?  Image pull failures in particular?  In the absence of `ImagePullSecrets`, the exact same keyring is used: https://github.com/GoogleCloudPlatform/kubernetes/pull/7974/files#diff-865dd182600da4f2a68f693afb7ca65fR206 .

**Comment by ixdy** [comment]
#6949 is another large change that went in today, though I don't know if it is likely to be causing the problems we're having today.

**Comment by roberthbailey** [comment]
I ran e2es multiple times yesterday and today on #6949 (but that doesn't mean that it works in conjunction with the other changes that went in at the same time).

**Comment by satnam6502** [comment]
FYI: the cluster level logging test (something I spent a lot of time and energy on) was broken by someone else. I take the blame for many things, but not this.

**Comment by timothysc** [comment]
Do we have a status update?  We have multiple PR's all blocked this.

**Comment by quinton-hoole** [comment]
We are actively working on this, and think we are close to resolving the issue.  No more than a few more hours of freeze.

**Comment by timothysc** [comment]
@quinton-hoole many thanks!

**Comment by lavalamp** [comment]
Leading candidate is #6949 assigning CIDRs that don't match the forwarding rules. We will probably roll back shortly.

**Comment by lavalamp** [comment]
Problem is here: https://github.com/GoogleCloudPlatform/kubernetes/blob/1f4172d23c4e949362ba6c96f5e7b1aa987e1be6/pkg/cloudprovider/gce/gce.go#L574

GCE cloud provider ignores conflict errors.

Problem:
1. A CIDR is selected.
2. The forwarding route is created.
3. The attempt to write the CIDR to the node fails, probably due to the node status having been written, changing the resourceVersion.
4. The second time around, the opposite CIDR is selected.
5. Creating the forwarding rule fails with a conflict, which is silently ignored.
6. Then the wrong CIDR is successfully written to the node.

After that your cluster is pretty hosed.

**Comment by cjcullen** [comment]
Then that problem is definitely on me.

#8164 fixes it.

**Comment by dchen1107** [comment]
cc/ @fgrzadkowski

**Comment by cjcullen** [comment]
To be clear, I'm not advocating merging #8164 to fix this. We should remove the hacky "assume it's correct if it's already there" logic. We may leak routes until we get #8164 in.

**Comment by lavalamp** [comment]
We think this will fix it, but give us some time to make sure the tests have stabilized.

**Comment by dchen1107** [comment]
Finally our jenkin tests are finished, but still have issues with logging and density test. Better than before.

**Comment by wojtek-t** [comment]
As for Density test - the test failed because the latency metrics were too high. This is NOT a correctness problem - it's just performance problem.

**Comment by wojtek-t** [comment]
Might be related to the underlying issue - our scalability test suite is still failing and basically the problem is that the cluster is not starting correctly. The last two runs failed during cluster validation on:

    0;31mDetected 91 ready nodes, found 91 nodes out of expected 100. Your cluster may not be working.

**Comment by quinton-hoole** [comment]
We have managed to stabilize the system sufficiently to lift the merge freeze.  It will take about to a day to systematically merge the PR backlog.

A few end to end tests remain unreliable (see below).  If you see any of these tests fail in your local testing, you can ignore the failures until further notice.  We hope to have these stabilized within the next day or two, at which point I will update this thread.  

Thanks for your patience.

Q

Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch
- Cluster health has bad status: red

Services should be able to create a functioning external load balancer
- service external-lb-test in namespace e2e-tests-service-0-2c72586e-ab35-4f80-a30c-1c169f8272a3 doesn't have a public IP after 240.00 seconds

Services should correctly serve identically named services in different namespaces on different external IP addresses
- service s0 in namespace e2e-tests-service-0-59b2c3ca-71d5-4fcb-9a7b-e92e2909a1e4 doesn't have a public IP after 240.00 seconds

**Comment by dchen1107** [comment]
We lifted merge freeze, but there are tons of backlog needed to merge. Please continue reviewing prs, but leave on-call, which is me today to merge, so that we can rate limit the merges and avoid another merge freeze. Thanks!
