### ISSUE TITLE
kubectl: alias "logs" to "log" command

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8535]
Given `docker logs` it's a bit weird that ours is called 'log'.  Can we rename ours or provide an alias?

**Comment by smarterclayton** [comment]
Let's just rename it.  It's not a verb, it's an implicit get of a noun.

**Comment by smarterclayton** [comment]
it's "show logs" but I think everyone and their brother expects "logs" to be the command.

**Comment by thockin** [comment]
+1 - my fingers know how to type "logs" better than "log"
