### ISSUE TITLE
Node status test should mock out ip lookup

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#8549]
Looks like some kubelet unit tests perform a lookupIp which ends up depending on the health of the local resolver. Specifically @timothysc has this failing:
http://fpaste.org/223604/14320862/

Which leads to the test in:  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet_test.go#L3317
And we recently swapped out the node names from testnode to 127.0.0.1, so probably the culprit?

@roberthbailey

**Comment by bprashanth** [comment]
/ref https://github.com/GoogleCloudPlatform/kubernetes/issues/8534

**Comment by roberthbailey** [comment]
Interesting. I did swap out the node names in the unit test as part of #6949 to be 127.0.0.1, party because I thought that it wouldn't have any problems resolving during unit tests.
