### ISSUE TITLE
Add 'svc' as a DNS search path

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8569]
Needed for new DNS schema transition.  #8089 was reverted in #8568 because of #8512 

Need to add 'metatdata' to e2e names-to-resolve list for GCE

@ArtfulCoder @vishh

**Comment by thockin** [comment]
OK, so we have a real problem.

if libc resolver has a limit of 6 search paths, and we intend to prepend at least 3 (ns.svc.cluster.local svc.cluster.local cluster.local) there's a very real possibility that a random machine on which someone wants to run kube will have more than 3 search domains.  Even worse, what we really want is to prepend 4 (otherwise we have to do a release with which you MUST update your DNS server), and even GCE has 3 search paths.

So the question is how to handle it?

1) Use less search paths ourselves.  Force users to use more specific names or even FQDNs.  Mitigates but does not eliminate the problem.

2) Log an error in kubelet, but soldier on: "some of your DNS search domains may get dropped".  It really is "may" since we don't know what every resolver lib does.  Need a way for people to fix this, e.g. a kubelet flag --dns-search-paths="foo.com,k.foo.com" which trumps /etc/resolv.conf

3) Make kubelet hard-stop.  Log an event, set a Condition, refuse to run.  Still need a way to fix this as in (2). 


@smarterclayton for consult.

**Comment by vishh** [comment]
I suggest the following strategy to move forward:
1. Kubelet checks for the number of search paths in host's `/etc/resolv.conf` and mark the node unhealthy if it has more than a maximum number of search paths. We can also add a kubelet flag to let users provide custom search paths for pods.
2. Avoid being backwards compatible while introducing the new "svc" sub-domain.

**Comment by smarterclayton** [comment]
For reference RHEL recommends running dnsmasq on systems affected by this, because dnsmasq isn't affected - https://bugzilla.redhat.com/show_bug.cgi?id=168253 links to some discussion about the ABI on it.

**Comment by smarterclayton** [comment]
Could we drop 'cluster.local' for now from the search path?  I think i'm less concerned about that one if it's unlikely people change it.

**Comment by thockin** [comment]
I like it.  If we drop cluster.local for now, we can keep compat and squeek by on GCE.  We still need to solve the problem overall.

**Comment by vishh** [comment]
How about the following:
1. Require kube dns pod to be upgraded as part of the next release (v0.18.0)
2. Make kube dns create dns records with and without `svc` sub-domain (This
is the current plan)
3. Update kubelet to replace existing search paths with
`myns.svc.cluster.local` and `svc.cluster.local` in the next release
(v0.19).

Existing pods will not face any resolving issues as long as they don't use
FQDNs or have their namespace set to `svc`.

Pipelining the changes provides some time for users to update their pods if
they use FQDNs.

Does this work for Openshift @smarterclayton?

**Comment by smarterclayton** [comment]
We already dropped the old paths for support, so what you've proposed is fine for us.

----- Original Message -----

**Comment by thockin** [comment]
@vishh raised a good point - Clayton's suggestion doesn't work until search paths are transitioned.

We need to be sure:
a) running pods can resolve "svc" and "svc.ns" to "svc.ns.cluster.local"
b) new pods can resolve "svc" and "svc.ns" to "svc.ns.svc.cluster.local" or "svc.ns.cluster.local". depending on search paths

Then we can transition search paths to svc.cluster.local.  So I think Vish is right, but minor nits:

1. Make kube-dns release that supports both old and new names.
2. Tell users to upgrade kube-dns after 0.18 before 0.19.
3. Generate only new search paths in 0.19; running pods are fine, new pods are fine
4. Later: Make kube-dns drop support for old names

This will let us squeek by on GCE.  In the mean time, we can consider how to make kubelet warn when it detects a problem, and how to mitigate said problem.

**Comment by thockin** [comment]
@smarterclayton re: dnsmasq, I played with it and got it doing what we need wrt nameservers but NOT wrt search paths.  As far as I can tell, it expects to pass queries on unmolested, and that the client has proper search paths.  Is there some config I am not seeing that makes it apply search paths to incoming queries before forwarding them?  Otherwise we're still stuck at 6.

**Comment by smarterclayton** [comment]
Is the instruction I got internally.

```
1. Install dnsmasq.
2. Create an /etc/resolv.conf with a single entry pointing
  to 127.0.0.1 as the resolver
3. Configure dnsmasq to use a different (private) resolv.conf,
  say /etc/resolv.conf.dnsmasq.
4. In /etc/resolv.conf.dnsmasq, add as many domains as you like.
```


----- Original Message -----

**Comment by thockin** [comment]
dnsmasq manpage specifically says it ignores everything but 'nameserver' directives from any resolv.conf file.  That means it does not do search path expansion, which is exactly what I observe.  DNS forwarding works but it only forwards the queries, not expand them.
