### ISSUE TITLE
Recreating cluster in Container Engine confuses gcloud tool

### ISSUE THREAD

**Issue by rsokolowski** [GoogleCloudPlatform/kubernetes#8590]
In my development workflow I experiment in Container Engine cluster and once I'm done with the experiment I delete the cluster (to clean it up) and recreate it with the same name.
This confuses gcloud tool (gcloud alpha container kubectl) which stores the IP address of the master in local file - once the cluster is recreate it gets new IP and gcloud can't reach it. I workaround it by editing the file with the new IP address of the master, however this isn't very nice experience.

**Comment by roberthbailey** [comment]
This problem is specific to GKE so I've filed an internal bug for it.
