### ISSUE TITLE
kubectl: dump request response

### ISSUE THREAD

**Issue by philips** [GoogleCloudPlatform/kubernetes#8610]
It would be great to be able to get the full request/response that kubectl is making out to a log file or stderr. It really aids in debugging and learning an API if you can drop down and see the "raw" requests.

For example etcdctl gives you a `curl` example and the raw output:

```
$ etcdctl --debug -o json set foobar baz
Cluster-Endpoints: http://172.17.8.101:4001
Curl-Example: curl -X PUT http://172.17.8.101:4001/v2/keys/foobar -d value=baz
{"action":"set","node":{"key":"/foobar","value":"baz","modifiedIndex":11282,"createdIndex":11282},"prevNode":{"key":"/foobar","value":"baz","modifiedIndex":11162,"createdIndex":11162},"etcdIndex":11282,"raftIndex":19965,"raftTerm":4}
```

**Comment by deads2k** [comment]
I've never seen an implementation of this sort of logging info that I've liked, but I also agree that I want the feature.  Maybe a wrapper around a `client.Request` that keep track of what it's asked to do?

**Comment by bprashanth** [comment]
> Maybe a wrapper around a client.Request that keep track of what it's asked to do?

Why keep track? Maybe just a fprintf/glog in our request library that's toggled with a flag on the request, this is essentially what i end up doing when i debug.

**Comment by deads2k** [comment]
> Why keep track? Maybe just a fprintf/glog in our request library that's toggled with a flag on the request, this is essentially what i end up doing when i debug.

Prettiness of display or alternative analysis?  Recognition of common patterns?  We do have a patch downstream we're considering: https://github.com/openshift/origin/pull/3088

**Comment by deads2k** [comment]
I think I'd prefer to have it as an option on the `client.Config` as opposed to triggering based on glog level, but that was bigger than I'd want to carry.

**Comment by deads2k** [comment]
Oh, I should add that if you'd take this sort of patch during your code freeze, I'll submit an kube PR.

**Comment by bprashanth** [comment]
how would you trigger your patch for kubectl? 

>Oh, I should add that if you'd take this sort of patch during your code freeze, I'll submit an kube PR.

@bgrant0607

**Comment by deads2k** [comment]
> how would you trigger your patch for kubectl?

We could plumb in `loglevel` like we do in `osc`.
