### ISSUE TITLE
namespace field in the namspace JSON file

### ISSUE THREAD

**Issue by pamatteo** [GoogleCloudPlatform/kubernetes#8617]
Hi,

Inside the JSON template of namespace it is possible to specify a field called namespace. I was wondering what is its meaning? Is it possible to create namespaces inside another namespace (other than the default one)?

**Comment by derekwaynecarr** [comment]
A namespace provides a scope for many resource types in cluster (pods, services, replication controllers, etc).  You can create multiple namespaces to segregate content in the cluster as desired.  A namespace can not be nested.  By default, when you start Kubernetes you get a "default" namespace to hold content, but you can create others.  There is lifecycle with a namespace, so if you delete a namespace all of its contents are removed.  Namespaces do not support nesting.
