### ISSUE TITLE
Defining c at top level in test/e2e/networking.go is a trap!

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8630]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/networking.go#L34

Having c defined at top level there, but not set all the time, lays a trap for the imprudent programmer that I have fallen in to too many times.

Is there any reason for it?  If not I can clean it up (though probably not today)

**Comment by roberthbailey** [comment]
This was added in #6600 when the c variable was commented out in the Describe function below, but then the variable in the Describe function was added back in as part of #6643. Both changes were by @jayunit100 and the reviewers were @quinton-hoole and @satnam6502 in case they have any insight.

**Comment by jayunit100** [comment]
that c is indeed an error which needs to be removed , and it leads to shadowing of variables

**Comment by roberthbailey** [comment]
@jayunit100 can you send a PR to fix it?

**Comment by jayunit100** [comment]
yup, on it!

**Comment by jayunit100** [comment]
We can close this one now that the pr is merged.
