### ISSUE TITLE
Binding a Service to an externally defined Endpoint?

### ISSUE THREAD

**Issue by dmcqueen** [GoogleCloudPlatform/kubernetes#8631]
I have a Service config with no selector defined like

```javascript
{
  "kind": "Service",
  "apiVersion": "v1beta3",
  "metadata":{
     "name":"elasticsearch",
     "labels":{
        "name":"elasticsearch"
     }
  },
  "spec": {
    "ports": [
      {
        "port":9200,
        "targetPort":9200,
        "protocol":"TCP"
      }
    ]
  }
}
```
and an endpoint defined as 
```javascript
{
    "kind": "Endpoints",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "elasticsearch"
    },
    "subsets": [
        {
            "addresses": [
                { "IP": "172.16.98.6" }
            ],
            "ports": [
                { "port": 9200, "protocol" : "TCP" }
            ]
        }
    ]
}
```
I can see both the Service and the Endpoint via kubectl but the portalIP on the service is not routing traffic to the endpoint even thought the endpoint is available and returning.   Is there a binding step that I'm missing?  The docs just make reference to a manual mapping.

**Comment by pmorie** [comment]
I have a similar-sounding issue to triage in downstream

**Comment by thockin-cc** [comment]
I just tried manually and it worked ok...

$ cat /tmp/svc.yaml
apiVersion: v1beta3
kind: Service
metadata:
  name: manual
spec:
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 9376
thockin@freakshow kubernetes probe-logs /$ cat /tmp/eps.yaml
apiVersion: v1beta3
kind: Endpoints
metadata:
  name: manual
subsets:
- addresses:
  - IP: 10.244.0.5
  - IP: 10.244.1.28
  - IP: 10.244.2.4
  - IP: 10.244.3.7
  - IP: 10.244.3.8
  ports:
  - name: default
    port: 9376
    protocol: TCP

**Comment by dmcqueen** [comment]
maybe something in my particular setup. I'm using 0.17.0 on ubuntu 14 in vmware.

vagrant@ubuntu-14~$ kubectl get services -l name=elasticsearch
NAME            LABELS               SELECTOR   IP(S)      PORT(S)
elasticsearch   name=elasticsearch   <none>     11.1.1.3   9200/TCP

NAME                 ENDPOINTS
elasticsearch       172.16.98.6:9200

vagrant@ubuntu-14~$ curl 172.16.98.6:9200
{
  "status" : 200,
  "name" : "Star Stalker",
  "cluster_name" : "localindex",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}

vagrant@ubuntu-14~$ curl 11.1.1.3:9200
curl: (52) Empty reply from server


iptables look like

REDIRECT   tcp  --  anywhere             11.1.1.3             /* default/elasticsearch:9200 */ tcp dpt:9200 redir ports 56537
DNAT       tcp  --  anywhere             11.1.1.3             /* default/elasticsearch:9200 */ tcp dpt:9200 to:172.16.80.129:56537

**Comment by thockin** [comment]
On Thu, May 21, 2015 at 2:03 PM, Dave McQueen <notifications@github.com> wrote:
>
> maybe something in my particular setup. I'm using 0.17.0 on ubuntu 14 in vmware.
>
> vagrant@ubuntu-14~$ kubectl get services -l name=elasticsearch
> NAME LABELS SELECTOR IP(S) PORT(S)
> elasticsearch name=elasticsearch 11.1.1.3 9200/TCP
>
> NAME ENDPOINTS
> elasticsearch 172.16.98.6:9200

I might be wrong, but normally the existence of a 172 pod IP means you
did not configure networking.  Are you running flannel or OVS or
something?  did you read docs/networking.md?

**Comment by dmcqueen** [comment]
The 172.16.98.6 address is the IP of the host vm.  In the scenario above ES is listening on the host port 9200.  Doesn't work even if I explicitly set to 127.0.0.1.   I also tried not binding the ES pod to the host port and pushing an endpoint with the ES Pods IP explicitly defined and the Service still won't route to the Pod unless I'm using a selector.

**Comment by thockin** [comment]
Interesting.  You can hit the actual endpoint directly, the Endpints object
looks OK.

A few bits of info:

run `iptables-save` (more detail in there)

run `kubectl get -o json service elasticsearch`

run `kubectl get -o json endpoints elasticsearch`

maybe poke in the kube-proxy logs and see if anything seems amiss?

**Comment by dmcqueen** [comment]
Endpoint is there

vagrant@ubuntu-14:~$ /usr/lib/kubernetes/cluster/kubectl.sh get endpoints 
NAME                 ENDPOINTS
cadvisor             172.17.1.21:8080
client               172.17.1.15:3001
couchbase            172.17.1.19:8092,172.17.1.19:8091
elasticsearch        172.16.98.6:9200
elasticsearch-logs   172.17.1.32:9200

From kube-proxy logs on curl of service portalIP

E0522 19:35:14.435804   31467 proxier.go:74] Couldn't find an endpoint for default/elasticsearch:9200: missing endpoints
E0522 19:35:14.435872   31467 proxier.go:119] Failed to connect to balancer: missing endpoints

**Comment by dmcqueen** [comment]
```javascript
vagrant@ubuntu-14:~$ /usr/lib/kubernetes/cluster/kubectl.sh get -o json endpoints elasticsearch
{
    "kind": "Endpoints",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "elasticsearch",
        "namespace": "default",
        "selfLink": "/api/v1beta3/namespaces/default/endpoints/elasticsearch",
        "uid": "29c8f362-00b8-11e5-9880-000c291ca2c6",
        "resourceVersion": "91207",
        "creationTimestamp": "2015-05-22T19:24:27Z"
    },
    "subsets": [
        {
            "addresses": [
                {
                    "IP": "172.16.98.6"
                }
            ],
            "ports": [
                {
                    "port": 9200,
                    "protocol": "TCP"
                }
            ]
        }
    ]
}
```

**Comment by thockin** [comment]
kubectl get -o json service elasticsearch

**Comment by dmcqueen** [comment]
```javascript
vagrant@ubuntu-14:~$ /usr/lib/kubernetes/cluster/kubectl.sh get -o json services elasticsearch
{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "elasticsearch",
        "namespace": "default",
        "selfLink": "/api/v1beta3/namespaces/default/services/elasticsearch",
        "uid": "327779b5-00b8-11e5-9880-000c291ca2c6",
        "resourceVersion": "91211",
        "creationTimestamp": "2015-05-22T19:24:42Z",
        "labels": {
            "name": "elasticsearch"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "9200",
                "protocol": "TCP",
                "port": 9200,
                "targetPort": 9200
            }
        ],
        "selector": null,
        "portalIP": "11.1.1.44",
        "sessionAffinity": "None"
    },
    "status": {}
}
```

**Comment by thockin** [comment]
You named your port "9200" in your Service, but you did not specify a name
in the Endpoints.  Consider what would your Endpoints look like if this
Service had more than one port.  Simplest answer is to remove
`service.spec.ports[0].name` entirely - you don't need a name if you only
have one port.

**Comment by thockin** [comment]
I am so confident in my answer that I'll say this: please close this bug once you confirm  :)

**Comment by dmcqueen** [comment]
Totally right, the missing name in the Endpoint ports def was it. Thanks!
