### ISSUE TITLE
coreos guide strange setup

### ISSUE THREAD

**Issue by rubycut** [GoogleCloudPlatform/kubernetes#8663]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml#L119

Portal net option is given as 10.100.0.0/16, --portal_net=10.100.0.0/16

But kubernetes is running on 10.244.0.0/16 and flannel is setup like that.

So, I am new to kubernetes, services that I setup are not connectable from other nodes (minions), I don't see routing information or iptables nat for 10.100.0.0/16 range.

Is that mistake in config file, should portal net also be on 10.244 or my understanding is wrong?

**Comment by bakins** [comment]
Have you created any services yet?  Kube-proxy adds iptables rules for portals (service IP:port) as services are created.  Portal network should not overlap with the container network.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md

**Comment by rubycut** [comment]
Correct, it started working. Forwarding is done through firewall nat tables.
