### ISSUE TITLE
minStartupPods should be 0, and passed as cmd line option.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#8666]
*this is a breaking change* (in the sense that e2e's will never run on some configurations of clusters, anymore) , so we want to fix it asap . good news its its a one char fix :) 
- the bug : Hardcoding minStartupPods=1 makes e2es impossible to run on a clean cluster of any sort.
- solution
(1) Lets roll it to `minStartupPods=0` for now and 
(2) then lets add a **command line option** `--kube.minStartupPods` to set it, so folks wanting to run on a warm cluster can do so as they want to

**Comment by jayunit100** [comment]
cc interested parties : @eparis @timothysc @rrati  @satnam6502

**Comment by rrati** [comment]
I assume this was added to ensure some pods providing cluster services, like dns, are running before kicking off the suite.  It doesn't appear to take into account the ability to run the e2e's on a cluster without those services.  One can always accept the DNS test will fail since they aren't running the DNS service/pod and therefore skip the tests with --ginkgo.skip.

**Comment by mbforbes** [comment]
Are there any clusters you have that don't have any (even infrastructure) pods on them?

The number we have at startup is somewhere around 8 or 10 right now and seems to be growing. I assumed the continued containerization of kubernetes components would make this number grow.

We can definitely pass this as a command-line flag to override to 0, but the default (IMHO) should be > 0 to prevent a race condition with the component that starts up infrastructure pods (kube-addons).

**Comment by eparis** [comment]
Sure, lots of them.  Often I launch a dns pod as part of my setup, but it is certainly not required...

the kubernets-ansible scripts (both in the tree and outside of the tree) can give you a working cluster with no pods at all running...

**Comment by mbforbes** [comment]
Closed with #8677

**Comment by jayunit100** [comment]
actually almost closed :) ... technically, still open ...  see pr above
