### ISSUE TITLE
Allow test configuration for Kubelet for e2e

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#8669]
It's certainly needed for max pods per node.

**Comment by gmarek** [comment]
I already dug through salt stack, and figured out a way to do it. Namely I want to put a 'test' grain into grains file in ```configure_vm.sh```, and then make salt add additional parameter to ```DAEMON_ARGS``` in ```cluster/saltbase/salt/kubelet/default```.

I run out of time to finish it today, but I'll finish this on Monday (given than some Salt wizard don't know a better way to allow separate test config).

**Comment by gmarek** [comment]
@davidopp

**Comment by alex-mohr** [comment]
Moving this to team/testing.  @gmarek driving via PR #8802

**Comment by davidopp** [comment]
I think we should move this out of 1.0. It is required for supporting --max-pods, but that feature is not needed for 1.0 (we are already accomplishing the same thing in a hacky way using LimitRange default of 0.1 CPU per pod). @gmarek has bigger fish to fry that are critical for 1.0 (#3952/#3954).

**Comment by alex-mohr** [comment]
@davidopp thanks, done.

**Comment by gmarek** [comment]
Closing in favor of #11308

**Comment by gmarek** [comment]
Closed wrong thing...

**Comment by gmarek** [comment]
Closed per #11308
