### ISSUE TITLE
Gingko timeouts don't stop the test

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8672]
I saw a timeout in the e2e test: `Services` / `should serve a basic endpoint from pods`

The problem is that it looks like gingko fails to terminate the test correctly; I subsequently get this logged every second (even in other tests)...
```STEP: Failed to get endpoints: endpoints "endpoint-test2" not found (ignoring for 1 second)```

**Comment by quinton-hoole** [comment]
@lavalamp you debugged this to a Ginkgo bug/usability issue, which I believe you filed?  I can't seem to find the issue number.  Please add here if you have it.

**Comment by lavalamp** [comment]
See: https://github.com/onsi/ginkgo/issues/165

Ginkgo's timeout feature is *totally broken* and *unfixable*, and should not be used.

**Comment by lavalamp** [comment]
That said, that function does the even more totally broken thing of ```defer```ing a ```close(Done)``` call at the very end of the function instead of the very beginning. Seriously, how did that get into our codebase?
