### ISSUE TITLE
AWS Not Deploying Correctly

### ISSUE THREAD

**Issue by stevesloka** [GoogleCloudPlatform/kubernetes#8682]
I just downloaded 17.1 with hopes that I could deploy to AWS. When I run kube-up.sh I get to where it waits for the master-salt to start and it never does so times out and quits. Are there any logs that I can provide to assist with troubleshooting? // @justinsb #8114 

Creating vpc.
Adding tag to vpc-0fc6496a: Name=kubernetes-vpc
Adding tag to vpc-0fc6496a: KubernetesCluster=kubernetes
Using VPC vpc-0fc6496a
Creating subnet.
Using subnet subnet-2e5f384b
Creating Internet Gateway.
Using Internet Gateway igw-c102afa4
Associating route table.
Configuring route table.
Adding route to route table.
Using Route Table rtb-0d8a1a68
Creating security group.
Starting Master
Adding tag to i-338801c4: Name=kubernetes-master
Adding tag to i-338801c4: Role=kubernetes-master
Adding tag to i-338801c4: KubernetesCluster=kubernetes
Waiting for master to be ready
Attempt 1 to check for master node [master not working yet]
Attempt 2 to check for master node [master not working yet]
Attempt 3 to check for master node [master running @<IP>]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
Attempt 5 to check for salt-master [salt-master not working yet]
Attempt 6 to check for salt-master [salt-master not working yet]
Attempt 7 to check for salt-master [salt-master not working yet]
Attempt 8 to check for salt-master [salt-master not working yet]
Attempt 9 to check for salt-master [salt-master not working yet]
Attempt 10 to check for salt-master [salt-master not working yet]
Attempt 11 to check for salt-master [salt-master not working yet]
Attempt 12 to check for salt-master [salt-master not working yet]
Attempt 13 to check for salt-master [salt-master not working yet]
Attempt 14 to check for salt-master [salt-master not working yet]
Attempt 15 to check for salt-master [salt-master not working yet]
Attempt 16 to check for salt-master [salt-master not working yet]
Attempt 17 to check for salt-master [salt-master not working yet]
Attempt 18 to check for salt-master [salt-master not working yet]
Attempt 19 to check for salt-master [salt-master not working yet]
Attempt 20 to check for salt-master [salt-master not working yet]
Attempt 21 to check for salt-master [salt-master not working yet]
Attempt 22 to check for salt-master [salt-master not working yet]
Attempt 23 to check for salt-master [salt-master not working yet]
Attempt 24 to check for salt-master [salt-master not working yet]
Attempt 25 to check for salt-master [salt-master not working yet]
Attempt 26 to check for salt-master [salt-master not working yet]
Attempt 27 to check for salt-master [salt-master not working yet]
Attempt 28 to check for salt-master [salt-master not working yet]
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
salt-master failed to start on <IP>. Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)

**Comment by justinsb** [comment]
Ouch - sorry about the problem.

Did you remove the IP address from this line, or did it not log one:
```Attempt 3 to check for master node [master running @]```

If there's no IP then I suspect the machine is not being assigned a public IP, which is probably a VPC setting.  We've learned from e.g. the DHCP options that we might have to explicitly specify some of these options, as otherwise AWS can pick up defaults that aren't what I expect.

I will also try to reproduce the problem with 17.1 myself.

**Comment by stevesloka** [comment]
No I took the IP out, it came through ok. The master machine spins up just fine, just can't get past the check for salt-master.

**Comment by tanmaybinaykiya** [comment]
Are you certain that your ssh keys have been configured correctly? You can verify it by ssh-ing into the master node.
Take a look at https://github.com/GoogleCloudPlatform/kubernetes/issues/6570

**Comment by stevesloka** [comment]
@tanmaybinaykiya Thanks for your suggestion, that indeed was the problem. I was using an existing key-pair and needed to set the following env variable: AWS_SSH_KEY

E.g: `export AWS_SSH_KEY=~/.ssh/kubernetes`

**Comment by justinsb** [comment]
Thanks for figuring this out... I am going to try to improve the handling of SSH keys in the script (at the very least, it shouldn't fail silently!)

**Comment by stevesloka** [comment]
@justinsb Sounds great, thanks for the help with this. Until you have the script updated, I added a PR to add this variable to the docs (#9061).

**Comment by kushortiz** [comment]
i am able to ssh to master but still getting this issue, any help ?

Attempt 3 to check for master node [master running @]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
Attempt 5 to check for salt-master [salt-master not working yet]
Attempt 6 to check for salt-master [salt-master not working yet]
Attempt 7 to check for salt-master [salt-master not working yet]
Attempt 8 to check for salt-master [salt-master not working yet]
Attempt 9 to check for salt-master [salt-master not working yet]
Attempt 10 to check for salt-master [salt-master not working yet]
Attempt 11 to check for salt-master [salt-master not working yet]
Attempt 12 to check for salt-master [salt-master not working yet]
Attempt 13 to check for salt-master [salt-master not working yet]
Attempt 14 to check for salt-master [salt-master not working yet]
Attempt 15 to check for salt-master [salt-master not working yet]
Attempt 16 to check for salt-master [salt-master not working yet]
Attempt 17 to check for salt-master [salt-master not working yet]
Attempt 18 to check for salt-master [salt-master not working yet]
Attempt 19 to check for salt-master [salt-master not working yet]
Attempt 20 to check for salt-master [salt-master not working yet]
Attempt 21 to check for salt-master [salt-master not working yet]
Attempt 22 to check for salt-master [salt-master not working yet]
Attempt 23 to check for salt-master [salt-master not working yet]
Attempt 24 to check for salt-master [salt-master not working yet]
Attempt 25 to check for salt-master [salt-master not working yet]
Attempt 26 to check for salt-master [salt-master not working yet]
Attempt 27 to check for salt-master [salt-master not working yet]
Attempt 28 to check for salt-master [salt-master not working yet]
Attempt 29 to check for salt-master [salt-master not working yet]
Attempt 30 to check for salt-master [salt-master not working yet]
Attempt 31 to check for salt-master [salt-master not working yet]
Attempt 32 to check for salt-master
salt-master failed to start on . Your cluster is unlikely
to work correctly. Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)
