### ISSUE TITLE
Link to replication controller documentation in examples

### ISSUE THREAD

**Issue by juliaferraioli** [GoogleCloudPlatform/kubernetes#8701]
All the demos below do not link to the documentation

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/cassandra
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/cluster-dns
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/elasticsearch
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook-go
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/hazelcast
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/kubernetes-namespaces
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/logging-demo
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/phabricator
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/redis
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/spark
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/storm
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/update-demo

**Comment by RichieEscarez** [comment]
Ive update all the examples to include inline links to not only the replication controller help topic but also to the following help topics (where mentioned): pods, services, namespaces, and secrets.
