### ISSUE TITLE
Update fedora_manual_config.md to remove mention of the --machines argument

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8710]
This flag is deprecated and no longer has any effect.

@eparis

**Comment by eparis** [comment]
ok, we aren't using it in the guide, just mentioning it isn't needed.  we'll get it updated
@aveshagarwal

**Comment by aveshagarwal** [comment]
@eparis https://github.com/GoogleCloudPlatform/kubernetes/pull/8785

**Comment by eparis** [comment]
Closing the issue, just working the PR
