### ISSUE TITLE
Clean up hack/jenkins/e2e.sh

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#8713]
Fix nits in #8703

**Comment by ixdy** [comment]
We should also make it not fail if `E2E_OPT` is not defined. (Right now one must set `E2E_OPT`="" explicitly, which is annoying.)

In reality we should probably clean this up significantly; there are now many Jenkins builds calling this script, with lots of mysterious behavior based on what environment variables are specified.
