### ISSUE TITLE
Update cluster/ubuntu/util.sh to no longer pass --machines

### ISSUE THREAD

**Issue by roberthbailey** [GoogleCloudPlatform/kubernetes#8714]
This flag is deprecated and no longer has any effect.

@WIZARD-CXY @jainvipin

**Comment by WIZARD-CXY** [comment]
@roberthbailey I wonder which version does this include.Now ubuntu approach is using ubuntu 0.15.0.

**Comment by roberthbailey** [comment]
This change was checked in this week, so it will be true for clusters at 0.18.0+ (once the next release is cut next week). So the next time the ubuntu documentation is updated, this change should be reflected.

**Comment by WIZARD-CXY** [comment]
Oh，it means that minion node can be automatically discovered by the master node when then kubelet set `--api_server=$APISERVER`? No other configuration is needed?

**Comment by roberthbailey** [comment]
Yes, the kubelet, when passed the location of the apiserver, will register itself and then post node update messages. The only part that may depend on your deployment environment is the set of addresses that the kubelet passes to the apiserver. They will be based on the name of the node, reverse resolving the name of the node, or checking for addresses from the cloud provider.

**Comment by WIZARD-CXY** [comment]
Got it.I will include this when I updates the doc and scripts. 
Besides, I have a little questions here. https://github.com/GoogleCloudPlatform/kubernetes/issues/8402#issuecomment-104758171
Eric told me the addon services do not have service-account now.Will 0.18.0+ have it?

**Comment by roberthbailey** [comment]
Service accounts will be included as part of 0.18.0 as well.

**Comment by WIZARD-CXY** [comment]
got it

**Comment by jainvipin** [comment]
@roberthbailey - makes sense
