### ISSUE TITLE
Remove --machines from contrib/init/systemd

### ISSUE THREAD

**Issue by eparis** [GoogleCloudPlatform/kubernetes#8725]
@aveshagarwal
Can you please update contrib/init/systemd/environ/controller-manager  and contrib/init/systemd/kube-controller-manager.service to remove --machines= related references?

@roberthbailey 

related to #8704

**Comment by aveshagarwal** [comment]
@eparis sure.

**Comment by aveshagarwal** [comment]
@eparis https://github.com/GoogleCloudPlatform/kubernetes/pull/8785

**Comment by eparis** [comment]
closing, we'll just deal with the PR
