### ISSUE TITLE
kubernetes-ui Node Graph Legend is Cut Off

### ISSUE THREAD

**Issue by mikeln** [GoogleCloudPlatform/kubernetes#8726]
The http://<master>:8080/static/app/#/dashboard/ display has the legend cut off under for each of the node(minion) graph.

Issue appears to be the css is 10px too small.  The following, tested via firebug, appears to correct the layout issue:

svg.legend height has to be increased from 115 to 125.
char_area should correspondingly increase height from 425 to 435 (just to be safe).

    kubernetes/www/app/assets/css/app.css 

    1365 .dashboard .server-overview svg.legend {
    1366   height: 125px;
    1367 }

    1380 .dashboard .server-overview .chart_area {
    1381   width: 325px;
    1382   height: 435px;
    1383 }

**Comment by mikeln** [comment]
![kubgraphbefore](https://cloud.githubusercontent.com/assets/2447510/7781711/591d6520-00a9-11e5-8298-186432ce6a2d.png)

![kubgraphafter](https://cloud.githubusercontent.com/assets/2447510/7781710/58ffd514-00a9-11e5-9389-f42b93cd8b66.png)

**Comment by lavalamp** [comment]
@jackgr @prielly

**Comment by bgrant0607** [comment]
Can this be closed?

**Comment by bgrant0607** [comment]
I believe this was resolved by #10422
