### ISSUE TITLE
Unable to use secret when Kubernetes is running inside Docker

### ISSUE THREAD

**Issue by sroze** [GoogleCloudPlatform/kubernetes#8734]
When running Kubernetes in Docker (let's say the same way explained in the Docker single node getting started guide), we can't use an secret because the filesystem refuse to be mounted.

Here's the logs I have in the kuberlet container:
```
E0523 14:42:05.128717       1 mount_linux.go:103] Mount failed: exit status 32
Mounting arguments: tmpfs /var/lib/kubelet/pods/fd23fd94-0158-11e5-8412-00224dae008e/volumes/kubernetes.io~secret/dns-token tmpfs []
Output: mount: block device tmpfs is write-protected, mounting read-only
mount: cannot mount block device tmpfs read-only

E0523 14:42:05.128971       1 kubelet.go:1108] Unable to mount volumes for pod "kube-dns-v1-kgnso_default": exit status 32; skipping pod
I0523 14:42:05.129059       1 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-dns-v1-kgnso", UID:"fd23fd94-0158-11e5-8412-00224dae008e", APIVersion:"v1beta3", ResourceVersion:"117", FieldPath:""}): reason: 'failedMount' Unable to mount volumes for pod "kube-dns-v1-kgnso_default": exit status 32
E0523 14:42:05.132463       1 mount_linux.go:103] Mount failed: exit status 32
```

**Comment by pmorie** [comment]
What docker version are you on? You need docker 1.6 for this to work.

**Comment by sroze** [comment]
```
# docker -v
Docker version 1.6.2, build 7c8fca2
```
:)

**Comment by pmorie** [comment]
Could you provide more info about your cluster? What options are you using to run the kubelet?  It looks to me from the log like the wrong mounter is being used:

```
E0523 14:42:05.132463       1 mount_linux.go:103] Mount failed: exit status 32
```

In a container, the kubelet should be using the mounter from `nsenter_mount.go` instead.  Are you passing `--containerized` to the kubelet?  See the example in [local-up-cluster.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/local-up-cluster.sh#L196)

**Comment by pmorie** [comment]
Also, is selinux enforcing?

**Comment by sroze** [comment]
@pmorie I'm not starting docker with the `containerized` option, that may be the point (following [the docker multi-node documentation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md#starting-the-kubernetes-master). Since I'll setup my cluster without Docker, I'll try in few days with this option!

**Comment by pmorie** [comment]
@sroze were you able to make progress on this?

**Comment by sroze** [comment]
@pmorie Nop, I moved to non-containerized kubelet so didn't have this issue, and never add time to try again with containerized. Based on [that comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/9051#issuecomment-112832838) I'm closing the issue.
