### ISSUE TITLE
e2e test for tmpfs must specify RestartPolicy: RestartPolicyNever

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8745]
In test/e2e/empty_dir.go, we run a pod that basically runs once and logs status about the mounts, which we then validate.

In the test, we start the pod, wait for it to exit, and then get the logs.

But, we don't specify a restart policy.  The default is restart always.  So it will keep restarting.  So testContainerOutputInNamespace, which calls waitForPodSuccessInNamespace, will never exit: `ci.State.Termination` will be nil, though `ci.LastTerminationState.Termination` is getting set.

I will propose a PR that sets RestartPolicy to never for the empty_dir test.  But there is a deeper issue - how did this test _ever_ pass?  How would it ever happen that State.Termination would be set, with RestartPolicy: Always?

(I am hoping it is the other bug I found with kubelet restart, but I don't know that I entirely believe that)

**Comment by pmorie** [comment]
Very good question.

**Comment by justinsb** [comment]
Also, I want to apologize - my comments could be read as much harsher than I intended.  Rather it is very confusing to me, because usually this test does pass, and I can't understand how.  I am really hoping that if we can figure out why/when it passes, then maybe we can see if the same thing is the cause of some of the other flakes.

Ideas as to when it might work:

1) Maybe the retry loop eventually sees a state after it has terminated but before it has been restarted (i.e. we have to catch it in the window)
2) Maybe there is a by-design thing where we limit the number of restarts eventually
3) Maybe there is an issue where we don't restart containers under some odd conditions

I am not very familiar with this bit of the code (the Docker integration & scheduler, I guess), so this is mostly just speculation...

**Comment by pmorie** [comment]
@justinsb I think I've got a break in the case:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L259-L279

We're only looking at the termination status, not the pod status.

Looks like we should be able to refactor this to use PodStatus; #2632 is closed out.
