### ISSUE TITLE
e2e test needed for session affinity

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#8748]

**Comment by jszczepkowski** [comment]
I'll gladly work on it.

**Comment by roberthbailey** [comment]
It turns out that @brendandburns has a PR out for this already (https://github.com/GoogleCloudPlatform/kubernetes/pull/8881)

**Comment by brendandburns** [comment]
And that PR is now merged, so I'm closing this issue.
