### ISSUE TITLE
Minimal gcloud firewall access for GCE load-balancers?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8791]
Is there any way to open a firewall rule for a GCE LB without also opening traffic direct to the pods?

I'm doing this:

```
gcloud compute firewall-rules create ingress --allow tcp:80 --target-tags=kubernetes-minion
```

I believe this allows traffic to hit the minions directly also.

For least-privilege reasons, I would prefer to just open traffic via the load balancer.  But I can't figure out either how to apply a tag to the load balancer, or to have a firewall rule apply a target IP filter.

**Comment by a-robinson** [comment]
There's sadly no way to specify the target IP that a firewall applies to in GCE, only the target VM tags. That shouldn't open direct traffic to the pods, though, unless your pods have externally routable IPs or are using host ports.

**Comment by a-robinson** [comment]
Feel free to reopen if you have followup questions, but closing for now as there's no action to take.

**Comment by fotinakis** [comment]
If you're talking about the GCE HTTP(S) load balancer (not sure about the network load balancer), you can create a firewall rule that opens up only to 130.211.0.0/22. From the [docs](https://cloud.google.com/compute/docs/load-balancing/http/): "Traffic from the load balancer to your instances has an IP address in the range of 130.211.0.0/22"
