### ISSUE TITLE
./cluster/kube-up.sh not working as expected (Mac, boot2docker): kubectl not installed on master kubernetes node 

### ISSUE THREAD

**Issue by pramttl** [GoogleCloudPlatform/kubernetes#8796]
I followed the following steps in Mac OS X Yosemite (which has boot2docker installed).

Step 1:
go was installed and GOPATH and GOROOT environment variables were set correctly.
export GOROOT='/usr/local/go'
export GOPATH ='/Users/pranjal/go'

Step 2: boot2docker start

Step 3:

     cd $GOPATH/src/github.com/GoogleCloudPlatform/

Step 4: Cloned my fork of kubernetes (Forked May 25, 2015)

     git clone https://github.com/pramttl/kubernetes

Step 5: I set environment variables as instructed by the error message on running `vagrant up` straight away:

       export KUBERNETES_PROVIDER=vagrant
       export VAGRANT_DEFAULT_PROVIDER=virtualbox
       
Step 5: I ran `./cluster/kube-up.sh`

Step 6: 2 kubernetes nodes (in the form of virtual machines on my Mac) were created called master and minion-1. When I got into the kubernetes master node using `vagrant ssh master` and tried to see if `kubectl` CLI exists, I got an error.

```
pranjal:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ vagrant ssh master
Last login: Tue May 26 04:11:29 2015 from 10.0.2.2
[vagrant@kubernetes-master ~]$
[vagrant@kubernetes-master ~]$ kubectl
-bash: kubectl: command not found
```

Nothing seems to be installed on the fedora machine, not even docker. Is this normal?

**Comment by uruddarraju** [comment]
Can you please try `/usr/local/bin/kubectl ? `

**Comment by pramttl** [comment]
@uruddarraju: That appears to work. 
I was expecting `/usr/local/bin` to be on the $PATH by default.

**Comment by uruddarraju** [comment]
cool. Thanks for letting me know.
