### ISSUE TITLE
201 Walkthrough references concept (API) not yet introduced

### ISSUE THREAD

**Issue by juliaferraioli** [GoogleCloudPlatform/kubernetes#8820]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/walkthrough/k8s201.md

This walkthrough uses concepts like the API object at multiple points, but the API hasn't been introduced yet in this or the prior walkthrough. Suggest either spending a section on the API, or removing the reference and working around it.

**Comment by jeffmendoza** [comment]
I'll take this one
