### ISSUE TITLE
Examples using Compute Engine should specify that setup includes project and billing

### ISSUE THREAD

**Issue by juliaferraioli** [GoogleCloudPlatform/kubernetes#8824]
Several examples use Compute Engine for the cluster. They should specify that to complete the example, the user needs to:

1. Create a project
2. Configure gcloud
3. Set up billing

Two examples of where this is needed are:

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/mysql-wordpress-pd
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/meteor

**Comment by jeffmendoza** [comment]
@juliaferraioli How about linking to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md instead?

**Comment by jeffmendoza** [comment]
@juliaferraioli please assign to me.

**Comment by juliaferraioli** [comment]
My $.02:

Linking to that doc is the least we should do. However, that introduces another point of friction -- parsing the new page. While it introduces an extra point of maintenance, we should pull in the relevant steps to this Readme, and still link back to the setup page.

**Comment by jeffmendoza** [comment]
@juliaferraioli How does this look:
https://github.com/GoogleCloudPlatform/kubernetes/compare/master...jeffmendoza:patch-1
https://github.com/jeffmendoza/kubernetes/blob/patch-1/examples/mysql-wordpress-pd/README.md

**Comment by juliaferraioli** [comment]
That's exactly what I would expect for prereqs.
