### ISSUE TITLE
Clarify origin of $ZONE in MySQL Wordpress PD example

### ISSUE THREAD

**Issue by juliaferraioli** [GoogleCloudPlatform/kubernetes#8825]
Example talks about the definition of $ZONE, but doesn't clarify where the default comes from or how to find it via querying your project. This can significantly slow down the execution of the example.

Suggestion: link to the [default file for GCE](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/config-default.sh)

**Comment by jeffmendoza** [comment]
Please assign to me
