### ISSUE TITLE
Provide PD size suggestion for MySQL-Wordpress-PD example

### ISSUE THREAD

**Issue by juliaferraioli** [GoogleCloudPlatform/kubernetes#8828]
In the [second section](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/README.md#create-two-persistent-disks), the readme tells you to set the disk size to something that will meet your needs. This doesn't give the user any guidance for the purposes of the example.

Suggestion: rephrase to "First create the mysql disk, setting the disk size to meet your needs. For this sample, we suggest a size of XX:"

**Comment by jeffmendoza** [comment]
@amygdala @juliaferraioli I'm working on this readme for another issue, and can get this too

**Comment by jeffmendoza** [comment]
Fixed by #9629
