### ISSUE TITLE
service.sh e2e flaky - pull from gcr.io, not docker.

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#8849]
e2e output:

service-13483 portal failed from container, expected:

        service-13483-bzy5s
service-13483-qlk9b
service-13483-vq7md

        got:

        service-13483-bzy5s
service-13483-bzy5s
service-13483-qlk9b
        

It looks like the test might be wrong:

https://github.com/GoogleCloudPlatform/kubernetes/blob/4a6ab7fd3698c5cc7172c5bd63efab320d1f2d17/hack/e2e-suite/services.sh#L268

It seems to try 10 curls against a service with 3 pods behind it, and fail if it doesn't find all 3 pods after 10 tries.

The probability of this happening is about 3 * 0.66^10 = 4.7% (if my high school stats still works :-)

Q

**Comment by roberthbailey** [comment]
@thockin - did you write that test (long, long ago)?

**Comment by thockin** [comment]
While I admit the logic is suspect (why not just loop 30 times?) it is
known to have succeeded many times, no?  I do recall it being very fragile
wrt output format, and making me basically swear off shell forever...

**Comment by brendandburns** [comment]
@thockin is this still open/relevant? I know you did some work here...

**Comment by quinton-hoole** [comment]
#8953 (which added some retries) does not seem to have fixed this test completely, although the failure mode is now different:

Test 1: Prove that the service VIP is alive.
Verifying the VIP from the host
waiting for service1 at 10.0.182.230:80
waiting for service1 at 192.168.1.1:80
waiting for service1 at 192.168.1.2:80
waiting for service2 at 10.0.200.24:80
Verifying the VIP from a container
waiting for service1 at 10.0.182.230:80
time="2015-06-13T16:22:00Z" level=fatal msg="Could not reach any registry endpoint" 
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [1].
testing service1 VIP from container failed
namespaces/services-test-8716

More comments shortly...

**Comment by quinton-hoole** [comment]
Failure rate is ~3.3% over the past 100 runs.  The error is pulling a busybox image from docker:

      sudo docker pull busybox >/dev/null;
      sudo docker run busybox sh -c '

We need to clone this image to gcr.io.

Dropping this to post-1.0.

**Comment by brendandburns** [comment]
Closing this one as we now pull from gcr for everything.
