### ISSUE TITLE
[DOCS] update pod-states.md with information about probing and probe types.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#8861]
There don't appear to be any explanations of how to use readiness or liveness probes, with exception of one or two sentences in `pod-states.md` and `replication-controller.md`. 

Can we get a rough page up with the basics of what these probes are and how they are meant to be used ? 

- What is a probe?
- What is a livenessProbe vs a readinessProbe ?
- How are either of these normally used.  

There is of course the connection to "Readiness" here which is the important part we want to explain.  Im playing around some with these things by looking at the api + the examples stuff.  But I won't be a good candidate for writing the doc page.  

Possibly @mikedanese might be able to provide a quick sketch up of how to get the best info on these , if busy,  then if you want to dump some links in this thread, I or someone else  can investigate some more and write up a more formal docs update.

**Comment by mikedanese** [comment]
Ack. I have some downtime today so I can write up a sketch.
