### ISSUE TITLE
Admission control doesn't handle subresources correctly

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#8868]
A POST to /pods/foo/status should result in admission control being told the following:

```
resource := "pods/status"
kind := "Pod"
operation := "update"
```

Right now, it results in:

```
resource := "pods"
kind := "Pod"
operation := "update"
```

The resource values should align with what is registered with the storage object.

Need to update admission controllers in code today to handle sub-resource properly.

/cc @smarterclayton @csrwng

**Comment by smarterclayton** [comment]
Likewise, pod exec should be:

```
resource := "pods/exec"
kind := "ConnectRequest"
operation := "???"
```

**Comment by csrwng** [comment]
operation := "connect"

**Comment by smarterclayton** [comment]
Without this change admission control is inconsistent with authorization about how it handles sub resources.

**Comment by bgrant0607** [comment]
Is this the root cause of #9878?

**Comment by smarterclayton** [comment]
Yes, although some admission controllers would need to look at both

**Comment by derekwaynecarr** [comment]
I thought #9878 was originally caused by @smarterclayton misusing a data population tool I had wrote.  I guess in theory, if a user added a quota to a namespace that had previously defined pods that had not set an explicit resource limit this would have happened.

@bgrant0607 - would you accept a fix for this for 1.0?

**Comment by derekwaynecarr** [comment]
If #9878 is p1, this needs to be bumped to match.

**Comment by bgrant0607** [comment]
In principle, yes. In general, bug fixes are welcome for 1.0, unless huge/risky, and it's not good to have a bunch of functionality in k8s that actually only works in Openshift.

**Comment by derekwaynecarr** [comment]
I will put something together.  This is still an issue in OpenShift so we are actually no better in this scenario :-)

**Comment by derekwaynecarr** [comment]
I am biased to add a field ```Subresource``` to admission attributes so its consistent with the ```APIRequestInfo``` object.  I would also need to add ```Subresource``` to ```RequestScope```. I guess in concept, I could concat ```Resource/Subresource``` before calling admission, but not sure if that is really preferred or not.  My gut thinks its better to have more information and keep them separate.

**Comment by derekwaynecarr** [comment]
Tracking down what happens in ```Authorizer``` to here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/handlers.go#L210

I don't see how authorizer is subresource aware either

**Comment by derekwaynecarr** [comment]
I must be reading something wrong, need to do more testing, or we convert what is on APIRequestInfo when we build a RequestScope

**Comment by derekwaynecarr** [comment]
I have tracked this all down now.

1. The Kubernetes authorizer is not sub-resource aware today
2. The OpenShift authorizer is sub-resource aware today because it has its own code that concatenates Resource/Subresource when building request attributes

@deads2k and I would like to add ```GetSubresource``` as an operation on the authorizer.Attributes and admission.Attributes interface so they are consistent upstream.  We would then look to make the downstream authorizer consistent in OpenShift.

So ```RequestScope``` needs to carry ```Subresource``` from ```APIRequestInfo``` in order to pass it through to admission.  Will submit a PR for this issue, and open another issue to track making authorizer.Attributes in Kubernetes subresource aware.
