### ISSUE TITLE
Harden kubectl proxy

### ISSUE THREAD

**Issue by stephenR** [GoogleCloudPlatform/kubernetes#8871]
The current default behavior of kubectl proxy is to listen on all addresses on port 8001. Thus anyone on the same network gets full access to the apiserver of my cluster.
It would be good to default to listen on localhost and maybe add a flag to override this behavior.

The second issue is that the proxy is vulnerable to dns rebinding. I.e. if I'm running a kubectl proxy and browse the web at the same time, a malicious website can interact with the local apiserver. The recommended way to protect against dns rebinding is to check the Host header for expected values if present.

**Comment by jlowdermilk** [comment]
> The recommended way to protect against dns rebinding is to check the Host header for expected values if present.

Can you expand on this? What expected values would we be checking for?

**Comment by stephenR** [comment]
> > The recommended way to protect against dns rebinding is to check the Host header for expected values if present.

> Can you expand on this? What expected values would we be checking for?

If it's a legitimate request from the browser, the host header should either include localhost:8001 or an ip address, i.e. 127.0.0.1:8001 or [::1]:8001 but other addresses might be possible. An empty host header is probably fine too.

Another issue with this proxy is that other web based attacks will apply, for example XSRF and XSS.
To protect against XSRF attacks I think it would be sufficient to rely on the fact that you can't post cross-origin with an application/json content type. We'd just need to add a check for that content-type in the api. However, there might also be sensitive endpoints behind GET requests.
http://localhost:8001/api/v1bet3/namespaces/default/pods/elasticsearch-logging-dr7bq/exec comes to mind, though that one doesn't work since it requires a spdy connection upgrade, but maybe there are others?
And then there's the /proxy/ endpoint that passes the requests through to services running in kubernetes. That means any XSS in kibana can be used to bypass other restrictions and e.g. read /api/v1beta3/secrets or post a new pod description.

What's the usual way this proxy is used, via the browser or through curl..? Maybe there's some better way to harden this service, e.g. require a special header on any request and reject an requests that don't have them (which would still need protection against dns rebinding)?

**Comment by stephenR** [comment]
> However, there might also be sensitive endpoints behind GET requests.

Found one:
http://localhost:8001/api/v1beta3/proxy/nodes/kubernetes-minion-brc6/run/default/elasticsearch-logging-dr7bq/elasticsearch-logging?cmd=ls%20-l&stdout=1

With that, if you have kubectl proxy running and visit http://evil.com, evil.com will be able to run arbitrary commands in the cluster.

**Comment by roberthbailey** [comment]
The proxy is often used with a web browser, e.g. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/update-demo/README.md#step-one-turn-up-the-ux-for-the-demo

**Comment by stephenR** [comment]
A part of my previous comment was wrong. It's actually possible to POST application/json cross origin, so checking the content-type wouldn't be enough to protect against XSRF.

**Comment by stephenR** [comment]
So I still think the proxy is scary if someone actually tries to attack it.
The api needs some XSRF protection so that an attacker can't trigger it cross-origin. A custom header might be fine in this case.
However, I'd be happier if we could completely drop POST requests to the API since any XSRF protections can be bypassed with an XSS. That is, any XSS in kibana, elasticsearch or any other service reachable via the /proxy/ api.

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
@brendanburns are you working on this issue? I can take a look if you are not.

**Comment by brendandburns** [comment]
I'm working on this in the context of

https://github.com/GoogleCloudPlatform/kubernetes/pull/9287

But I'm not doing anything else yet.  

Maybe the next thing is to set a CORS header?

--brendan
