### ISSUE TITLE
Should we auto-open ports for load-balanced service?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#8900]
Currently (on GCE) we don't automatically open ports for a load-balancer service.  Users must manually open them  (`gcloud compute firewall-rules create ingress --allow tcp:80 --target-tags=kubernetes-minion`).  Mentioned this to @thockin and he suggested that maybe we _should_ be opening them.  Should we be, or do we expect users to open firewall-rules for any services they create?

In general, I'd like to understand the philosophy here.  AWS is wide-open right now in terms of firewall-rules, so I want to lock that down asap.

**Comment by thockin** [comment]
I assumed that we were doing this already.  The question is whether we can do this with enough granularity to not hurt anyone.

**Comment by justinsb** [comment]
1) We have no mechanism for specifying any allowed src-ip other than 0.0.0.0/0 (e.g. something on Service.Spec).
2) We could fairly easily add a flag to kube-cloud-controller, which would control the allowed src-ip range for an LB.  So no per-service control, but I would imagine the typical use-case for not allowing everyone is to restrict access to the entire cluster to a particular subnet.  We could also have a value that would mean "don't open this for me".
3) On GCE, opening a port on the LB actually means allowing traffic to the nodes - there are no rules on the LB itself.  This should be safe as long as kube-proxy has set up the firewall rules for the load-balancer first.  I don't know if we can have a catch-all rule for GCE LBs that would avoid this sequencing requirement.
4) On AWS & I believe OpenStack, you can set firewall rules directly on the LB, so no implementation problems here I don't think.

**Comment by roberthbailey** [comment]
This was previously discussed in https://github.com/GoogleCloudPlatform/kubernetes/issues/3636 where we decided that it would be better _not_ to automatically poke holes in the firewall for external services.

**Comment by thockin** [comment]
Note that one of my own replies said "I don't think we should automatically
open firewalls unless the user has explicitly asked for external access."
 The bug shifted from "should we open firewalls for external load
balancers" to "should we auto-start services with external load balancers
and firewalls opened".  I am against the latter (e.g. my brand new cluster
should not come up with a for-pay cloud load balancer providing worldwide
access to kibana) but lean in favor of the former.

Sadly, though, GCE's firewall rules are under-specified.  If I put a
service on port 10250 and ask for a load-balancer, which opens firewalls I
have now put all of my kubelets on the internet.

**Comment by justinsb** [comment]
Could we default-drop inbound traffic in iptables on GCE, and then just open the ports we need?  (It probably isn't a terrible idea in general anyway - defense in depth)

**Comment by thockin** [comment]
It's pretty hostile to any other use of the machines, which may be OK.
Which set of ports?  Every service?  all ports?  I'm not sure how to
describe this - security is not my thing :)

**Comment by bgrant0607** [comment]
The heapster case was different -- it exposes cluster data and therefore requires auth.

To me, a request for an external load balancer means that you want it to be visible, and we should make that happen.

**Comment by alex-mohr** [comment]
I don't know how feasible this is on other cloud providers, but on GCE could we do:
(1) have an instance-tag-controller that assigns a tag-$service to each node with a pod belonging to $service (https://cloud.google.com/sdk/gcloud/reference/compute/instances/add-tags)
(2) create a firewall that with --target-tag=tag-$service
(3) when the service is deleted, the firewall and all tag-$services are also removed?
Also possible that's not a default behavior for a service or it's controlled by serviceScope: {internal,external} or createFirewallRules: true or something.

**Comment by thockin** [comment]
I think we will NOT open firewalls for 1.0 because of issues on GCE and unknown others.  We will instead do #9150 for now, and consider how to do this by default safely after 1.0

**Comment by thockin** [comment]
@alex-mohr that doesn't fix the exposure on GCE, so I don't want to do it by default.

**Comment by thockin** [comment]
Decision reversed, fixed for 1.0

**Comment by zmerlynn** [comment]
This goes all the way back to #3636 :)
On Jul 14, 2015 9:50 AM, "Tim Hockin" <notifications@github.com> wrote:

Closed #8900 <https://github.com/GoogleCloudPlatform/kubernetes/issues/8900>
.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/8900#event-355559626>
.
