### ISSUE TITLE
Vagrant provision script - avoiding environment settings

### ISSUE THREAD

**Issue by JasonGiedymin** [GoogleCloudPlatform/kubernetes#8907]
In the provision script it tries to do `grep -v` which is an inverted match for `/^#...` regex expression. On some systems users _may_ have colors set via the user's profile. The result is a concat with color codes injected into the resulting provision scripts, ultimately failing the provision and failing `vagrant up` command.

It may be better to avoid this and other edge cases by using awk.

I have a fork with this change:
https://github.com/JasonGiedymin/kubernetes/commit/f25ecb7e4689d751a66ffcf1bab42ae56bcadc4e

Please review.

**Comment by derekwaynecarr** [comment]
The change is fine.  Feel free to open a PR
