### ISSUE TITLE
Regression: TestNoManualChangesToGenerateDeepCopies failed at HEAD

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#8928]
My branch is synced to commit b8a808b1ae2321a6b9081e2ce3a2d8cf18b4f561 this morning. 

--- FAIL: TestNoManualChangesToGenerateDeepCopies (0.03s)
	conversion_generation_test.go:126: please update conversion functions; generated: api.deep_copy.txt; first diff: 
		expected: 	if in.ISCSI != nil {
		
		     got: 	return nil
	conversion_generation_test.go:126: please update conversion functions; generated: v1beta3.deep_copy.txt; first diff: 
		expected: 	if in.ISCSI != nil {
		
		     got: 	return nil
	conversion_generation_test.go:126: please update conversion functions; generated: v1.deep_copy.txt; first diff: 
		expected: 	if in.ISCSI != nil {
		
		     got: 	return nil
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/runtime	0.141s

**Comment by dchen1107** [comment]
Closed it since it is not reproducible after sync again.

**Comment by bprashanth** [comment]
Fyi update-generated-deep-copies.sh was only recently included in the presubmit hooks and would've fixed it

**Comment by dchen1107** [comment]
Thanks. Yes, the issue is gone now.
