### ISSUE TITLE
kubectl get should show creation time for other resources

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#8929]
e.g. being able to know when a namespace was created (at a  glance) would be nice.

**Comment by bgrant0607** [comment]
FWIW, AGE is in the proposed output for kubectl get pods -- #7843.

**Comment by thockin** [comment]
That's what I meant, I was just in a rush :)  I want to see that my
namespace was created "5 minutes ago" vs "about a week ago"

**Comment by bgrant0607** [comment]
FWIW, that form could be used for describe but isn't suitable for get, since it's wide and variable in the number of words.

**Comment by hurf** [comment]
@thockin - I've created a PR for this issue, can you review it to see if it is as what you expected?
