### ISSUE TITLE
e2e GCE test failure/flake: DNS should provide DNS for headless services

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#8933]
Test went from 100% passing to failing roughly every other run since last night.
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/6459/testReport/(root)/Kubernetes%20e2e%20suite/DNS_should_provide_DNS_for_headless_services/history/

**Comment by jlowdermilk** [comment]
cc @vishh

**Comment by rjnagal** [comment]
@ArtfulCoder do you want to take this up? @vishh is out today.
The test has passed in all of yesterday's runs. Not sure if there has been an actual fix here.

**Comment by jlowdermilk** [comment]
I think we can close as obsolete.
