### ISSUE TITLE
e2e GCE test failure/flake: Networking should function for intra-pod communication

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#8934]
Timed out 8 of the last 11 runs
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/6459/testReport/(root)/Kubernetes%20e2e%20suite/Networking_should_function_for_intra_pod_communication/history/

**Comment by lavalamp** [comment]
The timeout is surprising... inclined to think that there's actually a system problem but we'll see.

**Comment by lavalamp** [comment]
I accidentally repro'd this locally, and the problem was conflicting routes in the system.

**Comment by lavalamp** [comment]
Unfortunately I deleted the routes without actually looking at them, and now I haven't been able to trigger the leak again.

**Comment by lavalamp** [comment]
I tried kube-down.sh, kube-push.sh, and the reboot test, none of those caused routes to leak.

**Comment by jlowdermilk** [comment]
Closing as obsolete.
