### ISSUE TITLE
e2e GCE test failure/flake: Monitoring verify monitoring pods and all cluster nodes are available on influxdb using heapster

### ISSUE THREAD

**Issue by jlowdermilk** [GoogleCloudPlatform/kubernetes#8935]
test panicked:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/6459/testReport/(root)/Kubernetes%20e2e%20suite/Monitoring_verify_monitoring_pods_and_all_cluster_nodes_are_available_on_influxdb_using_heapster_/

cc @satnam6502

**Comment by jlowdermilk** [comment]
Vish please take a look if you have cycles or reassign if there's someone with better context.

**Comment by rjnagal** [comment]
I looked at the panic and it was due to the last test (networking) timing out but still running. I think the fix is more in better cleanup between tests.

**Comment by lavalamp** [comment]
I just saw this... it's totally due to ginkgo's cleanup when a test times out. I can fix.

**Comment by lavalamp** [comment]
I will get this one.

**Comment by lavalamp** [comment]
Ugh, the thing ginkgo does when a test times out is totally lame...

**Comment by lavalamp** [comment]
Instead of working around this, I've filed https://github.com/onsi/ginkgo/issues/165

I'm going to go back to a manual timeout on this test.
