### ISSUE TITLE
e2e GCE test failure/flake: Kubernetes e2e suite.Docker Containers should be able to override the image's default arguments (docker cmd) (from (junit_01.xml))

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#8941]
This particular test passed for last many days. 

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/6460/testReport/junit/(root)/Kubernetes%20e2e%20suite/Docker_Containers_should_be_able_to_override_the_image_s_default_arguments__docker_cmd_/

Stacktrace

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/docker_containers.go:60
Test Panicked

**Comment by rjnagal** [comment]
@lavalamp I think this is same gingko clean up issue as #8935 - closing.


•... Timeout [120.338 seconds]
Networking
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:246
  should function for intra-pod communication [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:244

  Timed out

  ....

[AfterEach] Docker Containers
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/docker_containers.go:45

•! Panic [5.596 seconds]
Docker Containers
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/docker_containers.go:82
  should be able to override the image's default arguments (docker cmd) [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/docker_containers.go:60

  Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/src/go/src/runtime/asm_amd64.s:401

  Full Stack Trace
  /usr/src/go/src/runtime/panic.go:42 (0x4141fe)
  /usr/src/go/src/runtime/sigpanic_unix.go:26 (0x41a9b4)
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:169 (0x4b666c)
  /usr/src/go/src/runtime/asm_amd64.s:401 (0x43e205)
  /usr/src/go/src/runtime/panic.go:387 (0x415058)
  /usr/src/go/src/runtime/panic.go:42 (0x4141fe)
  /usr/src/go/src/runtime/sigpanic_unix.go:26 (0x41a9b4)
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:197 (0x4b691f)
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:210 (0x4b7ba7)
  /usr/src/go/src/runtime/asm_amd64.s:401 (0x43e205)
  /usr/src/go/src/reflect/value.go:419 (0x705e55)
  /usr/src/go/src/reflect/value.go:296 (0x704c4c)
  /usr/src/go/src/runtime/asm_amd64.s:2232 (0x440341)
