### ISSUE TITLE
'--api-prefix' option in 'kubectl proxy' documentation is wrong

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8943]
Without `--api-prefix`, `kubectl proxy` works just fine,
```
$ curl localhost:8001/api/
{
  "versions": [
    "v1beta1",
    "v1beta2",
    "v1beta3"
  ]
}
```

With '--api-prefix=xxx-api', it stops work:
```
$ curl localhost:8001/xxx-api/
404 page not found
```

My `kubectl` version:
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-878-g851f6b754241c0-dirty", GitCommit:"851f6b754241c01f30c43cddd2f9ca8c7c3f42f5", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-893-g58b683fe296da8-dirty", GitCommit:"58b683fe296da870fdbc6eb1a32dcf50ed94a8e3", GitTreeState:"dirty"}
```
 
@jlowdermilk, could you take a look? Thanks.

**Comment by bgrant0607** [comment]
--api-prefix was added in #4279.

@jimmidyson could you take a look? This appears to be completely broken, so we should fix it or rip it out.

**Comment by caesarxuchao** [comment]
Reading the code and I find the way to fix it. You need to use `--api-prefix=\xxx-api\`, note the backslash. 

I will fix the man page.

**Comment by bgrant0607** [comment]
@caesarxuchao What's an example command line that works?

**Comment by caesarxuchao** [comment]
```
$ kubectl proxy --api-prefix=/xxx-api
```
then 
```
curl localhost:8001/xxx-api/
```

**Comment by bgrant0607** [comment]
Ah, the default flag value has leading and trailing slashes:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/proxy.go#L52

The example in the documentation is wrong:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/proxy.go#L36

Re-opening for doc fix.

**Comment by caesarxuchao** [comment]
The trailing slash is not necessary.

#8948 and #8949 duplicate each other.
