### ISSUE TITLE
Events not being logged

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#8954]
pkg/client/record has a StartLogging method.  The intention was that when you call Record, you get and event *and* a local log message, so that events are intermixed with more detailed local log lines, to give context and to aid debugging when event recording is unavailable.

Searching for calls to StartLogging, it seems like only the kubelet binary does this.  Need to add StartRecording to Scheduler, Controller-manager, the all-in-one-binary, and any other event-generating binaries.

**Comment by erictune** [comment]
@lavalamp

**Comment by rjnagal** [comment]
@lavalamp @erictune Is this a v1-candidate?

**Comment by feihujiang** [comment]
Hi, I wonder if anyother has already started working on this? If not, I would volunteer myself to do this.

**Comment by erictune** [comment]
fixed by #9177
