### ISSUE TITLE
Swagger description tags for restartPolicy is out of date in v1beta3 and v1 APIs

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#8977]
restart policy for all containers within the pod; one of RestartPolicyAlways, RestartPolicyOnFailure, RestartPolicyNever; defaults to RestartPolicyAlways

Should be just Always, OnFailure, Never.

imagePullPolicy had a similar problem, but looks like it was fixed.

cc @MikeJeffrey @smarterclayton @dchen1107 @caesarxuchao @krousey

**Comment by RichieEscarez** [comment]
Fix in api through #9215 and published to swagger through #9256 (ive checked and the changes are live) so closing.
