### ISSUE TITLE
no definition of 'trap-add' in util.sh

### ISSUE THREAD

**Issue by suxianqun** [GoogleCloudPlatform/kubernetes#8985]
when run the commands in ubuntu:
$ KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

it will report error. there is no definition of 'trap-add' in ubuntu/util.sh

**Comment by rjnagal** [comment]
@WIZARD-CXY @resouer can you take a look?

**Comment by WIZARD-CXY** [comment]
This pr https://github.com/GoogleCloudPlatform/kubernetes/pull/8621/ adds this function.It seems @MCyprien forget to define it.......

**Comment by WIZARD-CXY** [comment]
And I'm sure this pr https://github.com/GoogleCloudPlatform/kubernetes/pull/8986 is fixing this.

**Comment by MCyprien** [comment]
hum, yes, I certainly forgot sorry for that

**Comment by erictune** [comment]
fixed by 8986
