### ISSUE TITLE
Assigned container port for multi worker storm workers

### ISSUE THREAD

**Issue by sushantk** [GoogleCloudPlatform/kubernetes#8988]
Hello,

I am looking to solve the final piece of puzzle for running a complete Storm cluster on k8s. I have gone through this example: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/storm  and it doesn't solve the multi worker problem.

In Storm, an application can have multiple workers (JVM) ranging anywhere from 10 to 100 or more. Each worker runs on a bare metal supervisor or inside a container in a docker based setup. In a multi-worker storm application, workers connect and stream data to each other based on application defined topology. The workers discover each other by registering their host name and service port in zookeeper, which is part of the storm cluster. 

It would be odd and impractical to fit this into k8s service model. We solved this in Marathon by letting the framework assign a dynamic port to the container and map the same port to the host. See https://github.com/mesosphere/marathon/pull/1548 and https://github.com/mesosphere/marathon/pull/1468.
With this, a worker would bind itself to the dynamically assigned container port P and register the same in zookeeper. Marathon would forward the same port number P on the host to the container. When another worker discovers and connects to this worker on host's port P, it would get routed to the container's port P.

Could you suggest if there is already an alternate solution to this in k8s or you would be open to a patch with the Marathon like solution?

Regards,
Sushant

**Comment by bgrant0607** [comment]
Why can't each worker register its pod IP and container port?

**Comment by sanjana-bhat** [comment]
@bgrant0607, we want to use replication controller to launch supervisors with replicas=100. How is an IP assigned to each of these replicas? 

I tried launching zookeeper of kind replication controller and this is what I notice in the pod description
k8sm/bin/kubectl get pods
POD                    IP            CONTAINER(S)   IMAGE(S)                              HOST   LABELS               STATUS    CREATED      MESSAGE
zk1-controller-l6jnr   172.17.0.19                                                         A   name=zk1-container   Running   34 minutes   
                                     zookeeper      sanjanab/k8s-zookeeper:latest                                                                         Running   34 minutes   

My apologies if I am missing something here.

**Comment by bgrant0607** [comment]
What cloud provider, OS distro, and networking solution are you using? How are you allocating network ranges for the nodes?

The networking model and implementation are described here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/networking.md

The pod IPs should be routable, at least from within the cluster.

**Comment by sanjana-bhat** [comment]
We are using kubernetes-mesos and looking into flannel. Do you have any pointers on the solutions available on these?

**Comment by sushantk** [comment]
Also, is having a dynamically allocated container port still a possibility as a solution that wouldn't require a layered networking solution?

**Comment by sushantk** [comment]
https://github.com/mesosphere/kubernetes-mesos/issues/312

**Comment by bgrant0607** [comment]
cc @jdef @guenter

**Comment by jdef** [comment]
@sushantk it appears that you've run into an unfortunate consequence of the port-mapping approach used by default in k8s-mesos, which assumes that the mesos cluster has been configured with default docker networking. Like marathon, host ports are allocated from resource offers on a mesos slave. Unlike marathon, which uses environment variables to expose this metadata, the k8s-mesos host-to-container port mapping metadata is not exposed to the underlying container.

A recent docker PR attempts to partially address this by exposing mappings via the filesystem:
https://github.com/docker/docker/pull/13363

I've filed an issue to track this in the kubernetes-mesos repo as well: https://github.com/mesosphere/kubernetes-mesos/issues/323

For an interim solution, when setting up your mesos cluster you could take the approach that stock k8s takes: assign each host a secondary /24 CIDR range, assign the docker bridge an IP from this range and allow Docker to assign IPs from this range. You can then use the stock k8s controller-manager and everything should just work.

K8s also documents an overlay networking approach here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/ovs-networking.md

**Comment by jdef** [comment]
FWIW k8s has been working on a downward API (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/downward_api.md). k8s-mesos *could possibly* expose port-mapping information through this mechanism.

Also, I should add that the mesos team is working on a solution that would ultimately allow k8s-mesos to assign an IP-per-pod, where IP's are allocated from a managed IP resource pool. These IP's would be routeable across the cluster.

**Comment by sanjana-bhat** [comment]
@jdef, apart from exposing the port-mapping information this would also require the framework to assign a dynamic port to the container and map the same port to the host. We achieved this in marathon with the following fix: [mesosphere/marathon#1548](https://github.com/mesosphere/marathon/pull/1548) and [mesosphere/marathon#1468](https://github.com/mesosphere/marathon/pull/1468).

**Comment by jdef** [comment]
Why does the port number need to match between the host and container?

**Comment by sanjana-bhat** [comment]
@jdef, this is especially useful for apps that advertise the port they are listening on to the outside world for P2P communication. Without this feature, they would erroneously advertise their private container port which is usually not the same as the externally visible host port. For ex: multi workers in storm.

**Comment by jdef** [comment]
OK, so storm workers are advertising only their port and not an IP address
to go along with it?

**Comment by sushantk** [comment]
I am closing this in favor of recommended approach of using overlay network.
