### ISSUE TITLE
Block link-local and localhost service/endpoint addresses in apiserver proxy

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#8989]
Reported by @stephenR

It's possible to turn the master into a proxy to localhost or the GCE metadata server by adding a new endpoint that points to the service.

To reproduce, add a new endpoint by posting to http://apiserver/api/v1beta3/endpoints with a description like:
```
{ "metadata": { "name": "myendpoint", [...] },
  "subsets": [
    {
      "addresses": [
        { "IP": "169.254.169.254", [...] }
      ],
      "ports": [
        { "port": 80, "protocol": "TCP" }
] } ] }
```

If you then go to http://apiserver/api/v1beta3/proxy/namespaces/default/services/myendpoint/ you can interact with the master's metadata server.

We can't validate that Endpoints are within the cluster CIDR because we deliberately allow importing of external addresses -- that was the original purpose of allowing users to post Endpoints. 

I wouldn't disallow link-local and localhost addresses in Endpoints, either, since that might be useful in the future. I'd prefer to just disallow proxying to such addresses. 

Obviously we'd need to resolve DNS names before checking.

See also #8871

cc @roberthbailey @a-robinson @stephenR @lavalamp

**Comment by roberthbailey** [comment]
@thockin

**Comment by thockin** [comment]
I think it would be simpler to disallow 169.254.0.0/16 as endpoints,
document why and move on.  The alternatives are more complicated and
difficult to internalize and debug.

**Comment by bgrant0607** [comment]
The user would either get an error when trying to post the Endpoints, or when trying to access the proxy. The latter is unlikely, IMO, except in malicious circumstances.

The former would prevent using services to do something like publish a local metadata service (say, similar to the [ACI metadata service](https://github.com/appc/spec/blob/master/SPEC.md#app-container-metadata-service)) on a link-local address.

But I'm ok with that approach for now, since it seems easy to change later.

**Comment by thockin** [comment]
Yeah, we can open it up as real requirements emerge, was my feeling.

**Comment by lavalamp** [comment]
I agree w/ @thockin's fix. Also we should block any similar range that AWS uses, etc.

**Comment by lavalamp** [comment]
Or resolve "metadata" and block just that.
