### ISSUE TITLE
labels not updating when pods updated on node-based pods

### ISSUE THREAD

**Issue by rwehner** [GoogleCloudPlatform/kubernetes#9008]
This is occurring on a v0.17.1 Kubernetes cluster running on top of CentOS7/VMWare-based hosts.

I run a log-collection pod on every node (minion) by placing the pod manifest in `/etc/kubernetes/manifests/` and running the `kubelet` process with the `--config=/etc/kubernetes/manifests` option. The log-collection manifest looks like:

    apiVersion: v1beta3
    kind: Pod
    metadata:
      labels:
        app: fluentd
        env: test
        version: v0.5.4
      name: fluentd-rsyslog
    spec:
      containers:
      - name: fluentd-rsyslog
        image: <my_private_registry>:<myuser>/kubernetes_fluentd_rsyslog:v0.5.4
        imagePullPolicy: Always
        env:
        - name: "FLUENTD_RSYSLOG_HOST"
          value: "<some_value>"
        - name: "FLUENTD_RSYSLOG_PORT"
          value: "<some_value>"
        volumeMounts:
        - name: varlog
          mountPath: /varlog
        - name: containers
          mountPath: /var/lib/docker/containers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: containers
        hostPath:
          path: /var/lib/docker/containers

When I upgrade the log-collection container, I replace the manifest in `/etc/kubernetes/manifests/` with the new version. Only the `version:` label and the `image:` location change to reflect the updated version string. The kubelet discovers the manifest change, stops the old pod and starts the new one. However, while it does pull and run the updated image, it never updates the labels on the pod to reflect what is in the manifest. You can see the image updated, but not the label:

    $ kubectl get pods -l app=fluentd

    POD                    IP            CONTAINER(S)      IMAGE(S)                                                         HOST         LABELS                                STATUS    CREATED      MESSAGE
    fluentd-rsyslog-kubmin00   172.16.47.2   fluentd-rsyslog   <my_private_registry>:<myuser>/kubernetes_fluentd_rsyslog:v0.5.4  kubmin00/   app=fluentd,env=test,version=v0.5.3    Running   18 minutes

The labels do get updated if I change the upgrade process for the log-collection container to the below, but this increases the time that I have no log collection running on the node:

1. Remove the old manifest from `/etc/kubernetes/manifests/`
1. Wait for the kubelet to remove the old pod.
1. Move the new manifest into `/etc/kubernetes/manifests/`

Clearly, I worked out this upgrade process by experimentation and it may not be the recommended way to do it. However, I think it uncovers an issue with not updating pod labels when other parts of a manifest are applied. It seems like it would be more correct to apply the full manifest rather than applying just part of it. Perhaps this is a bug in how the kubelet watches for and applies manifest updates when using node-based pods without replication controllers?

Thanks!

**Comment by yujuhong** [comment]
Thanks for reporting the issue!

Here is how the file-based pods work:
Kubelet submits a request to the apiserver to create a mirror pod based on the manifest file. If it detects that the mirror pod's spec differs from the manifest file, it'd re-create that mirror pod. In your case, the label change was not a spec change, hence kubelet did nothing.

This issue should be resolved once we stop comparing the pod specs, and simply store can compare the hash of the manifest file (#8683). Unfortunately, #8683 is currently not scoped for our v1.0 release, so I may not be able to get to it until post v1.0.

**Comment by rwehner** [comment]
Thanks for the explanation, @yujuhong. It is good to understand the issue and know where to track the likely resolution. I'll subscribe to https://github.com/GoogleCloudPlatform/kubernetes/issues/8683.

I have an acceptable workaround for my exploratory work and a post-v1.0 timeline seems fine to me. Thanks again!
