### ISSUE TITLE
kubectl: bad error message for Kind-less yaml

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#9010]
Given a YAML file without a 'Kind':

```
$ k create -f /tmp/y
error: no objects passed to create
```

Not a very helpful message

**Comment by manansaraf** [comment]
If someone hasn't started fixing this issue, I would like to start on it then!

**Comment by quinton-hoole** [comment]
Thanks @manansaraf.  @mikedanese can confirm.

**Comment by mikedanese** [comment]
#9357 fixes this.

**Comment by mikedanese** [comment]
@manansaraf #9405 might be of interest
