### ISSUE TITLE
active log streaming times out after 5 minutes

### ISSUE THREAD

**Issue by brenton** [GoogleCloudPlatform/kubernetes#9013]
I noticed that if I'm following a pod log that is being actively written to it will timeout after 5 minutes.  However if the pod is not writing logs the request will not timeout.  In that case the request will remain open seemingly indefinitely.

I can change the behavior by modifying this line of code:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L68

To make it happen faster you can set the value lower.  I've been testing with 1 minute.

Steps to reproduce:

1. Launch cluster
2. Create the nginx pod in `examples/pod.yaml`
3. In another terminal generate log output by hitting the pod: `while :; do curl 172.17.0.22; sleep 0.5; done` (you'll need to change the ip).
4. Watch the logs: `time curl -ivs --raw "http://127.0.0.1:8080/api/v1beta3/namespaces/default/pods/nginx/log?container=nginx&follow=true&previous=false"`

In this case whenever the WriteTimeout is reached curl will receive the zero sized chunk and the connection will be closed.  If you leave out step 3 curl will continue seemingly indefinitely.

This behavior definitely seems odd.  Is the usage of WriteTimeout correct here?  A quick search shows that others have been confused by the intention of WriteTimeout which is why I ask.

**Comment by rjnagal** [comment]
@lavalamp is this same as #6513 ?

**Comment by brenton** [comment]
From discussions on the OpenShift side it sounds somewhat related however what we're talking about is a reasonable (but arbitrary) timeout set.  Users of `kubectl logs -f <pod>` are subjected to this timeout with no good way to pick up where they left off to avoid redownloading potentially large quantities of logs.

**Comment by TomasTomecek** [comment]
To me, it would make sense if the api endpoint had argument which would fetch logs from line `N` (it's easy to track on client on which line we're at), exactly what `tail -n +N` does:

```
-n, --lines=K
      output the last K lines, instead of the last 10; or use -n +K to output lines starting with the Kth
```

I'm assuming that kubelet gets logs using docker api, unfortunately there is no such thing in docker's api:

```
tail – Output specified number of lines at the end of logs: all or <number>. Default all
```

**Comment by lavalamp** [comment]
> no good way to pick up where they left off to avoid redownloading potentially large quantities of logs.

I think users that want to do this should get the logs from elastic search instead of from kubectl.

**Comment by brenton** [comment]
I can't say I disagree about needing something like elastic search in a real world deployment.  I guess part of the weirdness is that clients of the logging API rarely know how much is going to be pulled down before they make the request.  I guess the answer now if you're following the logs is "5 minutes worth".

I know this isn't how it's implemented today but in my mind following the logs should behave more like `tail` or `journalctl -f`.  Meaning, when you state you want to follow you don't fetch the entire log file you just get wherever it happens to be (and maybe a little more for context).  If you want the whole file you don't pass in `-f`.

**Comment by TomasTomecek** [comment]
Any update? This is _really_ annoying and I'm thinking of patching my k8s.

**Comment by liggitt** [comment]
I think the default API timeout has been lengthened to 60 minutes

Defined:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L54

Used for API server:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L418

It looks like the kubelet timeout is still 5 minutes, so that would gate log streaming to 5 minutes:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L68

**Comment by liggitt** [comment]
More nuances in https://github.com/GoogleCloudPlatform/kubernetes/pull/8574
* Looks like the API http server times out after 60 minutes: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L418
* Watches time out between 5 and 10 minutes: https://github.com/GoogleCloudPlatform/kubernetes/pull/8574/files#diff-8083573e04feb68d0fbb1eed942974b9R70
* Kubelet http server still times out after 5 minutes

**Comment by TomasTomecek** [comment]
> Kubelet http server still times out after 5 minutes

Which means that getting logs timeouts after 5 minutes?

**Comment by liggitt** [comment]
yeah

**Comment by liggitt** [comment]
@dchen1107 did #8574 intentionally leave the kubelet timeout at 5 minutes, or should it be using the same ReadWriteTimeout as the api server?

**Comment by liggitt** [comment]
nm, @dchen1107 just merged the pr. @bprashanth, did #8574 intentionally leave the kubelet timeout at 5 minutes, or should it be using the same ReadWriteTimeout as the api server?

**Comment by bprashanth** [comment]
@liggitt we could easily bump up the kubelet timeout. The handlers on the kubelet don't have their own built in timeouts (like I did for watch), so a potential downside is long hanging /stats requests could hog connections, and depending on why they're hanging, continue consuming kubelet/cpu/cadvisor time. 

@lavalamp had a suggestion previously about using elasticsearch, are you running with a cluster that doesn't have the addons (https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons, if you set it up with kube-up it should)?

**Comment by lavalamp** [comment]
IMO there's no reason not to make kubelet server's timeout really long, at least for these requests.

**Comment by krousey** [comment]
I'm trying to put in a fix to increase the kubelet timeouts to 1 hour to match the master. Unfortunately adding proper timeout handling for these cases may not make 1.0, but hopefully this can make it less annoying.
