### ISSUE TITLE
Enable InfluxDB and Grafana dashboard on GCE by default

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#9028]
Some time back, we made decision to switch to GCM for monitoring, and GCL for logging for kubernetes clusters on GCE. But for logging, we still deploy Elasticsearch and Kibana services, but stop deploying InfluxDB and Grafana dashboard for monitoring. Given GCM is not completely ready yet, should we re-consider the decision for 1.0 release here?

```
$ cluster/kubectl.sh cluster-info
Kubernetes master is running at https://130.211.141.142
Elasticsearch is running at https://130.211.141.142/api/v1beta3/proxy/namespaces/default/services/elasticsearch-logging
Kibana is running at https://130.211.141.142/api/v1beta3/proxy/namespaces/default/services/kibana-logging
KubeDNS is running at https://130.211.141.142/api/v1beta3/proxy/namespaces/default/services/kube-dns
```

cc/ @brendanburns @thockin @vishh @saad-ali

**Comment by satnam6502** [comment]
Note that when logging to GCP is selected, we do not deploy the Elasticseach and Kibana pods.
The output shown above is for -- I guess -- a GCE cluster which has the default logging selection i.e. Elasticsearch -> Kibana.

**Comment by vishh** [comment]
I would recommend running Influxdb+Grafana since GCM doesn't work outside of GCE anyways.

**Comment by dchen1107** [comment]
@saad-ali volunteerly takes this work, thanks!

**Comment by saad-ali** [comment]
@erickhan, @dchen1107,, @vishh, and I sync'd up on this offline.

We've decided to do the following for GCE:
* For metrics:
  * Disable GCM
  * Enable InfluxDB/Grafana
* For events:
  * Leave GCL enabled
* For logs:
  * Disable Elasticsearch
  * Enable GCL

**Comment by satnam6502** [comment]
@saad-ali do you mean that for GCE clusters you now want logging to GCL to be the default rather than Elasticsearch/Kibana? It's not really a matter of "disabling" the Elasticsearch instances (and Kibana) since the type of cluster logging is determined at cluster birth time (and can't easily be changed afterwards right now).

**Comment by saad-ali** [comment]
@satnam6502 Yes, we'd prefer to align the story for events and cluster logs (both GCL or both elastic). We can sync up offline.

**Comment by goltermann** [comment]
@saad-ali Is this one finished with the merge of #9309, or is there still work to do?

**Comment by saad-ali** [comment]
@goltermann, yes, with #9309 this is resolved (InfluxDB/Grafana/GCL are enabled and GCM is disabled for GCE). I will close the issue.

I created #9757 to track the 3rd bullet point above: "Disable ElasticSearch and enable GCL for GCE"
