### ISSUE TITLE
kubernetes on azure not working : 

### ISSUE THREAD

**Issue by srakesh28** [GoogleCloudPlatform/kubernetes#9036]
I was trying to follow these instruction @ https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md  to build some containers and manage it but I can’t get pass the step of deploying apps

Steps I am able to run until is cluster/kube-up.sh (

This step never finishes , loops on Validation step and never ends, but I can see master and Menons spin up in Azure portal and can SSH to master , It looks like the kube-up.sh is not successful.

But  I tried Next steps of deploying a sample app on nginx container fails

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/simple-nginx.md

It basically can't connect to master node with error it can't connect to localhost:8080 api server

One thing other thing is doc is not clear about where to run this from ? Workstation , or kubernetes master ?

Also when run kubectl run my-nginx --image=nginx --replicas=2 --port=80 it says "run" is not recognized option.

Thanks

**Comment by yaroska** [comment]
Can you please try if these steps will work for you:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/README.md

**Comment by srakesh28** [comment]
Thank you  for your response, I have tried this steps also and it still does not work.
With this steps  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/README.md    I can successfully, spin up to ./create-kubernetes-cluster.js and able to ssh intto kube-00 , but after that it fails at step core@kube-00 ~ $ kubectl get minions
I get error as below:

Error: Get http://172.18.0.12:8080/api/v1beta3/minions: dial tcp 172.18.0.12:8080: i/o timeout

 basically it seems after install none of the Services are started on master. 
 Rakesh Shah
408-391-9610

**Comment by errordeveloper** [comment]
> `Error: Get http://172.18.0.12:8080/api/v1beta3/minions: dial tcp 172.18.0.12:8080: i/o timeout`

That's a bit odd, I'll take a look into it now.

**Comment by errordeveloper** [comment]
Ok this is due to mass rename that came with 300547110093d435dfb1cd31e6337d53d92f7194, I will update the code to use latest 0.18 release.

**Comment by yaroska** [comment]
Thank you very much, Ilya. 
Is it possible to add some error handling? Because now script process without an error but nothing works.

**Comment by errordeveloper** [comment]
@yaroska it'd be great to chat over on IRC, I'm not sure what exactly did you do and what didn't work... I'm `errordeveloper` in Freenode.

**Comment by errordeveloper** [comment]
@yaroska feel free to post details here, but IRC might be just a bit easier :)

**Comment by errordeveloper** [comment]
This should be fixed with #9060.
