### ISSUE TITLE
PORTAL_NET and service-cluster-ip-range

### ISSUE THREAD

**Issue by codemeow5** [GoogleCloudPlatform/kubernetes#9040]
kubernetes of the v0.15.0 version is still using the parameters of portal_net, but the script has been changed to "service-cluster-ip-range".

**Comment by thockin** [comment]
That parameter is renamed in 0.18, but the old flag to apiserver is still
accepted.

It's possible I missed some case where I need to accept both names - can
you explain the problem you are seeing?

Tim

**Comment by codemeow5** [comment]
I downloaded the 0.15 k8s via build.sh. When I tried to start, the log showed "unknown tag service-cluster-ip-range".
I follow this document
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

**Comment by thockin-cc** [comment]
0.15 is more than a month old.  Try 0.18 or else switch back to
--portal-net and PORTAL_NET flags.

**Comment by WIZARD-CXY** [comment]
@codemeow5 I'm the maintainer of the ubuntu k8s approach.I will bump the version to 0.18 soon
