### ISSUE TITLE
Permission error when mounting volumes

### ISSUE THREAD

**Issue by jsdir** [GoogleCloudPlatform/kubernetes#9051]
I get the following error when trying to use secret volumes in a pod:

```
E0531 20:49:19.686615       1 mount_linux.go:103] Mount failed: exit status 32
Mounting arguments: tmpfs /var/lib/kubelet/pods/21ff95cc-07d4-11e5-adf3-d4bed9346fba/volumes/kubernetes.io~secret/secret-volume tmpfs []
Output: mount: permission denied

E0531 20:49:19.686673       1 kubelet.go:979] Unable to mount volumes for pod "api-server-rsfne_default": exit status 32; skipping pod
I0531 20:49:19.686707       1 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"api-server-rsfne", UID:"21ff95cc-07d4-11e5-adf3-d4bed9346fba", APIVersion:"v1beta3", ResourceVersion:"30493", FieldPath:""}): reason: 'failedMount' Unable to mount volumes for pod "api-server-rsfne_default": exit status 32
```

```
Server Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
```

I'm also running the cluster locally from Docker: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md

**Comment by erictune** [comment]
What is your docker version?  Needs to be 1.6.
What options are you using to run the kubelet?  Should be passing `--containerized`.
Are you using SELinux?

**Comment by erictune** [comment]
@pmorie knows the most about this area.
I just asked the questions that he asked in #8734

**Comment by pmorie** [comment]
@jsdir Are you still having an issue with this?

**Comment by jsdir** [comment]
@pmorie Sorry for not responding sooner. @erictune's answer worked for me.

**Comment by dalanlan** [comment]
Sorry but i got the same pb. 
I wonder which solution worked for u since "--containerized" seems not ready yet. 
/cc @jsdir

**Comment by pmorie** [comment]
@dalanlan Which version of docker are you using, and on which platform?

**Comment by dalanlan** [comment]
Hmm...docker version: 1.7.1; k8s:v1.0.1; ubuntu14.04;
Sort it out by adding `--privileged` when running a containerized kubelet, may not coming in a recommended way though. @pmorie

**Comment by pmorie** [comment]
@dalanlan yep, you need to use both `--privileged` and `containerized`, but you may run into issues with the docker version distributed for ubuntu. Can you confirm that mounts are working for volumes in your deployment?

**Comment by dalanlan** [comment]
[Here](https://github.com/GoogleCloudPlatform/kubernetes/issues/11544#issuecomment-122632789) is what i suffered at the beginning. The original logs for kubelet was produced under the circumstance without --privileged` & `--containerized`.
I tried to add `--containerized` only (without `--privileged`) and another problem came up.
Finally i used `--privileged` only (without `--containerized`) and get rid of those mount problem. 
So far so good. Minor problems maybe. See [here](https://github.com/GoogleCloudPlatform/kubernetes/issues/11733#issuecomment-124275534).

Actually, params `--privileged` & `--containerized` are not specified in the [doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md#starting-the-kubernetes-master). Do you think it would be nicer to enclose them?
