### ISSUE TITLE
 kube2sky.go:260] Failed to create a kubernetes client: invalid --kube_master_url specified  http://10.5.39.41:8080

### ISSUE THREAD

**Issue by yanypunix** [GoogleCloudPlatform/kubernetes#9054]
kubernetes version 0.17.0
my skydns-rc.yaml
       .........
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.4
        args:
        # command = "/kube2sky"
        - -domain= "aaa.com"
        - -kube_master_url= http://10.5.39.41:8080
        .......

but prompt me invaild
[root@fedora3 dns]# kubectl log kube-dns-cvnhz  kube2sky 
2015-06-01T10:11:13.868733844Z I0601 10:11:13.866246       1 kube2sky.go:148] Etcd server found: http://127.0.0.1:4001
2015-06-01T10:11:14.867709800Z F0601 10:11:14.867145       1 kube2sky.go:260] Failed to create a kubernetes client: invalid --kube_master_url specified  http://10.5.X.41:8080
[root@fedora3 dns]# telnet 10.5.39.41 8080               
Trying 10.5.X.41...
Connected to 10.5.X.41.
Escape character is '^]'.

**Comment by erictune** [comment]
why is the letter "X" in the --kube_master_url?

**Comment by yanypunix** [comment]
yes, 10.5.X.41=10.5.39.41

**Comment by roberthbailey** [comment]
I don't see why you'd be getting that error, a simple example program doesn't reproduce it (http://play.golang.org/p/8ZwUyHocm8).

**Comment by yanypunix** [comment]
#cat aa.go
package main

import "fmt"
import "net/url"

func main() {
        u, err := url.Parse("http://10.5.39.41:8080")
        if err != nil {
                fmt.Printf("error: %v\n", err)
                return
        }
        fmt.Printf("'%s' '%s'\n", u.Scheme, u.Host)
}
#go build aa.go
# ./aa 
'http' '10.5.39.41:8080'

# curl http://10.5.39.41:8080
{
  "paths": [
    "/api",
    "/api/v1beta1",
    "/api/v1beta2",
    "/api/v1beta3",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/static/",
    "/swagger-ui/",
    "/swaggerapi/",
    "/validate",
    "/version"
  ]
}

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by yanypunix** [comment]
i will try it,close issue
