### ISSUE TITLE
Reboot e2e test is flaky

### ISSUE THREAD

**Issue by jszczepkowski** [GoogleCloudPlatform/kubernetes#9062]
Two cases of Reboot e2e are flaky on Jenkins: unclean reboot (echo b | sudo tee /proc/sysrq-trigger) and kernel panic (echo c | sudo tee /proc/sysrq-trigger). They reboot only one node, while reboot of the second doesn't happen and causes test timeout:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-reboot/123/console
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-reboot/120/console

**Comment by jszczepkowski** [comment]
CC @quinton-hoole

**Comment by quinton-hoole** [comment]
Master tracking bug #9312

**Comment by quinton-hoole** [comment]
Re-opening.  Current status as follows:

1. Reboot each node by dropping all outbound packages for a while and ensure they function afterwards (Failed 8 times in the last 30 runs. Stability: 73 %) #9062 
1. Reboot each node by dropping all inbound packages for a while and ensure they function afterwards (Failed 5 times in the last 30 runs. Stability: 83 %) #9062 
1. Reboot each node by ordering unclean reboot and ensure they function upon restart (Failed 3 times in the last 30 runs. Stability: 90 %) #9062 
1. Reboot each node by triggering kernel panic and ensure they function upon restart (Failed 3 times in the last 30 runs. Stability: 90 %) #9062 
1. Reboot each node by switching off the network interface and ensure they function upon switch on (Failed 3 times in the last 30 runs. Stability: 90 %) #9062 
1. Reboot each node by ordering clean reboot and ensure they function upon restart (Failed 3 times in the last 30 runs. Stability: 90 %) #9062

**Comment by quinton-hoole** [comment]
Any progress on this @jszczepkowski ?  cc @fgrzadkowski in case Jerzey is OOTO.

**Comment by jszczepkowski** [comment]
@quinton-hoole Sorry for replying so late, but I was on holidays. The flakiness was caused by liveness probes of some pods (e.g.: kube-dns).

**Comment by wojtek-t** [comment]
Also - @jszczepkowski implemented a fix for it - see #10547

**Comment by quinton-hoole** [comment]
For some reason #10547 seems to have fixed most but not all reboot tests.  For example:

Reboot each node by dropping all outbound packets for a while and ensure they function afterwards:

kubernetes-e2e-gce-reboot #1257 (Failed 8 times in the last 30 runs. Stability: 73 %)

Need to investigate and fix.

**Comment by quinton-hoole** [comment]
@jszczepkowski perhaps you could take a look in Poland while the U.S. is celebrating July 2nd, 3rd, 4th? :-)

**Comment by jszczepkowski** [comment]
There was a problem with monit restarting kubelet because of blocking localhost communication on firewall. Fixed by #10703.

**Comment by wojtek-t** [comment]
@jszczepkowski - since #10703 is now merged, can we close this issue? Or is there anything remaining here?

**Comment by quinton-hoole** [comment]
Yes, I think that we can close this now.  All reboot tests are pretty stable (1 failure in 180 runs, in total):

1. Reboot each node by dropping all inbound packets for a while and ensure they function afterwards (No known failures. Stability 100 %)	4 min 5 sec	Passed
1. Reboot each node by dropping all outbound packets for a while and ensure they function afterwards (No known failures. Stability 100 %)	4 min 6 sec	Passed
1. Reboot each node by ordering clean reboot and ensure they function upon restart (Failed 1 times in the last 30 runs. Stability: 96 %)	1 min 41 sec	Passed
1. Reboot each node by ordering unclean reboot and ensure they function upon restart (No known 1. failures. Stability 100 %)	1 min 25 sec	Passed
1. Reboot each node by switching off the network interface and ensure they function upon switch on (No known failures. Stability 100 %)	4 min 0 sec	Passed
1. Reboot each node by triggering kernel panic and ensure they function upon restart (No known failures. Stability 100 %)
