### ISSUE TITLE
Pods using NFS Persistent Volume failing with GO panic exception

### ISSUE THREAD

**Issue by wattsteve** [GoogleCloudPlatform/kubernetes#9064]
When I submit a pod that mounts a NFS Volume Claim, the pod is never started on the scheduled Kubernetes Node.

Version: v0.17.1-915-g6fa2777e26559f

Error on the Kubelet: http://pastebin.com/Yjdj41cF
PV definition and demonstration that the NFS server is working: http://pastebin.com/dRktZPWb
Pod and Claim Files: http://pastebin.com/J6GhKipL

**Comment by thockin** [comment]
#9055 should fix this
