### ISSUE TITLE
GCE Cluster turnup should fail if stale routes exist

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#9066]
I have been bitten by this twice - conflicting routes that exist when my cluster comes up.  This causes REALLY hard to debug network issues.  I would rather that cluster turnup be aborted.

**Comment by alex-mohr** [comment]
Idea: list all routes/lbs/nodes/disks/firewalls/other GCE resources at creation, check for regexp match against cluster name and error if any matches are found.

Bonus points for a --delete-preexisting-resources flag?

**Comment by alex-mohr** [comment]
@cjcullen as fyi

**Comment by davidopp** [comment]
This seems vaguely related to #8285

**Comment by alex-mohr** [comment]
Closing this specific-about-routes issue in favor of @8285 with broader coverage.
