### ISSUE TITLE
kubectl run is reporting an error on HEAD

### ISSUE THREAD

**Issue by derekwaynecarr** [GoogleCloudPlatform/kubernetes#9068]
I execute:

```shell
$ kubectl run nginx --image=nginx
error: Parameter: default-name is required
```

**Comment by derekwaynecarr** [comment]
Appears to be related to changes made in this PR:

https://github.com/GoogleCloudPlatform/kubernetes/pull/8804

**Comment by derekwaynecarr** [comment]
Looks like the change here:

https://github.com/GoogleCloudPlatform/kubernetes/pull/8804/files#diff-961b43a40b4bf2300c985aa16ebcc813L119

```expose``` should have a different set of param names than ```run```

**Comment by derekwaynecarr** [comment]
Looks like they do have a different set of names, but for ```run``` the wrong default was set.

**Comment by erictune** [comment]
@kargakis
