### ISSUE TITLE
Add v1 tests

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#9070]
#8917 deletes tests for deprecated apis. Now we will add tests for v1. I will make several small PRs and refer to this issue.

@bgrant0607 @krousey @nikhiljindal

**Comment by bgrant0607** [comment]
Part of #7018

**Comment by caesarxuchao** [comment]
I've finished adding v1 tests based on the changes made in #8917.

Here is a list of test files that contains "v1beta3" but not "v1". I'll go through them one by one.

```
~/.../kubernetes/pkg$ find ./ -type f -name "*test*" | xargs grep -l "v1beta3" | xargs grep -L "v1\b"
```
./runtime/unstructured_test.go
./runtime/helper_test.go
./registry/podtemplate/etcd/etcd_test.go
./apiserver/api_installer_test.go
./apiserver/apiserver_test.go
./kubelet/config/file_test.go
./kubelet/config/common_test.go
./api/v1beta3/conversion_test.go
./api/v1beta3/defaults_test.go
./api/latest/latest_test.go
./api/serialization_test.go
./api/testapi/testapi.go
./api/testapi/testapi_test.go
./api/meta/restmapper_test.go
./api/conversion_test.go
./kubectl/cmd/util/factory_test.go
./kubectl/cmd/expose_test.go
./client/record/events_cache_test.go
```

**Comment by caesarxuchao** [comment]
In latest_test.go, line 73,
```
	if v, k, err := RESTMapper.VersionAndKindForResource("replicationControllers"); err != nil || v != "v1beta3" || k != "ReplicationController" {
		t.Errorf("unexpected version mapping: %s %s %v", v, k, err)
	}
```
Is this still the behavior we expect? More specifically, do we want VersionAndKindForResource to return v1 or v1beta3? We will need to change the order of registered versions if we want v1 to be returned.

@bgrant0607

**Comment by caesarxuchao** [comment]
Hi @bgrant0607,

For these tests have v1beta3 test cases but not v1, but I don't think adding v1 will make a difference. Shall I leave them as they are, or shall I add v1 tests for them?
./apiserver/api_installer_test.go
./kubectl/cmd/util/factory_test.go
./kubectl/cmd/expose_test.go
./client/record/events_cache_test.go

`./registry/podtemplate/etcd/etcd_test.go`  uses a v1beta3 codec. Please advise if I should duplicate the test for v1.

Also please take a look at my last comment about `latest_test.go`.

Thank you.

**Comment by bgrant0607** [comment]
@caesarxuchao `replicationControllers` was valid only for v1beta1 and v1beta2. It should be all lowercase `replicationcontrollers` for both v1beta3 and v1.

**Comment by bgrant0607** [comment]
We're not ready to make v1 the preferred API yet. It's not even enabled by default.

**Comment by bgrant0607** [comment]
PodTemplate was not in v1beta1 and v1beta2. It should be in v1 as well as v1beta3.

**Comment by bgrant0607** [comment]
api_installer_test.go, factory_test.go, and expose_test.go: Just change those from v1beta3 to v1.

event_cache_test.go: I don't think it depends on the apiversion -- it's data in the event. Try changing all instances of v1beta2 to "version".

**Comment by caesarxuchao** [comment]
I will make these changes in #9225

**Comment by bgrant0607** [comment]
You can remove the `if api.PreV1Beta3(testapi.Version())` checks from pod_template_test.go.

**Comment by bgrant0607** [comment]
And you should be able to remove "newerHelper" in master.go and just use c.EtcdHelper.

**Comment by caesarxuchao** [comment]
I understand "replicationControllers" should not be valid for v1beta3 or v1. But currently the RestMapper.VersionAndKindForResource will tolerate "replicationControllers", because it lower case the string before looking it up in the map. I will modify this line of test but I won't change the behavior of this function.
