### ISSUE TITLE
0.18.1 release

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#9087]
This issue is for accumulating cherrypicks for 0.18.1.

* Fix for kubectl run: #9071
* Fix for kubectl exec (not fixed yet -- was broken by PR #8604)

cc @jlowdermilk @roberthbailey @zmerlynn

**Comment by ncdc** [comment]
kubectl exec issue is #9113

**Comment by dchen1107** [comment]
If we want to patch v0.18, I want to include #8681, which creates /system container. We recently observed abusive daemon process takes too much cpu and causes machine unresponsive. @brendandburns

**Comment by zmerlynn** [comment]
I'd like to get #9118 for upgrade testing (it's causing initial version deployment headaches), but it still needs an LGTM.

**Comment by bgrant0607** [comment]
The exec fix is in #9164.

**Comment by bgrant0607** [comment]
@dchen1107 #8681 is a non-trivial change and not a bug fix, so I don't think we should include it in the patch release.

**Comment by brendandburns** [comment]
Personally, I'm ok with #8681, since it is a bug fix (users have reported node CPU spiking taking down clusters).

I've picked it into the 0.18.1 that I'm testing, so we'll make sure it passes e2e.  Then we can make a decision about if we're comfortable shipping that.

**Comment by bgrant0607** [comment]
That PR said it depended on #8586.

**Comment by brendandburns** [comment]
#8586 looks like it was merged 7 days ago, so it's already in the release afaik.

**Comment by brendandburns** [comment]
Closing this as done.  The release is live as default in GKE.
