### ISSUE TITLE
In web UI redirect / to actual URL

### ISSUE THREAD

**Issue by tobegit3hub** [GoogleCloudPlatform/kubernetes#9090]
I follow the instruction to start the kubernetes web UI. It's 404 when I open http://127.0.0.1:8080 . Finally  I knew that the correct directory is http://127.0.0.1:8080/static/app/#/dashboard/ . 

We should start the web ui in root directory(I mean http://127.0.0.1:8080) so that anyone like me will not be confused.

**Comment by bgrant0607** [comment]
I agree the UI isn't very discoverable. We should redirect from `/` to the correct path. (Assuming that the UI is working well enough to expose it at all.)

**Comment by mikedanese** [comment]
I can do this if no one else is on it. Should we redirect all requests to `/` and `/index.html` or just requests with specific user-agents?

**Comment by bgrant0607** [comment]
We return a list of resource paths on `/` currently:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/index.go#L31

We could either redirect for certain user-agents, or choose another, simpler, more obvious, top-level path, like `/www` or `/ui`, which would at least show up in the list of valid paths.

**Comment by tobegit3hub** [comment]
That's great! @mikedanese @bgrant0607

**Comment by tobegit3hub** [comment]
Great job :+1: @mikedanese
