### ISSUE TITLE
Add "The Kubernetes Github Workflow" to docs/devel/

### ISSUE THREAD

**Issue by JeffPaine** [GoogleCloudPlatform/kubernetes#9091]
I'd like to suggest converting the content of "[The Kubernetes Github Workflow](https://docs.google.com/presentation/d/1HVxKSnvlc2WJJq8b9KCYtact5ZRrzDzkWgKEfm0QO_o/pub?start=false&loop=false&delayms=3000&slide=id.g8c9142d48_00)" from google docs preso to markdown for inclusion in `docs/devel/`.

These slides contain important info for new contributors which would ideally appear right in the dev docs and also be under version control.

Happy to submit a PR for this (with a little guidance on what file it should appear in)!

**Comment by JeffPaine** [comment]
I'd offer that `docs/devel/development.md` is the right place to include this info.

[Keeping your development fork in sync](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#keeping-your-development-fork-in-sync) covers some of the content of the presentation, but the other sections in devlopment.md that discuss forking the project contradict the contents of the presentation (for example cloning from `GoogleCloudPlatform/kubernetes` as opposed to forking, cloning and adding an upstream remote). Happy to make all that consistent at the same time.

**Comment by thockin** [comment]
I think the truth is that many workflows work just fine.  We documented the
simplest one for people who are not deeply familiar with Git (we had to
on-board a lot of people very quickly).  I'm very much in favor of better
documentation and making it more available, but I don't think we need to
demand consistency in this - Got is a powerful tool that many people use in
different but equally valid ways :)

Docs PRs are ALWAYS welcome

**Comment by JeffPaine** [comment]
Thanks for the explanation! Totally fair points I don't disagree with.

Rather than wholesale inclusion, is it appropriate to simply add a brief section to the docs on a basic git workflow but mention it's not required? I don't have a strong feeling either way, my only goal is nice docs / on-ramping experience and this was the first thing that tripped me up as I'm getting started :)

**Comment by thockin** [comment]
I would be fine to include the equivalent of these slides as "one of the
more common git workflows that core developers use".  PRs welcome.

**Comment by JeffPaine** [comment]
Sounds good, I'll put together a PR, thanks for the guidance so far!
