### ISSUE TITLE
kube-push does not restart Kubelets if only flags in salt file were changed.

### ISSUE THREAD

**Issue by gmarek** [GoogleCloudPlatform/kubernetes#9110]
I was playing with salt configs and noticed that after kube-push I need to restart Kubelet by hand for it to read the new flags. I believe it should be done automatically by the script.

**Comment by gmarek** [comment]
@davidopp

**Comment by alex-mohr** [comment]
Piotr's fixing up kube-push atm -- perhaps something he can look into?

**Comment by piosz** [comment]
Sorry, I don't have time for this.

**Comment by davidopp** [comment]
@zmerlynn @roberthbailey

**Comment by dchen1107** [comment]
I can take a look today.

**Comment by dchen1107** [comment]
hmm, I cannot reproduce the issue here. Here are the steps I am doing:

1) Change log_level flag through salt config file:

```
$ git diff
diff --git a/cluster/saltbase/pillar/logging.sls b/cluster/saltbase/pillar/logging.sls
index 25e8351..c75e6c9 100644
--- a/cluster/saltbase/pillar/logging.sls
+++ b/cluster/saltbase/pillar/logging.sls
@@ -1 +1 @@
-log_level: "--v=2"
+log_level: "--v=4"
```
2) before kube_push, kubelet is running with flag --v=2 and pid is 5583

```
# ps -ef | grep kubelet
root      3649  5351  0 20:00 pts/1    00:00:00 grep kubelet
root      5583     1  1 Jun01 ?        00:21:30 /usr/local/bin/kubelet --api_servers=https://kubernetes-master --cloud_provider=gce --config=/etc/kubernetes/manifests --allow_privileged=False --v=2 --cluster_dns=10.0.0.10 --cluster_domain=cluster.local --configure-cbr0=true --cgroup_root=/ --system-container=/system
```

3) after kube_push, kubelet is restarted with new flag --v=4 and pid is 4252

```
# ps -ef | grep kubelet
root      4252     1  3 20:01 ?        00:00:02 /usr/local/bin/kubelet --api_servers=https://kubernetes-master --cloud_provider=gce --config=/etc/kubernetes/manifests --allow_privileged=False --v=4 --cluster_dns=10.0.0.10 --cluster_domain=cluster.local --configure-cbr0=true --cgroup_root=/ --system-container=/system
root      5052  5351  0 20:02 pts/1    00:00:00 grep kubelet
```

@gmarek Which flag were you changing?

**Comment by gmarek** [comment]
Just added some flag in DAEMON_ARGS in the default salt config. I tried this by modifying the file by hand, not by setting some additional grains.

**Comment by dchen1107** [comment]
I move this back v1.0 since it blocks #8151 which is targeted for 1.0. Also fix the on the way.
