### ISSUE TITLE
kubectl exec <pod> needs to remove <pod> from args it sends to container

### ISSUE THREAD

**Issue by ncdc** [GoogleCloudPlatform/kubernetes#9113]
When running `kubectl exec`, if you don't specify the deprecated `-p <pod>` and instead just do `<pod>`, it doesn't strip off the 1st command line arg, so

```
kubectl exec nginx date
```

sends the command `nginx date` to the container, whereas

```
kubectl exec -p nginx date
```

correctly sends just `date`

Regression from #8604

**Comment by ncdc** [comment]
@smarterclayton FYI

**Comment by smarterclayton** [comment]
We still support --, correct?

**Comment by ncdc** [comment]
@smarterclayton yes, we still support `-p pod`, but it's marked deprecated.

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by brendandburns** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9164

has the fix.  (and better unit test coverage) Sorry for the breakage!
