### ISSUE TITLE
the K8S_VERSION in kubernetes/cluster/ubuntu/build.sh is too old

### ISSUE THREAD

**Issue by suxianqun** [GoogleCloudPlatform/kubernetes#9114]
the ‘K8S_VERSION’ in kubernetes/cluster/ubuntu/build.sh is too old,  the new option ‘--service-cluster-ip-range’ added in kubernetes/cluster/ubuntu/build.sh was not supported when K8S_VERSION="v0.15.0".

**Comment by erictune** [comment]
should be fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/9102
