### ISSUE TITLE
Flaky test: TestRequestExecuteRemoteCommand

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#9119]
A test is flaky.  

https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/65002732

--- FAIL: TestRequestExecuteRemoteCommand (0.04 seconds)
	remotecommand_test.go:207: 1: expected true, got false: <nil>
FAIL

This is with go1.3, though I suspect it is not version-related.
This is during race testing, but there is not a specific message about a race being detected.  Probably things are happening in a different order, causing a test expectation to fail.
This is also during coverage measurement, which might also affect timing. 

Please try running this test many times to see if it fails again, and then fix it.  Run with race detection and coverage if needed to repro.

**Comment by erictune** [comment]
@ncdc I think you authored this test.  Would you check if there are any downstream fixes, and if not run it a bunch of times to see if it fails for you?

**Comment by ncdc** [comment]
@erictune I have an idea what's going on. I can take a look in a bit.

**Comment by ncdc** [comment]
Unfortunately I've got other things on my plate at the moment. But my guess is that the execute command is able to finish reading the data for the stdin/stdout/stderr streams before the error stream's data comes through, leading to the flake. 1 possible solution would be to have the test use "slow" or never-ending readers/writers for the stdin/stdout/stderr streams, while letting the error stream's data come through quickly.

**Comment by bprashanth** [comment]
Also observed here https://app.shippable.com/builds/5579ea717915e70b0059767b

**Comment by yujuhong** [comment]
Just saw a similar failure:
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/69774690

```
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd	2.056s	coverage: 64.5% of statements
--- FAIL: TestRequestExecuteRemoteCommand-2 (0.00 seconds)
	remotecommand_test.go:207: 1: expected true, got false: <nil>
```

**Comment by ncdc** [comment]
I will try to work on a fix this week.

**Comment by karlkfi** [comment]
xref: #10775
