### ISSUE TITLE
Low performance to get the endpoints for the service

### ISSUE THREAD

**Issue by nkwangleiGIT** [GoogleCloudPlatform/kubernetes#9122]
Hi,
We met with low performance issue when create a service and try to visit the service port using kube-proxy.

After some debug, we found that it'll take a long time to retrieve the endpoints information of the service, here is the output using "kubectl describe service", and the "Endpoints" will be "<none>" for more than 1 minute, and we can visit the service port successfully once the endpoints is available.

Could you shed me some light about how we should do the troubleshooting for this kind of issue? seems it's caused by the low performance of api-server? and the endpoints information take long time to be saved to etcd?

Thanks a lot！

root@iZ253wunw7zZ:~# **kubectl describe service hw1-avplz --namespace=nkwanglei**
W0602 22:22:55.291240    2800 request.go:291] field selector: v1beta3 - events - involvedObject.name - hw1-avplz: need to check if this is versioned correctly.
W0602 22:22:55.291350    2800 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - nkwanglei8lrp: need to check if this is versioned correctly.
W0602 22:22:55.291374    2800 request.go:291] field selector: v1beta3 - events - involvedObject.kind - Service: need to check if this is versioned correctly.
W0602 22:22:55.291414    2800 request.go:291] field selector: v1beta3 - events - involvedObject.uid - b80a60af-0932-11e5-b82c-00163e0057bf: need to check if this is versioned correctly.
Name:			hw1-avplz
Labels:			name=hw1-avplz
Selector:		name=hw1-avplz
IP:			192.168.15.180
Public IPs:		123.57.48.74
Port:			port-rrs7-46102	46102/TCP
Endpoints:		port-rrs7-46102	**&lt;none&gt;**  -> long time to see the endpoints here!
Session Affinity:	None
No events.

**Comment by lavalamp** [comment]
This should be very quick-- so my guess is that it's the pods that are slow to come up. They won't be included until they're running and healthy.

If that doesn't answer your question, to help you narrow it down your config .json/.yml files, and your controller-manager log would be helpful.

**Comment by nkwangleiGIT** [comment]
Hi lavalamp, thanks for your kindly help, as I can see the pods should already be started and running normally. I can check the container log and saw the server started.

Here is the json file for service and replicator:
Service
'''{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "hw1-0qjo0",
        "namespace": "nkwanglei8lrp",
        "selfLink": "/api/v1beta3/namespaces/nkwanglei8lrp/services/hw1-0qjo0",
        "uid": "d4517856-09c7-11e5-8d1b-00163e0057bf",
        "resourceVersion": "10348506",
        "creationTimestamp": "2015-06-03T08:09:16Z",
        "labels": {
            "name": "hw1-0qjo0"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "port-74ni-40231",
                "protocol": "TCP",
                "port": 40231,
                "targetPort": 80,
                "nodePort": 0
            }
        ],
        "selector": {
            "name": "hw1-0qjo0"
        },
        "portalIP": "192.168.3.38",
        "type": "ClusterIP",
        "publicIPs": [
            "123.57.48.74"
        ],
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}
'''
Replicator
'''
{
    "kind": "ReplicationController",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "hw1-0qjo0",
        "namespace": "nkwanglei8lrp",
        "selfLink": "/api/v1beta3/namespaces/nkwanglei8lrp/replicationcontrollers/hw1-0qjo0",
        "uid": "d4508db8-09c7-11e5-8d1b-00163e0057bf",
        "resourceVersion": "10348504",
        "creationTimestamp": "2015-06-03T08:09:16Z",
        "labels": {
            "name": "hw1-0qjo0"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "name": "hw1-0qjo0"
        },
        "template": {
            "metadata": {
                "creationTimestamp": "2015-06-03T08:09:16Z",
                "labels": {
                    "name": "hw1-0qjo0"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "hw1-0qjo0",
                        "image": "10.171.81.240:8080/test/hello-world:latest",
                        "ports": [
                            {
                                "containerPort": 80,
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {
                            "limits": {
                                "cpu": "50m",
                                "memory": "64Mi"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "imagePullPolicy": "IfNotPresent",
                        "capabilities": {},
                        "securityContext": {
                            "capabilities": {},
                            "privileged": false
                        }
                    }
                ],
                "restartPolicy": "Always",
                "dnsPolicy": "ClusterFirst",
                "serviceAccount": ""
            }
        }
    },
    "status": {
        "replicas": 0
    }
}
'''
What log level I should use to collect controller-manager log? for now, I can only some warnings below:
'''
E0603 16:24:25.981512   19888 resource_quota_controller.go:74] Error synchronizing: resourcequotas "dl528888" cannot be updated: the resource was updated to 10359640
E0603 16:24:26.031636   19888 resource_quota_controller.go:74] Error synchronizing: resourcequotas "wangh" cannot be updated: the resource was updated to 10359687
E0603 16:24:26.081357   19888 resource_quota_controller.go:74] Error synchronizing: resourcequotas "wjp719" cannot be updated: the resource was updated to 10359648
E0603 16:24:26.131424   19888 resource_quota_controller.go:74] Error synchronizing: resourcequotas "xds2000" cannot be updated: the resource was updated to 10359646
E0603 16:24:26.182200   19888 resource_quota_controller.go:74] Error synchronizing: resourcequotas "yorkoliu" cannot be updated: the resource was updated to 10359729
E0603 16:24:26.231436   19888 resource_quota_controller.go:74] Error synchronizing: resourcequotas "seanliang" cannot be updated: the resource was updated to 10359678
'''

Thanks!

**Comment by lavalamp** [comment]
I think -v=4 should be good to get this message: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/service/endpoints_controller.go#L256

This should help us narrow down whether the endpoint controller is slow, or something else is wrong.

How large is your cluster? Approximately how many pods are you running?

**Comment by nkwangleiGIT** [comment]
We're running more than 300 pods in a 10 nodes cluster by now, will change the log level and put the log here later, thanks a lot!

**Comment by nkwangleiGIT** [comment]
Hi  lavalamp, we found that it's probably caused by the low performance on kube-proxy side, we tried the scenarios below:
1. On all minions/slaves, we start the kube-proxy service; and on a separate host, we also start flannel and kube-proxy service, use this host as the publicIPs of k8s service, so any request will come from this host, so we can hide the k8s master/slave behinde this proxy host.

2. We stopped the kube-proxy service on all k8s slaves, and use the separate proxy host as the single proxy.

I'm not sure what's the recommended approach to support large number of services, do we need to have multiple kube-proxies and masters to have better load balance?

BTW, we'll use publicIPs and a random service port to create these services and associated rc/pods, and each user can use the publicIPs and port to access there service.

Thanks.

**Comment by nkwangleiGIT** [comment]
Hi lavalamp, here is the log from kube-controller-manager log using "--v=4", and I'm creating a service with name *"hw123"*:
https://github.com/nkwangleiGIT/docker-node-hello/blob/master/kube-controller-manager-bak.log

The creation of service is about "22:08:42.376079":
```
I0604 22:08:42.376033   18689 replication_controller.go:351] Finished syncing controller "zzwangsh/mysql-2c1pz" (80.497µs)
I0604 22:08:42.376079   18689 controller_utils.go:119] Controller hw123-sbegc either never recorded expectations, or the ttl expired.
I0604 22:08:42.376194   18689 controller_utils.go:133] Setting expectations &{add:1 del:0 key:nkwanglei8lrp/hw123-sbegc}
```

The time to finish syncing service is about "22:10:29.636040"
```
I0604 22:10:29.535102   18689 endpoints_controller.go:258] Finished syncing service "294168881r6vs/lvyao-fg06q" endpoints. (502.314888ms)
I0604 22:10:29.636040   18689 endpoints_controller.go:258] Finished syncing service "nkwanglei8lrp/hw123-sbegc" endpoints. (503.760573ms)
I0604 22:10:29.837167   18689 endpoints_controller.go:258] Finished syncing service "294168881r6vs/wp-host-fckv5" endpoints. (502.568419ms)

So it tool almost 1min 47s  to have the service available, anything we should check futher for this issue?

Thanks a lot!

```

**Comment by lavalamp** [comment]
Thank you for all the details!

> The creation of service is about "22:08:42.376079":

The log snippet you included shows replication controller manager creating pods for a replicationController, not a service being created. apiserver's log is probably the best place to look for the canonical service creation time.

> The time to finish syncing service is about "22:10:29.636040"

So it takes about half a second for the service's endpoints to be generated. So the time is being lost in either some sort of propagation delay or in starting the pods themselves.

> low performance on kube-proxy side

Can you explain how you observed this low performance, and what nature it took? 

After looking at your log, I have some more questions so I can better understand your scenario and maybe try to reproduce. How many services do you have? How many replication controllers? Approximately how frequently on average do you start/stop your replication controllers and services?

**Comment by nkwangleiGIT** [comment]
Hi  lavalamp,
Actually, we're not quite clear about how kube-proxy works, seems it's just create some routing rules in iptable on each kube-proxy node. Looking at the kube-proxy log, seems these rules was created quickly. 

The number of services and replication controllers are both over 300, actually we don't start/stop the rc or service frequently, would like to have them running as long as possible.

Thanks.

**Comment by nkwangleiGIT** [comment]
BTW, is there any performance tuning parameters we can use on api-server or kubelet? thanks!

**Comment by lavalamp** [comment]
@nkwangleiGIT I'm writing a test to start a RC with a single pod and wait for it to be ready; then start a service that will point at that pod & measure latency until the endpoint is updated. I'm still not quite clear if this is what you're doing or not and my most likely candidate for the delay you see is the delay until the pod(s) become ready.

If you start the RC & service at the same time, the endpoints won't get updated until the pod's image has been pulled and is running. If there's another source of delay, hopefully my test will find it.

There aren't generally performance tuning flags; one thing you can try is to set etcd's GOMAXPROCS env var to something higher than 1. It may or may not help.

**Comment by lavalamp** [comment]
On a 2 node cluster, I did 200 trials of the test I mentioned, 16 at a time in parallel. Median time between service creation and endpoint generation was 1.1s, 99th percentile was 3.3s. I think these numbers are fine. I will shortly package this test up in a PR.

```
INFO: Latencies: [39.427951ms 39.674627ms 40.404877ms 40.425447ms 40.70249ms 41.491146ms 42.035126ms 42.181021ms 42.429628ms 43.012722ms 53.244064ms 60.146213ms 62.723308ms 109.994677ms 123.28312ms 133.380116ms 156.037232ms 176.309933ms 219.164138ms 272.661005ms 281.473552ms 289.375036ms 309.1729ms 310.372419ms 325.046391ms 366.41952ms 370.367198ms 371.959213ms 375.235249ms 530.504888ms 544.88371ms 555.665094ms 568.291587ms 574.550725ms 739.295657ms 744.711605ms 748.661097ms 762.197713ms 768.900279ms 769.672282ms 770.366349ms 770.478547ms 782.849021ms 784.577183ms 810.612402ms 820.163666ms 824.591481ms 829.692408ms 907.858768ms 919.53622ms 942.051295ms 947.508639ms 948.407366ms 956.834389ms 959.190455ms 960.158559ms 963.248173ms 965.751464ms 966.698203ms 966.855325ms 968.904647ms 970.35762ms 973.789123ms 974.52125ms 975.033664ms 975.073473ms 990.253395ms 1.01074082s 1.013139442s 1.020497644s 1.026778431s 1.030077789s 1.030548458s 1.032950274s 1.034546229s 1.041128843s 1.08989952s 1.090670032s 1.099052897s 1.104544645s 1.113579906s 1.115579051s 1.124516067s 1.127656864s 1.13310972s 1.138039857s 1.14558559s 1.159724825s 1.16293187s 1.16552548s 1.166007701s 1.166165267s 1.166901594s 1.167751132s 1.168457339s 1.171804568s 1.171943228s 1.172093757s 1.175634714s 1.177815813s 1.180733012s 1.206186232s 1.218063852s 1.226394615s 1.230531562s 1.231302898s 1.304779981s 1.316198503s 1.335440913s 1.339945289s 1.344405978s 1.345114537s 1.345570854s 1.348946556s 1.349535923s 1.350947624s 1.356714508s 1.358430276s 1.358561472s 1.360713816s 1.362018939s 1.363382096s 1.364806026s 1.365029326s 1.366680106s 1.369483222s 1.369916857s 1.370549764s 1.370686121s 1.370921155s 1.371321699s 1.372325703s 1.374127822s 1.374636953s 1.377226619s 1.487155721s 1.488110086s 1.508405194s 1.536409997s 1.547778989s 1.549291996s 1.553465564s 1.558285969s 1.558607044s 1.559599665s 1.562678418s 1.562702726s 1.570128917s 1.570866263s 1.57107557s 1.571081579s 1.571559257s 1.571864964s 1.574800501s 1.574882562s 1.60008048s 1.630434547s 1.650318548s 1.65908627s 1.690669318s 1.709858049s 1.732304281s 1.735477274s 1.752737451s 1.755875783s 1.767103114s 1.773960444s 1.776742133s 1.828194982s 1.871643975s 1.963175994s 1.965939816s 1.979133247s 1.991637873s 2.154117602s 2.166542406s 2.169241516s 2.173004487s 2.221932423s 2.237743016s 2.292934224s 2.29399058s 2.301439184s 2.400282871s 2.539325881s 2.562574843s 2.56361982s 2.569292018s 2.572950189s 2.610160801s 2.766430447s 2.771766553s 2.833507889s 3.026726317s 3.11700965s 3.129388693s 3.146623548s 3.172774996s 3.313625559s 3.394861599s]
INFO: 50 %ile: 1.180733012s
INFO: 90 %ile: 2.292934224s
INFO: 99 %ile: 3.313625559s
```

**Comment by lavalamp** [comment]
Can you run the test in #9354 against your cluster?

I think if you pull my change in that branch something like the below should work to run just this test against your cluster:
```
$ hack/build-go.sh
$ go run hack/e2e.go -v -check_version_skew=false -test -test_args=--ginkgo.focus=.*latency |& less -r
```

This will tell us if the delay you see is service creation -> endpoint generation or something else.

**Comment by davidopp** [comment]
@nkwangleiGIT could you please respond or close the issue? Thanks!

**Comment by dchen1107** [comment]
cc/ @dchen1107

**Comment by nkwangleiGIT** [comment]
Hi lavalamp, 
Thanks for your test case for troubleshooing
1. I tried GOMAXPROCS on etcd, seems it didn't do much help
2. About the step below:
```
$ hack/build-go.sh
$ go run hack/e2e.go -v -check_version_skew=false -test -test_args=--ginkgo.focus=.*latency |& less -r
```
Kubernetes build system is on another host that is different with the environment that has this issue, could you point me how I can run this test agains a remote kubernetes system?

Thanks!

**Comment by lavalamp** [comment]
@nkwangleiGIT you should be able to run it anywhere that you can run e.g. `kubectl get pods`. I just tested myself and after building, the below command worked for running it against a normal (non-e2e) cluster:

```
KUBE_CONFIG_FILE=config-default.sh hack/ginkgo-e2e.sh --ginkgo.focus=.*latency
```

But it now occurs to me that rather than me guessing, perhaps the easiest way to figure this out is for you to condense your config that shows the problem into a short script? Can you make an example bash script that shows the problem, using gcr.io/google_containers/pause as the image that it runs?

Also, can you say what version of kubernetes you're running? I should have asked earlier.

**Comment by nkwangleiGIT** [comment]
Hi lavalamp,
The endpoints update seems some quicker now, around 10s, so I'll take a look at your test case and try it later. For now, we just upgraded to 0.18.2.
And we found some performance issue of kube-proxy, and more discussion here:
https://github.com/GoogleCloudPlatform/kubernetes/issues/9673
I think we can close this issue for now, and will open another one if it's an issue, thanks.

**Comment by lavalamp** [comment]
Ah-- I recently rewrote the endpoint controller, if you were running anything <= 0.16 (I think?), it probably would have been slow. :)
