### ISSUE TITLE
kubelet panics on instances without public IP (AWS)

### ISSUE THREAD

**Issue by antoineco** [GoogleCloudPlatform/kubernetes#9123]
Since node auto-registration was introduced in v0.18.0, the `kubelet` crashes on AWS if the instance it runs on doesn't have a public IP.

The full error trace is available here: https://gist.github.com/antoineco/8d5a168aae8ab5b94cef

**Comment by dchen1107** [comment]
cc/ @roberthbailey

**Comment by roberthbailey** [comment]
The kubelet asks the cloud provider for node addresses, and the implementation is specific to each provider. It looks like this is a bug in the aws cloud provider: the stack trace points to [line 412 of aws.go](https://github.com/GoogleCloudPlatform/kubernetes/blob/v0.18.0/pkg/cloudprovider/aws/aws.go#L412).

**Comment by justinsb** [comment]
Thanks for the great bug report.  Working on a fix in #9189.
