### ISSUE TITLE
Upgrade ui-dashboard from v1beta2 to v1

### ISSUE THREAD

**Issue by mikedanese** [GoogleCloudPlatform/kubernetes#9170]
Currently the ui dashboard seems broken. Am I doing something wrong?

![kube-ui](https://cloud.githubusercontent.com/assets/1787169/7952301/b316cf68-0968-11e5-8a63-2236d6acfe6c.png)

As it's making requests to /api/v1beta2 and a quick grep shows:
```
➜  www git:(master) grep -r 'v1beta2' .
./app/assets/js/app.js:         "k8sApiServer": "/api/v1beta2",
./master/shared/config/development.json:  "k8sApiServer": "/api/v1beta2",
./master/shared/config/generated-config.js:             "k8sApiServer": "/api/v1beta2",
```

So this is part of #8087. Is it possible for us to bump these versions @preillyme @bcbroussard ?

**Comment by bgrant0607** [comment]
Hmm. v1beta3 support was added, but I'm not sure why the v1beta2 support is still there.
```
		"k8sApiServer": "/api/v1beta2",
		"k8sApiv1beta3Server": "/api/v1beta3",
```
cc @jackgr 

Yes, we should eliminate v1beta2 references.

cc @caesarxuchao @krousey

**Comment by bcbroussard** [comment]
@bgrant0607 I'll have a fix for this shortly

**Comment by bgrant0607** [comment]
Thanks, @bcbroussard.
