### ISSUE TITLE
gendocs is demanding I regenerate docs, and is changing - to . in flag names.

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#9173]
-      --api-version="": The API version to use when talking to the server
-      --certificate-authority="": Path to a cert. file for the certificate authority.
-      --client-certificate="": Path to a client key file for TLS.
-      --client-key="": Path to a client key file for TLS.
+      --api.version="": The API version to use when talking to the server
+      --certificate.authority="": Path to a cert. file for the certificate authority.
+      --client.certificate="": Path to a client key file for TLS.
+      --client.key="": Path to a client key file for TLS.

@eparis did something change here?  Did we import a new cobra today?

**Comment by eparis** [comment]
I didn't touch cobra...   let me look.

**Comment by eparis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8026

Was the last time we touched cobra/pflag

**Comment by eparis** [comment]
and HEAD is working fine for me. Do you need to make clean to get rid of Godeps/_workspace/pkg?

**Comment by eparis** [comment]
also 5eae2378d6ef71d7125c59a5fdb452a3591753ff was the last time we used a '.' in the util.WordSepNormalizeFunc...   which should be gone in head...

**Comment by thockin-cc** [comment]
Weird.  It stopped happening.  Weird.
