### ISSUE TITLE
remove characters unhandled by go templates from labels

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#9185]
Even though ```k8s-app``` and ```kubernetes.io/cluster-service``` are valid labels, they cannot be queried by ```kubectl get -o template:

```
error: error parsing template {{range.items}}{{.metadata.name}}@{{.metadata.labels.kubernetes.io/name}} {{end}}, template: output:1: bad character U+002F '/'
error: error parsing template {{range.items}}{{.metadata.name}}@{{.metadata.labels.k8s-app}} {{end}}, template: output:1: bad character U+002D '-'
```

(Or maybe there is a way to quote / and -?)

I suggest changing the labels to make better users experience.

**Comment by marekbiskup** [comment]
cc @satnam6502 @zmerlynn

**Comment by satnam6502** [comment]
I think @thockin originally dreamed up these names? Do we have a policy for legal characters for label keys and values?

**Comment by thockin** [comment]
a) Go's template language is atrocious
b) Go's template language does not handle anything but trivial indexing
c)
http://stackoverflow.com/questions/24267608/how-to-print-the-value-of-a-key-containing-dots

I can't even make 'index' work.

kubectl get pods -o template -t '{{range .items}}{{index .metadata.labels
"run"}}{{end}}'  gives me a zero-value error

**Comment by BenTheElder** [comment]
Relevant Issue: https://github.com/GoogleCloudPlatform/kubernetes/issues/4348 and PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/8858 should be landing a different template language implementation this summer.

**Comment by daizuozhuo** [comment]
The PR: #9296 has solved this problem. Please have a look at it.

**Comment by marekbiskup** [comment]
I'm closing this issue. the `/` character in labels is a design decision and we don't want to change it.
And now we have other template languages, as @daizuozhuo said.
