### ISSUE TITLE
GCE-PD times out @ 10s, and then just keeps retrying to attach...

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#9190]
GCE-PD attempts to attach the PD.  If that call goes long, the RPC times out, but the call can eventually succeed.

We don't check if the PD is already attached before we try to attach again, that attach fails (since it's already attached) and we just loop on trying to attach and failing.

**Comment by swagiaal** [comment]
Hmm.. it looks like the attach check here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/gce/gce.go#L643 is never reached. If the disk is already attached the gce attach call just succeeds and the volume is mounted if it attached as READ_ONLY when Attach call is requesting READ_WRITE the call still succeeds but the pod is not able to mount the volume, and the loop keeps going forever.

**Comment by brendandburns** [comment]
Closing this, as I believe it is fixed by 9542, will re-open if it re-occurs.
