### ISSUE TITLE
k8s-bot and @bgrant0607 have the same Github icon

### ISSUE THREAD

**Issue by davidopp** [GoogleCloudPlatform/kubernetes#9198]
It's a little confusing.

**Comment by bgrant0607** [comment]
Previously my icon was unrecognizable, IMO, so it's a strict improvement over the default one.

**Comment by davidopp** [comment]
I wasn't suggesting any specific solution, other than implying that one of the icons should be changed.

**Comment by pmorie** [comment]
Change the k8s-bot's icon to @bgrant0607's face, then they will be
different.  :-|

**Comment by vmarmol** [comment]
@pmorie lol

**Comment by erictune** [comment]
How do we know that the k8s-bot and bgrant0607 *are* different?

**Comment by dchen1107** [comment]
Thanks Eric to poke this thread, otherwise I would miss such good joke. @pmorie Support you!

**Comment by bgrant0607** [comment]
Fixed.

**Comment by davidopp** [comment]
LOL!

**Comment by pmorie** [comment]
@bgrant0607 :trophy: :trollface:
