### ISSUE TITLE
Secrets and EmptyDir E2E are broken in master

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#9208]
With SELinux enforcing and in permissive mode, I always get the following:

```
• Failure [20.087 seconds]
Secrets
/home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/secrets.go:100
  should be consumable from pods [It]
  /home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/secrets.go:99

  "content of file \"/etc/secret-volume/data-1\": value-1" in container output
  Expected
      <string>: 
  to contain substring
      <string>: content of file "/etc/secret-volume/data-1": value-1

  /home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:633
------------------------------
SSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] Secrets [It] should be consumable from pods 
/home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:633

Ran 1 of 68 Specs in 20.088 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 67 Skipped --- FAIL: TestE2E (20.09s)

• Failure [20.067 seconds]
EmptyDir volumes
/home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/empty_dir.go:69
  should support r/w on tmpfs [It]
  /home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/empty_dir.go:68

  "mount type of \"/test-volume\": tmpfs" in container output
  Expected
      <string>: 
  to contain substring
      <string>: mount type of "/test-volume": tmpfs

  /home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:633
------------------------------
SSSSSSSSSSSSSSSSSSSSSSS

Summarizing 2 Failures:

[Fail] EmptyDir volumes [It] volume on tmpfs should have the correct mode 
/home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:633

[Fail] EmptyDir volumes [It] should support r/w on tmpfs 
/home/pmorie/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:633

Ran 2 of 68 Specs in 40.142 seconds
FAIL! -- 0 Passed | 2 Failed | 0 Pending | 66 Skipped --- FAIL: TestE2E (40.15s)

```

**Comment by pmorie** [comment]
@jayunit100

**Comment by jayunit100** [comment]
@timothysc

**Comment by timothysc** [comment]
what do events and kubelet logs say?

**Comment by pmorie** [comment]
I would look for mount failures in the kubelet logs.

**Comment by jayunit100** [comment]
Note that this    failure is breaking networking e2e's and others as well.

**Comment by bgrant0607** [comment]
Which e2e tests specifically are failing?

@erictune

**Comment by erictune** [comment]
@bgrant0607 Since SELinux is mentioned, I think this must be a redhat-owned e2e.

**Comment by jayunit100** [comment]
Fwiw I think the break is recent . Iirc networking was passing yesterday from head.

**Comment by pmorie** [comment]
I'm going to dig into this one tonight, since I have to make a code change to the emptyDir plugin and this has to be fixed first.

**Comment by timothysc** [comment]
Something destabilizing has occurred, below is the complete set of abnormal issues.  

It doesn't appear to be SELinux related, b/c it was disabled on this test run, still digging.   

[Fail] Networking [It] should function for intra-pod communication 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:136

[Fail] hostDir [It] MOD volume on tmpfs should have the correct mode 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Volumes [Skipped] GlusterFS [It] should be mountable 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/volumes.go:179

[Fail] Secrets [It] should be consumable from pods 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Pods [It] should contain environment variables for services 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Volumes [Skipped] NFS [It] should be montable 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/volumes.go:192

[Fail] Docker Containers [It] should be able to override the image's default commmand (docker entrypoint) 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Downward API [It] should provide pod name and namespace as env vars 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Docker Containers [It] should be able to override the image's default command and arguments 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] EmptyDir volumes [It] volume on tmpfs should have the correct mode 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Cadvisor [It] should be healthy on every node. 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cadvisor.go:77

[Fail] EmptyDir volumes [It] should support r/w on tmpfs 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Docker Containers [It] should use the image defaults if command and args are blank 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] hostDir [It] should support r/w on tmpfs 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

[Fail] Docker Containers [It] should be able to override the image's default arguments (docker cmd) 
/var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:645

**Comment by bgrant0607** [comment]
Is anything passing?

**Comment by jayunit100** [comment]
did e2e's pass this chaos, upstream ? if **yes** then i wonder wether maybe some change coupled functionality to a robust cloud provider  impl ?

**Comment by bgrant0607** [comment]
We run several sets of tests on GCE and GKE. The tests that have been reasonably stable are still stable, including:
```
export GINKGO_TEST_ARGS=" --ginkgo.skip=Skipped|Reboot|PD|Elasticsearch|identically\snamed\sservices|external\sload\sbalancer|Services.*Type\sgoes\sfrom|Services.*nodeport\ssettings "
export GINKGO_TEST_ARGS=" --ginkgo.skip=Skipped --ginkgo.focus=PD|Elasticsearch|identically\snamed\sservices|external\sload\sbalancer|Services.*Type\sgoes\sfrom|Services.*nodeport\ssettings "
export GINKGO_TEST_ARGS=" --ginkgo.focus=Reboot "
```

**Comment by bgrant0607** [comment]
I take it back. The e2e run that started around 7pm PST just failed with similar symptoms.

**Comment by pmorie** [comment]
@bgrant0607 Interesting -- which commits were new in that run?

**Comment by pmorie** [comment]
Maybe that can give us a range to bisect

**Comment by bgrant0607** [comment]
No new commits.

**Comment by bgrant0607** [comment]
Just a minute.

**Comment by bgrant0607** [comment]
#9211

cc @lavalamp

**Comment by bgrant0607** [comment]
There was one passing e2e run with #9211, actually. There were no changes in the failing run AFAICT.

**Comment by bgrant0607** [comment]
Running e2e with #9232 now.

**Comment by pmorie** [comment]
@bgrant0607 I think that more than one issue is in play -- which tests failed in your internal run?

I would believe that #9211 affects the services test, but I don't think it would affect emptyDir.

I'm going to dig into this locally and try to debug the emptyDir e2e -- I think that will lead us to the root cause of secrets and the networking e2e (potentially) as well.

**Comment by pmorie** [comment]
Interesting, I just got green on emptyDir locally.

**Comment by pmorie** [comment]
Also, #9211 was committed too late to be the root cause of the secrets failures we saw earlier.  Both @jayunit100 and I had failures at around 12:00 pacific time.

**Comment by pmorie** [comment]
Interesting, got a clean secrets run just now too.

**Comment by bgrant0607** [comment]
I wonder if it's a problem with an image (someone had pushed a bad DNS image on Monday) or access to the docker registry or somesuch.

**Comment by bgrant0607** [comment]
Kubernetes e2e suite.hostDir should support r/w on tmpfs
Kubernetes e2e suite.Docker Containers should use the image defaults if command and args are blank
Kubernetes e2e suite.Secrets should be consumable from pods
Kubernetes e2e suite.EmptyDir volumes should support r/w on tmpfs
Kubernetes e2e suite.Docker Containers should be able to override the image's default commmand (docker entrypoint)
Kubernetes e2e suite.Cadvisor should be healthy on every node.
Kubernetes e2e suite.Docker Containers should be able to override the image's default command and arguments
Kubernetes e2e suite.Pods should contain environment variables for services
Kubernetes e2e suite.ServiceAccounts should mount an API token into pods
Kubernetes e2e suite.EmptyDir volumes volume on tmpfs should have the correct mode
Kubernetes e2e suite.Docker Containers should be able to override the image's default arguments (docker cmd)
Kubernetes e2e suite.Downward API should provide pod name and namespace as env vars

**Comment by pmorie** [comment]
@bgrant0607 I'm going to kick off a full local run, will post results.

**Comment by bgrant0607** [comment]
What I see in a successful run:
```
STEP: Trying to get logs from node e2e-gce-minion-p5ug pod pod-secrets-4babd86d-0a57-11e5-b6c8-42010af01555 container secret-test: <nil>
STEP: pod logs:mode of file "/etc/secret-volume/data-1": -r--r--r--
content of file "/etc/secret-volume/data-1": value-1
```
What I see in the failed run:
```
STEP: Trying to get logs from node e2e-gce-minion-iond pod pod-secrets-cddd3a94-0a5f-11e5-bbd3-42010af01555 container secret-test: <nil>
STEP: pod logs:
```

**Comment by bgrant0607** [comment]
The pod logs line is blank for every failing test.

**Comment by bgrant0607** [comment]
The e2e run in progress does not exhibit this problem.

**Comment by bgrant0607** [comment]
The e2e run passed.

**Comment by bgrant0607** [comment]
#9155 was merged 22 hours ago. Does that timeframe fit?

**Comment by bgrant0607** [comment]
2 successful e2e runs.

**Comment by pmorie** [comment]
@bgrant0607 So, do I understand correctly that the internel jenkins had a single broken run, then 3 more successful runs after that?

**Comment by pmorie** [comment]
@bgrant0607 re: #9155 I cannot timeframe it personally as I have been focusing on OpenShift related matters pretty hard the last few days except for code reviews for kube.

@jayunit100 does the timeframe around #9155 line up with your observations?  When did you first notice these breaks?

This is reminding me of a number of e2e issues I wanted to create -- will peel those off.

**Comment by bgrant0607** [comment]
@pmorie Yes, only a single broken run with the symptoms discussed in this issue.

**Comment by pmorie** [comment]
Interesting @bgrant0607 - my machine got into a weird state and I didn't
trust my first results (many failures, FTR). I'm re-running now.

**Comment by pmorie** [comment]
This is cleaner:

**Comment by pmorie** [comment]
I'm probably going to dig into some of these failures more tomorrow and see if I can get some more breaks like we saw today.  If it calms down tomorrow, I'll close this out.

**Comment by pmorie** [comment]
Don't think this needs to be p0 anymore, @bgrant0607.

**Comment by timothysc** [comment]
well emptyDir is passing this a.m. 

I'm going to run the battery of tests and report.

**Comment by timothysc** [comment]
Most tests are green again, however it appears that introspective services now has a new implied semantic out of the gate, so tests like Networking fail with the following error: 

"Unable to read service account token: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"

Are we now forcing security setup from stage 0?

**Comment by jayunit100** [comment]
EmptyDir still fails for me .  Something about the mount type not being of type tmpfs.

http://paste.fedoraproject.org/228932/14334348/

```
  [91m"mount type of \"/test-volume\": tmpfs" in container output
  Expected
      <string>: mount type of "/test-volume": 61267
      content of file "/test-volume/test-file": mount-tester new file
     
      mode of file "/test-volume/test-file": -rw-r--r--
     
  to contain substring
      <string>: mount type of "/test-volume": tmpfs[0m
```

**Comment by jayunit100** [comment]
Ah. looks like **DOCKER VERSION** is an important factor here.  I found that by updating my docker version fixed  everything the EmptyDir issue.

**Comment by bgrant0607** [comment]
FYI @quinton-hoole

**Comment by timothysc** [comment]
We're still trying to sus-out why Jay's setup is magically fixed and our Atomic Cluster still shows the error.

**Comment by timothysc** [comment]
So we've traced down the issue to a silently failed mount on atomic for the secrets (#7101).  There are no log issues what so ever, but when we docker inspect a pass/fail it pops out clear as day. 

Passing (Jay): 
"VolumesRW": {
        "/dev/termination-log": true,
        "/var/run/secrets/kubernetes.io/serviceaccount": false
    }

Failing (Mine-Atomic): 
"VolumesRW": {
        "/dev/termination-log": true
    },

logs:  Unable to read service account token: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

well derp-derp b/c it's not there.  They question is why?  and why no error.?.?

**Comment by timothysc** [comment]
I think we may have rooted the last issue... details here: https://bugzilla.redhat.com/show_bug.cgi?id=1229319

**Comment by timothysc** [comment]
@pmorie @eparis - I'm still getting the same silent mount failure on atomic 7.1.3 ...

**Comment by timothysc** [comment]
So it seems that the reason it doesn't fail in my case, is defaults have changed around service-accounts which appear to have been updated for other configs, but on wide-open default there is no mount, but tests expect them on startup.  

@jayunit100, @rrati.  

Please close... we'll open other issues as needed.  

This is a bug imho, but we'll root them out 1 by 1.

**Comment by pmorie** [comment]
Closing out.
