### ISSUE TITLE
Docs: container-environment.md should link to or include downward_api.md

### ISSUE THREAD

**Issue by jeffmendoza** [GoogleCloudPlatform/kubernetes#9220]
[container-environment.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/container-environment.md) should link to, or possibly be merged with [downward_api.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/downward_api.md). These are both applicable to someone getting started and or porting an app to kubernetes, who need to figure out what metadata is available from the environment.

**Comment by bgrant0607** [comment]
cc @pmorie

**Comment by RichieEscarez** [comment]
#10130 (related to downward API)

**Comment by bgrant0607** [comment]
cc @thockin, since he's working on #10130

**Comment by pmorie** [comment]
@jeffmendoza Good suggestion -- apologies for the latency, it has been a crazy summer and I'm still digging out.

**Comment by pmorie** [comment]
@jeffmendoza I made an initial mention of this in #12056, PTAL

**Comment by jeffmendoza** [comment]
Nice!

**Comment by jeffmendoza** [comment]
Looks like it's merged, closing
