### ISSUE TITLE
Configure an array of replication controllers/pods in a single json/yaml file

### ISSUE THREAD

**Issue by sanjana-bhat** [GoogleCloudPlatform/kubernetes#9231]
Hi All,

Does k8s support configuring an array of rc/pods in a single json/yaml file?

Thanks,
Sanjana

**Comment by jsdir** [comment]
I don't know where the documentation is for this, but there appears to be a `List` kind that defines multiple `items`.

https://github.com/GoogleCloudPlatform/kubernetes/blob/51a4e08ebd4938db6ef7c0bcce26b7fb21bb8248/docs/secrets.md#use-case-pods-with-prod--test-credentials

**Comment by sanjana-bhat** [comment]
@jsdir, thanks for a quick turnaround!
