### ISSUE TITLE
'kubectl get nodes' returns unknown command

### ISSUE THREAD

**Issue by adyanthaya17** [GoogleCloudPlatform/kubernetes#9237]
Hi, I'm following the ubuntu.md document to build my kubernetes node, having both master and minion configured in same node and another minion node but I'm getting an error while I run the below command:

$kubectl get nodes
 NAME            LABELS                                 STATUS
10.x.x.x   kubernetes.io/hostname=10.x.x.x   Ready
10.x.x.y   kubernetes.io/hostname=10.x.x.y   NotReady

The 10.x.x.y is the separate minion node. I haven't set the bridge utils yet, is that the reason it's unable to fetch the state?

**Comment by adyanthaya17** [comment]
Okay, so it seemed it was because the Docker wasn't installed on my machine. But I do have a further question. When I add another minion node to the set up, during the kubectl get nodes the node states as NotReady.

**Comment by quinton-hoole** [comment]
Have you looked in /var/log/kube-kubelet.* on 10.x.x.y for errors?

**Comment by WIZARD-CXY** [comment]
@adyanthaya17. You must install bridge-util to get docker use flannel network. Maybe there are other problems. A look at the kubelet log will be helpul

**Comment by adyanthaya17** [comment]
Hi, thank you for the responses. So I reinstalled the ubuntu kubernetes setup of master and minion node. I have installed docker on both the nodes as it behaves as minion nodes. I have a new error this time.

When I run the command 'KUBERNETES_PROVIDER=ubuntu ./kube-up.sh', it reads as cluster validation succeeded. Even it's able to fetch the node state that reads 'Ready'.

The thing is when I issue the command 'kubectl get nodes' it comes as command not found. I'm issuing it in the directory that has kubectl but I have no clue what to do. All the services are up and running.

**Comment by WIZARD-CXY** [comment]
@adyanthaya17, you forget something in my guide. The `kubectl` binary should be in cluster/ubuntu/binary directory.You can put it into your `PATH` directory.So you can use

**Comment by adyanthaya17** [comment]
@WIZARD-CXY I did run the command in the specified directory. I have installed the same before and that time I didn't get this error and I could list the node states.

**Comment by WIZARD-CXY** [comment]
uhh, I'm a little confused, I need more info. Did you check the line 356 in utils.sh?

**Comment by adyanthaya17** [comment]
Yes, I did check it. It reads just like the document. 

 verify-cluster
  detect-master
  export KUBE_MASTER_IP="${KUBE_MASTER_IP}:8080"
  export CONTEXT="ubuntu"
  create-kubeconfig
}

**Comment by WIZARD-CXY** [comment]
Ah, I found it. Because someone has added the code and merged it today.https://github.com/GoogleCloudPlatform/kubernetes/pull/9227.Now it's broken.I will figure it how to fix it soon

**Comment by adyanthaya17** [comment]
A quick question, I installed and configured kubernetes files yesterday and it read everything was done i.e the environment is up and running. If I want to set up  from scratch what do I do? That is from getting repository and all that.

**Comment by WIZARD-CXY** [comment]
I don't understand... what do you mean by  That is from getting repository and all that??

**Comment by adyanthaya17** [comment]
The first step of the document is building kubernetes repository on your machine. As I have run the command 'KUBERNETES_PROVIDER=ubuntu ./kube-up.sh' all my services are up and running. To stop the services I can use 'KUBERNETES_PROVIDER=ubuntu ./kube-down.sh' but I want to remove all the services, configuration from the machine for a fresh building of kubernetes.

**Comment by jlowdermilk** [comment]
Apologies, I broke this with #9227. Sending fix now.

**Comment by WIZARD-CXY** [comment]
I am going to fix it today so leave it to you😃

**Comment by adyanthaya17** [comment]
The issue of kube-up.sh seems to be fixed by adding 2 lines to the code file though I'm still facing the issue where I'm unable to list the nodes by using 'kubectl get nodes'. I'm issuing this command in /kubernetes/cluster/ubuntu/binaries where the kubectl is located. This is what I have:

Kubernetes cluster is running.  The master is running at:
http://10.x.x.x

Using master 10.x.x.x
... calling validate-cluster
Found 2 nodes.
        NAME            LABELS                                 STATUS
     1  10.x.x.x   kubernetes.io/hostname=10.x.x.x   Ready
     2  10.x.x.y   kubernetes.io/hostname=10.x.x.y   Ready

Validate output:
NAME                 STATUS    MESSAGE   ERROR
controller-manager   Healthy   ok        nil
scheduler            Healthy   ok        nil
etcd-0               Healthy   {"action":"get","node":{"dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3},{"key":"/coreos.com","dir":true,"modifiedIndex":8,"createdIndex":8}]}}
                     nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://10.x.x.x:8080

When I issue the command:
$ kubectl get nodes
kubectl: command not found

**Comment by adyanthaya17** [comment]
Another thing here is previously when I issued the command 'ifconfig' I was able to see my docker network but once I ran the 'kube-up.sh' command the docker network wasn't present on both the master and minion node but only the flannel network was added.

**Comment by jlowdermilk** [comment]
```
$ kubectl get nodes
kubectl: command not found
```
You need to put the `kubectl` binary somewhere on your path. Distro-specific binaries are included in the [official release tars](https://github.com/GoogleCloudPlatform/kubernetes/releases), or you can build it from the repo by running `hack/build-go.sh`.

**Comment by adyanthaya17** [comment]
I ran the command in /kubernetes/cluster/ubuntu/binaries and also tried by moving the kubectl to a different PATH. I ran the command in the /kubernetes/hack directory but I' facing error there.

$ ./build-go-sh 

Can't find 'go' in PATH, please fix and retry.See http://golang.org/doc/install for installation instructions.

!!! Error in /home/appaad/kubernetes/hack/lib/golang.sh:438

**Comment by WIZARD-CXY** [comment]
@jlowdermilk It seems the changes to ubuntu was not enough. Other things will fail. I will try to fix it today.

**Comment by adyanthaya17** [comment]
Hi, is there another way to fix the kubectl command issue here.

**Comment by jlowdermilk** [comment]
According to @WIZARD-CXY this was (actually-for-real-this-time) fixed with #10005. Have you tried it with a recent build?

**Comment by WIZARD-CXY** [comment]
yeah , I confirmed

May the force be with you

**Comment by adyanthaya17** [comment]
@jlowdermilk Yes I did check with the recent build. The /ubuntu/util.sh file was added with lines but the results seems the same. I even rebuild the kubernetes on a new node to check it.

**Comment by adyanthaya17** [comment]
I followed the following steps:
### Linux
$ wget https://storage.googleapis.com/kubernetes-release/release/v0.17.0/bin/linux/amd64/kubectl
$ chmod +x kubectl
$ mv kubectl /usr/local/bin/

And then I executed the command:
$ kubectl get nodes
NAME            LABELS                                 STATUS
10.x.x.x   kubernetes.io/hostname=10.x.x.x   NotReady
10.x.x.y   kubernetes.io/hostname=10.x.x.y   NotReady

I'm confused right now. When I ran the command kube-up.sh the final steps of it read like this:

Using master 10.x.x.x
... calling validate-cluster
Found 2 nodes.
NAME LABELS STATUS
1 10.x.x.x kubernetes.io/hostname=10.x.x.x Ready
2 10.x.x.y kubernetes.io/hostname=10.x.x.y Ready

Validate output:
NAME STATUS MESSAGE ERROR
controller-manager Healthy ok nil
scheduler Healthy ok nil
etcd-0 Healthy {"action":"get","node":{"dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3},{"key":"/coreos.com","dir":true,"modifiedIndex":8,"createdIndex":8}]}}
nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://10.x.x.x:8080

If the state is reading ready why is it giving NotRead state while I make use of kubectl command.

**Comment by WIZARD-CXY** [comment]
weird, never happend in my lab.Try to use a 0.18.2 kubectl if your server side is using 0.18.2.It should located in cluster/ubuntu/binaries

**Comment by adyanthaya17** [comment]
Previously I had built the kubernetes repo and then had manually downloaded the kubectl, I re-did it by first manually downloading the kubectl and then building the kubernetes repo. I'm able to fetch the state that's reading ready state.

**Comment by adyanthaya17** [comment]
I restarted my machine and ran the kubectl get command but the master node status reads as 'NotReady' state.

**Comment by adyanthaya17** [comment]
The master node goes to 'NotReady' state just after five minutes of bringing up the cluster and setting up master and minion node.
