### ISSUE TITLE
Vagrant hanging on adding SaltStack's COPR repository

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/kubernetes#9241]
With `KUBERNETES_PROVIDER=vagrant`, `go run hack/e2e.go -v -up -test` the provisioning hangs on:
`==> master:  *  INFO: Adding SaltStack's COPR repository`

I've had this happen multiple times now, the current time has been hung for about 15 minutes while I attempted to debug and search for similar issues. I can `vagrant ssh master` from another shell but the one running e2e is just sitting on a blank line following that. 

Running `top` over ssh shows very little resource usage. Pinging 8.8.8.8 works so networking is up.
On the host machine ruby shows as using 0% cpu.

Not sure what's going on here, but I can't spin up a cluster currently because of it.

**Comment by derekwaynecarr** [comment]
I think there were problems with the fedora mirrors this evening.  Hope it clears up soon.

**Comment by derekwaynecarr** [comment]
If it continues to hang, I will look to alternate mechanisms to bootstrap salt

**Comment by derekwaynecarr** [comment]
Were you running with this PR (not yet merged)

https://github.com/GoogleCloudPlatform/kubernetes/pull/9093

Trying to see if your issue was with fedora 20 or 21 mirrors.

**Comment by derekwaynecarr** [comment]
I just tried this morning at 10:57AM EST and the Salt repositories are functional again.

Closing, reopen if you see the issue again.

**Comment by BenTheElder** [comment]
Sorry, yes, just tested and they appear to be working again for me as well.

**Comment by mattmb** [comment]
Seeing the same thing here.
```
export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash
```

This seems to be hanging: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L2593

Just going to try on fedora 21

**Comment by mattmb** [comment]
Now failing on the first call to yum `yum install -y openvswitch bridge-utils`
```
Config time: 0.004
Yum version: 3.4.3
rpmdb time: 0.000
Setting up Package Sacks
Using older repomd.xml
  Latest: Tue Jun  9 08:15:48 2015
  Using: Wed Jun 10 08:00:24 2015
```
Or on a different network
```
master: Cannot retrieve metalink for repository: fedora/21/x86_64. Please verify its path and try again
```
Are we doing anything non default with yum? Or are the repositories it happens to be selecting for me just broke?
