### ISSUE TITLE
What kind of load-balancing ?

### ISSUE THREAD

**Issue by Artenac2** [GoogleCloudPlatform/kubernetes#9243]
I work for two weeks on Kubernetes  now and i didn't find any informations about the kind of load-balancing.

I explain myself, I want to know if kubernetes uses round-robin or other kind of load-balancing specific.

Or if Kubernetes uses all load-balancer.

And how can we specify on a file ?

**Comment by jsdir** [comment]
Right now, Kubernetes only uses [round-robin load balancing in `kube-proxy`](https://github.com/GoogleCloudPlatform/kubernetes/blob/fdb44a9ad23fec1525ae92e5b2f80bc605be3a79/docs/design/architecture.md#kube-proxy).

**Comment by Artenac2** [comment]
And will they implement other load-balancers or they will stay on the round-robin idea?

**Comment by thockin** [comment]
It's round robin, with optional session affinity. It may change to a
simpler probabilistic model soon (still with affinity). We don't have plans
to do anything else at the moment, though we are not against it. Do you
have real requirements?

**Comment by Artenac2** [comment]
For now, I have not real requirements but round robin with, for example, a database container with some replicas, it can be weird, right ? Even if I know a database container with some replicas can be weird too, it just an example for understand.

**Comment by thockin** [comment]
You can use ClientIP for session affinity, so that repeated connections
(within a time window) will get the same backend.

**Comment by Artenac2** [comment]
Thanks for help.
