### ISSUE TITLE
[usability-issue] kubectl commands shows confusing line: Starting cluster using os distro ..

### ISSUE THREAD

**Issue by pramttl** [GoogleCloudPlatform/kubernetes#9246]
Example:

kubectl cluster-info shows a redundant line: `Starting cluster using os distro: ubuntu`
The cluster is already up, so the phrase "Starting cluster" is confusing in context of the command. (My kubernetes test cluster is running on AWS i.e. KUBERNETES_PROVIDER=aws. I had used kube-up.sh to create a test kubernetes cluster on aws).  Log of my shell session:

```
pranjal:~$ kubectl cluster-info
Starting cluster using os distro: ubuntu
Kubernetes master is running at https://<ip-hidden>
Elasticsearch is running at https://<ip-hidden>/api/v1beta3/proxy/namespaces/default/services/elasticsearch-logging
Kibana is running at https://<ip-hidden>/api/v1beta3/proxy/namespaces/default/services/kibana-logging
KubeDNS is running at https://<ip-hidden>/api/v1beta3/proxy/namespaces/default/services/kube-dns
```

**Comment by justinsb** [comment]
Thanks for the bug report @pramttl; I've filed a PR to fix it.
