### ISSUE TITLE
[feature-suggestion] [kubectl] Ability to filter "kubectl get <resource>"  output to show only select columns

### ISSUE THREAD

**Issue by pramttl** [GoogleCloudPlatform/kubernetes#9247]
`kubectl get <resource_name>` prints all the resource info as a table by default. Sometimes there is just too much data and one row of the table is not able to fit in one line. It takes time to comprehend that entire output. It may be particularly useful to restrict columns by name. So for example in context of resource pod, something like..

`kubectl get pods --filter names`

that would only pod names instead of an entire table containing all columns like POD, HOST, STATUS, CREATED, etc. would be particularly useful.

Exact interface for this might need to be discussed and planned on a wiki. (I'll try to update this issue with a more detailed suggest if I can think of something)

**Comment by pramttl** [comment]
For now I realized I can do something like `kubectl get pods |  awk '{print $1}'` to get the column name I want (i.e. just the name of the pods in this case)

**Comment by thockin** [comment]
This is actually in progress.  #7843

**Comment by bgrant0607** [comment]
Are you aware of `-o template`?

**Comment by bgrant0607** [comment]
See also discussion in #7843

**Comment by pramttl** [comment]
@bgrant0607: Yeah I know the `-o template`. (I have just used the `-o json` format till now)

Looks like #7843 is exactly what I reported (as @thockin pointed out) , so this is duplicate then, closing issue.
