### ISSUE TITLE
[feature-suggestion] [kubectl] Regex based filtering instead of requiring exact name of resource

### ISSUE THREAD

**Issue by pramttl** [GoogleCloudPlatform/kubernetes#9248]
Example:
One of the pods running on my cluster is `elasticsearch-logging-v1-n0hpm`.

Let's say i want to get information about this pod, then I have to type:

    kubectl describe pods elasticsearch-logging-v1-n0hpm

If the following command also did the job, then that would be a great feature:

    kubectl describe pods elasticsearch

That would save a lot of time.  Like vagrant uses regular expressions in its CLI. `vagrant ssh master` is enough to ssh into a server that may be called *master-helloworld*. If there are multiple outputs then an  error can be shown, listing all the resources that match, or simply all resources can be described.

**Comment by thockin** [comment]
This is what labels are for!

`kubectl get pods -l app=elasticsearch`

Unfortunately `describe` does not do labels because it expects a single
response.  This might be a reasonable extension to make - more than 1
object in describe or taking the first of a selector or something.

**Comment by bgrant0607** [comment]
+1. Use labels. I think describe does take labels now.

**Comment by nikhiljindal** [comment]
kubectl describe does not support -l.

I just ran ```kubectl describe pods frontend``` and it gave me the description of all pods with name frontend* in my cluster.
@pramttl Is that not the case for you?

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9705 is adding support for -l in kubectl describe

**Comment by bgrant0607** [comment]
Closing since label selection is the preferred approach.

**Comment by thockin** [comment]
It would be nice to prefix-match like docker does with IDs.
