### ISSUE TITLE
services/kibana-logging API endpoint broken: Error: 'dial tcp 10.244.2.5:5601: connection refused

### ISSUE THREAD

**Issue by pramttl** [GoogleCloudPlatform/kubernetes#9268]
Endpoint: `/api/v1beta3/proxy/namespaces/default/services/kibana-logging`
(I am not sure if the endpoint is broken but it seems so)

I entered `kubectl cluster-info'. The output had the following line:

```
Kibana is running at https://52.26.73.41/api/v1beta3/proxy/namespaces/default/services/kibana-logging
```

When I access the URL [above](https://52.26.73.41/api/v1beta3/proxy/namespaces/default/services/kibana-logging). I still get the output:

```
Error: 'dial tcp 10.244.2.5:5601: connection refused'
Trying to reach: 'http://10.244.2.5:5601/'
```

The IP `10.244.2.5` seems to be hardcoded somewhere. Even though my master node IP is changed, the hardcoded IP is being accessed (possibly) causing this ERROR.

**Comment by quinton-hoole** [comment]
cc @satnam6502

**Comment by satnam6502** [comment]
Using a fairly recent build I have no problem accessing either Elasticsearch or Kibana for logging.
Did you wait until the status of both the Elasticsearch and Kibana pods were `Running` before connecting?

```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.0-377-ga1c2641b536c12-dirty", GitCommit:"a1c2641b536c123abfd0ae1d848910af2578cddf", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.0-377-ga1c2641b536c12-dirty", GitCommit:"a1c2641b536c123abfd0ae1d848910af2578cddf", GitTreeState:"dirty"}
```

**Comment by satnam6502** [comment]
Is this still an issue? If not then please can this issue be closed?

**Comment by quinton-hoole** [comment]
Re-open if necessary.
