### ISSUE TITLE
Vagrant with Virtualbox: Error when minion is being registered with cloud provider

### ISSUE THREAD

**Issue by fahadpolash** [GoogleCloudPlatform/kubernetes#9270]
Hello,

I am getting the following error:
Wrote config for vagrant to /home/nio/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
......
Waiting for each minion to be registered with cloud provider
Error: an error on the server has prevented the request from succeeding (get nodes)

**Comment by quinton-hoole** [comment]
Hi 

Have you looked in /var/log/kube-nodecontroller.* for error messages?

**Comment by fahadpolash** [comment]
Nothing is there.

[vagrant@kubernetes-master ~]$ cat /var/log/kube-controller-manager.log 
[vagrant@kubernetes-master ~]$ 
[vagrant@kubernetes-master ~]$

**Comment by derekwaynecarr** [comment]
Are you using virtual box?
Are you running from HEAD or an older release?

There were 2 fixes to the vagrant setup this week.  One to fix Kubelet registration on nodes (which required a code changes in cloud provider and may result in errors on earlier release versions), and another to move to Fedora 21 and Docker 1.6.

At HEAD, vagrant should be stable today.  I spun machines up and down multiple times today using VirtualBox.

**Comment by BenTheElder** [comment]
I saw the cluster fail to create twice after updating due to problems with the mirrors seemingly earlier this evening, but it seems to be working now.

However there have been a number of warnings and errors:
````
==> minion-2: Downloading packages:
==> minion-2: warning: /var/cache/yum/x86_64/21/fedora/packages/bridge-utils-1.5-10.fc21.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 95a43f54: NOKEY
==> minion-2: Public key for bridge-utils-1.5-10.fc21.x86_64.rpm is not installed
==> minion-2: Public key for openvswitch-2.3.1-3.git20150327.fc21.x86_64.rpm is not installed
==> minion-2: --------------------------------------------------------------------------------
==> minion-2: Total                                              1.3 MB/s | 1.9 MB  00:01     
==> minion-2: Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-21-x86_64
==> minion-2: Importing GPG key 0x95A43F54:
==> minion-2:  Userid     : "Fedora (21) <fedora@fedoraproject.org>"
==> minion-2:  Fingerprint: 6596 b8fb abda 5227 a9c5 b59e 89ad 4e87 95a4 3f54
==> minion-2:  Package    : fedora-repos-21-2.noarch (@anaconda)
==> minion-2:  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-21-x86_64
==> minion-2: Running transaction check
==> minion-2: Running transaction test
==> minion-2: Transaction test succeeded
==> minion-2: Running transaction (shutdown inhibited)
==> minion-2:   Installing : openvswitch-2.3.1-3.git20150327.fc21.x86_64                  1/2
==> minion-2:  
==> minion-2:   Installing : bridge-utils-1.5-10.fc21.x86_64                              2/2
==> minion-2:  
==> minion-2:   Verifying  : bridge-utils-1.5-10.fc21.x86_64                              1/2
==> minion-2:  
==> minion-2:   Verifying  : openvswitch-2.3.1-3.git20150327.fc21.x86_64                  2/2
==> minion-2:  
==> minion-2: 
==> minion-2: Installed:
==> minion-2:   bridge-utils.x86_64 0:1.5-10.fc21                                             
==> minion-2:   openvswitch.x86_64 0:2.3.1-3.git20150327.fc21                                 
==> minion-2: Complete!
==> minion-2: Created symlink from /etc/systemd/system/multi-user.target.wants/openvswitch.service to /usr/lib/systemd/system/openvswitch.service.
==> minion-2: Create a new docker bridge
==> minion-2: Cannot find device "cbr0"
==> minion-2: bridge cbr0 doesn't exist; can't delete it
==> minion-2: Add ovs bridge
==> minion-2: ovs-vsctl: 
==> minion-2: no bridge named obr0
==> minion-2: ovs-vsctl: no port named gre0
==> minion-2: Add tun device
==> minion-2: ovs-vsctl: no port named tun0
````

This happens on both minions when running `go run hack/e2e.go -v -up -test`
It seems to still be working though.

This is running on my [BenTheElder:iptables_proxy](https://github.com/BenTheElder/kubernetes/tree/iptables_proxy) branch but it's currently rebased up to master.

**Comment by derekwaynecarr** [comment]
I will look to hide the warning text. The not found bits were for ensuring the system did not have a previously configured sdn

**Comment by quinton-hoole** [comment]
@fahadpolash please re-open if you're still seeing the problems when sync'd to HEAD.

**Comment by fahadpolash** [comment]
I have used the latest release v0.18.1
https://github.com/GoogleCloudPlatform/kubernetes/releases

Still getting the same errors.

**Comment by derekwaynecarr** [comment]
Not release.  Literally the HEAD of source tree is your best bet right now.  I do not plan to back port changes to 18.1 branch.
