### ISSUE TITLE
Multiple e2e tests fail with "Missing service account" when run in parallel

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#9272]
Some examples below (from our Jenkins e2e continuous integration):

Docker Containers should be able to override the image's default command and arguments

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/docker_containers.go:81
Failed to create pod: Pod "client-containers-6bd82955-0ae5-11e5-9b61-42010af01555" is forbidden: Missing service account e2e-tests-containers-afbfc705-8f08-4d3a-8927-cff5845472f7/default: <nil>

=========

hostDir MOD volume on tmpfs should have the correct mode

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/host_path.go:75
Failed to create pod: Pod "pod-ed43f1af-0aea-11e5-8379-42010af01555" is forbidden: Missing service account e2e-tests-hostdir-2f80b7b2-0256-4246-8187-342aab3eda0f/default: <nil>

==================

Pods should be restarted with a docker exec "cat /tmp/health" liveness probe

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pods.go:451
creating pod liveness-exec
Expected error:
    <*errors.StatusError | 0xc208546d00>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "Pod \"liveness-exec\" is forbidden: Missing service account e2e-test-44eb32f3-0af7-11e5-b2d4-42010af01555/default: <nil>",
            Reason: "Forbidden",
            Details: {ID: "liveness-exec", Kind: "Pod", Causes: nil, RetryAfterSeconds: 0},
            Code: 403,
        },
    }
    Pod "liveness-exec" is forbidden: Missing service account e2e-test-44eb32f3-0af7-11e5-b2d4-42010af01555/default: <nil>
not to have occurred

**Comment by quinton-hoole** [comment]
There were a lot more of these overnight:

https://github.com/GoogleCloudPlatform/kubernetes/blob/a15c69798b1f01067ac07101c1d92c4a6d540d54/plugin/pkg/admission/serviceaccount/admission.go#L175

**Comment by quinton-hoole** [comment]
cc @lavalamp

**Comment by derekwaynecarr** [comment]
Cc @liggitt. - need to wait for service accounts before pods are admitted in test.

**Comment by liggitt** [comment]
@derekwaynecarr I thought you added that in beforeEach:
```
// beforeEach gets a client and makes a namespace.
func (f *Framework) beforeEach() {
	By("Creating a kubernetes client")
	c, err := loadClient()
	Expect(err).NotTo(HaveOccurred())

	f.Client = c

	By("Building a namespace api object")
	namespace, err := createTestingNS(f.BaseName, f.Client)
	Expect(err).NotTo(HaveOccurred())

	f.Namespace = namespace

	By("Waiting for a default service account to be provisioned in namespace")
	err = waitForDefaultServiceAccountInNamespace(c, namespace.Name)
	Expect(err).NotTo(HaveOccurred())
}
```

**Comment by liggitt** [comment]
oh, those tests create another namespace than the one in beforeEach

**Comment by lavalamp** [comment]
Wow, this is really unfortunate.

Can you just modify the createTestingNS to wait for the service account?

**Comment by liggitt** [comment]
sure... though I'd like to clean those up to use NewFramework instead as soon as there's time

**Comment by lavalamp** [comment]
Longer term, this is going to be a big usability issue unless we also make kubectl create namespace wait. There should be a "ready" field in the namespace (is there? I haven't looked; better yet, use the sequence number pattern), we should NOT make clients know this obscure detail to use the system.

**Comment by liggitt** [comment]
is that what the initializer concept is intended to do long-term?

**Comment by liggitt** [comment]
namespace has a status.phase, but that only tracks "active" and "terminating" right now, not "preparing"

**Comment by derekwaynecarr** [comment]
A namespace does have a phase of active or terminating.  This is really a use case for some type of initializers concept in future.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
@derekwaynecarr Yes, we really want an initializer for this. Pod creation shouldn't fail. The pod should just remain pending/inert until the service account exists.

**Comment by derekwaynecarr** [comment]
I think moving some stuff out of admission control and into object initializers is a high priority post 1.0.  In this case, it's a pod that is initialized and not the namespace in my view.  The namespace is ready right away - after all you can create other resource types besides a pod.

**Comment by liggitt** [comment]
> In this case, it's a pod that is initialized and not the namespace in my view

Agree. It would require doing things like allowing mutation of pod.spec until initialized, and controllers not acting on a pod with initializers remaining

**Comment by lavalamp** [comment]
Ah, I see. Yes, I agree, an initializer and/or kubelet should spin until the account becomes available.

**Comment by quinton-hoole** [comment]
@lavalamp, please label lgtm once you're happy with this PR.  I'm keen to merge as soon as you're happy.

**Comment by lavalamp** [comment]
looks like parallel jenkins is happy again.
