### ISSUE TITLE
Move all docs and examples to the v1 API

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/kubernetes#9286]
cc @caesarxuchao @nikhiljindal @RichieEscarez

**Comment by bgrant0607** [comment]
Forked from #7018

**Comment by bgrant0607** [comment]
Is there anything left to be done on this issue?

**Comment by caesarxuchao** [comment]
There are still 2 references to v1beta3 in the cassandra example. I will submit a patch.

**Comment by krousey** [comment]
@bgrant0607 I just did a quick pass and couldn't find anything in the examples. There's a few things in the getting started guides.

<pre>
> find docs/getting-started-guides -type f -exec grep -i -nHI -3 -e v1beta {} +
docs/getting-started-guides/mesos.md-149-```bash
docs/getting-started-guides/mesos.md-150-$ cat <<EOPOD >nginx.json
docs/getting-started-guides/mesos.md-151-{ "kind": "Pod",
docs/getting-started-guides/mesos.md:152:"apiVersion": "v1beta1",
docs/getting-started-guides/mesos.md-153-"id": "nginx-id-01",
docs/getting-started-guides/mesos.md-154-"desiredState": {
docs/getting-started-guides/mesos.md-155-  "manifest": {
docs/getting-started-guides/mesos.md:156:    "version": "v1beta1",
docs/getting-started-guides/mesos.md-157-    "containers": [{
docs/getting-started-guides/mesos.md-158-      "name": "nginx-01",
docs/getting-started-guides/mesos.md-159-      "image": "nginx",
--
docs/getting-started-guides/mesos.md-215-{
docs/getting-started-guides/mesos.md-216-  "id": "frontend",
docs/getting-started-guides/mesos.md-217-  "kind": "Service",
docs/getting-started-guides/mesos.md:218:  "apiVersion": "v1beta1",
docs/getting-started-guides/mesos.md-219-  "port": 9998,
docs/getting-started-guides/mesos.md-220-  "selector": {
docs/getting-started-guides/mesos.md-221-    "name": "frontend"
--
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-28-      printf '{
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-29-        "id": "%s",
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-30-        "kind": "Minion",
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml:31:        "apiVersion": "v1beta1",
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-32-        "labels": { "environment": "%s" }
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-33-        }' "${minion_id}" "${env_label}" \
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml-34-        | /opt/bin/kubectl create -s "${master_url}" -f -

</pre>

**Comment by bgrant0607** [comment]
Mesos is covered by #8957

**Comment by bgrant0607** [comment]
Azure is covered by #5799.

Closing this issue.
