### ISSUE TITLE
Delete outdated CHANGELOG

### ISSUE THREAD

**Issue by JeanMertz** [GoogleCloudPlatform/kubernetes#9313]
Wondering if it's just an oversight that the latest Git tag is `v0.18.1`, while the [CHANGELOG](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/CHANGELOG.md) file still points to 0.17 as the latest version?

I am using that file to track changes and know where to look out for when upgrading the cluster. Any other way (besides a regular commit diff) to keep in the loop of all the changes between versions?

**Comment by JeanMertz** [comment]
Answering myself: https://github.com/GoogleCloudPlatform/kubernetes/releases

**Comment by bgrant0607** [comment]
Yes, we should just delete that file, rather than maintaining 2 locations.

@RichieEscarez
