### ISSUE TITLE
IP address of service's public load balancer not returned by kubectl

### ISSUE THREAD

**Issue by evandbrown** [GoogleCloudPlatform/kubernetes#9329]
In 0.18.1 on Google Container Engine, I have a service with createExternalLoadBalancer=true. The load balancer is created and works as expected, but neither `kubectl get service` nor `kubectl describe service` include the LB IP. This worked in 0.17.1.

Output of `kubectl get service` (condensed to show relevant service):

```shell
NAME              LABELS                                                                           SELECTOR                    IP(S)           PORT(S)
...
nginx-ssl-proxy   name=nginx,role=ssl-proxy                                                        name=nginx,role=ssl-proxy   10.15.249.170   443/TCP
                                                                                                                                               80/TCP
```

Output of `kubectl describe service/nginx-ssl-proxy` (note the first 4 lines are a separate issue, #8636):

```shell
W0605 11:26:01.870978   45582 request.go:291] field selector: v1beta3 - events - involvedObject.name - nginx-ssl-proxy: need to check if this is versioned correctly.
W0605 11:26:01.871514   45582 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0605 11:26:01.871525   45582 request.go:291] field selector: v1beta3 - events - involvedObject.kind - Service: need to check if this is versioned correctly.
W0605 11:26:01.871533   45582 request.go:291] field selector: v1beta3 - events - involvedObject.uid - 7efc951b-0baf-11e5-94ff-42010af0de54: need to check if this is versioned correctly.
Name:			nginx-ssl-proxy
Labels:			name=nginx,role=ssl-proxy
Selector:		name=nginx,role=ssl-proxy
IP:			10.15.249.170
Port:			https	443/TCP
Endpoints:		https	10.12.1.4:443
Port:			http	80/TCP
Endpoints:		http	10.12.1.4:80
Session Affinity:	None
No events.
```

**Comment by thockin** [comment]
The version of kubectl must be stale.

```
$ k describe services/hostnames
W0605 11:46:25.069897   11184 request.go:291] field selector: v1beta3 -
events - involvedObject.namespace - default: need to check if this is
versioned correctly.
W0605 11:46:25.070009   11184 request.go:291] field selector: v1beta3 -
events - involvedObject.kind - Service: need to check if this is versioned
correctly.
W0605 11:46:25.070032   11184 request.go:291] field selector: v1beta3 -
events - involvedObject.uid - 11ef230b-04d0-11e5-8062-42010af0fd40: need to
check if this is versioned correctly.
W0605 11:46:25.070054   11184 request.go:291] field selector: v1beta3 -
events - involvedObject.name - hostnames: need to check if this is
versioned correctly.
Name: hostnames
Labels: run=hostnames
Selector: run=hostnames
Type: LoadBalancer
IP: 10.0.138.45
LoadBalancer Ingress: 130.211.149.1
Port: default 8675/TCP
NodePort: default 30689/TCP
Endpoints: 10.244.0.6:9376,10.244.1.7:9376,10.244.2.11:9376 + 2 more...
Session Affinity: None
No events.
```

Alternately, try `kubectl get -o yaml` for your service

**Comment by evandbrown** [comment]
I'm using the latest kubectl that comes with gcloud (just did `gcloud components update` to confimr):

```shell
kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.1", GitCommit:"befd1385e5af5f7516f75a27a2628272bb9e9f36", GitTreeState:"clean"}
```

Outputting yaml doesn't help:

```shell
- apiVersion: v1beta3
  kind: Service
  metadata:
    creationTimestamp: 2015-06-05T18:20:08Z
    labels:
      name: nginx
      role: ssl-proxy
    name: nginx-ssl-proxy
    namespace: default
    resourceVersion: "1774"
    selfLink: /api/v1beta3/namespaces/default/services/nginx-ssl-proxy
    uid: 7efc951b-0baf-11e5-94ff-42010af0de54
  spec:
    createExternalLoadBalancer: true
    portalIP: 10.15.249.170
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: nginx-ssl-proxy-https
    - name: http
      port: 80
      protocol: TCP
      targetPort: nginx-ssl-proxy-http
    selector:
      name: nginx
      role: ssl-proxy
    sessionAffinity: None
  status: {}
```

Maybe a stale `kubectl` bundled `gcloud`?

**Comment by bgrant0607** [comment]
The gcloud release cycle is different than our release cycle, unfortunately.

**Comment by evandbrown** [comment]
Thanks, Brian. Might make sense to pin the cluster version created by
gcloud rather than defaulting to latest, though I expect these types of
issues will be less frequent after 1.0. Thoughts?

**Comment by bgrant0607** [comment]
Not so simple, actually. Some discussion about this in #3955, #4855, and #5889.

**Comment by bgrant0607** [comment]
This issue is old, but I believe the high-level problem is still valid. Users need to pull the ingress IP out of the json/yaml:
http://kubernetes.io/v1.0/docs/user-guide/connecting-applications.html#exposing-the-service

**Comment by brendandburns** [comment]
This is no longer true (looks like it hasn't been true since https://github.com/GoogleCloudPlatform/kubernetes/pull/8707)

I will update the docs.

**Comment by bgrant0607** [comment]
Thanks for the doc update. However, I think it would be useful to distinguish between internal and public IPs explicitly, by using different columns.

**Comment by brendandburns** [comment]
ok, sg.

**Comment by bgrant0607** [comment]
Summarizing side conversation...

Current output looks like:
```
$ kubectl get services kube-dns --namespace=kube-system
NAME       LABELS       SELECTOR             IP(S)       PORT(S)
kube-dns   <none>       k8s-app=kube-dns     10.0.0.10   53/UDP
                                                         53/TCP
```

Output conventions were discussed in the get pods issue:
https://github.com/GoogleCloudPlatform/kubernetes/issues/7843#issuecomment-101365459

I'd like get output to be one line per resource.

In this case, I'd eliminate the labels column, since `-L` supports specifying labels as columns.

I'd move selector to be the rightmost field displayed, due to length and utility.

Separate columns for cluster and public IPs. NodePort services should just say "Nodes" in the public IP column. Cluster services should say "<n/a>". If that is changed, please also change other instances:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L987

Ports should be on the same line, separated by commas.

**Comment by bgrant0607** [comment]
We could call the public IP/name column "INGRESS", to match the API.

**Comment by brendandburns** [comment]
Ok, I updated #12423 

Example output:
```console
$ kubectl get svc
NAME         CLUSTER IP       EXTERNAL IP       PORT(S)                SELECTOR     AGE
kubernetes   10.179.240.1     <none>            443/TCP                <none>       8d
nginxsvc     10.179.252.126   122.222.183.144   80/TCP,81/TCP,82/TCP   run=nginx2   11m
```

I adopted `<none>` (and fixed the `<n/a>` to be `<none>` too) since I think that looks better than empty string.

Also, note that your spec didn't mention age, but all of the other things have age last, so I kept it for consistency.

ptal.
--brendan

**Comment by bgrant0607** [comment]
Thanks. Looks great. Yes, AGE was added very recently. It makes sense for it to be last.

In order for cut, etc. to work, we need a uniform number of columns, so please use CLUSTER_IP and EXTERNAL_IP.
