### ISSUE TITLE
Drop /redirect/ verb for v1

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#9332]
@lavalamp  @bgrant0607 

Let's drop support for `/redirect/` verb in v1.  
It is only useful if the client, master and nodes are on the same network, which is not always the case.
Better to just tell people to use `/proxy/`

**Comment by bgrant0607** [comment]
SGTM

**Comment by lavalamp** [comment]
Yes, it is not worth the costs of keeping it documented.

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by erictune** [comment]
Remove from docs/accessing-the-cluster.md
