### ISSUE TITLE
use outputdir for all perf data in e2es

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#9336]
easy one.  i can tackle it now or else someone beat me to it.
looks like marek has put a bandaid over the density.go test to put data in /tmp rather than local dir.
tim suggests, lets solve it once and for all w/ using the already existing outputdir option.
  @timothysc @rrati @gmarek

**Comment by timothysc** [comment]
cc @davidopp  re: https://github.com/GoogleCloudPlatform/kubernetes/pull/8809#issuecomment-109421230
