### ISSUE TITLE
UI has partially cut off view

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#9347]
See attached screenshot. The line below FS2 is cut off.

![screenshot from 2015-06-05 16 00 59](https://cloud.githubusercontent.com/assets/1454434/8016720/3eeac226-0b9c-11e5-8bc6-937728e91ec5.png)

**Comment by bgrant0607** [comment]
cc @jackgr @bcbroussard @preillyme

**Comment by mikedanese** [comment]
I think this is fixed.
