### ISSUE TITLE
UI is not as self-explanatory as it could be

### ISSUE THREAD

**Issue by kprobst** [GoogleCloudPlatform/kubernetes#9350]
In the dashboard of the UI, we list CPU, Memory, and FS. I would argue that there's no reason to abbreviate FS and let users puzzle over what we mean. There is plenty of horizontal space available.

Also, whatever we can do to explain the donut chart. It's actually not clear to me what the light purple and black areas mean (but it could be cut off and explained lower, see issue #9347).

**Comment by bgrant0607** [comment]
cc @jackgr @bcbroussard @preillyme

**Comment by bgrant0607** [comment]
Can this be closed?

**Comment by bgrant0607** [comment]
I believe this was resolved by #10422.
