### ISSUE TITLE
Etcd logs on master

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#9352]
Just realized we don't have etcd logs on the master. Need them for debugging. Should be easy to mount /var/log into the container and capture stdout/err, haven't had a chance to dig and see if something more subtle is going on. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/etcd/init.sls seems to indicate that they should be in /var/log @ArtfulCoder

**Comment by davidopp** [comment]
@ArtfulCoder am I correct in understanding you're working on this?

**Comment by ArtfulCoder** [comment]
@davidopp yes. I have referenced a PR now.
