### ISSUE TITLE
Bad certificate on Vagrant/e2e

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/kubernetes#9359]
After running `go run hack/e2e.go -v -up` on 0f1c4c25c344f70c3592040b2ef092ccdce0244f (master) and ssh'ing into minion-1 and running `sudo journalctl -u kube-proxy` I get:
````
Jun 06 01:39:58 kubernetes-minion-1 kube-proxy[3239]: E0606 01:39:58.902167    3239 api.go:180] Unable to load endpoints: Get https://10.245.1.2:6443/api/v1/endpoints: x509: certificate signed by unknown authority
````
repeatedly.

@derekwaynecarr Any ideas?

**Comment by BenTheElder** [comment]
I think this commit: https://github.com/GoogleCloudPlatform/kubernetes/commit/50eb9ad598daf4ab33de6e6608acf60570979441 [`Use https only for the kubelet port`]  might be why this just cropped up as an issue?

I've been digging around and I don't see the CA cert getting setup on the minions, is this expected?

**Comment by derekwaynecarr** [comment]
Just saw this now.  Have not had a chance to debug further, but appreciate any help if you have time to continue debugging.  I won't be able to look at this until tomorrow.

**Comment by BenTheElder** [comment]
After a bit of hacking on util.sh I can scp over and install the ca cert and then restart the kube* services giving a new error:
`Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)`

It looks like we need to set up the client certs too https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/accessing_the_api.md#ports-and-ips-served-on


Rudimentary tweak to `cluster/vagrant/util.sh`
````shell
function kube-up {
  get-password
  create-provision-scripts

  vagrant up

  export KUBE_CERT="/tmp/$RANDOM-kubecfg.crt"
  export KUBE_KEY="/tmp/$RANDOM-kubecfg.key"
  export CA_CERT="/tmp/$RANDOM-kubernetes.ca.crt"
  export CONTEXT="vagrant"

  (
   umask 077
   vagrant ssh master -- sudo cat /srv/kubernetes/kubecfg.crt >"${KUBE_CERT}" 2>/dev/null
   vagrant ssh master -- sudo cat /srv/kubernetes/kubecfg.key >"${KUBE_KEY}" 2>/dev/null
   vagrant ssh master -- sudo cat /srv/kubernetes/ca.crt >"${CA_CERT}" 2>/dev/null

   create-kubeconfig
  )

  local j
  for (( j=1; j<=${NUM_MINIONS}; j++ )); do
      local OPTIONS=`vagrant ssh-config minion-$j | awk -v ORS=' ' '{print "-o " $1 "=" $2}'`
      local CERT_NAME=`basename ${CA_CERT}`
      scp ${OPTIONS} "${CA_CERT}" vagrant@127.0.0.1:~/
      vagrant ssh "minion-$j" -- "sudo sh -c \"cp /home/vagrant/${CERT_NAME} /etc/pki/ca-trust/source/anchors/kubernetes.ca.pem\""
      vagrant ssh "minion-$j" -- "sudo sh -c \"update-ca-trust extract\""
      vagrant ssh "minion-$j" -- "sudo sh -c \"systemctl restart kube*\""
  done

  verify-cluster
}
````
That gets the certificate authority set up but still needs client certs.

**Comment by roberthbailey** [comment]
For auth you can specify a client cert, a bearer token, or basic auth credentials depending on how the master is configured.

**Comment by BenTheElder** [comment]
Further debugging shows that `/var/lib/kube-proxy/kubeconfig` is empty on minion-1 and that this is being passed to kube-proxy:
````
vagrant@kubernetes-minion-1 ~]$ ps aux | grep ku
root      3736  0.4  0.9  14860  9700 ?        Ssl  00:08   0:03 /kube2sky -domain=cluster.local -kubecfg_file=/etc/dns_token/kubeconfig -kube_master_url=https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
root      3978  1.0  1.6 215228 16756 ?        Ssl  00:08   0:06 /usr/local/bin/kube-proxy --master=https://10.245.1.2:6443 --kubeconfig=/var/lib/kube-proxy/kubeconfig --v=2
root      3979  7.9  4.9 893800 50472 ?        Ssl  00:08   0:49 /usr/local/bin/kubelet --api_servers=https://10.245.1.2:6443 --enable-debugging-handlers=true --hostname_override=10.245.1.3 --cloud_provider=vagrant --config=/etc/kubernetes/manifests --allow_privileged=False --v=2 --cluster_dns=10.247.0.10 --cluster_domain=cluster.local
vagrant   7531  0.0  0.2 113000  2264 pts/0    S+   00:19   0:00 grep --color=auto ku
````

I've refactored the token generation to work more like AWS (done in util.sh, before making the cluster) but I'm still figuring out providing them to the minions.

**Comment by derekwaynecarr** [comment]
If you push a branch with your current approach, I can help finish up tomorrow.

**Comment by BenTheElder** [comment]
Ok thanks, I think I've got it almost figured out, bust it seems like possibly saltstack is trying to manage the kube-proxy config and making an empty default one over the one I've written so hopefully that's the last thing that needs fixing. I'll push and mention it here before I quit for the night.

**Comment by BenTheElder** [comment]
Still debugging the config creation but here's the branch:
https://github.com/BenTheElder/kubernetes/tree/vagrant_certificates

**Comment by BenTheElder** [comment]
I think ultimately the issue was just a space missing when piping in EOF on creating the config files...
Regardless I've refactored so that the tokens are generated in util.sh and can be placed across all of the nodes. It seems to be working now.

Side note: in order to `vagrant ssh minion-2` I find i have to do:
`NUM_MINIONS=2 vagrant ssh minion-2`
If commands aren't prefixed with NUM_MINIONS=n then vagrant just assumes there must be 1 minion which is odd and seemingly unexpected behavior when there are 2 minions up and running.

**Comment by derekwaynecarr** [comment]
you should export NUM_MINIONS to the value desired or set it in your bash config file.

**Comment by BenTheElder** [comment]
Of course; I just meant that because in this case NUM_MINIONS is being set by the e2e config, and if your config NUM_MINIONS is the default of 1 or unset then vagrant strangely seems to not be able to access or list the minion, so others may run into that issue if they are only running tests.
