### ISSUE TITLE
Service accounts should also mount CA certificate

### ISSUE THREAD

**Issue by jimmidyson** [GoogleCloudPlatform/kubernetes#9363]
Service accounts currently mount the generated token but in order to use it against the API server you either have to disable certificate validation (bad but easy) or manually set up secrets for the CA certificate.

It would be really nice to have the CA certificate automatically mounted to a known location like the token is when using a service account.

**Comment by liggitt** [comment]
Dupe of https://github.com/GoogleCloudPlatform/kubernetes/issues/7648

**Comment by jimmidyson** [comment]
OK thanks - closing
