### ISSUE TITLE
Problem with inbound Internet => Container traffic on GCE

### ISSUE THREAD

**Issue by diferential** [GoogleCloudPlatform/kubernetes#9372]
I'm trying to setup the 'guestbook' example on my GCE instance, but running into issues exposing this service to the internet.

I cannot connect to any of my internet based ports, but the container <=> container networks do seem to work and I can telnet from within a Kubernetes VM to the container based IPs and the 'target' ports of 80.

I changed the port to bind the service to 880 and a type of NodePort.

From my understanding of the 'services' and network pages, this type of NodePort should bind on the INTERNET interface of GCE, right?
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md

Note that I also tried loadbalancing but that did not create a GCE loadbalancer that I could see either.

The GCE IPs that are internet-bound are 10.240.0.0/16 but I do not see any rule doing DNAT for those ports. There's also no 880 daemon listening on my nodes, so I do not see how this incoming traffic would work from the internet.

What am I doing wrong here? 

Thanks for your help in advance with this,
Emilian
```
$ cat frontent-service.yml
{
   "kind":"Service",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"frontend",
      "labels":{
         "name":"frontend"
      }
   },
   "spec":{
      "ports": [
        {
          "port":880,
          "targetPort":80,
          "protocol":"TCP"
        }
      ],
      "selector":{
         "name":"frontend"
      },
      "type":"NodePort"
   }
}

$ kubectl get service
NAME            LABELS                                                                           SELECTOR            IP(S)           PORT(S)
frontend        name=frontend                                                                    name=frontend       10.87.244.251   880/TCP
kube-dns        k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns    10.87.240.10    53/UDP
                                                                                                                                     53/TCP
kubernetes      component=apiserver,provider=kubernetes                                          <none>              10.87.240.2     443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes                                          <none>              10.87.240.1     80/TCP
redis-master    name=redis-master                                                                name=redis-master   10.87.248.194   6379/TCP
redis-slave     name=redis-slave                                                                 name=redis-slave    10.87.247.83    6379/TCP

root@k8s-cdb-437922f2-node-dlra:/home/emilian# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      5532/kubelet    
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      5442/kube-proxy 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2258/sshd       
tcp6       0      0 :::4194                 :::*                    LISTEN      5532/kubelet    
tcp6       0      0 :::48837                :::*                    LISTEN      5442/kube-proxy 
tcp6       0      0 :::59017                :::*                    LISTEN      5442/kube-proxy 
tcp6       0      0 :::52234                :::*                    LISTEN      5442/kube-proxy 
tcp6       0      0 :::10250                :::*                    LISTEN      5532/kubelet    
tcp6       0      0 :::10255                :::*                    LISTEN      5532/kubelet    
tcp6       0      0 :::22                   :::*                    LISTEN      2258/sshd       
tcp6       0      0 :::44761                :::*                    LISTEN      5442/kube-proxy 
tcp6       0      0 :::59034                :::*                    LISTEN      5442/kube-proxy 
tcp6       0      0 :::53756                :::*                    LISTEN      5442/kube-proxy 

$ gcloud compute routes list
NAME                                         NETWORK DEST_RANGE     NEXT_HOP                                           PRIORITY
default-route-36fdb60c1d86974f               default 10.240.0.0/16                                                     1000
default-route-e89d7204c6244600               default 0.0.0.0/0      default-internet-gateway                           1000
k8s-cdb-e13aaef7-0c6f-11e5-9343-42010af022a5 default 10.84.1.0/24   us-central1-f/instances/k8s-cdb-437922f2-node-otl9 1000
k8s-cdb-e1f8505b-0c6f-11e5-9343-42010af022a5 default 10.84.0.0/24   us-central1-f/instances/k8s-cdb-437922f2-node-dlra 1000
k8s-cdb-e22c7078-0c6f-11e5-9343-42010af022a5 default 10.84.2.0/24   us-central1-f/instances/k8s-cdb-437922f2-node-yc78 1000
k8s-cdb-master                               default 10.87.239.0/24 us-central1-f/instances/k8s-cdb-master             1000

root@k8s-cdb-437922f2-node-dlra:/home/emilian# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-PORTALS-CONTAINER  all  --  anywhere             anywhere             /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
KUBE-NODEPORT-CONTAINER  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-PORTALS-HOST  all  --  anywhere             anywhere             /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
KUBE-NODEPORT-HOST  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  anywhere            !10.0.0.0/8          

Chain KUBE-NODEPORT-CONTAINER (1 references)
target     prot opt source               destination         

Chain KUBE-NODEPORT-HOST (1 references)
target     prot opt source               destination         

Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             10.87.240.2          /* default/kubernetes: */ tcp dpt:https redir ports 44761
REDIRECT   tcp  --  anywhere             10.87.240.1          /* default/kubernetes-ro: */ tcp dpt:http redir ports 48837
REDIRECT   udp  --  anywhere             10.87.240.10         /* default/kube-dns:dns */ udp dpt:domain redir ports 38095
REDIRECT   tcp  --  anywhere             10.87.240.10         /* default/kube-dns:dns-tcp */ tcp dpt:domain redir ports 53756
REDIRECT   tcp  --  anywhere             10.87.248.194        /* default/redis-master: */ tcp dpt:6379 redir ports 59017
REDIRECT   tcp  --  anywhere             10.87.247.83         /* default/redis-slave: */ tcp dpt:6379 redir ports 52234
REDIRECT   tcp  --  anywhere             10.87.244.251        /* default/frontend: */ tcp dpt:880 redir ports 59034

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             10.87.240.2          /* default/kubernetes: */ tcp dpt:https to:10.240.252.201:44761
DNAT       tcp  --  anywhere             10.87.240.1          /* default/kubernetes-ro: */ tcp dpt:http to:10.240.252.201:48837
DNAT       udp  --  anywhere             10.87.240.10         /* default/kube-dns:dns */ udp dpt:domain to:10.240.252.201:38095
DNAT       tcp  --  anywhere             10.87.240.10         /* default/kube-dns:dns-tcp */ tcp dpt:domain to:10.240.252.201:53756
DNAT       tcp  --  anywhere             10.87.248.194        /* default/redis-master: */ tcp dpt:6379 to:10.240.252.201:59017
DNAT       tcp  --  anywhere             10.87.247.83         /* default/redis-slave: */ tcp dpt:6379 to:10.240.252.201:52234
DNAT       tcp  --  anywhere             10.87.244.251        /* default/frontend: */ tcp dpt:880 to:10.240.252.201:59034
```

**Comment by thockin-cc** [comment]
kubectl get -o yaml shows the full picture. Setting type to NodePort tells
the system to allocate a port (for example 30123) that is available on all
nodes. That is the port that your service is available on. Then you have to
open firewalls for that port - we don't do that by default for safety.

**Comment by diferential** [comment]
What do you mean by a port that is available on all nodes? What is a nodeip
compared to a clusterip? I thought the former is would bind the service to
the VM interface, while the later only to the internal cluster IPs.

From my inspection above the port is only available on the internal
interfaces of Kubernetes and not on the GCE VM interface. Even if I
manually open up the firewall I won't be able to access my service
externally.

**Comment by justinsb** [comment]
Your rule for port=880 is this one:
```
REDIRECT   tcp  --  anywhere             10.87.244.251        /* default/frontend: */ tcp dpt:880 redir ports 59034
```

iptables remaps traffic on the service IP & port 880 to a port that kube-proxy chooses to listen on locally, in this case 59034.

For NodePort, I would expect to see a port chosen in the 30000-32767 range, also redirected to port 59034.  I don't see that, so something has not worked correctly.

Can you please post the output from `kubectl get -o yaml guestbook` and also `kubectl get service guestbook`; if everything was working that should tell us the NodePort that you would have to open, but hopefully it can provide some diagnostic hints for us.

**Comment by jakobholmelund** [comment]
Im not sure if this is related. But it seems that the way that nodes, targetpools and instances are named in container engine have changed. I just tried to setup a new cluster the exact same way i did a month ago. Everything get's created and everything internally seems to work but the load balancer address just hangs. I will try to follow one of the walkthroughs tonight. But i have tried to get my own setup up and running all weekend with no luck. I'm not sure if it's the Load balancer that doesn't hit the service or the service that can't find the controller.

Here is the log from

$ kubectl describe service django

W0608 10:37:24.125197   13172 request.go:291] field selector: v1beta3 - events - involvedObject.kind - Service: need to check if this is versioned correctly.
W0608 10:37:24.125239   13172 request.go:291] field selector: v1beta3 - events - involvedObject.uid - d7af5786-0db4-11e5-98c7-42010af0712b: need to check if this is versioned correctly.
W0608 10:37:24.125247   13172 request.go:291] field selector: v1beta3 - events - involvedObject.name - django: need to check if this is versioned correctly.
W0608 10:37:24.125253   13172 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.

Name:			django
Labels:			name=django
Selector:		name=django
IP:			10.219.242.0
Port:			<unnamed>	80/TCP
Endpoints:		<unnamed>	10.216.1.14:80,10.216.1.15:80
Session Affinity:	None
No events.

$ kubectl get -o yaml django
Error: no resource "django" has been defined

My setup is:

Controller

{
  "id": "frontend-controller-v12",
  "kind": "ReplicationController",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "django",
    "labels": {
      "name": "django",
      "version": "v12"
    }
  },
  "spec": {
    "replicas": 2,
    "selector": {
      "name": "django",
      "version": "v12"
    },
    "template": {
      "metadata": {
        "labels": {
          "name": "django",
          "version": "v12"
        }
      },
      "spec": {
        "containers": [{
          "name": "django",
          "image": "gcr.io/xxxx/xxxxx:latest",
          "command": ["gulp", "prod"],
          "workingDir": "/code",
          "ports": [{
            "name": "http-server",
            "containerPort": 80,
            "protocol": "TCP"
          }]
        }]
      }
    }
  }
}

Service

{
	"apiVersion": "v1beta3",
	"kind": "Service",
	"metadata": {
		"name": "django",
		"labels": {
			"name": "django"
		}
	},
	"spec": {
		"createExternalLoadBalancer": true,
		"ports": [{
			"port": 80,
			"targetPort": "http-server",
			"protocol": "TCP"
		}],
		"selector": {
			"name": "django"
		}
	}
}

**Comment by diferential** [comment]
I've since deleted the cluster to save the money. I'll do another
experiment and report back here.
Could it be problematic if I created the cluster from the GCE page instead
of the gcloud commands?

**Comment by jlowdermilk** [comment]
@jakobholmelund there were some incompatible v1beta3 api changes between 0.17 and 0.18. The `kubectl` binary shipped with the cloud sdk is currently 0.17 while the k8s version container engine launches by default is 0.18+. The cloudsdk release tomorrow will  include an updated kubectl binary (0.18.1), but in the meantime you could retry your setup using a kubectl binary from https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.18.1.

**Comment by dchen1107** [comment]
cc/ @dchen1107

**Comment by diferential** [comment]
If this is due to version incompatibility, it would be good if Kubernetes
checked for version incompatibility before accepting to make changes on a
cluster.

What guarantees does Kubernetes offer in that case? Should I create an
issue tracking that if the version checking is not implemented right now?
