### ISSUE TITLE
Binaries for 0.18.1.1 not publicly available

### ISSUE THREAD

**Issue by pires** [GoogleCloudPlatform/kubernetes#9375]
This returns 404, https://storage.googleapis.com/kubernetes-release/release/v0.18.1.1/bin/linux/amd64/kube-apiserver

**Comment by brendandburns** [comment]
To be honest, it's identical to v0.18.1

The version that I uploaded to github was accidentally built first with a dirty git client.  I didn't want to overwrite the version with a file with different sha1 and md5 so I added v0.18.1.1

You can just use v0.18.1 in Google Cloud Storage, it's the exact same binary.

(sorry for the confusion)

--brendan
