### ISSUE TITLE
kubectl should properly validate against malformed json files

### ISSUE THREAD

**Issue by fabianofranz** [GoogleCloudPlatform/kubernetes#9380]
When a malformed json file[1] is passed to `create` the `error: no objects passed to create` is returned. Increasing the log level to 4 we get a `Unable to load file "<file>": unable to get type info from "<file>": couldn't get version/kind; json parse error: invalid character '\n' in string literal`. 

This happens because the resource builder in `create` is marked as `ContinueOnError` so that the creation of elements can succeed even when other elements fail. However, there is no previous validation for lower-level errors like JSON marshalling problems. This needs to happen *before* `InfoForData`, otherwise malformed JSON issues will not error right away and will only appear in logs. `yaml.ToJSON` [does not perform actual JSON validation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/yaml/decoder.go#L35), it only [checks for an open brace as prefix](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/yaml/decoder.go#L164).

[1] malformed json file (unexpected commas):
```
{
  "apiVersion": "v1beta3",
  (...)
  "metadata": {
    "name": "quota",
  },
  (...)
}
```

**Comment by bgrant0607** [comment]
@brendandburns are you working on this? If not, please unassign.

**Comment by fabianofranz** [comment]
This was apparently fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/9357.
