### ISSUE TITLE
e2e tests for add-on update

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#9394]
Add-on update was added in #9128 (it fixed #8107).
It was manually tested and automated tests are missing. The following scenarios should be tested:

 1. If a service/rc manifest is deleted, the object should be deleted from the API server
 1. If a new service/rc manifest was added, the object should be created.
 1. If the version of an rc is changed, the rc should be updated (in the future - check that rolling update is performed, e.g. by monitoring that the service handled by the rc is accessible)
 1. verify that after kube-push, the changes in addons are reflected "immediately" (the kube-addons linux service should be restarted by kube-push)

Add-on updater will be rewritten as a pod, so the tests should have as little dependency on the implementation as possible.

cc @zmerlynn @davidopp @fgrzadkowski @satnam6502

**Comment by davidopp** [comment]
@marekbiskup it would obviously be great if you can get this in by Friday, though I realize that might not be possible.

**Comment by marekbiskup** [comment]
Scenarios 1-3 are ready in #9394
There are only a few lines changed in production code.

I wonder If performing kube-push during e2e tests is a good idea. It takes long.
Are there any tests for kube-push? I could add my case to those tests. If not, maybe I can skip scenario 4 as well. Are we consider kube-push production code?

**Comment by davidopp** [comment]
I think you meant #9493.

**Comment by zmerlynn** [comment]
I don't think doing kube-push during an e2e is a great idea. We've got Jenkins runs that are doing `kube-push` between e2e runs, which seems like a possible right approach, though also limiting (because there's no active load at that point). There's so many wrong answers here. :)

**Comment by zmerlynn** [comment]
To expand a bit further... The main reason I'm a little twitchy about is that it's pretty invasive. It's reconfiguring the entire node in the middle of an e2e run, which stands the chance of possibly wreaking all sorts of havoc. I'm not sure I really want to debug that.

**Comment by marekbiskup** [comment]
The test is ready for the second round of review (#9493)

**Comment by marekbiskup** [comment]
The third round of review is necessary. To be ready on Monday.

**Comment by roberthbailey** [comment]
@marekbiskup is this ready to be reviewed again?

**Comment by marekbiskup** [comment]
Status: already LGTM-ed. Waiting for merge.
Shippable fails for unknown reasons (as always).
