### ISSUE TITLE
Docker oom_score_adj is 0, should probably be lower (more important)

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#9411]
Docker oom_score_adj is 0, but it being killed is probably at least as disruptive as kube-proxy crashing.

(This turned out not to be the cause of my problem, but I think we probably want to do this)

**Comment by dchen1107** [comment]
@justinsb which version are you running? We did oom protect docker. Here is what I have on my node:

```
# pidof docker
14943

# cat /proc/14943/oom_score_adj 
-900
```

Today, we oom protect monit(-901), docker (-900), kubelet (-900), kube-proxy (-899), and all podinfra containers' process 

Is that enough?

**Comment by dchen1107** [comment]
I double checked my node, and restart docker daemon a couple of times, the oom_score_adj is set to be -900. I am closing it. Justin, feel free to open it if I missed anything here. Thanks!

**Comment by justinsb** [comment]
Sorry for false alarm; this was with a 0.17.1 build.  Confirmed that on newer builds docker does have oom_score_adj=-900 (and looking at the code, kubelet even reapplies it after a docker crash - nice!)
