### ISSUE TITLE
Make it clear that the script to bring up your first cluster is a one-time use script.

### ISSUE THREAD

**Issue by evasnee** [GoogleCloudPlatform/kubernetes#9414]
From: https://github.com/GoogleCloudPlatform/kubernetes/blob/2ffb875129602924257d2a8ea30a24d0e00c6cd1/docs/getting-started-guides/gce.md

curl -sS https://get.k8s.io | bash 

Feedback from users: 
   -- docs should mention the bring-up script creates a cluster with the name/prefix "kubernetes" and if you want more than 1 or to use a different name you must override that
   -- mention that the script is for a single cluster setup. can't be reused

**Comment by juliaferraioli** [comment]
@amygdala do you think this was addressed by your gce cleanup?

**Comment by amygdala** [comment]
Not really -- this one is still on my stack.  (should be an easy change though)
