### ISSUE TITLE
Make it clear you can't copy/paste the command for installing K8s command line tools.

### ISSUE THREAD

**Issue by evasnee** [GoogleCloudPlatform/kubernetes#9415]
path export (path/to/kubernetes/platforms/...) should be formatted to indicate that you can't just copy-paste 

![image](https://cloud.githubusercontent.com/assets/11644912/8042379/c35e4b48-0dd3-11e5-9579-e6d0a06ee84a.png)

Documentation: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md#installing-the-kubernetes-command-line-tools-on-your-workstation

**Comment by goltermann** [comment]
use angle brackets or curly braces
