### ISSUE TITLE
Consider scrubbing troubleshooting sections of help to be organized by symptom

### ISSUE THREAD

**Issue by evasnee** [GoogleCloudPlatform/kubernetes#9416]
Consider organizing troubleshooting sections by symptom/problem so that it's easier for people to find the solution to the problem they are experiencing in that moment.

**Comment by juliaferraioli** [comment]
@brendandburns you've taken on the troubleshooting section -- does this fit with how you've thought of the doc?

**Comment by bgrant0607** [comment]
We definitely need some kind of organization of our troubleshooting docs:
* docs/user-guide/application-troubleshooting.md
* docs/user-guide/debugging-services.md
* docs/user-guide/compute-resources.md#troubleshooting
* https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ
* https://github.com/GoogleCloudPlatform/kubernetes/wiki/Services-FAQ
* https://github.com/GoogleCloudPlatform/kubernetes/wiki/User-FAQ

**Comment by JanetKuo** [comment]
And also 
* docs/cluster-troubleshooting.md

I'll use `docs/troubleshooting.md` as a central place for organizing all other troubleshooting docs.

**Comment by bgrant0607** [comment]
SGTM
