### ISSUE TITLE
Fix misc issues with Guestbook app help documentation

### ISSUE THREAD

**Issue by evasnee** [GoogleCloudPlatform/kubernetes#9422]
Documentation: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook

There were several miscellaneous issues that users noted with the Guestbook walkthrough that would be worth fixing:
   -- docker logs xxx / FATA[0000] Get http://var/run/docker . permission denied.  Are you trying to connect to a TLS-enabled ... without TLS?  No, I forgot "sudo"
   -- docs reference port 8000, but none of the configs do
   -- "on the pod which (a node the service listens to)" --> this sentence makes no sense

**Comment by juliaferraioli** [comment]
@amygdala this was addressed in [#9754](https://github.com/GoogleCloudPlatform/kubernetes/pull/9754), correct?
