### ISSUE TITLE
Move generatePodStatus out of critical path for pod startup

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#9429]
Analyzing nodes where startup of a single pod on a 30 pod node takes O(10s) it's evident that generatePodStatus takes O(3s) and we do it twice before finally setting the status as Running. Even starting the containers takes < 1s. Can we skip the first generatePodStatus for new pods?

Most of the time for generatePodStatus is coming from a handful of docker operations in GetPodStatus (list, inspect, inspect image). 

/ref https://github.com/GoogleCloudPlatform/kubernetes/issues/3954

**Comment by dchen1107** [comment]
Skipping the first generatePodStatus for new pods doesn't help your goal in #3954: 99%ile end-to-end pod startup time, right? you still need podStatus is generated and it is running within 5s, right?

Speeding up generatePodStatus requires using docker event stream, which is out-of-scope of 1.0 unfortunately.

**Comment by bprashanth** [comment]
we generatePodStatus twice, seems debatable that we need the first one:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1132
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1091

**Comment by dchen1107** [comment]
@bprashanth I think you are right, the first one is not needed for new pods at all. I can quickly change that, or feel free to send me a pr on this. Thanks!

**Comment by yujuhong** [comment]
Yes, the first one is not necessary for new pods.

**Comment by gmarek** [comment]
This seems to be necessary for #3954. Promoting to v1.0

**Comment by bprashanth** [comment]
The fix for this is coupled into https://github.com/GoogleCloudPlatform/kubernetes/pull/9454, I'll split it out. Note that docker list/inspect etc shouldn't be taking so long in the normal case for a single new pod (just ssh into a stead node with 30 pods and run them), one of the reasons it does is concurrent podworker hammering.

**Comment by brendandburns** [comment]
Assigning to @bprashanth since he has a fix.

**Comment by dchen1107** [comment]
I am closing the issue for now. There are more optimization in syncloop and creation path. We are going to handle them post 1.0
