### ISSUE TITLE
kubectl doesn't provide describe namespace

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#9435]
All resources defined in kubernetes has both get and describe commands from kubectl, except namespace and cs (component statuses)

```
$ cluster/kubectl.sh describe namespaces default
error: no description has been implemented for "Namespace"
```

Proposed to add describe namespace, and dump all other objects / resources belonging to such namespace.

**Comment by dchen1107** [comment]
cc/ @bgrant0607 

Related discussion can be found at #9433,  #9356

**Comment by derekwaynecarr** [comment]
We have a command in OpenShift that describes a project (aka a namespace).  It shows the quota and the limit range settings.  I can send a PR to make that available in Kube if you like tomorrow.

**Comment by derekwaynecarr** [comment]
You can see sample output here:

https://github.com/openshift/origin/pull/2223

I don't want to dump ALL resources in the namespace, so I am hoping you are not recommending that because that would be completely unreadable.

**Comment by bgrant0607** [comment]
Yes, that looks useful.

It would be useful to get counts of all kinds of resources in the namespace. I suppose we could do that by setting up some quota by default.

**Comment by dchen1107** [comment]
Yes, that is useful. Also yes, not dump ALL objects of ALL resources. What Brian proposed sounds reasonable.

**Comment by derekwaynecarr** [comment]
Will send a PR for your review tomorrow.

**Comment by derekwaynecarr** [comment]
In absence of a quota, we could infer some counts on the client.  Will mull on it tonight.
