### ISSUE TITLE
Need a way for capturing information that only plugins understand in the API

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#945]
Inlining a map doesn't seem to work. http://play.golang.org/p/NnwTh9KI5r

Another (better?) possibility is to evolve APIObject. It should be possible to make an object type that can just store and regurgitate the JSON for an object that isn't understood.

**Comment by lavalamp** [comment]
I think @smarterclayton implemented the last bit of this already? am I misremembering?

**Comment by smarterclayton** [comment]
I believe both parts (unrecognized foreign child objects and extensions to objects) should be working now.

**Comment by thockin** [comment]
Is there an example so I can try it out?
