### ISSUE TITLE
Need to clean up after docker crash

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#9456]
After a docker crash, the processes running in the containers (usually?) keep running, and a lot of mounts are leaked.

In order to get docker to restart correctly, I often have to go through and kill all the processes, and the usually I have to delete all the mounts:
```cat /proc/mounts | grep docker.aufs | awk '{print $2}'  | sudo xargs -r umount```

We should make sure these processes are killed and remove any mounts that docker leaves behind as part of restarting it.

**Comment by dchen1107** [comment]
Docker restart will cleanup those running processes, including umount here. Monit is monitoring docker, kubelet, and kube-proxy process on a given node, and periodically check their status, and restart then upon failure. Is that enough here?

**Comment by justinsb** [comment]
Yes, but I think I have seen that Docker does not kill always those processes that were running in its containers.  I think that it never does so when killed by monit, but I will double check and see if I can reproduce reliably.

I think my core problem behind this series of issues is that I had too many big containers running.  When I ran out of memory, Docker stopped responding to monit, monit killed Docker but the (java) processes in my containers kept running, so Docker could not restart because the memory was not freed.

But I will try to reproduce with something less hand-wavy!
