### ISSUE TITLE
Vagrant:Fedora 21 repo failing 

### ISSUE THREAD

**Issue by fahadpolash** [GoogleCloudPlatform/kubernetes#9459]
Hello,
I was trying to bringing up the cluster from the github master branch which is using fedora 21. But I am getting the following errors:

==> master: Installing, enabling prerequisites
==> master: 
==> master: 
==> master:  One of the configured repositories failed (Fedora 21 - x86_64),
==> master:  and yum doesn't have enough cached data to continue. At this point the only
==> master:  safe thing yum can do is fail. There are a few ways to work "fix" this:
==> master: 
==> master:      1. Contact the upstream for the repository and get them to fix the problem.
==> master: 
==> master:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
==> master:         upstream. This is most often useful if you are using a newer
==> master:         distribution release than is supported by the repository (and the
==> master:         packages for the previous distribution release still work).
==> master: 
==> master:      3. Disable the repository, so yum won't use it by default. Yum will then
==> master:         just ignore the repository until you permanently enable it again or use
==> master:         --enablerepo for temporary usage:
==> master: 
==> master:             yum-config-manager --disable fedora
==> master: 
==> master:      4. Configure the failing repository to be skipped, if it is unavailable.
==> master:         Note that yum will try to contact the repo. when it runs most commands,
==> master:         so will have to try and fail each time (and thus. yum will be be much
==> master:         slower). If it is a very temporary problem though, this is often a nice
==> master:         compromise:
==> master: 
==> master:             yum-config-manager --save --setopt=fedora.skip_if_unavailable=true
==> master: 
==> master: Cannot retrieve metalink for repository: fedora/21/x86_64. Please verify its path and try again

Any idea?

**Comment by derekwaynecarr** [comment]
Looks like a transient error with fedora mirrors.  Will try in morning to see if issue is gone.

**Comment by fahadpolash** [comment]
I tried this morning as well. Still the same errors. FYI..
[vagrant@kubernetes-master ~]$ 
[vagrant@kubernetes-master ~]$ sudo yum update


 One of the configured repositories failed (Fedora 21 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable fedora

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=fedora.skip_if_unavailable=true

Cannot retrieve metalink for repository: fedora/21/x86_64. Please verify its path and try again
[vagrant@kubernetes-master ~]$ 
[vagrant@kubernetes-master ~]$ 
[vagrant@kubernetes-master ~]$ 
[vagrant@kubernetes-master ~]$ cat /etc/yum.
yum.conf     yum.repos.d/ 
[vagrant@kubernetes-master ~]$ cat /etc/yum.repos.d/fedora.repo 
[fedora]
name=Fedora $releasever - $basearch
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-debuginfo]
name=Fedora $releasever - $basearch - Debug
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/releases/$releasever/Everything/$basearch/debug/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-source]
name=Fedora $releasever - Source
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/releases/$releasever/Everything/source/SRPMS/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
[vagrant@kubernetes-master ~]$ cat /etc/yum.repos.d/fedora-updates.repo 
[updates]
name=Fedora $releasever - $basearch - Updates
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/$basearch/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
enabled=1
metadata_expire=6h
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-debuginfo]
name=Fedora $releasever - $basearch - Updates - Debug
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/$basearch/debug/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch
enabled=0
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-source]
name=Fedora $releasever - Updates Source
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/SRPMS/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch
enabled=0
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
[vagrant@kubernetes-master ~]$ cat /etc/yum.repos.d/fedora-updates-testing.repo 
[updates-testing]
name=Fedora $releasever - $basearch - Test Updates
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/testing/$releasever/$basearch/

metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch
enabled=0
metadata_expire=6h
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-testing-debuginfo]
name=Fedora $releasever - $basearch - Test Updates Debug
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/testing/$releasever/$basearch/debug/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-debug-f$releasever&arch=$basearch
enabled=0
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-testing-source]
name=Fedora $releasever - Test Updates Source
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/testing/$releasever/SRPMS/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-source-f$releasever&arch=$basearch
enabled=0
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
[vagrant@kubernete

**Comment by fahadpolash** [comment]
Hello,
Fedora 21 repo is working fine. I had to add proxy in /etc/yum.conf file.
After adding proxy, it seems working. Though it is getting hanged in slat's repo. I am opening new issue for that. Thanks.
