### ISSUE TITLE
Seeing error on command mentioned in gettingstarted/docker.md 

### ISSUE THREAD

**Issue by tanmaybinaykiya** [GoogleCloudPlatform/kubernetes#9460]
I tried to follow the example and the following command failed.

    kubectl -s http://localhost:8080 run nginx --image=nginx --port=80 
    > Error: unknown command "-s"
     Run 'kubectl help' for usage.

Is the command supposed to be run-container?

**Comment by juliaferraioli** [comment]
[run-container](https://github.com/GoogleCloudPlatform/kubernetes/blob/1d50e97305f33075bcd7e337f1bb0296f013934b/pkg/kubectl/cmd/run.go#L49) is deprecated. What version of kubectl are you using?

**Comment by brendandburns** [comment]
This is b/c the kubectl that is suggested is the 0.17.0 release we shouldn't have updated that page for run, without updating the code/images.

Please use:
```
kubectl -s http://localhost:8080 run-container nginx --image=nginx --port=80 
```

I will revert the docs until we update the image.
