### ISSUE TITLE
Rolling update of addon RCs and update of addon services

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/kubernetes#9463]
Two important things:
 1. The add-on replication controllers should be rolling upgraded.
 1. Services and RCs should be updated if their parameters change (currently they are updated only if the name changes)

At the same time, the additional improvements are welcomed
 1. add-on manager (currently kube-addons linux service) should be run as a pod (as a controller)
 1. the bash code should be rewritten in go, to improve error handling and maintainability 

cc @zmerlynn @davidopp @fgrzadkowski @satnam6502

**Comment by fgrzadkowski** [comment]
I think we should have separate issues for each of the steps/tasks you've listed, because IMO they have different priorities. My initial ordering would be:

1. Run as a pod
2. Rewrite in go
3. Updating Services when definition changes
4. Rolling update

**Comment by marekbiskup** [comment]
I created these issues:

Rolling update #9467 
Update addon services when their definition changes #9468
Run addon update process as a pod #9469
Rewrite bash code of addon updater in go #9470
