### ISSUE TITLE
Copy all "user" documentation to GitHub Pages (http://kubernetes.io/)

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#9494]
Setup http://kubernetes.io (gh-pages branch) for publishing transformed copies of the user documentation (source .md files remain in the master branch).

**Details**:
 * *(updated)* All non-kubernetes-contributor documentation will be transformed to .html and published on http://kubernetes.io/ (this site will be the main source for all user facing documentation) (#7034)
     * Including the content in these folders: docs, examples, getting-started-guides  
       Excluding: designs, proposals, devel, man
 * A site navigation tree will be added:
     * Structured to separately display multiple release versions (#8969)
     * Organized by user role "Cluster Administrator" and "Application Developer" (#7299)
 * Google Custom Search Engine will be integrated
 * Stable versions and an "in-development" version of the documentation will be published:
     * Stable versions of the documentation represent released versions:
         * *(update)* Once a version is 'released' to gh-pages, all maintenance is done there in gh-pages (.html files). In other words, the .html files in gh-pages become the source files for a released version.
         * Only one version behind HEAD is in-scope for maintenance 
         * Maintenance changes can include Bugs and new or changed content but nothing that is not supported in that release
         * Fixes or changes implemented to a stable version should also get pushed into the "in-development" version (if applicable)
     * The unstable (in-development) version reflects development's HEAD:
         * Contributor can deliver changes, updates, and fixes to this "in-development" version 
         * This version should be/remain in-sync with development

*(update)* The following are no longer issues because the source files for examples, api, and cli docs will remain in the master branch
~~**Other dependencies that need ATTENTION**:~~
 * ~~Examples folder is also included in product image. *We need to resolve how this will work.*~~
 * ~~Swagger API gets automatically generated (master branch: hack/update-swagger-spec.sh). *We need to ensure docs at HEAD remain current.*~~
 * ~~kubectl CLI gets automatically generated (master branch: hack/run-gendocs.sh). *We need to ensure docs at HEAD remain current.*~~
 * ~~Other scripts? .md file analytics?~~

**New file handling process**:
 * "stable" versions of the files will live in a folder (folder name = version #) in gh-pages
 * "unstable" (HEAD/in-development) versions of the files will live in a folder (folder name = HEAD) in gh-pages
 * *(update)* The copy of HEAD will be transformed and copied to gh-pages to maintain currency.
 * *(update)* To update a released version, you update the previously transformed .html files in the corresponding folder in the gh-pages branch

**TODO**:
 * DONE: ~~Create new site navigation tree and map all existing documents (and issues)~~
 * Fix all linking (apply linking changes that reflect necessary file directory changes in gh-pages (for handling multiple "versions" of the docs)) (#1571)
 * Create corresponding Jekyll and Liquid site files (.yml, _layout/.html, and _scss/.html files) for:
     * Create site navigation tree
     * Individual help topics 
     * A topic specific header (to include search box)
     * Landing pages (ie set of getting started guides, examples, tutorials, troubleshooting)
 * Add support for Google Custom Search Engine
 * Test, review, get approval in Fork before publishing

**For Development Team:**  (Chao Xu owns this)
 * Add the following steps to the release process:
     * Script in the "[front matter](http://jekyllrb.com/docs/frontmatter/)" to the top of each each file:  
     `---`  
      `layout: docwithnav`  
      `---`  
 * Process all [link text](../linktofile.md) links so that they point to .html files -> <a href="../linktofile.html">link text</a>
 * For the release process, copy "user-facing" docs from master to corresponding folder in gh-pages
 * DONE: ~~Change hard coded links/URLs from "http:docs.k8s.io/*filename.md*" to relative URL "../../docs/*filename.md*" (#3059, #1571)~~

**Known issues:**
 * On page refresh (or when navigating directly to a page) the site navigation tree does not open nor select the corresponding topic
 * DONE: ~~Images need to be manually resized (or need to create some targeted scripting to resize)~~

**Comment by erictune** [comment]
I think the HEAD docs and the code need to live in the same branch.
  1. It is pretty convenient as a developer to be able to search the docs in the same subdir as the code.  I don't think a single git client can include stuff from multiple branches.
  1. It is nice when code changes are accompanied with doc changes in the same PR.  I don't think a single PR can cover changes from multiple branches.
 
Therefore, I think what needs to happen is when we make a release stable, we need to copy the docs from master to gh-docs.

So, at any moment in time, gh-pages has docs for the "stable" version release, and master has docs for what you call "unstable".

**Comment by RichieEscarez** [comment]
Hi @erictune,
I spoke to @brendandburns about this and in short, for the sake of simplicity in the long run, the decision was to continue as planned and separate the docs into the gh-pages branch. 

Search will be available in Kuberenets.io and the expectation is as the code stabilizes that eventually there will be fewer and fewer combined code and doc changes.

**Comment by erictune** [comment]
Your mockup for changes to kubernetes.io shows a left-nav with links to examples.  Will examples/ also be moving to gh-pages?

**Comment by bgrant0607** [comment]
Is this "move" or "copy"?

It is very useful to be able to update the documentation in the same PR as the code, and we should be moving more CLI and API documentation into the code. 

Additionally, if we move the generated files to another branch, we need to automate the process by which they are updated or they'll quickly become out of date.

**Comment by RichieEscarez** [comment]
@erictune yes, the plan is that all user facing doc will **move** to gh-pages, including examples.

@bgrant0607 about the CLI and API generated output, yes, good point. @brendandburns do you have any suggestions around automating the update process?

**Comment by bgrant0607** [comment]
I'm going to move user docs to docs/user-guide. #11093

**Comment by bgrant0607** [comment]
Decision: Copy, not move.

**Comment by bgrant0607** [comment]
cc @thockin @lavalamp

**Comment by lavalamp** [comment]
gh-pages should be considered an *output* of our release/documentation process. It's not appropriate to keep unversioned docs there, nor to send PRs to it that aren't part of a release process.

**Comment by bgrant0607** [comment]
Closing in favor of #11344.
