### ISSUE TITLE
Kubertenes with Vagrant instructions do not work

### ISSUE THREAD

**Issue by dorongrinstein** [GoogleCloudPlatform/kubernetes#9501]
On a Mac OS X v10.10.3 with Vagrant 1.7.1 and VirtualBox 4.3.28 r100309, after following the Kubernetes with Vagrant instruction page, when I do

export KUBERNETES_PROVIDER=vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox
export NUM_MINIONS=1
curl -sS https://get.k8s.io | bash

and then
vagrant ssh master

[vagrant@kubernetes-master ~]$ sudo systemctl status kube-apiserver

I get:

kube-apiserver.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

I am able to navigate to the Swagger endpoint
https://10.245.1.2/swagger-ui/#!/api/getAPIVersions

That seems to work. Can someone from the team explain what might I be doing wrong, or perhaps the documentation isn't up-to-date?

**Comment by roberthbailey** [comment]
Assigning to @derekwaynecarr

**Comment by dorongrinstein** [comment]
This is the same issue as 7683. I am closing this issue.
