### ISSUE TITLE
Can't see Shippable build results

### ISSUE THREAD

**Issue by ghodss** [GoogleCloudPlatform/kubernetes#9502]
I can't see the results of any Shippable builds, which means when a PR fails I have no idea why, and so it's quite hard to fix. No matter what build I try to look at, I get the below screen indefinitely, even with multiple reloads.

![screen shot 2015-06-09 at 12 11 36 pm](https://cloud.githubusercontent.com/assets/5209643/8067169/c895fcd2-0ea0-11e5-9ec8-9699df2a05cd.png)

**Comment by pmorie** [comment]
Unfortunately you have to be on the GCP gh team to see these.

**Comment by yifan-gu** [comment]
One workaround I tried before is to enable shippable build for your own fork of the project. Then you can see the results on your own fork.

But sometimes it will generate some spam messages to the k8s' irc channel (Not sure if this is fixed yet)

**Comment by hurf** [comment]
Same problem to me.

**Comment by hurf** [comment]
@yifan-gu I've tried to enable shippable build for my own fork, but it failed for non code reason. Do I need special settings in shippable.yml under root directory?

Part of the log message is as follows, do you have any idea of the error?

 ./hack/build-go.sh
    +++ [0611 11:04:21] Building go targets for linux/amd64:
        cmd/kube-proxy
        cmd/kube-apiserver
        cmd/kube-controller-manager
        cmd/kubelet
        cmd/hyperkube
        cmd/kubernetes
        plugin/cmd/kube-scheduler
        cmd/kubectl
        cmd/integration
        cmd/gendocs
        cmd/genman
        cmd/genbashcomp
        cmd/genconversion
        cmd/gendeepcopy
        examples/k8petstore/web-server
        github.com/onsi/ginkgo/ginkgo
        test/e2e/e2e.test
    +++ [0611 11:05:12] Placing binaries
     GOPATH=$PWD/Godeps/_workspace:$GOPATH go install ./...
    cluster/addons/dns/kube2sky/kube2sky.go:34:2: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/api" in any of:
    	/root/.gvm/gos/go1.4/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api (from $GOROOT)
    	/root/workspace/src/github.com/hurf/kubernetes/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api (from $GOPATH)
    	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api
    cluster/addons/dns/kube2sky/kube2sky.go:35:2: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/client" in any of:
    	/root/.gvm/gos/go1.4/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client (from $GOROOT)
    	/root/workspace/src/github.com/hurf/kubernetes/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client (from $GOPATH)
    	/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client

About the message spam in irc channel, I guess it can be turned off by deleting

    notifications:
      irc: "chat.freenode.net#google-containers"

lines in shippable.yml.

**Comment by yifan-gu** [comment]
@hurf It's the gopath problem, because now you are now under $GOPATH/src/hurf instead of $GOPATH/src/GoogleCloudPlatform.

Quick hack:
Add these two lines at the end of `before_install` in shippable.yml
```yaml
 - ln -s $GOPATH/src/github.com/hurf $GOPATH/src/github.com/GoogleCloudPlatform
 - cd $GOPATH/src/github.com/GoogleCloudPlatform/kubernetes
```

**Comment by hurf** [comment]
@yifan-gu, thanks, it works. But it brings new git problem. It seem shippable only recognize shippable.yml in master branch.

when shippable.yml is modified in master branch. It works fine

     **git checkout -f master --
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
     git reset --hard bc1fdb8e659f1d43fdfd9609976dbfc9987da339
    HEAD is now at bc1fdb8 Merge remote-tracking branch 'upstream/master'**
     echo "No .gitmodules file was found in the repository"
    No .gitmodules file was found in the repository
      before_install ✓ 1 seconds
     source $HOME/.gvm/scripts/gvm;
     if [[ $SHIPPABLE_GO_VERSION == "tip" ]]; then gvm install tip; gvm use tip; fi
     if [[ $SHIPPABLE_GO_VERSION == *release* ]]; then gvm install release; gvm use release; fi
     if [[ $SHIPPABLE_GO_VERSION =~ [0-9].[0-9] ]]; then gvm install go$SHIPPABLE_GO_VERSION; gvm use go$SHIPPABLE_GO_VERSION; fi
    Already installed!
    **Now using version go1.4
     export GOPATH=$SHIPPABLE_GOPATH
     ln -s $GOPATH/src/github.com/hurf $GOPATH/src/github.com/GoogleCloudPlatform
     cd $GOPATH/src/github.com/GoogleCloudPlatform/kubernetes
       install**

when modify shippable.yml in another branch, the change seems not be recoginzed.

     **git checkout -f FETCH_HEAD
     git merge origin/shippable_settings
    Merge made by the 'recursive' strategy.
     shippable.yml | 5 ++---
     1 file changed, 2 insertions(+), 3 deletions(-)**
     echo "No .gitmodules file was found in the repository"
    No .gitmodules file was found in the repository
      before_install ✓ 0 seconds
     source $HOME/.gvm/scripts/gvm;
     if [[ $SHIPPABLE_GO_VERSION == "tip" ]]; then gvm install tip; gvm use tip; fi
     if [[ $SHIPPABLE_GO_VERSION == *release* ]]; then gvm install release; gvm use release; fi
     if [[ $SHIPPABLE_GO_VERSION =~ [0-9].[0-9] ]]; then gvm install go$SHIPPABLE_GO_VERSION; gvm use go$SHIPPABLE_GO_VERSION; fi
    Already installed!
    **Now using version go1.4
     export GOPATH=$SHIPPABLE_GOPATH
      install**

So if I want to modify the shippable.yml in master branch, a commit A is generated. Then I create a new branch, and commit patch B. It works with shippable. But when I created a pr to GCP/kubernetes, both A and B are included in the pr. That troubles me for a long time, and still cann't find a way to solve this. Do you know how to deal with this situation?

**Comment by yifan-gu** [comment]
@hurf hmm, I can build on shippable with the shippable.yml in branches rather than master. But it's overall pretty bad experience. I think the reviewer will give you the shippable log if any.

**Comment by bgrant0607** [comment]
cc @kmerker

**Comment by ghodss** [comment]
Any feedback from Shippable on this? Is this something they are planning to fix, or are there any workarounds? It really slows down iterating on PR's when you don't know why your PR isn't passing Shippable.

**Comment by bgrant0607** [comment]
We believe this to be resolved.
