### ISSUE TITLE
kubectl uses "ID" rather than "Name" in help string

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#9511]
```
kubectl help delete
...
// Delete a pod using the type and ID specified in pod.json.
$ kubectl delete -f pod.json
...
```
In v1 there is no ID.  There is only UID and Name.

**Comment by manansaraf** [comment]
So if all the "ID" has to be replaced to "Name" in the help output, I can do it if no one else wants to do it

**Comment by feihujiang** [comment]
@manansaraf Do you start to work on this? If you have no time, I could work on this.

**Comment by manansaraf** [comment]
Sure go ahead
