### ISSUE TITLE
k8sm apiserver process failed to start on mesos master Centos-7-based node due to network issue

### ISSUE THREAD

**Issue by kcao3** [GoogleCloudPlatform/kubernetes#9512]
Hello,

I am trying to run Kubernetes, version 0.18.0 on my mesos clusters. I actually have two mesos clusters:
both are based on Centos7 OS. The first cluster I run from AWS and the second cluster I am running
from an isolated network environment. On both of my k8sm clusters, on the mesos-master node,
I start the apiserver process using the command as the following:

/opt/k8sm/bin/km apiserver \
--address=${servicehost} \
--etcd-servers=http://${servicehost}:4001 \
--service-cluster-ip-range=10.10.10.0/24 \
--port=8888 --cloud-provider=mesos \
--cloud-config=/opt/k8sm/mesos-cloud.conf \
--v=2 >apiserver.log 2>&1 &

On the mesos-master node from my first k8sm cluster, where it's running on AWS, I was able start the k8sm apiserver.
However, on the mesos-master node from my second k8sm cluster, where the nodes are running in an isolated network
environment but they can see one another, I got the following error starting the k8sm apiserver:

[root@floyd2 scripts]# cat apiserver.log
I0609 16:17:01.138172 23434 mesos.go:67] new mesos cloud, master='floyd2:5050'
I0609 16:17:01.141410 23434 standalone.go:46] creating new standalone detector for &MasterInfo{Id:master,Ip:168427778,Port:5050,Pid:master@floyd2:5050,Hostname:*floyd2,XXX_unrecognized:[],}
I0609 16:17:01.141514 23434 standalone.go:67] Detect()
I0609 16:17:01.141529 23434 standalone.go:69] spinning up asyc master detector poller
I0609 16:17:01.141552 23434 standalone.go:78] spawning asyc master detector listener
I0609 16:17:01.141604 23434 standalone.go:140] polling for master leadership at 'floyd2:5050'
I0609 16:17:01.141727 23434 standalone.go:80] waiting for polled to send updates
I0609 16:17:01.142035 23434 master.go:243] Node port range unspecified. Defaulting to 30000-32766.
F0609 16:17:01.142278 23434 master.go:264] Unable to find suitable network address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid this wait.

The following shows the current status of all the network interfaces of the mesos-master node:
[root@floyd2 scripts]# ifconfig
docker0: flags=4099 mtu 1500
inet 172.17.42.1 netmask 255.255.0.0 broadcast 0.0.0.0
ether 56:84:7a:fe:97:99 txqueuelen 0 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 0 bytes 0 (0.0 B)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

enp16s5: flags=4099 mtu 1500
ether 00:19:bb:cb:cc:ba txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 0 bytes 0 (0.0 B)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

enp3s0: flags=4163 mtu 1500
inet 10.10.1.2 netmask 255.255.255.0 broadcast 10.10.1.255
inet6 fe80::221:5aff:fed5:9a24 prefixlen 64 scopeid 0x20
ether 00:21:5a:d5:9a:24 txqueuelen 1000 (Ethernet)
RX packets 1467975 bytes 373164041 (355.8 MiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 970980 bytes 296110995 (282.3 MiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73 mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10
loop txqueuelen 0 (Local Loopback)
RX packets 5294668 bytes 533618577 (508.8 MiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 5294668 bytes 533618577 (508.8 MiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

To avoid conflict IPs, I even tried to change the service-cluster-ip-range flag to something else
(such as 192.0.0.0/24) but it did not make any difference. I also turned off all the firewall but that did
not help either.

The error from the apiserver.log led me to retrieve the source code for master.go:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go

Again, I was able to run this k8sm apiserver process from one machine but not the other.
Both of these machine are Centos-7 based.

So the following are my questions:
1. Does anyone know the root cause for this error?
2. Does anyone know why the k8sm apiserver program failed to "select an IP"?
3. Does anyone know if there is a way to debug the k8sm apiserver program?

Thank you very much in advance for your help.

**Comment by jdef** [comment]
This was a network configuration problem on the user's host (I've xref'd the issue w/ the details). It's been resolved.

**Comment by liaoqb** [comment]
How to solve this problem, can you give a more detailed answer for me ????
