### ISSUE TITLE
Restart policy Never rejected in v1 API Call

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#9526]
The RC:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: cauldron
  namespace: default
spec:
  replicas: 1
  selector:
    app: cauldron
  template:
    metadata:
      labels:
        app: cauldron
    spec:
      containers:
      - name: cauldron
        image: kubernetes/cauldron:1.0
        imagePullPolicy: Always
      restartPolicy: Never
```
Attempt to create:
```
$ kubectl create --validate -f cauldron-rc.yaml
I0609 15:32:53.898176    8328 schema.go:160] field detail &{{0xc208431050 <nil>   []   0xc208434be0 <nil>} list of containers belonging to the pod; cannot be updated; containers cannot currently be added or removed; there must be at least one container in a Pod}
The ReplicationController "cauldron" is invalid:spec.template.restartPolicy: spec.template.restartPolicy: unsupported value 'Never'
make: *** [rc] Error 1
```
Fails even without the `--validate` flag.

**Comment by dchen1107** [comment]
@satnam6502 I think kubernetes does the right thing here. From doc: https://github.com/GoogleCloudPlatform/kubernetes/blob/a58847e45d4bd996564d6c5fae8169864b8a2ac7/docs/replication-controller.md

"ReplicationController is only appropriate for pods with RestartPolicy = Always (Note: If RestartPolicy is not set, the default value is Always.). ReplicationController should refuse to instantiate any pod that has a different restart policy. "

**Comment by satnam6502** [comment]
Well part of my complaint was about the hex in the error message.

**Comment by satnam6502** [comment]
As for RC, I guess I wanted a different kind of controller which "launches N pods and waits for each to run to completion".

**Comment by thockin** [comment]
Validation errors should NOT include %v object dumps - this is terrible UX.

**Comment by satnam6502** [comment]
The spurious hex output issue has now been resolved by another PR I merged earlier today.

**Comment by lavalamp** [comment]
You want a 'job controller'. RC doesn't offer this feature, it's only for long-running services.

**Comment by satnam6502** [comment]
Indeed. I offer to write one after 1.0. Indeed, I have an urge to write lots of new kinds of controllers.
