### ISSUE TITLE
kubectl describe outputs unnecessary warning messages.

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#9546]
$ kubectl describe po apache1
    W0610 01:17:14.439254   28086 request.go:302] field selector: v1 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
    W0610 01:17:14.439399   28086 request.go:302] field selector: v1 - events - involvedObject.uid - cee7253e-0e8a-11e5-b63e-fa163e837eb3: need to check if this is versioned correctly.
    W0610 01:17:14.439442   28086 request.go:302] field selector: v1 - events - involvedObject.name - apache1: need to check if this is versioned correctly.
    Name:				apache1
    Image(s):			test/apache:1
    ...

This happens with #9462

**Comment by hurf** [comment]
I looked into the code and found it's because client is using v1 api version now, but `resourceTypeToFieldMapping` didn't provide a key for v1.

[https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request.go#L314][1]
[1]: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request.go#L314

**Comment by hurf** [comment]
[https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request.go#L301][1]
[1]: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request.go#L301

for those fields don't need converting, no need to send a warning message.

**Comment by marekbiskup** [comment]
Please also resolve this inconsistency:

```
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ cluster/kubectl.sh describe node/asdf
Error from server: minion "asdf" not found
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ cluster/kubectl.sh describe node asdf
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ echo $?
0
```

 1. error is found in the first case, but not in the second one
 1. the word `minion`

**Comment by nikhiljindal** [comment]
The field selector error is being fixed in https://github.com/GoogleCloudPlatform/kubernetes/pull/9966

**Comment by bgrant0607** [comment]
Missed from #7018 and #8087

**Comment by bgrant0607** [comment]
@marekbiskup Please file another issue for the describe node problem.

**Comment by marekbiskup** [comment]
Reported #10156 for my first comment here

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9966 is now submitted and you should not be getting those error messages any longer.
