### ISSUE TITLE
the wrong doc URL shown when NodePort service is created

### ISSUE THREAD

**Issue by gongysh2004** [GoogleCloudPlatform/kubernetes#9566]
$ cat nginx-service-nodeport.yaml 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  clusterIP: 192.168.3.84
  selector:
    name: nginx
  type: NodePort

$ kubectl -s http://192.168.0.201:8080 create -f ./nginx-service-nodeport.yaml 

				You have exposed your service on an external port on all nodes in your cluster.
				If you want to expose this service to the external internet, you may need to set up
				firewall rules for the service port(s) (tcp:8000) to serve traffic.
				
				See https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/services-firewall.md for more details.
				services/nginx-service-nodeport

two bugs:
1. tcp:8000 should be tcp:nodeport, since the nodeport is the external exposed port
2. the https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/services-firewall.md should be
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/services-firewalls.md
i.e. services-firewalls instead of services-firewall

**Comment by gongysh2004** [comment]
I am working on it.. correct result should be:
$ kubectl -s http://192.168.0.201:8080 create -f ./nginx-service-nodeport.yaml 

				You have exposed your service on an external port on all nodes in your cluster.
				If you want to expose this service to the external internet, you may need to set up
				firewall rules for the service port(s) (tcp:31592) to serve traffic.
				
				See https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/services-firewalls.md for more details.
				services/nginx-service-nodeport

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by thockin** [comment]
PR is in flight and LGTM

**Comment by brendandburns** [comment]
Closed by #10134
