### ISSUE TITLE
kubectl run-container has changed to run

### ISSUE THREAD

**Issue by andronat** [GoogleCloudPlatform/kubernetes#9577]
Isn't this `run` instead of `run-container` at 0dfb681ba5d5dba535895ace9d650667904b5df7?

It is changed from: #8319 and #8596

/cc @brendandburns

**Comment by brendandburns** [comment]
@andronat those instructions referred to an old hyperkube image (v0.17.0) and so I needed to preserve them.  

https://github.com/GoogleCloudPlatform/kubernetes/pull/9651

has the complete update.
