### ISSUE TITLE
TestCreateCleanWithPrefix fails if KUBERNETES_MASTER is set

### ISSUE THREAD

**Issue by andronat** [GoogleCloudPlatform/kubernetes#9578]
This test fails when the testing environment has the `KUBERNETES_MASTER` declared.

```
--- FAIL: TestCreateCleanWithPrefix (0.00s)
	client_config_test.go:228: Expected "http://localhost:8080", got "10.1.2.3:8080"
FAIL
```

```
$ echo $KUBERNETES_MASTER
10.1.2.3:8080
```

A similar case was here: #8646

I am not sure which is the correct way to fix this. Any suggestions?

/cc @jdef (4b8995f0093369465f728e686416b52f8b10b0a8)

**Comment by jdef** [comment]
how about this: add a bool flag (default of `false` is desired) to the `DirectClientConfig` struct:
- `type DirectClientConfig struct { ... ignoreEnvironmentConfig bool }`
- alter `DirectClientConfig.getCluster()` to check that flag and ignore `EnvVarCluster` if set
- alter the failing test case such that it directly creates the `DirectClientConfig` instance, and sets the flag to true
