### ISSUE TITLE
Modify redis guestbook example to use a term other than 'slaves'

### ISSUE THREAD

**Issue by amygdala** [GoogleCloudPlatform/kubernetes#9593]
I'd like to see us avoid the use of the term 'slave' in the guestbook redis stuff where possible.
Maybe use 'minion' instead for all the names and labels.
As part of this, the frontend image (kubernetes/example-guestbook-php-redis:v2) will need to be rebuilt, since it references 'redis-slave' in the php script.

**Comment by goltermann** [comment]
This is a Redis term, for what it's worth.  http://redis.io/topics/replication  We still may or may not want to change what we use.

**Comment by amygdala** [comment]
yeah, I know... I still constantly wince, though, and suspect many others do the same.

**Comment by satnam6502** [comment]
If we are going to get rid of `salve` then do we also need to get rid of `master`?

**Comment by amygdala** [comment]
After discussion w/ Brendan, we're going to punt on doing this, at least for now.
