### ISSUE TITLE
kube-addons.sh hardcoded kubectl path

### ISSUE THREAD

**Issue by jeffbean** [GoogleCloudPlatform/kubernetes#9599]
`cluster/saltbase/salt/kube-addons/kube-addons.sh` has a hardcoded bin path. This is not the path for yum installed Kubernetes and maybe more cases.

Should be a variable at least. similar to `kube-addon-update.sh`.

**Comment by alex-mohr** [comment]
I think @jlowdermilk has the most kubectl context and can figure out something reasonable to do here?
