### ISSUE TITLE
Scheduler doesn't exclude terminated or succeeded pods when scheduling

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#9601]
Pods that are terminated or in success are no longer running, so they shouldn't be included in the scheduler's decisions.

**Comment by davidopp** [comment]
What is the behavior you're observing? That a terminated/succeeded pod that is not running under a replication controller comes back to life on a new node?

**Comment by lavalamp** [comment]
No-- he means that the scheduler think that pods in those states are consuming resources when in fact they aren't.

**Comment by brendandburns** [comment]
Closed by #9613
