### ISSUE TITLE
New mergo version breaks config merging

### ISSUE THREAD

**Issue by jseaidou** [GoogleCloudPlatform/kubernetes#9621]
We were accidentally using the HEAD of mergo and found that it breaks the assumptions of merge. If a field in the config is not empty, the overwrite will not override. Before making a change, I was curious if upgrading the version is something the project will require or are we comfortable having it pinned at this version

**Comment by mikedanese** [comment]
I've had some issues with mergo before (see #4008 #4416). Personally, I'm comfortable with leaving it pinned, until it doesn't work for us, at which point we could remove it altogether. I mean it's _just_ one method.

**Comment by jseaidou** [comment]
@mikedanese Fair enough. I will close the ticket.

**Comment by imdario** [comment]
How can I help you? Maybe I introduced a bug through a pull request and it wasn't detected by my testing suite.

**Comment by mikedanese** [comment]
@imdario if you'd like, you could bumb the version of Mergo that we are using to your HEAD and see which tests break and why. you can run tests from the root of the project by running `make test`. Were there any breaking api changes recently merged into Mergo?

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/Godeps/Godeps.json#L347-L351
