### ISSUE TITLE
Proposal for extending kubectl get [resource] by printing resource labels as extra columns

### ISSUE THREAD

**Issue by andronat** [GoogleCloudPlatform/kubernetes#9631]
### **Proposal**

After finishing with #9032, we can also add resource labels as extra columns when we print resources. 

The user could define in a flag `--label-column=` or `-l` the names of the labels that he wants to print, and then **kubectl will append extra columns in the end of each resource row**. 

The extra column will use:
* as header-column name --> the label name
* as per row value --> the label value for each resource

For labels:
* names can be both in lowercase or uppercase
* non-recognized labels will return `<n/a>` to explicitly declare that this label is not available in this resource _(as labels are strings, we can differentiate empty string "" with non-existing label)_ **???**
* declaration order on the command reflects on printing

### **Example**
```
$ kubectl get pods --label-column=version,deployment
NAME             READY     REASON    RESTARTS   AGE  VERSION  DEPLOYMENT
my-nginx-00jsd   0/1       Pending   0          ~1m  v1       2016-01-01
my-nginx-7kqqp   0/1       Pending   0          ~1m  v1       2016-01-01
my-nginx-fb2s6   0/1       Pending   0          ~1m  v2       2016-01-02
```

/cc @ghodss 

*I will update this comment during the conversation with the latest scheme we have agreed on. This first proposal is just to initialise a conversation.*

**Comment by ghodss** [comment]
@bgrant0607 @brendandburns

**Comment by ghodss** [comment]
It would be nice to reserve a single letter for this flag if there's one available that makes sense. `-l version,deployment` would be really convenient.

**Comment by andronat** [comment]
Added `-l` to the proposal

**Comment by andronat** [comment]
Sorry `-l` is already being used. I replaced it with `-z`.

Also, are all labels capital? Do we to be case-sensitive? Should I capitalise all input from user?

**Comment by bgrant0607** [comment]
Label validation is here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L56

Labels are not all capitals. For the column header, I'd strip off the key namespace and capitalize the key. We should output the label values as is.

It should be possible to specify the same command-line option multiple times. We might also want to support a single option containing a list, but multiple options should work as well.

What characters are available for the short flag other than `z`?

**Comment by ghodss** [comment]
I like the idea to specify multiple items through the same option multiple times. Does cobra support that? Do we have a convention established yet for specifying multiple items?

**Comment by andronat** [comment]
@bgrant0607 
> I'd strip off the key namespace and capitalize the key

Sorry, does that mean split the label string at `/` keep the last part and capitalise it? Or keep the first part and capitalise it?

> It should be possible to specify the same command-line option multiple times

This is not possible in cobra ATM. I can open a ticket though and I can also work on it if you want.

> What characters are available for the short flag other than z?

Currently `-h` `-o` `-l` `-t` `-w` and `-s` are used.

**Comment by bgrant0607** [comment]
Re. same option multiple times: Yes, that works. We do that for `-f`. See, for example, create:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/create.go#L47

Re. namespace: Yes, split at `/`, keep the last part, and capitalize it.

Re. short flags: We want to use flags consistently across commands, where possible, so please look at other commands to see which short flags we've used. Maybe grep for `cmd.Flags()`. Maybe `-k` for "key"?

**Comment by andronat** [comment]
Flags used: `-f`, `-p`, `-P`, `-r`, `-c`, `-h`, `-o`, `-l`, `-t`, `-w`, and `-s`. `-k` is free or we can even use `-L`?

Namespace: Done

Multipleflags: Sorry I didn't see that. Done on the current commit

I will squeeze the commits when you are ready to merge.

**Comment by bgrant0607** [comment]
I like `-L`
