### ISSUE TITLE
Add link to kubectl.md in Getting Started Guide

### ISSUE THREAD

**Issue by goltermann** [GoogleCloudPlatform/kubernetes#9632]
Suggest we link to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl.md in the getting started guides.  Anyone standing up their first cluster is going to want to play around with all the kubectl options, and this is a useful reference page.

**Comment by bgrant0607** [comment]
We could copy the relevant text from https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md#installing-the-kubernetes-command-line-tools-on-your-workstation to other guides.

**Comment by bgrant0607** [comment]
Probably a link to the new user guide (docs/user-guide) would be better, once we have a TOC doc for it (Monday, hopefully).

**Comment by bgrant0607** [comment]
We should copy that text about installing kubectl to docs/user-guide/prereqs.md
