### ISSUE TITLE
Prevent concurrent GetContainerInfo requests from hitting docker

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#9641]
GetPods(https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L722) can be quite slow when we get a flurry of requests on the /stats endpoints. A snippet from my logs https://gist.github.com/bprashanth/20559b465c6fbea72ebb. It also seems to slow down other docker operations, a concurrent generatePodStatus takes ~2s.

Can we teach GetContainerInfo about the runtime cache? I mean replace this line: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2180
with:

```go
	pods, err := kl.runtimeCache.GetPods(false)
	if err != nil {
		return nil, err
	}
	pod := kubecontainer.Pods(pods).FindPod(podFullName, podUID)
	return pod.FindContainerByName(containerName), nil
```

/ref https://github.com/GoogleCloudPlatform/kubernetes/issues/3954

**Comment by yifan-gu** [comment]
The answer I think is yes as long as the consumer of the information can tolerate the slightly older data (2 seconds older than real for now).

**Comment by gmarek** [comment]
@gmarek

**Comment by bprashanth** [comment]
@vmarmol maybe has thoughts

**Comment by bprashanth** [comment]
Closed via referenced pr
