### ISSUE TITLE
Unable to mount localPath volume

### ISSUE THREAD

**Issue by casusbelli** [GoogleCloudPlatform/kubernetes#9657]
Hello!
I've been trying to play through the persistent-volumes example running a hack/local-up-cluster.sh setup. In several setups i always ended up with nginx serving me the default start page but not the index.html file from the volume to be mounted in the container at /var/www/html/ .

```
[root@kaisers cluster]# ./kubectl.sh get services
NAME              LABELS                                    SELECTOR            IP(S)       PORT(S)
frontendservice   <none>                                    name=frontendhttp   10.0.0.36   3000/TCP
kubernetes        component=apiserver,provider=kubernetes   <none>              10.0.0.1    443/TCP
[root@kaisers cluster]# curl 10.0.0.36:3000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

I used a standard docker nginx image, as the example did not specify otherwise, any ideas on what went wrong? The single difference i could see between the example and my outputs  was that my output showed:

```
NAME      LABELS       CAPACITY      ACCESSMODES   STATUS    CLAIM               REASON
pv0001    type=local   10737418240   RWO           Bound     default/myclaim-1   
```

which has a different LABELS value, the example shows:

```
NAME                LABELS              CAPACITY            ACCESSMODES         STATUS    CLAIM
pv0001              map[]               10737418240         RWO                 Bound     myclaim-1 / 6bef4c40-e50b-11e4-972f-80e6500a981e                               
```

In the logs i could find the following error comment (kubelet.log): 

```
I0611 09:57:07.584766    9759 manager.go:271] Container inspect result: {ID:d3e60b9f547aeebbf7be0547c873cd4001a0cc6058ad79b2e9d3a40ffe8899b5 Created:2015-06-11 07:54:59.022027925 +0000 UTC Path:nginx Args:[-g daemon off;] Config:0xc2082f0480 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:11290 ExitCode:0 Error: StartedAt:2015-06-11 07:55:00.374922302 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:a785ba7493fd9009be71023045790697f334486b11a45f7e830652d39665a451 Node:<nil> NetworkSettings:0xc2089c5590 SysInitPath: ResolvConfPath:/var/lib/docker/containers/c80aa508836443ce8969a0545dd182a719e8b05b27deedc0a63bb33da13ab96d/resolv.conf HostnamePath:/var/lib/docker/containers/c80aa508836443ce8969a0545dd182a719e8b05b27deedc0a63bb33da13ab96d/hostname HostsPath:/var/lib/docker/containers/c80aa508836443ce8969a0545dd182a719e8b05b27deedc0a63bb33da13ab96d/hosts Name:/k8s_myfrontend.8d4e3c81_mypod_default_272a41e7-100f-11e5-b9e5-3417ebaec833_5a3aced1 Driver:devicemapper Volumes:map[/dev/termination-log:/var/lib/kubelet/pods/272a41e7-100f-11e5-b9e5-3417ebaec833/containers/myfrontend/d3e60b9f547aeebbf7be0547c873cd4001a0cc6058ad79b2e9d3a40ffe8899b5 /var/cache/nginx:/var/lib/docker/vfs/dir/4b65b1bac70b5ef1fe324491cbfbf32cfc63646a539c1ac9ee48cbec88629eea /var/run/secrets/kubernetes.io/serviceaccount:/var/lib/kubelet/pods/272a41e7-100f-11e5-b9e5-3417ebaec833/volumes/kubernetes.io~secret/default-token-rd5nk /var/www/html:/prod/silvan] VolumesRW:map[/dev/termination-log:true /var/cache/nginx:true /var/run/secrets/kubernetes.io/serviceaccount:false /var/www/html:true] HostConfig:0xc2080fe1e0 ExecIDs:[] AppArmorProfile:}
```
 but no other issues / hints.

Any ideas if this is misconfiguration or if the example has issues?

**Comment by markturansky** [comment]
@casusbelli The examples referenced in the PV README work.  Those are my test/dev examples :)

I see your volume's path ```/var/www/html:/prod/silvan```

Is that directory accessible by Kubelet?  selinux enabled?

**Comment by casusbelli** [comment]
Thanks for the feedback!
Yep, the path is accessible, and I tried also with the examples local /tmp/data-01/ path because /prod/ is a mounted distributed storage volume . Results where the same. 
SeLinux is in permissive mode, it's a CentOS 7 box.

**Comment by markturansky** [comment]
Would you mind sharing your pv, claim, and pod json/yaml?

**Comment by casusbelli** [comment]
In the end I simply ran the example files directly from the git directory as I couldn't find out what was wrong with my config. No modifications. 
When that didn't work I filed this ticket. :-D

In essence I did a checkout from GitHub , ran hack/run-local.sh and followed on with the example, everything as root. 
(I'm currently on my mobile, shellscript name might be misspelled).

**Comment by brendandburns** [comment]
I think the Docker nginx (https://registry.hub.docker.com/_/nginx/) uses ```/usr/share/nginx/html``` not ```/var/www/html```  judging from the examples given on the hub's page.

**Comment by casusbelli** [comment]
Bang on, path in the image was different!
 _sigh_
Thanks a lot Mark & Brendan !!
