### ISSUE TITLE
Reduce  container ID in event to 12 characters

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#9661]
Event logs the full ID of containers, it takes lot of places in the screen and make it hard to read other useful information.

    Thu, 11 Jun 2015 11:34:50 +0000   Thu, 11 Jun 2015 11:34:50 +0000   1         nginx-controller-6df80   Pod                     spec.containers{nginx}              killing            {kubelet 127.0.0.1}         Killing 08b2ba60914f1997d22669d2c1bce174fb9154350e143a224b48808a939f9072
    Thu, 11 Jun 2015 11:35:23 +0000   Thu, 11 Jun 2015 11:35:23 +0000   1         nginx-controller-904vw   Pod                     implicitly required container POD   started            {kubelet 127.0.0.1}         Started with docker id 381491cf5002fed558ae809db44a391755dbd0ccb1e722d1d0241bf58cbd298d

When using `docker ps`, it shows only the first 12 characters of the id, and `docker inspect` can take this as parameter or auto completing the full ID.

    $ docker ps
    CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS              PORTS               NAMES
    381491cf5002        gcr.io/google_containers/pause:0.8.0   "/pause"               7 minutes ago       Up 7 minutes                            k8s_POD.ef28e851_nginx-controller-904vw_default_f28c9688-102d-11e5-beea-fa163e837eb3_c3f25fb1
    $ docker inspect 381491cf5002
    $ docker inspect 381491cf5002fed558ae809db44a391755dbd0ccb1e722d1d0241bf58cbd298d 

Can we do the same thing as docker do, any put more detailed information in the event as mentioned in #6532?

**Comment by brendandburns** [comment]
I think we'd happily take a PR to do this... ;)

**Comment by piosz** [comment]
Fixed by #9706. Thanks @hurf!
