### ISSUE TITLE
E2E: Modify networking.go to verify containers (rather than client) can access internet.

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#9662]
From a recent thread https://groups.google.com/forum/#!topic/google-containers/aDdYFLcQxk4 , it looks  like we can modify networking.go to do a test of external connectivity which is actually useful :). 

The snippet im suggesting we replace ... 

```
resp, err := http.Get("http://google.com")
		if err != nil {
			Failf("Unable to connect/talk to the internet: %v", err)
		}
		if resp.StatusCode != http.StatusOK {
			Failf("Unexpected error code, expected 200, got, %v (%v)", resp.StatusCode, resp)
		}
```

... in its place, we should write a test w/ a  simple pod which pings google **FROM INSIDE A CONTAINER** and prints "SUCCESS" after its done, then grep for the SUCCESS string.

**Comment by timothysc** [comment]
report sure.. but many people want an air-gaped cluster.

**Comment by jayunit100** [comment]
Yeah .... 
This might be a warning report rather than an error.

**Comment by piosz** [comment]
Increasing priority due to regression #10281
