### ISSUE TITLE
What storage driver (& kernel & OS) should AWS use?

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#9675]
I have struggled to find a filesystem/kernel for AWS that really works well.

* GCE uses wheezy with a custom kernel and aufs, but aufs seems like a dead-end: it isn't in the kernel and looks like it never will be AFAICT.  Getting GCE's kernel onto AWS would likely be work, both one-off and ongoing (?).

* overlayfs seems like the future of aufs, but is only in newer kernels

* if we're going to use a newer kernel, btrfs has a lot of benefits if it works.  It is definitely _more_ reliable in newer kernels.

* I never got devicemapper to work.  It apparently needs a custom-build of Docker (dynamically linked?)

I think the actual OS is driven more by the kernel.  Ubuntu seems to make it a bit easier to run newer longterm kernels, so I've been using that.  Ubuntu with btrfs seems to work pretty well, although I still hit the disk-full problem which was supposed to be fixed in 3.18 (though I may be missing an option or may need to install the latest tools or something of that nature).

**Comment by erictune** [comment]
Btrfs looks like it has some benefits in the desktop and "pet" server scenarios.  However, the benefits appear reduced in the Kubernetes environment:
  - Atomic COW snapshots: this is useful for backups, but you shouldn't need to backup your node because it can be recreated.
  - Per-block checksumming: nice, but, again, nodes can be reimaged or replaced if they start acting weird; persistent volumes are backed by a cluster file system that already has software level reduncancy.
  - Volume management: what are partitions for when you have images?

I'd opt for stability over features I probably don't need.

**Comment by iterion** [comment]
CoreOS defaults to ext4 + overlayfs which gets us away from btrfs. But, I think there is some work needed to get the master running on CoreOS.

**Comment by justinsb** [comment]
I have done a lot of investigation, and here is what I have found:

* Ubuntu 14.04 images include a fairly old kernel.  Lots of "random" e2e tests failures with aufs enabled (20% failures?).  They mostly pass with btrfs, but the older kernel version has issues with the disk being full when it is not.

* Debian Wheezy images have a kernel that is just too old; Docker doesn't officially support it.

* Debian Jessie images have a newer kernel, and this would be a good option, but you have to set some boot options and reboot.

* Vivid Vervet seems to work pretty well - no reboot needed, but it uses systemd and our salt version is super-buggy with systemd at least on 15.04.  These Salt problems do not appear to have been fully resolved.  But if we can get past the Salt problems, it looks like a fairly good choice: aufs, overlayfs & btrfs look like they will all work.

The options are: Vivid Vervet with some salt work, or 14.04/Wheezy/Jessie & upgrade the kernel/boot-options with either a reboot or a custom AMI.

Rebooting is painful, both for users and for our e2e tests.  Our "up" scripts don't do particularly well with a reboot in the middle, though they largely tolerate it (which is impressive!)  I think the most sensible thing would be to reboot just before starting salt, and rely on salt being configured to auto-start on next boot.  This does then mean that the kernel upgrade would have to be done outside of salt.

Making our own AMI is not fun either, particularly because then someone is then on the hook for upgrading it every time they find a vulnerability in overlayfs ;-)

I propose to make Vivid Vervet the default for Kubernetes Version 1; we've been running with Ubuntu anyway as the default.  I'll add a kernel upgrade with reboot to the other platforms if I have time, but I don't think it is critical path.  There's some Salt work for Vervet but I have it sitting in a branch that I will tidy up, and it works great if I essentially pull systemd management out of salt (#9892)

I personally favor btrfs; I agree that we don't need the benefits but I think containers are based around volumes sharing files and btrfs gets this right, with snapshots and copy-on-write files.  I agree entirely @erictune that we shouldn't care about backups here.  (I think it is important for persistent volumes, but I think that's a separate concern).  My view is that checksumming is particularly useful if you can just panic and throw away the container / machine; and that volume management is _really_ useful on EC2 which for some reason decides to present its instance storage as multiple devices - it is much more convenient to combine them using btrfs than it is to do LVM as well.

But... I think with vivid vervet the storage mechanism can be the user's choice.  We can even make aufs the default so it's closer to GCE :-)

**Comment by bkeroackdsc** [comment]
CoreOS works well on AWS with k8s. Bootstrapping the cluster via cloud-config is quite simple and eliminates the need for salt and opaque automation scrips.
