### ISSUE TITLE
API server hangs with --etcd-config

### ISSUE THREAD

**Issue by mnemotiv** [GoogleCloudPlatform/kubernetes#9711]
If I'm using --etcd-servers=http://127.0.0.1:2379 - API server starts normally.

If I'm using --etcd-config=/var/lib/etcd/etcd.json - API server hangs right after publishing swagger log lines and doesn't publish/bind ports and API server process stays "hanged" here without any errors.

```
{
  "cluster": {
    "leader": "http://127.0.0.1:2379",
    "machines": [
      "http://127.0.0.1:2379"
    ]
  },
  "config": {
    "certFile": "",
    "keyFile": "",
    "caCertFiles": [],
    "timeout": 5,
    "consistency": "STRONG"
  }
}
```

I've tried with all certificate files, https protocol and etcd with https/certs also - same  problem with etcd-config.

CoreOS alpha: 695.0.0 and 709.0.0 (this happens on both versions).
Kubernetes: 0.18.0 , 0.18.1 , 0.18.2

**Comment by mnemotiv** [comment]
Why v1.0-post milestone? How to make a secure ectd<->k8s once v1 is out?

**Comment by nikhiljindal** [comment]
I just ran ```./hack/local-up-cluster.sh --etcd-config=/tmp/etcd.json``` on HEAD and my local cluster came up fine.

@mnemotiv Does it work for you on HEAD?

**Comment by mnemotiv** [comment]
@nikhiljindal no, it doesn't:
```
14990 plugins.go:69] No cloud provider specified.
```
now it stops earlier without even publishing swagger info to logs.

https://github.com/GoogleCloudPlatform/kubernetes/pull/9390 - go-etcd client updated
https://github.com/GoogleCloudPlatform/kubernetes/pull/9447 - reverted the above due to failed tests
maybe this is related - we need an updated go-etcd

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9862 is updating go-etcd.

@mnemotiv Doesnt look like you are using local-up-cluster.sh to bring up your cluster. Can you specify the exact command you are running?

**Comment by mnemotiv** [comment]
@nikhiljindal I'm running on VPS machines with CoreOS latest alpha, not a virtual machines on my laptop. I want to ensure that it runs on bare-metal, not on only dev-laptop

**Comment by mnemotiv** [comment]
Etcd2 is fully accessible for all other services via http://127.0.0.1:2379

The etcd config json file above doesn't work and kube-apiserver doesn't shout out any errors at all.

```bash
/opt/bin/kube-apiserver \
--bind-address=${FLANNEL1_IPV4} \
--secure-port=6443 \
--insecure-bind-address=127.0.0.1 \
--insecure-port=8080 \
--authorization-mode=AlwaysAllow \
--client-ca-file=/etc/ssl/etcd/ca.crt \
--tls-cert-file=/etc/ssl/etcd/master.host.crt \
--tls-private-key-file=/etc/ssl/etcd/master.host.key \
--kubelet-certificate-authority=/etc/ssl/etcd/ca.crt \
--kubelet-client-certificate=/etc/ssl/etcd/master.host.crt \
--kubelet-client-key=/etc/ssl/etcd/master.host.key \
--kubelet-https=true \
--kubelet-port=10250 \
--etcd-prefix=/kubernetes.io \
--old-etcd-prefix=/registry \
--etcd-config=/var/lib/etcd/etcd.json \
--service-cluster-ip-range=10.2.0.0/16 \
--allow-privileged=true \
--profiling=false \
--event-ttl=24h \
--logtostderr=true
```

**Comment by mnemotiv** [comment]
How I'm dumb, timeout is in nanoseconds... it should be at least x100000-x1000000000 times bigger. Sorry.
