### ISSUE TITLE
AWS: CreateTCPLoadBalancer fails with 2 subnets in the same AZ.

### ISSUE THREAD

**Issue by iterion** [GoogleCloudPlatform/kubernetes#9718]
I ran into an issue today when trying to create an externally load balanced service on AWS. It appears that when we create a ELB on AWS we just pull all of the subnets in the VPC and pass those to the creation of the ELB. AWS complains with `ELB cannot be attached to multiple subnets in the same AZ.`

In my setup I had 3 subnets (2 of which were not actually used by the cluster) and 2 of those subnets were in us-east-1a. The workaround for now is easy, just recreate one of my subnets in a different AZ.

Perhaps we should be smarter about choosing what subnets are passed to the ELB? Maybe try to determine what subnets are actually used by the cluster?
Thoughts @justinsb?

```
I0612 15:58:06.606804       5 servicecontroller.go:202] Got new Sync delta for service: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:vapor-web2 GenerateName: Namespace:default SelfLink:/api/v1beta3/namespaces/default/services/vapor-web2 UID:dc384902-1077-11e5-bdba-0e2fba11dd83 ResourceVersion:381386 CreationTimestamp:2015-06-11 20:24:28 +0000 UTC DeletionTimestamp:<nil> Labels:map[role:web2 app:vapor] Annotations:map[]} Spec:{Ports:[{Name:web Protocol:TCP Port:80 TargetPort:{Kind:1 IntVal:0 StrVal:web} NodePort:30213} {Name:web-ssl Protocol:TCP Port:443 TargetPort:{Kind:1 IntVal:0 StrVal:web-ssl} NodePort:31206}] Selector:map[role:web2 app:vapor] ClusterIP:10.0.253.191 Type:LoadBalancer DeprecatedPublicIPs:[] SessionAffinity:None} Status:{LoadBalancer:{Ingress:[]}}}
E0612 15:58:06.741159       5 servicecontroller.go:167] Failed to process service delta. Retrying: failed to create external load balancer for service default/vapor-web2: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
I0612 15:58:06.775169       5 servicecontroller.go:283] Creating LB for service default/vapor-web2
I0612 15:58:06.777364       5 aws.go:1433] CreateTCPLoadBalancer(aaaaaaaaaaaaaa, us-east-1, <nil>, [0xc208c03f40 0xc208c03f90], [ip-172-20-0-10.ec2.internal ip-172-20-0-11.ec2.internal ip-172-20-0-12.ec2.internal ip-172-20-0-13.ec2.internal])
```

**Comment by justinsb** [comment]
Nice find.  I think I have fixed this (accidentally) although I'm not sure whether it has made it into a release yet.  We should be tagging the subnet with a tag Name=KubernetesCluster, Value=${clusterid}, and then we should be filtering on that.  Are you running on a build that includes this: https://github.com/GoogleCloudPlatform/kubernetes/commit/33a3d884f23e5a449397450cef55340adfa46bd9

And if so, how are you subnets tagged (i.e. did I make a mistake?)

**Comment by iterion** [comment]
I'm actually starting up a new cluster now with latest master and found a couple small script issues that slowed me down. I'll have some PR's up for those shortly :).

It looks like 33a3d88 might have resolved the issue, but I'll try to recreate the same scenario with a new cluster and get back to you here.

**Comment by iterion** [comment]
@justinsb looks like you were right about 33a3d88! I started a new cluster and recreated subnets in the same way I had them before and everything is working fine. Closing this since it's already been fixed in master.

**Comment by manojlds** [comment]
How does kubernetes know what the `clusterid` is?

**Comment by krancour** [comment]
I have a similar question to @manojlds.  Where can I find the cluster id?  I have been digging through k8s docs and googling and I can't find any useful information on how one can determine a cluster's id.

**Comment by justinsb** [comment]
The clusterid is set on the KubernetesCluster tag on all resources (VPCs, subnets, instances etc); it is how we know what instances are owned by a particular k8s cluster.

It is controlled by the KUBE_AWS_INSTANCE_PREFIX environment variable passed to kube-up (see cluster/aws/config-default.sh).

More details on how this works are here: https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md

**Comment by krancour** [comment]
@justinsb, thanks for the info!  Got it.
