### ISSUE TITLE
Missing validation for Service.Spec.Ports.TargetPort

### ISSUE THREAD

**Issue by sdminonne** [GoogleCloudPlatform/kubernetes#9734]
Original openshift issue https://github.com/openshift/origin/issues/3143
If Service.Spec.Ports.TargetPort is defined as `string` there's no validation on this.
The user could write something like ( `targetPort` with `""`)
```shell
{
   "kind":"Service",
   "apiVersion":"v1",
   "metadata":{
      "name":"redis-master",
      "labels":{
         "name":"redis-master"
      }
   },
   "spec":{
      "ports": [
        {
          "port":6379,
          "targetPort": "6379"
        }
      ],
      "selector":{
         "name":"redis-master"
      }
   }
}
```
and the final results could be no endpoints for the service. 

Some kind of validation with some syntax check should be introduced (for example  https://tools.ietf.org/html/rfc6335#section-5.1)

I'm submitting a PR to add some validation.

**Comment by thockin** [comment]
I see this in validation:

```
        if sp.TargetPort != util.NewIntOrStringFromInt(0) && sp.TargetPort != util.NewIntOrStringFromString("") {
                if sp.TargetPort.Kind == util.IntstrInt && !util.IsValidPortNum(sp.TargetPort.IntVal) {
                        allErrs = append(allErrs, errs.NewFieldInvalid("targetPort", sp.TargetPort, portRangeErrorMsg))
                }
        }
```

I guess that validation happens afetr defaulting, so we should never see that case, wo I guess it should be an error.

**Comment by bgrant0607** [comment]
@thockin are you working on this?

cc @krousey

**Comment by thockin** [comment]
I just tagged you as the 2nd LGTM for #9736
