### ISSUE TITLE
Couldn't unpack Salt tree in master startup script

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#9743]
Jun 12 21:46:07 e2e-test-quinton-master startupscript: Running startup script /var/run/google.startup.script
Jun 12 21:46:07 e2e-test-quinton-master startupscript: == kube-up node config starting ==
Jun 12 21:46:08 e2e-test-quinton-master startupscript: Networking functional on e2e-test-quinton-master (10.240.94.15)
Jun 12 21:46:08 e2e-test-quinton-master startupscript: Mounting master-pd
Jun 12 21:46:14 e2e-test-quinton-master startupscript: Downloading binary release tar (https://storage.googleapis.com/kubernetes-staging-8e55f027a8/devel/kubernetes-server-linux-amd64.tar.gz)
Jun 12 21:46:14 e2e-test-quinton-master startupscript:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jun 12 21:46:14 e2e-test-quinton-master startupscript:                                  Dload  Upload   Total   Spent    Left  Speed
Jun 12 21:46:14 e2e-test-quinton-master startupscript: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   127  100   127    0     0   1316      0 --:--:-- --:--:-- --:--:
--  1511
Jun 12 21:46:14 e2e-test-quinton-master startupscript: Downloading Salt tar (https://storage.googleapis.com/kubernetes-staging-8e55f027a8/devel/kubernetes-salt.tar.gz)
Jun 12 21:46:14 e2e-test-quinton-master startupscript:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jun 12 21:46:14 e2e-test-quinton-master startupscript:                                  Dload  Upload   Total   Spent    Left  Speed
Jun 12 21:46:14 e2e-test-quinton-master startupscript: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100 35105  100 35105    0     0   815k      0 --:--:-- --:--:-- --:--:
-- 1038k
Jun 12 21:46:14 e2e-test-quinton-master startupscript: Unpacking Salt tree and checking integrity of binary release tar
Jun 12 21:46:14 e2e-test-quinton-master startupscript: 
Jun 12 21:46:14 e2e-test-quinton-master startupscript: gzip: stdin: not in gzip format
Jun 12 21:46:14 e2e-test-quinton-master startupscript: tar: Child returned status 1
Jun 12 21:46:14 e2e-test-quinton-master startupscript: tar: Error is not recoverable: exiting now
Jun 12 21:46:29 e2e-test-quinton-master startupscript: Couldn't unpack Salt tree. Retrying...

**Comment by quinton-hoole** [comment]
Discovered during testing of https://github.com/GoogleCloudPlatform/kubernetes/pull/9738

Debugging...

**Comment by quinton-hoole** [comment]
Note: without resolving this we cannot run Jenkins e2e tests under different GCE projects.  Running multiple e2e jobs in the same GCE project is causing a variety of quota exhaustion, test flakyness etc, so it's important to resolve this.

**Comment by quinton-hoole** [comment]
The error message is bogus.  The file does not exist at all:

$ wget https://storage.googleapis.com/kubernetes-staging-8e55f027a8/devel/kubernetes-server-linux-amd64.tar.gz
--2015-06-12 22:33:46--  https://storage.googleapis.com/kubernetes-staging-8e55f027a8/devel/kubernetes-server-linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.181.132, 2607:f8b0:4001:c02::84
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.181.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-06-12 22:33:47 ERROR 404: Not Found.

**Comment by quinton-hoole** [comment]
I suspect that this probably because I did the e2e.go --build in a different project than the e2e.go --up.
So the buckets are different.

Rebuilding...

**Comment by quinton-hoole** [comment]
Indeed.
Ginkgo ran 1 suite in 2m7.46661881s
Test Suite Passed
Closing.

**Comment by ihmccreery** [comment]
I'm getting a similar issue in a GCE cluster turned up using vanilla `cluster.kube-up.sh` in a project I've mostly used for GKE clusters.  Investigating.

**Comment by ihmccreery** [comment]
During kube-up.sh I see:

    Creating gs://kubernetes-staging-4c2ab8624f
    Creating gs://kubernetes-staging-4c2ab8624f/...
    +++ Staging server tars to Google Storage: gs://kubernetes-staging-4c2ab8624f/devel
    +++ kubernetes-server-linux-amd64.tar.gz already staged ('rm ./cluster/../cluster/gce/../../cluster/../_output/release-tars/kubernetes-server-linux-amd64.tar.gz.sha1' to force)

Looking in my developers console, I `kubernetes-salt.tar.gz`, but no `kubernetes-server-linux-amd64.tar.gz`.

I think this is a bug where we assume that because `_output/release-tars/kubernetes-server-linux-amd64.tar.gz.sha1` exists, we've already staged to the correct project, which seems like the wrong assumption.  Re-opening.

**Comment by ihmccreery** [comment]
If I'm correct, the component would be `cluster/gce/util.sh:function copy-if-not-staged()`.

**Comment by ihmccreery** [comment]
I'm punting on this for now to get other work done; @quinton-hoole, let me know your thoughts on my comments above, or if you'd like to move this to a separate, more accurately-named bug.

**Comment by quinton-hoole** [comment]
Thanks for your excellent debugging@ihmccreery, yes, please fix in a separate  more accurately-named bug, cross referencing this one.
