### ISSUE TITLE
api documentation is not aimed at kubectl users

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/kubernetes#9753]
We have lots of api documentation in docs/api.md and docs/api-conventions.md.  But it is focused
on direct REST access and on how to extend the API.

We need documentation which is for people who:
  - will interact mostly with kubectl 
    - gloss over REST/HTTP
  - don't plan on extending the API 
    - less prescriptive tone, less design discussion
  - are not thinking about the problem of multiple api versions yet
   - deemphasize the version stuff.

**Comment by erictune** [comment]
I'll take an initial pass at this.

**Comment by bgrant0607** [comment]
Also sort of relevant: #7257, #5331, #3060

**Comment by satnam6502** [comment]
Ah, sorry for prematurely closing this issue.

**Comment by erictune** [comment]
Related to #10966

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by erictune** [comment]
Fixed by #11357
