### ISSUE TITLE
Don't rewrite relative URLs in reverse-proxied HTML

### ISSUE THREAD

**Issue by timstclair** [GoogleCloudPlatform/kubernetes#9756]
Rewriting relative URLs breaks paths which are loaded into the browser at a different path from where they are served, as is the case with angularjs templates. Since relative paths should already be relative to the proxy path prefix, the solution is to simply not rewrite those paths.

This issue is blocking #9674

**Comment by davidopp** [comment]
We can close this now, right?

**Comment by timstclair** [comment]
Yup!
