### ISSUE TITLE
Disable ElasticSearch and enable GCL for GCE.

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#9757]
We've decided to do the following for GCE:

* Metrics:
  * Disable GCM
  * Enable InfluxDB/Grafana
* Events:
  * Leave GCL enabled
* Logs (this issue):
  * Disable Elasticsearch
  * Enable GCL

The 1st bullet point was tracked by #9028

This issue is to handle the 3rd bullet point: to disable ES and enable GCL for GCE.

Assigning to @satnam6502

CC @erickhan, @dchen1107, @vishh, @goltermann

**Comment by satnam6502** [comment]
Closed via  #9758
