### ISSUE TITLE
Problems on quota and limits.

### ISSUE THREAD

**Issue by hurf** [GoogleCloudPlatform/kubernetes#9790]
I was testing quota and limitrange following [example/resourcequota/README][1].

First in step 3, there supposed to be a creation failure, but it succeeded. And the resource caculation seems not working for cpu and memory.

    $ kubectl get pods --namespace=quota-example
    NAME          READY     REASON    RESTARTS   AGE
    nginx-rxtko   1/1       Running   0          21s

    $ kubectl describe namespace quota-example
    Name:	quota-example
    Labels:	<none>
    Status:	Active
    
    Resource Quotas
     Resource		Used	Hard
     ---			---	---
     cpu			0	20
     memory			0	1Gi
     persistentvolumeclaims	0	10
     pods			1	10
     replicationcontrollers	1	20
     resourcequotas		1	1
     secrets		0	10
     services		0	5
    
    No resource limits.

Second, then I created a different quota to the same namespace. It should not working but worked. The result is as follows:

    $ kubectl describe quota q --namespace=quota-example
    Namespace:		quota-example
    Name:			quota1
    Resource		Used	Hard
    --------		----	----
    cpu			0	20
    memory			0	1Gi
    persistentvolumeclaims	0	10
    pods			1	10
    replicationcontrollers	1	20
    resourcequotas		2	1
    secrets			0	10
    services		0	5
    
    Namespace:		quota-example
    Name:			quota2
    Resource		Used	Hard
    --------		----	----
    cpu			0	50
    memory			0	2Gi
    persistentvolumeclaims	0	10
    pods			1	10
    replicationcontrollers	1	20
    resourcequotas		2	1
    secrets			0	10
    services		0	5

But it seems only the first one is taking effect.

    $ kubectl describe namespace quota-example
    Name:	quota-example
    Labels:	<none>
    Status:	Active
    
    Resource Quotas
     Resource		Used	Hard
     ---			---	---
     cpu			0	20
     cpu			0	20
     memory			0	1Gi
     memory			0	1Gi
     persistentvolumeclaims	0	10
     persistentvolumeclaims	0	10
     pods			1	10
     pods			1	10
     replicationcontrollers	1	20
     replicationcontrollers	1	20
     resourcequotas		2	1
     resourcequotas		2	1
     secrets		0	10
     secrets		0	10
     services		0	5
     services		0	5
    
    No resource limits.

Also I created more than one limit of same type:

    Resource Limits
     Type		Resource	Min	Max	Default
     ----		--------	---	---	---
     Container	memory		-	-	1Gi
     Container	cpu		-	-	500m
     Container	cpu		-	-	100m
     Container	memory		-	-	512Mi

I think we should allow one quota and one limit of same type to apply to a namespace.

[1]: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/resourcequota/README.md

**Comment by derekwaynecarr** [comment]
Which provider or cluster did you use?  What admission control plugins are enabled? 

See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admission_controllers.md

Need more info to know how to assist, but I suspect a simple configuration issue.

**Comment by hurf** [comment]
@derekwaynecarr Thanks Derek! My mistake for not enable any admission controller. After the configuration, the resource caculation works now, and only one resourcequota is accepted.

**Comment by hurf** [comment]
@derekwaynecarr  Is there any scenario would request more than one resourcequota in one namespace? Since resourcequota contains resourcequota itself, I guess it allows user to config the quantity by their needs.

**Comment by hurf** [comment]
@derekwaynecarr I read https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/admission_control_limit_range.md , is multi limitranges used for the possible enhancement mentioned in the last section?
Since limitRange contains a list of limitRangeItems, can we have a restriction that one namespace can contain only one limitRange resource? If we want to define different limitranges for different pods, we can add/modify the limitRangeItems.

Another thing is that I found the validation of limiteRange is not strict. I created a limitRange like this:

    Resource Limits
     Type		Resource	Min	Max	Default
     ----		--------	---	---	---
     Container	memory		1Gi	256Mi	512Mi
     Container	cpu		200m	50m	100m
     Pod		cpu		100m	500m	-
     Pod		memory		512Mi	2Gi	-

**Comment by derekwaynecarr** [comment]
I will use this issue to fix the validation enforcement to guarantee a min is less than a max and that a default is in the specified range.  

In OpenShift, we run with the restriction that a namespace has a single limit range and we enforce that via quota.  If you have multiple, basically each limit is enforced prior to admission so the resource being admitted needs to be valid according to all of the documents.

**Comment by derekwaynecarr** [comment]
Right now, we do not yet support a limit range targeting a particular class of pods via a label selector but it's a possible feature enhancement in the future.  If done, it would be post Kube 1.0

**Comment by hurf** [comment]
@derekwaynecarr - you're really quick, I was about to do it.
