### ISSUE TITLE
long time to get response from kube-proxy sometimes

### ISSUE THREAD

**Issue by nkwangleiGIT** [GoogleCloudPlatform/kubernetes#9793]
Hi, 
We're experiencing a strange issue below when try to access the service using kube-proxy, here is the output of curl:
```
wanglei$ curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n"  mysql-ujyll.proxy1.tenxcloud.net:44572 
time_connect: 0.110
time_starttransfer: 0.146
time_total: 0.146

wanglei$ curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n"  mysql-ujyll.proxy1.tenxcloud.net:44572 
time_connect: 0.062
time_starttransfer: 18.771
time_total: 18.771

wanglei$ curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n" mysql-ujyll.proxy1.tenxcloud.net:44572 
time_connect: 0.599
time_starttransfer: 0.721
time_total: 0.727

wanglei$ curl -o /dev/null -s -w "time_connect: %{time_connect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n" mysql-ujyll.proxy1.tenxcloud.net:44572 
time_connect: 0.161
time_starttransfer: 23.716
time_total: 23.716
```
As you can see, it's quite slow to get the response for the 2nd and 4th time, but the time is expected for 1st and 3rd time. Then we did more tries, and found the quick and slow one will appear by turns, not sure what we can do to find out the potential issue here, need your comments, thanks!

**Comment by lavalamp** [comment]
> found the quick and slow one will appear by turns

Is it possible that you have two pods implementing the service, and one of them is quick and one slow?

**Comment by lavalamp** [comment]
e.g., if you do `kubectl get endpoints serivceName`, are there two endpoints, and is one of them faster than the other?

**Comment by thockin** [comment]
We know kube-proxy has a long-tail problem, but it's not THIS bad.

**Comment by thockin** [comment]
If you can repro this with kube-proxy running -v=4, please send the logs.  Leaving this in candidate for now.

**Comment by thockin** [comment]
I'm going to close it for now.  If you can repro, please reopen

**Comment by tarun-asthana** [comment]
@thockin Where can i see the reopened discussion ?
