### ISSUE TITLE
Readiness probe tears down container if initial delay is not passed

### ISSUE THREAD

**Issue by bparees** [GoogleCloudPlatform/kubernetes#9798]
We have a scenario with no liveness probe defined, and a readiness probe defined with an initial delay.  It appears that this logic:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L146

results in tearing down the container immediately because the initial delay has not passed so the probe returns failure.

My understanding is that readiness probe failures are not supposed to result in a container teardown unless the readiness probe has previously succeeded, but I don't see any indication of such logic here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1351-L1365

@smarterclayton @rcernich

**Comment by smarterclayton** [comment]
@mikedanese and @yifan-gu because you've been involved.

**Comment by smarterclayton** [comment]
My expectation was the same as Ben - that in the absence of a successful readiness check, the container shouldn't be torn down - only when readiness transitions from unready -> ready that a subsequent failure could result in teardown.  Or, that readiness does not result in teardown.

**Comment by smarterclayton** [comment]
We just need a decision on what the correct behavior is (why it's a p1) so we can put a patch in place.

**Comment by bparees** [comment]
Also having the readiness probe return failure just because the initial delay has not passed seems like the wrong behavior.

**Comment by smarterclayton** [comment]
Agree, readiness was supposed to be a ratchet, not a switch.

**Comment by mikedanese** [comment]
@bparees There was a bug in readiness probe and the fix was merged on friday in #9680. Are you working off the most recent version of HEAD? Before this, Readiness probe failures would cause a pod to be killed. The failure before the initial delay is actually the documented semantic here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pod-states.md#container-probes.

**Comment by smarterclayton** [comment]
We missed that - hadn't pulled since Friday morning :). Looking.

**Comment by bparees** [comment]
thanks @mikedanese i was a little behind.
