### ISSUE TITLE
Accessing etcd cluster from within a pod/container

### ISSUE THREAD

**Issue by OllyGinger** [GoogleCloudPlatform/kubernetes#9805]
Hi. I'm trying to access our etcd cluster from within a pod/container. There is an etcd node running on each minion, so I should be able to get to it. If I try to access the etcd api using the minion's 'docker0' network interface it's fine, but I'm not aware of any way that this gets exposed to a pod.

Ideally I would just use the etcd cluster that's running as part of kubernetes, but I guess the other option might be just to run a second etcd cluster 'within' k8s.

**Comment by mikedanese** [comment]
In the GCE setup, etcd runs only on the master and we restrict access to only the apiserver. We do this for security and to implement fine grained access control. Depending on your setup, it is possible to bypass this.

**Comment by OllyGinger** [comment]
Ok, thanks. I did some more reading up on the issue, and it seems that I just needed to find out the IP address of the minion from within the container and then contact etcd via that address. 

```
export DOCKER_HOST_IP=$(ip route | grep 'default' | awk '{print $3}')
```

The above code is what I was looking for :+1:
