### ISSUE TITLE
There should be a resize timer

### ISSUE THREAD

**Issue by pmorie** [GoogleCloudPlatform/kubernetes#9815]
It's a pretty common test to want to know how fast a cluster can resize a replication controller for some specific pod template.  It would be great if there was a kubectl command that could:

1.  Resize some replication controller R to some new size N
2.  Watch R and time how long it takes the _running_ replica count to go to N

@detiber @smarterclayton @derekwaynecarr

**Comment by pmorie** [comment]
@erictune @bgrant0607

**Comment by bgrant0607** [comment]
Please add your use case to #1899 and close this one.

**Comment by pmorie** [comment]
Updated; closing.
