### ISSUE TITLE
Require Service.ContainerPort

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#983]
The fallback for now is to use Container[0].Port[0] which is, IMO, confusing.

**Comment by pmorie** [comment]
+1 to the idea of working with ports only as a set.

One thing I'll add, making it explicit and requiring `ContainerPort` to be set makes it much easier to write a UI that presents how service align with ports in pods.

`ContainerPort` isn't the greatest name.  I like `TargetPodPort` the best but it is a bit verbose.

**Comment by brendandburns** [comment]
Assigning to @thockin since he says his refactor will cover the rename.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/59

**Comment by brendandburns** [comment]
I'm going to close this issue as:
   * Port has been renamed to ContainerPort
   * We now have improved default behavior, and attempts to implement a (more) complete solution were rejected by @thockin 

Re-open if you have any concerns.
