### ISSUE TITLE
Mesos getting started guide fails due to missing parameter for apiserver

### ISSUE THREAD

**Issue by michaeltchapman** [GoogleCloudPlatform/kubernetes#9852]
in `docs/getting-started-guides/mesos.md` the command:

    ./bin/km apiserver \
      --address=${servicehost} \
      --mesos_master=${mesos_master} \
      --etcd_servers=http://${servicehost}:4001 \
      --service-cluster-ip-range=10.10.10.0/24 \
      --port=8888 \
      --cloud_provider=mesos \
      --v=1 >apiserver.log 2>&1 &

fails because apiserver needs the parameter --portal_net.

**Comment by jdef** [comment]
it looks like this was filed against a buggy version of the getting started guide. it has since been corrected so I'm closing this out.
