### ISSUE TITLE
Kubernetes does not support https health or readiness checks 

### ISSUE THREAD

**Issue by stevekuznetsov** [GoogleCloudPlatform/kubernetes#9866]
The probes fail, attempting to parse the TLS handshake response as an HTTP response:

Sample output from `kubectl describe pod`
`Readiness probe failed: Get http://<IP>:8443/healthz/ready: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

`Liveness probe failed: Get http://<IP>:8443/healthz: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

@smarterclayton @derekwaynecarr

**Comment by smarterclayton** [comment]
My opinion is that both readiness and liveness should support https endpoints and skip certificate verification.  Certificates are not relevant (and not even likely to be signed for the pod ip).  Lots of existing infrastructure would have trouble exposing separate http and https ports.

**Comment by thockin** [comment]
No objections from me

**Comment by smarterclayton** [comment]
I believe all that needs to be done is for `pkg/probe/http/http.go` to pass a TLSConfig that has InsecureSkipVerify set to true.  @stevekuznetsov can you look into that.

**Comment by thockin** [comment]
PR has been approved

**Comment by mrshah-at-ibm** [comment]
For CA, we can use the `httpGet` liveliness probe. For Orderer/Peer, we will still have to use the TCP liveliness probe until Fabric 1.4 is delivered.
