### ISSUE TITLE
Unable to set node unschedulable

### ISSUE THREAD

**Issue by eparis** [GoogleCloudPlatform/kubernetes#9873]
Before #8449 I was able to do

So how do I add nodespec.unschedulable = true? Before I did:
```
kubectl update nodes 10.12.6.11 --patch='{"apiVersion": "v1beta3", "spec": {"unschedulable": true}}'
```

But since patch was removed I decided to try:

```
# echo '{
    "apiVersion": "v1",
    "kind": "Node",
    "metadata": {
        "name": "10.12.6.8",
        "uid": "bddf34f1-13a0-11e5-b8c6-5254000ef5e9"
    },
    "spec": {
        "externalID": "10.12.6.8",
        "unschedulable": true
    }
}' | kubectl update -f -
```

But ended up getting
```
Error from server: minion "10.12.6.8" cannot be updated: the resource was updated to 44058
```

What's a man to do?

**Comment by mikedanese** [comment]
No resource version?
```
kubectl get node kubernetes-minion-peos -o json | jq '.spec.unschedulable=true'  | kubectl update -f -
```
works for me. Do we want to re-enable patch for v1 using strategic merge patch?

**Comment by bgrant0607** [comment]
We should at least make update retry to avoid false conflicts with status updates. Otherwise, update is not so usable.

See also #8625.

**Comment by davidopp** [comment]
And #9878 and #8868 and ...

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by bgrant0607** [comment]
We should also clarify the error message.

**Comment by bgrant0607** [comment]
@davidopp Those 2 issues are not directly related to this one.

**Comment by bgrant0607** [comment]
@mikedanese If we were going to re-enable patch, I'd like it to use strategic merge patch, yes. I don't think that needs to be in 1.0, however, if full-object updates work. I'd also eventually like a patch command that invokes the PATCH functionality in apiserver.

**Comment by davidopp** [comment]
@bgrant0607  Ah you're right, I thought those were also version number conflicts but they're not.

**Comment by nikhiljindal** [comment]
Patch now works after https://github.com/GoogleCloudPlatform/kubernetes/pull/9993

I am updating ```kubectl update``` to allow updating a resource without resourceVersion in https://github.com/GoogleCloudPlatform/kubernetes/pull/10074.
If there is no resourceVersion specified in the user given json, then we add to it the resourceVersion from the latest etcd object.

**Comment by bgrant0607** [comment]
Both issues were fixed.
