### ISSUE TITLE
0.17 to 0.18 ECDSA keys regression

### ISSUE THREAD

**Issue by farcaller** [GoogleCloudPlatform/kubernetes#9889]
After successfully setting up TLS-secured kubernetes at 0.17 I failed to upgrade to 0.18, specifically apiserver failing to start with:

```
Invalid Authentication Config: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 set:false omitEmpty:false} tbsCertificate @2
```

**Comment by liggitt** [comment]
This is likely the serviceaccount token authenticator defaulting to the server key. The default token generator and authenticator implementation only supports an rsa signing key.

**Comment by liggitt** [comment]
I'll take a look at this tonight

**Comment by liggitt** [comment]
A workaround until this is fixed is to generate an RSA key and explicitly set it for the serviceaccount authenticator and token controller (see local-up-cluster.sh for an example)
