### ISSUE TITLE
Can we stop supporting TRACE method in proxy requests

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/kubernetes#9893]
Forked from https://github.com/GoogleCloudPlatform/kubernetes/issues/3996#issuecomment-107784888

Swagger does not support TRACE (https://github.com/swagger-api/swagger-codegen/issues/877#issuecomment-112391320) method which is causing issues while using swagger-codegen.

Do we use TRACE anywhere? Is it fine to remove it?

@bgrant0607 @smarterclayton

**Comment by smarterclayton** [comment]
I'm not aware of any uses of it.

**Comment by saad-ali** [comment]
Needs v1 triage (PR pending)

**Comment by nikhiljindal** [comment]
xref https://github.com/GoogleCloudPlatform/kubernetes/issues/9964 as TRACE is also failing swagger validation

```
$ swagger-tools validate api/swagger-spec/resourceListing.json api/swagger-spec/api.json api/swagger-spec/v1beta3.json api/swagger-spec/v1.json api/swagger-spec/version.json 

  API Declaration (/api/v1beta3) Errors:

    #/apis/99/operations/5/method: No enum match for: TRACE

  API Declaration (/api/v1) Errors:

    #/apis/99/operations/5/method: No enum match for: TRACE
```

**Comment by bgrant0607** [comment]
TRACE was there for completeness.

We use the proxy with elasticsearch. Perhaps @satnam6502 knows whether Elasticsearch needs TRACE.

**Comment by satnam6502** [comment]
No, I don't think it needs TRACE. I think I or someone else added TRACE (for completeness) long after Elasticsearch for logging was working.

**Comment by smarterclayton** [comment]
Technically even swagger 1.2 did not acknowledge TRACE as a valid option.

----- Original Message -----
