### ISSUE TITLE
Kubelet shouldn't consider itself healthy if SyncPods is stuck

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#9895]
@ArtfulCoder and I observed a situation where kubelet's syncLoop was not running, but kubelet still said it was healthy. Action item here is for syncLoop to log a time every time it runs, and /healthz to not return OK if that time is too far in the past.

@dchen1107 @bprashanth

**Comment by bprashanth** [comment]
That's what I suspected with  https://github.com/GoogleCloudPlatform/kubernetes/issues/9833#issuecomment-112498179

The syncLoop should run every 10s: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1671

It would not run if there was a hang in SyncPods, which prevents control from reaching the syncLoop again. Any chance you have repro steps? I'd expect slow docker to slow it down (image gc, container killing etc).

It sounds like you want the kubelet to report the node as NotReady if the syncLoop hangs right? (not /healthz)

**Comment by dchen1107** [comment]
@bprashanth yes, that is what I suspected too. I am going to close that one to favor this one. Thanks!

**Comment by bprashanth** [comment]
Can we change this bug title then (or fork another)? Since I think reporting the node as unhealthy will just gloss over a potential deadlock

**Comment by dchen1107** [comment]
Once the kubelet claim itself unhealthy, monit should pick it up and restart kubelet. From the initial issue  #9833 reported by @saad-ali, he mentioned that restarting either kubelet or docker should fix the issue. In this case, restarting kubelet should workaround the issue, with less cost than restarting docker.

**Comment by bprashanth** [comment]
Ah. for my own education, how does restarting the kubelet help? (I can see how restarting docker does)

**Comment by bprashanth** [comment]
haha, i think i know why it helps, becuase we kill the pod workers on kubelet restart. 

If I'm right this will happen when you have pods with a lot of containers and you attempt to kill some of them after they've started the pod infra container but before they've started all the other containers (the workers will go on trying to create containers with a non-existing network namespace container while SyncPods is also hammering docker with delete requests).
