### ISSUE TITLE
Volume Documentation Needs to be Updated

### ISSUE THREAD

**Issue by saad-ali** [GoogleCloudPlatform/kubernetes#9915]
[Volume documentation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md) only talks about these volumes:
* EmptyDir
* HostPath
* GCEPersistentDisk
* NFS

However, we [now support](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L211) many more volume types. Documentation should be updated to reflect this.

**Comment by bgrant0607** [comment]
cc @thockin @markturansky

**Comment by HaiyangDING** [comment]
Is anyone working on this? If not, I would like to do it.

**Comment by markturansky** [comment]
@HaiyangDING go for it :)  Improving PV docs is on my TODO list, too.

**Comment by HaiyangDING** [comment]
@markturansky 
Sure, thank you. I will start now, hope to send a PR ASAP.
