### ISSUE TITLE
Error: the server could not find the requested resource (post replicationcontrollers)

### ISSUE THREAD

**Issue by maulik887** [GoogleCloudPlatform/kubernetes#9945]
Hi, Trying my hands on kubernetes first time. I have one controller defined like this,
```javascript
{
   "apiVersion": "v1beta3",
   "kind": "ReplicationController",
   "metadata":{
      "name":"myapp",
      "labels":{
         "name":"myapp"
      },
      "namespace": "default"
   },
   "spec":{
      "replicas":1,
      "selector":{
         "name":"myapp"
      },
      "template":{
         "metadata":{
            "labels":{
               "name":"myapp"
            }
         },
         "spec":{
            "volumes": null,
            "containers":[
               {
                  "name":"myapp",
                  "image":"repo/myapp",
                  "ports":[
                     {
                        "containerPort":80,
                        "protocol": "TCP"
                     }
                  ],
                  "imagePullPolicy": "IfNotPresent"
               }
            ]
         }
      }
   }
}
```

And I'm trying to create rc something like this- **kubectl create -f myapp-controller.json** That gives me error- "Error: the server could not find the requested resource (post replicationcontrollers)"
My kubectl version is-
Client Version: version.Info{Major:"0", Minor:"15.0", GitVersion:"v0.15.0", GitCommit:"", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"0", Minor:"14+", GitVersion:"v0.14.1-dirty", GitCommit:"77775a61b8e908acf6a0b08671ec1c53a3bc7fd2", GitTreeState:"dirty"}

Running kubernetes cluster on virtual machine running ubuntu. Any idea where things are broken ?

**Comment by nikhiljindal** [comment]
I ran kubectl create -f myapp-controller.json using your json on my cluster and it worked fine.

Can you verify that your cluster is running fine by running ```kubectl cluster-info``` or ```kubectl get pods```
I will also recommend syncing to the latest version and trying again. The current version on HEAD is 19 and you are using 14 and 15.

**Comment by maulik887** [comment]
To be specific I'm running kubernetes cluster how it mentioned [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md). When I check cluster info it says- **Kubernetes master is running at http://localhost:8080**. 

And there is one pod running three containers-
POD     IP     CONTAINER(S)      IMAGE(S)      HOST      LABELS    STATUS    CREATED
nginx-127  controller-manager   gcr.io/google-containers/hyperkube:v0.14.1  127.0.0.1/127.0.0.1 <none>   Running  5 hours
                      apiserver            gcr.io/google-containers/hyperkube:v0.14.1                                             
                      scheduler            gcr.io/google-containers/hyperkube:v0.14.1                                             
I will try with latest version but do you see anything fishy happening here ?

**Comment by nikhiljindal** [comment]
No nothing fishy here.

**Comment by maulik887** [comment]
I'm still getting same error with latest version of [kubectl](https://storage.googleapis.com/kubernetes-release/release/v0.19.0/bin/linux/amd64/kubectl)

Client Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.0", GitCommit:"6b0d4ffed36adb0e2585333f01a553ab3e0970fd", GitTreeState:"clean"}

**Comment by nikhiljindal** [comment]
Sorry for not being clear before. Update your kubernetes cluster code as well and not just kubectl.

**Comment by maulik887** [comment]
I was about to say that :) Updated kubernetes cluster version and things started to work fine.
Thanks for the help.
