### ISSUE TITLE
Microservice in k8s

### ISSUE THREAD

**Issue by huangqg** [GoogleCloudPlatform/kubernetes#9947]
Hi,
k8s is designed for Microservice architect. as we deployed a k8s cluster with more about 2000 pods. and we are consider the Microservice on the cluster. here is my concerns:
1. a pod can contain multiple containers, how does the containers connect with each other? I try to connect the container by localhost, but it failed, for example:
  ```
the pod contains wordpress and mysql image, I set the WORDPRESS_DB_HOST=localhost:3306,    
but it can't connect to the mysql via localhost:3306,  how do I get the mysql host for wordpress in the pod?
```

2. how does k8s/pod handle the dependence between multiple containers in one pod, for example, the deploy/start sequence.

3. what the best practise of the Microservice implementation for k8s? or any advise for Microservice in k8s.

Thanks very much!

**Comment by thockin** [comment]
Containers in a pod should absolutely see each other on localhost.  If that is not working, there's something VERY strange going on.

We do not sequence startup within a pod (well, we start them in the order they are listed but we do it concurrently, I think).  It's your job to make sure your containers in a pod behave "correctly" in the face of failure.

As for advice: Reduce coupling whenever possible.

**Comment by huangqg** [comment]
thanks for your comments.
