### ISSUE TITLE
Container-optimized Google Compute Engine image article and manifest issue

### ISSUE THREAD

**Issue by rreinurm** [GoogleCloudPlatform/kubernetes#9951]
Tried to deploy new GCE instance using latest container-vm image (container-vm-v20150611) and found few issues then setting up manifest file. According to article https://cloud.google.com/compute/docs/containers/container_vms the container volumes should be mounted in manifest like:
```
volumes:
    - name: string
      source:
        hostDir:
          path: string
```
If I checked api spec from http://kubernetes.io/third_party/swagger-ui/#!/v1beta3/ or http://kubernetes.io/third_party/swagger-ui/#!/v1 then I found that working manifest is
```
  volumes:
    - name: string
      hostPath:
        path: string
```

Additionally I find confusing in the document that api version should be set v1beta3 or v1. If I set version to v1beta3 then kubelet reported APIVersion:"v1". Not sure if its same.
```
I0617 16:29:32.330839    6713 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"96b62f4f468865a2b0a69a6d8351f148-aerospike-wallet", UID:"96b62f4f468865a2b0a69a6d8351f148", APIVersion:"v1", ResourceVersion:"", FieldPath:"implicitly required container POD"}): reason: 'pulled' Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
```

It was interesting to discover that I can mount directly to GCE persistent disk. It would be nice to mention that possibility as so far I have manually mounted extra disks for that purpose.

And the last. Changelog does not reflect that container-vm image was updated in June where docker has been updated to 1.6.2.

**Comment by bgrant0607** [comment]
Sorry about that. You are correct. hostDir has been converted to hostPath in v1beta3/v1, as mentioned here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md#v1beta3-conversion-tips-from-v1beta12

**Comment by bgrant0607** [comment]
The docs have been updated to v1
