### ISSUE TITLE
rbd volume target mount point is created after it's checked for existence

### ISSUE THREAD

**Issue by farcaller** [GoogleCloudPlatform/kubernetes#9952]
I find [this code](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/volume/rbd/rbd_util.go#L103) questionable, as the check always fails when directory doesn't exist, and it's being created [a few lines later on](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/volume/rbd/rbd_util.go#L111).

**Comment by rootfs** [comment]
nice reading. The basic idea is to ensure the directory is not already mounted before rbd starts to use this directory to mount the device. 

you'll find kubelet checks the volume mount periodically. If kubelet finds the volume is already mounted, it won't mount it again. This is why kubelet probes the existence of mount point.

**Comment by farcaller** [comment]
But then who's going to bootstrap the directory if `os.MkdirAll` is never reached? I managed to get out of this loop only by issuing `mkdir` myself, after which the pod started up.

**Comment by rootfs** [comment]
if `MkdirAll` is not reached, something wrong happened. Do you have a kubelet log I can peek?

**Comment by rootfs** [comment]
btw, are you still using containerized kubelet?

**Comment by farcaller** [comment]
```
Jun 17 18:00:35 da kubelet[19850]: E0617 18:00:35.275216   19850 disk_manager.go:55] failed to attach disk
Jun 17 18:00:35 da kubelet[19850]: E0617 18:00:35.275286   19850 rbd.go:175] rbd: failed to setup
Jun 17 18:00:35 da kubelet[19850]: E0617 18:00:35.275402   19850 kubelet.go:1125] Unable to mount volumes for pod "docker-registry-5ao4s_default": rbd: /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/kube-common-image-docker-registry-images failed to check mountpoint; skipping pod
Jun 17 18:00:35 da kubelet[19850]: I0617 18:00:35.275490   19850 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-5ao4s", UID:"be123450-151a-11e5-8031-e6a1db081618", APIVersion:"v1beta3", ResourceVersion:"32538", FieldPath:""}): reason: 'failedMount' Unable to mount volumes for pod "docker-registry-5ao4s_default": rbd: /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/kube-common-image-docker-registry-images failed to check mountpoint
Jun 17 18:00:35 da kubelet[19850]: E0617 18:00:35.301625   19850 pod_workers.go:108] Error syncing pod be123450-151a-11e5-8031-e6a1db081618, skipping: rbd: /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/kube-common-image-docker-registry-images failed to check mountpoint
Jun 17 18:00:35 da kubelet[19850]: I0617 18:00:35.301782   19850 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-5ao4s", UID:"be123450-151a-11e5-8031-e6a1db081618", APIVersion:"v1beta3", ResourceVersion:"32538", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: rbd: /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/kube-common-image-docker-registry-images failed to check mountpoint
```

Kubelet isn't containerized (is that even possible to use one with rbd mounts?)

**Comment by rootfs** [comment]
looks i made a regression [here](https://github.com/GoogleCloudPlatform/kubernetes/pull/6578#discussion_r30807150)

**Comment by rootfs** [comment]
@farcaller  opened #9957 to fix it, thank you for spotting this problem!
