### ISSUE TITLE
Document the v1 system requirements

### ISSUE THREAD

**Issue by RichieEscarez** [GoogleCloudPlatform/kubernetes#9984]
This is normally boilerplate info. Do we have hardware and software requirements that need to be specified?

For example:

System Requirements (minimums, types, versions, sizes, etc.):

Hardware:
 - Supported IaaSs
 - Supported OSs
 - Supported Networking
 - Supported Configuration Management
 - Supported Web Browsers
 - Minimum Memory Requirements
 - Minimum CPU (Mhz)
 - Minimum Hard Drive Space (running and install, etc)
 - Supported VMs
 - ..... ?

Software:
 - Libraries?
 - Go?
 - cURL?
 - Docker?
 - ......?

**Comment by erictune** [comment]
Users can't expect arbitrary combinations of (IaaSs, OS, Networking, Config Management) to work.
They have to use specific combinations that have been made to work together, listed
[here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md), or build a system from [scratch](
https://github.com/GoogleCloudPlatform/kubernetes/pull/10271)

I'm not aware if any compatibility testing has been done for Web Browsers. 

The ram/cpu/disk space requirements on the desktop/laptop are trivial. 

In terms of requirements for nodes, I would recommend minimum 1 core and 1GB ram for the master.  Nodes can have less ram.  I documented this in #10271.

Supported VMs: this is basically the same as IaaS.

On the desktop/laptop, you don't need to install anything other than kubectl, plus either curl or wget for a few of the examples.

On the cluster, you do need to install several things.  I've described those in #10271.  The various other getting-started-guides also cover what you need to install.  The way you install it different depending on what getting started guide you use.

**Comment by alex-mohr** [comment]
I think https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md meets to v1 bar?

**Comment by RichieEscarez** [comment]
I agree the getting started grid covers the specific combinations that work but there are several details about Nodes mentioned in #10271 that aren't mentioned elsewhere: https://github.com/erictune/kubernetes/blob/how-to-write-a-gsg/docs/getting-started-guides/scratch.md#nodes

Do you think it would benefit users (those who use the pre-canned getting started guides) if a copy of that "Nodes" section in #10271 was added to: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md?

Plus when the "Getting Started from Scratch" doc is ready, we should call it out specifically from the README, something like:
"Want to create custom clusters? For a more hands-on experience and in-depth view of Kubernetes, trying Getting Started from scratch."

**Comment by erictune** [comment]
Most of the getting-started-guides other than scratch ensure that your nodes meet the requirements in one way or another.  

I added language similar to what you suggested to  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md

**Comment by erictune** [comment]
I think with the new Scratch Getting-started-guide #10271 that this is mostly addressed.  Closing, and we can open new issues if user feedback indicates specific
